### ISSUE TITLE
Date widgets in API 16/17 show time in their answer

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1002]
If you have a datetime widget with a no-calendar appearance and select the date, the answer that is shown below the Select date box includes time. It should just be the date (e.g., only the month, only the month-year).

<img width="684" alt="screen shot 2017-05-02 at 14 48 40" src="https://cloud.githubusercontent.com/assets/32369/25636252/795c24ac-2f46-11e7-9570-5601d0cd5fb0.png">

This behavior also happens if you use the Jump to or Edit menu, the times also appear.
<img width="666" alt="screen shot 2017-05-02 at 14 49 06" src="https://cloud.githubusercontent.com/assets/32369/25636286/8dcd14fa-2f46-11e7-9ba1-09d7437fed99.png">

**Comment by lognaturel** [comment]
[Here](https://github.com/opendatakit/collect/blob/ee3ad1153b928be3966b4956f1b8a46b68892642/collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java#L81) is the explanation for that -- [`getBestDateTimePattern`](https://developer.android.com/reference/android/text/format/DateFormat.html#getBestDateTimePattern(java.util.Locale,%2C+java.lang.String)) was introduced in API 18. The current fallback is to show the full date according to the locale. An alternative would be to just use [`getDateTimePattern`](https://github.com/opendatakit/collect/blob/ee3ad1153b928be3966b4956f1b8a46b68892642/collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java#L90) but the down side is that the components might not be in the right order for the locale.

**Comment by lognaturel** [comment]
Not much we can do on the Collect side.
