### ISSUE TITLE
IndexOutOfBoundsException in ListView

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1003]
Seen with API 19, 21, 22. Stack trace from Firebase Crash:
```
Exception java.lang.IndexOutOfBoundsException: Invalid index 11, size is 0
java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:255)
java.util.ArrayList.get (ArrayList.java:308)
android.widget.SimpleAdapter.bindView (SimpleAdapter.java:147)
android.widget.SimpleAdapter.createViewFromResource (SimpleAdapter.java:126)
android.widget.SimpleAdapter.getView (SimpleAdapter.java:114)
android.widget.AbsListView.obtainView (AbsListView.java:2347)
android.widget.ListView.makeAndAddView (ListView.java:1864)
android.widget.ListView.fillDown (ListView.java:698)
android.widget.ListView.fillGap (ListView.java:662)
android.widget.AbsListView.trackMotionScroll (AbsListView.java:4991)
android.widget.AbsListView.scrollIfNeeded (AbsListView.java:3418)
android.widget.AbsListView.onTouchMove (AbsListView.java:3801)
android.widget.AbsListView.onTouchEvent (AbsListView.java:3632)
android.view.View.dispatchTouchEvent (View.java:8476)
```

**Comment by grzesiek2010** [comment]
It's really hard to find out what's wrong... I'm not even sure which list it is, I guess it's [FormDownloadList](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java). Does the first line look always like above? I mean is it always `index 11, size is 0` ?

**Comment by lognaturel** [comment]
@grzesiek2010 Now that you have Firebase Crash access, you can take a moment to look through the different crashes and see if you get any ideas. If I recall correctly, the index value isn't always the same.

**Comment by grzesiek2010** [comment]
@lognaturel I guess it isn't always the same. Ok I can look at this issue again.

**Comment by grzesiek2010** [comment]
@lognaturel I was trying to reproduce the issue but still without success. I will be tracking logs.

**Comment by lognaturel** [comment]
Any new ideas, @grzesiek2010? I'm afraid I don't have any. It seems to continue happening almost every day. https://console.firebase.google.com/u/2/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/cbb271ed?duration=2592000000 (needs auth) 

It seems so strange to me that no one would be reporting it. Maybe it's not actually a hard crash?

**Comment by grzesiek2010** [comment]
@lognaturel 
Nothing new. I have no idea what's wrong.

> Maybe it's not actually a hard crash?

I guess it must be.

**Comment by mmarciniak90** [comment]
@lognaturel I tried to reproduce this crash without success.
I worked with Android 5.1 and with the newest device Nexus 5X.
I tried reproduce this on Collect v1.11 and v1.5.1.
I verified cases with ODK Aggregate and Google Sheets.

**Comment by lognaturel** [comment]
Well, I think we can close for now, then. Unless someone can give us more info it's going to be really hard to track down.

**Comment by bhanuprakashsharma** [comment]
I also stuck in same case : I fetch contact and simultaneously show in bunch of 50. 
When i press back button then  same error came. This happens when I scroll fast and press back button.
