### ISSUE TITLE
When default Aggregate success message is sent, show in current language

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1010]
#### Software and hardware versions 
Collect v1.6.1

#### Problem description
#336 enabled custom server responses. This is great when an organization configures custom messages but not so great for organizations who use standard Aggregate because they end up with the English message "full submission upload was successful!" no matter the language Collect is set to.
<img width="229" alt="screen shot 2017-05-04 at 10 00 04 am" src="https://cloud.githubusercontent.com/assets/967540/25709977/79f2dcba-30b0-11e7-8080-33a3247d03d0.png">

#### Steps to reproduce the problem
1. Change the phone language to anything but English
1. Successfully send a form

#### Expected behavior
The success message should match the Collect language when it is the standard Aggregate message.

#### Other information 
I propose adding a constant for the standard Aggregate text and adding something like
```
if (customResponse is STANDARD_AGGREGATE_SUCCESS_TEXT and language is not English)
    show localized success string (R.string.success)
else
   show customResponse
```
How does that sound?

**Comment by lognaturel** [comment]
@jnordling it would be very helpful to hear your thoughts on this!

**Comment by jnordling** [comment]
I think the proposed check for the language is a good idea, especially since aggregate has no idea what language ODK is operating at can very user to user. This could also be solved by having the custom messaging be a configuration in the settings. We did that initially but then had to remove it. Over all I think the English check is fine...

**Comment by lognaturel** [comment]
Awesome, thanks! @nikialexopoulou, it's yours. 😊

**Comment by lognaturel** [comment]
Hi @nikialexopoulou, how is this going? We have a code freeze on Wednesday and it would be great to get this in before! If you're stuck, can you please create an "in progress" pull request so someone can help you? Or if you won't have time, perhaps we can pass it on to someone else. Thanks!

**Comment by nikialexopoulou** [comment]
Hello @lognaturel ! The part I haven't done yet is the "customResponse is STANDARD_AGGREGATE_SUCCESS_TEXT" condition within the if statement. I'm not sure how I should check it and why this is necessary to be done.

**Comment by lognaturel** [comment]
@nikialexopoulou The idea with the custom message feature is that a server can define a special message that people will see when they submit a form. Aggregate has a default message ("full submission upload was successful!". You'll want to create a constant for that message and then detect when the server provides that message. If the server has provided that message, it's not really a "special message", it's the Aggregate default. So that's the case in which, if the language is not English, we want to fall back to "Success" in the user's language. That will be more useful than "full submission upload was successful!" which the user might not understand.

**Comment by nikialexopoulou** [comment]
@lognaturel Yes, but i don't understand why to use this. I mean, why to have a different message according the language? Why should the custom message be displayed when the language is English, instead of the "Success" message?

**Comment by nikialexopoulou** [comment]
@lognaturel Also, let's suppose I create a constant for the message "full submission upload was successful!". I don't know how to detect server's message. How do I know what's​ the server's answer? I'm trying to find this, but I can't.

**Comment by lognaturel** [comment]
`messageParser.getMessageResponse()` gives you the server message.

**Comment by lognaturel** [comment]
Thanks for looking into this, @nikialexopoulou! If you'd like to share what you have so far as a pull request, that would be great. @grzesiek2010 will finish it up so we can get it in the next release.
