### ISSUE TITLE
Use embedded zxing lib in BarcodeWidget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1021]
#843 introduced the zxing library for reading barcodes because it's a lot more convenient for users who want to use the QR code import feature. Now that we have the dependency, the BarcodeWidget should use it instead of requiring users to install the ZXing app.

**Comment by MukundAnanthu** [comment]
@lognaturel Could I please take this one up before 507/508??

**Comment by lognaturel** [comment]
Sounds good to me, @MukundAnanthu!
