### ISSUE TITLE
choice filters not working in some devices

### ISSUE THREAD

**Issue by Hanseph** [getodk/collect#1022]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
@Hanseph Please fill out the issue template so we can help you! As the prompts say, you'll need to provide software and hardware versions, a detailed description of the problem, steps to reproduce it and the behavior you expected. We recommend that you attach a sample form.

**Comment by lognaturel** [comment]
@Hanseph When you have a chance to provide more information, please re-open this issue.

**Comment by delcroip** [comment]
Hi I have the same issue on a galaxy tab 3 T210, it is working fine online https://odk.enke.to/preview?form=https://xlsform.opendatakit.org/downloads/6tc0z5h8/Q_camp_Assesement_draft.xml
I have a 
- select one province, with a default value and no choice_filter
- select on district  with a default value and this choice_filter choice_filter = ${province}

br

**Comment by grzesiek2010** [comment]
@delcroip 
Could you attach your xls form?

**Comment by delcroip** [comment]
[Q_camp_Assesement_draft.xlsx](https://github.com/opendatakit/collect/files/3008610/Q_camp_Assesement_draft.xlsx) but I fear that is the same issue as https://github.com/opendatakit/collect/issues/378
 br

**Comment by grzesiek2010** [comment]
Yes, choice_filter which uses values from the same group (with `field-list` appearance) can't work and it's the same issue as #378 as you noticed. Just get rid of `field-list` appearance.

**Comment by delcroip** [comment]
thank you, hopefully it will be supported at some point, br
