### ISSUE TITLE
Small icon

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1030]
#### Problem description
The icon is small in comparison with icons of other apps
![screenshot_2017-05-17-12-20-34](https://cloud.githubusercontent.com/assets/3276264/26149983/cf697c70-3afc-11e7-909e-65e12722c8ff.png)

I think it doesn't look good.

Do we want a new (refreshed) icon too as we are going to implement #464 ? or we only should to fix existed one?

@lognaturel @yanokwa

**Comment by lognaturel** [comment]
Interesting! What are your device/Android specs? On all the devices/Android versions I've used, it looks like:
<img src = "https://cloud.githubusercontent.com/assets/967540/26175863/bcb5e1d2-3b19-11e7-96e2-1fdf3086e8e7.png" width="400">

**Comment by grzesiek2010** [comment]
@lognaturel that printscreen is from Samsung Duos Android 4.2.2 but when I use this device today it's ok:

![screenshot_2017-05-18-13-57-31](https://cloud.githubusercontent.com/assets/3276264/26201199/1faeaf36-3bd2-11e7-8138-205880d1a2eb.png)

something strange... ok I'll close the issue now.

**Comment by lognaturel** [comment]
Your phone is haunted, @grzesiek2010 👻👻👻
