### ISSUE TITLE
Field-list appears when deleting repeat with no field-list

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1032]
#### Software and hardware versions 
Collect v1.6.0

#### Steps to reproduce the problem
Download this form: [delete-transform.xlsx](https://github.com/opendatakit/collect/files/1009495/delete-transform.xlsx)

There are three fixed repeats in this form. Enter unique data for text a, repeat 1 (text b and c) and repeat 2 (text b and c). Go back to repeat 1's text b. Long press on the label and remove the group. 

You will be shown a field-list. This unexpected because there are no field-lists in the form. This behavior does not happen in ODK Collect 1.4.10 and my guess is it was introduced in https://github.com/opendatakit/collect/pull/274.

Probably related to https://github.com/opendatakit/collect/issues/1033.

**Comment by lognaturel** [comment]
This is not quite related to this issue but it seems perhaps it shouldn't be possible to delete a repeat when a `jr:count` was specified. Currently the UI makes it look like a repeat was deleted but in fact it wasn't. After the form is closed and reopened, there's an empty group at the end. We should look into improving that for #809.

**Comment by grzesiek2010** [comment]
@lognaturel 

> This is not quite related to this issue but it seems perhaps it shouldn't be possible to delete a repeat when a jr:count was specified

you can remove group but then a new one is added automatically at the end so you still have the same number of groups, I think it's ok.
