### ISSUE TITLE
Arranging the form names in ascending/descending order provides bad user experience. 

### ISSUE THREAD

**Issue by srshah193** [getodk/collect#1039]
#### Software and hardware versions 
Collectv1.6.1

#### Problem description
Arranging the forms in ascending or descending order on the basis of their names opens a NavDrawer from right side.

#### Steps to reproduce the problem
Instead of using a NavDrawer <A-Z> and <Z-A> button can be used.

#### Expected behavior
It works properly but has a bad user experience.

**Comment by yanokwa** [comment]
Hi @srshah193! Thanks for filing this issue. 

I'm not sure what you mean by a button can be used. Can you please mock up (e.g., maybe a paper sketch that you attach to this issue) the user interface you had in mind? Alternatively, point to an Android app that does what you describe so we can see it.

Additionally, a number of Android applications (e.g., Gmail) use NavDrawer. Can you point to some evidence (e.g., Android UI best practices) that say NavDrawer use result in a bad experience?

**Comment by srshah193** [comment]
In the current version ,a icon is shown for sorting them alphabetically which opens a NavDrawer instead 
![1234](https://cloud.githubusercontent.com/assets/21021240/26284657/4f7dd9ce-3e5e-11e7-9890-ad6031a6d0d8.PNG)
![new](https://cloud.githubusercontent.com/assets/21021240/26284656/4f69b98a-3e5e-11e7-8e43-f2c78f10a828.PNG)
Android pop up menu can be used if features like sort by date are to added.
Or two icons can be used interchangeably as in the image.

**Comment by lognaturel** [comment]
@srshah193 As you've probably seen going through some of the open issues and pull requests, we are in the process of doing a full user experience update led by @shobhitagarwal1612 through [Google Summer of Code](https://summerofcode.withgoogle.com/). The current proposal for modernizing the sorting interface is to use a [bottom modal sheet](https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets) which matches the Google Docs apps, for example:
<img width="582" alt="screen shot 2017-05-21 at 8 27 11 pm" src="https://cloud.githubusercontent.com/assets/967540/26289372/244fe6be-3e65-11e7-840f-7a3fd539ac5d.png">

We will have a better way to comment on proposed UX changes soon. In the mean time, if you have any comments on this approach, please share!

**Comment by shobhitagarwal1612** [comment]
Some other approaches to this other than bottom dialog sheet can be:

![images](https://user-images.githubusercontent.com/8918023/27885795-ea61c138-61f6-11e7-9022-7e5280dafebe.jpg)

![download](https://user-images.githubusercontent.com/8918023/27885796-eb482eb6-61f6-11e7-9df5-96e3778c0ea1.jpg)

![download](https://user-images.githubusercontent.com/8918023/27885797-ec57b060-61f6-11e7-8983-74dc76f1a813.png)

![0rst2h0](https://user-images.githubusercontent.com/8918023/27885798-edc18f48-61f6-11e7-9a51-706ad9bed7b2.png)
