### ISSUE TITLE
Add Bangla form support

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1041]
> I have Bangla script which my Android device (version 5.0.1) cannot recognize in text, so it seems that the only solution is to upload an image for every question and answer option in Bangla.
- christinamergenthaler@gmail.com

Related thread: https://groups.google.com/d/msg/opendatakit/jbJ9P4Oj7UM/9yO3FRkXhkYJ

I'm filing this issue mostly to gather information about what the state of Bangla on the various versions of Android, how we could support it (e.g., bundle fonts, render in web view) in Collect, and who might be interested in writing the code.

**Comment by chrislrobert** [comment]
We've had a great many users use Bangla, and my impression is that the Galaxy and Nexus devices have supported it for years, plus many other devices as well. I would also check the versions of devices sold in-country, which are more likely to be regional builds with direct support. Almost certainly buying new devices that directly support Bangla would be far more efficient than the available work-arounds.
