### ISSUE TITLE
Set app language after reading settings from QR code

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1051]
The app language setting is set by a QR code but the interface doesn't immediately change. It takes the app relaunching before it does.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 This is one you might be interested in looking at. I quickly included the language in the prefs yesterday but then realized it won't refresh right away.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I'll be looking into this
