### ISSUE TITLE
Lack of altitude and accuracy when we use location

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1052]
#### Software and hardware versions 
Collect 1.6.1

#### Problem description
When we use location and google sheets only latitude and longitude is sent to google sheet. The answer is without altitude and accuracy.

Form for testing: 
[loc.txt](https://github.com/opendatakit/collect/files/1029227/loc.txt)

**Comment by lognaturel** [comment]
This was probably deliberate but it would be good to know why. @yanokwa?

**Comment by yanokwa** [comment]
We didn’t add it because the Google Sheets integration was for mapping into Google products and you can’t map if you have all that data in the column. I think it'd be reasonable to add another two columns. One for altitude and another for accuracy.

**Comment by sashank27** [comment]
@opendatakit-bot claim

**Comment by sashank27** [comment]
@opendatakit-bot claim --force

**Comment by aishwarya-sankhla** [comment]
@opendatakit-bot claim

**Comment by aishwarya-sankhla** [comment]
Could you please guide on how I could reproduce this?

**Comment by yanokwa** [comment]
It'd help to know what you've tried so far. 

The high level steps are
1. Configure Collect to use Google Drive. http://docs.opendatakit.org/collect-connect-google/
1. Rename the form for testing above (https://github.com/opendatakit/collect/issues/1052#issue-231351261) to loc.xml and upload it to your Google Drive. 
1. Fill out the form and submit it to Google Sheets.

**Comment by aishwarya-sankhla** [comment]
I had previously pushed the form using adb but hadn't configured the the Google drive which is why I was not able to reproduce it.But now I'm able to view it.

Could you please tell how to go about this problem?

**Comment by yanokwa** [comment]
@aishwarya-sankhla What have you tried so far?

**Comment by lognaturel** [comment]
Great you're able to view the form now @aishwarya-sankhla! I agree it would be helpful to understand what you've tried so far. I do want to give you a warning that there is a pull request open that will modify Google Sheets code quite a bit that will need to be merged before this. You can see it at #1851. Hopefully it will go through testing tomorrow and can be merged then.

After that, you will need to see how latitude and longitude are currently split up into two columns and do the same for accuracy and elevation. You should verify that it works when results are added to an existing spreadsheet that doesn't have accuracy and elevation as well as when a new one is created.

**Comment by brunoguic** [comment]
@opendatakit-bot claim

**Comment by xsteelej** [comment]
@opendatakit-bot claim

**Comment by xsteelej** [comment]
@opendatakit-bot claim

**Comment by xsteelej** [comment]
Hi @yanokwa, @lognaturel,

I've managed to get the form from google drive, I had to add:

`<?xml version="1.0"?>`

To the top of loc.xml (renamed from loc.txt) before it would appear in "Get Blank Form".

I've filled out the form, got a geo location and finalised it. However, I'm not sure how to submit it to Google Sheets? I've tried "Send Finalized Form" but get an error:

"Geo - invalid sheet id".

(I've noticed that this does create an empty "Open Data Kit" folder on my Google Drive).

**Comment by brunoguic** [comment]
Hi @xsteelej, I had the same problem here some days ago..

My work around was create a new Google Sheet inside the empty "Open Data Kit"; get the shareable url-link from this sheet, and use that link as "Fallback submission URL" on the General Settings -> Server

I hope this enable you continue your development until get some more appropriate answer.

**Comment by xsteelej** [comment]
Hi @brunoguic,

Thanks, that did work! I've managed to upload the data to a sheet!

**Comment by xsteelej** [comment]
Hi @yanokwa,

It looks like altitude / accuracy was intentionally removed from the data-Point, I found this comment in 
`prepareListOfValues`:

```
// Check to see if answer is a location, if so, get rid of accuracy
// and altitude, try to match a fairly specific pattern to determine
// if it's a location [-]#.# [-]#.# #.# #.#
```

**Comment by lognaturel** [comment]
👍@brunoguic that's the way I would get the submissions working. You could also add a `submission` block to the form that sets the URL there (https://opendatakit.github.io/xforms-spec/#form-definition) but for testing I often just override the fallback URL instead.

From @yanokwa: "We didn’t add it because the Google Sheets integration was for mapping into Google products and you can’t map if you have all that data in the column." I think another reasons the accuracy and altitude columns weren't added was because they get closer to the 256 column limit, especially if there are several points collected. But users have asked for it and my sense is that GSheets integration is used for smaller forms. 200+ questions is a big survey.

**Comment by ravi808** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Hi @ravi808! Please be sure to look at assignees, tags and conversations before claiming an issue! There's an in progress pull request at #1052 I have unassigned you. If you'd like to talk through some possible issues to take on, please join us at http://slack.opendatakit.org/ in the #collect-code channel. Thanks!

**Comment by xsteelej** [comment]
Awaiting review
