### ISSUE TITLE
Can't swipe when an answer for image widget with web appearance is added

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1063]
#### Problem description
I'm not able to swipe left/right when an answer for image widget with `web` appearance is added.

Form for testing: 
[imageWeb.txt](https://github.com/opendatakit/collect/files/1032058/imageWeb.txt)

**Comment by lognaturel** [comment]
What I've found is that you can swipe where the prompt is. 😄 So yeah, it's a pretty terrible experience. Thank you for filing the issue.

Could we deprecate this one? Do we know how people use it?

**Comment by grzesiek2010** [comment]
@lognaturel I have no idea why we need this widget. Maybe you are right and we should deprecate this one.

**Comment by akshay-ap** [comment]
@lognaturel @grzesiek2010 
Selected image is no scaled to fit the screen using this widget. Same goes for image taken from camera.
Also, zoom in and zoom out buttons are buggy.
<img src="https://user-images.githubusercontent.com/16358982/33143476-f7ff223e-cfdf-11e7-9a41-013bb8bccfae.png" width=35%>

**Comment by lognaturel** [comment]
I agree, it's really bad. I honestly don't know what it was intended for. My preference would be to deprecate it soon, we just don't have a great deprecation process yet. This one might be safe to just remove.

**Comment by akshay-ap** [comment]
What is the procedure for deprecation?

**Comment by lognaturel** [comment]
We don't have one yet. 😩 Typically it would be something like announcing that a feature is going away with a timeline for removal. Defining this kind of process will be a great thing for the [Technical Steering Committee](https://forum.opendatakit.org/t/proposed-governance-for-odk-1-technical-steering-committee/10027) to do once it is in place.

**Comment by grzesiek2010** [comment]
There is a pr https://github.com/opendatakit/collect/pull/2800 which removes this widget so we can close the issue.
