### ISSUE TITLE
Update app after resetting settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1067]
#### Software and hardware versions 
Collect v1.7.0-beta-3

#### Problem description
The app isn't updated after settings are reset so it may not show the actual state of things.

#### Steps to reproduce the problem
1. Uncheck a couple of options in admin settings
1. Reset all settings from admin settings
1. Note that the options that were unchecked are still unchecked even though internally they are now set to true

===

1. Change the language in general settings
1. Reset all settings from admin settings
1. Note that the language doesn't change until the app is quit and restarted

#### Expected behavior
Admin settings and/or language should be updated.

#### Other information 
#1058 may be a nice example to look at. The challenge with this one is that I think we do want to show the result of the different reset components so going back to the landing screen may not be the best thing to do.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
