### ISSUE TITLE
ODK crashes if we use some words as a section name

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1074]
#### Software and hardware versions 
Collect v1.7.0

#### Problem description
ODK crashes if we use words like:
end, start, today, deviceid, simid, phonenumber as a section name.

**Comment by grzesiek2010** [comment]
I've just added a small fix on the Javarosa side. We shouldn't use these words so in that case we just skip related indexes.

Here is a form for testing: 
[testX.txt](https://github.com/opendatakit/collect/files/1035812/testX.txt)

**Comment by dcbriccetti** [comment]
@grzesiek2010 why is this? What’s special about those words?

**Comment by grzesiek2010** [comment]
@dcbriccetti Sorry for that poor description!
It's not exactly about "words". Look at the part of form:

       <data id="a26280000014QdjAAE">
                    <start />
                    <end />
                    <today />
                    <deviceid />
                    <simid />
                    <phonenumber />
                    <phonenumber>
                        <text />
                    </phonenumber>
                    <closemessage />
       </data>

As you can see, the questions are inside group with name `phonenumber` so the path is like `/data/phonenumber/text` where the path to automatically added, hidden question at the beginning of a form is `/data/phonenumber`. The same problem occurs if we use one of other existed name: `start`, `end` etc.

This case should be caught by form builder/creator but someone might edit a form manually so my fix is only to avoid the crash.

**Comment by lognaturel** [comment]
I think a slightly more precise description of this would be that there's a crash when nodes that bind to preloads have other nodes nested in them?

I don't know how in the world you discovered this but in general I'm in favor of more `null` checks so this is good!

Closed in opendatakit/javarosa#57
