### ISSUE TITLE
Problem with external widgets

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1075]
#### Software and hardware versions 
Collect v1.7.0

#### Problem description
During investigation of https://github.com/opendatakit/collect/issues/272 I ran into [ExStringWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java) and I noticed this:

> If the app does not launch, enable the text area for regular data entry

but I'm not eble to see this TextView, it's always disabled.

#### Other information 
The problem concerns ExIntegerWidget and ExDecimalWidget as well.

@lognaturel Do we really need these widgets?

**Comment by grzesiek2010** [comment]
@lognaturel if we really need here is a small fix https://github.com/opendatakit/collect/pull/1076/files

**Comment by lognaturel** [comment]
This is great, thanks! The standard example is [breathcounter](https://opendatakit.org/downloads/download-info/breathcounter-apk/) and we know it's a fairly common integration point.
