### ISSUE TITLE
Allow manual entry of points for geo widgets

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1084]
@geomapdev in #1028:

> use long press to manually collect a position. In many cases the user cannot stand in the location he/she wants to map.

This is already in geoshape.

**Comment by grzesiek2010** [comment]
We can just use `appearance="placement-map"` and we are able to do that manually. Am I missing something?

**Comment by lognaturel** [comment]
@grzesiek2010 It looks like the functionality isn't consistent between map types.

Do support long press to manually add points:
- OSM geopoint w/ `placement-map` appearance
- Google geoshape
- OSM geoshape

Don't support long press to manually add points:
- Google geopoint w/ `placement-map` appearance
- Google geotrace
- OSM geotrace

**Comment by davereinhart** [comment]
I would also add that it would be good to leave it up to the user instead of part of the form design...  In the field they may want to use current position for most records, but may also need to collect some features they are not able to stand directly on top of.

**Comment by lognaturel** [comment]
Yes, I agree @geomapdev. I think the widgets that currently support manual point creation do it as you describe except that the geoshape ones should also support position-based collection.
