### ISSUE TITLE
Linking different forms

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1086]
From thoduor@gmail.com and https://groups.google.com/d/msg/opendatakit/XLU3S3y9FR8/KqFwPdwoCAAJ

> I hope this finds you well. Just as an idea, is it possible to link different odk forms i.e in the process of filling one form you call another form. Or maybe using one form as a menu where it calls other forms?

**Comment by lognaturel** [comment]
I'll close this for now while the high-level discussion happens [on the forum](https://forum.opendatakit.org/t/linking-different-forms/6636/4). We can re-open once there's a specification.
