### ISSUE TITLE
Crash when loading sample mbtiles file as offline layer

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1093]
#### Software and hardware versions 
Collect v1.7.0-10-gb8bb7103a

#### Problem description
The [sample mbtiles file from Mapbox](https://www.mapbox.com/help/define-mbtiles/) doesn't work as an offline layer.

#### Steps to reproduce the problem
1. Place the [sample mbtiles file from Mapbox](https://www.mapbox.com/help/define-mbtiles/) in a folder in /sdcard/odk/layers
1. Open a form such as Widgets from the default server that includes geo activities
1. Open a geo activity
1. Tap on the layers icon
1. Select the layer put on the device

#### Expected behavior
The layer should work.

#### Other information
I think this is worth investigating because it's the sample provided by MapBox and very likely to be standards-compliant. My wild guess is that the implementation in Collect assumes that something not required by the spec is always there.
 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
	at org.odk.collect.android.spatial.OsmMBTileSource.createFromFile(OsmMBTileSource.java:93)
	at org.odk.collect.android.spatial.OsmMBTileProvider.<init>(OsmMBTileProvider.java:0)
	at org.odk.collect.android.spatial.MapHelper$1.onClick(MapHelper.java:230)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1119)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3152)
	at android.widget.AbsListView$3.run(AbsListView.java:4067)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by grzesiek2010** [comment]
@jnordling any idea? We want to fix this issue I've made only initial investigation so far. Maybe you have a brilliant idea what's wrong? 
we get null here https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/spatial/OsmMBTileSource.java#L92

**Comment by jnordling** [comment]
@grzesiek2010 Ill take a look. I think the MBTiles 1.1 spec (tile_data should exist in table 'tiles' not 'images'), but still with backwards compatibility.

**Comment by grzesiek2010** [comment]
@jnordling 
It's not related I think because if we use `images` it's the same.

**Comment by jnordling** [comment]
Ok just for reference. I think the new spec can be implemented like this.. Ill keep digging. Do you have a sample mbtile file thats not work. I can give it a test.

**Comment by jnordling** [comment]
`

       Cursor tilesExistCursor = db.rawQuery("SELECT * FROM sqlite_master WHERE name ='tiles' and type='table'",new String[] {});
       Cursor imagesExistCursor = db.rawQuery("SELECT * FROM sqlite_master WHERE name ='images' and type='table'",new String[] {});
       if(tilesExistCursor.getCount() != 0){
           cursor = db.rawQuery("SELECT tile_data FROM tiles LIMIT 0,1",new String[] {});
       }else if(imagesExistCursor.getCount() != 0){
           cursor = db.rawQuery("SELECT tile_data FROM images LIMIT 0,1",new String[] {});
       }
       tilesExistCursor.close();
       imagesExistCursor.close();

       if (cursor != null && cursor.getCount() != 0) {
           cursor.moveToFirst();
           is = new ByteArrayInputStream(cursor.getBlob(0));

           Bitmap bitmap = BitmapFactory.decodeStream(is);
           tileSize = bitmap.getHeight();
           logger.debug(String.format("Found a tile size of %d", tileSize));
       }
`

**Comment by grzesiek2010** [comment]
@jnordling look at the first comment there is a link there. You can also use https://openmaptiles.org/downloads/#country

**Comment by jnordling** [comment]
@grzesiek2010 I took a look at it in more detail. I think your correct, its something else. Im going to investigate a bit further. Ill report back when I know whats happening.

**Comment by jnordling** [comment]
Ok I think it has to do with that the MBtiles specification has changed alot since this was added, heres why I think that... I found a old MBtiles from when this was first develop (using TileMile which is no longer supported) and it works fine. [Try with old MBTile](https://s3.amazonaws.com/geoodk.com/downloads/mbtiles/MapBox_Demo_Layer.zip)

When I use the more up to date MBtiles probably created using MapBox Studio, they are throwing these errors. 

I wonder if we should be using a lib for this that supports backwards compatibility of these files as well as the new ones.

Image of old Mbtile file working with current build,

<img src="https://cloud.githubusercontent.com/assets/11786919/26790064/64faa290-49e0-11e7-9fd6-8b19aa30b157.png" width="250px"/>

**Comment by lognaturel** [comment]
I changed the file extension of the `mbtiles` file to `db` to explore it with a DB browser. If I look at the `format` key in the `metadata` table, I see that the tile blobs are stored as `pbf`. The current code assumes that the blobs are bitmaps (`BitmapFactory.decodeStream(is)`) but as I understand it, they could be `pbf`, zipped `pbf`, `jpg` or `png`. The tile type should be read from the metadata table.

@grzesiek2010 [this](https://github.com/mapbox/awesome-vector-tiles) will probably be a good place to look for decoding `pbf`.

**Comment by lognaturel** [comment]
@grzesiek2010 I think you mentioned looking on the osmdroid side to see whether `pbf` is supported or whether there's any intention to support it. I think the answer is no: https://github.com/osmdroid/osmdroid/issues/101

Now we need to decide whether it's worth adding a tile provider. I suggest we wait until the offline map feature is documented such that people actually use it and that an actual user requests PBF support. How does that sound?

**Comment by lognaturel** [comment]
Actually, I had another thought. @grzesiek2010, how about throwing up an error message for now if the format is not jpg or png? That would be much better than a crash.

**Comment by grzesiek2010** [comment]
@lognaturel 
https://github.com/opendatakit/collect/pull/1172/files
I've added a simple null check as only this line causes the crash. So currently if there is something wrong with the layer file the default one is visible.

I think we should merge it now an I'll will try to find better solution in the future.
