### ISSUE TITLE
Popup for incorrect username & password after loading valid credentials from settings file / QR code

### ISSUE THREAD

**Issue by carl-eis** [getodk/collect#1100]
#### Software and hardware versions 
Collect v1.7.0, Android v7.0, device used: LG G5 (HG-H850)

#### Problem description
When loading in settings from a file and trying to get a new blank form from a server requiring authentication, a popup will show displaying "Invalid username or password for server...", even though the username/password combination is correct. Clicking "OK" will continue to login and show the available forms as usual, proving that the username & password combination is indeed correct.

[Screenshot of popup](http://i.imgur.com/vZOupVw.png)

#### Steps to reproduce the problem
- Navigate to General Settings > Platform settings
- Set up a url, username & password combination for a password-protected aggregate server
- Navigate to Admin Settings > Import/Export Settings > Context menu > Share
- Save the QR code to a folder on the device
- Uninstall ODK & delete the odk folder on the device's storage
- Install ODK from the play store
- Navigate to Admin Settings > Import/Export Settings 
- Choose "Select code from SD Card", pick the QR code that was saved earlier
- After "Settings imported successfully" notification is shown, click "Get Blank Form". The "Invalid username or password" popup described above will appear.

#### Expected behavior
Clicking "Get Blank Form" after loading settings from a file should not show an "Invalid username / password" popup if the details are correct.

#### Other information 
This was tested with both the "collect.settings" file in the odk folder, and a QR code image.

**Comment by smoyte** [comment]
+1 

I was just about to file this one.
