### ISSUE TITLE
"Nothing available to display..." text is visible too long.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1105]
#### Software and hardware versions 
Current master branch

#### Problem description
"Nothing available to display..." text is visible too long.
It might occur in other lists as well.

![issue](https://cloud.githubusercontent.com/assets/3276264/26832331/6589b620-4acf-11e7-883c-4dc0aae3ef81.gif)

**Comment by shobhitagarwal1612** [comment]
I'm working on it
