### ISSUE TITLE
WebUtils.getXmlDocument() does not reliably drain stream before closing

### ISSUE THREAD

**Issue by alxndrsn** [getodk/collect#1106]
`skip()` is used unreliably to drain stream at https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java#L396-L400

Related, `isr.close()` is called in two places.  As `isr.close()` is called in the `finally` block, it can probably be deleted from https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java#L391-L392.  If it really needs to be set to `null`, this should likely also happen in the `finally` block.

**Comment by icemc** [comment]
@alxndrsn and @lognaturel will like more directives on this issue. Will love to look into it

**Comment by alxndrsn** [comment]
Ref stream draining:
```
// ensure stream is consumed...
final long count = 1024L;
while (isr.skip(count) == count) {
    // skipping to the end of the http entity
}
```
This code doesn't necessarily do what the comment implies that it does - as per [the javadoc for InputStream.skip(long)](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#skip(long)):

> Skips over and discards `n` bytes of data from this input stream. The `skip` method may, for a variety of reasons, end up skipping over some smaller number of bytes, possibly `0`. This may result from any of a number of conditions; reaching end of file before `n` bytes have been skipped is only one possibility. The actual number of bytes skipped is returned. If `n` is negative, no bytes are skipped.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010  This can be closed now.
