### ISSUE TITLE
Sort the list and Filter the list options are available via device menu button

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1111]
#### Software and hardware versions 
Current master branch

#### Problem description
Sort the list and Filter the list options are available via device menu button what's wrong I think and we don't need it.

![screenshot_2017-06-08-15-48-15](https://user-images.githubusercontent.com/3276264/26931803-f4227bfe-4c61-11e7-916b-758de8bf1429.png)

**Comment by lognaturel** [comment]
@grzesiek2010 Can you please do a quick sanity check off master with your device?
