### ISSUE TITLE
Supporting Ethiopian Calendar Widget

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1113]
From https://github.com/opendatakit/opendatakit/issues/1284

> Can we add Ethiopian date widget for ODK..the full source code is developed by Commcare and can be found at https://confluence.dimagi.com/display/commcarepublic/Alternate+Calendar+Formats+for+CommCare+Android. this is not an issue but we can take it as a feature

**Comment by konishon** [comment]
can I work on this @lognaturel ?

**Comment by grzesiek2010** [comment]
@nishontan it's already done (almost done since it's under code review) https://github.com/opendatakit/collect/pull/1505

my bad I should have done that:
@opendatakit-bot claim
