### ISSUE TITLE
Include some kind of versioning with settings files

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1115]
Currently, there are two ways to import settings through files: putting a `collect.settings` file in the ODK root (usually /sdcard/odk) and reading from a QR code which includes settings JSON. As the pace of development on Collect increases, settings will be more likely to change and we should have a way to ensure that old config files or QR codes continue to be usable.

One example of that can be seen in #1101 -- two settings having to do with autosend were combined into one. In that case, it is possible to check which keys already exist and use that information to do the migration but ideally we would have a standardized way to also deal with brand new keys or changed defaults.

On the json side, we can easily use a `version` key. On the serialized file side, I think we can add another `HashMap` including a `version` key.

How should version be represented? Options I can think of:
1. An integer that increases by 1 each time there's a breaking change. This is similar to database versions used for migrations.
2. A string representing the Collect tag (e.g. `v1.7.0`). We'd have to do some manipulations to it to turn it into a number that can be compared.

I have a slight preference for 1 because it's simple and matches the database approach.

**Comment by nribeka** [comment]
Personally, I prefer the second one since it's going to much easier if there's a need for developers to validate the version number (and I'm pretty sure we will need to manually validate the settings sometimes). The first approach will need a mapping between settings version and the collect version.

It should be a lot of effort to convert the string representation to integer, right?

**Comment by seadowg** [comment]
This would be a good discussion to move to the [forum](https://forum.getodk.org) if it needs to be continued.
