### ISSUE TITLE
Avoid first question "add new group"

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/collect#1121]
Good morning,

the message (Add new group toto) we get when we enter a repeat group in collect is a bit disturbing for the users.
We actually "solve" the problem by deleting **jr:template=""** string in th xml file.
Once this is done, the message appears only before the second round in the repeat group.

Could it be possible to set this as the default behaviour ?

Thanks again and a lot,

Mathieu Bossaert

**Comment by lognaturel** [comment]
This is really a pyxform issue -- filed at https://github.com/XLSForm/pyxform/issues/182!
