### ISSUE TITLE
Change "Add new group xxx" to "Add new"

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/collect#1122]
Hi,

"Add new ..." is easier to understand for the user than "Add new group ...'

Maybe it is just a translation problem, but I think it is important. Collegues on fields don't add a group, they don't know what is a group, they just add one more element.

For example they never add a new "group species", the add a new species to a list.

**Comment by mathieubossaert** [comment]
I just made a suggestion in transifex...

So I suggest to replace 

> Add another "1%s" group?

and 

> Add a new "" group?

 by 

> Add a/an "1%s" ?

For me this is clear enough for the end user. The group concept is ok for form designers, but not at all for collect users. In french it could be 

> "Ajouter un(e) "1%s" ? 

https://www.transifex.com/opendatakit/collect/translate/#fr/strings/8478157
https://www.transifex.com/opendatakit/collect/translate/#fr/strings/8478159

**Comment by lognaturel** [comment]
Thanks for bringing this up again! Let's keep the conversation on the forum for a bit so we can get feedback from other users and decide on a course of action: https://forum.opendatakit.org/t/change-prompt-when-adding-new-group-new-loop/20025
