### ISSUE TITLE
geo fields sould be store in wkt

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/collect#1123]
Good morning,

Actually, the geoshape field stores data into a string with a "strange" format. 

The use of Well Known Text format could be a great enhancement. All the databases supported by odk do understand that format. https://fr.wikipedia.org/wiki/Well-known_text 

Actually we have to create some fun sql to get data into GIS Eneblad databases such as PostGIS.

**Comment by mathieubossaert** [comment]
Here is the function I made yesterday to create a valid PostGIS geometry (WGS84) from odk geofields : 

```sql
CREATE OR REPLACE FUNCTION odk.geom_from_odk_to_postgis(LONG numeric, LAT numeric, GEOTRACE TEXT, GEOSHAPE TEXT)
RETURNS geometry(GEOMETRY,4326) AS
$$
WITH geom_from_odk AS 
(
        SELECT trim(COALESCE(NULLIF(trim(concat(LAT,' ',LONG),';'),' '),
        GEOTRACE,
        GEOSHAPE),';') as geom_odk
),
node_array AS (
        SELECT geom_odk, unnest(string_to_array(btrim(geom_odk::text, ';'::text), ';'::text)) AS unnest,
        array_length(string_to_array(btrim(geom_odk::text, ';'::text), ';'::text), 1) AS nb_points,
        generate_series(1, array_length(string_to_array(btrim(geom_odk::text, ';'::text), ';'::text), 1)) AS ordre,
        split_part(unnest(string_to_array(btrim(geom_odk::text, ';'::text), ';'::text)), ' '::text, 1)::numeric AS LAT,
        split_part(unnest(string_to_array(btrim(geom_odk::text, ';'::text), ';'::text)), ' '::text, 2)::numeric AS long
        FROM geom_from_odk
)--, geom AS (
SELECT 
CASE
WHEN node_array.nb_points = 1 THEN st_union(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326))
WHEN st_isclosed(st_makeline(array_agg(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326) ORDER BY node_array.ordre))) IS FALSE THEN st_makeline(array_agg(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326) ORDER BY node_array.ordre))
WHEN st_isclosed(st_makeline(array_agg(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326) ORDER BY node_array.ordre))) AND node_array.nb_points > 3 THEN st_makepolygon(st_makeline(array_agg(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326) ORDER BY node_array.ordre)))
-- ELSE the polygon is invalid because made of 3 points, 1st and 3rd are the same so we create a linestring
ELSE st_makeline(array_agg(st_setsrid(st_makepoint(node_array.long::double precision, node_array.lat::double precision), 4326) ORDER BY node_array.ordre))
END AS geom
FROM node_array
GROUP BY node_array.nb_points;
$$
  LANGUAGE sql VOLATILE
  COST 100;
```

**Comment by mathieubossaert** [comment]
With WKT format, a simple use of postgis function ST_GeomFromText(geo_column) should do the job :-)
http://postgis.net/docs/ST_GeomFromText.html

**Comment by lognaturel** [comment]
@mathieubossaert, apologies about the lack of response here! I think this is a pretty big conversation because it would involve changes to the XForms spec and tools across the ODK ecosystem (including Collect, Aggregate, etc).

I think the right place to kick off the discussion would be on the forum in the Features section ([here](https://forum.opendatakit.org/c/features)) since it's such a broad, open-ended discussion. If consensus is reached on an actionable plan, then it can move to issues across all the tools that would need to change.

I encourage you to post there with a high-level description of the problem a change in the geo widgets' output format would solve and any suggestions you have for how to approach it.

**Comment by mathieubossaert** [comment]
@lognaturel, no problem, I've just created the topic : https://forum.opendatakit.org/t/geo-fields-sould-be-store-in-wkt-format-well-known-text/7048

Thanks,

Mathieu
