### ISSUE TITLE
Delete after send option doesn't work

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1129]
#### Software and hardware versions 
Collect v1.7.1

#### Steps to reproduce the problem
1. Check "Delete after send" option in "General Settings"
2. Complete any form
2. Go to "Send Finalized Form" and send that form

#### Expected behavior
That instance should be deleted automatically.

#### Other information 
It's caused by https://github.com/opendatakit/collect/pull/574/files#diff-b569288bc988dd4905e004c69dbba56dL660

@lakshyagupta21 could you explain why you changed `STATUS_SUBMITTED` to `STATUS_COMPLETE` because I don't understand why we need that.

**Comment by lognaturel** [comment]
Good find, @grzesiek2010. This is not good because people depend on delete after send to remove sensitive data. It would be great to have some kind of test of this behavior at some point in the not too distant future.
