### ISSUE TITLE
Consistently use "autosend" or "auto send"

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1132]
I don't think "autosend" is a word, so we should probably go for "auto send." When it's capitalized, it should be "Auto send."

**Comment by VisheshVadhera** [comment]
Hey, can I tackle this one?

**Comment by lognaturel** [comment]
That would be great, thank you!

**Comment by VisheshVadhera** [comment]
I see in some of the places we are using "autosend" as preference key. Just wondering if changing it to "auto_send" that will break compatibility for existing set of users?

**Comment by lognaturel** [comment]
Only user-facing strings need to be changed!

**Comment by VisheshVadhera** [comment]
Alright, on it!
