### ISSUE TITLE
Allow select1 appearances to combine with search/autocomplete

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1137]
From [the XLSForm spec](https://xlsform.org): "The non-default appearance style goes into the column first, followed by a space, then the search() expression. [e.g., quick search()]"

**Comment by lognaturel** [comment]
This is a little stranger than I expected. I kind of wondered at the time why `search` had parens after it and it turns out there is a search function that's used to filter part of a CSV. I think that the cryptic comment in `WidgetFactory` that says 

> // SurveyCTO-revised support for dynamic select content (from .csv files)
> // consider traditional ODK appearance to be first word in appearance string

was meant to explain that the appearance tests use `startsWith` so that `search()` could be combined with it. However, in April of 2016 the `search` appearance that filters a list of choices was added which made the `search()` "function" unaccessible for select one. [Here](https://forum.opendatakit.org/t/use-of-two-appearances/9443/3?u=ln) is the full explanation. 

To make things stranger, the current `search`/`autocomplete` appearance wasn't added to select multiples so the `search()` "function" still works there.

Perhaps we should see about officially deprecating `search()` before we make this change?

**Comment by lognaturel** [comment]
I think the `search()` appearance/function, as weird as it is, is too broadly used for deprecation at this time.

Other appearances should combine with `search()`, `search` and `autocomplete`.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
