### ISSUE TITLE
Add "export settings" functionality back

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1138]
In the recent changes to preferences, "Save Settings to Disk" was removed from the Admin Settings. That feature allowed users to export a serialized `collect.settings` file that could be pushed to multiple devices. 

For most people, QR code configuration will now be more convenient but some people may still prefer to use configuration files. In addition #1099 is adding the ability to load json preference files which will be easier to generate and verify than the serialized files.

Since we haven't discussed removing the serialized file creation with the broader community, I think we should bring that back. In addition, we could also add the ability to generate a json file.

**Comment by lognaturel** [comment]
@carl-eis @hooverlunch @acawood777 @grzesiek2010 @shobhitagarwal1612 you've all been thinking about externally loaded settings recently so I'd be interested to hear your thoughts. I know some of you are generating the settings files on the server side so perhaps it doesn't matter to you.

**Comment by shobhitagarwal1612** [comment]
> In the recent changes to preferences, "Save Settings to Disk" was removed from the Admin Settings.

@lognaturel I can still see this option under options menu in Admin Preferences.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I don't see an options menu in Admin Prefs on any device I've tried, all running API 22.

**Comment by acawood777** [comment]
@shobhitagarwal1612 @lognaturel   The option was still available in v1.7.0, on the QR code page, by clicking the Android Menu button on my Android 4.4.2 device.  
 Haven't tested now, but I know when @jovaee was working on the settings a day or two back he also couldn't see the option in this place.

@lognaturel  As to the main question, given ODK's huge userbase and many possible permutations of how people use the app, it's probably not a good idea to just pull a feature.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 and I discussed in Slack and the removal was an accidental side-effect of the change in the UI libraries. It works for him because he has a hardware options menu button! 

@shobhitagarwal1612 can you look into bringing it back when you have a chance?

**Comment by shobhitagarwal1612** [comment]
Sure
