### ISSUE TITLE
'Go To Prompt' icon is not visible on Android 4.1 and 4.4, both Samsung devices

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1154]
#### Software and hardware versions 
Collect - current master
Android v4.4 - Samsung J1
Android v4.1 - Samsung GALAXY YOUNG GT-S6310
#### Problem description
'Go To Prompt' icon is not visible. Option is visible when user clicks on 3 dots

#### Steps to reproduce the problem
User stars form
User sees 3 dots in header
User clicks on 3 dots and sees 'Go To Prompt' option 

#### Expected behavior
'Go To Prompt' option is visible next to save icon
Only 'General Setting' is under 3 dots
 
#### Other information 
Discovered during testing [Migrating to Android Support Library #912](https://github.com/opendatakit/collect/pull/912)
![screenshot_2017-06-14-13-39-21](https://user-images.githubusercontent.com/3907554/27135182-29c06f4a-5118-11e7-9a78-55424943f3fe.png)
![screenshot_2017-06-14-13-39-27](https://user-images.githubusercontent.com/3907554/27135188-2d55cdb2-5118-11e7-9f40-c25b6653dc5b.png)

**Comment by yurilaguta** [comment]
Working on it.
