### ISSUE TITLE
'Go Up' option looks like an active button

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1156]
#### Software and hardware versions 
Collect - current master
Android 5.0
Android 6.0

#### Problem description
'Go Up' option looks like an active button. The same background colour is visible. Buttons differ only by frame.

#### Steps to reproduce the problem
1. User starts form
2. User clicks on 'Go To Prompt' icon
3. 'Go Up' button looks like an active
![master](https://user-images.githubusercontent.com/3907554/27135885-063c8228-511a-11e7-84e4-d21a3702327a.png)

#### Expected behavior
Button is grey which shows that is inactive

#### Other information 
Regression. Button looks like expected on v1.7.1
![1 7 1](https://user-images.githubusercontent.com/3907554/27135910-1211c66c-511a-11e7-8cc3-80e9f910d121.png)

**Comment by lognaturel** [comment]
I'm going to mark some of these UI issues as part of the UI refresh project but that doesn't mean @shobhitagarwal1612 needs to be the one to address them! Others are very welcome to help (thank you @mmarciniak90 and @grzesiek2010).
