### ISSUE TITLE
User is moved to General Setting from Server Settings, User interface, Form manager, User and device identity when user changes device orientation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1184]
#### Software and hardware versions 
Collect current master, v1.8.0 beta-9
Android v4.1, v4.4, v5.1, v6.0, 
Device used: 
- Samsung Galaxy Young GT-S6310, 
- Samsung Galaxy J1 SM-J100H, 
- Huawei Y560-L01, 
- Sony Xperia Z3 D6603

#### Problem description
User is moved to General Setting from Server Settings, User interface, Form manager, User and device identity when user changes device orientation

#### Steps to reproduce the problem
1. User is on one of view:  Server Settings, User interface, Form manager, User and device identity
2. User changes device orientation
3. User is moved to General settings

#### Expected behavior
User is still on the same view in other orientation.

#### Other information 
Problem discovered during testing [Settings redesign #1101](https://github.com/opendatakit/collect/pull/1101)

**Comment by mmarciniak90** [comment]
The same situation is in Admin settings. User is moved to Admin settings when user changes device orientation on some of sub-menu in Admin settings

**Comment by lognaturel** [comment]
@shobhitagarwal1612 could you please look at this one?

**Comment by shobhitagarwal1612** [comment]
Sure, I'll look into it today

**Comment by lognaturel** [comment]
From @mmarciniak90 on #1188:

> **Use case:**
> 1. User goes to General Settings
> 2. User goes to Server
> 3. User changes device orientation
> 4. User is moved to General Settings (bug: #1184)
> 5. User changes device orientation again
> 6. User clicks device back button
> 7. Header line gets thicker  :heavy_exclamation_mark: To leave setting user need to click again on device back button
> 8. User clicks on server
> 9. User sees unexpected combination of two views
> ![screenshot_20170622-204454](https://user-images.githubusercontent.com/3907554/27450643-9d217978-578c-11e7-92bf-a7fc26701442.png)
> ![screenshot_20170622-204457](https://user-images.githubusercontent.com/3907554/27450642-9d1da92e-578c-11e7-8183-293f1840ec47.png)
> ![screenshot_20170622-204500](https://user-images.githubusercontent.com/3907554/27450641-9d19bee0-578c-11e7-9dc4-6be88066305d.png)
