### ISSUE TITLE
Crash if user changes devices orientation on Server settings and second time on General settings and then user clicks device back button

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1191]
#### Software and hardware versions 
Collect current master v1.8.0 beta 9, 
Android v4.1, v4.4, v5.1, v6.0, 
Device used: 
- Samsung Galaxy Young GT-S6310, 
- Samsung Galaxy J1 SM-J100H, 
- Huawei Y560-L01, 
- Sony Xperia Z3 D6603

#### Problem description
Crash if user changes devices orientation on Server settings and second time on General settings and then user clicks device back button

#### Steps to reproduce the problem
1. User goes to General Settings
2. User goes to Server
3. User changes device orientation
4. User is moved to General Settings (bug: #1184)
5. User changes device orientation again
6. User clicks device back button
7. App crashes

#### Expected behavior
User leaves Settings

#### Other information 
Problem discovered during testing [Settings redesign #1101](https://github.com/opendatakit/collect/pull/1101)
Problem is not visible when user changes device orientation on User interface, Form management or User and device identity

**Comment by shobhitagarwal1612** [comment]
Closed in #1188
