### ISSUE TITLE
Settings menu is not visible

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1211]
#### Software and hardware versions 
Collect v1.8.0, Android v6.0, HOT 4 (X557)

#### Problem description
From Play Store review: "The new update hid the setting menu.  Please fix."

#### Steps to reproduce the problem
Unknown, user asked for more information

#### Expected behavior
Same menus should be available as in previous releases.

**Comment by yanokwa** [comment]
Just got another report from a OnePlus3 running Android 7.1

>New update hides the settings 'dots' on the top right corner on my device, a One Plus 3. However, the same update does not have this issue on our field assistant's phones which are Xiaomi Redmi 4As.
