### ISSUE TITLE
"Save Settings to Disk" no longer available

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1214]
#### Software and hardware versions 
Collect v1.8.0; Galaxy Tab A, Android 5.1.1 and Moto G4, Android 7.0.0

#### Problem description
Regression of #1138; the "Save Settings to Disk" menu item is no longer available from Admin Settings.

#### Steps to reproduce the problem
Go to the Admin Settings.

#### Expected behavior
"Save Settings to Disk" is available from the three dots menu as in previous versions.

**Comment by lognaturel** [comment]
I spent a little bit of time looking into this but I'm not having any luck. I can see `onCreateOptionsMenu` is never called but in the context of a `PreferenceActivity`, I'm not sure where to go from there. @shobhitagarwal1612 maybe you know how to address it?

**Comment by shobhitagarwal1612** [comment]
Looking into it
