### ISSUE TITLE
Clicking the device back button does not close the 'Change Admin Password' dialog

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1220]
#### Software and hardware versions 
Collect v1.8.0
Android 4.1, 4.2, 4.4, 5.1, 6.0

#### Problem description
Clicking the device back button does not close the 'Change Admin Password' dialog

#### Steps to reproduce the problem
User goes to Admin Settings
User opens 'Admin Password'
User wants to close the dialog
Device back button does not close 'Change Admin Password' dialog

#### Expected behavior
Clicking the device back button closes 'Change Admin Password' dialog

**Comment by srsudar** [comment]
This is due to the call to the `builder.setCancelable(false)` [line in `AdminPreferencesFramgent.java`](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java#L130). 

Changing that line to `builder.setCancelable(true)` restores back button behavior. Does anyone know why it was included in the first place?

**Comment by grzesiek2010** [comment]
I think we should adopt one approach for all dialogs: either we allow to close dialogs using device back button (and clicking outside the dialog) or we should block it.

and we have to remember about it working on: #541 

What do you think @lognaturel ?

**Comment by lognaturel** [comment]
My sense is that this was deliberate to force the user to explicitly choose to accept the password or cancel. In a lot of contexts, it's not a big deal if the dialog is accidentally dismissed. In this case, it would be bad if a user thought they set an admin password when they didn't. What do you think @srsudar, @grzesiek2010?

**Comment by srsudar** [comment]
That makes some sense to me, as long as the goal is to include consistent behavior on password dialogs as part of the dialog refresh. This particular dialog can currently be dismissed via rotation, but I bet that will change with the refresh.

The [material design guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-behavior) don't offer much guidance:

> Dialogs may be dismissed either by tapping outside of the dialog, or tapping the system back button (on Android). Alternatively, the user’s ability to dismiss a dialog may be disabled, so that one of the actions must be chosen before proceeding.

As a user I think I would prefer the ability to dismiss via the back button, but I don't feel at all strongly about it as long as it was a deliberate decision to go against what I expect as the "normal" behavior.

**Comment by lognaturel** [comment]
No super strong feelings here so let's keep it as-is for now.
