### ISSUE TITLE
App crashes when user goes to URL widget on Android 4.2.1, Infinix X451

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1221]
#### Software and hardware versions 
Collect v1.8.0
Android 4.2.1
Infinix X451
[Widgets.txt](https://github.com/opendatakit/collect/files/1111898/Widgets.txt)
[WidgetsReadOnly.txt](https://github.com/opendatakit/collect/files/1111899/WidgetsReadOnly.txt)

#### Problem description
App crashes when user goes to URL widget 

#### Steps to reproduce the problem
1. User starts job with attached forms
2. User opens URL widget
3. App crashes 

#### Expected behavior
User is able to open URL widget without crash

#### Other information 
Discovered during testing [ Handle readonly using all widgets](https://github.com/opendatakit/collect/pull/1195)

**Comment by lognaturel** [comment]
@mmarciniak90 Is there also a problem with URLs accessed from the About menu?

**Comment by grzesiek2010** [comment]
@lognaturel No it isn't it was a problem in the widget class only but I added changes in https://github.com/opendatakit/collect/pull/1224/files#diff-222355720a50b9a557d326daa09baf11R75 just in case to avoid similar situation in about menu for example (as you noticed it would be possible)

**Comment by lognaturel** [comment]
Of course, thanks! Forgot they used the same utility. 👌
