### ISSUE TITLE
Auto restart application after crash/force close

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1235]
Whenever the application encounters an unhandled exception, the app crashes. The user usually tries to open it again. So I want to propose that we restart the application after `crash`/`force close` in order to improve the user experience. @grzesiek2010 What do you think?

[link1](http://chintanrathod.com/auto-restart-application-after-crash-forceclose-in-android/
) [link2](https://stackoverflow.com/questions/22978245/how-to-prevent-android-app-from-crashing-due-to-exception-in-background-thread)

**Comment by srsudar** [comment]
Would it still be clear to the user that a crash had occurred? If it looked like it just kicked them out of a form to the start screen, that apparent unpredictability might be as bad as a crash.

Would there be a way to make sure you didn't get stuck in a loop? If it got in a bad state and crashed on opening, eg, it would be bad news if it kept crashing and then restarting itself.

Is this a common practice other apps do and I don't realize it? Occasionally I'll get a notification saying "crash captured" or something, but I don't know what app it is or where it came from. It could be something like this I suppose.

**Comment by grzesiek2010** [comment]
I agree with @srsudar generally I'm not in favor of this.

**Comment by lognaturel** [comment]
We have a pretty hard time getting users to report crashes and bad behavior and I think that that reopening the app would make it even less clear to users that something bad happened. That along with @srsudar's good observations make me think we should close.
