### ISSUE TITLE
Exception java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1237]
Logs from firebase:
> Exception java.lang.OutOfMemoryError: Failed to allocate a 21964732 byte allocation with 13225104 free bytes and 12MB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.BitmapFactory.nativeDecodeStream (BitmapFactory.java)
android.graphics.BitmapFactory.decodeStreamInternal (BitmapFactory.java:646)
android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:622)
android.graphics.BitmapFactory.decodeFile (BitmapFactory.java:402)
org.odk.collect.android.utilities.FileUtils.getBitmapScaledToDisplay (FileUtils.java:204)
org.odk.collect.android.widgets.ImageWidget.<init> (ImageWidget.java:201)
org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt (WidgetFactory.java:136)
org.odk.collect.android.views.ODKView.<init> (ODKView.java:199)
org.odk.collect.android.activities.FormEntryActivity.createView (FormEntryActivity.java:1225)
org.odk.collect.android.activities.FormEntryActivity.showNextView (FormEntryActivity.java:1381)
org.odk.collect.android.activities.FormEntryActivity.onFling (FormEntryActivity.java:2858)
android.view.GestureDetector.onTouchEvent (GestureDetector.java:650)
org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent (FormEntryActivity.java:1320)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:71)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:71)
com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:373)
android.view.View.dispatchPointerEvent (View.java:10165)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4446)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4314)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3914)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3880)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4007)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3888)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4064)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3914)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3880)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3888)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3861)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6257)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6196)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6157)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6360)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:192)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:323)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:6123)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

**Comment by lognaturel** [comment]
Did I understand correctly that this will be addressed in #1210 by e5a6fed? If so, please close!

**Comment by grzesiek2010** [comment]
Yes you are right.
