### ISSUE TITLE
App URL included in strings for translation

### ISSUE THREAD

**Issue by nap2000** [getodk/collect#1243]
app_url is included in strings.xml and hence is included in the translations.  Commonly it is left untranslated as "http://opendatakit.org" which is fine however sometimes other URLs are used such as in https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/values-ru/strings.xml

**Comment by lognaturel** [comment]
Sigh. How brazen! Hopefully it was just a misunderstanding. At least it's a fork of ODK and not something totally random.

**Comment by lognaturel** [comment]
I just changed the translation by hand for the last release but we should try to get a new contributor to move the string as suggested by the August release or Just Do It if we can't get a new person in.

**Comment by dr0pdb** [comment]
@lognaturel  Is this still up for grabs ? I would like to solve it as my first minor bug fix if it's available

**Comment by lognaturel** [comment]
Yes, please!
