### ISSUE TITLE
Dynamic selects from pre-loaded data gives 'java.util.Vector' error

### ISSUE THREAD

**Issue by sowmyaaguptaa** [getodk/collect#1245]
Collect v1.7.1 Android v5.1.1, device used - Redmi 2s

I am trying to preload data from a csv file into a select box dynamically.
I created the XLSForm as guided here - http://xlsform.org/#dynamic-selects-from-pre-loaded-data
But on running it on the ODK Collect it gives an error saying,

"The search handler returned a object of type 'java.util.Vector'."

I have no idea of how to solve this and not able to find any solution.
Please help!

**Comment by lognaturel** [comment]
Thanks for posting your form on [the forum](https://forum.opendatakit.org/t/dynamic-selects-from-pre-loaded-data-gives-java-util-vector-error/8993/2)! That's the best place for support so please follow up there.
