### ISSUE TITLE
Replacing ListView with RecyclerView

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1254]
We know that in the [ListView](https://developer.android.com/reference/android/widget/ListView.html) to increase the performance we have to use the ViewHolder pattern. This is simply a java class that holds the references to the widget in the row layout of the ListView (for example TextView, ImageView and so on). Using this pattern we avoid to call several times findById method to get the UI widget reference making the ListView scrolling smoother. Even if this pattern was suggested as best-practice we could implement our Adapter without using this pattern.
[RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html) enforces this pattern making it the core of this UI widget and we have to use it in our Adapter.

**Pros:**
- integrated animations for adding, updating and removing items
- enforces the recycling of views by using the ViewHolder pattern
- supports both grids and lists
- supports vertical and horizontal scrolling
- can be used together with DiffUtil

**Cons:**
- no OnItemClickListener but this problem can be easily solved by using interface

[Reference](https://www.survivingwithandroid.com/2014/07/android-recyclerview.html)

**Comment by lognaturel** [comment]
I want to think a little strategically about this. Given that the biggest reason to switch to `RecyclerView` is performance, are there actually known performance issues with the current implementation?

Or is the reason to do this now more that it is necessary for the more prototype/experimental changes that you have planned for the remainder of your Google Summer of Code project?

**Comment by shobhitagarwal1612** [comment]
I know that no one has ever reported any performance issue related but it's something that exists when the number of items in the list gets too big. So as a good practice I wished to tackle it by replacing the list views with the better alternative, recycler view. When I had proposed that we should move to the form first approach, then it seemed to me that recycler view would be best for it. Switching to recycler view should not change anything visually but it can enhance the performance when the number of items in the list is too big

**Comment by srsudar** [comment]
Does `RecyclerView` perform better than `ListView` if there are a lot of items in a list? I didn't think it did. I thought the main difference in performance is just what you mention above, that it enforces the ViewHolder pattern.

Outside of potential performance gains, the big benefit of `RecyclerView` I think is that you get add/remove animations for free. This might be a good thing for the UI refresh, but it strikes me as a nice-to-have.

`ListView` and `RecyclerView` don't have complete API parity. `RecyclerView` does not have `setChoiceMode()`, for instance, which is called in several places in Collect. I know this can be worked around, but it won't be a straight drop in replacement.

My biggest worry is that I think that the code will have to stop relying on `ListFragment`. Am I wrong about that? That would be a big change. If this happens, I think including tests for whatever the replacement is would be the biggest gain.
