### ISSUE TITLE
Nested groups with `field-list` appearance

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1255]
Analyzing the firebase crash reports I found out that some users might try to use a form that contains a group with `field-list` appearance which contains another group. It's not allowed and I'm wondering if there is any particular reason why. 
Everything inside that group with  `field-list` appearance should be displayed on one page of course other groups as well even if they don't have `field-list` appearance.

What do you think?

**Comment by lognaturel** [comment]
This does indeed seem like a strange limitation. @grzesiek2010 do you remember where the limitation comes from? Is it in Collect or deeper in JavaRosa? This would be good to investigate further.

**Comment by grzesiek2010** [comment]
No, I can't recall I would need to debug the project.
