### ISSUE TITLE
App slows down when user has finished many forms and clicks on 'Save Form and Exit' when internet connection is turned on

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1257]
#### Software and hardware versions 
Android 6.0, Sony Z3
Collect - pr/1249 

#### Problem description
App slows down when user has finished a lot of forms and clicks on 'Save Form and Exit' when internet connection is turned on

#### Steps to reproduce the problem

1. User has *turned on internet connection*
2. User fills amny forms
3. User clicks on 'Save Form and Exit'
4. App slows down - User need to wait few seconds until user is moved to main view

#### Expected behavior
App does not slow down

#### Workaround
User disables internet connection

#### Other information 
App does not slow down if internet connection is disabled
Problem noticed during testing [Caused by android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1)](https://github.com/opendatakit/collect/pull/1249)

**Comment by grzesiek2010** [comment]
I'm on it but we need to merge https://github.com/opendatakit/collect/pull/1263 before
