### ISSUE TITLE
User should see progress dialog during deleting saved forms

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1258]
#### Software and hardware versions 
Android 6.0, Sony Z3

#### Problem description
Progress of delete forms is not visible
 
#### Steps to reproduce the problem
1. User has many saved forms (eg. 1000)
2. User wants to delete all saved forms 
3. User clicks on 'Select All' and then 'Delete Selected'
![screenshot_20170718-104714](https://user-images.githubusercontent.com/3907554/28311862-4ab810aa-6bb1-11e7-92f7-c08975707f44.png)
4. User is not informed about a progress in removing forms
- deleting about 1000 forms takes about *1m30s*
- additionally user can goes to other views - that can cause other problems

#### Expected behavior
User sees similar dialog to 'Sending Form'
![screenshot_20170718-104544](https://user-images.githubusercontent.com/3907554/28311697-c281fd54-6bb0-11e7-9f56-6fc8d090a54b.png)

#### Other information 
Noticed during testing [Caused by android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1) #1249](https://github.com/opendatakit/collect/pull/1249)

**Comment by dr0pdb** [comment]
Working on it!
