### ISSUE TITLE
SeekBar not visible on vertical range widget, Android 7.0

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1262]
#### Software and hardware versions 
Collect v1.8.1-30-g06adb7f3c, Android v7.0, Motorola G4

#### Problem description
The vertical range widget bar isn't visible. 
<img src="https://user-images.githubusercontent.com/967540/28342394-dab991a4-6bcc-11e7-8cc9-465e1c032f2f.png" width="200">

#### Steps to reproduce the problem
Use [this form](https://github.com/opendatakit/collect/files/1127308/range.txt). Both ticks and no-ticks appear without the line.

#### Expected behavior
The SeekBar should have a vertical line.

**Comment by grzesiek2010** [comment]
I'm not able to reproduce this issue it works well on our devices I also tried vd Android Api 24 and 25 and its ok.

**Comment by lognaturel** [comment]
I think Android 7.0 might be the worst. Unfortunately it's what the Moto G4 is stuck on and it's a fairly popular device. See #993 for another terrible example.

I guess we leave it for now unless someone else has an idea on how to address it.

**Comment by mmarciniak90** [comment]
@lognaturel @grzesiek2010 
I was able to reproduce this problem. 
Page reload is a condition of this bug, so you can go to other question and return to it or just change screen orientation.
This is visible only on Android 7.0. I also checked Android 4.1, 4.2, 4.4, 5.1, 6.0, 8.0

**Comment by grzesiek2010** [comment]
@lognaturel I'll take a quick look at it when I'm free. Probably it's an another Android bug like #1782

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
I'm now almost sure that it's an Android 7 bug. I have seen many issues similar to this one. I'm unclaiming this.

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot unclaim

**Comment by ArmenApresyan8** [comment]
Also you can reproduce this by going to background and coming back to app by recent apps button.

**Comment by lognaturel** [comment]
Awesome of you to look into it, @ArmenApresyan8! 

> Also you can reproduce this by going to background and coming back to app by recent apps button.

This is still with Android 7, right? If so, I will close and mark this as "Won't fix".

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

I like this issue, it's a challenging one !

**Comment by huangyz0918** [comment]
@opendatakit-bot Be patient, my boy, I’m waiting for the QAs 🏖🥂🌝

**Comment by lognaturel** [comment]
Hehe, I'm glad I'm not the only one who likes to have a little fun with our friend @opendatakit-bot! 😄
