### ISSUE TITLE
Sort on 'Fill Blank Form' view takes into account a case-sensitive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1264]
#### Software and hardware versions 
Collect v1.8.1
Noticed during testing [Sort menu redesign - Bottom Sheet Dialog](https://github.com/opendatakit/collect/pull/1242)
#### Problem description
Sort on 'Fill Blank Form' view takes into account a case-sensitive
![screenshot_2017-07-20-12-43-45](https://user-images.githubusercontent.com/3907554/28413804-39e5f5dc-6d49-11e7-8168-25c47c46daa1.png)

#### Steps to reproduce the problem
User opens 'Fill Blank Form' view
User sees list of form
Part of forms starts with a upper case letter and part lower case letter
User sees that sorting by name is not correct

#### Expected behavior
Forms are sorted alphabetically even if form names starts from lower case and upper case

**Comment by ngumbau** [comment]
@lognaturel Hi Hellen, I was wondering if I can get assigned this ticket.

**Comment by dsrees** [comment]
@opendatakit-bot claim
