### ISSUE TITLE
Dialogs with multiple possible actions look bad

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1265]
It's no longer very clear that save or ignore changes are clickable:
<img src="https://user-images.githubusercontent.com/967540/28394980-99ef1b4c-6ca5-11e7-984a-257f9154ee37.png" height=200> <img src="https://user-images.githubusercontent.com/967540/28394984-9d7b7fa8-6ca5-11e7-92f3-90f1103c548c.png" width=200>

I looked through the [material design guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-simple-dialogs) and would like to propose something like the following:
<img width="326" alt="screen shot 2017-07-19 at 5 32 59 pm" src="https://user-images.githubusercontent.com/967540/28395375-6acb4130-6ca8-11e7-9a99-e54a5b853d65.png">
Disclaimer, I am not a designer and certainly open to other ideas! The icons should probably be tinted with the accent color. @shobhitagarwal1612 it would be good to get your feedback.

From what I understand, material design would suggest automatically saving and not presenting this kind of dialog at all. This can certainly be reviewed at some point, but for now I think it would be best to make the dialog more usable and fit in with other dialogs that now roughly follow material design guidelines.

Note that the guidelines explicitly state that this kind of dialog should have no cancel button and that the user should just use the back button or tapping outside the dialog to dismiss it. The cancel button has been on that dialog for a long time, though, and I think it's better not to assume that users know those other ways of dismissing dialogs.

**Comment by shobhitagarwal1612** [comment]
Sorry for the late response. How about breaking this into two dialogs?

First one would be : 


```
Exit All Dialogs?

        No   Yes 
```


If user presses `Yes` then : 

```
Save changes?

      No   Yes
```

**Comment by yurilaguta** [comment]
IMHO two clicks will be more annoying.
When I'm exiting Writing a new email screen in (Gmail app) it's Saves it automatically as a draft. And shows Toast.

Calendar on the other hand shows:
![screenshot_20170817-193751](https://user-images.githubusercontent.com/1853043/29406252-d58b8dee-8383-11e7-8ef2-d7a68659f90a.png)
when I try to exist just create event.

Should we drop the icons? It looks much cleaner without them.

Maybe something like:
"Leaving All Widget form with unsaved changes?"
'Cancel'  'Discard' 'Save'

**Comment by lognaturel** [comment]
The double dialog does seem like it would be more disruptive so I'm not sure I like it very much.

@Yurii-Laguta when you say drop the icons, do you just mean leaving it as it is currently? Perhaps just making sure cancel is on the right and in uppercase and dropping the icon would make it look better. I wouldn't be opposed to doing just that.

The problem with three buttons side by side is that we do need to support small screens and multiple languages.

**Comment by yurilaguta** [comment]
@lognaturel I mean don't show any icons. On the second thought Action icons look good, but not the title.

I see the 3 button won't work.

How about Bottom sheet dialog? Similar to Google Photos app, it's nicely dismissible with swipe down or back button, will it be too much learning curve for user?
Another advantage it's close to the back button, so it's less disruptive than dialog in the centre.
![screenshot_20170818-201557](https://user-images.githubusercontent.com/1853043/29454992-b26fa758-8452-11e7-818d-60a23172874c.png)

**Comment by yurilaguta** [comment]
Started working on it.
[Off topic] is there a way to self assign issue?

**Comment by yurilaguta** [comment]
@lognaturel is that something you had in mind?:
<img width="317" alt="screenshot 2017-08-19 15 59 24" src="https://user-images.githubusercontent.com/1853043/29483957-89b41632-84f7-11e7-9c4e-c7763e3caefd.png">
To me this one looks better:
<img width="303" alt="screenshot 2017-08-19 16 31 56" src="https://user-images.githubusercontent.com/1853043/29484156-07dd397c-84fc-11e7-85f6-70206e8e1340.png">

**Comment by yurilaguta** [comment]
Here is version with bigger icons and smaller text
<img width="305" alt="screenshot 2017-08-19 16 44 55" src="https://user-images.githubusercontent.com/1853043/29484243-cb424712-84fd-11e7-9eb8-0a16ac6c513e.png">

**Comment by lognaturel** [comment]
@Yurii-Laguta unfortunately there isn't a way to self-assign issues yet but hopefully that will come very soon. See https://forum.opendatakit.org/t/fine-grained-permissions-for-github-issues-self-assign-labels/9352 for where we're at and please jump in if you have any other ideas!

I am intrigued by the bottom sheet idea and I hadn't noticed that interface before. I think the situation may be a little different. In the Google Photos, the bottom sheet shows up when a user taps the trashcan icon. The back button hides the bottom sheet when it's out. In the Collect case, the back button would trigger the bottom sheet. I suppose tapping the back button again would also hide the sheet / cancel. That seems like it could be a somewhat unexpected interaction.

@wonderchook, @hooverlunch you both have a good feel for what your respective users need. Do you have any opinions on this issue and proposed changes?

**Comment by smoyte** [comment]
This all looks good to me. :)

**Comment by yurilaguta** [comment]
@lognaturel very good point, I see now that bottom sheet is not suitable for this use case.
Please let me know if any changes required.

**Comment by lognaturel** [comment]
The form exit dialog has been updated. It would be good to reuse the same layout and look for the draw/signature/annotate widgets.

**Comment by shobhitagarwal1612** [comment]
Fixed in #1360

**Comment by lognaturel** [comment]
Let's keep open until the draw/signature/annotate menu uses the same look and feel!

**Comment by yurilaguta** [comment]
@lognaturel would you assign it to me and please point in direction of how
to get to draw/signature/annotane menus

On 4 Sep. 2017 7:26 am, "Hélène Martin" <notifications@github.com> wrote:

Let's keep open until the draw/signature/annotate menu uses the same look
and feel!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opendatakit/collect/issues/1265#issuecomment-326832279>,
or mute the thread

**Comment by lognaturel** [comment]
Awesome, thanks @Yurii-Laguta! Take a look at `createQuitDrawDialog()` in `DrawActivity`.

**Comment by yurilaguta** [comment]
@opendatakit-bot assignToMe

**Comment by lognaturel** [comment]
Our poor bot is not all that clever, @Yurii-Laguta. 😕 The only command it understands to assign issues is "claim" so you would type `opendatakit-bot claim`. You can check out the other commands it understands at https://github.com/opendatakit/zulipbot/blob/master/src/config.js

**Comment by yurilaguta** [comment]
thanks @lognaturel 
@opendatakit-bot claim
