### ISSUE TITLE
Read-only fields with text or numbers should not display an underline and should use black text

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1268]
The read-only modifier is typically used to echo back values. This has been confirmed by @yanokwa and by looking through actual forms.

A recent change made read-only fields with text look more like disabled fields. This is a good change in principle but doesn't match actual usage. @batkinson has confirmed that this causes problems on real forms because the font color is not high enough contrast to read.

I propose going back to how things were previously with any text displayed in a read-only widget being black and with no underline being shown. For `EditText`s, it's clear that they're not editable because of the lack of edit line. For widgets like the location widget, it's clear that they're not editable because the button is disabled.

**Comment by yanokwa** [comment]
I agree with this proposal.
