### ISSUE TITLE
Add support for likert appearance

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1272]
https://github.com/opendatakit/build/issues/173 is adding a likert appearance to select_one. Enketo has support for this, but Collect doesn't. Since most users of Build use Collect, we should probably add it.

We need to have a discussion about what this should look like because there isn't a lot of horizontal space on most devices.

**Comment by lognaturel** [comment]
https://blog.enketo.org/likert-widget/ shows how Enketo does this. The code is [here](https://github.com/enketo/enketo-core/blob/master/src/widget/select-likert/likertitem.scss).

I see two significant decision points: 
- how to wrap or truncate labels 
- how to determine padding (fixed, based on label size, based on screen size, etc)

It should support [image choices](https://docs.opendatakit.org/form-question-types/#select-widget-with-image-choices). The image size should probably be capped according to the device width.

I don't think think it should support [audio or video choices](https://docs.opendatakit.org/form-question-types/#including-image-video-or-audio-files-as-choices).

See also [range](https://docs.opendatakit.org/form-question-types/#range-widgets) and the [various select appearances](https://docs.opendatakit.org/form-question-types/#select-widgets).

**Comment by grzesiek2010** [comment]
[SurveyCTO](https://www.surveycto.com/releases/2-41-announcement/) added such an appearance
![image](https://user-images.githubusercontent.com/3276264/65311177-212ece80-db90-11e9-90c4-1494794f3152.png)

**Comment by lognaturel** [comment]
For those who may not be familiar with SurveyCTO, it's a product based around ODK tools. They've forked Collect and added various enhancements. Do you have a particular action to suggestion, @grzesiek2010, or are you showing a sample of what it could look like?

**Comment by grzesiek2010** [comment]
I just wanted to point out that they implemented something that looks pretty good I think. Maybe we could ask them whether they would like to contribute to ODK Collect adding this widget or at least sharing the code.

**Comment by lognaturel** [comment]
That makes sense! They're commercial and closed source and said a few years they weren't going to be part of the community anymore so I'm not sure it makes sense to go that direction. Their fork is at least 3 years old so I think it would be quite difficult to bring in their code, anyway.

**Comment by PieterBenjamin** [comment]
If the phone is not being held horizontally, do you think a vertical scale might work? i.e. having the "best" or highest agreement on the top, and "worst" or lowest agreement on the bottom of the screen. 

edit: this would probably look best for the discrete levels (likert/image labels) but I think the qualitative scale would probably look fine if it horizontally spanned a vertical screen. It doesn't seem like having a longer distance to scale would add a ton of value.

**Comment by lognaturel** [comment]
@PieterBenjamin my sense is that a likert scale is intended to always be horizontal. I think that it's ok to assume that users will either pick devices that are wide enough in portrait or train their staff to fill out surveys in landscape when using likert scales.

There is a user-facing thread at https://forum.opendatakit.org/t/support-for-likert-scales-in-build-and-collect/9127 where feedback could be solicited. It's fairly old so it's possible that those users have moved on but it's likely that others would jump in.

For now, only the discrete levels is needed. There isn't yet a form specification for the qualitative scale variant.

This is very similar to the existing `list` appearance on selects (see https://docs.opendatakit.org/form-question-types/#grouping-multiple-widgets-on-the-same-screen). The `likert` appearance should only be supported for select ones, should display labels below radio buttons and should display a line between radio buttons. Ideally I think there would be better label-wrapping rules. Currently with the `list` appearance and other related ones, labels immediately overlap with no attempt at wrapping. Those improved wrapping rules could be applied to the `list` appearance and other related ones. (Warning that this is starting to overlap with https://github.com/opendatakit/collect/issues/3300).

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Hi @akshay-ap! So nice to see you here! 😊 @PieterBenjamin and a group he's working with contacted me about this issue but I forgot to let them know they should claim it! I believe they've started on it but I'll let them confirm.

**Comment by PieterBenjamin** [comment]
@lognaturel @akshay-ap Sorry about that! we're actually in the middle of talking about it right now! We've been working our way through everything and didn't realize we had to claim the issue.  To confirm - yep! We're going to be working on this 👍

**Comment by akshay-ap** [comment]
Ohh! No problem. Will look into other issues then.
@opendatakit-bot unclaim

**Comment by PieterBenjamin** [comment]
@opendatakit-bot claim

**Comment by PieterBenjamin** [comment]
@akshay-ap Thanks! Sorry for the confusion.

**Comment by lognaturel** [comment]
From Slack:
> In the event the users provides insufficient images should it default to just the text? And in the event there isnt enough choices given by the user should the text be defaulted to something we set such as the default (agree, disagree, strongly agree and etc)?

This behavior should be identical to the select one behavior. It should be possible to set BOTH text and an image for each choice. If no image is specified, only the text should be included. If no text is specified, nothing should be displayed for that choice. That could be a deliberate design decision by the form designer -- they may want to specify images for the first and last choice, text for the middle choice and no label for the other choices, for example.

I don't think this behavior is documented at https://docs.opendatakit.org/form-question-types/#select-widgets or https://docs.opendatakit.org/form-question-types/#including-media-files-in-choices. Could you please file an issue if you're not finding it?

Note also that there can be translations for any text or media label: https://docs.opendatakit.org/form-language/ (that would be a good case to add an automated test for as well)

**Comment by andrewsiew2** [comment]
Hi @lognaturel , thanks for the reply. When you said the behavior in the last paragraph do you mean the select one behavior of allowing images and text at the same time? If so I can check it out and file an issue. Also, more edge cases, should the number of options always be 5 or should it strictly be based on the number of choices they provided? And let's say if we do want to keep it at 5 all the times, do we render what is given or not render anything and log or toast the error to indicate the wrong number of choices given. Also, should the user be able to set the size of the images? For now, I made a constraint on how large it can be but there may be cases where the image is more rectangular and the forced constraint may distort the image.

**Comment by lognaturel** [comment]
> When you said the behavior in the last paragraph do you mean the select one behavior of allowing images and text at the same time?

Whoops, I reorganized the paragraphs to hopefully make more sense. Yes, I mean what happens if you have both text and images. Now that I think about it, I'm not sure whether or not it's permitted to have a blank choice label so that might be something to try and make explicit.

> should the number of options always be 5 or should it strictly be based on the number of choices they provided?

It should be based on the number of provided choices. It's ok if certain choice counts don't work on narrow screens.

> should the user be able to set the size of the images?

No. I think this will need a bit of trying different options out. My instinct would be to cap the horizontal edge based on available space. That is, use the original image size unless the width goes beyond a certain fraction of the available screen in which case the whole image is scaled proportionately based on that horizontal edge cap.

**Comment by PieterBenjamin** [comment]
@opendatakit-bot unclaim

**Comment by PieterBenjamin** [comment]
@shouryaj all yours

**Comment by shouryaj** [comment]
@opendatakit-bot claim

**Comment by andrewsiew2** [comment]
Hi @lognaturel , 
We were talking about how the horizontal line should be and there are 2 designs in mind:
This one, which has the lines touching the buttons
![horizontal_1](https://user-images.githubusercontent.com/24306733/67525666-07d5e200-f668-11e9-85dc-594f8ac77450.JPG)

and this one which has the lines not touching the buttons. 
![horizontal_2](https://user-images.githubusercontent.com/24306733/67526018-c4c83e80-f668-11e9-82a2-3208f31e2d1f.JPG)

Also the color is going to be gray like below
![grayJPG](https://user-images.githubusercontent.com/24306733/67525667-086e7880-f668-11e9-9967-75fed6b5cc84.JPG)

Let me know which design you think might be better.

**Comment by lognaturel** [comment]
I'm in favor of the line touching the buttons.

**Comment by andrewsiew2** [comment]
@lognaturel I recalled you mentioned that we could make this widget collect data for data analysis. How do we do this? I was looking at another widget but there doesn't seem to be a distinct way to do this. Do we have to add something to another code at a higher level? Also, where should we put the docs for this widget?

**Comment by lognaturel** [comment]
> make this widget collect data for data analysis

I'm afraid I don't understand what you mean by this. Once the widget is implemented, any form could request a likert question by including a `select_one` question with the `likert` appearance. When a data collector selects a value, it will be saved as part of the form data, submitted to the server and be available for analysis like any other data collected with Collect.

> where should we put the docs for this widget?

I would suggest adding a new "likert widget" section after [this one](https://docs.opendatakit.org/form-question-types/#select-widget-with-image-choices)

**Comment by shouryaj** [comment]
@opendatakit-bot claim
