### ISSUE TITLE
Improve experience when opening app after old fork

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1278]
#### Software and hardware versions 
Collect v1.8.1

#### Problem description
After an old fork of Collect is installed, the databases may be in an unexpected state. The only way I can find to recover is to manually remove the affected databases.

#### Steps to reproduce the problem
1. Install the current version of Collect
1. Install an old fork of Collect such as [SecureDataKit](https://play.google.com/store/apps/details?id=com.securedatakit&hl=en)
1. Launch the old fork
1. Launch Collect
1. The app closes after showing a message like
<img src="https://user-images.githubusercontent.com/967540/28649050-fb68a966-7226-11e7-868b-674e96b3962b.png" width=300 />

#### Expected behavior
This should be a recoverable error. I believe that it is always safe to drop either the forms or the instances databases because they can be reconstructed from XML. Does that sound accurate? If so, perhaps Collect should simply do that on launch without alerting the user. 

Alternately, a dialog could be shown saying something like "The forms/instances database is in an unknown state, probably because an older version of Collect is also on this device. If you would like to use this version of Collect, the databases can be rebuilt from your forms. Would you like to use this version of Collect and rebuild the databases? YES NO" I don't really know how to phrase this one since people may not realize that other apps they use are Collect forks.

**Comment by grzesiek2010** [comment]
@lognaturel 
The problem doesn't exists on 1.10.2 looks like it has been fixed here https://github.com/opendatakit/collect/pull/1327/files because if I use a version without these changes I'm able to reproduce the issue.

So looks like we can close the issue.

**Comment by lognaturel** [comment]
🎉🎉
