### ISSUE TITLE
Crashes on start when it tries to getDeviceId 

### ISSUE THREAD

**Issue by ebensakyi** [getodk/collect#1285]
Neither user 10257 nor current process has android.permission.READ_PHONE_STATE

**Comment by lognaturel** [comment]
@ebensakyi Can you please try v1.9.0 which is now available from the Play Store? This crash should be fixed.

**Comment by lognaturel** [comment]
@ebensakyi If you see this in version 1.9.0 or greater, you can reopen the issue and let us know exactly what version you are using and what devices.
