### ISSUE TITLE
java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass

### ISSUE THREAD

**Issue by agoktas** [getodk/collect#1300]
Guy my apk works on my own phone but I attached it to Google Play Store.I installed app from store but it doesn't work.
When I check developer console I see this error.
Please help me what can I do?

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2819)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2988)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1631)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:380)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1086)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2809)`

**Comment by lognaturel** [comment]
Is it possible that there is more to the error? If so, it would be very helpful to get all of it since I don't think it's showing anything about ODK Collect specifically. Have you tried deleting the application and then installing it from the Play Store?

**Comment by agoktas** [comment]
The app that is on google play can not be deleted but I tried to update it.Although this,still I see same error.

**Comment by lognaturel** [comment]
I'm not seeing enough information here to troubleshoot, unfortunately. I'm also not finding the crash in our logs. @grzesiek2010 any ideas?

**Comment by lognaturel** [comment]
It's likely ProGuard/multidex related but I don't know how to narrow it down from there. Now that I think about it, I have seen crashes that could be related while looking through the Play Store logs.

One that I'm finding right away is [this one](https://play.google.com/apps/publish/?dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=2384&clusterName=apps/org.odk.collect.android/clusters/17abae71) (needs permissions):
```
java.lang.RuntimeException: 
  at android.app.LoadedApk.makeApplication (LoadedApk.java:516)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4514)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1381)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:5292)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:497)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:457)
  at android.app.Instrumentation.newApplication (Instrumentation.java:975)
  at android.app.LoadedApk.makeApplication (LoadedApk.java:511)
```

[This StackOverflow thread](https://stackoverflow.com/questions/15686593/java-lang-classnotfoundexception-in-dalvik-system-basedexclassloader-findclass) seems it could have some ideas but in my first read I don't see anything that we don't already do.

**Comment by srsudar** [comment]
Is that the complete exception? I'd expect there to be a name of a missing class, maybe obfuscated by proguard?

**Comment by lognaturel** [comment]
The one I posted is complete so that makes me think @agoktas's is as well. It's possible that the class name is obfuscated but seems strange that they wouldn't be in any other files. `-dontobfuscate` is specified in the config so I wouldn't expect any obfuscation to be occurring except perhaps in dependencies.

**Comment by lognaturel** [comment]
By some very strange coincidence, I ran into the stack trace I posted while working on a different project. In that context, I first installed the app by running the gradle run task through the Android Studio interface and everything was working fine. Then I built a debug apk and tried to install it from `adb install` and ended up with that stack trace. Uninstalling the app didn't help, neither did rebooting the phone. I ended up on [this StackOverflow question](https://stackoverflow.com/questions/36881299/java-lang-classnotfoundexception-after-android-studio-update) and tried some of the things suggested. It seems like cleaning and rebuilding did the trick.

I'm not sure this is related to @agoktas' problem but perhaps there are some ideas there.

**Comment by agoktas** [comment]
Lognaturel thanks for your suggestion.I will try it now.

**Comment by MackHuang** [comment]
Did you solve the problem now? If resolved, can tell how to solve?

**Comment by MackHuang** [comment]
Have you solved the problem now? If solved, can tell me how to solve?

**Comment by lognaturel** [comment]
What out of the suggestions above have you tried, @MackHuang?

**Comment by agoktas** [comment]
Thank you ı solved



Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: MackHuang <notifications@github.com>
Tarih: 10.10.2017 06:03 (GMT+03:00)
Alıcı: opendatakit/collect <collect@noreply.github.com>
Cc: agoktas <ali_goktas_34@hotmail.com>, Mention <mention@noreply.github.com>
Konu: Re: [opendatakit/collect] java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass (#1300)


Did you solve the problem now? If resolved, can tell how to solve?

**Comment by agoktas** [comment]
Yes I solved.Thanks for your attention :)



Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: MackHuang <notifications@github.com>
Tarih: 10.10.2017 06:05 (GMT+03:00)
Alıcı: opendatakit/collect <collect@noreply.github.com>
Cc: agoktas <ali_goktas_34@hotmail.com>, Mention <mention@noreply.github.com>
Konu: Re: [opendatakit/collect] java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass (#1300)


Have you solved the problem now? If solved, can tell me how to solve?

**Comment by agoktas** [comment]
Yes I solved.Thanks for your attention :)



Samsung Galaxy akıllı telefonumdan gönderildi.

Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: Hélène Martin <notifications@github.com>
Tarih: 10.10.2017 06:44 (GMT+03:00)
Alıcı: opendatakit/collect <collect@noreply.github.com>
Cc: agoktas <ali_goktas_34@hotmail.com>, Mention <mention@noreply.github.com>
Konu: Re: [opendatakit/collect] java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass (#1300)


What out of the suggestions above have you tried, @MackHuang<https://github.com/mackhuang>?

**Comment by Chintuz** [comment]
HI, Can you please help in resolving the same issue. I am facing it in playstore build.

Any suggestion, I have already implemented multidex in the app, this issue is reflected many times.

Please help!

Thanks

**Comment by lognaturel** [comment]
@Chintuz Do you mean you see this error when you run ODK Collect from https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=en_US? If not, then it's not a Collect issue and you can try posting on Stackoverflow or another general dev forum!

**Comment by HalyangDream** [comment]
> HI, Can you please help in resolving the same issue. I am facing it in playstore build.
> 
> Any suggestion, I have already implemented multidex in the app, this issue is reflected many times.
> 
> Please help!
> 
> Thanks

请问解决这个问题了吗？我们的应用在google play console 上也是被这个问题困扰？

**Comment by MackHuang** [comment]
> 你在上面的建议中尝试过什么，@MackHuang？

Yes   I solved it   Thank you for your attention.

**Comment by MackHuang** [comment]
> 你在上面的建议中尝试过什么，@MackHuang？

Yes, I solved it. Thank you for your attention.

**Comment by MackHuang** [comment]
在app的build.gradld的defaultConfig中：multiDexEnabled
dependencies中添加：compile 'com.android.support:multidex:1.0.0'

试下是否有用呢？

在 2018-09-29 16:59:41，"HalyangDream" <notifications@github.com> 写道：


HI, Can you please help in resolving the same issue. I am facing it in playstore build.

Any suggestion, I have already implemented multidex in the app, this issue is reflected many times.

Please help!

Thanks

请问解决这个问题了吗？我们的应用在google play console 上也是被这个问题困扰？
