### ISSUE TITLE
Inbuilt barcode scanner

### ISSUE THREAD

**Issue by kusaasira** [getodk/collect#1304]
#### Software and hardware versions 
Collect v1.8.0, Android any device used

#### Problem description
In the previous versions i.e. <1.5, there was an external barcode scanner that worked far much better than the inbuilt one reason being it also had automatic lighting which helped my team a lot in the field since we scan devices that are indoors in remote areas where in most cases there isn't enough light or no light at all. But for the inbuilt barcode scanner, it doesnot help with this which is a big setback.

#### Expected behavior
- The barcode inbuilt scanner to turn on the flashlight when it detects there is no enough light.

**Comment by shobhitagarwal1612** [comment]
Hey @kusaasira 
I would like to solve your problem by adding a button for turning `on`/`off` the flashing manually or `auto` mode.

@lognaturel @yanokwa @kusaasira What do you think?

**Edited**
I created a [ScannerWithFlashlightActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/ScannerWithFlashlightActivity.java) for scanning QRCode in Admin Settings. Same can be used here as well. It has a button for toggling the flashlight manually.

**Comment by kusaasira** [comment]
Hey @shobhitagarwal1612 

That will be the best and great idea. I support you on this.

**Comment by shobhitagarwal1612** [comment]
I created a [ScannerWithFlashlightActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/ScannerWithFlashlightActivity.java) for scanning QRCode in Admin Settings. Same can be used here as well.

**Comment by lognaturel** [comment]
Thanks for reporting this issue, @kusaasira. Before we make the change, can you please try the QRCode scanner in admin settings and let us know whether that works as you expect? You can find it in Admin Settings > Import/Export settings > Scan code from other device. If that looks good then going with as similar approach as @shobhitagarwal1612 suggests will work well and we can plan on getting that in the next release.

**Comment by lognaturel** [comment]
@kusaasira Have you had a chance to try out the flashlight option with the bulk configuration QR code?

**Comment by lognaturel** [comment]
It's too bad that we haven't received feedback from @kusaasira but I think @shobhitagarwal1612's suggestion is a solid one. @shobhitagarwal1612 is finishing up summer of code, @grzesiek2010 could you take this one?

**Comment by kusaasira** [comment]
Dear all,

Am so sorry for being away. Been on and off. So on the other hand, I upgraded from Eclipse to the latest Android studio but am really having a hell running the code. Let me get you feedback in a few hours as am configuring it an d on the other hand, is anyone else here using Android Studio or it is just my problem?

**Comment by shobhitagarwal1612** [comment]
Hello @kusaasira 
You can try out the latest version of Collect from the play store for checking out the QRCode scanner which @lognaturel suggested  https://github.com/opendatakit/collect/issues/1304#issuecomment-320035045

> is anyone else here using Android Studio or it is just my problem

I think everyone is using Android studio now. What kind of problem are you facing? Can you please describe it in detail.

**Comment by kusaasira** [comment]
@shobhitagarwal1612 , I think you meant the flash light on the QR scanner yet I meant the un built barcode scanner for a field that has type='barcode' that is the inbuilt barcode that replaced Zxing barcode scanner. Remember Zxing had that either manual turn on flashlight or auto turn on barcode. 

My android studio is now working fine, was just issues with gradle but I think all is well now. So is my issue in the new update on google playstore or here?

@lognaturel , the QR scanner works as good as I wish it could for the barcode scanner field.

**Comment by lognaturel** [comment]
Thanks for the feedback, @kusaasira and for the implementation, @shobhitagarwal1612!

@kusaasira If you want to check out what @shobhitagarwal1612 has done, it is here: https://github.com/opendatakit/collect/pull/1383. I just had one small question about the implementation and it should be shipped to the Play Store by this coming Sunday or Monday.

@kusaasira If you have any other questions about your development environment, consider joining us in the developer chat at http://slack.opendatakit.org!

**Comment by kusaasira** [comment]
@lognaturel you're welcome. I'll be glad once it is out on Play Store. Thank you @shobhitagarwal1612  for the work.

Thank you for the great work.

On the other hand, this [link ](https://slack.opendatakit.org/)provided above seems not to be working. Do I need special access to it?

**Comment by shobhitagarwal1612** [comment]
Please try this one:
https://opendatakit.slack.com

**Comment by kusaasira** [comment]
@shobhitagarwal1612 please invite me to join as I cannot join the team. My email is joshuakusaasira@gmail.com

**Comment by shobhitagarwal1612** [comment]
Invitation link sent!

**Comment by kusaasira** [comment]
Thank you.

**Comment by lognaturel** [comment]
Whoops, sorry, it's http, not https. Glad you could join us through an invite!
