### ISSUE TITLE
Time zone is not updated automatically 

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1309]
#### Problem description
Time zone is not updated automatically if we change our timezone and open the app again.

#### Steps to reproduce the problem
1. Minimize ODK Collect
2. Change your time zone in settings
3. Open ODK Collect again
4. Open TimeWidget

#### Expected behavior
The default date displayed by picker should be the same as device time.

#### Actual behavior
look at device time and at the picker.
![screenshot_2017-09-05-14-48-39](https://user-images.githubusercontent.com/3276264/28969293-4ea8198c-7924-11e7-894f-84ae483f37c1.png)

#### Other information 
Discovered during investigation of #170 

Probably if the app is killed when you minimize it then it's updated and everything works well but if your device has enough memory and the app is not killed the problem occur.

**Comment by dr0pdb** [comment]
@lognaturel @yanokwa Is this issue still up for grabs ?

**Comment by yurilaguta** [comment]
Most likely the issue is Android Manifest declaration like:
android:configChanges="locale|orientation|screenSize"

**Comment by grzesiek2010** [comment]
@mmarciniak90 Since you [confirmed](https://github.com/opendatakit/javarosa/pull/189#issuecomment-334143097) everything s ok on current master branch please check if I'm right that the issue has been fixed by https://github.com/opendatakit/collect/pull/1492. Then we can close it.

@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
Tested with success.
I verified app which was created without changes from #1492 and with that changes.
I confirm that this problem is not visible. 
Time picker works as expected.
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
Ok thanks.
