### ISSUE TITLE
Rename 'Type' to 'Server' in Admin Settings > User Settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1311]
The top-level item for defining a server used to be "type" (as in server type) but now it is "server". It looks like the admin settings were not updated to match.

**Comment by deepak-thakur** [comment]
how can i help ?

**Comment by shobhitagarwal1612** [comment]
Hello @deepak-thakur. The access control preference `Type` has to be renamed to `Server`.
You can find it in `Admin Settings` > `User Settings`

Thanks :)

**Comment by dr0pdb** [comment]
@deepak-thakur Actually i am working on it too. Infact i will push my PR shortly. I mentioned it on the slack channel but forgot to drop a comment here. You can find another issue to resolve.
Thanks :smile:
