### ISSUE TITLE
ODKSQLiteOpenHelper - why do we need this class?

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1334]
#### Problem description
Currently we use custom [ODKSQLiteOpenHelper](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/ODKSQLiteOpenHelper.java) instead of Android's SQLiteOpenHelper. It would be good to know why as our class might be faulty (as we can see in this case https://github.com/opendatakit/collect/issues/1325)

**Comment by lognaturel** [comment]
I don't think we're going to be able to get a historical reason, unfortunately! It may just be that it wasn't in the Android project at the class was introduced. I think we should use the Android base class and update the subclasses as needed to get the ODK-specific behavior.

**Comment by grzesiek2010** [comment]
Ok I'll do that.
