### ISSUE TITLE
Removing the first group caused that the user is moved to previous screen

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1349]
#### Problem description
Removing the first group caused that the user is moved to previous screen

#### Steps to reproduce the problem
1. User fills the form with repeat groups / table
2. User removes first group
3. User is moved to previous screen

#### Expected behavior
If user sees the group as a table, moving user to previous screen when he removes first row is not necessary. User should stay on tabular view and first row should be deleted.

#### Other information 
Problem comes from project where tabular view was implemented

**Comment by grzesiek2010** [comment]
@mmarciniak90 ODK Collect doesn't support tabular view for repeats. Could you confirm the problem exists because I tried a form with repeat group and with "field-list" too and I wasn't able to notice described behavior.

**Comment by mmarciniak90** [comment]
@grzesiek2010 I investigated this problem and checked older ODK version.
This problem was visible until version 1.4.12.
"Add New Group?" dialog appears from the version 1.4.13 released on January 23, 2017
Dialog completely disappears and it works as expected in version 1.7.0 release on May 31, 2017

Problem is no longer valid.

**Comment by grzesiek2010** [comment]
Great!
