### ISSUE TITLE
When auto-send is set to wifi only, forms still auto sent on a data connection

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1355]
From a Play Store review:

> Very frustrating when you go back to page to edit, all options are auto selected. It keeps using the auto form upload even when you opt for uploading when connected to Wi-Fi only

@grzesiek2010 could you please see if you can reproduce it and if so look into a fix?

**Comment by grzesiek2010** [comment]
@lognaturel I have tried but I can't reproduce this issue... It works well to me.

> when you go back to page to edit, all options are auto selected

Do you know what that means? which page, which options? Maybe it is a key to reproduce the issue.

**Comment by lognaturel** [comment]
I don't currently have an Android phone with a working SIM so this one is hard for me to try! Can you please describe what exactly you tried so we have a record of it? I interpreted it as when selecting Wi-Fi only from the auto send section of the general settings, forms are auto sent on a data connection but I'm not totally sure.

Any chance this could be device or Android version specific? The report was from Android 6.0.

**Comment by grzesiek2010** [comment]
@lognaturel I've tested two scenarios:
1st scenario:
1. Select "Wifi only" option as your Auto Send option
2. Turn off your wifi
3. Finalize one of your form

2nd scenario:
1. Select "Wifi only" option as your Auto Send option
2. Keep your wifi turned on but close all connections
3. Finalize one of your form

In both cases I was connected to a cellular network of course as well.

Can't reproduce using Sony Xperia Z3 D6603 Android 6.0.1 too.

**Comment by lognaturel** [comment]
And for absolute completeness, the form did not send in either situation is that correct?

Once I get your confirmation I'll close this and hopefully the user will come here and add details eventually. I also encouraged them to join the forum.

**Comment by grzesiek2010** [comment]
@lognaturel 

> And for absolute completeness, the form did not send in either situation is that correct?

Yes, the form did not send, everything works as expected.
