### ISSUE TITLE
Caused by java.lang.IllegalArgumentException: Unterminated quote

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1366]
#### Software and hardware versions 
Collect v1.9.0

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/8ba2a500?duration=2592000000&appVersions=2397

> java.text.SimpleDateFormat.validatePattern (SimpleDateFormat.java:307)
java.text.SimpleDateFormat.<init> (SimpleDateFormat.java:356)
org.odk.collect.android.provider.InstanceProvider.getDisplaySubtext (InstanceProvider.java:243)
org.odk.collect.android.provider.InstanceProvider.insert (InstanceProvider.java:216)
android.content.ContentProvider$Transport.insert (ContentProvider.java:220)
android.content.ContentResolver.insert (ContentResolver.java:1195)
org.odk.collect.android.tasks.InstanceSyncTask.doInBackground (InstanceSyncTask.java:168)
org.odk.collect.android.tasks.InstanceSyncTask.doInBackground (InstanceSyncTask.java:49)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)

It's related to Hindi language (double quote at the end): https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/values-hi/strings.xml#L173

**Comment by grzesiek2010** [comment]
I've just fixed this bug in Transifex https://www.transifex.com/opendatakit/collect/translate/#hi/strings/8478346 
@shobhitagarwal1612 I saw you are a coordinator there don't know if you have to accept it. Please review me change and accept if it's needed.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010  Looks good to me. I have reviewed the change.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 great, thanks!

**Comment by lognaturel** [comment]
Thank you both!
