### ISSUE TITLE
"Not supported by calendar-mode DatePicker" Bug

### ISSUE THREAD

**Issue by russbiggs** [getodk/collect#1367]
#### Software and hardware versions 
Collect v1.9.1, Android v7.0.0 Samsung Galaxy S2 SMT713
Collect v1.9.1, Android v7.0.0 Samsung Galaxy S2 SMT710

#### Problem description
I am experiencing the same "Not supported by calendar-mode DatePicker" bug described in the now closed issue [#991](https://github.com/opendatakit/collect/issues/991). I am seeing this issue only on SMT713 Galaxy S2s when using the datetime data type and no value in the  appearance field.  I do not experience this issue on my SMT710 which is a very similar model. Adding the "no-calendar" appearance fixes the issue, but it seems like that shouldn't be necessary for all forms. The issue only appeared when upgrading to Android 7.0

![image001](https://user-images.githubusercontent.com/8487728/29574860-09abed2c-8720-11e7-8971-8ea3c815c6c9.png)

#### Steps to reproduce the problem
I've included an example xml of a form that causes the issue
[datetime_test.txt](https://github.com/opendatakit/collect/files/1242592/datetime_test.txt)

#### Expected behavior
Date widget should pop up without needed a specified appearance value.

#### Other information 
 Adding the "no-calendar" appearance fixes the issue.

**Comment by lognaturel** [comment]
This sounds like it's an Android bug that we probably can't do anything about. We were able to find a work around for the particular instance in #991 but I don't see anything else we could try. My guess is that Samsung patched the version of Android for one device but not the other. I have a Moto G4 running Android 7.0 and I have to say it is terribly buggy. If you have any way of going to either 7.1 or back to 6, I would highly recommend it.

@grzesiek2010 Do you happen to have any ideas?

**Comment by grzesiek2010** [comment]
@russbiggs Could you install [this app](https://play.google.com/store/apps/details?id=com.splendapps.splendo&hl=en) on those devices? Looks like this app displays a calendar in the same way so if it doesn't work too then it must be a problem with those specific devices.

You need to install the app I mentioned, then open it, click on a big `+` icon and try to set date.

**Comment by russbiggs** [comment]
@grzesiek2010 I just installed the To-Do app and it seems to handle the calendar and time widgets correctly.

**Comment by grzesiek2010** [comment]
@russbiggs and you can see this?
![screenshot_2017-08-29-17-09-30](https://user-images.githubusercontent.com/3276264/29828437-fa484ffc-8cdc-11e7-8138-8a2f49247dd4.png)

**Comment by russbiggs** [comment]
@grzesiek2010 Yeah thats the widget that popped up in the To-Do app.  Thats also the widget I can see on the SMT710 for ODK.

**Comment by grzesiek2010** [comment]
@russbiggs thanks. That means it's a bug on our side. I'll try to investigate it.

**Comment by russbiggs** [comment]
@grzesiek2010 Great thanks, let me know if there is anything I can do to help.

**Comment by grzesiek2010** [comment]
@russbiggs does TImeWidget work well on your device? I mean TimeWidget in Collect app of course.

**Comment by russbiggs** [comment]
@grzesiek2010 Yes, we we use time and not datetime the TimeWidget is able to come up without issue

**Comment by grzesiek2010** [comment]
@russbiggs thanks for your help. As you probably imagine it's hard to track down I don't have such devices so I'm not able to reproduce the issue and debug the app.
Soo I'm wondering if you could install this app: [app.zip](https://github.com/opendatakit/collect/files/1264225/app.zip)
I prepared it special for you to create some logs.

and use this form [date.txt](https://github.com/opendatakit/collect/files/1264226/date.txt)
If you install this app and open the attached form please select any date and finish the form (by clicking on "Save Form and Exit" button). After that a special file should be created in odk folder on your device it should be odk/logs.txt.

Please send me this super small file.

**Comment by russbiggs** [comment]
@grzesiek2010 here it is:
[logs.txt](https://github.com/opendatakit/collect/files/1264466/logs.txt)

**Comment by grzesiek2010** [comment]
@russbiggs thanks!

My first idea is to check out different themes for this dialog. I prepared an app and a form for you. Could you test it? 
[app.zip](https://github.com/opendatakit/collect/files/1266541/app.zip)


Please install that app and use attached form. That form contains four date questions and each uses different theme. Could you check if maybe any of these displays properly?

**Comment by russbiggs** [comment]
@grzesiek2010  All four work.  The final one date4 doesn't appear as a popup but takes of the whole screen.

**Comment by grzesiek2010** [comment]
@russbiggs great to hear that. That means we are really close to fix this issue.
