### ISSUE TITLE
App crashes when I try to set my server type

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1368]
#### Software and hardware versions 
Current master branch

#### Problem description
App crashes  when I try to set my server type to `Google Drive, Google Sheets`

#### Steps to reproduce the problem
1. Go to `General Settings -> Server`
2. Click on `Type`
3. Select `Google Drive, Google Sheets`

I'm not sure but probably you need a fresh installation of the app to reproduce the issue.

#### Other information 
The problem has been added in https://github.com/opendatakit/collect/pull/1293/files#diff-58e7d71de50e629a828406faaa502de5

**Comment by lognaturel** [comment]
@grzesiek2010 You have become the master at catching big issues before they affect users! Wow!
