### ISSUE TITLE
Can't take image/draw/signature

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1380]
#### Software and hardware versions 
Current master branch

#### Problem description
We can't take image/draw/signature because of https://github.com/opendatakit/collect/pull/1365/files
We missed the fact that the intent value is empty in those cases what is described here:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L674

**Comment by lognaturel** [comment]
Ooops! I totally didn't think of this at all. Good catch and yes, we miss you a lot @mmarciniak90!
