### ISSUE TITLE
Add account in settings, not just at form upload

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/collect#1386]
#### Software version
Collect v1.91

#### Problem description

In **General Settings -> Server -> Google Sheets settings**, you can select an existing Google account, or *no account*.

In **Get Blank Forms** you can select an existing Google account, or *Add Account*.

I imagine it would make more sense to be able to add an account in the Server settings screen.

**Comment by mkmar01** [comment]
@lognaturel I would like to work on this issue

**Comment by lognaturel** [comment]
Thanks, that sounds great, @batbrain7!

**Comment by lognaturel** [comment]
@batbrain7 If you would still like to work on this one, please comment with `opendatakit-bot claim` so that you can be assigned to it.

**Comment by mkmar01** [comment]
@opendatakit-bot @lognaturel 
I got busy with my university exams , now I can get back to the issue and would still like to work on it

**Comment by icemc** [comment]
@batbrain7  are you still working on this issue?

**Comment by akshay-ap** [comment]
@opendatakit-bot claim.
@lognaturel builds are failing for `./gradlew connectedCheck -Pandroid.useDexArchive=false`. What might be the issue?

**Comment by lognaturel** [comment]
@akshay-ap Looks like you saw the Slack discussion about the tests and were able to get the latest master and get your build passing. 👍
