### ISSUE TITLE
FormEntryActivity Refactor - 'currentView' access is dangerously inconsistent.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1389]
There are 20 different places where the cast ((ODKView) currentView) occurs in FormEntryActivity. Some of these have an instanceof check before, some have a null check before, some have both, and some have neither. 

This variable is only ever set to the result of createView. There are paths through createView that return non ODKView objects and null.

I propose hiding the currentView access behind an `@Nullable` getter, checking for the correct type, and returning null if the currentView is not ODKView.  At the call site, we can replace the direct attribute access with null check calls to this method.

**Comment by grzesiek2010** [comment]
I agree we should refactor this part of code and btw it would be greate if we can change that name...
`ODKView` why? Does it sound strange to anyone else? Maybe `SurveyView` or `FormView`?

**Comment by lognaturel** [comment]
@jknightco the proposed change sounds great.

@grzesiek2010 I'm not necessarily opposed to that but I think it's a separate question!

**Comment by icemc** [comment]
Hello @grzesiek2010 @lognaturel I will like to look into this issue.

**Comment by lognaturel** [comment]
Fantastic, thanks @icemc! For issues that don't need discussion you can simply comment `opendatakit-bot claim` and it will be yours. 😊

**Comment by icemc** [comment]
opendatakit-bot claim

**Comment by lognaturel** [comment]
Ahhh, I'm sorry. You need the `@` in front of the bot name to get its attention.

**Comment by icemc** [comment]
yeah forgot about that too

**Comment by icemc** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thank you Mr. @opendatakit-bot. 🤣🤣
