### ISSUE TITLE
Change text on Form Import setting

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/collect#1397]
General Settings -> Form Management -> Import saved forms as finalized

The combination label and hint text makes this setting unclear.

I propose:

Label: Finalize forms on import
Hint: Affects forms added directly to /instances/ folder.

**Comment by konishon** [comment]
@lognaturel Can I claim the issue ?

**Comment by icemc** [comment]
@nishontan comment @opendatakit-bot claim. To claim this issue

**Comment by lognaturel** [comment]
Yes, please go ahead @nishontan! And @icemc is right, if you comment with `@opendatakit-bot claim`, you'll own the issue.

**Comment by konishon** [comment]
@opendatakit-bot claim
