### ISSUE TITLE
Add FAQ or Guide feature in Collect app.

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1398]
#### Software and hardware versions 
Collect v1.9.1, Android v4.4.2.

#### Problem description
I think there should be direct link to FAQ section in Collect app so that they are accessible easily. Currently what I felt is accessing FAQ section https://opendatakit.org/help/faq/ can be quite difficult as android user might not be aware of its existence. So my suggestion is to include an FAQActivity where all questions from https://opendatakit.org/help/faq/ can be seen through app easily.

The FAQ or Guide section should look something like this :  https://github.com/Manabu-GT/ExpandableTextView as it will lead to better user experience.

(I prefer not to directly load https://opendatakit.org/help/faq in android app using webView or chrome custom tab.)

#### Expected behavior
An option to view "FAQ" or "Guide" in "About" section.
On clicking this option, an activity will be started where user can view FAQ or Guide.
#### Other information 
Suggestions to implement : There should be some facility to receive FAQ or Guide in JSON format which will be rendered to UI in Collect Android Application.

**Comment by akshay-ap** [comment]
[](url)

**Comment by adammichaelwood** [comment]
The documentation can be built and served in a variety of useful formats for consumption by the app:

http://www.sphinx-doc.org/en/stable/builders.html

**Comment by adammichaelwood** [comment]
This might be a feature for a second issue, but:

It would be great if the help docs inside the app linked directly to relevant things in the  app. So, for example, if it talks about *General Settings*, you can click that and it will take you straight there.

This would require a custom Sphinx role that emits in-app links when run through whichever builder is used, and the doc writer(s) would need some relatively easy way to know how to specify the in-app targets.

**Comment by adammichaelwood** [comment]
From akshay, via slack:

> How do u propose to use Sphinx for getting JSON of FAQ

- Fork and clone down the [docs repo](https://github.com/opendatakit/docs)
- Run the build with the json builder: `sphinx-build -b json . json`
- Look at the output in `/json/` and see what it looks like -- how usable it is for consumption by the app
- Coordinate with @yanokwa to add the json builder to the circleci deployment and host it somewhere like `json.docs.opendatakit.org` (or wherever)

**Comment by adammichaelwood** [comment]
Also - you might not be aware but the FAQ at https://opendatakit.org/help/faq/ will be deprecated and removed in the near future. Docs are at:
http://docs.opendatakit.org/

There's currently an [open PR for a collect guide](https://github.com/opendatakit/docs/pull/111) in [the docs repo](https://github.com/opendatakit/docs). That will be expanded. 
Anyway, it would be convenient, I think, for the entire documentation to be sucked into the app.

**Comment by adammichaelwood** [comment]
I suggest this issue be re-titled to:
"Add Documentation in Collect App"

**Comment by muarachmann** [comment]
@yanokwa , @lognaturel , @grzesiek2010 i might have a good idea for FAQs. I am ok with the fact for making it a separate section on its on. I propose an expandable layer with header and body. I have built something similar before and i think it will enhance the UI of the app too. 

- The header can briefly describe what the faq is all about e.g How to create a form 
- The body will contain explanations on how to do that. 

- On launch of this section, a default tab would be open , and on click on any other sections, the currently open tab will give way for the newly clicked open tab to display its content. Some sort of accordion.

- I am willing to work on this if given the go ahead :)
- I did something similar in one of my apps for comics for the faq section. See the image below of what i mean

![expandable](https://user-images.githubusercontent.com/16350814/51444213-54654900-1cf5-11e9-86b1-a5f2c1507b6e.png)

**Comment by muarachmann** [comment]
Of course the theming will follow suite ODK's theme

**Comment by yanokwa** [comment]
We've had FAQs on the website and removed them because they fall out of date quickly. I'm open to the idea of a tutorial or guide of some sort, but that's a conversation that should happen at https://forum.opendatakit.org/c/features. 

Given all that, I think we should close this issue because it's not actionable. What do you think, @grzesiek2010 @shobhitagarwal1612?

**Comment by shobhitagarwal1612** [comment]
I agree with @yanokwa. This issue should be discussed in the forum first

**Comment by muarachmann** [comment]
ok @shobhitagarwal1612 , thanks for your reply

**Comment by grzesiek2010** [comment]
I agree so I'm closing it.
