### ISSUE TITLE
Use JavaRosa's ReferenceManager.instance() instead of _()

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1405]
The current use of JavaRosa's `ReferenceManager._()` results in the following warning: "use of '_' as an identifier might not be supported in releases after Java SE 8".

As of JavaRosa 2.5.0, `_()` has been renamed to `instance()` (see [release notes](https://github.com/opendatakit/javarosa/releases/tag/v2.5.0)). `_()` is still provided for backwards compatibility but it would be good to start using `instance()`.

This change should be done with IDE help to make sure no manual errors are introduced. The pull request description should describe how this was done and how it was verified that no more warnings remain.

**Comment by shobhitagarwal1612** [comment]
This has been already added in PR #1396

**Comment by lognaturel** [comment]
Thanks, @shobhitagarwal1612!

**Comment by shobhitagarwal1612** [comment]
@lognaturel please remove the in progress label as PR #1396 has been closed without merging
