### ISSUE TITLE
Refactor: QuestionWidgets should call saveAnswer() on the corresponding form when updated.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1421]
This is an intermediate step in preparation for #378.

Calling `saveAnswer` causes JavaRosa to reevaluate related forms' relevancy, spitting out `CHANGE_RELEVANT` events to any Observers registered with `registerStateObservers`. Watching for these events will allow us to update dependent fields within fieldlists.

**Comment by heyjamesknight** [comment]
The QuestionWidget base class should also be aware of whether or not the Widget belongs to a fieldlist, and whether or not save needs to be called immediately or when the Widget goes off screen (the current behavior).

**Comment by seadowg** [comment]
Closing this, as it looks like the issue that it's in service of has already been closed.
