### ISSUE TITLE
Refactor: QuestionWidget needs unified means for getting/setting Answers.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1422]
This is an intermediate step in preparation for #378, and must be completed before #1421. 

In order to ensure setAnswer is called whenever a field is updated, QuestionWidget needs to be modified to provide a unified way for subclasses to set updated answers. Individual subclasses will be responsible for determining when it is appropriate to update the underlying Answer.

The QuestionWidget base class should also be made aware of whether or not the Widget is a member of a FieldList, and whether or not we need to save the new Answer to the underlying form, or wait until the Widget goes off screen (the current behavior).

**Comment by seadowg** [comment]
Closing this, as it looks like the issue that it's in service of has already been closed.
