### ISSUE TITLE
Refactor: QuestionWidget subclasses should be refactored and repeated code should be moved into new abstract classes based on shared functionality.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1423]
This is an intermediate step in preparation for #378, and must be completed before #1422.

Currently, the IBinaryWidget implementations have a lot of redundant code. By refactoring the interface into an abstract class and handling answer setting/getting in a unified fashion, we can prepare all of them for #1422.

**Comment by heyjamesknight** [comment]
After looking at the IBinaryWidget implementations, it looks like there's 3 or 4 archetypes within the 12 or so implementations. I believe we should pull the shared components out and move as much into these new intermediate abstract classes as possible to make the changes needed by #1422 easier.

**Comment by seadowg** [comment]
This is actually happening! @SaumiaSinghal has started the charge here and as slowly move towards the new ["framework"](https://github.com/getodk/collect/blob/master/docs/WIDGETS.md) for widgets we should see more improvements. I'm closing this as the goal is tracked in [STATE.md](https://github.com/getodk/collect/blob/master/docs/STATE.md).
