### ISSUE TITLE
Filter on single select and multi select question is cleared  if user changes device orientation OR minimizes app OR locks and unlocks screen

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1427]
#### Software and hardware versions 
Issue discovered during testing #1415

#### Problem description
Filter on single select and multi select question is cleared when device orientation is changed, app is minimized and when user locks and unlocks the screen 

#### Steps to reproduce the problem
1. User starts job with single select question and multi select question with appearance="autocomplete" -> [select.txt](https://github.com/opendatakit/collect/files/1284588/select.txt)
2. User is on single select question and user adds some filter
3. User changes device orientation OR minimizes app OR locks and unlocks screen
4. Filter is cleared

#### Expected behavior
- Filter is not cleared even if user changes device orientation OR minimizes app OR locks and unlocks screen
- Filter is cleared only when user clears it manually

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
