### ISSUE TITLE
Remove unused method from ZipUtils

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1434]
[ZipUtils](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ZipUtils.java) contains an unused method [extractFirstZipEntry](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ZipUtils.java#L59). Also, `Timber.w` can be replaced by `Timber.i` at some places in this file (line [85 ](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ZipUtils.java#L85) and [103](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ZipUtils.java#L103)).

**Comment by shobhitagarwal1612** [comment]
duplicate of #1476

**Comment by nwagu** [comment]
@opendatakit-bot claim
