### ISSUE TITLE
Remove final modifier from utility methods in MediaUtils

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1435]
The **final** modifier is used along with **static** in methods when we want to prevent the static method from getting overridden. But this (MediaUtils) is a utility class and is not being used as a super class anywhere. So, it's better we remove this keyword to prevent unnecessary confusion.

**Comment by icemc** [comment]
@lognaturel  what do you think about this issue?

**Comment by dcbriccetti** [comment]
Why not wait until a need to override arises? Perhaps it never will.

**Comment by lognaturel** [comment]
I agree with @dcbriccetti. I'm guessing this idea came from an overzealous IDE warning, it seems IntelliJ warns about static methods that are also final. I would argue this is a good practice. More at https://stackoverflow.com/questions/1932399/is-it-a-bad-idea-to-declare-a-final-static-method
