### ISSUE TITLE
Column Limit Uploading on Google Spreadsheet 

### ISSUE THREAD

**Issue by lokpriya** [getodk/collect#1444]
#### Software and hardware versions 
Collect v1.10.2, Android [5.1,] device used...

#### Problem description
Dear all
I have only 116 columns for spreadsheet but while uploading form it gives message that your form has 467 columns. Please help to solve the problem. I have attached the screenshot and xml form.
#### Expected behavior
It is supposed that columns are counted both **survey** and **choices** sheets. It would be better if columns defined only on survey sheets are counted and choices are only the options to fill the answers
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
![screenshot_2017-09-10-07-47-26](https://user-images.githubusercontent.com/27809339/30245568-8704336a-95fd-11e7-9863-a131051be886.png)
[CARITASNPJ.xlsx](https://github.com/opendatakit/collect/files/1290199/CARITASNPJ.xlsx)

**Comment by lognaturel** [comment]
Thanks very much for attaching your form, @lokpriya, that will make troubleshooting much easier.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 you're now our resident Google Sheets expert! Would you like to take a look at this one?

**Comment by shobhitagarwal1612** [comment]
@lognaturel Sure :smiley:

**Comment by lognaturel** [comment]
From Slack [here](https://opendatakit.slack.com/archives/C35ENHA64/p1505401193000410) -- @shobhitagarwal1612 identified that the select1 choice sets are represented by [secondary instances](https://opendatakit.github.io/xforms-spec/#secondary-instances---internal) in the XML. It seems that the column limit counter takes all nodes in instances into account when it should only consider nodes in the **primary** instance (the one that actually determines the form fields).

**Comment by lokpriya** [comment]
@lognaturel  Yes only primary instance (from Survey Sheet) should be counted  in the google spreadsheet column as they are actual  determiners for the answer we require.
