### ISSUE TITLE
Answer in single select and multi select question is highlighted on black instead of blue on Android 4.1, 4.2, 4.4

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1454]
#### Software and hardware versions 
Discovered during testing [#1415](https://github.com/opendatakit/collect/pull/1415#issuecomment-327422510)
Confirmed on master branch v1.10.2-12-g4c0d0a2-dirty

#### Problem description
User sees than selected answer in single select and multi select question is highlighted on black instead of blue

#### Steps to reproduce the problem
1. User uses device with Android 4.1 or 4.2 or 4.4
2. User is on single select or multi select question
3. User chooses answer
4. User sees that selected option is highlighted on black 

#### Expected behavior
User sees that selected answer is highlighted on blue
![screenshot_2017-09-12-12-40-45](https://user-images.githubusercontent.com/3907554/30321849-d1316bd6-97b7-11e7-9d3f-cd36039dd140.png)
![screenshot_2017-09-12-12-40-58](https://user-images.githubusercontent.com/3907554/30321853-d2c6b1f4-97b7-11e7-9e62-ede71155a095.png)
![screenshot_2017-09-12-12-41-03](https://user-images.githubusercontent.com/3907554/30321854-d3f4b85a-97b7-11e7-90e1-d5a3fd734d3c.png)

#### Other information 
Checkbox at the end of form is highlighted on blue
![screenshot_2017-09-12-12-41-15](https://user-images.githubusercontent.com/3907554/30321868-e39f06d4-97b7-11e7-8e4d-77c916ff8615.png)

**Comment by grzesiek2010** [comment]
@mmarciniak90 Could you check what is the color of those controls using your devices and another app ideally something popular. Is it blue?

**Comment by mmarciniak90** [comment]
@grzesiek2010 I checked search settings in Chrome browser.
![screenshot_2017-09-12-15-17-03](https://user-images.githubusercontent.com/3907554/30328167-d46f4a4a-97ce-11e7-9c48-2fea173f4222.png)
There is the same situation : 
* single select icon is black on Android 4.1, 4.2, 4.4
* single select icon is blue on Android 5.1, 6.0, 7.0

**Comment by grzesiek2010** [comment]
@mmarciniak90 thanks!
So I think it's ok. It's a default android color and we shouldn't force to use other.

**Comment by lognaturel** [comment]
Well that is very interesting! I think @grzesiek2010 is right and that it's actually the expected behavior. What do you think @mmarciniak90?

**Comment by mmarciniak90** [comment]
@lognaturel, I agree with @grzesiek2010. Leaving the default color is OK for me.
