### ISSUE TITLE
Settings are not updated if we navigate across tem.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1455]
#### Software and hardware versions 
Collect v1.10.2

#### Problem description
Settings are not updated if we navigate across them.

#### Steps to reproduce the problem
1. Go to `Admin Settings` -> `User Settings` and uncheck something
2. Go to the previous screen using a device back button
3. Click on `General Settings` and then `User interface`

#### Expected behavior
The option you uncheked should be hidden

#### Current behavior
The option you uncheked is visible and you need to go to the main menu and go to settings again to refresh it and the it works as expected.

**Comment by icemc** [comment]
Was able to reproduce the issue. Will start working on it ASAP

**Comment by icemc** [comment]
@nribeka was so busy recently that I didn't notice u had already assign this issue to me. Well PR on the way

**Comment by icemc** [comment]
@opendatakit-bot claim

**Comment by icemc** [comment]
Coming back again on this issue. 
Hello @yanokwa , @lognaturel , @grzesiek2010.  Going through the code base I realized that when In admin mode (that is when you are in admin settings) any setting you restrict the normal user from using is still available to the admin but not in the normal settings section(User settings). Isn't this the right behavior? if  yes then this is not an issue, else then I would love working on it (hope to complete it this time)! What do you think?

**Comment by grzesiek2010** [comment]
@icemc 
you might be right. I didn't know it works in that way. @lognaturel what do you think? Looks like a feature not a bug.

**Comment by lognaturel** [comment]
Thanks, @grzesiek2010 and @icemc, you're right that the admin can continue seeing all user settings.
