### ISSUE TITLE
Bearing widget not working

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1458]
#### Software and hardware versions 
Collect v1.10.2, Motorola G4 4th Gen XT1625 - Android 7.0, Samsung Galaxy S4 GT-I9506 - Android 5.0.1

#### Problem description
I set both devices outside for several minutes and never got a bearing reading. Previously it seemed to be very quick to achieve a reading so I think there is a regression. I tried this on 1.10.2 from the Play Store which predates changes to the location infrastructure or widget refactors.

I would start by trying to find the latest version that worked and then see what changed in the code.

**Comment by heyjamesknight** [comment]
Is this possibly related to the refactor? I believe I had to make some minor changes to BearingWidget.

**Comment by lognaturel** [comment]
I thought it could be but I tried it with 1.10.2 fresh from the Play Store and saw the same behavior.

**Comment by heyjamesknight** [comment]
Phew!

**Comment by grzesiek2010** [comment]
Works well on my Samsung galaxy S4 and Collect 1.10.2 tomorrow I can test other devices.

**Comment by grzesiek2010** [comment]
I've tested 
- Samsung Galaxy S4 Android 5.0.1
- Samsung Galaxy S Duos 2 Android 4.2.2

and I'm not able to reproduce the issue, everything is ok. @mmarciniak90 please check out your devices.

**Comment by mmarciniak90** [comment]
I was able to reproduce this problem on:
* Samsung J1 with Android 4.4
* Huawei Y5 with Android 5.1

I verified this on Collect v1.10.2 and master branch.
I didn't discover what cause this problem. 
Problem is not connected with location because devices were able to define location. 
I restarted devices but it does not resolve the problem.
I used devices with WiFi connection and LTE connection.

**Comment by grzesiek2010** [comment]
Good to know we have devices to reproduce the issue. I can investigate it after my vacation (after 25th September).

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
