### ISSUE TITLE
Website description for the repository

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1463]
The website mentioned on the collect repository at the end of the description links to itself which is redundant as we are already on that page. Shouldn't it be something else like https://opendatakit.org/use/collect/ or maybe the link to the [playstore](https://play.google.com/store/apps/details?id=org.odk.collect.android)?

![image](https://user-images.githubusercontent.com/8918023/30412864-3f070e0a-9938-11e7-94e5-c43a82a0571f.png)

@lognaturel @yanokwa What do you think?

**Comment by lognaturel** [comment]
Hmm, I *think* it's like this so that forks link back to the root? I'm not sure that's useful, though, since the parent repository usually shows up right under the fork name. I've seen other projects do this but I'm not sure why.

**Comment by shobhitagarwal1612** [comment]
Yes, including the link to parent repository seems redundant to me.

**Comment by icemc** [comment]
Hello! I will strongly recomend that the link be replaced with a more useful link or a list of useful links such as playStore etc. Most android app repositories out there, have a playstore link on their introductory section.

**Comment by lognaturel** [comment]
Thanks @shobhitagarwal1612 and @icemc. I set it to https://opendatakit.org/use/collect/ for now because I think the play store link doesn't provide quite enough context. We can perhaps change it to the docs site once that's more mature.
