### ISSUE TITLE
BUG strange behaviour with buttons instead of swiping 

### ISSUE THREAD

**Issue by atl2017** [getodk/collect#1464]
#### Software and hardware versions 
Collect v1.10.2, Android 6.0.1, 4.4.2 device : SAMSUNG S5 

#### Steps to reproduce the problem
[TestRepeat.xlsx](https://github.com/opendatakit/collect/files/1303167/TestRepeat.xlsx)

[Video](https://drive.google.com/open?id=0B966-DLxVMApblNBYURtRGYwR3M)
#### Expected behavior
Question after second group should be displayed just once.

**Comment by mmoye** [comment]
Upvoted. Was just about to post the same issue with an example xlsx. Let me know if it would be helpful.

**Comment by lognaturel** [comment]
Thanks for the report @atl2017 and @mmoye! If it's quick for you to post @mmoye, more examples always help.

**Comment by mmoye** [comment]
Sure thing. See attached.
[test.xlsx](https://github.com/opendatakit/collect/files/1307552/test.xlsx)

For our test we added to the first repeat (any number of times) but skipped the second repeat. Goes to the summary screen and then to Save & Exit when swiping, but will enter an endless loop on the summary screen if using forward/backward navigation buttons.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thank you for the thorough issue reports and test forms @atl2017 and @mmoye! Thanks to @grzesiek2010, the fix is now integrated an will be part of the next release at the end of October.

To be notified when the beta is out, you can watch the topic https://forum.opendatakit.org/c/releases/pre-releases and to be notified when the final release is out, you can watch the topic at https://forum.opendatakit.org/c/releases

**Comment by JasonIves** [comment]
I'm still seeing this in 1.10.2.

2 levels of nested repeats, after moving out of both get stuck on notes screen.  Only happens with buttons enabled.  Swipe only it works fine.

Let me know if more info is needed.

Jason

**Comment by lognaturel** [comment]
The fix hasn't been released yet and will be in 1.11.0. If you are able to build the current `master` and verify that it would be very helpful! I'm pretty sure we successfully tracked it down, though.

**Comment by JasonIves** [comment]
Gotcha, will try to test it.  Thanks.
