### ISSUE TITLE
Widget tests are not included in the code coverage report

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1473]
Some of the tests like the widget tests are being run by the CircleCI but they are not included in the jacoco code coverage report. One difference that I could notice between these tests and those which are included in the code coverage report is that they are using **mockito** and **roboElectricTestRunner**.

@alxndrsn @jknightco You both have written tests using mockito and roboElectricTestRunnner. Any idea what is missing here?

**Comment by heyjamesknight** [comment]
Not familiar with Jacoco, but the major difference with the Robolectric
tests is that they're under 'test' instead of 'androidTest' and run as
regular JUnit tests instead of as Instrumentation tests. Could you see if
Jacoco is looking at both 'test' and 'androidTest'?

**Comment by alxndrsn** [comment]
This was a Jacoco bug, and I've seen it before on Android.  Upstream issue is https://github.com/jacoco/jacoco/pull/288.

In this project, I fixed it by forcing Jacoco to _downgrade_ to 0.7.2: https://github.com/medic/medic-gateway/blob/master/build.gradle#L14-L16  It now looks like it's been fixed upstream, and Jacoco 0.7.7 or greater should support Robolectric tests again.

That linked project uses a gradle plugin called `jacoco-everywhere`, which might be useful in Collect.  Also there's is a bit more info that might be relevant in this comment and the surrounding issue: https://github.com/paveldudka/JacocoEverywhere/issues/13#issuecomment-216543125

**Comment by shobhitagarwal1612** [comment]
Thanks @alxndrsn @jknightco! :smiley:
