### ISSUE TITLE
Field list scrolls to top when binary data is collected

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1475]
#### Software and hardware versions 
Collect v1.10.2

#### Problem description
When a binary widget is populated from within a field list, the field list scrolls to the top.

#### Steps to reproduce the problem
Use the form [field-list-forum-9842.xml.txt](https://github.com/opendatakit/collect/files/1307953/field-list-forum-9842.xml.txt), scroll to the bottom and get either an image or a geopoint. After the value is set, the field list scrolls to the top.

#### Expected behavior
The scroll position in the field list should match the last binary widget to receive data.

@jknightco you're in this part of the code looking at binary widgets and field lists so how do you feel about taking this one on?

**Comment by heyjamesknight** [comment]
On it!

**Comment by lognaturel** [comment]
🎉🎉 I really don't understand GitHub permissions, it looks like I can't assign it to you. Can you please use the fancy new :robot: to self-assign (@opendatakit-bot c laim -- space added so I don't claim it)?

**Comment by heyjamesknight** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@yanokwa Do you know why this claim failed?

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot unclaim

**Comment by yanokwa** [comment]
Try the claim again, @jknightco! I think the 🤖 was taking some personal time off 😂

**Comment by heyjamesknight** [comment]
@opendatakit-bot claim

**Comment by heyjamesknight** [comment]
Lazy robots! At this rate they'll never reach the singularity.

**Comment by lognaturel** [comment]
So rude, now 🤖 is treating you like you just showed up, @jknightco! Doesn't it know you already have a massive pull request awaiting review?? 😅

**Comment by heyjamesknight** [comment]
@opendatakit-bot unclaim
Will return to this once the Geo Widgets are updated.

**Comment by xsteelej** [comment]
Work in progress

**Comment by xsteelej** [comment]
Work in progress

**Comment by xsteelej** [comment]
opendatakit-bot claim

**Comment by xsteelej** [comment]
@opendatakit-bot in progress

**Comment by grzesiek2010** [comment]
@xsteelej do you still work on this? any problems? I think it's similar to the issue I solved recently so I could take a look.

**Comment by xsteelej** [comment]
Thanks @grzesiek2010, I'm still working on #2257. I'm happy if you want to take a look at this one.
