### ISSUE TITLE
Icons in 'Exit form' dialog are too close to the dialog edge on Android 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1478]
#### Software and hardware versions 
Collect v1.10.2 - current master, Android v4.1, device Samsung Young

#### Problem description
Icons in 'Exit form' dialog are too close to the dialog edge on Android 4.1.

#### Steps to reproduce the problem
1. User starts form
2. User clicks on device back button
3. User sees Exit form dialog

#### Expected behavior
Left margin is visible.

#### Actual result
Icons are close to the dialog edge.
![screenshot_2017-09-18-15-16-21](https://user-images.githubusercontent.com/3907554/30544135-cba0cafe-9c85-11e7-82af-5c9163096633.png)

#### Other information 
Problem is not visible on Android 4.2, 4.4, 5.1, 6.0, 7.0

**Comment by yurilaguta** [comment]
I'll have a look
