### ISSUE TITLE
JodaTime dependency unnecessarily inflating memory footprint.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1488]
The default JodaTime dependency is a standard JAR, which Android loads inefficiently. Swapping to the library here will instead load JodaTime as an Android resource, which should reduce memory footprint: https://github.com/dlew/joda-time-android

**Comment by yurilaguta** [comment]
I'm on it.

**Comment by lognaturel** [comment]
I think you were asking about self-assignment of issues a few weeks back. We've now introduced a sweet new bot that now lets you do that! For the next issue you take on, you can comment with `opendatakit-bot claim` and our friendly bot will assign you. 😊🤖
