### ISSUE TITLE
Sorting of form names takes into account a case-sensitive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1489]
#### Software and hardware versions 
Verified on Collect v1.9.1

#### Problem description
Sorting of form names takes into account a case-sensitive on views:
- ~~Fill Blank Form~~ (fixed in #1482)
- Edit Saved Form
- Send Finalized Form
- View Sent Form
- Delete Saved Form - Saved Forms
- Delete Saved Form - Blank Forms

#### Steps to reproduce the problem
1. User opens one of mentioned view
2. User sees list of form
3. Part of forms starts with a upper case letter and part lower case letter
4. User sees that sorting by name is not correct

#### Expected behavior
Forms are sorted alphabetically even if form names starts from lower case and upper case

**Comment by dsrees** [comment]
@opendatakit-bot claim
