### ISSUE TITLE
LocalDateTime vs DateTime

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1491]
From @jknightco in `DateWidget`: `This is LocalDateTime but TimeWidget is just DateTime. Seems like we should make these consistent.`

We need to think through why these may have been different and what the implications are. My gut reaction is that `TimeWidget` should not have a timezone because time without a date can't properly get timezone adjustments but we know from #170 that time does have a TZ.

@grzesiek2010 You've thought deeply about these issues so may have some feedback.

**Comment by heyjamesknight** [comment]
Yeah, this was definitely something I didn't want to touch without understanding what was going on. I do think they should probably be consistent, however.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 You've thought deeply about these issues so may have some feedback.

Unfortunately I can't recall anything. Looking at the history I can see we used `DateTime` in DateWiget too.
So I think LocalDateTime has been implemented to fix daylight saving issue.

https://github.com/grzesiek2010/collect/commit/95ae651d5d021bdf63e413b18922a9db94d8ec36
Probably we need LocalDateTime to skip daylight saving gaps properly. So it's required there.

I don't know if we can use the same in the TimeWidget.

**Comment by grzesiek2010** [comment]
@jknightco @lognaturel I've been working on Ethiopian calendar recently and I can confirm that LocalDateTime in DateWidget and in DateTimeWidget is required to handle daylight savings.

Here is a case if you want to reproduce the issue I'm talking about:
1. Change your timezone to Nairobi (GMT +3).
2. Change LocalDateTime to DateTime in DateTimeWidget
3. Try to add this answer: 01.01.1960 00:00

Or you can use [DaylightSavingTest](https://github.com/opendatakit/collect/blob/master/collect_app/src/test/java/org/odk/collect/android/utilities/DaylightSavingTest.java)

I think we can close this issue.

**Comment by grzesiek2010** [comment]
A good question here is why we use LocalDateTime instead of LocalDate in DateWidget where we don't need the time? 
I think we should and looks like I have to investigate it.

**Comment by grzesiek2010** [comment]
We have had a lot bugs in managing dates and times since recently everything is fine let's not change anything so I'm closing.
