### ISSUE TITLE
Backward button is clickable on first question in form if user changes device orientation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1497]
#### Software and hardware versions 
Collect - current master
Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

#### Problem description
Backward button is clickable on first question in form if user changes device orientation

#### Steps to reproduce the problem
1. User uses forward/backward buttons to navigate
2. User is on first question in form
3. Backward button is visible but it is not clickable
4. User changes device orientation
5. Backward button is clickable

#### Expected behavior
Backward button is not clickable

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by codedsun** [comment]
@grzesiek2010  @mmarciniak90  can I work on this issue?

**Comment by grzesiek2010** [comment]
@codedsun yes please go ahead.

**Comment by codedsun** [comment]
@grzesiek2010 @mmarciniak90 Guide me how can i recreate this issue.
I downloaded a blank form of All Widgets , then entered in the fill blank form, I don't see any forward or backward button.

**Comment by grzesiek2010** [comment]
@codedsun 
They are invisible by default. Go to General Settings -> User Interface -> Navigation and select the second or third option.

**Comment by codedsun** [comment]
@grzesiek2010 PR send kindly review.
