### ISSUE TITLE
Appearance of Forward/backward navigation buttons depends on Android version

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1498]
#### Software and hardware versions 
Collect current master
Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

#### Problem description
Appearance of Forward/backward navigation buttons depends on Android version

#### Steps to reproduce the problem

**1. Android 6.0, 7.0**
- arrows are brighter than buttons background 
- backward button on first question looks like active
![screenshot_20170927-124456](https://user-images.githubusercontent.com/3907554/30909807-afa294e6-a382-11e7-945a-8cc360579de5.png)

**2. Android 5.1**
- arrows are darker than buttons background 
- backward button on first question looks like active
![screenshot_2017-09-27-12-45-11](https://user-images.githubusercontent.com/3907554/30909989-627e2da0-a383-11e7-8226-c4c32e80952e.png)

**3. Android 4.1, 4.2, 4.4**
- arrows are darker than buttons background 
- backward button on first question looks like inactive
![screenshot_2017-09-27-12-45-24](https://user-images.githubusercontent.com/3907554/30910082-ac4f3a64-a383-11e7-885a-ad74fbfa30a5.png)

#### Expected behavior
Buttons are consistent on all Android versions

**Comment by grzesiek2010** [comment]
I'm in favor of creating our own navigation buttons and not to relay on defaults. It would look better and the same across different android versions.
@lognaturel what do you think.

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs discussion"

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs discussion"

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
