### ISSUE TITLE
Option to dynamically sync itemcsv from server

### ISSUE THREAD

**Issue by mkswati** [getodk/collect#1501]
Hi,

I am using ODK Collect for data collection. I am struck in a scenario where I need a dynamic itemcsv update as the option I am using in my form are changing frequently due to parallel data collection. Also I need to place more than 100,000 records itemcsv to filter the required items. I want a feature where user specify its location in the application settings and itemcsv is downloaded from the server while another user have its own itemcsv loaded based on its location. I can create the server end to filter the request based on user request but have no idea on collect part.

**Comment by lognaturel** [comment]
Hi @Mkswati! Thanks for your patience with this. Some of what you describe is possible today. Some is a little less clear. https://forum.opendatakit.org/c/support is the place to ask for support. If what you need is not yet possible, then it can be specified on the forum as well.
