### ISSUE TITLE
Clicking an image used as a choice does not select that option

### ISSUE THREAD

**Issue by acawood777** [getodk/collect#1510]
#### Software and hardware versions 
Collect v1.10.2, Android v4.4.2, Samsung S4 mini (GT-I9190)

#### Problem description
I have a yes/no question, and have added thumbs-up / thumbs-down images to the choices.
Tapping on the images does not select yes/no - the user has to tap on the actual "Yes" or "No" text, which is not intuitive, especially when the image is significantly larger than the text.

#### Steps to reproduce the problem
Create a single-select question with an `image` column in the choices sheet, and provide images for the choices.

#### Expected behavior
Tapping the image should select the corresponding option

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
