### ISSUE TITLE
Do we need prefernces.xml file

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1523]
There is a file in xml dir named prefernces.xml. As I remember this file had been using before we redecorated our settings. Currently it isn't used by any setting fragment. 
We use this file only here:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/application/Collect.java#L264
and here:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ResetUtility.java#L82
what at first glance looks unnecessarily.

The code from prefernces.xml file is covered in other files we really use in our settings.

I think someone forgot to remove this file. I'm I missing something? 
@shobhitagarwal1612 you were working on settings as I remember. Could you confirm we don't need this file?

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Yes, we can get rid of this file now. Also, the default value for preferences is set in both the XML for each of the preference screen and the `PreferenceKeys.java`. So, I propose that we should set the default values using the `PreferenceKeys.java` in both of the two usages as mentioned above and replace the hardcoded default values in the preference xmls with a string reference.

**Comment by shobhitagarwal1612** [comment]
We should start to work on this after #1495 is merged

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 yes but I think we don't need it at all. 

> So, I propose that we should set the default values using the PreferenceKeys.java in both of the two usages as mentioned above and replace the hardcoded default values in the preference xmls with a string reference.

Why do we need that. I think it should work out of the box. Even if we reset settings then default values should be used out of the box.
Am I wrong?

**Comment by shobhitagarwal1612** [comment]
By "preferences xmls" I mean the different xmls for each preference screen like `form_management_preferences.xml`, `user_interface_preferences.xml`, etc and not the file `preference.xml`

**Comment by shobhitagarwal1612** [comment]
So, I am also in favor of removing the file `preference.xml`

**Comment by grzesiek2010** [comment]
I'm confused you agree we can remove the file but you think we need to call something else it those two places where that file is used? Because I don't think we need that.

**Comment by shobhitagarwal1612** [comment]
My knowledge is limited on the options for setting the default value for shared preferences. Pardon me if I am wrong. Maybe I should read more before continuing further in this discussion. As far as I know, this file is being used for setting the default values and I assumed that either we should replace it with the new preferences file or by setting the default values which are in `PreferenceKeys.java` manually by iterating through each value. But since you clearly have more knowledge and experience in this field, so kindly lead this discussion in the forward direction.

**Comment by grzesiek2010** [comment]
Ok thanks. I'm pretty sure we don't need at all. I'll do some quick tests and if I'm ok I'll ask @mmarciniak90 for more testing.

**Comment by shobhitagarwal1612** [comment]
:)

**Comment by lognaturel** [comment]
@grzesiek2010 I think what @shobhitagarwal1612 is saying is that there's still redundancy between the individual preference xml files and the `PreferenceKeys` java file. For an example of when it's done right, see `aggregate_preferences.xml`. The default server URL is set by a string. The default for `KEY_SERVER_URL` uses that same string. There are other cases in which hardcoded values are used and they could get out of sync. Did I get that right, @shobhitagarwal1612?

**Comment by shobhitagarwal1612** [comment]
What if we remove the default values from the xmls and use the `GENERAL_KEYS` for setting the default values in `GeneralSharedPreferences`. In that way all the default values will be handled and set only from a single point in the entire codebase

**Comment by grzesiek2010** [comment]
I think we should rather remove defaultValues form that GENERAL_KEYS not from preference files... why do we need that? We don't keep the same in adminKeys and I think if we load preferences files properly we can remove it right? and just read form sharedPrefs.

**Comment by grzesiek2010** [comment]
... or maybe it really makes sense it would allow us to read only preferences with default values not entire files. I hav to investigate it.
