### ISSUE TITLE
NullPointerExceptions related to the FormController

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1533]
There are some strange NPEs related to the FormController visible on Firebase or Google Play. It's not really common problem but it takes place in a various different places.
I decided to take a look at it and find out what's going on. I took v1.10.2 into account only.

Reports:
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/4418670f?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/2a6c40c9?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/fb2a145f?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/00c794e5?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/87ad4d09?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453

I was trying to find something all reports have in common.
In most cases Tecno devices are most affected or at lest they are mentioned. I've checked here:
https://console.firebase.google.com/project/api-project-322300403941/analytics/app/android:org.odk.collect.android/overview

and Tecno isn't really popular so it might indicate there is something wrong with this model.

The second common thing (maybe even more common) are visible logs. It's often:
[Reloading form and restoring state.](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L340)
and
[Loading instance from shadow file: ...](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java#L327)

Esspecially the first log ([Reloading form and restoring state.](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L340)) is interesting to me since I can't imagine when it might take place. 

It has been added [here](https://github.com/grzesiek2010/collect/commit/8ef9a0ac0675094109154cc0882c4d6f5f2119c5)
and the comment says:

> Implement resume handling when app gets tossed out of memory during external intent firing.

So I tried to throw OutOfMemoryException when I start camera, I tried to set the formController value to null then as well but it's not the same - not the same logs.

Any ideas how can I reproduce it? When it takes place in a real life. @yanokwa maybe you can help.

**Comment by grzesiek2010** [comment]
@mitchellsundt maybe you can help to reproduce that case since it was your commit?

Why when we return to the collect app the value of formController might be null?

**Comment by grzesiek2010** [comment]
@jknightco maybe you have any idea how to reproduce mentioned case?

**Comment by heyjamesknight** [comment]
@grzesiek2010  it doesn't look like I have access to the Firebase console (that or something is broken) @lognaturel is that something you could help with?

**Comment by grzesiek2010** [comment]
@jknightco yes you don't have access but you don't need that since I've already analyzed those reports and I'm asking about the second part of my description starting with: 

> The second common thing (maybe even more common) are visible logs. It's often:

I can't reproduce the case when [this line](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L340) is called and this is my problem.

**Comment by grzesiek2010** [comment]
I'm closing this issue, we handle most of the problems we had with `FormController` if there is any new we can create a separate issue.
