### ISSUE TITLE
Duplicated FileUtil class.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1534]
In org.odk.collect.android.utilities we have two similar classes:
[FileUtil](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/FileUtil.java)
[FileUtils](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java)

@jknightco you have added the first one. Any reason why?

**Comment by heyjamesknight** [comment]
@grzesiek2010 I'd like to slowly move away from the static utility classes and move towards concrete implementations that can be more easily mocked. Rather than submit a large refactor that does away with the old one completely I created the concrete class and added the methods I needed.

**Comment by grzesiek2010** [comment]
Ok I'm closing the issue if it's considered.
