### ISSUE TITLE
remove link to googlegroups from issue model

### ISSUE THREAD

**Issue by mfrasca** [getodk/collect#1536]
the explanatory text you get when you start opening an issue contains a link to the deactivated google groups

> This space is for submitting problems and feature requests. For general usage or form design questions, please email opendatakit@googlegroups.com or for ODK Collect source code questions, please email opendatakit-developers@googlegroups.com

this should be replaced with a link to the forum.

**Comment by lognaturel** [comment]
YES, you are so right!

**Comment by vkdrn** [comment]
@opendatakit-bot claim

**Comment by mfrasca** [comment]
I also often type "this closes #x", while github wants "please do close #x".

**Comment by lognaturel** [comment]
@mfrasca it wasn't closed yet because the change hadn't been merged! Both "close" and "closes" are recognized - https://help.github.com/articles/closing-issues-using-keywords/
