### ISSUE TITLE
Import RequestCodes instead of its members

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1537]
In classes updated by https://github.com/opendatakit/collect/pull/1508/files, instead of importing specific constants and using them directly, use `import static org.odk.collect.android.utilities.ApplicationConstants.RequestCodes;` and access the constants explicitly through `RequestCodes`. This makes their origin more clear.

From @jknightco at https://github.com/opendatakit/collect/pull/1508#issuecomment-336824777

**Comment by vkdrn** [comment]
@opendatakit-bot claim
