### ISSUE TITLE
Instrumentation test needed for the All Widgets Form.

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1540]
Right now contributors have to manually walk through the All Widgets Form when testing changes to the QuestionWidget base class or any of its children. A simple Instrumentation test that walks through the entire All Widgets Form, opens the app, closes the app, sets answers, moves back and forth, etc. would go a long way to making sure that functionality remains consistent across commits.

**Comment by heyjamesknight** [comment]
@opendatakit-bot claim

**Comment by jknightco** [comment]
`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':collect_app:testDebugUnitTest'.
> Task with path 'unzipJacocoAgent' not found in project ':collect_app'.
`
Not sure what the best fix is. @shobhitagarwal1612 @lognaturel any ideas?

**Comment by grzesiek2010** [comment]
Now we have many espresso tests that cover our test cases so we can close.
