### ISSUE TITLE
Drawables can be converted to scalable assets (e.g., PNG to SVG)

### ISSUE THREAD

**Issue by asclepiusgal** [getodk/collect#1549]
#### Problem description
Collect is using .png drawables instead of scalable vector graphics (SVG). These PNG assets can be converted over to SVG to improve the app's UI / UX.

**Comment by sashank27** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
Hi @sashank27, are u still working on this issue? If not I can claim it.

**Comment by Shubham-vish** [comment]
@opendatakit-bot claim

**Comment by Shubham-vish** [comment]
I would be very thankful if anybody could guide me.

**Comment by shobhitagarwal1612** [comment]
Hey @Shubham2320 and thanks for picking the issue. As the issue description says, we are using .png files at many places as image resources which are not scalable. So, each of them should be replaced with a vector file.

**Comment by Shubham-vish** [comment]
:) I've read many documentations about converting .png files to .svg but all I found are methods to convert each file separately and here we want to convert multiple files together so is there any other way anybody could suggest to achieve this goal in an easier way.

**Comment by lognaturel** [comment]
Thanks for your interest in this issue, @Shubham2320! It looks like this is already being addressed in #1885. 

https://material.io/icons/ is generally a good source for icons that can be used in apps.
