### ISSUE TITLE
There is no difference when user records videos in low or high resolution

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1575]
#### Software and hardware versions 
Collect v1.11.0
Verified on Android 7.0, 4.4, 4.1, 6.0, 5.1

#### Steps to reproduce the problem
1. High-resolution video recording is ENABLED
2. User fills form and records 5s video
3. User saves form
4. High-resolution video recording is DISABLED 
4. User starts new form and records 5s video

#### Expected behavior
User sees that videos are recorded in other resolutions

#### Actual result
I was not able to verify a resolution of videos but I verified a videos size. 
Video size should be different in low and high resolution but the difference is almost irrelevant 

| Device | High-resolution | Low-resolution |
| --- | --- | --- |
| Sony Z3 | 9.5 MB | 9.2 MB |
| Samsung S7 | 32.4 MB | 31.5MB |
| Samsung Young | 1.7 MB | 1.2 MB |
| Infinix | 3.8 MB | 2.0 MB|

 Only on Infinix device is significant difference in video size.

**Comment by grzesiek2010** [comment]
We use [EXTRA_VIDEO_QUALITY](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java#L129) and it's rather a hint than a command so the camera app might ignore it. Looks like in most of cases it's ignored but it depends on the camera app as I said.

My only idea is to add something like `This option depends on the camera app you use` or something like that. @lognaturel what do you think.

**Comment by lognaturel** [comment]
Interesting find, @mmarciniak90! I don't think we can reliably scale down video in a performant way so I propose we just make the documentation more clear that this might not always work just as @grzesiek2010 suggests.

**Comment by akshay-ap** [comment]
@lognaturel @grzesiek2010 In such cases can we provide some option to user that will convert video from high resolution to low resolution? Internally we can use some library like ffmpeg

**Comment by grzesiek2010** [comment]
@akshay-ap if it works well and doesn't take much time maybe it's reasonable. You can try if you want.

**Comment by lognaturel** [comment]
My sense is that this should be really low priority. It's not a feature users have asked for and I think video is pretty rare overall.
