### ISSUE TITLE
Refactor: Widgets should handle parsing Activity responses on their own (FormEntryActivity does this currently)

### ISSUE THREAD

**Issue by heyjamesknight** [getodk/collect#1580]
FormEntryActivity's `onActivityResult` function is 600+ lines and does a lot of preprocessing that really should be handled by the Widgets themselves. As it stands now, it takes extra effort to see what each Widget expects to be handed back in its `setBinaryData` method.

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
The `WaitingForDataRegistry` is a step in the right direction here but there is still definitely work to do. I think really (like suggested here) the parsing/processing of data just needs to move into the widgets.

**Comment by seadowg** [comment]
`FormEntryViewModel.answerQuestion` is another step towards a better world here. Closing this issue as we're not working on these improvements in one focused block (they're happening bit by bit).
