### ISSUE TITLE
Can not navigate back when I'm at the end of the form with nested groups.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1582]
#### Software and hardware versions 
Collect v1.11.0

#### Problem description
I discovered the issue during the work on `Repeat titles`:
https://github.com/opendatakit/collect/issues/183
https://github.com/opendatakit/xforms-spec/issues/141

The problem is when I have nested groups (one is repeat group) in my form and I try to navigate back when I'm at the end of the form. It's not possible but if I swipe forward I'm moved to the first question.

#### Steps to reproduce the problem
Use this form:
[repeat_group_new.xml.txt](https://github.com/opendatakit/collect/files/1430883/repeat_group_new.xml.txt)

#### Other information 
Looks like everything is ok if you use a group with `field-list` appearance.

**Comment by lognaturel** [comment]
Now this is a weird one. Looks like it's been around for a while and no one has reported it. I'm wondering whether we should still issue a patch release. @yanokwa?

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
The problem is on the Javarosa's side https://github.com/opendatakit/javarosa/issues/218
