### ISSUE TITLE
Lint and test output files are not copied to artifacts in CircleCI

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1585]
`checkstyle`, `pmd` and `findbugs` reports are correctly copied over and visible from the artifacts tab in CircleCI. However, `lint` reports are not. No test reports are available.

**Comment by Divya063** [comment]
@lognaturel I would like to work on this

**Comment by konishon** [comment]
@Divya063 Hey, comment @opendatakit-bot claim. To claim this issue

**Comment by lognaturel** [comment]
That sounds great, @Divya063! 

@nishontan thanks for the bot reminder. Make sure to use back quotes to escape the command as in `@opendatakit-bot claim` or you'll accidentally claim the issue for yourself! 😊

**Comment by Divya063** [comment]
@opendatakit-bot claim
