### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1586]
```
       android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(is displayed on the screen to the user and with text: is "0.162")' doesn't match the selected view.
        Expected: (is displayed on the screen to the user and with text: is "0.162")

org.odk.collect.android.utilities.DateTimeUtilsTest > getDateTimeLabelTest[Moto G (4) - 7.0] FAILED
        org.junit.ComparisonFailure: expected:<20 Okt[] 1991> but was:<20 Okt[.] 1991>
        at org.junit.Assert.assertEquals(Assert.java:115)
```

**Comment by heyjamesknight** [comment]
This is actually a test @grzesiek2010 added; I mentioned it to him the other day when I was looking into Gradle updates and assumed it was just related to my branch being in a weird state. Looks like it popped back up.

The only change introduced that could affect this would be updating the testing utilities, but I don't know how that would cause formatting tests to fail. Looking into it now.

**Comment by heyjamesknight** [comment]
Some of these appear to be formatting issues (such as the '.') but others appear to be a timezone issue (687967200000 is 14:00 in UTC, but when I run the tests in CET it expects 15).

**Comment by grzesiek2010** [comment]
It's strange but it depends on Android version. Here I have two devices with the same language but different os version. In the second case, there is a dot.
![date](https://user-images.githubusercontent.com/3276264/32326034-ab66be00-bfd1-11e7-8d60-feaa45c74c22.png)

I removed those tests and I kept only one for English locale as it should be enough I think. #1588 

But now the problem is with your test @jknightco 

> org.odk.collect.android.AllFormsWidgetTest > testActivityOpen[circleci-android22(AVD) - 5.1.1] FAILED

**Comment by lognaturel** [comment]
There are currently several ways that the integration tests can fail depending on the configuration of the test device. For example:
- if the device doesn't have the required sensors, the bearing question will fail
- if the Zebra Print application is installed, the test will hang forever

I think this is a separate issue but `DateTimeUtils` test fails with `org.junit.ComparisonFailure: expected:<Oct 20, 1991, [14]:00> but was:<Oct 20, 1991, [07]:00>` when I run locally.

**Comment by lognaturel** [comment]
@grzesiek2010 I'm guessing that the `DateTimeUtils` problem has to do with the locale my device is set to. Can we force a locale before the test? I tried setting my phone locale to French/France which is supposed to use 14:00 but that still didn't work so I'm not totally sure that's it.

**Comment by heyjamesknight** [comment]
@lognaturel Can you clarify what you mean in regards to the Bearing test? We're currently mocking out the intents there—it shouldn't ever pass off to the actual Bearing Activity. 

Fixing the Printer one now.

**Comment by heyjamesknight** [comment]
@lognaturel re: the DateTimeUtils, I also tried a number of things to get it to lock into a specific timezone but I could not do so successfully.

**Comment by lognaturel** [comment]
Interesting regarding the bearing widget. Does it work in the emulator for you? What I see is that the screen shows a toast saying it can't get the bearing and then the console shows that the value doesn't match what was expected.         `android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(is displayed on the screen to the user and with text: is "0.182")' doesn't match the selected view.
        Expected: (is displayed on the screen to the user and with text: is "0.182")`

Just encountered test failures because my device was set to French. Is it possible to look for buttons with text from a certain resource ID or does it have to look for the actual test in the interface?

**Comment by heyjamesknight** [comment]
Yeah, works fine in the emulator for me. I'll see if I missed something, but it shouldn't ever be actually calling out to the other Activity. 

I'll look at the resource id issue. Normally we'd just use the View IDs but since we set them randomly in code often it makes things a bit differently. If I can't use string IDs I'll see if we can set a common View ID for those fields.

**Comment by lognaturel** [comment]
Not a big deal about the resource ID! I understand why you did it that way now. Totally reasonable and we can add that as a note in the testing guide.
