### ISSUE TITLE
CircleCI builds should fail fast on error

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1609]
We used to run the different build commands in a big line separated by `&&` to make sure that the build failed immediately when there was an issue. By first running fast tasks (`checkstyle`, `pmd`, etc) we could tighten the feedback loop and only run slow tasks (integration tests) if necessary. I think the order should be:
1. `pmd`
1. `checkstyle`
1. `lint`
1. `findbugs`
1. tests

At some point those build commands were separated and now we only get feedback when all have run to completion. The build now takes 35 minutes so this is a real problem.

This seems like a great application for workflows - https://circleci.com/docs/2.0/workflows/

@Divya063 you may be interested in this one since you're looking at other CircleCI matters.

**Comment by lognaturel** [comment]
Could we just run the gradle `check` task instead??

**Comment by shobhitagarwal1612** [comment]
Does it stops the build if one of the tasks fails?

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Sorry I didn't answer this. Yes. But it also runs all checks including connected tests and tests on all build variants which may not be necessary.

Additionally, unit tests currently fail on release builds because of the calls on `FirebaseCrash`. That's something we should eventually look at fixing.
