### ISSUE TITLE
Sent forms again available for sending after deletion of `instances.db`

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1611]
#### Software and hardware versions 
Collect v1.11.0, Android v7.0.1, device used : Moto m
#### Problem Description
After deleting the `instances.db` and restarting the app, `Send Finalized Form` button form shows that there are not forms available for submission but on clicking the button, all forms are available even if they have been already sent. 
#### Steps to reproduce the problem
Send the finalized forms. Delete the `instances.db` file. Restart the app. Go to main menu. Click `Send Finalized form`.
#### Expected behaviour
`instances.db` should not be removable. Even if user deletes it, the sent forms should be available for submission again. 
#### Other information 
This can be fixed by changing the `status` in `instances` table. I propose that when a new `instances` table is created and if forms are available in `sdcard/odk/instances` directory instead of storing them as `completed` in `status` column , they should be marked as something else like `completed_but_do_not_send` . But doing this will create a problem (for developers and testers ) that if completed forms are manually added in `sdcard/odk/instances` for testing purpose they wont be available for submission. To do so, `instances.db` also need to be created by developer/tester.

Advantage: Forms filled from the device the user uses will only be available for submission.

**Comment by lognaturel** [comment]
I think this is ok. Deleting the `instances.db` file is unusual and should be expected to cause some problems. I think what we should do is document the behavior to expect when deleting a DB file.

**Comment by akshay-ap** [comment]
Should this be documented in `Collect` developer docs?

**Comment by lognaturel** [comment]
I think it’s useful for users, too. It’s good to know what the implications are since the dbs can be deleted from admin settings. I filed an issue in the docs repository.
