### ISSUE TITLE
Options in dialog 'Zoom to ...' are not visible at whole in horizontal position

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1614]
#### Software and hardware versions 
Collect v1.11.1
Problem depends on screen size

#### Problem description
Options in dialog 'Zoom to ...' are not visible at whole in horizontal position

#### Steps to reproduce the problem
1. User uses device on horizontal position
2. User opens one of Geo question
3. Dialog 'Zoom to ...' with options 'Zoom to current location' and 'Zoom to saved feature' appears
4. User does not see buttons at whole
![screenshot_2017-11-08-15-30-29](https://user-images.githubusercontent.com/3907554/32554724-02ce1f08-c49b-11e7-89e8-e9f2dd628389.png)

#### Expected behavior
* User is able to scroll on 'Zoom to ...' dialog OR dialog is resized

**Comment by codedsun** [comment]
@lognaturel I want to work on this issue!

**Comment by grzesiek2010** [comment]
@codedsun currently @jknightco is working on big changes in this area https://opendatakit.slack.com/archives/C35ENHA64/p1511178185000272
so we should postpone all other related issues.

**Comment by lognaturel** [comment]
Will be addressed by @jknightco's updates.
