### ISSUE TITLE
Unused space is visible under buttons in GeoPoint question

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1615]
#### Software and hardware versions 
Collect v1.11.1

#### Steps to reproduce the problem
1. User uses device in horizontal position 
2. User opens GeoPoint question with maps appearance
3. User sees option buttons on the right side
4. Unused space is visible under buttons
![screenshot_2017-11-08-15-30-58](https://user-images.githubusercontent.com/3907554/32555036-ec71745c-c49b-11e7-8cbe-ab489b791bfb.png)

#### Expected behavior
* Whole right area should be used to display buttons

#### Notes
Problem is visible only on GeoPoint question

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by akshay-ap** [comment]
@lognaturel  The issue can be closed now.
