### ISSUE TITLE
User sees misleading information in toast in Selfie widget when front camera is not available in device

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1617]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
User sees misleading information in toast in Selfie widget when front camera is not available in device

#### Steps to reproduce the problem
1. User uses device **without** front camera
2. User is on the Selfie widget
3. User clicks on 'Take Picture' button
4. User sees toast with message 'Tap the screen to take a picture'
![screenshot_2017-11-08-15-51-50](https://user-images.githubusercontent.com/3907554/32555564-66c466d2-c49d-11e7-8031-f4a57089440b.png)

#### Expected behavior
* User should be informed that front camera is not available in device

**Comment by akshay-ap** [comment]
@mmarciniak90 Are you fixing the issue or shall I?

**Comment by lognaturel** [comment]
Go ahead and claim it, @akshay-ap! 🎉

**Comment by akshay-ap** [comment]
@opendatakit-bot claim
