### ISSUE TITLE
Refactor org.adk.collect.android.utilities.Validator

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1620]
#### Software and hardware versions 
Collect v1.11.0, Android v7.0, device used : Moto M

#### Problem description
The class `org.adk.collect.android.utilities.Validator` is used to validate Form Meta Data entered by user. The name of the class seems too vague. There is no validation for phone number. Regex for email validation needs to be improved. Current EditText for phone number doesn't have any validation.
Splitting EditText for phone number into Country Code and number would be even better.

#### Expected behaviour
Name of class should be renamed to `FormMetaDataValidator` because it has been used for only validating FormMetaData input.
Changes in regex proposed :
Regex for email : 
http://emailregex.com/
https://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

Regex for phone number : 
https://stackoverflow.com/questions/8634139/phone-validation-regex
https://www.regextester.com/1978

Also, tests for phone number needs to be added.

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
This requires conversation. If you search prior issues, you'll see that the regex were already discussed!

**Comment by akshay-ap** [comment]
Discussion on #1299 regarding validating email shows the reason for simple regex.

**Comment by lognaturel** [comment]
Yes, that's the one, thanks for finding it. Based on that conversation and the general desire to keep things frustration-free for users, I think we should keep the email validation as it is and not add a phone validation. Does that seem right to you @akshay-ap or would you still like to advocate for more validation?

**Comment by akshay-ap** [comment]
Current validation seems to work and as it is not a critical feature, I am ok with current implementation.
The same goes with phone number validation. But, adding a simple validation for number won't cause any harm I think.

**Comment by lognaturel** [comment]
👍 Let's keep things as-is for now.
