### ISSUE TITLE
User is able to open more than one dialog when user quickly clicks the button several times 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1624]
#### Software and hardware versions 
Verified on Collect v1.11.1

#### Problem description
User is able to open more than one dialog when user quickly clicks the button several times 

#### Steps to reproduce the problem
1. User quickly clicks the 'Select date' button several times 
   * Problem could also be related to other widgets.
2. Dialog appears
3. User selects date and clicks OK 
4. User sees that additional dialog is visible with default date
   * If user clicks OK on this dialog, date value will be changed

![dialog](https://user-images.githubusercontent.com/3907554/32723139-ab36bbb2-c86c-11e7-81c4-d2cfb0c200fb.gif)

#### Expected behavior
User is not able to open two dialogs

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
