### ISSUE TITLE
Change Google account selection dialog to match app theme

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1626]
The account selection dialogs use the dark theme.

Screenshots from @mmarciniak90 [here](https://github.com/opendatakit/collect/pull/1612#issuecomment-343869649):

| Dialog before fix | Dialog on Get Blank Form view | Dialog after fix |
| ------------- | ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/3907554/32719692-89c2a154-c861-11e7-9fb9-62fee1839bbe.png) |  ![getblankform](https://user-images.githubusercontent.com/3907554/32719704-91c095b4-c861-11e7-844f-451cb2dec341.png) | ![after](https://user-images.githubusercontent.com/3907554/32719710-96ac8e70-c861-11e7-9a0b-fcc2b0d3b6f7.png) |

The first answer from https://stackoverflow.com/a/32955986/137744 seems like the way to go.

**Comment by akshay-ap** [comment]
@opendatakit-bot claim
