### ISSUE TITLE
User is able to open form or list two times when user quickly clicks form name / button in main menu several times

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1630]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
User is able to open form or list two times when user quickly clicks form name / button in main menu several times

#### Steps to reproduce the problem
**Use Case 1:**
1. User quickly clicks the 'Edit Saved Form' button several times
2. List of forms appears two times

**Use Case 2:**
1. User clicks on 'Fill Blank Form'
2. User quickly clicks the form name several times
3. Form is open two times

#### Expected behavior
User is not able to open two forms or lists

#### Notes
I discovered this problem during testing #1625

**Comment by grzesiek2010** [comment]
since it's related to #1625 
@opendatakit-bot claim
