### ISSUE TITLE
User is moved to main Google Drive list  if user clicks on 'Go back' when a list of shared forms is displayed

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1631]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
User is moved to main Google Drive list  if user clicks on 'Go back' when a list of shared forms is displayed

#### Steps to reproduce the problem
1. User uses Google Sheets
2. User opens 'Get Blank Form' list
3. User sees list of forms

<img src="https://user-images.githubusercontent.com/3907554/32781820-ae8bf414-c946-11e7-8582-a84753501e20.png" width="50%" height="50%">

4. User clicks on 'Shared with Me'
5. User sees a folder

<img src="https://user-images.githubusercontent.com/3907554/32781843-bca1266e-c946-11e7-8d1f-4baa63c70c04.png" width="50%" height="50%">

6. User clicks on folder
7. User sees content of the folder and buttons: 'Go back' and 'My Drive'

<img src="https://user-images.githubusercontent.com/3907554/32781858-c4679f2c-c946-11e7-9d36-f900110efbde.png" width="50%" height="50%">

8. User click on 'Go back' button
9. User sees content of user drive and button 'My Drive'
<img src="https://user-images.githubusercontent.com/3907554/32781862-c8e75894-c946-11e7-9815-52433a1d4416.png" width="50%" height="50%">

#### Expected behavior
User sees correct view
 <img src="https://user-images.githubusercontent.com/3907554/32781843-bca1266e-c946-11e7-8d1f-4baa63c70c04.png" width="50%" height="50%">

#### Other information 
Discovered during work on #1003

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
