### ISSUE TITLE
Move MediaPlayer field from QuestionWidget

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#1640]
I recommend removing the MediaPlayer field from the abstract QuestionWidget and putting it into a new abstract subclass one level below, for those few widgets that actually use it.

#### Software and hardware versions 
Collect v1.11.0

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
