### ISSUE TITLE
Add support for nonlinear repeats

### ISSUE THREAD

**Issue by mdudzinski** [getodk/collect#1647]
The best reference -> https://forum.opendatakit.org/t/change-static-text-in-groups-prompt/1505

Frankly, I'm not sure how it should look like so it would be super helpful if we could see how it looked like in JavaRosa J2ME days. Since the ODK fork has been modified to *not* contain any J2ME related code, the original repo (https://bitbucket.org/javarosa/javarosa/wiki/Home) should be used. I have no idea if J2ME dev tools are still available these days but I guess we'll find out.

Everything should be ready on the [javarosa](https://github.com/opendatakit/javarosa) side because there is still code that references the nonlinear repeats feature like:
* `FormEntryController#EVENT_REPEAT_JUNCTURE`
* `FormEntryModel#REPEAT_STRUCTURE_NON_LINEAR`
* `REPEAT_STRUCTURE_NON_LINEAR` branches in `FormEntryModel#incrementHelper` and `FormEntryModel#decrementHelper`

There is also some code pointing to this feature on the ODK Collect side as well:
```
case FormEntryController.EVENT_REPEAT_JUNCTURE:
    Timber.i("Repeat juncture: %s", formController.getFormIndex().getReference());
    // skip repeat junctures until we implement them
    break;
```

**Comment by seadowg** [comment]
This would be a good discussion to continue in the [forum](https://forum.getodk.org) as it's around adding new features to Collect.
