### ISSUE TITLE
QR code with exported settings does not include sorting settings

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1654]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
QR code with exported settings does not include sorting settings

#### Steps to reproduce the problem
1. User opens 'Fill Blank Form' view
2. User sorts forms by Date, newest first  
3. User exports settings to QR code and collect.settings file
4. One user imports settings from QR code and other one from collect.settings file
5. Both users go to 'Fill Blank Form' view
6. First user sees that forms are sorted as default
6. Second user sees that forms are sorted by date

#### Expected behavior
Both users have the same sorting settings on **all views**

**Comment by grzesiek2010** [comment]
That's because QR code contains only settings from General/Admin settings while the settings file contains all shared preferences.
The question is: does it work as expected @lognaturel ?

**Comment by lognaturel** [comment]
I agree this is ok. I think of the screen options as something at the enumerator's discretion to help them do their work more easily.
