### ISSUE TITLE
Default values in settings are restored if user update to version with #1623

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1660]
#### Software and hardware versions 
Collect with #1623 

#### Problem description
Default values in settings are restored when user updated Collect to version with changes from #1623 

#### Steps to reproduce the problem
1. User has installed collect without changes from #1623 
2. User changes few settings
3. User updates to Collect with changes from #1623 

#### Expected behavior
All settings remain unchanged

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
