### ISSUE TITLE
User should be notified if a new version of a form is available before loading the form

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1667]
As a user, I would like to be notified if a new version of a form is available when I try to load such a form. Thanks to that I will be able to decide whether I want to download a newer version or not.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
This would be a really good complement to #1653. If there's connectivity, then the server should be checked for new versions. Ideally it would be done in the background so form load isn't slowed down. Then a dialog can be displayed saying that there has been an update to the form and the user can update it from 'Get Blank Form.'

@jniles I see you liked this issue. Any opinions on how the feature should work?

**Comment by lognaturel** [comment]
Here is what I'm currently imagining:
- Load the form and check for updates in parallel. 
- If form loading finishes first, continue the update check. 
- If there are no updates, launch the form as usual. 
- If there is an update, ask the user if they want to download the new form.
- If the user taps yes, stop loading the old form, download, load and launch the new form.
- If the user taps no, load and launch the old form.

**Comment by lognaturel** [comment]
This was discussed by the Technical Steering Committee and there were concerns about server load. If someone wants to take this up the next step would be to write up a proposed specification.

**Comment by Obaid51** [comment]
Hi lognatural, I was also thinking the same thing. I guess I could give it a try. Let me know if it is available.
