### ISSUE TITLE
Background service for polling the server

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1668]
As I user I would like to be notified if newer versions of form I use are available. We should polling the server once in a while and show a notification if needed.

A user should be able to set a frequency of polling the servers so we should provide a few options like:

- once a day
- every hour
- every 10 minutes
etc.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Small detail but just so all things makes sense to us in the future -- what you want is "polling", not "pooling"! https://en.wikipedia.org/wiki/Polling_(computer_science) vs https://en.wikipedia.org/wiki/Pool_(computer_science) 😊

**Comment by grzesiek2010** [comment]
> Small detail but just so all things makes sense to us in the future -- what you want is "polling", not "pooling"! https://en.wikipedia.org/wiki/Polling_(computer_science) vs https://en.wikipedia.org/wiki/Pool_(computer_science) :blush:

Thanks.
