### ISSUE TITLE
Repeat count after group in jump screen breadcrumb

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1670]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
Groups sometimes show a repeat count. I think this may happen just with groups that are nested in repeats but I'm not sure yet. Reported by @hooverlunch when looking at #1648

#### Steps to reproduce the problem
Use form [nested-repeats.xml.txt](https://github.com/opendatakit/collect/files/1511886/nested-repeats.xml.txt). Tap on the [jump icon](http://docs.opendatakit.org/collect-forms/?highlight=jump#filling-out-forms) and drill down to a pet. See:
![](https://user-images.githubusercontent.com/702320/33386628-5ebb365c-d4f9-11e7-918c-63460ec45db3.png)

#### Expected behavior
"Louise" is the label of a simple group, not a repeat so it should not have parentheses or a number after it. The breadcrumb should show Friends (1) > Louise > Pets (1). This works correctly for the in-form breadcrumb but not for the one in the jump screen/hierarchy view.

The first step will be to confirm under what conditions this happens. I would try a form with just one group, another one with nested groups and then one with a group inside a repeat.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@lognaturel 

> The first step will be to confirm under what conditions this happens.

It takes place when a repeat group is inside another group (repeat or regular). Here is a fix #1749
