### ISSUE TITLE
Default displayed hour changes when rotate screen on android 4.1 on Gregorian calendar form.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#1679]
#### Software and hardware versions 
Collect v1.11.1, Android v4.1.

#### Problem description
Default displayed hour changes when rotate screen on android 4.1 on Gregorian calendar form.

#### Steps to reproduce the problem
1. Go to Gregorian calendar form 
2. Choose a date on first page of the form. It's presented in "day month year hour" order. Hour is default as 12:00:00 AM.
3. Rotate device, hour is viewed as 00:00:00 now.

#### Expected behavior
Default hour shouldn't change during screen rotation.
 
#### Other information 
Issue occurs on all pages of form. Screenshots attached.  
![screenshot_2017-12-01-09-13-13](https://user-images.githubusercontent.com/33342488/33485472-bf4136da-d6a6-11e7-9d35-262a790c25c1.png)
![screenshot_2017-12-01-09-13-20](https://user-images.githubusercontent.com/33342488/33485473-bf5aebf2-d6a6-11e7-9a15-9b87c2b4e7dc.png)
![screenshot_2017-12-01-09-13-27](https://user-images.githubusercontent.com/33342488/33485474-bf744a8e-d6a6-11e7-9998-a0ec066a67b4.png)

**Comment by dr0pdb** [comment]
@kkrawczyk123 @lognaturel Can i get the ```Gregorian Calendar ``` form for testing ? 
@opendatakit-bot claim

**Comment by lognaturel** [comment]
👍 The Gregorian calendar is just the standard one so you should be able to use the All Widgets form from the default server or linked from the README.

**Comment by dr0pdb** [comment]
I couldn't find it on the All Widgets form as well the forms in the ```README```

**Comment by lognaturel** [comment]
Any of the questions that start with "Date" will do.

**Comment by kkrawczyk123** [comment]
I used that one:
[gregorian.xml.txt](https://github.com/opendatakit/collect/files/1541836/gregorian.xml.txt)

**Comment by lognaturel** [comment]
@srv-twry it sounds like you weren't able to reproduce this on a 4.1 emulator. Did you also get a chance to try a physical device?

@kkrawczyk123 is the problem on any rotation? Or just on portrait to landscape or something weird like that? What device were you using? Do you have another 4.1 device you could try on? 

I'm kind of thinking that this is niche enough we may just not worry about it unless a user reports it.

**Comment by dr0pdb** [comment]
@lognaturel I tried it on a physical Android 5.1.1 device and Android 4.1 emulator but couldn't reproduce.
I couldn't test it on an Android 4.1 physical device though.

**Comment by lognaturel** [comment]
Thanks for the details. Let's see what @kkrawczyk123 comes back with.

**Comment by dr0pdb** [comment]
@opendatakit-bot unclaim

**Comment by kkrawczyk123** [comment]
@lognaturel yes, it was any rotation. I have Samsung GT-S6310 and I don't have any other device with android 4.1 so I can't try it.

**Comment by grzesiek2010** [comment]
@lognaturel @kkrawczyk123 @srv-twry 
According to the statistics from Google Play Console Android 4.1 is used by 2.3% of our users.
It's the lowest os version we support and in the future, we will stop doing that (like we did with Android 2.x and 3.x a few months ago).

So, in my opinion, it doesn't make sense to fix it and the risk of regressions is bigger. 
@lognaturel I know you like it: **The game is not worth the candle** :smile: 

But of course, it's good to know about such a bugs so maybe we should keep it open but add a flag like `won't fix`?

**Comment by lognaturel** [comment]
Hehe, 🕯.

I think we can close. If a user encounters it they/we can search for it and reopen. I think screen rotation while filling a survey is also rare so this is unlikely to happen in normal conditions. Thanks for looking into it @kkrawczyk123 @srv-twry @grzesiek2010!
