### ISSUE TITLE
First launch experience activity

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1680]
#### Software and hardware versions 
Collect v1.11, Android v7.0, Moto M

#### Problem description
In current version of `Collect` app, there is no section that can guide user through the usage of app when it is installed for first time. It is might be difficult for new users to understand how to use `Collect`. 

#### Expected behavior
An introductory section that will run on first install of app that will help users understand basic usage of app.
Proposed section will contain : 
1.Configuring server settings
2.Downloading forms
3.Filling forms
4.Sending to server
5.Links to contact to ODK community.

#### Other information 
Here is the discussion regarding this feature on ODK Forum
https://forum.opendatakit.org/t/faq-or-guide-section-in-odk-collect-android-application/9684

Here is the the first tryout: 
<img src="https://user-images.githubusercontent.com/16358982/33493256-790c1e7a-d6e5-11e7-87b6-8cc3af176b39.gif" width=35%>

Video link : https://www.youtube.com/watch?v=_DGhzUMg-UA&feature=youtu.be

Here is link to library used : 
https://github.com/heinrichreimer/material-intro

#### Issues that need discussion
1. Content.
2. Current tryout has images. Each image is around 20kb. So, Should Images be used?
3. Alternative to images (Current library supports use of layouts.)
3. Should third party library be used (leads to faster development and rapid prototyping but limits functionalities that can be achieved ) or should there be custom implementation (gives flexibility to have any type of behavior but everything needs to be built from scratch)?

Suggestions are welcome!

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Since this is a feature request/suggestion, let's keep the discussion on that forum thread.
