### ISSUE TITLE
All form versions are visible and available 

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1694]
#### Software and hardware versions 
Collect v1.11.1

#### Steps to reproduce the problem
1. Download a form from Aggregate
2. Edit a form and bump the form version
3. Upload that forms to Aggregate
4. Download the updated form

#### Problem description
I can see and use both forms and it's ok but in some cases, it might be good to see and use only the newer one. 
My proposal is to add an option to Admin settings. Something like "Keep older form versions" (true by default). 
Thanks to that someone can disable this option and work only with newest forms.

**Comment by lognaturel** [comment]
Do you imagine this would delete older forms or just hide them?

The older forms may still be needed if they have corresponding instances that can be edited. Hiding them from the form listing would be safe and may be sufficient. Perhaps they could still show up in the delete menu.

**Comment by grzesiek2010** [comment]
@lognaturel 

I would prefer to hide them. It's not a problem, in this case, to keep them in the database and it might be safer.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
