### ISSUE TITLE
pulldata doesn't work on external CSVs with ^M as line ending characters

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1695]
#### Software and hardware versions 
Collect v1.11.1

#### Problem description
Pulldata doesn't work on external CSVs with ^M as carriage returns 

#### Steps to reproduce the problem
Download the form and data below. 
[test.xlsx.zip](https://github.com/opendatakit/collect/files/1543582/test.xlsx.zip)
[test.xml.zip](https://github.com/opendatakit/collect/files/1543615/test.xml.zip)
[data-bad.csv.zip](https://github.com/opendatakit/collect/files/1543585/data-bad.csv.zip)
[data-good.csv.zip](https://github.com/opendatakit/collect/files/1543586/data-good.csv.zip)

Push the form and the good data to the device.
```
adb push test.xml /sdcard/odk/forms/
adb push data-good.csv /sdcard/odk/forms/test-media/data.csv
```
Open the form in Collect. Test with household:`K050003` and member:`05`.  It will pull up a study site: `California`. 

Now push the bad data.
```
adb push data-bad.csv /sdcard/odk/forms/test-media/data.csv
```
Re-open form in Collect. Test with household:`K050003` and member:`05`. It will not pull up any site data.

#### Other information
If you open up the CSVs in vim, you'll see that bad data has `^M` (DOS/Windows) as line ending characters.
<img width="900" alt="data-bad" src="https://user-images.githubusercontent.com/32369/33780849-28a9ee2c-dc07-11e7-94f5-6f74c580cde1.png">

The good data has "proper" newlines.
<img width="395" alt="data-good" src="https://user-images.githubusercontent.com/32369/33780850-28c43340-dc07-11e7-9416-f01ddd3ee624.png">

I have not looked at the SQLite DB that CSVs go into and to see what is written there for both good and bad data, but that might a good place to start.

I have not explored how this works with external itemsets. The behavior there might be different.

**Comment by konishon** [comment]
Apparently
toSafeColumnName in ExternalDataUtil returns "c__key" instead of expected "c_key"
" key" has whitespace at the start. 
```
string.trim(); 
string.replaceAll("\\s+","");
CharMatcher.WHITESPACE.trimFrom(string);

```
None of these could get rid of that pesky whitespace. Now, The start of the text doesn't have a line break and the values in the columns are in good shape.I assume opencsv took care of it.

**Comment by lognaturel** [comment]
> Now, The start of the text doesn't have a line break and the values in the columns are in good shape.I assume opencsv took care of it.

What do you mean by "now"? 😊 Are you talking about a change you made?

**Comment by konishon** [comment]
Oh! I had a look into the table and the ^M  not present there. So my point was the start of the text should not have ^M either way.

**Comment by yanokwa** [comment]
@nishontan, is this an issue that you'd like to send in a PR for? If so, write `@opendatakit-bot claim` as a comment to claim it!

**Comment by lakshyagupta21** [comment]
```
public static String toSafeColumnName(String columnName) {
        // SCTO-567 - begin all column names with "c_" to avoid possible conflicts with
        // reserved keywords; also, escape any potentially-illegal characters
        return "c_" + columnName.trim().replaceAll("[^A-Za-z0-9_]", "_").toLowerCase(
                Locale.ENGLISH);
    }
```
Is there any specific reason why we are replacing illegal characters by `_`  ?
Because this is causing a problem while creating the database the unwanted character gets replaced by `_` so the column name becomes 'c__key' but it is should be 'c_key'.

**Comment by xsteelej** [comment]
@opendatakit-bot claim

**Comment by xsteelej** [comment]
Upon performing a hexdump on _data-bad.csv_ I can see the presence of a byte order mark (BOM) https://en.wikipedia.org/wiki/Byte_order_mark

Java reads the BOM char into a String when reading UTF-8 files, which is a known Java bug: https://bugs.java.com/view_bug.do?bug_id=4508058

In this particular case, it looks like the "key" field is prepended with the BOM and corrupts the key field in the database.

The presence of ^M chars does not appear to be the problem.

I'll fix it and raise a pull request for review.
