### ISSUE TITLE
Add instructions about squashing commits in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dr0pdb** [getodk/collect#1711]
#### Software and hardware versions 

Collect v1.11.1, All

#### Problem description

Add instructions about squashing the commits in pull requests. 

#### Steps to reproduce the problem

NA

#### Expected behavior

There should be instructions about squashing the commits into one with meaningful commit message in the ```CONTRIBUTING.md``` file.

#### Other information 

I do understand this means rewriting the history and not all pull requests need to be squashed into one but the contributor should squash all the WIP and minor changes into one. 

@lognaturel Views ?

**Comment by lognaturel** [comment]
I agree it would be useful to have clearer guidelines around commit messages. The ideal would be small, meaningful commits that make the evolution of the code easy to trace. You can see some examples at https://github.com/opendatakit/collect/commits?author=batkinson 

Some resources I like on the topic are https://dev.bleacherreport.com/small-commits-for-fun-and-profit-part-1-git-add-patch-c0966a562b10 and https://www.bignerdranch.com/blog/small-distinct-commits-say-you-care/. Ideally only the smallest features would involve a single commit.

Right now most contributors' commits don't tend to be very meaningful. In that case, maintainers can squash upon merge but I think we should start to move more aggressively to requiring commits that tell a meaningful story, make review faster and more meaningful and help track down future problems.

**Comment by dr0pdb** [comment]
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
I wonder how to ensure that each of multiple commits for a single file results in something that compiles and runs right. A file is atomic as far as the compiler is concerned.

**Comment by lognaturel** [comment]
This will require deeper policy discussion across the ODK project before it can be an issue to close.
