### ISSUE TITLE
Selected image is not added if location question is answered in form displayed on one page 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1713]
#### Software and hardware versions 
Collect v1.12.0
Collect v1.11.1
Collect v1.10.0

#### Problem description
Selected image is not added if location question is answered in form displayed on one page 

#### Steps to reproduce the problem
1. User fills attached form
2. **User adds answer to location question** (it is required step!)
3. User clicks on 'Choose Image'
4. User selects image

#### Expected behavior
* User sees that image question is answered
* User sees that selected image is visible

#### Actual result
* Collect v1.11.1, v1.12.0 - image is not added 
* Collect v1.10.0 - app crashes
* Problem does not exists if user take a picture via camera

#### Other information 
Form: [OnePageForm.xml.txt](https://github.com/opendatakit/collect/files/1558950/OnePageForm.xml.txt)

**Comment by dr0pdb** [comment]
@mmarciniak90 I am able to reproduce it. The hierarchy view doesn't work either in the form.
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
It might be important and we may want to add this to v1.12.0 @lognaturel what do you think?
If so and you @srv-twry have problems let me know.

**Comment by dr0pdb** [comment]
@grzesiek2010 You can take a look. I am not so familiar with the codebase just yet so i might require more time. Moreover there has been an issue reported about the thousands separator feature hence i will take that.
@opendatakit-bot unclaim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
