### ISSUE TITLE
Ability to choose backward button on first page of TestRepeat.xml form.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#1722]
#### Software and hardware versions 
Collect v1.12.0 beta.0, Android v 6.0, 4.4, 5.1 

#### Problem description
Moving backward button is clickable on first page of the form.

#### Steps to reproduce the problem
1. Go to General Settings/User interface/Navigation and choose "Use forward/backward buttons"
2. Go to Fill blank form and open TestRepeat form.
3. Click on backward button on first page of the form.

#### Expected behavior
Backward button shouldn't be able to use on first page of forms.

#### Other information 
I didn't notice that on other forms that I tested. Problem didn't occur on Collect 1.11.0 so it seems to be regression.
Form in attachment:
[TestRepeat.xml.txt](https://github.com/opendatakit/collect/files/1562290/TestRepeat.xml.txt)

**Comment by akshay-ap** [comment]
I was able to reproduce the issue.
@lognaturel Do you know of any reason why is it happening in v.1.12beta.0 ?
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@akshay-ap The only issue is that the button is enabled, right? I'm able to reproduce that as well. Once I add a repeat the button is disabled again. This is incorrect behavior but it's not very bad and I don't think it's masking any deeper bugs. I don't know off the top of my head what might be causing it but it would be great if you could look into it and share your findings, @akshay-ap.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
