### ISSUE TITLE
More than one date dialog is opened when user quickly clicks the button several times

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1723]
#### Software and hardware versions 
Collect v1.12.0

#### Problem description
More than one date dialog is opened when user quickly clicks the button several times

#### Steps to reproduce the problem
1. User quickly clicks the 'Select date' button several times
2. Dialog appears
3. User selects date and clicks OK
4. User sees that additional dialog is visible with default date

#### Expected behavior
User is not able to open two dialogs

#### Other information 
Problem related to https://github.com/opendatakit/collect/issues/1624. 
Noticed during release testing

**Comment by dr0pdb** [comment]
Able to reproduce. 
@opendatakit-bot claim
