### ISSUE TITLE
A message about available form update is visible if we use zipped media files like csv file

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1729]
#### Software and hardware versions 
Collect v1.12.0beta

#### Problem description
A message about available form update is visible if we use zipped media files like csv file

#### Steps to reproduce the problem
1. Use `https://nafundi-test.appspot.com`
2. Download `cascading select external itemsets` form
3. Open downloaded form.
4. Go to `Get Blank Form` list

#### Expected behavior
A message about available updated form shouldn't be visible for `cascading select external itemsets` form.

**Comment by akshay-ap** [comment]
@grzesiek2010  I am trying to reproduce the problem. Can you elaborate `3. Open downloaded form.`?
I tried opening the form using file manager. Is that what you mean?

**Comment by grzesiek2010** [comment]
@akshay-ap 

by `Open downloaded form` I mean start filling such a form.
This issue is part of my work on form updates so I'll take it. I saw you claimed #1722 so I think you have something to do.

@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
I investigated the issue and there is no easy way to fix the problem and check for updates when we use compressed files.

Here is an example of the manifest file we use https://nafundi-test.appspot.com/xformsManifest?formId=samplepreload
That file contains an md5 hash but this hash is for the compressed file. When we download that form and start filling the compressed file is extracted and removed so we have only a csv file we want and need. 
Then the hash of csv file is different than the hash of compressed file of course. If I compress the extracted file again to get a hash it will be different too since the generated archive does not only contain the compressed file data, but also some additional attributes (dates probably etc?) .

The only solution here is to send two hashes or even only a hash of extracted file not a hash of a compressed file.

@lognaturel 
what do you think?

**Comment by grzesiek2010** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
As of Central 0.4, CSV attachments are gzipped if the client accepts it (see [forum](https://forum.getodk.org/t/odk-central-support-for-zipped-media-files/16481/6?u=ln)). Central does NOT support uploading a zip file manually.
