### ISSUE TITLE
Improve repeat interface

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1733]
#### Software and hardware versions 
Collect v1.11, Android v7.0, device used Moto M

#### Problem description
In case of nested repeated groups, it is difficult for users to understand the process of form filling.
This has been discussed here : https://opendatakit.slack.com/archives/C4146P8TA/p1511391416000104

#### Steps to reproduce the problem
Link to nested repeat form : https://opendatakit.slack.com/files/U35QXEX8F/F85JESH2T/nested-repeats.xml.txt

#### Expected behavior
 A simpler interface that would be easier to understand from user's perspective.
#### Other information 
I think a `ListView` would be a better option. Instead of swiping left to add new repeat groups, users will click `add repeat/ group button` on same widget and an entry will be added to `listView` after data has been filled.

**Comment by lognaturel** [comment]
This would work better as a forum conversation because it is very open-ended.
