### ISSUE TITLE
Taking picture needs to take 2 snapshot before accepting

### ISSUE THREAD

**Issue by rahman9909** [getodk/collect#1736]
#### Software and hardware versions 
Collect v1.11.1, Android v6.0.1, device used...

#### Problem description
Taking picture needs to take 2 times before accepting the picture. It takes two snapshots and then shows the image in app. 
#### Steps to reproduce the problem
just take picture widget and try to take a picture
#### Expected behavior
It will take one picture and still wait for to take another picture before goes back to the app.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
@rahman9909 
I think it's a problem with the camera app you use. Could you tell us what it is? Have you noticed the same problem using that app without the ODK Collect?

**Comment by lognaturel** [comment]
This is very unlikely to be a Collect bug. @rahman9909 if you answer @grzesiek2010's questions we could look into it further.
