### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1737]
#### Software and hardware versions 
Collect v1.12.0

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/7e0343c8?reportTypes=REPORT_TYPE_UNSPECIFIED&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/1b4f7f56?reportTypes=REPORT_TYPE_UNSPECIFIED&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/9c7d60d2?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/f8bc9527?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

#### Steps to reproduce the problem
1. Download a form with media files like `All Widgets` form
2. Remove media folder manually
3. Open the list of available forms

#### Expected behavior
You can see the list and you can see that a newer version of `All Widgets` form is available

**Comment by lognaturel** [comment]
I'm confused about how this is happening on so many different devices. Seems somehow people have a media directory in the DB but no actual directory? Or are getting an I/O error?

**Comment by grzesiek2010** [comment]
@lognaturel I thought it was the problem since I was able to reproduce the issue but looks like it wasn't the only bug.
I can still see lots of crashes in Firebase. Here is a second fix #1748
