### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1739]
#### Software and hardware versions 
Collect v1.12.0

#### Problem description

> Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:325)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
arrow_drop_down
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
org.odk.collect.android.tasks.DownloadFormsTask.getMd5Hash (DownloadFormsTask.java:758)
org.odk.collect.android.tasks.DownloadFormListTask.doInBackground (DownloadFormListTask.java:233)
org.odk.collect.android.tasks.DownloadFormListTask.doInBackground (DownloadFormListTask.java:52)
android.os.AsyncTask$2.call (AsyncTask.java:305)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:243)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/b84b13e4?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2608

https://play.google.com/apps/publish/?account=6923365842552008664&dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=2608&clusterName=apps/org.odk.collect.android/clusters/b84b13e4&detailsSpan=7

#### Other information 
It's not a big problem, only about 12-14 reports.

**Comment by lognaturel** [comment]
This code hasn't changed, right? It's moved around which is why it's being flagged as a new crash but is there anything new that would explain a null hash? Are certain servers sending down media files without properly populating the manifest?

**Comment by grzesiek2010** [comment]
> This code hasn't changed, right?

right.

> Are certain servers sending down media files without properly populating the manifest?

It's a hash for forms, not media files. Probably the received values are null don't know why.

**Comment by lognaturel** [comment]
If a particular server implementation hasn't sent the form hash then form listing in Collect never would have worked so that doesn't seem likely. I wonder whether the formList or manifest XML could be getting corrupt or only partially transferred somehow.
