### ISSUE TITLE
'Connecting to Server' dialog is not closed automatically if user changes device orientation 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1741]
#### Software and hardware versions 
Collect v1.11

#### Problem description
Connecting to Server dialog is not closed automatically if user changes device orientation 

#### Steps to reproduce the problem
1. User goes to 'Get Blank Form'
2. User sees dialog 'Connecting to Server'
3. User changes device orientation
4. Dialog is not auto closed when forms are loaded
![screenshot_2017-12-19-02-31-42](https://user-images.githubusercontent.com/3907554/34153038-e78f77c4-e4b0-11e7-81e3-5dfc6cee31be.png)

#### Expected behavior
Dialog 'Connecting to Server' is closed automatically when forms are loaded even if user changes device orientation

**Comment by codedsun** [comment]
I would like to work on the issue @lognaturel

**Comment by lognaturel** [comment]
That sounds great, @codedsun! Please use `@opendatakit-bot claim` to claim it.

**Comment by codedsun** [comment]
@lognaturel I am encountering one more issue in this, that when the forms are not loaded and we change the  orientation, the dialog is shown but no data is fetched and changing back the orientation will fetch the form list.

**Comment by codedsun** [comment]
@lognaturel  @grzesiek2010 I debugged and found that, that we have put the key that it contains the form list, and in onCreateMethod( ) when I checked the size of formlist it says to 0.
and we are not getting as an instance of DownloadFormList Task hence the downloading is not done and getLastNonConfigurationInstance is also of Fragment, hence this condition also goes to false.

`else if (formNamesAndURLs.isEmpty() && getLastNonConfigurationInstance() == null)
 {
            // first time, so get the formlist
            downloadFormList();
        }`

Shall I file a new issue regarding this?

**Comment by grzesiek2010** [comment]
@codedsun I think it might be the same issue. You said that the dialog is shown but no data is fetched and I guess that's why it's not closed.

If you are sure it's a separate case (after debugging and analyzing the code) you can create another issue but as I said I guess it's the same.

**Comment by ShivamArora** [comment]
@opendatakit-bot claim

**Comment by ShivamArora** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
