### ISSUE TITLE
When running Collect on a TV, scrollbars are too wide

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1745]
#### Software and hardware versions 
Collect v1.12, H96 PRO with Android 7.1.2

#### Problem description
When running Collect on a TV, scrollbars are too wide.
![img_0096](https://user-images.githubusercontent.com/32369/34169040-17f79da8-e4b4-11e7-80fa-3af801cdbc8b.jpg)

#### Steps to reproduce the problem
Load Collect on a device with a large screen. Try to download a blank form.

#### Expected behavior
Reasonably sized scrollbars. Is there an Android standard for how to render scrollbars on large-screen devices? Let's discuss that first before moving on to a PR.

**Comment by lognaturel** [comment]
Let's wait for a user to actually request this.
