### ISSUE TITLE
NPE getting form version status

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1746]
#### Software and hardware versions 
Collect v1.12.0

#### Problem description
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.odk.collect.android.logic.FormDetails.isNewerFormVersionAvailable()' on a null object reference
org.odk.collect.android.adapters.FormDownloadListAdapter.getView (FormDownloadListAdapter.java:76)
android.widget.AbsListView.obtainView (AbsListView.java:3170)
android.widget.ListView.makeAndAddView (ListView.java:2140)
android.widget.ListView.fillDown (ListView.java:762)
android.widget.ListView.fillFromTop (ListView.java:826)
android.widget.ListView.layoutChildren (ListView.java:1865)
android.widget.AbsListView.onLayout (AbsListView.java:2942)
android.view.View.layout (View.java:18878)
android.view.ViewGroup.layout (ViewGroup.java:5953)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1741)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1585)
android.widget.LinearLayout.onLayout (LinearLayout.java:1494)
```
I think this means that a form that is in `filteredFormList` is not in `formNamesAndURLs` which seems like a bad state.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
@lognaturel the problem still occurs https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/30d69c8a?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2612

https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/6f382b96?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2612

but it's not common.

**Comment by lognaturel** [comment]
@grzesiek2010 That's a different problem! For this one, the issue was that a formID that was present in the filtered list wasn't found in the map of all ids to details. The other one is that there is no form at a given position in the filtered list. I've filed it at #1756.
