### ISSUE TITLE
Add support for SVG image assets

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1763]
If an SVG image is used, it is currently reported as invalid. Try form https://docs.google.com/spreadsheets/d/17eDX7wYPsZnvk6nHzx3WkwHADXqj1IJezK6zE5SiSu4/edit#gid=0 with media [svg-images-media.zip](https://github.com/opendatakit/collect/files/1613463/svg-images-media.zip) to reproduce.

Allow SVG images. I think they should always scale to fit the device width but if you have other ideas, please share in comments.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
This was really just as a stepping stone to #1764. I don't think we need to support svgs aside from that.
