### ISSUE TITLE
User is able to add Fallback submission URL easily

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1773]
#### Problem description
It could be difficult to add a Fallback submission URL. User need to get a URL to Copy/Paste memory.
Other way is put the full URL manually.

I use external barcode scanner to scan a QR code with the URL and then I copy it to Fallback submission URL field.
It could be a good feature for users to allow opening a barcode scanner directly from ODK Collect

Other idea is using OCR function instead of barcode scanner.

#### Steps to reproduce the problem
1. User goes to `General Settings` -> `Server`
2. User changes `Type` to `Google Drive, Google Sheets`
3. User adds `Fallback submission URL `
#### Expected behavior
Adding Fallback submission URL should be easily

**Comment by lognaturel** [comment]
That's an interesting one! Hopefully fallback URL isn't generally needed so I don't know how important it is to make this easier. In fact, maybe the fact that it's hard is a useful deterrent? Any one else have thoughts on this?

**Comment by shobhitagarwal1612** [comment]
@lognaturel I would like to work on this issue. I can think of creating a UI which displays all google sheets which are present in the chosen google account's drive. Maybe once it is easier to use, more people will start using it given that it is so easy to setup than compared to aggregate. We can even add an option to share the google sheets with other people from the app itself using the Sheets API.

@lognaturel @yanokwa What are your thoughts?

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
