### ISSUE TITLE
User sees confusing toast in case with Server Required Authentication appears

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1778]
#### Software and hardware versions 
Verified on Collect v1.11.1

#### Problem description
User sees confusing toast after specific steps when Server Required Authentication appears

#### Steps to reproduce the problem
1. User sees dialog:
<img src="https://user-images.githubusercontent.com/3907554/34820680-26730928-f6b9-11e7-9470-af90d9148e76.png" height="40%" width="40%" >

2. User does not put credentials and clicks OK button
3. User sees the dialog again and clicks on Cancel button
4. User is moved to `Send Finalized Form` page and form is selected
5. User clicks on `Send Selected` button
6. User sees toast with information `Sorry, you have not selected any forms!`
<img src="https://user-images.githubusercontent.com/3907554/34820903-e19435c4-f6b9-11e7-8649-b29ba5046fe8.png" height="40%" width="40%" >

#### Expected behavior
- Option 1: Form is unselected on `Send Finalized Form` page
- Option 2: ODK Collect detects that form is selected and confusing toast is not displayed

#### Other information 
Discovered during testing https://github.com/opendatakit/collect/pull/1768

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
