### ISSUE TITLE
Range widget with appearance="picker" starts with an incorrect value

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1782]
#### Software and hardware versions 
Verified on Collect v1.11.0

#### Problem description
Range widget with appearance="picker" starts from incorrect value

#### Steps to reproduce the problem
1. User starts form with Range widget with appearance="picker"
2. User sees question
3. User sees 10 as a first value, next to 2
<img src="https://user-images.githubusercontent.com/3907554/34830304-66ffd5ee-f6db-11e7-93a0-4f5636303de9.png" height="40%" width="40%" >

4. Values back to normal when user swipes
<img src="https://user-images.githubusercontent.com/3907554/34830361-8a0c8e56-f6db-11e7-9c21-f121f2950729.png" height="40%" width="40%" >

#### Expected behavior
First value is 1

Used form: 
[All widgets.xml.txt](https://github.com/opendatakit/collect/files/1622975/All.widgets.xml.txt)

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by akshay-ap** [comment]
I am working on it.

**Comment by akshay-ap** [comment]
I am trying to find the cause of such behavior.
In `org.odk.collect.android.fragments.dialogs.NumberPickerDialog.onCreateDialog()` method ,
I added `Log.i("===: ","numberPicker.getValue() :"  + String.valueOf(numberPicker.getValue()));` for debugging. 
![debug](https://user-images.githubusercontent.com/16358982/35191228-9a8a8036-fe9b-11e7-8cb6-37809862b7fe.png)

The display value array is [10,9,8,7,6,5,4,3,2,1] stored in `getArguments().getSerializable(DISPLAYED_VALUES)`

The logged value `9` seems to be correct as it is expected `1` on the screen. But, the displayed value is `10` on the screen which is at index `0`.
I am unable to find reason for such behavior.

**Comment by grzesiek2010** [comment]
It looks as if it's an Android bug. I was surprised because I tried to reproduce the issue and I used my Samsung Galaxy S4 with Android 5 (everything is ok) then I used Android 4.4. (everything is ok), Android 4.2 (everything is ok too)... Android 7 - yes I can reproduce the issue using that device, but I also can confirm that the list of displayed values is well prepared. And even if you select that wrong "10" the displayed value is 1 as expected so only the displayed in the NumberPicker value is wrong but the original one is ok.

What even weirder the problem takes place when we have a range 1-10 but everything is ok if I use 1-7 :smile: looks as if Android confuses 1 with 10 and 11 (I didn't check other numbers).

**Comment by akshay-ap** [comment]
If default value anything other than `1`, everything works fine. Like if default is set to `2` the number picker shows values correctly.

**Comment by grzesiek2010** [comment]
> If default value anything other than 1, everything works fine.

That's not true. I tested this form 
[range.xlsx](https://github.com/opendatakit/collect/files/1681900/range.xlsx) and the same issue is when we have a range: 
2-20 then 20 is displayed
2-22 then 22 is displayed etc.

Looks like a very strange bug in Android OS and there is nothing we can do here but we can keep this issue just to know about this bug.

**Comment by grzesiek2010** [comment]
@lognaturel @akshay-ap I created a sample project to confirm it's not our bug the project is here: https://github.com/grzesiek2010/NumberPickerBug and I also reported the issue here: https://issuetracker.google.com/issues/72690635

That's all we can do.

**Comment by akshay-ap** [comment]
@grzesiek2010  Thanks for correcting.

**Comment by lognaturel** [comment]
Nice report, @grzesiek2010. Let's close this since it's not a Collect issue. Please update here once you hear more from Google.
