### ISSUE TITLE
Choose an account dialog starts with no option initially selected.

### ISSUE THREAD

**Issue by dr0pdb** [getodk/collect#1786]
#### Software and hardware versions 
Collect v1.12.x, Android v5.1.1, device used Oppo f1

#### Problem description
The "Choose an account" dialog starts without any option initially selected.

#### Steps to reproduce the problem
General settings -> Server -> Set type to Google drive,sheets -> Now select Google account

#### Expected behavior
The dialog should start with the previously selected google account (if it exists) or the first option.

#### Other information 
Found while working on #1777 
Certainly not a problem but most app have one option as a default one in radio options dialog.

**Comment by marcparicio** [comment]
@opendatakit-bot claim

**Comment by ghost** [comment]
@opendatakit-bot claim
