### ISSUE TITLE
Get Blank Form list disappears after canceling refresh and then selecting clear all/select all button.  

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#1793]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Get Blank Form list disappears after canceling refresh and then selecting clear all/select all button.  

#### Steps to reproduce the problem
1. Go to Get Blank Form
2. Click on "Refresh" button.
3. Cancel that process.
4. Click on Select All or Clear All button.

#### Expected behavior
Get Blank Form shouldn't disappear at all. 

#### Other information 
Screenshot attached. Notice that Get Selected button should not be available in that situation too. 
![screenshot_get](https://user-images.githubusercontent.com/33342488/35035460-b9114ec2-fb71-11e7-8c2b-da9bcc2540b7.png)

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
@lognaturel Please close this issue.
