### ISSUE TITLE
Collect crash when canceling refresh and then clicking on checklist.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#1796]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Collect crash when canceling refresh and then clicking on checklist.

#### Steps to reproduce the problem
1. Go to Get Blank Form.
2. Click on "Refresh" button.
3. Cancel that process.
4. Try to select any item from the checklist.

#### Expected behavior
Collect should not crash.

#### Other information 
It doesnt't matter if items from the checklist ale selected or not, the same error occurs. 
Screenshot of behavior attached.
![screenshot_crash](https://user-images.githubusercontent.com/33342488/35036235-06ff2b20-fb74-11e7-9e75-6f3e452cb3e8.png)

**Comment by grzesiek2010** [comment]
Awesome you reproduced one of the most common issues I can see in the Firebase list.
https://console.firebase.google.com/u/0/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/d7a24a06?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2612

> Exception java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(16908298, class android.widget.ListView) with Adapter(class org.odk.collect.android.adapters.FormDownloadListAdapter)]
android.widget.ListView.layoutChildren (ListView.java:1562)
android.widget.AbsListView.onTouchUp (AbsListView.java:3979)
android.widget.AbsListView.onTouchEvent (AbsListView.java:3762)
android.view.View.dispatchTouchEvent (View.java:8502)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2428)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2109)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2434)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2123)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2434)

I hadn't known which list is faulty before.

**Comment by lakshyagupta21** [comment]
Can I work on this issue?

**Comment by grzesiek2010** [comment]
@lakshyagupta21 yes, please. You can add a comment to assign you to the issue https://forum.opendatakit.org/t/fine-grained-permissions-for-github-issues-self-assign-labels/9352/9?u=grzesiek2010

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
