### ISSUE TITLE
Suboptimal implementation of splash screens

### ISSUE THREAD

**Issue by samagra14** [getodk/collect#1803]
#### Software and hardware versions 
Collect debug , Android v 8.0.0, device used = MiA1

#### Problem description
Currently, the splash screen is implemented via a dedicated splash activity which is not an optimal way of implementing splash screens. Moreover setting up SharedPref and other functionalities in the splash activity is also suboptimal. The correct way of implementing splash screens as stated by Google can be found on the link below :-
https://android.jlelse.eu/launch-screen-in-android-the-right-way-aca7e8c31f52
If you build the app from the code, then in a few instances, the splash activity is not visible at all. This is because the SharedPreferences are checked and whether to show the splash screen or not is determined.

#### Steps to reproduce the problem
Just build the app and launch it. If you have chosen to not show the splash screen, then nothing will be visible for a few seconds and then the main activity will be started. This is a bad User Experience.
Besides this, even if the splash screen is shown, it is implemented in a wrong manner. There will be no advantage of the splash screen during a cold startup.

#### Expected behaviour
Splash screens are a part of Android Architecture and there should be no checks to determine whether to show the splash screen or not. It must be shown at all the times when the app is experiencing cold startup.Otherwise, the UI will become unresponsive.

#### Other information 
To resolve this issue, a new Theme has to be implemented and the splash screen should be used in the form of a drawable and then applied to the windowBackground theme. Also, the code which is performed in the splash activity should be moved to the MainMenuActivity.
Besides, Splash Screens are shown only when during cold startup. If there is no splash screen during cold startup, then there will be no responsiveness and the UI will appear frozen.

For more information, see this : 
https://material.io/guidelines/patterns/launch-screens.html#

**Comment by lognaturel** [comment]
As discussed in Slack, this splash screen has a little bit of an unusual purpose. It was added primarily to provide a branding opportunity, not to increase responsiveness.
