### ISSUE TITLE
User should see buttons on Get Blank Form list even if the list is empty

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1805]
#### Software and hardware versions 
Collect with https://github.com/opendatakit/collect/pull/1799

#### Problem description
User should see buttons on `Get Blank Form` list even if the list is empty

#### Steps to reproduce the problem
1. User goes to `Get Blank Form`
2. User clicks on Refresh
3. User cancels
4. User sees empty form list:
<img src="https://user-images.githubusercontent.com/3907554/35274549-590ab6e0-0034-11e8-9433-78839776dd24.png" height="40%" width="40%" >
5. User needs to move back to main screen and again open `Get Blank Form`

#### Expected behavior
* Attached view contains  `Select All` / `Refresh` / `Get selected`
* Only `Refresh` button is active.

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
