### ISSUE TITLE
Misleading error message on malformed formList XML

### ISSUE THREAD

**Issue by issa-tseng** [getodk/collect#1811]
https://github.com/opendatakit/collect/blob/7d725d760e71e95467f3f2fc847e9638a55dabb9/collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java#L221

1. The code is actually checking tags _and values_ so the error may be triggered with a tag present but no value in the tag.
2. `formId` should be `formID`.

**Comment by raks097** [comment]
I have a few questions regarding this issue:
Do you mean the formId in the error message be formID or the variable formId which is being used.?
I  think formId as a variable need not be changed.
Clarification on this would really help me in fixing this issue

**Comment by raks097** [comment]
@opendatakit-bot claim

**Comment by raks097** [comment]
@clint-tseng  Isn't it the intended behaviour that an error message is shown if that tag doesn't have a value?

**Comment by issa-tseng** [comment]
1. The XML tagname is formID, not formId. So if a person sees an error message that says “formId is missing”, they are going to think that they need to add a tag called `formId`, and they are going to be confused when it still thinks it’s missing.
2. The error message right now says that it is “missing” the “tag”, but if you _do_ have the tag `<formID></formID>` it still tells you the tag is missing even though you have provided it. What it means to communicate is that not only must the tag be present, but it must also contain a value.

I would propose an error message similar to the following: “a required tag is missing or empty: formID, name, or downloadUrl”.

**Comment by raks097** [comment]
> The XML tagname is formID, not formId. So if a person sees an error message that says “formId is missing”, they are going to think that they need to add a tag called formId, and they are going to be confused when it still thinks it’s missing.
> The error message right now says that it is “missing” the “tag”, but if you do have the tag <formID></formID> it still tells you the tag is missing even though you have provided it. What it means to communicate is that not only must the tag be present, but it must also contain a value.

@clint-tseng  Thank you for the clarification.
I'd like to point out that a similar kind of misleading message can found in line 275 in the same java file.
I'd be fixing that as well
