### ISSUE TITLE
Use Lombok to reduce boilerplate code in POJOs

### ISSUE THREAD

**Issue by dr0pdb** [getodk/collect#1815]
#### Software and hardware versions 
Not specific to a particular version.

#### Problem description
Currently there is a lot of boilerplate code such as getters and setters in POJOs.

#### Expected behavior
We can make use of a stable and very popular library [Lombok](https://projectlombok.org/) which through annotation processing provides us with getters and setters automatically. 

###### PROS:
1. Lesser boilerplate code.
2. Modern industry standard.
3. Very simple to work with (Only needs ```@Data``` annotation).

###### CONS:
1. Will require the lombok plugin to be installed in Android studio.

@lognaturel @grzesiek2010 What are your views ?

**Comment by heyjamesknight** [comment]
Downvote for plugin install.

**Comment by dcbriccetti** [comment]
Cliff Click makes a case for not using getters and setters in many cases.
http://cliffc.org/blog/2018/01/18/getters-and-setters/
https://www.quora.com/Are-we-supposed-to-use-getters-and-setters-for-every-instance-variable-in-real-life-Java-programs-or-is-it-just-something-they-tell-you-at-the-university/answer/Cliff-Click-3
Scala removes the usual Java boilerplate. What about Kotlin?

**Comment by lognaturel** [comment]
Thanks for the idea @srv-twry! In general I think we should stay away from refactors for their own sake. Perhaps if there's some new code that needs to be written and new dependencies can address user needs then they should be considered.
