### ISSUE TITLE
Toasty/Snacky library

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1819]
Recently I have run into a pretty nice library called [Toasty](https://github.com/GrenderG/Toasty) which makes regular toast more meaningful by adding icons and colors. I think it might be something we should rethink. Now we use only grey toasts without any icons. They look the same for good information and for errors. Sometimes they are barely visible.

Here is a similar lib but fo snackbars called [Snacky](https://github.com/matecode/Snacky).

@lognaturel @yanokwa what do you think? Let me know if you find it useful I can go ahead then.

**Comment by lognaturel** [comment]
If there's a specific need for a richer toast in the future, let's file that specific issue with a clear user benefit.
