### ISSUE TITLE
User should see visual difference between the nested groups with `field-list` appearance

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1823]
#### Software and hardware versions 
Collect with https://github.com/opendatakit/collect/pull/1821

#### Problem description
User does not see nested group names in form with `field-list` appearance.

#### Steps to reproduce the problem
1. User creates form with few nested groups with `field-list` appearance, e.g.:
![g3](https://user-images.githubusercontent.com/3907554/35724170-b72b6e78-07f4-11e8-8f34-5f50a10820cc.png)
2. User starts form
<img src="https://user-images.githubusercontent.com/3907554/35724230-e7c1cee2-07f4-11e8-874b-64bf94979059.png" height="40%" width="40%" >
3. There is no visual difference between the groups

#### Expected behavior
* User sees nested group names
* User should not have doubts as to which group the question belongs to

**Comment by mmarciniak90** [comment]
We need to discussion about ways to identify nested groups.
One way is to add 'g1 > g2', 'g2 > g3' tag above a question text.

@opendatakit-bot label "needs discussion"

**Comment by grzesiek2010** [comment]
Yeah this is tough... probably the best solution is to display a group name always if a group name of the previous question was different? That's all we can't eg highlight groups using different colors because we can have multiple nested groups and it doesn't make sense.

**Comment by lognaturel** [comment]
I imagine that for now if people use groups inside of field lists it's more for logical grouping than for display. I would say we leave this as-is for now and perhaps reconsider once #378 is addressed because at that point using longer field-lists will be much more compelling.
