### ISSUE TITLE
Message in 'field-list' error is doubled

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1826]
#### Software and hardware versions 
Verified on Collect v1.12.2
Issue noticed during testing https://github.com/opendatakit/collect/pull/1821

#### Problem description
Message in 'field-list' error is doubled

#### Steps to reproduce the problem
1. User starts form with repeat group with `field-list` appearance
* I used this form:  [g6Error.xml.txt](https://github.com/opendatakit/collect/files/1689060/g6Error.xml.txt)
2. User sees error message
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/35729944-3d2d3ba6-0808-11e8-9e23-5613404ff072.png">
3. Error message is doubled

#### Expected behavior
* Error message is not doubled

**Comment by S2606** [comment]
@opendatakit-bot claim

**Comment by S2606** [comment]
@opendatakit-bot claim

**Comment by S2606** [comment]
@mmarciniak90 Sorry for not asking before claiming but can i work on this?

**Comment by dr0pdb** [comment]
@S2606 Please go ahead. You can work on any unclaimed issue. If she wanted to work on it, she would have claimed it. you don't have to ask :smile:

**Comment by abdulwd** [comment]
@opendatakit-bot claim

**Comment by abdulwd** [comment]
@opendatakit-bot unclaim

**Comment by Mrunzzz** [comment]
@opendatakit-bot claim

**Comment by Mrunzzz** [comment]
@mmarciniak90 I couldnt find this in the project. Please direct me to it

**Comment by mmarciniak90** [comment]
@Mrunzzz  use `Ctrl` + `Shift` + `F` and try to find `Only questions are allowed in 'field-list'` in project

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
If `e.getMessage()` equals with `e.getCause().getMessage()`, we don't have to show them both. All we need to do is to add a judgement. :)
