### ISSUE TITLE
Where is this package/class located?

### ISSUE THREAD

**Issue by abelcallejo** [getodk/collect#1832]
https://github.com/opendatakit/collect/blob/f8dd3949763b93e05f9acdd61ebaaf899cb98653/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L46

**Comment by dr0pdb** [comment]
@abelcallejo Hi!, It is a dynamically generated class, i.e. it is generated at the time you build your application. 
Infact, you're not supposed to edit this file. What is the problem that you're facing for which you want to know it's location ?
