### ISSUE TITLE
Loading form does not end when it contains an empty field-list group

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1833]
#### Software and hardware versions 
Collect v1.12.2
Android 5.1 and above.

#### Problem description
Loading form does not end in specific form with metadata

#### Steps to reproduce the problem
* User starts form: [metadata2.xml.txt](https://github.com/opendatakit/collect/files/1689484/metadata2.xml.txt)
* Loading form does not end on Android 5.1 and above.

#### Expected behavior
* Error message is visible
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/35735525-12da6c9c-081d-11e8-9073-3a2dc0b86891.png">

#### Other information 
*  Issue noticed during testing https://github.com/opendatakit/collect/pull/1821

**Comment by huangyz0918** [comment]
In my Android simulators, there are no differences with different APIs.
The devices in Android 4.2 , 4.4, 5.1, 8.1, 7.0 , all of them don't have this error dialog, just `ArrayIndexOutOfBoundsException` and a looped `FormEntryActivity.createView` in debugger. So my understanding is we should put these error messages in an error dialog ? right ? @mmarciniak90 @lognaturel 

PS. My Collect version is: v1.14.0

**Comment by lognaturel** [comment]
It’s not immediately clear to me that this form should fail. I think a good first step would be to isolate the failure. Is it the itext call that is a problem? The empty field list? Then we can better decide if there’s a fix or whether the error dialog should be shown.

**Comment by huangyz0918** [comment]
This exception would crash our App, I agree with you to isolate this failure first.
As you said, this exception was caused by **The empty field list**, I have added some `<input> </input>` in `<group appearance="field-list">` in this form, and it worked. 

<img src="https://i.loli.net/2018/04/01/5ac101b67a7f1.jpg" width = "300"  align=center />

Maybe we can build an error dialog in this case.
@lognaturel  anyway, happy weekend :)

**Comment by huangyz0918** [comment]
When field list is empty, method `stepOverGroup()` and `stepToNextEvent(boolean stepIntoGroup)` would call each other without an end. I think I can simply break this infinity loop and show an error dialog with `return stepToNextEvent(STEP_INTO_GROUP);` in `FormController`, but different APIs may have different error messages. I don't know if we should build a specific dialog or just simply break this loop.

@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot I'm waiting for someone to review my solution ; ) 
It would be ok soon, so be patient.

**Comment by huangyz0918** [comment]
@opendatakit-bot I'm waiting for someone to review my solution ; ) 
It would be ok soon, so be patient.
