### ISSUE TITLE
`Selected:` text is visible below the button in Select multiple question with `minimal` appearance even if nothing selected

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1838]
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Problem description
`Selected:` text is visible below the button in Select multiple question with `minimal` appearance even if nothing selected.
It disappears after removing response.

#### Steps to reproduce the problem
You can use All Widgets form available on the aggregate demo server.
1. Go to Select multiple question with `minimal` appearance
2. `Selected:` is visible below the button.
3. Add any answer
4. Remove response

#### Expected behavior
That text should be visible only if any option is selected.

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by dr0pdb** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Hi @srv-twry! Thanks so much for all the great help on Collect. Since you’re now a veteran, please leave quick wins for new contributors! Big thanks also for welcoming new people. If you notice other small issues like this that need fixing, creating quick win issues is a huge help. 😊

**Comment by dr0pdb** [comment]
Sure @lognaturel , will leave them from now, and also create them if i notice some. 😊

**Comment by lognaturel** [comment]
You are awesome, thanks! 😎
