### ISSUE TITLE
Selected options from select multiple question are not separated in hierarchy view.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1839]
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Problem description
Selected options from select multiple question are not separated in hierarchy view.

#### Steps to reproduce the problem
1. Use any form with select multiple question.
2. Select at least two options.
3. Go to hierarchy view.

#### Expected behavior
Selected options from select multiple question should be separated by a comma or a semicolon in hierarchy view.

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by akshay-ap** [comment]
`org.javarosa.form.api.FormEntryPrompt` builds a string of selected values in `SelectMultiData`.

To view `,` separated values in hierarchy view, I suggest the following change in `org.javarosa.form.api.FormEntryPrompt.getAnswerText()`  line 179 onwards:

           StringBuilder b = new StringBuilder();
             List<Selection> values = (List<Selection>)data.getValue();
                 for(Selection value : values) {
                     //Old
                     //b.append(this.getSelectItemText(value)).append(" ");
                     //Suggested change
                     b.append(this.getSelectItemText(value)).append(", ");
                 }
                 text = b.toString();

I don't think it is possible to do it by any other way. 
@grzesiek2010 What do you think?

**Comment by akshay-ap** [comment]
After the above change, here is the result.
<img src=https://user-images.githubusercontent.com/16358982/35902264-8dab666a-0c00-11e8-9fff-87f589e4a957.png width=35%>

**Comment by shobhitagarwal1612** [comment]
There shouldn't be any trailing commas.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
why? If you have options with space it's not legible at all.

**Comment by shobhitagarwal1612** [comment]
> There shouldn't be any trailing commas.

I meant the last one, after `D`
It should be `A, B, C, D` and not `A, B, C, D,`

**Comment by grzesiek2010** [comment]
@akshay-ap 

If it's on the Javarosa's side it needs discussion because it might affect other tools which use that library. But I think you can also build that text on your own... you know use `org.javarosa.form.api.FormEntryPrompt.getAnswerText()` by default but if a data type is select multiple the use your custom way.

**Comment by akshay-ap** [comment]
@grzesiek2010 Thanks for the suggestion.
Here is the change in `org.odk.collect.android.utilities.FormEntryPromptUtils`

```
if (data instanceof SelectMultiData) {
            String text;
            StringBuilder b = new StringBuilder();
            List<Selection> values = (List<Selection>)data.getValue();
            for(Selection value : values) {
                b.append(fep.getSelectItemText(value)).append(", ");
            }
            b.delete(b.length()-2,b.length());
            text = b.toString();
            return text;
        }
```
No need for any change on `javarosa` side.

**Comment by grzesiek2010** [comment]
yes something like that.

**Comment by akshay-ap** [comment]
Shall I issue PR?

**Comment by grzesiek2010** [comment]
Sure go ahead.
