### ISSUE TITLE
Thre is a space between the status bar and the toolbar in `General Settings`

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1844]
#### Software and hardware versions 
Collect v1.12.2 an older versions
Samsung Galaxy S4, Android 5.0.1

#### Problem description
Thre is a space between the status bar and the toolbar in `General Settings`.

#### Steps to reproduce the problem
![screenshot_2018-02-08-12-22-36](https://user-images.githubusercontent.com/3276264/36005630-da282dfa-0d38-11e8-8656-553317719c7e.png)

**Comment by grzesiek2010** [comment]
It might be something tricky so I would mark this issue as:
@opendatakit-bot label "contributor friendly"

**Comment by lakshyagupta21** [comment]
I tried to check if something is present between status bar and toolbar by enabling "show layout bounds" but I didn't find the extra space. Have you tried to look for the issue on other devices also?
![screenshot_2018-02-09-23-33-11-590_org odk collect android](https://user-images.githubusercontent.com/18495162/36042907-7a9ba086-0df3-11e8-8c78-2a2dcd736f6d.png)

**Comment by grzesiek2010** [comment]
Yes, I think it's visible only on some devices / Android versions.

**Comment by prashulstha** [comment]
The issue is because of the layout attributes we give to the toolbar. I had similar problem. The solution is to use assign True to alignParentTop.

**Comment by rishabhkalra96** [comment]
@opendatakit-bot claim

**Comment by rishabhkalra96** [comment]
@opendatakit-bot claim

**Comment by prashulstha** [comment]
Hi I was also hoping to contribute to this project. If is it okay with you.

**Comment by rishabhkalra96** [comment]
Hello @pradhulstha,  it looks like you hadn't claimed it before so I claimed it!  
Please give me a couple of days to work on it. If no submissions come from my then I will unclaimed it for sure. Meanwhile you can check other issues as well. 
I hope you understand!

**Comment by Shubham-vish** [comment]
@rishabhkalra96  are you still working on this or can I take this issue if possible.

**Comment by rishabhkalra96** [comment]
@opendatakit-bot  claim

**Comment by manishakeim** [comment]
Can I claim this issue?

**Comment by manishakeim** [comment]
@opendatakit-bot claim

**Comment by manishakeim** [comment]
@opendatakit-bot unclaim

**Comment by AjaySharvesh3** [comment]
can I claim this issue?

**Comment by AjaySharvesh3** [comment]
@opendatakit-bot claim
