### ISSUE TITLE
Improve the labels and summary texts in About

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1846]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
The labels and summary texts for the About screen can be improved

Suggestion from @yanokwa  https://github.com/opendatakit/collect/pull/1802#pullrequestreview-95583399

```
 - Share ODK Collect
 - Are your colleagues still collecting data on paper? Share ODK Collect with them.

 - Leave a Play Store review
 - Your (hopefully positive) review increases the visibility of the App in the Play Store.

 - Open source libraries/licenses
 - We stand on the shoulders of giants!
```

**Comment by raks097** [comment]
@opendatakit-bot claim

**Comment by raks097** [comment]
I'd like to work on this issue

**Comment by raks097** [comment]
Hi!
I uploaded a PR which could possibly fix this issue but it failed on a test by CircleCI.
It failed due to an error which was in no way related to the commits that I had done.
Can someone suggest what to do next?

**Comment by rishabhkalra96** [comment]
@raks097 Are you still working on the issue? I believe the bot is not responding accurately and hadn't labelled "in progress" to this issue. Please let me know if you are not working on this.

**Comment by grzesiek2010** [comment]
> @raks097 Are you still working on the issue? I believe the bot is not responding accurately and hadn't labelled "in progress" to this issue. Please let me know if you are not working on this.

He has already created a pr for this issue: https://github.com/opendatakit/collect/pull/1861

**Comment by grzesiek2010** [comment]
@raks097 please claim this issue again just for clarity.

**Comment by raks097** [comment]
@rishabhkalra96 I have already created a pr for this issue.
You can find other issues at https://github.com/opendatakit/collect/issues
Welcome to the community

**Comment by raks097** [comment]
> @raks097 please claim this issue again just for clarity.

@opendatakit-bot claim

**Comment by raks097** [comment]
I had initially put a PR with respect to this.
It was under a review and got recently closed.
I'm rebasing my build as we speak and put up a new PR as soon as possible.
Thanks!

**Comment by yanokwa** [comment]
@raks097 Looking forward to it and sure that your PR targets just the issue!

**Comment by raks097** [comment]
@yanokwa 
I have submitted a new PR regarding this issue.
It would be helpful if someone could review it and tell their opinions regarding the changes.
Thank you for your time
