### ISSUE TITLE
Introduce new-front alias for image selfie appearance

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1848]
The `selfie` appearance for the `image` type allows form designers to request pictures to be taken from the front camera. After discussion at https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338, it was decided that the `new-front` appearance would be better by analogy to `new`.

The `new-front` appearance should be introduced as an alias for `selfie`. `selfie` should remain for existing forms that may use it.

See `search` and `autocomplete` for another example of appearance aliases.

**Comment by muhammadfawwaz** [comment]
@opendatakit-bot claim

**Comment by muhammadfawwaz** [comment]
@lognaturel so we add "new-front" widget? or just redesign from selfie widget?

**Comment by nanahamzat** [comment]
Hello, i will like to contribute in this as well. How do i get an invite

**Comment by lognaturel** [comment]
You should add an alias so that both the new-front and the selfie appearances do the same thing. See search and autocomplete for another example. 

@nanahamzat please look for an issue that hasn’t been claimed! Make sure to read through the contribution guide to learn how to claim issues.

**Comment by nanahamzat** [comment]
Thank you for your reply. I will look into that
