### ISSUE TITLE
Selection with autoadvance isn't displayed properly for right-to-left languages

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1849]
As reported at https://forum.opendatakit.org/t/odk-collect-autoadvance-gui-fix/11745

> With right to left alphabets the autoadvance symbol covers the first three letters of each word.

**Comment by vrjgamer** [comment]
Hi @lognaturel, can u please tell me how can i reproduce this bug?

**Comment by grzesiek2010** [comment]
@vrjgamer you need to use a `SelectOne` widget with `quick` appearance. You can find such a widget in `All widgets` form, it's called `Select widget autoadvance` or something similar. The problem is with right-to-left languages because in this widget we have a small icon for each option, it's on the right side and looks like it covers a text.

**Comment by vrjgamer** [comment]
I would like to try fixing this bug. Can I claim it?

**Comment by lognaturel** [comment]
Yes, please!

**Comment by vrjgamer** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
@grzesiek2010 I can't claim it 😅 ?

**Comment by lognaturel** [comment]
Go ahead @vrgamer, you can work on this one.

**Comment by vrjgamer** [comment]
@lognaturel  @grzesiek2010 
Hi, I was able to reproduce the problem. 
Please see this screen 

![screenshot_20180216-044115](https://user-images.githubusercontent.com/10618953/36286054-fa4e5230-12d3-11e8-8c58-00b6c8b11856.png)

I am not sure which language it is 😅, but here is the screen:

![screenshot_20180216-044459](https://user-images.githubusercontent.com/10618953/36286117-45f9eb54-12d4-11e8-9edb-786b8c904f48.png)

Also i saw some other bugs too. There some buttons which don't have the translated text.
I have listed some of them.

![screenshot_20180216-044032](https://user-images.githubusercontent.com/10618953/36286141-641ce0fa-12d4-11e8-9167-2933c82f9472.png)

![screenshot_20180216-044026](https://user-images.githubusercontent.com/10618953/36286148-68b0bd62-12d4-11e8-9ec3-a8d31ad8bb8f.png)

**Comment by vrjgamer** [comment]
Hi I think i know how to fix this issue. But i need some help from you.
I got three solutions for this issue but each have their own drawbacks.

First one: In the widget class 'SelectOneAutoAdvanceWidget', I set the gravity of the radiobutton in the code to RIGHT, before adding it to the layout like this->
```
....
RadioButton radioButton = createRadioButton(i);
radioButton.setOnClickListener(this);
//check which language
radioButton.setGravity(Gravity.RIGHT); // this is what i added

ImageView rightArrow = (ImageView) thisParentLayout.getChildAt(1);
rightArrow.setImageBitmap(b);
buttons.add(radioButton);
....
```
That shifted all the text to right. And this is how it looks. 
![screenshot_20180216-050345](https://user-images.githubusercontent.com/10618953/36287766-d94c69ba-12dc-11e8-94ba-f5a6edb52fc3.png)
But the problem with this is, we have to check for language and apply the gravity to only those languages with right to left alignment.

Second fix: In the 'quick_select_layout.xml' we can do the following changes:
```
....
<!--Aligning linear layout relative to imageview such that it doesn't overlap the imageview -->
    <LinearLayout
        android:orientation="horizontal"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_toLeftOf="@+id/quick_select_right_arrow"
        android:layout_toStartOf="@+id/quick_select_right_arrow"
        android:layout_marginEnd="10dp"
        android:layout_marginRight="10dp"
        />
<!-- added id to imageview that holds the arrow -->
    <ImageView
        android:id="@+id/quick_select_right_arrow"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_centerVertical="true"
        android:contentDescription="@string/select_answer" />
....
``` 
This will restrict the linear layout that holds the radiobutton, from overlapping the arrow icon.
And here is how it looks:
![screenshot_20180216-055731](https://user-images.githubusercontent.com/10618953/36287981-72f37cce-12de-11e8-9037-06609757898b.png)

And it stays consistent with left aligned languages without any change of code. Below is a screen for 'English' language without change of any code:
![screenshot_20180216-055754](https://user-images.githubusercontent.com/10618953/36288026-b4631188-12de-11e8-8a3c-9e416e199e21.png)

But the problem with this is that the divider line between the options is not spanning the entire row.

Third fix: In the class 'SelectOneAutoAdvanceWidget', we can set a padding-left to the radiobutton equal to the size of the bitmap + some extra space. Like this:
```
...
    ImageView rightArrow = (ImageView) thisParentLayout.getChildAt(1);
    rightArrow.setImageBitmap(b);
//check for language
      int padLeft = b.getWidth()+ 10; // b is the bitmap and we are setting its width + 10 as padding
      radioButton.setPadding(padLeft, 0, 0 ,0);
      buttons.add(radioButton);
...
```
This prevents overlapping of radiobutton-text with the arrow bitmap.
Here is how it looks:
![screenshot_20180216-054117](https://user-images.githubusercontent.com/10618953/36288146-50f35792-12df-11e8-8109-c8f400130e79.png)

But for this we need to check the language and only set padding-left to languages with right alignment.

I think second solution is better as not much code has to be changed, only if we don't care much about the row-divider line. @lognaturel @grzesiek2010 please tell me what you think.

**Comment by lognaturel** [comment]
Nice, @vrjgamer! I haven't looked at this in detail yet but it seems it should be possible to use directives like `START` and `END` that adapt to the language direction. Have you explored that option at all?

**Comment by vrjgamer** [comment]
@lognaturel  No I haven't checked that option. I will look into it.

**Comment by lognaturel** [comment]
Awesome. To be clear, I'm talking about https://developer.android.com/reference/android/view/Gravity.html#END

**Comment by grzesiek2010** [comment]
@lognaturel is right and probably it should look like in the first picture https://github.com/opendatakit/collect/issues/1849#issuecomment-366111657

**Comment by vrjgamer** [comment]
@lognaturel  @grzesiek2010 
I tried using Gravity.START directive, but it still doesn't solve our problem.
![screenshot_20180216-152152](https://user-images.githubusercontent.com/10618953/36302202-a431f7b2-132d-11e8-982e-3a241a3de5ac.png)

I think we can solve this using LayoutDirection LOCALE directive. 
Please check this link: https://developer.android.com/reference/android/util/LayoutDirection.html
Or https://android-developers.googleblog.com/2013/03/native-rtl-support-in-android-42.html?m=1

**Comment by grzesiek2010** [comment]
@vrjgamer I guess the layout container we use to display each row (radio button, text, and image) might be broken).

**Comment by vrjgamer** [comment]
@grzesiek2010 by broken what do u mean 😅 ?

**Comment by grzesiek2010** [comment]
I mean that there might be something wrong with text attributes since as I can see the radio button is displayed properly, the icon too.

**Comment by vrjgamer** [comment]
@lognaturel  @grzesiek2010  
I think it is because we are dynamically generating the radio buttons. As we only pass the context and no AttributeSet in the constructor, it takes in the default attributes for initialization. I think default text alignment is left to right. And this causes the ananomaly.

**Comment by grzesiek2010** [comment]
> I think it is because we are dynamically generating the radio buttons.

Can't you add appropriate attributes dynamically too?

**Comment by vrjgamer** [comment]
yes that's what i am working on 😃 .

**Comment by vrjgamer** [comment]
@lognaturel  @grzesiek2010 
Hi I solved the issue but it seems to work only for Android API levels 17 & above (our current min. api level is 16). Here's what i did:
In class SelectOneWidget class, there is a function called createRadioButton() which obviously creates our radiobutton views. In this method i made the following changes:
```
. . . 
 RadioButton radioButton = new RadioButton(getContext());
 radioButton.setTextSize(TypedValue.COMPLEX_UNIT_DIP, getAnswerFontSize());
 radioButton.setText(choiceDisplayName);
 radioButton.setMovementMethod(LinkMovementMethod.getInstance());
 radioButton.setTag(index);
 radioButton.setId(ViewIds.generateViewId());
 radioButton.setEnabled(!getFormEntryPrompt().isReadOnly());
 radioButton.setFocusable(!getFormEntryPrompt().isReadOnly());

// This is what i  added
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
      // method setTextAlignment requires min api level of 17
     radioButton.setTextAlignment(TEXT_ALIGNMENT_VIEW_START); 
  }else{
    // TODO: 17-02-2018 add support for api below 17
   }
. . .
```
Output: 
![dassdasdwadsdsa](https://user-images.githubusercontent.com/10618953/36326156-17810e18-1380-11e8-89d8-bbf95c3a4b3b.png)
References: 
https://android-developers.googleblog.com/2013/03/native-rtl-support-in-android-42.html?m=1
https://developer.android.com/reference/android/view/View.html#attr_android:textAlignment
https://developer.android.com/reference/android/view/Gravity.html

And it seems like it also fixed other views with radiobuttons like: SelectOneWidget, SelectOneSearchWidget, SelectOneSearchWidgetAutoComplete, GridSelectOneWidget.
![dsadsadasdsa](https://user-images.githubusercontent.com/10618953/36325756-def3ef08-137e-11e8-9687-01b15a771a0e.png)

I tried searching for the alternative for API level below 17 but I didn't find any till now.

**Comment by lognaturel** [comment]
That's great! Have you looked at resources such as https://stackoverflow.com/questions/20103079/android-widget-textview-settextalignment-java-lang-nosuchmethoderror?

**Comment by vrjgamer** [comment]
@lognaturel 
I went through the link and it seems like the only other way to set the text alignment in api level lower than 16 is using Gravity, but for setting gravity we need to find the language direction. 
I will try this solution: https://github.com/nispok/snackbar/issues/58

**Comment by vrjgamer** [comment]
@lognaturel @grzesiek2010 
Hi Good news I got the solution that fits all api levels. 
Here's what i did, (in reference to https://github.com/nispok/snackbar/issues/58), I put a check for the direction of the language and set the gravity of the text accordingly. 
```
. . .
protected RadioButton createRadioButton(int index) {
. . . 
        Locale currentLocale = getResources().getConfiguration().locale;
        if (isRTL(currentLocale)) {
            radioButton.setGravity(Gravity.END);
        } else {
            radioButton.setGravity(Gravity.START);
        }
. . .
}
private boolean isRTL(Locale locale) {
        int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
        return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
                directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
}
. . .
```
This gives the same results as the previous solution. 😄

**Comment by vrjgamer** [comment]
comparison of LTR and RTL language
![sdsadas](https://user-images.githubusercontent.com/10618953/36328944-1dcaa0e0-138a-11e8-9a4b-7d67bf1cfec8.png)

**Comment by grzesiek2010** [comment]
In the last case, images should be under radio buttons I think. You can fix it as well as a part of this issue.

**Comment by vrjgamer** [comment]
While solving this problem, I encountered some bugs.
_**First Bug:**_
**Steps to reproduce:**
1. Select a Right to Left language.
2. Select any form 
3. Click on Overview button in the top-bar (icon that looks like a diagonal arrow pointing a dot)
**Expected behaviour**
This should show a list of all the widgets that are there in the form.
**Behaviour Found**
The screen is blank and it doesn't show any widget list. 
![screenshot_20180217-020613](https://user-images.githubusercontent.com/10618953/36329233-41b56ffc-138b-11e8-81b3-31e68978e5b2.png)

_**Second Bug**_
**Steps to reproduce:**
1. Get 'All Widgets' form from the 'Get Blank Form' Option.
2. Open the 'All Widgets' form and go to the page with 'List Group'.
**Expected Behaviour**
The page is suppose to a list of different widgets with all options clearly visible.
**Behaviour Found**
All the widget text and options are all cluttered and nothing is clearly visible.
![screenshot_20180217-011101](https://user-images.githubusercontent.com/10618953/36329502-2e7d449a-138c-11e8-87fd-642a6aedb248.png)

**Comment by grzesiek2010** [comment]
Yes, we know that we probably have lots of issues related to right-to-left languages. Just be focused on this one, then you can file separate issues.

**Comment by vrjgamer** [comment]
@grzesiek2010 I am not able to find where the Grid select one option is. The select one widget with images. Can u please guide me.

**Comment by vrjgamer** [comment]
@grzesiek2010 @lognaturel 
Hi, I found the bug for Widget with images and radiobutton, it was in MediaLayout class. The layout parameters were defined statically and with directives the support only LTR languages. So I updated the directives such that it supports both the LTR and RTL languages. Here is how it looks:
![fghasjdkl](https://user-images.githubusercontent.com/10618953/36357285-d146456e-1521-11e8-883a-94b74a71e571.png)
Does this look okay?
If yes, should I start with the pull request?

**Comment by vrjgamer** [comment]
@lognaturel  @grzesiek2010 
Hi, I am not able to solve this error on circleci
its giving me error-> ` 'Execution failed for task ':collect_app:compileDebugJavaWithJavac' `
I tried create it with a new fork but still the same error.

it gives success for local build with .\gradlew.bat
Please help

**Comment by lognaturel** [comment]
There are some
