### ISSUE TITLE
Remove no-value log messages in FormEntryActivity (and perhaps elsewhere)

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#1853]
FormEntryActivity produces messages of no value such as these:

```
02-11 22:29:20.188 1905-1905/org.odk.collect.android I/FormEntryActivity: onAnimationStart in
02-11 22:29:20.490 1905-1905/org.odk.collect.android I/FormEntryActivity: onAnimationEnd in
02-11 22:29:20.491 1905-1905/org.odk.collect.android I/FormEntryActivity: afterAllAnimations
```

Please remove them, as well as similar messages you might find in other files.

**Comment by JainilGada** [comment]
@opendatakit-bot claim

**Comment by rishabhkalra96** [comment]
Looks like i can contribute to fix this issue. If anyone is not doing it then i am interested to take over!

**Comment by grzesiek2010** [comment]
@rishabhkalra96 this issue is already claimed by @JainilGada I know it's not visible here because that `opendatakit-bot` is faulty and if you try to claim an issue for the first time it's ignored.

@JainilGada please claim again if you still want to work on it.

**Comment by rishabhkalra96** [comment]
OK, Thank you for informing
Just in case if no "re-claim" comes from @JainilGada , i would like to claim it

**Comment by grzesiek2010** [comment]
> Just in case if no "re-claim" comes from @JainilGada , i would like to claim it

sure.

**Comment by JainilGada** [comment]
@opendatakit-bot claim
