### ISSUE TITLE
Inconsistency between SelectOne widgets.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1855]
#### Software and hardware versions 
Current master branch

#### Problem description
Last month we implemented `image-map` appearance for select questions. I noticed a small inconsistency between that new widget and ordinary `SelectOneWidget`. 
If we use the first one we can unselect our answer clicking on the same value what is not possible in `SelectOneWidget`. 

#### Expected behavior
I'm not sure which approach we should choose but it should work in the same way. @lognaturel what do you think?

#### Other information 
![singleselect](https://user-images.githubusercontent.com/3276264/36142574-c9fc4a1a-10a8-11e8-9f7b-46fd744a44bc.gif)

Form for testing:
[canada.zip](https://github.com/opendatakit/collect/files/1719434/canada.zip)

@opendatakit-bot label "needs discussion"
@opendatakit-bot label "quick win"

**Comment by lognaturel** [comment]
Let's use radio button behavior. That means a second click on the image map should not unselect. Note that the unselect behavior should exist in the case of multiple selection.

**Comment by SIMRAN1** [comment]
@grzesiek2010  @lognaturel  may I work on this issue?
@opendatakit-bot  claim

**Comment by grzesiek2010** [comment]
@SIMRAN1 yes please go ahead. You need to use `claim` not `Claim`.

**Comment by grzesiek2010** [comment]
@SIMRAN1 it doesn't work if you edit your comment you need to do that again because you are still not assigned to this issue.

**Comment by SIMRAN1** [comment]
okk thanks @grzesiek2010

**Comment by SIMRAN1** [comment]
@opendatakit-bot  claim

**Comment by grzesiek2010** [comment]
@SIMRAN1 
and one more time if it was your first claim :smile:

**Comment by SIMRAN1** [comment]
@opendatakit-bot  claim
@grzesiek2010 please tell me how to proceed to solve this issue?

**Comment by grzesiek2010** [comment]
as @lognaturel said a user shouldn't be able to unclick selected value in SelectOne widget. You ca try the attached form.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
Hello guys~
I saw this issue by accident, and I think my code can meet this requirment, I don't know if this is what you want : @grzesiek2010 @lognaturel 

Single mode which user can only choose one area and cannot cancel the highlight by twice-click：
![single mode](https://i.loli.net/2018/03/16/5aab55e98efa9.gif)

Multiple mode allows user to select many areas and can cancel the highlight by twice-click：
![multiple mode](https://i.loli.net/2018/03/16/5aab55d14878e.gif)

If these meet your demands , I think you can close this issue and I will submit my pull request immediately that you can check if this solution is valid and merge that into origin.
And I'm working on another issue recently, so it seems I cannot claim this issue,I hope you guys can save your time working on other issues if you have seen this post.

Think you :)

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
