### ISSUE TITLE
Default OSM basemap is not set

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1856]
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Steps to reproduce the problem
1. Go to `General Settings` -> `User Interface`
2. Change `Mapping SDK` for `OpenStreetMap SDK`

#### Expected behavior
Default basemap should be set.

#### Other information 
![defaultosmbasemap](https://user-images.githubusercontent.com/3276264/36144569-bf713514-10ae-11e8-8b2e-28f3660f54ef.gif)

@opendatakit-bot label "quick win"

**Comment by abdulwd** [comment]
May I work on this issue? Also, default **Basemap** is set to **Streets** as I can see on the first installation of the app.
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@abdulwd 

As I see you are not new here since you have already fixed two issues but it was almost a year ago so let's say you can take one `quick-win` just as a warm-up an then please take something more complex.

> Also, default Basemap is set to Streets as I can see on the first installation of the app.

It's when `Mapping SDK` is set for `Google Maps` but the problem here is with `OpenStreetMaps` SDK.

You need to claim the issue if you want to work on it https://forum.opendatakit.org/t/fine-grained-permissions-for-github-issues-self-assign-labels/9352/9?u=grzesiek2010

**Comment by abdulwd** [comment]
@grzesiek2010 Sure! I must have taken something more complex. Thanks. :)

**Comment by abdulwd** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@abdulwd Please make sure to accept the email invitation so that you can be assigned to the issue.

**Comment by abdulwd** [comment]
@opendatakit-bot claim
@lognaturel I have already accepted the email invitation maybe I need to claim it again.
