### ISSUE TITLE
Popup menu in Import/Export Settings exists only for one item

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1857]
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Popup menu in Import/Export Settings exists only for one item

#### Steps to reproduce the problem
1. Go to `Admin Settings` -> `Import/Export Settings`
2. Open the popup menu.

#### Expected behavior
`Save Settings to Disk` may have its own icon like `Share QE code`.
Please use vectors, not png icons.

#### Other information 
![screenshot_2018-02-13-13-26-04](https://user-images.githubusercontent.com/3276264/36149884-c7241138-10c1-11e8-8c58-c542ab2589bc.png)
![screenshot_2018-02-13-13-26-09](https://user-images.githubusercontent.com/3276264/36149885-c742b5f2-10c1-11e8-90aa-a27b2928cf0c.png)

@opendatakit-bot label "quick win"

**Comment by vrjgamer** [comment]
Hello sir, can i help fixing this issue?

**Comment by grzesiek2010** [comment]
Hi @vrjgamer 
please go ahead. You need to claim this issue, take a look here how to do that: https://forum.opendatakit.org/t/fine-grained-permissions-for-github-issues-self-assign-labels/9352/9?u=grzesiek2010

**Comment by vrjgamer** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
Hi, I have finished adding the icon for "Save Setting to Disk". I am using vectors for "Save" & "Share" options. But its showing an error for the "Share" icon.
If I use the default android resource it works perfectly like below:
` 
....
 <item
        android:id="@+id/menu_item_share"
        android:title="@string/share"
        android:icon="@android:drawable/ic_menu_share"
        app:showAsAction="ifRoom"
        />
....
`
but if i use my custom icon, it gives me an error. Here is the code:
`....
   <item
        android:id="@+id/menu_item_share"
        android:title="@string/share"
        android:icon="@drawable/ic_menu_share"
        app:showAsAction="ifRoom"
        />
.....
`
and error:
 `.....
02-14 01:42:06.779 23545-23545/org.odk.collect.android E/UncaughtException: android.content.res.Resources$NotFoundException: Drawable org.odk.collect.android:drawable/ic_menu_share with resource ID #0x7f08009b
                                                                            Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_share.xml from drawable resource ID #0x7f08009b
                                                                                at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:729)
                                                                                at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:575)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:767)......
......
......
`
I tried cleaning by `Project` -> `Clean` , but its still giving me the same error.
This is a screenshot:
![screen](https://user-images.githubusercontent.com/10618953/36172281-66a6403c-112b-11e8-8a57-7bf59ac4002b.png)
I hope this is okay.
I will try fixing it.

**Comment by vrjgamer** [comment]
Nevermind I fixed it. 
Please check the screen, before i commit it.

![screen2](https://user-images.githubusercontent.com/10618953/36173517-51b99ef4-112f-11e8-82e2-82be22b8cf71.png)

**Comment by grzesiek2010** [comment]
@vrjgamer thirst thing, you need to claim the issue again since it was your first comment you received a message and it was ignored.

When it comes to your screen. Where those icons come from? I'm asking because save icon here https://material.io/icons/ looks different and I would prepare that one since we already use the same but grey color https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/drawable/ic_save_grey_32dp.xml

**Comment by vrjgamer** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
ok I will use the existing save button.
I will change the share icon with this: https://material.io/icons/#ic_share

**Comment by vrjgamer** [comment]
Hi, I hope this is better.
![screen](https://user-images.githubusercontent.com/10618953/36187362-c63db888-116a-11e8-86ea-6f2700268ba6.png)

**Comment by grzesiek2010** [comment]
@vrjgamer yes looks better but black icons please since those look as if they are disabled.

**Comment by vrjgamer** [comment]
I think this should do it.
![screen_dark](https://user-images.githubusercontent.com/10618953/36201403-e10fb16c-11a5-11e8-8a65-70df5f772a62.png)


So should i proceed by pulling a new request?

**Comment by grzesiek2010** [comment]
> So should i proceed by pulling a new request?

sure

**Comment by vrjgamer** [comment]
@grzesiek2010 Sir this time, I did a re-fork and started from scratch. I added one vector icon for share icon and made changes only in settings_menu.xml. 
I don't know why it failed.
Can you please try re-running the test?

**Comment by vrjgamer** [comment]
@grzesiek2010 
Hi,  I would like to work on another issue. Do you have any suggestions?

**Comment by grzesiek2010** [comment]
As a second issue you can take something from https://github.com/opendatakit/collect/issues?q=is%3Aissue+is%3Aopen+label%3A%22contributor+friendly%22 but avoid `quick-wins`

**Comment by vrjgamer** [comment]
@grzesiek2010  Thanks, I will make sure i avoid quick-wins
