### ISSUE TITLE
Replace png icons from FormEntryActivity with vectors

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1858]
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Replace png icons from FormEntryActivity with vectors

#### Steps to reproduce the problem
Just open any form.

![screenshot_2018-02-13-13-38-05](https://user-images.githubusercontent.com/3276264/36150235-445d3d9a-10c3-11e8-8b87-f5bbbe04f84c.png)

#### Expected behavior
We should use vectors instead of pngs, and both icons should be black like here for example: 
![screenshot_2018-02-13-13-38-01](https://user-images.githubusercontent.com/3276264/36150233-44431c26-10c3-11e8-8cc6-e3ebf450abea.png)

it looks better.

@opendatakit-bot label "quick win"

**Comment by vsham20** [comment]
Hi, Can i pick this issue to work on?

**Comment by grzesiek2010** [comment]
@vsham20 

please go ahead. You need to claim this issue: https://forum.opendatakit.org/t/fine-grained-permissions-for-github-issues-self-assign-labels/9352/9?u=grzesiek2010

**Comment by Shreya001** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@Shreya001 please claim again. It was ignored since it was your first claim.

**Comment by Shreya001** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
@Shreya001 you can use the following code for save button vector (https://material.io/icons/#ic_save)
save it as -> ic_save_black_32dp.xml
```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="36dp"
        android:height="36dp"
        android:autoMirrored="true"
        android:viewportHeight="24.0"
        android:viewportWidth="24.0">
    <path
        android:fillColor="@color/black"
        android:pathData="M17,3L5,3c-1.11,0 -2,0.9 -2,2v14c0,1.1 0.89,2 2,2h14c1.1,0 2,-0.9 2,-2L21,7l-4,-4zM12,19c-1.66,0 -3,-1.34 -3,-3s1.34,-3 3,-3 3,1.34 3,3 -1.34,3 -3,3zM15,9L5,9L5,5h10v4z"/>
</vector>
```
I am not sure about the function of the second button. Assuming it to be download button. You can use the following vector drawable (https://material.io/icons/#ic_arrow_downward):
save it as -> ic_download_black_36dp.xml
```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="36dp"
    android:height="36dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:pathData="M0 0h24v24H0V0z" />
    <path
        android:fillColor="@color/black"
        android:pathData="M20 12l-1.41-1.41L13 16.17V4h-2v12.17l-5.58-5.59L4 12l8 8 8-8z" />
</vector>
 ```

**Comment by lumarega** [comment]
@opendatakit-bot claim

**Comment by lumarega** [comment]
This is the current icon used:
![image](https://user-images.githubusercontent.com/18705293/37246129-362e7cd4-2482-11e8-9395-89e49509758b.png)

but is not available within the material design icons to create the vector based on it. 
So I would like your insight on it @grzesiek2010  @lognaturel. Is it ok if we change for another icon? For example this icon:

![image](https://user-images.githubusercontent.com/18705293/37246154-ac8cdce0-2482-11e8-85eb-d97d175cf49c.png)

Any suggestions will be appreciated!
