### ISSUE TITLE
Inconsistency between Geopoint widgets' button name

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1859]
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Problem description
The button text changes if any location is recorded if we use the `GeopointWidget` with `map` appearance but it doesn't if we use that widget without any appearance

![screenshot_2018-02-13-13-58-13](https://user-images.githubusercontent.com/3276264/36151444-7f5157a2-10c7-11e8-83f7-40be7da48465.png)
![screenshot_2018-02-13-13-58-15](https://user-images.githubusercontent.com/3276264/36151445-7f98ceac-10c7-11e8-84ba-9d9231d1029e.png)

#### Steps to reproduce the problem
You can use `All Widgets` form.

#### Expected behavior
I think the text in the first case should be changed too. Maybe `View or Change Location` is not good since we can't view that location but we can use eg. just `Change Location`

#### Other information 
The problem is visible if we use both Google and OSM SDK.

@opendatakit-bot label "quick win"

**Comment by Shreya001** [comment]
@grzesiek2010 can I work on this issue?

**Comment by sammy1997** [comment]
@opendatakit-bot claim

**Comment by sammy1997** [comment]
@opendatakit-bot claim

**Comment by sammy1997** [comment]
@Shreya001 you can claim an issue using the bot. So you don't need to tag mentors I guess. :)

**Comment by Shreya001** [comment]
Ok Thanks  @sammy1997 :)

**Comment by grzesiek2010** [comment]
@Shreya001 @sammy1997 that's right you can claim an issue if it's free.

@sammy1997 as I understand you added that comment only to show how it works so, please unclime now and let @Shreya001 do that. 

[EDIT} I saw @Shreya001 has already claimed another issue so I think it's ok if you @sammy1997 are going to keep this one.

**Comment by sammy1997** [comment]
Ok @grzesiek2010 .

**Comment by Shreya001** [comment]
Ok @grzesiek2010

**Comment by SIMRAN1** [comment]
@opendatakit-bot claim

**Comment by arihant-001** [comment]
@opendatakit-bot claim

**Comment by isabelcosta** [comment]
@opendatakit-bot claim
