### ISSUE TITLE
The keyboard should be visible just after showing an EditText field if a requested application is missing.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1864]
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
The keyboard should be visible just after showing an EditText field if a requested application is missing.
#### Steps to reproduce the problem
1. Use `All widgets` form
2. Go to` Ex string widget` or `Ex integer widget` or `Ex decimal widget`
3. Click on the `Launch` button.

#### Expected behavior
The field for manual putting an answer is visible and active but the keyboard is hidden so we should show the keyboard automatically. 

#### Other information 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3276264/36208126-562e8616-1198-11e8-8926-c46f8a01b188.gif)

It should work in the same way in BearingWidget.

@opendatakit-bot label "quick win"

**Comment by sashank27** [comment]
@opendatakit-bot claim
