### ISSUE TITLE
Toggle button doesn't work as expected

### ISSUE THREAD

**Issue by lakshyagupta21** [getodk/collect#1868]
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Toggle button doesn't work as expected to be while doing search for instances and forms

#### Steps to reproduce the problem
1. Delete Saved Form
2. Search for blank form
3. Select any form
4. Close Search
5. List will be displayed with the selected items but with "Clear all" label
#### Expected behavior
Instead of "Clear all" button "Select all" should be displayed
#### Other information 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/18495162/36244835-ef637f84-124d-11e8-88bc-d4d1d459277c.gif)

Activities that needs to be taken care for this issue - Delete Saved Form, Send Selected Form

**Comment by vladalexgit** [comment]
@opendatakit-bot claim

**Comment by vladalexgit** [comment]
@opendatakit-bot claim --force

**Comment by anipmehta** [comment]
@opendatakit-bot claim --force

**Comment by harsh-2711** [comment]
I wanna work on this issue if it's still open
