### ISSUE TITLE
QRCode shouldn't be regenerated if the settings haven't changed

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1879]
#### Software and hardware versions 
Collect v1.12

#### Problem description
QRCode is generated every time, even if the settings have not changed. 

#### Steps to reproduce the problem
Goto `Admin Settings` > `Import/Export Settings`

#### Expected behavior
The last generated QRCode should be cached in the sd-card and used if the settings have not changed since the last generated time.

@opendatakit-bot claim

**Comment by vrjgamer** [comment]
Should we save it as an image and then keep the uri in preferences

**Comment by shobhitagarwal1612** [comment]
I have already submitted a PR for this 
https://github.com/opendatakit/collect/pull/1880

Please have a look
