### ISSUE TITLE
Forms are not selected if user clicks on button 'Select All' and then clicks on arrow or X in search bar on `Delete Saved Form` view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1884]
#### Software and hardware versions 
Collect current master 
Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

#### Problem description
Forms are not selected if user clicks on button 'Select All' and then clicks on arrow or X in search bar on `Delete Saved Form` view

#### Steps to reproduce the problem
1. User goes to `Delete Saved Form` view
2. User opens `Blank Forms` view
3. User clicks on search icon
4. User adds filter to search
5. User sees searched forms and clicks `Select All` button
6. **User clicks on `X` or `<-`** 
7. Forms are unselected

![search](https://user-images.githubusercontent.com/3907554/36376918-e73ec1e8-156c-11e8-83c8-09889b3cf723.gif)

#### Expected behavior
* Forms are selected on view with all forms

#### Other information 
Discovered during testing #1867 and #1870

**Comment by Shreya001** [comment]
@opendatakit-bot claim

**Comment by Thodoris1999** [comment]
@opendatakit-bot claim
