### ISSUE TITLE
Add test for "trigger" question in AllWidgetsFormTest

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1890]
The test `testTriggerWidget` already exists but it doesn't do anything currently. It should randomly either check or not check the checkbox, go to the question list, come back to the question and then verify that the value is still set as expected.

`testStringWidget` or other tests that already are included can be used as an example.

For more information about Android testing in an ODK context, see https://www.youtube.com/watch?v=6iZaRF3njH4

**Comment by ArmenApresyan8** [comment]
@lognaturel I'v made implementation for it (#1923), but what about other tests? There are many tests that also do nothing just like this one.

**Comment by lognaturel** [comment]
@ArmenApresyan8 That's great! I've created a generic issue with the other tests to take on at #1933.
