### ISSUE TITLE
Issues with storage option

### ISSUE THREAD

**Issue by harsh-2711** [getodk/collect#1894]
Software and hardware versions 
Tested on One Plus 5T running Android 8.0

Problem description
On downloading any form from the server, the images get also downloaded in the phone storage.

Expected behavior
The images should be available directly via server without storing them on phone

Steps to reproduce the problem
Web View can be used to show the images via server

Would you like to work on the issue?
Yes

**Comment by lognaturel** [comment]
Thanks for your interest in Collect, @harsh-2711! It is primarily used offline so this is not desired behavior. To learn more about ODK and how it is used, please see https://opendatakit.org
