### ISSUE TITLE
Pictures taken by the SelfieWidget are rotated incorrectly on Android 4.4 and 4.2

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1900]
#### Software and hardware versions 
Collect v1.12
Android v4.4 and 4.2

#### Problem description
Pictures taken by the SelfieWidget are rotated incorrectly

#### Steps to reproduce the problem
1. User uses device in vertical orientation
2. User takes selfie image
3. Image is rotated

| case/device  | Samsung J1 | Infinix | 
| ------------- | ------------- | ------------- |
| Android | 4.4 | 4.2 |
| selfie widget, front camera, vertical device orientation | **horizontal** | **horizontal** |
| selfie widget, front camera, horizontal device orientation | horizontal | horizontal |

#### Expected behavior
Image is not rotated

#### Other information
Related to #1877

**Comment by ShenJack** [comment]
@mmarciniak90 I didn't notice that those two devices are on Android below 5.0, it's my responsibility to fix it, and I've already got some ideas to handle this.

**Comment by ShenJack** [comment]
@opendatakit-bot claim

**Comment by mmarciniak90** [comment]
@ShenJack It's great that you have ideas. We must to take care on devices with Android below 5.0 because they are still popular among our users.

**Comment by ShenJack** [comment]
@opendatakit-bot label "needs testing"

**Comment by akshay-ap** [comment]
I would like to test it on Asus Zenfone 5 (api 19).
@mmarciniak90 How do I test the changed code?

**Comment by mmarciniak90** [comment]
@akshay-ap You need to build app on `pr/1911` branch. Then take image on Selfie widget on both orientations. You can use `All widgets` form.
Images cannot be rotated.

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
