### ISSUE TITLE
Updating the time picker dialog

### ISSUE THREAD

**Issue by ArmenApresyan8** [getodk/collect#1901]
#### Software and hardware versions 
Collect v 1.12.2
Android 7.0
Samsung Galaxy S6 edge

#### Problem description

The time picker is old

#### Steps to reproduce the problem

Just click on any time picker button

#### Expected behavior

The mew material design time picker should be opened, like the date picker, which is material design
![screenshot_20180221-123516](https://user-images.githubusercontent.com/18738136/36481733-245a2eaa-172a-11e8-8f66-de429cf8ed39.png)
![screenshot_20180221-123532](https://user-images.githubusercontent.com/18738136/36482259-2780a3a0-172c-11e8-9153-47a748b0152b.png)

#### Other information 
I want to work on it

**Comment by lognaturel** [comment]
The material design time picker is a lot more complicated for users and requires familiarity with a clock so the decision was made to use the old one. 

In fact, many users choose the `no-calendar` appearance for dates as well.

I don't think we should add the new time picker. Other opinions?

**Comment by ArmenApresyan8** [comment]
I think using the new time picker is a good idea, as it is recommended by Google. Also users with Android 5+ must be familiar with it, because it is used in default Android apps, e.g. alarms.

**Comment by ArmenApresyan8** [comment]
Else we can add an option in settings where user can choose which time picker they want to use while filling the forms.

**Comment by yanokwa** [comment]
@ArmenApresyan8 Just because Google recommends it isn't a compelling reason for me. What does the Material Design time picker actually look like? If we add it, what will it look like for our users who aren't on Android 5?

**Comment by ArmenApresyan8** [comment]
![components-pickers-time1](https://user-images.githubusercontent.com/18738136/36509556-8e16dc54-1779-11e8-9c00-f8c567ca2141.png)

It looks like this, where first you choose hour, then minutes. 
I'm not sure about Android 5- users, they will either see this dialog, or the old one. I'll check it tomorrow.

**Comment by grzesiek2010** [comment]
I agree with @lognaturel it might be too difficult for some users.
