### ISSUE TITLE
Image select one widget does not allow answer to be removed

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1903]
#### Software and hardware versions 
Collect v1.13.0-beta.0

#### Problem description
A question with the clickable SVG does not allow answer to be removed.

#### Steps to reproduce the problem
1. Connect your phone to https://opendatakit.appspot.com
1. Download the All Widgets form
1. Navigate to the Image select one widget
1. Select any districts.
1. Long press on the map or answer to show Edit prompt
1. Tap remove response and confirm
1. Response is still shown 

#### Expected behavior
1. Response should be removed

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
