### ISSUE TITLE
Run code quality before build_debug and test_unit

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1905]
In https://github.com/opendatakit/collect/blob/master/.circleci/config.yml, we `build_debug` and `test_unit` simultaneously with `build_debug` running the code quality checks. 

I think it might be better if the code quality checks (`./gradlew pmd checkstyle lint findbugs`) are run on one machine first. This way, if they fail, it fails quickly without `test_unit` running.

**Comment by lognaturel** [comment]
Does running `test_unit` in parallel actually slow down the code quality checks? If not, running them in parallel seems like the way to go.

**Comment by shobhitagarwal1612** [comment]
I noticed that earlier it took 6 min 46 seconds to run the build and unit tests. Now it takes 6 min 16 seconds. So 30 seconds less for non-master builds.

**Comment by yanokwa** [comment]
I did some quick tests and my assumptions that pmd/checkstyle/lint would be faster if run alone is incorrect.

> time ./gradlew clean pmd checkstyle lint findbugs
> BUILD SUCCESSFUL in 3m 17s

> time ./gradlew clean testDebugUnitTest
> BUILD SUCCESSFUL in 1m 16s

**Comment by shobhitagarwal1612** [comment]
Is there a way to cache the dependencies for `pmd`, `findbugs` or even other dependencies?

**Comment by yanokwa** [comment]
No idea. Not sure it's a huge pain point, but maybe we can file a contributor friendly issue to speed up the build and then close this one?

**Comment by shobhitagarwal1612** [comment]
Yes please!

**Comment by yanokwa** [comment]
Closed. Please file the issue when you get a chance, @shobhitagarwal1612. You are the infrastructure expert now :)
