### ISSUE TITLE
Small color picker

### ISSUE THREAD

**Issue by ArmenApresyan8** [getodk/collect#1907]
#### Software and hardware versions 
Collect v 1.12.2
Android 7.0
Samsung Galaxy S6 edge

#### Problem description

The color picker is very small on the screen and almost impossible to choose the color you want

#### Steps to reproduce the problem

1) Open an image type with draw appearance 
2) Click on plus FAB
3) Click on "Set color"
#### Expected behavior

The color picker should be bigger

#### Screenshots 
![28460360_1548389028608050_1981746943_o](https://user-images.githubusercontent.com/18738136/36510624-15361f30-177d-11e8-81af-6c963117b0cb.png)
![28343307_1548387458608207_659312532_o](https://user-images.githubusercontent.com/18738136/36510627-16655eca-177d-11e8-96c3-b71c68f1a6cc.png)

#### Other information 

I would like to work on it. Also can you provide the right size for it?

**Comment by vrjgamer** [comment]
@opendatakit-bot claim

**Comment by vrjgamer** [comment]
@opendatakit-bot unclaim

**Comment by ArmenApresyan8** [comment]
@lognaturel should I work on this?

**Comment by lognaturel** [comment]
@ArmenApresyan8 Sure, please claim it with `@opendatakit-bot claim`.

**Comment by muhammadfawwaz** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
@ArmenApresyan8 If you'd like to work on this one, that would be great. There are no specific requirements other than it should be more usable than the current one. I recommend sharing a UI sketch here for others to comment on. There were also some great ideas at #682.

**Comment by ArmenApresyan8** [comment]
I'll work on it as soon as possible.

**Comment by ArmenApresyan8** [comment]
Also, all integer values in `ColorPickerDialog` are hardcoded, I'll change it.

**Comment by vrjgamer** [comment]
@lognaturel the existing color picker is really not optimized and hard coded which is difficult to modify. 
I have a simple suggestion, how about we use UI that is similar to photoshop hue/saturation selector.  Something like this: https://www.cssscript.com/wp-content/uploads/2017/01/Minimal-HSLA-Color-picker-With-Pure-JavaScript.png
![sdfghj](https://user-images.githubusercontent.com/10618953/36871303-dad395c4-1dc7-11e8-9674-e7d8c7858494.png)
or this https://cdn.dribbble.com/users/45209/screenshots/3143833/hsl_color_picker.png
![hsl_color_picker](https://user-images.githubusercontent.com/10618953/36871537-8fd769b4-1dc8-11e8-9501-f53d78b2818f.png)
 This is even easier to use and code. 😅  
What do you think?

**Comment by ArmenApresyan8** [comment]
I think it's more complex than the one we have now

**Comment by vrjgamer** [comment]
i don't think its complex. You can create 3 sliders - hue, saturation, value - from which you can get the current value and convert them to get the red, green, blue values to find the specific color.
here is an example of how to change HSV to RGB: https://examples.javacodegeeks.com/desktop-java/awt/rgb-to-hsb-and-vice-versa-color-conversion/

**Comment by lognaturel** [comment]
As you explore different UI options, consider that Collect users are typically not very technical. Also, annotations are not high art, they're typically quick circles or arrows. Adding hue, saturation, brightness, hex values, etc seems possibly confusing for little benefit.

**Comment by ArmenApresyan8** [comment]
@vrjgamer I mean it's complex for the users, not for us to develop.

**Comment by ArmenApresyan8** [comment]
@lognaturel What about using this lib?
https://github.com/jaredrummler/ColorPicker

**Comment by ArmenApresyan8** [comment]
@lognaturel What do you do think about using this lib?
https://github.com/jaredrummler/ColorPicker

**Comment by ArmenApresyan8** [comment]
We can also use the default colors appearance.

**Comment by ArmenApresyan8** [comment]
Fixed it anyway (#1978). But not the best solution, most of code is still hardcoded.

**Comment by dcbriccetti** [comment]
I think making the current control bigger is an excellent idea. I see an advantage to picking the hue with one click, then picking the saturation and brightness with a second click, over manipulating three sliders.

**Comment by lognaturel** [comment]
#1978 is a good approach for keeping changes minimal.

@ArmenApresyan8 I imagine using https://github.com/jaredrummler/ColorPicker won't add much to APK size, right? If that's confirmed, it seems like a good lib to use. There's always some risk associated with libraries if they stop being supported, etc but in this case it would be very easy to swap out or revert back to the current custom implementation.

**Comment by ArmenApresyan8** [comment]
@lognaturel I can check it later how much the APK size will be increased.

**Comment by ArmenApresyan8** [comment]
@lognaturel APK size was increased by 46.2 KB when using this lib.

**Comment by dcbriccetti** [comment]
That’s a very small increase, it seems to me. It sounds like @lognaturel would like to have you use this color picker. If so, I agree.

**Comment by lognaturel** [comment]
Yes, I agree. @ArmenApresyan8 your instinct to try to minimize changes and dependencies is a very good one. In this case the benefits are clear and the downsides few. If you'd like to send in a PR using the lib and close your scaling one, please do!

**Comment by ArmenApresyan8** [comment]
OK, I'll do it.

**Comment by ArmenApresyan8** [comment]
@lognaturel Should I also include it in open source libraries list?

**Comment by lognaturel** [comment]
Yes, please, @ArmenApresyan8!

**Comment by ArmenApresyan8** [comment]
@lognaturel what do you think about this?

![screenshot_20180313-211401](https://user-images.githubusercontent.com/18738136/37358885-a8dc4ac4-2705-11e8-93a4-dc80c12d097a.png)
![screenshot_20180313-212752](https://user-images.githubusercontent.com/18738136/37358889-aa226fda-2705-11e8-8048-94c83051da0d.png)

**Comment by dcbriccetti** [comment]
That’s a nice improvement! Can you change the orientation in the custom mode (lower picture) so that the hues are on the long axis, so that the scroll bar is not needed? Scrolling adds one more interaction.

**Comment by ArmenApresyan8** [comment]
You mean change the orientation of screen?

**Comment by dcbriccetti** [comment]
No. The contents. Right now there is wasted space on the left and right that could be used to remove the need for scrolling.

**Comment by ArmenApresyan8** [comment]
I don't think I can change the code of lib.

**Comment by ArmenApresyan8** [comment]
OK, here is it.
https://github.com/ArmenApresyan8/collect/tree/new_color_picker

**Comment by ArmenApresyan8** [comment]
I think it was designed for portrait screens.

**Comment by ArmenApresyan8** [comment]
![screenshot_20180313-223611](https://user-images.githubusercontent.com/18738136/37362553-f7040d78-270e-11e8-975e-fe4c6008a221.png)

What about this one?

**Comment by ArmenApresyan8** [comment]
We should use our old dialog with my scaled option :)

**Comment by lognaturel** [comment]
I'm ok with either. The last screenshot you shared looks fine to me. Presumably it looks great in portrait, right?

**Comment by ArmenApresyan8** [comment]
Yes, they look good in portrait. So should we use the last one?

**Comment by dcbriccetti** [comment]
Trouble is, the draw widget is landscape-only, right?

**Comment by lognaturel** [comment]
Ah. Right. Annotate takes the orientation of the image but straight draw is indeed landscape only. I’m still ok with that latest screenshot. @dcbriccetti?

**Comment by dcbriccetti** [comment]
Oh. Yeah. Me too. How’d you get rid of the scroll bar, @ArmenApresyan8?

**Comment by ArmenApresyan8** [comment]
The last screenshot I added was a different lib. The first ones were with the scroll bar, I think we can't change it because there was hardcoded size for the dialog and it was for portrait only. If the last one looks OK, we can use it. Here is it
https://github.com/yukuku/ambilwarna

**Comment by ArmenApresyan8** [comment]
It is also working faster with the colors rendering, then the current one we have.

**Comment by dcbriccetti** [comment]
Could I trouble you to push it so I can play with it?

**Comment by ArmenApresyan8** [comment]
I'll do that after I get home.

**Comment by ArmenApresyan8** [comment]
@dcbriccetti I pushed it here. https://github.com/ArmenApresyan8/collect/tree/new_color_picker
If it's okay, I'll open a pull request.

**Comment by dcbriccetti** [comment]
![wasted space](https://user-images.githubusercontent.com/55099/37421624-fc265672-2776-11e8-8957-211438c7a978.png)

I’m disappointed that it doesn’t take advantage of the space available. But it works OK. I would not object to using it. Let’s see what @lognaturel thinks.

**Comment by lognaturel** [comment]
Sounds great to me. It's clearly a big improvement to the tiny one that's there now.

**Comment by ArmenApresyan8** [comment]
It doesn't look great because it is designed for portrait screen.
OK then I'll open a PR soon.

**Comment by ArmenApresyan8** [comment]
![screenshot_20180315-144205](https://user-images.githubusercontent.com/18738136/37458666-2a8298b2-285f-11e8-9a5b-8b69fa14259f.png)
We can also use alpha slider, what do you think?

**Comment by grzesiek2010** [comment]
@ArmenApresyan8 do you still work on it? If not I can take a look.

**Comment by ArmenApresyan8** [comment]
You can work on it.

**Comment by ArmenApresyan8** [comment]
@grzesiek2010 you can work it.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
