### ISSUE TITLE
All blank forms to download are not visible when user adds and then removes text in search bar for Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1909]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
All blank forms to download are not visible when user adds and then removes text in search bar for Google Drive

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User adds text to search bar
4. User sees forms 
5. User removes text added to search bar
6. All available forms are not visible
![searchbargoogle](https://user-images.githubusercontent.com/3907554/36544025-52e0f28c-17dd-11e8-9253-007f7bb9ed25.gif)
#### Expected behavior
* All forms should be visible when user removes text in search bar

**Comment by Diefenbaker** [comment]
Hey, if it's ok I'd like to take a whack at this one? I've reproduced the issue locally and will have some time over the next few days to look at it.

**Comment by Diefenbaker** [comment]
@opendatakit-bot claim

**Comment by mmarciniak90** [comment]
@lognaturel 
I suggest that the search bar on Google Drive similar to search bar when user uses Aggregate. 
The dynamic search bar should be available to Google Drive because it is more user friendly. 
Searching when user clicks the magnifying glass icon causes a lot of issues.

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs discussion"
