### ISSUE TITLE
Fix lint warnings

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1912]
#### Problem description
Running `lint` gradle task detects **146** warnings!
```
Note: Some input files additionally use or override a deprecated API.
Note: Some input files additionally use unchecked or unsafe operations.
100 warnings
:collect_app:compileReleaseJavaWithJavac
:collect_app:lint
Ran lint on variant debug: 146 issues found
Ran lint on variant odkCollectRelease: 144 issues found
Ran lint on variant release: 144 issues found
```
#### Steps to reproduce the problem
Run `.gradlew/lint` in terminal 
 
#### Expected behavior
No warning 

#### Other information 
The report is generated here : `collect_app/build/reports/lint/lint-result.html`

The best approach to tackle this is to fix one issue at a time instead of fixing all in a single PR.

**Comment by lognaturel** [comment]
👍Some of the lint checks are not that useful and others result in so many files changed that there's too much risk to taking them on. For anyone interested in looking into this, please comment below with the lint check you'd like to resolve and get some feedback on whether it's a good one to take on. Thanks!

**Comment by nanahamzat** [comment]
I would like to look into variant debug issue. what do you think? @shobhitagarwal1612 @lognaturel

**Comment by lognaturel** [comment]
@nanahamzat I'm not sure which one that is! Could you link me to it? DrawAllocation is one that would be good to address: https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#DrawAllocation

Some others I think might be worth looking into:
- https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#StaticFieldLeak
- https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#UnusedIds (are they actually unused?)
- https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#RtlSymmetry
- https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#Overdraw
- https://1616-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#UselessLeaf

**Comment by ShivamArora** [comment]
I would like to work on it.

But I do have a question.

Do I need to work on all of them and then commit or resolve some of them and commit with some of the solved warnings?

**Comment by lognaturel** [comment]
@ShivamArora - you can find the answer in the original issue: "The best approach to tackle this is to fix one issue at a time instead of fixing all in a single PR." PR means pull request, apologies if that was unclear.

**Comment by huangyz0918** [comment]
@lognaturel Do you mean that we should address those issues one by one and each time we solved an issue ,we need to submit a new pull request ? 
Or just commit once after solving an issue and submit a single PR to hold all these commits?

Probably you’d prefer the first option? I’m not sure if this way may create lots of PRs

**Comment by grzesiek2010** [comment]
I'm closing this issue. I reviewed our lint's there is not much to do there and also it's not like we want to fix all warnings (or ignore), some of them shouldn't be fixed but are helpful so shouldn't be ignored as well.
