### ISSUE TITLE
Cluttered appearance of List Group 

### ISSUE THREAD

**Issue by vrjgamer** [getodk/collect#1913]
#### Software and hardware versions 
Collect v1.12.1, Android v7.1, device used Moto g4+

#### Problem description
The List group widget appears to be cluttered on small devices but works well with larger devices.

#### Steps to reproduce the problem
1. Get 'All Widgets' form from the 'Get Blank Form' Option.
2. Open the 'All Widgets' form and go to the page with 'List Group'.

#### Expected behavior
The page is suppose to a list of different widgets with all options clearly visible.

#### Other information 
A Solution can be to have the options appear below the question and also in a vertical order, I think this will ensure clear visibility of the options and questions.

**Screenshot**
![screenshot_20180217-011101](https://user-images.githubusercontent.com/10618953/36329502-2e7d449a-138c-11e8-87fd-642a6aedb248.png)

**Comment by lognaturel** [comment]
This is the intended behavior. This specific question looks much better on a bigger screen. When form developers use this on smaller screens they don't include a hint. What you suggested has been tried previously but it was not what surveyors wanted.
