### ISSUE TITLE
Blank hierarchy/jump view for RTL language

### ISSUE THREAD

**Issue by vrjgamer** [getodk/collect#1914]
#### Software and hardware versions 
Collect v1.12.1, Android v7.1.0, device used Moto g4+

#### Problem description
The 'All Widgets Page' that shows all the widgets in the form, is blank when a RTL language is selected.

#### Steps to reproduce the problem
1. Select a Right to Left language.
2. Get 'All Widgets' form from the 'Get Blank Form' Option and then open the form.
3. Click on Overview button in the top-bar (icon that looks like a diagonal arrow pointing a dot).

#### Expected behavior
The page should show a list of all the widgets in the form.

**Screenshot**
![assdsasa](https://user-images.githubusercontent.com/10618953/36568012-8119b73a-184e-11e8-87ea-4e7422b35568.jpg)
![screenshot_20180217-020613](https://user-images.githubusercontent.com/10618953/36329233-41b56ffc-138b-11e8-81b3-31e68978e5b2.png)

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot please be patient
