### ISSUE TITLE
Show current page number in the form

### ISSUE THREAD

**Issue by vrjgamer** [getodk/collect#1915]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
There is no visual element that tells the user how many pages he/she has visited till now. This will be a great improvement in the UI, specially for long forms.

#### Steps to reproduce the problem
Open any form

#### Expected behavior
Should show page number and total number of pages in the form

#### Other information 
I think showing a small pop-up on the bottom right corner of the page should work. I have created a small example of how it will look: 

![ui_update](https://user-images.githubusercontent.com/10618953/36568691-f34db28c-1850-11e8-8eb2-c5d742163051.png)
In the above ☝️ example, 9 is the page number and 20 is the total count of pages. 

This pop-up can be a temporary one. It can be shown when the user changes the page and then it can fade away after a few seconds. This will provide the required insights about the page number and total number of pages in the form.

**Comment by yanokwa** [comment]
Closing in favor of #616.
