### ISSUE TITLE
Navigation between questions while filling/viewing forms

### ISSUE THREAD

**Issue by raks097** [getodk/collect#1916]
#### Software and hardware versions 
Collect v1.13.0, Android 6.0, Sony Xperia C4 Dual

#### Problem description
![initform](https://user-images.githubusercontent.com/17434014/36575639-ffb8a128-1871-11e8-9988-8e1d2005b705.jpeg)
While filling or viewing the forms, the navigation buttons are missing below each question.
It would be much easier for the user to have some sort of buttons he can click on to navigate
between questions while filling the forms.I had to click the 'go to prompt' button every time to go to a 
different question.

#### Steps to reproduce the problem

Click on Fill Blank Form/Edit Saved Form
Choose a form you'd like to fill
Try going to the next question without using "go to prompt" button

#### Expected behavior
![fillingform](https://user-images.githubusercontent.com/17434014/36575877-4f283a4c-1873-11e8-97d6-95a03be5e72f.jpg)

Navigation buttons are seen below each question .

#### Other information 
While reviewing the code I found out that form_entry.xml does have ImageView (which are intended to act as buttons) as a part of the layout. form_entry.xml is used in FormEntryActivity.java but the intended navigation buttons are not being seen in the application.
It'd be helpful if someone can test it out on other devices as well to make sure it is not device specific.

**Comment by lognaturel** [comment]
Go to General Settings > User interface and set your preference for Navigation.
