### ISSUE TITLE
Options can be clicked twice in About Activity

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#1917]
#### Software and hardware versions 
Collect v1.12.2, 
Android v7.0, device used Moto M
Android v 4.4.2, device used Asus zenfone 5

#### Problem description
Options in `AboutAcivity` can be clicked twice. Fast double tapping of any of the option performs the action twice. 
  
#### Steps to reproduce the problem
1. Go to option menu.
2. Select `About` item.
3. Double click `Visit the ODK website` / `Join the ODK forum` / `Share ODK Collect` / `Leave a review` (quickly tap the option twice) 

On Moto M
1. `Visit the ODK website` 2 . `Join the ODK forum`
<img src="https://user-images.githubusercontent.com/16358982/36578850-d1900944-1885-11e8-8282-1843e2e3eb1d.gif" width=30%> <img src="https://user-images.githubusercontent.com/16358982/36578851-d1efa340-1885-11e8-8dbd-ec6676e7673d.gif" width=30%>

On Asus Zenfone 5

1. `Share ODK Collect` 2. `Leave a review`
<img src="https://user-images.githubusercontent.com/16358982/36579798-026608fc-188b-11e8-9c21-f09ad7cb65cf.gif" width=30%> <img src="https://user-images.githubusercontent.com/16358982/36579799-02976d20-188b-11e8-9e6c-de37e78244e8.gif" width=30%>

#### Expected behavior
The options should be clickable only once.

#### Other information 
Related to `AboutActivity` in package `org.odk.collect.android.activities`.
The reproducibility of issue is device dependent

**Comment by Thodoris1999** [comment]
@opendatakit-bot claim
