### ISSUE TITLE
"Select all" button should be disabled whenever user cancels the "Get blank form" task

### ISSUE THREAD

**Issue by lakshyagupta21** [getodk/collect#1919]
#### Software and hardware versions 
Collect v1.13.0-beta

#### Problem description
Whenever user cancels the "Get blank form" first time, user is able to click on "Select all" button even if there is no list displayed.
#### Steps to reproduce the problem
1. Get Blank Form
2. Tap on 'Cancel'
3. "Select all" button is enabled
#### Expected behavior
"Select all" button should be disabled if user cancels the task
#### Other information 
![ezgif com-resize 1](https://user-images.githubusercontent.com/18495162/36581653-08219c44-1894-11e8-84f1-cb0648888ae0.gif)

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
Done
@opendatakit-bot unclaim

**Comment by lakshyagupta21** [comment]
@ArmenApresyan8 There is no need to unclaim any issue if you raised a PR for it. It means that you're not working on this issue anymore.

**Comment by ArmenApresyan8** [comment]
@lakshyagupta21 So what should I do if I have finished it and I want to work on other issues?

**Comment by deveshSingh06** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
@deveshSingh06 I have already resolved this issue. #1922

**Comment by deveshSingh06** [comment]
@opendatakit-bot unclaim
