### ISSUE TITLE
[Screengrab] Set up a Dockerfile to build collect app and create ruby environment

### ISSUE THREAD

**Issue by Divya063** [getodk/collect#1920]
In reference to opendatakit/docs#487
 To simplify the process of setting up screengrab tool, set up a docker image to build collect app inside docker container and install gems necessary to run screengrab command.

**Comment by lognaturel** [comment]
Can you please provide more context for this one?

If I understand correctly, the challenge is that the `screengrab` tool requires having a ruby environment set up and that this can be complicated. The idea is to create a docker image that the tool can be run from.

The Collect repo seems like an unusual place to keep this! Could it be in the docs repo?

**Comment by lognaturel** [comment]
Glad you could screengrab working without this extra infrastructure! 😊👌
