### ISSUE TITLE
Use `WebViewActivity` for showing Open Source Licenses

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1926]
Remove the activity `OpenSourceLicensesActivity` and use `WebViewActivity` for showing the Open Source Licenses

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot claim

**Comment by ArmenApresyan8** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@shobhitagarwal1612 Can you explain a bit about what problem this solves?

**Comment by shobhitagarwal1612** [comment]
`WebViewActivity` was recently added which displays webpages using webview.
 `OpenSourceLicensesActivity` does the same thing, ie displays the open source licenses using a webview. But the UI of the `WebViewActivity` is more consistent with the ChromeCustomTabs. So, reusing the same class will remove redundant code and keep the UI consistent
