### ISSUE TITLE
Add missing tests in AllWidgetsTests

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1933]
Several tests in AllWidgetsTests are unimplemented.

testStringWidget or other tests that already are included can be used as an example. Some will be more challenging than others.

For more information about Android testing in an ODK context, see https://www.youtube.com/watch?v=6iZaRF3njH4

**Please comment below with the test you would like to add.**

**Comment by ArmenApresyan8** [comment]
I'll try to implement more tests :)

**Comment by garglakshya18** [comment]
I will try to implement some tests!

**Comment by garglakshya18** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Great @armenapresyan8 and @garglakshya18! Please comment with which you’re taking on (e.g “I’ll do all the select one variants”) so you don’t do the same ones.

**Comment by ArmenApresyan8** [comment]
I'm implementing range widgets right now.

**Comment by ArmenApresyan8** [comment]
I'll do date and time pickers next.
