### ISSUE TITLE
Spinner widget opens with end-of-list

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1935]
#### Software and hardware versions 
Collect v1.13.0 and older versions

#### Problem description
Spinner widget opens with end-of-list

#### Steps to reproduce the problem
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/3276264/36667657-ec0a0bd8-1aee-11e8-9f7f-2cb32a1e57e0.gif)

#### Expected behavior
The first element should be visible.

#### Other information 
Form for testing: 
[selectOneMinimal.xml.txt](https://github.com/opendatakit/collect/files/1758305/selectOneMinimal.xml.txt)

@opendatakit-bot label "contributor friendly"

**Comment by iammvaibhav** [comment]
claim

**Comment by iammvaibhav** [comment]
I would like to work on this

**Comment by shobhitagarwal1612** [comment]
Sure, please comment `@opendatakit-bot claim` below to claim this issue!

**Comment by iammvaibhav** [comment]
@opendatakit-bot claim
