### ISSUE TITLE
User should see icons in Admin Settings view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1936]
#### Problem description
`Admin Settings` view should be consistent with `About` view and  `General Settings` view.
User should see icons in `Admin Settings` view.

#### Steps to reproduce the problem
1. User opens `Admin Settings`

#### Expected behavior
* The `Admin Settings` view is consistent with `About` view and  `General Settings` view
* Blue icons are visible
* Full text is readable

#### Other information 
Related to #1802

**Comment by sashank27** [comment]
@opendatakit-bot claim

**Comment by sashank27** [comment]
@mmarciniak90 I would like to work on this issue

**Comment by Hanan194** [comment]
@lognaturel do you approve adding icons to this ?. I wanted to work on it but I then saw the needs discussion label

**Comment by devanshi7799** [comment]
@mmarciniak90 @lognaturel can I work on this issue?

**Comment by devanshi7799** [comment]
@opendatakit-bot claim

**Comment by devanshi7799** [comment]
@opendatakit-bot force-claim

**Comment by devanshi7799** [comment]
@opendatakit-bot claim

**Comment by devanshi7799** [comment]
@lakshyagupta21 I have not claimed any other issue in this repository. Can you please tell me why i am unable to work on this one?

**Comment by seadowg** [comment]
@devanshi7799 not sure what's happening here. @lognaturel I can't see @devanshi7799 assigned to any other issues do you have an idea what's got our bot confused?

**Comment by grzesiek2010** [comment]
You can use `claim --force` and it should do the job. @devanshi7799 the bigger problem is that the issue contains` needs discussion` label so we are not sure about it, so please investigate the issue and share your ideas first because it doesn't make sense to start working on the code immediately if we don't know what we expect.

**Comment by devanshi7799** [comment]
@grzesiek2010 @seadowg i think the icons in the Admin setting view must be similar to the ones used in General setting view. If you have any other ideas please suggest.
thanks :)

**Comment by grzesiek2010** [comment]
Adding an icon for every single option is not a must. There is nothing about it in the documentation https://material.io/design/platform-guidance/android-settings.html#placement
We decided to have icons just for categories that's ok I think in your device settings you probably can notice the same.
The thing is that `Admin Settings` doesn't contain only categories like `General Settings`.
In Admin Settings you have for example:
Admin Password or Reset Application. So if we add icons for such options why not for the others in General Settings eg. Username, Password etc.
However, I think we can decide to have icons just in the main screen for both General and Admin Settings no matter if it's a category or an option.
Another thing is that it might be difficult to find suitable icons for options like `Main Menu Settings`, `User Settings`, `Form Entry Settings`.
Maybe as a first step you can explore [icons](https://material.io/resources/icons/?style=baseline) and show us your proposal?

**Comment by grzesiek2010** [comment]
We are going to remove Admin Settings and new protected section will have icons so let's close.
