### ISSUE TITLE
Remove menu icon with General Settings option from Get Blank Form view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1937]
#### Problem description
Menu icon with General Setting option is visible which can cause confusions

#### Steps to reproduce the problem
1. User opens `Get Blank Form` view and sees all forms from Aggregate server
2. User clicks on menu icon (3 dots) and opens General Settings
3. User changes server to Google Drive and returns to previous screen
4. Forms from Aggregate server are still visible even if user refreshes view

#### Expected behavior
* I suggest to remove menu icon with General Settings option form Get Blank Form view

**Comment by mmarciniak90** [comment]
@lognaturel Is there any reason why we should keep this menu?

@opendatakit-bot label "needs discussion"

**Comment by lognaturel** [comment]
Removing it makes sense to me. @yanokwa also agrees.

**Comment by ShivamArora** [comment]
@lognaturel @mmarciniak90 Can you please explain what is the expected behavior of the app on returning back after changing preferences?

I didn't understand the problem why we need to remove the preferences from there?

EDIT: Understood the expected behavior from a discussion on Slack.

**Comment by ShivamArora** [comment]
@opendatakit-bot claim
