### ISSUE TITLE
Collect tries to send all forms even if error occurred precluding to continue sending

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1939]
#### Software and hardware versions 
Collect v1.13 and earlier

#### Problem description
Collect tries to send all forms even if error occurred precluding to continue sending

#### Steps to reproduce the problem
1. User sends a lot of forms
2. Error occurred (need to check few error types)
3. User is informed about error after sending all forms

#### Example of real use case:
1. User uses ODK Aggregate server
2. User sends 1000 forms which have declared google sheets `<submission action="https://docs.google.com/spreadsheets/d/***/edit?usp=sharing" method="form-data-post"/>`
3. Error occurred 
![screenshot_2018-02-26-19-43-40](https://user-images.githubusercontent.com/3907554/36679738-e12a5b4c-1b0b-11e8-8b03-e6a4ba8286c1.png)

4. User need to wait wait a few minutes because Collect tries to send all forms

#### Expected behavior
* Sending process should be stopped after the first error

**Comment by TheNerdyFeline** [comment]
@opendatakit-bot claim

**Comment by ayush13mishra** [comment]
@opendatakit-bot claim

**Comment by ayush13mishra** [comment]
@opendatakit-bot unclaim

**Comment by breakbusyloop** [comment]
@mmarciniak90 is there an easy way to get that many forms onto a device for testing this repro? Do you have a .zip of forms that I can download to use in testing?

**Comment by mmarciniak90** [comment]
@OpenDataNerd yes, you can copy data from this zip [backup1249.zip](https://github.com/opendatakit/collect/files/3972758/backup1249.zip)

**Comment by chidauri** [comment]
@opendatakit-bot claim
