### ISSUE TITLE
Select ones with spaces are not loaded on edit

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1942]
#### Software and hardware versions 
Collect v1.31.0

#### Problem description
[test.xlsx](https://github.com/opendatakit/collect/files/1760271/test.xlsx)
[test.xml.zip](https://github.com/opendatakit/collect/files/1760274/test.xml.zip)

1. Load the attached form. 
1. Select "za munda" as a country and swipe.
1. Confirm the country is loaded on the next page.
1. Save the form, and confirm on the SD card (adb into the phone, cat the instances file) that the XML has the value
1. Edit the saved form in Collect.
1. Confirm that "za munda" is not available.
1. Save the form, and confirm on the SD card (adb into the phone, cat the instances file) that the value is gone.

#### Expected behavior
When a form is loaded, all values that are persisted are loaded.

**Comment by grzesiek2010** [comment]
@yanokwa it's not Collect bug https://github.com/opendatakit/javarosa/issues/263
