### ISSUE TITLE
The dynamic search bar should be available on `Get Blank Form` view for Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1944]
#### Software and hardware versions 
Collect v1.13 and earlier

#### Problem description
The search bar on Google Drive should be similar to search bar when user uses Aggregate.
The dynamic search bar should be available to Google Drive because it is more user friendly.
Searching when user clicks the magnifying glass icon causes a lot of issues.

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User tries to search a form, he adds text
4. User need to click on magnifying glass icon to search
5. When user removes a part of added text, search bar shows empty view
6. When user removes a whole text, he need to click magnifying glass icon -> confusing toast appears and all forms are visible

#### Expected behavior
* Search bar should work in the same way as search bar for Aggregate server.
* Searching is performed when user adds or removes a letter. 
* It is not necessary to click on search icon

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
