### ISSUE TITLE
Repeat groups do not update their number of iterations when the variable changes

### ISSUE THREAD

**Issue by jniles** [getodk/collect#1945]
#### Software and hardware versions 
Collect v1.13.0, Android v7.1.1, Asus Zenfone 4 Max X00ID

#### Problem description
A repeat group does not change the initial number of iterations even if updated to a new value of iterations.  For example, if you ask "how many pets do you have?" and then repeat a series of questions for each pet, the user _must_ get the initial value right on the first time otherwise they will be stuck with an incorrect number of iterations/questions.

#### Steps to reproduce the problem
Make a repeat group with a dynamically-populated number of iterations.  Fill in the number of iterations and then swipe left to register it.  Return and update the value to a new number and notice that the repeat number of iterations is unchanging.

See the attached form.  
[BrokenRepeatForm.xlsx](https://github.com/opendatakit/collect/files/1762141/BrokenRepeatForm.xlsx)

#### Expected behavior
If a user updates the repeat group iteration value, the repeat group should only repeat that number of times.  If the user has already registered data in the repeat group, it should be removed/deleted if the iteration count decreases.  If it increases, the old data stays the same.

#### Other information 
None.

**Comment by lognaturel** [comment]
This behavior has so far been considered intentional to avoid the possibility of data loss if someone accidentally change the count. Embedding a group with a relevant based on the count is a way to get the behavior you want. More at https://forum.opendatakit.org/t/repeats-are-not-respecting-the-jr-count-value-after-a-change/11709/4

Do you feel strongly that repeats should be deleted?

**Comment by jniles** [comment]
@lognaturel , thanks for getting back to me so quickly.  I'll try the workaround and see how it works.  If we end up doing this for every form, then I'll reopen this as a feature request with the rationale.
