### ISSUE TITLE
Validate date in range

### ISSUE THREAD

**Issue by 2math** [getodk/collect#1946]
#### Software and hardware versions 
Collect v1.12.2, Android v8.1.0, device used... Nexus x5

#### Problem description
I have a select full date question in my form, which must be btw specific dates.
And doesn't pass the validation.
Here is the bind node from the XForm:
```
 <bind nodeset="/data/select_date" type="date" constraint="(. &gt;= '2018-01-01') and (. &lt;= '2018-03-31')" jr:constraintMsg="jr:itext('/data/select_date:constraintMsg')"/>
```

#### Steps to reproduce the problem
When I select any date in this range or even out side of the range, saving the answer doesn't pass the validation :(

#### Expected behavior
If the selected day is btw the constarined range to save the answer and pass validation
```java
    public IAnswerData getAnswer() {
          Date date = materialCalendarView.getSelectedDate();
          return new DateData(date);
      }
```
#### Other information 
Here is a test form :
[AllFieldsForm (1) (1).xml.txt](https://github.com/opendatakit/collect/files/1763397/AllFieldsForm.1.1.xml.txt)
I have tested it with Collect app too and is with same behaviour

I will appreciate any help.
Thanks!

**Comment by lognaturel** [comment]
For form design questions, please post to https://forum.opendatakit.org/c/support and tag with `form-design`!
