### ISSUE TITLE
Strings for missing intents should be translated

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1954]
The `activity_not_found` resource string takes a format argument to specify which task couldn't be completed (e.g. signature capture, image capture, etc).

Currently, this string is always in English. This may make it difficult for users who don't speak English to recover from the problem.

Introduce string resources for all the format argument strings currently used.

**Comment by ArmenApresyan8** [comment]
But are there translations for other languages?

**Comment by lognaturel** [comment]
@ArmenApresyan8 First of all, now that you've been a regular contributor, please leave the quick win issues for people new to the project! 😊

Then, you can read about the translation process in the README. Translations are generally added very quickly so they should be available in many languages by the next release.

**Comment by ArmenApresyan8** [comment]
@lognaturel Can I still contribute to contributor friendly issues? 😊

**Comment by roychowdhuryrohit-dev** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Yes, absolutely, @ArmenApresyan8!

Welcome @roychowdhuryrohit-dev and thanks for taking this on.

**Comment by lognaturel** [comment]
@roychowdhuryrohit-dev If you would still like to work on this issue, please accept the GitHub invitation you received. If not, someone else can take it on.

**Comment by hossamnasser938** [comment]
@lognaturel I've solved it and I'm ready to make a pull request but @opendatakit-bot prevents accept claiming as he thinks I'm on another issue but in fact I finished it and made a pull request waiting for review. I have finished all the work for this issue #1954

**Comment by lognaturel** [comment]
@hossamnasser938 please don’t take issues others have claimed. @roychowduhuryrohit-dev are you working on this? You are not showed as assigned because you have not accepted the invitation from GitHub yet.

**Comment by hossamnasser938** [comment]
Ok @lognaturel I did not now that @roychowdhuryrohit-dev have claimed

**Comment by hossamnasser938** [comment]
Thanks @lognaturel I've already resolved it and made a pull request waiting for review and testing
