### ISSUE TITLE
Log problems that aren't due to issues in Collect code at a log level lower than error

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1956]
#### Software and hardware versions 
Collect v1.13.0

#### Problem description
There are a number of issues logged with `Timber.e` that aren't related to Collect code problems. For example if a `ActivityNotFoundException` when an external intent is used, that's because the user is missing a particular application. In that case, the user should be notified through the UI. If an error is logged, it should be through `Timber.d` so it doesn't log remotely in production. 

Similarly, `JavaRosaException`s or `FileNotFoundException`s or `InvalidSyntaxException` in `ExternalDataUtil` are not ones we can change code to handle.

#### Expected behavior
`Timber.d` or `Timber.i` should be used for logging errors related to user input or device state.

**Comment by sashank27** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thanks for taking this on @sashank27! After you've completed this one, please make sure you take on bigger issues and leave `quick win`s for new people! 😊

**Comment by sashank27** [comment]
Sure @lognaturel :smile: 
Just a clarification, what exactly should I do for the `InvalidSyntaxException`s in `ExternalDataUtil` ?
