### ISSUE TITLE
Spinner widget does not open from start-of-list after swipe on options

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1960]
#### Software and hardware versions 
Collect v1.13.1 and older versions
Collect with #1955 
Android 4.1, 4.2, 4.4., 5.1, 6.0
Problem is not visible on Android 7.0 and 8.0
 
#### Problem description
Spinner widget does not open from start-of-list if user swipes on available options then closes widget and again opens it

#### Steps to reproduce the problem
1. User goes to Spinner Widget
2. User opens a option list
3. User swipes on list and sees middle options
4. User clicks outside the list to close it
5. User opens option list again
6. User sees middle options

| 1.13.1 | PR #1955 | 
| ------ | ------- |
| ![1 13 1](https://user-images.githubusercontent.com/3907554/36896162-6ac33928-1e09-11e8-9a00-4dbc5170fd9f.gif) | ![pr1955](https://user-images.githubusercontent.com/3907554/36896164-7104ffec-1e09-11e8-97dc-691ac6c2797d.gif) | 

#### Expected behavior
* Spinner widget opens from start-of-list

#### Workaround
* Select `Remove response` option (Edit Prompt -> Remove response is not a workaround)
* Change device orientation

**Comment by iammvaibhav** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@mmarciniak90 This seems like the right behavior to me. If the user taps out of the spinner after having scrolled in it, it may be accidental or to check something before coming back to pick an answer. Keeping the latest position seems useful.

**Comment by mmarciniak90** [comment]
@lognaturel Yes, you have right, it could be useful. 
I mentioned that the described case is not visible on Android 7.0 and 8.0, so should I transform this issue to fix behavior in the higher Android versions?

**Comment by lognaturel** [comment]
Oops, missed your latest comment! I missed that the behavior was different on different Android versions. Neither is really bad behavior so I would tend to leave it as it is. Having more special cases for Android versions makes code harder to deal with.
