### ISSUE TITLE
Display warning when select_multiple names have spaces in them

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1964]
For questions with multiple selection, the responses chosen by the user are stored as a space-separated list of the response `value`s. Most form builders either warn or error when a user tries to build a form with multiple selection questions that have `value`s with spaces but it's possible to include them when writing XML by hand or using external choices.

A little warning should be displayed when a choice has a space in it. This should look like the error that is shown when an image is missing (look for `R.string.file_missing` for examples).

https://github.com/opendatakit/javarosa/issues/263#issuecomment-369019465

Form: 
[multiple-spaces.xml.txt](https://github.com/opendatakit/collect/files/1776932/multiple-spaces.xml.txt) Notice that if you select some items, save the form, exit, reopen it, no values are selected.

Proposed text: "One or more underlying value is invalid because it has spaces in it."

https://github.com/opendatakit/collect/pull/2024 implements this feature for SelectMultiWidget. We need a more general solution, involving these related classes:
GridMultiWidget
SpinnerMultiWidget
ListMultiWidget
LabelWidget
SelectMultipleAutocompleteWidget
SelectMultiImageMapWidget

**Comment by iammvaibhav** [comment]
@opendatakit-bot claim

**Comment by iammvaibhav** [comment]
@opendatakit-bot unclaim

**Comment by ugoamanoh** [comment]
@opendatakit-bot claim
@opendatakit-bot claim

**Comment by bartekfi** [comment]
@opendatakit-bot claim

**Comment by bartekfi** [comment]
@opendatakit-bot claim --force

**Comment by bartekfi** [comment]
@lognaturel [Pull request](https://github.com/opendatakit/collect/pull/2251) that fixes this issue is created and ready to be reviewed.

**Comment by lognaturel** [comment]
Dear @opendatakit-bot, we are in testing so please bugger off! 🤖
