### ISSUE TITLE
Form name doesn't match latest finalized form in auto send notification

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1972]
#### Software and hardware versions 
Collect v1.13.0

#### Problem description
This is a user report and has not yet been confirmed. The user is seeing the wrong form name in the auto send notification.

#### Steps to reproduce the problem
1. Reset Collect by going to Admin Settings -> Reset
1. Set forms to auto send from general settings > form management
1. Download or transfer a few forms to the device
1. Fill a form, save and finalize it
1. Tap on the Collect clipboard icon in the notifications bar to see the auto send notification

#### Expected behavior
The form name should match the form that was just auto sent.

#### Other information 
This first needs to be reproduced. The code for the notification is in the `uploadingComplete` method of `NetworkReceiver`. I see no obvious cause for the problem.

**Comment by grzesiek2010** [comment]
Hmm, I can't reproduce this issue. Everything works well and the code also looks good.

**Comment by grzesiek2010** [comment]
@mmarciniak90 you can try when you are free.

**Comment by mmarciniak90** [comment]
@grzesiek2010, @lognaturel 
I tried to reproduce this bug without success.
I used the same app version.
I changed the form name at the end of filling a form and this changed name was visible in the notification which is good.
I tried also cases with no internet connection.

**Comment by lognaturel** [comment]
Thanks for the attempted reproductions, @grzesiek2010, @mmarciniak90. I'm not able to trigger the issue either.
