### ISSUE TITLE
The background of question text is still highlighted after listening to audio

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1975]
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
The background of question text is still highlighted after listening to audio.

#### Steps to reproduce the problem
1. Download `Birds` form from the demo server.
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/3276264/37034345-4f4c7888-2149-11e8-9e8a-e7a9da143c61.gif)

#### Expected behavior
I think we can get rid of that white background (It doesn't look good). Highlighting the text is enough.
@lognaturel do you agree.

**Comment by grzesiek2010** [comment]
@opendatakit-bot "quick win"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by hossamnasser938** [comment]
I'm working on this issue

**Comment by hossamnasser938** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Yes, I agree that highlighting the text is a sufficient indicator that audio is playing and that the background color change can be removed. 👍

**Comment by hossamnasser938** [comment]
Ok. I'm working on it @lognaturel

**Comment by hossamnasser938** [comment]
@lognaturel  Do you mean that the background color does not have to change when audio is playing?
