### ISSUE TITLE
There are no separator lines in SelectOneSearchWidget

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1976]
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
There are no separator lines in `SelectOneSearchWidget`

#### Steps to reproduce the problem
![screenshot_2018-03-06-14-55-04](https://user-images.githubusercontent.com/3276264/37035942-6f37b4dc-214e-11e8-8037-b5e1a50d759b.png)
![screenshot_2018-03-06-14-55-14](https://user-images.githubusercontent.com/3276264/37035943-6f98a2e2-214e-11e8-9d00-7631f2bcd0d0.png)

#### Expected behavior
I'm not sure whether we should add those lines in `SelectOneSearchWidget` or maybe remove them at all (from other widgets) but the layout in both cases should be consistent.

@lognaturel which approach do you prefer?

@opendatakit-bot label "quick win"
@opendatakit-bot label "needs discussion"

**Comment by hossamnasser938** [comment]
@grzesiek2010 I think the 'select one search widget' question lets the user search for search_widgets by typing first letter(s) but the 'select one widget'  does not. I think the case is not separator lines.

**Comment by grzesiek2010** [comment]
>  think the 'select one search widget' question lets the user search for search_widgets by typing first letter(s) but the 'select one widget' does not.

You are right but still, both widgets are for selecting one option so the layout should be the same.

**Comment by hossamnasser938** [comment]
So we have two different solutions whether to remove the EditText from 'Select one search widget' question or to add an EditText to 'Select one widget' question. Which one do you think is better?

**Comment by grzesiek2010** [comment]
No no no. You don't understand me. I mean that's ok we have one simple select one widget and another with an EditText for searching (we also offer a few other options like `autoadvance` etc. but never mind). I'm talking about that part of the layout where you have `RadioButtons`. It should look the same in both cases so we should have separators in both or remove them at all.

**Comment by hossamnasser938** [comment]
Oh yeah. You're wright. Now I understand what you mean. I'll work on it.

**Comment by hossamnasser938** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@hossamnasser938 I saw you already claimed at least two other `quick wins` so please leave this one for new contributors I think you can take something marked as `contributor friendly`.

**Comment by hossamnasser938** [comment]
@grzesiek2010 I claimed only one quick win and I'm trying to claim the second to get familiarized with the code base before contributing to contributor friendly

**Comment by arihant-001** [comment]
@opendatakit-bot claim

**Comment by arihant-001** [comment]
We should  have separators in both the widgets. It will look good with the line separators.

**Comment by arihant-001** [comment]
@opendatakit-bot unclaim
I have send a PR for fixing the issue.
I'm working on some other issue right now, so I unclaimed it.

**Comment by lognaturel** [comment]
Thanks, @ArihantJain456! Please don't unclaim an issue until it is closed.

**Comment by arihant-001** [comment]
If I don't then how I will be able to work on some other issue? @lognaturel

**Comment by arihant-001** [comment]
@opendatakit-bot unclaim

**Comment by akashdobaria** [comment]
I would like to work on this problem if available.

**Comment by lognaturel** [comment]
There was a pull request at #2072 but it caused a regression and we haven't heard from @Hanan194 so please go ahead, @akashdobaria. Do make sure to review #2072 and #1984 to see what has been tried before and why those approaches may not have worked. Thank you, @akashdobaria!

**Comment by akashdobaria** [comment]
@lognaturel I have submitted a pull request. Thank you. :)

**Comment by akashdobaria** [comment]
Hi @lognaturel,
I am sorry I opened a new pull request to submit the changes. It works fine now.

**Comment by ravi808** [comment]
@lognaturel  I would like to work on this problem.

**Comment by grzesiek2010** [comment]
@ravi808 there is a pull request ready for this issue https://github.com/opendatakit/collect/pull/2126
You can find something else :wink:

**Comment by ravi808** [comment]
@grzesiek2010  ok
