### ISSUE TITLE
Swiping back from end of form with repeat doesn't work

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1979]
#### Software and hardware versions 
Collect v1.13.2, Collect v1.12.0

#### Problem description
Swiping back from end of [repeat_group_new.xml.txt](https://github.com/opendatakit/collect/files/1786554/repeat_group_new.xml.txt) doesn't work. Swiping back and them forward goes to end of first repeat.

#### Steps to reproduce the problem
1. Open [repeat_group_new.xml.txt](https://github.com/opendatakit/collect/files/1786554/repeat_group_new.xml.txt)
1. Add a couple of repeats
1. Swipe to the end of the form
1. Swipe back, see that nothing happens
1. Swipe forward, see that you go back to the form

#### Expected behavior
1. Swiping back from the end screen should go to the end of the last repeat
1. Swiping forward from the end screen should not be allowed

#### Other information 
There should be automated tests in place for form navigation, especially with repeats. Note that this regression was not in the latest version. It could come from changes in JR. It could have something to do with forms that start with repeats.

**Comment by grzesiek2010** [comment]
@lognaturel we can close this issue since it's on the Javarosa's side https://github.com/opendatakit/javarosa/issues/278
