### ISSUE TITLE
RTL writing system is not visible on all views 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1981]
#### Software and hardware versions 
Collect v1.13.2
Devices with Android: 4.1, 4.2, 4.4, 6.0, 7.0, 8.0.

#### Problem description
RTL writing system is not visible on all views 

#### Steps to reproduce the problem
1. User uses Collect on RTL language
2. User opens Fill Blank Form / Get Blank Form / Delete Saved Form or starts filling some form
3. User sees that text is not start from the right of the page and continues to the left.

#### Expected behavior
* User sees text which starts from the right of the page and continues to the left on all views
* On one of my devices to tests - Huawei Y5 with Android 5.1 - RTL languages works as expected on most of all views.

#### Examples

| View | Android 6.0 - Moto G4 | Android 5.1 - Huawei Y5 | 
| ---- | ---- | ---- |
| Get Blank Form | ![screenshot_20180307-164007](https://user-images.githubusercontent.com/3907554/37090116-0100244c-21fb-11e8-9ff7-4fc941e4261f.png) | ![screenshot_2018-03-07-14-40-09](https://user-images.githubusercontent.com/3907554/37090133-0987df6a-21fb-11e8-9b21-76c00304904e.png) | 
| Fill Blank Form | ![screenshot_20180307-163619](https://user-images.githubusercontent.com/3907554/37090251-7f1d77e4-21fb-11e8-96e2-85b15f557280.png) | ![screenshot_2018-03-07-14-37-37](https://user-images.githubusercontent.com/3907554/37090256-8700d35c-21fb-11e8-9e79-47887e18dec6.png) | 
| Simple widget | ![screenshot_20180307-163716](https://user-images.githubusercontent.com/3907554/37090285-a5bc4254-21fb-11e8-808e-ec8b93caa546.png) | ![screenshot_2018-03-07-14-37-30](https://user-images.githubusercontent.com/3907554/37090292-ab1dacb0-21fb-11e8-97d7-69b2f6e34de6.png) | 
| Select one quick appearance | ![screenshot_20180307-164733](https://user-images.githubusercontent.com/3907554/37090380-0b4952c4-21fc-11e8-9668-6446b481bdf1.png) | ![screenshot_2018-03-07-14-46-32](https://user-images.githubusercontent.com/3907554/37090384-11fa7f94-21fc-11e8-8603-58ada74d0201.png)|

**Comment by Hanan194** [comment]
Hello, I'd like to work on this task as well

**Comment by Hanan194** [comment]
@opendatakit-bot claim

**Comment by kareemhamdy100** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@Hanan194, @kareemhamdy100 is one of you still interested in taking a look at this issue? Do you need help understanding it?

**Comment by kareemhamdy100** [comment]
I  Think my solution will solve it   !

**Comment by kareemhamdy100** [comment]
@opendatakit-bot unclaim

**Comment by kareemhamdy100** [comment]
I'm sorry but I have bad connection of internet so I'll leave  this problem  to others @lognaturel  
when my internet back  I will look forward to solve other quick win or other  issue and i will prepare my probosale too

**Comment by lognaturel** [comment]
Sorry to hear about your internet connection, @kareemhamdy100! Hoping it comes back for you soon and we look forward to seeing you then. 😊

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
In our `ODKView`, the direction of the `ViewPager` is from left to right (with LTR language).
But I think we need right to left slides in our forms with RTL language, It may be a new issue related to RTL languages. What do you think about that ?

__Schematic Pic:__
 <img src="https://i.loli.net/2018/03/23/5ab469a48da27.png" width = "300" align=center />
