### ISSUE TITLE
Problems with Range Widgets with RTL languages

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1983]
#### Software and hardware versions 
Collect v1.13.2

#### Problem description
Problems with Range Widgets with RTL languages

#### Steps to reproduce the problem
1. User uses RTL languages
2. User opens Range widget
3. Horizontal widget shows incorrect value on Android 4.4 (Vertical widget works as expected)

| Integer | Decimal  | 
| ---- | ----|
| ![screenshot_2018-03-07-13-19-56](https://user-images.githubusercontent.com/3907554/37092012-1c4f991a-2202-11e8-9c60-621d8fe419c1.png) | ![screenshot_2018-03-07-13-20-29](https://user-images.githubusercontent.com/3907554/37092015-1e7bd820-2202-11e8-8ea1-e07e5a8b0561.png) |

4. Vertical widget shows incorrect value on Android 5.1,  6.0, 7.0, 8.0

| Integer | Decimal  |
|----|----|
| ![screenshot_20180307-164121](https://user-images.githubusercontent.com/3907554/37092225-e4fa9dba-2202-11e8-8a1e-853d02367d1d.png) | ![screenshot_20180307-183643](https://user-images.githubusercontent.com/3907554/37092567-4112e11a-2204-11e8-9c37-bcbc13947b7b.png)|

5. Vertical widget is not centred on Android 4.2 and values are incorrect
6. Min and max values are overlapped in horizontal widget on Android 4.2

|  |  |  | | 
| ---- | ---- | ---- | ---- |
| ![screenshot_2018-03-07-13-37-41](https://user-images.githubusercontent.com/3907554/37092908-6a941a26-2205-11e8-8a2a-8f1d99b37bc2.png) | ![screenshot_2018-03-07-13-38-02](https://user-images.githubusercontent.com/3907554/37092920-750eae80-2205-11e8-8f5b-888376c35b79.png) | ![screenshot_2018-03-07-13-37-56](https://user-images.githubusercontent.com/3907554/37092922-752d50d8-2205-11e8-9b22-e05829756eef.png) |![screenshot_2018-03-07-13-37-50](https://user-images.githubusercontent.com/3907554/37092923-754cd534-2205-11e8-94d4-9d2b88426092.png)|

#### Expected behavior
* Range Widget always shows correct values

**Comment by Hanan194** [comment]
Hello, I want to take this task , will start working on it and show my progress as soon as possible

**Comment by Hanan194** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot unclaim

**Comment by huangyz0918** [comment]
This is a widget full of issues :(
__Tested Device:__
Samsung Galaxy S8, Android 7.0

__Problems:__
Vertical widgets show an incorrect value, and the blue line used to highlight disappeared.

| __Integer__       |__Decimal__       |
| --------  | :-----: |
| ![](https://i.loli.net/2018/03/22/5ab3c709a22fc.png)        | ![](https://i.loli.net/2018/03/22/5ab3c709a2627.png)     | 





Horizontal widget works well.
This is a problem associated with RTL language, I'm currently working on [issue#1981](https://github.com/opendatakit/collect/issues/1981), which is also a RTL problem, I think I can address both of them if they came from similar reason. If anyone would like to collaborate with me on these two issues, I would be very happy :>

**Comment by mmarciniak90** [comment]
@huangyz0918 
The problem with blue line looks more like https://github.com/opendatakit/collect/issues/1262.
Incorrect value is mentioned in point 4 of the problem description.
The behaviour of Range Widgets depends on Android version.

**Comment by jingege315** [comment]
@opendatakit-bot claim

**Comment by jingege315** [comment]
@opendatakit-bot unclaim

**Comment by huangyz0918** [comment]
I got a solution and successfully tested, and it worked !
Similar with #1981 , these problem caused by both Android Views and RTL languages circumstance.
I will open a new PR to submit my solution! :)

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
