### ISSUE TITLE
Update dependencies that don't need Play Services update

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1990]
Several dependencies are now out of date. See `build.gradle` in AndroidStudio to see them highlighted. 

All dependencies that can be updated should be. Because Play Services is a big download, it should not be updated at this time. That means dependencies such as `firebase-core` can't be updated immediately.

Other dependency updates may have issues with them so it will be important to verify that the updates work.

**Comment by arundhatigupta** [comment]
@lognaturel Thanks for assigning that issue to me. :)
I needed a little clarification on that. 
I can see outdated dependencies in the build.gradle. As you mentioned, Play Services is a big download and should not be updated at this time, what I need to do is to update all other dependencies to the latest possible version that work, except Play Services. Is that what I need to do? :)

**Comment by lognaturel** [comment]
That’s right!
