### ISSUE TITLE
Update testing dependencies

### ISSUE THREAD

**Issue by arundhatigupta** [getodk/collect#1996]
#### Problem description
Currently, the build.gradle consists of outdated testing dependencies. 

#### Expected behavior
The outdated testing dependencies should be updated to the latest version for which the code works well.

**Comment by arundhatigupta** [comment]
@opendatakit-bot claim

**Comment by arundhatigupta** [comment]
I am working on it. Stuck with failing tests.

**Comment by lognaturel** [comment]
@opendatakit-bot can be very impatient. 😊Consider posting a work in progress PR or some error messages you're getting here or in #collect-code to get some ideas from other community members.

**Comment by shobhitagarwal1612** [comment]
This is the Mockito and Powermock compatibility table


Mockito | PowerMock
-- | --
2.8.0-2.8.9 | 1.7.x
2.7.5 | 1.7.0RC4
2.4.0 | 1.7.0RC2
2.0.0-beta - 2.0.42-beta | 1.6.5-1.7.0RC
1.10.8 - 1.10.x | 1.6.2 - 2.0
1.9.5-rc1 - 1.9.5 | 1.5.0 - 1.5.6
1.9.0-rc1 & 1.9.0 | 1.4.10 - 1.4.12
1.8.5 | 1.3.9 - 1.4.9
1.8.4 | 1.3.7 & 1.3.8
1.8.3 | 1.3.6
1.8.1 & 1.8.2 | 1.3.5
1.8 | 1.3
1.7 | 1.2.5

Right now, we are already on the max version of PowerMock but we can't upgrade the Mockito to version 2.11.o as it breaks the tests cases

**Comment by grzesiek2010** [comment]
Reviewing and updating dependencies is something I do after each release so we can close.
