### ISSUE TITLE
Two 'Pause' icons are visible when user tries to play few sounds quickly

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1999]
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
Two 'Pause' icons are visible when user tries to play few sounds quickly

#### Steps to reproduce the problem
1. User opens `Birds` form from the demo server
2. User clicks on `Speaker` icon
3. `Speaker` icon is changed to `Pause` icon 
4. User immediately clicks on some other `Speaker` icon
5. User sees two `Pause` icons

| | |
| ---- | ---- |
| ![screenshot_20180312-132041](https://user-images.githubusercontent.com/3907554/37283574-615b4828-25f0-11e8-8dc9-c6eeb60eb3ae.png) | ![screenshot_20180312-132110](https://user-images.githubusercontent.com/3907554/37283580-64f2c10a-25f0-11e8-9529-c29a67273817.png)|

#### Expected behavior
* The `Pause` icon should be restored to `Speaker` icon if user starts to play other sound

#### Other information 
Noticed during testing #1987

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by laddha-adi** [comment]
I would like to work on this.

**Comment by sgrG24** [comment]
@opendatakit-bot claim

**Comment by laddha-adi** [comment]
hi @sgrG24 I am already working on this issue. You can find some other here https://github.com/opendatakit/collect/issues there are plenty of them!

**Comment by nwagu** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
