### ISSUE TITLE
Two kinds of cursive font are visible on hints - Andoroid 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2002]
#### Software and hardware versions 
Collect v1.13.2 and older 
Android 4.1

#### Steps to reproduce the problem
1. User opens `All Widget` form from demo server
2. User sees hints

![screenshot_2018-03-12-15-02-44](https://user-images.githubusercontent.com/3907554/37288465-411fcd72-25ff-11e8-9557-680f18b3a47c.png)
![screenshot_2018-03-12-15-03-14](https://user-images.githubusercontent.com/3907554/37288467-42f1a54e-25ff-11e8-9f1e-1ce32898d107.png)

#### Expected behavior
* Cursive font is the same for all text in hints

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "quick win"

**Comment by lognaturel** [comment]
This is caused by underscores in `select_one` and `select_multiple` which are being interpreted as markdown directives. I would tend to leave it as-is but if someone has a proposed alternative, please share.

**Comment by didicodes** [comment]
@opendatakit-bot claim

**Comment by didicodes** [comment]
hello @lognaturel  i want to fix this issue and i need some confirmation about it. From my understanding the issue is that the "selectmultiple" and "canadablank_map.svg" on the screenshot do not have the same font? To fix this issue i need to make all the hints have the same cursive font right? please correct me if otherwise thank you

**Comment by lognaturel** [comment]
The root of the problem is that the text is `select_multiple` and `Canada_blank_map`. Those underscores are being interpreted as markdown emphasis.

I think the fix should be to support escaping markdown directives using `\` as described in #2018. The form will then be changed to `select\_multiple` and `Canada\_blank\_map`. This will require updating `markdownToHtml` in `TextUtils` and the corresponding tests. Does that make sense?

**Comment by didicodes** [comment]
yes it does. I would ask any other question if i get stuck. Thank you

**Comment by didicodes** [comment]
@lognaturel i cant find the Image select multiple widget tag in the all_widgets.xml android resource file but i can find every other widget in the app but each time i run the ODK collect app on my phone it is also reflecting like every other widget is there any reason for this? because it doesn't even have a Java Activity. Should i add it to the all_widgets.xml file and create a java activity for it ? I need your feedback thank you

**Comment by lognaturel** [comment]
`all_widgets.xml` is a form that the Collect app renders. You can download it from the default server by going to 'Get Blank Forms', selecting it, tapping 'Download Selected'. You can then view it by tapping on Fill Blank Form and then tapping on the All Widgets form. You can read more about using Collect at http://docs.opendatakit.org/collect-intro/

Edit: I'm guessing you're looking at the testing `all_widgets.xml` form in the source which is now out of date. You can use the one from the server to see the latest.

**Comment by didicodes** [comment]
by default server do you mean from the ODK collect app?

**Comment by didicodes** [comment]
or from the ODK aggregate server

**Comment by didicodes** [comment]
hello @lognaturel sorry to disturb but I'm still waiting for your reply

**Comment by lognaturel** [comment]
I mean the Aggregate server configured in Collect settings if you make no changes to default settings. That has the latest version of the form.

**Comment by didicodes** [comment]
@lognaturel  yay! you replied *smiling *. When i do this would  be able to access the codes of the form to make changes to it?

**Comment by lognaturel** [comment]
Yes, you can pull the form off the device using adb, make changes and push it back. http://docs.opendatakit.org/collect-forms/?highlight=adb#loading-forms-with-adb (there's also `adb pull`. The form will be at `/sdcard/odk/forms/All Widgets.xml`).

**Comment by didicodes** [comment]
![screenshot_2018-03-20-12-53-13](https://user-images.githubusercontent.com/28895379/37654388-2982461a-2c42-11e8-880b-b9369389faa6.png)
![screenshot_2018-03-20-13-17-03](https://user-images.githubusercontent.com/28895379/37654389-29ce6478-2c42-11e8-9140-38b937204f49.png)
hello @lognaturel please look at the pictures and confirm if the issue has been fixed so i can make a pull request

**Comment by didicodes** [comment]
or should i go ahead and make a pull request @lognaturel ?

**Comment by lognaturel** [comment]
It does look like you have addressed the different fonts, @edyasikpo! But it doesn't seem like you escaped the _ as I had suggested or we would see them in `select_multiple`, for example. What approach did you take? You can also open a pull request and describe your approach there.

**Comment by didicodes** [comment]
i actually tried to escaping the markdown into HTML and it looked this way 
select\_multiple and Canada\_blank\_map 
Is that okay?

**Comment by didicodes** [comment]
oh it seems GitHub uses Markdown too because the backward slash i added isn't showing. 
my point is when i added the the backward slash to select_multiple and Canada_blank_map and pushed the codes to my phone the backward slash was still reflecting. 
@lognaturel

**Comment by lognaturel** [comment]
That means you made changes to `markdownToHtml` in `TextUtils` and the corresponding tests, right? If so, it sounds like there's one more step to do which is not to display the backslash when it is used to escape the following character. If you look at issue #2018 it may give you some ideas on the regular expressions and tests to try.

**Comment by didicodes** [comment]
okay Thank you

**Comment by didicodes** [comment]
![screenshot_2018-03-23-00-51-11](https://user-images.githubusercontent.com/28895379/37806095-50256fa6-2e3e-11e8-96c4-a72991337f57.png)
![screenshot_2018-03-23-00-51-24](https://user-images.githubusercontent.com/28895379/37806096-508b6590-2e3e-11e8-93d6-bffd28562013.png)
Hello @lognaturel . I carefully modified the TextUtils.java and the TextUtilsTest.java files like you suggested and its now working. I am so excited. I made a pull request some minutes ago. Thank you for the help so far.

**Comment by lognaturel** [comment]
#2018 is the issue to resolve.
