### ISSUE TITLE
Google Sheets media uploads should be more clearly named

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2005]
As described at https://forum.opendatakit.org/t/google-drive-sheets-as-server/12208/5

> the names of the media files should used the instance name or something that can be easily identify. like the name of the image files, audio files and video files. they are in numeric which does not give a clear picture as to which entry it belongs to when you download it.

@shobhitagarwal1612 when you have a chance, can you update this issue with the current behavior of the Google Sheets media upload? I think it'd be great if we could tie the media file uploads to the submission in some way.

**Comment by shobhitagarwal1612** [comment]
@yanokwa Media files are uploaded to google drive with the original name of the media

**Comment by yanokwa** [comment]
Correct, but they are all put in one folder, right? So if I download all the media files, I can't easily tell which image file belongs to which submission.

**Comment by shobhitagarwal1612** [comment]
That's correct

**Comment by grzesiek2010** [comment]
Files are uploaded to `Open Data Kit/Submissions/formIdDir/` I think it should be `Open Data Kit/Submissions/formIdDir/instanceIdDir/`

**Comment by grzesiek2010** [comment]
@yanokwa does this issue still need discussion or maybe I can go ahead according to my comment above?

**Comment by yanokwa** [comment]
I think what you've proposed would be a good change. But I wonder if this will be disruptive to change the format. Is it possible to only use this new format if `formIdDir` folder is empty? Any other concerns you can think of, @lognaturel?

**Comment by grzesiek2010** [comment]
@nodarik 
you are a real user so I think it's a good idea to ask you about your opinion because after that situation with reverting hyperlinks I'm a little bit afraid of such changes :smile:

**Comment by lognaturel** [comment]
Agreed it would be great to get feedback from @nodarik! 

My guess is that the current structure is sufficient. I'm guessing most users access media from the spreadsheet so the directory structure doesn't matter much. The access can be either by clicking on the link to the media or like @nodarik, scripting to pull all media files. In fact, a flat structure makes most scripting easier.

**Comment by grzesiek2010** [comment]
I created a topic on the forum to discuss the issue https://forum.opendatakit.org/t/store-media-files-uploaded-to-google-drive-in-separate-directories/23435 so let's close this one and continue there.
