### ISSUE TITLE
Support guidance form for hints

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2007]
From https://opendatakit.github.io/xforms-spec/#languages:

> Even within a single language, it is helpful to have multiple ‘forms’ of the same string. For example, a verbose phrasing used as the caption when answering a question, but a short, terse phrasing when that question is shown in the form summary. This can be done using the form attribute.

> Supported for <hint> content only. It is a description of the question that can be used to provide further guidance to enumerators. It is not meant to be shown in the client UI by default, but could be shown in a special view mode or on printouts.

I propose adding a setting at the bottom of General settings > form management > form filling labeled `Show guidance for questions` with possible values `Yes` and `No`. It should be `No` by default. If it is set to `Yes`, guidance text will be shown below the hint in blue italics.

Behavior discussion at https://forum.opendatakit.org/t/collect-collapsible-training-hints-guidance/12247

**Comment by lognaturel** [comment]
An alternative would be to provide two options for display: `Yes - collapsed` and `Yes - always shown`.

For `Yes - collapsed`, the `guidance` text could be shown collapsed by default with the option to click to expand (e.g. https://github.com/freecats/TextViewExpandableAnimation). I can see this being useful when enumerators don't fill a form out very often and may want to refresh their memory on the intent for a particular question.

**Comment by jd-alexander** [comment]
@opendatakit-bot claim

**Comment by jd-alexander** [comment]
@opendatakit-bot claim --force

**Comment by atl2017** [comment]
Hi @lognaturel  how can test it in xlsform? Or Is it possible to include in "All Widgets" form?
