### ISSUE TITLE
User sees modern progress bar during loading a blank form list from Google Drive and Aggregate

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2009]
#### Problem description
User should see a modern progress bar during loading a blank form list from Google Drive and Aggregate

##### Case with Aggregate server
1. User uses Aggregate server
2. User opens `Get Blank Form` view
3. Progress dialog is visible

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/37350008-a6562030-26cf-11e8-8392-d2d6c2223875.png">

##### Case with Google Drive
1. User uses Google Drive
2. User opens `Get Blank Form` view
3. User does not see information about progress

#### Expected behavior
* Modern progress bar is visible
* Progress bar is the same for the Aggregate server and Google Drive

**Comment by lognaturel** [comment]
Using a progress bar seemed like a good idea initially but now I'm thinking keeping that dialog and doing the same for Google Drive would be a great start. We may want to couple changing the progress indicator to a change in how the forms themselves are loaded (async).

**Comment by lakshyagupta21** [comment]
I was not able to see any dialog or anything else which shows that Google drive is loading its content, so I added progress dialog similar to aggregate server which will be shown whenever user clicks on any directory or changes between `Shared with me` and `My Drive`. If it looks fine then I can send a PR for this


![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/18495162/39655239-33dbb4a0-5016-11e8-83d3-b39fe284c4b4.gif)

**Comment by lognaturel** [comment]
@lakshyagupta21 that looks great to me. I /think/ that's what the issue was about but now I'm not totally sure and it would be good to get confirmation from @mmarciniak90. But either way, the change you're proposing is a good one. 👍

**Comment by shobhitagarwal1612** [comment]
The toolbar layout now includes a progress bar which is displayed in rest of the form/instance loading activities. Making the loading behaviour consistent throughout would be better. What are your thoughts @lognaturel @lakshyagupta21 ?

**Comment by lognaturel** [comment]
My sense is that the progress bar is appropriate for loading blank forms and filled forms from disk because those appear progressively. Since this is not the case for server listings, it seems that something that takes up the full UI is more appropriate. Perhaps eventually those form listings will be cached and only updated with new info in which case a progress bar could work but in the short term I think @lakshyagupta21’s suggestion is a good one.

**Comment by mmarciniak90** [comment]
@lognaturel  @lakshyagupta21 
This issue was created because we talked about change progress bar style to more modern. 
If we do this change, we should also ensure cohesion and add the new progress bar to Google Drive case.

**Comment by seadowg** [comment]
We're currently not focusing on improvements for the Google Drive flows so closing this.
