### ISSUE TITLE
Fix failing circle CI build

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2011]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
The build is failing because of an unused resource. This should be fixed quickly so that unwanted errors can be prevented from getting merged.

#### Steps to reproduce the problem
Try running `./gradlew lint` locally 

https://1926-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#UnusedResources

#### Expected behavior
Build should pass without any fails.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by manishakeim** [comment]
@opendatakit-bot claim

**Comment by Shrreya** [comment]
@opendatakit-bot claim

**Comment by Shrreya** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thanks for your interest in this issue, @Shrreya! Please be sure not to claim issues that are already assigned.

@manishakeim Any update on this? It would be good to get this fixed before merging other changes.

**Comment by Shrreya** [comment]
Sorry about that @lognaturel, I just started making myself familiar with the codebase. Could you suggest another quick win issue for me to begin with?

**Comment by lognaturel** [comment]
Actually, since this one his high-priority and you're available right now, I've assigned you back to it @Shrreya! Sorry about the confusion. Next time make sure to look for an unclaimed issue.

**Comment by manishakeim** [comment]
@lognaturel I'm working on it now
