### ISSUE TITLE
Use the X-OpenRosa-Accept-Content-Length header

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2012]
#### Software and hardware versions 
Collect v1.13.x

#### Problem description
From https://forum.opendatakit.org/t/12239

Collect doesn't currently use the `X-OpenRosa-Accept-Content-Length` header but always splits files into 10Mb posts. If a file exceeds 10Mb, it will be sent in its own post with the submission XML.

#### Expected behavior
Collect follows the agreed upon API at http://docs.opendatakit.org/openrosa-form-submission/

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @yanokwa, I need some help. If we're using `X-OpenRosa-Accept-Content-Length`, then how much size should be allowed as the content length, is it fine to go with 20Mb?

**Comment by yanokwa** [comment]
I think the idea here is that the server will respond with a Content-Length that it would like (e.g., https://github.com/opendatakit/collect/blob/master/collect_app/src/androidTest/java/org/odk/collect/android/tasks/InstanceServerUploaderTest.java#L105)  and that is the amount Collect should use to submit data. 

If the server doesn't specify a length, then we should do what Collect does now, default to 10MB (https://github.com/opendatakit/collect/blob/HEAD/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L411)

**Comment by SaumiaSinghal** [comment]
Okay @yanokwa, is it like the server attaches a Content-Length, whatever it likes, and we should use `X-OpenRosa-Accept-Content-Length` header to fetch it and if the length is more than that, then only, we must split files into that size post?  And if the server doesn't specify a length, then we should do what Collect does now.
