### ISSUE TITLE
Required message ignored when jr:requiredMsg is set

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2013]
#### Software and hardware versions 
Collect v1.13.0

#### Problem description
`jr:requiredMsg` on bind is ignored.

#### Steps to reproduce the problem
1. Load a form with a required message such as [required.xml.txt](https://github.com/opendatakit/collect/files/1809160/required.xml.txt)
1. Swipe forward on the first question

#### Expected behavior
Custom message should be shown.

#### Other information 
I've confirmed this works in Collect v1.12.0. This is likely a JavaRosa issue but wanted to file here first so that can be confirmed.

https://forum.opendatakit.org/t/pyxform-not-using-custom-required-message/12227

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@lognaturel we can close this issue since it's on the Javarosa's side https://github.com/opendatakit/javarosa/issues/275

**Comment by grzesiek2010** [comment]
@opendatakit-bot unclime
