### ISSUE TITLE
The gap between the *View Sent Form* and the *Get Blank Form* is really large compared to other views in the ODK collect v1.13.2

### ISSUE THREAD

**Issue by didicodes** [getodk/collect#2014]
#### Software and hardware versions 
Collect v1.13.2, 

#### Expected behavior
The distance between all the views should be the same

#### Other information 
Enhancing the Xml File

**Comment by manishakeim** [comment]
@opendatakit-bot claim

**Comment by Shrreya** [comment]
@opendatakit-bot claim

**Comment by Shrreya** [comment]
@opendatakit-bot claim --force

**Comment by edyasikpo** [comment]
claim

**Comment by didicodes** [comment]
@opendatakit-bot claim

**Comment by didicodes** [comment]
@opendatakit-bot claim --force

**Comment by grzesiek2010** [comment]
I'm pretty sure it's not a bug and it was considered probably to separate options used for downloading/removing forms and options used for working with forms (filling, editing etc.). 
@lognaturel what do you think?

**Comment by Shrreya** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
Thank you for looking into ODK Collect, @edyasikpo! As @grzesiek2010, this works as intended.
