### ISSUE TITLE
Remove `Go back` button and add `Select All` button on Get Blank Form with Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2015]
#### Software and hardware versions 
Collect v1.13.2

#### Problem description
Remove `Go back` button and add `Select All` button on Get Blank Form with Google Drive

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`

#### Expected behavior - acceptance criteria
* `Go back` button is removed. User is able to go back by clicking on device back button.
* `Select All` / `Clear All` button is visible instead `Go back` button. `Select all/clear all` functionality works correctly with Google Drive.

**Comment by mmarciniak90** [comment]
@lognaturel I have 2 questions:
* Should all forms be selected or unselected when user opens `Get Blank Form` view?
* Should the previously downloaded forms be unchecked? Should it recognize which forms have been downloaded and which have not been, as in the case for Aggregate?

@opendatakit-bot label "needs discussion"

**Comment by ravi808** [comment]
@mmarciniak90  are these issues resolved? I see all these changes have been made. 
As per your question, I suggest only the forms which are previously downloaded should be unchecked.

**Comment by mmarciniak90** [comment]
@ravi808 I'm quite busy with other project and I'm not up-to-date. Are you sure that it works in that way when you select Google Drive as a server?
