### ISSUE TITLE
Markdown: escaping, newlines, paragraphs

### ISSUE THREAD

**Issue by MartijnR** [getodk/collect#2018]
Hi there,

We've made some non-controversial tweaks to Markdown support in Enketo that may be interesting to adopt in Collect:

* support for escaping \* and \_ and \#
* fixed various subtle header bugs
* make a distinction between paragraphs (2 or more newline chars)and simple single newline chars to fix subtle bugs

updated regexes:
https://github.com/enketo/enketo-transformer/blob/master/src/markdown.js

updated tests:
https://github.com/enketo/enketo-transformer/blob/master/test/markdown.spec.js

**Comment by lognaturel** [comment]
Thanks, @MartijnR! 

Related to #2002 (being able to escape _ would solve it)

**Comment by didicodes** [comment]
@opendatakit-bot claim

**Comment by didicodes** [comment]
Yes! :smiley:

**Comment by lognaturel** [comment]
Leave us alone, @opendatakit-bot, we still have a QA backlog!
