### ISSUE TITLE
Missing Back Arrow (Up button) in Action Bar.

### ISSUE THREAD

**Issue by AjaySharvesh3** [getodk/collect#2025]
# Up Arrow vs Back Button
The Up button is used to navigate within an app based on the hierarchical relationships between screens.
So, Navigation of Up button in action bar is very useful for interior working operation in the application. Here is that missing. 
Now, this app is using the only Back button which is on mobile's bottom button. The mobile Back button is used to navigate, in reverse chronological order, through the history of screens that the user has recently worked with it. It is generally based on the temporal relationships between screens, rather than the app's hierarchy.
![odk](https://user-images.githubusercontent.com/27482105/37496734-46e2f756-28da-11e8-8b7d-6be65550e8d9.JPG)
#
**_Back button can return the user to the Home screen, or even to a different app.
Using Up Arrow button is very helpful and ensure that user remains in the app._**

**Comment by udhay24** [comment]
@opendatakit -git claim

**Comment by udhay24** [comment]
@opendatakit -bot claim

**Comment by udhay24** [comment]
@opendatakit-bot claim

**Comment by AjaySharvesh3** [comment]
@opendatakit-bot claim --force

**Comment by lognaturel** [comment]
I'm not sure that this is a desired feature. When Collect is opened from an external app, it's generally not desirable for an enumerator to go back to the main screen. 

I don't think the arrow adds much in the case of screens like About. 

Would be good to get other opinions before anyone starts making this change.

**Comment by grzesiek2010** [comment]
I'm not in favor of doing that. I think we don't need such an option and it's also not that common.

**Comment by shobhitagarwal1612** [comment]
> I'm not in favor of doing that. I think we don't need such an option and it's also not that common.

+1

**Comment by lognaturel** [comment]
Thanks for the idea, @AjaySharvesh3! Let's not make the change at this time. If you are looking for an issue to take on, please look for `quick win` and `contributor friendly` tags.
