### ISSUE TITLE
Update all_widgets.xml and AllWidgetsFormTest to match XLSForm in README

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2035]
As @edyasikpo noticed [here](https://github.com/opendatakit/collect/issues/2002#issuecomment-373554661), the `all_widgets.xml` form used in `AllWidgetsFormTest` is out of date with the form linked to from the README.

To update the form and test:
- [ ] Download the form from the README to an Excel file and then [convert it to XML](http://docs.opendatakit.org/form-design-intro/#javarosa-compliant-build-tools)
- [ ] Replace the existing `all_widgets.xml` document
- [ ] Move, add and remove widget tests from `AllWidgetsFormTest` to match the new version. For the `image-map` one that will be added, a body with just the `screenshot` call is sufficient for now

**Comment by vigneshtdev** [comment]
claim

**Comment by edyasikpo** [comment]
@opendatakit-bot claim

**Comment by vigneshtdev** [comment]
@lognaturel  
Here is list of widgets whose test's are to be removed: range_decimal_widget_vertical `testRangeDecimalVertical()` trigger_widget `testTriggerWidget()`.
Here is list of widgets whose test's are to be added: range_integer_widget_picker, image_widget_no_choose, select_one_image_map, elect_multi_image_map.

Can you/someone cross-check my work, so that I can proceed further?

Thanks.

**Comment by ayush13mishra** [comment]
claim

**Comment by ayush13mishra** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@ayush13mishra, please unclaim this issue. As I’m sure you saw, @vettyvignesh has started exploring it. @vettyvignesh, you are right, please proceed and make sure to claim the issue.

**Comment by eaasiedu** [comment]
Hello, I'd like to take a shot at this issue!

**Comment by lognaturel** [comment]
Hi @eaasiedu! @vettyvignesh already has a pull request open for this one (#2043)! @vettyvignesh please comment with `@opendatakit-bot claim` so it's clear this one is in progress. 😊

**Comment by vigneshtdev** [comment]
claim

**Comment by didicodes** [comment]
@vettyvignesh to actually claim this issue don't just type claim rather type `@opendatakit-bot claim`

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @lognaturel ...there's a little confusion if this issue is still open or not..If it's still open, I would like to give it a shot.

**Comment by SaumiaSinghal** [comment]
I just went through the code and found the widgets tests that need to be removed is testRangeDecimalVertical()...and the widgets whose tests need to be added are range_picker_integer_widget, image_without_choose_button_widget, selfie_video_widget, file_with_no_appearance_widget, select_one_image_widget, select_multiple_image_widget. 

This list is slightly different from the one suggested by @vigneshtdev. 

Can u check it once @lognaturel and tell me if i'm going in the right direction.
