### ISSUE TITLE
Checkbox click is focused on center in `Reset application`

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#2036]
#### Software and hardware versions 
Collect v1.13.2
Android v7.0 Moto m
Android v8.0 Google Pixel 2

#### Problem description
1. Moto m &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.Google Pixel 2
<img src = "https://user-images.githubusercontent.com/16358982/37699173-39053c6c-2d0c-11e8-86f4-25c0f67f1909.gif" width=30%> <img src = "https://user-images.githubusercontent.com/16358982/37701799-636c3e42-2d16-11e8-9a51-f73b467d6543.gif" width=30%>

#### Steps to reproduce the problem
Open `Collect`.
Go to option items.
Open `Admin Settings`.
Click `Reset application...`.
Check and uncheck options.

#### Expected behavior
Click on check box should not be focused on cente but on the checkbox itself. 
Also, text  `Reset application...` can be improved to `Reset application`.

#### Other information 
Couldn't reproduce the same issue on Asus zenfone 5.
Seems like issue is dependent on API level of device running `Collect`.

**Comment by grzesiek2010** [comment]
Why do you think it's a bug? The behavior might be different using various Android versions but that possibility to click on the title too is even better - consider people with big fingers :smile:  believe me it might be a problem to click on such a small checkbox.

**Comment by akshay-ap** [comment]
The title should be clickable.
I thought it is a bug because the animation shown on screen after clicking a checkbox is shown at the center of the screen. I had expected it to be shown on the checkbox.

**Comment by grzesiek2010** [comment]
Ohh I see it's definitely not our bug. If you want you can probably disable that animation in your device settings.

**Comment by lognaturel** [comment]
I think the animation is just wherever the tap happens. 

What about not having the animation since other places where we have selects don't include animations? On my Android 5.1 device they are very big which is unexpected and a bit strange!

**Comment by akshay-ap** [comment]
If the complete app is devoid of animations for selects, I think its better to do same in this case.

**Comment by grzesiek2010** [comment]
I fixed the problem and now we use the same effect like in other settings:
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/3276264/42514545-f7643f06-8459-11e8-844c-18ca05d1d1ce.gif)
