### ISSUE TITLE
Toggle button text not displayed as expected in Get Blank Form

### ISSUE THREAD

**Issue by lakshyagupta21** [getodk/collect#2039]
#### Software and hardware versions 
Collect v1.13

#### Problem description
Select all/Clear all button text not displayed as expected.
#### Steps to reproduce the problem
1. Get `Blank Form`
2. Search for any form
3. Tap on `Clear all`
4. Tap on `Select all`
5. Tap back button or close the search
6. List will be displayed with all the items selected and toggle button with label "Select all"

#### Expected behavior
Instead of `Select all` button `clear all` should be displayed

#### Other information 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18495162/37734410-1541fe9a-2d71-11e8-864e-bcc9a544a222.gif)

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by AbanoubGhadban** [comment]
@opendatakit-bot claim
