### ISSUE TITLE
Problem with field-list and constraints

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2041]
#### Software and hardware versions 
Collect v1.13.2 and all older version

#### Problem description
If we have two (or more) questions on one page and we use constraints a user may be blocked and can't navigate forward.

#### Steps to reproduce the problem
The easiest form to reproduce the issue: 
[problem.xml.txt](https://github.com/opendatakit/collect/files/1837502/problem.xml.txt)

1. Ope the attached form
2. In question 1 select the first radio button and in select two the second one
3. Navigate forward
4. Navigate Back
5. Change your answers - (question 1 - the second radio button  and question 2 the first one)
6. Navigate forward.

#### Other information 
The problem has been originally reported here: https://forum.opendatakit.org/t/error-on-odk-app-which-is-not-on-ona-webform/12296

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
I’m studying the code and the problem.

**Comment by dcbriccetti** [comment]
I added some logging to help understand the problem. I annotated the log and attached screen shots. Perhaps this will help us generate some alternate solutions.
[collect issue 2041 details.pdf](https://github.com/opendatakit/collect/files/1959508/collect.issue.2041.details.pdf)

[Where the logging comes from](https://github.com/opendatakit/javarosa/pull/306).

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/opendatakit/collect/pull/3023

**Comment by lognaturel** [comment]
🙌Thanks for following up on this, @grzesiek2010. Great that we could get to a generalized solution.
