### ISSUE TITLE
Replace the ic_save_black_36dp (png) with scalable vector

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2046]
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
Replace the ic_save_black_36dp (png) with scalable vector

We already have such a vector icon and we sue it in FormEntryActivity so there is no need to add a new one.

@opendatakit-bot label "quick win"

**Comment by CRMinges** [comment]
@opendatakit-bot claim
