### ISSUE TITLE
Media files are lost when user changes them but then ignores the changes.

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2049]
#### Software and hardware versions 
Collect v1.11.1, 1.14.0

#### Problem description
Media files are lost when user changes them but then ignores the changes.

#### Steps to reproduce the problem
1. User fills form and adds some media : video, photo, audio
![screenshot_20180323-100230](https://user-images.githubusercontent.com/3907554/37821010-54321450-2e7a-11e8-876c-9be96d744bcf.png)
2. User saves form
3. User edits form and update media
![screenshot_20180323-100319](https://user-images.githubusercontent.com/3907554/37821026-6101ee76-2e7a-11e8-9952-8d6718a9efc9.png)
![screenshot_20180323-100329](https://user-images.githubusercontent.com/3907554/37821032-63c99fbe-2e7a-11e8-86f9-5c67d3bf6cb5.png)
4. User ignore last changes 
![screenshot_20180323-100336](https://user-images.githubusercontent.com/3907554/37821035-671394cc-2e7a-11e8-8e0f-a4ed8a05ee04.png)
5. User opens form again
![screenshot_20180323-100354](https://user-images.githubusercontent.com/3907554/37821052-73512ca4-2e7a-11e8-9e8e-e91897cac47e.png)
6. Media is not available
![screenshot_20180323-100419](https://user-images.githubusercontent.com/3907554/37821328-306c098a-2e7b-11e8-8b3c-08629a61af99.png)
![screenshot_20180323-100424](https://user-images.githubusercontent.com/3907554/37821331-32ef1d1e-2e7b-11e8-88df-607b0cc8222e.png)

#### Expected behavior
Media files are not removed from device when user clicks on change it but when user saves form.

**Comment by grzesiek2010** [comment]
@opendatakit-bot calim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
