### ISSUE TITLE
add circle.yml so CI test output is visible

### ISSUE THREAD

**Issue by lindsay-stevens** [getodk/collect#205]
As described in [1] and shown in [2], adding a configuration file for CircleCI will allow individual test results to be shown. This would also be used to grab build artifacts for releases (but I'm not sure on the process for that). Happy to do this if / when #204 is merged so there's some content to show.

[1] https://circleci.com/docs/android/#test-metadata
[2] https://circleci.com/docs/android/#sample-circleyml

**Comment by max2me** [comment]
[Here is a PR](https://github.com/opendatakit/collect/pull/211) with basic CircleCI config that spits out APK into artifacts folder.

Once #204 is merged, we will need to ensure CircleCI correctly picks up test output.

**Comment by yanokwa** [comment]
Done! I've also added a link to the readme.
