### ISSUE TITLE
Add tests for bearing widget

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#2057]
#### Software and hardware versions 
Collect v1.13.2

#### Problem description
There is no test to check app behavior when the sensor to record bearing is available/unavailable.
It is being done manually.
#### Expected behavior
Add tests to verify the behavior of bearing widget.
#### Other information 
I shall add tests.

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @lognaturel, is this issue still open, Can i work on it?

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
There are lots of places we could cover with tests but creating a separate issue for every one which then exists for a long time doesn't make much sense. So we can close it.
