### ISSUE TITLE
Reduce gradle dependecies on UW-CSE servers

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#206]
"The 4 product build flavors exist because Collect currently shares its gradle configuration with the ODK 2.0 tool suite. ODK 2.0 uses the 3 of the build flavors to generate different binaries (Snapshot = new binary for each commit, Demo = synchronized stable points, Master = full release), and the last flavor (uitest) for separating out tests that require graphics rendering (our build server runs headless).

Collect is not currently part of that workflow, so it is possible to remove those flavors if there is community will to do it. I do not anticipate it being a lot of work, but we'd want to check against the common gradle config in this repository: https://github.com/opendatakit/gradle-config/"

@jbeorse What would it take to clean up the build files so there aren't dependencies on UW-CSE servers? Do you also think it'd be reasonable to get rid of the common gradle config? My overarching goal here is to reduce complexity so it's easy for folks to get started.

**Comment by srsudar** [comment]
How much of the signing stuff do we want to keep in the gradle files? E.g. [these lines](https://github.com/opendatakit/collect/blob/master/collect_app/build.gradle#L47). What is the vision for Collect's release process? I remember there was some talk about nightly signed builds, but I don't know what the outcome of that discussion was.

**Comment by srsudar** [comment]
[Here is a branch](https://github.com/srsudar/collect/tree/remove-uw-gradle) with a much simplified gradle config. I've removed the signing information, so I'm going to hold off on a PR until my question above about whether or not we want this in is resolved. It builds and installs locally for me.

**Comment by max2me** [comment]
@srsudar I'm still trying to figure out how everything is setup etc but your changes look good and simplify a lot.

**My 2c to your question:**
Given non-existent test coverage, I don't see us pushing out artifacts automatically to any users in the short run. So I assume that all releases will be done manually and we don't have to keep signing info in gradle config. This would also make CircleICI config simpler.

If you & @yanokwa agree, please file a PR.

**Comment by yanokwa** [comment]
Agreed that we don't want to push releases, but weekly/nightly builds seem like a reasonable idea. Is that possible to automate?

**Comment by max2me** [comment]
CircleCI will produce artifacts for us upon each check-in, we could also setup triggers for nightly/weekly check-ins. In all cases it depends on how we want to distribute APKs. Submitting them to alpha group through Play store might be tricky without setting up signing, but we could easily dump it into S3 bucket somewhere or do something more sophisticated if needed.

**Comment by lognaturel** [comment]
Talked to @yanokwa and he agrees something like builds dumped into an S3 bucket is a fine place to start.

@srsudar Is there a particular reason to use version 2.1.0 of the Android Plugin for Gradle? I upgraded to Gradle 3.1 and plugin 2.2.2 with no issues. It has the advantage of enabling Instant Run.

**Comment by srsudar** [comment]
@lognaturel not that I'm aware of. I think I was just eliminating files rather than altering anything, though I can update it as well and issue a PR.

**Comment by lognaturel** [comment]
@srsudar Sounds awesome! 👌

**Comment by srsudar** [comment]
@lognaturel I'm only seeing Android Studio (2.2.2) suggest upgrading to Gradle 2.14.1, though I see 3.1 has been released. [This document](http://tools.android.com/tech-docs/new-build-system/version-compatibility) suggests using the latest Gradle (i.e. 3.1), but also says Android studio requires 2.14.1+. I don't know 1) how up to date that page is, or 2) if the 2.14.1+ refers only to the patch version (2.14.x) or all versions (including 3.1).

I'm going to leave it as 2.14.1 for now, but am happy to upgrade it if you think 3.1 is the way to go. I've not yet gone above 2.14.1 in any of my projects, but more due to ignorance than conscious decision.

**Comment by lognaturel** [comment]
@srsudar Sounds great to me. I don't know the implications and there don't seem to be any obvious 'wins' to going up to 3.1.
