### ISSUE TITLE
Match Briefcase export behavior when repeats are submitted to Google Sheets

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2063]
#### Software and hardware versions 
Collect v1.14.0 beta

#### Problem description
Currently repeats are tied to their parent record but not their parent repeat in the case of nested repeats.

#### Steps to reproduce the problem
Use a form with nested repeats with Google Sheets as the server - [nested-indexed-repeat.xml.txt](https://github.com/opendatakit/collect/files/1849095/nested-indexed-repeat.xml.txt) for example.

#### Expected behavior
Match the Briefcase behavior by specifying `KEY` and `PARENT_KEY` columns instead of the current `instanceID` column that all repeats get. The only difference is that `KEY` includes the XPath path of the current node and `KEY_PARENT` includes the path of the parent node.

| friend_index | pet_index | friend | pet | note |              meta-instanceID              |                    KEY                    |
|--------------|-----------|--------|-----|------|-------------------------------------------|-------------------------------------------|
|            1 |         2 | Bob    | Baz |      | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6 |

| friend_count | friend_name | pet_total | pets_count |                PARENT_KEY                 |                         KEY                          |
|--------------|-------------|-----------|------------|-------------------------------------------|------------------------------------------------------|
|            1 | Bob         |         2 |          2 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[1] |
|            2 | Bill     |         1 |          1 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[2] |
|            3 | Farouk     |         2 |          2 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6 | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[3] |

| pet_count | pet_name |                      PARENT_KEY                      |                             KEY                              |
|-----------|----------|------------------------------------------------------|--------------------------------------------------------------|
|         1 | Fido      | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[1] | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[1]/pets[1] |
|         2 | Fanny      | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[1] | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[1]/pets[2] |
|         1 | Prancer     | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[2] | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[2]/pets[1] |
|         1 | Dancer       | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[3] | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[3]/pets[1] |
|         2 | Bob       | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[3] | uuid:3cc27b08-7ab4-42a6-9261-48eb2f9827d6/friends[3]/pets[2] |

**Comment by lognaturel** [comment]
For the top level record, `KEY` will be a duplicate of the `instanceID` column if it exists or a UUID that Collect generates at upload time if `instanceID` doesn't exist. https://forum.opendatakit.org/t/repeat-groups-and-google-sheets-upload/6677/30

**Comment by grzesiek2010** [comment]
> or a UUID that Collect generates at upload time if instanceID doesn't exist

could you tell me where it takes place? I can't see that.

**Comment by lognaturel** [comment]
What do you mean? Where it should take place? This is not currently-existing behavior, it's a further requirement for the issue based on your suggestion.

**Comment by grzesiek2010** [comment]
ok, so that UUID should be generated by myself right? I understood that we already use such an id somewhere.

**Comment by lognaturel** [comment]
> oks so that UUID should be generated by me right?

Yes, exactly. 😊
