### ISSUE TITLE
Replace icons used in geo activities using vectors

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2068]
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
In our geo activities we use png icons so it would be good to remove them and use vectors instead.

Icons I'm talking about:

ic_add_location_black_36dp
ic_my_location_black_36dp
ic_layers_black_36dp
ic_delete_black_36dp
ic_person_pin_circle_black_36dp
ic_place_black_36dp
distance

@opendatakit-bot label "quick win"

**Comment by orsidudas** [comment]
@opendatakit-bot claim

**Comment by orsidudas** [comment]
Hello,
the distance icon is not available in the Clip Art. I've searched some other options, can I change the picture for any of these? Which one will be a good option?
![gesture](https://user-images.githubusercontent.com/11819879/38062761-0c8d5896-32f6-11e8-9c89-0ac52414730b.PNG) ![swap](https://user-images.githubusercontent.com/11819879/38062762-0caba648-32f6-11e8-876d-25f8a8d9ddc7.PNG) ![tab](https://user-images.githubusercontent.com/11819879/38062763-0cc7d1e2-32f6-11e8-8078-d13f2c787e1a.PNG) ![timeline](https://user-images.githubusercontent.com/11819879/38062807-3827854e-32f6-11e8-8dac-bd77707dbf4f.PNG) ![vertical align](https://user-images.githubusercontent.com/11819879/38062764-0ceaa370-32f6-11e8-9a16-b9e29fbfdb69.PNG)

**Comment by grzesiek2010** [comment]
@orsidudas 

No those icons are not good you can try to find something free (be careful) https://www.google.pl/search?q=distance+icon&oq=distance+icon&aqs=chrome.0.69i59j69i61j69i60l2.2407j0j9&sourceid=chrome&ie=UTF-8

If it's not possible let me know and I can prepare such an icon in Inkscape.

**Comment by MrPKGupta** [comment]
@orsidudas 
You can try converting png to vector. Lots of websites are providing this for free.

**Comment by aryansoni1108** [comment]
@grzesiek2010 
You can try this website it has many vector icons for all your need
https://www.flaticon.com/

**Comment by nani92** [comment]
@opendatakit-bot claim
