### ISSUE TITLE
Warn about bad URLs in new forms

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#207]
As discussed in #175, Collect should scan new forms and warn about invalid URLs. Since it's so hard to change the URL of a submission once it's created, you shouldn't really be allowed to continue.

**Comment by shouryalala** [comment]
@yanokwa May i give this a shot?

**Comment by yanokwa** [comment]
@shouryalala Yes, but before you send in a PR, write a quick proposal about your approach to fixing this.

**Comment by shouryalala** [comment]
@yanokwa I did look into the issue thoroughly and i think the best possible method to tackle this would be to implement a method that would scan the submission url as soon as the form is downloaded. 
If there is a submission url, it can check for its validity by seeing if its possible to establish a connection.
All this would be implemented in the setGoogleDriveFormDownloadListener Async task so it would notify the user as soon as the form is downloaded. What do you think?

**Comment by yanokwa** [comment]
@shouryalala This sounds good to me. And to be clear, I think the form be downloaded, parsed, and then if it doesn't have the URL, it should be removed from the device and the user should be alerted. I'm looking forward to your pull request!

**Comment by dr0pdb** [comment]
@yanokwa 
If this is still open, then instead of trying to establish a connection to check the validity of the ```URL``` can't we just use ``` Patterns.WEB_URL.matcher(potentialUrl).matches()```. [Source](https://stackoverflow.com/a/5930532/6748052)
Establishing a connection is expensive in terms of resources. What do you think ?

**Comment by lognaturel** [comment]
@srv-twry I know that @shobhitagarwal1612 had done some work to validate URLs but I don't quite remember the context. @shobhitagarwal1612 do you remember? I think there was a lot of conversation about the approach there.

**Comment by shobhitagarwal1612** [comment]
I worked on this issue #873. That issue was to prevent the forms with bad submission_url from getting downloaded from aggregate

**Comment by lognaturel** [comment]
Thank you! Is it possible that these are duplicates? This one doesn't have a lot of details but I think they're the same! Would be good to get confirmation from @yanokwa

**Comment by shobhitagarwal1612** [comment]
I am also quite confused with this line. Scan new forms from where?

>  Collect should scan new forms and warn about invalid URLs

**Comment by lognaturel** [comment]
Perhaps he meant in the `DiskSyncTask` for forms that are manually added to the sdcard? That seems like #709 though.

**Comment by shobhitagarwal1612** [comment]
I can confirm that the forms added manually to sd card with bad submission URL are not getting loaded. #709 is fixed

**Comment by lognaturel** [comment]
🙏 @shobhitagarwal1612! @yanokwa I would like to close this unless you have more details on what the issue is.

**Comment by yanokwa** [comment]
Sorry about not closing this issue. I agree that it's been fixed by https://github.com/opendatakit/collect/pull/716 (forms from disk) and https://github.com/opendatakit/collect/pull/1059 (forms from Aggregate)
