### ISSUE TITLE
Selected form is not marked when the user scrolls up and down but form can be downloaded from Google Sheets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2074]
#### Software and hardware versions 
Collect v1.14.0, 
verified on Android 5.1, 6.0

#### Problem description
Selected form is not marked when the user scrolls up and down but form can be downloaded from Google

#### Steps to reproduce the problem
1. The user uses Google Sheets
2. The user opens `Get Blank Form`
3. The user selects some forms and scrolls up, the selected form is not visible in the screen
4. The user scrolls down to see selected form
5. The form is unselected but `Download Selected` button is active and the user can download the form

#### Expected behavior
* Selection does not disappear

**Comment by grzesiek2010** [comment]
@lakshyagupta21 

could you explain why [here](https://github.com/opendatakit/collect/pull/1970/files) you got rid of RecyclerView I implemented [here](https://github.com/opendatakit/collect/pull/1780)?

**Comment by lakshyagupta21** [comment]
@grzesiek2010 
We already had the code for search and sort so to reuse the same code I changed the implementation. At the time of implementation, I didn't notice this issue. 
I'll look into it.

**Comment by lognaturel** [comment]
I'm not able to reproduce this even though I do have forms that can scroll off the screen. Presumably it can happen if the form list is very long?

**Comment by lakshyagupta21** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18495162/38121241-b31fb9b0-33eb-11e8-8744-8a6b5082c15f.gif)
