### ISSUE TITLE
Collect crashes on Import/Export settings.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2075]
#### Software and hardware versions 
Collect v1.14.x, Android v6.0, 5.1 probably other versions too.

#### Problem description
Collect crashes when choosing Import/Export settings.

#### Steps to reproduce the problem
1. Go to Admin Settings
2. Click on Import/Export Settings

#### Expected behavior
The barcode should appear and it should be possible to export/ import settings.

#### Other information 
Screenshot attached:
![screenshot_collect crash](https://user-images.githubusercontent.com/33342488/38074826-78bffdfe-3330-11e8-85ac-4ffc46b38ce7.png)

**Comment by grzesiek2010** [comment]
@kkrawczyk123 I think your branch is not updated, the problem has been fixed in https://github.com/opendatakit/collect/pull/2071 could you confirm?

**Comment by kkrawczyk123** [comment]
I can confirm that this issue has been already fixed on master.
