### ISSUE TITLE
The user is not able to remove response on required data and time widget when only one value is added

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2076]
#### Software and hardware versions 
Collect v1.14.0
Verified on Android 5.1, 6.0

#### Problem description
The user is not able to remove response on required data and time widget when only one value is added

#### Steps to reproduce the problem
1. Open the attached form - [dateTimeTest.xml.txt](https://github.com/opendatakit/collect/files/1859336/dateTimeTest.xml.txt)
2. Go to the required question
3. Select one value (date or time) and hold to open `Remove response` dialog
4. Remove response
5. Value is not removed
 
#### Expected behavior
* Value is removed even if only part of the answer is added

**Comment by grzesiek2010** [comment]
I'm not sure if it a bug...
if a user adds only one value in such a case it's not treated as an answer and if you navigate backwards/forward, change a device orientation or open the hierarchy view it's cleared.

So if it's not treated as an answer it shouldn't be cleared too.

**Comment by mmarciniak90** [comment]
So we should block appearing the `Remove Response` dialog. 
In my opinion, if the dialog is available it should work.

**Comment by grzesiek2010** [comment]
I agree there is no point in showing that option if the answer is null.
