### ISSUE TITLE
Save button icon is not visible on maps of Geopoints widgets.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2078]
#### Software and hardware versions 
Collect v1.14.x, Android v6.0, 5.1 probably other versions too

#### Problem description
Save button is not visible on maps of Geopoint widgets.

#### Steps to reproduce the problem
1. Go to Geopoint widget with map appearance
2. Start Geopoint, map should open

#### Expected behavior
It used to be 5 buttons in a map panel - save button icon is missing now, there is just small square which has saving functionality. 

#### Other information 
I used a regular All widgets form.
Screenshot attached:
![screenshotsavebutton](https://user-images.githubusercontent.com/33342488/38081684-e4ae59b6-3344-11e8-86bd-668f94e21492.png)

**Comment by grzesiek2010** [comment]
@kkrawczyk123 the same as https://github.com/opendatakit/collect/issues/2075#issuecomment-377165282

**Comment by kkrawczyk123** [comment]
I confirm it has been fixed on master.
