### ISSUE TITLE
Show geometries already collected when using the map to collect a new geometry

### ISSUE THREAD

**Issue by khalifeserge** [getodk/collect#2083]
This feature already existed PARTIALLY in GeoODK but never made it to ODK collect when the feature from GeoODK where backported to ODK collect. It would be very useful if the map showed the previous geometries collected. THere should some sort of control over what is show and that could maybe be accomplished with an appearance keyword or some other way that the ODK Collect developer think is best. The functionality should include the following

1. Show all geometries from all forms already collected on the map
2. Show all geometries collected using this form (any version) (all instances of this form)
3. Show only geometries collected in this instance of the form (assuming the gps in a repeat group)

It would also be nice if the map widget could have a snap option that would allow the user to press near a node and have the geometry snap to it. This would allow collecting information or networks (roads, electric, water) to be completed in a more user friendly way and would make ODK even more useful for GIS activities

Regards

**Comment by lognaturel** [comment]
Same as with the other feature description -- can you please post on https://forum.opendatakit.org/c/features and be sure to separate out features that are different? Thanks!
