### ISSUE TITLE
Media layout doesn't work as expected in RTL locales

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2101]
First identified by @vrjgamer and partially addressed by #1958.

The layout should be mirrored from LTR.

**Comment by huangyz0918** [comment]
It will be easier to fix those issues if we give up `API == 16`.
Building a method with @ TargetApi

**Comment by lognaturel** [comment]
Good point, @huangyz0918. It's totally ok to give up on API 16 since it's not as common these days.

**Comment by huangyz0918** [comment]
So, let me give it a shot, @opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot yes, dude
