### ISSUE TITLE
Add image crop view in ImageWidget

### ISSUE THREAD

**Issue by huangyz0918** [getodk/collect#2104]
#### Problem description
When I am using the ImageWidget, I feel uncomfortable because the image cannot be resized by myself (although I can click this image to launch my system gallery, my gallery has **no crop** feature). ODK Collect just simply put the whole image into the form and has no options for me to crop that. I have to take a lot of pics until I get a satisfied one. 
#### Expected behavior
I think we should add a build-in `image-crop` view when user has finished their photo shooting.
#### Other information 
I'd like to improve this.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs discussion"
@opendatakit-bot claim

**Comment by ghost** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Tracked [on the forum](https://forum.getodk.org/t/allow-cropping-image-from-camera-or-gallery/12778) waiting for feedback and a design.
