### ISSUE TITLE
Add an analytics event to find out how often ActivityLogger is enabled

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2109]
We need to deprecate ActivityLogger (https://github.com/opendatakit/collect/issues/1395), but we don't know how many people are using it.

One easy first win on this issue might be to sending a Google Analytics event if `sdcard/odk/log/enabled` exists. https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/ActivityLogger.java#L117 might be a good place for this code.

Once we get data from one or two releases, then we can decide when/how we proceed.

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
