### ISSUE TITLE
Audit log: end screen event doesn't show end time when followed by constraint error

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2111]
For example, use form [group-audit.xml.txt](https://github.com/opendatakit/collect/files/1896743/group-audit.xml.txt) and put in a string longer than 2 characters in the untitled2 field. The log says:

```
end screen,,1523402518461,
constraint error,,1523402521285,
```

To see the log, save the form at least once, `adb shell` to go into the device and then `cat /sdcard/odk/instances/group-audit_yyyy-mm-dd_hh-mm-ss/audit.csv`.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
