### ISSUE TITLE
Field list questions are shown on separate screens after jump because of constraint error

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2112]
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
Field list questions are shown on separate screens after jump because of constraint error

#### Steps to reproduce the problem
1. Use a form with a question in a field list that has a constraint such as [group-audit.xml.txt](https://github.com/opendatakit/collect/files/1896749/group-audit.xml.txt)
1. Enter a value that violates the constraint (e.g. Foobar in the form above)
1. Jump to the end of the form
1. Tap save and finalize
1. Jump back to the question with the constraint but on a single screen

#### Expected behavior
Jump back to the field list with the question that is problematic highlighted

**Comment by grzesiek2010** [comment]
I wouldn't say it's a bug. I'm pretty sure it was a considered solution to indicate which answer is not valid. If we return to the field list you don't know which question it was about. 
If you want to change this behavior we need to for example change the background color of such an invalid question to indicate it.

So I would rather mark this issue as an improvement, not a bug.

**Comment by lognaturel** [comment]
I'm ok marking this as an enhancement but I do think it breaks expectations. The code is simply `this.jumpToIndex(outcome.failedPrompt);` and I don't think the intent was to break up a field list, it's a side effect of jumping to the specific question rather than the containing field list.

Note that when jumping to a question in the field list after this happens you're back in the field list. When the constraint message is shown when swiping away from a field list, it's also unclear which question caused the toast. I've filed that in #2118 and perhaps we can start by coming up with a good UI change for that and then address this one.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
