### ISSUE TITLE
Audit log: end time not included in jump event

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2113]
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
Jump events are logged without an end time:
```
group questions,/data,1523402512553,1523402516517
jump,,1523402516517,
```

#### Steps to reproduce the problem
1. Use a form with audit logging such as [group-audit.xml.txt](https://github.com/opendatakit/collect/files/1896749/group-audit.xml.txt)
1. Jump to somewhere else in the form
1. To see the log, save the form at least once, `adb shell` to go into the device and then `cat /sdcard/odk/instances/group-audit_yyyy-mm-dd_hh-mm-ss/audit.csv`

#### Expected behavior
The jump start time matches the end time of the event before it. Similarly, the jump end time should match the start time of the event after it.

**Comment by grzesiek2010** [comment]
I think `jump` event was considered as just opening the `HierarchyView` so end time of what?  end time of opening? doesn't make sense. I know what you mean, you would like to have both times but then that event should be called `hierarchy_view` (opening and closing) for example.

For me, it's ok to leave it as it is but you decide :smile:

**Comment by lognaturel** [comment]
The hierarchy view is also referred to as the jump screen. https://docs.google.com/document/d/1LqVlVpePjA7Q1snjhA_ZQoDuzFqbtQcIygwcEzO_LJs/edit# listed the hierarchy event (later renamed to jump) as an interval event so I think the initial intent was to include both start and end.

The reason I think this is helpful is that it makes it easier to calculate how much total time was spent on the jump screen which can provide insights on how users navigate the form. Granted, one could use the start time of the event after it but it makes computations in a spreadsheet somewhat more complicated because then you can't just drag a formula down.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
