### ISSUE TITLE
When there's a validation error caused by a question in a field list, it's not clear which question has caused it

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2118]
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
When there's a validation error caused by a question in a field list, it's not clear which question has caused it

#### Steps to reproduce the problem
1. Open a form with multiple questions in a field list, at least one of which has a constraint or required condition (e.g. [field-list-constraint.xml.txt](https://github.com/opendatakit/collect/files/1900134/field-list-constraint.xml.txt))
1. Put in an answer that fails the constraint or omit a required question
1. Swipe forward, see a toast
1. Note that it's not clear which question has resulted in the toast

#### Expected behavior
It should be clear which question caused the problem. The screen should be scrolled to the problematic question and the question should be highlighted in some way (e.g. changing the background color). Ideally the question gets focus where appropriate (i.e. a question with edittext).

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
