### ISSUE TITLE
Refactor list views using Adapter Pattern

### ISSUE THREAD

**Issue by huangyz0918** [getodk/collect#2127]
#### Problem description
As @grzesiek2010 said in #2099 , It's better to refactor lists using **Adapter Pattern**. So thanks : )
> Xml Files ---> Adapter ---> Java Class

**It can:**
- Simplify our code and make it easier to read.
- Help us manage our list items.
- Remove the unnecessary `if-else` statements.
- Make code easier to patch fixes and changes.

**Which list may need this refactor?**
- [ ] Media Layout items: see `MediaLayout.java` --> `setAVT` method or others.
- [x] Jump/Hierarchy view items: see `HierarchyElementView.java` or others. (need discussion whether it needs a refactor or not)

#### Expected behavior
Code can be easier to read and modify with **Adapter Pattern**.

@opendatakit-bot label "refactor"
@grzesiek2010 I think PR #2123 and PR #2099 are **hot fix** pull requests focus on specific issues, if we need to refactor related lists, we can work on this issue after hot fixes were merged.

**Comment by grzesiek2010** [comment]
@huangyz0918 I refactored our HierarchyView to show what I meant it's here https://github.com/opendatakit/collect/pull/2128

**Comment by grzesiek2010** [comment]
When it comes to MediaLayout I'm not sure if it should be an adapter (since we don't use a list there) but the layout should be created using an xml file at least to avoid all those if statements.

**Comment by huangyz0918** [comment]
@grzesiek2010 Yes it really needs a refactor but I'm too busy recently (I have to prepare my English exam), so let's see if anyone can take a look and improve this.

**Comment by grzesiek2010** [comment]
Ok, I see no problem. I appreciate your help!

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot unclaim

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
