### ISSUE TITLE
Select All button is disabled when all forms were downloaded.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2131]
#### Software and hardware versions 
Collect v1.14.x, Android v4.1, 4.2, 4.4, 5.1, 6.0, 7.0 and 8.1 device used...

#### Problem description
Select All button is disabled when all forms were downloaded.

#### Steps to reproduce the problem
1. Go to Get Blank forms, Select all forms and download selected.
2. Go back to Get Blank forms. (I expected select all button will be enabled, screenshot attached)
![screenshot_20180417-145431](https://user-images.githubusercontent.com/33342488/38871202-72100be6-4250-11e8-91a3-428d40997eaf.png)
3. Select checkbox next to some of the forms. (Get selected button enables but select all is still disabled - clear button doesn't display at all, screenshot attached)
![screenshot_20180417-145421](https://user-images.githubusercontent.com/33342488/38871263-9f1a524a-4250-11e8-85b6-7c57f4738100.png)

#### Expected behavior
All forms should be selected when open Get Blank Forms and all buttons should be enabled. Select all/Clear all button should be enabled especially when you select some checkboxes manually.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
I agree with @grzesiek2010 ’s suggestion, we should not select all the forms by default. We should only select those have not been downloaded. @kkrawczyk123

**Comment by grzesiek2010** [comment]
> We should only select those have not been downloaded. 

To be clear: It works in that way you don't need to change anything here. the only problem is the button is disabled when all forms are downloaded.

**Comment by huangyz0918** [comment]
Got that, that will be much easier, sorry for inconvenience. @grzesiek2010 
I’ll update my PR as soon as possible.

**Comment by grzesiek2010** [comment]
> sorry for inconvenience

not an inconvenience at all
