### ISSUE TITLE
Collect 1.4.10 won't restart form after interrupted responding

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#214]
Sometimes responding to a form is interrupted because of low battery etc. When trying to restart the same form from the Collect menu, "Unsaved changes recovered from savepoint!" flashes briefly and the menu reappears.

This is fixed by manually deleting the instance folder, but this is too much to ask from some less technically savvy users, who are locked out of the form. Is there some shortcut?

I'm using Collect 1.4.10 in Android 5.1.1.

From sebastian.therman@gmail.com

**Comment by yanokwa** [comment]
A good first pass is to set up an emulator image, set the power in that emulator low to trigger the low battery message, and see if this can be reproduced.

**Comment by max2me** [comment]
@yanokwa I'm unable to reproduce this on my Android device (running Android 6.0). Lollipop emulator on my machine is incredibly slow so it is not much help either :(

I've looked through the code and dont see any obvious reasons for this issue to occur.

In the cases that I was able to encounter this message (by starting to fill out form > killing the app > then starting to fill out new form again), I was able to get out of that screen by pressing Back button several times.

**Comment by yanokwa** [comment]
@max2me I've asked the bug reporter for a stack trace to see if that helps. 

If Sebastian responds, it'd also be good to know exactly how to reproduce this. Is the problem at 10%, 5%, 1%? Does the phone turn off? Is it the dialog that pops up that is the problem? Does it seem to be phone specific? Form specific?

If we don't get a response in a week, then we can close this issue and focus instead of #241 which is another take on this problem.

As to the emulator, I find that installing HAXM (this might be Mac only) and using a Nexus 5 with x86_32 image works a lot better.

**Comment by max2me** [comment]
@yanokwa I have HAXM installed and running but I suspect fairly old CPU I have on dev machine does not have all virtualization capabilities. it's interesting that Android 4.x images run significantly smoother than 5.x when I tried it yesterday. Another unfortunate part is that new emulator that's being shipped with AS 2.0 doesnt support snapshots yet so one has to wait a long time for emulator to boot up.

**Comment by yanokwa** [comment]
We have not received any feedback from OP for about two weeks, so I'm closing this issue.
