### ISSUE TITLE
Buttons are disabled on GPS widgets with maps on Androids from 4.1 to 4.4.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2143]
#### Software and hardware versions 
Collect v1.14., Android v 4.1, 4.2 and 4.4

#### Problem description
Buttons are disabled on GPS widgets with maps:

- on the geopoint type with placement-map appearance and geopoint type with maps appearance: 2 upper buttons are disabled:
![screenshot_2018-04-19-15-21-45](https://user-images.githubusercontent.com/33342488/39043907-ebf909cc-448e-11e8-8452-1aeb1b2567cd.png)

- on the geotrace type with no appearance: 1st and 4th buttons are disabled:
![screenshot_2018-04-19-15-38-03](https://user-images.githubusercontent.com/33342488/39044139-97ef26da-448f-11e8-8001-fc9b74189981.png)

Buttons are enabled after location is loaded - on higher Androids versions they all look like enabled all the time and it would be good to unify them.

#### Steps to reproduce the problem
Open map view of widgets: 
- geopoint type with placement-map appearance
-  geopoint type with maps appearance
-  geotrace type with no appearance

#### Expected behavior
All buttons should be enabled and the user should be able to use them.

#### Other information 
I used regular All widgets.xml form

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

PS. I think we should not enable all the buttons, we should follow #2262 .

**Comment by lognaturel** [comment]
Agreed, @huangz0918 thank you!

**Comment by lognaturel** [comment]
Thank you, @huangyz0918!
