### ISSUE TITLE
random() repeating the same random number for each device

### ISSUE THREAD

**Issue by lbramley** [getodk/collect#2144]
I also raised this on the [ODK forum](https://forum.opendatakit.org/t/random-numbers-are-the-same-by-device/12776/2).

#### Software and hardware versions 
Collect 1.14.0, Samsung Galaxy S4 running Android 5.0.1 (amongst other devices)

#### Problem description
Including a once(random()) calculation seems to result in the random number being repeated verbatim for all surveys conducted by that device with that form.

#### Steps to reproduce the problem
Use XLSForm with a calculate field containing "once(random())" . See [this file](https://github.com/opendatakit/collect/files/1931692/randomTest_broken.xlsx).

#### Expected behavior
Each instance completed by the same device should have a different random number.

#### Other information 
At a guess it may have to do with how the seed is being set?

**Comment by lognaturel** [comment]
Thanks, @lbramley! I'm closing in favor of https://github.com/opendatakit/javarosa/issues/301 because this will need to be fixed in Javarosa, a library that Collect uses for form processing.

**Comment by lognaturel** [comment]
@lbramley My apologies, I was wrong about that. the problem was introduced by https://github.com/opendatakit/collect/pull/1829/files. I verified this by checking out the commit before and after.

**Comment by dcbriccetti** [comment]
I concur with your diagnosis, @lognaturel. Form values from the instance are being serialized and deserialized. I’d like to do some more investigation before we abandon the asynchronous caching feature. @srv-twry: FYI

**Comment by dcbriccetti** [comment]
I’m making the cache saving synchronous again.
