### ISSUE TITLE
OpenStreetMap reset on geo widgets when rotate screen.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2145]
#### Software and hardware versions 
Collect v1.14.x, Android v 4.1, 4.2, 4.4, 5.1, 6.0 and 7.0.x.x, device used...

#### Problem description
OpenStreetMap reset on geo widgets when rotate screen when it should just change an orientation to horizontal.
Gif of the issue:
[4-20-18-12-40-PM.mp4.zip](https://github.com/opendatakit/collect/files/1931907/4-20-18-12-40-PM.mp4.zip)

#### Steps to reproduce the problem
1. Choose OpenStreeMap as mapping sdk (General Settings/ User Interface/ Mapping)
2. Go to Geopoint widget (geopoint type with placement-map appearance/geopoint type with maps appearance/geotrace type with no appearance/geoshape type with no appearance)
3. Start loading loction
4. Zoom to current location
5. Rotate screen.

#### Expected behavior
Map shouldn't disappear it should just rotate - the same as when Google Maps is chosen as mapping sdk.

#### Other information 
- this issue doesn't occur on Android 8.1
- this issue concerns only geotrace type with no appearance and geoshape type with no appearance widgets on Android 6. 
- I used a regular All wigdets.xml form.

**Comment by lognaturel** [comment]
Closing in favor of #2310
