### ISSUE TITLE
Remove truncation in clear prompt dialog 

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2149]
#### Software and hardware versions 
Collect v1.10.x

#### Problem description
https://forum.opendatakit.org/t/odk-collect-bug/12619

We only show 50 characters of a question label when we create the clear dialog. My guess is that this change was made because there was no easy way to have the question text be truncated.

#### Steps to reproduce the problem
Build a form with a two labels. One that is 40 characters, one that is 60 characters. Try to clear the dialog on both and see the different behavior.

#### Expected behavior
I think the behavior is probably fine, but I figure I should file an issue so we can discuss removing it and changing the dialog so the text is scrollable.

**Comment by grzesiek2010** [comment]
I don't think it's worthwhile to change that. I would close this issue.

**Comment by grzesiek2010** [comment]
I said that I would close this issue and no one has been against so...

**Comment by yanokwa** [comment]
You didn't give me enough time to respond! 😂

I think this was added because with multiple questions on a screen, you might not know what you are removing, so this gives you some of that context. But it's odd that we just take any string even a right to left string and chop it at an arbitrary 50 characters.

I think this is somewhat worthwhile for a contributor to explore how to provide that context in a way that works with multiple languages (maybe a scrollable question text and the answer as well). Have I convinced you to reopen?

**Comment by grzesiek2010** [comment]
Ok, let's reopen.

**Comment by grzesiek2010** [comment]
Let's maybe decide whether we want to change anything here or just close the issue. Do you have any preferences @seadowg @lognaturel?

**Comment by seadowg** [comment]
Happy to close. We truncate in other places (like on the app bar), so I think there's precedent for it, and making the title scrollable is non-trivial (as far as I understand).
