### ISSUE TITLE
`Select All` button is changed to `Clear All` button when the user clicks on the Search icon

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2153]
#### Software and hardware versions 
Collect - master

#### Problem description
`Select All` button is changed to `Clear All` button when the user clicks on the Search icon

#### Steps to reproduce the problem
1. The user opens `Send Finalized Form` or `Delete Saved Form` view
2. `Select All` button is active
3. The user clicks on the search icon
4. `Select All` is changes to `Clear All' immediately

| | |
|---|---|
|![screenshot_20180424-170013](https://user-images.githubusercontent.com/3907554/39192507-d76f867e-47c8-11e8-9469-fb1d38d53b50.png)|![screenshot_20180424-170017](https://user-images.githubusercontent.com/3907554/39192516-dba77c74-47c8-11e8-8ec2-af86c0da49f7.png)
|![screenshot_20180424-170041](https://user-images.githubusercontent.com/3907554/39192571-fc0b222c-47c8-11e8-866d-faa40e0181ba.png)|![screenshot_20180424-170053](https://user-images.githubusercontent.com/3907554/39192584-01152574-47c9-11e8-9fb4-e93c36be21f5.png)|

#### Expected behavior
`Select All` button should be visible until all checkboxes are not selected

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Kindly go away Mr. Bot, a bunch of us have been taking a little time away from the computer so we can be refreshed so there's a little bit of a backlog. Just because you are a computer doesn't mean we are, @opendatakit-bot. 🤖
