### ISSUE TITLE
Show GPS as all caps

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#2156]
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
GPS shows as gps in the dialog that appears when a GPS fix is being acquired. Search the source for `location.getProvider()`. One of the values `getProvider` returns is `gps`. That value, and probably only that value, should be changed to `GPS` before being presented to the user.

#### Steps to reproduce the problem
Fill the All widgets form and select the GeoPoint Widget. Push Start GeoPoint. You should see this, eventually:

![screen shot 2018-04-25 at 12 03 03 pm](https://user-images.githubusercontent.com/55099/39267138-d0ac352c-4880-11e8-97fb-3bbfa0c506a5.png)

#### Expected behavior
“GPS”, being an initialism, should always appear capitalized to the user.

**Comment by KiaFarhang** [comment]
Hi there @dcbriccetti,

Hope you're doing well! I wanted to check before I claim this. I see three calls to `location.getProvider()` in the source code: in `GeoPointActivity`, `GeoPointMapActivity` and `GeoPointOsmMapActivity`.

All three seem to be creating a GPS accuracy message for the user. I'm new to Android but it looks like the `getProvider()` method is system-level, so we'd have to transform it to uppercase for our purposes like so:

```java
public String getProviderAccuracyMessage(@NonNull Location location) {
    return getString(R.string.location_provider_accuracy, location.getProvider().toUpperCase(), truncateDouble(location.getAccuracy()));
}
```

Fixing the capitalization noted in this issue would probably only require the change in `GeoPointActivity`, but would we prefer changing it in all three classes for the sake of consistency?

**Comment by dcbriccetti** [comment]
Hi Kia. We should translate to uppercase only those values that should appear capitalized. In this case, perhaps only "gps" -> "GPS". This translation only needs to happen where the value is presented to the user.

**Comment by KiaFarhang** [comment]
Thanks Dave. In that case, I think just switching from `location.getProvider()` to `location.getProvider().toUpperCase()` in those three class methods should do the trick without interfering with any other strings or values. I'll @opendatakit-bot claim this one and file a PR. Appreciate the help! -Kia

**Comment by dcbriccetti** [comment]
GPS needs to appear in all caps because it’s an initialism. Why would you make the others all caps? I suggest a data structure with the values of all providers that should be made all caps, or just something hardcoded:
`String provider = ... .equals("gps") ? "GPS" : ... .`

**Comment by KiaFarhang** [comment]
Ah, my mistake - so `getProvider()` doesn't always return `gps` if the location is sourced another way? Like I said, new to Android - appreciate your patience :)

In that case, is `getProvider()` guaranteed to return `gps` in the context of any of these classes? Or would it make more sense to use a ternary operator something like this?

```java
public String getProviderAccuracyMessage(@NonNull Location location) {
    return getString(R.string.location_provider_accuracy, location.getProvider().equals("gps") ? location.getProvider().toUpperCase() : location.getProvider(), truncateDouble(location.getAccuracy()));
}
```

**Comment by dcbriccetti** [comment]
It may return gps. So your code with the conditional operator is good. It would be nice if you could not duplicate it in the three files. That’ll be the hard part.

**Comment by KiaFarhang** [comment]
Thanks Dave. We could create a simple utility method sort of like this:

```java
public String standardizeGPSLocationProvider(String locationProvider){
    if(locationProvider.equals("gps")) {
        return "GPS";
    }     
    
    return locationProvider;
}
```

Then just pass the result of `location.getProvider()` through this method across the three files. If we take that approach, do you think this method makes sense in any of the current utility classes? I'd hate to create a new class just for this if we don't have to. However, taking a look at the utility classes available, I'm not sure it makes sense inside any of them.

**Comment by dcbriccetti** [comment]
That sounds good. You might put it in the common superclass of those three classes for now, and we’ll see if we get some other suggestions. Some people who might have an opinion and weigh in here: @shobhitagarwal1612 @grzesiek2010

**Comment by dcbriccetti** [comment]
I’d rather see the tighter
` return locationProvider.equals("gps") ? "GPS" : locationProvider;`
One line instead of five.

Thanks for working on this issue!

**Comment by KiaFarhang** [comment]
Sounds good Dave! Thanks for all your help. I'll plan on filing a PR with a new `CollectAbstractUtility` method to uppercase its string parameter if that parameter equals `"gps"` - and I'll do it with the one-line ternary approach. Have a great rest of your day!

**Comment by dcbriccetti** [comment]
I just had a thought. How about inserting an abstract parent, `LocationActivity` between the three classes and `CollectAbstractActivity`, and putting the method there?

**Comment by KiaFarhang** [comment]
Ah, so we keep the functionality constrained to just the classes that need
it? I like that, I can take that approach.

**Comment by KiaFarhang** [comment]
Hi @dcbriccetti , wanted to follow up before I file the PR. I know the contributors' guide recommends using string resources instead of string literals. I don't know if that would apply for an acronym like GPS. 

Do you think it's safer to add `"gps"` as a string resource and simply have the capitalization method call `toUpperCase()` as necessary, rather than hard coding the string `"gps"` into the capitalization method? Thanks in advance.

**Comment by dcbriccetti** [comment]
I suggest hard coding if the API doesn't translate gps into other languages.

> --

Sent from a hand computer

**Comment by KiaFarhang** [comment]
Thanks so much for all your help! Just filed the PR :)
