### ISSUE TITLE
Collect crashes when user changes device orientation during loading image to any of Image Widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2158]
#### Software and hardware versions 
Collect master

#### Problem description
App crashes when the user changes device orientation during loading image

#### Steps to reproduce the problem
1. The user starts a form with images
2. The user chooses some image
3. The user sees dialog `please wait a few moments.`
![screenshot_20180427-095359](https://user-images.githubusercontent.com/3907554/39351171-3637da8e-49f0-11e8-9001-e3e6132792a5.png)
4. User changes device orientation
5. App crashes

#### Expected behavior
* ODK Collect does not crash
* Image is loaded

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @mmarciniak90 ...It seems like collect is having a problem in uploading large size images.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Yes @opendatakit-bot, I'm working on it. I was just going to create a PR.
