### ISSUE TITLE
The user is not able to add audio and video from Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2159]
#### Software and hardware versions 
Collect master
Android 5.1, 6.0, 7.0, 8.0

#### Problem description
The user is not able to add audio and video from Google Drive

#### Steps to reproduce the problem
1. The user tries to add an audio file from Google Drive
2. The user tries to add video file from Google Drive
3. The user sees message and file is not attached

| | |
|---|---|
|![screenshot_20180427-101524](https://user-images.githubusercontent.com/3907554/39352279-bec29cd8-49f3-11e8-8ede-c29f7bbafe6c.png)|![screenshot_20180427-101752](https://user-images.githubusercontent.com/3907554/39352282-c30a38a0-49f3-11e8-9843-a5e065a8b418.png)|

#### Expected behavior
1. User is able to add audio and video file from Google Drive

**Comment by ShenJack** [comment]
@opendatakit-bot claim

**Comment by ShenJack** [comment]
I've reproduced, I'll try fixing them. @mmarciniak90 @lognaturel

**Comment by ShenJack** [comment]
@lognaturel  since this fix may need to show saving dialog during fetching audio/video from google drive, the previous version only have "saving_image_dialog" and "saving_dialog" to show, should there be more dialog such as "saving_audio_dialog", or just use "saving_dialog" instead ?

**Comment by lognaturel** [comment]
@ShenJack Nice to see you and thanks for taking this on! I think using the generic `saving_dialog` is a fine approach and it looks like that's what you've done in #2189. 🎉

**Comment by yanokwa** [comment]
This is also an issue on the file widget, but we should fix that in a separate PR.
