### ISSUE TITLE
Direct tile access has been discontinued when using Mapquest

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#216]
From piyushsh18@gmail.com

"My xlsform collecting geopoint and it also use "appearance=maps" in input tag but when I try to collect geopoint from devices when mapping SDK selected as Openstreet Map SDK and basemap as Mapquest Streets/ Satellite the it want load the Mapquest tiles in basemap and it says "As of july 11, 2016 direct tile access has been discontinued".

And when I select mapping SDK as Google Maps SDK and basemap as Streets/ Satellite/ terrain/ Hybrid and then try to collect geopoint from the form window it automatically disappear or crash and navigate me to ODK main page.

So kindly guide me how to configure or what setting has to be performed for using Geo widgets."

**Comment by yanokwa** [comment]
This is likely a problem with having Google Play Services installed.

From the thread:  "I facing Google Maps issue only in Xiaomi devices (I had tested on Redmi Note 3) but on other devices like Samsung Tablet it's working fine. So can you guide me how to solve the issue for above device. And I also check Google play services installed in Xiaomi device still the issue is persist."

**Comment by yanokwa** [comment]
I can confirm that Mapquest has disabled access to their tiles. We need to add replacements that do not require API keys. The ones I've found are:
- http://maps.stamen.com (standard terrain, labels)
- https://carto.com/location-data-services/basemaps (mapzen, positron, dark matter)

Mapnik, USGS_TOPO, USGS_SAT are also tile sources that should be available that we should try to add. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java has relevant code.

@jnordling Your input here would be great.

**Comment by max2me** [comment]
@yanokwa I've added [few more tile sources](https://github.com/opendatakit/collect/pull/246) and removed MapQuest.
