### ISSUE TITLE
Describe how best to support light and dark themes when adding UI components

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2165]
#2061 adds support for a dark theme. 🎉 

As new UI components are added, they need to use `colorControlNormal`, `primaryTextColor`, etc to make sure the look changes based on the the theme. Advice on how best to do that should be added to https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md. This should also be linked to from [the pull request template](https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

@shobhitagarwal1612, as the feature developer, I think you are best positioned to take a first pass when you get a chance! 😊

**Comment by shobhitagarwal1612** [comment]
Thanks @lognaturel 
Will definitely do it soon :smile:

**Comment by jd-alexander** [comment]
@shobhitagarwal1612 How does the buttons on the `MainScreenActivity` get their colour? I want to use that setup for a component but at first glance I haven't been able to figure it out.

**Comment by shobhitagarwal1612** [comment]
@jd-alexander the buttons are coloured implicitly. We don't need to mention the colour, it automatically picks from the current theme
