### ISSUE TITLE
ODK crashes after entering "1 Jan 1990/1994/1986/1987" in Peru time zone

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#217]
Source: https://groups.google.com/d/msg/opendatakit/3c2N3mrjk3g/VhL1nfQDBQAJ

"The 3rd of October I had a problem with a Date field in my survey. Every time it had the date "1 Jan 1990/1994/1986/1987" ODK Collect crashed. This also happend in 2 other cellphones with different Android Versions.

Trying to "fix" the problem I found in the error report that it had something to do with the Time Zone and the daylight savings time (Screenshots attached).

Indeed,  changing the Time Zone from "GMT-05:00 standard hour for Perú" to "GMT-05:00 standard hour for Bogotá" fixed the problem with this dates in my Galaxy S6 (haven't tried with the other cellphone or the ones deployed yet).

¿Does anyone else had this problem before? What seems weird is that now (after changing the Time Zone back to the Standard hour for Perú) I can't reproduce the problem again, it works fine, but I fear this could happen again.

The time zone for Perú appears when it's configured as "automatic". The closest to it is the Bogota Time Zone, but as far as i have tried, this error only occurs when it's with the Perú Time Zone (as said in my first post).

Searching for DST changes in Perú i found this: https://www.timeanddate.com/time/change/peru/lima
Indeed, the years it was changed 1 hour back are the sames ODK Collect crashes."

![screenshot_20161003-180714](https://cloud.githubusercontent.com/assets/32369/19937888/d810bc20-a11a-11e6-8761-5bd989c1cba5.png)
![screenshot_20161003-175000](https://cloud.githubusercontent.com/assets/32369/19937886/d80d3190-a11a-11e6-9162-534a3962279e.png)

**Comment by yanokwa** [comment]
I've tried Genymotion and Android's emulators, but still can't get the Peru time zone. Until that happens, it's unlikely this will get fixed. 

An upgrade to the latest jodatime, plus wrapping some of the date code is likely the best option.

**Comment by lognaturel** [comment]
Unifying with #356
