### ISSUE TITLE
Selected forms are automatically unselected when user clicks on search icon on `Send Finalized Form` view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2171]
#### Software and hardware versions 
Collect - master

#### Problem description
Selected forms are automatically unselected when the user clicks on the search icon on `Send Finalized Form` view

#### Steps to reproduce the problem
1. The user opens `Send Finalized Form`
2. The user clicks on `Select All` button (problem is not visible when the user selects checkboxes one by one)
3. The user clicks on the search icon
4. Checkboxes are unselected

#### Expected behavior
Previously selected forms are still selected even if the user clicks on the search icon

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
