### ISSUE TITLE
Show form version and form id when deleting blank forms

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2173]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Under Delete Saved Form > Blank Forms, the form list should also show the form version and form ID, similar to what Fill Blank Form and Get Blank Form does. To be precise, I expect the UI to look like...

>**Form title**
Version: 123456 ID: form-title

#### Steps to reproduce the problem
Download a form with a version (e.g., All Widgets from opendatakit.appspot.com)

#### Other information 

**delete blank forms**
![screen shot 2018-05-07 at 14 14 04](https://user-images.githubusercontent.com/32369/39725578-2738bd6e-5201-11e8-8965-5951257a9545.png)

**fill blank form**
![screen shot 2018-05-07 at 14 15 29](https://user-images.githubusercontent.com/32369/39725584-2d22adc0-5201-11e8-8df8-46d1526eb158.png)

**get blank form**
![screen shot 2018-05-07 at 14 17 19](https://user-images.githubusercontent.com/32369/39725649-6eb6e418-5201-11e8-8f78-81bb97e3e81c.png)

**Comment by surajdubey** [comment]
I'd love to work and submit PR on this @yanokwa

**Comment by yanokwa** [comment]
Awesome! Read https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md and there will be instructions on what to do to claim the issue.

**Comment by jaindiv26** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim --force

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim --force

**Comment by SaumiaSinghal** [comment]
Thanks @opendatakit-bot ..:)
I got the problem...I'll try working on it @yanokwa
