### ISSUE TITLE
Replace icons we use in DrawView with vectors

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2195]
#### Problem description
Replace icons we use in DarwView with vectors

Icons we should replace:
ic_clear_white
ic_save_white
ic_color_lens_white
ic_add_white

#### Steps to reproduce the problem
1. Open `All Widgets` form
2. Navigate to `Draw widget`

#### Expected behavior
All mentioned icons should be replaced with vectors. 

#### Other information 
![screenshot_2018-05-14-10-14-48](https://user-images.githubusercontent.com/3276264/39985867-3eb35bac-5760-11e8-9899-15bc56357925.png)

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by adhiljuvane** [comment]
Replaced icons in DrawView using vectors in #2226

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010 ...I would like to work on this issue.

**Comment by grzesiek2010** [comment]
Hi @SaumiaSinghal 

a pull request for this issue is almost ready #2226 I requested some changes and no answer for 8 days so let's wait a few days more and then we can close the current one and let you work on this.

**Comment by SaumiaSinghal** [comment]
Okay @grzesiek2010, Just let me know about it...Thanks :)

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010...Can i work on it now?

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
> Hie @grzesiek2010...Can i work on it now?

yes I think so.
