### ISSUE TITLE
The attachment icon is ArbitraryFileWidget is always black even in Dark theme

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2197]
#### Software and hardware versions 
Current master branch

#### Other information 
![screenshot_2018-05-14-10-32-06](https://user-images.githubusercontent.com/3276264/39986660-a57b5540-5762-11e8-8145-4dc37cdfba09.png)

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Closed in #2178
