### ISSUE TITLE
The user sees success information in notification even if an error occurs

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2200]
#### Software and hardware versions 
Collect with #2095

#### Problem description
The user sees success information in notification although error occurred
#### Steps to reproduce the problem
1. The user has selected `Automatic download` in Form Update settings
2. The new version of the form is available but internet connection error occurred during downloading
3. The user sees success information in the notification 
3. The user clicks on notification and sees view with header `Forms downloaded`

| Notification| Error | Error |
|---|---|---|
|![screenshot_20180514-124315](https://user-images.githubusercontent.com/3907554/39990388-fcaa5502-575b-11e8-8997-d25976aa60ba.png)|![screenshot_20180514-123721](https://user-images.githubusercontent.com/3907554/39990417-10a39802-575c-11e8-9cf4-7accd142a023.png)|![screenshot_20180514-124320](https://user-images.githubusercontent.com/3907554/39990424-13d8bc64-575c-11e8-84ff-198a4c6b6c7b.png)|

#### Expected behavior
* User sees different text in notification if an error occurs
* User sees different text in the header if an error occurs

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
