### ISSUE TITLE
Full message from the newest notification is visible even if the user clicks on the older notification

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2202]
#### Software and hardware versions 
Collect with #2095

#### Problem description
Full message from the newest notification is visible even if the user clicks on the older notification

#### Steps to reproduce the problem
1. Few types of notification are visible
![screenshot_20180514-103356](https://user-images.githubusercontent.com/3907554/39990793-0dfa1f08-575d-11e8-8a5f-52cd616a9495.png)
1a. Notification icons look different
2. The user clicks on the oldest notification
3. The user sees view with information about the newest
![notif](https://user-images.githubusercontent.com/3907554/39991062-d5043516-575d-11e8-8dae-a32d4bc4508d.gif)

#### Expected behavior
* Notification icons should look the same
* Each notification shows correct message

**Comment by ShenJack** [comment]
@opendatakit-bot claim

**Comment by ShenJack** [comment]
@opendatakit-bot unclaim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
