### ISSUE TITLE
Extra orientation changing is visible after back from drawing view on Android 8.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2211]
#### Software and hardware versions 
Collect v1.14.0
Android 8.1

#### Problem description
Extra orientation changing is visible after back from drawing view on Android 8.1

#### Steps to reproduce the problem
1. The user opens `Draw widget` or `Annotate widget` or `Signature widget`
2. The user is on `drawing view`
3. User backs to question
4. If the user uses a device on portrait position, the extra orientation changing is visible. If the user uses a device in horizontal position, it is hard to change position to portrait.

![draw](https://user-images.githubusercontent.com/3907554/40060230-ade33a98-5845-11e8-9ea3-376d248e02f3.gif)

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
Since it's an [android issue](https://issuetracker.google.com/issues/69168442) and it's nothing serious we can close and not to care.
