### ISSUE TITLE
Re-enable minify in build.gradle file

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#222]
Minify used to be enabled in [`build.gradle`](https://github.com/opendatakit/collect/blob/master/collect_app/build.gradle) but it fails when run by `./gradlew assembleRelease`. See errors [here](https://circleci.com/gh/lognaturel/collect/22).

Fix the ProGuard issues and re-enable minify.

**Comment by yanokwa** [comment]
Fixed!

**Comment by srsudar** [comment]
Did I break this with the gradle build file merge? If so, sorry about that.

**Comment by lognaturel** [comment]
@srsudar 😊 It's never about blame but regardless, it wasn't that! We had some challenges getting the CircleCI artifacts to get generated properly and the issue came out then.
