### ISSUE TITLE
Users are moved to form list instead of main menu after saving a form

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2229]
#### Software and hardware versions 
Current master branch

#### Problem description
My quick investigation told me it's caused by https://github.com/opendatakit/collect/pull/2119

I'm not sure but I guess it was implemented by accident.

#### Steps to reproduce the problem
1. Open and save any form
2. You are moved back to the form list

#### Expected behavior
We had been moving to the main menu before that change has been implemented.

@lognaturel @jd-alexander do you know anything about this change?

**Comment by jd-alexander** [comment]
@grzesiek2010  I am gonna have a look. Thanks for catching this!
