### ISSUE TITLE
Radio buttons aren't visible in dark mode with Android 4.4.2

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2230]
#### Software and hardware versions 
Collect v1.15.beta.0 Huawei Y336 with Android version 4.4.2.

#### Problem description
Radio buttons are black on a dark gray background.
![](https://opendatakit-a3b1.kxcdn.com/uploads/default/original/2X/0/0ffec18446a9c14292b5d338b9fbb93d03569823.png)

#### Steps to reproduce the problem
Go to a question with radio buttons.

#### Expected behavior
Radio buttons are white.

#### Other information 
Reported at https://forum.opendatakit.org/t/odk-collect-v1-15-beta/13086/27

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
