### ISSUE TITLE
Invalid question is not highlighted in red on the field list on Android 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2235]
#### Software and hardware versions 
Collect with #2184 
Android 4.1

#### Problem description
Invalid question is not highlighted in red on the field list 

#### Steps to reproduce the problem
1. The user fills a form with the field list with validation
2. The user puts invalid answers
3. The user tries to go next/finish form
4. The user is moved to the field list, sees toast but an invalid question is not highlighted on red

#### Expected behavior
Invalid question is highlighted on red

**Comment by SaumiaSinghal** [comment]
You are talking about the constraints that exist in forms like widgets and sample, Right @mmarciniak90?

**Comment by lognaturel** [comment]
That's right, @SaumiaSinghal. The all widgets form shouldn't have any constraints but the sample one does. If you go to the PR description for #2184, you'll see a form @grzesiek2010 to illustrate the change he made to make sure that when there are multiple questions on a screen, the one with a problem is highlighted. You should be able to see it in Android versions above 4.1 and not in 4.1.

**Comment by SaumiaSinghal** [comment]
Thanks for reference @lognaturel, I'd like to work on this issue!

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
I can't reproduce this on Android 4.1.2.

**Comment by huangyz0918** [comment]
I can't reproduce this on Android 4.1.2 too.

**Comment by grzesiek2010** [comment]
I think the issue is caused by disabled animations like https://github.com/opendatakit/collect/issues/3368 @kkrawczyk123 or @mmarciniak90 please confirm

**Comment by kkrawczyk123** [comment]
@grzesiek2010 Confirmed that animations were turned off on Android 4.1 device.
