### ISSUE TITLE
Incorrect icon in the header is sometimes visible - Android 5.1 - unknown steps to reproduce

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2240]
#### Software and hardware versions 
Collect - master
Android v5.1
Huawei Y5

#### Problem description

| Correct icon | ![screenshot_2018-06-02-14-32-44](https://user-images.githubusercontent.com/3907554/40483301-09007668-5f47-11e8-8136-512e3fbeae8a.png)| 
|---|---|

|Incorect icon| ![screenshot_2018-06-02-14-32-27](https://user-images.githubusercontent.com/3907554/40483322-1d8c3d7e-5f47-11e8-81bb-a5a561bd187c.png)|![screenshot_2018-06-02-14-31-56](https://user-images.githubusercontent.com/3907554/40483324-206f9b80-5f47-11e8-835f-dd7c83202e23.png)|
|---|---|---|

#### Steps to reproduce the problem
Unknown

#### Workaround
Close Collect and open it again

#### Other information 
The same icon is in main Android menu
![screenshot_2018-06-02-14-36-21](https://user-images.githubusercontent.com/3907554/40483346-31076676-5f47-11e8-80c1-610e493f4c9a.png)

**Comment by huangyz0918** [comment]
I think the shape of the icon is controlled by the system launcher (in some special ROMs), they use the same shape and icon appearance to unify the design. Like MIUI (XiaoMi), EMUI (Huawei) and happened in specific API levels. I don't know how to fix this, maybe it cannot be fixed since it was decided by the ROM version. @mmarciniak90

**Comment by lognaturel** [comment]
That sounds exactly right, @huangyz0918. I'm guessing there isn't really anything we can do about it and I think that's ok. It's the joy of Android customizability!

**Comment by lognaturel** [comment]
Almost certainly nothing we can do about this one so closing.
