### ISSUE TITLE
"This is an update to a form you have"  message disappears after canceling and refreshing connection to the server. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2243]
#### Software and hardware versions 
Collect v1.15.x, Android v4.4, 6.0 probably others too,

#### Problem description
"This is an update to a form you have"  message disappears after canceling and refreshing connection to the server. 

#### Steps to reproduce the problem
1. Click on Get Blank form - Forms to download displays, the green message "This is an update to a form you have" is present.
2. Go back to the main menu
3. Click on Get Blank form and Cancel Connection to the server
4. Click on the Refresh button
5. Form list displays correctly but the green message "This is an update to a form you have" is gone. 
 
#### Expected behavior
After refreshing Get Blank Form List initial state should be restored, nothing should be missing.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
