### ISSUE TITLE
Dark theme is not applied to the main menu when user load settings from collect.settings file

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2244]
#### Software and hardware versions 
Collect master

#### Problem description
Dark theme is not applied to the main menu when user load settings from collect.settings file

#### Steps to reproduce the problem
1. The user puts [collect.settings.txt](https://github.com/opendatakit/collect/files/2038789/collect.settings.txt) file to odk directory
2. The user opens Collect app
3. The user sees the main menu in light mode but other views in dark mode
4. Dark mode is applied to the main menu after reopening the app

#### Expected behavior
Dark mode to the main menu is applied immediately after loading a collect.settings file

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
