### ISSUE TITLE
The user is not able to add files from Google Drive to File widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2258]
#### Software and hardware versions 
Collect master
Android 5.1, 6.0, 7.0, 8.0

#### Problem description
The user is not able to add files from Google Drive to `File widget`

#### Steps to reproduce the problem
1. The user tries to add a file from Google Drive to `File widget`
2. The user sees a message in toast and file is not attached

#### Expected behavior
The user is able to add a file from Google Drive to `File widget`

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@SaumiaSinghal Thanks so much for your interest in this issue! I missed @ShenJack's comment at https://github.com/opendatakit/collect/pull/2189#issuecomment-392821948 -- since he's already fixed this in another place, let's let him take this one on.
