### ISSUE TITLE
Database migrations are not executed if app is not launched directly

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2259]
#### Software and hardware versions 
Collect versions that involve a database change

#### Problem description
When Collect isn't launched directly, database migrations may not be run.

#### Steps to reproduce the problem
I haven't yet reproduced it myself but this is the likely scenario.

1. Set autosend to true, turn off connectivity
1. Finalize a form
1. Update Collect but don't open it
1. Turn connectivity back on

This seems to result in the following crash ([Firebase console](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b04ea9b11e9fa0aa56833df?time=last-seven-days&sessionId=5B0DABC901BE00014412C514E74B529E_DNE_0_v2)):
```java
Caused by android.database.sqlite.SQLiteException
no such column: lastDetectedFormVersionHash (code 1)
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (SQLiteConnection.java)
arrow_drop_down
android.content.ContentResolver.query (ContentResolver.java:441)
arrow_right
org.odk.collect.android.dao.FormsDao.getFormsCursor (FormsDao.java:47)
org.odk.collect.android.dao.FormsDao.getFormsCursorForFormId (FormsDao.java:74)
org.odk.collect.android.receivers.NetworkReceiver.isFormAutoSendEnabled (NetworkReceiver.java:167)
org.odk.collect.android.receivers.NetworkReceiver.uploadForms (NetworkReceiver.java:107)
org.odk.collect.android.receivers.NetworkReceiver.onReceive (NetworkReceiver.java:61)
android.app.ActivityThread.handleReceiver (ActivityThread.java:2921)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)
```

#### Expected behavior
No crash.

#### Other information 
I think that in that case, ~`Collect`'s `onCreate` is not executed because the app has previously been loaded. See https://stackoverflow.com/a/7686586/137744 and the follow up comment.~ I think the `InstanceProvider` may still be in memory with stale content. This same issue may be happening when Collect is launched via an external intent right after an update.

**Comment by grzesiek2010** [comment]
`FormMetadataMigrator.migrate` has nothing to do with SQLiteException since it just deals with preferences not with the database.

I'm still not able to find out why every time we upgrade the database bunch of crashes occurs. I thought that maybe it's caused by an exception during upgrading but we collect such events so it would be visible in reports https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/helpers/FormsDatabaseHelper.java#L292

The only real case I can imagine is that people use forks of ODK Collect with higher database version and then if we try to upgrade our database it doesn't take place. Kind of crazy scenario but maybe this is it.

**Comment by jd-alexander** [comment]
@grzesiek2010 I just spent some time looking through the code you wrote to add the new column and everything looks fine; will investigate some more. In terms of the ODK fork idea would forks that are uploaded to the Play Store still be able to send crash events that ODK receives? How are the Crashlytics API keys provisioned?

**Comment by jd-alexander** [comment]
One possible fix would be to defer execution until the app is actually opened so there could be a database version check and or find some means by which migration runs before carrying out any database operations. Just some thoughts.

**Comment by jd-alexander** [comment]
Another idea. You can install the previous version of Collect without this database upgrade on an emulator and then you can drag the new version unto it. That's one way it could be reproduced.

**Comment by lognaturel** [comment]
Oops, yes, @grzesiek2010, I meant database migrations. So those are run by getWritableDatabase/getReadableDatabase, right? Are there cases where those aren’t run or might fail?

**Comment by grzesiek2010** [comment]
> In terms of the ODK fork idea would forks that are uploaded to the Play Store still be able to send crash events that ODK receives?

We have three build variants: debug, release, odkCollectRelease and only the last one collects crashes.

> Another idea. You can install the previous version of Collect without this database upgrade on an emulator and then you can drag the new version unto it. That's one way it could be reproduced.

Bro, I have tried many times :) and our QAs also test upgrading if we implement any changes.

> So those are run by getWritableDatabase/getReadableDatabase, right?

yes, upgrading is triggered if needed when you use your database so I can't see any case where it could be skipped.

> Are there cases where those aren’t run or might fail?

as I said I can't imagine such a case, I tried even cases like installing a new version without opening it and triggering database operation using NetworkReciver and it works well too so no idea.

**Comment by lognaturel** [comment]
Perhaps `InstanceProvider` (and therefore `SQLiteOpenHelper`) being already in memory could explain the state? @grzesiek2010 had you used the older version of Collect before doing the update?

I also wonder whether updating from the Play Store has a different effect than dragging and dropping the new version.

Regardless, given that 100s of crashes have been recorded by Crashlytics but we have not received crash reports on the forum, the crash is probably happening in the background and not affecting users, right? Perhaps we could/should catch it and log rather than letting the crash happen?

**Comment by grzesiek2010** [comment]
> had you used the older version of Collect before doing the update?

yes

> I also wonder whether updating from the Play Store has a different effect than dragging and dropping the new version.

it shouldn't be different.

> Regardless, given that 100s of crashes have been recorded by Crashlytics but we have not received crash reports on the forum, the crash is probably happening in the background and not affecting users, right? 

it's possible.

> Perhaps we could/should catch it and log rather than letting the crash happen?

I'm not sure if it's a good idea since it takes place in a few different places not only in `FormsDao` class but also in `FormsProvider`.
My another idea is that it might be an SQLite exception... what if [onUpgrade](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/helpers/FormsDatabaseHelper.java#L93) fails and it's not our fault. 

I opened this pr: https://github.com/opendatakit/collect/pull/2290 to collect logs in such a case so I think it's a good first step to check.

**Comment by jd-alexander** [comment]
Back to this. @grzesiek2010 would just checking if this column exists and if not then don't proceed within the `NetworkReceiver` thus stopping this exeception for now and we could just silently log it if anything.

**Comment by grzesiek2010** [comment]
> would just checking if this column exists and if not then don't proceed within the NetworkReceiver thus stopping this exeception for now and we could just silently log it if anything.

I'm not sure I would leave it as it is and check logs we will collect thanks to #2290 

Why I'm not sure?
1. It's not about only that particular `lastDetectedFormVersionHash`. It takes place every time we add new columns and sometimes I see similar reports about columns we added a long time ago.

2. It's the most common crash but no one complains so probably it doesn't crash the app it just doesn't allow to send forms automatically.

3. Catching the exception or just avoiding it by checking columns doesn't really change anything:
-auto send still doesn't work
-users don't know about it (like in the point 2)

I think we should find a cause or just do nothing. Catching exceptions, avoid them does that make any sense in this case?

**Comment by grzesiek2010** [comment]
The problem turned out to be with forks and has been fixed in https://github.com/opendatakit/collect/pull/3323 we will be even safer once we enable scoped storage and stop sharing databases with other apps.
