### ISSUE TITLE
Problem with visibility of inactive icons on Geo Widgets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2262]
#### Software and hardware versions 
Collect v1.15.0

#### Problem description
 Problem with visibility of inactive icons on Geo Widgets

#### Steps to reproduce the problem

**Use case 1: Google Maps**
1. The user opens Geo widgets
2. Inactive icons look like active on all Android version

**Use case 1: OpenStreetMap**
1. The user opens Geo widgets
2. Inactive icons look like active on Android 5.1, 6.0, 7.0, 8.1

|Android 5.1|![screenshot_2018-05-30-15-43-30](https://user-images.githubusercontent.com/3907554/40721010-d5bb94c0-6407-11e8-83d8-b5a2f6279dad.png)|![screenshot_2018-05-30-15-42-25](https://user-images.githubusercontent.com/3907554/40721011-d5d6fa58-6407-11e8-89b0-e97507a76e4a.png)|![screenshot_2018-05-30-15-22-56](https://user-images.githubusercontent.com/3907554/40721012-d5f47074-6407-11e8-96d1-1c777307b3ec.png)|
|---|---|---|---|
|Android 4.4|![screenshot_2018-05-30-15-43-20](https://user-images.githubusercontent.com/3907554/40721057-ee6d6d9a-6407-11e8-8768-baf99a778cae.png)|![screenshot_2018-05-30-15-42-21](https://user-images.githubusercontent.com/3907554/40721058-ee89c47c-6407-11e8-98bc-95b23bfa980c.png)|![screenshot_2018-05-30-15-23-06](https://user-images.githubusercontent.com/3907554/40721060-eea75190-6407-11e8-8838-d6d4ba5cdabe.png)|

#### Expected behavior
Icons look like active only when they are active

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim -force

**Comment by lognaturel** [comment]
I didn't see our bot was blocking things @SaumiaSinghal. You should now be able to claim it if you would like.

**Comment by huangyz0918** [comment]
I can make sure that this issue is the same with #2143 , and the description here is better than that since we cannot set all the buttons enabled if not prepared. 

@SaumiaSinghal If you don't mind, can I work on this ?

@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Thank you @lognaturel...No worries, I can work on other issues in the repository. Yes sure, @huangyz0918, go ahead...:)
