### ISSUE TITLE
None translatable string-array time_scale in GeoTrace

### ISSUE THREAD

**Issue by mkne** [getodk/collect#2264]
#### Software and hardware versions 
Collect v1.15.0, Android v4.4.2

#### Problem description
In the widget GeoTrace the fixed strings "Seconds" and "Minutes" are used. They come from the String-Array time_scale which is marked as not translatable. 

#### Steps to reproduce the problem
Fill in an empty "all-widgets" form and swipe (~42 times) until you get to the geotrace widget.
Click on the add marker button (+) and select automatic mode in the dialog Select GeoTrace mode.
Then you should see the dropdown box with secons or minutes.

#### Expected behavior
The strings Seconds and Minutes should be displayed in the selected language of the user.

**Comment by lognaturel** [comment]
Thank you for reporting, @mkne!

**Comment by rk635636** [comment]
@opendatakit-bot claim

**Comment by rk635636** [comment]
I am working on it. 
We have to add two keys one for Seconds and one for Minutes in strings.xml in all languages. And then we have to use reference of keys in arrays.xml
