### ISSUE TITLE
Changing device orientation affects the appearance in RTL languages on Android 8.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2265]
#### Software and hardware versions 
Collect v1.15.0
Android 8.1
RTL language
'Do not keep activities' turned OFF

#### Problem description
A part of views are returned to LTR appearance after change device orientation

#### Steps to reproduce the problem
1. The user uses RTL language

|![screenshot_20180605-161231](https://user-images.githubusercontent.com/3907554/40981777-55f5d1d8-68cb-11e8-9dff-b13589926fa8.png)|![screenshot_20180605-161221](https://user-images.githubusercontent.com/3907554/40981779-561b1902-68cb-11e8-9b05-2e814ffb150f.png)|![screenshot_20180605-161217](https://user-images.githubusercontent.com/3907554/40981780-563ef070-68cb-11e8-896d-0e4d2d41d912.png)|![screenshot_20180605-161336](https://user-images.githubusercontent.com/3907554/40981834-7774b388-68cb-11e8-83b9-d620e63633bd.png)|
|---|---|---|---|

2. The user changes device orientation
3. Views are moved to LTR appearance

|![screenshot_20180605-161239](https://user-images.githubusercontent.com/3907554/40981873-906a8a8e-68cb-11e8-8f22-073a4c22da1e.png)|![screenshot_20180605-161342](https://user-images.githubusercontent.com/3907554/40981870-9008cd44-68cb-11e8-9038-69c5ceddcdb6.png)|![screenshot_20180605-161317](https://user-images.githubusercontent.com/3907554/40981871-902c076e-68cb-11e8-9576-b742cfee151e.png)|![screenshot_20180605-161244](https://user-images.githubusercontent.com/3907554/40981872-904d88f8-68cb-11e8-8782-d8458a1fb67f.png)|
|---|---|---|---|

#### Expected behavior
Changing device orientation does not affect the appearance in RTL languages

**Comment by huangyz0918** [comment]
I guess this issue may be the same reason as #2211 . To address that, we may need to build a basic activity (`CollectAbstractActivity`) and override the `onResume()` and `onPause()` like #2212 .

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
