### ISSUE TITLE
Incorrect default value in range picker widget with picker appearance

### ISSUE THREAD

**Issue by rk635636** [getodk/collect#2266]
#### Software and hardware versions 
Collect v1.15.0, Android v7.1.1

#### Problem description
In the range integer widget with picker appearance there is a incorrect default value in picker dialog.
#### Steps to reproduce the problem
Fill in an empty "all-widgets" form and swipe until you get to the Range picker integer widget.
Click on the select value button. 
<p float="left">
<img src="https://user-images.githubusercontent.com/21003697/40991716-49721222-6912-11e8-9566-5fe27847edb3.png" width="200" height="400" /> 
</p>
Here the number picker dialog shows default value as 10, but if we click on OK button it gives selected value as 1.

#### Expected behavior

The default behaviour of number picker dialog should be like this
<br>
<img src="https://user-images.githubusercontent.com/21003697/40992112-76c388a4-6913-11e8-905b-cfe332b11846.png" width="200" height="400" />  
<br>

**Comment by grzesiek2010** [comment]
The bug is on Android's side
https://github.com/opendatakit/collect/issues/1782

**Comment by rk635636** [comment]
Ohk. I didn't know it was closed. Thanks though.

**Comment by lognaturel** [comment]
Good catch and thanks for reporting, @rk635636! Too bad there's not much we can do about it.
