### ISSUE TITLE
stepToOuterScreenEvent() invoked on null reference

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2270]
#### Software and hardware versions 
Collect v1.15, all Android versions

#### Problem description
Stack trace from Crashlytics ([link](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b0d4fa96007d59fcd4a967c?time=last-seven-days&sessionId=5B16CC710393000176FCE3336351F200_DNE_0_v2) requires credentials):

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int org.odk.collect.android.logic.FormController.stepToOuterScreenEvent()' on a null object reference
arrow_right
org.odk.collect.android.activities.ViewFormHierarchyActivity.onCreate (ViewFormHierarchyActivity.java:43)
android.app.Activity.performCreate (Activity.java:6675)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1119)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2732)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2844)
android.app.ActivityThread.-wrap12 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1572)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:203)
android.app.ActivityThread.main (ActivityThread.java:6361)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
```

#### Expected behavior
No crash.

#### Other information 
Marked as high priority because it has affected relatively many users.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by jd-alexander** [comment]
I have been trying to reproduce this but haven't been successful so far. The crash reports show that several of the devices that are crashing have more than sufficient RAM at the crash so that's probably not the issue.

**Comment by lognaturel** [comment]
Yes, I'm puzzled by this as well. There seem to be lots of cases where `formController` can be `null`, this one just happens to be one users hit a lot. Could it have to do with the app going out of memory due to inactivity or orientation change or something? I notice that in `FormEntryActivity.onResume` the form controller may not be set if the formloadertask is null or if its status is not finished.

**Comment by SaumiaSinghal** [comment]
Right now I'm trying to solve some other issue. @opendatakit-bot, I'll work on it afterwards.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by bartekfi** [comment]
@opendatakit-bot claim
