### ISSUE TITLE
Remove toast with a warning about spaces in underlying values for multi select widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2284]
#### Software and hardware versions 
Collect master

#### Problem description
Remove toast with a warning about spaces in underlying values for multi select widget

#### Steps to reproduce the problem
1. The user starts the form [multi-warning.xml.txt](https://github.com/opendatakit/collect/files/2089678/multi-warning.xml.txt)
2. The user adds an answer to the first question
3. The user sees toast with the warning
![screenshot_20180611-140030](https://user-images.githubusercontent.com/3907554/41228174-f6757d12-6d66-11e8-87d3-8c7783cd206c.png)

#### Expected behavior
Toast with the warning does not appear

#### Other information 
Related to #2251

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "good first issue"

**Comment by bartekfi** [comment]
@opendatakit-bot claim

**Comment by bartekfi** [comment]
I claim it as I have a solution ready here: https://github.com/bartoszfilipowicz/collect/commit/43359cf6eb320c50d579ad24caa0ee3c379407e2
I'll create PR after merger of https://github.com/opendatakit/collect/pull/2251 to avoid duplicated commits, as this commit is built on top of content of 2251.
