### ISSUE TITLE
Refactor code with lambda expressions 

### ISSUE THREAD

**Issue by huangyz0918** [getodk/collect#2294]
#### Problem description
Since we use java8 to build our project, I think we should refactor code with lambda for a code consistency.

#### Expected behavior
Replace all the listeners with lambda expressions.

@opendatakit-bot label "refactor"

**Comment by lognaturel** [comment]
How about we add something about lambdas to the contributor guide? I think the approach @jd-alexander mentioned at https://github.com/opendatakit/collect/pull/2293#discussion_r194951565 is a good one -- new code should use lambdas and as existing code is modified safe refactors with IDE support can be performed as a "clean up" step before starting work. That way we're always sure those changes go through QA.

**Comment by jd-alexander** [comment]
Sure! that sounds like a good idea! It could probably be one of the checklists in the PR template. Or should it just go to the general contributor guide? thats what you meant?

**Comment by lognaturel** [comment]
The general contributor guide feels like the right place for it.
