### ISSUE TITLE
Server settings path changes updated but not immediately shown. 

### ISSUE THREAD

**Issue by rik702** [getodk/collect#2303]
#### Software and hardware versions 
Collect v1.15.1, Android v7.1.1, emulator, but all..

#### Problem description
Minor issue...  When updating the "Form list path" and the "Submission path" in Server Settings for an "other" server, the changes are not immediately reflected on the Server Settings screen, but they are changed, as coming out of the Server Settings screen and going back in shows the updated settings.
#### Steps to reproduce the problem
Update either field in an "other" server in Server Settings.
#### Expected behavior
The changes are immediately shown on the screen (like for the other fields).

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
