### ISSUE TITLE
Handle location permissions

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2321]
#### Software and hardware versions 
Collect v1.15.1 and older versions.

#### Problem description
We need to handle location permissions to be able to increase `targetSdkVersion` what is a must.

Needed permisssions:
https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_FINE_LOCATION
https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_COARSE_LOCATION

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by vishnus1224** [comment]
@opendatakit-bot claim

**Comment by vishnus1224** [comment]
@opendatakit-bot claim --force

**Comment by grzesiek2010** [comment]
@vishnus1224 sorry but I finished work on it but I'm waiting for merging https://github.com/opendatakit/collect/pull/2358 first, the WIP pr is here #2320  I didn't notice the boot unassigned me :/

**Comment by vishnus1224** [comment]
@grzesiek2010 no worries :). I took it coz u were unassigned. I'll have a look at something else

**Comment by grzesiek2010** [comment]
>  I'll have a look at something else

sure, thanks!
