### ISSUE TITLE
Username not included in filled form (just after reading collect.settings? Just on older Android?)

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2326]
#### Software and hardware versions 
All Collect versions. Specifically reproduced on Android 4.4.2 after reading from `collect.settings`. See [forum thread](https://forum.opendatakit.org/t/username-not-appearing-on-the-submitted-records/10676/12?u=ln).

#### Problem description
The username "preload" is no always populated in filled forms. We have a systematic reproduction on Android 4.4.2 after reading from `collect.settings` and a potential report of it happening under different circumstances.

#### Steps to reproduce the problem
See [forum thread](https://forum.opendatakit.org/t/username-not-appearing-on-the-submitted-records/10676/12?u=ln).

#### Expected behavior
Changes to username read by `collect.settings` are immediate reflected in filled forms.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
