### ISSUE TITLE
When form language is RTL but Collect language is LTR, form text is not shown RTL

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2330]
#### Software and hardware versions 
Collect v1.15.0+

#### Problem description
https://forum.opendatakit.org/t/odk-collect-1-15-1-right-align-issue/13754

#### Steps to reproduce the problem
1. Add a form that has label or hint in a RTL language like Arabic or Urdu (e.g. https://data2.unhcr.org/en/documents/details/52583 -> [arabic.xml.txt](https://github.com/opendatakit/collect/files/2142489/arabic.xml.txt))

1. Open the form

#### Expected behavior
Text should appear RTL. See v1.14.0 for desired behavior.

**Comment by lognaturel** [comment]
@mmarciniak90 Please add a quick item to the testing checklist for a form with RTL text when Collect is set to a LTR language!

**Comment by mmarciniak90** [comment]
@lognaturel, case was added!

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
