### ISSUE TITLE
Be able to bundle initial forms with the application

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#234]
A non-trivial number of users would like to be able to bundle forms with the app. One reasonable way of doing this is a combination of auto-updating forms (#35), OTA bulk configuring (#232), and maybe white-labeled builds (#233). https://github.com/medic/medic-collect might be a useful place to start.

**Comment by lognaturel** [comment]
Will likely be addressed by bulk configuration. Further feature design will go on the forum.
