### ISSUE TITLE
Recording and saving an audio file causes a crash

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2342]
#### Software and hardware versions 
f0d5fa2 on sms_submission branch. Android 7.0 on Moto G5 Plus

#### Problem description
Recording and saving an audio file causes a crash

#### Steps to reproduce the problem
* Install the [Sony Audio Recorder](https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder)
* Download the All Widgets form and navigate to the Audio widget
* Record sound (and grant any necessary permissions)
* Save sound and press Done.
* Collect crashes

#### Other information 
```
06-29 13:41:41.508 27437 27437 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=Intent { dat=content://com.sonymobile.androidapp.audiorecorder.content/voice recordings/music recordings/Audio recording 2018-06-29 13-41-35.wav typ=audio/raw flg=0x1 }} to activity {org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4094)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at org.odk.collect.android.utilities.MediaUtils.getDataColumn(MediaUtils.java:648)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at org.odk.collect.android.activities.FormEntryActivity.onActivityResult(FormEntryActivity.java:765)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6931)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	... 9 more
06-29 13:41:41.512  2412  2448 W ActivityManager:   Force finishing activity org.odk.collect.android/.activities.FormEntryActivity
```

Perhaps related to #705, but the stack trace is different.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Sorry got caught up somewhere. I'll work on this after a few days.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by rk635636** [comment]
@opendatakit-bot claim

**Comment by rk635636** [comment]
I guess function `getColumnIndexOrThrow` is working properly only on devices before Android N. 
So first I copied the audio file and then used that one.

**Comment by lognaturel** [comment]
@rk635636 does seem to be right that it's not necessary to use the `_data` column from a uri to get a file path. #2430 has a lot of good ideas to work from. A PR to address this should provide context for the proposed changes and make sure there are no unrelated changes.

**Comment by lognaturel** [comment]
To provide a bit more context, the code path that is failing currently is in the branch of `MediaUtils.getPath` that handles content provider URIs. As @rk635636 found, in that case, pulling from the content resolver is better because it doesn't assume that the content provider uses the `_data` pattern (see [Stackoverflow comment](https://stackoverflow.com/questions/20067508/get-real-path-from-uri-android-kitkat-new-storage-access-framework/20559175#comment51352750_20559175)).

The change introduced in #2557 does fail for the media document path. A likely way to approach this would be to change the content provider branch to use the content resolver and leave `getDataColumn` alone. 

It would be worth reviewing the StackOverflow thread the `getPath` code comes from: https://stackoverflow.com/questions/20067508/get-real-path-from-uri-android-kitkat-new-storage-access-framework/20559175#20559175. Some people don't seem to think the code Collect uses is a good approach.
