### ISSUE TITLE
Google Sheets upload error dialog not descriptive enough 

### ISSUE THREAD

**Issue by jd-alexander** [getodk/collect#2349]
#### Software and hardware versions 
Collect v1.16.0beta, Android v7.0, Google Nexus 6

#### Problem description
When you are uploading a form via the Google Sheets integration and the link is missing an error dialog is shown about a missing sheet id. That error message is not clear enough since a direct reference to a sheet id isn't used during the configuration of the Google Sheets server type.

![screenshot-2018-07-02_11 32 50 835](https://user-images.githubusercontent.com/1509205/42244339-44ebcd28-7eda-11e8-9e39-ed9566a9530a.png)

#### Steps to reproduce the problem
Upload a form with the Google Sheets integration enabled and ensure that you have an empty submission fallback url.

#### Expected behavior
The error dialog should show a possible message such as "Missing submission url" since that's stating the value that can be added to the form or to the fallback settings inside the Google Sheets settings screen.

**Comment by jd-alexander** [comment]
@opendatakit-bot  "good first issue"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "good first issue"

**Comment by iraj21** [comment]
@opendatakit-bot  claim

**Comment by rashinkafernando** [comment]
@opendatakit-bot claim

**Comment by rashinkafernando** [comment]
@opendatakit-bot unclaim

**Comment by ajwad-shaikh** [comment]
@opendatakit-bot claim

**Comment by nshestiuk** [comment]
@opendatakit-bot claim
