### ISSUE TITLE
See a list of submitted files and the data you entered

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#235]
From a user "The forms stay on the phone but only the forms' titles can be reviewed and currently there is no capability of reviewing the entered values. Therefore, we want the field staff to have the ability of reviewing the entered values if possible."

This is functionality that is also important because it helps enumerators know that their submission has actually been sent.

**Comment by yanokwa** [comment]
Duplicate.

**Comment by lognaturel** [comment]
Closed by #417
