### ISSUE TITLE
Collect crashes when click on "Get Barcode" or "Scan code from other device"

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2353]
#### Software and hardware versions 
Collect v1.15..x, Android all device used...

#### Problem description
Collect is crashing when using Barcode widget and when try to import/export settings by the barcode.

#### Steps to reproduce the problem
1. Go to Import/export settings and click on "Scan code from other device"
2. Use All widgets form and Barcode widget.

#### Expected behavior
The user should be able to use the barcode widget and import/export settings.

#### Other information 
It is a regression and it's probably caused by changes from: https://github.com/opendatakit/collect/pull/2309

@opendatakit-bot label "regression"
@opendatakit-bot label "high priority"

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
