### ISSUE TITLE
Error about external data db not found even when it is on sdcard

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2357]
#### Software and hardware versions 
Samsung S9s using Android 8.0.0 and ODK Collect 1.50.0

#### Problem description
https://forum.opendatakit.org/t/error-using-pre-loaded-csv/13678

External CSV db file is sometimes not seen by `exists()` so users sees error message.

#### Steps to reproduce the problem
Not consistently reproducible.

#### Expected behavior
No error.

#### Other information 
@grzesiek2010 can you please link to the stack traces you're seeing? I don't see anything that's obviously related.

I would like to start by simply removing the `exists` call and adding `Timber` logging for other exceptions in the `External*` classes.

**Comment by grzesiek2010** [comment]
Here are reports
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b0d09c96007d59fcd44c27e?time=last-ninety-days&sessionId=5B4459D9035100012F51C557EDB25301_DNE_3_v2

**Comment by lognaturel** [comment]
@grzesiek2010 On the forum you wrote that you couldn't see reports from versions before 1.15.0. Is that maybe because you were only looking at Crashlytics and not at Firebase Crash? I see you mentioned the change but did you actually look at Firebase Crash Logs? I see:
- https://console.firebase.google.com/u/0/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/98bd7e7a?duration=2592000000
- https://console.firebase.google.com/u/0/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/f4561af9?reportTypes=NON_FATAL_JAVA&duration=2592000000

And there are more so that gets us for sure back to 1.4.15 (Feb 20, 2017) with relatively high frequency. Most likely some number of those are truly situations where users didn't attach the files but we currently can't tell the difference between those and the case where `exists` is returning the wrong thing.

I think we can be pretty confident it's not a regression but most likely something odd about the device state. I still think it would be helpful to remove the `exists` call and make sure other error states are logged (most probably are already). That will tell us if the file truly can't be opened.

**Comment by grzesiek2010** [comment]
> Is that maybe because you were only looking at Crashlytics and not at Firebase Crash?

I looked through both. Probably I missed them because the exception looks different in Crashlytics, sorry (I looked for `ExternalDataManagerImpl` but in Firebase it's `ExternalDataException - ExternalDataUtil.populateExternalChoices`)

Ok, I agree we can try what you proposed. I created a pull request https://github.com/opendatakit/collect/pull/2365

**Comment by lognaturel** [comment]
> because the exception looks different in Crashlytics

Hah, I think that's why I couldn't find it in Crashlytics originally. So we're even. 😉
