### ISSUE TITLE
Unable to play video recorded by selfie-video widget on Android 4.2  

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2364]
#### Software and hardware versions 
Collect v1.15.x, Android v4.2.x,

#### Problem description
Unable to play video recorded by selfie-video widget on Android 4.2  

#### Steps to reproduce the problem
1. Open selfie video widget on Android 4.2
2. Record a video
3. Click on Play Video button

#### Expected behavior
Video should be played using a default video player app or some other installed app - I tried VLC media player - which worked on other Androids.
I am able to play video recorded by regular video widget with using both app.

I used All widgets form.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Sorry, i got busy somewhere, but I'm working on it.
