### ISSUE TITLE
Randomize select options and track that ordering

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#237]
The ability to randomize comes up time and time and again. See https://groups.google.com/forum/#!searchin/opendatakit/randomization and https://groups.google.com/forum/#!searchin/opendatakit-developers/randomization. It'd be great to take this on.

**Comment by Bastiantheone** [comment]
@yanokwa I have a couple questions about this issue.
Do you want to have randomization for all four select widgets?
With "track that ordering", do you mean that I have to assure the picked answers and the recorded answers match, or that I need to keep a record of each ordering?

**Comment by yanokwa** [comment]
Hi @Bastiantheone! Yes, you'd randomize all select widgets. Track ordering means that for each randomization, you need to track how it was ordered and include that in the form somehow. This is important because researchers like to know if there are option-order effects.

https://github.com/kobotoolbox/enketo-express/issues/363 touched on some of these issues and an approach to do things work. Before taking on this feature in Collect, it'd be good to build consensus around that approach.

@MartijnR do you have ideas on how best to add this to Enketo and Collect? @lognaturel can we add to the XForms spec work?

**Comment by MartijnR** [comment]
There is this proposal: https://github.com/opendatakit/xforms-spec/issues/51, which is the way to go, in my opinion. 

I wonder if recording the option-order is important enough to 'have to' solve. Would be nice of course but I suspect that it's only a small percentage of randomization-lovers that need that.

**Comment by Bastiantheone** [comment]
My idea was to have an integer list of the same size as the items list. The values in the array correspond to the position. Then using the collections.shuffle function to randomize the order. If we decide to keep track of the ordering we can input the randomizer list into the form. It will show the index of each answer option.

![randomizeidea](https://cloud.githubusercontent.com/assets/23250770/23774994/714c8878-04f4-11e7-8f05-c43d2405eac1.png)

**Comment by dcbriccetti** [comment]
How about Collections.copy(randomizedItems, mItems), then shuffle. They’re just references, so you don’t need the complexity of the extra level of indirection for good performance.

Or, just shuffle mItems itself?

`for (i, j = 0 ...` where `i` is  not related to the looping process (as `j` is), is probably a code smell (though I couldn’t name it).

**Comment by Bastiantheone** [comment]
@dcbriccetti yes you're right. I came up with my approach because I wanted to have the option to track the ordering easily. Thinking about it more it is not hard to keep track of the order of shuffled mItems. A string where you keep adding the index would probably suffice.

**Comment by dcbriccetti** [comment]
If you just shuffled mItems itself could you avoid such tracking?

**Comment by Bastiantheone** [comment]
The tracking is being considered to make it possible analyzing if the order makes a difference in the answers

**Comment by dcbriccetti** [comment]
Oh, I get you. Thanks for your patience.

**Comment by yanokwa** [comment]
Another thing to think about is *where* in the stack to implement the logic. Since it's going to be an XPath function, I think the best place for this is probably in JavaRosa [JavaRosa](http://github.com/opendatakit/javarosa).

**Comment by lognaturel** [comment]
Implemented in https://github.com/opendatakit/javarosa/issues/273
