### ISSUE TITLE
Hide "Submission transport" server settings section from admin settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2374]
From https://forum.opendatakit.org/t/send-submissions-via-sms/12166/3:

"I would like the enumerator to have the option of selecting the transport option, but for this option to be hidden using the Admin settings if not required"

**Comment by jd-alexander** [comment]
This seems like something that would aid in ensuring more granular control of what the user is able to control in relation to the `Server` settings. Currently, the admin is able to disable access to the 'Server` setting altogether so adding this would make that a lot more customizable.

**Comment by lognaturel** [comment]
Current admin menu:
<img width="302" alt="screen shot 2018-07-17 at 1 38 33 pm" src="https://user-images.githubusercontent.com/967540/42844079-c0ce2c5a-89c6-11e8-8a14-1b7bd9cf4380.png">

The challenge is that "submission transport" is a subset of "server". The best strategy I can think of is to add a new select below "Server". If "Server" is unchecked, "Submission transport" is unchecked and disabled.

**Comment by jd-alexander** [comment]
> The challenge is that "submission transport" is a subset of "server". The best strategy I can think of is to add a new select below "Server". If "Server" is unchecked, "Submission transport is unchecked and disabled.

So by itself "Submission transport" can be toggled on and off and it's enabled state is tied to the "Server" value.

**Comment by lognaturel** [comment]
Yes, that's right. Additionally, I think probably it should become unchecked in addition to being disabled if Server is unchecked because it's just not possible to show "Submission transport" without "Server".
