### ISSUE TITLE
Use SMS delivery reports

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2375]
Currently, delivery reports are not used. We have discussed two uses for them:
- pulling out the header identifier that could be matched with an instanceID so submissions to SMS and HTTP can be aligned
- providing the user with certainty that their submissions have been delivered

@jd-alexander proposed providing delivery details in a bottom sheet in [this forum thread](https://forum.opendatakit.org/t/send-submissions-via-sms/12166/56)

I think that's a good idea. I think it would require implementing a separate db table to keep track of message status over time.

**Comment by jd-alexander** [comment]
Yes, this would also work in unison with the implementation of background sending which is being discussed here #2371

**Comment by grzesiek2010** [comment]
We can't send form via SMS because of the Google policy so we can close.
