### ISSUE TITLE
Address SQL injection vulnerability in older binaries

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2379]
The Play Store has flagged Collect as vulnerable to [SQL Injection](https://support.google.com/faqs/answer/7668308). @grzesiek2010 addressed this in #2281 for the current releases. Please note that this is not really dangerous for users in any way.

v1.13.2, v1.4.16, v1.4.10, v1.4.7, v1.4.5 are still active in the Play Store for users on older Android versions who can't upgrade and they still show the vulnerability. If these are not patched, they will be removed from the store.

Patching them will require checking out the appropriate tag (see https://github.com/opendatakit/collect/tags), creating a new branch from that tag and then applying the change. 

Note: v1.1.7 is currently still available but will be deprecated shortly because it has so few active users.

**Update status**
- [x] v1.13.3 - 2706
- [x] v1.4.17 - 1068
- [ ] 1.4.10.1 - 1062 - Conflict
- [ ] 1.4.7.1 - 1054
- [ ] 1.4.5.1 - 1049

**Comment by grzesiek2010** [comment]
@lognaturel 
as we agreed I started with the newest one v1.13.2 here is a fix for this version: https://github.com/grzesiek2010/collect/commit/9b930e6b618a4b8721394d6c7a90e7791c38417a

let me know if it's ok and I can go ahead.

**Comment by lognaturel** [comment]
It certainly looks great to me! @yanokwa do you think we should try to build this and push to the Play Store before taking on the other versions so we're sure it works?

**Comment by lognaturel** [comment]
We've discovered that the `versionCode` will need to be manually set because the commit count that currently sets it is always on `master` rather than on the current branch. https://github.com/opendatakit/collect/tree/v1.13.x has been updated with the contents of your branch @grzesiek2010 and that single update.

Now @yanokwa and I are trying to make sure it's safe to upload older APKs. https://developer.android.com/google/play/publishing/multiple-apks seems like a good resource.

**Comment by lognaturel** [comment]
1.13.3 is out. @grzesiek2010 what you did for it was great and the Play Store warning is indeed gone. The only addition will be to manually set the version code to one higher than the one in the original issue ⬆️. Thanks!

**Comment by grzesiek2010** [comment]
v1.4.17: https://github.com/grzesiek2010/collect/commit/662c47bbea1787aeef5df36f16e9a254a1578bd4

**Comment by grzesiek2010** [comment]
v1.4.11: https://github.com/grzesiek2010/collect/commit/7ae7ff2e6d1c34fdb3a424be499424102cb25a9c

**Comment by yanokwa** [comment]
v1.4.17 is on the Play Store. Let's keep going!

**Comment by grzesiek2010** [comment]
v1.4.11: https://github.com/grzesiek2010/collect/commit/62f7154b7055c6794a6242db4dd995ad70477631

**Comment by yanokwa** [comment]
@grzesiek2010, we've run into an issue where what you tagged v1.4.11 (should now be called v1.4.10.1) won't work because we don't have that version code available. We also don't have any other version codes that we can use.

While we try to figure out a way forward, can you please update 1.4.7.1 and 1.4.5.1, but in those commits, be sure to update the `versionName` in addition to the `versionCode`

**Comment by grzesiek2010** [comment]
v1.4.7.1 https://github.com/grzesiek2010/collect/commit/2d724f7776be31963abe6710f57d5d65d0c32743
v1.4.5.1 https://github.com/grzesiek2010/collect/commit/ac42b5eeebb0434b0cfaf97d7820df6254506d2e

**Comment by yanokwa** [comment]
I talked to some folks about Google about our issue with v1.4.1.4.10.110.1 and this is what they said...

> After the enforcement deadline you will no longer be able to submit a new apk that *contains* the security vulnerability. This is enforced across all apps that share the package name listed in the notice. These submissions will be blocked by the policy enforcement. 
> 
> Submissions that *do not* contain the security vulnerability will be allowed, regardless of the status of any other retained apks. This means that you will be free to submit updates to the apks that you have fixed, since any new apks you submit will not contain the security vulnerability. You will not be able to submit updates to the vulnerable apk that do not remove the vulnerability. In this case, you do not ever intend to update the currently vulnerable apk because there are no available version codes so there should be no problem.

What this means to me is that we should not worry about trying to ship 1.4.10.1, 1.4.7.1, and 1.4.5.1. We can leave them in the Play Store. My guess is that Google will eventually remove them.

**Comment by lognaturel** [comment]
That's a relief!

For completeness, the problem with 1.4.10.1 is that there are no version codes available, right? And with 1.4.7.1 and 1.4.5.1, I'm guessing they're hard to build because they're pre-Gradle?

**Comment by yanokwa** [comment]
Yes and yes. I think we can close this now...
