### ISSUE TITLE
Running performance tests on shared preferences

### ISSUE THREAD

**Issue by jd-alexander** [getodk/collect#2389]
#### Software and hardware versions 
Any Collect version. To test SMS submissions then any version after  Collect v1.16.0-beta.2 , Any Android device

#### Problem description
Collect makes heavy usage of `SharedPreferences` throughout the app. Most recently, `SharedPreferences` were used as a data store to back the submission state that needs to be persisted for SMS submission. This was done because the use of `SharedPreferences` allowed us to build out a quicker layer for persisting this state which would be temporary most times due to most of the finalized state being persisted to the `Instances` table and also the fact that the new `Submissions` database table that will track all transport types haven't been finalized. Nonetheless, we have to pay attention to the memory footprint of `SharedPreferences` because they are kept around in memory after the first call i.e if you make a call like this `PreferenceManager.getDefaultSharedPreferences()' then that behaviour is triggered. 

So, what we want to discover now is ho this impacst the performance of the app as `SharedPreferences` keys/values grow, especially since we have multiple preferences being utilized and held in memory.

#### Steps to reproduce the problem
Currently, we can't reproduce a performance issue because we haven't had one as yet. My thoughts on reproduction would involve simply creating a test environment where hundreds of SharedPreference records are inserted at a time and the memory usage of the app is monitored before and after this action. We can also look into monitoring the activity start times as well to see if any noticeable impacts are made there.

#### Expected behavior
The expected behaviour is that `SharedPreferences` won't cause any performance issues, nonetheless we have to put these tests in place because we should always be prepared in the event an enumerators uses the app outside of the use cases we might come up with eg. an enumerator that submits over a hundred SMS submissions at a time in an environment with spotty cell connectivity. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
This would be really good to do. I don't think it has to be formal tests -- setting up a protocol and trying it on a couple of devices with different stats would be sufficient.

**Comment by lognaturel** [comment]
Related: https://github.com/opendatakit/collect/issues/2410 is about at least providing a way to clear some of it out.

This stress testing is important to do soon. @jd-alexander if you have a set of steps and zip of submissions to try this with, we can then do it on various underpowered devices.

**Comment by jd-alexander** [comment]
Okay I am gonna start working on a way to do it.
