### ISSUE TITLE
SMS does not contain the defined content

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2391]
#### Software and hardware versions 
Collect v1.16.0 beta.4

#### Problem description
SMS does not contain the defined content

#### Steps to reproduce the problem
1. User starts the form `Send SMS or Email in Form`
2. User adds Participant name
3. User adds a phone number
4. User clicks on Launch to send SMS
5. SMS app is opened
6. SMS does not contain the defined content

|![screenshot_20180720-114556](https://user-images.githubusercontent.com/3907554/42995939-a8d8bd1c-8c01-11e8-9ea7-ec88fa7370b3.png)|![screenshot_20180720-114545](https://user-images.githubusercontent.com/3907554/42995930-a6fd3162-8c01-11e8-9860-774d97b5cbf9.png)|
|---|---|

#### Expected behavior
SMS contains the defined content

![screenshot_20180720-115441](https://user-images.githubusercontent.com/3907554/42996253-87343938-8c02-11e8-9237-077e027d5808.png)

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "high priority"

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@mmarciniak90 
The code is ok but the form you used is broken (not updated after recent changes). I don't have an original xls form so I just edited the xml one and you can use it:
[Send SMS or Email in Form.xml.txt](https://github.com/opendatakit/collect/files/2213748/Send.SMS.or.Email.in.Form.xml.txt)

@lognaturel please update the form and share the original xls file if you can.

**Comment by mmarciniak90** [comment]
Thanks, @grzesiek2010 for good news! 
It works on your form!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "high priority"
