### ISSUE TITLE
The checkbox on Send Finalized form list should not be selected when server authentication is canceled on form with specified submission URL. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2392]
#### Software and hardware versions 
Collect v1.16.0 beta 4, Android v 6.0, 4.4 probably other versions too.

#### Problem description
The checkbox on Send Finalized form list should not be selected when server authentication is canceled on form with specified submission URL. 

#### Steps to reproduce the problem
1. Use ODK Aggregate and form with specified submission URL
2. Send finalized form
3. On Server Required Authentication dialog, do not put credentials and click OK button.
4. When dialog show up again choose Cancel

#### Expected behavior
You should be moved to Send Finalized Form page and form should not be selected on the list - but currently, it is probably because of the new view of Send Finalized Form page.

#### Other information 
The issue occurs in both light and dark modes.
This feature was added in https://github.com/opendatakit/collect/pull/1783

@opendatakit-bot label "regression"
@opendatakit-bot label "good first issue"

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim
