### ISSUE TITLE
Options are not separated by lines in multi select question with appearance="autocomplete"

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2394]
#### Software and hardware versions 
Collect v1.14, 1.15, 1.16 (older version were not verified)

#### Problem description
Options are not separated by lines in multi-select question with appearance="autocomplete"

#### Steps to reproduce the problem
1. User starts a form with a multi-select question with appearance="autocomplete"
2. Options are not separated by lines

#### Expected behavior
* Options are separated by lines

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
