### ISSUE TITLE
Title of open source licenses screen is not human-friendly

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2397]
#### Software and hardware versions 
Since the open source licenses screen was introduced

#### Problem description
Title of open source licenses screen is not human-friendly.

#### Steps to reproduce the problem
1. In the overflow menu from the main screen, tap 'about'
1. Tap 'open source libraries / licenses'

See that the menu shows the file URI.

#### Expected behavior
Something friendly like "Open source licenses"

#### Other information 
I think this is likely as simple as setting the `title` tag.

**Comment by DreamyPhobic** [comment]
Can I work on this issue? At first look of the app, I also found it little odd. Thank You!

**Comment by shobhitagarwal1612** [comment]
Sure, please go ahead.
Just comment `@opendatakit-bot claim` to claim the issue

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by rashinkafernando** [comment]
@opendatakit-bot claim
