### ISSUE TITLE
Tint color in dark theme should be higher contrast

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2399]
See https://forum.opendatakit.org/t/dark-theme-radio-buttons-hard-to-see/13499

Android does seem to have a standard for some if its own screens that we should use: https://phandroid.com/2015/05/28/android-marshmallow-has-a-dark-theme-hidden-in-the-developer-options/ I'm not sure why this is not what the app compat dark theme uses (https://developer.android.com/guide/topics/ui/look-and-feel/themes). Ideally we can find that color defined somewhere in Android instead of having to use a color picker to define it.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@lognaturel 

I think using default accent colors is a good idea. We don't need to define those colors we just need to stop overriding them. Please take a look at my pr.
