### ISSUE TITLE
Add option to reset to app data

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#241]
Sometimes app data can get corrupt and you need to reset. Other times, orgs need to reset the app between deployments.

Add a dialog menu in admin settings to choose from a list of the things (settings, forms, submissions, metadata, databases, .cache, xml.bad, layers, etc) that can be reset.

**Comment by yanokwa** [comment]
Duplicate!

**Comment by max2me** [comment]
@lognaturel Should we also clear `osmandroid` cached tiles? They store them outside of our app folder so that is my only hesitation as to avoid accidentally messing other apps on the device (however unlikely that is).

**Comment by lognaturel** [comment]
@max2me Yes! That's a great one to add. They're in an odk folder so it would be very unlikely that an other app would use them.

**Comment by lognaturel** [comment]
No, I got that wrong, you're right, it's just in /osmdroid but I still think it's a good option to have. You can work on the wording to make it super clear - maybe something like "all OSM map tiles from phone"
