### ISSUE TITLE
Provide ways to clear out shared preferences representing SMS state

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2410]
Each time an attempt is made to send a filled form via SMS, a SharedPreference record is created for that filled form. These can get orphaned if the filled form is sent via Internet or the filled form is deleted.

At minimum, it should be possible to clear this with the admin settings > reset option. Ideally that state would also be cleaned up on filled form deletion.

**Comment by grzesiek2010** [comment]
We had to get rid of sending forms via sms feature so I'm closing this issue.
