### ISSUE TITLE
When sending is done via SMS, icons in Send Finalized Form are misleading

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2411]
#### Software and hardware versions 
Collect v1.16.0

#### Problem description
When sending is done via SMS, icons in Send Finalized Form are misleading

#### Steps to reproduce the problem
1. Load a form with SMS tags
1. Set the transport to SMS
1. Fill out the form
1. Send the filled form but let it fail in some way (e.g. no SIM), verify that a ! icon is shown
1. Go back to the main menu
1. Tap "Send Finalized Form"
1. See a pencil icon next to that failed submission

#### Expected behavior
The icon should indicate some kind of failure. I'm not exactly sure why it's not showing it. I would expect the shared preferences to still hold status information for this submission. Additionally, I would expect the database status to indicate failure.

**Comment by jd-alexander** [comment]
Okay! This shouldn't be happening so I am gonna double check soon!

**Comment by jd-alexander** [comment]
@opendatakit-bot claim
