### ISSUE TITLE
Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference 

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2418]
> org.odk.collect.android.activities.FormEntryActivity.getFileExtensionFromUri (FormEntryActivity.java:943)
org.odk.collect.android.activities.FormEntryActivity.saveChosenFile (FormEntryActivity.java:844)
org.odk.collect.android.activities.FormEntryActivity.access$400 (FormEntryActivity.java:152)
org.odk.collect.android.activities.FormEntryActivity$2.run (FormEntryActivity.java:792)
java.lang.Thread.run (Thread.java:818)

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b592d846007d59fcdc4d4e5?time=last-seven-days&sessionId=5B592BFD00DE00013786014FE7D2751F_DNE_0_v2

**Comment by poVoq** [comment]
Still getting this error sometimes on the latest playstore version of ODK with Kobotoolbox as the server back end
