### ISSUE TITLE
Human-friendly upload result message when the recived one is null.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2420]
#### Software and hardware versions 
Current master branch

#### Problem description
After fixing https://github.com/opendatakit/collect/pull/2414 if a server doesn't provide an uploading result message then
![screenshot_2018-07-26-14-06-04](https://user-images.githubusercontent.com/3276264/43261493-1dbfd1a8-90dd-11e8-92be-7a30d2a5f312.png)
 text `null` text is displayed.

I think it would be better to add something human-friendly like:
`No result message received` or something similar.

**Comment by grzesiek2010** [comment]
@lognaturel what do you think?

**Comment by lognaturel** [comment]
I think it’s better if users know there’s a problem and can report it. Like I said in the PR, it’s such an unusual case we shouldn’t spend any time on it. Adding a new string would mean a new set of translations.
