### ISSUE TITLE
Cannot Access Google Maps SDK on Xiaomi Redmi Note 3 Devices

### ISSUE THREAD

**Issue by piyush-shah** [getodk/collect#247]
### Software and hardware versions
_(ODK Collect V1.4.11, Android, device used Xiaomi Redmi Note 3)_

### Problem description
I am facing some issue in geopoint, geoshape and geotrace
Xlsform collecting geopoint, geoshape and geotrace with mapping SDK as Google Maps SDK and basemap as Streets/ Satellite/ terrain/ Hybrid and which includes "appearance=maps" in input tag raise error "Binary XML file line #24: Error inflating class fragment" on  Xiaomi Redmi Note 3 devices.

### Steps to reproduce the problem
Xlsform with geopoint, geoshape or geotrace and which includes "appearance=maps" in input tag.
And when I try to fill the Form on Xiaomi Redmi Note 3 devices, form window automatically disappear or crash and navigate me to ODK main page.

### Expected behavior
It Should open the map windows with Google basemap as Streets/ Satellite/ terrain/ Hybrid.

### Other information
[Error Log.txt](https://github.com/opendatakit/collect/files/585055/Error.Log.txt)
[Full Stack Trace.pdf](https://github.com/opendatakit/collect/files/585060/Full.Stack.Trace.pdf)

_(Things you tried, stack traces, related issues, suggestions on how to fix it...)_

**Comment by jnordling** [comment]
Hey @piyush-shah,

I will look into this. One question I have is, is this issue unique to the Xiaomi Redmi Note 3 Devices, or is this a bug in the widgets regarding the appearance tag. I have used the "appearance=maps" on the geopoint, but never for geoshape or geotrace. But Ill take a look.

Can you also share a sample form, if you have one.

**Comment by shobhitagarwal1612** [comment]
I couldn't reproduce this bug on Xiomi Redmi Note 4 (Android 7.0)

**Comment by lognaturel** [comment]
Thanks @shobhitagarwal1612 and sorry I missed your comment! Since there's no repro and no other report, I think we should close for now.
