### ISSUE TITLE
RTL language issues on Android 4.2.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2473]
#### Software and hardware versions 
Collect v1.16.x, Android v4.1, 4.2 device used...

#### Problem description
There is an issue with the display of reset select list in Androids 4.1 and 4.2 
Android 4.2:
![screenshot_2018-08-13-12-47-13](https://user-images.githubusercontent.com/33342488/44028180-5bd055a6-9ef9-11e8-9b9a-e1f4e2701e71.png)

On all other Android versions, the list is correctly aligned to the right side.

#### Steps to reproduce the problem
Open Admin settings and Reser application in RTL language. 

#### Expected behavior
The list should be aligned to right. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by kkrawczyk123** [comment]
I can see that there are more issues connected to Android 4.2 and RTL language like:
- choosing language for the form popup:
![screenshot_2018-08-13-13-34-00](https://user-images.githubusercontent.com/33342488/44034978-b0b79ce0-9f0e-11e8-8ba7-63215a55d4ee.png)
- not visible About section:
![screenshot_2018-08-13-13-37-52](https://user-images.githubusercontent.com/33342488/44035019-c96557aa-9f0e-11e8-898d-dc32e640d965.png)
- send finalizer form, get blank form and delete blank form lists:
![screenshot_2018-08-13-13-38-37](https://user-images.githubusercontent.com/33342488/44035076-ea773134-9f0e-11e8-971b-3b26ef959c7d.png)
![screenshot_2018-08-13-13-38-50](https://user-images.githubusercontent.com/33342488/44035077-eaa3b07e-9f0e-11e8-9523-c0e3371f7832.png)
![screenshot_2018-08-13-13-39-02](https://user-images.githubusercontent.com/33342488/44035078-eac23724-9f0e-11e8-8c67-6f3877a27015.png)

**Comment by kkrawczyk123** [comment]
When I set Collect's language as arabic and polish as a language of the form, an audio button is overlapping polish text, screenshot attached:
![screenshot_2018-08-13-11-03-21](https://user-images.githubusercontent.com/33342488/44084133-3a90b436-9fb6-11e8-9310-2e19459d9cb5.png)
In the opposite situation, when collect's language is polish and from language is arabic, everything seems to look just fine:
![screenshot_2018-08-13-11-02-36](https://user-images.githubusercontent.com/33342488/44084167-4e7eb4ac-9fb6-11e8-9e24-ea2360569612.png)

**Comment by kkrawczyk123** [comment]
When Collect's language is set as arabic and form's language is set as arabic too and Show guidance for questions is set as Yes - collapsed, guidance icon is centered somehow, screenshot attached:
![screenshot_2018-08-14-12-18-31](https://user-images.githubusercontent.com/33342488/44086660-8b4e9878-9fbd-11e8-9084-d6eaf31b91fb.png)

**Comment by grzesiek2010** [comment]
I investigate the mentioned issues on our another device with Android 4.2.2 and only the problem with overlapping audio/video buttons is visible. I guess there is something wrong with that particular device you have used @kkrawczyk123 it's [Infinix Race Bolt Q X451](https://bestmobs.co/infinix-race-bolt-q-x451/) - Android 4.2.1 it's a device we have had always many problems with, what @mmarciniak90 can confirm.

I'm going to ask our users to test it on their devices with Android 4.2. If everything is ok we can close this issue or just fix the problem with overlapping audio/video buttons.

**Comment by lognaturel** [comment]
Android <5 support will be dropped in v1.26 (https://github.com/opendatakit/collect/issues/3624).
