### ISSUE TITLE
Settings are displayed as RTL when you change language from arabic to english in the middle of filling the form on Androids 7.0 and 8.1

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2475]
#### Software and hardware versions 
Collect v1.16.x, Android v7.0 and 8.1

#### Problem description
Settings are displayed as RTL when you change language from arabic to english in the middle of filling the form on Androids 7.0 and 8.1

#### Steps to reproduce the problem
1. Set Collect's language as RTL language.
2. Star to fill a form.
3. In the middle of filling the form go to general settings and change the language to english/use device language.
4. Go back to the form that you were filling and continue
5. Open general settings once again.

the same happens with Admin Settings. 
#### Expected behavior
Settings should be aligned to the left side, not to the right. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by grzesiek2010** [comment]
This issue no longer exist, we can close.
