### ISSUE TITLE
Guidance icon is displayed in right when it should be on the left on Android 7.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2476]
#### Software and hardware versions 
Collect v1.x.x, Android v7 an 8.1. device used....

#### Problem description and reproduction steps:
As the old description wasn't detailed enough I am updating an issue. This is a gif of actions that I did, and the issue was reproducible for me each time I tried on Android 7 an 8.1. 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/33342488/46472556-e0eb0a80-c7dd-11e8-83f5-84fd841d36fd.gif)
1. In my first try, collect language is english, form language is arabic. Guidance icon is displayed properly on the left side.
2. In my second try I am changing collect's language from english to arabic. Guidance icon is displayed correctly on the right side.
3. In the third try I am changing collect's language from arabic to english back.
Settings are not even back to left side and when I open form guidance icon is still displayed on the right side. 
Recording app didn't let me to record killing app or screen rotation after which settings are back to left side and guidance icon as well. 

form that i used: 
[all_widgets.xml.txt](https://github.com/opendatakit/collect/files/2446233/all_widgets.xml.txt)
and the media folder: 
[all_widgets-media.zip](https://github.com/opendatakit/collect/files/2446236/all_widgets-media.zip)

#### Expected behavior
When change collect's language back to english, guidance icon should be displayed in thee left side.

#### Other information 
Issue is not reproducible on Androids from 4.1 to 6.0
issue connected with settings displayed in the wrong side has been reported separately in https://github.com/opendatakit/collect/issues/2475 but it would be good to fix them together

**Comment by grzesiek2010** [comment]
@kkrawczyk123 
I tried API 24/25 and everything looks ok to me. I think you made a mistake and the info button is on the right side because your global language is RTL also (not only the form language). I'm pretty sure it's the reason because all other elements like audio/video buttons, imageView are on the opposite side and even the toolbar is in RTL mode.

Could you confirm?

**Comment by kkrawczyk123** [comment]
@grzesiek2010 my mistake is that I described an issue in not enough steps to reproduce I will update it right now.

**Comment by grzesiek2010** [comment]
It's the same issue like the one described in https://github.com/opendatakit/collect/issues/2475 so I'm closing this.
