### ISSUE TITLE
Warning icon look depends on Submission transport settings

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2477]
#### Software and hardware versions 
Collect current master

#### Problem description
Warning icon look depends on Submission transport settings

#### Steps to reproduce the problem
1. The device does not have SIM card
2. User sets `Send submission via SMS`
3. The user opens `Send Finalized Form` page
4. The user sees warning icons

|![screenshot_20180814-131024](https://user-images.githubusercontent.com/3907554/44089202-6fa87eca-9fb5-11e8-93af-581b916c590d.png)|![screenshot_20180814-131041](https://user-images.githubusercontent.com/3907554/44089208-7510f7fc-9fb5-11e8-9695-50311ff80ed7.png)|
|---|---|

5. User set `Send submission via Select on send`
6. The user opens `Send Finalized Form` page
7. The user sees warning icons

|![screenshot_20180814-131049](https://user-images.githubusercontent.com/3907554/44089222-814ad768-9fb5-11e8-962d-002b820964b2.png)|![screenshot_20180814-131101](https://user-images.githubusercontent.com/3907554/44089225-839b775c-9fb5-11e8-885f-9527be690e9c.png)|
|---|---|

#### Expected behavior
* Warning icon looks always the same

**Comment by jd-alexander** [comment]
@opendatakit-bot claim

**Comment by jd-alexander** [comment]
I made the warning icons different so that it could be obvious when a SMS error had occurred. I am going to investigate what's causing this.
