### ISSUE TITLE
WebUtilsTest tests fail

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2485]
This is why the build is currently failing. 

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.opendatakit.httpclientandroidlib.Header.getValue()' on a null object reference
at org.odk.collect.android.utilities.WebUtils.getXmlDocument(WebUtils.java:328)
at org.odk.collect.android.utilities.WebUtilsTest.getXmlDocument_request_shouldNotSupplyHeader_Authorization_forHttpRequest(WebUtilsTest.java:72)
```

It appears to be introduced in #2466. I've confirmed the tests pass at 22365c5275b7f8083d675ac009ad4ce69c704b13 and then fail at 9eee16bedd0fdfda80f4c8a07340b682b782203c. The `catch` clause at line 422 was changed to only catch `IOException` so it doesn't handle the NPE anymore. @shobhitagarwal1612 do you happen to remember how you made this change? Was it IDE-recommended?

Note that there was a build failure after #2470 but it did not seem to be related.

**Comment by shobhitagarwal1612** [comment]
The failure is due to an NPE exception [here](https://github.com/opendatakit/collect/commit/9eee16bedd0fdfda80f4c8a07340b682b782203c#diff-a892fd7a3cad2cfb86f45a9051a2771aR328) as mentioned by @lognaturel and adding a null check fixed the issue. 

> It appears to be introduced in #2466. I've confirmed the tests pass at 22365c5 and then fail at 9eee16b. The catch clause at line 422 was changed to only catch IOException so it doesn't handle the NPE anymore. @shobhitagarwal1612 do you happen to remember how you made this change? Was it IDE-recommended?

No, the change wasn't suggested by IDE. It was the findbugs plugin which caught the issue and suggested to fix it by catching only the thrown exceptions. Actually, the point of making the change was this only. It was catching `Exception` even when it wasn't being thrown causing such unknown and unexpected behaviors.

**Comment by lognaturel** [comment]
Thanks, @shobhitagarwal1612! I'm asking about the IDE because it too can make suggestions for simplification in line with the various static analysis checkers. I suppose NPEs are never considered since they're runtime exceptions. I'm kind of surprised that the IDE didn't detect that `getContentType()` could return `null` but I think that is probably because `HttpEntity` is an interface type and so it doesn't know whether the implementation can return `null`.

We can keep this in mind for future refactors -- when changing from catching all `Exception`s to something more targeted (which is a GREAT change), there's always a risk that a runtime exception could have been caught this way and we should make sure to highlight it when listing potential risks.

In this specific case, @grzesiek2010, I would have recommended waiting on the merge because it makes https://github.com/opendatakit/collect/pull/2257 more risky. It's always a good idea to see what conflicts will be caused by a merge and decide whether the tradeoffs are worth it.
