### ISSUE TITLE
Server requires Authentication dialog not legible

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#249]
### Problem description
Server requires authentication dialog isn't legible.

### Steps to reproduce the problem
1. Set server to https://nafundi-demo.appspot.com
1. Get Blank Form
1. Server requires Authentication dialog appears with illegible username/password.

### Expected behavior
Username and password should be legible and conform to the Android style.
![dialog](https://cloud.githubusercontent.com/assets/32369/20262530/7d063e42-aa5a-11e6-90a8-2feded6be6ef.png)

**Comment by lognaturel** [comment]
Admin password screen has same problem.

**Comment by yanokwa** [comment]
Closed by #261
