### ISSUE TITLE
Geoshape: deleted polygon is visible after screen rotation

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2492]
#### Software and hardware versions 
Collect v1.16.x, Android v from 4.1 to 8.1. 

#### Problem description
After clearing and rotation of the screen, the deleted polygon is restored.

#### Steps to reproduce the problem
1. Open Geoshape widget.
2. Add a polygon.
3. Click on the clear button.
4. Rotate the device screen. 

#### Expected behavior
As polygon has been cleared it shouldn't be restored after screen rotation. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
I think this is related to #2310 -- there are several problems on device orientation changes.

I believe these will be addressed by @zestyping either in #2465 or a follow-on PR so I've labeled it as 'future release' so no one takes it on in isolation.
