### ISSUE TITLE
Long lists of choices take a long time to render

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2494]
#### Problem description
If the list of choices in a select one or select multiple question is long, it takes a long time to display that question because all `TextView`s are computed and held in memory. 

#### Steps to reproduce the problem
Load a form with a select question that has a long list of choices. These can come from a static choice list, a dynamic choice list or an external DB (using "search/pulldata" or "external itemsets").

#### Expected behavior
Views are only built for the currently-displayed items and a few before and after.

#### Other information 
As @shobhitagarwal1612 described in https://github.com/opendatakit/collect/issues/1254, this is probably a compelling place to use a `RecyclerView`.

**Comment by lognaturel** [comment]
Note: v1.16.3 accidentally included more commits than it intended to: https://github.com/opendatakit/collect/compare/v1.16.2...v1.16.3. One of the changes to list or textview rendering has caused a 3x slowdown on top of the usual slowness. It would probably be a good idea to start by identifying which of those commits caused the slowdown and resolving that so we're back to the same performance as in prior releases. Then we can work on improving from there.

**Comment by grzesiek2010** [comment]
This caused the problem https://github.com/opendatakit/collect/commit/f6087e3c5174bca3385af28ec545b5d6c2db055b

**Comment by lognaturel** [comment]
Ahh, good catch, @grzesiek2010. I'm not immediately seeing from the diff what the specific cause is. Seems all the same loops are there, the check on autoadvance was already there, etc. Have you been able to narrow it down more?

**Comment by grzesiek2010** [comment]
> I'm not immediately seeing from the diff what the specific cause is

because it's not directly caused by the commit I pointed out. The same slow performance is visibly on older versions if you use just `SelectOneWidget` (the form you shared with me contains `SelectOnceSearchWidget`). The commit I mentioned introduced refactoring to share the code and since f6087e3 `SelectOneWidget` and `SelectonceSearchWidget` use the same code (which works slowly). So the problem was visible even on older versions but not on `SelectonceSearchWidget`.

**Comment by lognaturel** [comment]
Select one widgets are now VERY fast thanks to @grzesiek2010 in #2513. 🎉 

I'm going to keep this issue open so we can fully close it when multi select widgets are similarly sped up. There are also some small bugs left to address that @mmarciniak90 described [here](https://github.com/opendatakit/collect/pull/2513#issuecomment-421320889).
