### ISSUE TITLE
Search() appearance/function should not show search interface unless search appearance is also specified

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2502]
There are two `search` appearances that Collect recognizes:
- `search` as an alias for `autocomplete` which shows a search box above select options
- `search()` appearance/function which pulls values from a CSV

Currently, Collect shows the search box above select options for both.

[different-search-appearances.zip](https://github.com/opendatakit/collect/files/2312395/different-search-appearances.zip) is a form that shows this issue for select ones. 

In that form, the first question ("Select from a CSV using search() appearance/function") should not show the search bar. However, it should be possible to combine the appearances. That is, the search bar should continue to show up for questions with label "Select from a CSV using search() appearance/function and search appearance" and "Select from a CSV using search() appearance/function and autocomplete appearance."

A simple approach might be to change `if (appearance.contains("search") || appearance.contains("autocomplete"))` in `WidgetFactory` to if (appearance.contains("search") && !appearance.contains("search(") || appearance.contains("autocomplete"))`

Please note that this is not a problem for select multiples because of #2501 which should be handled separately but using the same approach.

**Comment by yatri1609** [comment]
@lognaturel Can I work on this issue?

**Comment by lognaturel** [comment]
Sure, @yatri1609, that would be great! You can claim it by commenting with `@opendatakit-bot claim`. Be sure to check out [the contribution guide](https://github.com/opendatakit/collect#contributing-code) and if you have any questions, the #collect-code at http://slack.opendatakit.org/ is a great place to hang out!

**Comment by AOS002** [comment]
Hi!
Can I work on this issue? This is my first time contributing to an open source organization so I might need some help and time to fix this

**Comment by yatri1609** [comment]
@AOS002 I'm already working in this issue please find another one for yourself. Thanks !

**Comment by yanokwa** [comment]
@yatri1609, please claim the issue as described at https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by yatri1609** [comment]
@opendatakit-bot claim

**Comment by yatri1609** [comment]
I'm still working on it but I'm facing some difficulties in solving this

**Comment by lognaturel** [comment]
@yatri1609 it's no fun to struggle alone so consider putting up a work in progress PR with questions you may have, discussing your approach in this thread or asking questions in #collect-code in [the developer Slack](http://slack.opendatakit.org/)! I'm sure someone will be able to give you some good ideas to explore.

**Comment by yatri1609** [comment]
@opendatakit-bot unclaim
