### ISSUE TITLE
Forms change positions for a second while sending via SMS if `Sort by Date` is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2512]
#### Software and hardware versions 
Collect v1.16

#### Problem description
Forms change positions for a second while sending via SMS if `Sort by Date` is set

#### Steps to reproduce the problem
1. The user sets that submissions are sent via SMS
2. The user goes to `Send Finalized Form' and sees a list of finalized forms
3. The user changes sorting options to `Sort by Date`
4. The user clicks on `Select All` and sends them
5. The user sees that forms change positions for a second while sending

![sms](https://user-images.githubusercontent.com/3907554/44773613-49a4ee80-ab71-11e8-8fb2-43d5985b035e.gif)

#### Expected behavior
Forms does not change positions while sending

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by grzesiek2010** [comment]
We had to get rid of sending forms via sms feature so I'm closing this issue.
