### ISSUE TITLE
Log Google Analytics event when users toggles "Show sent and unsent forms" from "Send Finalized Form"

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2515]
Changes to how form filtering on the "Send Finalized Form" screen are being considered to, for example, better support SMS-based workflows (see https://forum.opendatakit.org/t/filter-submissions-sent-via-sms/14479/15). To inform that work, it would be helpful to know how often users change the filter on that view.

See [`WidgetFactory`](https://github.com/lognaturel/collect/blob/e14fb5368f38a6355c01b13ec12b0296f70ab361/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L320) for an example of logging an analytics event. The category should be "FilterSendForms" and the action should be "SentAndUnsent". In this case, no label is needed. 

The toggle happens in `InstanceUploaderList.showSentAndUnsentChoices`. We want to log the `showAll` case. Note that `logger` is not related to remote analytics.

**Comment by AOS002** [comment]
@opendatakit-bot claim

**Comment by AOS002** [comment]
Hi! @lognaturel
This is my first time contributing so I may need some help! I went through the code and I think I have some understanding of it now, please correct me if I am wrong. `InstanceUploaderList.showSentAndUnsentChoices` is the function that toggles the filter settings for the send finalized view and we want to log the show all `case`. I was thinking that I could either plug the analytics part in the show all `case` or make a function that contains the analytics part similar to the way its done in `WidgetFactory`.

Also how do I check if the event was logged or not?

**Comment by lognaturel** [comment]
> Also how do I check if the event was logged or not?

Good question. Someone with access to the analytics account is needed to check that the actual logging happens. I just did that and can confirm that it works as intended. 👍
