### ISSUE TITLE
Log Google Analytics event for protocol on server URL change

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2516]
[ODK Central](https://github.com/opendatakit/central) is designed to be secure out of the box. As options for supporting HTTP or not are being considered, it would be helpful to know what the ratio of HTTP to HTTPS servers used with Collect is.

Changes to the server URL go through `ServerPreferencesFragment.createChangeListener`. If the URL is valid, an analytics event should be logged with category "SetServer" and an action of either "HTTP" or "HTTPS" depending on the prefix of the URL (case insensitive).

Additionally, we would like to know what servers are the same without compromising user privacy. To do this, we can log a hash of the full URL. See [`WidgetFactory`](https://github.com/lognaturel/collect/blob/e14fb5368f38a6355c01b13ec12b0296f70ab361/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L302) for a similar example.

**Comment by nexusbr-geoengenharia** [comment]
@opendatakit-bot claim
