### ISSUE TITLE
Log Google analytics event on question that uses external app

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2517]
Collect forms can launch external applications to collect information from sensors, for example. See [documentation](https://docs.opendatakit.org/launch-apps-from-collect/).

As we consider enhancements or changes to this feature, it would be helpful to know how commonly it is used.

We'd like to know when an external app returning a value of any type is called. This means we can log the analytics event in the `ExStringWidget` constructor. `ExDecimalWidget` and `ExIntegerWidget` will also be logged this way because they are subclasses.

See [`WidgetFactory`](https://github.com/lognaturel/collect/blob/e14fb5368f38a6355c01b13ec12b0296f70ab361/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L320) for an example of logging an analytics event. The category should be "WidgetType" and the action should be "ExternalApp". In this case, no label is needed.

**Comment by cleoGson** [comment]
@opendatakit-bot claim
