### ISSUE TITLE
Bugs related to audio files

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2521]
#### Software and hardware versions 
Collect v1.16.4 and older versions

#### Problem description
Playing with audio files I discovered a few bugs I'll try to describe.

**BUG 1:**
If you have a select_one (or select_multiple) question and each item has an audio file you have to click two times to start an audio if another item is playing.

Expected behavior:
A new audio file should start immediately and if another one is playing that another one should be stopped.

**BUG 2:**
If we have AudioWidget and that widget contains audioButton it doesn't work at all and very strange things happen that are even difficult to describe. For example, if you click on audioButton and then you want to play a recorded sound the recorder plays a file that comes from the audioButton.

**BUG 3:**
If we have a field-list with a few questions it's possible to play many audios at the same time.

Here is a form which allows reproducing all mentioned issues: 
[MediaForm.zip](https://github.com/opendatakit/collect/files/2428602/MediaForm.zip)

**Comment by lognaturel** [comment]
Please see discussion starting at https://github.com/opendatakit/collect/pull/2532#issuecomment-428005875 before taking this one on. @grzesiek2010 had a good solution using `RxEventBus` but it should be possible to leverage the existing relationship between the components involved to address the problem without it.

**Comment by lognaturel** [comment]
Oops, I thought there was a stale assignment but it looks like you'd like to keep exploring this one, right @grzesiek2010? Perhaps you could share some ideas on the direction you expect to go in so there can be discussion around that.

**Comment by seadowg** [comment]
@grzesiek2010 @lognaturel am I right in thinking that "grid multi selects" (selects with compact appearance) don't support audio? As far as I can see they don't render audio buttons and don't play audio when selected/clicked. Just trying to work out if this is also a bug/regression or not.

Screenshot of the widgets I'm talking about from @grzesiek2010's example (at the bottom):

![Screenshot_1565021797](https://user-images.githubusercontent.com/556280/62479311-14534880-b7a5-11e9-9316-ca94c93b3778.png)

**Comment by grzesiek2010** [comment]
The compact should be compact so shouldn't display any buttons (audio or video).  I remember that playing audio worked in that case and an audio file was started just after selecting an item but it was a long time ago and then we implemented some improvements in that area (all select questions) deciding not to support it because it was a tricky case.

So I wouldn't say it's regression no one complains.
