### ISSUE TITLE
Test the API 23 and 24 features

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2526]
#### Problem description
Issue created to verify Android features implemented in Android 6.0 and 7.0.
The issue is aimed to check if any action on the ODK Collect side is needed.

**Comment by mmarciniak90** [comment]
@opendatakit-bot claim

**Comment by mmarciniak90** [comment]
@opendatakit-bot claim --force

**Comment by mmarciniak90** [comment]
Tested API 24 features:

https://www.android.com/versions/nougat-7-0/features/

* Screen zoom

|![screenshot_20180912-171611](https://user-images.githubusercontent.com/3907554/45431229-84497380-b6a7-11e8-9fd9-21d798610134.png)|![screenshot_20180912-171619](https://user-images.githubusercontent.com/3907554/45431232-86133700-b6a7-11e8-9c64-41eac68a6872.png)|
|---|---|
|![screenshot_20180912-171634](https://user-images.githubusercontent.com/3907554/45431236-890e2780-b6a7-11e8-92bc-03fe56af87e9.png)|![screenshot_20180912-171647](https://user-images.githubusercontent.com/3907554/45431243-8c091800-b6a7-11e8-8bda-4b65a42f82eb.png)|

* Split-screen mode

|![screenshot_20180912-171819](https://user-images.githubusercontent.com/3907554/45431314-b2c74e80-b6a7-11e8-972c-404ed7c71c49.png)|![screenshot_20180912-171830](https://user-images.githubusercontent.com/3907554/45431315-b4911200-b6a7-11e8-8be5-75df297ab036.png)|
|---|---|

* High performance mode
* Easy mode
* Displaying apps icons without frames
* Fonts
* Data Saver
* Quick switch

**Comment by mmarciniak90** [comment]
Tested API 23 features:
https://www.android.com/versions/marshmallow-6-0/features/

* Advanced controls to turn permissions on or off for installed apps
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/45554476-d5d43880-b836-11e8-89d1-000c44230176.png">

* Block Notification
* Treat as priority notifications from ODK Collect
* Battery optimisation
* Auto backup
* App search bar and favorites
* Google Assistant

**Comment by lognaturel** [comment]
One that I believe will break in API 23 is [adoptable storage](https://www.androidcentral.com/adoptable-storage). More about the dev details [here](https://developer.android.com/about/versions/marshmallow/android-6.0#adoptable-storage). I don't think it's a huge deal but might be good to check (if someone has a device that this can even be done with) and file an issue. Low priority because it doesn't seem all that useful.

**Comment by grzesiek2010** [comment]
I think it's time to close this issue.
