### ISSUE TITLE
ODK Collect 1.16.4 on Lenovo Tab 3 7": Geolocation can't find satellites

### ISSUE THREAD

**Issue by florianm** [getodk/collect#2527]
Problem: can't get a Geolocation when GPS satellites are hidden by a building but WiFi is available.

#### Software and hardware versions 
Collect v1.16.4, Android v5.0.1, Lenovo Tab 3 7" TB3-710F, outdoors with good view of sky (70% open, one story building on one side)

Cross-testing on other devices:

* Same lenovo model, different device got a fix fine (outdoors). This device gets no reception indoors.
* Samsung S2 Galaxy 10", Android 7, ODK-C 1.16.4: no GPS fix indoors (within WiFi - I expect an approximate fix from network). Walking outdoors with ODK form's Geolocation widget running (and finding 0/24 satellites), no fix. Outdoors, cancel Geolocation widget, keep form open, hit Geolocation again: GPS fix to below 5m accuracy from several satellites (~10ish) within < 10 sec. Yay!
* Same troubled lenovos, outdoors, 20m away from building, repeated attempts, suddenly getting a GPS fix after about 2-3 mins searching for satellites. Subsequent GPS fixes within < 10 sec.
* Same lenovos again close to building, 50% sky visible (South facing towards Antarctic, we're in Karratha on the northern coast of Western Australia - are there no GPS satellites over the Antarctic?): still getting a GPS fix, but slower (~30s)
* Same lenovos, indoors again - no fix.
* Motorola G4+ phone, same form, Android 6, indoors: no fix. Outdoors: instant fix.

#### Problem description
Android and all apps are up to date. Turned location services as well as device off and on again.
Cannot capture Geolocation in any ODK form (worked before on same devices) indoors within WiFi but with potentially bad GPS satellite coverage.

Problem could be my location / GPS satellite visibility (I'm testing outdoors).

Has anyone else got trouble getting a GPS fix sometimes?

#### Steps to reproduce the problem
Example of a form not working:
[Site_Visit_Start_0_3.xml.zip](https://github.com/opendatakit/collect/files/2374002/Site_Visit_Start_0_3.xml.zip)

* Form working outdoors proves it's not the form.
* ODK Collect 1.16.4 working outdoors proves it's not ODK-C - but a network fix would be nice!
* Maybe the building blocks out GPS satellites even if standing close to it outdoors?

#### Expected behavior
* GPS fix within 10 seconds (as ODK-C did before in same devices).
* GPS fix should come from network if satellites are unavailable. I remember this was the case in earlier ODK-Collect versions - has anything changed to "satellite only location" from the ODK-C end?

Reliability issues like this (especially when hitting on a demo day to the big wigs) can make or break a whole organisation's move towards ODK / digital data collection.

**Comment by lognaturel** [comment]
You should not generally expect to get a location indoors. It may be possible sometimes if the device reports a recently-acquired location or does recognize Wifi access points but those are not guaranteed.

That said there was also a change that could potentially have resulted in a behavior change. As of Feb 15, the Android fused location provider stopped reporting accuracies better than 10m: https://stackoverflow.com/questions/49289206/why-does-fusedlocationproviderapi-never-report-accuracy-better-than-10m-is-this. That API tried to use different sources for location. At that point, we had to revert to older APIs. There is still no explanation for this behavior change and no one we have talked to at Google has known what happened.

What happens if you turn GPS off entirely but leave Wifi on? That should force a fallback to Wifi but I don't think there's a great way for us to make that happen automatically.

**Comment by florianm** [comment]
Hi @lognaturel, here's a quick wrap-up from our field testing.

Thanks for the info re fused location provider - indeed this seems to have had a nengative impact. I remember getting a "location via network" back in the days when testing from the indoors. Unfortunately those fateful, make-or-break demos to top brass tend to be indoors with limited or no GPS signal.

Turning off location provider in the device and trying to capture an ODK collect geopoint is met with a "location provider is disabled" warning and the location system setting opening, so that's no good for testing indoors either.

We finally managed to resolve the "no GPS fix" problem by standing outdoors, about 20m away from our "GPS-proof" building. Between the five Lenovo Tab3 devices tested, one required a system reboot, the others took half a minute for their first GPS fix, and 3-6 seconds for subsequent fixes. Testing on remote beaches (no WiFi, clear view of sky), again one tablet required a reboot, the others were slow again to start with, then got fast GPS fixes.

The reproducible problem is:

* Attempting to capture an ODK-Collect Geopoint indoors with zero GPS signal: widget spins for minutes, nothing happens
* Walking outdoors with widget spinning: nothing happens
* Outdoors, cancelling widget, trying again: most devices will get a fix within half a minute (slower than expected), then a quick fix in subsequent attempts (good)
* Some devices (same hardware, same OS version, same app version) get so hung up that they require a reboot

I'm closing this issue as there's nothing ODK-C can do until the underlying location API changes again.
Thanks for your advice!

**Comment by lognaturel** [comment]
The long time to get a fix after being out of satellite view is expected. I think some chipsets do somewhat better with a cold start than others but in general connecting to enough satellites after none were in sight does take a while.

You should have control over which providers you turn on and off. Unfortunately it's not consistent between Android versions but for me I go to Settings > Privacy > Locating method and then I can change it to "Wi-Fi and mobile networks".

![screen](https://user-images.githubusercontent.com/967540/45642261-92630f80-ba6c-11e8-9ab5-020f8233699e.png)

That does allow me to get a point indoors.

**Comment by florianm** [comment]
Ah, found it. On Android 6 it's called "location accuracy" - "high accuracy" includes WiFi. The devices in question were all set to that, and within WiFi but out of GPS didn't seem to get a location.

**Comment by lognaturel** [comment]
> within WiFi but out of GPS didn't seem to get a location.

I believe you'll have to turn off the GPS for WiFi to be used.

**Comment by florianm** [comment]
That again will open the location system settings when using the ODK Collect GeoPoint widget. 
Unless that behaviour is something ODK-C could change, I assume it comes from the underlying Android API as you indicated in your earlier answer. 
Overall I'm happy with ODK-C working great outdoors, where all of our real world data collection happens.

**Comment by lognaturel** [comment]
Oh, how interesting and irritating! My Android version lets me selectively just turn off GPS and leave the WiFi provider on but I can believe that not all version do this.

> I'm happy with ODK-C working great outdoors, where all of our real world data collection happens.

👍 👍 Agreed that's the important part!

**Comment by florianm** [comment]
Update:
Samsung Galaxy S2 which always found good GPS signal, ODK Collect 1.21.2: no satellites found in over 1 minute, outdoors. Normal fix was auto-save with accuracy < 5m in 10-15 secs from GPS sat.
Eventually defaulted to location over WiFi (testing next to work with WiFi).

Motorola G6, also ODK-Collect 1.21.2, same location/situation, GPS satellite fix in ~10 secs (slower than usual), found about 10-15 satellites (so the Americans are not currently bombing someone else and left some satellites over Australia), some accuracy went below 5 m.

Last season (Oct 2018 - Mar 2019), our Lenovo Tab3 never got an accuracy below 10m, so never went to auto-save. Not tragic, but indication that something went wrong between Android location API and ODK-Collect.

**Comment by lognaturel** [comment]
At long last, the Fused location provider has been not only fixed but much improved by Google and it's making its way back to Collect. [The change is out in beta](https://forum.getodk.org/t/odk-collect-v1-28-beta-gps-plus-other-sensors-for-location-calculation-updates-in-repeats/27661).
