### ISSUE TITLE
Enable MissingPermission lint check

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2528]
According to http://tools.android.com/tips/lint-checks:

```
This check scans through your code and libraries and looks at the APIs being
used, and checks this against the set of permissions required to access those
APIs. If the code using those APIs is called at runtime, then the program will
crash.

Furthermore, for permissions that are revocable (with targetSdkVersion 23),
client code must also be prepared to handle the calls throwing an exception if
the user rejects the request for permission at runtime.
```

https://github.com/opendatakit/collect/pull/2506/files#r213148258 suppressed that check when the target SDK version went up to 23. 

The check should be re-enabled. If it's flagging real issues, those need to be addressed. If it's flagging false alarms, the check should be suppressed locally with the [`SuppressLint`](https://developer.android.com/reference/android/annotation/SuppressLint) annotation.

**Comment by kaftand** [comment]
@opendatakit-bot claim

**Comment by kaftand** [comment]
Yes! Still working on it! In the field right now so internet is crap. Hopefully can finish up this weekend!

**Comment by kaftand** [comment]
@opendatakit-bot claim
