### ISSUE TITLE
Showing error Plugin[id:'com.github.spotbugs',version '1.6.2'] was not found in any of the following sources

### ISSUE THREAD

**Issue by ghost** [getodk/collect#2531]
#### Software and hardware versions 
Collect v1.x.x, Android v3.0.1., device used... Windows 64-bit

#### Steps to reproduce the problem
Whenever I try to build the app it show me this error

#### Expected behavior

Error:(19, 0) Plugin [id: 'com.github.spotbugs', version: '1.6.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.spotbugs:com.github.spotbugs.gradle.plugin:1.6.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository
<a href="openFile:E:\gsoc project\collect\build.gradle">Open File</a>

I am not able to build the app

**Comment by ghost** [comment]
Any help will thankful !!!!!

**Comment by lognaturel** [comment]
This doesn't seem to be a problem with ODK Collect so I'm going to close the issue. 

If you still have the problem, please ask in the #collect-code channel of [the developer Slack](http://slack.opendatakit.org/) and be sure to state how you are attempting to build the app and what you have tried to overcome the problem.
