### ISSUE TITLE
Installation of .xml form into ..\assets\forms\ before building APK not working

### ISSUE THREAD

**Issue by thanhgis** [getodk/collect#2536]
#### Software and hardware versions 
Android Studio 3.1, Collect v1.6.4 source code from this GitHub. 

#### Problem description
Copied *.xml form and its media (*-media folder) into ..\assets\forms\ is not working
#### Steps to reproduce the problem
1. In Android Studio: 
- Create a new directory named "forms" inside "assets" directory; 
- Copy form_name.xml (procuded by using ODK XLSForm Offline v1.7.0) and its media folder (named as "form_name-media"). 
- Build APK file successfully. 
2. In mobile device, Android 5.x, 6.x, 7.x:
- Install APK file from the above. 
- Open ODK Collect, no form installed.
#### Expected behavior
Did I do somethhing wrong, or this feature has already removed?
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
Can you please point to documentation or other references that made you think this was a supported feature?

**Comment by lognaturel** [comment]
If you have any more information on where you've seen this functionality, @thanhgis, we can investigate! I don't believe it has ever been a feature in core Collect.
