### ISSUE TITLE
Reduce loading time for each widget by not creating it twice in certain cases

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2537]
#### Software and hardware versions 
Collect v1.17.0

#### Problem description
Every time we return from the `FormHierarchy` menu, the selected widget is generated twice instead of just once. 

The problem was noticed while working on https://github.com/opendatakit/collect/pull/2535/ as it was causing a lot of trouble in refactoring the code. Until now, the wait-mechanism was being used to reach to the widget for setting the answers from `onActivityResult`. But when `rxEvents` were added to the widgets to intercept them, it was noticed that the events were being received multiple times, even when only one widget was visible. 

Reason for that was that the `refreshCurrentView` was being called from both `onResume` and `onActivityResult`. 

#### Steps to reproduce the problem
I added logs at multiple places to verify that the widgets were being generated twice.

#### Expected behavior
It should just be created once.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
@shobhitagarwal1612 you may want to double check #3023 but I'm pretty sure it addresses everything in this issue.
