### ISSUE TITLE
Remove splash screen from ODK Collect

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#254]
The splash screen was added to enable branding. There continue to be forks of Collect because the splash screen with a custom logo is not adequate. I would like to remove the splash screen because it is not sufficient and focus instead on the solutions in #233

### Notes

We should make it so the new [Android 12 Splash Screen](https://developer.android.com/guide/topics/ui/splash-screen) is shown instead of our one (investigation into this in #4592). As part of this work we should make app initialization run while the splash screen is up (using the [new API](https://developer.android.com/guide/topics/ui/splash-screen#suspend-drawing)).

This would be a perfect time to consider updating the Collect icon...

**Comment by jnordling** [comment]
Do this PR relate to his issue? Skip intro screen #224

**Comment by lognaturel** [comment]
Hehe, @jnordling seems they would be related but no. This one refers to the screen that shows on app launch. The other one is the form instruction screen. So many intro screens!

**Comment by grzesiek2010** [comment]
Two months ago we started login events about splash screen https://github.com/grzesiek2010/collect/commit/c882a10ee332ecc70f4083453f03a3fe84d57af8

Now I can see 305 events https://analytics.google.com/analytics/web/#/report/app-content-event-events/a91951913w136214323p140411927/_u.date00=20190118&_u.date01=20190324&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:PreferenceChange

It's not a big number and generally, I don't like this option (I think that if someone wants his own name/logo, he should just fork our repo and implement required changes, we don't allow to change the logo or app name so why that image), so I would be in favor of removing it. 

We should at least remove logging those events because in some cases it causes a crash https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5c63005ef8b88c296394c625?time=last-seven-days&sessionId=5C9744F4031B0001197497531BFDFD8A_DNE_0_v2

but as I said I would like to remove both.

@yanokwa what do you think?

**Comment by shobhitagarwal1612** [comment]
Are you in favour of removing the ability to change splash screen image or the entire splash screen itself?

Maybe we can do a forum polling as well to get user opinion.

**Comment by grzesiek2010** [comment]
> Are you in favour of removing the ability to change splash screen image or the entire splash screen itself?

Generally both but at least the ability to change splash screen image.

**Comment by grzesiek2010** [comment]
I'll just add that during last year we received 28 events from 12 users where 82.1% of them are from Poland so triggered by the QA team:
https://console.firebase.google.com/u/0/project/api-project-322300403941/analytics/app/android:org.odk.collect.android/events~2Freport~2FShowSplashScreen%3Ft=1584016561439&fpn=322300403941&swu=1&sgu=1&sus=upgraded&params=_u..pageSize%253D25%2526_u.dateOption%253Dlast12Months%2526_r..eventId%253DShowSplashScreen&cs=app.m.events.detail&r=default&g=1

@lognaturel please close this issue if you still think it's better to keep the splash screen.

**Comment by lognaturel** [comment]
Thanks for bringing this back up, @grzesiek2010. It looks like I was on maternity leave when analytics were added so I missed it.

I just added analytics to track when the splash screen is displayed for an app launch that is not the first one. This also tracks a hash of the image path. That way, we'll know how many different custom images are being set and how often they're seen by actual users. This will help us know what kind of messaging to put around the deprecation.

The analytics you point to were merged right before this beta, @grzesiek2010, so it's not surprising that there are very few events so far.

**Comment by seadowg** [comment]
@lognaturel and I disucess while working on #3813 (which stops showing the splash screen unless it's been enabled by the user) and decided that a good way forward would be to remove the "Splash screen" preference that lets user's enable the default splash screen. This would mean that the splash screen would only show if a custom one is configured. I'll post acceptance below just to check @lognaturel and I are on the same page:

**Acceptance**

- [ ] Given I've never opened the app
When I open the app
I do not see a splash screen

- [ ] Given I've opened the app for the first time
When I navigate to the "User interface" settings in the app
Then I see a "Splash screen" option with "None selected" below it
When I click "Splash screen" 
And I select an image from my device
Then I see the image path below "Splash screen"
When I close (kill) and reopen the app 
Then I see the selected image

- [ ] Given I've selected a splash screen for the app
When I navigate to the "User interface" settings in the app
And I click "Splash screen"
And I click "Remove splash screen"
Then I see "None selected" under "Splash screen"
When I close (kill) and reopen the app 
Then I do not see a splash screen

**Comment by lognaturel** [comment]
Our hand will be forced around this with Android 12 and required splash screens. I don’t believe it will be possible to use configured images. https://developer.android.com/about/versions/12/features/splash-screen

**Comment by seadowg** [comment]
From the investigation done in #4592, our plan is now just to kill the splash screen entirely. This will need announced on the forum (added blocked tag for this).

**Comment by lognaturel** [comment]
Announced: https://forum.getodk.org/t/collect-splash-screen-will-be-removed-in-v2022-3/37410
