### ISSUE TITLE
Collect repeatedly asks for a username and password if a port number is included in the server URL

### ISSUE THREAD

**Issue by xsteelej** [getodk/collect#2541]
#### Software and hardware versions 
Collect v1.16.3, Android v8.0.0, Google Pixel 2 XL

#### Problem description
When a port number is appended onto the server URL and the user: _anonymousUser_ has the option "Data Collector" switched off, Collect repeatedly asks for a username and password when "Get Blank Form" is selected.

#### Steps to reproduce the problem

**Config on Aggregate server:**
1. Login as administrator
2. Select "Site Admin"
3. Untick Data Collector on "anonymousUser" (and any other columns that may be ticked)
4. Save Changes

**Config on Collect:**
1. Navigate to General Settings->Server
2. Enter the URL of the Server + Port number
3. Leave out the username / password

**Steps to reproduce:**

1. After configuring as above, navigate to "Get Blank Form"
2. Observe that the "Server Requires Authentication" pops up
3. Type in the administrator username / password (Or other username that has Data Collector ticked).
4. Observe that the request fails and Collect asks for the username / password over and over.

#### Expected behavior
Entering a correct username and password should be accepted and the operation completed successfully.

#### Other information 
N/A

**Comment by lognaturel** [comment]
Strangely, I still can't reproduce! I've cleared the settings on my device, removed it from memory, verified I'm running off the latest master, verified the server doesn't have anonymous access, changed the server password.

You're running Aggregate in the VM? Is there any kind of redirect going on?

What if you try https://nafundi-test.appspot.com with username test and password foo?

**Comment by xsteelej** [comment]
I'll try that yes

**Comment by xsteelej** [comment]
Hi @lognaturel ,

I tested it with that server and yes it works! Let me step through the code and figure out why - but yes it's when I'm running a VM, but I don't think a redirect is occurring.. I'll investigate and let you know shortly.

Thanks

**Comment by xsteelej** [comment]
Ok @lognaturel, now I know what the issue is - when the URL has a port attached to the host then the problem occurs.

**Comment by lognaturel** [comment]
Ahhh, perfect, thank you! That is a subtle case.

**Comment by xsteelej** [comment]
If you append :443 onto the back end of https://nafundi-test.appspot.com then the issue is repeatable.
