### ISSUE TITLE
Firebase Performance class definition not found

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2542]
#### Software and hardware versions 
Collect v1.17.0-beta.0, multiple Android versions and devices

#### Problem description
`NoClassDefFoundError` on `com.google.android.gms.internal.firebase-perf.zzw` for either the main menu ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b9ea423f8b88c29631db51d?time=last-seven-days&sessionId=5B9F87A603BF0001085AA1D208E86309_DNE_0_v2)) or the splash screen ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b9ea425f8b88c29631db559?time=last-seven-days&sessionId=5B9F67E101D80001315A70CFBA869AF0_DNE_0_v2)).

I think this is a fatal crash and am surprised no one has reported it. I've asked for reports [on the forum](https://forum.opendatakit.org/t/odk-collect-v1-17-beta/15196/2).
```
Fatal Exception: java.lang.NoClassDefFoundError
com.google.android.gms.internal.firebase-perf.zzw
com.google.firebase.perf.metrics.Trace.start (Unknown Source:44)
com.google.android.gms.internal.firebase-perf.zze.onActivityStarted (Unknown Source:48)
android.app.Application.dispatchActivityStarted (Application.java:223)
android.app.Activity.onStart (Activity.java:1241)
android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:589)
android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:177)
org.odk.collect.android.activities.MainMenuActivity.onStart (MainMenuActivity.java:425)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1248)
android.app.Activity.performStart (Activity.java:6213)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2658)
```

#### Steps to reproduce the problem
Unknown.

#### Expected behavior
No crash

#### Other information 
This could be related to https://github.com/firebase/quickstart-android/issues/550. If we can't figure it out quickly, I think we should remove performance monitoring.

**Comment by grzesiek2010** [comment]
yeah, it's definitely a firebase bug, I can't reproduce. Someone claims that making firebase-perf version lesser or equal to Firebase-core version fixes the issue (https://stackoverflow.com/a/51968102/5479029) 
generally, we could try but it's only one person so I wouldn't believe in that (since I can't reproduce on my own). So maybe as you said we should remove performance monitoring for now.

**Comment by lognaturel** [comment]
We don't include `firebase-crash` anymore since we use `crashlytics` so I don't think that particular issue and solution matches ours.

I've been able to remove Play Services on the Android 4.1.1 device I have. I saw a notification about a Play Services error but no crash. I'll be interested to see tomorrow whether a crash was logged because that would indicate it might not be fatal.

Since the change to remove the logging is so small, I tend to want to leave it in through the beta so we can gather more information. @mmarciniak90 @grzesiek2010, I'll leave it up to you to decide whether that's ok or whether you prefer #2546 to be merged before release testing starts.

**Comment by grzesiek2010** [comment]
I'm not totally in favor of merging #2546 right away. We can wait.

But I would give it (https://github.com/opendatakit/collect/pull/2548) a try.

**Comment by lognaturel** [comment]
This is still occurring in beta.1: [Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5ba4415df8b88c2963aa842a?time=last-seven-days&sessionId=5BA3E93E002B0001356B70CFBA869AF0_DNE_0_v2) so it looks like it probably wasn't a proguard issue.

**Comment by grzesiek2010** [comment]
...at least we tried.

**Comment by lognaturel** [comment]
Yes, it was a good thing to try for sure. We can still wait until right before the release to merge #2546 and see if we can get any more info from the beta somehow.

**Comment by lognaturel** [comment]
I'm not comfortable releasing with these crashes still happening. Unfortunately, it looks like users may have joined the beta without realizing what that means and may not know to report feedback. I think they're experiencing real crashes so let's merge #2546.

The Firebase Performance team is aware of the issue and sharing updates [on Stackoverflow](https://stackoverflow.com/a/52169082/137744).

**Comment by Sub-Zero-1** [comment]
Same here: 

Fatal Exception: java.lang.NoClassDefFoundError
com.google.android.gms.internal.firebase-perf.zzw

com.google.firebase.perf.metrics.Trace.start (Unknown Source:44)
android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:178)
com.sub_zero.ipostcard.activity.ProductActivity.onStart (ProductActivity.java:583)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1238)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Just saw it on my new updated App version.

**Comment by yanokwa** [comment]
@Sub-Zero-1 What specific version? Is it easy to reproduce? If so, how?
