### ISSUE TITLE
App crashes when user accept recorded sound and wants to add it to Audio widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2557]
#### Software and hardware versions 
Collect v1.17.0, 1.16.1, 1.16.0
Android v6.0, 7.0, 8.1
 
#### Problem description
App crashes when user accept recorded sound and wants to add it to Audio widget

#### Steps to reproduce the problem
1. User starts a form with Audio widget
2. User clicks on `Record Sound`
3. User accept recorded sound
4. App crashes

#### Expected behavior
* Sound is added 
* Crash does not occur

#### Notes 
Crash does not occur if the previously recorded sound is added

**Comment by grzesiek2010** [comment]
Isn't it a device with Sony Audio Recorder app? https://github.com/opendatakit/collect/issues/705

**Comment by mmarciniak90** [comment]
I'm able to reproduce the problem on Samsung S7, Motorola Moto G Play and Nexus 5X.
I used Audio Recorder app : https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder&hl=en

**Comment by grzesiek2010** [comment]
So we can close.

**Comment by lognaturel** [comment]
I can see the stack trace for a Moto G4 Play in the crash logs and it looks like it's actually a duplicate of #2342.
