### ISSUE TITLE
Widgets with buttons look different with the readonly option

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2562]
#### Problem description
Working on
https://github.com/opendatakit/collect/issues/2560
https://github.com/opendatakit/collect/issues/2558
https://github.com/opendatakit/collect/issues/2551

I noticed that our widgets look different with the readonly option. Sometimes buttons are hidden and sometimes just disabled. I think we should be consistent and keep just one approach.

**The button is hidden:**
BearingWidget
ImageWidget
DrawWidget
AnnotateWidget
SignatureWidget
AudioWidget
OSMWidgets
GeoWidget

**The Button is visible but disabled:**
VideoWidget
ArbitraryWidget
UrlWidget
ExStringWidget/ExIntegerWidget/ExDecimalWidget/ExPrinterWidget
RangePickerWidget
BarcodeWidget
DateWidget/TimeWidget
SpinnerWidget
GeoTrace/GeoShape widgets and GeopointWidget with maps orplacement-map appearance

Here is all widgest form where each question is readonly: 
[all-widgetsReadOnly.zip](https://github.com/opendatakit/collect/files/2402858/all-widgetsReadOnly.zip)

**Comment by lognaturel** [comment]
👍 Was thinking about this in the context of https://forum.opendatakit.org/t/append-ranked-choices/15243/7 -- I use this technique of using a read-only question to echo back a previous answer quite a bit and the button is really annoying in that case. 

I really can't see any reason to have the button. Not having it means that when we one day do logic updates within a single screen it would need to appear and disappear on readonly status changes but that seems fine to me.

I'd rather remove the button everywhere.

**Comment by grzesiek2010** [comment]
I also agree that it doesn't make sense to display those buttons.
Please take look at my pr https://github.com/opendatakit/collect/pull/2563
if you approve my approach you can close: 
https://github.com/opendatakit/collect/pull/2555 and
https://github.com/opendatakit/collect/pull/2561

because we don't need to disable those buttons if they are not displayed of course.

**Comment by lognaturel** [comment]
Let's start by narrowly fixing the issues in #2555 and #2561 and then we can continue to get feedback on this and plan on including it in the next release!

**Comment by lognaturel** [comment]
@yanokwa Do you think we should get user feedback on this or just move forward?

**Comment by yanokwa** [comment]
I think we can proceed with removing and ask for feedback in the beta. In the unlikely case that there are lots of complaints, it's easy to roll back.
