### ISSUE TITLE
Make it easier for users to update metadata, e.g. username

### ISSUE THREAD

**Issue by florianm** [getodk/collect#2573]
#### Problem description
Many data collectors share few devices. We use the metadata field "username" to attribute their survey effort. Many data collectors forget to update this field, leading to incorrect attribution and post-survey QA effort.

#### Expected behavior
Would it be possible, maybe even with an admin settings option, to promote metadata to a more prominent location? The target user group are tired volunteers, some not too techincally minded, grabbing devices at 5am and heading out to survey turtle nesting beaches.

I'm not an expert in UI/UX, but some options could be:

* Top level menu entry "Who am I" or "configure user" (looking for a better label than jargon-y "update metadata") as shortcut (with admin settings option to hide) to page "update metadata".
* Top level menu entry "configure device" allowing users to scan a (pre-printed or emailed) QR code to update some/all/non-sensitive settings (including but not limited to username).
* Move "update metadata" higher up in the settings. Still, must-have fields hidden in settings (three dots in corner of screen) are easy to overlook.

#### Observations
* Typing on a touch screen at 5am, even one's own name, is extremely error-prone. Scanning a QR code would fix typos but fails if QR code is not available/forgot to bring.
* Email might be easier to match to users, but extra typing effort (plus typos) is a considerable dent in the UX (unless scanned in via QR code).
* It's not always possible for a well-trained coordinator to hand out devices and during that hand-over, ensure that metadata are updated.

Other use cases might prefer email over usernames or have reason to update other (custom, see #443) metadata fields.

**Comment by lognaturel** [comment]
Sorry this slipped through the cracks, @florianm. Please file feature requests on the forum so they can be discussed, triaged and specified. There are lots of questions here about what the behavior should actually be that warrant discussion with the broader community.

We try to keep the issue tracker focused on issues that have a clear desired result and can be closed by a PR.

**Comment by florianm** [comment]
@lognaturel will do, thanks!
Edit: https://forum.opendatakit.org/t/make-it-easier-to-set-username/15909
