### ISSUE TITLE
Add Burmese (Myanmar) date widget

### ISSUE THREAD

**Issue by aurdipas** [getodk/collect#2588]
Add appearance burmese similar to ethiopian [#1505](https://github.com/opendatakit/collect/pull/1505).

https://en.wikipedia.org/wiki/Burmese_calendar

The goal is for the widget to look like other calendar widgets and to use standard Android components as much as possible. Ideally this will involve creating a new Joda chronology just like for the [EthiopicChronology ](https://github.com/JodaOrg/joda-time/blob/909046aa9aab5fae75e2152fd6ded722a4d5aba2/src/main/java/org/joda/time/chrono/EthiopicChronology.java).

There is a repo with MIT license that can be used https://github.com/chanmratekoko/mmcalendar .

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
Hi @DreamyPhobic 

the work of this issue is in progress using this I was just removed because I ran into some issues and wait for answers from the author of https://github.com/chanmratekoko/mmcalendar.

Please take one of the other issues.

**Comment by DreamyPhobic** [comment]
ok @grzesiek2010 no problem...Thanks.

**Comment by DreamyPhobic** [comment]
@opendatakit-bot unclaim

**Comment by aurdipas** [comment]
Any update @grzesiek2010 ?

**Comment by grzesiek2010** [comment]
No. The problem is with the repo we used https://github.com/chanmratekoko/mmcalendar/issues/1 so I hope the author is going to fix bugs.

**Comment by chanmratekoko** [comment]
> No. The problem is with the repo we used [chanmratekoko/mmcalendar#1](https://github.com/chanmratekoko/mmcalendar/issues/1) so I hope the author is going to fix bugs.

Hi @grzesiek2010 

You can use with this version.

```maven
<dependency>
  <groupId>com.github.chanmratekoko</groupId>
  <artifactId>myanmar-calendar</artifactId>
  <version>1.0.6.RC3</version>
</dependency>
```

And also you can test with this code.

```java
        int mmYear = 1358;

        String[] ema = { "First Waso", "Tagu", "Kason", "Nayon", "Waso", "Wagaung", "Tawthalin", "Thadingyut",
                "Tazaungmon", "Nadaw", "Pyatho", "Tabodwe", "Tabaung", "Late Tagu", "Late Kason" };

        MyanmarMonths myanmarMonths = MyanmarDateKernel.getMyanmarMonth(mmYear, 1);
        List<Integer> monthIndexes = myanmarMonths.getIndex();

        for (int index = 0; index < monthIndexes.size(); index++) {
            Integer monthIndex = monthIndexes.get(index);
            double julianDate = 0;
            if (index == 0) {
                Thingyan thingyan = ThingyanCalculator.getThingyan(mmYear);
                double newYearDay = thingyan.getMyanmarNewYearDay(); // Myanmar new year day
                julianDate = newYearDay;
            } else {
                julianDate = MyanmarDateKernel.m2j(mmYear, monthIndex, 1);
            }

            MyanmarDate myanmarDate = MyanmarDateKernel.j2m(julianDate);
            WesternDate westernDate = WesternDateConverter.convert(myanmarDate);

            System.out.println(" MY: " + myanmarDate.getYearInt() + " MMI: " + monthIndex + " WY: "
                    + westernDate.getYear() + " WMI: " + westernDate.getMonth() + " Day " + westernDate.getDay());
        }
```

Hopefully, It can help you. 

If you have any questions, please feel free to ask me.
