### ISSUE TITLE
Submissions with media to Ona fail with Premature end of Content-Length 

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2592]
Starting at  https://github.com/opendatakit/collect/commit/f5320f638cd12b767ccaba4c94b689bc4bdd7501 (the HTTP refactor) if you send a form submission to Ona with any media (e.g., form with a single image), it reports the following. This problem does not seem to occur with Aggregate.

>  Premature end of Content-Length delimited message body (expected: 114; received: 0

```
HttpClientConnection: org.opendatakit.httpclientandroidlib.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 114; received: 0
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:200)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:103)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.util.EntityUtils.consume(EntityUtils.java:88)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.execchain.MainClientExec.execute(MainClientExec.java:297)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.execchain.RetryExec.execute(RetryExec.java:88)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
HttpClientConnection: 	at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
HttpClientConnection: 	at org.odk.collect.android.http.HttpClientConnection.uploadSubmissionFile(HttpClientConnection.java:382)
HttpClientConnection: 	at org.odk.collect.android.tasks.InstanceServerUploader.uploadSubmissionFile(InstanceServerUploader.java:327)
HttpClientConnection: 	at org.odk.collect.android.tasks.InstanceServerUploader.processChunk(InstanceServerUploader.java:142)
HttpClientConnection: 	at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:435)
HttpClientConnection: 	at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:61)
HttpClientConnection: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
HttpClientConnection: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
HttpClientConnection: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
HttpClientConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
HttpClientConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
HttpClientConnection: 	at java.lang.Thread.run(Thread.java:761)
InstanceUploaderActivity: uploadingComplete: Processing results (1) from upload of 1 instances!
```

In 1.16.4 we:
1. Send a HEAD and get a 401 with WWW-Authenticate. 
1. Send a HEAD with Authorization and get back a 204. 
1. Send a POST with Authorization and get back a 201.

In 1.17.0 we:
1. Send a HEAD and get a 401 with WWW-Authenticate. 
1. Send a HEAD with Authorization and get back a 204. 
1. Send a POST with **no** Authorization and get back a 401 with WWW-Authenticate. 
1. Send a POST with Authorization and get back a 201.

Aggregate, Central, Kobo seem to handle this fine. Ona does not.

**Comment by lognaturel** [comment]
1.16.4 `localContext` when issuing `POST`:
> {BasicHttpContext@5289} "{http.request=HEAD /submission?deviceID=imei%3A357103072887707 HTTP/1.1 [User-Agent: Dalvik/2.1.0 (Linux; U; Android     5.1.1; SM-T285 Build/LMY47V) org.odk.collect.android/v1.16.4, X-OpenRosa-Version: 1.0, Date: Fri, 28 Sep 2018 06:40:36 GMT+00:00, Host: odk.ona.io, Connection:     Keep-Alive, Accept-Encoding: gzip,deflate, Authorization: Digest username="lognaturel", realm="DJANGO",     nonce="1538160118.28:1DDB:c184d0644c69f151637afb475745eed8", uri="/submission?deviceID=imei%3A357103072887707", response="fe2454c3b4fa97892859c56d39d6f5bf",     qop=auth, nc=00000001, cnonce="7b9bf273e3538370", algorithm=MD5, opaque="959BB86005D9CFD1BACCC162F4EA0924"], http.request-config=[expectContinueEnabled=false,     proxy=null, localAddress=null, cookieSpec=default, redirectsEnabled=true, relativeRedirectsAllowed=true, maxRedirects=1, circularRedirectsAllowed=true,     authenticationEnabled=true, targetPreferredAuthSchemes=[Digest, Basic], proxyPreferredAuthSchemes=null, connectionRequestTimeout=-1, connectTimeout=600"

1.17.0 `localContext` when issuing `POST`:
> {BasicHttpContext@5454} "{http.cookie-store=[], http.auth.auth-cache={http://odk.ona.io:80=[B@31e9b21b}, http.auth.credentials-provider={BASIC <    any realm>@odk.ona.io:8443=[principal: lognaturel], BASIC <any realm>@odk.ona.io:443=[principal: lognaturel], DIGEST <any realm>@odk.ona.io=[principal:     lognaturel]}}"
