### ISSUE TITLE
ODK Collect and ODK JavaRosa Integration

### ISSUE THREAD

**Issue by jeager** [getodk/collect#2609]
First of all, sorry for coming to github instead of ODK Forum, but I could't registrate myself, so I came here looking for some help :)

I've read about both **tools**, ODK Collect and ODK JavaRosa, As far as I understand, JavaRosa does the form rendering according to the specifications of the ODK XForms and the ODK Collect does a parse of this render for the Android Platform as an APP.

But I'm not sure if I get it right. Is there any extra documentation regarding the integration of these two tools? I've searched the Documentation of both but they only explain about themselves and **how to set it up**. My main doubt is **what is the responsability of each tool and how do they integrate with each other?**

Sorry again for posting it here instead of the ODK Forum.

**Comment by yanokwa** [comment]
JavaRosa is a Java library that renders forms complying with ODK XForms. Collect uses that library. Unfortunately, there isn't much documentation besides what you can see in the Collect source code.

If you have more questions, please try to register again on the form. If that fails, try asking on the Slack at http://slack.opendatakit.org.
