### ISSUE TITLE
Videos are not playing and sounds are deformed on Android 4.1.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2622]
#### Software and hardware versions 
Collect v1.17.x, Android v4.1.x, device used...

#### Problem description
Videos are not playing - they open but a black screen is visible and one of the sounds is deformed (3rd one) on Android 4.1.

#### Steps to reproduce the problem
Play video and play the 3rd audio. Form that I used is attached in https://github.com/opendatakit/collect/issues/2604.

#### Expected behavior
Vidoes and audios should play. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by DreamyPhobic** [comment]
I checked the problem in Android emulator with 4.1 jelly bean, I think it is a problem of in-built video player itself because even I wasn't able to play any video from gallery, it always show the same error "Can't play the video."

**Comment by lognaturel** [comment]
I agree with your assessment, @DreamyPhobic. I have a 4.1 device that does not have this property.
