### ISSUE TITLE
Offline Layer is not set on Android 7.0

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2624]
#### Software and hardware versions 
Verified Collect v1.15.1 and above
Samsung Galaxy S7
Android 7.0

#### Problem description
Offline Layer is not set on Android 7.0

#### Steps to reproduce the problem
1. The user selects Offline Layer

#### Expected behavior
1. Selected Offline Layer is set on map

**Comment by lognaturel** [comment]
https://docs.opendatakit.org/collect-offline-maps describes how to set up offline layers.

@mmarciniak90 It works on Android 8.0?

**Comment by mmarciniak90** [comment]
@lognaturel I'm able to check only on Android 8.1 because I do not have a device with Android 8.0, but I hope it is not a big deal.
**Offline Layer works correctly on Android 8.1**

**Comment by mmarciniak90** [comment]
Issue retested on **ODK v1.19**
* Problem is not visible on Xiaomi Redmi 4x with **Android 7.1**
* Problem is still visible on Samsung Galaxy S7 with **Android 7.0**

**Comment by mmarciniak90** [comment]
The issue is no longer valid. Retested on version 1.30.1.
Offline Layer is applied on map on Android 7.0.
Verified on all available maps and Geo widgets.
