### ISSUE TITLE
App crashes at the moment when Upload Results dialog should appear after sending ~1k forms if 'Do not keep activities' option is turned on

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2626]
#### Software and hardware versions 
Verified Collect v1.16.0 beta 3, v1.17.2

#### Problem description
App crashes at the moment when Upload Results dialog should appear after sending ~1k forms if 'Do not keep activities' option is turned on

#### Steps to reproduce the problem
1. 'Do not keep activities' option is selected in Android Developer Options
2. The user sends a lot of forms
![screenshot_20181010-115643](https://user-images.githubusercontent.com/3907554/46729145-ca80fb00-cc84-11e8-9081-8ca7f4f3726e.png)
3. All forms are sent properly and the user should see Upload Result dialog
4. App crashes when dialog should appear
[odk_crash3.txt](https://github.com/opendatakit/collect/files/2464286/odk_crash3.txt)

#### Expected behavior
Upload Results dialog appears
![screenshot_20181010-120432](https://user-images.githubusercontent.com/3907554/46729174-e4224280-cc84-11e8-9cf7-a8804bf5dc7b.png)

#### Notes
Tested cases with 470 and 200 submissions -> crash does not occur

**Comment by grzesiek2010** [comment]
Duplication of https://github.com/opendatakit/collect/issues/518
