### ISSUE TITLE
Incorrect disable and enabled logic of Geobuttons

### ISSUE THREAD

**Issue by huangyz0918** [getodk/collect#2633]
#### Software and hardware versions 
geo widgets on Android 4.4, 5.1, 6.0, 7.0, 8.1

#### Problem description
The logic of disabled and enabled geo buttons is incorrect, and you can see more details in this [comment](https://github.com/opendatakit/collect/pull/2276#issuecomment-428568004).

Trash button has a logic problem in:
- geopoint type with placement-map appearance
- geopoint type with map appearance
- geoshape type with no appearance

Zoom button has a logic problem in:
- geoshape type with no appearance

#### Steps to reproduce the problem
- open the geo widget.
- see the whether the button is active or disabled in different cases.

#### Expected behavior
- Buttons should be correct.

#### Other information 
@zestyping If you would like to fix these in your refactor about geo widget, you can claim this issue and please let me know, or I will sent a PR recently. :)

**Comment by lognaturel** [comment]
I believe that the geoshape zoom button issue is only for Google maps. It sounds like there are differences between when GPS is active and inactive.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
