### ISSUE TITLE
Audio recorded via Sony Audio Recorder app is not attached on Android 4.4, 4.2, 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2634]
#### Software and hardware versions 
Collect v1.16.4, 1.17.2 (I did not verify older versions)
Android 4.4, 4.2, 4.1

#### Problem description
Audio recorded via Sony Audio Recorder app is not attached on Android 4.4, 4.2, 4.1

#### Steps to reproduce the problem
1. The user uses a device with Android 4.4, 4.2 or 4.1
2. Sony Audio Recorder app is installed on the device
3. The user opens a form with Audio Widget, eg. All Widgets
4. The user records audio via Sony Audio Recorder app
5. The user saves sound and press Done
6. The user is moved to Audio widget but audio is not available
 
#### Expected behavior
Recorder audio is attached

#### Other information 
Discovered while testing #2613

**Comment by grzesiek2010** [comment]
On Android 4 [resultCode](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L651) is always 0 (`RESULT_CANCELED`) no matter if I accept a recorded file or not. probably that Sony Recorder Audio app just doesn't support Android 4. There is nothing we can do.
