### ISSUE TITLE
Offline basemap selection is lost on screen rotation

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2647]
#### Software and hardware versions 
All versions of Collect.

#### Problem description
If you have selected an offline basemap in the GeoTrace or GeoShape activities, then when the screen is rotated, your selection is lost.

#### Steps to reproduce the problem
Install an .mbtiles file on the device.  Start collecting a GeoTrace or GeoShape.  Tap the "layers" button on the right and choose your .mbtiles file.  The new basemap should appear.

Now rotate the screen.  Your selected basemap disappears.

#### Expected behavior
The basemap should stay there regardless of whether the screen is rotated.

(See related items: #2310, #2640)

**Comment by lognaturel** [comment]
@zestyping was the intent for this to be handled once MapHelper is reworked as was discussed on #2640 or do you want to consider a PR for it now?

**Comment by zestyping** [comment]
The intention was to handle it when MapsHelper is reworked.
