### ISSUE TITLE
Handle the cases better when the permission to access contacts is denied

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2649]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
If the permission to access accounts is denied while uploading instances to google sheets or getting blank forms, it gets stuck at a blank white screen.

#### Steps to reproduce the problem

- Goto `General Settings` > `Server` > Type: Google Drive
- Kill the app
- Reopen the app 
- Click `Send Finalized Form` or `Get Blank Form`
- If you select `Send Finalized Form` then select some forms and click `Send Selected`
- A dialog appears which is asking for access to contacts
- Choose `deny`
- If it was `Send FInalized Form`, it gets stuck at a white screen. If it was `Get Blank Form`, it gets stuck in the same activity

#### Expected behavior
Should go back to the previous activity 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by konishon** [comment]
@opendatakit-bot claim

**Comment by cypherop** [comment]
@opendatakit-bot claim

**Comment by cypherop** [comment]
@opendatakit-bot unclaim

**Comment by ravi-kishan** [comment]
@opendatakit-bot  claim
