### ISSUE TITLE
GEO: Add map settings for custom tile service

### ISSUE THREAD

**Issue by jnordling** [getodk/collect#265]
Feature request resulted from PR 'Updated open mapping options.' #216 #246 

Adding the ability to configure your own tiles server(s) url in the administrator/general settings.

I think there is a lot of potential for map settings, such as default zoom, extent, basemap, online layers etc.. The admin/general are kinda full as is. 
 
Would be a decent size task. All widgets would have to be changed OSM and Google. 

@jnordling

**Comment by wonderchook** [comment]
This would be very useful. In one of our projects I found out people were using OpenStreetMap tiles instead of satellite imagery we provide because they could zoom around and cache some tiles before being disconnected to the internet. For the specific satellite imagery we were using they would need to use GeoODK and also create MBtiles.

**Comment by lognaturel** [comment]
@wonderchook very interesting and great to have a specific use case to design and build this feature for. 

Can you tell us what the service you've been using for that imagery is?

**Comment by wonderchook** [comment]
We provide [DigitalGlobe's MapAPI imagery](https://mapsapi.digitalglobe.com/account). I could also see wanting to add other tile services, sometimes we work with groups that have tiled drone imagery as well. 

**Comment by jnordling** [comment]
Ill take this one. I have been wanting to add this for awhile. Ill have to think about it via ODK core structure. I thinking at the map setting level add a config your online use of a tile layer.

**Comment by jnordling** [comment]
It sounds like there is some reconstruction happening. https://github.com/opendatakit/collect/issues/507 If we are redoing geo stuff we should wait on this until that happens. I will stay on top of it.

**Comment by lognaturel** [comment]
There is now some infrastructure in `MapProvider` and related classes to support this. Inputs to the broader geo roadmap are tracked [in this document](https://docs.google.com/document/d/1OBWEOe_KRBldhyy80KuLPGnPM0WxKy6n81bLxGBgNCY/edit#heading=h.o8qrzqqjskt).
