### ISSUE TITLE
Error occurs when user adds file to File widget from SD card

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2652]
#### Software and hardware versions 
Verified Collect v1.16.4 and v1.17.2
Device with Internal Storage and **SD card**

#### Problem description
Error occurs when user adds file to File widget from SD card

#### Steps to reproduce the problem
1. The user uses a device with  Internal Storage and **SD card**
2. User want to add a file from SD card
![screenshot_2018-10-16-16-21-31](https://user-images.githubusercontent.com/3907554/47020084-dd9a3c00-d158-11e8-87d0-ca63bf5aed47.png)

3. User sees error
![screenshot_2018-10-16-16-23-05](https://user-images.githubusercontent.com/3907554/47020091-e2f78680-d158-11e8-874a-bfae3a4c4961.png)

#### Expected behavior
Adding files from SD card is allowed

**Comment by nshestiuk** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
#2654 fixes this for many devices but there appear to be some devices for which it doesn't work. If someone has one of those devices with an SDCard and can identify what they expect, there may be more improvements to make.

**Comment by nshestiuk** [comment]
@opendatakit-bot unclaim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
This is a pretty niche case, especially given that fewer and fewer devices have sdcard slots. Let's close and see if a user reports.
