### ISSUE TITLE
Replace newlines in form name with spaces (app-wide)

### ISSUE THREAD

**Issue by cooperka** [getodk/collect#2656]
#### Software and hardware versions

Collect v1.17.2

#### Problem description

During the testing of https://github.com/opendatakit/collect/pull/2653, we discovered that newlines are handled differently throughout Collect and Aggregate. It seems like several places convert them to spaces, and other places leave them as-is.

We should either **display them as spaces everywhere** or **convert them to spaces permanently** so no display modifications are necessary.

#### Steps to reproduce the problem

1. Download [instance_name_example.xml](https://github.com/opendatakit/collect/files/2481274/instance_name_example.xml.txt) to Collect
2. Fill the form, including a newline somewhere in the fields (e.g. your last name; form name is dynamic using the entered fields)
3. Save and go back to the form list to view the title

#### Expected behavior

Title should be displayed with spaces instead of newlines.

**Comment by grzesiek2010** [comment]
This issue no longer exist so I'm closing.
