### ISSUE TITLE
Form fails to load if select item has no label

### ISSUE THREAD

**Issue by tinok** [getodk/collect#2660]
#### Software and hardware versions 
Collect v1.7.2, Android v7.0

#### Problem description
When using a form that contains a `select` question that has a response item without a label, collect shows an error upon opening the form: `<item> has no <label>` -- even though the form is valid according to `validate` (which shows warnings but no errors). See 
[screenshot](https://user-images.githubusercontent.com/673511/47197951-869e8d80-d337-11e8-8d44-32f5bb0bc65f.png).

#### Steps to reproduce the problem
Open [this form](https://github.com/opendatakit/collect/files/2494508/burundi_test.xml.zip)
in Collect.

#### Expected behavior
Either:

1. Collect allows displaying responses without labels (preferred)
1. Validate shows an error instead of a warning for responses without any labels (or images, etc.)

#### Other information 
Checked this against the latest version of Validate and Collect.

**Comment by lognaturel** [comment]
> Collect allows displaying responses without labels (preferred)

Can you please describe the use case for an item without a label? I think it would make more sense for Validate to show an error. I wouldn't expect `pyxform` would let this through -- did you use something else to generate it or delete the label manually?

**Comment by tinok** [comment]
Good question, @lognaturel. It's valid xform and normal in many cases to not have a label, e.g.
* question or choice uses image
* question has a hint 
* using multiple label languages, not all labels have been translated yet

If we want to enforce each question/response to have a label we can change it in pyxform and validate to be an error instead of a warning.

**Comment by grzesiek2010** [comment]
@tinok 
I tried the form you attached using v1.17.2 and the newest one and I can't see any warning. I can open and use the form. Could you provide steps to reproduce the issue or maybe we can close it?

**Comment by tinok** [comment]
@grzesiek2010 That's great news If `1.17.2` no longer reproduces this bug I'll go ahead and close the issue here.
