### ISSUE TITLE
Remove unused classes

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2670]
#### Problem description
If a class becomes useless, static code analysis should be able to detect it. This will then automatically be enforced in the future builds as the static tools are run on Circle CI. 
`FormException` is one of the files (I haven't checked if there are any more or not) which is not being used.

#### Expected behavior
Circle CI build should fail the current `master` branch and should be able to point out that `FormException` should be removed as it is not being used anywhere

**Update (Please ignore the above description)**
 - No tool available to make that an automated check
 - Scope of this issue now is to remove the unused classes manually one by one

**Comment by ghost** [comment]
Hello, I'm interested in taking on this issue. Would ProGuard be the right thing to implement in order to achieve the expected behaviour?

**Comment by shobhitagarwal1612** [comment]
Hello @jsaroya and welcome to the community. 
Proguard is already enabled but the purpose of that is to remove those classes while compiling the apk. This issue is to detect those unused classes during static code analysis check (pmd, lint, checkstyle, spotbugs)

**Comment by ghost** [comment]
Thank you for the clarification Shobhit. I'm new to open source and looking for a good first issue to start with.

In order to fix this issue I need to modify the corresponding xml files within the config package, is that right? Just want to confirm before I begin.

**Comment by shobhitagarwal1612** [comment]
Yes, that's what I would also start with. 

If you haven't already introduced yourself to the community, please have a look at https://forum.opendatakit.org/t/introduce-yourself-here/6671

Also, join our slack channel #collect-code for asking any queries or questions regarding development.

:smile:

**Comment by shobhitagarwal1612** [comment]
If you would like to work on this issue, please comment `@opendatakit-bot claim` so that the bot can assign this issue to you

**Comment by ghost** [comment]
Ok, I'll make sure to do that. :)

@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
https://github.com/evernat/dead-code-detector/wiki/Usage

**Comment by muarachmann** [comment]
@shobhitagarwal1612 i would like to work on this, from the chat i see that i need this tool to use https://github.com/evernat/dead-code-detector/wiki/Usage to get the classes that are not use. What is this to do, remove them or ?? a guide would be helpful thanks 😃

**Comment by yash17525** [comment]
@shobhitagarwal1612  I have used the tool(Dead Code Detector) that you have metioned here: https://github.com/evernat/dead-code-detector/wiki/Usage  .And the report provided by this tool is not up to the mark when used on the collect app.It is not showing in it's results the "FormerException" Class ,that you have metioned earlier.

Given below  are images of the report:
![screenshot from 2019-01-23 22-42-59](https://user-images.githubusercontent.com/33418013/51624209-5b43c400-1f60-11e9-8b01-9d9804aa634f.png)
![screenshot from 2019-01-23 22-43-10](https://user-images.githubusercontent.com/33418013/51624216-5da61e00-1f60-11e9-8da4-5ad94ad84e0e.png)


I would like to work on this issue.Please guide me.

**Comment by shobhitagarwal1612** [comment]
Looks like findbugs/spotbugs doesn't support this [link](https://stackoverflow.com/questions/4721142/can-findbugs-detect-unused-public-methods) and so does PMD [link](https://sourceforge.net/p/pmd/discussion/188194/thread/37a971e0/)

But Android Studio's inspection tool is able to detect some of them 
To try that,
```
Analyze > Run Inspection By Name > Type "Unused declaration" > Check Classes 
```

I thought that this [library](https://github.com/evernat/dead-code-detector/wiki/Usage) should work but it doesn't. So, I think for now, it would be better if we can just detect the unused classes using the Android Studio's Analyze tool and remove them manually. 

 @muarachmann Would you like to give it a try since you were the first one to comment on the issue?

**Comment by shobhitagarwal1612** [comment]
@yash17525 That's right, I was playing around with tools when trying to add a automated check but unfortunately, I couldn't find anything promising. As mentioned in the above comment, Android Studio's tool  works well too.

**Comment by yash17525** [comment]
@shobhitagarwal1612  Thanks for your answer.I would try as suggested by you.

**Comment by muarachmann** [comment]
@yash17525 are on this. If yes let me know. Didnt get notified @shobhitagarwal1612 have been waiting for a reply on this for long. Kinna lost in the whole repo. @yash17525 if interested i will pick up some other issue thanks just let me know :)

**Comment by shobhitagarwal1612** [comment]
@muarachmann Please claim the issue by commenting `@opendatakit-bot claim`

**Comment by muarachmann** [comment]
@opendatakit-bot claim

**Comment by muarachmann** [comment]
> <@U41GJ54HL>, <@U367LV6QL>, <@U34CXHJP2> regarding <https://github.com/opendatakit/collect/issues/2670> i ran Analyze and seen close to 113 unused declarations. Whats the way forward… delete them, uncomment. Let me know your thoughts thanks
<sub>[View in Slack](https://opendatakit.slack.com/archives/C35ENHA64/p1549978317003300)</sub>

**Comment by shobhitagarwal1612** [comment]
@muarachmann You can remove one of the unused class and open a PR.

**Comment by muarachmann** [comment]
ok will do just that thanks @shobhitagarwal1612

**Comment by serializer** [comment]
Hey, I am new to the open source community. I was thinking about removing unused classes by simply using "Find Usages" function available in Android Studio.

**Comment by lognaturel** [comment]
Hi @tronku and welcome! That sounds great. If you can find a static analysis check that will make sure no newly unused classes are introduced, that would be ideal, but it's ok if not. It's possible you won't find any more unused classes in which case we can simply close this issue.

**Comment by serializer** [comment]
okay great!

**Comment by serializer** [comment]
@opendatakit-bot claim

**Comment by serializer** [comment]
@lognaturel  I have a doubt. I found two classes - MapFragment and AndroidShortcuts. Both have usages within themselves only, should i remove them too?
