### ISSUE TITLE
Always only one fail message when there is no submission URL in Google Sheets upload no matter of amount of submissions.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2671]
#### Software and hardware versions 
Collect v1.17.x, Android v8.1.x, device used...

#### Problem description
There is always only one fail message when failed to send submissions to Google sheet when no submission URL added no matter how many submissions you are trying to send. On other devices, Androids from 4.1-7.0 fail messages are displayed for each failed submissions. 
Screenshots of a try to send 28 submissions to Google sheet from master, and from pr with the updated error message:
![screenshot_20181023-135221](https://user-images.githubusercontent.com/33342488/47359102-20659200-d6cc-11e8-80d1-c39dbfb6a386.png)
![screenshot_20181023-135423](https://user-images.githubusercontent.com/33342488/47359116-2a879080-d6cc-11e8-945c-bb56b6a15540.png)

#### Steps to reproduce the problem
Use Android 8.11 device to:
1. On server settings input only Google account and do not add a fallback sumission URL
(do dot use form with defined submission url as well)
2. Try to send moe that 1 submission.

#### Expected behavior
For each failed process there should be separate fail message.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
This should be fixed by #2619. Please confirm.

**Comment by kkrawczyk123** [comment]
Actually, when I tried I saw an issue which I didn't see before in https://github.com/opendatakit/collect/pull/2619.

**Comment by lognaturel** [comment]
Thank you, you are absolutely right, @kkrawczyk123! I have fixed that issue. Now in #2619 you should see the "no sheet id" message for each submission that failed. Once that one gets merged, it will get the improved message from #2648.

**Comment by kkrawczyk123** [comment]
Confirmed that it is fixed in https://github.com/opendatakit/collect/pull/2619!
