### ISSUE TITLE
Allow pulldata() to be used on external_choices / itemsets.csv

### ISSUE THREAD

**Issue by joeflack4** [getodk/collect#2673]
## Current behavior
Using `pulldata()` on `itemsets.csv` (generated by the `external_choices` worksheet of an XLSForm)  does not appear to work.

## Expected behavior
Using `pulldata()` on `itemsets.csv` (generated by the `external_choices` worksheet of an XLSForm) should be able to work just as for any other csv file.

**Comment by lognaturel** [comment]
Please file feature requests on the forum so they can be triaged and specified.

**Comment by joeflack4** [comment]
Will do~
