### ISSUE TITLE
Gregorian date in Islamic/Coptic/Ethiopian/Nepali date widget should be visible in the language which is set in device

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2683]
#### Problem description
Gregorian date in Islamic/Coptic/Ethiopian/Nepali date widget should be visible in the language which is set in device

#### Steps to reproduce the problem
1. The user has set other device language than English
2. The user adds date to Islamic/Coptic/Ethiopian or Nepali date wigdet
3. Gregorian date is visible in English 

| | | |
|---|---|---|
|![screenshot_20181024-133933](https://user-images.githubusercontent.com/3907554/47428332-3f7b2700-d793-11e8-8f68-149e84498f09.png)|![screenshot_20181024-133926](https://user-images.githubusercontent.com/3907554/47428336-430eae00-d793-11e8-957c-e1371e0c70d4.png)|![screenshot_20181024-133921](https://user-images.githubusercontent.com/3907554/47428358-4d30ac80-d793-11e8-9501-3ddc08801e8a.png)|

#### Expected behavior
Gregorian date should be visible in the language which is set in the device

**Comment by ajwad-shaikh** [comment]
@opendatakit-bot claim

**Comment by ajwad-shaikh** [comment]
@lognaturel  @mmarciniak90  I think there's an easy fix to this.

The `getCustomDateTimeLabel` function in `DateTimeUtils` is set to `Locale.US`

```
private static String getCustomDateTimeLabel(Date date, DatePickerDetails datePickerDetails, boolean containsTime, Context context) {
        String gregorianDateText = getGregorianDateTimeLabel(date, datePickerDetails, containsTime, **Locale.US()**);

        DateTime customDate;
        String[] monthArray;
```

I tried changing the `Locale.US` to `Locale.getDefault()` . ***The Problem was solved!***

However, I am not sure if there are any other implications of this change.

@lognaturel  need some insight on if `Locale.US` was set for a reason.

**Comment by ajwad-shaikh** [comment]
> @lognaturel @mmarciniak90 I think there's an easy fix to this.
> 
> The `getCustomDateTimeLabel` function in `DateTimeUtils` is set to `Locale.US`
> 
> ```
> private static String getCustomDateTimeLabel(Date date, DatePickerDetails datePickerDetails, boolean containsTime, Context context) {
>         String gregorianDateText = getGregorianDateTimeLabel(date, datePickerDetails, containsTime, **Locale.US()**);
> 
>         DateTime customDate;
>         String[] monthArray;
> ```
> I tried changing the `Locale.US` to `Locale.getDefault()` . _**The Problem was solved!**_
> 
> However, I am not sure if there are any other implications of this change.
> 
> @lognaturel need some insight on if `Locale.US` was set for a reason.



@shobhitagarwal1612 Do you have any insight on if the change could have other implications?

**Comment by ajwad-shaikh** [comment]
Expecting an update to continue working on this :(
@shobhitagarwal1612  @mmarciniak90  @lognaturel 
Should I send a PR with the change?

**Comment by shobhitagarwal1612** [comment]
Apologies for the late reply.
Yes, please send a PR with the change and if anyone has any other ideas or suggestions then we can discuss it over there as well.

**Comment by ajwad-shaikh** [comment]
Hey @opendatakit-bot , I am working on the issue and the PR is submitted. But it wasn't clean and I'll be submitting another fresh clean PR by EOD
