### ISSUE TITLE
Auto-send triggered even if wrong connection type is available

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2684]
#### Software and hardware versions 
Collect v1.18 beta, Android v6.0, Moto G Play

#### Problem description
First reported by @kkrawczyk123 [here](https://github.com/opendatakit/collect/pull/2619#issuecomment-432207336):
> Only on one device Moto G Play, Android 6.0 I saw an issue connected to differentiate the type of connection. On cellular only in autosend - submission was sent when I turn wifi on not cellular and the same in the opposite situation when autosend was set to wifi only and I turn on cellular data. I wasn't able to reproduce it on other devices or on the same device but on the master branch.

#### Steps to reproduce the problem
1. Set auto-send to "Wifi only"
1. Turn off wifi but leave cellular on
1. Finalize a form

The form is sent even though it shouldn't be.

1. Set auto-send to "Cellular only"
1. Turn off cellular but leave wifi on
1. Finalize a form

The form is sent even though it shouldn't be.

#### Expected behavior
The form is only sent when the correct connection type is available.

**Comment by lognaturel** [comment]
I unfortunately don't have a device with a SIM so I'm not entirely confident about the behavior with different connection types. In current master on devices other than that Moto G Play, is it the case that if you set auto-send to wifi only and turn on cellular, nothing happens? And then if you turn on wifi, auto-send is successfully triggered? That would be the intended behavior and I think @kkrawczyk123 has confirmed this but would like to double check.

I am wondering whether the issue could have something with the retry behavior. Could someone please try https://github.com/lognaturel/collect/tree/collect-2684 and see whether that helps or just breaks the retry?

**Comment by grzesiek2010** [comment]
I tried to reproduce with the master branch the issue but no avail everything looks fine. Please try again @kkrawczyk123 if it's ok you can use the commit a81f7a66dd24039758db03693e6b0f889ed34b34 it's the one you commented under. Maybe it was something wrong with that version.

**Comment by kkrawczyk123** [comment]
@grzesiek2010, I also couldn't reproduce it on the newest master which is very weird ;o I am trying to think about some other conditions that could influent on that.

**Comment by grzesiek2010** [comment]
Maybe there was something wrong in the middle of that pr. If it works well and it's confirmed by two of us I think we can close.

**Comment by yanokwa** [comment]
@grzesiek2010 @kkrawczyk123 It sounds like this can be closed. If you disagree, please re-open!
