### ISSUE TITLE
Choose Google account window opens twice when double click on it

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2689]
#### Software and hardware versions 
Collect v1.17.2, Android vx.x.x, device used...

#### Problem description
Choose Google account window opens twice when double click on it

#### Steps to reproduce the problem
1. Go to a server, choose Google drive as type
2. Click on Google account twice

#### Expected behavior
Choose Google account window shouldn't open twice.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by muarachmann** [comment]
@opendatakit-bot claim
