### ISSUE TITLE
Move Collect wiki pages to Collect wiki

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#269]
The following pages should probably be moved to this repo.

https://github.com/opendatakit/opendatakit/wiki/Collect-Release-Notes
https://github.com/opendatakit/opendatakit/wiki/Collect-Troubleshooting
https://github.com/opendatakit/opendatakit/wiki/Collect-Source-Code-Overview

**Comment by jnordling** [comment]
GH pages might be good for this. https://pages.github.com/

**Comment by lognaturel** [comment]
For the release notes, we should use [https://github.com/opendatakit/collect/releases](https://github.com/opendatakit/collect/releases).

**Comment by seadowg** [comment]
@yanokwa @lognaturel it looks this stuff has moved into Github releases or is now covered in our (repo) docs. Closing this but reopen if I'm wrong!
