### ISSUE TITLE
App crashes if the user returns to Get Blank Form view when Storage permission is unselected

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2694]
#### Software and hardware versions 
Collect v1.18
Collect v1.17.**2**

Collect v1.17.1 works correct

#### Problem description
App crashes if the user returns to Get Blank Form view when Storage permission is unselected

#### Steps to reproduce the problem
1. The user opens the app as the first time and allows Storage permission
2. The user opens Get Blank Form / Delete Saved Form
3. Permission is unselected and the user returns to Collect
4. App crashes

#### Expected behavior
The user sees the dialog and is able to allow storage permission

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim

**Comment by manish3499** [comment]
@opendatakit-bot claim

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by breakbusyloop** [comment]
I've had a lot of trouble finding evidence of the crash in the logs, but using exception breakpoints reveals that the first null pointer exception that is triggered by the repro steps comes from DiskSyncTask.doInBackground.

In the following code fragment, formDefs is null due to the inability to access the filesystem.

```
File[] formDefs = formDir.listFiles();
for (File addMe : formDefs) {
...
```

**Comment by breakbusyloop** [comment]
I tested a code change with a fix for the DiskSyncTask null pointer reference, but that did not address the problem with the app crashing. I also tried registering a hook for unhandled exceptions, but no unhandled exceptions were making it to the exception handler. The problem may be occurring in a third party or in the Android system. I see exceptions like the following getting thrown right before the app dies:

```
android.system.ErrnoException: access failed: ENOENT (No such file or directory)

1 = {Class@6433} "class libcore.io.Linux"
2 = {Class@6148} "class libcore.io.ForwardingOs"
3 = {Class@6158} "class libcore.io.BlockGuardOs"
4 = {Class@6148} "class libcore.io.ForwardingOs"
5 = {Class@3699} "class android.app.ActivityThread$AndroidOs"
6 = {Class@8061} "class java.io.UnixFileSystem"
7 = {Class@8414} "class java.io.File"
8 = {Class@2730} "class android.app.SharedPreferencesImpl"
9 = {Class@2730} "class android.app.SharedPreferencesImpl"
10 = {Class@594} "class android.app.SharedPreferencesImpl$2"
11 = {Class@2349} "class android.app.QueuedWork"
12 = {Class@2349} "class android.app.QueuedWork"
13 = {Class@600} "class android.app.QueuedWork$QueuedWorkHandler"
14 = {Class@5219} "class android.os.Handler"
15 = {Class@3976} "class android.os.Looper"
16 = {Class@680} "class android.os.HandlerThread"

while attempting to access file:
/data/user/0/org.odk.collect.android/shared_prefs/com.google.android.gms.measurement.prefs.xml.bak
```

**Comment by breakbusyloop** [comment]
Ultimately the solution may be to force the user to exit the app after warning them to fix permissions. Currently the warning dialog appears but does not prevent the user from continuing to use the app. Without file permissions they can't get far, so perhaps we shouldn't let them use the app at all once we detect this problem.

**Comment by grzesiek2010** [comment]
We are just about to remove that permission because we will use scoped storage so I'm closing.
