### ISSUE TITLE
Upgrade osmdroid library version from 5.6.4 to 6+

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2695]
ODK Collect currently uses the org.osmdroid library version 5.6.4, from February 2017.  The latest version of this library is 6.0.1, released February 2018.

There have been several improvements and bug fixes to osmdroid since 5.6.4 that might be nice for us, such as support for higher zoom levels, fractional zoom levels, and geopackage support.  See https://github.com/osmdroid/osmdroid/wiki/Changelog for detailed release notes.

However, upgrading is more involved than just changing the version number in the `build.gradle` file.  The API has some non-compatible changes; for example, some of the classes for offline tile support are gone.

@zestyping: I took a brief look at this and didn't find obvious documentation on how to migrate from 5.6.4 to 6+.  I think someone will need to take a little time to survey what's changed and make a plan.  Anyone is welcome to look at this, but **please come up with a plan and let's discuss it here** before proceeding to make a pull request.

**Comment by grzesiek2010** [comment]
I tried to update osmdroid working on #3329 but noticed crashes like https://github.com/osmdroid/osmdroid/issues/1299 in the newest version 6.1.0 so let's wait for next release.

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/opendatakit/collect/pull/3728
