### ISSUE TITLE
OSM base map and MBTiles may disappear at zoom levels 21 or 22

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2696]
**NOTE:** This is a placeholder issue. We believe this is likely to be addressed by upgrading osmdroid.  See #2695.

On some phones, when you zoom all the way to zoom level 22 on an OSM map (in the GeoTrace or GeoShape activity), the base map tiles disappear, leaving just a blank grid.

@ivangayton reports:

> Some testing with OSM basemap:
> * Zoom works to 19, and you can pan anywhere you like.
> * When you zoom up to 20 and 21, it scales the tiles up (you can see that the labels pixillate, so it's obviously scaled). However, if you pan sideways, you go off the edge of the scaled tiles and find the graph-paper-grid empty area beneath. When moving laterally it seems it doesn't fetch new level-19 tiles to scale.
> * At zoom 22, the OSM tiles disappear altogether, leaving only the graph-paper-grid emptiness.
> So zooming to level 20 or higher seems only to work by scaling level-19 tiles that have already been downloaded. And then only to level 21—at level 22 it's blank.
>
> Immediately afterward on the same phone, I tried an MBTiles raster with tiles from level 16 to 20. That displayed perfectly until level 20, then disappeared—so at level 21 the scaled OSM tile popped up from behind the MBTiles. As far as I can see, the MBTiles never scale at all, while the OSM tiles seem to scale from 19 to 21 (but only in the region already covered by a downloaded level-19 tile).

On @zestyping's two phones (Sony Xperia Z3 compact, Huawei LYO-L21), exactly the above behaviour was observed.  When @lognaturel tried it on her phone, though, she was able to zoom all the way to 22 and the tiles did not disappear. Just as Ivan experienced, only the tiles that had been previously loaded at level 19 stayed present; new tiles did not load at zoom level 22.

#### Software and hardware versions 
Collect 1.17.1, osmdroid 5.6.4

#### Problem description
* OSM basemap tiles disappear at zoom level 22
* MBTiles disappear at zoom levels 21 or 22
* Panning to new areas does not cause new tiles to load at zoom levels 21 and 22

#### Steps to reproduce the problem
Select the OSM map API in the UI settings, open a GeoTrace or GeoShape widget, and zoom in as far as possible.

#### Expected behavior
Loaded tiles should stay visible and new tiles should load and appear.

**Comment by zestyping** [comment]
Please do not claim this issue until #2695 is addressed.

**Comment by grzesiek2010** [comment]
This issue does not occur anymore so I'm closing.
