### ISSUE TITLE
Fix minification for release APKs

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#271]
When trying to build a signed APK for release, the APK crashes on launch. Disabling [code shrinking with ProGuard](https://developer.android.com/studio/build/shrink-code.html) fixes it. It should be possible to minify a release build.

**Comment by yanokwa** [comment]
This also means that CircleCI builds also don't actually run :(

**Comment by grzesiek2010** [comment]
I'll take a look at it.

**Comment by grzesiek2010** [comment]
I've just added changes and keep javarosa classes in proguard file as it was a problem.
I tested sieze of apk too today and here is my report:

Size of apk without shrinking = 4,6 MB (4606834 bytes)
Size of apk with shrinking = 2,4 MB (2352714 bytes)
as above + my changes = 2,4 MB (2361122 bytes)

So shrinking works well.

**Comment by lognaturel** [comment]
This proguard configuration broke Google Drive (#360). It might be good to look at Dimagi's [CommCare rules](https://github.com/dimagi/commcare-android/blob/master/app/proguard.cfg) for ideas.

**Comment by grzesiek2010** [comment]
I investiagetd the problem and discovered that adding
`-dontobfuscate`

in proguard file fixes the problem. But we should test other functionalities. Maybe this change is not enough.

**Comment by lognaturel** [comment]
Very good to know. @mitchellsundt mentioned that it could also be related to the fact that the GDrive library is really old (#296).
