### ISSUE TITLE
Add Firebase Performance Monitoring

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2710]
https://github.com/opendatakit/collect/pull/2508 added Firebase Performance Monitoring. It went out in a beta and provided some interesting insights like network delays that users are experiencing in different locales and screens that take a long time to load.

We then saw crashes related to the dependency in https://github.com/opendatakit/collect/issues/2542 and removed it before going to production.

Some folks from the Firebase team have been looking at the problem reported at https://stackoverflow.com/questions/51933637/noclassdeffounderror-on-com-google-android-gms-internal-firebase-perf-zzw. 

https://github.com/firebase/quickstart-android/issues/550#issuecomment-434574615 suggests the latest release may address the problem. I have asked whether there's a consistent way to tell if it is fixed. We could wait to hear back about that, see if others report that the fix was successful or try it in the next beta.

**Comment by grzesiek2010** [comment]
@lognaturel what about this, can we add it back?

**Comment by lognaturel** [comment]
Thanks for doing a triage pass, @grzesiek2010. Were you thinking you might want to add it for this upcoming beta? I think that would be fine and we'd just have to be ready to roll back if any issues at all come in.
