### ISSUE TITLE
Make rating widget stars orange

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2711]
In https://github.com/opendatakit/collect/pull/2585, @akshay-ap introduced a star-based rating widget. Currently, the filled star color is the theme icon color (black for the default light theme and white for the dark theme).

In https://github.com/opendatakit/collect/pull/2585#issuecomment-434836043, @smoyth points out that orange is a common color for these types of ratings questions that is culturally neutral and high contrast against both white and black.

There is already an orange color used by the grid widget that is `#ff8c00`. I propose introducing a resource for that color and using it in both places (the grid widget currently builds the color from integer RGB values).

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I think this color works for both dark and light themes. Should it be introduced once as something like `highContrastHighlight` or do you think both themes should have it defined separately even if the value is the same? That would be something like `lightHighContrastHighlight` and `darkHighContrastHighlight`.

**Comment by shobhitagarwal1612** [comment]
> Should it be introduced once as something like `highContrastHighlight` or do you think both themes should have it defined separately even if the value is the same? 

Using a single color resource sounds like a better idea. The other option would require addition of another attribute and then adding it to both of themes in `theme.xml` which isn't required if both themes are going to have the same value

**Comment by akshay-ap** [comment]
@opendatakit-bot claim
