### ISSUE TITLE
Animations while navigating in Settings

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2714]
#### Software and hardware versions 
Collect v1.18.0

#### Problem description
In `General Settings` and `Admin Settings` when we move into the next level of setting, no animation effect is applied.
Every screen in the app follows a entry/exit transition animation. Same should also be followed in the settings for consistency (eg. Click `Fill blank form` and press back. Notice the animation effect)

#### Steps to reproduce the problem
1. Open `General Settings` from the options menu
2. Click on any sub setting
3. No transition animation effect is noticed

----------
1. Open `Admin Settings` from the options menu
2. Click on `Import/Export settings` or any of the `User Access Control`
3. No transition animation effect is noticed

#### Expected behavior
Transition effect should appear

**Comment by Stafedor** [comment]
Hello @shobhitagarwal1612, can I work on this issue ?

**Comment by shobhitagarwal1612** [comment]
Hey @Stafedor, please claim the issue by commenting `@opendatakit-bot claim` below

**Comment by Stafedor** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@shobhitagarwal1612 Can you please file another issue to review all transitions so we know where the differences are? Once we have that, it'll be a good place for new contributors like @Stafedor to help with.

**Comment by anemoiusjerry** [comment]
Hello can I get an update on this issue? As I would like to work on it if still open

**Comment by grzesiek2010** [comment]
Hi @anemoiusjerry 
there is a pull request here https://github.com/opendatakit/collect/pull/2735 but the solution is not satisfying for us. There is no action so we are going to close it and you can try but first please read what was wrong there.

**Comment by anemoiusjerry** [comment]
@grzesiek2010 can you clarify the problem for #2735? Is it that the solution plays different animations on different devices?

**Comment by yanokwa** [comment]
@anemoiusjerry Have you had a chance to read through the entire conversation at https://github.com/opendatakit/collect/pull/2735?

**Comment by AathmanT** [comment]
Can I work on this issue?

**Comment by janvi04** [comment]
hi!  I am Janvi. Can I work with this issue?

**Comment by grzesiek2010** [comment]
@AathmanT sure but according to my previous comment https://github.com/opendatakit/collect/issues/2714#issuecomment-447565409 it will be accepted only if new animations are consistent with those used by activities across different Android versions.

**Comment by AathmanT** [comment]
Okay. Thank you.

**Comment by AathmanT** [comment]
@opendatakit-bot claim

**Comment by AathmanT** [comment]
@opendatakit-bot unclaim

**Comment by Arnesh07** [comment]
@opendatakit-bot claim

**Comment by Arnesh07** [comment]
@opendatakit-bot unclaim

**Comment by fatimah5** [comment]
@opendatakit-bot claim 
I would like to work on this issue!

**Comment by wbagais** [comment]
@opendatakit-bot claim 
I want to work on this as well :)

**Comment by shashvat-kedia** [comment]
@opendatakit-bot claim
I am new to this project and would like to contribute.

**Comment by saumya1singh** [comment]
@opendatakit-bot claim
I am new to this project. I want to work on this issue.

**Comment by grzesiek2010** [comment]
Hi @SaumyaSingh1 
welcome here!

The issue is a bit tricky so please read all the comments carefully before you start work on the code.

**Comment by saumya1singh** [comment]
Okay @grzesiek2010

**Comment by devanshi7799** [comment]
@opendatakit-bot claim.
I am new to open source and i want to work on this issue.

**Comment by grzesiek2010** [comment]
I think it's not a `good first issue` because it's discouraging and demotivating... many new contributors tried and no one was able to fix it (then they disappeared) but at first glance it seems like something easy, In fact it's tricky, animations look different across different Android versions, we don't specify animations for other activities so we shouldn't do that here as well.
