### ISSUE TITLE
Memory leak due to Dexter library

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2715]
#### Software and hardware versions 
Collect v1.18.0

#### Problem description
The current version of [Dexter](https://github.com/Karumi/Dexter) causes memory leaks

#### Steps to reproduce the problem
1. Enable `leak canary` for debug build by using `Collect` application class instead of `TestCollect` in debug/AndroidManifest.xml
2. Run the app
3. Leak canary detects memory leak in `SplashScreenActivity` caused due to the usage of library `Dexter`

#### Expected behavior
No memory leak should happen

#### Other information 
https://github.com/Karumi/Dexter/releases suggests that version 5.0.0 resolves this problem. So, we should try updating the dependency and verify that it does solve this problem

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
