### ISSUE TITLE
Use highContrastHighlight in grid widget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2718]
https://github.com/opendatakit/collect/pull/2713 introduced the `highContrastHighlight` color resource. This is the same color as is used by `GridMultiWidget` and `GridWidget` for identifying selected items. 

Those two grid widget classes currently set the color using red, green and blue decimal values. They should use the `highContrastHighlight` resource instead to guarantee consistency.

**Comment by ajwad-shaikh** [comment]
@opendatakit-bot claim

**Comment by ajwad-shaikh** [comment]
I am setting a public final int BACKGROUND_ORANGE to get Resource int (highContrastHighlight) and then passing it to the setBackgroundColor directly.

I have compiled and tested the code later. No errors were noticed and the color shade showed up perfectly in the sample form Grid Widget.

**Comment by ajwad-shaikh** [comment]
Submitted PR https://github.com/opendatakit/collect/pull/2725

Thank you for the opportunity!

**Comment by ajwad-shaikh** [comment]
Apologies. Unused imports causing circleci tests to fail. Submitting another PR after cleaning the code.

**Comment by ajwad-shaikh** [comment]
I'm so sorry to have crowded so many PRs. The final PR #2727 qualifies both the CircleCi tests and also solves the issue.

Thanks for letting me work on this!
