### ISSUE TITLE
Create an XLSForm with all widgets

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#272]
This sample form will be used on the demo server and used for documentation and testing. Attach the XLSForm to a comment on this issue.

You can find a list of the widgets at https://github.com/opendatakit/collect/tree/master/collect_app/src/main/java/org/odk/collect/android/widgets
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java

http://xlsform.org/ref-table might also be helpful, but not that it's not a complete list.

**Comment by MartijnR** [comment]
The XLSForm link at the top of this form is a good start: https://enke.to/::widgets

**Comment by syedaffanhamdani** [comment]
Hello Martin! Are you working on it? If not then I would like to work on it please..

**Comment by yanokwa** [comment]
@syedaffanhamdani, I think @MartijnR was just pointing out a good place to start. You should start work on it!

**Comment by MartijnR** [comment]
yes, please do @syedaffanhamdani!

**Comment by syedaffanhamdani** [comment]
Thanks. I am working on it.

**Comment by syedaffanhamdani** [comment]
Sorry I am a bit swamped with other stuff. Cannot work anymore on it.

**Comment by wonderchook** [comment]
@syedaffanhamdani how far did you get? Can you share?

**Comment by Dvik** [comment]
hey, i would like to work on it. 
however, i'm getting a 'error getting form list' with error code 503. how to resolve this?

**Comment by rishsethia** [comment]
@wonderchook  @yanokwa @lognaturel 
I want to create the sample XLSForm ! Should I go ahead ?

**Comment by lognaturel** [comment]
@rishsethia Yes please, that would be wonderful!

**Comment by aakashswain001** [comment]
I want to create a sample XLSForm . Should I try ? Or this task has already been completed ?

**Comment by rishsethia** [comment]
@aakashswain001  It's done ! :D

**Comment by rishsethia** [comment]
Up for review :
~~https://docs.google.com/spreadsheets/d/1WE4Q5vHW1Qf5qQleor99BZ5tz3qluv4iYc-AOR8OKdE/edit?usp=sharing~~
https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ

**Comment by yanokwa** [comment]
Thanks, @rishsethia! Quick question. How did you verify that this form works in ODK Collect?

**Comment by rishsethia** [comment]
I didn't verify that it works for ODK Collect ! I used the code to make this XLSForm . Should I verify it by uploading it to the ODK Server ? Also , after that I would like to document usage of each widget in the code itself as it was cumbersome for me to look for entire code of certain widgets !
Thanks !

**Comment by yanokwa** [comment]
@rishsethia Verify it by converting the XLSForm to XML and running it in ODK Collect. I've put rough instructions at https://github.com/opendatakit/collect#testing-a-form-locally.

**Comment by yanokwa** [comment]
Hi @rishsethia! Have you been able to make progress here?

**Comment by rishsethia** [comment]
Hi @yanokwa 

Sorry about the delay . I had my mid semester exams last week , so was unable to make progress on it ! Getting to it on priority basis now ! Thanks ! :D

**Comment by rishsethia** [comment]
Hi @yanokwa , @lognaturel 

When I'm trying to get my xlsform converted on odk website , I'm getting this error :
Error: 'dict' object has no attribute 'parent'

Do you have any idea what this error is due to ? I also tested on all 3 mediums and on all 3 mediums , I am getting different type of error !
Thanks

**Comment by pailletm** [comment]
Hi @rishsethia,

I made some changes in the form. 
Everything should work now. (Think of adding media to compile and get a valid xlm) :D

[odkmpa3.xlsx](https://github.com/opendatakit/collect/files/836909/odkmpa3.xlsx)

**Comment by yanokwa** [comment]
@rishsethia Can you please allow suggestions from people who know your Google Sheets URL, so @pailletm can suggest those changes directly to your form.

**Comment by rishsethia** [comment]
Hi @yanokwa @pailletm 
Sure sir !

~~https://docs.google.com/spreadsheets/d/1WE4Q5vHW1Qf5qQleor99BZ5tz3qluv4iYc-AOR8OKdE/edit?usp=sharing~~

https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ

**Comment by pailletm** [comment]
Hi,
thank's, 
changes are made directly in your Google Sheet form.
Now, it's necessary to do some testing ;-)

**Comment by rishsethia** [comment]
Hi @yanokwa  @pailletm 

I've tested the form on the app and it works for the most part :D. I am facing this issue : 

1. Which external app to launch on external app data collection widgets ?

Thanks

**Comment by pailletm** [comment]
Hi @rishsethia,

maybe you can use this one :
https://github.com/opendatakit/breathcounter/blob/master/BreathCounter/breathTest.xml

**Comment by rishsethia** [comment]
Hello @pailletm 

On my device , it still says the requested app is missing . I originally used :

ex:change.uw.android.TEXTANSWER wherein also I faced same issue !

@yanokwa Apart from the external app launch issue , the form is ready! Thanks for your patience and apologies for delay due to exams  :D

**Comment by rishsethia** [comment]
Hello @yanokwa sir ,

Should I go ahead and upload the form on the server ?

**Comment by yanokwa** [comment]
@rishsethia How did you verify the form was working? When I try this on my Moto G4 running master, the second question fails with this error.

<img width="592" alt="error" src="https://cloud.githubusercontent.com/assets/32369/24212149/b67b11b6-0f04-11e7-8f09-1cbf5b5b4469.png">

**Comment by rishsethia** [comment]
Hi @yanokwa 

Yes sir , you are right ! I faced the same issue ! But this is due to a bug in the code !

At Line number 96 , in AlignedImageWidget , the if condition is wrong logically and should be replaced by ,

"  if (splits.length <= i) { "

Actually I solved the issue in my code but then forgot to mention it here !

Should I send a PR for the same ?

Thanks sir

**Comment by yanokwa** [comment]
@rishsethia Good thing we have this sample form that you made! First, file an issue that documents the problem, then send in the pull request.

Also, please don't call me sir! You are the one doing the work, I should call you sir!

**Comment by rishsethia** [comment]
@yanokwa , 

Okay Sure , going ahead and filing the issue !
And that is your humbleness sir ! :D

**Comment by lognaturel** [comment]
This looks great, @rishsethia, @pailletm! I'd like to get a few more eyes on it and then make sure it's available from the official server and mentioned in the README.
https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ

I tried to make sure that each control and appearance was included and clearly documented. There may still be a few missing. @wonderchook @shobhitagarwal1612 @grzesiek2010 @yanokwa and others, would be great to get your review.

**Comment by grzesiek2010** [comment]
@lognaturel I've investigated the file and I've made some changes. It looks ok for me.

**Comment by grzesiek2010** [comment]
@lognaturel We can close this issue

**Comment by lognaturel** [comment]
@grzesiek2010 You're right. Thanks to everyone who helped out on this! Now we just have to come up with a good process for keeping it up to date.
