### ISSUE TITLE
listFiles() in InstanceProvider#deleteAllFilesInDirectory() might retrun null

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2720]
#### Software and hardware versions 
Collect v1.18.0 and older versions

#### Problem description
[From Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5bd8bc81f8b88c2963df7a42?time=last-seven-days&sessionId=5BDB3E2F00D900012E8840DAE12BAEB1_DNE_1_v2) (requires auth):

```
org.odk.collect.android.provider.InstanceProvider.deleteAllFilesInDirectory (InstanceProvider.java:227)
org.odk.collect.android.provider.InstanceProvider.delete (InstanceProvider.java:288)
android.content.ContentProvider$Transport.delete (ContentProvider.java:374)
android.content.ContentResolver.delete (ContentResolver.java:1422)
org.odk.collect.android.upload.AutoSendWorker.doWork (AutoSendWorker.java:160)
androidx.work.Worker$1.run (Worker.java:57)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)

```

**Comment by grzesiek2010** [comment]
Ahh it's the same https://github.com/opendatakit/collect/issues/2709 so I'm going to close this issue.

**Comment by lognaturel** [comment]
Heh, I can see why you filed it. It really looks like it's something wrong with new code that should be fixed. Let's keep an eye on it! 👍
