### ISSUE TITLE
Sending forms via SMS doesn't work on Android >= 8

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2756]
#### Software and hardware versions 
Collect v1.18.*

#### Problem description
Sending forms via SMS doesn't work on Android >= 8

#### Steps to reproduce the problem
Try to send forms via SMS on Android >= 8

**Comment by yanokwa** [comment]
@mmarciniak90 I want to make sure you see this. Not sure how this got past our testing 😭
