### ISSUE TITLE
Execute transform error when running collect from android studio

### ISSUE THREAD

**Issue by anemoiusjerry** [getodk/collect#2760]
#### Software and hardware versions 
Collect v1.18.2, Android v9.0, Pixel XL API 28 (emulated)

#### Problem description
I am trying to test the app and when following the "Setting up your development environment" section but got build error: java.lang.IllegalStateException

Anyone else had this issue before? I tried googling but all suggested solutions have failed. Thanks

**Comment by grzesiek2010** [comment]
Hi @anemoiusjerry 

if you have a problem please as on Slack http://slack.opendatakit.org
or on the forum: https://forum.opendatakit.org/

opening a new issue is not a good way in case of such problems.
Btw. probably this is a solution to your problem:
https://github.com/opendatakit/collect#execution-failed-for-task-collect_apptransformclasseswithinstantrunfordebug
