### ISSUE TITLE
Dialog title and positive button not visible in Dark Theme

### ISSUE THREAD

**Issue by ravi-kishan** [getodk/collect#2801]
#### Software and hardware versions 
Collect v1.17.1, Android v7.0 API 24, Motorola Moto G4

#### Problem description
The title and positive button of the showAdditionalExplanation dialog are not visible in Dark Theme in preference activity. The dialog works correctly in other activities.

#### Steps to reproduce the problem
Goto General Settings->User Interface and select Dark Theme
Then goto General Settings -> Server -> Choose Google Drive in Type
Select Google Account ->Deny Contacts permission

Or any other way to see showAdditionalExplanation Dialog in preferences activity.
#### Expected behavior
The title and positive button should be visible
#### Other information
![odk](https://user-images.githubusercontent.com/31040431/51240803-7d5aa680-19a2-11e9-83af-8de19887be31.jpeg)

**Comment by ravi-kishan** [comment]
@grzesiek2010 May I work on this issue?

**Comment by grzesiek2010** [comment]
sure you can claim any not claimed issue. To do that please add a comment:
>@opendatakit-bot claim

**Comment by ravi-kishan** [comment]
@opendatakit-bot claim
