### ISSUE TITLE
Menu icon is not visible in the bar about logging location coordinates in the background on Android 4.2 and 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2813]
#### Software and hardware versions 
Collect https://github.com/opendatakit/collect/pull/2772
Android v4.2, v4.1

#### Problem description
Menu icon is not visible in the bar about logging location coordinates in the background on Android 4.2 and 4.1

#### Steps to reproduce the problem
1. User uses a device with Android 4.1 or 4.2
2. User opens form [AuditTestLocationBackground.xml.txt](https://github.com/opendatakit/collect/files/2786232/AuditTestLocationBackground.xml.txt)
3. User sees bar
![screenshot_2019-01-22-16-12-17](https://user-images.githubusercontent.com/3907554/51591775-2eef5f80-1eee-11e9-8751-49e569f5f7d4.png)

#### Expected behavior
Bar contains menu icon - 3 dots
![screenshot_20190122-142057](https://user-images.githubusercontent.com/3907554/51591820-47f81080-1eee-11e9-9fcb-de33d52921b7.png)

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
