### ISSUE TITLE
Bin icon is not visible in form with repeat titles

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2821]
#### Software and hardware versions 
Collect v1.19

#### Problem description
Bin icon is not visible in form with repeat titles

#### Steps to reproduce the problem
1. User fills the form with repeat titles [1648.xml.txt](https://github.com/opendatakit/collect/files/2791810/1648.xml.txt)
2. User adds a few repeat groups
3. User goes to `Jump screen`

| | | |
|---|----|---|
|![screenshot_20190124-141124](https://user-images.githubusercontent.com/3907554/51680672-adc5c480-1fe2-11e9-924c-d614a95cbb3a.png)|![screenshot_20190124-141128](https://user-images.githubusercontent.com/3907554/51680671-adc5c480-1fe2-11e9-85d6-0b93fcc465ad.png)|![screenshot_20190124-141133](https://user-images.githubusercontent.com/3907554/51680670-adc5c480-1fe2-11e9-9f2f-a7c2977b15c8.png)|

#### Expected behavior
Bin icon is visible in:
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/51680630-8cfd6f00-1fe2-11e9-9eed-289f407cba0b.png">

**Comment by mmarciniak90** [comment]
@cooperka, you are a specialist in these icons. Could you look at this case? I'm not totally sure that this icon is expected. Thanks!

**Comment by cooperka** [comment]
Thanks Marzena! You're right this is not expected, there should be a bin. I'll look into a fix tomorrow.
