### ISSUE TITLE
Cannot resolve symbol 'global_tracker' in Collect.java

### ISSUE THREAD

**Issue by ManojPandey121** [getodk/collect#2827]
`tracker = analytics.newTracker(R.xml.global_tracker);`

**Comment by awemulya** [comment]
I am to facing same error when trying to build in Editor.
Am I missing something ??

**Comment by grzesiek2010** [comment]
The `global_tracker` file is generated automatically. Please try to `Build->Clean Project` and `Build->Rebuild Project` and let us know if it helps.

**Comment by ManojPandey121** [comment]
I tried as the suggestion but the problem remains the same. The symbol is not resolved even after clean and rebuild of project.
![global_tracker_err](https://user-images.githubusercontent.com/22314145/51751905-252c4e80-20de-11e9-9503-12863123229f.PNG)

**Comment by grzesiek2010** [comment]
What about you @awemulya? You gave thumbs up so it helped I guess?

**Comment by awemulya** [comment]
I Comment out the code and it worked for me.
// tracker = analytics.newTracker(R.xml.global_tracker);

**Comment by ManojPandey121** [comment]
This is my stack Trace
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':collect_app:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.IllegalStateException: java.lang.IllegalStateException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


* Get more help at https://help.gradle.org

BUILD FAILED in 5m 23s
37 actionable tasks: 22 executed, 15 up-to-date`

**Comment by awemulya** [comment]
My thumbs up is for your quick support. I am getting the same error. as @ManojPandey121

**Comment by konishon** [comment]
@ManojPandey121 that log is a completely different issue, disable instant run and try again
![instant](https://user-images.githubusercontent.com/11831955/52267725-ec07a000-2961-11e9-904c-f84cda92e911.png)

**Comment by ManojPandey121** [comment]
And this worked for me. Thank you @nishontan dai.

**Comment by grzesiek2010** [comment]
Great so we can close.

**Comment by abelcallejo** [comment]
I am getting the same issue. I tried both @grzesiek2010's solution https://github.com/opendatakit/collect/issues/2827#issuecomment-457536987 and @nishontan's solution https://github.com/opendatakit/collect/issues/2827#issuecomment-457536987 but nothing seems to work. `R.xml.global_tracker` is still throwing the message:

> Cannot resolve symbol 'global_tracker'
