### ISSUE TITLE
Offering two ways of going up might be confusing

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2831]
#### Software and hardware versions 
Collect v1.19.x

#### Problem description
In the hierarchy view, we offer two ways of going up. I think the initial idea here was that this would be less confusing for users, but I think it results in two problems.

1. It draws user attention away from the fact that you can now add and delete repeats.
1. It's suggests that the two ups do different things. 

#### Steps to reproduce the problem
Edit Saved Form or Use the jump.
<img width="335" alt="screen shot 2019-01-28 at 5 53 09 pm" src="https://user-images.githubusercontent.com/32369/51878841-f7394b00-2325-11e9-8b04-e33db218db30.png">

#### Expected behavior
A single way to go up.

**Comment by yanokwa** [comment]
@smoyth @cooperka I don't remember, but did we explicitly decide to leave the up button. If so, why?

@grzesiek2010 @zestyping What do you think of the current UX of up?

**Comment by cooperka** [comment]
I don't remember explicitly deciding one way or the other, but in my opinion I think the "Go Up" button at the bottom should be removed now. That way users will also be directed to the new add/remove buttons at the top.

Having the button at the bottom was frustrating for some users because it required a lot of moving back and forth. The "jump menu" button is at the top when filling forms, so having the other navigational button there too makes sense.

**Comment by zestyping** [comment]
I agree with @yanokwa that there should be only one button for going up, and with @cooperka that the one at the bottom is the one that should be removed.

The up button at the top is better, but it is still nonstandard.  Android [has a UX convention for how to do "Up" navigation](https://developer.android.com/training/design-navigation/ancestral-temporal).  Shouldn't we try to follow it?

**Comment by grzesiek2010** [comment]
I was just about to report the same issue and I agree - the one on the bottom should be removed.

**Comment by cooperka** [comment]
I'll remove the bottom button.

@zestyping I think the sense in which Android recommends using the "Up" button is slightly different than how we're using it, and it may be confusing to put it there (integrated into the logo on the top left). On Android "up" is to go back in your **app's hierarchy** of screens, but in Collect it goes back in the **form's hierarchy**. It's not really "back" at all, given that you remain in the jump screen, and you may not have originally come from the item's parent. If you enter the jump menu from deep in the form, going "up" actually causes navigation into a new part of the form the user hasn't been to before.

**Comment by smoyte** [comment]
I am fine with getting rid of 'Go Up' button if y'all think it won't make people flip out in the field.

If we do get rid of 'Go Up', seems it would be good to keep the up arrow since then folks can hopefully figure out what it was replaced by.
