### ISSUE TITLE
Read-only questions with blank labels are not displayed in FormHierarchy

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2836]
#### Software and hardware versions 
Collect v1.18.2 and older versions

#### Problem description
In this pr https://github.com/opendatakit/collect/pull/2816 we discovered that read-only questions with blank labels are not displayed in FormHierarchy. 

It's strange that a question is not visible in the FormHierarchy but we can navigate to it. 

Maybe if a label is empty we can check for hint and display a hint if exists or just display a custom text like: "[No label]".

What do you think?
@cooperka @yanokwa

**Comment by yanokwa** [comment]
I don't think showing the hint is the right choice here. I think `[No label]` or something like that would be better. The danger here is that someone might really want a blank label, and it feels weird to override that.  All this to say, I think the current behavior is correct, but I could be convinced otherwise!

**Comment by grzesiek2010** [comment]
I don't understand the inconsistency here.
A question will be displayed in FormHierarchy if it's not read-only no matter if its label is blank but if it's read-only its label must be defined. Why? Even if a question is read-only it might have an answer (default value) so why read-only state is crucial here?

**Comment by yanokwa** [comment]
I think I misread the initial issue.

If a question doesn't have a label, it should be displayed, but with an empty label. I don't think whether or not it is read-only should matter.

I don't know why the initial code required a label to show if it was read-only. I agree with @grzesiek2010 that the read-only part is weird (and probably a bad decision we made in the past).
