### ISSUE TITLE
Get Collect ready for the Play Store 64-bit requirement

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2844]
According to https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

Starting August 1, 2019:
* All new apps and app updates that include native code are required to provide 64-bit versions in addition to 32-bit versions when publishing to Google Play.
* Extension: Google Play will continue to accept 32-bit only updates to existing games that use Unity 5.6 or older until August 2021.

Starting August 1, 2021:
* Google Play will stop serving apps without 64-bit versions on 64-bit capable devices, meaning they will no longer be available in the Play Store on those devices.
* This will include games built with Unity 5.6 or older.

https://developer.android.com/distribute/best-practices/develop/64-bit has guidance on the steps we can take today in order to ensure that your 32-bit app is ready to support 64-bit devices.

**Comment by grzesiek2010** [comment]
Looks as if it doesn't concern us. We don't use any native code so as they said in the doc:
`If you can not find any '.so' files in your app at all, then your app is already ready and no further action is required`

**Comment by yanokwa** [comment]
Thanks for looking into this. I've confirmed your findings by unzipping the apk, and running `find . -iname "*.so"`.

**Comment by yanokwa** [comment]
We now have native code in Collect, so this issue is now relevant. 

https://github.com/opendatakit/collect/issues/3097#issuecomment-495783546

**Comment by yanokwa** [comment]
I think with with the stub approach at https://github.com/opendatakit/collect/pull/3108 we don't have to make this change until August 2021. Do you agree, @seadowg?

**Comment by seadowg** [comment]
I'm a little worried about #3144 for this one but I'm a bit out of context on the Mapbox work however so I might be missing something here!

It looks like Mapbox has problems initializing on 64 bit devices as it wasn't falling back to the 32 bit binaries (due to `System.load` being called - https://stackoverflow.com/questions/27186243/use-32-bit-jni-libraries-on-64-bit-android). Are we OK with Mapbox not working on 64 bit devices?

**Comment by yanokwa** [comment]
Ugh. Forgot about #3144. Yeah, we want Mapbox to work on 64 bit devices. I'll send in a quick PR.
