### ISSUE TITLE
Copy/paste menu has no borders on Android 6.0

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#285]
#### Software and hardware versions 
ODK Collect v1.4.12, Android 6.0, device used Nexus 5

#### Problem description
Copy/paste menu has no borders on Android 6.0 and for this reason it looks ugly.

#### Steps to reproduce the problem
1. Open a survey with a StringWidget
2. Pass some chars into
3. Double tapp on the text

#### Actual behavior
Copy/paste menu is shown but without borders: http://imgur.com/8fZCYrQ

#### Expected behavior
Copy/paste menu is shown with borders: https://cdn2.vox-cdn.com/uploads/chorus_asset/file/4106704/ccp.0.png

**Comment by grzesiek2010** [comment]
I'll take a look at it.

**Comment by grzesiek2010** [comment]
@lognaturel I investigated this issue and discovered that it works (has the borders) if our targetSdkVersion is 14 or higher. Is there any reason to keep so low targetSdkVersion like we have now (9)? Can we increase this value?

**Comment by lognaturel** [comment]
Thanks @grzesiek2010, that's very good to know! I filed #293 because this question of API levels keeps coming up and we should address it. Hopefully we can just bump `targetSdkVersion` and solve this without a code change.

**Comment by grzesiek2010** [comment]
We can close this as we finished #293  targetSdkVersion. Now it looks ok.
