### ISSUE TITLE
Unable to choose Google account after Deny the permission window.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2852]
#### Software and hardware versions 
Collect v1.19.x, Android v6.0, 7.0, 8.1  device used...

#### Problem description
There is no way to choose Google account after Deny the permission window. Clicking on Google account causes no action. It is possible to display Google account window again after screen rotation. 

#### Steps to reproduce the problem
1. Go to Settings, Server
2. Choose type Google Drive, Google Sheets
3. Click on Google account
4. Deny the permission dialog
5. Click on OK on the next window.
6. Click on Google account again.
7. Rotate devices screen 
8. Click on Google account again.

#### Expected behavior
There should be always the possibility to accept permission window if you deny it first not only after screen rotation. Screen rotation should not matter.  

#### Other information 
Google account window displays also after killing an app.

**Comment by DreamyPhobic** [comment]
I like to work on it.
@opendatakit-bot claim
