### ISSUE TITLE
Icons next to draw options are not visible after first extend the menu

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2858]
#### Software and hardware versions 
Collect v1.19, older versions were not verified
Discovered during testing #2817 

#### Problem description
Icons next to draw options are not visible after first extend the menu

#### Steps to reproduce the problem
1. User opens Draw widget / Annotate widget / Signature widget 
2. User clicks on the `+` icon to extend the menu. Options have icons
3. User clicks again on `+` to collapse menu
4. User clicks on `+` once again
5. Icons next to options are not visible

| | |
|---|---|
|![screenshot_20190208-084657](https://user-images.githubusercontent.com/3907554/52465283-5ac14500-2b7e-11e9-9daa-b4bc189b59ff.png)|![screenshot_20190208-084701](https://user-images.githubusercontent.com/3907554/52465281-5ac14500-2b7e-11e9-8312-92eb505645c4.png)|

#### Expected behavior
 Icons next to options are always visible

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
