### ISSUE TITLE
Improve annotation widget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#286]
As described in [the form design examples document](https://opendatakit.org/help/form-design/examples/), the annotation widget has the following limitations: 

> The dimensions of the captured image will be reduced to fit the device screen prior to annotation. The annotation widget does not support panning or zooming.

Furthermore, the "Set Drawing Color" menu is extremely small and difficult to use on a phone.

**Comment by supreme96** [comment]
Is there a blank form that requires use of image widget as shown here - https://opendatakit.org/help/form-design/examples/

Such a form will be super helpful in resolving this issue.

**Comment by lognaturel** [comment]
[signature-form.xml.txt](https://github.com/opendatakit/collect/files/838530/signature-form.xml.txt) has a signature widget which only differs in `appearance`.

This is a rather large project that would ideally result in a completely redesigned annotation/signature widget. If you are interested in starting to look at it, please propose some general UI sketches for everyone to consider.

**Comment by supreme96** [comment]
👍  @lognaturel will do in probably a day

**Comment by supreme96** [comment]
@lognaturel is a complete redesign of the signature widget required? If we can resize the color picker dialog, I think signature widget would be fine. 
However I cannot comment at this point on the panning or zooming in annotation widget as I haven't been able to find a form that uses that widget.

**Comment by lognaturel** [comment]
@supreme96 The only difference between signature and annotation widgets is the `appearance`. For one it is `signature` and for the other it is `annotate`. That should let you get a form to test with!

**Comment by supreme96** [comment]
@lognaturel  should i begin with a resize of the color picker dialog?

I was thinking of changing the layout to better use the available screen real estate and an option to enter the hex rgb value of a color directly aswell.
What do you think of that?

**Comment by supreme96** [comment]
@lognaturel @yanokwa This is a sort of layout I am proposing :
![img_20170314_220840_hdr](https://cloud.githubusercontent.com/assets/15019358/23911548/2b4dbae6-0903-11e7-8829-396c3b4691dd.jpg)

**Comment by lognaturel** [comment]
@supreme96 Thanks for sharing a sketch, that's very helpful! I think what you've drawn out could be a good incremental improvement. 

What I meant by rethinking it is that perhaps a smaller number of colors to choose from that are in a side-scrolling tray at the bottom or a toolbar that slides out from the side or ...? could be better than having a full color palette in a dialog. I think it would be good to look at other Android drawing apps and see if that sparks some good ideas.

That said, we could also start by making small changes to make the widget more usable. @yanokwa @nribeka what do you think? Maybe we shouldn't let perfect be the enemy of good and start with what @supreme96 has proposed?

**Comment by supreme96** [comment]
@lognaturel I also think that limiting the number of colors available would be a  good idea. Considering the purpose for which the feature is to be used limiting the number of available choices would simplify design.

**Comment by nribeka** [comment]
I agree with you @lognaturel, we should start small and make incremental changes to the widget. Allow limited selection would be a first good start and then adding breakdown of further enhancement as you get used to the widget code.

This ticket could be specifically just doing the "Set Drawing Color" update only instead of taking the broad update the widget as a whole.

We maybe then need to decide what limited selection are we going to allow? Maybe a set of primary colors from the [material color](https://material.io/guidelines/style/color.html) list? Should we consider folks that are partially color blind when determining the lists?

**Comment by lognaturel** [comment]
@supreme96 Ok, how about filing an issue specifically for improving colors? You can say it's a piece of this issue and refer to it. Then you can make another quick sketch with limited colors and taking into account some of @nribeka's suggestions!

**Comment by supreme96** [comment]
@lognaturel @nribeka Ok, I'll file a separate issue to narrow down our selection of colors. Meanwhile I will get into sketching a simpler layout.

**Comment by nap2000** [comment]
The current signature widget seems to have gone backwards from its previous capabilities.  The phone switches into landscape mode for signature but then only shows a small portrait style window within that to take the signature.  End results is that captured signature images are a lot smaller than the used to be and in portrait.  At least thats what it seems to me.  

If this is correct should I raise this as a separate bug or assume it will be addressed by this issue?

![device-2017-03-30-105506](https://cloud.githubusercontent.com/assets/1946349/24481654/91689e46-1537-11e7-87af-9a2e2116884a.jpg)

**Comment by lognaturel** [comment]
@nap2000 Strange, I wonder when that happened. Should be a separate issue, I think. That's something we should fix for the next version.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Can we close this one now?

**Comment by grzesiek2010** [comment]
Yes, I think so.
