### ISSUE TITLE
Autoplay option doesn't work

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2861]
#### Software and hardware versions 
Collect v1.19.0 and older versions

#### Problem description
During testing #2817 we discovered that `autoplay` option doesn't work.
It crashes on 1.19, 1.18, 1.17
There is no crash but it also doesn't work on 1.16, 1.15 ... 1.8 (we didn't check every version between but we can assume it doesn't work in all cases)

#### Other information 
@yanokwa I said that probably we can remove that option since it seems useless but you didn't agree.
I think I'm right... @mmarciniak90 was testing that option today and it doesn't work on all devices in the way I described above (sometimes crashes).

It crashes on three last versions but we have no crash reports. Today @mmarciniak90 caused firs appearances:
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5c5d46dbf8b88c29631622fc?time=last-seven-days&sessionId=5C5D2E4102EA00013CCDBAA626940E27_DNE_8_v2

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5c5d47acf8b88c2963163597?time=last-seven-days

additionally, no one complained about it (it doesn't work on 1.16, 1.15 ... 1.8 and probably older versions) so I'm pretty sure it's completely useless. 

The link you attached https://forum.opendatakit.org/search?q=autoplay%20order%3Alatest also shows only one question about that option during last three years.

Even if we want to fix that option for some reason keep it then it would require some discussion.
1. Should that play only media files attached to choices or the one attached to the question too?
2. What if we have multiple questions on one page and we use that option.
etc.

I'm not a fan of that option.

**Comment by yanokwa** [comment]
I tested autoplay of audio and video media text questions on Collect v1.19.0 and it worked for me on my Moto G5. I've attached the [form.zip](https://github.com/opendatakit/collect/files/2847385/form.zip).

I don't know how it behaves on multiple questions on one screen. Perhaps you can adjust my form, try it and report back?

I agree that it doesn't work on choices and it doesn't show up in the spec or in Collect's code. I think I did a fork of Collect that did sequentially play choices a few years back, but I don't think stock Collect needs that feature.

**Comment by shobhitagarwal1612** [comment]
The pull request is open. Please wait

**Comment by marichaf** [comment]
Hello, 

I am currently working on a project using ODK that requires all questions and answer options to have audio files attached. The respondents are adolescents, and there is a considerable incidence of illiteracy or semi-literacy in the population. The questions we are asking are sensitive and we don't want survey/surveyor bias, so we are using a self-administered, audio-enabled approach (ACASI). Autoplay would be great for this. I am not an experienced programmer, so when I finally figured out how to implement the autoplay function in the XLSform, it worked for a few questions but inevitably crashed in two different forms that used it. 

I'm sharing this detail just to underscore that this feature is NOT useless, it's actually very useful and would make the survey a lot more user friendly for the population and would help us collect better data. I'm sure I'm not the only one and this is not the only project that would benefit from having this feature fully functional.
 
It would be great to have both the question and answer choices be auto-playable. I understand it might be hard to implement with several questions on the screen or if the user taps any of the audio buttons before the autoplay is fully done. It makes sense to limit functionality to non-grouped questions. 

It would be great if you could support developing the feature so it works. I'm happy to help with testing. 

Thanks!
Maricha

**Comment by shobhitagarwal1612** [comment]
Hey @marichaf!
We already have a PR https://github.com/opendatakit/collect/pull/2863 which resolves this bug and a couple of related issues but it is a bit outdated.
You can try it out and see if that works for you. I would be happy to resolve the conflicts and spend some time on it if any of the reviewers could provide their feedback on the approach.

**Comment by marichaf** [comment]
Hi @shobhitagarwal1612, thanks for this. I've never tested unpublished versions so I'm having trouble trying to compile in Android studio to be able to run it and test it with my form. Can you share an .apk file so I can test it?

**Comment by marichaf** [comment]
Hi again @shobhitagarwal1612 . I was able to get and test this version, and it does indeed work for my survey, with a few caveats: it does crash when I have audio autoplay specified for a field for which there is no audio, which is a mistake in programming anyway, so once I cleaned that up it ran through without crashing. It also occasionally (it happened twice while I was testing) does not autoplay on seemingly random questions for which there is definitely an audio file (if I tap the audio button it plays, but doesn't automatically start when I initially swipe to the screen). But, for the most part, it does seem to work. I have multiple languages of audio in this survey and it also works for the other language options, which is great. 

Just one more thing, on my comment about this on the ODK forum, @grzesiek2010 and @lognaturel  asked what kind of functionality I would need for the autoplay. This version I've tested works only for single question, multiple choice screens, which is fine, but it does not autoplay the answer choices, which I do need.  Is there some way to accomplish both? Again, I'm happy to test and provide feedback.

Thanks!

**Comment by lognaturel** [comment]
Thanks so much for sharing your use-case, @marichaf! For future reference, the corresponding forum thread is https://forum.opendatakit.org/t/autoplay-eventually-crashes-survey/20621/5 

The current goal is to get audio playback and autoplay fixed for Collect v1.24 with tentative release in early October. It would be wonderful to get your feedback along the way to make sure that all ongoing issues have been resolved and that all of the functionality you need is available and crash-free.

**Comment by seadowg** [comment]
Hey @marichaf. I'm working on fixing this and it'd be really interesting to get a better sense of exactly how you'd expect autoplay in choices to work for your use case. Would you be able to post an XLSForm example of the form you were describing? I'm more interested in what you'd expect to be able to do so don't worry about making a form that actually works in Collect right now 🙂

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
For the moment it should like the features we're looking to support are:

* Audio on a question will play automatically when a user swipes to a page if the question has audio in the autoplay column
* If the question is a select with audio files attached to the choices they will play in order (after the question) when the question has audio in the autoplay column
* Returning to question will not autoplay audio again (autoplay only happens when moving "forward")

I think if anything else comes up we can create new features for them.
