### ISSUE TITLE
Improve server settings UI

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#287]
#### Software and hardware versions 
ODK Collect v1.4.12

#### Problem description
The server settings section in General Settings is confusing.

#### Steps to reproduce the problem
1. Go to general settings
2. Tap on 'Platform'
3. Select 'Other'
4. Tap on 'Configure platform settings', the heading says 'ODK Aggregate Settings' even though this is the configuration for the "Other" platform type.

---
1. Go to general settings
2. Tap on 'Platform'
3. Select 'Google Drive, Google Sheets'
4. Username and password are not relevant in this context but they're still displayed and can be set.

---
1. Go to general settings
2. Under server settings, Username and Password seem to be related to Google account but they are actually the same information configured in Configure platform settings. If the username and password are shown on this screen, the server they correspond to should be as well. Maybe the server, username and password can be displayed in a compact, non-editable way in General Settings with the `Configure platform settings` button right below.

#### Expected behavior
Some thought should be given to how the server information is presented and modified. It would be good to start with a proposal in this thread that the community can iterate on.

**Comment by IanUme** [comment]
I'll start with a proposal! I think under "Server Settings" we can have *Platform* and *Configure platform* settings always. If *ODK Aggregate* or *Other* is selected, *Username* and *Password* will show as it does now (with *Google account* hidden). If *Google Drive, Google Sheets* is selected, *Username* and *Password* will be hidden and only *Google account* will be shown. I don't have any accounts myself so I'm not sure the exact functionality but I hope I understood it correctly.

**Comment by lognaturel** [comment]
That sounds great! To be clear, I don't think it makes sense to have username/password/Google account editable in more than one place. I think what you're suggesting is to remove them from the _Server Settings_ configuration group and only showing them in _Configure platform_ which sounds good to me. That means the big change in addition to removing the three credentials fields will be adding _Google account_ under _Configure platform_ when the selected platform is _Google Drive, Google Sheets_.

To try all this out, you can use https://opendatakittrial.com / admin / aggregate for the Aggregate setup with auth and [this quick tutorial](https://nafundi.com/blog/posts/serverless-odk-deployments-with-google-apps/) to set yourself up to send data to Google sheets.

@yanokwa can you think of anything else that should be considered when looking at this?

**Comment by IanUme** [comment]
Thanks for the test account info @lognaturel! I wasn't even thinking about the duplicate entries for username/password! I like your idea except I couldn't understand what: 
> adding Google account under Configure platform when the selected platform is Google Drive, Google Sheets.

meant. If I select *Google Drive, Google Sheets*, I can already see the *Google account* (necessary to login) in the *Configure platform settings* page (Title of the page is "GOOGLE SHEETS SETTINGS").

**Comment by lognaturel** [comment]
I also don't understand. I'm sorry, it was late! Please ignore, you're absolutely right that it's already there.

As I've looked more deeply into this, I've realized that there's more there than I thought.

The main problem here is the duplicate authentication settings which is confusing. The reason that the auth settings were left on the settings view is a little surprising -- it's because those values can be used to automatically fill certain special form fields. You can see that in the comment [here](https://github.com/opendatakit/collect/blob/81f8038c0723c023d1e1dbf360dc0de41a913798/collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java#L70) and also in PropertyManager [here](https://github.com/opendatakit/collect/blob/81f8038c0723c023d1e1dbf360dc0de41a913798/collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java#L135).

The idea behind those fields is that they could be used to identify the particular person collecting the data. They should not match the server credentials which is often the same for a whole organization.

I think this issue no longer captures the actual problem and solution so I rewrote it at #311 with our deeper understanding. @IanUme would love your thoughts on that one.

**Comment by lognaturel** [comment]
I also added #312 to address the title of the "Other" platform settings screen. That one is also surprisingly tricky.
