### ISSUE TITLE
Google's Drive Auth API will stop working in Dec 2019

### ISSUE THREAD

**Issue by cooperka** [getodk/collect#2870]
Android's [Authorizing Android Apps guide](https://developers.google.com/drive/android/auth) has a warning at the top:

> This API is deprecated. Clients must migrate to the Drive REST API or another suitable solution to avoid disruptions to your application.

Given that the deprecated API is linked to from Collect's [README](https://github.com/opendatakit/collect#using-apis-for-local-development), I'm assuming this affects us. I wasn't able to find an existing issue discussing this so I figured I'd submit one just in case.

Can anyone confirm whether action needs to be taken?

**Comment by yanokwa** [comment]
Ugh. It never stops with these deprecations. And they don't give folks a lot of time.

**Comment by shobhitagarwal1612** [comment]
Aren't we already using the Drive V3 REST APIs?

**Comment by shobhitagarwal1612** [comment]
https://developers.google.com/drive/api/v3/about-sdk

**Comment by grzesiek2010** [comment]
In [the doc](https://developers.google.com/drive/android/deprecation) they said:
![Screenshot from 2019-03-13 13-10-15](https://user-images.githubusercontent.com/3276264/54277926-61821400-4591-11e9-8dcc-71cfe2e6866d.png)

I'm 99% sure it's ok but I don't have an access so @yanokwa you need to confirm.

When it comes to the code I investigated the [Google Drive Android API Migration](https://github.com/gsuitedevs/android-samples/tree/master/drive/deprecation) and the code used there looks like in our codebase. There is a helper class [DriveServiceHelper](https://github.com/gsuitedevs/android-samples/blob/master/drive/deprecation/app/src/main/java/com/google/android/gms/drive/sample/driveapimigration/DriveServiceHelper.java) like our [DirveHelper](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/DriveHelper.java)
comparing for example a method for listing files:
https://github.com/gsuitedevs/android-samples/blob/master/drive/deprecation/app/src/main/java/com/google/android/gms/drive/sample/driveapimigration/DriveServiceHelper.java#L121

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/DriveHelper.java#L288

They look simillar so probably we don't need to change anything.

@shobhitagarwal1612 sice you have worked on this please take a look at my conclusions.

**Comment by yanokwa** [comment]
@grzesiek2010 Thanks for checking! I agree that the code in Collect matches the example and I can confirm that we have an OAuth credential that Collect uses to access drive.files.[create,get,list] and others.

@shobhitagarwal1612 If you disagree with our conclusions, please re-open!
