### ISSUE TITLE
Add icon with action 'Zoom to saved feature' to all Geo widgets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2873]
#### Software and hardware versions 
Collect with #2865 

#### Problem description
`Zoom to saved feature` action was totally removed from all Geo widgets. 

#### Steps to reproduce the problem
Use case 1:
1. User opens one of the Geo Widgets with map
2. User selects a different location than the current location
3. User clicks on `My location` icon (even by accident)
4. User is moved to current location 
5. There is no easy way to back to saved location if it is different than current location. User needs to zoom out many times to see saved location

Use case 2:
1. User opens one of the Geo Widgets with map
2. User selects a different location than current location
3. User saves this answer
4. User opens the map again
5. User is moved to selected location
6. User clicks on `My location` icon (even by accident)
7. User is moved to current location 
8. There is no easy way to back to saved location if it is different than current location. User needs to zoom out many times to see saved location

#### Actual behavior
* There is no easy way to back to saved location if it is different than current location. 
* User needs to zoom out many times to see saved location

|v.1.19|changes from #2865  |
|---|---|
|<img height="50%" src="https://user-images.githubusercontent.com/3907554/52701780-4ebcf500-2f7b-11e9-8e15-bf401172e73c.gif">|![geowithchanges](https://user-images.githubusercontent.com/3907554/52701801-5e3c3e00-2f7b-11e9-8b18-8382d0beee49.gif)|

#### Expected behavior
We need to discuss possible behaviors.
One option could be adding an additional icon to `Zoom to saved feature` action.

**Comment by lognaturel** [comment]
There is now a button to do this.
