### ISSUE TITLE
./gradlew testDebug: failed test in PermissionsTest. permissionCheck 

### ISSUE THREAD

**Issue by wbagais** [getodk/collect#2874]
Software and hardware versions
Collect v 2.0, Android v 3.2.1, mac

### Description
after cloning the project, I tried to run the test command `./gradlew testDebug` in mac terminal, and I get below errors:

#### in Test Summary:
PermissionsTest. permissionCheck:

* java.lang.AssertionError: Expected permission android.permission.READ_PHONE_STATE is missing from AndroidManifest.xml

Stander error:

* No such manifest file: build/intermediates/manifests/full/debug/AndroidManifest.xml No such manifest file: build/intermediates/manifests/full/debug/AndroidManifest.xml

#### in AndroidManifest.xml code:
Missing URL
Ensure the URL is supported by your app, to get installs and traffic to your app from Google Search. Issue id: AppLinkUrlError
`<intent-filter> <action android:name="android.intent.action.VIEW" /> <action android:name="android.intent.action.EDIT" /> <action android:name="android.intent.action.PICK" /> <category android:name="android.intent.category.DEFAULT" /> <data android:mimeType="vnd.android.cursor.dir/vnd.odk.form" /> </intent-filter>`

#### in IDE Fatal Errors:
java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: List is empty.
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: List is empty.

What is the problem and how can I fix it?

**Comment by yanokwa** [comment]
Collect v1.2.0 is a very old version. Are you sure that's the version you are running?

**Comment by wbagais** [comment]
@yanokwa no the version is 2.0 January 2004

**Comment by yanokwa** [comment]
There is no Collect v2.0. Perhaps you are using a fork? Either way, we don't provide developer support for forks or code from 15 years ago, so I'm closing this issue.
