### ISSUE TITLE
Rotating the device on the Get Blank Form screen displays a connection dialog that never goes away.

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#288]
#### Software and hardware versions 
ODK Collect v1.4.12, Android v6.0.1

#### Problem description
Rotating the device on the Get Blank Form screen displays a popup titled "Connecting to Server" with text "Please wait a few moments" that stays on the screen forever.

#### Steps to reproduce the problem
1. Go to the Get Blank Form screen
1. Rotate the screen
1. Enjoy "a few moments" of waiting

#### Expected behavior
The list of blank forms should be persisted such that no network calls need to be made on device rotation. The dialog should not pop up.

**Comment by carstendev** [comment]
I'll take a look at this.
