### ISSUE TITLE
Starting a new form from the hierarchy view might be confusing

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2884]
#### Software and hardware versions 
All versions

#### Problem description
Starting a new form from the hierarchy view might be confusing. it happens when we are restoring data. 

#### Steps to reproduce the problem
1. Open any blank form
2. Kill the app
3. Open the same blank form [hierarchy view is shown]

I can see two improvements:
1. A dialog or a snackbar that shows a message about restored data.
2. Saving a form automatically when a form is being killed. Then we could open such a form from the list of saved forms.

**Comment by lognaturel** [comment]
I ended up opening up a duplicate at #3494. The other one has a little more detail so closing this one.
