### ISSUE TITLE
Destination phone number looks inactive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2887]
#### Software and hardware versions 
Collect master

#### Problem description
Destination phone number looks inactive

#### Steps to reproduce the problem
1. User goes to `Server Settings`
2. User selects `Select on send` or `SMS` in `Submission transport` options
3. `SMS submission settings` becomes active
4. `Destination phone number` is grey

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/52955163-4f46f880-338c-11e9-9b11-a331e2ad7b47.png">

#### Expected behavior
`Destination phone number` is black
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/52955213-64bc2280-338c-11e9-8a1b-7b53fde7ec0a.png">

**Comment by grzesiek2010** [comment]
We are going to disable sending forms via SMS temporarily so let's just leave it as is for now.

**Comment by grzesiek2010** [comment]
That option is not there anymore and Collect can't send messages automatically so we can close.
