### ISSUE TITLE
Remove 255 sheet limit in Google Sheet support

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2888]
#### Software and hardware versions 
Collect v1.9.x

#### Problem description
Google Sheets used to have a 255 column limit, but according to https://support.google.com/drive/answer/37603, that's been changed to a 5 million cell limit. We should confirm that the limit is actually gone (maybe the API still has the limit). 

If so, we should probably remove the 255 column limit in Collect and
1. warn users that if they have a campaign with more than 5 million cells, submissions will fail
2. or try to create a new sheet if we run into that limit

**Comment by grzesiek2010** [comment]
@yanokwa 
right the limitation seems to be removed. I tested a form with 1k questions and was able to send it to GS without any problems.
