### ISSUE TITLE
Trash button does not change to inactive when user removes all points via Backspace button in GeoShape widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2908]
#### Software and hardware versions 
Collect v1.20

#### Problem description
Trash button does not change to inactive when user removes all points via Backspace button in GeoShape widget

#### Steps to reproduce the problem
1. User adds one point to **GeoShape** -> Backspace and Trash buttons become active
2. User clicks on Backspace button
3. Trash button is still active

In the case when User clicks on the trash button in Point 2, both buttons become inactive

#### Expected behavior
Trash button is inactive

#### Other information 
Probably related to #2890 or #2902

**Comment by zestyping** [comment]
@mmarciniak90 Thanks for catching these!  They're both fixed in #2910.
