### ISSUE TITLE
`My location` button becomes active when user adds a point even if the location was not recognized in GeoShape widget 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2909]
#### Software and hardware versions 
Collect v1.20

#### Problem description
`My location` button becomes active when user adds a point even if the location was not recognized in GeoShape widget 

#### Steps to reproduce the problem
1. User opens the map on GeoShape widget
2. Location is not recognized - `My location`, `Backspace` and `Trash` buttons are inactive
3. User adds one point
4. `My location` button becomes active but when user clicks on it nothing happens 
5. `My location` button does not back to the inactive state when the point is removed

|![screenshot_2019-02-22-12-00-39](https://user-images.githubusercontent.com/3907554/53235546-64749d80-3692-11e9-916a-62f281b2ac21.png)|![screenshot_2019-02-22-12-00-43](https://user-images.githubusercontent.com/3907554/53235550-68082480-3692-11e9-9545-2611824919a5.png)|
|---|---|

#### Expected behavior
`My location` button is active only when the location is recognized

#### Other information 
Probably related to #2890 or #2902
The same behavior on Google and OSM Maps

**Comment by zestyping** [comment]
@mmarciniak90 Thanks for catching these!  They're both fixed in #2910.

**Comment by shobhitagarwal1612** [comment]
Closed in #2910
