### ISSUE TITLE
Add de-duplicate() function to remove duplicates from a list of values

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#292]
`de-duplicate()` is a function available in SurveyCTO that can be helpful to do things like generating random numbers without duplicates as described in [this mailing list thread](https://groups.google.com/forum/#!topic/opendatakit/bQ7y_fBxuwE).

@chrislrobert that would be a wonderful contribution when your team has a moment to help with the merge!

**Comment by chrislrobert** [comment]
We have a series of useful additions that we can share. Meletis will work on a PR that includes all of them (all in XPathFuncExpr.java). Martijn will argue passionately against every one, I suspect, as crazy, renegade, out-of-spec monstrosities, and he won't be wrong. They've been extremely useful for our users and you guys can decide which ones you want to adopt in ODK. Happy to also discuss other expansions to the custom-function set as there seem to be a few key omissions that hold people back from improving their forms.

**Comment by chrislrobert** [comment]
https://bitbucket.org/m.sundt/javarosa/pull-requests/10 has a bundle of our additions. Please feel free to take or leave as you wish. Hopefully everything is relatively self-explanatory. Everything in there has been tested and loved by hundreds and thousands of users.

**Comment by chrislrobert** [comment]
Sorry, note that the index() function performs dramatically better than position(..) for very large, complex forms. The reason is because it doesn't include a formal reference to ".." that triggers recalculations when ".." changes in some way. (We originally built index() to get the nearest repeat index conveniently, ignoring non-repeated groups -- so adding a non-repeated group wouldn't require changing position(..) to position(../..) -- but then the performance boost was a total surprise.)

Each function might need its own issue/discussion. Sorry for piling them all into the one PR and commenting here.

**Comment by lognaturel** [comment]
Thanks @chrislrobert and @meletis! It's great to have something concrete to look at and will help a lot with the conversations that need to be had. It also brings up great questions like what is the "official" version of (ODK?) JavaRosa, how much of an effort should be made to reconcile the now divergent versions, etc. More soon but in the mean time if anyone else (@MartijnR?) has high-level thoughts on the issues at hand, I think this is as good of a place as any to keep a record of them.

**Comment by MartijnR** [comment]
> Each function might need its own issue/discussion.

I agree. If there is a need for a particular new XPath function, I'd definitely be happy to share my thoughts on how these should work (without looking at any code). And of course, as Chris astutely predicted, I will probably

> argue passionately against every one, ... , as crazy, renegade, out-of-spec monstrosities, and ... won't be wrong

Haha

We, in this ecosystem, have 3 unique form engines in production now, and lots of clever people working on them. If the goal is to be one giant happy interoperable family, we should give people a chance to voice their opinion on any XForm spec additions, such as these. We may get something out of it. This would also help avoid the risk of breaking up, if that is indeed considered undesirable (it is by me). When I write this, I'm really thinking only of how poorly external data was added in the past and how to avoid this from happening.

ODK Developer forum is probably the best place to discuss these, not the ODK Collect (nor Enketo Core) repo.

pinging @spatialdude, @alxndrsn for their interest

**Comment by lognaturel** [comment]
I got a little caught up in the excitement of "here's a concrete thing we can do now!" filing this issue this morning. 🙃 It's now clear this is a big conversation with lots of pieces. @yanokwa has started talking to the various people who use JavaRosa about the state of their forks. He will move this discussion to the "official" ODK-JavaRosa repo when that's sorted. But for now...

For this particular functionality (`de-duplicate`) and eventually for the other functions in the SurveyCTO PR, it seems before any decision is made, it would be good to explore whether it can be achieved with existing ODK-JavaRosa-supported functions and/or whether some parts of the XForms spec not implemented by ODK-JavaRosa could be added to achieve it. I see that XPath 2.0 has [distinct-values](https://www.w3.org/TR/xpath-functions/#func-distinct-values) which operates on a sequence, for example. @MartijnR is that something you can comment on? I'm still drinking from the firehose so I may have a bad mental model of how the pieces fit together. If what I'm asking for doesn't make sense, let me know!

**Comment by MartijnR** [comment]
@lognaturel this is a great find! I'm in favor of adding distinct-values() exactly as specified in XPath 2.0.  

(If not the ODK dev forum, the ODK-XForm-spec repo would be a better place to discuss spec-additions than the javarosa repo imo, because it's the neutral place. People like me have nothing to do in the JavaRosa  repo because we don't use it).

**Comment by lognaturel** [comment]
@MartijnR Going to the XForms spec repo makes so much sense! I've refiled at opendatakit/odk-xform-spec#49 and we can continue the conversation there.
