### ISSUE TITLE
The additional point is recorded in Automatic mode after rotating device in GeoTrace widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2920]
#### Software and hardware versions 
Collect v1.20 - current master

#### Problem description
The additional point is recorded in Automatic mode after rotating device in GeoTrace widget

#### Steps to reproduce the problem
1. User opens GeoTrace widget 
2. User selects `Automatic recording` mode
3. User selects some interval, eg. 30 MINUTES
4. User starts recording
5. User sees at bar that one point was added
6. **User changes device orientation**
7. Point is added (if accuracy was acceptable) on every change of device orientation

#### Expected behavior
Point is added according to a defined time interval even if device orientation is changed

**Comment by zestyping** [comment]
Previously reported as #2646, then claimed as #2658, but not completed.

**Comment by mmarciniak90** [comment]
@zestyping thanks.
Closed as a duplicate.
