### ISSUE TITLE
PMD: Exclude the SingularField rule.

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2932]
This issue is developer-facing only.

I propose that we stop enforcing the SingularField rule.  This rule suggests that if a field is only used in one method, it could be a local variable inside the method instead of a field of the class instance.

#### Rationale

1. The message for this rule looks like:

    > Perhaps 'activity' could be replaced by a local variable.

    It doesn't make sense for a "Perhaps" suggestion to be enforced so hard that it breaks the build.

2. The field might be defined on the class because the author intended it to be meaningful as a member of the class, and so it makes the most sense to keep it there.

3. This rule can generate needless work.  It typically comes into force when a field is used in two methods, say A and B, and then method A is edited or deleted so that the field is used in only method B.  But it is quite possible that A will be edited again in such a way that it uses the field, or we might add another method C that needs to use the field.  In this situation, the rule has forced us to do extra work that only has the effect of making a future edit also require more work.  This situation arises, for example, in test classes as test methods are added and removed.

In some situations, this rule may motivate a helpful edit.  But overall it doesn't seem to generate much value and may even have negative net value, so let's consider turning it off.

**Comment by zestyping** [comment]
@yanokwa @cooperka Thoughts on this?

**Comment by cooperka** [comment]
I agree with all 3 points of rationale 👍 thanks for suggesting.

**Comment by SaumiaSinghal** [comment]
Hie @zestyping! I would like to work on this issue :)

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
I completely understand @zestyping’s irritation. When there’s a system design that’s being developed over several pull requests, this kind of intermediary state can be reached. 

However, I think we generally strive to get individual pull requests to “complete” states. The danger with leaving in-progress things like fields that don’t yet need to be fields is that if we don’t go back to them things are in a more confusing state. Also, fields for future functionality may not be sufficient for developers other than the original author to figure out the architectural next steps. I’d rather see some of that information captured in the issue for an upcoming feature. 

Given that @seadowg and I are against this change, I believe @grzesiek2010 was the one who added the rule in the first place and we’re the three who spend the most time in the code base, let’s close.
