### ISSUE TITLE
A repeatable group which is outside a regular group is visible as a part of that group in the hierarchy

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2936]
#### Software and hardware versions 
Collect v1.20.0

#### Problem description
A repeatable group which is outside a regular group is visible as a part of that group in the hierarchy

#### Steps to reproduce the problem
1. Open the attached form 
[groupTestNav.xlsx](https://github.com/opendatakit/collect/files/2936240/groupTestNav.xlsx)
2. Fill the form adding repeatable groups
3. Open the hierarchy view
4. Click on `Group 1`
5. The repeatable group is visible but it's not a part of `Group 1`

**Comment by cooperka** [comment]
Fixed in https://github.com/opendatakit/collect/pull/2876
