### ISSUE TITLE
Deleting the last group breaks the hierarchy if it's in nested repeats.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2942]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Deleting the last group breaks the hierarchy if it's in nested repeats.
Form: 
[groupTestNav.xml.txt](https://github.com/opendatakit/collect/files/2954419/groupTestNav.xml.txt)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3276264/54161669-2b3e7a80-4453-11e9-9235-1f09d721f2ff.gif)

**Comment by nap2000** [comment]
Deleting a repeat also does not seem to result in calculates that have count() of the number of repeats being updated.  Is this the correct behaviour or another issue with "remove group"

**Comment by grzesiek2010** [comment]
@nap2000 you are right, thanks for reporting. It's a separate issue so I filed it here https://github.com/opendatakit/collect/issues/3016

**Comment by nap2000** [comment]
Thanks @grzesiek2010 this one had been bugging me!
