### ISSUE TITLE
Geo: Accuracy threshold and collection interval in form definition

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2947]
(This item is moved here from the [ODK Geo roadmap document](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit#).)

Currently, the enumerator can set a GPS accuracy threshold when collecting points for a GeoTrace or GeoShape, e.g. they can set it so that only points with an accuracy value < 5 m are recorded.  They can also set a collection interval, e.g. collect a point every 10 seconds.

It would be useful if the form designer could configure both of these things in the form definition, for all the geo widgets, so that the enumerator doesn't have to choose them.  With such a capability, the form designer could set a consistent accuracy threshold and collection interval for a survey project involving many items of geographic data and many surveyors, and surveyor training could be simplified.

The name of the configuration parameters are yet to be determined.  The proposed design is that if the parameters are set, then the "Input Method" dialog is skipped and data collection goes straight to "Automatic" mode with the accuracy threshold and collection interval set by the form definition.

**Comment by danbjoseph** [comment]
I would be worried that someone might have a use-case where they are using more than one of the geo widgets and want the parameters for the different widgets to be set differently? Would they just not set it and fall back to the existing method of adjusting parameters? 

What column(s) would this be set with in the form definition?

**Comment by zestyping** [comment]
Hey @danbjoseph, sorry for the trouble—we decided it would be better to discuss this on the ODK Forum first rather than here on GitHub.  Would you mind moving your comment onto the [forum discussion](https://forum.opendatakit.org/t/geo-setting-an-accuracy-threshold-and-collection-interval-in-the-form-definition/18940)?

**Comment by polinistro** [comment]
I noticed this is an old tread, I was wondering if there has been a brakethrough in it. this discussios happened 2019. I really need a solution now

**Comment by seadowg** [comment]
@polinistro you can set a threshold using `capture-accuracy` as documented [here](https://docs.getodk.org/form-question-types/#geopoint-widget).

**Comment by lognaturel** [comment]
@seadowg is correct that point accuracy can still be set.

However, we haven't had a chance to prioritize this issue about lines and shapes yet. It's being tracked [on the forum](https://forum.getodk.org/t/geo-setting-an-accuracy-threshold-and-collection-interval-in-the-form-definition/18940). Consider adding more details about your needs and use case. 

The work that we have prioritized is on the roadmap at https://getodk.org/roadmap
