### ISSUE TITLE
Geo: Optimize zoom levels for walking surveyors

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2948]
(This item is moved here from the [ODK Geo roadmap document](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit#).)

Currently, the geo widgets zoom to level 16 when zooming to the phone's GPS location.

This isn't optimal because it's a bit too zoomed out to see the level of detail one would need when walking a line for GeoTrace.  Also, the zoom level is always reset to 16 even if the current view is more zoomed in.

The proposed change is:
- When zooming the view to the current GPS location, zoom to level 19 _unless_ the zoom level is already 19 or higher.
- When the user starts collecting a trace, zoom further to level 21 unless the zoom level is already 21 or higher.

These zoom levels work fairly well for enumerators collecting a trace at walking speeds.  Below the first image is at zoom level 19; at less than 19 it would be hard to identify the surrounding buildings and neighbourhood.  Below the second image is at zoom level 21; at less than 21 it would be hard to tell whether a point is on the correct side of the street, for example.  At level 21, it is easy to distinguish the collected points, shown as small red circles, which are ten paces apart.

Zoom level 19:
![2019-03-16 23-07-25](https://user-images.githubusercontent.com/236086/54482749-9c8c7d80-4805-11e9-84f2-c95038ace9bb.png)

Zoom level 21:
![2019-03-16 23-07-28](https://user-images.githubusercontent.com/236086/54482750-a0200480-4805-11e9-96c0-30afe51b9aa3.png)

**Comment by danbjoseph** [comment]
If a user starts collecting a trace, and zooms out (say from 21 back to 20), does the zoom level stay at the adjusted level as they continue to walk around and collect the trace? Or will the widget adjust the zoom at any subsequent time during recording?

**Comment by zestyping** [comment]
@danbjoseph Sorry again.  This is now over on the ODK Forum at [this discussion topic](https://forum.opendatakit.org/t/geo-optimizing-zoom-levels-for-walking-surveyors/18941).
