### ISSUE TITLE
Geo: Filter points by location provider (GPS, wifi, etc.)

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2949]
(This item is moved here from the [ODK Geo roadmap document](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit#).)

Currently, when using Google Maps, locations from any provider are used (GPS, wifi, etc.), but when using OSM as the basemap, only GPS locations are used.

It would be useful to be able to configure the geo widgets (by the user or in the form) so that only GPS locations are used, because non-GPS locations (wifi, mobile tower, etc.) are much less accurate.

Some discussion is needed here as to whether we want to just filter to GPS only, or also allow filtering to wifi only, and how to provide feedback to the user about the state of the filter and which provider is being used.

**Comment by danbjoseph** [comment]
I definitely don't think it should be restricted to GPS only. 

Can the phone independently use wifi (that is, without going through Google Maps)? What factors influence the accuracy of using wifi for location? It was my understanding that it depends on working within a Google app and letting them check wireless access points near you against their database of access points they've built from user data as people walk around and data as their street-view cars drive around?

**Comment by zestyping** [comment]
@danbjoseph Yes, in general, Android phones can use wifi for location even when Google Maps is not open.  It does check wireless access points near you, but apps can activate that function without using Google Maps.

Moving this discussion over to the [ODK Forum here](https://forum.opendatakit.org/t/geo-filter-points-by-location-provider-gps-wifi-network/18942).
