### ISSUE TITLE
Unable to use Range widgets.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2954]
#### Software and hardware versions 
Collect v1.20.x, Android v4.2-8.1.x.x, device used...

#### Problem description 
There is no way to use/open any of Rane widgets using hierarchy view or when swiping through the form. The error message is displayed: 
![Screenshot_20190320-084956](https://user-images.githubusercontent.com/33342488/54678903-59cced00-4b06-11e9-9625-0ed64f32e70c.png)

#### Steps to reproduce the problem
1. Open All wigdets form and hierarchy view
2. Choose Rage widget
3. Click on one of the Range widget from the list. 
gif of reproduction steps attached:
![range_widgets](https://user-images.githubusercontent.com/33342488/54679395-73baff80-4b07-11e9-9669-52cb0fa106ee.gif)

#### Expected behavior
User should be able to open and use Range widgets, error message should not be visible. 

#### Other information 
I used All widgets form.

**Comment by grzesiek2010** [comment]
It's an issue in Javarosa. I'm closing this issue in favor of https://github.com/opendatakit/javarosa/issues/410
