### ISSUE TITLE
Collect 1.20 does not include translations done a month ago

### ISSUE THREAD

**Issue by atl2017** [getodk/collect#2968]
#### Software and hardware versions 
Collect v1.20

#### Problem description: I did spanish traslations of strings below. Still are display in english.

![image](https://user-images.githubusercontent.com/29519901/54993771-a003cf80-4f90-11e9-8d6a-bf8ebe4a4e06.png)

**Comment by grzesiek2010** [comment]
Those strings were added in the last release (v1.20) so we have just started collecting translations https://www.transifex.com/opendatakit/collect/ and we will add them in v1.21.
