### ISSUE TITLE
Backward/Forward navigation buttons

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2971]
#### Software and hardware versions 
Collect v1.20.0 and older versions

#### Problem description
The buttons we use to navigate backward/forward in a form don't follow material design patterns.

| Current buttons  | [Material design](https://material.io/design/navigation/understanding-navigation.html#forward-navigation) | Proposed changes |
| ------------- | ------------- | ------------- |
| ![Screenshot_1553767828](https://user-images.githubusercontent.com/3276264/55149462-81493880-514a-11e9-816e-04ddb3f40d0c.png)  | ![mio-design_assets_1TTBgGW-7heSB1QEBEwuSv0PiAdPehSbc_forward-button](https://user-images.githubusercontent.com/3276264/55149537-a342bb00-514a-11e9-8de3-c45540d71500.png)  | ![Screenshot_1553767951](https://user-images.githubusercontent.com/3276264/55149465-84442900-514a-11e9-9fae-fed2bcbab96f.png)  |

Such a solution we can also use to add a progress bar in the future (I know it's difficult but it's a thing we discuss every once in a while):
![Screenshot_1553769000](https://user-images.githubusercontent.com/3276264/55150845-48f72980-514d-11e9-8782-0fe8a709f698.png)

@lognaturel @cooperka @shobhitagarwal1612 any thoughts.

**Comment by shobhitagarwal1612** [comment]
I like the solution that you're proposing. Is the position of the bottom bar fixed?

**Comment by grzesiek2010** [comment]
Are you asking whether it's always visible or always on the bottom?

**Comment by cooperka** [comment]
I'm in favor! :art:

**Comment by shobhitagarwal1612** [comment]
> Are you asking whether it's always visible or always on the bottom?

I'm asking, what happens if the question exceeds the screen height? Is content behind the buttons or on the same elevation?

**Comment by grzesiek2010** [comment]
> I'm asking, what happens if the question exceeds the screen height? Is content behind the buttons or on the same elevation?

it works in the same way as before, nothing is hidden.
