### ISSUE TITLE
Unexpected error when user opens 'Sample Form - Preloading'

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2972]
#### Software and hardware versions 
Collect v1.21.0 beta.0
[sample_preloading.zip](https://github.com/opendatakit/collect/files/3019015/sample_preloading.zip)
#### Problem description
Unexpected error when user opens 'Sample Form - Preloading'

#### Steps to reproduce the problem
* User opens form 'Sample Form - Preloading'
* Error appears
![Screenshot_2019-03-28-17-00-11](https://user-images.githubusercontent.com/3907554/55172903-182de900-517b-11e9-9d99-c79966cfdda3.png)

#### Expected behavior
* Form opens correctly
* I checked case on v1.20 and it works properly

**Comment by grzesiek2010** [comment]
Closed in favor of https://github.com/opendatakit/javarosa/issues/415
