### ISSUE TITLE
Geo widgets manual entry should support long press

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2975]
#### Software and hardware versions 
Collect v1.21.0.beta0

#### Problem description
As discussed in https://github.com/opendatakit/collect/pull/2933#issuecomment-470331413, manual entry of points can now be done through single-tapping. It was previously done with long press. I spent several seconds thinking the widget was broken when it didn't respond to my long presses so I expect this will trip enumerators up. Since it doesn't "cost" anything to also support long press, I think we should. This is especially worth doing since the single tap interaction may soon be replaced by panning the map (as discussed [on the forum](https://forum.opendatakit.org/t/placing-geopoints-by-dragging-the-map-instead-of-long-pressing/18389)). That means it's even less worthwhile for users to learn the new behavior.

CC @yanokwa @zestyping

**Comment by zestyping** [comment]
This makes a lot of sense.  Thanks, @lognaturel!
