### ISSUE TITLE
App is crashing when try to use Google Drive after canceling dialog when Shared with Me is chosen. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2977]
#### Software and hardware versions 
Collect v1.21.x, Android vx.x.x, device used...

#### Problem description
The app is crashing when try to use Google Drive after canceling dialog when Shared with Me is chosen. I've just encountered that by accident. 

#### Steps to reproduce the problem
1. Choose Server Type as Google Drive/Google Sheets and select Google account
2. Go to Get Blank Form 
3. Click on Shared with Me 
4. Cancel Dialog
5. Try to open folder select form from the list. 

#### Expected behavior
The app should definitely not crash. 

#### Other information 
gif of reproduction steps attached:
 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33342488/55225550-2d565680-5213-11e9-9253-fe139606f234.gif)

**Comment by grzesiek2010** [comment]
@kkrawczyk123 this pr fixes the issue https://github.com/opendatakit/collect/pull/2970

**Comment by lognaturel** [comment]
Closed by #2970
