### ISSUE TITLE
Unexpected prompt to add not-relevant repeat instances

### ISSUE THREAD

**Issue by cooperka** [getodk/collect#2992]
#### Software and hardware versions 
Collect v1.21

#### Problem description
As [discussed in PR #2990](https://github.com/opendatakit/collect/pull/2990#issuecomment-479600700), using the [hiddenRepeat.xml](https://github.com/opendatakit/collect/files/3040187/hiddenRepeat.xml.txt) form, stepping forward and backward results in unexpected prompts to add new instances of groups that are designated as `relevant="false()"`.

#### Steps to reproduce the problem
1. Step to a repeatable group that's not relevant
2. You're prompted to add a new instance

#### Expected behavior
You should not be prompted to add a new instance.

**Comment by chidauri** [comment]
Hi , i was trying this issue, what i see is that the relevance is considered after we have answered the prompt but it should be considered before(ideally) , am i right?

**Comment by grzesiek2010** [comment]
I added a fix on the javarosa side https://github.com/getodk/javarosa/pull/570
