### ISSUE TITLE
User should be informed then scanned QR code does not contain settings 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2993]
#### Problem description
User should be informed then scanned QR code does not contain settings 

#### Steps to reproduce the problem
1. User goes to `Admin Settings`
2. User goes to `Import/Export settings`
3. User clicks on `Scan code from other device`
4. User scans QR code which does not contain ODK settings

#### Expected behavior
* User is informed that QR code does not contain settings
* When user selects an incorrect file from SD card, toast is visible
![Screenshot_20190404-103532](https://user-images.githubusercontent.com/3907554/55542019-781a1780-56c6-11e9-9758-1d83ac0fe32f.png)

**Comment by iadeelzafar** [comment]
Did you mean instead of the currentToast text
We should replace it to
```QR code does not contain settings```

**Comment by andrewmlee** [comment]
Would this include all translations?

**Comment by lognaturel** [comment]
No, @andrewmlee, only the English string needs to be introduced in `strings.xml`. If you know languages other than English, you're encouraged to help translate in [Transifex](https://github.com/opendatakit/collect#contributing-translations), though! It takes about 24 hours after a merge for the source strings to get there. Thanks!

**Comment by devanshi7799** [comment]
@lognaturel is this issue open?

**Comment by lognaturel** [comment]
Hi @devanshi7799, yes it is! It would be a great one to get addressed.

**Comment by devanshi7799** [comment]
hello @lognaturel, i tried to scan QR codes which does not contain ODK settings. It does shows error message stating that it does not contain settings. 

devices used- vivo y51l and micromax HS2

**Comment by grzesiek2010** [comment]
Isn't this issue already fixed by this pr https://github.com/opendatakit/collect/pull/3422? @mmarciniak90

**Comment by lognaturel** [comment]
Ah, indeed, looks like #3421 was redundant.
