### ISSUE TITLE
Geo: Google Map and OSM use different location providers

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2997]
Currently, when using Google Maps, locations from any provider are used (GPS, wifi, etc.), but when using OSM as the basemap, only GPS locations are used.

This is inconsistent.  We should make the behaviour the same, regardless of the map SDK.

See related discussion: https://forum.opendatakit.org/t/geo-filter-points-by-location-provider-gps-wifi-network/18942

**Comment by lognaturel** [comment]
Aw, we had talked about this at some point but it drifted off the radar! Good to have an issue for it.

Related: #2717 #1460

**Comment by zestyping** [comment]
@lognaturel The full solution for #3241 should address this, too.

**Comment by lognaturel** [comment]
Closed in #3772
