### ISSUE TITLE
Checkbox state not saved on screen rotation

### ISSUE THREAD

**Issue by iadeelzafar** [getodk/collect#3001]
#### Software and hardware versions 
Collect debug build variant
Galaxy Nexus API 24

#### Problem description
Mark as finalized checkbox state not saved on screen rotation.

#### Steps to reproduce the problem
1- Go to Edit Saved Forms
2- Open a form and click on Go To End button.
3- Check the checkbox and  then rotate screen.
4- You'll notice that state is not being saved.
#### Expected behavior
State should be saved.
#### GIF:
<img src="https://user-images.githubusercontent.com/36811908/55673670-6f8f3000-58c4-11e9-820a-f4779b124014.gif" height="700" width="394">

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by martintrollip** [comment]
Hi, 

Is this still an issue? 

Failed to reproduce on `v1.24.0 beta.0-3-g237121bf0-dirty`

![rotate](https://user-images.githubusercontent.com/13981100/67041242-83460980-f125-11e9-94a6-06e9be6c550d.gif)

**Comment by devansh-299** [comment]
Cannot reproduce this , I think this issue can be closed

Collect v1.25.0
Android 9

**Comment by lognaturel** [comment]
Thanks, @devansh-299!
