### ISSUE TITLE
When Google Maps is used as mapping engine, don't render labels on top of offline layers

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3004]
#### Software and hardware versions 
Collect v1.21

#### Problem description
When offline tiles are used with the Google Maps engine, the default basemap labels are rendered on top which may conflict with elements in a custom basemap or layer.

See discussion at https://forum.opendatakit.org/t/behavior-of-offline-tiles-with-osm-vs-google-maps/18704

#### Steps to reproduce the problem
1. Set mapping engine to Google Maps in Settings
1. Add offline tiles - https://docs.opendatakit.org/collect-offline-maps
1. Note that labels are rendered on top of the offline tiles

#### Expected behavior
Labels should not be rendered on top of offline tiles.

**Comment by ChakshuGautam** [comment]
Hi, 
We have been using ODK for some of our Apps in [Samagra](https://in.linkedin.com/company/samagra-transforming-governance) and love the effort the community has put on this. I would like work on this issue as token of thanks for such a great project. Let me know if the issues is still available.

Thanks.

**Comment by lognaturel** [comment]
That is fantastic, @ChakshuGautam! Does Samagra use offline mapping? There are further improvements planned for geo features in Collect and you might consider sharing your needs and feedback on the threads at https://forum.opendatakit.org/search?q=geo%20category%3A9%20order%3Alatest.

I filed this issue thinking that offline maps weren't previously supported with the Google Maps engine but @zestyping mentioned in passing to me that he thought they were and that this behavior had existed for a while. I haven't had a chance to look into that. The first thing that would be super helpful is to check out an older Collect version (you can do that by checking out a tag such as v1.15.0), make sure you have [a maps API key](https://github.com/opendatakit/collect#using-apis-for-local-development) and report back on whether [offline tiles](https://docs.opendatakit.org/collect-offline-maps) work with the Google Maps SDK.

**Comment by chidauri** [comment]
Hi @lognaturel , i want to work on this, do i first need to check if offline tiles worked with older version, as you directed above?

**Comment by chidauri** [comment]
@opendatakit-bot claim
