### ISSUE TITLE
'Get account permission' dialog does not appear because of changing device orientation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3012]
#### Software and hardware versions 
Collect v1.18 (older versions were not verified)

#### Problem description
'Get account permission' dialog does not appear because of changing device orientation

#### Steps to reproduce the problem
Case1:
1. User goes to General Settings -> Server and sets Google Drive
2. User clicks on `Google account`
3. Permission dialog appears and user clicks on Deny
4. `Get account permission` dialog appears
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/55862693-41864600-5b79-11e9-854b-4157c578fbd2.png">

5. User changes device orientation
6. `Get account permission` dialog **disappears**

Case2:
1. User goes to General Settings -> Server and sets Google Drive
2. User clicks on `Google account`
3. Permission dialog appears and user changes device orientation and then clicks on Deny
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/55862739-595dca00-5b79-11e9-9bc4-78e940ee075c.png">

4. `Get account permission` dialog **does not appear**

#### Expected behavior
`Get account permission` appears even if user changes device orientation

**Comment by grzesiek2010** [comment]
All those additional dialogs work in that way, I think it's ok since it's just additional info and it's not that crucial we need to ensure it's displayed after rotating a device again.
I'm closing the issue.
