### ISSUE TITLE
Deleting a repeat does not result in calculates that have count() of the number of repeats

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3016]
#### Software and hardware versions 
Collect v1.21.0 and older versions

#### Problem description
Deleting a repeat does not result in calculates that have count() of the number of repeats.

The problem has been reported in this issue: https://github.com/opendatakit/collect/issues/2942#issuecomment-480468517

#### Steps to reproduce the problem
1. Open the attached form: 
[countRepeatTest.xml.txt](https://github.com/opendatakit/collect/files/3074617/countRepeatTest.xml.txt)
2. Ad a few groups (let's say 3).
3. Navigate to the last question which should show number 3.
4. Navigate back and remove one group.
5. Navigate forth - the number is still 3.

**Comment by lognaturel** [comment]
@grzesiek2010, can you please give a little bit of commentary when you pick up an older issue that's not part of the milestone so that we can have the context about why it's coming back up and when it should be reviewed?

**Comment by lognaturel** [comment]
I should add. ~For this specific issue, make sure to review https://github.com/getodk/javarosa/blob/master/dag.md#c---a-repeat-instance-is-deleted.~ I now see that the count expression is outside of the repeat so it's not related to that section. It would be good to also check against JavaRosa master.

Based on why this is coming back up, we can discuss when it should be prioritized.

**Comment by grzesiek2010** [comment]
Sorry, I know it's not the best approach but I was blocked with a few other tasks so I went through the list of existed issues.
The description here is not perfect in fact the problem occurs only if we delete the last group because then recalculation is not triggered. I created a draft pr based on my investigation https://github.com/getodk/javarosa/pull/572 so you can take a look.

**Comment by lognaturel** [comment]
Ahh, great. Sorry about the blocking and good to know that's where you're at! Picking up an old task is totally great, it's just helpful to have a little bit of context on why and what initial findings are.

**Comment by lognaturel** [comment]
Turns out this is a good time to take this because I have recently been in that code myself and can provide thoughtful review without needing to load a whole bunch of context back into my brain. 👍

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/getodk/javarosa/pull/572
