### ISSUE TITLE
Remove extra state and use Android APIs in activities with checkable lists

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#303]
`DataManagerList`, `FormDownloadList`, `FormManagerList` and `InstanceUploaderList` all host lists of items that can be selected or unselected with checkboxes. #300 aligns the behavior of their "toggle" buttons and increases code sharing between them. It would be good to see if more code can be shared between them and to review their use of state.

For example, `mToggled`, `mSelectedCount` and `mSelected` could likely be replaced by calls on [`getCheckedItemIds`](https://developer.android.com/reference/android/widget/AbsListView.html#getCheckedItemIds()). However, see [this comment](https://github.com/opendatakit/collect/pull/300#issuecomment-267835728) and #306 from @jwishnie -- this will require changing the way some items are IDed. 

<strike>[`getCheckedItemCount()`](https://developer.android.com/reference/android/widget/AbsListView.html#getCheckedItemCount()) would also be useful but it's only available in API 11+ so it might be worth waiting until #293 is resolved and the minimum SDK version is increased before doing this refactoring.</strike> Addressed by #471

**Comment by dcbriccetti** [comment]
This is getting near ready to go.

**Comment by dcbriccetti** [comment]
`FormDownloadList` needed very little work. Just removing an unused field and changing another field to a local variable.

**Comment by dcbriccetti** [comment]
This is ready for review and merging. This includes everything in https://github.com/opendatakit/collect/pull/475, which is also ready to go, so you may want to merge this and discard PR 475.
I should remind everyone that I am fairly new to Android, and may have made common mistakes. So if you’re risk-averse, or have a release coming or something, you may want to hold off.

**Comment by lognaturel** [comment]
Thanks! I'm starting the review now-ish. Next release isn't for another few weeks so it's a great time to shake things up. Plus, everyone is suddenly very interested in touching all the list-related classes so I think it will be easier to merge this and make incremental changes as needed.
