### ISSUE TITLE
Add more metadata to the audit log

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3036]
There is useful information about the form filling session that is not included in the audit log. If there are problems with a form filling session, that audit log information.

* Form name, version, ID -- this is already in the instance, but it would be nice to have in the log to keep that information together with the audit.
* Collect version, Android version -- useful to know if a form was filled with a buggy version of Collect
* Language change -- useful to know what the enumerator was seeing when filling out the form. Translation could have been bad.
    * See user request: https://forum.opendatakit.org/t/know-which-language-the-survey-was-administered-in/19154

There are some ongoing conversations about introducing a [virtual instance for metadata](https://forum.opendatakit.org/t/odk-xforms-spec-proposal-introduce-a-virtual-instance-for-metadata/19122/6) but feels separate from this implementation.

**Comment by lognaturel** [comment]
@yanokwa Can you move this to a forum features post, please?
