### ISSUE TITLE
The user should be notified that something is happening when re-evaluating the form takes time

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3039]
#### Software and hardware versions 
Collect v1.21.1 and prior

#### Problem description
When a user swipes from one question screen to the next, the whole form needs to be re-evaluated. This can take up to several seconds and currently the user has no feedback that something is happening. Additionally, user actions are still processed so it's common for a user to think they haven't swiped, swipe again, and then end up skipping a question.

#### Steps to reproduce the problem
Fill a form with lots of logic or big datasets. For example, [nigeria_wards_internal.xml.zip](https://github.com/opendatakit/collect/files/3113793/nigeria_wards_internal.xml.zip)

#### Expected behavior
Some kind of [progress indicator](https://material.io/design/components/progress-indicators.html) should be shown. User input should be ignored during processing.

#### Other information 
This is user-facing so perhaps it should be discussed on the forum but I wanted to make sure we had a record of the issue in the mean time since it has been bothering me for a long time. I don't think most users will care what the indicator is so it might just make sense for a developer who can take this on to make a proposal. I think a linear indeterminate indicator (https://material.io/design/components/progress-indicators.html#linear-progress-indicators) below the app bar is probably the most appropriate. This would interact with a possible overall progress-through-the-form indicator which has been often requested (and not done because it's confusing with skip logic and repeats).

**Comment by ghost** [comment]
Hey @lognaturel. I would love to work upon it.

**Comment by lognaturel** [comment]
Hi @geekRishabhjain! That's great. The first step is to think through different progress indicator options and positioning and to make a proposal, ideally with rough sketches (can be simple like a photo of a pencil and paper sketch). The proposal can be in a comment or in a linked Google doc. It should describe decisions in as much detail as possible -- how/if it would interact with different question types, why the specific indicator, why positioned where it's proposed, why the proposed color, etc.

**Comment by seadowg** [comment]
~~It could be that we can handle this by running the operations `FormSaveViewModel#saveAnswersForScreen` off the main thread and showing an indicator while we do so.~~

The above is wrong, but there are other "save answer for screen methods" that we might be able to hook this into. Ideally all the save logic would go through the `ViewModel` but that might be a whole thing.

Update: we'd want to look at `FormEntryActivity#saveBeforeNextView` I think. We should look into if we can replace that with something on `FormSaveViewModel` or alternatively just hook a progress indicator straight into that method.
