### ISSUE TITLE
Long-term fix for breaking change when openning instance upload list activity from external app

### ISSUE THREAD

**Issue by ekigamba** [getodk/collect#3040]
#### Software and hardware versions 
Collect v1.21.0, Android v7.0.0, Samsung SM T713

#### Problem description
Previously the form instance upload list page, called **Send Finalized Form** and displays a list of finalized forms for upload, could be openned using the following code:

```
 Intent surveyIntent = new Intent();
 surveyIntent.setComponent(new ComponentName("org.odk.collect.android", "org.odk.collect.android.activities.InstanceUploaderList"));
 surveyIntent.setAction(Intent.ACTION_EDIT);
 activity.startActivity(surveyIntent);
```
The new name for the activity is `org.odk.collect.android.activities.InstanceUploaderListActivity` thus external applications relying on this cannot open the page with version **v1.21.0** of ODK Collect 

#### Other information 

Suggestions on how to fix it:

1. Rename the integration in external applications
2. Rename the activity in ODK Collect
3. Add an action with a data type for openning the same activity

Each of the following suggestions has it's own 
- **amount of effort**
- **consequence to current users due to mismatching versions**
- **Sufficiency for providing a long-term fix**

Any other suggestion is welcome 😄 !!!

A long-term fix for the breaking change is required. The change made is in this PR https://github.com/opendatakit/collect/pull/2769/files#diff-2f6e2181f5fe37baca5afc44b6824d87R87

**Comment by grzesiek2010** [comment]
We should use the last option. Other activities we can run from an external app work in that way. You can take a look at https://github.com/grzesiek2010/collectTester

**Comment by ekigamba** [comment]
Thanks @grzesiek2010. Is there a way that we could have both the old and new way for users who have not updated ODK Collect?

**Comment by grzesiek2010** [comment]
> Is there a way that we could have both the old and new way for users who have not updated ODK Collect?

Can't you use the new name of that activity if the old one doesn't exist?

**Comment by lognaturel** [comment]
@grzesiek2010 The external API for the app should be stable. So sorry we didn't catch that change in review! 

I definitely think we should make the prior class name work as previous and issue a point release. We can also introduce an action and put external direct access to the activity on a deprecation path but then we need to communicate that with users somehow and give them time to change existing integrations.

**Comment by ekigamba** [comment]
That's a good idea @lognaturel.

How long(OR after how many releases) do you retain deprecated components before removing them?

**Comment by lognaturel** [comment]
@ekigamba We always consult with users of the feature when it's a deliberate deprecation (rather than an accident like this one). So in this case you and anyone else who uses that integration point could say what your constraints are. The goal is to give enough time for users to adapt as needed.

**Comment by ekigamba** [comment]
@lognaturel Thanks for this. I will communicate this and get back ASAP

**Comment by lognaturel** [comment]
@ekigamba I don't see any reason to deprecate anything at the moment. I think this is an issue of making sure all reviewers are on the same page about what constitutes the public API of the app. I've proposed #3045 to help make sure this kind of regression doesn't happen again.

**Comment by ekigamba** [comment]
Thanks @lognaturel
