### ISSUE TITLE
Store the server URL that was imported by QR code. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3043]
#### Software and hardware versions 
Collect v1.21.x, Android vx.x.x, device used...

#### Problem description
Only URLs that were introduced manually in General Settings/Server are stored in the drop-down URL list after using another server URL. User does not have to input the URL again, just choose it from the list, switching servers, when needed, is very easy and comfortable. 
When the server's URL is imported by QR code it is visible in the General Settings/Server right after import. But when you change it to default one or another introduced manually it is not visible on the drop-down URL list and to use it, the user has to input the URL manually again.

#### Steps to reproduce the problem
1. Introduce server URL on the one device, open Admin Settings, Import/Export Settings
2. On another device open Admin Settings, Import/Export Settings and Scan Code from the first device
3. Open General Settings/Server on the device on which you've just imported the settings, the URL introduced on the second device should be visible.
4. Click on URL, on displayed dialog use the drop-down arrow and change URL to another from the list. 
5. Click on URL again, imported server URL is not visible on the drop-down list.

#### Expected behavior
I think that imported URL should be stored on the URL list, as with Aggregate it is much easier to input manually the URL it is far more complicated with Central (nearly not possible at all). I think it might be a good idea to give users the opportunity to jump between Aggregate and Central without a must to scan the QR code every time especially when they are in the field and they do not have computers. 
Another good question is if the whole list of the URL used on 1st device should be stored on the 2nd or just the one used when QR code was scanned. 
@lognaturel @yanokwa @grzesiek2010 what do you think about that improvement suggestion?

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lovisgod** [comment]
HI @yanokwa @grzesiek2010 how can I contribute to this issue?

**Comment by lognaturel** [comment]
Welcome, @lovisgod! The first thing to do would be to make sure you can reproduce the issue with the description provided and that you understand the proposed solution. If not, you can ask questions here.

Please make sure you've read through [the contribution guide](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md) and when you're ready to claim the issue, you can comment with `@opendatakit-bot claim` to assign yourself to it.

**Comment by lovisgod** [comment]
HI, @lognaturel @grzesiek2010  I have forked the repo but confused which of the directories has the main project. Am thinking its the collect_app folder.
