### ISSUE TITLE
Update Collect icon to new specification by June 2019

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3047]
> We are introducing new design specifications for your app icons on Google Play. If you do not take any action by June 24, 2019, your app icon will be converted to legacy mode. Starting May 1, 2019, any new icons uploaded must meet the new guidelines. Visit your store listings for more information. 
> 
> More https://developer.android.com/google-play/resources/icon-design-specifications

**Comment by yanokwa** [comment]
@grzesiek2010 I think this might be a good fit for you.

**Comment by grzesiek2010** [comment]
Do we want a completely new proposal or only adjust the current one?

**Comment by lognaturel** [comment]
It would be good to start by adjusting the current one. 📋

**Comment by yanokwa** [comment]
I just uploaded the version that @grzesiek2010 did to the Play Store.

![odk-collect-icon](https://user-images.githubusercontent.com/32369/59227122-6a32b800-8b89-11e9-8c6d-c2ead9484c12.png)

**Comment by lognaturel** [comment]
How about attaching the source here so it exists somewhere if you are both riding on the same bus that gets hit? 🚌
