### ISSUE TITLE
Show that form updates are available with Google Drive integration

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3048]
#### Software and hardware versions 
Collect v1.21.2 and prior

#### Problem description
When the server is set to Google Drive, there is no indication that form updates are available.

#### Steps to reproduce the problem
Upload a form to Google Drive, upload it or its media, go to Get Blank Form and see that there is no indication of updates.

#### Expected behavior
The "This is an update to a form you have" message should show when updates are available.

#### Other information 
We should really consider abstracting away commonalities between the two download lists at some point.

**Comment by chidauri** [comment]
@opendatakit-bot claim

**Comment by chidauri** [comment]
Hi @lognaturel , when showing the files to user in the adapter we have access to `com.google.api.services.drive.model.File` which contains `getId()`, can this id be used to check if that form exists in formsdatabase or is that different id?

**EDIT.** Figured out that they are not same, i was thinking of doing this in the same way as `isNewerFormVersionAvailable()` does in DownloadFormListUtils.java with md5hash but for that we'll need to download forms, which is not feasible. So maybe we are left with using the name field and modified time field, but this is risky too i guess :P

**Comment by chidauri** [comment]
@grzesiek2010 would it be okay to use last modified time to indicate form updates in this case? since md5 is not available until we download the files.

**Comment by lognaturel** [comment]
Sorry we didn't get back to you on this, @chidauri! Yes, using the last modified time in this case is great since we don't get the same manifest as with custom servers.
