### ISSUE TITLE
Use git describe --tags --dirty as the versionName

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#305]
Currently, `versionName` is manually set in `build.gradle`. Instead, have it come from `git describe --tags --dirty` so that releasing a new version only requires creating a new tag and so that it is possible to track where non-release builds come from.

The `getVersionName()` method [here](http://stackoverflow.com/questions/17097263/automatically-versioning-android-project-from-git-describe-with-android-studio-g/24121734#24121734) should do exactly what is needed.

Since the version name will be very descriptive for non-production builds, the `versionCode` should be removed from the landing screen.

In non-production builds, the information after the tag should be on its own line. For example, if the latest tag is `v1.4.12`, and the result of `git describe --tags --dirty` is `v1.4.12-43-gdbd2bd7a-dirty` the title should look like 

```
ODK Collect v1.4.12
43-gdbd2bd7a-dirty
```

It's ok that it's cluttered because it will only affect developers. It should be possible to spilt the string on the first `-` to separate the two parts of the version. It is ok to assume that tags will not have dashes in them. 

For production builds, the title should look the same as it does now but with the build number removed.

**Comment by grzesiek2010** [comment]
I noticed there is a build number in the latest tag too. It looks like: v1.4.12_rev_1063-69-g04a53bb when i use git describe --tags --dirty. Won't the next tags contain that part or am I missing something?

**Comment by lognaturel** [comment]
Yes, you're correct that until now tags have included build numbers. Moving forward they will not, though. The implementation should assume that the tag is whatever is before the first '-' so it doesn't matter what the tag convention is.

**Comment by lognaturel** [comment]
To be extra clear -- it's ok that for the current state of the repo you get something more like
```
ODK Collect v1.4.12_rev_1063
43-gdbd2bd7a-dirty
```
The next release will be tagged as v1.4.13 and moving forward things will look more like what I described previously (without _rev_xxxx).
