### ISSUE TITLE
Crash when user opens selfie widget on Android 4.2 and below

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3051]
#### Software and hardware versions 
Collect current master 
Android v4.2 and v4.1

#### Problem description
Collect crashes when user tries to open `Selfie widget` or `Selfie video widget` on Android 4.2 and below

#### Steps to reproduce the problem
1. User fills `All widgets` form
2. User swipes to `Selfie widget` or `Selfie video widget`
3. Collect crashes

**Logs**
[crash4.1.txt](https://github.com/opendatakit/collect/files/3152726/crash4.1.txt)
[crash4.2.txt](https://github.com/opendatakit/collect/files/3152727/crash4.2.txt)

#### Expected behavior
* Collect does not crash
* User is able to fill mentioned widgets

#### Other information 
Discovered during testing #3038

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Android 4 is no longer supported.
