### ISSUE TITLE
Months in Myanmar calendar are not displayed on some devices

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3054]
#### Software and hardware versions 
Current master branch

#### Problem description
The problem has been reported here https://github.com/opendatakit/collect/pull/2662#issuecomment-491258283

Months in Myanmar calendar are not displayed on some devices. The only device we are able to use for reproduction is Infinix Race Bolt Q X451 device with Android 4.2.

![57524338-d1a9dd80-7327-11e9-8b05-fa0a48b396a1](https://user-images.githubusercontent.com/3276264/57557103-2aee2d00-7379-11e9-9f10-2d02b7b8b794.png)

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010! I would like to look into this issue. After doing some research on this, I found out that Android does support Unicode but for Android version lower than 4.3, the fonts included does not support all Unicode characters and the rendering does not take place for scripts of some language like Burmese. However, I was thinking that for lower Android versions, it will be better if the names of the Myanmar month are displayed in English language itself like Tagu, Kason and so on.

**Comment by grzesiek2010** [comment]
Hi @SaumiaSinghal 
using English language when those characters are not available is a good solution so please go ahead.

**Comment by SaumiaSinghal** [comment]
Thanks, @grzesiek2010! Yes, I am working on the same!

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
No longer needed because support for Android <5 will be dropped shortly (https://github.com/opendatakit/collect/issues/3624). Thanks for taking this on, @SaumiaSinghal!
