### ISSUE TITLE
Replace implementation of ListViewUtils.selectedItemCount with ListView.getCheckedItemIds()

### ISSUE THREAD

**Issue by jwishnie** [getodk/collect#306]
#### Problem description

In order to count the number of selected items in a ListView, [ListViewUtils.selectedItemCount](https://github.com/opendatakit/collect/blob/7848bba45c84e433ae1fd04be4b59ac5716f402e/collect_app/src/main/java/org/odk/collect/android/utilities/ListViewUtils.java#L13) inefficiently loops through the SparseBooleanArea returned by ListView.getCheckedItemPositions()

This could be replaced with a more efficient call to ListView.getCheckedItemIds() **but** ListView.getCheckedItemIds() only works if the ListView's underlying adaptor has [stable ids](http://stackoverflow.com/questions/18217416/android-what-is-the-meaning-of-stableids#18217552)

**NOTE:** Some ListViews used in ODK Collect _do_ have stable IDs and some do not. It appears that those that use a SimpleCursorAdapter are stable and those that use a SimpleAdapter are not.

I have not checked all the List activities, but the following are examples of one with Stable and one with Unstable IDs
- FormDownloadList (Unstable IDs), uses SimpleAdapter
- DataManagerList (Stable IDs), uses SimpleCursorAdapter

#### Steps to reproduce the problem
1. Set a break point in ListViewUtils.selectedItem()
2. Launch ODK Collect under the debugger
3. Select 'Get Blank Form'
4. Press 'Toggle All'
5. At breakpoint, set a watch for `lv.getAdapter.hasStableIds()`
6. *NOTICE:* Ids are not stable.
<img width="361" alt="formdownloadlist" src="https://cloud.githubusercontent.com/assets/62867/21370429/7ac70666-c6c0-11e6-8d11-3a0b303ffb11.png">

7. Continue program
8. From Collect main menu, select 'Delete Saved Form'
9. In either tab (with some forms present) hit 'Toggle All'
10. At breakpoint, observe watch for  `lv.getAdapter.hasStableIds()`
11. 6. *NOTICE:* Ids _are_ stable.
<img width="494" alt="datamanagerlist" src="https://cloud.githubusercontent.com/assets/62867/21370400/4ac520ba-c6c0-11e6-93a2-5045a89243a4.png">

#### Expected behavior
If all List Activities use List Views with adapters with stable IDs, we can use the more efficient calls.

**Comment by lognaturel** [comment]
Addressed by #471 but the information about stable IDs will be important for addressing #303.
