### ISSUE TITLE
I am using ODK to conduct a surevy. However I failed to upload in the ONA server. The problem I encountered says the following: b'ODK Validate Errors:\n>> Something broke the parser. See above for a hint.\nDependency cycles amongst the xpath expressions in relevant/calculate\n\nResult: Invalid'. Any help ?

### ISSUE THREAD

**Issue by alexo21** [getodk/collect#3069]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by akshay-ap** [comment]
Hi @alexo21 !! 
Forum would be the correct place to ask for support.
I would suggest you to post it in support section with detailed explanation.
Link: https://forum.opendatakit.org/.
