### ISSUE TITLE
Inappropriate 'Shared with Me/My Drive' button is visible if the user navigates to deeper directories

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3071]
#### Software and hardware versions 
Collect v1.21.0

#### Problem description
Inappropriate 'Shared with Me/My Drive' button is visible if the user navigates to deeper directories

##### Case1:
1. GoogleDrive is set in server settings
2. User goes to `Get Blank Form`
3. User clicks on `Shared with Me` button
4. User goes to some folder
5. **User sees `Shared with Me` button instead of `My Drive` button**
6. User goes to some folder
7. **User sees `My Drive` button**

##### Case2:
1. GoogleDrive is set in server settings
2. User goes to `Get Blank Form`
3. User goes to some folder
4. **User sees `My Drive` button**
5. User goes to some folder
6. **User sees `Shared with Me`**

![videogif](https://user-images.githubusercontent.com/3907554/57845041-76696680-77d1-11e9-9b75-a02966497c23.gif)

#### Expected behavior
If the user is somewhere in `Shared with Me` directory, the user should always have an option to move directly to `My Drive` directory

**Comment by SaumiaSinghal** [comment]
Hie @mmarciniak90, I would like to work on this!

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
