### ISSUE TITLE
Turn off the Checkstyle rule requiring a blank line before static { } blocks.

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#3075]
This is a developer-facing issue only.

Checkstyle currently enforces the following rule:

```
'STATIC_INIT' should be separated from previous statement.
```

This forces us to put a blank line before any `static { }` declaration.  For example, Checkstyle breaks the build for the following code:

```
    protected static final Map<String, String> STYLE_URLS = new HashMap<>();
    static {
        STYLE_URLS.put(GeneralKeys.MAPBOX_MAP_STREETS, Style.MAPBOX_STREETS);
        STYLE_URLS.put(GeneralKeys.MAPBOX_MAP_LIGHT, Style.LIGHT);
    }
```

It rejects the code because there is no blank line between the first line and the second line.

I think we should turn this off, because a `static { }` block commonly has the purpose of initializing a declared member, just as in this example where the purpose is to declare a constant `HashMap` populated with some constant values.  In this case, the `static { }` block should be grouped together with the declaration, because the declaration and initialization of this member should be treated as a unit.  It's unfortunate that Checkstyle would force us to write this code in a way that is slightly less clear as to its purpose.

**Comment by muarachmann** [comment]
Hi @zestyping i would love to take on this i see it concerns the following https://github.com/opendatakit/collect/blob/master/config/checkstyle.xml am i right? If guided i would love to give it an attempt thanks. Looking forward to your response

**Comment by SaumiaSinghal** [comment]
Hie @zestyping, I would like to work on this issue.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
