### ISSUE TITLE
Lines between points in geoshape hidden by offline map

### ISSUE THREAD

**Issue by nap2000** [getodk/collect#308]
The points are visible but the lines are hidden.

#### Software and hardware versions 
Collect v1.4.12 (1063), Android v6 device used: Samsung Note 4

#### Problem description
If you complete a geoshape question over the top of an offline map then the lines of the polygon will be hidden.

#### Steps to reproduce the problem
1. Add an mbtiles offline map to the phone. 
2. Create a form with a geoshape question.  
3. Attempt to answer the geoshape question over the top of the offline map.

#### Expected behavior
I'd expect to see the lines of the polygons and not just the markers indicating the points.

#### Other information 
None

**Comment by lognaturel** [comment]
Fixed by #309
