### ISSUE TITLE
Support persian calendar

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3084]
Some time ago one of our users asked  about supporting persian calendar:
https://forum.opendatakit.org/t/persian-calendar-available-for-odk/19256

There are some java libs we could to do that.

@lognaturel please consider it, maybe it could be added to v1.23

**Comment by lognaturel** [comment]
👍 Could you do a rough estimate of effort? Are there different lib options? Is there one with an API that makes adding it straightforward? Is it likely to have special cases like the Myanmar calendar?

**Comment by grzesiek2010** [comment]
In this case, we have many possible solutions.
I was able to find some project on Github like:
https://github.com/amirmehdizadeh/JalaliCalendar
https://github.com/razeghi71/JalaliCalendar
Both are created by just one person so I find it a bit risky to use and in case of any communication problems it might be difficult like it was in case of Myanmar calendar.

Another possible solution is ICU http://site.icu-project.org/
the problem here is that on android it's available from API 24 (Android 7) so in order to support older versions, we would need to add another dependency which is pretty heavy ~10mb

The last possible solution I found is:
time4j http://time4j.net/javadoc-en/net/time4j/calendar/PersianCalendar.html
it also requires a new dependency but in this case it like ~1mb
It requires API 21 (Android 5) so it's not perfect but acceptable.

**Comment by grzesiek2010** [comment]
To sum up, the last option looks like the one we should use.

**Comment by lognaturel** [comment]
I would lean towards one of the simple first two you've found. https://github.com/mohamadian/PersianJodaTime also seems worth exploring. https://github.com/JodaOrg/joda-time/issues/435 shares the reference paper it's based on. I like that it's just the Persian chronology and that it's based on Joda which is already a dependency.

I understand your hesitance about dependencies that are not very popular and only maintained by a single person. I think the Persian calendar is somewhat better documented so hopefully it won't be as problematic.

I'm not very excited about adding yet another generic date/time library. 1mb is quite big for a calendar if you consider the whole app was ~4mb before adding native mapping libraries!
