### ISSUE TITLE
Enable pitch and roll widgets in Collect, to supplement compass bearings

### ISSUE THREAD

**Issue by mitchellsundt** [getodk/collect#3088]
Originally reported on Google Code with ID 1063

```
What tool are you using?
ODK Collect 1045 (Device LG G2)

What is frustrating, troubling, annoying or lacking?

A new widget to record compass bearings was added to ODK collect in Oct 2013.
See:
https://code.google.com/p/opendatakit/source/detail?r=987078d8b2f6c9973b4b208000366b520bd149e1&name=default&repo=collect

From the above commit, the values for pitch and roll are also read from the device's
sensors (however these 2 values are //commented out in BearingActivity.java)

How would you like it to work?

Similar to the new 'bearing' widget, to have 2 new widgets for "pitch" and "roll  "bearing"
of type decimal, appearance="pitch" and "roll" which use
the device's g sensor to get readings of the orientation of the device.
```

Reported by `peterdcrees` on 2014-09-15 07:44:39

**Comment by mitchellsundt** [comment]
```
you write them, we'll add them into the mainline.
```

Reported by `mitchellsundt` on 2014-10-16 22:41:09

**Comment by florianm** [comment]
Observation on accuracy: We compared bearings recorded by the bearing widget on four identical Samsung Galaxy S2 tablets, and the bearing differed by more than 20 degrees between them. Our cheaper tablets don't have a compass built in.
We now use manual hand-held compasses ($10) with $100 Lenovo Tab3 tablets.

Side note 2: Our most accurate bearing & pitch measurement comes from laser rangefinders. Some of those have Bluetooth. The most effective integration for ODK Collect would be if ODK Collect would recognize the bt-connected laser rangefinder, and with one trigger pull of the rangefinder, would record distance, bearing and pitch in one go. If my colleagues decided to get one of those bt-enabled laser rangefinders, I could possibly act as beta tester for any kind of integration.

**Comment by lognaturel** [comment]
I'm going to close this for now since it's a really old feature request. Good point @florianm about being able to get much more useful results from specialized devices. If this is still a need you have, please write a forum feature request.
