### ISSUE TITLE
Verify the behavior of Google Sheets URL and update hint text

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#310]
Currently, the Google Sheets URL is used when there is no submission URL in the form. It's unclear what happens when that URL points to an arbitrary endpoint (Google Sheets or otherwise).

Manually verify the behavior of Google Sheets URL and update hint text accordingly.

**Comment by shouryalala** [comment]
@lognaturel @yanokwa May i take this up?

**Comment by yanokwa** [comment]
Hi @shouryalala! Yes, please try it out. You can find instructions at https://www.google.com/earth/outreach/tutorials/odkcollect_drive.html.
