### ISSUE TITLE
Values in audit file are mixed after updating form and changing audit options

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3100]
#### Software and hardware versions 
Current master branch

#### Problem description
The problem exists only if we upgrade a form disabling one of the options and we edit a saved form so it's rather a very rare case.

#### Steps to reproduce the problem

1. Create a form with tracking locations and changes in audit file.
2. Fill a form.
3. Upgrade the form disabling one option.
4. Edit the saved form.

**Comment by lognaturel** [comment]
Discussed in #3094 and decided not to fix because it's so unlikely. https://github.com/opendatakit/docs/issues/1054 is a docs issue to describe the behavior.
