### ISSUE TITLE
Text on GeoShape and GeoTrace  button is not changed when the answer is added

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3104]
#### Software and hardware versions 
Collect v1.22

#### Problem description
Text on GeoShape and GeoTrace  buttons is not changed when the answer is added

#### Steps to reproduce the problem
1. User clicks on the button `Start GeoTrace` or `Start GeoShape`
2. User adds a location
3. User saves answer
4. User is moved to view with the button `Start GeoTrace` or `Start GeoShape`
5. `View or Change Location` button is visible when the user moved to other questions and returns to it OR changes device orientation
 
| ![Screenshot_2019-05-28-13-38-18](https://user-images.githubusercontent.com/3907554/58475471-554c3280-814e-11e9-8b05-fc8de657d64f.png) |![Screenshot_2019-05-28-13-38-53](https://user-images.githubusercontent.com/3907554/58475480-5d0bd700-814e-11e9-93df-002fdd3446c7.png)|![Screenshot_2019-05-28-13-38-59](https://user-images.githubusercontent.com/3907554/58475487-6301b800-814e-11e9-9953-01363201057c.png)|
|---|---|---|

#### Expected behavior
* `View or Change GeoShape (GeoTrace)` button is visible

**Comment by grzesiek2010** [comment]
It would be good to agree on one universal title to avoid changing it when an answer is added. I remember that we have fixed a similar issue some time ago so it shows it's a tricky case and having a universal title would allow us to avoid such small bugs.

**Comment by zestyping** [comment]
@grzesiek2010 I agree that would simplify things!  For now, I've prepared a quick fix for your review in #3107.
