### ISSUE TITLE
Fail more gracefully when using Mapbox with non ARM devices

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3115]
#### Software and hardware versions 
Master, x86 device (emulator)

#### Problem description
On x86 device, loading a geowidget when Collect has the Mapbox SDK crashes Collect. It'd be good if it failed more gracefully.

#### Expected behavior
Maybe you can't select Mapbox if you are on an architecture that isn't supported. 

Or maybe instead of crashing we catch the exception and show some useful error message (Mapbox SDK isn't supported on your device). With this approach, it'd be nice if we also put some warning when people are changing the SDK. Warning people at that point seems like the best thing to do.

#### Other information 

I suggested an approach at https://github.com/opendatakit/collect/pull/3108#issue-282965295, but @zestyping knows this code better, so his approach at https://github.com/opendatakit/collect/pull/3108#issuecomment-496771401 is probably better.

**Comment by zestyping** [comment]
I've done a simple fix for this; just testing it now before I make a PR.
