### ISSUE TITLE
Clarify "other" platform settings 

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#312]
#### Software and hardware versions 
Collect v1.4.12

#### Problem description
In settings, when setting the platform type, "Other" is an unclear label. Also, when "Other" is selected, the screen shown after tapping on Configure platform settings has the title "ODK Aggregate Settings". Changing the username or password in Configure platform settings when the platform type is Aggregate also changes them for the Other platform type (the backing values are the same).

#### Steps to reproduce the problem
Go to "General Settings".

#### Expected behavior
"Other" is called "OpenRosa" and the username / password are not shared between platform types. On the Configure platform settings screen when the platform type is OpenRosa, I would expect a single title that says "OpenRosa Settings" (no second title "Other Platform Settings").

#### Other information 
`OtherPreferencesActivity` is currently implemented as a subclass of `AggregatePreferencesActivity`. Implementing this change would require separating them. The actual username and password backing values are also shared between the two platform types.

**Comment by lognaturel** [comment]
@yanokwa @batkinson Was the intent of "Other" really for it to be for OpenRosa endpoints or could it have been for non-compliant endpoints? I notice that for example Ona will direct their users to configure ODK Aggregate Settings. Do we know of deployments that use "Other" currently? Is there a conversation somewhere about the addition of the "Other" option?

**Comment by yanokwa** [comment]
The hope for Other was for folks who might not want to use /formList and /submission as endpoints. I doubt it is used at all, but I have no evidence.

One option is to move the /formList and /submission into ODK Aggregate settings and remove the Other option. If we want to be extra compliant, we'd then rename ODK Aggregate to OpenROSA.

**Comment by lognaturel** [comment]
Closing until we have a spec for this. I do think it's important.
