### ISSUE TITLE
The app is asking for permission even if it is not necessary

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3122]
#### Software and hardware versions 
Collect v1.18.0 (older versions were not been verified)
Android 6.0 and newer

#### Problem description
The app is asking for permission even if it is not necessary

#### Steps to reproduce the problem
1. Only the `Storage` permission is selected
2. The user turns on `Auto send`
3. User finishes form
4. The form is sent with success
5. The user turns off `Auto send`
6. User finishes form
7. User tries to send it
8. User sees permission dialog
9. User clicks on `Deny`
10. The form is sent with success

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/58795927-380ade80-85fc-11e9-9b48-3513da43f80e.png">

#### Expected behavior
The app is asking for permission only when it is required

**Comment by grzesiek2010** [comment]
It's not required but it's good to have it, you are right that forms will be sent with success even if the permission is not granted but then `Device ID` won't be added to the request, more info:
https://github.com/opendatakit/collect/pull/2387
https://github.com/opendatakit/collect/pull/2506

**Comment by lognaturel** [comment]
Ahh, yes, good call, @grzesiek2010. I know that in the normal path through manual submission, there's an explanation dialog that says why the permission is needed. Is it not shown in this case? Would there be a way to show it?

**Comment by grzesiek2010** [comment]
Yes, it's possible but in this case, we don't do that. I can't recall why but it's the only case when we request that permission but don't display the additional dialog so I'm pretty sure it was on purpose. Do you think we should?
