### ISSUE TITLE
Speaker, play, pause icons should be more clear in dark mode

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3123]
#### Software and hardware versions 
Collect v1.18 (older versions were not been verified)

#### Problem description
Speaker, play, pause icons should be more clear in dark mode

#### Steps to reproduce the problem
1. User sets `Dark mode`
2. User fills `Birds` form - [birds.zip](https://github.com/opendatakit/collect/files/3247268/birds.zip)
3. User sees page with `speaker, play, pause` icons

|![Screenshot_20190603-130006](https://user-images.githubusercontent.com/3907554/58798465-f3367600-8602-11e9-8e45-a530f0a81794.png)|![Screenshot_20190603-132212](https://user-images.githubusercontent.com/3907554/58798447-df8b0f80-8602-11e9-996c-b46936f3706f.png)|![Screenshot_20190603-132234](https://user-images.githubusercontent.com/3907554/58798456-e4e85a00-8602-11e9-80e1-c91310a032df.png)|
|---|---|---|

#### Expected behavior
* A good idea may be to change the background of icons

**Comment by grzesiek2010** [comment]
We need a broader discussion here. Those icons don't look good in the dark mode neither in the light. Some time ago I started investigating it and added my proposal https://github.com/opendatakit/collect/pull/2523

**Comment by seadowg** [comment]
I'm going to have a look at this. Did a session with a designer recently looking over the set of audio features we have and have a few changes/tweaks to make that hopefully fix this as well.

@opendatakit-bot claim
