### ISSUE TITLE
Results from select multiple questions might be converted to dates in Google Sheet

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3124]
#### Software and hardware versions 
Collect v1.22.0 and older versions

#### Problem description
Results from select multiple questions might be converted to dates in Google Sheet

#### Steps to reproduce the problem
Fill the form: [SampleQuestions.xml.txt](https://github.com/opendatakit/collect/files/3249008/SampleQuestions.xml.txt)
1. In the first question select options: 6, 2, 3
in the second question select options: 11, 7, 3

2. Finalize and send the form.

The result will be:
![image](https://user-images.githubusercontent.com/3276264/58826833-e4bb7f00-8641-11e9-946e-7bdfb237b5ca.png)

**Comment by grzesiek2010** [comment]
I can see a few options to resolve the issue:
1. Do nothing on the Collects side and ask users to change the format of their sheet from Automatic to Plain text (it won't fix already received answers).
2. Wrap each answer from select multi-question in quotes.
3. Convert answers from select multi-questions removing spaces after each comma:
`6, 2, 3` -> `6,2,3`

The last option would be my favorite but can we be sure it will work in the same way in the future? Maybe one day both `6, 2, 3` and `6,2,3` will be treated as dates.

@lognaturel what do you think?

**Comment by grzesiek2010** [comment]
Or another 4th and probably the best solution would be to set those formats automatically when a sheet is created. I'm looking at the API to check if it's possible.

**Comment by grzesiek2010** [comment]
Ok, I fixed the issue https://github.com/opendatakit/collect/pull/3128 and I think it's the best option.

**Comment by lognaturel** [comment]
For future reference, the forum post that prompted this was https://forum.opendatakit.org/t/strange-output-from-select-multiple-questions/19889
