### ISSUE TITLE
Autocompletion issues in v1.22

### ISSUE THREAD

**Issue by JeanBaisez** [getodk/collect#3132]
Hi all, here is an issue i just notice today:

#### Software and hardware versions 
Collect v1.22  

#### Problem description
Autocompletion work the first time but then if you go back to change the text, the autocompletion will display the same answer as before you change the text. 

For example i want to select a species from a list, i write the first letters of Vipera aspsis : vip... then on the next screen i can choose between a list of species starting by 'vip' which contain vipera aspis; But instead of selecting vipera aspis and going to the next screen, i decide to go back to change the specie name im looking for. I write 'pod' for Podarcis muralis and proceed to the next sreen. But instead of displaying some species name starting by 'pod' it's displaying the previous list of species starting by 'vip'.
 
#### Steps to reproduce the problem
try with my files

[espece.zip](https://github.com/opendatakit/collect/files/3257634/espece.zip)
[formulaire_adherent.xlsx](https://github.com/opendatakit/collect/files/3257636/formulaire_adherent.xlsx)

#### Other information 
i try the same form with odkcollect 1.21 and it work just fine

thanks for the help !

**Comment by lognaturel** [comment]
Thanks for reporting this, @JeanBaisez. I'm taking a look now.

**Comment by lognaturel** [comment]
Thanks very much for the detailed report and sample form, @JeanBaisez. I have a fix ready at #3133 and it should be released in the next couple of days.

If you are interested, I wanted to let you know that as of Collect 1.22, it's now possible to have logic within a single screen. That means you could avoid the quick appearance and instead have the kingdom (règne) and search questions on the same screen or even the kingdom, search and final selection questions on the same screen. Here's the modified form for you to try: [formulaire_adherent.xlsx](https://github.com/opendatakit/collect/files/3258721/formulaire_adherent.xlsx).

**Comment by JeanBaisez** [comment]
You'r welcome ! thanks a lot for this quick intervention and for upgrading my file with the knew features !

**Comment by lognaturel** [comment]
La version 1.22.1 a été publiée et devrait être disponible très bientôt. On préfèrerait éviter ce genre de problème mais si c'est pour arriver, on essaye au moins de réagir rapidement! 

@JeanBaisez Je vous invite à vous joindre au beta (https://forum.opendatakit.org/t/odk-collect-v1-22-beta/19767) pour pouvoir essayer vos formulaires vite fait avant la publication d'une nouvelle version.

Bonne collecte de données! 🚀
