### ISSUE TITLE
Filtered choice list using external csv fails in repeat in v1.22

### ISSUE THREAD

**Issue by mmoye** [getodk/collect#3135]
#### Software and hardware versions 
Collect v1.22, Android vx.x.x, Samsung tablet

#### Problem description
Using an external csv to filter choices only the first selection within a repeat is available. On 2nd repeat the original choice is used to filter values rather than a new selection. 

#### Steps to reproduce the problem
For example, within a repeat: 
Step 1 select category: fruit, vegetable, animal
Step 2 select type: apple, banana, orange [fruit]; carrot, potato, radish [veg]; cat, dog, rabbit [animal]

In 1st round of repeat user selects fruit and then apple. In 2nd round of repeat user selects vegetable, but choice are still apple, banana, orange. 

#### Expected behavior
Step 1 should filter step 2 with every new instance of repeat

#### Other information 
This process has been used for many past generations of ODK Collect. When we roll back to the previous version the repeat and filtering works as expected. This is definitely unique to the new release of v1.22.

**Comment by yanokwa** [comment]
Thanks for filing this issue, @mmoye!

@lognaturel Can you please review? This sounds like a regression and it'd be good to get it into the impending hot fix if possible.

**Comment by lognaturel** [comment]
Thanks, @mmoye! This is a symptom of the same problem #3132 describes. I just merged a fix for it and v1.22.1 should be out in the next few hours.

Thanks for filing the detailed issue. If you can, we'd also appreciate it if you could join the beta program as described in https://forum.opendatakit.org/t/odk-collect-v1-22-beta/19767 to help us catch some of these issues before they are released. We have an extensive manual quality assurance process in addition to some automated tests but with the range of what's possible in Collect, sometimes problems like this come up.

**Comment by mmoye** [comment]
@lognaturel @yanokwa Thanks so much for the hotfix!
