### ISSUE TITLE
Samsung S7 Rooted - Appcloner Crashes

### ISSUE THREAD

**Issue by keeshianicole** [getodk/collect#3140]
I just rooted my samsung S7, create clone on appcloner, but as soon as I created my app which is instagram, it crashes, it says Instagram has stopped close app.

Instagram version: 96.0.0.28.114
App Cloner: 1.5.19

**Comment by lognaturel** [comment]
Hi @keeshianicole! This is the repository for ODK Collect, part of [Open Data Kit](http://opendatakit.org/) for mobile data collection. For questions about other apps, please find their repositories!
