### ISSUE TITLE
Ignore require for notes

### ISSUE THREAD

**Issue by qlands** [getodk/collect#3162]
Variables of type Note should ignore if they are declared as required. Otherwise a survey cannot proceed because a Note cannot be filled

**Comment by grzesiek2010** [comment]
We don't have a special widget for notes it's just a `StringWidget` which is read-only. It doesn't make sense to make a question read-only and required at the same time, however, I agree we could handle it better.
Probably we should ignore require flag if a question is read-only. Do you agree @lognaturel?

**Comment by adrianocunha3000** [comment]
It is a feature! This behavior with "relevant" is useful for stopping using the form after some checks fail.

**Comment by lognaturel** [comment]
Thanks for chiming in, @adrianocunha3000. I've typically done what you describe with a combination of `relevant` and `constraint` on a read-only text field but I agree that using `required` is even simpler.

In general, I don't think we should exclude specific feature combinations, especially if they're allowed by W3C XForms. It's confusing to explain and can block useful techniques. Our form language is very powerful and one unfortunate side effect is that it is possible to express forms that don't make sense in a particular context. Forms need to go through testing anyway so hopefully all of these kinds of issues are caught before a form is published.
