### ISSUE TITLE
Remove custom handling for file types

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3173]
From https://github.com/opendatakit/collect/pull/3163

"For a rainy day / good first issue, some of the types that Collect matches against are handled by the Android type mapper. It would be great for someone to go through and remove custom handling for those, I think."

**Comment by seadowg** [comment]
This is in reference to [`CollectThenSystemContentTypeMapper`](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/http/CollectThenSystemContentTypeMapper.java) which has quite a lot of hardcoded extension to content type mappings that it could probably be deferring to Android.

**Comment by lognaturel** [comment]
Specifically, https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/http/CollectThenSystemContentTypeMapper.java#L34 has the custom map. The source for Android's `MimeTypeMap` is [here](https://android.googlesource.com/platform/frameworks/base/+/61ae88e/core/java/android/webkit/MimeTypeMap.java). All of the mappings that match can be removed from the custom map.

**Comment by seadowg** [comment]
I was worried that Android's version might not be the same for all the versions we support but it looks like from the log (https://android.googlesource.com/platform/frameworks/base/+log/61ae88e/core/java/android/webkit/MimeTypeMap.java) that it hasn't been touched for about 9 years.

It's probably worth checking once we've done this that "video/3gpp" still works on an API 16 device to make sure that the last changes made it in to Jelly Bean.

**Comment by chidauri** [comment]
Hi, i want to work on this issue(it really is rainy day here :P)

**Comment by seadowg** [comment]
@chidauri go for it! If you want to claim an issue have a look at [this guide](https://github.com/opendatakit/collect/blob/master/docs/CONTRIBUTING.md)

**Comment by chidauri** [comment]
@opendatakit-bot claim
