### ISSUE TITLE
Support offline filling and exporting

### ISSUE THREAD

**Issue by sunshine0576** [getodk/collect#3185]
When the network cannot be connected, import the form template locally and export Excel。

**Comment by lognaturel** [comment]
Hi @sunshine0576! You can use Briefcase to do this -- https://docs.opendatakit.org/briefcase-using/#pull-from-collect

If you have follow up questions or other support questions, please join the community at https://forum.opendatakit.org/. We'd love to read about you and your projects in [the introduction thread](https://forum.opendatakit.org/t/introduce-yourself-here/6671).
