### ISSUE TITLE
App updates must target Android 9 (API 28) by November 2019

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3189]
>Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.
>
>From August 2019, new apps must target at least Android 9.0 (API level 28).
> From November 2019, app updates must target Android 9.0 (API level 28).
> 
> https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by anilshatharashi** [comment]
Just raised a PR [here ](https://github.com/opendatakit/collect/pull/3315#issue-309561276)
