### ISSUE TITLE
Collect v1.23.0 crashes during filling form on Android 4.2

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3192]
#### Software and hardware versions 
Collect v1.23.0-beta.0
Android v4.2
The problem does not occur on v1.22.4

#### Problem description
Collect v1.23.0 crashes during filling form on Android 4.2

#### Steps to reproduce the problem
1. The user opens `All widgets` form
2. The form is loaded and the user sees the first screen
3. The user swipes to next question OR clicks on the icon to open hierarchy view

#### Expected behavior
User is able to fill form

#### Other information 
![Screenshot from 2019-07-05 14-58-07](https://user-images.githubusercontent.com/3907554/60723934-58002b80-9f35-11e9-9f4d-b85c0f1e4b88.png)
[crash.txt](https://github.com/opendatakit/collect/files/3362767/crash.txt)

**Comment by lognaturel** [comment]
Oh, how fun! This is because of the JavaRosa update which includes a `hashCode` implementation for `FormIndex`. The implementation uses `Objects.equals` which [was introduced in API 19](https://developer.android.com/reference/java/util/Objects).

It's great that we're catching this now because https://github.com/opendatakit/javarosa/pull/450 uses it as well. I'll make the change for both and we can update the snapshot.

**Comment by lognaturel** [comment]
The JavaRosa snapshot was just updated with https://github.com/opendatakit/javarosa/pull/455 that should fix this issue.

I'm not really sure when we should close an issue like this. I'd be ok with it being closed now if @mmarciniak90 verifies it with the snapshot. Alternately, we could wait until the PR with the actual JavaRosa 2.15.0 release. Please let me know which process you prefer and I'll try to follow it for all JavaRosa PRs.

**Comment by kkrawczyk123** [comment]
@lognaturel I have confirmed on the newest master that I am not able to reproduce the issue reported by @mmarciniak90. I have identified another crash and reported in https://github.com/opendatakit/collect/issues/3234 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
