### ISSUE TITLE
Instance subtext should be translated on the currently set language in Collect

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3195]
#### Software and hardware versions 
Collect v1.22.4 and older versions

#### Problem description
Instance subtext should be translated on the currently set language in Collect
it's the same issue as with forms https://github.com/opendatakit/collect/issues/3026 but here we want to fix instance subtext.

**Comment by lognaturel** [comment]
Let's go back to #1419 since it has a few more details.
