### ISSUE TITLE
Referring to node in secondary instance with path that also exists in primary instance can result in a dependency cycle

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3197]
Copied from https://github.com/opendatakit/javarosa/issues/449 so we don't forget to QA it.

#### Software versions 
All Collect versions

#### Problem description
A useful pattern with the `last-instance` feature is to accumulate values across instances. See [dont-show-options-selected-in-other-instances.xml.txt](https://github.com/opendatakit/javarosa/files/3336913/dont-show-options-selected-in-other-instances.xml.txt) for an example. That means referring to the same reference in the current instance and in the previous instance. JavaRosa incorrectly reports a cycle because `TreeReference`s don't take instance into consideration when compared for equality.

#### Steps to reproduce the problem
Try to parse the form above (e.g. by loading it in Collect). See the crash at https://github.com/opendatakit/javarosa/blob/59611cc0755dfbaf6631866ff15d6a9a516df704/src/main/java/org/javarosa/core/model/IDag.java#L473. The cycle reported involves the `previous_schools` node.

#### Expected behavior
No dependency cycle reported.

**Comment by lognaturel** [comment]
@mmarciniak90 The JavaRosa snapshot update should fix this.

**Comment by mmarciniak90** [comment]
**Verified on version**: 1.23.0 beta.2
**Verified on Android**: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

**I can confirm that:**
* It is possible to fill form `dont-show-options-selected-in-other-instances.xml `
* Error `Dependency cycles amongst the xpath expressions in relevant/calculate` is not visible while loading form (**visible on v1.22.2** , **not visible on v1.23 beta.0 as well**)
* issue #3192 is no longer visible

I'm not totally sure about behavior in mentioned form. It probably looks good but @lognaturel could you confirm?

| | |
|---|---|
| 1. Form filled for the first time | ![Screenshot_2019-07-18-15-38-58](https://user-images.githubusercontent.com/3907554/61462546-14fd7980-a973-11e9-8522-c6ade4f48386.png)|
| 2. Form filled for the second time | ![Screenshot_2019-07-18-15-39-13](https://user-images.githubusercontent.com/3907554/61462464-f5fee780-a972-11e9-905b-c31b113c6d99.png)|
|3. Form filled for the third time|![Screenshot_2019-07-18-15-39-29](https://user-images.githubusercontent.com/3907554/61462575-20e93b80-a973-11e9-89b8-6902b653ac06.png)|
|4. Form filled as a first is opened and **automatically updated** |![Screenshot_2019-07-18-15-39-42](https://user-images.githubusercontent.com/3907554/61462622-33637500-a973-11e9-87a6-5ce24455cbfe.png)|

**Comment by lognaturel** [comment]
Ah, yes, this form design trick doesn't work if you need to re-open saved forms. There's unfortunately not much we can do about that.

Also, this particular form is odd because there are three school questions but the constraint is only based on the last one. That's just because I was experimenting with different ways to show the constraint.

Thanks for the thorough check, @mmarciniak90!

**Comment by mmarciniak90** [comment]
@lognaturel thank you for the explanations.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
