### ISSUE TITLE
ODK Collect v1.22.4 - Spanish traslation in left tab is missed (Delete Saved Form)

### ISSUE THREAD

**Issue by atl2017** [getodk/collect#3199]
#### Software and hardware versions 
Collect v1.22.4, Android v9.0.1, device used. Huawei P10+

#### Problem description
Saved Forms is traslated in spanish as F. GUARDADOS

![image](https://user-images.githubusercontent.com/29519901/60856226-12a95b80-a1cc-11e9-80c8-8bd79b9f778b.png)

but in Collect -> Delete Saved Forms is displayed only as F. in portrait mode. It is Ok in landscape mode.

![image](https://user-images.githubusercontent.com/29519901/60856300-497f7180-a1cc-11e9-9b75-a1a243cf93e0.png)

#### Other information 
It was Ok in previous releases. Maybe we should reduce font size

**Comment by grzesiek2010** [comment]
I think it depends on the Android version? Are you sure it worked in previous versions well on the same device with the same Android version?

**Comment by atl2017** [comment]
I should verify with earlier version. How can download it?

**Comment by lognaturel** [comment]
Thanks for the detailed report, @atl2017! You can get older releases at https://github.com/opendatakit/collect/releases. v1.21 is at https://github.com/opendatakit/collect/releases/download/v1.21.2/ODK-Collect-v1.21.2.apk

**Comment by atl2017** [comment]
Sorry, I was wrong. It does not work with earlier version. 

v 1.18.1 had shorter traslation and works fine. I am going to change transifex back for this shorter string.
![image](https://user-images.githubusercontent.com/29519901/60924019-c9a5e580-a265-11e9-844e-44640e0594a4.png)

So there is no issue and it should be closed. Thanks @lognaturel @grzesiek2010

**Comment by lognaturel** [comment]
Thanks so much for following up, @atl2017! I just added you as a coordinator of the Spanish team in Transifex. You can mark the change as reviewed to make it so that only coordinators and managers can edit that string. I'd also recommend leaving a note about why it needs to be short so you or someone else remembers in the future.

**Comment by atl2017** [comment]
Thanks @lognaturel. I made comment and have checked as reviewed.
