### ISSUE TITLE
Refresh map icons

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3202]
~~Blocked by #4943~~

#### Software and hardware versions 
Collect v1.22.4 and older versions

#### Problem description
Icons in our map widgets don't look well, probably we should follow Google Maps design using circular icons.

| ODK Collect  | Google maps |
| ------------- | ------------- |
| ![Screenshot_2019-07-10-00-03-46](https://user-images.githubusercontent.com/3276264/60926311-67b9a000-a2a6-11e9-9e12-a24b67b90b7a.png)  | ![Screenshot_2019-07-09-23-59-22](https://user-images.githubusercontent.com/3276264/60926548-2aa1dd80-a2a7-11e9-8339-b9a9c601c738.png)  |

@seadowg if it's not in conflict with your work/plans I would do that.

**Comment by seadowg** [comment]
It does look like the map page could use a touch up although as far as I can see the icons themselves are actually Material (https://material.io/tools/icons/?icon=3d_rotation&style=baseline). 

To me it looks very much like the Google Maps example is using Floating Action Buttons (I'm sure you know them but here's the guidelines doc: https://material.io/design/components/buttons-floating-action-button.html). While I think it might be nice to move to a pattern more like this in future (perhaps even with an expanding FAB) I'd worry that changing it without first testing it out with users might make it more confusing for them - they could already have "learned" behaviors from the way it works right now. Does that make sense?

I'd vote for pausing this right now and seeing about a way to get feedback from users on that screen to see what we could improve.

**Comment by grzesiek2010** [comment]
> the icons themselves are actually Material

yes, I meant refreshing buttons not just icons.

> To me it looks very much like the Google Maps example is using Floating Action Buttons

No, there is no FAB there, just circular buttons.

**Comment by seadowg** [comment]
I'm not sure if they're using the Android component itself but IMO those buttons look like they fit into the [regular and mini FAB specs](https://material.io/design/components/buttons-floating-action-button.html#specs). 

I also noticed that the Material Design guidelines use Google Maps as an example of using multiple FABs for different actions: https://material.io/design/components/buttons-floating-action-button.html#usage. They annoyingly don't seem to have an example with the "mini" buttons at the top 😒.

**Comment by SaumiaSinghal** [comment]
Thank you @grzesiek2010 for directing me here. I proposed almost the same in my GSoC proposal. I opened a [topic](https://forum.getodk.org/t/use-floating-action-button-for-buttons-on-map-fragments/27499) for this in the forum. 

Also, I feel that using FAB would make it easy to distinguish between active and inactive buttons.
Disabled FAB button          |     Enabled FAB button
:-------------------------:|:-------------------------:
![WhatsApp Image 2020-06-19 at 12 34 47](https://user-images.githubusercontent.com/35730054/85106774-61f46a80-b22a-11ea-9f3e-2ede86915356.jpeg) |  ![screenshot_mapfragment_fab](https://user-images.githubusercontent.com/35730054/85106758-5c972000-b22a-11ea-81a9-5e3a6424c2ec.jpeg)

**Comment by seadowg** [comment]
Here's a quick spike on using Material 2 FABs for the buttons (on the selection map):

<img width="311" alt="Screenshot 2022-06-03 at 10 32 37" src="https://user-images.githubusercontent.com/556280/171828917-b9439682-1c11-400d-98cf-f91b74d93f92.png">

How does that feel to you @grzesiek2010?

**Comment by grzesiek2010** [comment]
> How does that feel to you @grzesiek2010?

Shape and size are great but I'm not sure if i like the color... (maybe I like just white more). What disabled icons would look like?

**Comment by seadowg** [comment]
> Shape and size are great but I'm not sure if i like the color... (maybe I like just white more)

Yeah @lognaturel had the same reaction. I think we should go ahead with it like this and then try both colours in the app to see how we feel. That way we can compare them while scrolling around the map etc.

> What disabled icons would look like?

Good question! I can definitely mock that up. I couldn't think of a case where we disable them though?

**Comment by grzesiek2010** [comment]
> I couldn't think of a case where we disable them though?

Maybe not in the map of forms but in geo widgets we do that:

![Screenshot_1654597579](https://user-images.githubusercontent.com/3276264/172358427-d4e9c8fb-5324-462c-b379-e93ba5a14768.png)
