### ISSUE TITLE
Investigate why a sleep is needed for Espresso test with minimal select in field list

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3203]
https://github.com/opendatakit/collect/blob/e1a726ef6ca5a9c95b4abd3569a04f97e3193c24/collect_app/src/androidTest/java/org/odk/collect/android/formentry/FieldListUpdateTest.java#L388 introduces a test over a minimal select in a field list. @grzesiek2010 said at https://github.com/opendatakit/collect/pull/3181#discussion_r300395916 that the spinner is not clickable immediately. Espresso should generally be able to handle that so there may be an issue with the implementation.

**Comment by seadowg** [comment]
@opendatakit-bot claim
