### ISSUE TITLE
Reorganize testing forms and media files

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3220]
#### Problem description
We are having more and more testing forms in the `assets` directory, it looks like:
![image](https://user-images.githubusercontent.com/3276264/61436332-d946bd80-a93a-11e9-959d-050b5c63af89.png)

in my opinion, it's kind of a mess and makes sharing media files difficult. I understand that it's important to have a separate dir eg for regression test but do we need that dir for assets as well?

Could we keep everything on one level or maybe in two dirs `forms` and `media`?

What do you think @lognaturel @seadowg @mmarciniak90 @kkrawczyk123

**Comment by mmarciniak90** [comment]
@grzesiek2010, I totally agree with you. We need to arrange this area. Especially, because the number of forms and media will grow up. Two dirs is a good idea.

**Comment by seadowg** [comment]
@grzesiek2010 I like the `forms` and `media` approach!

**Comment by kkrawczyk123** [comment]
Me too!

**Comment by lognaturel** [comment]
Works for me! I don't think there's any particular reason to separate forms into different directories. I'm pretty sure it's only like that because the `forms` directory was added after some of the earliest tests.
