### ISSUE TITLE
Add analytics for "jr:choice-name"

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3223]
> Do we have any metrics on how frequently jr:choice-name is used? I agree it is arguably a bit 'hacky', non-standard (hence jr:...) and, obviously, quite buggy... So if its not actually being used much then perhaps it is a good candidate to consider for deprecating?
-- https://forum.opendatakit.org/t/jr-choice-name-doesnt-give-a-value-when-called-from-inside-a-repeat-group/19619/20

The implementation will likely look like https://github.com/opendatakit/collect/pull/2406.

**Comment by grzesiek2010** [comment]
`jr:choice-name` is handled in javarosa and we in collect don't know if the returned value is a result of `jr:choice-name` or not, so it would be difficult to collect such analytics. Does that make sense?

**Comment by lognaturel** [comment]
Agreed with @grzesiek2010. The issue links to analytics put in for `current()` in a choice filter. We could only track that because we were only looking in the choice-filter context. `jr:choice-name` could be used anywhere a calculation is used so there's really no hook in Collect to identify that.
