### ISSUE TITLE
The scroll bar is missed on About view 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3226]
#### Software and hardware versions 
Collect v1.20.0 (I did not verify older versions)

#### Problem description
The scroll bar is missed on About view 

#### Steps to reproduce the problem
1. The user uses a device in the horizontal position
2. The user opens About view
3. The scroll bar is not visible on view

#### Expected behavior
The scroll bar is always visible when not all options are visible on view

#### Other information 
Discovered during testing #3207

**Comment by seadowg** [comment]
@lognaturel this feels like a nice candidate for moving to the UI project

**Comment by anilshatharashi** [comment]
Raised a PR for this here https://github.com/opendatakit/collect/pull/3268#issue-302989744
