### ISSUE TITLE
Error message displayed when try to fill fieldlist-updates submission. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3230]
#### Software and hardware versions 
Collect v1.23.x, Android 4.2, 4.4 5.1, 6.0 an 8.1, device used...

#### Problem description
Error message is displayed when try to fill fieldlist-updates.xml form submission. It is visible when user swipes to Save Form and Exit view or jump to the last question using hierarchy view. I have investigated a bit and the issue is not visible on version 1.22.0. It must have been introduced in 1.22.1 as I able to reproduce it on all release version till 1.23.2 and current master as well.
![Screenshot_2019-07-23-12-15-36](https://user-images.githubusercontent.com/33342488/61712812-73ea3680-ad57-11e9-97d5-bf694f5a9559.png)

#### Steps to reproduce the problem
1. Copy the form to sd/add and download from Google Drive/Aggregate
2. Fill the form, go to the last question and swipe to Save Form and Exit

#### Expected behavior
The error message should not be visible, the user should be able to finish the submission. 

#### Other information 
Form attached: 
[fieldlist-updates.xml.txt](https://github.com/opendatakit/collect/files/3422042/fieldlist-updates.xml.txt)
The interesting fact it is that after running FieldListUpdate espresso test, the issue is not visible.

**Comment by lognaturel** [comment]
I think this is because the last question in that form is now a question that accesses an external CSV. If you add [fruits.csv.txt](https://github.com/opendatakit/collect/files/3424307/fruits.csv.txt) to the media folder, that should fix it. The tests add the media file so I'm pretty sure that's why running them also makes the error go away.

**Comment by kkrawczyk123** [comment]
Thank you @lognaturel ! I don't know how I could miss that! I am closing the issue!

**Comment by lognaturel** [comment]
Not a problem, @kkrawczyk123! I filed https://github.com/opendatakit/collect/issues/3235 because the message is really not very helpful.
