### ISSUE TITLE
Mapbox offline vector mbtiles: fill is applied to all polylines, even ones that don't close

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3240]
#### Software and hardware versions 
Collect v1.23.beta-4

#### Problem description
Some layers in an mbtiles may include unclosed polylines. Because we don't have access to style information, all are currently filled.

[countries.mbtiles](https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries.mbtiles):

![mbtiles-fills](https://user-images.githubusercontent.com/236086/61822675-000b6500-ae0f-11e9-8015-49a4018272a4.png)

#### Steps to reproduce the problem
Put [countries.mbtiles](https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries.mbtiles) in `/sdcard/odk/layers`, open a geo widget.

#### Expected behavior
Since we have no way of knowing which polylines are intended to be filled and which aren't, don't fill any.

**Comment by zestyping** [comment]
This was closed by #3238.
