### ISSUE TITLE
Mapbox map fragment does not stop requesting location updates

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3241]
#### Software and hardware versions 
Collect v1.22+

#### Problem description
After opening a geo widget with a Mapbox basemap, location updates are requested until Collect is quit.

#### Steps to reproduce the problem
- Select a Mapbox basemap from the Maps settings
- Launch a geo widget
- Close the geo widget
- See on `logcat` and in the Android status bar that location updates continue

#### Expected behavior
Location updates should end when the geo widget is closed. Ideally location updates should also stop when Collect is paused or stopped.

**Comment by zestyping** [comment]
So far I've tried `                locationComponent.getLocationEngine().removeLocationUpdates(this);
` and `            locationComponent.onStop();` / `onDestroy();` and they haven't helped.

Hmm.

**Comment by zestyping** [comment]
Okay, a more complete fix is needed.  I discovered that location updates also continue indefinitely if you start the GoogleMapFragment, rotate the screen, and then quit the GoogleMapFragment.
