### ISSUE TITLE
Provide proper attribution for map tiles

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3251]
Collect makes available beautiful basemaps from a number of free web services. I just did some licensing due diligence and realized that we violate several:

- Carto: the [terms of service](https://drive.google.com/file/d/0B3OBExqwT6KJNHp3U3VUamx6U1U/view) state: "When using the Services, you must provide attribution to both OpenStreetMap and CARTO, as described at https://carto.com/attributions." It looks like it should be "© OpenStreetMap contributors, © CARTO"
- Stamen: from [the maps service landing page](http://maps.stamen.com/#toner), the attribution should be "Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>." 
- USGS: the [terms of service](https://www.usgs.gov/faqs/what-are-terms-uselicensing-map-services-and-data-national-map?qt-news_science_products=0#qt-news_science_products) state: "request that the following acknowledgment statement of the originating agency be included in products and data derived from our map services when citing, copying, or reprinting: "Map services and data available from U.S. Geological Survey, National Geospatial Program.""

**Comment by zestyping** [comment]
@lognaturel Oops, I didn't catch your self-assignment (or assign it to myself) before working on this.  Would you like to take over the PR in #3255?
