### ISSUE TITLE
Configure osmdroid to provide Collect User-Agent string to tile servers

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3252]
We are supposed to identify the Collect app to tile servers: https://github.com/osmdroid/osmdroid/wiki/Important-notes-on-using-osmdroid-in-your-app#set-the-http-user-agent-variable

**Comment by zestyping** [comment]
Putting it first (before `Dalvik`) seems reasonable.  I don't think we need to replace the app ID; I agree it's unusual but it also works well.  Just my two cents. :smile:
