### ISSUE TITLE
Basemap attribution text disappears on rotation and zoom for geopoint with maps and placement-map appearances

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3263]
#### Software and hardware versions 
Collect v1.23.0

#### Problem description
#3255 added attribution text for basemap options from sources other than Mapbox and Google. These basemap options are displayed by the osmdroid mapping engine. Rotating the screen or zooming in to the current location makes these disappear.

#### Steps to reproduce the problem
1. Select a basemap source other than Mapbox or Google in General Settings > Maps > Basemap source.
1. Open a form such as All Widgets on the default server with geopoint questions with appearance maps and placement-map
1. Tap on Start GeoPoint on one of those questions
1. Notice that the attribution text is in the lower right corner
1. Rotate the screen
1. Notice that the attribution text is gone
1. Tap the back button
1. Tap on Start GeoPoint
1. Notice that the attribution text is in the lower right corner
1. Zoom to current position

#### Expected behavior
Attribution text should always be visible as it is with the geotrace and geoshape question types.

#### Other information 
This looks like a lifecycle management issue that may go deeper than just this.

**Comment by nshestiuk** [comment]
@opendatakit-bot claim
