### ISSUE TITLE
Unable to open Get Blank Form list with Aggregate as Server and date with unicode characters

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3266]
#### Software and hardware versions 
Collect v1.23.x, Android 4.4, 5.1, 6.0, 7.0. 

#### Problem description
I have encountered a weird bug when performing regression testing. I had chosen the Spanish language in devices settings and tried to open Get Blank Form. I had default Aggregate in Server settings I saw an error message: 
![Screenshot (Jul 31, 2019 1_11_33 PM)](https://user-images.githubusercontent.com/33342488/62209128-019dd580-b399-11e9-86fa-825c54b1d230.png)

I started to investigate and these are the results that I have obtained:
- The error message was NOT visible when I changed the language to English in Collect or Devices Settings
- The error message was NOT visible when I changed the Date to 30th of July and to 1st August this year in devices Settings
- The similar error message was visible when I chose Date in Devices Settings to 29th February of 2020, I can't find any reason why 31th of July is any kind of suspicious date
- I tried with different languages, I was able to reproduce this error with Spanish, Polish, Arabic, Czech and Russian. Probably it occurs also for some other languages which name I don't know.
- I was NOT able to reproduce it on Collect 1.22.4 and 1.22.0
- This is the logcat:
`2019-07-31 12:25:33.831 4830-6253/org.odk.collect.android E/CollectServerClient: Parsing failed with Unexpected char 0xe9 at 2 in Date value: mié., 31 jul. 2019 10:25:33 GMT+00:00 while accessing https://opendatakit.appspot.com/formList
2019-07-31 12:25:34.029 4830-4830/org.odk.collect.android E/ViewRootImpl: sendUserActionEvent() mView == null`

#### Steps to reproduce the problem
1. Try today or change date in devices settings to 31th of July 2019
2. Set language in Collect or Device Settings Spanish/Polish/Arabic/Czech/Russian.
3. Try to open Get Blank Form

#### Expected behavior
I can't see any reason why the user should not be able to open Get Blank Form on 31th of July.

**Comment by yanokwa** [comment]
This was reported by a user to me via Facebook. Looks like the same issue. Just adding it here for historical purposes.

> If I'm using Collect with "device language" (Hungarian), I can not download empty form, because in hungarian we use " á, í, é, ó, ú, ő, ű" e.g.: July = Július or in short júl., and it throw an error message. "Form listing failed. Oarsing failed with Unexpected char 0xfa at 8 in Date value: Cs, 25 júl. 2019 07:26:52 GMT+00:00 while accessing...." Simple workaround if I change the Collector language to english.
