### ISSUE TITLE
Answers for multiple widgets are not remembered if user select it by clicking on icons

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3290]
#### Software and hardware versions 
Collect v1.22.0 (older versions were not verified)

#### Problem description
Answers for multiple widgets are not remembered if user select it by clicking on icons

#### Steps to reproduce the problem
1. User fills form [SelectTest3028.zip](https://github.com/opendatakit/collect/files/3471536/SelectTest3028.zip)
2. User starts filling questions with **multiple widget**
3. User adds answers by **clicking on the icons** (not the checkboxes)
4. User goes to the next question and returns to previous
5. User sees that question does not have answers

#### Expected behavior
Answers for multiple widgets are remembered even if user select it by clicking on icons

**Comment by lognaturel** [comment]
I know this wasn't introduced in v1.23.0 but we know we'll do another point release so it'd be great to get this one in.
