### ISSUE TITLE
Doubled : sign is visible on the bottom bar in the map in Spanish

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3291]
#### Software and hardware versions 
Collect v1.22.4 (older versions were not verified)

#### Problem description
Doubled : sign is visible on the bottom bar in the map in Spanish

#### Steps to reproduce the problem
1. The Spanish language is set on device or in ODK Collect
2. User opens GeoTrace or GeoShape widget
3. User adds point via **Automatic location recording** method
4. User sees the bar at the bottom with double `:: `
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/62535658-3eac1100-b84c-11e9-96b6-67f132409e12.png">

#### Expected behavior
: is not doubled

**Comment by grzesiek2010** [comment]
I fixed that string on transifex. It will be visible once we update strings.
