### ISSUE TITLE
Hyperlink to the sheet with a repeat group is not clickable

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3292]
#### Software and hardware versions 
Collect v1.23
Related to #3128 
Google Sheets

#### Problem description
Hyperlink to the sheet with a repeat group is not clickable
Value with a hyperlink to other sheet is preceded by a sign `'`.

![Screenshot from 2019-08-06 15-25-51](https://user-images.githubusercontent.com/3907554/62543605-820f7b00-b85e-11e9-959f-63797530688b.png)

#### Steps to reproduce the problem
1. User fills form: [repeatWithMedia.xml.txt](https://github.com/opendatakit/collect/files/3472409/repeatWithMedia.xml.txt)
2. User adds repeat group
3. User sends a submission to Google Sheet
4. Clickable URL is available for media but not for a sheet with a repeat group

#### Expected behavior
A hyperlink is always clickable

**Comment by lognaturel** [comment]
This feels like it should go in the point release.
