### ISSUE TITLE
Document current select implementations and the features and data sources they support

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3300]
There has been a lot of churn in the select implementations because behavior is inconsistent between the different variants. It would be helpful to take a step back, document existing behavior, make a deliberate choice about intended behavior, and implement all the changes. When we treat differences in behavior as bugs, we are more likely to miss problems like https://github.com/opendatakit/collect/issues/3297.

This is something @grzesiek2010, @seadowg and I have discussed. @grzesiek2010 will take the lead on producing the document. It should capture the range of existing behavior and limitations. For example, the "fast itemsets" data source can only be used with select ones. The `autocomplete`/`search` appearance (NOT the `search()` appearance/function data source) can't combine with `minimal`. The `minimal` appearance is slow because it uses a spinner, etc.

Once we have a complete picture of the current state of things, we can close this issue and file code change issues as needed.

**Comment by grzesiek2010** [comment]
I decided to create that document as a spreadsheet thanks to that it's more transparent and we can download and test it.
https://docs.google.com/spreadsheets/d/1uA6NeUbE51WACiKUjErFUxYFeJdGGWglNGKivuzei7I/edit?usp=sharing

As you can see there are lots of red marks what indicate an unexpected behavior (I didn't count but I would say that in ~50% of cases there is something wrong).
Many of the bugs are rather small and we could probably fix them easily but in my opinion, it's not the biggest problem and not the thing we should start from.
I think the main problem is that we have many various widgets, too many compared to appearances we want to support. It's difficult to keep all of them updated and ensure they support
all appearances we want. Removing some of them would make managing appearances much easier.

Here are my ideas:
1. `SpinnerWidget` and `SpinnerMultiWidget` (`minimal` appearance)- I've heard a few times that users would like to be able to use `minimal` and `autocomplete` appearances together.
It's not possible using the current implementation with those two classes. What about using a button+dialog (like in range widget) and displaying the same layout we use for normal selects. If we shared the same code we could get rid of `SpinnerWidget` and `SpinnerMultiWidget` and additional appearances that work with normal selects would work
with `minimal` as well. It would also solve the slow performance problem.
2. I'm not a fan of `GridWidget` and `GridMultiWidget` (`compact`, `columns-pack` appearances) I think users can achieve a similar result using `columns` or `columns-x` appearances.
The code would be shared, it would work faster and look better.
I tried to get rid of them implementing new select appearances a few months ago but @lognaturel  was skeptical back then, maybe now I'm able to convince you?
3. Appearances: `list`, `list-nolabel` and `label` could use just one widget, now we have two `ListWidget` and `LabelWidget` (the same in case of select_multiple). This case is special,
we don't need to support here appearances like `autocomplete` or `no-buttons` just `quick` in case of select_one.

Other things:
1. It's not possible to use select_multiple with external choices.
2. The hierarchy of Select widgets is pretty complex and it would require reviewing sample:
`SelectOneWidget` extends `AbstractSelectOneWidget` which extends `SelectTextWidget` which extends `SelectWidget` which extends `ItemsWidget`
3. Styling choices/questions/hints should take place in one place to avoid missing it in one of the widgets. 

Then at the and we should fix those small problems I mentioned at the beginning.

**Comment by lognaturel** [comment]
Thanks for doing this, @grzesiek2010. Here are a few thoughts for now.

Regarding your top 3 suggestions:
3 seems fairly isolated and a clear win so I think it's just a matter of filing an issue and making it so.

I'm going to have to keep thinking about 2. Some of those exist mostly for backwards compatibility.

Thinking more about 1, I realize that `minimal`/spinner is really intended for small lists of choices. It's with the addition of the `autocomplete` appearance that it would become viable for larger datasets and that performance would become important. I agree we should do this. I think hiding the spinner behind a button would not be minimal enough and that ideally it should behave like an autocompletetextview.

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@grzesiek2010 has done initial documenting. We need to triage into issues.

**Comment by lognaturel** [comment]
I think most of what was described at https://github.com/getodk/collect/issues/3300#issuecomment-528822082 is now done.

Some still remaining:
- appearances in red in [this test form](https://docs.google.com/spreadsheets/d/1uA6NeUbE51WACiKUjErFUxYFeJdGGWglNGKivuzei7I/edit?usp=sharing)
- list, list-nolabel and label could use just one widget
- select_multiple with external choices -- I don't think we should do this. Folks can use the `search()` appearance/function or external secondary instances.

Could you please update your spreadsheet, @grzesiek2010? Anything else?

**Comment by grzesiek2010** [comment]
Ok I'll review it.

> Anything else?

This maybe: https://github.com/getodk/collect/issues/4051

**Comment by grzesiek2010** [comment]
I reviewed that big form with various possible combinations and was able to to change some red cells to green so it works a bit better. No regression detected. The next step might be #4051 generally getting rid of the `ItemsetWidget` which exteds SelectOne widget and is created only to handle external choices what makes it difficult to work with minimal appearance since it would need to extend a differet widget.
We need to have one class/widget that would read choices no matter what source is used to avoid building separate widgets for different sources. We have different widgets for different appearances and that's enough.
