### ISSUE TITLE
Missing test coverage: AutoSenderWorker

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3307]
It's possible to create breaking changes in `AutoSendWorker` and it's dependencies without causing any tests to fail. 

In my (very up for debate opinion): It most likely makes sense for `AutoSendWorker` to be tested at a Robolectric level with non Android SDK dependencies such as `OpenRosaHttpInterface` mocked out.

**Comment by breakbusyloop** [comment]
If we do get Robolectric tests in place, it would serve to pin down the behavior while we refactor to expose smaller methods to cover in unit tests. The first refactoring I'd look at is the repeated checks for "google_sheets" as the upload target. It looks like there should be an interface and two classes for handling the specifics of each upload target.

**Comment by seadowg** [comment]
@OpenDataNerd that's a good spot. And I agree: getting some critical path tests around it is a great starting point in service of us pulling it apart 👍. If you want to take a look at this feel free to assign (you can send @opendatakit-bot a "claim").

**Comment by seadowg** [comment]
This is pretty out of date now. There is some basic coverage of auto send which is good but definitely more work to be done! Closing this as it doesn't feel like it needs tracked as an issue.
