### ISSUE TITLE
Verify that correct location provider is visible for Geo widgets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3313]
#### Software and hardware versions 
Collect v1.23 with #3309

#### Problem description
During testing #3309 I was wondering if the correct provider is visible for all Geo widgets.
I executed a few testes but precise verification is desirable.

#### Steps to reproduce the problem
* Internet connection is turned OFF.
* In Android location settings, `Device only` option is set

|Widget|Google Maps|Mapbox|OSM|
|---|---|---|---|
|Geopoint without map apperance|Using GPS|Using GPS|Using GPS|
|Geopoint with map apperance|Using GPS|Using fused|Using GPS|
|GeoTrace|GPS location accuracy:...|GPS location accuracy:...|GPS location accuracy:...|
|GeoShape|GPS location accuracy:...| GPS location accuracy:...|GPS location accuracy:...|

* Internet connection is turned ON.
* In Android location settings, `High accuracy` option is set

Results are the same as in the table above.

**Comment by grzesiek2010** [comment]
Dealing with providers seems fine but there is a problem with those strings...

In `GeoShape` and `GeoTrace` the message is hardcoded so it always starts with `GPS location accuracy:` and then we just add a value (`GPS location accuracy: %.2f m`)
In `GeoPoint` we use a different string `Using %1$s. Accuracy is %2$s m.` 

I think in all widgets the message should be the same (or at least as similar as possible). Does that make sense to display such a detailed message (about the provider)? I don't think that it's important for users and even might be difficult to understand for some of them.

What about displaying a message like: `Location accuracy is %s`?

**Comment by grzesiek2010** [comment]
@lognaturel you were off when I share my thoughts so you might have missed it. Anyway, when you are free please let me know what you think.

**Comment by lognaturel** [comment]
Using `Location accuracy is %s m` across the board sounds good to me. Using a string and making sure the value passed into it has two decimals will be an improvement over using the format string to get the right precision. Notice that we should include the units (m) in the translation string, though, so that it can be localized.

How about we do this in the beginning of v1.26 so the string has time to get translated before the release? Otherwise accuracy strings will be in English in a bunch of languages.

**Comment by grzesiek2010** [comment]
Ok I'll remove it form 1.25

**Comment by grzesiek2010** [comment]
Ohh I've just noticed there is another issue https://github.com/opendatakit/collect/issues/3324 
I though we can just display the accuracy but apparently there is someone who needs more information. We need to decide which direction is better.
