### ISSUE TITLE
Referring to node in secondary instance with path that also exists in primary instance can result in a dependency cycle

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3316]
### Software and hardware versions 
Collect v1.23.2
Problem is not visible in versions: from Collect v1.23.0 beta 2 to v1.23.1 

#### Problem description
Problem from https://github.com/opendatakit/collect/issues/3197

#### Steps to reproduce the problem
1. User starts form 
[dont-show-options-selected-in-other-instances.xml.txt](https://github.com/opendatakit/collect/files/3534212/dont-show-options-selected-in-other-instances.xml.txt)
2. User sees an error message: `Dependency cycles amongst the xpath expressions in relevant/calculate`

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/63589749-3d981500-c5aa-11e9-8d5b-3d5bba577724.png">

#### Expected behavior
User is able to fill the form

#### Other information

**Comment by kkrawczyk123** [comment]
**Description update:**
Behavior from 1.27.0 Beta 1:
![Screenshot_20200518-170838](https://user-images.githubusercontent.com/33342488/82229274-83f88580-992a-11ea-9d03-f37a814e3fec.png)

**Comment by lognaturel** [comment]
Fixed by getodk/javarosa#578
