### ISSUE TITLE
Repeat group dialog disappears after locking phone

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3322]
This started on the [forum](https://forum.opendatakit.org/t/add-new-prompt-desappears-after-unlocking-the-screen/21564).

#### Software and hardware versions 

Collect v1.23.3

#### Problem description

When prompted to add a repeat group, locking your phone (or navigating to another app) and then returning to the app shows a blank screen without the dialog prompt. You can swipe back and forward to be reprompted.

#### Steps to reproduce the problem

1. Start filling out a blank form with a repeat (an example: [why.xlsx](https://github.com/opendatakit/collect/files/3546228/why.xlsx))
2. When the repeat group prompt ("Add one more group?") appears press the home button or lock the phone
3. Return to the app

You'll just see a blank screen.

#### Expected behavior

I'd expect to still be prompted to add a repeat group (or not). The current situation could be very confusing, especially if you had locked the phone to deal with something else and then come back to it a few minutes later.

#### Other information 

It looks like the offending line of code is [here](https://github.com/opendatakit/collect/blob/4a8d2990cf5788e0b471455d5b192ca1cf68c377/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L2104). It would be intersting to know why we dismiss dialogs and if this weirdness could potentially be addressed with a redesign (I've noticed a discussion happened around this in #809).

**Comment by lognaturel** [comment]
It looks like the form entry activity was checked in with https://github.com/opendatakit/collect/commit/996093f7b0ffadd1e67bd14410759f3c32109a37 and doesn't have any explanation for the dialog dismissal. I would guess it was part of some boilerplate the activity was based on.

Repeats are a real pain point for users. There are many issues and forum posts making suggestions in various different directions.

@seadowg, I think that it would make sense for you to do some thinking about repeat UI in the near term. What do you think about making it the next big area of study and improvements after the current audio work gets to a stable place?

In particular, I'd like to have an answer for https://forum.opendatakit.org/t/change-prompt-when-adding-new-group-new-loop/20025 before v1.24 goes out and it would be really helpful to discuss options and how to validate them with you.

**Comment by seadowg** [comment]
@lognaturel Yeah I think that makes a lot of sense. We can discuss prioritizing the [UX Project](https://github.com/opendatakit/collect/projects/3) now we've got it populated and see if we think this goes next!

**Comment by seadowg** [comment]
Removing discussion due to recent research: https://github.com/seadowg/collect-design/blob/master/research/repeats.md
