### ISSUE TITLE
Provide more troubleshooting information for geopoint questions

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3324]
From @florianm at https://github.com/opendatakit/collect/issues/2008#issuecomment-428488422:

> location mode (is GPS even on), which location provider is used (Wifi? GPS? others?)

Is there other troubleshooting information to consider?

The first step would be to come up with a proposed UI. That is, does it just go below the satellite count? What's the exact wording that would most help users? Etc.

**Comment by florianm** [comment]
Thanks for following up!

How about a line underneath the satellite count:
"Location mode: {GPS+WiFi/WiFi/...}"
"Location source: {GPS/WiFi/Network}"

Can the Android location API tell:
*  the location mode ("high accuracy" / "low accuracy" etc)
* the currently polled location source (no answer from GPS, now trying WiFi)

**Comment by lognaturel** [comment]
Closing in favor of https://github.com/getodk/collect/issues/4718
