### ISSUE TITLE
Show two decimal points of accuracy in geoshape and geotrace top bar

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3336]
The geo question types that use maps show the accuracy radius of the current geolocation at the top of the screen. The geopoint question types show two digits after the decimal point but the geotrace and geoshape widgets only show one. They should show 2 because some hardware can get to cm-accuracy.

Reported by @ivangayton at https://twitter.com/ivangayton/status/1169948484042219522

![device-2019-09-10-155216](https://user-images.githubusercontent.com/967540/64656085-12535980-d3e3-11e9-820a-c70d5705a427.png)

**Comment by ivangayton** [comment]
Thanks Hélène,

I'd meant to make this request but hadn't found time!

For background: we are getting cm-precise Geotraces by using a UBlox ZED-F9P GPS chip on an ArduSimple board and Raspberry Pi Zero. Our documentation is still a work in progress but the basic idea is here: https://github.com/hcwinsemius/RTK_GNSS.

More to share in the coming weeks as we improve this workflow; at the moment it's still way too fiddly to recommend for production use (though I imagine there are a few people sufficiently motivated to get this kind of accuracy that they'll be willing to jump through the hoops).

![UBlox_geotrace](https://user-images.githubusercontent.com/5991943/64677780-cb5b7780-d467-11e9-81b1-2b88c7db396f.jpg)

**Comment by be-wake** [comment]
Can I do that?
I am new here.

**Comment by be-wake** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/opendatakit/collect/pull/3345
