### ISSUE TITLE
Relaunching Collect after minimizing gives different results

### ISSUE THREAD

**Issue by bognasoldev89** [getodk/collect#3343]
#### Software and hardware versions 
Collect v1.23.3 (store, release apk, master apk) Android 4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0

#### Problem description
During testing #3328 issue I stepped into some inconsistency. I was going through sets od settings and part of my testing suite was minimizing the app and relaunching it by the icon. And some of the Androids went back to the place where minimizing happened and the rest opened Collect on Main Menu.
I am aware of Don't keep activities option, it was off during all tests.
I am also aware that this can be an issue while building .apk and installing it on device, but I don't think the store version should be prone to this.

#### Steps to reproduce the problem
1. Open Collect and go wherever - start filling the form or go to settings
2. Minimize Collect
3. Relaunch Collect by the icon

#### Expected behavior
I expect that Collect would reopen exactly where it was (if this is possible of course, but I think it is in most cases). Or, at least, to be consistent - all versions back to the Main Menu.

#### Other information 
I tried to reproduce this issue for a few days on different versions:
1. 2019-09-12
-- store version - 4.2 got back to where it was; 4.4, 5.1, 6.0, 7.0, 8.1, 9.0 got back to the Main Menu
-- 1.23.3 release, 1.23.2 release, master - all Androids got back to the Main Menu
2. 2019-09-13
-- store version - 4.2 and 6.0 got back to where it was, 4.4, 5.0, 7.0, 8.1, 9.0 got back to the Main Menu
-- 1.23.3 release - all Androids got back to the Main Menu
3. 2019-09-16
-- store version - 6.0, 7.0 got back to where it was, 4.4, 5.1, 7.0, 8.1, 9.0 got back to the Main Menu

Yes, Android 7.0 mentioned twice is not a mistake, on the same day I had different results for the same device.

**Comment by grzesiek2010** [comment]
@mmarciniak90 @kkrawczyk123 
is it something you are able to reproduce?

**Comment by mmarciniak90** [comment]
@grzesiek2010 I was able to reproduce this issue or similar. 
I executed tests on the v1.26 Beta 1
I noticed this behavior on Android 6.0. I was not able to reproduce on Android 7.0, 8.1

Use case:
1. Start filling form
2. Minimize Collect
3. Relaunch Collect clicking on shortcut icon from 'desktop'
4. Collect opens exactly on the same page
5. Minimize Collect again
6. Relaunch Collect clicking on the icon from the application list
7. This relaunch opens Collect's main menu -> clicking device back button returns to form

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/76759759-a1736c80-678c-11ea-85c2-280895e4ca3c.gif)

`Don't keep activities` is turned off.

EDIT:
While testing another issue I noticed described behavior on Android 7.0

**Comment by grzesiek2010** [comment]
Could you check on the version from the store? I guess it's the same issue we have mentioned in [Troubleshooting](https://github.com/getodk/collect#moving-to-the-main-view-if-user-minimizes-the-app)

**Comment by mmarciniak90** [comment]
@grzesiek2010 mentioned behavior is noticeable on released version 1.30.1 but **only on Android 6.0.**
On Android 7.0, 8.1, 10.0, this behavior is not visible.
@kkrawczyk123 can you check this case on Android 5.1?

**Comment by kkrawczyk123** [comment]
@mmarciniak90 @grzesiek2010 I have verified the latest play store version on ma devices with Androids 5.1, 7.1 and 9.0 and I was not able to reproduce the issue on any of them.

**Comment by grzesiek2010** [comment]
If you were able to reproduce it just on one device and it's ot a serious bug let's close the issue.
