### ISSUE TITLE
Input method in geotrace and geoshape pop-up doesn't always adjust to vertical position of the device

### ISSUE THREAD

**Issue by bognasoldev89** [getodk/collect#3355]
#### Software and hardware versions 
Collect v1.23.3 Android v5.1, Huawei Y560-L01, 854x480

#### Problem description
I noticed this while testing #3345 and confirmed this on master and store versions.
Using Input method and choosing Automatic location recording checkbox is too large and the scroll bar doesn't appear.
I am not sure if this is an Android or resolution issue so I mentioned both.

#### Steps to reproduce the problem
1. Open geotrace or geoshape widget
2. Rotate device to a vertical position
3. Open Input method options

#### Expected behavior
I expect that there would be a scroll bar.

#### Other information 
Example:
![Screenshot_2019-09-18-16-53-06](https://user-images.githubusercontent.com/51324797/65160607-50c9c380-da36-11e9-8c8e-e2c58151b096.png)

**Comment by SaumiaSinghal** [comment]
Hie! I would like to work on this issue.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
