### ISSUE TITLE
When settings values are changed while filling a form, the new values should take effect immediately

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3356]
#### Software and hardware versions 
Collect v1.23 and prior though I think this worked as expected at some point.

#### Problem description
When the text font size is changed while a form is being filled, those changes don't take effect until the form is exited and the re-entered.

#### Steps to reproduce the problem
1. Open a form to fill
1. Tap the overflow menu, settings, user interface, change the font size
1. Tap back three times
1. Notice that the font size has not changed
1. Exit the form
1. Re-enter the form and notice that the font size has changed

#### Expected behavior
Font size setting should take effect immediately.

#### Other information 
Navigation type (swipe vs. buttons) takes effect immediately. I haven't looked in detail at other settings and when they apply.

**Comment by ScorchingShade** [comment]
I would like to work on that! I am fairly new to this so could I get some help knowing more about this issue

**Comment by grzesiek2010** [comment]
Hi @ScorchingShade nice to see you here. The steps seem very clear, could you tell us what you don't understand or which step?

**Comment by devanshi7799** [comment]
@lognaturel I want to work on this issue. 
If anyone is not currently working can i claim this?
Thanks :)

**Comment by chidauri** [comment]
hey @seadowg , if #3408 is inactive, can i take this issue up?

**Comment by seadowg** [comment]
@chidauri lets confirm that #3408 isn't still being worked on first!

**Comment by seadowg** [comment]
@chidauri the PR is closed now so feel free to claim

**Comment by chidauri** [comment]
@opendatakit-bot claim
