### ISSUE TITLE
Handle server custom response during submission

### ISSUE THREAD

**Issue by jnordling** [getodk/collect#336]
The OpenRosa form submission API response details a message response ( ).The issue is that ODK Collect does not handle/use/display the contents of the <message> tag. 

Currently Collect show standard messaging, which is totally fine. Just proposing adding the option if server is configured to response with detailed messages. 

    <OpenRosaResponse xmlns="http://openrosa.org/http/response">
        <message>Form Received! You've submitted 5 forms today</message>
    </OpenRosaResponse>

See this thread https://groups.google.com/forum/#!msg/opendatakit-developers/GOaPRgy4oNM/zWIQO6F-XZIJ where Mitch says that this is missing from ODK Collect. 

Also see https://groups.google.com/forum/#!topic/opendatakit-developers/hDnfWCUWSO0

**Comment by jnordling** [comment]
I am currently working on this, just wanted to add to issues list to keep track. I will submit a PR once tested.

**Comment by lognaturel** [comment]
I believe #194 is a duplicate, right?

**Comment by jnordling** [comment]
Yes! Sorry missed this Ill add my comments to that.
