### ISSUE TITLE
E/CollectServerClient: Parsing failed with ContentType: text/html; charset=utf-8 returned from: https://** is not text/xml.  This is often caused by a network proxy.

### ISSUE THREAD

**Issue by Yonkokilasi** [getodk/collect#3364]
#### Software and hardware versions 
Collect v02f3ab2, Android 9 , device used...

#### Problem description
E/CollectServerClient: Parsing failed with ContentType: text/html; charset=utf-8 returned from: https://** is not text/xml.  This is often caused by a network proxy.  Do you need to login to your network? while accessing https://** 
The stars are the link to where I fetch the forms from.
#### Steps to reproduce the problem
Just run the app and replace the default_server_url with your server url
#### Expected behavior
The app should load the forms.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
This sounds more likely to be an issue with your server or network connection. Does the default server work? What other servers did you try? Did you verify that you're not behind a proxy?

**Comment by Yonkokilasi** [comment]
Yes the issue was serves side on Kobo toolkit.
