### ISSUE TITLE
Settings pages have grey text on Android 4.x

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3367]
### Software and hardware versions 
Collect current version
Android v4.4, 4.2

#### Problem description
Settings pages have grey text on Android 4.x

#### Steps to reproduce the problem
1. The user goes to `General Settings` or `Admin Settings`
2. User sees that options headers and descriptions are grey

|master|1.23.3|
|---|---|
|![Screenshot_2019-10-01-14-59-43](https://user-images.githubusercontent.com/3907554/65960761-78b52000-e455-11e9-8724-00f66316c84a.png)|![Screenshot_2019-10-01-15-12-51](https://user-images.githubusercontent.com/3907554/65960974-e8c3a600-e455-11e9-94b1-79964eee5d0c.png)|
|![Screenshot_2019-10-01-15-00-05](https://user-images.githubusercontent.com/3907554/65960762-78b52000-e455-11e9-8f52-b3aebc7645b6.png)|![Screenshot_2019-10-01-15-13-02](https://user-images.githubusercontent.com/3907554/65961010-fa0cb280-e455-11e9-80de-b8243660d5a0.png)|
|![Screenshot_2019-10-01-14-59-35](https://user-images.githubusercontent.com/3907554/65960763-78b52000-e455-11e9-911a-a1e1bce0df26.png)|![Screenshot_2019-10-01-15-13-10](https://user-images.githubusercontent.com/3907554/65961044-0d1f8280-e456-11e9-8feb-224db9454de3.png)|

#### Expected behavior
Settings pages have black text

**Comment by seadowg** [comment]
This looks like it could be because we're now closed to the system theme for settings. We can probably be more specific with the color in some way though.

**Comment by lognaturel** [comment]
I tend to think that this is ok. The background is also paler by default so it's not hard to read. If someone has free time to address it, great, but I think it's low priority. I've marked it as `help wanted` in case a new contributor wants to take a look.

**Comment by shldhll** [comment]
@lognaturel I would like to work on this issue.

**Comment by seadowg** [comment]
Hey @shldhll. Our [contributing guide](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md) explains how to claim issues and our review process. Have a look at that before you get started!

**Comment by shldhll** [comment]
@opendatakit-bot claim
