### ISSUE TITLE
Invalid question is not highlighted in red on the field list on Android 5.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3368]
#### Software and hardware versions 
Collect v1.23.3
Android v5.1
Device: Huawei Y560-L01

#### Problem description
Invalid question is not highlighted in red on the field list

#### Steps to reproduce the problem
1. The user fills a form with the field list with validation  
[OnePageFormSubmission.xml.txt](https://github.com/opendatakit/collect/files/3676763/OnePageFormSubmission.xml.txt)
2.  The user puts invalid answers
3. The user tries to go next/finish the form
4. The user is moved to the field list, sees toast but an invalid question is not highlighted on red

#### Expected behavior
Invalid question is highlighted on red

**Comment by grzesiek2010** [comment]
Ther is a similar issue https://github.com/opendatakit/collect/issues/2235
@mmarciniak90 maybe the device you are using has animations turned off?
It's the only way I can reproduce the issue.
Please go to Developer options and disable:
- Window animation scale
- Transistion animation scale
- Animation duration scale

then restart your device and check the attached form.

**Comment by mmarciniak90** [comment]
Thanks, @grzesiek2010. I'm not able to say for sure but it is very likely that animation was turned off. 
Now, when I'm sure that aminations are turned on, I do not see this issue.
