### ISSUE TITLE
CSV attachments not uncompressed

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3369]
#### Software and hardware versions 
Collect v1.23.3; probably since the okhttp change

#### Problem description
Central's default install [configures nginx](https://github.com/opendatakit/central/blob/75f11f18b6d697a73b025b46a9d0e7f6e2e5f0c0/files/nginx/odk.conf.template) to gzip files larger than 1.2mb. Collect should uncompress these on receiving them but doesn't.

Reported at https://forum.opendatakit.org/t/odk-central-corrupts-large-csv-media-files/22365

#### Steps to reproduce the problem
1. Set up a form with a media attachment > 1.2mb on Central or any other server configured to gzip large files
1. Download the form
1. Fill it out and notice the attachment is corrupt

For a specific example, configure Collect with
![collect-settings](https://user-images.githubusercontent.com/967540/65986095-0c77f380-e438-11e9-9aff-2f9d571cbf89.png)

Download the form CentralTest19c, jump to the "Select the Field Officer" question. You can also pull the CSV from `/sdcard/odk/forms/CentralTest19c-media`, change the extension to zip and verify that it can be successfully unzipped.

#### Expected behavior
The attachment should be unzipped.

**Comment by lognaturel** [comment]
I'm unfortunately not going to have time to look at this in the next several days. @seadowg, since you've looked at the networking code most recently, could you please investigate? It'd be great to have a fix for v1.24. I see that there are tests for a gzipped body but maybe not for gzipped individual attachments?

**Comment by seadowg** [comment]
@lognaturel I can look at this tomorrow 👍

**Comment by lognaturel** [comment]
Thanks to @issa-tseng for looking at the server side. It seems to be a Central problem.

I was convinced the issue was due to the okhttp change but really, it would have been surprising for no one to have run into it yet given the size of forms and media attachments out there.
