### ISSUE TITLE
Ensure leak canary is enabled for the debug build or remove it

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3373]
According to https://github.com/opendatakit/collect/issues/3366#issuecomment-537500260, Leak Canary is not enabled for the debug build. It should either be or should be removed entirely.

I think it's been helpful in the past and would be good to enable for the debug build.

Todos:

- [x] Confirm with @opendatakit/testers what the problem described at https://github.com/opendatakit/collect/issues/3373#issuecomment-538491186 is
- [ ] File issues for all currently identified leaks
- [x] Document Leak Canary usage in the readme and/or contribution guide

**Comment by grzesiek2010** [comment]
This pr https://github.com/opendatakit/collect/pull/3370 has enabled it but today I heard from @mmarciniak90 that it's a big hassle so I would remove it. We can enable it in the future once we have time to investigate reported issues instead of having it enabled all the time.

**Comment by lognaturel** [comment]
Got it -- that makes sense, removing `TestCollect` from the debug manifest means that `Collect` is used instead which enables Leak Canary. I didn't realize that this was a side effect of the PR when reviewing.

Can you or @mmarciniak90 say more about what makes it a hassle? I'm not immediately seeing any issues with master but I also don't have the LeakCanary app installed. Is it that it is actually identifying leaks (perhaps #2716?)?

**Comment by grzesiek2010** [comment]
I haven't tested it after merging #3370 but @mmarciniak90 said that she was receiving many alerts/messages and it was even closing or crashing the app so it was a problem during testing.

> Is it that it is actually identifying leaks (perhaps #2716?)?

right.

**Comment by lognaturel** [comment]
@mmarciniak90 Do you have the Leak Canary app installed? Maybe the thing to do is to file issues for the problems it flags and then uninstall it unless specifically looking for leaks?

**Comment by shobhitagarwal1612** [comment]
I can confirm that LeakCanary is enabled for debug builds and is reporting memory leaks.

![Screenshot_1571557975](https://user-images.githubusercontent.com/8918023/67156540-58360280-f33d-11e9-9a51-00bf359bb7d2.png)
![Screenshot_1571558234](https://user-images.githubusercontent.com/8918023/67156541-58360280-f33d-11e9-9987-2dbd873af125.png)

**Comment by lognaturel** [comment]
Thanks, @shobhitagarwal1612! I talked to @mmarciniak90 and the problem is that while I thought the Leak Canary app could get uninstalled, it's impossible without also uninstalling the Collect debug build. In the short term, @grzesiek2010 has agreed to do a time-boxed exploration of the current leaks and see whether they can be quickly fixed. I believe #2716 is the most disruptive since it does happen often.

**Comment by lognaturel** [comment]
There's a note in the contribution guide, the most common leaks have been addressed, and we're back on track with a process to file issues and address leaks as they're identified so we can close this issue.
