### ISSUE TITLE
Revise `AudioVideoImageTextLabel` spacing and layout

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3382]
This view is the basically the "header" for any question:

![Screenshot_1570551839](https://user-images.githubusercontent.com/556280/66482256-788ed300-ea9a-11e9-8fa8-34ba94a9f38f.png)

The view is also used in the select choices. You can see from the screen shot that there are two cosmetic problems:

1. Spacing around the items is probably too small. You can see the scrollbar actually overlaps the buttons on the right slightly.
2. The label and the audio button are layed out at slightly different heights. This can make it a little hard to differentiate what section owns what label/control.

My suggestion would be to look at trying to look at fixing these problems while also reworking the typography for this view in line with that ongoing effot (https://forum.opendatakit.org/t/reworking-collects-typography/20634/3).

**Comment by ABHISHEK-AMRUTE** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
Hey @ABHISHEK-AMRUTE! Thanks for having a look at this. Just as a heads up I'm working on #425 which may end up having some overlapping work. Probably good for us to push any work early (as draft PRs) so we can keep an eye out for conflicts!

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
Clean up tasks to get this closed now #3455 is merged:

- [ ] Fix spacing for text widgets

Additional clean up I'll follow up with:

- [ ] Rework `QuestionWidget` so it is defined using XML - right now it's hard to work with layouts for widgets as everything is defined procedurally
- [ ] Rework `ODKView` so it is defined using XML - right now it's hard to work with layouts for widgets as everything is defined procedurally
- [ ] Add an issue for revising each individual widget's typography and spacing
