### ISSUE TITLE
Information about the newest version has a blue color instead of green

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3385]
#### Software and hardware versions 
Collect master

#### Problem description
Information about the newest version has a blue color instead of green

#### Steps to reproduce the problem
1. User goes to `Get blank form`
2. User sees information about the newest version
3. Text is blue instead of green

#### Expected behavior

|current master| v1.23.3 |
|---|----|
|![Screenshot_20191010-145032](https://user-images.githubusercontent.com/3907554/66570354-ba3c7e00-eb6d-11e9-9bad-41aeae73ddd1.png)|![Screenshot_20191010-145110](https://user-images.githubusercontent.com/3907554/66570355-ba3c7e00-eb6d-11e9-8618-ff2011bfd3e9.png)|

**Comment by be-wake** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
This was discussed in https://github.com/opendatakit/collect/pull/3225 and is a deliberate change to stick with a narrow palette rather than introduce another color.
