### ISSUE TITLE
Submissions are duplicated in Google Sheets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3391]
### Software and hardware versions 
Collect v1.24.0 beta.0
Verified only on Android 7.0 and 8.1
Reproduced also on v1.23.3 on Android 8.1

#### Problem description
Submissions are duplicated in Google Sheets

#### Steps to reproduce the problem
1. User fills a lot of forms (1006 forms in my case)
2. User sends forms to Google Sheet (**auto-send and auto delete options were selected**)
3. User sees duplicated submissions in Google Sheet (1514 submissions visible in Google Sheet)
[simple.xlsx](https://github.com/opendatakit/collect/files/3723385/simple.xlsx)
![Screenshot from 2019-10-14 09-38-43](https://user-images.githubusercontent.com/3907554/66735368-7051e180-ee66-11e9-88cc-d5426da590cf.png)

#### Expected behavior
* Submissions are not duplicated

**Comment by lognaturel** [comment]
Thanks for clarifying that this is not a regression from 1.23 to 1.24.

You have a zip of submissions that you push onto the phone to do tests like this, right? Could you please attach so it's easier to reproduce? Did you try to submit manually without auto-send and if so, did you confirm the problem doesn't happen?

**Comment by grzesiek2010** [comment]
Does that happen if you cancel and start sending forms again?

**Comment by mmarciniak90** [comment]
@lognaturel here is a zip with needed data - [backup1249.zip](https://github.com/opendatakit/collect/files/3972388/backup1249.zip)

The problem is still visible.

@grzesiek2010 no, I did not cancel sync

**Comment by dimwight** [comment]
Tried to look at this recently but couldn't get the test data to work. Is this still an active issue?

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by seadowg** [comment]
We're not currently focused on improving Google Drive flows so closing this.
