### ISSUE TITLE
Progress bar is not visible on Get Blank form loading/downloading dialog on Android 5

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3392]
#### Software and hardware versions 
Collect v1.23.3x, Android v5.1.x, device used...

#### Problem description 
The loading progress bar is not visible on Get Blank Form loading dialog/ downloading form dialog/ delete saved form dialog. Screenshot attached:
On the left there is an Android 5.1 screen, and in the right expected behavior from Android 7.1
![Screenshot from 2019-10-15 15-01-55](https://user-images.githubusercontent.com/33342488/66833913-ff412580-ef5c-11e9-9921-7544fb45718a.png)

#### Steps to reproduce the problem
Go to Get Blank Form no matter if Google Sheet selected or Aggregate as a server, wait until the list displays. 

#### Expected behavior
The progress bar should be visible on those dialogs.

#### Other information 
I have also checked the same Android with Collect 1.23.3 and the issue is also visible.
The issue is not visible on other Android versions.

**Comment by grzesiek2010** [comment]
The code is ok the problem was caused by animations turned off in developer options.
