### ISSUE TITLE
The first question in `field-list` disappears under some circumstances, if select_multiple questions are used.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3402]
#### Software and hardware versions 
Collect v1.23.2

#### Problem description
The first question in `field-list` disappears under some circumstances, if select_multiple questions are used.

The problem has been reported here https://forum.opendatakit.org/t/odk-collect-version-1-23-3-multiple-select-from-csv/22828/2.

#### Steps to reproduce the problem
1. Open the attached form:
[selectmulpipleBug.zip](https://github.com/opendatakit/collect/files/3745005/selectmulpipleBug.zip)
2. Select any option in the first question
3. Select any option in the second question

**Comment by ShivamPrajapati-dev** [comment]
@opendatakit-bot claim
