### ISSUE TITLE
Fill Blank Form page is always empty in Android 10

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3418]
This was reported on the forum: https://forum.opendatakit.org/t/nothing-available-to-display-on-fill-blank-form-page/22974/2.

#### Software and hardware versions 
Collect v1.24, Android v10, Installed from Play Store (doesn't appear in debug builds)

#### Problem description

Downloaded forms are not displayed in "Fill Blank Form" page on Android 10.l

#### Steps to reproduce the problem

On an Android 10 device with Collect installed from the Play Store:
1. Download a form
2. Open "Fill Blank Form"

Form is not shown.

#### Expected behavior

Downloaded forms should be shown.

### Other information

After digging in a little the problem appears to have appeared in https://github.com/opendatakit/collect/commit/237121bf0c5938a65f3d7f04f7285e65ba3c8218. It's only reproducible on builds using ProGuard (`minifyEnabled(true)` in `build.gradle`).

**Comment by grzesiek2010** [comment]
Yes, probably it has something to do with libraries because I could swear I tested Android 10 after bumping `targedSdkVersion`. I'll take a look.

**Comment by grzesiek2010** [comment]
you were right about `androidx.lifecycle:lifecycle-extensions` the bug was caused by updating the library. It's the second big problem caused by that lib... annoying.

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"
