### ISSUE TITLE
Improve error message when "Accept submissions" is disabled

### ISSUE THREAD

**Issue by vinaygopinath** [getodk/collect#3428]
#### Software and hardware versions 
Collect v1.24.1
Android v8.1.0

#### Problem description
When a form is not marked to "Accept submissions" under Forms Management --> Forms List on the ODK aggregate server, attempting to fill out and send the form on ODK Collect displays a dialog with a cryptic error message with technical information.
![accept submissions error](https://user-images.githubusercontent.com/324200/67935388-152b2900-fba0-11e9-8383-599909dc9918.jpeg)

#### Steps to reproduce the problem
**ODK Aggregate**
1. Create a form (or reuse an existing form), marking it to not "Accept submissions" (make sure the checkbox is unchecked)

**ODK Collect**
1. Select "Get Blank Form" and select the form you created above.
2. Select "Fill Blank Form", fill in the form, and mark the form as finalized
3. Select "Send Finalized Form", select the form, and send
4. The error message shown above should be displayed

#### Expected behavior
The app should recognize that the form is not marked to accept submissions, and inform the user.
If recognizing that status of the "Accept submissions" form is difficult, the app should offer a helpful hint to the user, with something like
> Failed to upload (name of form)
> Please make sure (name of form) is configured to accept submissions on the server

**Comment by seadowg** [comment]
Thanks for this @vinaygopinath!

**Comment by rajkumaar23** [comment]
I would like to work on this issue.

**Comment by rajkumaar23** [comment]
@opendatakit-bot claim

**Comment by rajkumaar23** [comment]
@lognaturel Waiting for you reply for a long time to fix this issue 😅
