### ISSUE TITLE
Form with `identify-user=true` audit attribute adds identifier to audit log events

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3435]
If `identify-user` is enabled, any time a person opens a form with this feature enabled, they are prompted with a “Enter a user identifier for the audit log” dialog to identify themselves with a plaintext ID or name.

A non-blank identifier will be required to open the form. All audit log events until the form is closed will be attributed to that identifier. The person filling out the form will be responsible for making sure that they exit all forms before handing their device to someone else for editing.

The full spec for this feature is here: https://docs.google.com/document/d/1lVObIqvM75tCSA5w8Iu3WropJDQmpE3Cap3GWOepTOY

Design for feature here: https://github.com/seadowg/collect-design/tree/master/prototypes/identify-user

#### Acceptance

 - [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
Then I am told I need to identify myself

 - [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And I enter my name
And I click "enter"/"go" on the keyboard
Then I can fill in the form normally

- [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And I click "enter"/"go" on the keyboard without entering anything
Then I remain on the same screen

- [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And I go back/click the cross
Then I return to the main menu

 - [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And I enter my name
And I click "enter"/"go" on the keyboard
And I fill in the form
Then the form's audit log includes my name in all events in the `user` column

- [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And I enter my name with commas or quotes ("Call,u"m"")
And I click "enter"/"go" on the keyboard
And I fill in the form
Then the form's audit log includes my name ("Call,u""m""") in all events in the `user` column

 - [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And rotate the device
Then I'm still prompted to enter my identity

 - [x] Given I've downloaded a form with `identify-user=true`
When I click on the form
And background/resume the app
Then I'm still prompted to enter my identity

- [x] Given I've downloaded a form with `identify-user=false`
When I click on the form
Then I am not prompted to enter my name
And I can fill in the form normally

**Comment by lognaturel** [comment]
Support starts in ODK Collect v1.25, pyxform 1.0.0, XLSForm Online v2.0.0. Documentation is at https://docs.opendatakit.org/form-audit-log/#enumerator-identification
