### ISSUE TITLE
MapFragment memory leaks

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#3446]
![mapbox-leak](https://user-images.githubusercontent.com/236086/68724870-98218b80-0571-11ea-9d98-93085439ca65.png)
![google-leak](https://user-images.githubusercontent.com/236086/68724872-9952b880-0571-11ea-8e1f-aca4c24053e0.png)
![osmdroid-leak](https://user-images.githubusercontent.com/236086/68724875-9a83e580-0571-11ea-92e3-31154c785882.png)

**Comment by alokbatham** [comment]
@opendatakit-bot claim

**Comment by alokbatham** [comment]
@opendatakit-bot claim --force

**Comment by mmarciniak90** [comment]
After merge #3445 to master, I retested GeoTrace widget to check where leaks are still visible.

Case for **Google Maps**:
1. User clicks on `Start GeoTrace`
2. View with map is opened (User can add location, input method does not matter. Adding a location is not required)
3. User leaves map view
4. User waits a moment - leak is recorded

Leak noticed on Android: 4.2, 4.4, 5.1, 6.0, 8.1, 9.0, 10.0
**Leak does not appear on Android 7.0!**

I noticed the same behavior for **OSM** and I did not observe leaks when I used **Mapbox**.

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/72616110-7e684000-3936-11ea-8a25-1f16deea7e1c.png">

Androids 8.1, 9.0, 10.0 have additionally this leak. Both leaks appear together.
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/72616212-b7081980-3936-11ea-8ad1-146445f2dd13.png">

**Comment by srujner** [comment]
Checked on master 3ddd5c65ef4d4fad74c3621309f43df0ec3af896

Leaks are no longer visible for all map sources.

**Case for Google Maps:**

- User clicks on Start GeoTrace
- View with map is opened (User can add location, input method does not matter. Adding a location is not required)
- User leaves map view
- User waits a moment - leak is recorded

**Checked on Androids**: 8.1, 10, 11, 12 ,13

**Comment by grzesiek2010** [comment]
Cool, let's close then.
