### ISSUE TITLE
Running on Android studio 3.5.2 faild

### ISSUE THREAD

**Issue by Saint-Cyr** [getodk/collect#3456]
#### Software and hardware versions 
I just clonned a fresh repository and try to Run it from Android studio 3.5.2 
I'm using Ubuntu 16.04 and Android studio 3.5.2

#### Problem description
I get the following error: 
com.google.android.instantapps.sdk.lib.AdbCommandException: Error launching activity org.odk.collect.android/com.squareup.leakcanary.internal.DisplayLeakActivity
Command output:
Starting: Intent { flg=0x800 cmp=org.odk.collect.android/com.squareup.leakcanary.internal.DisplayLeakActivity }
Error type 3
Error: Activity class {org.odk.collect.android/com.squareup.leakcanary.internal.DisplayLeakActivity} does not exist.

Error while Uploading and launching Instant App

#### Other information 
Notice that I'm a dummy in android development. My goal was just to edit the GUI (colors, logo, icons...).

**Comment by seadowg** [comment]
It looks like you're trying to run this is an Instant App. Make sure you're run configuration in Android Studio has **Module** "collect_app" and **Deploy** is set to "Default APK". I'd try reimporting if you're unable to set those.
