### ISSUE TITLE
RadioButtons/CheckBoxes are distorted

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3472]
#### Software and hardware versions 
Current master branch

#### Problem description
This is what I see on Android 5.1 Samsung Galaxy S4:
![Screenshot_2019-11-26-15-07-25](https://user-images.githubusercontent.com/3276264/69639127-4d693e80-105c-11ea-8b6d-733b0d9855b8.png)
![Screenshot_2019-11-26-15-07-38](https://user-images.githubusercontent.com/3276264/69639130-4e01d500-105c-11ea-9ae4-ddff9d79ae1e.png)

**Comment by seadowg** [comment]
@grzesiek2010 you seeing this on any other devices?

**Comment by grzesiek2010** [comment]
No.

**Comment by grzesiek2010** [comment]
I know which commit causes it so I'll take a look to check if there is a smile solution.

**Comment by grzesiek2010** [comment]
@seadowg 
https://github.com/opendatakit/collect/commit/326aa876806265c37a58bc72748764cc627c350a#diff-de55feb5ba476c75a8ef9928aec0b362

That file causes it, it's a workaround because you had problems with margins?

**Comment by seadowg** [comment]
The `inset`? Yeah that gives us a clickable left/start margin. I've got an [SO question open](https://stackoverflow.com/questions/58913567/how-to-add-padding-before-checkbox-radiobutton-across-api-levels) around a better way but no joy yet 😭

**Comment by grzesiek2010** [comment]
If I see that on my device I'm sure many of the users will notice it as well.

**Comment by seadowg** [comment]
Yeah would be good to get a sense of if this is a Samsung issue or it's specific to API levels as this hadn't come up on emulators or in QA. It might be we need to go with a more hacky solution like a view that propogates clicks to the `RadioButton` to get this margin to work properly.

**Comment by lognaturel** [comment]
Yikes. No such issue on my Samsung Galaxy Tab A, Android 5.1.1.
