### ISSUE TITLE
Margin is not noticeable for widgets with buttons when a value is added manually

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3493]
#### Software and hardware versions 
Collect v1.25

#### Problem description

Margin is NOT visible for widgets:
* Ex string when a value is added manually
* Ex integer when a value is added manually
* Ex decimal when a value is added manually
* Bearing when a value is added manually

#### Steps to reproduce the problem
1. User opens one on mentioned widgets
2. User clicks on the button
3. Text field appears
4. Margin is not visible for the text field

#### Expected behavior
Margin is noticeable 

#### Other information 
Noticed during testing #3464

**Comment by SaumiaSinghal** [comment]
Hie @mmarciniak90, I would like to work on this issue. Can I claim it?

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
