### ISSUE TITLE
Behavior when recovering from savepoint file is implicit and confusing

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3494]
1. Tap Start new form and select a form
1. Fill some values
1. Kill Collect
1. Reopen Collect
1. Tap Fill Blank form and select the same form as before

The hierarchy view is shown with some values filled in. This is because Collect recovered from a savepoint file.

1. Tap Start new form and select a form
1. Fill some values
1. Tap the save button on the toolbar
1. Fill some more values
1. Kill Collect
1. Reopen Collect
1. Tap Start new form and select the same form as before

A blank form is shown. Collect does not recover from a savepoint file when opening a new form because the savepoint file belongs to a previously-saved instance. If that instance is opened from Drafts, it will show the hierarchy view with the savepoint values filled in.

This is hard to build a mental model around, especially since there is no indication of recovery from a savepoint file. When opening from Drafts, recovery vs. opening a normal saved form look identical. When opening from Start new form, it's possible to guess that the values that are displayed in the hierarchy view come from some kind of recovery. @zestyping has mentioned that it feels random when the populated hierarchy is displayed and when it isn't.

I think we should give some kind of explicit feedback to the user that a savepoint file is being recovered. We should also let the user know about recovered values in a previously-saved instance from Fill Blank Form since this is probably where a user would go back to after an interruption.

This will require design. We can probably go to the forum with a proposal as the next step but for now I want to make sure the existing behavior is documented and explained somewhere.

**Comment by seadowg** [comment]
We're also seeing problems with the audit log because of this:

1. Open form to edit (with `track-changes`)
2. Change a value
3. Kill app
4. Open form to edit again
5. Save

We don't see the `question` event with the change.

**Comment by lognaturel** [comment]
This behavior is even more confusing when Collect is launched from another application: [forum thread](https://forum.getodk.org/t/start-new-form-doesnt-seem-to-start-a-blank-new-form/43398/5?u=ln)

**Comment by seadowg** [comment]
@lognaturel is something that could push back into a design discussion rather than being an issue?

**Comment by seadowg** [comment]
We decided that we'll fix this at the same time as fixing #4879. When a loading a save point, Collect will always prompt the user to either recover or discard it.

@grzesiek2010 I'm assigning to you as you're already work on it!
