### ISSUE TITLE
Form with `track-changes` missing changes for question if edited after save

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3498]
#### Software and hardware versions 
Collect v1.24.x

#### Problem description

If a form is saved while viewing a question (using the 💾 icon) and then a change is made the `question` event will not have its `old-value` and `new-value` populated.

#### Steps to reproduce the problem

1. Fill in the [attached form](https://github.com/opendatakit/collect/files/3927316/track-changes.zip).
2. Open the form to edit
3. Go to the question
4. Click 💾
5. Make a change
6. Press back
7. Press "Save changes"

The `question` event will be in the logs but will not have the `old-value` and `new-value` populated.

#### Expected behavior

There are a few things we could do. The two that come to the top of my head are:

1. `question` event is somehow updated with the `old-value`/`new- value` on the second save
2. A second `question` event appears after `form-save` with the `old-value`/`new- value`

Personally the second feels more correct to me.

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 do you folks agree that we go with the second option here?

**Comment by seadowg** [comment]
@lognaturel and I caught up about this and agreed the second option made more sense. I'll remove the "needs discussion" label for the moment. @grzesiek2010 let me know if you disagree!

**Comment by grzesiek2010** [comment]
Sounds good to me.
