### ISSUE TITLE
No focus on text field on Server URL / Username / Password dialogs, keyborad does not appear - Android 9.0

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3502]
#### Software and hardware versions 
Collect v1.25.0 beta 2, 
Android v9.0, v10.0

#### Problem description
No focus on text field on Server URL / Username / Password dialogs, keyboard does not appear

#### Steps to reproduce the problem
1. User goes to General Settings -> Server
2. User clicks on URL / Username /  Password
3. Dialog appears but without the focus on text field and the keyboard does not appear

#### Expected behavior
Keyboard appears

**Comment by SaumiaSinghal** [comment]
Hie @mmarciniak90 @grzesiek2010! I would like to work on this issue, Can I claim it?

**Comment by be-wake** [comment]
@opendatakit-bot claim

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"
