### ISSUE TITLE
Part of text is cut in RTL language on Android 7

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3504]
#### Software and hardware versions 
Collect v1.25. beta2
Android v7

#### Problem description
Part of text is cut in RTL language on Android 7

#### Steps to reproduce the problem
1. Set some RTL language
2. Open `All widgets` form

| v1.24.1 | v1.25 beta 2|
| ---|---|
|![Screenshot_20191206-115842](https://user-images.githubusercontent.com/3907554/70318780-20b5e380-1821-11ea-95ba-481eaf7ee07c.png)|![Screenshot_20191206-115246](https://user-images.githubusercontent.com/3907554/70318792-24e20100-1821-11ea-8018-cae7a595278a.png)|
|![Screenshot_20191206-115856](https://user-images.githubusercontent.com/3907554/70318811-2dd2d280-1821-11ea-845c-766cef415e8b.png)|![Screenshot_20191206-115310](https://user-images.githubusercontent.com/3907554/70318824-34614a00-1821-11ea-8c33-90e9c39a1e50.png)|

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "regression"

**Comment by seadowg** [comment]
Looks like 57a1464478b539b7858d708f56946db0a64fcaf2 is responsible for this. Not quite sure what part yet though.

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"

**Comment by ERICXUCHI** [comment]
@mmarciniak90 Hello, can you offer me your all-widgets.xml file? I cannot download it online. 

Thank you very much!

**Comment by lognaturel** [comment]
You can find it [here](https://github.com/getodk/collect#testing-a-form-without-a-server)!

**Comment by ERICXUCHI** [comment]
> You can find it [here](https://github.com/getodk/collect#testing-a-form-without-a-server)!

Yes, but the origin file is broken. 

I found it in the project, thanks all the same.

**Comment by lognaturel** [comment]
The section I linked you to has the latest version as a Google Sheets document and instructions for converting to an XForm. Other versions you find are likely out of date. Which link is broken?
