### ISSUE TITLE
Gradle 6.0 deprecates implicit semantics for handling file collisions

### ISSUE THREAD

**Issue by breakbusyloop** [getodk/collect#3507]
#### Software and hardware versions 
Collect v1.2.5

#### Problem description
NOTE: Affects developers only. May be specific to Windows.
Gradle has deprecated features and changed behavior that the ODK build relies on. After upgrading to Android Studio 3.6 (currently in beta) and Gradle 6.0.1 you receive the following warning when trying to build:
```
Gradle Daemon started in 7 s 558 ms
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.3/userguide/command_line_interface.html#sec:command_line_warnings
CONFIGURE SUCCESSFUL in 5m 35s
```

The build itself fails with strange errors in Jetify:
```
> Task :collect_app:javaPreCompileDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':collect_app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':collect_app:debugCompileClasspath'.
   > Failed to transform file 'nbi-stubs-1.0.0.aar' to match attributes {artifactType=android-classes, org.gradle.usage=java-api}
      > Execution failed for AarToClassTransform: C:\Users\Robert Morton\.gradle\caches\transforms-2\files-2.1\9d2389ea93b0b876cb0ecfb4ff196fb1\jetified-nbi-stubs-1.0.0.aar.
         > entry
   > Failed to transform artifact 'myanmar-calendar.jar (com.github.chanmratekoko:myanmar-calendar:1.0.6.RC3)' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\Robert Morton\.gradle\caches\modules-2\files-2.1\com.github.chanmratekoko\myanmar-calendar\1.0.6.RC3\ad2fc4e77e58b199832bca753f7265a93d9c47b4\myanmar-calendar-1.0.6.RC3.jar.
         > Failed to transform 'C:\Users\Robert Morton\.gradle\caches\modules-2\files-2.1\com.github.chanmratekoko\myanmar-calendar\1.0.6.RC3\ad2fc4e77e58b199832bca753f7265a93d9c47b4\myanmar-calendar-1.0.6.RC3.jar' using Jetifier. Reason: duplicate entry: META-INF/maven/com.github.chanmratekoko/myanmar-calendar/pom.xml. (Run with --stacktrace for more details.)
```

Looking inside the Myanmar calendar JAR file reveals multiple files with the same filename in the same location, which becomes a problem when they are unpackaged into the file system. Previously Gradle handled this behavior silently, but now the 'duplicatesStrategy' must be explicitly declared. See here: https://docs.gradle.org/current/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated

#### Steps to reproduce the problem
Upgrade to Android Studio 3.6 (latest beta preview).
Set the gradle dependency to 6.0.1 (by rebuilding the wrapper?)
Attempt to build

#### Expected behavior
successful build

#### Other information 
Gradle build scan output with all the failure details:
https://scans.gradle.com/s/jysy2vhe3jsqk

**Comment by rik702** [comment]
Get the same on macos 10.15.3 (Catalina) with Android Studio 3.6.  ODK Collect 1.25.2 
(the "Failed to transform file 'nbi-stubs-1.0.0.aar'" one, not the myanmar one)
