### ISSUE TITLE
With OpenStreetMap or Google mapping engines, offline layer is not displayed after initial zoom to geolocation

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3514]
#### Software and hardware versions 
Collect v1.25

#### Problem description
With OpenStreetMap or Google mapping engines, offline layer is not displayed on load. This works as intended with Mapbox -- the offline layer is displayed on load.

#### Steps to reproduce the problem
1. Put a raster mbtiles file that does not provide very zoomed tiles into the `/sdcard/odk/layers` folder (e.g. https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries-raster.mbtiles)
1. Set that file as the offline layer
1. Open a map geo widget or the form map and notice that the offline layer is not shown
1. Zoom all the way out and see that it's still not displayed
1. Set the layer to none
1. Set the layer to the same raster file and notice that it's now displayed
1. Zoom in until it's not displayed
1. Zoom back out and see that it's now displayed

#### Expected behavior
The offline layer should be displayed on load.

**Comment by lognaturel** [comment]
Need to check whether this is a regression.

**Comment by lognaturel** [comment]
Can reproduce in v1.23 so this is not new behavior. I think it has to do with rendering order. I can actually see the offline layer when the map is first loaded but then it disappears when the viewport is zoomed to the current location and only comes back if the layer is selected again.

**Comment by grzesiek2010** [comment]
This issue does not occur anymore so I'm closing.

**Comment by lognaturel** [comment]
Hurray!
