### ISSUE TITLE
Remove "ODK Collect >" from app bar

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#352]
I believe the "ODK Collect >" that is at the top of every menu was added at a time when there was no icon to identify the application. Now that there is an application icon, it's harmful to have that text because it prevents users from seeing what activity they are in. I think we should remove it.

### Existing UI
![old](https://cloud.githubusercontent.com/assets/32369/22196633/bc13cd86-e180-11e6-8c2c-77a7eb10c793.png)

### Proposed UI
![new](https://cloud.githubusercontent.com/assets/32369/22196632/bbe2df6e-e180-11e6-8f4f-ee0c789e933b.png)

**Comment by shobhitagarwal1612** [comment]
I'd like to tackle this issue

**Comment by Snailed** [comment]
you should be welcome, I was going to change it tonight.

**Comment by shobhitagarwal1612** [comment]
The app is crashing  at splashscreen. Can you please help me?

> 02-04 01:51:04.067 9599-9599/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                        Process: org.odk.collect.android, PID: 9599
>                                                                        java.lang.RuntimeException: Unable to get provider org.odk.collect.android.provider.InstanceProvider: java.lang.ClassNotFoundException: Didn't find class "org.odk.collect.android.provider.InstanceProvider" on path: DexPathList[[zip file "/data/app/org.odk.collect.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.odk.collect.android, /vendor/lib, /system/lib]]
>                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:5011)
>                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4582)
>                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522)
>                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
>                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:110)
>                                                                            at android.os.Looper.loop(Looper.java:193)
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292)
>                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
>                                                                            at dalvik.system.NativeStart.main(Native Method)
>                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "org.odk.collect.android.provider.InstanceProvider" on path: DexPathList[[zip file "/data/app/org.odk.collect.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.odk.collect.android, /vendor/lib, /system/lib]]
>                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
>                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
>                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:4996)
>                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4582) 
>                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522) 
>                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
>                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
>                                                                            at android.os.Looper.loop(Looper.java:193) 
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292) 
>                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
>                                                                            at dalvik.system.NativeStart.main(Native Method) 
>

**Comment by lognaturel** [comment]
Closed by #368
