### ISSUE TITLE
The unexpected form is available to fill

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3533]
### Software and hardware versions 
Collect master

#### Problem description
User is able to fill the form with invalid submission URL

#### Steps to reproduce the problem
1. User downloads form: [form-with-invalid-submission-url.xml.txt](https://github.com/opendatakit/collect/files/3961324/form-with-invalid-submission-url.xml.txt)
2. The form is visible on the `Fill Blank Form` list

#### Expected behavior
* Message appears
![Screenshot_2019-12-13-15-37-37-399_org odk collect android](https://user-images.githubusercontent.com/3907554/70808677-7e69a300-1dc0-11ea-9f8a-646116bca81a.png)
* bad is added to xml at the end
![Screenshot_2019-12-13-15-37-52-457_com ghisler android TotalCommander](https://user-images.githubusercontent.com/3907554/70808772-ad801480-1dc0-11ea-9b4a-20adc40f95bc.png)

**Comment by grzesiek2010** [comment]
I fixed the problem on the javarosa side https://github.com/opendatakit/javarosa/pull/518/
The problem was that after changes implemented in https://github.com/opendatakit/collect/pull/3523 we started using FormDef.getSubmissionProfile() method to get the defined submission.
However that method was broken because it returned values using just the default key but if a submission contained its own id it is added to the list using the id not the default key.

**Comment by lognaturel** [comment]
This is the same form that was used at https://github.com/opendatakit/collect/pull/3452#issuecomment-558230900. Please make sure it's modified in your test form suite to not have an `id`! Setting the `id` attribute on a submission is not supported. The intent for that feature in JavaRosa was for clients to be able to send different parts of a form to different servers.

I think this behavior is correct given that the `id` is not supported. That is, there is no default submission profile so the full form should be sent to the server that the client configures. It's very unlikely that anyone has a form with an `id` like this but in such a case we'd want to warn them that their form is not standards-compliant but still let them fill it out and send to the client-defined server.

**Comment by grzesiek2010** [comment]
Without that id everything is fine, I didn't know it's not supported...

**Comment by lognaturel** [comment]
So sorry about that, @grzesiek2010. I didn't want to get distracted from what I was doing so I didn't look at this issue long enough to see it was one we'd already discussed. 😭

**Comment by grzesiek2010** [comment]
No worries. Ok so we can close?

**Comment by lognaturel** [comment]
As I was looking at https://github.com/opendatakit/javarosa/pull/518, I realize that I misunderstood what the `id` was intended for. It's the `bind` that's supposed to identify a subset to submit. This is also unsupported. `id` is for [specifying multiple submission actions](https://en.wikibooks.org/wiki/XForms/Submit#The_Submit_Element). @opendatakit/testers please modify the form to have no `id` or `bind`. Thanks!
