### ISSUE TITLE
Unable to download forms without media attachments

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3535]
#### Software and hardware versions 
Collect current master.x, Android v7, 9 probably all.x.x, device used...

#### Problem description
The error message is displayed when try to download form from Central:
![Screenshot_20191213-161532](https://user-images.githubusercontent.com/33342488/70811264-8d9f1f80-1dc5-11ea-9f11-fe040b5efd1e.png)

#### Steps to reproduce the problem
1. Import settings via QR code from Central to Collect.
2. Go to Get Blank Form
3. Select form from the displayed list
4. Click on Get Selected

#### Expected behavior
The form should be successfully downloaded.

#### Other information 
!! The issue does not occur on beta, only on current master

**Comment by seadowg** [comment]
Looks like the error message comes from `FormDownloader#processOneForm`

**Comment by seadowg** [comment]
Seeing a `NullPointerException` at line 175 in `FormDownloader`:

```java
setupReferenceManagerForForm(ReferenceManager.instance(), new File(tempMediaPath));
```

Here `tempMediaPath` is `null`.

**Comment by seadowg** [comment]
The `tempMediaPath` being `null` seems to be because the `FormDetails` passed to `processOneForm` returns `null` for `getManifestUrl()`.
