### ISSUE TITLE
cannot find symbol class Maptile

### ISSUE THREAD

**Issue by zahira21** [getodk/collect#3543]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by seadowg** [comment]
Hey @zahira21. What version of Collect are you using? Where in the app did you see this occur? Did the app crash?

**Comment by zahira21** [comment]
I had downloaded the source code for the Collect in android studio. But there is a gradle error which says cannot find symbols class Maptile. It is the latest version of collect. App even hasnot been installed

**Comment by seadowg** [comment]
Have you made sure to sync Android Studio with the Gradle files?

**Comment by zahira21** [comment]
yes it is the error that has occurred during sync Android Studio with Gradle files. And i don't know how to solve it

**Comment by seadowg** [comment]
Would you be able to share the full stack trace you get and what version of Android Studio you're using? We do ask these questions in the issue template and it helps us help you if you give us as much info as possible!

**Comment by zahira21** [comment]
I am using the android version of 3.5.2.  Should I add any extra
library for MapTile
[image: Capture.PNG]

**Comment by seadowg** [comment]
@zahira21 you shouldn't have to add any extra libraries. Our builds are all working fine. I think this back and forth would be better supported by the [Collect slack channel](http://slack.opendatakit.org/) as others will be able to help as well. I'm going to close this issue for now but definitely post there if you're still having trouble!
