### ISSUE TITLE
 File "<string>", line 4, in <module> FileNotFoundError: [Errno 2] No such file or directory: 'news.json'

### ISSUE THREAD

**Issue by chintaaruna123** [getodk/collect#3567]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by seadowg** [comment]
This doesn't look like it relates to this repo. Please feel free to repoen with the information in the issue template filled out if it does!
