### ISSUE TITLE
[UX] "Delete Saved Form" button is confusing

### ISSUE THREAD

**Issue by eeshugerman** [getodk/collect#3591]
#### Software and hardware versions 
Collect v1.25.1, Android 10
(though this applies to all versions AFAIK)

#### Problem description
The main menu button "Delete Saved Form" is used to delete both "saved" and "blank" forms.

#### Steps to reproduce the problem
N/A
#### Expected behavior
I would recommend changing the text to "Delete Form".

#### Other information 
N/A

**Comment by devanshi7799** [comment]
@eeshugerman can i work on this one?

**Comment by seadowg** [comment]
@eeshugerman I was interested to hear about the problems you were running into with this? We've introduced a new "Exactly match server" form management mode that simplifies the "Delete saved form" page that might help you. 

I'll close this for the moment but obviously we can reopen if you're still seeing problems!
