### ISSUE TITLE
Unable to scan QR codes with inverted colors

### ISSUE THREAD

**Issue by bojko108** [getodk/collect#3614]
Hello, I'm using ODK Collect for collecting various types of data and one of the sources is a QR Code. The problem is that the QR Codes are printed with inverted colors and reading them is not possible with current version of ODK Collect.
#### Software and hardware versions 
Collect v1.25.1, Android v9, device used Huawei P30 Lite
#### Problem description
I'm unable to scan QR codes with inverted colors. I know it's a bad practice to use QR codes with inverted colors, but most of the libraries that read QR codes support mixed scan mode. **zxing-android-embedded**, used by ODK Collect, also supports it: [https://github.com/journeyapps/zxing-android-embedded/pull/327](https://github.com/journeyapps/zxing-android-embedded/pull/327) (from v3.6.0)
#### Steps to reproduce the problem
1. Download a sample form:
[TestForm.zip](https://github.com/opendatakit/collect/files/4127624/TestForm.zip)
2. You can go to [https://www.qrcode-monkey.com/6-reasons-why-your-qr-code-is-not-working](https://www.qrcode-monkey.com/6-reasons-why-your-qr-code-is-not-working)
3. Open ODK Collect and select Fill Blank Form.
4. Start collecting and try to scan both images. The one on the right is with inverted colors and cannot be read with ODK Collect.
#### Expected behavior
It would be convenient to be able to scan both types of images: normal and inverted.
#### Other information 
As I've said, zxing-android-embedded can scan in mixed mode, but it should be upgraded to a new version. I've checked current version (v3.3) used by ODK Collect and it can also be used to scan in inverted colors mode with:
```java
Intent intent = getIntent();
intent.putExtra(Intents.Scan.INVERTED_SCAN, true);
capture.initializeFromIntent(intent , savedInstanceState);
```
in [.../collect/android/activities/ScannerWithFlashlightActivity.java](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/ScannerWithFlashlightActivity.java) so there is no need to upgrade.

I'm wondering if it's possible to implement an option to switch between normal and inverted colors mode. Possible solution is to add a switch to ScannerWithFlashlightActivity form and the user can use it to set the scan mode manually. What do you think?

**Comment by lognaturel** [comment]
Thanks for the carefully-written issue, @bojko108 and welcome to the community! As you've noted, this is an easy change to make and @grzesiek2010 has even gone right ahead to making it so it will be part of the next release, planned for early March.

I invite you to join our community forum and [introduce yourself and your project](https://forum.opendatakit.org/t/introduce-yourself-here/6671/1067). That's typically where feature requests would go though with something this clear, it's not needed!

**Comment by bojko108** [comment]
Thank you for your quick response, I'm glad this feature will be soon included in the app, thanks :)
