### ISSUE TITLE
Collect crashes after minimizing an app when Rank widget popup displayed.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3615]
#### Software and hardware versions 
Collect v1.25.1, Android v4.2-10, device used...

#### Problem description
Collect crashes after minimizing/extinguishing an app when Rank widget popup displayed.

#### Steps to reproduce the problem
1. Open Rank widget
2. Click Rank items button
3. Minimize/extinguish the app

#### Expected behavior
The app should not crash. User should be able to restore the app from the background. 

#### Other information 
I have used All widgets form with rank widget.

**Comment by grzesiek2010** [comment]
It requires a fix in Javarosa https://github.com/opendatakit/javarosa/pull/536

**Comment by lognaturel** [comment]
I've detailed issues with the proposed JavaRosa change at https://github.com/getodk/javarosa/pull/536#issuecomment-633733161.
