### ISSUE TITLE
Move saving .settings file out of Import/Export settings and rename Import/Export settings to QR code configuration

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3618]
I was talking to @andrewsiew2 about the QR code settings feature and he pointed out that having QR code configuration and the `.settings` file export on the same screen is confusing. We'd rather use a name like `QR code configuration` instead of `Import/Export settings`. We can't currently because the screen doesn't just do QR code configuration.

I propose pulling the saving to `.settings` functionality out of the current screen and putting it directly in Admin Settings right above the `User Access Control` section with name `Save legacy .settings file to disk". The details text should say "Will be removed in a future version. Please use the QR code above.". There should be analytics on this settings option so we can track usage.

Once that is done, the existing Import/Export Settings screen can be renamed to `QR code configuration`.

I chose not to put this on the forum because it seems like a relatively minor change. I think that if @andrewsiew2 agrees with this proposal and no one objects after a few days, then we can remove the `needs discussion` tag and proceed.

**Comment by yanokwa** [comment]
I'm OK with this. I'd also think we should add a header called `App Configuration` or something. Then put  the following...
* Reset application...
* Configure via QR code
* Save configuration to file
   * Will be removed in a future version

**Comment by andrewsiew2** [comment]
@opendatakit-bot claim

**Comment by andrewsiew2** [comment]
@opendatakit-bot claim --force
