### ISSUE TITLE
Remove analytics for null form controller

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3621]
The `getFormController` methods in `FormEntryActivity` currently log analytics when the `formController` is `null`. However, the flow through that activity relies on the `formController` being null before the form is loaded. Those analytics have not been helpful and should be removed.

**Comment by anubhav11march** [comment]
I would like to work on this

**Comment by seadowg** [comment]
Hey @anubhav11march 👋

You can follow the instructions in our [CONTRIBUTING.md](https://github.com/opendatakit/collect/blob/master/docs/CONTRIBUTING.md) on how to get started with a contribution.

**Comment by lognaturel** [comment]
How is this going, @anubhav11march? If you need any help getting set up, find us [in Slack](https://slack.opendatakit.org). We definitely want this in the next release!

**Comment by anubhav11march** [comment]
@lognaturel  Hey, Sorry, I got busy with something. I will work on this tomorrow onward and will definitely ensure to complete it before next version. :)

**Comment by lognaturel** [comment]
Thanks, @anubhav11march!

**Comment by shubhamkumar1739** [comment]
@lognaturel as this issue was inactive from a few days, I fixed it.
