### ISSUE TITLE
Set minSdkVersion to 21 and remove special cases for APIs under 21

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3624]
The biggest change coming to the upcoming v1.26 release is starting the [scoped storage migration](https://forum.opendatakit.org/t/collect-will-need-to-stop-using-sdcard-odk-for-files/24159). This is not relevant to users on older versions of Android. Additionally, Android <5 now only accounts for 6% of Collect users.

The [Technical Steering Committee](https://opendatakit.org/community/governance/#tsc-1) discussed dropping support for Android < 5 and decided to move forward in this release.

There are currently several special cases for APIs under 21 and these should be removed.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
