### ISSUE TITLE
Illegal class file: Class module-info is missing a super type. Class file version 53.

### ISSUE THREAD

**Issue by BadMask121** [getodk/collect#3626]
#### Software and hardware versions 
Collect v1.x.x, Android v3.5.3, device used...

#### Problem description
i get the below when i want to run the build for the first time , recently updated my android stuiod to version 3.5.3
"Illegal class file: Class module-info is missing a super type. Class file version 53."
#### Steps to reproduce the problem
Click the "Run" button then on build process it will fail
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by be-wake** [comment]
This is not an issue of application. It is because you are using Windows for development.
Look at this to resolve the issue.
https://github.com/opendatakit/collect/blob/master/docs/WindowsDevSetup.md
