### ISSUE TITLE
Markup Image button should be disabled when there is no media or path to default image is invalid.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3634]
#### Software and hardware versions 
Collect v1.26x, Android v4-10, device used...

#### Problem description
For Annotate widget with default image described Markup Image button should be enabled only when path to default image is described in a correct way. Currently, when delete media and open form Markup button is enabled. The same issue is visible when the default image path is described in incorrect way. Screenshots attached:
| invalid | media deleted |
| -------- | -------- |
![Screenshot from 2020-02-11 11-19-30](https://user-images.githubusercontent.com/33342488/74230148-13efb900-4cc4-11ea-8340-b19232593037.png) | ![Screenshot from 2020-02-11 11-19-12](https://user-images.githubusercontent.com/33342488/74230164-1b16c700-4cc4-11ea-8237-b7e142272da1.png) 

#### Steps to reproduce the problem
Just open Annotate widget with default image described in the wrong way or delete media. I have used form: 
[defaultImage.zip](https://github.com/opendatakit/collect/files/4185248/defaultImage.zip)

#### Expected behavior
Markup Image button should be active only when the picture is added/ path to default image is described correctly.

**Comment by chidauri** [comment]
@opendatakit-bot claim
