### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by zahira21** [getodk/collect#3641]
How to give the READ_PHONE permission. If the permission is asked at the starting of the app then the app automatically crashes. It's been a month that I have tried to remove the permission issue

**Comment by lognaturel** [comment]
Is this an issue for you on the Collect version in the Play Store? Please be sure to fill out the entire issue template including device info and Android version.

**Comment by zahira21** [comment]
I had downloaded the source code provided in the git hub to prepare my own customized app. There is an issue with READ_PHONE permission. We have to provide ask permission from java class instead of from the activity class.

**Comment by lognaturel** [comment]
It sounds like you’ve solved the problem on your fork so that’s great. It hasn’t been an issue on master so I’m closing this issue.
