### ISSUE TITLE
Test image widgets display correct image

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3643]
There aren't currently tests for the image widgets (widgets descending from `BaseImageWidget`) that ensures they display the correct image based on the file path in a prompt. We now have tests that they display an image default however (#3642) so we should add the "normal" case to these tests as well.

**Comment by starboi02** [comment]
Can i work on this?

**Comment by grzesiek2010** [comment]
Hi @starboi02 
sure go ahead :smiley:
