### ISSUE TITLE
Move app version to toolbar and remove tagline

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3650]
<img src="https://user-images.githubusercontent.com/967540/75195171-4c54b580-570e-11ea-9f17-6486c043e02e.png" width="250" />

Described by @seadowg at https://github.com/seadowg/collect-design/tree/master/prototypes/revised-main-menu. For now, no changes would be made to the buttons.

Additionally, the git commit hash needs to be added for builds that don't come from a tagged commit. This will only matter to developers so I don't really mind where it goes. I propose putting it right above the buttons and below other UI components such as banners.

**Comment by seadowg** [comment]
@lognaturel what's the thinking behind needing the commit SHA displayed? Personally I've never used it.

**Comment by lognaturel** [comment]
> Personally I've never used it.

Ah, well, maybe I'm the only one! @grzesiek2010? @opendatakit/testers? I find it very valuable to be able to connect a running version with a commit hash when I discover a new issue or when I'm comparing alternative implementations. It's really helpful when doing releases to be very confident we're on a clean, tagged commit so I think we should have an at-a-glance way to confirm that.
