### ISSUE TITLE
Undesirable button is visible on readOnly video widgets.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3653]
### Software and hardware versions 
Collect v maser, Android v probably all, checked on 7-10, device used...

#### Problem description
The undesirable button is visible on readOnly version of video widget and selfie video widget:
![Screenshot (Feb 26, 2020 10_46_04 AM)](https://user-images.githubusercontent.com/33342488/75334221-bcd31200-5887-11ea-803d-d5be73d227e7.png)

#### Steps to reproduce the problem
Just open readOnly version of video/selfie video widget. 

#### Expected behavior
The behavior from Collect 1.25.2:
![Screenshot_20200226-104517](https://user-images.githubusercontent.com/33342488/75334326-eb50ed00-5887-11ea-8ec7-ee56ecda7843.png)

#### Other information 
The form that I have used: 
[all-widgetsReadOnly.xml.txt](https://github.com/opendatakit/collect/files/4254861/all-widgetsReadOnly.xml.txt)

**Comment by shubhamkumar1739** [comment]
@grzesiek2010 I am a newbie and i wish to contribute. Can I work on it?

**Comment by grzesiek2010** [comment]
@shubhamkumar1739 ok go ahead!

**Comment by seadowg** [comment]
@kkrawczyk123 @shubhamkumar1739 am I right in thinking that the button should still appear if it's read only AND it has content (a video/selfie)?

**Comment by shubhamkumar1739** [comment]
@seadowg yes even I thought so. But I decided to stick with the expected behaviour mentioned in the issue.

**Comment by kkrawczyk123** [comment]
@shubhamkumar1739  expected behavior describes case when there is no content.

**Comment by shubhamkumar1739** [comment]
ok i'll make the changes
