### ISSUE TITLE
Use Google Sheets API v4

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#367]
#### Software and hardware versions 
Collect v1.4.14

#### Problem description
Collect currently uses an older API to interface with Google Sheets. This has probably contributed to minification issues and is a barrier to updating other libraries.

#### Other information 
The first question to answer is whether it will be possible to upgrade this library in isolation or whether it will also require updating other libraries such as Google Play Services. As much as possible, this upgrade should be isolated from others.

I looked at [Google's quick start guide](https://developers.google.com/sheets/api/quickstart/android) and their example requires several other updated libraries. I don't know whether this is for the rest of their example or whether they are truly needed to use `com.google.apis:google-api-services-sheets:v4-rev108-1.22.0`. I tried only adding
```
    compile('com.google.apis:google-api-services-sheets:v4-rev108-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
```
to build.gradle and removing `google-api-client-1.20.0.jar` which gets replaced by 1.22. That does compile although I didn't look to see if the API is useable. That would be the first thing to verify.

The [migration guide](https://developers.google.com/sheets/api/guides/migration) from v3 to v4 will probably be helpful.

**Comment by grzesiek2010** [comment]
I was working on this a few weeks ago but I wasn't able to finish. The doc wasn't very well and it was short of good examples (https://developers.google.com/sheets/api/quickstart/android as I can see last update is February 23 so they are still working on that).

I'm told someone asked about this issue so you can feel free and take it as now I'm working on a few other things and it doesn't make sense to block this one. The main problem I ran into was the doc as I said. I wasn't able eg. to find similar easy way for inserting aswers. Now we just collect pairs (column name and answer) https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java#L625 and we can insert that collection easily https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java#L631 all answer are added in the right places (according to column names)

Maybe someone has an expirience with this new Api and is able to fix that.

**Comment by lognaturel** [comment]
One thing that I would recommend and that might make this update easier is to isolate the calls to the external service in a connection object of some kind -- https://www.martinfowler.com/articles/refactoring-external-service.html

**Comment by shobhitagarwal1612** [comment]
I'm working on this

**Comment by shobhitagarwal1612** [comment]
I am facing some difficulty running the application with the added dependency for sheets-v4.
`compile('com.google.apis:google-api-services-sheets:v4-rev463-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }`
 App successfully builds but when I try running the app, it shows following error:
>Error:Execution failed for task ':collect_app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/api/client/http/AbstractHttpContent.class
@nribeka  @lognaturel @grzesiek2010 Has anyone faced similar issue? Please help

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 Please try to do the same https://github.com/grzesiek2010/collect/commit/f225d0478918236673f7038701543cd3c94f87f7 except of removing guava lib (as I remember we need that)

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 I solved the problem by updating other libraries as well but had to remove guava lib as it was showing the same duplicate entry error. What is the purpose of guava lib as after removing it, the app is running fine?

**Comment by grzesiek2010** [comment]
https://github.com/opendatakit/collect/pull/403
but as you work on this functionality I think you can remove that lib.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 I will make sure that other features are not affected by removing it

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 Good luck!

**Comment by lognaturel** [comment]
@shobhitagarwal1612 As you saw from the link @grzesiek2010 provided, guava was an implicit gdoc dependency. So he is correct, there's no problem in removing it once the gdoc jar is removed.

Please try to be as minimal as possible in your lib updates! The more changes we introduce, the more likely there are to be bugs.

Looks like this is going well! Thanks for taking it on.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I had to update quite a number of libraries as it was impossible to run the code without that.
