### ISSUE TITLE
Error message when search() expression uses missing column is misleading

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3674]
#### Software and hardware versions 
Collect v1.25.2

#### Problem description
Error message when search() expression uses missing column is misleading.

#### Steps to reproduce the problem
1. Open a form with a `search()` expression that refers to a column that doesn't exist such as [bad-search-column.zip](https://github.com/opendatakit/collect/files/4288996/bad-search-column.zip)
1. See that the error message is "File <file> is missing."

#### Expected behavior
In v1.24.0, a dialog showed the SQL error. That wasn't great but at least it gave the user more of a hint as to what went wrong. I think that's the best we can do.

**Comment by lognaturel** [comment]
The problem is that the file is successfully ingested in this case, it just can't be queried. By the time the exception capture happens, there is no more .csv file because it has been moved to .imported. I'd like to know what happened between v1.24 and v1.25 to explain the behavior change in case there were other ramifications to that change but #3666 does incidentally fix this because the .csv file will be left alone.

**Comment by lognaturel** [comment]
This was fixed by #3666 but I think we should do a quick sanity check around the changes that caused the problem. Is that what you've claimed, @grzesiek2010?

**Comment by grzesiek2010** [comment]
I can confirm that a dialog with more valuable message is displayed:
![Screenshot_2020-03-11-18-17-21](https://user-images.githubusercontent.com/3276264/76439279-71a71c00-63bc-11ea-97e4-25387c8a2c55.png)

@lognaturel do you think it would be good to handle it somehow and display something more user friendly?

**Comment by lognaturel** [comment]
> @lognaturel do you think it would be good to handle it somehow and display something more user friendly?

There are various different SQLite exceptions that could happen at that point. To display a friendlier message, we'd need to do something like use a regex on the exception message. The message is ugly but I think it's relatively easy to understand so I'd tend to leave it. If you're ok with that you can close, @grzesiek2010.
