### ISSUE TITLE
Save button in Reason for changes page does not work after rotating device orientation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3689]
#### Software and hardware versions 
Collect v1.26.0 beta
Works correctly on v1.25.2

#### Problem description
Save button in Reason for changes page does not work after rotating device orientation

#### Steps to reproduce the problem
1. User fills the form [track-changes-reason-on-edit.xml.txt](https://github.com/opendatakit/collect/files/4298052/track-changes-reason-on-edit.xml.txt)
2. User goes to `Edit Saved Form `
3. User edits an answer, go to `Save and Exit` and click on it.
4. User inputs a reason
5. User rotates the screen
6. User clicks on Save button
7. **User is moved to view with the `Save and Exit` button, instead of to the main menu**

#### Expected behavior
The form is saved and user is moved to the main menu

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "regression"

**Comment by seadowg** [comment]
@grzesiek2010 it looks like you have a few things in flight. I can take a look at this if you want?

**Comment by grzesiek2010** [comment]
> @grzesiek2010 it looks like you have a few things in flight. I can take a look at this if you want?

Thanks but I already have a solution I guess. Since you probably know more about LiveData please take a look and let me know if my thinking is right #3690.

Does that really work in that way that after rotating a device it won't remember about observers like this https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L1824

and we need what I did herehttps://github.com/opendatakit/collect/pull/3690/files#diff-03ff45091550285dd88b56927010c457R429

**Comment by seadowg** [comment]
@grzesiek2010 hmmm yeah as far as I understand it absolutely should remember that observer so you shouldn't have had to make the change you made in #3690. I'm going to try and wrap my head around it.

**Comment by seadowg** [comment]
@grzesiek2010 actually don't listen to earlier Callum. Earlier Callum is wrong - the activity will of course call `onDestroy` when rotating which will kill the observation.

@grzesiek2010 @lognaturel What confused me is that the `FormEntryActivity` has `android:configChanges="orientation"` in the manifest which should mean that it is not recreated on rotation. It seems like this isn't working through (you can demonstrate by debugging `onCreate`/`onDestroy` and rotating). It looks like it does work for the `MainMenuActivity` though. I'm wondering whether you also need `screenSize` for this to work? Either way I think `configChanges` is confusing and so if we can we should ditch the flag from the `FormEntryActivity` (probably after release). This doesn't solve this issue but it makes it clearer that acitvity just behaves "normally" on rotation. What do you folks think?

**Comment by grzesiek2010** [comment]
I' also not a fan of flags like `orientation`/`screenSize` it would be good to get rid of it but I find it risky so definitely not now before release.
