### ISSUE TITLE
Simplify version parsing code and ensure that different tag structures won't cause a crash

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3693]
See https://github.com/opendatakit/collect/pull/3685#issuecomment-595494561 for suggested approach. I think that by first handling the beta version suffix and then splitting on the first `-`, there will no longer be a crash risk but this should be added to the tests (e.g. `my-cool-version` or `777` as versions).

**Comment by shobhitagarwal1612** [comment]
I think that this issue was closed by mistake in #3777.

**Comment by seadowg** [comment]
@shobhitagarwal1612 nope! It might seem unrelated but we added test cases to cover this.
