### ISSUE TITLE
Espresso regression tests don't work on device with Android 9.0

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3700]
#### Software and hardware versions 
Collect v1.25/1.26.x, Android v9.0, device used: Xiaomi Redmi 7 and Samsung A50

#### Problem description
Espresso regression tests don't work on real devices with Android 9.0. They run without any problems on the emulator.

#### Steps to reproduce the problem
Try to run them on device with Android 9.

#### Expected behavior
Espresso regression tests should work as on other devices.

#### Other information 
Stacktrace: 
[xiaomi.txt](https://github.com/opendatakit/collect/files/4313035/xiaomi.txt)

**Comment by lognaturel** [comment]
@kkrawczyk123 do you have animations turned off on that device? If you haven't tried that yet, could you try turning them off?

**Comment by kkrawczyk123** [comment]
@lognaturel The attached stack trace was with "Animation scale 1x". I have tried with Animations off this is the stack trace: 
[animationOffxiaomi.txt](https://github.com/opendatakit/collect/files/4318154/animationOffxiaomi.txt)

**Comment by grzesiek2010** [comment]
As I said today (during our meeting) I tried to fix the problem using the mentioned device but to no avail. I even tried espresso tests from other repositories with the same result. Can we close and use emulators instead?

**Comment by lognaturel** [comment]
Yes, let's keep an eye out for more info when other contributors have similar devices but let's do regression checks on emulators and not worry about explicitly trying to hunt this down. @seadowg mentioned that vendors may be doing things to the operating system that conflict with what Espresso tries to do.

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"
