### ISSUE TITLE
Add an option to send data to Google Sheets without the apostrophe

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3703]
#### Software and hardware versions 
All versions and all devices

#### Problem description
We use an apostrophe to send data to Google Sheets in order to protect users from automatic conversion of some answers, actually it's used just in case of three question types:
- text
- select_multi
- barcode

but still it's a problem for some users. The apostrophe is not needed if we send data to a sheet that if Plain Text is used as a formatting option in the sheet settings.

I think for those aware users we should add an option to send data without the apostrophe to solve problems like:
https://forum.opendatakit.org/t/apostrophe-in-front-of-calculated-formatted-date-prevents-google-sheets-query-function-to-operate/25382

The option would be disabled by default and contain a description about the dangerous it might cause.

**Comment by grzesiek2010** [comment]
@lognaturel I think it would be good to have it in v1.27 since it's a recurring problem. Any thoughts?

**Comment by seadowg** [comment]
We're not currently focused on improving Google Drive flows so closing this.
