### ISSUE TITLE
Improve the code responsible for updating numbers in buttons in the main menu

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3705]
#### Software and hardware versions 
All versions and devices.

#### Problem description
We have a nasty code in [MainMenuActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L608) responsible for updating numbers in buttons. It causes that [updateButtons()](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L503) method is called every time we update instances.db.
That means it's called for every single row we update during migration (actually I [fixed it by disabling the observer](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L668) simple but still)
The same behavior I noticed when auto send is working. It might not be a problem if forms are being send but if for example there is something wrong with the url  it just goes through all saved instances and that also causes calling [updateButtons()](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L503) method for every single instance.

In a result if we are in the `MainMenu` the `UI` is blocked. 

It was supposed to update the buttons after sending each form but I don't think it's that important. i think we could just wait for ending and update the buttons once and get rid of all that code we use now..

@lognaturel @seadowg any thought?

**Comment by seadowg** [comment]
Oh wow yeah I'd never really dug into this code. Seems overly complex to me. I'm wondering if we could just have the database queries in the new `MainMenuViewModel` and expose methods for the form counts?

**Comment by grzesiek2010** [comment]
> I'm wondering if we could just have the database queries in the new MainMenuViewModel and expose methods for the form counts?

could you elaborate a bit?
you mean count the forms for example in `onResume()` and once `AutoSendWorker` is done like I proposed or more often maybe like now but with some other improvements?

**Comment by seadowg** [comment]
> you mean count the forms for example in onResume() and once AutoSendWorker is done like I proposed or more often maybe like now but with some other improvements?

Yeah I was thinking `onResume` but hadn't considered `AutoSendWorker`. I'm wondering if this is an opportunity to use the LiveData + MVVM + Repository architecture that [Google seems to be all about](https://developer.android.com/jetpack/docs/guide)? Might be something we could chat about on a call or try and draw out. I know @lognaturel was talking about incorporating more Repository interfacts (like the `InstancesRespository`) so that would fit into this kind of world.

**Comment by grzesiek2010** [comment]
Yeah so that's what I meant as well.

**Comment by seadowg** [comment]
This is code actually a lot nicer now, so I think we can close this.
