### ISSUE TITLE
Insufficient spacing above grid of select questions

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3709]
#### Software and hardware versions 
Collect v1.26.0

#### Problem description
![device-2020-03-13-083712](https://user-images.githubusercontent.com/967540/76636197-e20d8480-6505-11ea-9988-94796a2fad73.png)

#### Steps to reproduce the problem
Open a form with a grid of select questions such as [this one](https://docs.google.com/spreadsheets/d/1CWjrWnneTAl1Gs8-BaT-VwJV8TgrbKlYXPMK5HjGVrU/edit#gid=0).

#### Expected behavior
The spacing above this question should be the same as above normal labels.

**Comment by SaumiaSinghal** [comment]
Hi @lognaturel! I would like to take this one.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
