### ISSUE TITLE
After using the repeat dialog to add a repeat, if the next question has a text field, the keyboard is not shown

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3710]
#### Software and hardware versions 
Collect v1.26.0, Android 5.1, Galaxy Tab A

#### Problem description
After using the repeat dialog to add a repeat, if the next question has a text field, the keyboard is not shown.

#### Steps to reproduce the problem
1. Open a form with repeats in which the first field in the repeat requires keyboard input (e.g. [send-sms-or-email-in-form.xml.zip](https://github.com/opendatakit/collect/files/4331752/send-sms-or-email-in-form.xml.zip))
1. Swipe to the end of the first repeat instance
1. Tap 'Add' on the dialog
1. Notice that the field has focus but the keyboard is not displayed

#### Expected behavior
The keyboard should be displayed

#### Other information 
I'm guessing this is a regression from v1.25.0 but haven't checked yet.

**Comment by grzesiek2010** [comment]
I used two real devices and two emulators and can't reproduce... what device did you use?

**Comment by lognaturel** [comment]
🤦🏻‍♀️Why didn't I fill that in?! Android 5.1, Galaxy Tab A. Great to hear it's not wide-spread. Let's close and see if a user reports. Confirmed it doesn't happen on an emulator.

**Comment by grzesiek2010** [comment]
One of devices I used was Android 5.1. We can also ask @mmarciniak90 to take a look on her devices. Please do that only if you are free since the priority is low.

**Comment by lognaturel** [comment]
Ah, I just had sudden inspiration. I had transition animations off on my device and with those settings, the keyboard appears between fields in a repeat but not for that first field in the repeat. When I turn transition animations on, everything works as expected. So let's not worry about this at all.
