### ISSUE TITLE
First time running the app and I get a database error that says "no such column: geometryType(code 1); while compile SELECT ...... FROM instances. Please how do I go about this

### ISSUE THREAD

**Issue by owolabiezekiel** [getodk/collect#3712]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
After setting up the project and running the first time, the error above appears

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
Hi @owolabiezekiel 

it's a rare problem that might occur when you use ODK Collect and another app that is based on ODK Collect like KOBO for example. Is that your case?

Recently I fixed the same problem reported on the forum https://forum.opendatakit.org/t/error-code-1-sqlite-error/25301/8
If you want please share with me the same file I asked for in that topic and I'll send you a fixed version of it that will solve the problem.

For now I'm closing we can continue the discussion on the forum.

**Comment by owolabiezekiel** [comment]
I have checked and I have exactly the same error as in the forum. what are
the things to need me to provide for you to help resolve this issue?
