### ISSUE TITLE
How to set server username and password preferences in mainactivity

### ISSUE THREAD

**Issue by owolabiezekiel** [getodk/collect#3724]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
I currently want to enable ODK to autoatically set the admin username and password preferences from main activity but I keep getting the error that "Attempt to invoke virtual method 'android.widget.EditText android.preference.EditTextPreference.getEditText()' on a null object reference"

#### Steps to reproduce the problem
I am following the example of how we get and set these preferences in ServerPreferencesFragment.java but I am not having  a breakthrough

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
It's a question about changes you want to implement in your own fork so please ask on the forum.
