### ISSUE TITLE
Dark mode is reset after scanning Central QR code

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3726]
#### Software and hardware versions 
Collect v1.26, 1.25.x, Android vprobably all versions.x.x, device used...

#### Problem description
The dark mode is reset after scanning Central QR code.

#### Steps to reproduce the problem
1. Set dark mode
2. Scan Central QR code 

#### Expected behavior
Light mode is visible except dark mode, so it is reset somehow while scanning. 

#### Other information 
Any Central QR code will do.

**Comment by mmarciniak90** [comment]
This issue is not connected to dark mode only. I checked part of settings and they are restored to default after scanning.

**Comment by lognaturel** [comment]
This is expected. When a QR code is scanned, the keys it contains are set. All other keys are reset to defaults. We may want to consider an option to leave all other settings as they previously were but that should be a forum discussion.
