### ISSUE TITLE
Dark `Choose account for ODK Collect` dialog for light mode

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3729]
#### Software and hardware versions 
Collect v1.24.0
Older versions weren't verified

#### Problem description
Dark `Choose account for ODK Collect` dialog for light mode

#### Steps to reproduce the problem
1. User uses the light mode
2. User goes to `General Settings` -> `Server`
3. User selects Google Drive in Type option
4. User clicks on `Google account` to open dialog `Choose account for ODK Collect`
5. **Dialog is dark** 

![Screenshot_20200320-163008](https://user-images.githubusercontent.com/3907554/77180129-c6881800-6ac9-11ea-9ffd-255ea09c79dd.png)

#### Expected behavior
Dialog `Choose account for ODK Collect` is light for light mode and dark for dark mode

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by dczerwinski** [comment]
@getodk-bot claim

**Comment by dczerwinski** [comment]
Dialog is created not by ODK app but by Google. We are sending intent for result to get user Google Account in `ServerPreferencesFragment.requestAccountsPermission()`.
In the official documentation, I couldn't find any way to change the background of the dialog, but there were a lot of hints on the internet to add this extras to intent:
```
        // Where 0 is for dark theme and 1 is for light theme
        intent.putExtra("overrideTheme", 0);
        intent.putExtra("overrideCustomTheme", 0);
```

However, it doesn't work for us. I debugged the code and checked that the values were set correctly, but they have no effect on the theme of the dialog.  As I read on stackoverflow, these solutions don't work on newer android versions. Perhaps google has disabled the ability to change the theme.

Sources: 
https://developers.google.com/android/reference/com/google/android/gms/common/AccountPicker
https://stackoverflow.com/questions/28237798/change-style-of-google-play-services-accountpicker-dialog/32219725
https://stackoverflow.com/questions/22047940/android-accountpicker-set-light-theme

**Comment by grzesiek2010** [comment]
Ok it seems like we can't fix this indeed so i'm going to add won't fix label. Thanks for investigating the issue.
