### ISSUE TITLE
Can't update gradle/android gradle plugin

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3732]
#### Problem description
in https://github.com/opendatakit/collect/pull/3728 I updated a lot of dependencies as after every release. However I sipped [gradle](https://github.com/opendatakit/collect/blob/master/gradle/wrapper/gradle-wrapper.properties#L7)/[android gradle plugin](https://github.com/opendatakit/collect/blob/master/build.gradle#L9) because I ran into a problem:

'
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':collect_app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':collect_app:debugCompileClasspath'.
   > Failed to transform file 'nbi-stubs-1.0.0.aar' to match attributes {artifactType=android-classes, org.gradle.usage=java-api}
      > Execution failed for AarToClassTransform: /home/nik/.gradle/caches/transforms-2/files-2.1/55819e8a03778985b5116304fc094d03/jetified-nbi-stubs-1.0.0.aar.
         > entry 

It's the same users has been reporting on the forum recently:
https://forum.opendatakit.org/t/build-failed-cause-entry/25552/

https://forum.opendatakit.org/t/failed-to-transform-file-nbi-stubs-1-0-0-aar-to-match-attributes/25233/

#### Steps to reproduce the problem
It would be good to start from https://github.com/opendatakit/collect/pull/3728 and update gradle and android gradle plugin to their newest versions.

**Comment by grzesiek2010** [comment]
@seadowg do you want to take a look? I couldn't fix it...

**Comment by seadowg** [comment]
This seems related to changed made back in #3108. I can take a look later and see if it makes any sense. Probably some changes to Gradle that mean we have to change something about those stubs.

**Comment by grzesiek2010** [comment]
> This seems related to changed made back in #3108

I know that but couldn't handle it.

**Comment by seadowg** [comment]
Had a play with a few different things (mostly based on 3.6.0 changes) to see if I could fix this:

* Disable jetifier for the .aar file (`android.jetifier.blacklist=nbi-stubs-1.0.0.aar`)
* Disable the new APK creator (`android.useNewApkCreator=false`)
* Compress native libs (`android:extractNativeLibs="true"`)

Nothing fixing this as of yet but will dig a little deeper tomorrow. Wondering if it could be that the .aar we're building is invalid in someway and we've been getting away with it.

**Comment by seadowg** [comment]
@shobhitagarwal1612 guessing that was a mistake?

**Comment by shobhitagarwal1612** [comment]
Sorry, did that by mistake while browsing it on phone

**Comment by seadowg** [comment]
Playing around with this some more I'm pretty sure it's that our `.aar` with the stubs is just wrong.  AARs do have some mandatory contents (https://developer.android.com/studio/projects/android-library.html#aar-contents) and I can get this working by copying the jni stubs into our source code directly (into `collect_app/src/main/jniLibs`). 

I'll look at moving our stubs into a gradle submodule (so they're not in the main code) and then make a PR!
