### ISSUE TITLE
ODK Collect 1.26 error after taking  a picture

### ISSUE THREAD

**Issue by EduWF** [getodk/collect#3733]
#### Software and hardware versions 
Collect version 1.26. Android version is unknown.

#### Problem description
Upon submission the form generates the following message (translated from Spanish)
"Attention, the form was not saved correctly. Attempt to invoke virtual method'int org.odk.collect.andoird.logic.FromCont rolle.validateAnswers(boolean)' on a null object reference". 
 
#### Steps to reproduce the problem
Filling out the form and taking a picture of a document.

#### Expected behavior
Move on to next question.

#### Other information 
Collect version 1.26 seems to be the one with bugs. The user tried version 1.25 and version 1.23.3 and they seem to be okay.

**Comment by grzesiek2010** [comment]
Hi @EduWF 
thanks for reporting the issue.

Is this something you can reproduce multiple times? I mean I'm sure you are if you are filling the same form, but if you kill the app and open the form again?

I think it's a random problem not related to v1.26 which might happen but one you open the form again as I mentioned above it shouldn't take place again.

**Comment by lognaturel** [comment]
@EduWF I also can't reproduce. Can you please try the same thing again as @grzesiek2010 suggested? If you can reproduce, please re-open the issue and share the form and Android version.

**Comment by EduWF** [comment]
Thank you for your reply. The user restarted the device and reinstalled the
app. All is working fine now.
