### ISSUE TITLE
Provide submission summary when tapping a submission on the form map

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3737]
Currently, tapping on a submission from the form map opens that submission for viewing or editing. Instead, it should be possible to see:
- the instance name
- the current instance status
- the last status change time
- the tappable action that can be taken on the form (view, edit, etc)

Future extensions may include:
- displaying the first image from the submission
- displaying a user-specified image from the submission
- displaying user-specified fields from the submission

Todo:
- [x] design basic user interface and share on forum

**Comment by grzesiek2010** [comment]
I started working on the issue from looking for a good way to display such a summary.
There are two options to do that:
### InfoWidows
![image](https://user-images.githubusercontent.com/3276264/78348488-6782d280-75a2-11ea-8acd-33f7ea1cce31.png)
the image above comes from google docs so it presents google maps,we also use Mapbox and OSMDroid both also provide their own infowindows.

### BottomSheet
It would be something like (the content is just hard-coded):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3276264/78348663-b92b5d00-75a2-11ea-86a2-cd9417cc5d19.gif)


The implementation with BottomSheet seems like a right solution to me at least for two reasons:
- we could add one BottomSheet and use it in `FormMapActivity`, if we wanted to use infowindows it would require implementing them in all MapFragment separately
- BottomSheet gives us more space to display instance details, buttons to open an instance etc.

@lognaturel should I open a topic on the forum?

**Comment by lognaturel** [comment]
Thanks, @grzesiek2010, I agree with your conclusions. I think your first point about having to implement overlays separately for each map provider makes it especially clear that a bottom sheet is the way to go.

I'd say we should base the design either on Google Maps or on [the Material Design standard bottom sheet](https://material.io/components/sheets-bottom/#standard-bottom-sheet). I don't feel particularly strongly about which. How to display the action is probably the other biggest design question (what kind of button, etc).

Sharing on the forum once you have a basic draft of how all the information should be displayed sounds great to me.
