### ISSUE TITLE
Add custom Firebase Performance traces or remove dependency

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3739]
Firebase Performance monitoring was added some time ago. Currently we only collect the default traces and that information has not been actionable. At the same time, the dependency has caused issues for various contributors (e.g. https://github.com/opendatakit/collect/blob/master/docs/WindowsDevSetup.md#known-issues). For v1.27, we should either [add actionable custom traces](https://firebase.google.com/docs/perf-mon) or remove the dependency.

One actionable trace I can think of is registering form load time. We know that some folks are spending a long time loading forms. It would be great to know what the range of load times are. It would also be helpful to get separate traces for load time during initial metadata discovery, cache building time, and time to load form from cache. We won't know anything about the form definitions but we'll be able to answer questions like:
- How common is it to get a multi-minute load time?
- What kinds of devices are used that take the longest time?
- Does the cache generally help?

Some other:
- loading select lists
- loading the image map widget
- finalizing a submission
- loading the form submission map

**Comment by rajkumaar23** [comment]
I would like to work on this.

**Comment by lognaturel** [comment]
Hi @rajkumaar23! Are you still interested in this issue? In general, you can go ahead and claim issues with `help wanted` or `good first issue` tags! Learn more in the [contribution guide](https://github.com/getodk/collect#contributing-code).

**Comment by SaumiaSinghal** [comment]
Hi @lognaturel! I would like to work on this, if no one else is working on it.

**Comment by rajkumaar23** [comment]
@SaumiaSinghal I'm not working. You can go ahead and try :) Also, you can claim this issue using @getodk-bot

**Comment by SaumiaSinghal** [comment]
Thanks @rajkumaar23 for letting me know. :)

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
