### ISSUE TITLE
Add Spotbugs back in

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3740]
We recently had to remove Spotbugs because of an [issue on their side](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/90). We should see if this is something we can work around or if not wait for a fix.

**Comment by SaumiaSinghal** [comment]
Hi @seadowg! I would like to look into it.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
@SaumiaSinghal ooops I left out that it was removed in #3728 so good to use that as a starting point rather than `master`

**Comment by grzesiek2010** [comment]
Spotbugs does not work well with kotlin so now as we add all the new code using kotlin I think it doesn't make sense to add spotbugs back.
