### ISSUE TITLE
The first answer is removed even if a user tries to remove another answer from the field-list

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3751]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
The firs answer is removed even if a user tries to remove another answer from the field-list.

#### Steps to reproduce the problem
Test the attached form (try to remove the second answer): 
[fl.xml.txt](https://github.com/opendatakit/collect/files/4408637/fl.xml.txt)

**Comment by mmarciniak90** [comment]
This case worked as expected on v1.25.1
