### ISSUE TITLE
Color of the line under the `Saved Forms` and `Blank Forms` on Delete Saved Form view is blue instead of the consistent color for a color scheme on dark mode

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3759]
#### Problem description
Color of the line under the `Saved Forms` and `Blank Forms` on Delete Saved Form view is blue instead of the consistent color for a color scheme on dark mode

#### Steps to reproduce the problem
1. User sets dark mode
2. User goes to `Delete Saved Form`
3. The line under `Saved Forms` and `Blank Forms` is blue in dark mode 

![Screenshot_2020-04-02-20-50-20-091_org odk collect android](https://user-images.githubusercontent.com/3907554/78290285-cead7200-7523-11ea-9b4c-fc8179699c13.jpg)

#### Expected behavior
Color of the line under the `Saved Forms` and `Blank Forms` is consistent  with the color scheme on dark mode

Noticed during testing #3750

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim
