### ISSUE TITLE
EXIF metadata not stored in pictures taken with Android 6.0.1 native camera app

### ISSUE THREAD

**Issue by racetiger** [getodk/collect#3780]
#### Software and hardware versions 
Collect v1.26.2, Android v6.0.1, Nexus 5

#### Problem description
When taking pictures with the native Android Camera app through the [default image widget](https://docs.opendatakit.org/form-question-types/#default-image-widget), the resulting picture has no EXIF metadata.

Taking simultaneously a picture with the same device in the same place with the same app saves the EXIF metadata without any problem

#### Steps to reproduce the problem
- download the "All widgets" form from the ODK Aggregate Demo server
- go to the "Image widget" question
- click on the "take a picture" button, choose the native Android Camera App, and save the picture
- back to ODK collect, save the form
- use an EXIF capable app (e.g [Photo EXIF Editor](https://play.google.com/store/apps/details?id=net.xnano.android.photoexifeditor&hl=en)) to display the EXIF metadata of the picture 
- there's no EXIF information at all there.

#### Expected behavior
the picture should have the EXIF information saved when taking the picture through ODK with the EXIF capable native camera app.

#### Other information 
Other users in my organization faced the same issue with different devices.
Using a different camera app (like Open Camera) fixes the problem.

**Comment by ItloMd9** [comment]
@getodk-bot claim

**Comment by ItloMd9** [comment]
Dear @lognaturel , 
I have not received the invitation for the ticket yet.
Could you please check

**Comment by lognaturel** [comment]
I hadn't noticed that our bot seemed to misbehave. I've assigned you. Welcome and please let us know if you have any questions!
