### ISSUE TITLE
Performance improvement suggestion 

### ISSUE THREAD

**Issue by cataloque** [getodk/collect#3781]
#### Software and hardware versions 
Collect v1.2.2

#### Problem description
They could affect performance.
In the position of  code:
org.odk.collect.android.utilities.FileUtils: android.graphics.Bitmap getBitmapScaledToDisplay()，
bitmap object is created with the invocation of decodeFile().
In the position  code:
org.odk.collect.android.widgets.GridWidget.getView() 
getBitmapScaledToDisplay() will be called many times and new bitmap objects will be created continuously. We know that bitmap objects can consume a large amount of memory. This wastes a lot of CPU cycles in decoding and RAM in storing bitmap objects. On low end devices, GC will kick in frequently because of RAM pressure.

#### Expected behavior
Maybe we can use a memory cache and a disk cache to store the bitmap objects. Then app can reuse them instead of creating new bitmap objects continuously.In addition, since image decoding is slow, we can perform these operations in worker threads (e.g., via AsyncTask).
Looking forward to your response and hope this information is useful for you.
Could you kindly have a look at this issue? Thanks.

**Comment by seadowg** [comment]
@cataloque thanks for looking into this. As much as you're right about these operations being a potential performance hit it would be good to understand if you're actually experiencing any performance problems from them? 

As with any time, there are a finite number of things that can be improved, and so we need to prioritize work that addresses real world problems that people experience. I'm going to close this for the moment but please feel free to reopen if you have examples of devices or forms that are running experiencing performance problems.
