### ISSUE TITLE
Can not send data to ODK Aggregate

### ISSUE THREAD

**Issue by RohitPatnaik** [getodk/collect#379]
Hello All,

While sending data to ODK Aggregate from ODK Collect we face the following error: 

**Error: Generic Exception: Invalid use of BasicClientConnManager: connection still allocated. Make sure to release the connection before allocating another one.** 

Thanks.

**Comment by yanokwa** [comment]
Please answer the following questions...

1. Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

2. Steps to reproduce the problem

3. Other information 
Things you tried to fix, stack traces

**Comment by yanokwa** [comment]
Closed due to lack of information. 

@RohitPatnaik, if you provide the needed information, we'll gladly re-open the issue.
