### ISSUE TITLE
Upload coverage reports to codecov.io

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3796]
Now we are sharding our tests on Firebase Test Lab we get a coverage report for every shard (rather than just one for all the connected tests). In Circle CI we were previously copying the coverage report we downloaded from Firebase with this line (in `.circleci/config.yml`):

```
mkdir -p collect_app/build/outputs/code-coverage/connected && cp firebase/Pixel2-27-en-portrait/artifacts/coverage.ec collect_app/build/outputs/code-coverage/connected/coverage.ec
```

The new reports are downloaded as part of our `test_instrumented` job and are stored for each shard in `firebase/Pixel2-27-en-portrait-shard_x/artifacts/sdcard/coverage.ec` where `x` is the shard number. This means we need to either find some way to include these files as part of our `jacocoTestReport` gradle task or work out a way to merge them before running it.

This should be fixable without modifying CI by downloading coverage files locally (not all 50 just a couple) and then putting together a workflow for merging and uploading to codecov.io. Once we've done that we can make changes that let us automate the upload in Circle CI.

**Comment by shobhitagarwal1612** [comment]
@getodk-bot claim

**Comment by lognaturel** [comment]
Test coverage master @shobhitagarwal1612 to the rescue! 🎉 🙏

**Comment by shobhitagarwal1612** [comment]
I couldn't find any coverage file (`coverage.ec`) in the output of the [shards](https://circleci.com/api/v1.1/project/github/getodk/collect/8832/output/104/0?file=true&allocation-id=5ebd8c1c80666d21e3a600b4-0-build%2F5475A68A)

**Comment by shobhitagarwal1612** [comment]
The last time they were generated was 27 days ago ([workflow](https://app.circleci.com/pipelines/github/getodk/collect/162/workflows/75b99952-bf24-4985-8457-5a6c916b59ae/jobs/8564))

**Comment by seadowg** [comment]
There seems to be a problem with the codecov upload so I'm reopening this. Hopefully we're able to get this working in a docker image now but I'm not sure how the codecov auth works.

**Comment by shobhitagarwal1612** [comment]
The problem seems to be in the report generation step [link](https://app.circleci.com/pipelines/github/getodk/collect/284/workflows/e5d42b25-efea-491d-b416-5be1a9e9e7bd/jobs/8907)

Specifically, the failure is caused by:
```
> Task :collect_app:generateDebugUnitTestConfig
> Task :collect_app:testDebugUnitTest
> Task :collect_app:testDebugUnitTest FAILED
```

`./gradlew -PciBuild=true -PenableJacoco=true jacocoTestReport` runs unit tests again. That seems obsolete. Maybe we should try fixing that first.

**Comment by seadowg** [comment]
I doubt we'll be looking at this any time soon. We haven't really felt any need for coverage analysis over the last couple of years (although it would be nice to have). In fact, I'm going to submit a PR that removes Jacoco entirely, as we really shouldn't bother with Gradle plugins we're not actually using.
