### ISSUE TITLE
Adding new repeat groups using the plus icon is broken

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3798]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Adding new repeat groups using the plus icon is broken. I discovered the issue working on #3016 so to reproduce we can use the form attached there.

#### Steps to reproduce the problem
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/3276264/79989427-1fbfde80-84b0-11ea-9e92-dbb91c628ee8.gif)

**Comment by lognaturel** [comment]
Can you please wait until #3656 is merged and then verify again? That behavior gets touched there.

**Comment by grzesiek2010** [comment]
It's still visible after merging #3656

**Comment by lognaturel** [comment]
I can't reproduce on master. Is it possible that you're using JavaRosa master rather than released JavaRosa?

**Comment by grzesiek2010** [comment]
Can't reproduce using the current master so I'm closing maybe I have made a mistake recently and didn't pull newest changes...

**Comment by lognaturel** [comment]
Since you saw this working on #3016, I wonder whether it could be an issue with JavaRosa master. Let's make sure to try this as soon as we merge in a snapshot for the next JR version.
