### ISSUE TITLE
Collect crashes when user removes all repeat groups and clicks on device back button

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3799]
#### Software and hardware versions 
Collect v1.25.1 (older versions were not verified)

#### Problem description
Collect crashes when user removes all repeat groups and clicks on device back button

#### Steps to reproduce the problem
1. User starts form [nested-repeats.xml.txt](https://github.com/getodk/collect/files/4519317/nested-repeats.xml.txt)
2. User adds one group
3. User goes to hierarchy view
4. User clicks on bin
5. User sees empty hierarchy view
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/80042194-a8fe0200-84fe-11ea-8d54-161954fa9bb7.png">

6. User clicks on the device back button
7. Collect crashes

##### Alternative case
1. User starts form [repeatTest.xml.txt](https://github.com/getodk/collect/files/4519385/repeatTest.xml.txt)
2. User adds one group
3. User goes to hierarchy view
4. User clicks on bin
5. User clicks on the device back button
6. User is moved to form, dialog 
7. Error dialog is visible in background
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/80042784-31c96d80-8500-11ea-9eb2-f2a5e39f1226.jpg">

#### Expected behavior
Question dialog allowing to add group should appear without errors and crashes

#### Notes
Noticed during testing #3656

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/getodk/collect/pull/3912
