### ISSUE TITLE
How to Link 2 or more forms in odk and share data offline to another smartphone

### ISSUE THREAD

**Issue by caryvane** [getodk/collect#3800]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by caryvane** [comment]
Hi everybody
1-) Please since few years people are looking for a way to link 2 or more odk forms in odk 1. The fact is that I have found some open codes to add some new functions inside my odk 1 and these open codes don't work on odk X-tools since it uses a different programming language. If I decide to use odk X-tools because of its ability to links 2 or many forms, I loose all others functions I have added in odk 1.

2-) I am also looking for open codes for odk 1 to share offline data from a device to another, as Trebleshot (an Androïd app) do.

I must confess I am not a developper! 
Thanks

**Comment by lognaturel** [comment]
Please take a look at https://github.com/getodk/skunkworks-crow to see whether it could meet your needs. It is not an official ODK tool but a lot of good thought has gone into it. 

For further general support inquiries like this please use [the forum](https://forum.getodk.com).

**Comment by caryvane** [comment]
Hi lognaturel.
Thank you for your very helpfull answer. It is great...i am so happy

**Comment by caryvane** [comment]
> Please take a look at https://github.com/getodk/skunkworks-crow to see whether it could meet your needs. It is not an official ODK tool but a lot of good thought has gone into it.
> 
> For further general support inquiries like this please use [the forum](https://forum.getodk.com).

Excellent
