### ISSUE TITLE
Upgrade to the new Firebase Crashlytics

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3807]
#### Problem description
The topic from the forum https://forum.getodk.org/t/fixing-leaks-in-collect-app/26137/3 made me thinking what actually fabric is for. I took a look at the documentation and found out that it's needed fro crashlytics but now it's legacy and we can switch to the new [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android) and get rid of fabric.

@lognaturel @seadowg any thoughts pros/cons?

**Comment by seadowg** [comment]
It looks like it's beta but I think once it goes "1.0" I don't see a reason not to switch.
