### ISSUE TITLE
Authorization Basic not added in header during form upload post request

### ISSUE THREAD

**Issue by vishwa1937** [getodk/collect#3809]
#### Problem description
I am currently facing  a problem during uploading/sending form using POST (over HTTPS) the authorization basic is not added in header. But when i send request to get/download forms it is adding auth basic in header. 

#### Expected behavior
Need to add basic auth in header during form upload.

**Comment by seadowg** [comment]
@vishwa1937 could you post what Collect version you're using and what server you're uploading to?

**Comment by seadowg** [comment]
@vishwa1937 are you still seeing this problem?

**Comment by seadowg** [comment]
@vishwa1937 I'm going to close this for the moment but please let us know if you're still running into problems.
