### ISSUE TITLE
Not all settings are imported from older Collect versions

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3811]
#### Software and hardware versions 
Collect v1.26.2 (and Collect v1.22.0)

#### Problem description

Settings that have been migrated in someway (in their storage in Android's `SharedPreferneces`) aren't imported correctly when going from an old version (before they were migrated) to a new version (after they were migrated).

#### Steps to reproduce the problem

1. Open Collect 1.22.0
2. Change the Map SDK (General Settings > User interface > Mapping SDK) to "OpenStreetMap SDK"
3. Open Collect 1.26.2 
4. Change the Map SDK (General Settings > Maps > Source) to  "Google"
5. Scan the QR code from Collect 1.22.0 in Collect 1.26.2

You'll see that the Maps "Source" is still "Google" rather than "OpenStreetMap".

#### Expected behavior

Settings that had preference migrations applied to them should still import correctly from QR codes or settings files. This means that the import code (potentially `PreferenceSaver`) needs to perform the migrations in `PrefMigrator` in someway.

**Comment by seadowg** [comment]
@grzesiek2010 have you made any progress on this? It looks like we probably need this fixed for #3818 and I think this should really follow on from changes in #3813 so I'm happy to take this on if not!

**Comment by grzesiek2010** [comment]
Not yet do you want to fix it as a part of #3813 if so no problem.

**Comment by seadowg** [comment]
Yeah I can build on top of that! Thanks.
