### ISSUE TITLE
Simplify Server settings screen by removing Other type and replacing ODK Aggregate with ODK

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3812]
See description at https://forum.getodk.org/t/collect-server-settings-screen-remove-other-server-type-and-replace-odk-aggregate-with-odk/26299

This should not involve any changes to the settings keys because server types ODK Aggregate and Other currently share the URL/username/password parts of their configurations.

While here, it will likely make sense to migrate settings to the androidx libraries.

**Comment by seadowg** [comment]
![](https://media.giphy.com/media/3ornk57KwDXf81rjWM/giphy.gif)

@getodk-bot still working on it my little friend

**Comment by seadowg** [comment]
![](https://media.giphy.com/media/3ornk57KwDXf81rjWM/giphy.gif)

@getodk-bot still working on it my little friend

**Comment by seadowg** [comment]
Finishing the last part of this (converting the prefs screen to AndroidX) keeps getting pushed back as other things come up. I think it'd be best to admit defeat here and make a new issue for the conversion. After looking at it again I think there needs to be more test coverage written up before ripping the screen apart and I think it'd be better to write those tests and do the conversion as part of some user visible work. 

Sound good @lognaturel? If you agree I think we can close this and then just post a PR with my fix for #3901.

EDIT: And we should just add a note to the `STATE.md` about moving to AndroidX.

**Comment by lognaturel** [comment]
Yes, that sounds good to me.
