### ISSUE TITLE
User can leave Server settings without Google account not set dialog after importing QR Code

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3825]
#### Software and hardware versions 
Collect v1.26, previous versions, Android v probably all except 5.1.x.x, device used...

#### Problem description
Google account not set dialog is not displayed after scanning qr code with Google Drive selected as settings

#### Steps to reproduce the problem
1. On the first device select Google Drive server type and select Google account
2. On the second, scan qr code with settings from the first one
3. On the second device open Server settings: Google account is empty
4. Choose back button

#### Expected behavior
User should not be able to leave server settings when Google Drive is selected without choosing Google account - error message should be displayed. 

#### Other information 
Weird thing is that only on Android 5 Google account is actually imported via qr code, it might be connected to permissions somehow.

**Comment by seadowg** [comment]
We're not currently focused on improving Google Drive flows so closing this.
