### ISSUE TITLE
Instance map view improvements

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3828]
#3778 adds a summary view when tapping an instance on a form's instance map. This issue is to track enhancements to that view:
- grow the selected marker icon ~and make it red~, same as in Google Maps
- dismiss bottom sheet on back button press
- dismiss the bottom sheet if there's a tap that's not on a map button or on an instance
- maintain the bottom sheet on device rotation

**Comment by mmarciniak90** [comment]
Use case:
1. Mapbox / OSM is set
2. User opens form's instance map
3. User selects marker icon to see details
4. User minimizes app or locks the screen
5. User returns to app

Actual result:
The bottom sheet is moved down a bit

**Comment by mmarciniak90** [comment]
Use case:
1. `Moving backwards` option is unselected
2. User opens form's instance map
3. User selects marker icon with Saved / Finalized / Failed status to see details
4. `View Send Form` button is visible

Actual result:
Text on the button is misleading. Submission is not sent.

**Comment by grzesiek2010** [comment]
@lognaturel could you clarify this:
> dismiss the bottom sheet if there's a tap that's not on a map button or on an instance

I'm not sure if I understand... should we hide the bottom sheet when a user taps on a map just?

**Comment by lognaturel** [comment]
Yes, if the user taps just on the map at a spot that doesn't have an instance marker, we assume they want to dismiss the bottom sheet so they can see more of the map, pan around, etc. See Google Maps for what I mean. This is particularly important on a small screen since the slide down gesture is not entirely intuitive.

**Comment by grzesiek2010** [comment]
> grow the selected marker icon and make it red, same as in Google Maps

the red one is already used so I decided to just grow the selected one without changing its color.

**Comment by grzesiek2010** [comment]
I have found one more case that should be improved:
When we use the pin marker the center of the icon points to a saved location what look very misleading. For example I saved a form in Gdańsk (northern Poland by the Baltic Sea) but when I zoom out the map and especially if I click on a marker what makes it bigger it points to the center of Poland or even almost to Czech Republic:

![Screenshot_1592471912](https://user-images.githubusercontent.com/3276264/85003241-3f911d00-b156-11ea-8211-f16835943554.png)
![Screenshot_1592471915](https://user-images.githubusercontent.com/3276264/85003245-40c24a00-b156-11ea-89e5-4ca2613c8e9b.png)

I'm going to fix this.

**Comment by grzesiek2010** [comment]
> I have found one more case that should be improved:
When we use the pin marker the center of the icon points to a saved location what look very misleading. For example I saved a form in Gdańsk (northern Poland by the Baltic Sea) but when I zoom out the map and especially if I click on a marker what makes it bigger it points to the center of Poland or even almost to Czech Republic:

should be fixed now.

**Comment by lognaturel** [comment]
Good call on that last one.
