### ISSUE TITLE
Crazy calendar - missing and extra days in Oct 2016 Sao Paulo timezone

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#383]
#### Software and hardware versions 
Collect v1.4.14

#### Problem description
15.10 occurs two times in the calendar. 
22.10 doesn't exists.

#### Steps to reproduce the problem
1. Change time zone to Sao Paulo
2. Use DateWidget or DateTimeWidget
3. Enter "Oct 2016"

#### Other information 
![screenshot_2017-01-25-22-02-00](https://cloud.githubusercontent.com/assets/3276264/22314854/b179cc9c-e363-11e6-9cfc-c7f9002a7f85.png)

**Comment by lognaturel** [comment]
This seems like it's almost certainly daylight savings time related. October 16th was the daylight savings time change date in 2016 - https://www.timeanddate.com/time/zone/brazil/sao-paulo

**Comment by grzesiek2010** [comment]
Right and probably we can't fix this but it's good to know about this issue. I checked the same using DatePickerFragment (an other app) and using Google Calendar and it works well (if we use a spinner instead of a calendar it works ok too) so it's only related to the calendarView in DatePicker as I think.

**Comment by lognaturel** [comment]
Great, seems right that it's a bug in a deeper level. I'll close the issue but it's good to have a record of it in case other people experience it.

**Comment by grzesiek2010** [comment]
I noticed something even stranger - missed first week Jan/1940 in Nairobi timezone.
![screenshot_2017-02-24-12-57-43](https://cloud.githubusercontent.com/assets/3276264/23299103/805e9348-fa80-11e6-9e46-e9507f44cfc7.png)
