### ISSUE TITLE
Collect crashes when open blank form on v1.27.0 beta 0

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3836]
#### Software and hardware versions 
Collect v1.27.x, Android all from 5.1 to 10 device used...

#### Problem description
Collect crashes when try to open blank form.

#### Steps to reproduce the problem
1. Download any form
2. Go to Fill Blank Form
3. Click on Downloaded form

#### Expected behavior
The app should not crash, user should be able to fill form

**Comment by kkrawczyk123** [comment]
@getodk-bot label "high priority"
@getodk-bot label "regression"

**Comment by kkrawczyk123** [comment]
@grzesiek2010 @seadowg Could you take a look at that as the first thing in your morning as it's a blocker for release testing.

**Comment by seadowg** [comment]
We're not seeing this on master so it's probably only in a release build type. Could be something to do with ProGuard. I'm guessing it's [this crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/bd4f5ba3bf650b9bb26c469b91e8ceb7?time=last-seven-days&sessionId=5EBE4D700141000116326742CDED275B_DNE_0_v2) but I'm confused as to why that would happen in the release build and not master. Will keep in investigating.
