### ISSUE TITLE
Crash on creating repeat

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3844]
Discovered on Firebase: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/dd74083d67f410ebf91ab087006aac32?time=last-seven-days&sessionId=5EC0D6D4012900012EF581F660321501_DNE_0_v2

#### Software and hardware versions 
Collect v1.27.0 Beta 1

#### Problem description

It looks like Collect is crashing when adding repeats from the hierarchy view if "Don't keep activities" is enabled (probably originally happened on a low mem device).

#### Steps to reproduce the problem

1. Enable "Don't keep Activities" in Developer Settings
2. Open any form with repeats
3. Open Hierarchy view and navigate to the repeat group
4. Click ➕
5. Click "Add"

#### Expected behavior

The Add Repeat dialog should not be shown and the app should not crash when the repeat is added.

**Comment by grzesiek2010** [comment]
There must be another way to reproduce the issue because it's still visible on v1.27.0. Fewer reports but still: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/348ba62150925a6e0907635c0c7767a2?time=last-seven-days&sessionId=5ED5EB72012A00017C1E397FA2DD633D_DNE_0_v2

**Comment by seadowg** [comment]
@grzesiek2010 could we create a new issue for this as presumably the reproduction steps are going to be different? Unless you can still reproduce that way?

**Comment by grzesiek2010** [comment]
I'll try to reproduce the issue and then if steps differ or I'm not able to do that at all I'll create a separate issue.

**Comment by grzesiek2010** [comment]
I'm not 100% sure it's the same but I was able to reproduce this https://github.com/getodk/collect/issues/3897 so let's close again.
