### ISSUE TITLE
Broadcast of Intent { act=com.mapbox.scheduler_flusher flg=0x14 (has extras) }

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3846]
#### Software and hardware versions 
Collect v1.27.0-beta

#### Problem description
The QA team has been reporting that there are more ANRs in the newest version. I investigated the issue and discovered that there is one new ANR that is the most common one now and and it's probably this.

`Broadcast of Intent { act=com.mapbox.scheduler_flusher flg=0x14 (has extras) }`

https://play.google.com/apps/publish/?account=6923365842552008664&dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=3782&errorType=ANR&clusterName=apps/org.odk.collect.android/clusters/17827f0f&detailsAppVersion=3782&detailsSpan=7

I guess it has something to do with [Display mapbox map to perform initialization](https://github.com/getodk/collect/pull/3819/commits/9cede13f5ad9e5f060cdd2941a1a8720903b287b)

I was able to find two similar issues on the internet:
https://github.com/mapbox/mapbox-gl-native-android/issues/263
https://github.com/mapbox/mapbox-events-android/issues/310

in the firs one there is a comment:
> the com.mapbox.scheduler_flusher stems from Telemetry.

in the second one the author claims that adding:
`-keep class com.mapbox.android.telemetry.** { *; }`
fixed the issue but also someone else claims that it shouldn't be needed because it is already fixed in mapbox... maybe the issue is back?

Should we try or you have better ideas @lognaturel  @seadowg?

**Comment by seadowg** [comment]
My first instinct is that we should take the Mapbox initialization code out and then try and push these issues back to the Mapbox team (it looks like they are pretty engaged in their open source projects). The amount of working around here feels pretty risky to me. However it looks like we don't have analytics on which map providers our users are using (maybe I missed them though) that would help me understand the cost/benefit. I guess ultimately I feel like we're trying to make Mapbox do something it really doesn't want to do. I'd be keen for us to start looking at other flows to get map offline basemaps working (maybe have the user trigger initialization for instance).

All that said I'd be happy to go with the ProGuard change if you both feel it's worth the risks of other things going wrong to get offline Mapbox in there.

**Comment by lognaturel** [comment]
We know from looking at our Mapbox API usage that Mapbox has been used very little until now. Currently we know there's a big deployment using it.

A lot of ~crashes~ ANRs that look like this are still being logged. https://play.google.com/apps/publish/?account=6923365842552008664#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=3803&errorType=ANR&clusterName=apps/org.odk.collect.android/clusters/b993eb3d&detailsAppVersion=3803&detailsSpan=7

No one has explicitly complained about ANRs or crashes but it seems they're happening at a high frequency affecting hundreds of users. I do think we should consider removing the initialization. What do y'all think?

**Comment by seadowg** [comment]
@lognaturel not able to access that page. I'd vote yes if we're seeing high numbers of crashes!

**Comment by grzesiek2010** [comment]
Those are ANRs not crashes. 
Taking into account that:
- it probably takes place during initializing mapbox and we do that only once (we have a key that checks it)
- there are 264 reports / 251 impacted users

looks like it happens often but just once for a single user so I think it's not a big problem.

**Comment by lognaturel** [comment]
> Those are ANRs not crashes.

Yes, sorry, I've been speculatively connecting some dots in my head and didn't lay all that out here. 

We have about the same rate of crashes in native Mapbox code and I think they may be related to the ANRs. Like maybe the initialization hangs for a while and then eventually crashes or something like that. The crashes also look like they're happening once per user so that may be why we don't get reports -- users have the app stop responding and close on them. Then they reopen it, and then they don't worry about it.

I've posted at https://github.com/mapbox/mapbox-gl-native-android/issues/126 in case it could be related.

**Comment by lognaturel** [comment]
To be clear: not a huge priority but I think we should keep the issue open and see if we can learn more. I think the next step is seeing whether/how Mapbox folks respond.

**Comment by lognaturel** [comment]
According to https://github.com/mapbox/mapbox-gl-native-android/issues/126#issuecomment-650708237, this is almost certainly because we don't destroy the `MapView` that's created for initialization purposes. I don't know why we can't reproduce. but I think we should add the `destroy` at least for v1.28 but perhaps even as another point release.
