### ISSUE TITLE
Fix visual issues in Magenta theme

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3849]
The new "experimental" Magenta theme has some visual issues that will need to be fixed before it's ready for primetime:

- [x] Some dialogs in the app use the wrong button styles:

<img alt="" width="40%" height="40%" src="https://user-images.githubusercontent.com/3907554/81072644-ba73e080-8ee6-11ea-81cc-7a6cbe761aa1.png">

- [x] Search bar has extra 🔍 icon in "Delete saved form" search

<img alt="" width="40%" height="40%" src="https://user-images.githubusercontent.com/3907554/81071364-e5f5cb80-8ee4-11ea-99da-7010ef6216ed.png">

- [x] Search view text colors are wrong (see screenshot above)

- [x] On magenta view scroll is not visible until you actually start to scroll what differentiates it from the other modes

It's totally fine if picking this up to just solve one of the issues!

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim

**Comment by mmarciniak90** [comment]
I would like to improve consistent. The magenta theme should follow other themes when issue #3919  will be merged.

1. Capital letters should be visible in tabs on all themes
2. Tab background color should be identical with the form list background color on all themes theme.

| light mode | dark mode | magenta mode|
|---|---|---|
![Screenshot_20200624-123656](https://user-images.githubusercontent.com/3907554/85549652-7ec0e180-b620-11ea-922f-3ab2742731c0.png)|![Screenshot_20200624-123713](https://user-images.githubusercontent.com/3907554/85549655-7f597800-b620-11ea-9ddf-dfe3b6bc8331.png)|![Screenshot_20200624-123734](https://user-images.githubusercontent.com/3907554/85549657-7ff20e80-b620-11ea-83b6-73d502c16790.png)
![Screenshot_20200624-123645](https://user-images.githubusercontent.com/3907554/85549766-9a2bec80-b620-11ea-9a85-4799ae4ea890.png)|![Screenshot_20200624-123707](https://user-images.githubusercontent.com/3907554/85549771-9ac48300-b620-11ea-9a9b-42554b5d3a7e.png)|![Screenshot_20200624-123726](https://user-images.githubusercontent.com/3907554/85549774-9b5d1980-b620-11ea-9ce6-f0e5dcc779b2.png)

**Comment by grzesiek2010** [comment]
> 1. Capital letters should be visible in tabs on all themes
> 2. Tab background color should be identical with the form list background color on all themes theme.

The difference stems from the fact that magenta uses Theme.MaterialComponents but light/dark mode not. I think we should first switch those modes to Theme.MaterialComponents as well. @seadowg is that on your todo list maybe or did you think about it?

**Comment by seadowg** [comment]
@grzesiek2010 My idea was to get Magenta feeling right and then we can basically redo the grey (light) and dark theme using the setup for Magenta but with those theme's respective colors. It might be that if people like Magenta it could become the default and we'd just have to make a new dark theme. 

@mmarciniak90 agree on the tab background - that looks off. I'm not sure about caps though. I think it's OK for the themes to have different approaches right now. Also, we've been leaning away from all caps styles across the app (as there seems to be a consensus that they are bad for accessibility reasons).

**Comment by kkrawczyk123** [comment]
I have noticed a few things that might be also considered for Magenta mode:
- Get Blank Form loading dialog: Cancel button is white for aggregate and pink for google drive
- if "turn on flashlight" button should stay pink in magenta mode
- on magenta view scroll is not visible until you actually start to scroll what differentiates it from the other modes

**Comment by seadowg** [comment]
@kkrawczyk123 nice finds! Yeah I think we should fix all of these.

**Comment by seadowg** [comment]
> if "turn on flashlight" button should stay pink in magenta mode

@kkrawczyk123 what did you mean by this?
