### ISSUE TITLE
Allow the autocomplete appearance with the same behavior as search for select ones

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#386]
`search` is currently a valid appearance for select ones. Add an `autocomplete` appearance with the exact same behavior.

The code is [here](https://github.com/opendatakit/collect/blob/eb8243b6d381239e46689183b71836e576c86ad8/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L182). The change simply requires also testing for the string "autocomplete". [This commented out code](https://github.com/opendatakit/collect/blob/eb8243b6d381239e46689183b71836e576c86ad8/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L163) should also be removed.

See also XLSForm/xlsform.github.io#79.

**Comment by marcos-lg** [comment]
Hi, I would like to work on this issue if nobody is working on it yet.
