### ISSUE TITLE
All buttons look like active but do not respond with Mapbox map when Internet connection is not available 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3878]
#### Software and hardware versions 
Collect v1.25 (older versions were not verified)

#### Problem description
All buttons look like active but do not respond with Mapbox map when Internet connection is not available 

#### Steps to reproduce the problem
1. Install the app without Internet connection.
2. Select Mapbox in General Settings -> Maps.
3. Go to All widgets for and open some widget with map appearance OR map view with submissions
4. All buttons are active 
5. Buttons don't respond

|![Screenshot_20200528-105823](https://user-images.githubusercontent.com/3907554/83121640-e0019d80-a0d2-11ea-938e-9e2e6e08d8d1.png)|![Screenshot_2020-05-28-10-44-03-112_org odk collect android](https://user-images.githubusercontent.com/3907554/83121641-e09a3400-a0d2-11ea-924e-7ad1cde624b4.jpg)|
|---|---|

#### Expected behavior
Only proper buttons are active, eg. Trash button should be inactive because there is nothing to clear

#### Other information 
Noticed while testing #3869

**Comment by grzesiek2010** [comment]
1. First of all those buttons always look like inactive (gray color). Some time ago I reported an issue [Refresh map icons](https://github.com/getodk/collect/issues/3202) and I still think it would by a nice improvement.
2. We need to distinguish two cases:
- **no internet** (but the provider has been initialized before), maybe some maps has been cached, we can use offline maps so those buttons shouldn't be disabled.
- **not initialized map provider** in this case those buttons are almost useless that's right but GPS still works and a user for example can still record traces/shapes automatically so still it might be kind of useful in case where a user is in a remote area and forgot to initialize maps

taking that into account I would first refresh those buttons and then try to disable/enable them based on the provider state.

Thoughts @lognaturel @seadowg ?

**Comment by seadowg** [comment]
Yeah I think I agree. It would be hard to do inactive/active button state right now. It'd probably also make sense to show a warning snackbar (or something similar) in these semi-broken states right?

**Comment by grzesiek2010** [comment]
> It'd probably also make sense to show a warning snackbar (or something similar) in these semi-broken states right?

yes, but I'm afraid it won't be trivial to determine if a provider has been initialized, I need to check it.

**Comment by grzesiek2010** [comment]
We have updated those buttons so I'm closing this issue.
