### ISSUE TITLE
View last submitted data at the time of filling up the form

### ISSUE THREAD

**Issue by ratikanta131** [getodk/collect#389]
We are filling up and submitting data of a particular form.

If again we need to fill up that particular form and we want to see what was the last answer for particular questions, we need this feature.

Suppose we are going to collect the data of a geographical location, after 1 year we are going collect data of that particular location again (of a particular form) and we want to see that last visit data, while filling of the form. 

In above kind of requirement we need this feature.

We will see the last visit data in the same question page.

**Practical Scenario:**
Last year average patient visited to X area hospital in a week is 100. Current year it is 70. When we are putting the value 70, we want to know last year it was 100.

#### Other information 
We have tried to pull last submission file from the server to instance folder then we are viewing the form like we view the Edit Saved Form. 

We have added an option (view last visit data) in the option menu, after tapping on that menu we are viewing last visit submission form. 

The problem in above approach is each time we want to see answer of one question, we have to open that(Edit Saved Form like) activity and scroll down to that question, again back and fill up current question.

**Comment by yanokwa** [comment]
@ratikanta-sdrc  Have you tried CSV preloading as described at http://xlsform.org/#pre-loading-csv-data. Why is that not adequate?

**Comment by grzesiek2010** [comment]
Now as we have [Remembering previously entered values](https://github.com/opendatakit/collect/pull/2882) we can close (especially that the author didn't even answer the question above)
