### ISSUE TITLE
Field Papers/Collect Integration

### ISSUE THREAD

**Issue by wonderchook** [getodk/collect#390]
#### Problem description
[Field Papers](http://fieldpapers.org/) allows users to print maps and sketch on them. After done they take a picture with their phone and upload to the Field Papers site. Different groups have used ODK and Field Papers together in the past to collect data. This is often in situations where small phones are being used to digitizing on screens does not work that well or a map is printed for discussion. Integrating the two systems together would allow people to submit a Field Paper picture as part of their questionnaire and then that picture could automatically be submitted for georeferencing instead of it being a two step process.

**Comment by lognaturel** [comment]
This is a great concept that hopefully someone will bring up again [in the forum's features category](https://forum.opendatakit.org/c/features/9) for deeper discussion and design.
