### ISSUE TITLE
Accuracy value is not becoming more and more accurate on the OSM map

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3929]
#### Software and hardware versions 
Collect with #3772 

#### Problem description
Accuracy value is not becoming more and more accurate on the OSM map

#### Steps to reproduce the problem
1. OSM map is selected in Collect's settings 
2. User starts a form with Geowidget (eg. All widgets)
3. User opens geo widget with map appearance like: 
   * Geopoint with placement-map appearance
   * Geopoint with maps appearance 
   * Geotrace
   * Geoshape
4. User sees accuracy value
5. Accuracy value is not becoming more and more accurate when the map is opened

#### Expected behavior
Accuracy value is changing and becomes more and more accurate

**Comment by lognaturel** [comment]
Closed by #3772
