### ISSUE TITLE
OSM map is NOT zoomed to current location automatically on Geotrace and Geoshape

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3930]
#### Software and hardware versions 
Collect with #3772 

#### Problem description
OSM map is NOT zoomed to current location automatically

#### Steps to reproduce the problem
1. OSM map is selected in Collect's settings
2. User starts a form with Geotrace and Geoshape widgets
3. User opens Geotrace / Geoshape widget
4. User sees map and accuracy value is on green background
5. OSM map is NOT zoomed to current location automatically

#### Expected behavior
OSM map is zoomed to current location automatically

**Comment by lognaturel** [comment]
Closed by #3772
