### ISSUE TITLE
Crash when navigating to Form Hierarchy

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3935]
#### Software and hardware versions 
Collect v1.27.2 (and previous versions)

#### Problem description

The app can crash if `instanceFile` is `null` in the app's `FormController` instance. Crash seen in Firebase: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/589a5fd64d5115cc3a1fa88e067346a2?time=last-seven-days&sessionId=5EF06C4C01150001215EC47FED3DAC57_DNE_8_v2

#### Steps to reproduce the problem

?

#### Expected behavior

App should not be able to get into this situation. Any path way that would lead to the `instanceFile` being `null` should exit form entry.

**Comment by grzesiek2010** [comment]
This is an old report so let's close for now and reopen later if needed.
