### ISSUE TITLE
Update scoped storage migration banner for v1.28

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3936]
The scoped storage migration banner currently reads "You must migrate Collect forms to private storage by August 2020 to comply with Android requirements." We should change this to make sure users know that in the following version the migration will be forced.

I think we need to keep some high-level context: "You must migrate Collect forms to private storage to comply with Android requirements."

Then we need to add some urgency. Possible ideas are:
* "This will be **done automatically** in the next Collect release."
* "In v1.29, **the migration will be forced on install**."

Here is what I think will happen in the next version (v1.29):
* On app launch, if the migration hasn't successfully happened yet, the migration will be triggered and the full screen dialog with status information will be shown.
* The migration results will be shown in the full screen dialog so that the user sees the message.
* If the migration failed, the migration banner will still be displayed and will say something like "The last storage migration attempt failed. Please migrate manually."

Depending on timing, we'd either target SDK 29 with v1.29 or v1.30 (https://github.com/getodk/collect/issues/3360). I think that to play it safe we can set `requestLegacyExternalStorage` to `true` and keep it that way until we need to target SDK 30. Technically this means we could push back the automatic migration but the longer we wait the more new users have to go through the migration so I think we should do it as soon as possible.

CC @seadowg @grzesiek2010 (who I'm sure will be as thrilled as I am when we can fully move on from all this)

**Comment by seadowg** [comment]
This all makes sense. I think "This will be done automatically in the next Collect release." is a good route for the text as it pushes that this is happening **NEXT** rather than at some point.

One thing we could start doing that I don't believe we currently do is to just automatically use Scoped Storage on devices that don't have any forms etc. I think we could do this by switching to scoped storage when we create the ODK dirs (probably in `StorageInitializer`). Does that make sense?

**Comment by grzesiek2010** [comment]
Makes sense to me as well.

> One thing we could start doing that I don't believe we currently do is to just automatically use Scoped Storage on devices that don't have any forms

As I remember we were thinking about it as we talked about the design for the migration process and someone probably Yaw was strongly against? Can't recall why exactly.

**Comment by seadowg** [comment]
> As I remember we were thinking about it as we talked about the design for the migration process and someone probably Yaw was strongly against? Can't recall why exactly.

I think initially it would have been weird as people would have expected copying files into the old "odk" dir to work. I'm thinking maybe now it's been a while, and we've been warning people we could get away with it? Unless there is another reason I haven't thought of!

**Comment by lognaturel** [comment]
> automatically use Scoped Storage on devices that don't have any forms

The reason we didn’t do this is because a new installation could need to integrate with OMK/some tool that uses a direct integration with Collect. For example, Ona has posted on the forum that they do need a way to hand media attachments to Collect and they’ll be adding support for this. In the mean time, new users of their integration would break if we forced the scope storage change.
