### ISSUE TITLE
Review analytics events and drop ones that are no longer actively used

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3952]
For example, we now know `likert` is broadly used and can stop tracking those events. It's hard to know what to pay attention to when we have a lot of events and Firebase caps the number of actions that we can see in its interface so it's worth it to clean up periodically.

**Comment by lognaturel** [comment]
I've reviewed analytics events and [written some notes](https://docs.google.com/document/d/1iPJd3LuJo7WHrss0H01HRT0GwyXK3qt9Ukxk28mbIyg/edit).

I propose removing ConfigureQRCode, FilterSendForms, NullFormController, ScanQRCode, LaunchFormWithBGLocation, Likert

Other actions for v1.28:
- Track attempted configurations from QR code, settings files, and outcome (success?)
- Replace SetCustomEndpoint with events on submission and formlist that tracks URLs without a default suffix? This would help identify endpoints actually used.

Other actions to consider:
- More marketing around audio features to see if adoption changes
- Change default update frequency for “downloaded forms only” and maybe “exactly match server” to every hour
- Remove “high resolution” setting for video
- Marketing around video to see if folks who need to capture video might find Collect compelling
- Marketing around autosend option and configuring via form definition and QR Code
- Put together QR code templates for common scenarios (untrusted enumerators, set it and forget it, etc)
- Marketing around both “downloaded forms only” and “exactly match server” for form updates; lots of folks are doing subsequent form updates and could benefit from automation
- Consider making autosend default
- Consider working towards autoupdate forms on device the default (possibly disruptive as servers with lots of enumerators will get lots more traffic)

CC @seadowg

**Comment by seadowg** [comment]
@lognaturel lets discuss these in our catch up tomorrow and then put some actions together for next steps. In short, I pretty much agree with everything!
