### ISSUE TITLE
Add analytics for Match Exactly

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3958]
~~Blocked by #3959 / #3940.~~

* Send event with server hash when clicking refresh button
* Set user property for selected "form update" mode ("manually", "match_exactly" and "previously_downloaded_only")
* Send event when a sync completes with failure or success (like storage migration). Include error type with failures.

**Comment by seadowg** [comment]
I was thinking for this we could start using Firebase/Google analytics' ["User Properties"](https://firebase.google.com/docs/analytics/user-properties?platform=android#java) features. In my head, this gives us an easy way to quickly work out what proportion of our users are using each "update mode". It might also be interesting to be able to filter other events based on what the update mode is, so we can make calls around design/UX changes specifically for "Match Exactly". Maybe an "update_mode" property with "manually", "match_exactly" and "previously_downloaded_only"?

**Comment by lognaturel** [comment]
> start using Firebase/Google analytics' "User Properties" features

Not something I had thought about but I think it's a really good idea.

Other things I think we want to get a feel for are:
- do users generally want automatic or manual updates? This might lead us to change defaults in the future.
- at what frequency do users trigger manual updates? We might consider moving to a model where visiting Fill Blank Form triggers the sync.

**Comment by seadowg** [comment]
@lognaturel are you referring to manual vs automatic in the case of Match Exactly or just generally here?

**Comment by lognaturel** [comment]
I meant just for match exactly but now that you mention it I think it should be for both modes with automatic options.
