### ISSUE TITLE
Soft delete form definitions if device has corresponding form instances 

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3961]
Currently, manually deleting a form definition removes both the database entry and the files for that form definition. With the addition of a form download mode that exactly matches the form list on the server (#3956), this is problematic. A user might still have submissions for a form that will no longer be in their formlist because it is marked as closing. They may need to edit those submissions and doing so requires the form definition. It's possible to get in this bad situation with manual delete of form definitions as well -- users may not expect that a side effect of deleting a form definition is that they can no longer open filled forms.

Instead of always hard deleting form definitions, hard delete should only occur for a formID/version combination if there are no corresponding submissions. If there are corresponding submissions, the formID/version combination's database entry should be updated to indicate soft delete and the files should remain. That formID/version combination should not be visible anywhere in the user interface. As soon as the last submission for that formID/version combination is deleted, the files and database entry for that formID/version combination should be fully removed.

- [x] Given I've enabled "Match Exactly"
 And there's a form definition formID/version combination currently on the device that is not in the server-provided form list
 And that form definition formID/version combination **does not** have corresponding submissions
 When I visit Fill Blank Forms
 And I tap the ♻️ (refresh) icon
 That form definition formID/version combination's files and database entry should be fully deleted

- [x] Given there's a form definition formID/version combination currently on the device that **does not** have corresponding submissions
 When I visit Delete Saved Form
 And I select that Blank Form and delete it
 That form definition formID/version combination's files and database entry should be fully deleted

- [x] Given I've enabled "Match Exactly"
 And there's a form definition formID/version combination currently on the device that is not in the server-provided form list
 And that form definition formID/version combination **does** have corresponding submissions
 When I visit Fill Blank Forms
 And I tap the ♻️ (refresh) icon
 That form definition formID/version combination's database entry should be modified to indicate that it has been soft deleted
 And that form definition formID/version combination should not appear anywhere in the user interface

- [x] Given there's a form definition formID/version combination currently on the device that **does** have corresponding submissions
 When I visit Delete Saved Form
 And I select that Blank Form and delete it
 That form definition formID/version combination's database entry should be modified to indicate that it has been soft deleted
 And that form definition formID/version combination should not appear anywhere in the user interface

- [x] Given there's a form definition formID/version combination that has been soft deleted
 When I visit Delete Saved Form
 And I delete the last Saved Form corresponding to that formID/version combination
 That form definition formID/version combination's files and database entry should be fully deleted

- [x] Given there's a form definition formID/version combination that has been soft deleted
 When the last Saved Form corresponding to that formID/version combination is auto deleted
 That form definition formID/version combination's files and database entry should be fully deleted

Note: it's also possible for a user to delete instances through `adb` or an external file manager. I don't believe `InstanceSyncTask` currently identifies this kind of change and I think it would be fine not to address that case.

I believe all of this could be handled by modifying the implementations for `FormsProvider.delete` (to look for corresponding instances to decide whether to soft or hard delete) and `InstanceProvider.delete` (to look for a corresponding soft deleted form definition that may need to be hard deleted).

**Comment by seadowg** [comment]
@lognaturel on the fifth acceptance criteria:

>  Given there's a form definition formID/version combination that has been soft deleted
When I visit Delete Saved Form
And I delete the last Saved Form corresponding to that formID/version combination
That form definition formID/version combination's files and database entry should be fully deleted

This should also be the case when we submit the last instance of a formID/version combo right?

**Comment by lognaturel** [comment]
> This should also be the case when we submit the last instance of a formID/version combo right?

Thought some more about this and actually it's still possible to view a form instance that was sent which requires the corresponding form definition. So no, I don't think that the submission status of corresponding submissions should have any effect on the corresponding form definition.

**Comment by seadowg** [comment]
@lognaturel doh you're right. I can adjust for this.
