### ISSUE TITLE
Answer in repeat group is removed when user opens repeat group dialog but he does not decide to remove

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3970]
#### Software and hardware versions 
Collect v1.25 (older versions were not verified)

#### Problem description
Answer in repeat group is removed when user opens repeat group dialog but he does not decide to remove

#### Steps to reproduce the problem
1. User opens form with repeat groups e.g. [nested-repeats.xml.txt](https://github.com/getodk/collect/files/4918630/nested-repeats.xml.txt)
2. User adds answer
3. User opens `Remove group` dialog and clicks on **Cancel**
4. User noticed that answer is removed

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/87423039-f2c82700-c5d9-11ea-8b59-2f9cb04b1be7.gif)

#### Expected behavior
Answer does not change

#### Other information 
Noticed during testing #3839

**Comment by SaumiaSinghal** [comment]
@mmarciniak90 I fixed this issue in #3839 

![cancel-does-not-clear-value](https://user-images.githubusercontent.com/35730054/87449994-8bcb6200-c61b-11ea-85e5-a3774918f355.gif)

**Comment by grzesiek2010** [comment]
I can confirm it is no longer visible on master
