### ISSUE TITLE
Add apostrophes for more data types while sending to Google Sheets

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3978]
#### Software and hardware versions 
Collect v1.27.3

#### Problem description
In version [v1.25](https://github.com/getodk/collect/pull/3462) we get rid of adding apostrophes to every single cell sending to Google Sheets and decided to do that only in case of:
- text
- select_multi
- barcode

We assumed that the risk of automated conversion is related to only those types of questions. It turns out that the problem might also occur if we use:
- select_one
- likert
- rank 

widgets, so we should consider handling those data types too.

#### Other information 
The problem has been originally reported on the forum: https://forum.getodk.org/t/wrong-submissions-how-to-deal/28269

**Comment by seadowg** [comment]
We're not currently focused on improving Google Drive flows so closing this.
