### ISSUE TITLE
Enabling Auto send should submit forms on device

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3980]
When the user enabled "Auto send" in Form Management settings should schedule submission of the forms currently on the device. Right now forms would not auto submit until another instance was filled out. 

**Acceptance**

- [ ] Given I've filled out (and finalized) a form
And I've still not sent that form to the server
When I go to Form Management settings (in General settings)
And I enable Auto send
And my connection is correct for the auto send type I enabled
Then my form is sent to the server

**Comment by SandeepHG** [comment]
I would love to solve this issue

**Comment by seadowg** [comment]
@SandeepHG great! If you start by reading [this](https://github.com/getodk/collect#contributing-code) (including the linked guides). When you're ready to start working on the issue it'd be good to post your thinking about how you could test and implement it. We can then discuss and assign it to you!

**Comment by asaikarthikeya** [comment]
@seadowg I would like to work on this.

**Comment by asaikarthikeya** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/70392921/102576255-19573480-411b-11eb-84de-a3c94cf4f393.png)
I had this build issue could you please help me with build issues.

Thankyou.

**Comment by asaikarthikeya** [comment]
@seadowg @lognaturel 

if I am not wrong , the relevant class to work on solving this issue is
collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java  

In
`private boolean atLeastOneFormSpecifiesAutoSend() 
 for (Form form : forms) {
**if (Boolean.valueOf(form.getAutoSend())) {
                    return true;
                }**                
            }
        }
        return false;
    }`

If we include a break statement into **if** loop does that help in auto sending , Instead of waiting for user to enter another instance?

**Comment by seadowg** [comment]
@asaikarthikeya I don't think that's quite right. What we'd like to happen is for the auto send work (`AutoSendTaskSpec` using `Scheduler`) to be scheduled when the user enables auto send in settings (which happens in `FormManagementPreferences`).

I'll update the issue with acceptance criteria so that's hopefully clearer.

**Comment by TomRCummings** [comment]
Would it be appropriate to add an `InstanceSubmitScheduler` to `FormManagementPrefencesFragment`, which would be used to `ScheduleSubmit` when auto send setting changes?

**Comment by seadowg** [comment]
@TomRCummings yeah that sounds about right?. We'd just need to schedule a submission (using `scheduleSubmit`) when the setting is turned on. You can probably inject an instance `InstanceSubmitScheduler` using Dagger's `@Inject` in `FormManagementPreferencesFragment` and that would also let you add a test in `FormManagementPreferencesFragmentTest` that checks the interaction with `InstanceSubmitScheduler`. Would you be interested in working on this issue?

**Comment by TomRCummings** [comment]
@seadowg Excellent, that makes sense with what I was thinking. I would be interested in working on this

**Comment by seadowg** [comment]
Great! You can follow the instructions in https://github.com/getodk/collect/blob/master/docs/CONTRIBUTING.md to claim the issue and get started with a contribution back here. Feel free to post any questions here or on our [Slack](https://slack.getodk.org/).

**Comment by TomRCummings** [comment]
@getodk-bot claim
