### ISSUE TITLE
Automatic download checkbox should be disabled for Never periodic form update check

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3982]
#### Software and hardware versions 
Collect v1.28.- current master, Android all device used...

#### Problem description
Automatic download checkbox is now enabled for default choice: Never in Periodic form updates check, see screenshots:
| master v1.28.0 | store version 1.27.3 |
| --------- | ---------|
| ![Screenshot (Jul 23, 2020 9_02_13 AM)](https://user-images.githubusercontent.com/33342488/88260701-318a6b00-ccc5-11ea-8fc7-ea51d0c4e125.png) | ![Screenshot_20200723-090551](https://user-images.githubusercontent.com/33342488/88260716-3a7b3c80-ccc5-11ea-8aea-fe6798b96f64.png) |

#### Steps to reproduce the problem
1. Go to General Settings/ Form Management
2. Click on Automatic download checkbox without changing Periodic form updates check

#### Expected behavior
User should not be able to select automatic download checkbox when periodic form updates check is set to Never.

#### Other information 
It works well on the store version: 1.27.3, so it is a recently introduced regression issue.

**Comment by kkrawczyk123** [comment]
@getodk-bot label "regression"

**Comment by seadowg** [comment]
@grzesiek2010 probably not worth starting on this now as #3977 and other match exactly stories are changing a lot on this screen.

**Comment by seadowg** [comment]
In addition to fixing this @lognaturel pointed out that when Match Exactly is enabled "Automatic Download" should be ticked (but disabled).

**Comment by grzesiek2010** [comment]
Ah ok
