### ISSUE TITLE
Blank form update mode setting is indented to give space for non-existent icon

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3990]
#### Software and hardware versions 
`master`

#### Problem description
The new `Blank form update mode` is indented in whereas other `Form management` settings aren't. I think this is because the migration to androix preferences happened concurrently with adding this setting.

#### Steps to reproduce the problem
Go to form management settings.

#### Expected behavior
All form management settings should be close to the left edge.

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
