### ISSUE TITLE
Experimental settings section should be hidden or removed

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3991]
#### Software and hardware versions 
`master`

#### Problem description
There's an Experimental settings section that was added temporarily while working towards match exactly. It should be hidden or removed now that nothing is in it. @seadowg maybe you had a plan for it already?

#### Steps to reproduce the problem
Go to general settings

#### Expected behavior
The Experimental section doesn't show up

**Comment by seadowg** [comment]
Great shout. I can do it as part of the PR I'm working on.

**Comment by seadowg** [comment]
I'm thinking even if the section is empty it's probably quite useful to have for adding new features in the future. Should we maybe only allow it in beta/dev?

**Comment by lognaturel** [comment]
Yup, beta/dev only sounds great.
