### ISSUE TITLE
Improve style of gradle file

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#400]
The gradle file now uses both long form and shortcut styles for defining external dependencies as described [here](https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html#sec:external_dependencies_tutorial). It would be better if they all used the long form style (using `group:`, `name:`, `version:`). That includes for `testCompile` and `androidTestCompile`.

Additionally, there are two extra newlines [here](https://github.com/opendatakit/collect/blob/master/collect_app/build.gradle#L98) and an extra comment [here](https://github.com/opendatakit/collect/blob/master/collect_app/build.gradle#L124). I didn't notice that comment before -- it was related to #399 and would have been better as a comment on the PR rather than in the code.

@shobhitagarwal1612, if you want to take it, this one should be quick for you since you were just in this code!

**Comment by shobhitagarwal1612** [comment]
@lognaturel Yeah I would love to work on this

**Comment by shobhitagarwal1612** [comment]
The version upgrade of opencsv didn't introduce any bug so i didn't mention it in the PR. But as a reminder I mentioned it in the code. I guess I should remove it now.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 one more thing to potentially address in this one. For the `opencsv` dependency, the group looks strange, I believe it's a fork. Why not use https://mvnrepository.com/artifact/net.sf.opencsv/opencsv where you can use 2.3? Eventually we'll want to go to 3 but that will require some deeper code changes.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Thanks. I will replace the opencsv line to the original maven repo
