### ISSUE TITLE
Audio is hearable after removing response on Audio widget

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4005]
#### Software and hardware versions 
Collect v1.27.3 (older versions were not verified)

#### Steps to reproduce the problem
1. User adds audio to Audio widget
2. User plays it
3. User removes response when audio is played
4. **The response is removed but the sound is still hearable**

#### Expected behavior
* Audio is not hearable after removing response

#### Other information 
Noticed while testing #3992

**Comment by seadowg** [comment]
@mmarciniak90 are these both visible in Collect 1.27.3?

**Comment by mmarciniak90** [comment]
@seadowg I retested it on v1.27.3 and only the case with removing response is reproducible.

**Comment by seadowg** [comment]
@seadowg yeah getting the same thing 👍. Could we split this in two issues and mark the second ("Use case 2") as a "regression"?
