### ISSUE TITLE
Improvements to match exactly. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4007]
#### Software and hardware versions 
Collect v1.28.x, Android vx.x.x, device used...

There are few small things that could be improved, testing result from #3992:

- When Match Exactly is selected, Get Blank Form is not visible in menu but it is still visible as enabled in Admin Settings/Main Menu Settings: 
![Screenshot_20200804-094952](https://user-images.githubusercontent.com/33342488/89268058-4dccc700-d638-11ea-8c45-3985f8535605.png)
It should be disabled like Edit Saved Form option when Moving backward is selected.

- When Match Exactly is selected there is only one default option: Automatic download that is disabled and the checkbox is empty what might be little confusing:
![Screenshot (Aug 4, 2020 9_55_34 AM)](https://user-images.githubusercontent.com/33342488/89268472-de0b0c00-d638-11ea-990f-e6c3c09860ac.png)
It should still be disabled be the checkbox should be selected by default then. 

- When Use refresh arrow on Fill Blank Form list when there is no internet connection or airplane mode is turned on, the auto-download refresh keeps failing and failing. It might not be sure for user that he lost internet connection as it might happen suddenly and be totally unexpected so I feel like toast informing about the connection lost would be much friendlier for users, like when try to get blank form without connection:
![Screenshot_20200804-100014](https://user-images.githubusercontent.com/33342488/89269421-2840bd00-d63a-11ea-8ff0-88aac6771a00.png)

- In Admin Settings/User settings Blank form update mode has a weird indentation what differs it from other option:
![Screenshot_20200804-101735](https://user-images.githubusercontent.com/33342488/89270756-17914680-d63c-11ea-9785-7772b4fb81d4.png)
This issue is not visible on Android 5.1 but it is on all other devices.

**Comment by seadowg** [comment]
> When Use refresh arrow on Fill Blank Form list when there is no internet connection or airplane mode is turned on, the auto-download refresh keeps failing and failing.

@kkrawczyk123 not following here. Is this referring to the Refresh (🔃) button on "Fill Blank Form" or the "Previously downloaded only" auto update/download?

**Comment by kkrawczyk123** [comment]
@seadowg It is referring to Refresh button on Fill Blank Form when match exactly is selected.

**Comment by seadowg** [comment]
I think for the offline error case we should just show a toast when the user hits the refresh button while Android says the device is offline.

**Comment by mmarciniak90** [comment]
**Use case to improve:**
1. Aggregate server is set
2. Another mode than`Manually` is selected
3. `Automatic download` is selected
4. User changes server to Google Drive 

**Actual result**
`Automatic download` is selected but not editable

**Expected result**
`Automatic download` is unselected
