### ISSUE TITLE
User is not informed that the new form version was automatically downloaded with `Exactly match server` option

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4009]
#### Software and hardware versions 
Collect with #3992 

#### Problem description
User is not informed that the new form version was automatically downloaded with `Exactly match server` option

#### Steps to reproduce the problem
1. User sets `Exactly match server` 
2. All forms are downloaded
3. New form version is added to the server
4. New form version is automatically downloaded but user is not informed about that action

#### Expected behavior
User sees notification with information about download latest form version.
User should be informed about downloaded the latest version as with  the `Previously downloaded forms only` option

Relates to #2236

**Comment by seadowg** [comment]
@lognaturel and I discussed this and agreed it's probably something we're going to want down the line. It seems like right now it's better to wait on getting feedback around Match Exactly as it might be that we want to make changes to how updates are scheduled (time of day vs interval). It's also unclear if people want notifications only when there are updates/new forms or if notifications are the right way to communicate updates.

**Comment by grzesiek2010** [comment]
It's been a while and since we have been talking about match exactly recently what do you think about this issue? Do we want it or we can close? @seadowg @lognaturel

**Comment by seadowg** [comment]
It still feels like it **might** be something we want to do at some point but right now I don't think we need an issue for it? I'll close now, but if anyone disagrees then can reopen!
