### ISSUE TITLE
Automatic download doesn't work for 'previously downloaded form only' after refusing to update manually

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4012]
#### Software and hardware versions 
Collect v1.28.x, Android v all, device used...

#### Problem description
When testing #3992 I have noticed a regression issue for previously downloaded forms only option. When you select that option you will get notification about available form update and if you do not download it and change to automatic download - automatic download doesn't work even if you see that there is form uptade info in Get Blank Forms. Collect stops to recognize there is form update after refusing to download the first try. 

#### Steps to reproduce the problem
1. Download form from server versions of the form (i have tried for Aggregate)
2. Log to another server where you have version2/ upload version2 to the same server (it doesn't matter which way you choose it's reproducible for both)
3. This is an update to a form you have info that should be visible in get blank form.
4. Go to General Settings/Form Management
5. Choose Previously downloaded forms only  
6. You will get a notification immediately
7. Ignore available update 
8. Select Automatic download checkbox
9. Wait for notification and form update

You will never get notification and form won't be updated.

#### Expected behavior
After 15 minutes, notification about automatic download should display, form should be updated automatically.

#### Other information 
I have tried the same case for 1.27.3 store version and it works properly.

@getodk-bot label "regression"

**Comment by seadowg** [comment]
oooooft. Nice find.
