### ISSUE TITLE
User is not able to read the whole error message when `Exactly match server` is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4018]
#### Software and hardware versions 
Collect master with #3986 

#### Problem description
User is not able to read the whole error message when `Exactly match server` is set

#### Steps to reproduce the problem
Use case 1:
1. `Exactly match server` is set
2. User adds not existing aggregate URL 
3. User sees notification with message but there is no option to read the whole message
4. If user clicks on it, user is moved to `Fill Blank Form` list and the refresh icon is red.

![Screenshot_20200810-103540](https://user-images.githubusercontent.com/3907554/89765702-23c34b00-daf7-11ea-9f2f-b5c91b5a4b3d.png)

Use case 2:
1. `Exactly match server` is set and there is no internet connection
2. User sees notification with message but there is no option to read the whole message

![Screenshot_20200810-101735](https://user-images.githubusercontent.com/3907554/89765716-27ef6880-daf7-11ea-965b-ce0b8a0cbc4d.png)

#### Expected behavior
Dialog with the whole message is visible when user clicks on notification with error
OR if we don't want to show dialog
Whole message is visible in the notification

**Comment by seadowg** [comment]
Ah I thought these would be expandable, but they aren't. I'll have a look at improving this.

**Comment by seadowg** [comment]
![https://media.giphy.com/media/Nx0rz3jtxtEre/giphy.gif](https://media.giphy.com/media/Nx0rz3jtxtEre/giphy.gif)

@getodk-bot hello there! Still working on it my little friend.
