### ISSUE TITLE
username field on form populated incorrectly when original username is incorrect

### ISSUE THREAD

**Issue by michaelcleary** [getodk/collect#4027]
#### Software and hardware versions 
Collect v1.27.3, various Android versions

#### Problem description
If the user enters an incorrect username when configuring the server settings, that incorrect username is being used to populate the username field on a form, even though the user has subsequently corrected the username in order to be able to connect to the server to obtain the form.

#### Steps to reproduce the problem
1. Create a form that includes the username metadata field and place it on an ODK Aggregate (or compatible) server. In this case I am using Onadata, although I'm not sure if this has any bearing on the issue.
1. In ODK Collect, under General Settings -> Server, enter the server URL, username and password, but enter an incorrect username (one that will fail authentication)
2. Go back to the menu screen and select Get Blank Forms. You will get a dialog box saying 'Incorrect username or password for server: ...'
3. Now enter the correct username and press OK. Now you will get the form.
4. Fill the form, save and submit.
5. The form is received on the server, but the username field is populated with the original, incorrect username.

#### Expected behavior
The form should be populated with the corrected username.

**Comment by lognaturel** [comment]
Thanks for the detailed writeup, @michaelcleary!

On the development side, I believe `WebCredentialsUtils.saveCredentialsPreferences` should call `ApplicationInitializer.initializeJavaRosa`. It should also be straightforward to add a test to `ServerAuthDialogFragmentTest`.
