### ISSUE TITLE
Improve error handling for Match Exactly

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4039]
Changes we should make:

- [x] When there is a `SSLException` user should see notification with text similar to "Collect can't reach the server at..." but start with "Collect can't connect securely to server..."
- [x] When there is a 404 fetching the form list the user should see the "Collect can't reach the server at..." notification

**Comment by seadowg** [comment]
@lognaturel looking at OkHttp I don't think we're actually going to be dealing with `GeneralSecurityException` as it's not an `IOException` and the client only throws those. I'm guessing we want to be deal with `SSLException` (https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLException.html). Does that sound right or were there other cases you had in mind?

I'll need to work out a way to verify that's definitely what we're going to get back.

**Comment by lognaturel** [comment]
Interesting! I mentioned `GeneralSecurityException` because I saw at least one example on the forum. I think it was a [`CertificateException`](https://docs.oracle.com/javase/7/docs/api/java/security/cert/CertificateException.html) but I'm not immediately finding it. It must have been before the switch to OKHttp. So yes, fine not have a case for that, then.

**Comment by seadowg** [comment]
> It must have been before the switch to OKHttp

Ah right that makes sense. Looking at the OkHttp docs I reckon we're good to go with SSLException then (https://square.github.io/okhttp/https/#debugging-tls-handshake-failures).

**Comment by seadowg** [comment]
@lognaturel ah this completely eluded me when we chatted about it but most of the places we throw a `FETCH_ERROR` there is no exception. This is because the `OpenRosaXmlFetcher` (the artist formerly known as `CollectServerClient`) currently catches `Exception` and then returns a `DocumentFetchResult` with the exception's message. Pretty much everywhere else we see a `FETCH_ERROR` there isn't an underlying exception but a problem with the http or XML response. 

I think we could rework all this but I'm a little worried it's a rabbit hole and would hold this up. I'm thinking a good way forward is to create a separate issue and fix as part of #4040 (as that's already playing around in that neighbourhood). Thoughts?
