### ISSUE TITLE
Add an option to disable fake location providers

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4048]
#### Software and hardware versions 
All versions

#### Problem description
Currently enumerators may use fake location providers and fill forms to pretend working in particular places.

The problem has been originally reported on the forum https://forum.getodk.org/t/restricting-fake-location-application-while-collecting-gps-points-with-collect-android-app/29231/5

#### Expected behavior
We initially agreed that it would be good to add a new option in Admin Settings that would enable fake providers for users that really need it (the option would be disabled by default).

**Comment by grzesiek2010** [comment]
@lognaturel 
could you take a look and share your thoughts?

**Comment by lognaturel** [comment]
I’ll eventually respond to the forum thread. I think the first thing we need go do is update docs for what to do when enumerators are untrusted as this is only one concern of many.

**Comment by lognaturel** [comment]
Just noticed you self-assigned, @grzesiek2010. Let's hold off on this one for now, please.

**Comment by grzesiek2010** [comment]
I'm closing this issue since we have addressed it in a different way (https://github.com/getodk/collect/pull/4358)
