### ISSUE TITLE
The order of the displayed answers from the multi-select widget on hierarchy view complies with the order of clicking

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4050]
#### Software and hardware versions 
Collect v1.26.3 (older versions were not verified)

#### Problem description
The order of the displayed answers from the multi-select widget on hierarchy view complies with the order of clicking 

#### Steps to reproduce the problem
1. User opens `All widgets` form
2. User fills all multi select widgets
3. User opens hierarchy view
4. User sees that the order of the displayed answers complies with the order of clicking not with the option order, e.g. `D, A` is displayed instead `A, D`

Additional case:
Because of changes from #3964, the mentioned case appears also on spinner widget for select_multiple

| | v1.26.3 | PR #3964 |
|---|---|---|
|spinner widget|![Screenshot_20200827-162903](https://user-images.githubusercontent.com/3907554/91456844-07a80380-e884-11ea-9467-9728cdc53ba1.png)|![Screenshot_20200827-163224](https://user-images.githubusercontent.com/3907554/91456861-0d054e00-e884-11ea-960b-09a56048b6b2.png)|
|hierarchy view|![Screenshot_20200827-162907](https://user-images.githubusercontent.com/3907554/91456926-1bec0080-e884-11ea-84a8-0837089a63bb.png)|![Screenshot_20200827-163231](https://user-images.githubusercontent.com/3907554/91456941-20181e00-e884-11ea-8cab-42f3e506ec8f.png)|

#### Expected behavior
The order of the displayed answers from the multi-select widget on hierarchy view complies with the option order

**Comment by grzesiek2010** [comment]
I'm afraid that some users might use that bug/feature to rank items since our RankingWidget is relatively new and some people might not know about it. Taking into account what I said i think it would be better not to take the risk and keep it as is. @lognaturel what do you think?

**Comment by lognaturel** [comment]
I don’t really understand this issue. Could you please describe what behavior has changed? Is there a change in the underlying order or in the display order? I generally agree that we shouldn’t change the underlying order. I don’t see a good reason for the display order to be any different than the underlying order.

**Comment by grzesiek2010** [comment]
Nothing has changed as I understand, It has always worked in that way. If we were creating those widgets now I would probably handle it and display selected items according to their position but now as it already exist we shouldn't change it.

**Comment by lognaturel** [comment]
@mmarciniak90's screenshots show a difference between v1.26.3 and #3964. Was that just because she selected choices in different orders in those cases? Or did the spinner widget possibly reorder choices in some way previously?

**Comment by mmarciniak90** [comment]
@lognaturel 
> Or did the spinner widget possibly reorder choices in some way previously?

Yes, the spinner widget reordered choices before PR#3964. It does not follow the order of clicking but the order in which they appear in the list. I clicked on `D` then `B`, but I saw `B`, `D`.

We need to make a decision on what order we want to represent answers for multi-select widgets. 
When I created this issue I thought that we should represent the user's answers according to the list of options. 
Right now (after PR#3964) it follows the order of clicking and I think it's good because it's consistent with other multi-select widgets.

**Comment by jkpr** [comment]
Hi, we noticed this today. We relied on the previous behavior that the order of saved multi-select answers was the same as shown on screen. So we could list a bunch of family planning methods in order of effectiveness:

- Method A
- Method B
- Method C

and get the most effective one that was selected with `selected-at(${family_planning_method}, 0)`. Now that doesn't work.

Based on the linked PR #3964 it looks like the data is saved in order that the items are selected, and de-selecting just removes from that list.

**Comment by lognaturel** [comment]
I believe the intent was to close this issue. All select multiple appearances now have consistent behavior which is desirable. Prior to #3964, the `minimal` appearance had special behavior that @jkpr ended up relying on. 

In general, the choice order should be considered an implementation detail that shouldn't be relied on. I'll respond with a strategy to get @jkpr's desired behavior on [the forum](https://forum.getodk.org/t/how-to-get-the-option-on-a-select-multiple-that-was-displayed-highest-in-the-list/34943).

Please re-open if I misunderstood!
