### ISSUE TITLE
Minimal appearance doesn't work with "fast external itemsets"

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4051]
#### Software and hardware versions 
`master`

#### Problem description
Minimal appearance doesn't work with ["fast external itemsets"](http://xlsform.org/en/#external-selects).

#### Steps to reproduce the problem
Load a form with "fast external itemsets" and the minimal appearance such as [select_one_external.xlsx](https://github.com/getodk/collect/files/5138302/select_one_external.xlsx).

#### Expected behavior
The `minimal` and `minimal autocomplete` appearances should have the same behavior as with other selects.

I believe this was intended to be addressed by #3964 but you'll have to confirm, @grzesiek2010.

**Comment by grzesiek2010** [comment]
> I believe this was intended to be addressed by #3964 but you'll have to confirm, @grzesiek2010.

I don't think it was in the scope. A separate (`ItemsetsWidget`) is responsible for handling `fast external itemsets` so that will require some refactoring, however I agree that it would be good to have it (not necessarily in v1.28).
