### ISSUE TITLE
Radio buttons/checkboxes are not visible in select on Android 5.0

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4060]
####  Software and hardware versions 
Collect v1.28, Android v5.0

#### Problem description
Radio buttons/checkboxes are not visible in select on Android 5

The bug has been originally reported on the forum: https://forum.getodk.org/t/boxes-for-select-multiple-in-android-5/29621/4

#### Steps to reproduce the problem
Try any form with selects on android 5.0

**Comment by seadowg** [comment]
Just removed from the mileston as the PR is in there.
