### ISSUE TITLE
Add list of contributors

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#407]
It'd be nice to have a list of contributors inside ODK Collect. This needs discussion because I'm not sure who counts as a contributor, what information we display (e.g., GitHub username? full name? organization), how we order it (e.g., number of commits, date of last commit), etc.

**Comment by grzesiek2010** [comment]
I think we can keep the order from https://github.com/opendatakit/collect/graphs/contributors the other way I know is `git fame` command to get a list of contributors. There is even an API https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts I know we want do have this offline but maybe we can build such page once during release?

**Comment by jnordling** [comment]
I think this would be nice. Always nice to show all the people working on the project. Could be good for morale.

**Comment by abhaymaniyar** [comment]
I would like to work on Collect's UI. I will be using Material design principles. I am also thinking of changing default network access framework to Retrofit 2 because of its simplicity. I am also thinking of implementing this functionality in the app using GitHub API. Any comments on that?

**Comment by yanokwa** [comment]
@abhaymaniyar And what about the people who contributed before the code was on GitHub?

**Comment by abhaymaniyar** [comment]
@yanokwa I think then we would have to add their names manually. And if we have a excel sheet about their details, we can extract the required data programmatically.

**Comment by yanokwa** [comment]
@lognaturel had a good suggestion that I really like. We should use https://github.com/kentcdodds/all-contributors (our fork is at https://github.com/opendatakit/contributors). We can then pull all the contributors from the various repos and have Collect (and the other tools) render that page.

**Comment by seadowg** [comment]
I think we're unlikely to spend time on this - it's probably a responsibility that https://getodk.org could handle in the future. If anyone wants to reopen feel free!
