### ISSUE TITLE
French buttons for Google Drive form download get resized improperly

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#408]
#### Software and hardware versions 
Collect v1.4.14

#### Problem description
<img width="243" alt="screen shot 2017-02-13 at 11 45 47 am" src="https://cloud.githubusercontent.com/assets/967540/22870457/6b7cc978-f1e2-11e6-897a-4af091d30942.png">
This happens in any language that has very long text for the download button.

There's a similar but less dramatic problem on the Aggregate download blank form screen:
![screen shot 2017-02-13 at 12 02 44 pm](https://cloud.githubusercontent.com/assets/967540/22870681/7a7e4c10-f1e4-11e6-8c27-40a85f82f874.png)

#### Steps to reproduce the problem
1. Change Collect protocol to Google Drive, Google Sheets in Collect settings
1. Configure the platform settings with a google account that has forms in Drive
1. Change device language to French (Settings > Language and Input > Language)
1. Go to Télécharger un formulaire vierge (download blank form)

#### Expected behavior
Buttons should not look like that. 😊 I'm not exactly sure what should happen. Perhaps the buttons should have a minimum width.

Note: I'm updating the translation to match the text on the Aggregate form download button. But this doesn't entirely solve the problem.

**Comment by Dvik** [comment]
Would it be better if the width of the buttons are in a particular ratio like 1:1:2?

**Comment by lognaturel** [comment]
@Dvik I'm not sure if that's the right ratio (maybe 1:1:1 makes sense?) but the idea of fixed ratios is probably the right one. It'd be great to see it in action if you'd like to submit a pull request.

**Comment by Dvik** [comment]
Is this change acceptable? The first screenshot is the old one and the second is the new one.

![screenshot_2017-03-01-03-52-54](https://cloud.githubusercontent.com/assets/6627828/23437180/2d14c62e-fe33-11e6-81dd-8a82f2fac4a5.png)

![screenshot_2017-03-01-03-55-25](https://cloud.githubusercontent.com/assets/6627828/23437190/33b58e6e-fe33-11e6-8ba3-7f3c73934f67.png)

**Comment by Dvik** [comment]
Is this change acceptable? 
The first one is the old one and the second the new one.
![old](https://cloud.githubusercontent.com/assets/6627828/23437283/882b934e-fe33-11e6-91ac-4f17fcb4c215.JPG)
![new](https://cloud.githubusercontent.com/assets/6627828/23437284/8bf81d62-fe33-11e6-9a0b-1dc55d6d1182.JPG)

**Comment by lognaturel** [comment]
That's much better! I think the buttons should all have the same height, what do you think?

**Comment by Dvik** [comment]
yeah, that's also my concern. trying to do that

**Comment by Dvik** [comment]
The first one is when ODK Aggregate is chosen as platform and the second one when Drive is selected as platform. Let me know if this works.
![new1](https://cloud.githubusercontent.com/assets/6627828/23438277/441461f0-fe37-11e6-9595-4760f4611673.JPG)
![new2](https://cloud.githubusercontent.com/assets/6627828/23438278/4415ecf0-fe37-11e6-9858-d8234ea84072.JPG)

**Comment by lognaturel** [comment]
Looks great! Do make sure it still looks reasonable in English and then I think it's ready for a pull request!

**Comment by Dvik** [comment]
In English.
![eng2](https://cloud.githubusercontent.com/assets/6627828/23438680/f62853b4-fe38-11e6-82c9-2e2fc710ab1d.JPG)
![eng1](https://cloud.githubusercontent.com/assets/6627828/23438681/f6305488-fe38-11e6-9d11-4161f33d6075.JPG)

Also, in future as a part of the UX changes in GSOC, we should consider using the Bottom Navigation View recently added in the Design Support Library. https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

**Comment by lognaturel** [comment]
Fantastic. 

Make sure to include suggestions like that in your GSoC application!
