### ISSUE TITLE
Lines are cut off on Likert widget when RTL language is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4096]
#### Software and hardware versions 
Collect master

#### Problem description
Lines are cut off on the Likert widget when RTL language is set

#### Steps to reproduce the problem
1. User uses app with RTL language set
2. User opens Likert widget
3. Lines are cut off

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/93348840-0476b680-f837-11ea-88a1-b087bd97daca.jpg">

#### Expected behavior
Lines are not cut off

**Comment by mmarciniak90** [comment]
@getodk-bot label "regression"

**Comment by seadowg** [comment]
Closing as the Likert widget no longer has lines
