### ISSUE TITLE
Show warning when legacy settings import used

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4111]
Collect currently supports importing files from a `.settings` or `.json` file when the app loads. It'd be good for this to eventually go away, so we don't have to keep maintaining the code paths.

**Acceptance**

- [x] Given I've set up a settings `.settings` file
When I open Collect
I see a dialog warning me that `.settings ` support will be removed

- [x] Given I've set up a settings `.json` file
When I open Collect
I see a dialog warning me that `.json` support will be removed

Text for the dialog will be: 

> Settings were successfully imported from a <file type> file. This functionality will be removed in a future version. Please use QR code configuration instead.

**Comment by lognaturel** [comment]
That sounds good. We only just added analytics for these features and we haven't announced their removal so I'm not comfortable saying when we'll remove them. Can we leave it a little open-ended?

Currently there's a toast that says "Settings imported successfully". I think we want something like

> Settings were successfully imported from a .settings[.json] file. This functionality will be removed in a future version. Please use QR code configuration instead.

Only one action - OK

Title - Successful settings import
