### ISSUE TITLE
Crash on RuntimeException when adding repeat

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4119]
#### Software and hardware versions 
Collect v1.27.4; [Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b4d80d96007d59fcdcad981?time=last-seven-days&sessionEventKey=5F6CCB66029800011C980B8DF8617D36_1454540976116208809) shows it occurred back to at least v1.25.2

#### Problem description
If a form has a reference to a value inside of a repeat that is not qualified (doesn't specify a specific repeat instance) and is used in a context where a single node is expected, there's a hard crash.

#### Steps to reproduce the problem
1. Load a form such as [bad-instance-name.xml.zip](https://github.com/getodk/collect/files/5280566/bad-instance-name.xml.zip)
1. Add a first repeat instance
1. Attempt to add a second repeat instance and experience a crash

#### Expected behavior
The user should see the text from the `RuntimeException` ~and the form should close~.

#### Additional information
Validate should catch these kinds of issues so it's likely these forms aren't being built with XLSForm or converted with pyxform-based tools.

I paid close attention to the crashes that happened in v1.28 ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b4d80d96007d59fcdcad981?time=1599609600000:1600991999000&sessionEventKey=5F6C63F400160001361633C70654677F_1454426636061422683)) to see if there was anything about them that could point to a change in behavior. It looks like a single form that has a structure like [relevant-repeat.xml.zip](https://github.com/getodk/collect/files/5280608/relevant-repeat.xml.zip).

**Comment by lognaturel** [comment]
[This crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/eba8b2e75659fa3dc26f5da38df91b85?time=last-seven-days&sessionEventKey=5F73A7A9017B000113C27588F0E3EF13_1456478979182267923) is another one that happens at `newRepeat` time. Ideally a solution to the issue above would also lead to this error message being shown to the user instead of a crash. I'm a bit more troubled by this one because I don't know what can cause it and it doesn't look like we've seen it before. I've filed an issue for JR at https://github.com/getodk/javarosa/issues/608

**Comment by seadowg** [comment]
@lognaturel with other form crashes (we account for them happening when stepping to the next screen on adding a repeat) we don't close the form. I'm thinking for this we should also just leave the form open so the user can grab any data they have entered etc.

**Comment by lognaturel** [comment]
It looks to me like the original crash is still happening in v2022.4.x, probably under some specific conditions we didn't address: https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b4d80d96007d59fcdcad981?time=last-ninety-days&sessionEventKey=63B0751D000F00010DC8BE27EBD3FA81_1762404693153170961

It looks like there's one form triggering it and it likely uses a dynamic select on repeat. Probably not common enough to resurface but wanted to make a note of it.
