### ISSUE TITLE
Help/guidance/warning area should be hidden when there is no content

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4129]
#### Software and hardware versions 
Collect v1.28.1 (and earlier)

#### Problem description

The view that shows help, guidance and warning text still takes up space when there is no content displayed in it.

#### Steps to reproduce the problem

1. Make a form with a question that has no help, guidance or warning
2. Scroll to the question

You'll see there is some extra space between the question label and the answer.

#### Expected behavior

Extra space (view) should disappear when there is nothing to display in it.

#### Other information 

It'd also be good to revise the spacing once this change is made to make sure there is still enough space between the label/help and the answer in all the widgets. We should add spacing to widgets individually if they feel cramped.

**Comment by grzesiek2010** [comment]
The issue does not exist according to my investigation:
| Hint and guidance  | No hint and no guidance |
| ------------- | ------------- |
| ![2](https://user-images.githubusercontent.com/3276264/100921400-d0796c00-34dc-11eb-9dd9-a89b578dfab4.png) | ![1](https://user-images.githubusercontent.com/3276264/100921397-cfe0d580-34dc-11eb-9c2d-1ac90ebb7ac3.png)  |

[layoutTest.xlsx](https://github.com/getodk/collect/files/5631583/layoutTest.xlsx)

**Comment by lognaturel** [comment]
#4130 addressed it. I think it was left open because of:

> It'd also be good to revise the spacing once this change is made to make sure there is still enough space between the label/help and the answer in all the widgets. We should add spacing to widgets individually if they feel cramped.

I have not noticed any issues in my use. I think it would be good for @getodk/testers to keep an eye out for any spacing improvements they might suggest as they do the regression pass.
