### ISSUE TITLE
Sort by displays unexpectedly after using map button and search icon

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4132]
#### Software and hardware versions 
Collect v1.28.x, Android v all .x.x, device used...

#### Problem description
Sort by menu displays unexpectedly after using map view button on Fill Blank form view. 

#### Steps to reproduce the problem
scenario 1:
1. Open fill blank form 
2. Click on Sort by icon
3. Click on view map button
4. Leave the map using back button

scenario 2:
1. Open fill blank form 
2. Click on search icon 
3. Click on view map button
4. Leave the map using back button

gif of both scenarios:
![ezgif com-video-to-gif (37)](https://user-images.githubusercontent.com/33342488/94812847-91a13a00-03f7-11eb-9b76-8c5e814bd381.gif)

#### Expected behavior
Fill blank form view should display, sort by menu should not be visible, it should be hidden in both cases. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
