### ISSUE TITLE
The form end screen is not centered vertically

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4137]
#### Software and hardware versions 
Collect master branch

#### Problem description
The form end screen is not centered vertically
![Screenshot_1601642242](https://user-images.githubusercontent.com/3276264/94923849-ce833480-04bc-11eb-887e-c685db1f555b.png)

**Comment by lognaturel** [comment]
This doesn't affect v1.28, right? It came from a change merged after?

**Comment by grzesiek2010** [comment]
> It came from a change merged after?

that's correct.
