### ISSUE TITLE
The app crashes when a user tries to attach downloaded media files on Android 10

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4139]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
The app crashes when a user tries to attach downloaded media files on Android 10
it's what I discovered thanks to firebase reports:
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5321cc71b505e4165f16c7ea6223e44b?time=last-seven-days&versions=v1.28.1%20(3923)&sessionEventKey=5F79A2DE0062000179EACD3BF8DFBB82_1458154635563220359

#### Steps to reproduce the problem
1. Open the All widgets form
2. Navigate to the ImageWidget
3. Try to attach an image that you previously downloaded

![Screenshot_1601887944](https://user-images.githubusercontent.com/3276264/95059479-3aea7780-06f9-11eb-8331-7e9d996d2ee7.png)

**Comment by lognaturel** [comment]
Great find. We've had some users complaining about issues attaching images in reviews, and this must be it.
