### ISSUE TITLE
Audio recordings longer than an hour display incorrect length

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4143]
#### Software and hardware versions 
Collect v1.28.1 (and earlier)

#### Problem description

Audio recordings longer than an hour only display the number of minutes past the hour. So, if you record for 1 hour and 14 seconds the length of the recording would be "00:14":

![69143b791eef27e2a3d60a7db8fbcfbe2c74acda](https://user-images.githubusercontent.com/556280/95180697-3e920300-07ba-11eb-8dd5-218d1485b5cd.png)

#### Steps to reproduce the problem

1. Open a form with an audio question
2. Choose an audio file longer than an hour (easier than recording)

#### Expected behavior

If the time is greater than an hour we should probably display the time as "hh:mm:ss:". We should make sure this works for 100+ hours (although I doubt we'll see anyone record for that long).

**Comment by seadowg** [comment]
@grzesiek2010 @lognaturel I'm thinking we should slot this into 1.29. What do you think?

**Comment by grzesiek2010** [comment]
If we have time why not.
