### ISSUE TITLE
"Too many SQL variables" error when submitting results

### ISSUE THREAD

**Issue by nap2000** [getodk/collect#415]
#### Software and hardware versions 
Collect v1.4.11, Android v unknown, device used unknown

#### Problem description
When attempting to submit finalised data an SQL error is reported: "Too many SQL Variables...".   Refer to the attached image.

![screenshot](https://cloud.githubusercontent.com/assets/1946349/22975177/a9470590-f3c0-11e6-9dac-c4386bb4ccb5.jpg)

According to the image there were approximately 1,035 completed surveys that were being sent.

#### Steps to reproduce the problem

Complete more than 1,000 finalised surveys and submit.

#### Expected behavior

The System should not fail at an arbitrary number of completed instances.

#### Other information 
This problem is related to issue #323.  The "fix" to use an SQL "IN" instead of an "OR" appears to have offered an improvement but not a complete solution.  

The good news is that with the more compact SQL you can count the number of instances that the device is attempting to upload which in this case was 1,035.  Also the error message is more informative.  According to [StackOverflow](http://stackoverflow.com/questions/15312590/what-is-the-limit-of-sql-variables-one-can-specify-in-a-single-execsql-query) there is a limit in sqlite3 of 999 which seems to correlate with the error shown.

**Comment by nribeka** [comment]
I can have a look at this @yanokwa.

Looking real quick at the code, cmiiw, it query to get all form instances by their id and then it iterate and upload that form instance one by one, right?

**Comment by yanokwa** [comment]
Great, @nribeka! Yeah, my quick look confirms your assessment.

**Comment by nap2000** [comment]
Great.  It would be good if the solution completely removed the limit.  That is automatically send 1,500 instances rather than alerting the user that they have selected more than 999 or just sending 999 and waiting for the user to select the remaining 501.

Would it be possible to have some kind of test script that can generate a large number of test instances included as part of this fix?  This would be useful for stress testing as well as checking that any fix to this problem actually works.

**Comment by nribeka** [comment]
@nap2000 I just open #470 and was looking for some sort of script to test this out. Definitely don't want to create 1000 form instances by hand.

**Comment by nap2000** [comment]
@nribeka thanks for looking at this!

How did you go testing it with 1 instance?  Also you should test it by adjusting the SQLITE_MAX_VARIABLE_NUMBER to say "2" then try with 3 instances.  If you didn't do something like this then I think you may find some errors though I could be wrong.
  1. Row 530.  The selection args array will be greater than the number of parameters?
  2. Row 531.  When sending the second chunk won't this put a comma before the first parameter

I would have a preference for passing a new array with just the instances that are going to be sent in the chunk to processChunk.   That saves the processChunk from worrying about the complexity of start / end and might make the code easier to understand.

Yes a stress test script would be great and not just for this problem but also for those of us testing servers.

**Comment by nribeka** [comment]
@nap2000 ah you create a separate copy of array for each chunk? I think I was trying to avoid that approach, but I definitely can refactor the code if that makes the code more readable.

**Comment by yanokwa** [comment]
+1 to the test script idea. The way I'd do this is to write a script that generates all the instances folders. Then I'd copy instances.db from an existing Collect install and use an insert query to add those instances. Then move the instances and instances.db to the existing ODK install. @nribeka are you up for trying this approach out?

An alternative approach is #472, but that's going to be a bigger lift.

**Comment by nap2000** [comment]
Thanks  @nribeka. My apologies I didn't get a notification when you submitted your updated pull request or I would have reviewed it then. This is great.
