### ISSUE TITLE
The label in tabs in Delete Saved Form are not fully visible in some phones

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#416]
#### Software and hardware versions 
Collect v1.4.14-24-g5d0db9f-dirty, Android v4.4.2, Xolo Q700s plus(screen size 4.5 inch 480x854 pixels) 

#### Problem description
The label in tabs (Saved forms & Blank forms) in Delete Saved Form are not fully visible. Refer to attached image.

![device-2017-02-16-155920](https://cloud.githubusercontent.com/assets/8918023/23018248/4fc7312c-f463-11e6-85ad-e060ea029460.png)

#### Expected behavior
The tab labels should be completely visible.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 It's rather caused by screen size I think so you can add such info about a device you use.
