### ISSUE TITLE
Only fetch manifest when needed when getting form list from server

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4161]
After #4040 the app will always grab the manifest for each form when fetching the form list. This simplified a lot of code but introduces a regression where we make more requests than we did before.

#### Steps to reproduce the problem

1. Load Collect with network profiling (easiest in Android studio)
2. Set server to something with more than one form
3. Go to "Get Blank Forms"
4. Download one form
5. Refresh the form list

You'll see that when refreshing the form list the device will make a request for each form in the list (to grab the manifest). 

#### Expected behavior

Collect should only request the manifest for forms that are on the device. If a form is not on the device Collect shouldn't need to check the manifest to see if there have been any changes.

#### Other information 

This is probably best fixed by making `ServerFormDetails` an abstract type that can have `WithManifest` and `WithoutManifest` concrete implementations. That way it can just make the number of requests it needs and consumers (like `ServerFormDownloader`) can fetch the manifest only if they need to.

**Comment by grzesiek2010** [comment]
It's been a while since it was reported. The code has changed and now we download all manifest files but we store them so that we do not need to download them again when we download particular forms. I'm closing the issue.
