### ISSUE TITLE
Margin for buttons on Barcode widget and Audio widget is not visible

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4162]
#### Software and hardware versions 
Collect master

#### Problem description
Margin for buttons on Barcode widget and Audio widget is not visible

#### Steps to reproduce the problem
1. User starts All widgets form 
2. User goes to Barcode widget -> Margin for button is not visible
3. User goes to Audio widget -> Margin for buttons is not visible

|![Screenshot_20201009-115533](https://user-images.githubusercontent.com/3907554/95570226-e6ac0400-0a26-11eb-8e62-b24abb503b7d.png)|![Screenshot_20201009-115537](https://user-images.githubusercontent.com/3907554/95570227-e7dd3100-0a26-11eb-923a-a365b16e12ea.png)|
|---|---|

#### Expected behavior
Margin is visible

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
