### ISSUE TITLE
All icons on map view look like active when Magenta theme is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4163]
#### Software and hardware versions 
Collect master
Magenta theme

#### Problem description
All icons on map view look like active when Magenta theme is set

#### Steps to reproduce the problem
1. User fills `All widgets` form
2. User goes to some Geo widget with map view
3. User opens map and sees that all buttons look like active

|![Screenshot_20201009-122145](https://user-images.githubusercontent.com/3907554/95572683-9b93f000-0a2a-11eb-87d9-d5a881fc9edc.png)| ![Screenshot_20201009-122159](https://user-images.githubusercontent.com/3907554/95572690-9cc51d00-0a2a-11eb-8f9f-1fcce450293a.png)| ![Screenshot_20201009-122212](https://user-images.githubusercontent.com/3907554/95572691-9d5db380-0a2a-11eb-8dfc-b7dc90fdfc57.png)|
|---|---|---|
|![Screenshot_20201009-122306](https://user-images.githubusercontent.com/3907554/95572698-a0f13a80-0a2a-11eb-969d-78900c7608f5.png)| ![Screenshot_20201009-122322](https://user-images.githubusercontent.com/3907554/95572700-a189d100-0a2a-11eb-86b0-fb31cd8ad22b.png)| ![Screenshot_20201009-122335](https://user-images.githubusercontent.com/3907554/95572705-a2bafe00-0a2a-11eb-9cf5-11584bee08ca.png)|

#### Expected behavior
User sees active and inactive buttons on map view for Geo widget

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
