### ISSUE TITLE
Gaps in scale are visible in the Likert widget when Magenta theme is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4165]
#### Software and hardware versions 
Collect master
Magenta theme

#### Problem description
Gaps in scale are visible in the Likert widget when Magenta theme is set

#### Steps to reproduce the problem
1. User sets Magenta theme
2. User starts form with Likert widget e.g. All widgets
3. User goes to Likert widget -> User sees gaps in scale

|Magenta theme| Light theme to compare| 
|---|---|
|![Screenshot_20201009-123622](https://user-images.githubusercontent.com/3907554/95574037-a5b6ee00-0a2c-11eb-9219-defe2e9e1331.png)|![Screenshot_20201009-123700](https://user-images.githubusercontent.com/3907554/95574292-021a0d80-0a2d-11eb-964a-f73949969f1c.png)|

#### Expected behavior
Scale is visible without gaps

**Comment by grzesiek2010** [comment]
This is something related or even the same https://github.com/getodk/collect/issues/4096 can we mere it into one issue?

**Comment by seadowg** [comment]
Closing as the Likert widget no longer has lines
