### ISSUE TITLE
constraint_message not referencing actual value

### ISSUE THREAD

**Issue by erigmac** [getodk/collect#4174]
> Hi @lognaturel,
> 
> The issue seems to be closed but when i try it out in the ODKCollect v1.27.1 i don't see it working as it should. Did i get something wrong?
> 
> **Have also attached the xlsform for testing:**
> 
> [Constraint Dynamic Error Message.xlsx](https://github.com/getodk/collect/files/4739859/Constraint.Dynamic.Error.Message.xlsx)
> 
> _Originally posted by @Kalyan-Lama in https://github.com/getodk/collect/issue_comments/640039062_

Hi @lognaturel,

It seems that the constraint_message is not referencing the actual value of the variable in collect but instead referencing the location.

I can confirm with the test form that @Kalyan-Lama provided in #874  with the following results below.

As of ODK Collect v1.28.2, the message shows as
"You chose  **/data/Q1** in Q1 but now it's different!"
instead of
"You chose **Fruit 1** in Q1 but now it's different!"

Thanks,
Eri

**Comment by lognaturel** [comment]
Thanks, @erigmac and @kalyan-lama! In general, please use [the forum](https://forum.getodk.org/c/support/6) to describe unexpected behavior that you see. Developers can then triage it to the appropriate repository.

This is a form conversion issue and I have filed https://github.com/XLSForm/pyxform/issues/474. As I describe there, a workaround is to introduce an empty fake translation language column (e.g. `constraint_message::Fake`).
