### ISSUE TITLE
ODK Collect crashes if server url starts with HTTP://

### ISSUE THREAD

**Issue by hpardess** [getodk/collect#4176]
I am using Collect v1.28.2.x and Android v10.

The latest update causes to break application and ODK collect fails to fetch the form from our application. We don't use SSL certificate (http://). Is SSL certificate must to use ODK Collect?

**Comment by lognaturel** [comment]
Sorry you're having this trouble! HTTP should still be supported. Can you please share the details of your server? Is it Aggregate?

**Comment by hpardess** [comment]
We are not using Aggregate but we developed our own platform and integrated ODK collect. Everything was working as expected since last two years but after release of v1.28.2, things are broken.

My API and aggregate API returns same xml response but I don't get list of blank forms from my API. The only difference i observe between both APIs is https protocol.

**Comment by lognaturel** [comment]
Do you implement the [OpenRosa APIs](https://docs.getodk.org/openrosa/)? Those are the ones supported by Collect.

We did see some crash reports within code paths for deprecated APIs. I believed there has to be a malformed server response to trigger it (@seadowg might remember off the top of his head). If you could confirm whether you implement a non-OpenRosa API  that would help us figure out the next step.

**Comment by lognaturel** [comment]
https://github.com/getodk/collect/issues/4126 is the related issue. It looks like the crash we're seeing would only happen if implementing a legacy API AND listing a form with no ID.

**Comment by lognaturel** [comment]
Closing for now because we don't know enough to troubleshoot. If you can give us more info on what API you are implementing and ideally give us access to a server that has this problem, please let us know!

**Comment by hpardess** [comment]
Here is the response of formList from my server but they are not listed in ODK Collect
<img width="817" alt="Screen Shot 1399-08-19 at 4 14 09 PM" src="https://user-images.githubusercontent.com/6196491/98537922-9f27ca80-22a7-11eb-9cfc-fbd60ae97ac8.png">


And this is the demo URL provided by ODK and it lists the forms in odk Collect
<img width="1118" alt="Screen Shot 1399-08-19 at 4 15 58 PM" src="https://user-images.githubusercontent.com/6196491/98537610-1f99fb80-22a7-11eb-81c8-6bea1abdc3d5.png">

Also my API is not public, it is restricted and I used DigestAuthenticationEntryPoint for authentication. I was working fine since last two years but it is not working after last release of ODK collect app.

**Comment by lognaturel** [comment]
Thanks for those screenshots. They illustrate why you are experiencing #4126: `formId` values are not specified for forms. Although `formId` is required, Collect was previously resilient to it not being there. As we have reduced redundancy between code paths it is now necessary.

All that said, the API you are implementing is not documented or supported. If you have come across documentation that describes it, please let us know. It was the API for Aggregate < 1 but was replaced by [the OpenRosa formList API](https://docs.getodk.org/openrosa-form-list/) in 2009 or so. Aggregate still provides the old `formList` when not given a value for the `X-OpenRosa-Version` header but other systems should not implement it. We expect to remove Collect support for it soon.

Any information on where you found out about this API would be helpful as we manage the deprecation! I also highly encourage you to join [the forum](https://forum.getodk.org/) if you haven't already and follow the [releases](https://forum.getodk.org/c/releases/16) category to learn about betas and see what changes are upcoming in the tools that you use.

I see you also messaged me directly with some more information about your projects. Thanks for sharing and I know the community would love to learn more. The [forum showcase](https://forum.getodk.org/c/showcase/10) is a good place for that and I'm happy to work with you on a post if you'd like.

**Comment by hpardess** [comment]
Once I was reading about API and shared it in following post:
https://forum.getodk.org/t/odk-survey-blank-forms-list-response/15131

ODK collect uses either xformList or formList url to fetch the blank forms from server. You can observe the response for bellow URLs
https://opendatakit.appspot.com/xformsList
https://opendatakit.appspot.com/formList

but in latest release of ODK Collect, both APIs works as expected and lists all blank forms while my API also return same xml but it is not listing blank forms.

**Comment by lognaturel** [comment]
Do you see how URLs in the `formList` response you link to include a `formId` query parameter? e.g. https://opendatakit.appspot.com/formXml? **formId=v1.25-identify-user-track-changes-reasons** Have you tried adding that?

But again, please be aware that Collect is unlikely to support that API for long. You should read and understand [this documentation](https://docs.getodk.org/openrosa-form-list/) for the standards-compliant `formList` response. Aggregate is no longer under development and contains a lot of deprecated code so please go by the documentation rather than by the Aggregate implementation.

**Comment by hpardess** [comment]
Oh I got it... You mean the URL of each listed form must have formId query parameter.

**Comment by lognaturel** [comment]
As pointed out at https://github.com/getodk/collect/issues/4126#issuecomment-725554697 by @itlomd9 it doesn’t look like those URLs are actually parsed and there’s probably a formId element expected. The Aggregate response you see is never used so it’s not a model to follow. 

The options I see are:
- implement the expected OpenRosa API. This is what I recommend. It will be required for future Collect versions. 
- read through the Collect code to figure out where the formId was expected with the legacy API and implement that 
- propose a PR to go back to prior behavior for the legacy API 

It would be helpful to hear from both of you how you came to implement this API. Was it looking at the Aggregate response?

**Comment by lognaturel** [comment]
We will be fully removing support for the legacy Aggregate APIs in v1.31: https://github.com/getodk/collect/issues/4450.

**Comment by hpardess** [comment]
> Do you see how URLs in the `formList` response you link to include a `formId` query parameter? e.g. https://opendatakit.appspot.com/formXml? **formId=v1.25-identify-user-track-changes-reasons** Have you tried adding that?
> 
> But again, please be aware that Collect is unlikely to support that API for long. You should read and understand [this documentation](https://docs.getodk.org/openrosa-form-list/) for the standards-compliant `formList` response. Aggregate is no longer under development and contains a lot of deprecated code so please go by the documentation rather than by the Aggregate implementation.

I have changed the URL and here is result but still the latest version of odk collect does not list blank forms but it gets hang and exits from application.
This new change still works as expected in ODK Collect v1.28.2.x but fails in latest version.

<img width="761" alt="Screen Shot 1400-01-16 at 8 19 10 PM" src="https://user-images.githubusercontent.com/6196491/113594225-a41d5a00-964c-11eb-90c2-d9d130e7d24a.png">

**Comment by lognaturel** [comment]
Please either keep using Collect v1.28.x or implement the supported [OpenRosa formList API](https://docs.getodk.org/openrosa-form-list/). 

All support for the deprecated API that your server implementation uses has now been removed from Collect. It was replaced almost 10 years ago with the OpenRosa formList API and we don't know enough about it to continue supporting it.

Do also please note that your server runs http which means all of your passwords and sensitive data are sent in clear text. We strongly recommend against an HTTP server. Could you consider switching to ODK Central or another supported server implementation?

**Comment by hpardess** [comment]
https://github.com/getodk/collect/blob/a98986a3178692be0e3fb053bf22fb59718e5abe/collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java#L155

This line of code creates recent problem. The formId is sent in query parameter while it check formID elements which does not exist and set as null.

**Comment by lognaturel** [comment]
Great! That means your options are:
- Update your server to use the supported OpenRosa API
- Keep using Collect v1.28.x
- Create a fork of Collect to maintain support for the legacy API
 
See https://github.com/getodk/collect/issues/4450 and https://forum.getodk.org/t/odk-collect-v1-30/32551/2 -- all support for the legacy form list API will be removed in the next Collect version.
