### ISSUE TITLE
Add geotext widget

### ISSUE THREAD

**Issue by wonderchook** [getodk/collect#418]
In some circumstances we have users that need to manually type in coordinates from a GPS devices into the mobile device running ODK there are a couple scenarios where this happens. 

1. Situations where the GPS device cannot be connect to the phone (for example it doesn't have bluetooth)
2. Situations where data is actually collected on paper forms but is later entered through ODK

Ideally the widget would handle scenarios where a single point was collected as well are boundary corners (polygons).  One idea was to also take a picture of the GPS screen to serve as backup documentation of the data that was entered.

**Comment by jnordling** [comment]
I think there are two main ways to go about this one.

It can definitely be down via XLSForm standardIs with the text data type and groups via http://xlsform.org, I have done this in the past for manually typing in GPS from Garmin devices. For polyline/polygon data you could have a group name manual_geoshape and then either use repeated groups function or blob/long text a user can can type it in. For a single point this can be done with two fields for example manual_lat/manual_lng. 

With that,
I do agree that there is a use case for GeoWidgets to have manual inputs and I think that a great idea. I wonder if we can just add and appearance tag to the geowidgets of "manual" which just renders inputs types vs the map....

Anyways just thoughts.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I would like to work on this

**Comment by seadowg** [comment]
Closing this for now. If it still feels like a feature you'd like, then starting a discussion at https://forum.getodk.org/c/features/ is a better idea than here.
