### ISSUE TITLE
Button for launching an external app to get multiple values is unstyled

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4193]
#### Software and hardware versions 
Collect v1.18 and earlier

#### Steps to reproduce the problem
1. Launch a form with an intent group (https://docs.google.com/spreadsheets/d/1bWBACjdC-ZdQgFYCHCrQmUoORIPjU64dfcqiLm_c1fg/edit#gid=0)
1. See that the Launch button is hard to see because it doesn't look like a button

#### Expected behavior
For now we should probably use the same button style as we use everywhere else.

**Comment by grzesiek2010** [comment]
Maybe Outlined button like we use in case of media buttons or map icon button?

|  | |
| ------------- | ------------- |
| ![Screenshot_1604358172](https://user-images.githubusercontent.com/3276264/97971349-2914f680-1dc3-11eb-8503-63c7f217c6cb.png)  | ![Screenshot_1604397281](https://user-images.githubusercontent.com/3276264/97971357-2a462380-1dc3-11eb-99ac-bc78c717c0c9.png)  |

what do you think @seadowg @lognaturel I'm not good at design at all.

**Comment by seadowg** [comment]
I think just a standard `MaterialButton` (like in the screenshot on the right). I'd think of this action as "high emphasis" (it's important/primary) so the "contained button" style makes the most sense looking at https://material.io/components/buttons#contained-button. The intent behind the "outlined button" is for it to be used in "medium emphasis" (or secondary) actions.
