### ISSUE TITLE
Display sub-meter accuracies using cm

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4198]
#### Software and hardware versions 
Collect v1.28 and prior

#### Problem description
It's now somewhat practical to get sub-meter location accuracy readings and it's something @IvanGayton and others have been actively working on. Currently sub-meter accuracies are displayed using decimals. Since https://github.com/getodk/collect/issues/3336, two decimal points are included.

#### Steps to reproduce the problem
1. Get high-precision GPS equipment connected to a device
1. Get a sub-meter accuracy reading

This is going to be hard to reproduce because it generally will require specialized equipment. I think we can make the change just with tests and without having to reproduce.

#### Expected behavior
Accuracy readings under a meter should be displayed in centimeters. I don't think there should be any decimals.

https://twitter.com/SmartGeospatial/status/1322609245968281600

**Comment by lognaturel** [comment]
@ivangayton How important is it to you/your users to see sub-meter accuracy in centimeters? That is, is seeing an accuracy of `0.01m` problematic?

**Comment by ivangayton** [comment]
> @ivangayton How important is it to you/your users to see sub-meter accuracy in centimeters? That is, is seeing an accuracy of `0.01m` problematic?

**Comment by ivangayton** [comment]
Ah, sorry @lognaturel I missed the notification here!

It's not important; decimal meters is totally fine. The kind of users who, like me, will sometimes be worried about centimeter-level accuracy will be absolutely fine with some decimal places. 

People using high-end surveying gear tend to use centimeters to describe accuracy, but it's definitely not a formal convention (and some people use millimeters anyway, so even the informal convention isn't really standardized).

On the very remote chance that someone might be using civil engineering grade GPS gear ($100,000 units that can achieve millimeter accuracy) with ODK, it could make sense to allow up to three decimal places for readings in meters, but I can't really imagine a circumstance where I or anyone I work with would need more than two decimal places.
