### ISSUE TITLE
Performance improvements in loading images

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4205]
#### Software and hardware versions 
Collect v1.28.4 and older versions

#### Problem description
This is a continuation of what I discovered and described in https://github.com/getodk/collect/pull/4201#issuecomment-721690499

To sum up the problem is that having choices with images and columns-n appearance is particular leads to heavy operations that on many devices especially those poor might cause ANRs and OutOfMemoryErrors.

I prepared a sample form that show everything clearly:
[selectMinimalTest.zip](https://github.com/getodk/collect/files/5493111/selectMinimalTest.zip)

The form contains a few selects with different configurations (different number of choices, columns appearance or not, styling or not, images or not).
It clearly shows that having images is the most problematic case. It takes a lot of time and in many cases might cause OutOfMemoryErrors.

We can't leave it as is especially now when our audience is growing and more people are experiencing such problems.
I made a quick experiment and used [Glide](https://github.com/bumptech/glide) to load images in choices. The result was more than satisfying (on master opening a dialog took over 20s but using Glide just like 1s):

| Master branch  | using Glide |
| ------------- | ------------- |
| ![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/3276264/98220423-93a66d80-1f4e-11eb-8180-4140f72a5d16.gif)  | ![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/3276264/98220415-91441380-1f4e-11eb-9a9e-f8ac2a695d11.gif)  |

Glide is recommended by Google but there are also other popular libraries like [Picasso](https://square.github.io/picasso/) or [Coil](https://github.com/coil-kt/coil) so it might be worth investigating which one is best for us.

Maybe this is not even the only possible improvement we can implement (but I think the most important one). We should review our RecyclerView to check for other possible bottlenecks.

If we add Glide (or any other library) to load images in choices we should do the same in ImageWidegets.

**Comment by lognaturel** [comment]
Thanks for writing this up. We discussed today and are going to try to do it as v1.29. @grzesiek2010 I think we can broaden the issue title to include any use of images, right?

**Comment by grzesiek2010** [comment]
I just updated the form adding questions with 1k choices and can''t see any difference between 30 and 1k choices during opening the dialog:
[selectMinimalTest.txt](https://github.com/getodk/collect/files/5495847/selectMinimalTest.txt)

> I think we can broaden the issue title to include any use of images, right?

Yes I'll update the issue.
