### ISSUE TITLE
Forward button doesn't work well

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#421]
#### Software and hardware versions 
Collect v1.4.14

#### Problem description
Forward button doesn't work well.

#### Steps to reproduce the problem
1. Go to "General Settings">"Navigation"
2. Check option "Use forward/backward buttons
3. Open any form
4. Use "Go to end" option and after that "Forward" button is enabled at the last screen (what is wrong)
5. Navigate to the first question using "Backward" button
6. Navigate to the end using "Forward" button
7. Navigate to the first question using "Go to prompt" option and after that "Forward" button is disabled (what is wrong)

#### Expected behavior
"Forward" button should be always enabled on the first question.
"Forward" button should be always disabled on the last screen.

@paraschadha2052 you are working on similar #384 so you can take this one too if you want of course.

**Comment by paraschadha2052** [comment]
Yes, it looks like a similar issue. I will look into it.
