### ISSUE TITLE
Changes in audio recorders in experimental settings are not applied immediately when user sets it in the middle of the form

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4212]
### Software and hardware versions 
Collect master

#### Problem description
Changes in audio recorders in experimental settings are not applied immediately when user sets it in the middle of the form.

#### Steps to reproduce the problem
1. User starts form
2. User opens audio widget -> external recorder is opened
3. User opens `General Settings` in the middle of form
4. User goes to `Experimenta` settings
5. User unselects using an external app
6. User backs to the form and opens audio widget
7. External recorder is opened -> changes is settings wasn't applied

![4190_2](https://user-images.githubusercontent.com/3907554/98540323-0d5f9380-228e-11eb-9246-a5b85f8058cd.gif)

#### Expected behavior
The internal recorder is visible.
Changes in audio recorders are applied immediately even if user sets it in the middle of the form.

#### Notes
Related to #4190

**Comment by seadowg** [comment]
@lognaturel how do we feel about just always reloading the page/screen when we return from settings?

**Comment by lognaturel** [comment]
Seems ok. Is performance the concern? It does seem like it's probably the easiest option.

**Comment by seadowg** [comment]
It looks like we always save answers for the screen (happens in `onPause`) as well so I think just reloading when returning from settings is the way to go.

**Comment by lognaturel** [comment]
Sounds reasonable to me!
