### ISSUE TITLE
Admin can disable external recording setting

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4229]
**Acceptance**

- [x] Given I have access to Admin Settings
When I navigate to "User settings"
And I uncheck "External app recording"
Then that setting is hidden in General Settings

- [x] Given I have access to admin settings
When I navigate to "User settings"
And I check "External app recording"
Then that setting is shown in General Settings

**Comment by lognaturel** [comment]
This also interacts with https://github.com/getodk/collect/issues/4223. If "External app recording" is off in admin settings then the user should never get the option to change that setting.

It's not super likely that the admin setting would be changed before the first time a user sees an audio question but I think we should still honor it for consistency.

**Comment by seadowg** [comment]
@lognaturel makes sense. I'll add acceptance to that story.
