### ISSUE TITLE
Entering dates: re-order mm-dd-yyyy regardless of device locale

### ISSUE THREAD

**Issue by dalerhoda** [getodk/collect#424]
Entering dates on a touchscreen device is more tricky than entering other types of fields, and the entry error rates are unacceptably high, as measured in a recent experiment entering more than 10,000 known dates in 12 different combinations of factors (phone vs. tablet; single-entry vs double-entry; calendar vs. no-calendar vs. radio button interface).  (Mean rate = 1 error in every 20 dates, after throwing out data from 5 persons (of 24) with worst performance; the rate varied by combination of factors and was worst for the ODK default calendar interface on a smart phone, single-entry, averaging one error in every 10 dates entered.)

In some contexts, field staff are copying dates from a written record and it would be helpful to be able to format the interface to look as much like the written dates as possible.  

The order of month, day, and year elements in the no-calendar version of date data collection is currently tied to the device locale, but sometimes we know that the written dates will follow another format and we want to specify the order to match the written records regardless of the device locale.

Please include an option for specifying the left-to-right order of the date elements.  Thank you!

**Comment by lognaturel** [comment]
I think we can add a setting in general settings' Client section called "Date Format" that when tapped shows a dialog with radio button options. The default option can be "Use phone locale" and additional options can be "yyyy-dd-mm", "yyyy-mm-dd", "mm-dd-yyyy", "dd-mm-yyyy". Would that meet your requirements, @dalerhoda?

Another option that I haven't thought deeply about is to make this a form setting either at the form or the field level.

**Comment by NamanArora** [comment]
@lognaturel Hi! I would like to know the status of this issue. Is this still under consideration?

**Comment by lognaturel** [comment]
@NamanArora Yes! I think we just need some input from @dalerhoda to make sure we address this in a way that is most helpful. @yanokwa may have some thoughts as well.

**Comment by lognaturel** [comment]
@NamanArora If you'd like to work on this, please do. We can go with the app-wide setting I have suggested unless you have an alternative to propose. I don't know what I meant when I said "Client section" above. It should go in "User Interface" below "Text font size". It should work like "Text font size" with the options described above. It should be hideable from the Admin Settings.

The challenging part will be actually using that setting appropriately. I would recommend looking at the widgets that use dates and writing up a quick proposal of on how you would approach it.

**Comment by yanokwa** [comment]
@NamanArora Have you been able to make some progress on this?

**Comment by NamanArora** [comment]
I am not getting much time to work on it, so if anyone's interested please feel free to take this up.

**Comment by nikialexopoulou** [comment]
May I work on this one?

**Comment by grzesiek2010** [comment]
@nikialexopoulou I think it's not assigned so why not. @lognaturel

**Comment by yanokwa** [comment]
@nikialexopoulou Please go ahead!

**Comment by saraswatmanu** [comment]
Any progress on this issue yet?

**Comment by nikialexopoulou** [comment]
@saraswatmanu yes, I'm working on it.

**Comment by lognaturel** [comment]
@nikialexopoulou Don't hesitate to ask questions in Slack or send in an "in progress" pull request if you want some feedback or have any questions!

**Comment by lognaturel** [comment]
@dalerhoda Can you please let us know whether you think an an app-wide setting or a per-question form setting would be better for this? Doing it at the app level is not as straightforward as I had hoped so we really need to make sure that it's actually the right approach before going to far down that road. Keep in mind that if we do it app-wide, the decision on the date order will need to be made as phones are configured. Then either the setting will remain available to enumerators and they'll get to change it as they collect data or the setting will be hidden when the phones are configured so that enumerators always see dates in a certain way.

For example, let's say the locale is US English. Dates by default will be mm-dd-yyyy. If a setting at the app level is changed to dd-mm-yyy, all forms will use that format unless enumerators are given the ability to change the date style as they wish.

**Comment by lognaturel** [comment]
I had a chance to talk to Dale briefly about this and unfortunately an app-wide setting won't solve the problem because different forms might have different date orders. I will file an issue on the XForms spec side of things so we can discuss adding an option for date order at the form level.

@nikialexopoulou unfortunately we will need to wait on this one.

**Comment by jwishnie** [comment]
@lognaturel @dalerhoda can you explain why an app-wide setting is not appropriate?

I see date-format as a view preference that should _not_ be baked into the underlying form model.

If it is a view preference, the same forms (e.g. a standard protocol) can be used anywhere in the world, with ODK displaying (and requesting) dates in the format appropriate where they are used.

If this kind of view preference is baked into the underlying form, one would need to create a new copy of a form _just_ to get the right date format for a new location.

Seems like a bad mixing of model and view to do this

**Comment by lognaturel** [comment]
The case that @dalerhoda found was particularly error-prone is when enumerators need to enter in a date that exists on some other written material. For example, they're looking at a health insurance card with a date of birth on it or a product label with an expiration date. If the format of the ODK question doesn't match the format of the date, it's easy to make mistakes. This is something a form developer would have the knowledge to address and is independent of the form language or locale.

If you just want to match the locale of the enumerators, you can set that at the phone level and it should work great.

That said, @dalerhoda it would be very interesting to see whether some of the changes we've already made to the date widgets in response to other issues you filed help with this as well. In particular, the date is now always echoed back after selection in short form matching the locale -- "26 Oct, 2017" in US English, "26 oct. 2017" in French, etc. I expect this would help enumerators confirm correctness and catch mistakes. That said, it won't help with a product label that says "5/6/2016" (that one time I threw food away right after I bought it thinking it was a month expired, remembered I was in Latin America, pulled it out of the trash).

**Comment by jwishnie** [comment]
I have thoughts... Move to Discourse!

https://forum.opendatakit.org/t/date-formats-for-input-and-display-in-collect/10357

**Comment by breakbusyloop** [comment]
> different forms might have different date orders

Can we decouple the date format that is displayed to users from the date format that is stored in the submitted form data (and resulting spreadsheet / database)?

We could greatly reduce ETL post-processing if the form designer could ensure that dates are all stored in the same format regardless of how they are entered by the user.

**Comment by lognaturel** [comment]
> Can we decouple the date format that is displayed to users from the date format that is stored in the submitted form data

Absolutely. The format of submitted dates is governed by the [ODK XForms spec](https://opendatakit.github.io/xforms-spec/#data-types).

It's not clear from this issue thread but we're just talking about the display order, here. I think we've concluded that this needs to be specified at the form definition level but we don't have a spec for it yet so there's nothing to build.

In fact, let's close this issue and favor the forum discussion. Thanks for doing some triage, @OpenDataNerd!
