### ISSUE TITLE
Handle errors while copying recording

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4240]
- [x] Something explodes while starting recording - show error dialog, send Timber error
- [x] Storage runs out while copying (or any other IO error) - make sure file isn't deleted, show file path (and full error) in error dialog, send Timber error

**Comment by lognaturel** [comment]
Here's another interesting possible error for built-in audio: certain devices might not have the codecs we think they should. Seems like manufacturers might take some out, possibly to avoid royalties. I saw someone saying this about certain low-end manufacturers when looking for something else but am not finding the reference again. https://stackoverflow.com/a/12369710/137744 makes the claim as well. More: https://stackoverflow.com/questions/12362918/android-reliable-audio-recording-all-devices?rq=1

**Comment by seadowg** [comment]
@lognaturel yeah I've been trying to make sure we're accounting for any errors that can bubble up out of `MediaRecorder`. It looks like (and these SO's seem to back up) that if there are missing codecs, unsupported sample rates etc the error comes out of the call to `prepare()`.
