### ISSUE TITLE
Radio buttons with few options: add more space between response rows

### ISSUE THREAD

**Issue by dalerhoda** [getodk/collect#425]
When a radio button question has a small number of answer options: (e.g., male or female) it would be nice to separate them a bit, to decrease the likelihood of accidentally pressing the wrong button. 

Our recent experiment on date data entry errors also showed one error in every 50 entries of sex.  Spacing the responses farther apart might help drive this error rate down where it belongs...well below one error in every 100 entries.

**Comment by lognaturel** [comment]
I think this issue is going to depend a lot on device. I was shocked to use some devices recently where the touch screen seemed subtly off -- I'd have to tap a whole half centimeter below where I wanted the tap registered. On my own test device, taps are precise and I'd never have any chance of selecting the wrong radio button.

I see two options here:
- Decide the count limit below which there's more spacing - 2? 5?
- Add a new appearance (something like `spaced-out`) that lets the form designer specify that there should be more space.

**Comment by grzesiek2010** [comment]
@lognaturel 
now we can do that and it wouldn't be a big deal since we use RecyclerView for selects. I don't like the first option I would choose between a new appearance and a new option in settings.
What do you think?

**Comment by dalerhoda** [comment]
I like the new appearance idea.

**Comment by lognaturel** [comment]
I also prefer an appearance. But I'm wondering whether this issue might be addressed by the new `columns-n` appearance that will be in the 1.22 release. This is the same as the existing `compact-n` but includes radio buttons or checkboxes. See a sample form [here](https://docs.google.com/spreadsheets/d/19-pgIh0Kmw1Hlau_Tjt1Z0VGv57Ep47TDEI3swtKswo/edit?usp=sharing) and a screen capture of this form being filled in Collect 1.22:

![columns-n](https://user-images.githubusercontent.com/967540/58723852-eeb65700-838f-11e9-9204-747eaa9b46ab.gif)

It doesn't change the vertical target size and horizontally, the entire column is tappable. That is, I can tap in the blank space anywhere between the end of the text "Male" to the radio button for "Female" to select "Male". I do think errors of the type @dalerhoda described would be much less likely, though, and that the targets are generally easier to hit.

While I was showing new behavior from 1.22, I also wanted to highlight to @dalerhoda that dependent logic is now possible within a single screen (see the pregnancy example with relevance). I think this could really help with questions that have shared context.

**Comment by grzesiek2010** [comment]
@dalerhoda what do you think? If using columns is a good solution we can close the issue.

**Comment by dalerhoda** [comment]
@lognaturel @grzesiek2010 Thank you for roping me in.  The columns are something I've wanted for some time...I'd like to see how they look with 3+ choices, though...n with 3 choices...one answer will be comfortably far from the others but two may still be unnecessarily close.  I would like to just space those 3 responses out in one column.  (If they are very short answers, maybe 3 columns will look okay...) Mostly I see 2+ columns as a good choice for 2 answers or for 15+ very answers (to avoid scrolling...like day of the month in a yea-even-more-improved radio button date picker) but not helping a lot for 3-15 response options.  Does that make sense?

**Comment by seadowg** [comment]
As @lognaturel noticed there is a great example of it looking hard to hit the select options in [this video](https://www.youtube.com/watch?v=vR-jYWVfPS8&feature=youtu.be&t=78). I'm going to start playing with what we can do to make this better.

**Comment by seadowg** [comment]
From playing around on some different screen sizes and jumping into layout inspector it seems that there are two key problems to me:

1. The vertical sizing of the tap area for a select is fairly small (compared to a text field for instance) and there is no spacing between the options
2. There is a small margin on the left/start of the select option that won't select the option if tapped. This means users holding a larger device by the sides might miss the area altogether

This screenshot taken using the layout inspector for a 10" device illustrates these points:

<img width="1017" alt="Screenshot 2019-10-21 at 14 36 29" src="https://user-images.githubusercontent.com/556280/67245340-99e3ad80-f410-11e9-809d-bdf69e2872e4.png">

I think to fix the overall issue we can play with:

1. Increasing the height of the select options
2. Adding some kind of spacing between select options
3. Remove the margin on the left/start of the select option

The last one might be a little trickier and might be better addresses in work towards #3382 but I'll have a look/think and report back.

**Comment by seadowg** [comment]
As a quick spike I played around with using the [standard list specs](https://material.io/components/lists/#specs) to determine the vertical height of the options. I think making this change in a non hacky way (and also cleaning up some code/cosmetics) is a bit more work but I wanted to share the before and after:

![Screenshot_1571698415](https://user-images.githubusercontent.com/556280/67249091-4034b080-f41b-11e9-8f78-08a8855d850c.png)

And after:

![Screenshot_1571698320](https://user-images.githubusercontent.com/556280/67249101-47f45500-f41b-11e9-8007-b0696e4547bd.png)

These are both using a 10" hdpi screen. Does this look too big? @lognaturel @dalerhoda 

My instinct is that with this size we don't need spacing between the options as well...
