### ISSUE TITLE
Android process death might cause crashes if takes place during filling a form

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4250]
#### Software and hardware versions 
Collect all versions

#### Problem description
Android process death might cause crashes if takes place during filling a form. We have been testing destroying activities using Don't keep activities option but this is something else we also should take into account. 

#### Steps to reproduce the problem
I was able to reproduce the issue in real life without using any developer options but that might be extremely difficult or even impossible for other developers/testers so here are steps you need to use to make sure you can reproduce the problem:
1. Go to Settings -> Developer Options -> Background process limit. Set this to "No background processes"
2. Open the demo form and navigate to the image widget.
3. Click take picture
4. Put the app into background and open any other app
5. Get back to the app and take picture
6. Try to navigate forward

the difference between the steps mentioned above and those I used in real life is that I didn't change anything in settings (step 1) and sometimes I had to perform step 4 and open more than one other app **but sometimes I didn't even have to put the app into background.**

#### Expected behavior
We should get back to the form and can continue working with it.

#### Other information 
Here is a good article that describes what's going on with android process death https://medium.com/inloopx/android-process-kill-and-the-big-implications-for-your-app-1ecbed4921cb

**Comment by grzesiek2010** [comment]
### This is a big day!
All those crashes with null form controller we have seen in reports and handled adding multiple checks are caused by this issue and now we can reproduce it.
Here is another good article that describes our case https://medium.com/@davethomas_9528/please-dont-use-singletons-to-persist-state-on-android-7bac9bc78b29

> You see the Android system can kill your application at any given time. When it does all your static variables go away too. The funky thing is though, the application can be killed, and you won’t restart from your MAIN LAUNCHER activity. If the user did not specifically kill the app, the app stays in the recently used apps and the user can restart it from the activity it was suspended on.

Let's fix it once and for all.

**Comment by lognaturel** [comment]
@getodk-bot We were working on it today, actually. This is tricky stuff, give us time!! 🤖
