### ISSUE TITLE
Collect crashes when user tries to download form via CollectTester if URL settings are not set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4253]
#### Software and hardware versions 
Collect v1.28
CollectTester

#### Problem description
Collect crashes when user tries to download for via CollectTester if URL settings are not set

#### Steps to reproduce the problem
1. ODK Collect uses default server settings 
2. User uses CollectTester
3. User does not add URL settings to CollectTester
4. User goes to `Download Form` in CollectTester
5. User adds id `all-widgets`
6. Collect crashes [crash.txt](https://github.com/getodk/collect/files/5622167/crash.txt)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/100734943-b9e5ee80-33d0-11eb-9c44-793bfc6e219a.gif)

#### Expected behavior
`All widget` form is downloaded

**Comment by lognaturel** [comment]
It looks like we don't have documentation for this feature, annoyingly enough. Do you happen to remember what the expected behavior is? Is it supposed to use the URL configured by Collect in that case?

**Comment by mmarciniak90** [comment]
> Do you happen to remember what the expected behavior is? Is it supposed to use the URL configured by Collect in that case?

I've checked behavior for Collect v1.27.0 and CollectTester uses configuration defined in Collect.

**Comment by lognaturel** [comment]
That sounds right. Then I think we should include it as a bug fix for v1.29 if we can.
