### ISSUE TITLE
Read-only Ex printer widget on the field-list has no spacing below hint

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4260]
#### Software and hardware versions 
Collect 1.27.3 (older versions were not verified)

#### Problem description
Read-only Ex printer widget on the field-list has no spacing below hint

#### Steps to reproduce the problem
1. User starts a form with read-only Ex printer widget on the field-list [4228all-widgets-read-only-field-list.xml.txt](https://github.com/getodk/collect/files/5630448/4228all-widgets-read-only-field-list.xml.txt)
2. User sees Ex printer widget
3. Question has no spacing below hint

![Screenshot_20201202-165004](https://user-images.githubusercontent.com/3907554/100896368-d52f2780-34be-11eb-8dd5-04754b90fba9.png)

#### Expected behavior
Consistent appearance for all widgets is expected.
Space below the question is visible.

**Comment by grzesiek2010** [comment]
We can close this issue because we decided to remove that empty space form all read-only widgets without answers: https://github.com/getodk/collect/pull/5364
