### ISSUE TITLE
Make Geopoint display format user-configurable DMS or DD

### ISSUE THREAD

**Issue by florianm** [getodk/collect#4262]
#### Software and hardware versions 
Collect v1.29.0 beta and all versions before 

#### Problem description
Some enumerators use the coordinates captured through the Geopoint widget to backfill paper datasheets.
Since we use decimal degrees on the datasheets, the default DMS format of the captured coordinates is dangerously incorrect.

Enumerators *can* be trained to navigate the read-only view, where the coordinates are shown in their native DD format.

#### Steps to reproduce the problem
* In a form on ODK Collect, capture a Geopoint. 
* Find the captured coordinates (lat lon alt acc) displayed in DMS format after successful capture.

#### Expected behavior
Since DMS are "just numbers" without navigational value (projected Easting / Northing, being metres, would translate to distances on the ground), I see no value in the DMS format over the DD format when displaying the captured geopoint in the form.
There could be use cases that rely on the DMS format being shown after location capture. These might be fringe use cases like mine (writing data out of an ODK Collect form into a paper datasheet). The expected main use of captured Geopoints is the export from ODK Collect, which is in the native format (DD) anyways. 

I would like to suggest a configuration setting to toggle the default display format of lat/lon coordinates between DMS and DD (with a default to DMS to maintain continuity).

#### Other information 
Our current "hack" is to use the read-only navigation view in order to access DD formatted coordinates.

**Comment by lognaturel** [comment]
Let’s get this one on the forum features category for triage and broader discussion. It would be good to hear from others what’s the most helpful. Perhaps a form-level configuration would be an alternative, for example. 

In general, starting on the forum is the best way to get more visibility! Makes sense to skip for small bug fixes or totally obvious features like adding something to Build.

**Comment by florianm** [comment]
Done: https://forum.getodk.org/t/odk-collect-make-geopoint-display-format-user-configurable-dms-or-dd/31496
And yep, sorry for yet again starting an issue in the wrong place...

**Comment by lognaturel** [comment]
Thank you! No worries. With all the tools and different perspectives it is certainly confusing. The forum is always a good bet and things are less likely to get lost there.
