### ISSUE TITLE
Collect does does not support select_one_from_file with CSV with label::language_desc (language_id) - Download failure

### ISSUE THREAD

**Issue by qlands** [getodk/collect#4266]
Hi,

I  just came across a problem with ODK Collect where the App is unable to download a blank form if it uses select_one_from_file and if such CSV file has labels in multiple languages. For example: 

list_name | name | label::English (en) | label::Spanish (es) | label::French (fr)
-- | -- | -- | -- | --

Collect reports "Download Failure" but not extra information is added.

Using collect version 1.28.4

**Comment by lognaturel** [comment]
This is not currently supported. See https://forum.getodk.org/t/proposal-customize-name-and-label-columns-in-selects-from-external-data-in-xlsform/27265 for a spec-level discussion.

If you're only using Collect, https://xlsform.org/en/#external-selects or https://xlsform.org/en/#dynamic-selects-from-pre-loaded-data might be options.

**Comment by qlands** [comment]
The problem is that then both Enketo and ODK Collect are mutually excluded:
- Enketo does not support select_one_external or search() only select_one_from_file https://github.com/kobotoolbox/enketo-express/issues/545#issuecomment-242851549
- ODk Collect does support select_one_from_file with multiple languages.

**Comment by lognaturel** [comment]
> ODk Collect does support select_one_from_file with multiple languages.

Does Enketo? If it does, it's not spec-compliant. If you're interested in a spec for this that all clients can adhere to, please join the forum conversation!
