### ISSUE TITLE
Discard changes dialog visible for GeoTrace and GeoShape read-only widgets

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4267]
#### Software and hardware versions 
Collect v1.28.x, Android v all, device used...

#### Problem description
When GeoTrace and GeoShape widgets have points in read-only user is able to view map but when try to leave map view using back button discard changes dialog is displayed what suggests that some changes have been made.
![ezgif com-video-to-gif (44)](https://user-images.githubusercontent.com/33342488/101161764-98377200-3631-11eb-80de-acb3880c91c3.gif)

#### Steps to reproduce the problem
1. Open form with GeoTrace/GeoShape widget readonly with points
2. Open map view
3. Use back button to leave map

#### Expected behavior
Discard changes dialog should not be visible for read-only Geo widgets.

#### Other information 
Form that I have used: 
[4228AllWidgetsWithAnswersReadOnly.xml.txt](https://github.com/getodk/collect/files/5642595/4228AllWidgetsWithAnswersReadOnly.xml.txt)

**Comment by SaumiaSinghal** [comment]
Hi @kkrawczyk123! This is related to my work. I missed this case :/ ,thanks for reporting. I will try to fix this.

**Comment by lognaturel** [comment]
Thanks so much, @SaumiaSinghal! It's great to see you here and I hope all is well with you.

**Comment by SaumiaSinghal** [comment]
Yes @lognaturel, everything's good. Thanks for asking! :)
