### ISSUE TITLE
Entering dates: move the no-calendar wheels down to the center of the screen

### ISSUE THREAD

**Issue by dalerhoda** [getodk/collect#427]
With the current no-calendar option for collecting dates, the wheels appear near the top of the screen.

The interface allows long scrolls...as long as your finger starts on the wheel, it can scroll downward to the bottom of the screen and scroll through many options.  

There is less ability to scroll upward through many options because one's finger hits the top of the screen quickly.

This means that if the default day on the interface is 1 and you need to scroll to 10, rather than scrolling upward 9 clicks, it may be most efficient to scroll down because you can go the entire ~20 clicks with one long scroll.

It would be nice to have the option to put the wheels in the center of the screen, vertically, so the user has equal leeway for long-scrolls up or long-scrolls down.

The downside to doing this is that the length of the longest long-scroll would be shortened...because when scrolling downward the user could no longer go the length of the screen...only half its length.  

On tablets, this will be balanced by likely making it possible to go from any starting point to any ending point with one long scroll in the shortest direction.

On phones, it may hamper the user by requiring more long scrolls than before, albeit in the direction that seems most logical because it is the shortest.

This is not something I feel super strongly about, but we have noticed that the simplest entry in terms of number of scrolls & swipes is sometimes to scroll in the counter-intuitive direction and I would like to alleviate that cognitive burden and minimize the number of scroll motions necessary to reach the goal, in hopes that it will help with entry error rates.

It is fine to have a general philosophy that is device agnostic...of course we want all surveys to work on all devices, but in many cases on a particular survey we know that we'll be using tablets, and that would lead us to select this no-calendar-mid-screen option to allow equal-opportunity scrolling in whichever direction is shortest, even if it shortens the longest-possible scroll.

**Comment by lognaturel** [comment]
I think we should consider using [dialog pickers](https://developer.android.com/guide/topics/ui/controls/pickers.html).

**Comment by shobhitagarwal1612** [comment]
@lognaturel I am interested in taking up this issue

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I believe @grzesiek2010 has made some progress on this. @grzesiek2010 is that right?

**Comment by grzesiek2010** [comment]
@lognaturel yes and @shobhitagarwal1612 knows about it as we've talked on slack. Sorry I should have added a comment.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @grzesiek2010 Sounds good! I just want to make sure we don't duplicate work. 

If you're chatting about features, don't hesitate to discuss in #collect-code.

**Comment by lognaturel** [comment]
Closed by #789.
