### ISSUE TITLE
Pause button is not visible when using internal recorder on Android 5.1

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4283]
#### Software and hardware versions 
Collect v1.29.x, Android v 5.1, device used...

#### Problem description
The pause button is not visible when recording on Androids 5.1:
![Screenshot_2020-12-09-10-02-34](https://user-images.githubusercontent.com/33342488/101609228-fb951b80-3a06-11eb-93d5-5d2ba2896bfc.png)

#### Steps to reproduce the problem
Just use an internal audio recorder and device with Android 5.1

#### Expected behavior
The pause button should be visible and useable.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

@getodk-bot label "Specific to Android version"

**Comment by seadowg** [comment]
@kkrawczyk123 oooft my bad this is intended but should have mentioned it on Slack. Pause will only be available on Android 7+.
