### ISSUE TITLE
Audio widgets are not blocked while the internal recorder is recording if the external app is set as default

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4285]
#### Software and hardware versions 
Collect master

#### Problem description
Audio widgets are not blocked while the internal recorder is recording if the external app is set as default

#### Steps to reproduce the problem
1. External app for recording is used as a default
2. User starts form where audio quality is set
3. User records audio with audio quality defined
4. Other audio widgets are not blocked

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/3907554/101621928-b11b9b00-3a16-11eb-932a-fb97fee6e612.gif)

#### Expected behavior
All audio widgets are blocked

**Comment by seadowg** [comment]
@mmarciniak90 oh wow imagine if someone actually made this form! What happens after the user hits "OK" on the error dialog in the Sony app? Does it just return to Collect?

**Comment by lognaturel** [comment]
This seems ok to me. It’s effectively handled by the other recording app.

**Comment by mmarciniak90** [comment]
> What happens after the user hits "OK" on the error dialog in the Sony app? Does it just return to Collect?

You need to leave the Audio Recorder app by clicking on the back button.
Audio recorded by the internal app is still in progress. You can continue recording or stop it.
