### ISSUE TITLE
Do not ask for storage permissions users who use scoped storage

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4288]
#### Problem description
Using scoped storage we don't need storage permission because it's our own space.

#### Expected behavior
New users and those who have already migrated to scoped storage should not be asked to grant storage permission.

**Comment by grzesiek2010** [comment]
There is a problem with this issue.
When a user installs the app we check if odk dir exists on sdcard. If it exists we still use unscoped storage and automated migration will be performed.
So in order to check it we need storage permission.
So I can't turn it off for new installs because according to our definition new installs are not only those new but new + without odk dir on sdcard.

**Comment by lognaturel** [comment]
Ah, interesting. We certainly could forget about an existing `/sdcard/odk` directory in the case of a fresh install. The argument I see for keeping that behavior is that users may not realize that they have that directory and Collect picking it up does mean they get a chance to clean up. However, I can't imagine that's a very common case. What do you think?

**Comment by grzesiek2010** [comment]
Maybe you are right maybe I tried to be overprotective... even if the odk dir exists but we enable scoped storage it won't be removed so users will be able to recover their data.
