### ISSUE TITLE
PackageManger can no longer detect ODK

### ISSUE THREAD

**Issue by Mearman** [getodk/collect#4298]
This isn't an ODK specific issue, but some others here might have also encountered this.

I'm updating an app where I was using `PackageManager.getApplicationInfo` to see if ODK was installed. But that appears to no longer work.

I'm trying to use `getInstalledApplications` instead, but that appears to only give me the system app and the applications in the package-space I'm querying from itself.

Any solutions/suggestions would be greatly appreciated.

**Comment by yanokwa** [comment]
Closing because not relevant to ODK Collect. Perhaps try StackOverflow?

**Comment by Mearman** [comment]
No worries. It ended up being a new requirement to have the package query in the manifest.

**Comment by lognaturel** [comment]
Glad you figured it out! There have been many permissions-related changes to Android in APIs 28+.

If you don't already know about the ODK forum, please check it out at https://forum.getodk.org/. We try to start ODK conversations there and keep the repositories for issues that can be closed by code commits. The forum is a great place to share what you're working on and collaborate with others.
