### ISSUE TITLE
Error in Samsung 10, android 10

### ISSUE THREAD

**Issue by Charstone** [getodk/collect#4299]
![Screenshot_20201212-153903_LogME.jpg](https://user-images.githubusercontent.com/75914575/101996300-44d4bc00-3ce2-11eb-8bb1-fc3aaab56d65.jpg)[]()[]()

**Comment by Charstone** [comment]
And I created files Manually, but after logging in ERRORS OCCURRED enough to stop responding any time you open it keeps stopping....

**Comment by yanokwa** [comment]
This looks like an issue with your fork, not with stock Collect. Please comment on the issue if you can reproduce it with stock Collect and we can investigate then.
