### ISSUE TITLE
Upgrade mapbox-android-plugin-annotation

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4305]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
The current version of mapbox-android-plugin-annotation is v9:0.8.0. Upgrading it to v9:0.9.0 is not just about changing the number it will require more changes and testing as proved by:
https://github.com/getodk/collect/issues/4300
https://github.com/getodk/collect/issues/4302

**Comment by seadowg** [comment]
I think this is superseded by #4893
