### ISSUE TITLE
ExternalDataException results in fatal crash

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4310]
#### Software and hardware versions 
Collect v1.28-beta.1 (not verified previously)

#### Problem description
From [Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/cfb1b563d327a0e2823a12f20330751d?time=last-seven-days&versions=v1.29.0-beta.2%20(4026);v1.29.0-beta.1%20(4012)&sessionEventKey=5FD09D9302020001208C0386282CE26B_1482734828793756264) (credentials required):
```
Fatal Exception: org.odk.collect.android.exception.ExternalDataException
no such column: c_label (code 1 SQLITE_ERROR): , while compiling: SELECT c_key, c_label FROM externalData WHERE c_lvl2 LIKE ?
org.odk.collect.android.external.ExternalDataUtil.populateExternalChoices (ExternalDataUtil.java:228)
org.odk.collect.android.widgets.items.ItemsWidget.readSearchPulldataItems (ItemsWidget.java:80)
org.odk.collect.android.widgets.items.ItemsWidget.<init> (ItemsWidget.java:51)
org.odk.collect.android.widgets.items.SelectMinimalWidget.<init> (SelectMinimalWidget.java:21)
org.odk.collect.android.widgets.items.SelectOneMinimalWidget.<init> (SelectOneMinimalWidget.java:32)
org.odk.collect.android.widgets.WidgetFactory.getSelectOneWidget (WidgetFactory.java:266)
org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt (WidgetFactory.java:200)
org.odk.collect.android.formentry.ODKView.configureWidgetForQuestion (ODKView.java:294)
org.odk.collect.android.formentry.ODKView.addWidgetForQuestion (ODKView.java:276)
org.odk.collect.android.activities.FormEntryActivity.updateFieldListQuestions (FormEntryActivity.java:2730)
org.odk.collect.android.activities.FormEntryActivity.access$1900 (FormEntryActivity.java:217)
org.odk.collect.android.activities.FormEntryActivity$10.run (FormEntryActivity.java:2651)
```

#### Steps to reproduce the problem
Unsure but probably have a CSV external file for `search()`/`pulldata()` with a column missing.

#### Expected behavior
This should throw up an error dialog but not crash the app.

**Comment by grzesiek2010** [comment]
How about catching that exception and displaying like warnings about missing files (#4321)?
| Before  | After |
| ------------- | ------------- |
| ![Screenshot_1608208889](https://user-images.githubusercontent.com/3276264/102489643-0d616900-406e-11eb-8608-18ec918c04c2.png) | ![Screenshot_1608208404](https://user-images.githubusercontent.com/3276264/102489639-0c303c00-406e-11eb-8b95-cc228262be8e.png)  |

**Comment by lognaturel** [comment]
Wish we weren't showing raw SQL errors but not worth doing anything about now. That aside, the inline message is good. Were you able to reproduce a hard crash?

**Comment by grzesiek2010** [comment]
> Were you able to reproduce a hard crash?

No it was just a dialog that showed up and I saw an error just in logs.
