### ISSUE TITLE
SplashScreenActivity should be AppCompatActivity with a theme

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4311]
#### Software and hardware versions 
Collect v1.28 and prior

#### Problem description
If something goes wrong when getting storage permissions, a dialog is attempted to be shown but fails with an `IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

```
org.odk.collect.android.utilities.DialogUtils.showDialog (DialogUtils.java:83)
org.odk.collect.android.activities.SplashScreenActivity$1.granted (SplashScreenActivity.java:83)
org.odk.collect.android.utilities.PermissionUtils$1.granted (PermissionUtils.java:128)
org.odk.collect.android.utilities.PermissionUtils$9.onPermissionsChecked (PermissionUtils.java:275)
com.karumi.dexter.DexterInstance$1.run (DexterInstance.java)
com.karumi.dexter.MainThread.execute (MainThread.java)
com.karumi.dexter.DexterInstance.checkMultiplePermissions (DexterInstance.java)
com.karumi.dexter.DexterInstance.checkPermissions (DexterInstance.java)
com.karumi.dexter.Dexter.check (Dexter.java)
```

**Comment by grzesiek2010** [comment]
Taking into account that it's a rare crash and we are going to get rid of storage permissions does that make sense to do anything here?

**Comment by lognaturel** [comment]
Good point, @grzesiek2010, about soon no longer needing storage permissions. 🎉
