### ISSUE TITLE
Form showing after media files download failure

### ISSUE THREAD

**Issue by adrianocunha3000** [getodk/collect#4332]
Collect v1.29.2 Android v9 (2020-11) LG K12+

#### Problem description

If the download of one, more or all of the media files fails, the form still appears in the list of blank forms to be filled out. 

Well... If the media files are important for filling out the electronic form, the electronic form should not be displayed if there is a connection failure during form and media files download.

#### Steps to reproduce the problem

Create a form with three large media files.
During media download, put your phone on airplane mode to receive a failure message.
Press Fill Blank Form.
Despite the connection failure, the incomplete form will appear.

#### Expected behavior

The electronic form should not be displayed if there is a connection failure during form and media files download.

#### Other information 

This should be treated just like a cancelled form download - remove the form and any associated media files.

**Comment by seadowg** [comment]
@adrianocunha3000 thanks for reporting! ~~In previous versions of Collect the app would simply crash in this scenario, but it looks like in fixing that for 1.29 we might have introduced this weirdness.~~

Edit: Looks like the [crash on downloading media files](https://github.com/getodk/collect/issues/4324) was a regression introduced in development between 1.28.4 and 1.29.0.

**Comment by adrianocunha3000** [comment]
@seadowg Extra information - when using "Exactly match server" mode [1] and this problem happens, the refresh bottom on [fill] Blank Form screen does not download the missing media files.

[1] Great feature!

**Comment by lognaturel** [comment]
Thanks for the report, @adrianocunha3000! This is now fixed in v1.29.3 which should be available shortly from the Play Store.
