### ISSUE TITLE
Reset app state should reset Admin Settings and bulk configure file

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#435]
When you reset the app state (currently in Admin Settings), the  Settings option only resets General Settings. My vision for this app reset is to get the app back to the default settings and remove anything that could change that. I believe the reset should also:
1. Reset Admin Settings
1. Delete odk/settings/*
1. Delete /sdcard/odk/collect.settings

**Comment by grzesiek2010** [comment]
@yanokwa 
I think you are right I'll take this and I'll start work on this tomorrow.

**Comment by grzesiek2010** [comment]
I created pr for this issue but I don't understand something. As I noticed we save settings in collect.settings file which is stored in odk/settings/ so I don't understend points 2 and 3. I think it should be one point eg. "Delete odk/settings/collect.settings" am I wrong?

I created related issue https://github.com/opendatakit/collect/issues/456
