### ISSUE TITLE
Downloading a form with the same hash fails every other time

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4355]
#### Software and hardware versions 
Collect v1.29.3, works in v1.29.2

#### Problem description
Downloading a form with the same formid and version fails every other time. The user reporting this uses match exactly which is particularly annoying because the forms will disappear and re-appear periodically. https://forum.getodk.org/t/document-has-no-root-element-error-message/32121

#### Steps to reproduce the problem
1. Download a form such as All Widgets from the default server, verify it opens
2. Go back to Get Blank Form, select the same form, download it
3. Go to Fill Blank Form, see that the form is no longer there
4. On the device in `/sdcard/Android/data/org.odk.collect.android/files/forms`, verify that the form was added a `.bad` extension and is an empty file

#### Expected behavior
It should be possible to request downloading a form with the same formid and version over and over again. Files (form or media) with the same hash should be skipped.

#### Other information 
I think the problem was introduced in #4333 and is that `ServerFormDownloader.downloadXform`'s result will have a file that is the destination form XML file if the form was already on the device. Then `installEverything` will try to copy the file onto itself and apparently the result is to empty the file.

@seadowg This is freshest for you! An easy solution would be to wrap the form def copy in `if (!formFile.getAbsolutePath().equals(fileResult.file.getAbsolutePath()))` in `installEverything`. Would be great to have a test and maybe you can think of a better approach. Perhaps `file` should be `null` in this case.

**Comment by lognaturel** [comment]
Leaving this open because it's not yet fixed on master.

**Comment by seadowg** [comment]
@lognaturel I've got the cherry-pick in progress!
