### ISSUE TITLE
Collect crashes when user records selfie video when the internal audio recorder is in use

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4375]
#### Software and hardware versions 
Collect master
Android 5.1, 7.0, 7.1, 8.1

#### Problem description
Collect crashes when user records selfie video when the internal audio recorder is in use

#### Steps to reproduce the problem
1. User starts form [AllQ4222AudioQualitySelfieVideo.xml.txt](https://github.com/getodk/collect/files/5904701/AllQ4222AudioQualitySelfieVideo.xml.txt)
2. User starts recording audio via internal recorder
3. User opens selfie video widget 
4. Collect crashes

#### Expected behavior
E.g. Selfie video widget should be inactive as audio widget

#### Other information 
Discovered during testing #4354

**Comment by grzesiek2010** [comment]
We removed the selfie video widget in https://github.com/getodk/collect/pull/5468 so I'm closing.
