### ISSUE TITLE
Add group dialog displays as a first, before information about permission needed to background recording

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4388]
#### Software and hardware versions 
Collect master with background recording feature

#### Problem description
Add group dialog displays as a first, before information about permission needed to background recording

#### Steps to reproduce the problem
1. User starts form with repeat groups and background recording. Permissions are not granted
2. User sees dialog allowing to add group, under it second dialog is visible
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/107364776-2f122600-6adc-11eb-9b0d-a50a17f7d7ba.png">

3. User rotates device -> dialog informing about permission is visible as a first, under it dialog allowing to add group is visible
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/107364790-31748000-6adc-11eb-8f1e-e5fcec058c3b.png">

#### Expected behavior
Permission dialog should be always visible as a first.

#### Other information 
Related to #4385

**Comment by seadowg** [comment]
Ah nice find! @lognaturel and I discussed this and decided we won't bother fixing as:

1. It only happens the first time a user opens the form (if they haven't granted audio permissions)
2. Fixing it would be a lot of work
