### ISSUE TITLE
Refactor preference classes

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#441]
The [PreferencesActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java) and [AdminPreferencesActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesActivity.java) classes do most of their work in their `onCreate` methods. The comment "assign all the preferences in advance because changing one often affects another. also avoids npe." suggests there are interdependent preferences but these are not specifically documented. It would be great to untangle the code and put some tests in place to document the interdependences.

The [PreferenceActivity superclass](https://developer.android.com/reference/android/preference/PreferenceActivity.html) has changed since API 11 and now offers more structure. We will be changing the `minSdkVersion` to 16 in the next release (#293) so the new structure should be used in the refactor.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I would like to handle this issue. Any advices?

**Comment by yanokwa** [comment]
Hi @shobhitagarwal1612! @dcbriccetti has dibs on this issue.

**Comment by shobhitagarwal1612** [comment]
ok

**Comment by dcbriccetti** [comment]
I’d like to work this one. And I’d welcome input.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Apologies -- @dcbriccetti and I had a separate conversation about these specific classes and I filed this issue just for him. We should have made sure it was clear he was taking it on and really had more of our conversation in a public channel. We will make sure to do better in the future!

If you are interested in some refactoring, that would be great! There's a lot to do ranging from improving code style to making it more modular and introducing some tests. What I would recommend doing is filing an issue for a specific class that you want to work with to indicate that you're taking it on. You can start by issuing a pull request for surface changes like improving names, cleaning up comments, improving hanging indents, reordering methods for clarity and things like that (what you did in addition to the fix in #459). That should be quick to review and merge but will have huge value. Then you can go on to make deeper changes such as breaking monster methods into smaller ones. Even better if you can introduce unit tests as you do it. 

We haven't talked a lot about the refactoring process as a community yet and it's certainly an art that takes time to develop. I think it will be very helpful to work through several examples together and the sooner we get started, the better. I would recommend starting by issuing small pull requests with just a few changes so that they're easy to evaluate and discuss.

@dcbriccetti also has good experience with refactoring in other projects and I'm sure he will have interesting suggestions as he addresses these classes.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Do have some similar bugs in mind?
