### ISSUE TITLE
Background jobs for all projects continue to run

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4430]
Blocked by #4417 

- [x] Given I've set up match exactly in a Project
When I switch to another project
Then the both background jobs continue to work as expected

- [x] Given I've set up match exactly in two Projects
Then the both background jobs (from both projects) continue to work as expected

- [x] Given I've set up auto update in a Project
When I switch to another project
Then the auto update continue to work as expected

- [x] Given I've set up auto update in two Projects
Then the auto update (in both projects) continue to work as expected

- [x] Given I've set up auto send in a project
And I've filled out some forms that haven't sent yet
And have disconnected from the connection that lets auto send happen
When I change projects
And then reconnect to the connection for auto send
Then the forms are sent as expected

- [x] Given I've set up auto update or match exactly in a previous version of Collect
When I upgrade
Then the jobs continue to work as expected

- [x] Given I've set up a project with auto update or match exactly
When I delete the project
Then those jobs don't continue to run in the background

- [x] Given I've set up a project with auto send
And I've filled out some forms that haven't sent yet
And have disconnected from the connection that lets auto send happen
When I delete the project
And then reconnect to the connection for auto send
Then the auto send job doesn't run

- [x] Given I'm launching the app for the first time
When I add a project via a QR code
And the project config includes match exactly
Then the forms update as expected once the project is set up

- [x] Given I'm launching the app for the first time
When I add a project via a QR code
And the project config includes auto update
Then the forms update as expected once the project is set up

## Notes

We could use input data or the tag for to get the project ID to the WorkManager job. We'll also need to make sure that when we cancel jobs they only cancel for that project.

Autosend can run for all projects (that have autosend enabled) whenever it's scheduled if that's easier.

Existing work manager jobs will need to be migrated. It's actually important we do this whenever we change **any** of the background worker classes, so it might just be worth something that always reschedules background work on upgrade  (and cancels old jobs).

**Comment by lognaturel** [comment]
To consider during implementation: should submission and project delete be allowed while auto-send is in progress? 

QA had also highlighted project switching during background jobs as a possible source of weirdness but with the ways we've talked about implementing these I don't think they'd be an issue.
