### ISSUE TITLE
Log audit events for change in microphone permissions if background recording is requested

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4433]
Addition to #4380 discussed at https://github.com/getodk/collect/pull/4395#issuecomment-778084989

- [ ] Given I am filling a form that requests background recording
And I'm filling out a form
When I go to Android settings and revoke microphone permissions to Collect
Then a "microphone permissions not granted" event is added to the audit log

- [ ] Given I am filling a form that requests background recording
And I'm filling out a form
And microphone permissions are not given to Collect
When I go to Android settings and grant microphone permissions to Collect
Then a "microphone permissions granted" event is added to the audit log

See also "location permissions granted/not granted" events from background location features. In the case of background location, the permissions events are always logged on form open. I think it's less noisy and more helpful overall to only log a change if it's a deviation from the typical state. That is, we know microphone permissions were granted if the form was opened and typical form filling sessions won't have anything to do with microphone permission changes. I don't feel super strongly about this but wanted to share my reasoning for how I wrote the stories. I think it would also be ok to change the first event to `microphone permissions revoked` since it's not exactly analogous to the corresponding location one.

**Comment by seadowg** [comment]
When talking about this I'd completely breezed past the idea that we'd never actually submit an instance in which the permission was denied - we don't let the enumerator fill the form in! 

I'm also not sure if we can actually implement this as you've described in the acceptance. As far as I know there is no way to get a callback when the permissions change outside the process like this. And, as far as I can see, changing permissions at runtime resets our app process. This means that the enumerator wouldn't be able to finish filling out the form if they denied them halfway through as the form (and app) would reload, and they'd get kicked out if they continued denying the permission. 

I'm going to investigate and confirm my theory on the behaviour above, but I'm currently not sure if this makes sense ☹️

**Comment by seadowg** [comment]
Yeah, playing around with this it definitely seems that the app is killed if the user changes a permission (like disabling the microphone permission) from Android settings. When we navigate back to the app it restarts from the same place, so the user will be asked to grant permissions again as the form loads. I haven't managed to find a way of detecting that this is happening - it seems it's similar to a "Force Stop" in that `onDestroy` is not called in the Activity or Service components.

As far as I can tell there isn't a way to disable the mic and then continue to fill out a form so any additions to the audit log will never make their way to the server. Likewise, you can't grant permissions during form entry as you're not allowed into the form in the first place. Given all that it seems the only thing we could log about permission changes for a form with background recording is if the user grants permission at the beginning of the form - this would be self-evident from the fact that a recording is included however. 

@mmarciniak90 are you able to confirm this as well?  As a heads-up, when changing permissions like this, I've noticed that the recording notification pops back up when the app restarts which is something I'm investigating.

**Comment by lognaturel** [comment]
Hmm, I did not expect from review that the form would close in case of permissions being revoked but that seems reasonable! So indeed, there is no event to log.
