### ISSUE TITLE
Collect crashes when user finalizes form if microphone permission was revoked and accepted while filling the form with background recording

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4441]
#### Software and hardware versions 
Collect v1.30 Beta 1

#### Problem description
Collect crashes when user finalizes form if microphone permission was revoked and accepted while filling the form with background recording

#### Steps to reproduce the problem
Condition: 'Don't keep activity' is turned on

1. Open form with a background recording
2. Revoke microphone permission
3. Go back to form
4. Agree for microphone permission in form
5. Try to finalize form
6. Collect crashes 

stacktrace:
`2021-02-18 16:22:17.812 22910-22910/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main Process: org.odk.collect.android, PID: 22910 java.util.NoSuchElementException at java.util.HashMap$HashIterator.nextEntry(HashMap.java:854) at java.util.HashMap$KeyIterator.next(HashMap.java:885) at org.odk.collect.android.formentry.RecordingHandler.handleBackgroundRecording(RecordingHandler.java:70) at org.odk.collect.android.formentry.RecordingHandler.lambda$handle$0$RecordingHandler(RecordingHandler.java:48) at org.odk.collect.android.formentry.-$$Lambda$RecordingHandler$V-ws2wEX8QL3nQl0XXD8NB2yn5M.onChanged(lambda) at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131) at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149) at androidx.lifecycle.LiveData.setValue(LiveData.java:307) at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) at org.odk.collect.android.formentry.saving.FormSaveViewModel.lambda$createAnswerFile$1$FormSaveViewModel(FormSaveViewModel.java:378) at org.odk.collect.android.formentry.saving.-$$Lambda$FormSaveViewModel$2uu05vBIQlrmlmrKOPHT6fFCUdQ.accept(lambda) at org.odk.collect.async.CoroutineScheduler$immediate$1.invokeSuspend(CoroutineScheduler.kt:17) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6165) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

#### Expected behavior
Crash does not occur

#### Other information 
Noticed during testing #4434 
@getodk-bot label "Specific to Android version"

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123  I can't seem to reproduce this (using an Android 7 emulator). Could you post a copy of the form that you were using when you saw this?

**Comment by kkrawczyk123** [comment]
@seadowg I was able to reproduce it on: 
[AuditTestLocationBackground.xml.txt](https://github.com/getodk/collect/files/6009319/AuditTestLocationBackground.xml.txt)
[AllQ4222AudioQualityBackground.xml.txt](https://github.com/getodk/collect/files/6009320/AllQ4222AudioQualityBackground.xml.txt)
I also reproduced it on Background audio recording form from default server.

**Comment by seadowg** [comment]
> I also reproduced it on Background audio recording form from default server.

Ah interesting. I'll try these out, thanks. I wonder if the test form (used in `BackgroundAudioRecordingTest`) is different in someway that's stopping the error from happening...

**Comment by seadowg** [comment]
@kkrawczyk123 ah do you have "Don't keep activities" on?

**Comment by seadowg** [comment]
@kkrawczyk123 yeah I can reproduce this on different Android versions if I have "Don't keep activities" on. It seems that as well as the repro in the description you can reproduce by opening the form when permissions haven't been granted (and then grant them).

**Comment by kkrawczyk123** [comment]
@seadowg Yes, you are right - I've just tried that I was able to reproduce also on Android 9.0 when enabled don't keep activities. 

@getodk-bot unlabel "Specific to Android version"

**Comment by seadowg** [comment]
This is some awkwardness with JavaRosa and Andorid lifecycle butting heads.

~~I think on Android 7/7.1 this is because we actually end up opening a new Activity (and killing `FormEntryActivity`) to ask for permission, so some state is wiped out (that's kept in a `BackgroundAudioViewModel`).~~

~~In other OS versions its subtler and only explodes with the repro steps in the description (not just opening a form for the first time).~~ It looks like when come back to the form after revoking permissions we reload from a savepoint so show the hierarchy. This permission request is triggered (by JavaRosa) before `FormHierarchyActivity` starts though so is lost when we return to `FormEntryActivity`.

Bah, humbug. Definitely feels like we should fix this as it could cause some serious flakiness. /cc @lognaturel @grzesiek2010

EDIT: It repro is the same for different Android versions. I think I confused myself by not realizing I was loading a savepoint.
