### ISSUE TITLE
Remove trailing semicolon from geotrace and geoshape serialized value

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4451]
Currently traces and shapes always end in a trailing `;`. This is not very elegant but clients of data produced by Collect can typically easily be made robust to this quirk. However, it seems it's not practical to deal with it in Enketo: https://forum.getodk.org/t/problem-with-gps-shape-and-line-modification-in-enketo/32531/3.

`GeoPolyActivity.formatPoints` -- we can either explicitly deal with the fencepost problem or just trim the last `;` at the end.

**Comment by SaumiaSinghal** [comment]
Ach, @lognaturel! I didn't see this issue till now. I found, while working on issue #4267, (when we check whether the chosen map points are the same as the `originalAnswerString` or not, in order to decide whether to show the Discard Changes Dialog on pressing back button), that, `formatPoints` does not return the points formatted as to match the `originalAnswerString`. Spaces were needed to be added while concatenating  the points, and trailing semi-colon needs to be removed. 

However, I found that it is better to use `parsePoints` to compare the points and the `originalAnswer`, and so went with it. As an add on, I have updated the `formatPoints` method in the PR(#4470 ) as well.

**Comment by lognaturel** [comment]
I'm coming back to your latest comment, @SaumiaSinghal, because it seems like it might have the key to #4179. Neither @mmarciniak90 or I were able to get into a state where the underlying value had spaces between points. However, when you say:

> formatPoints does not return the points formatted as to match the originalAnswerString. Spaces were needed to be added while concatenating the points, and trailing semi-colon needs to be removed.

That really makes it sound like you got to the state in question and so that's what led you to the change we're discussing at https://github.com/getodk/collect/pull/4470#discussion_r594532039. Do you have a test or reproduction steps that got you to that state? Thanks for the helpful comment!

**Comment by SaumiaSinghal** [comment]
I reproduced the issue as follows;

User opens All Widgets Form.
User goes to Geotrace Widget
User records and saves points and moves back to Geotrace widget screen.
User can see no space between points
User kills and relaunch it.
User opens All Widget Form and checks GeoWidget
User can see spaces between points in geotrace widget


| Before killing and relaunching the app  | After killing and relaunching the app |
| ------------- | ------------- |
| ![Screenshot_20210317_055423](https://user-images.githubusercontent.com/35730054/111396798-d985f600-86e5-11eb-8e00-25e563a3e062.png) | ![Screenshot_20210317_055500](https://user-images.githubusercontent.com/35730054/111396849-f15d7a00-86e5-11eb-976d-2caa90fecf4f.png) |
| ![Screenshot_20210317_055428](https://user-images.githubusercontent.com/35730054/111396871-fd493c00-86e5-11eb-8893-c9f25d1459e8.png) | ![Screenshot_20210317_055457](https://user-images.githubusercontent.com/35730054/111396896-06d2a400-86e6-11eb-972b-5fa3531254e8.png) |

**Comment by lognaturel** [comment]
Thank you! I have no idea what @mmarciniak90 and I were doing. It's easy to reproduce just by saving a form, then opening it for edit and immediately sending it. No need to go to the question or anything like that. @mmarciniak90 can you please confirm you can also reproduce and update #4179 with the simplest steps? Looks like the bug is that there's a reformatting step that doesn't only affect display but actually changes the underlying value.

**Comment by SaumiaSinghal** [comment]
No problem at all! :)

**Comment by mmarciniak90** [comment]
The repro steps are so simple! I don't know how I missed it :disappointed: 
I'm able to reproduce. I checked it on Android 7.0, 8.1, 10.0. I also checked that issue is not dependent on the selected map, it is visible on all maps.

**Comment by florianm** [comment]
This could be a fix for getodk/central#300 which impacts @timonweitkamp

**Comment by lognaturel** [comment]
@florianm #4179 is the issue related to what @TimonWeitkamp was observing, yes. So new submissions will not exhibit the issue after the fix is released.
