### ISSUE TITLE
A user needs to click twice the up icon to navigate in the hierarchy if a repeat group is used

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4457]
#### Software and hardware versions 
Collect v1.30

#### Problem description
A user needs to click twice the up icon to navigate in the hierarchy if a repeat group is used

#### Steps to reproduce the problem
1. Open the attached form 
[names.xlsx](https://github.com/getodk/collect/files/6070324/names.xlsx)

2. Open the hierarchy
3. Click the up icon once (everything is fine)
4. Do the same again and it doesn't work you need to do this step twice

#### Other information 
The issue does not occur if we add a nested normal group: 
[names2.xlsx](https://github.com/getodk/collect/files/6070320/names2.xlsx)

**Comment by dimwight** [comment]
This looks interesting, but I can't reproduce (despite the admirably clear description) using this [slightly reworked form](https://github.com/getodk/collect/files/7001824/names.4457_.xlsx). Just a single press of the up button works fine?
