### ISSUE TITLE
Crash when using Timestamp Camera Free

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4458]
#### Software and hardware versions 
Collect v1.30.1. User's workflow was working on v1.29.5.

#### Problem description
We have reports from a user that he and his team are experiencing crashes when trying to add pictures (see [review](https://play.google.com/console/u/0/developers/6923365842552008664/app/4974849288395221404/user-feedback/review-details?reviewId=gp%3AAOqpTOEjlIqlPApaecz4t-L5MYG_gI4Czadf2bLPZl6VD1ls3QmJvFvlkbIaZvA4OMWCv-t_Xz142zucaiPflnM&corpus=PUBLIC_REVIEWS)). He says they  use [Timestamp Camera Free](https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree&hl=en_US&gl=US). I've tried using it as my default app with Moto G5, Android 7.1 and that works. I've tried attaching pictures from it with Pixel 3A, Android 11 and that also works.

I've asked for more details on workflow. I think the crash is [this one on Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/3ddd52fccd131dbe93e954f40687da19?time=last-seven-days&versions=v1.30.1%20(4094)&sessionEventKey=603E97C6006B0001177FA127E295BD67_1513593247377389545):

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:48)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:21)
android.os.AsyncTask$3.call (AsyncTask.java:394)
java.lang.Thread.run (Thread.java:923)
```

It almost looks like Collect is going out of memory but that seems really strange to happen consistently and on multiple devices.

#### Steps to reproduce the problem
Unknown.

#### Expected behavior
No crash.

**Comment by lognaturel** [comment]
@grzesiek2010 could you please take a look at this one?

**Comment by lognaturel** [comment]
We now have 14 users affected since March 1st. It appears to be consistent for them -- they're each trying a bunch of times. It's not a lot of users but it feels like there might be a deeper issue here.

The code that's crashing has been in use for picking images for some time. The thing that has changed is that it's used when an external app is used to take a picture.

The only explanation I can come up with is that the activity is going out of memory for some reason. That said, I'd expect "do not keep activities" to lead to the same crash and I can't get it to. Did you try that, @grzesiek2010? The behavior might be slightly different depending on the Android version.

Why does `MediaLoadingFragment` have a strong reference to the activity instead of using `getActivity()`? I don't think it makes a difference in behavior but would be easier to read, I think.

I believe the intent is for the task to be able to continue to run even if there is an orientation change. That's why `setRetainInstance` is set to `true` and the task has `onAttach` and `onDetach` methods. I don't think `onDetach` is necessary. Does that seem right?

**Comment by grzesiek2010** [comment]
> The only explanation I can come up with is that the activity is going out of memory for some reason. That said, I'd expect "do not keep activities" to lead to the same crash and I can't get it to. Did you try that, @grzesiek2010?

Yes I tried.

> I don't think onDetach is necessary

We can try removing it but I don't know if it's going to solve the issue.

**Comment by lognaturel** [comment]
> I don't know if it's going to solve the issue.

I /think/ it's just a no-op. Was only pointing it out because it confused me for a bit.

**Comment by lognaturel** [comment]
The user continues to report that it doesn't work but has not yet provided information to help troubleshoot. I started by asking for steps to reproduce. I have now tried asking more specific questions:

1) Do you see Take Picture / Choose image ("Tomar la Foto" o "Escojar la Imagen") buttons?
2) Which one do you tap on?
3) Which application opens when you tap on it? (Is https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree really the one that is launched)
4) Are you able to take the picture?
5) When exactly does the crash happen? Right when you get back to ODK Collect?
6) What Android version do you use?
7) Have you made any modifications to your device such as rooting it or changing developer settings?
8) Have you tried launching the photo app, taking the picture that you want and then choosing it from Collect?

**Comment by grzesiek2010** [comment]
I took another look but i have nooo idea...
Now that `MediaLoadingFragment` is widely used while attaching a file:
- draw/annotate/signature
- capture image
- choosing files (all types)
- new external binary widgets

but we have just those 14 affected users (probably from one team?) there must be something special (wrong) on their side.

**Comment by lognaturel** [comment]
Same. As I've said, it bothers me knowing that these users for sure have a problem that was caused by a change on our end but if they can't give us more information, I guess I just have to accept that we've done what we can.
