### ISSUE TITLE
About page is accessible from settings/projects dialog

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4460]
~~Blocked by #4419~~

**Acceptance**

- [ ] Given I'm on the main menu
When I click the icon on top right to open the settings/projects dialog
And I click on About
Then I land on Collect's About menu

**Notes**

The "About" menu item should be below "Add projects" in the section below the project list.

**Comment by grzesiek2010** [comment]
@lognaturel 
I wanted to make sure nothing has changed here because that about button is not visible in 
![image](https://user-images.githubusercontent.com/3276264/111787291-0fca9d80-88bf-11eb-8aa0-9938d4526463.png)

could you confirm it should be below `Add project`?

**Comment by lognaturel** [comment]
Yes, this diagram looks polished but it should be treated as high-level and fairly rough. We talked about matching how the Google apps display “terms of service” and “privacy policy” in their footers. For now let’s only include About and if it looks unbalanced when everything is in place we can add a direct link to the privacy policy, for example.
