### ISSUE TITLE
Content providers should work with projects

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4462]
~~Blocked by #4417~~

**Acceptance**

- [x] Interacting with forms from the content provider should work as if using the first created (chronologically) project
- [x] Interacting with instances from the content provider should work as if using the first created (chronologically) project

**Comment by lognaturel** [comment]
When we get here, we should do another round of discussion around the fallback behavior if no project ID is specified. I expect that would be used in the case of existing apps that interact with Collect data through the content providers.

"current project" is something that can change at any time so it feels problematic. I currently think it's easier to reason about something like "of all the projects in existence, the first one created" or some other fixed identifier. That way people who want to use an existing app that uses the content providers without a project id know that they have to make sure e.g. they first create the project they want to use the app with and then any other projects they may want.

**Comment by kkrawczyk123** [comment]
@seadowg I am not sure if it's a part of this one but I have noticed that sending submissions through CollectTester doesn't work on our beta.

**Comment by seadowg** [comment]
@kkrawczyk123 hmm could definitely be related. We'll probably use CollectTester to test changes out when working on this I'd imagine so we can check that again then.
