### ISSUE TITLE
Reset application does not remove maps cache

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#4464]
#### Software and hardware versions 
Collect v1.30.1

#### Problem description
Resetting Collect does not reset the maps cache

#### Steps to reproduce the problem
1. Uninstall Collect.
2. Reinstall Collect.
3. Get blank form and download all widgets form
4. Fill blank form using the map view. Zoom in on your area so tiles cache.
5. Admin Settings > Reset application > Select map layers and OSM tile cache
6. Put phone in airplane mode.
7. Fill blank form using the map view. Zoom in on your area and you'll see the tiles
8. Look in `/sdcard/Android/Data/org.odk.collect.android/cache` and there will still be files there.

#### Expected behavior
Reset removes `/sdcard/Android/Data/org.odk.collect.android/cache` (or its contents).

**Comment by lognaturel** [comment]
> removes /sdcard/Android/Data/org.odk.collect.android/cache (or its contents)

Are you absolutely sure you saw map tiles in that folder? It's the default Android cache folder and we don't use it. I can't reproduce any tiles ending up there and @grzesiek2010 says at #4659 that they're stored in the default location which is `/sdcard/Android/data/org.odk.collect.android/files/osmdroid/tiles`.

I think what happened is that Collect used to set a custom tile cache path to be able to control that but when we reworked the geo functionality a couple years ago that probably went away. Given that no one has asked for this and that I can't even remember why we wanted to clear the map tile cache, I think @grzesiek2010's suggestion of removing that functionality is a good one.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 says at #4659 that they're stored in the default location which is /sdcard/Android/data/org.odk.collect.android/files/osmdroid/tiles

I didn't say that I saw anything there I just said that this is the value returned if by: `Configuration.getInstance().getOsmdroidTileCache()` (which we tried to clear during resetting)

but whether it's really used... I don't know for sure.

**Comment by lognaturel** [comment]
I evaluated `Configuration.getInstance().getOsmdroidTileCache()` and got `/sdcard/osmdroid/tiles` which makes a lot of sense and does contain tiles. We can't touch that folder and shouldn't anyway.

It may be that we could set our own cache folder but I don't think it's very important and would bring up a number of annoying design issues. @yanokwa agrees with the decision we made to remove this resetting.

More info about osmdroid tile caching at https://osmdroid.github.io/osmdroid/Tile-Caching.html

**Comment by yanokwa** [comment]
And just for the record, there are files in `/sdcard/Android/Data/org.odk.collect.android/cache`, it's just not related to mapping...although `no_pois` definitely sounds mappy!

```
cache_bd.m
cache_its.m
cache_its_ter.m
cache_r.0
cache_r.m
cache_vts_inaka_org.odk.collect.android_default.m
cache_vts_labl_org.odk.collect.android_default.m
cache_vts_no_pois_org.odk.collect.android_default.m
cache_vts_org.odk.collect.android_b87c7f0634821fdd.0
cache_vts_org.odk.collect.android_b87c7f0634821fdd.m
cache_vts_org.odk.collect.android_default.m
debug
```
