### ISSUE TITLE
Add analytics for OSM question type

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4466]
Follow up from conversation on #4033. We don't know how much this functionality is used. I think the ideal is to track every time that a value is returned from the OSM app to make sure it's a real usage. We should track the form hash with that.

**Comment by SaumiaSinghal** [comment]
Hi @lognaturel! How about if I include the analytics in #4033 itself. Every time, the user clicks launch open map kit button, we should be able to track it with the form hash.

**Comment by lognaturel** [comment]
Doing it in #4033 sounds good to me, thank you! If possible, it would be great to track the /return/ from the OSM app with a non-empty response. If that's a lot more work, then tracking the launch is fine.
