### ISSUE TITLE
Instances added/removed on disk should update in Collect

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4474]
~~Blocked by #4417~~

The `InstanceSyncTask` not being run is causing a bug where the progress bar always appears on some screens (Edit Saved, Send Finalized, View Sent and Delete Saved).

## Acceptance

- [x] Given I've created a directory for an instance and copied an instance file into it
When I open the app
And I go to "Edit Saved Form"
And I click on the filled form (of the instance I copied)
Then the filled form opens as normal

- [x] Given I've filled out a form
And I've then deleted the instance directory
When I go to "Edit Saved Form"
And I click on the filled form (of the instance I deleted)
Then I don't see a crash

## Notes

In previous versions of Collect `InstanceSyncTask` would run whenever the user views an instance list in the app (Edit Saved Forms etc). This would do two things:

* Add any instances that are on disk but in the db to the db (and encrypt them if the form includes encryption)
* Remove any instances that are in the db but not on disk from the db

This is mostly undocumented and untested behaviour and there are some performance concerns around loading every instance into memory to do this every time we view an instance. Some alternative approaches could be:

~~1. Implement some form of optimized iteration through all the instances~~
2. Only add instances when viewing instance lists and show an error when trying to open an instance without a file on disk
~~3. Add a button in the app for performing this sync so it becomes on demand rather than automatic~~

**Comment by lognaturel** [comment]
#3648 is related. I assume it would just incidentally be fixed because it doesn't make sense to look for `instanceId` anywhere other than where the spec says it should be.

**Comment by seadowg** [comment]
@lognaturel coming back to this now, I'm thinking we go with option 2 (only add new instances on disk when syncing and make sure the app doesn't crash when opening instances with deleted files) and adding analytics to see if this ever actually happens. What do you think?

**Comment by lognaturel** [comment]
Sounds good to me. 👍

**Comment by seadowg** [comment]
@lognaturel great! I'll update acceptance. I might make it that the sync happens in one place (main menu for instance) so that this logic is a little more contained, but I'll play around with it and work out what's easiest.

**Comment by seadowg** [comment]
~~@lognaturel do you think we still need to support adding encrypted instances via disk sync?~~

We already added analytics to track this, so clearly we are going to see!
