### ISSUE TITLE
Text added in < > is not visible in the hierarchy view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4480]
#### Software and hardware versions 
Collect 1.30 (older versions were not verified)

#### Problem description
Text added in < > is not visible in the hierarchy view

#### Steps to reproduce the problem
1. User starts form with String widget, e.g. `All widgets` form
2. User adds value in < >
3. User opens the hierarchy view -> **added value is not visible**
4. Correct text is visible on servers: Central, Aggregate, Google Sheet

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/111646991-68883080-8802-11eb-809c-a628853d6e50.gif)

#### Expected behavior
The whole value is visible on the hierarchy list

**Comment by aasim-syed** [comment]
under what folder does this come? I think i can help!

**Comment by seadowg** [comment]
This will be regressed by #4992. We'll need to come up with a fix for this that allows selects choices to still be rendered as HTML when they are used as secondary text for a hierarchy item.
