### ISSUE TITLE
Augment "Form Download Failed" message with source of error

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4489]
Related to https://github.com/getodk/collect/issues/4345. We do swallow too much. 

Quite a few of these errors are because of misbehaving/incompatible servers and that is a nice courtesy to provide more info about.

A recent example we've seen is a CSV attachment with missing column names. It's reasonable for a server not to check this and it's currently unnecessarily difficult to troubleshoot. (related to https://github.com/getodk/javarosa/issues/444)

Mockup: https://www.figma.com/proto/XaN5etTC2Br1AyVJ1IqNi0/Errors?page-id=0%3A1&node-id=2%3A93&viewport=241%2C48%2C0.62&scaling=scale-down&starting-point-node-id=2%3A2

## Acceptance

- [x] Given I've setup Collect with a server with multiple forms
When I download the forms via "Get Blank Forms"
And all downloads succeed
Then I see a message that downloads succeeded

- [x] Given I've setup Collect with a server with multiple forms
When I download the forms via "Get Blank Forms"
And one or more downloads fail
Then I see a message that tells me how many downloads failed

- [x] Given I've setup Collect with a server with multiple forms
When I download the forms via "Get Blank Forms"
And one or more downloads fail
And I click "Show details"
Then I see a list of the forms (and their ID/version) that failed to download
And each form has a message corresponding to the error that occurred

## Notes

Right now the `FormDownloader` just throws `FormDownloadException` with no real message. We should move to including a `FormSourceException` in the `FormDownloadException` or create a similar mapping of different subtypes for different scenarios so we get more specific error messages when a download fails.

We're very likely going to want to use the "Errors" screen here in other cases (like match exactly syncs and form uploads) so it probably needs to be an `Activity` (rather than a full screen dialog or other fragment) and it would make sense for it to take a list of exceptions (with title/subtitles) in via its `Intent`.

We originally looked at making the error cards expand to show the stack trace, but we're not sure if we need that. We'll see if QA can find any cases that might move that back into scope.

**Comment by seadowg** [comment]
We need to discuss exactly how we solve this. One idea has been to include an expandable section in the error dialog that shows the exception message.

**Comment by seadowg** [comment]
It would be good to close #1703 as part of this.

**Comment by seadowg** [comment]
I've put together a mockup of an idea for a new "Errors" screen we could use to show the details of multiple errors: https://www.figma.com/proto/XaN5etTC2Br1AyVJ1IqNi0/Errors?page-id=0%3A1&node-id=2%3A2&viewport=207%2C348%2C0.6222753524780273&scaling=scale-down.

My idea is that each error would have a title (for form downloads this would be the form name), a human error message (the exception message) and then a truncated stack trace. I initially thought about having expandable error info in the dialog, but I realized it would be awkward given we'd want to show errors from both "Get Blank Form" and Match Exactly error notifications.

Interested in thoughts from @grzesiek2010, @kkrawczyk123 and @mmarciniak90.

**Comment by lognaturel** [comment]
Having a separate errors screen is a good idea! If possible, I think it would be ideal for the same human-readable error message to be shown in the initial dialog rather than just “Failure”. Often that’s enough information so there’s a lot of value to it being immediately skimmable without having to navigate away.

**Comment by seadowg** [comment]
@lognaturel I'm almost tempted to say we don't show individual form details on that failure dialog at 'Get Blank Forms' - we could just go with something even simpler like "Form downloading failed" and rely on "Show details". It seems like it's really hard to come up with something that's going to be easy to comprehend with the screen real estate there, given we might have some forms succeeding and others failing.

**Comment by mmarciniak90** [comment]
I agree with you that a human-readable error message is needed for sure. The "Failure" status is not enough, especially since the status is not highlighted somehow, the user may overlook it. Can you consider making this text bold?

I do like your idea. The user can see details (and share them) but is not overwhelmed by information on the first page.

In match exactly we have a bit different situation. User sees notification and nothing more. I'd rather be informed. As a user, I don't know even what form failed.
Is there any chance to add this behavior to match exactly?

I'm worried about the list of possible errors. Are we able to change it for all possibilities? 

>for form downloads this would be the form name 

Do you want to remove the version information? This is how Figma presents it.
Last question - Where user is moved when he clicks on the arrow?

**Comment by seadowg** [comment]
> I agree with you that a human-readable error message is needed for sure. The "Failure" status is not enough, especially since the status is not highlighted somehow, the user may overlook it. Can you consider making this text bold?

Maybe we could do something like this: if all forms succeed in downloading, just have a dialog that says something like "Form downloads succeeded" and then in cases where form downloads fail we could just list the ones that failed (and have the show details button). What do you think? I can mock that up if it's useful.

> In match exactly we have a bit different situation. User sees notification and nothing more. I'd rather be informed. As a user, I don't know even what form failed.
Is there any chance to add this behavior to match exactly?

I'm thinking we'd add a "Show details" action to the notification.

> I'm worried about the list of possible errors. Are we able to change it for all possibilities?

We have human error messages for a few different cases (which we could expand). For me the advantage of this flow is that we can fallback to just showing the exception if we don't have a human message which at least makes diagnosing the problem easier if the user posts to the forum.

> Last question - Where user is moved when he clicks on the arrow?

The back arrow or the one that expands/contracts the card? The back arrow would just return to the Main Menu I think (whatever clicking ok in the error dialog would do now) and the expand/contract arrow just shows/hides the exception stack trace.

**Comment by grzesiek2010** [comment]
Generally I like that idea. I'm wondering if we shouldn't keep it in one dialog and instead of having `Show details` button make the failures expandable. I know it would blow the dialog in case of many forms but do people really download multiple forms at once? I would rather expect them downloading 1 maybe 2 forms.

**Comment by seadowg** [comment]
>  I'm wondering if we shouldn't keep it in one dialog and instead of having Show details button make the failures expandable.

I guess my thinking around the separate screen really came from the idea that we'd need a way to show these errors in the match exactly case as well. For context, I'm making an assumption that over time Match Exactly will be more popular than Manual form management, and so I guess I'm designing for that first and then working out how Get Blank Form can fit in. Another factor is that there has been talk of eventually having even manual form downloads (and sends) occur in the background. If that ends up being the case, then they'd also have a notification, for error states. Does that make the extra screen seem more attractive?

**Comment by lognaturel** [comment]
I like where the conversation is going and just want to highlight a few things that are related in my mind (and probably need their own issues):
- I think we’ve talked about showing an error dialog directly when in match exactly mode and manually triggering a form refresh. Getting a notification in that flow is subtle and not all that helpful (as @grzesiek2010 pointed out). Whether or not we’ve discussed it, I think it would be good to at least explore. Ideally that dialog and the Get Blank Form dialog would be the same including whatever mechanism to get a stacktrace/further details designed here. 
- For those who do check the notifications, it can be pretty confusing to see failure after failure if there’s something wrong with the server or network. See [this](https://forum.getodk.org/t/alert-message-form-update-failed-confusing-the-field-workers/34562). A more specific message in the notification could help.
- We do need to eventually improve submission error messages as well. Ideally whatever is designed here can apply to that too.

**Comment by seadowg** [comment]
> I think we’ve talked about showing an error dialog directly when in match exactly mode and manually triggering a form refresh. Getting a notification in that flow is subtle and not all that helpful (as @grzesiek2010 pointed out). Whether or not we’ve discussed it, I think it would be good to at least explore. Ideally that dialog and the Get Blank Form dialog would be the same including whatever mechanism to get a stacktrace/further details designed here.

> We do need to eventually improve submission error messages as well. Ideally whatever is designed here can apply to that too.

That's a good point. I'm thinking that pushes us more and more towards a simpler dialog (that only shows for failure) that allows clicking through to details. I think we build this for Get Blank Forms with the knowledge the flow should basically be the same (and mostly reusable) for these other parts of the app. My thinking is that should be pretty easy if the whole thing just deals in lists of `Exception`s (I smell some module separation 🤗).

> For those who do check the notifications, it can be pretty confusing to see failure after failure if there’s something wrong with the server or network. See this. A more specific message in the notification could help.

I've added an issue with thoughts on improvements for the notifications experience [here](https://github.com/getodk/collect/issues/4787). I'm pretty convinced that adding retries will help us here. I'll reply to that forum thread and try and work out what they mean by "offline" (if they're truly offline, we shouldn't see failures).

**Comment by lognaturel** [comment]
A simple dialog is feeling reasonable to me as well. Could the message be generic in the case of success (“all forms/submissions succeeded”) and have a count of failures in case of issues (“2 of 3 forms/submissions failed”)?

**Comment by seadowg** [comment]
> A simple dialog is feeling reasonable to me as well. Could the message be generic in the case of success (“all forms/submissions succeeded”) and have a count of failures in case of issues (“2 of 3 forms/submissions failed”)?

Yup, that's what I'm thinking ("in cases where form downloads fail we could just list the ones that failed"). I think you're right that we don't even need to list the failed forms, though, just the number that went wrong. I can redo the mockups and now that it seems we're all thinking along the same lines!

**Comment by seadowg** [comment]
Ok I've updated the [prototype](https://www.figma.com/proto/XaN5etTC2Br1AyVJ1IqNi0/Errors?page-id=0%3A1&node-id=2%3A2&viewport=241%2C48%2C0.62&scaling=scale-down&starting-point-node-id=2%3A2) with an even simpler dialog and added clicks in. Let me know what you think!

**Comment by grzesiek2010** [comment]
I added one comment about having title and message vs just title.

**Comment by lognaturel** [comment]
I’m having trouble viewing comments so forgive me if this is redundant. It’s not clear to me what “Form 1” and “Form 3” are placeholders for. I think it’s important that the forms are identified as explicitly as possible when their identity is known. Form id and version are helpful because they get at the unique form definition that failed (as opposed to form title which may be shared between many versions). Other than that, looks good!

**Comment by seadowg** [comment]
>  It’s not clear to me what “Form 1” and “Form 3” are placeholders for

Oh I was thinking these would be form display name. I think I agree that for debugging we should have id and version as well. I'll add that to the mockup.

**Comment by seadowg** [comment]
Ok I'm going to add acceptance and the mockup to the description and remove the "needs discussion" from this now.
