### ISSUE TITLE
Refine project color

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4493]
Mock up for color picker dialog is [here](https://user-images.githubusercontent.com/967540/119382207-93fe2000-bc76-11eb-969e-56a1b35ca0c5.jpg)
Figma with project color palette is [here](https://www.figma.com/file/nDsMAYQDIflyl7rznEhwnN/ODK-Collect-Multiple-Project-Support-(v2021.2)?node-id=454%3A60).

## Acceptance

- [ ] Given I've added a project already
When I add another project with the same server domain (path and protocol can be different)
Then the new project has the same icon color
And the color is one of the project color palette colors

- [x] Given I've added a project already
When I navigate to admin settings
And click on "Project color"
Then I see a dialog with a hex value and a preview of the color
And when I change the hex value
The preview color changes

- [x] Given I've added a project already
When I navigate to admin settings
And click on "Project color"
Then I see a dialog with a color palette (of the project colors)
And when I click on one of the colors
Then the hex value changes (along with the color preview)

## Notes

Color generation based can be very simple. @lognaturel suggested something like `domain.hashCode() % numColorsInPalette` would be enough.

It probably makes sense for the color picker dialog to live in a new module (or `androidshared`) seeing as it's a potentially reusable component and shouldn't need any of collect specific logic in it. 

As much as possible we should just follow material design on the layout, so if something from the mock-up doesn't make sense it's fine to tweak it.

### Assumptions

- A lot of people won’t care what color the project is
- Some people will want to change the color (to work with their emoji icon or to differentiate from other projects that happen to be the same)
- Some people will want to use an exact color to match a brand
- People who share devices will want the color of a project to be the same across devices
- A limited set of color options is helpful for people who don't have a preference (but still want it to look good)

**Comment by lognaturel** [comment]
> Choosing a color will be harder if people can choose any color

I’d frame it as “a limited set of color options is helpful for people who don’t have specific color requirements and just need a fast option that looks good.”

This covers all I can think of for now. Another consideration that I don’t think is captured anywhere is that we will have to provide colors in a sensible format for the settings json. It would make most sense to be for that to be a hex representation.

**Comment by seadowg** [comment]
Agreed! I've changed the description.

> Another consideration that I don’t think is captured anywhere is that we will have to provide colors in a sensible format for the settings json

~~Hmmm yeah I think we need a story to drive out import/export. I'll add a placeholder to the backlog and we can discuss.~~ Nope it's #4426.

> rave specific color requirements

This was screaming to be giphyed:

![](https://media.giphy.com/media/g6dm5eMVxxo2Y/giphy.gif)

**Comment by seadowg** [comment]
We're thinking a way forward is to have a color picker that lets the user choose from the named material colors (https://material.io/resources/color/#!/?view.left=0&view.right=0) and includes a text field for a hex code all presented in a dialog. @lognaturel can mock that up and post here, so we can continue to discuss.

**Comment by lognaturel** [comment]
My sense is that this isn't worth a Figma mockup but let me know if you think that would be helpful. Here's a very rough sketch of what I have in mind (note the hex value is editable):
![dialog](https://user-images.githubusercontent.com/967540/119382207-93fe2000-bc76-11eb-969e-56a1b35ca0c5.jpg)

I don't feel very strongly about what it looks like. Here are some constraints/ideas I've considered:
- There needs to be a coherent way of showing what the current color selected is between the palette picker and the hex input. The most straightforward way I can think of doing that is showing a preview and always updating the hex value. In my drawing I put the preview to the left of the hex input but I don't feel strongly about that. It might be clearer to have a separate Preview row below. Basically, once a Material color is picked from the palette, it just populates the hex value (which remains editable) and shows a preview. I don't think there needs to be anything to mark the specific Material color that is selected at that point.
- I don't feel strongly about the layout of the palette. I like the idea of using circles to match our representation of projects. I think matching that size would be nice. That's what got me to a 4x5 grid. I also wouldn't be opposed to dropping some of the Material colors to reduce the options and make the palette more compact.
- From [the material colors](https://material.io/resources/color/#!/?view.left=0&view.right=0) linked above, the 500 variants are usually considered "the color". However, for lime, yellow and amber, white text isn't legible. We could decide that's fine and those colors are only meant for projects with emoji icon characters. Alternately, I think using 700 for those and 500 for others would work well. I'm also ok with consistently using 700 for all. Anyone feel strongly about this?
- If we were building an app from scratch I might consider making this a bottom sheet. Given that we have many configuration dialogs, I think a dialog is most consistent.

I briefly looked for a library that could help. [This one](https://github.com/enricocid/Color-picker-library) is my favorite of the bunch but it's kind of too much all around and also very deprecated. [This one](https://github.com/kristiyanP/colorpicker) might give good ideas. My current sense is that it's best to make our own.

**Comment by seadowg** [comment]
> The most straightforward way I can think of doing that is showing a preview and always updating the hex value.

Big fan of that. Seems really simple and hopefully clear as to what's going on. We should probably try this out on a few people outside the team ("hallway testing") once it's built to see if it makes sense to folks.

> We could decide that's fine and those colors are only meant for projects with emoji icon characters. Alternately, I think using 700 for those and 500 for others would work well. I'm also ok with consistently using 700 for all. Anyone feel strongly about this?

I had assumed that there must a way to grab the "accessible" text color for any given hex but haven't had a chance to look into it. If white works for all the 700s thought that seems like a neat solution!

> If we were building an app from scratch I might consider making this a bottom sheet. Given that we have many configuration dialogs, I think a dialog is most consistent.

Agreed! I think for us the dialog makes most sense right now.

> My current sense is that it's best to make our own.

Yeah this is one of those things that you always feel should be a library, but ultimately they always end up unmaintained. I think just building it but keeping it simple makes sense.

**Comment by lognaturel** [comment]
> a way to grab the "accessible" text color

The best I can see is [from the ~new~ color palette from image stuff](https://developer.android.com/reference/androidx/palette/graphics/Palette.Swatch#getTitleTextColor()). Looks like we probably could pass in an rgb int to build a swatch and use whatever the algorithm is. It wouldn't generate black or white. Body text might be what we want to get more contrast.

**Comment by seadowg** [comment]
Make sense! I think the colors scheme should just be a "GetODK" branding decision, and then we can work around the contrast probably if we need to

**Comment by lognaturel** [comment]
> the colors scheme should just be a "GetODK" branding decision

Which color is this? I was talking about automatically picking a text color for the project icon character once a project color is selected either from the material palette or from a hex code. My initial thinking was that it'd always be white but it looks like the Palette API could provide an alternate option.

**Comment by seadowg** [comment]
> Which color is this?

Sorry that wasn't clear. I meant whether we use the material colors at like 300, 500 or 700? I guess I would think that how "vibrant" or "muted" the colors are is kind of a branding decision. Of course, it totally might not matter but just calling out that I'm happy for that to just be decided, and we can then look whether we can always do one text color or need to use the Palette API.

**Comment by seadowg** [comment]
@lognaturel I'm kind of thinking that we've dropped the idea of having a "generated" color based on the server/project name. If so, I reckon it makes sense to have the "Add project" form just use a random color from our picker each time?

**Comment by lognaturel** [comment]
Looks like we've developed divergent concepts of when fallback values for project name/icon/color are set! I've described what I had in mind at https://github.com/getodk/collect/issues/4428#issuecomment-848261115. I've been imagining the defaulting as something that happens once the project configuration form is submitted, not in the form itself. 

With the simplification I've proposed at https://github.com/getodk/collect/pull/4573#issuecomment-848443742, the picker described in this thread would only be accessible from Admin Settings. By the time a user gets to it, indeed, it would always be populated by a system-provided color. I still think it's important for that system-provided color to be consistent for the same domain. I would be fine with something simplistic like hash(domain) % colors_in_palette. It does mean a lot of potential for collisions but we could adjust later if we find out that's annoying.

**Comment by seadowg** [comment]
> I still think it's important for that system-provided color to be consistent for the same domain. I would be fine with something simplistic like hash(domain) % colors_in_palette. It does mean a lot of potential for collisions but we could adjust later if we find out that's annoying.

Yeah, I agree with that. I think we're probably ready to write acceptance for this issue then: it will include adding color generation and also a picker to the "edit" screen. The last thing we need to decide on is which set of material colors to use, but maybe we can finalize that when we chat tomorrow.

**Comment by lognaturel** [comment]
I've done a quick mockup of 15 colors [here](https://www.figma.com/file/nDsMAYQDIflyl7rznEhwnN/ODK-Collect-Multiple-Project-Support-(v2021.2)?node-id=454%3A60):

<img width="248" alt="Screen Shot 2021-05-27 at 10 11 16 AM" src="https://user-images.githubusercontent.com/967540/119868435-e25c2a80-bed3-11eb-95f8-303f36b40a48.png">

I removed black and 4 other colors I didn't think added much. They're on the side for you to see. I used the 500 variant for all except for the pink which didn't feel pink enough to me. I used the A200 variant for that one.

I'm torn about the yellow. I like having a true yellow. I think it can make sense with an emoji. White text is not very legible but I'm not really sure it matters all that much? In the case where a project is randomly assigned that color, the icon character was probably also auto-generated an not meaningful either.

**Comment by seadowg** [comment]
> I'm torn about the yellow. I like having a true yellow. I think it can make sense with an emoji. White text is not very legible but I'm not really sure it matters all that much?

I think we can find a way (like with the Palette API) to use an accessible text color for the icon. People will be able to choose any color they want, so it's probably good to be doing that anyway. That can be a "post beta" issue.

I'll write up acceptance for this issue and then remove "needs discussion" as I think we're good to go here!
