### ISSUE TITLE
Make sure Google Sheets publishing works for Google Apps domains

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#450]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
Google sheets publishing doesn't work for Google Apps for your domain accounts.

#### Steps to reproduce the problem
*note: you will want to have a "Google Apps for your domain" account to test. This is an account that is in a custom domain (email address @something.com) but that is hosted on Google infrastructure. Your company or university might supply one.*
1. Go to Settings > Accounts > Google and add a Google Apps for your domain account
1. Change the protocol to "Google Sheets, Google Drive"
1. Select your Google Apps for your domain account
1. Get, fill out and try sending a form

#### Expected behavior
Google apps for your domain accounts should work like regular Google accounts

**Comment by grzesiek2010** [comment]
I'm able to use my account which is gorczykowski@soldevelo.com so look like everything is fine.
