### ISSUE TITLE
The time of finalization a form is not updated after the form edition

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4511]
#### Software and hardware versions 
Collect master
Collect v1.30.1 works correctly 

#### Problem description
The time of finalization a form is not updated after the form edition

#### Steps to reproduce the problem
1. User fills some form and finalizes it - pay attention to the finalization time
2. User waits few minutes and edits finalized form
3. User sees that finalization time isn't updated and the progress bar is visible all the time (also on Send Finalized Form, View Send Form and Delete Saved Form)

#### Expected behavior
The latest finalization time is visible, it is updated after each saved edition.

**Comment by mmarciniak90** [comment]
@getodk-bot label "regression"

**Comment by mmarciniak90** [comment]
Issue probably related with #4516

**Comment by seadowg** [comment]
Ach there is a mistake in the tests that let this slip through (comparing a string to a long to check the long had changed). Should be a simple fix.

**Comment by kkrawczyk123** [comment]
The same issue is visible when save the form, and then finalize it in another step: on edit saved form finalized date is in fact date of saving.

**Comment by seadowg** [comment]
@getodk-bot still working on it!
