### ISSUE TITLE
Auto-send appears to maintain stale state or get stuck somehow

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4513]
A user reported [on the forum](https://forum.getodk.org/t/odk-collect-saying-background-send-running-when-sending-forms/33017) being unable to manually send submissions because Collect reported a background submission was ongoing even after a device reboot.

I have experienced scanning in a QR code with the auto-send setting on and seeing that a finalized submission does not send. I have not been able to identify a pattern for when that happens. I've usually reinstalled the app when that happens.

@mmarciniak90 has also experienced unexpected behavior with auto-send that she was able to resolve by killing and restarting Collect. @mmarciniak90 was it a failure to send like I described or something else?

**Comment by grzesiek2010** [comment]
It has happened to me recently.... I thought that maybe I have spoiled something refactoring the code that is related to this functionality but if this issue exist probably it's not the case.

**Comment by dbemke** [comment]
We tried to reproduce the issue on Androids 8.1, 10, 11, 12, 13 but we weren’t able to get to the state when we weren’t able to send forms.

**Comment by lognaturel** [comment]
Thanks! Let’s close for now. No new reports that I can link to this and I have not had any related problems recently.
