### ISSUE TITLE
Recorded points are gone after minimizing app on GeoShape/Trace widgets when Mapbox is selected

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4515]
#### Software and hardware versions 
Collect v1.29, Android all , device used...

#### Problem description
When testing #4470 I have noticed that when points are recorded they are no longer visible after minimizing app and returning to it when Mapbox is selected.
![ezgif com-video-to-gif (54)](https://user-images.githubusercontent.com/33342488/114699971-3db9cb00-9d21-11eb-864b-7c7a9f90b0d9.gif)

#### Steps to reproduce the problem
1. Set map as Mapbox
2. Go to GeoTrace/GeoShape widget
3. Add some points
4. Minimize app
5. Go back to app
Points are gone, even if polygon is still visible

#### Expected behavior
Recorded points should not be lost after minimizing app. They should be visible after returning to app

#### Other information 
- Issue does not occur on Google maps and OSM
- don't keep activities was turned off

**Comment by lognaturel** [comment]
This has the same root cause as #3883 / #3515

**Comment by grzesiek2010** [comment]
This issue does not occur anymore so I'm closing.
