### ISSUE TITLE
Problems with form lists updating when something changes

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4516]
#### Software and hardware versions 
Collect master

#### Problem description
Problems with form lists updating when something changes

#### Steps to reproduce the problem
Successfully sent submission does not disappear from `Send Finalized Form` list. You need to leave the view.
![1](https://user-images.githubusercontent.com/3907554/114878119-35848d00-9e00-11eb-976a-0b5e3e11401e.gif)

Submission state is not updated on `Send Finalized Form` list
![2](https://user-images.githubusercontent.com/3907554/114878173-42a17c00-9e00-11eb-86cb-7fdd18e87d89.gif)

Deleted forms are also visible on `Delete Saved Form` list.
![3](https://user-images.githubusercontent.com/3907554/114878180-446b3f80-9e00-11eb-906c-04ed57e6f509.gif)

#### Other information 
Related to #4439

**Comment by seadowg** [comment]
I'm playing around with fixes for this. However, I was thinking it would be worth discussing an alternative: change the behaviour of these flows, so we always return to "main menu" after performing some action in a form list (sending, editing or deleting forms). This would certainly simplify the code around form lists in general as they wouldn't have to worry about reloading after these kinds of actions, but it might be that it would make some enumerators' lives harder. I'm not sure...

cc/ @lognaturel, @grzesiek2010

**Comment by lognaturel** [comment]
> always return to "main menu" after performing some action in a form list

I think this would add friction in a lot of cases and ideally it could be avoided. I think people do things like select a few submissions to send and if it doesn't take a crazy long time, they send more. In general, I think being tossed back to the Main Menu after actions can be disorienting (e.g. even after filling out a form).

How much extra complexity are we talking about? Either way the same update needs to happen, no?

**Comment by seadowg** [comment]
> Either way the same update needs to happen, no?

It would mean we'd only need to load forms when we first view the screen. The main menu already refreshes whenever you return to it.

> I think people do things like select a few submissions to send and if it doesn't take a crazy long time, they send more.

Yeah, this seems super valid. Cool I'll continue down the path I was on then! Just wanted to make sure that we discussed the behaviour.
