### ISSUE TITLE
Auto-send to fallback submission URL does not work

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4520]
#### Software and hardware versions 
Collect master

#### Problem description
Auto-send to fallback submission URL does not work

#### Steps to reproduce the problem
1. User sets Google Drive as a server and add Fallback submission URL
2. User select Auto send (Delete after send is optional but I usually select this option)
3. User downloads form, finalizes it
    
#### Expected behavior
Submission should be sent to the Fallback submission URL automatically but it's visible on the device and user needs to send it manually

#### Other information 
Related to #4439

**Comment by mmarciniak90** [comment]
@getodk-bot label "regression"

**Comment by seadowg** [comment]
@mmarciniak90 could you share the form you used please? I'm interested in if it had a submission URI in the definition or not.

**Comment by mmarciniak90** [comment]
@seadowg, as I remember I tried a few forms. You can easily reproduce this with `All widgets` form downloaded from the default server.

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/3907554/116240558-428c6f00-a764-11eb-8bc8-7037405f31ea.gif)

**Comment by seadowg** [comment]
We should address this when doing #4430
