### ISSUE TITLE
Infinite progress bar on all Collect views

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4525]
#### Software and hardware versions 
Collect master, Android v all, device used...

#### Problem description
Progress bar is loading infinitely on Edit Saved Form, Send Finalized Form, View Sent Form and Delete Saved Form views even views are empty. 

#### Steps to reproduce the problem
1. Install Collects master
2. Open each views

#### Expected behavior
- Progress bar should not load infinitely
- Progress bar should disappear when the view is loaded

#### Other information 
Progress bar disappears after screen rotation but only on Edit Saved Form and View Sent Form Views.

**Comment by kkrawczyk123** [comment]
@getodk-bot label "regression"

**Comment by seadowg** [comment]
Closing this as I remembered it's just a consequence of #4474.
