### ISSUE TITLE
Can't use `ActivityScenario#launch` with action Intents in tests

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4536]
This is because of https://github.com/android/android-test/issues/496 (which is closed but still occurring). Tests affected by this have comments with the issue URL.

**Comment by seadowg** [comment]
Found a work around for this in the end.

**Comment by ryanholden8** [comment]
Facing the same issue - Can I ask what was the workaround?

**Comment by seadowg** [comment]
Using `androidx.test` 1.5.0 it looks like we are able to use action Intents with `ActivityScenario` in instrumented tests (i.e. running on a device/emulator), but it looks like it still doesn't work in Robolectric. For the latter though, we'd not as far as I can think ever be launching an Activity implicitly so that's good enough for us right now (although frustrating that it's inconsistent).
