### ISSUE TITLE
Answers to required questions are gone when finalize form 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4566]
#### Software and hardware versions 
Collect v1.30.x, Android v probably all, device used...

#### Problem description
When testing Central, I have noticed that some of the added answers in the form are gone when trying to edit on Central. I investigated and it turned out that they are gone when finalizing form on Collect so it's not a Central issue. 
Form that I have used: https://test.getodk.cloud/#/projects/307/forms/elqas_v1
[elqas_v1.xlsx](https://github.com/getodk/collect/files/6493592/elqas_v1.xlsx)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/33342488/118485971-5733a580-b719-11eb-9ce8-1e29ffe18fcb.gif)

#### Steps to reproduce the problem
1. Download form to Collect
2. Fill the submission, all required questions 
3. Finalize form
4. Open Edit Saved form and see that previously added answers are gone: question "Name of locality" for all repeats. 

#### Expected behavior
Answers to required questions should not be cleared when finalizing the form. 

#### Other information 
I haven't noticed such an issue when using other forms with required questions.

**Comment by lognaturel** [comment]
This form misuses `calculate`s in an attempt to have dynamic defaults. On finalize, the value of `house_locality_name` is always set to the value of `locality`. `locality` is not required (weird) and I see in your video that you didn't give it a value. That means the value of `house_locality_name` for every repeat instance is always cleared on save. More [in this recent forum thread](https://forum.getodk.org/t/how-to-popout-a-value-for-the-next-question/33491/4?u=ln).

CC @yanokwa who might know where this form came from (eLQAS v1). Would be good to let folks know about this mistake if the form is still in use/published. CC also @grzesiek2010 so you can see in action why I really wanted to add to that forum thread.

**Comment by lognaturel** [comment]
Although this is mostly a form design issue, there is something weird about the order of evaluations and checks on form finalization that would be good to investigate at some point. I've filed https://github.com/getodk/javarosa/issues/633.

**Comment by yanokwa** [comment]
The form is published at https://github.com/polio/elqas but I don't know anyone using it.
