### ISSUE TITLE
Repeat is not shown in hierarchy view if first instance has no relevant content

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4570]
#### Software and hardware versions 
Collect v1.30.1

#### Problem description
Repeat is not shown in hierarchy view if first instance has no relevant content

#### Steps to reproduce the problem
See [this form](https://docs.google.com/spreadsheets/d/1gs1vBCotSUsZ7A3YJdtfs-KOrCcbhyFUOWMPO-lm4p0/edit#gid=0). Select 'beans', see that the repeat is shown in the hierarchy view. Select some other vegetables but not 'beans' and see that the repeat is not shown.

#### Expected behavior
The repeat should be shown even if its first instance has no relevant content. This is related to another issue I know we've discussed where if there are no instances of a repeat yet, it doesn't show in the hierarchy view. It might make sense to fix both and always show a repeat if there is one in the `body`.

**Comment by dimwight** [comment]
Took an initial look at this, partly as a way of getting to grips with repeats. The trouble seems to start in `FormHierarchyActivity.refreshView`  on entry to the switch case `EVENT_GROUP`, where `FormController.isGroupRelevant` returns `false`. So maybe a Javarosa issue?

**Comment by dimwight** [comment]
Actually not, there seems to be a trivial fix in `FormHierarchyActivity.refreshView`. Working on a PR.

**Comment by seadowg** [comment]
@dimwight I'm trying to dig into the issue here and thought you might have already covered the same tracks. Why is it that selecting "Beans" in the attached form works and selecting other veg doesn't? As far as I can see the repeat has "relevant content" no matter what kind of veg is selected.

**Comment by dimwight** [comment]
@seadowg do you have time to review my explanation added to #4762 about a week ago? I had hoped this would make clear what seems to be going on and why my proposed fix works.

**Comment by seadowg** [comment]
Sorry for the delay @dimwight. I'll hopefully be able to take a look within the next couple of days.

**Comment by seadowg** [comment]
I've managed to create a simpler form that seems to demonstrate the problem: https://docs.google.com/spreadsheets/d/11WQI3IpKuqLAaoU-djxOyIxTuED10IFqKBlta_dL7Q0.
