### ISSUE TITLE
Add Google account support to project setup

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4575]
~~Blocked by #4428~~
Mockup: https://www.figma.com/file/nDsMAYQDIflyl7rznEhwnN/ODK-Collect-Multiple-Project-Support-(v2021.2)?node-id=37%3A219

## Acceptance

- [x] Given I've navigated to the manual project setup screen
When I click "Configure" next to "My project uses Google Drive
And I choose my account
Then my project is added as my google account name (email)
And the project icon is the first letter of my account name
And the in the project list it shows "`<google account name>` / Google Drive" under the project name

- [x] Given I've navigated to the manual project setup screen
And I have a Google account on the phone with forms set up
When I click "Configure" next to "My project uses Google Drive
And I choose my account
And I navigate to Get Blank Forms
Then I can download the forms I have in my account

- [x] Given I've navigated to the manual project setup screen
When I click "Configure" next to "My project uses Google Drive
And I click cancel
Then I return to the manual setup screen

- [x] Fix font size for "My project uses Google Drive" text

**Comment by lognaturel** [comment]
See https://www.figma.com/file/nDsMAYQDIflyl7rznEhwnN/ODK-Collect-Multiple-Project-Support-(v2021.2)?node-id=37%3A219 for a concept. I've added `My project uses Google Drive. Configure.` ~to track the bottom bar~ (tracking the bottom bar might cause all kinds of overlap problems so let's just do some even vertical space from the help text. We can probably add the help text with this issue, too). I think the eye is kind of drawn to it which is too bad but I'm not coming up with other ideas I like at the moment. Anyone else?

Tapping `Configure` would show the "Choose account" dialog. Choosing an account and then tapping "OK" would implicitly set the server type to Google Drive. Both the project name and username would be based on the Google account name. Server would just be "Google Drive". So if I select lollipopsrainbows@gmail.com, I'd see the project listed as:

(L) lollipopsrainbows@gmail.com
      lollipopsrainbows@gmail.com / Google Drive
