### ISSUE TITLE
Add import/export of project details via QR

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4582]
## Acceptance

- [x] Given I'm viewing a project's QR code in settings on my first device
And have Collect open on a second device
When I click "Add project" on the second device
And scan the QR code displayed on the first device
Then a new project is added to the second device
And the project details (name, icon etc) are the same as the project on the first device
And the settings for the project are the same as the project on the first device

- [x] Given I'm viewing a project's QR code in settings on my first device
And have Collect open at the first launch screen on a second device
When I click "Configure with QR code" on the second device
And scan the QR code displayed on the first device
Then a project is set up to the second device
And the project details (name, icon etc) are the same as the project on the first device
And the settings for the project are the same as the project on the first device

- [x] Given I'm viewing a project's QR code in settings on my first device
And have Collect open at Admin Settings
When I click "Configure with QR code" on the second device
And scan the QR code displayed on the first device
Then the project is updated on the second device
And the project details (name, icon etc) are the same as the project on the first device
And the settings for the project are the same as the project on the first device

## Notes

The project details could live in either `admin` or in a new `project` object in the config JSON depending on whatever is easiest for implementation.

**Comment by lognaturel** [comment]
I went over [our original planning doc](https://docs.google.com/document/d/14306XDqkua_p1iOUmHqJq9vH2nFepPqR-ieYaukpxKw/edit) and I see we left whether to introduce a `project` object or to put project settings in the existing `admin` object as TBD. I now remember that the question we had was around how we go from a settings screen to `SharedPreferences` to a JSON representation. My hunch is that it's simpler to just use `admin` but I'm not sure.

I don't think there's a strong user-facing difference to one over the other. On one hand, there's something clean about the JSON reflecting the screens in the app. On the other, it's very natural to think of project settings as separate.

I think in this case implementation tradeoffs can drive the decision.

**Comment by seadowg** [comment]
Cool ok so it seems like we're all on the same page that there isn't a strong reason to go in any direction. @grzesiek2010 I'll change the note in the description.
