### ISSUE TITLE
GPS Connection Issue

### ISSUE THREAD

**Issue by krishnapaul123456** [getodk/collect#4585]
Dear team I am getting issue when trying to capture location detail using my Android phone I have tried multiple time to capture location using Android version -8.1 but satellite connectivity is showing 0/24 and location provider is showing fused
![IMG-20210528-WA0005](https://user-images.githubusercontent.com/85030623/120077417-fbc5c800-c0c7-11eb-9371-324222dd0f1d.jpg)
![IMG-20210528-WA0006](https://user-images.githubusercontent.com/85030623/120077481-434c5400-c0c8-11eb-8b89-2dc10f18b312.jpg)
![IMG-20210528-WA0007](https://user-images.githubusercontent.com/85030623/120077483-447d8100-c0c8-11eb-8512-0942bd6f3a66.jpg)
![IMG-20210528-WA0005](https://user-images.githubusercontent.com/85030623/120077488-45161780-c0c8-11eb-9d29-8da9c974c697.jpg)

#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by mmarciniak90** [comment]
I only see this behavior inside the building. @krishnapaul123456, did you see this outside?
In general, finding satellites inside the building is more difficult.
It's not related to only Android 8.1 but to all devices. 
Verified on v1.30.1

**Comment by krishnapaul123456** [comment]
Yes I have tested it in open ground and getting the same issue where accuracy is showing 3000m and satellite connection is 0,I don't know what is issue.

**Comment by lognaturel** [comment]
This is likely related to your specific device or to permissions you have or haven’t granted. It is unlikely to be reproducible with other devices. To see if other users have had a similar experience and may have advice, please post to the community forum at https://forum.getodk.org.
