### ISSUE TITLE
Prevent editing of submissions that failed to send

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4589]
We've been getting more and more reports of users getting submission errors because the server has already received a submission with the current submission's id but with different XML. From Central, the error message is 

> A submission already exists with this ID, but with different XML. Resubmissions to attach additional multimedia must resubmit an identical xml_submission_file.

See [this forum post](https://forum.getodk.org/t/odk-central-upload-error-a-submission-already-exists-with-this-id-but-with-different-xml/33596) for an example.

I think the majority of these errors would be prevented if we didn't allow editing of submissions that failed to send. I can't think of a downside of doing this -- it really is unexpected that those could be edited. My guess is that data collectors open failed submissions to try to see what could have happened and then save them when they exit which would change the value of an end timestamp if there is one.

Longer-term I think we should stop allowing edits of any finalized forms but that's a much more disruptive change so I'd like us to consider the narrower proposal above first.

**Comment by lognaturel** [comment]
@dimwight I know you're working on becoming one of the universe's top 4 experts on external data in ODK through https://github.com/getodk/collect/issues/4500 but I just thought of you in the context of this issue. I /think/ it will be relatively straightforward. It might just be adding some tests and then adding a condition to an `if`, I'm not sure. It will definitely have significant user impact so could be really satisfying to do. I've claimed it for myself for now but happy for you to take it on if it seems like an interesting one to you!

**Comment by dimwight** [comment]
Thanks for thinking of me @lognaturel, since this seems a pressing issue I can put #4500 on the back burner for a while (currently working on an automated test for what looks like a fairly complete solution). 
To save spending the usual week trawling the codebase, any hints as to where the relevant portions live?

**Comment by lognaturel** [comment]
> currently working on an automated test for what looks like a fairly complete solution

Oh wow, that's great! Up to you -- if you prefer to have one thing in your head at a time, it might make sense to wrap that up. There's no major rush here. We're at least 3 weeks out from a release and that's probably optimistic given what's still pending in https://github.com/getodk/collect/issues/4439.

Here's the journey I went on trying to find where this would be:
- First I looked for tests around editing saved forms. I see some related testing in Android connected feature tests (Espresso) but nothing specific to editing saved forms. I searched by names I would expect and then looked in the `instancemanagement` package as well as the `forms` module. I don't see anything and that kind of makes sense because it's code that hasn't been touched in a long time.
- Then I went looking for the implementation. I was looking for something with "edit saved" or "instances" in the name. Then I remembered `InstanceChooserList` (which is an `Activity`) from experience -- that was not very obvious. I remembered that `InstanceChooserList` is used both for showing a list of sent forms and a list of editable forms. That's what the `editMode` field is about.
- In `onCreateLoader`, I see the `CursorLoader` that drives the list generated from two different methods depending on whether we're editing or not.
- The pair of `CursorLoaderFactory.createUnsentInstancesCursorLoader` methods look like what we're looking for. Currently they include all form instances with a status other than `STATUS_SUBMITTED` which would include `STATUS_SUBMISSION_FAILED`.

Instances have 4 possible statuses which are defined at the top of the `Instance` class. We'd like to only include submissions that have `STATUS_INCOMPLETE` or `STATUS_COMPLETE`. These correspond to finalized/unfinalized from a user perspective.

The hard part is testing this. The ideal would be to have as narrow of a test as possible but I'm not seeing great options. Maybe `CursorLoaderFactory` can be tested directly? I don't think we should consider dramatically restructuring this code at the moment. It might make the most sense to go with an integration type of test.

**Comment by dimwight** [comment]
Thanks, that's just what I was hoping for.
#4500 now just needs a lot of drudge work before some sort of PR emerges from the mist, so perhaps I could follow your trail for a few days and see where it leads me.

**Comment by dimwight** [comment]
PS -
>It might make the most sense to go with an integration type of test.

Illustrative examples within Collect?

**Comment by lognaturel** [comment]
> drudge work before some sort of PR emerges from the mist

Great, this will hopefully be a nice palate cleanser, then!

> Illustrative examples within Collect?

You might want to start by looking at `EditSavedFormPage` which is a [Page Object](https://martinfowler.com/bliki/PageObject.html) providing an API to interact with the "Edit Saved Form" screen in UI-driven tests. You can run `QuickSaveTest` to see how it's used. You should see all the steps in the test happen on your emulator/device. `clickEditSavedForm` opens the "Edit Saved Form" screen and verifies what instances are there.

I think the new test would be in a new test class in the `androidTest` `instancemanagement` package. `DeleteFilledFormTest` and `SendFinalizedFormTest` are pretty similar to what I'm imagining `EditSavedFormTest` would look like. The new thing will be getting a submission in a "failed to send" state. You can't simulate not having a network connection because that's handled separately. I see the `StubOpenRosaServer` has `alwaysReturnError` which looks like just what we'd need. Maybe `TestDependencies` could have a constructor that makes it possible to configure the server to always return an error.

**Comment by dimwight** [comment]
Thanks @lognaturel for this gen, I would welcome your thoughts on the following tentative conclusions (the more tentative as I'm still so new to the territory). 

### The issue

* Seems to arise when the server has actually received a submission but its `HttpPostResult` has not arrived back due to a network failure. 
* So submissions logically have a limbo-like status once they have been sent but before a response is received. 
  * This normally lasts almost no time but is prolonged indefinitely on a network failure. 
### One resolution
* We could formalise the limbo status by applying eg a (generally temporary) `STATUS_SUBMISSION_INITIATED`. 
* But this would substantially complicate the submission process eg in `InstanceServerUploader.uploadOneSubmission` and `InstanceUploader.submissionComplete`.
  * Submission status would be essentially ternary - couldn't be represented as a `boolean`, would need something `enum`-like.
* And we would need to provide for subsequent handling of forms where due to network failure the temporary status wasn't overwritten.
  * All to trap a statistically rare event.
### Another solution?
* Might it be simpler to consider locking finalized forms? A bit draconian, but logically clean and to my untutored eye looks fairly simple to implement. 
* For instance
  * Add a toast warning, requiring an OK, that finalizing will lock the form. 
  * Exclude finalized forms from `InstanceChooserList` when it's 'Edit Saved Form'). 
* Since such a change would noticeably affect the user experience, I imagine it would need to be considered carefully. 
* However in the meantime I can have a speculative go at a detail implementation - if only as part of my continuing self-training. :)

**Comment by lognaturel** [comment]
Your analysis looks good! We already have the `STATUS_SUBMISSION_FAILED` status which means that a send was requested but not completed. That's the status we want to exclude editing on for now.

> Might it be simpler to consider locking finalized forms?

Unfortunately we know this would disrupt existing workflows. Like I said in the original issue, it would be an eventual goal but we need to announce it, design a thoughtful UI that communicates the change, etc. In the mean time, preventing edits of `STATUS_SUBMISSION_FAILED` accomplishes what we need with no downside we can think of.

**Comment by dimwight** [comment]
Thanks  for these kind words, but I seem to have misunderstood the spec. If we are happy to lock _all_ instances tagged `STATUS_SUBMISSION_FAILED` then certainly things look much simpler.

Incidentally I've been trying to guess how Collect experiences this issue, might it be a timeout while waiting for the `HttpPostResult` that never comes?

**Comment by lognaturel** [comment]
> If we are happy to lock all instances tagged STATUS_SUBMISSION_FAILED then certainly things look much simpler.

Yes, I believe that is sufficient! Using `STATUS_SUBMISSION_FAILED` instead of defining what you described as `STATUS_SUBMISSION_INITIATED` means we'll block edits in cases that we know for sure the server saw nothing about (404s, 500s, etc) but I don't think that's an issue. Reaching that submission failed state means the user either has autosend on or explicitly sent the submission. Either way, I don't think they would expect to be able to make edits, and any edits they do make are accidental. As you concluded, it's very odd that submissions in the "finalized" state can still be edited at all. It's definitely not what we would do if we were redesigning this functionality but we know for sure that users' workflows depend on that behavior. However, I don't think there are similar expectations after a submission attempt on an instance.

As I said earlier, I think the functional change will require updating two conditionals and that's it.

> I've been trying to guess how Collect experiences this issue, might it be a timeout while waiting for the HttpPostResult that never comes?

That's my best guess. Now that I think more about it, I think cancelling a submission after part of it has already been submitted to the server is another way to reach this state. After a cancel, I believe Collect will ignore the response. So this fix would probably address https://github.com/getodk/collect/issues/4539 as well which would be great news.

Note that we don't need to test getting into the bad state. If you want to simulate it for your own purposes you could try setting a breakpoint after Collect has sent all its bits but before the server response is received. Then you can either turnoff your device/emulator's Internet connection or tap 'cancel' on the UI, then resume code execution. I think those should both get you to the `STATUS_SUBMISSION_FAILED` state.

**Comment by dimwight** [comment]
I now have a demo of what looks like a possible resolution, if I put it in as a PR can you let me have your comments?

**Comment by lognaturel** [comment]
Absolutely! You can open a draft and later mark as ready.

**Comment by lognaturel** [comment]
Closed by #4655
