### ISSUE TITLE
Polish project color dialog

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4606]
- [x] Add icon text in preview icon. Ideally this would be the real icon text if it's set with a fallback to `A` but always showing `A` is fine too.

- [x] Make sure hex code text box doesn't wrap with a narrow screen (screenshot from Moto G5)
<img width="438" alt="wrapping hex box" src="https://user-images.githubusercontent.com/967540/121961950-edf58100-cd1c-11eb-8f90-1df617cb91cb.png">

- [x] Rethink hex label. Right now it looks really random. The intent was for it to provide context for the text box so users know what to look for. Maybe "hex color code" would better achieve that. At the very least, it should be more clearly visually linked with the text box. Maybe it's not necessary.

- [x] Add validation to the hex code text box. Currently the number of characters is capped to 6. if characters outside of the hex range are included, the color just stays as it was last set with no other feedback. As soon as 6 valid hex characters are included, the color of the preview changes. One idea is to show "invalid hex code" and prevent tapping 'ok' until 6 valid digits are provided. This likely could be a separate issue handled later.

**Comment by kkrawczyk123** [comment]
I think that it should be also prevented from clearing the filed content as right now I am able to accept empty value what causes a crash - there is no way to open admin settings after that - Collect crashes each time.

**Comment by lognaturel** [comment]
I happened to change the color of one of my calendars today and saw this:
<img width="282" alt="Screen Shot 2021-06-16 at 2 57 23 PM" src="https://user-images.githubusercontent.com/967540/122299737-3b0b5b80-ceb3-11eb-881a-ba9d3158500d.png">

I like the `Hex` there and I think the preview is clear. So some font size/color tweaks along with some changes to spacing might be enough. Perhaps making the preview bigger than the palette circles would help. I also like putting `A` in there and we'd talked about it before.

**Comment by lognaturel** [comment]
I did some YOLO merging of #4617 to get most of these good improvements into the beta (and especially the crash prevention). I've also updated the remaining items based on conversation in that PR.
