### ISSUE TITLE
Move link to ODK website to About menu

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#462]
The first item In General Settings is `ODK Collect`. This should be moved to the first item in the `About` menu. 

The text should be `Open Data Kit website` and the link should point to `https://opendatakit.org`. There should be no summary text.

**Comment by NamanArora** [comment]
Hello, I would like to work upon this issue and fix it at the earliest. Can I proceed with it?

**Comment by yanokwa** [comment]
It's yours, @NamanArora!

**Comment by yanokwa** [comment]
Congrats on your first PR, @NamanArora. 🎉🕺🏾🎉
