### ISSUE TITLE
Always fall back to the "Demo Project" name when the domain is demo.getodk.org and no project name is set

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4626]
Tapping on "Try a demo" provisions a project with name "Demo project" and corresponding icon and color. There should be the same behavior in the following cases:
- [x] manually configuring "https://demo.getodk.org" as the URL
- [x] upgrading from a prior version with the server configured as "https://demo.getodk.org"
- [x] scanning a QR code with "https://demo.getodk.org" as the URL and without a project name
- [x] scanning a QR code no (or empty) URL and without a project name

I'm hoping there's a single place where the fallback project name is defined that this special case can be added to.

**Comment by seadowg** [comment]
@lognaturel on the last case:

> scanning a QR code with "https://demo.getodk.org" as the URL and without a project name

If we scan an old QR that's configured with the demo URL, then we won't actually get a URL in the JSON (as the default value is being used). Given that, do we want to end up with "Demo project" when we scan a QR code with **no** URL in the config  instead? Or, do we just want that case to happen for QR codes generated elsewhere?

**Comment by lognaturel** [comment]
Good point. I don’t exactly remember these code paths but ideally the name can be set after the URL is set however it ends up being set. So yes, in all cases where the URL ends up being the demo URL, the project name (and thus the icon char and color) should be the same unless they are explicitly overwritten.

**Comment by seadowg** [comment]
@lognaturel that makes sense. I'll that case to the issue description.
