### ISSUE TITLE
Possible ReferenceManager conflict when form filling and/or background form update(s) happen concurrently

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4634]
@seadowg pointed out when fixing background form updates for multiple projects that the singleton `ReferenceManager` is a problem if two different projects begin form update jobs at the same time (https://github.com/getodk/collect/pull/4593#issuecomment-856260937) and/or form filling and a form update job start at the same time. I believe this is an existing issue that was introduced by https://github.com/getodk/collect/pull/3523 which added `ReferenceManager` configuration to the initial form discovery pass. Even within one project, it would be possible to launch form filling and have another form automatically start updating at the same time. In that case, one would have the final say on the `ReferenceManager` configuration and the other would fail.

The introduction of projects makes this a little more obvious and likely because it's now possible for multiple automatic form update jobs to start at the same time.

Some options to explore:
- Avoid the need to configure the `ReferenceManager` in form discovery by addressing https://github.com/getodk/javarosa/issues/444
- Have the `ReferenceManager` manage several forms' paths
- Offer a JavaRosa code path that bypasses the `ReferenceManager` for building a `FormDef` by passing in secondary instance paths (this sounds really annoying now that I write it out)

Thoughts on desired behavior:
- Ideally the user does get feedback at time of form download if a secondary instance is missing (though other media attachments can be missing with no feedback until form filling so maybe not?) Related: https://github.com/getodk/collect/issues/4489

**Comment by seadowg** [comment]
Yeah, this all makes sense to me! I think the risk of this is going to become greater and greater as people set up multiple projects on their devices. I'm leaning towards us going with "Avoid the need to configure the ReferenceManager in form" but that's based on my assumption that it would require the least rework.
