### ISSUE TITLE
Latest Collect can't start in clean AS emulator?

### ISSUE THREAD

**Issue by dimwight** [getodk/collect#4636]
Looks like it can't finish start-up unless its folder structure is already present. 

1. Check out a branch and make sure it's up to date - eg to _Merge pull request #4624_.  
2. Cold-boot the emulator, close and restart to refresh Device File Emulator.  
3. Open DFE, delete _sdcard/Android/data/org.odk.collect.android_. 
4. Make Project, run Collect. 
5. 'Launch succeeded' but nothing happens and process dies - repetitions result in some combination of a black screen and 'ODK Collect keeps stopping'. 
5. Synchronise DFE - deepest path is _/sdcard/Android/data/org.odk.collect.android/files/projects_. 
6. Start any emulator-based test eg `:collect_app:connectedDebugAndroidTest`. 
1. Check in DFE that all expected folders have appeared. 
8. Collect will now run!

**Comment by seadowg** [comment]
@dimwight I'm not able to reproduce this. Which emulator are you using (i.e. which API level) and what do you mean by "Make Project"? I tried using the demo project and creating one manually and both worked fine.

**Comment by dimwight** [comment]
Thanks @seadowg for looking into this, it made me retest my little procedure after _wiping_ the emulator instead of just cold-booting. That done, the problem disappears.

To answer your specific points,

>Which emulator are you using (i.e. which API level) 

A Pixel_3a_API_30_x86 targeting 11.0, from a recent install of AS 4.2.1 64-bit.

Maybe this pickiness/fragility is another Windows vs *nix  issue.

>what do you mean by "Make Project"? 

Just the Build>Make Project Ctrl+F9 menu item in AS.
