### ISSUE TITLE
Able to multiclick on Add button on manually enter project details view

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4641]
#### Software and hardware versions 
Collect v2021.2, Android v all device used...

#### Problem description
I have noticed that I can click on Add button on manually enter project details view multiple times and add the same project multiple times. 
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/33342488/123270920-9d420d00-d500-11eb-8b2f-856946929ec6.gif)
(I am not sure why this video has such bad quality - I used the same app as always)

#### Steps to reproduce the problem
1. Click on Add project
2. Click on Manually enter project details
3. Input URL
4. Tap multiple times on Add button

#### Expected behavior
User should not be able to Add multiple project by multi-clicking on Add button

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
I added it to the list of issues https://github.com/getodk/collect/issues/4439
