### ISSUE TITLE
Immediately switch to newly-added project

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4644]
Currently, when a new project is added, a toast is shown but the current project is not changed. We initially had designed project addition this way thinking of the case where multiple projects are provisioned at once.

As I've used projects and talked to users about how they plan to use them, I think it will be more common to add a project and then immediately want to do something with that project. I think we should immediately switch to a newly-created project and show the `switched_project` toast text.

Marking as `needs discussion` for now so @grzesiek2010, @seadowg can chime in based on their observation. @yanokwa is on board.

**Comment by grzesiek2010** [comment]
I don't feel strongly against or in favor so if you talked to users and they prefer switching immediately let's do that.

**Comment by seadowg** [comment]
@lognaturel yeah pretty indifferent as well. Feel like it'll be hard to get this "right" as I'm sure there will always be cases where switching immediately makes sense and cases where it doesn't.
