### ISSUE TITLE
Long server URL is cut off on Projects dialog.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4667]
#### Software and hardware versions 
Collect v2021.2 Android all, device used...

#### Problem description
When create project with very long URL that doesn't fit in one line on Project dialog, the whole URL is not visible and it is cut off. I agree that it's not a very common case but it still might happen and we should consider if long URLs should be wrapped and displayed with ..... in one line or if it should be divided into two lines and displayed as a whole.

see screenshot, appspot.com is not visible correctly:
![1625217337240](https://user-images.githubusercontent.com/33342488/124255009-fd046d80-db29-11eb-9d8d-f5910ce46a73.jpg)

Issue is also visible when project is selected and when scroll is not visible:
![Screenshot_2021-07-02-11-36-44-052_org odk collect android](https://user-images.githubusercontent.com/33342488/124255112-19a0a580-db2a-11eb-9f35-0f3ad41c1a44.jpg)

#### Steps to reproduce the problem
Just create project with extremely long URL.

#### Expected behavior
URL should be visible or wrapped. @lognaturel @grzesiek2010 what do you think?

**Comment by grzesiek2010** [comment]
As I said in https://github.com/getodk/collect/pull/4672 I think one line for project name and 2 lines for url would be a good solution for this problem. Let me know if you don't agree.

**Comment by lognaturel** [comment]
Looks good to me. 👍
