### ISSUE TITLE
Move admin settings into protected section of project settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4682]
The list below is a complement to the [Figma mockup](https://www.figma.com/file/qOwdGX7QgNOAzQ10TVxH6h/ODK-Collect-settings?node-id=7%3A2050) to make it easier to keep track of all needed changes. 

- [x] Rename "General Settings" to "Settings" in project selection dialog ([Figma](https://www.figma.com/file/qOwdGX7QgNOAzQ10TVxH6h/ODK-Collect-settings?node-id=7%3A2050))

- [x] Change "General Settings" app bar title to "Project settings"

- [x] Add "Project display" category to "Project settings" between "Server" and "User interface"

- [ ] Move "Project name", "Project icon", "Project color" to new "Project display" category; drop "Project" from the labels and keep all behavior the same

- [x] Add "Protected" section  to "Project settings"

- [x] Move existing "Admin Password" option from Admin Settings to "Set admin password" in "Protected" section of "Project settings"; keep dialog and behavior the same.

- [x] Add "Project management" category to the "Protected" section of "Project settings" below "Set admin password".

- [x] Move existing "Reset project", "Configure via QR code", "Delete project" to new "Project management" category

- [x] Add "Access control" category to the "Protected" section of "Project settings" below "Project management".

- [x] Move existing "Main menu", "Settings" and "Form entry" categories; keep behavior the same

- [x] Remove "Admin Settings" from project selection dialog ([Figma](https://www.figma.com/file/qOwdGX7QgNOAzQ10TVxH6h/ODK-Collect-settings?node-id=7%3A2050))

**Comment by grzesiek2010** [comment]
@lognaturel @seadowg 
what do you think about keeping settings separately after this change (we used separate sharedprefs for general and admin settings)? Should we still have separate prefs for those protected settings or maybe we should merge them (migrate admin prefs to general prefs)?

**Comment by seadowg** [comment]
@seadowg long term I think it would be nicer to just have one bucket of settings, but I wouldn't be opposed to keeping them separate for the moment and then revising in the next release. There is a `KeyMover` migration that we've used to move settings from general/admin to meta, so I guess it might be pretty simple.... Whatever is easiest I reckon!

**Comment by lognaturel** [comment]
> I guess it might be pretty simple

Maybe. 😬 Making this change would mean changing the way settings json is read and written, right? Seems risky to me so even if it's where we're going, I'd rather it be done in another release. That is, unless keeping the two buckets adds a ton of complexity.

**Comment by grzesiek2010** [comment]
Ok I also think it would require too much work. I'll file a separate issue for that.
