### ISSUE TITLE
Change default form update frequency

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4690]
This should change from 15 mins to 1 hour based on analytics that people often increase it. Should change for Match Exactly and Previously Downloaded Only.

**Comment by lognaturel** [comment]
[These](https://console.firebase.google.com/u/0/project/api-project-322300403941/analytics/app/android:org.odk.collect.android/events/~2Freport~2FPreferenceChange%3Ft%3D1626207014101&fpn%3D322300403941&swu%3D1&sgu%3D1&sus%3Dupgraded&params%3D_u..pageSize%253D25%2526_r..eventId%253DPreferenceChange&cs%3Dapp.m.events.detail&r%3Ddefault&g%3D1) are the analytics I'm looking at. Any others?

My interpretation is that 15 mins is a reasonable default. This only tells us about users manually setting the frequency and not about users scanning in a configured QR code, right? And it looks to me like 15mins is the most popular manual choice followed by 24 hours. The concern with 15mins is that it could overwhelm servers in certain cases with many data collectors. We haven't heard of any instances of this but the default has been 15mins for some time now.

**Comment by seadowg** [comment]
@lognaturel huh. I think I misinterpreted from our conversation that 24 hours was the most popular, but I see you meant "other that than the default". Yeah let's not do this!

**Comment by lognaturel** [comment]
Sorry, I think I mostly was mumbling to myself. We didn’t really consider the 15min default as much as I would have liked in the first place but now that it’s in effect I think changing it would be disruptive. Maybe it’s good that we just went with it without overthinking — if it’s not causing problems then it is more likely to get users the updates that they need. 

I find it interesting that the second most popular choice is every 24hrs but I don’t really know what that means. Maybe those folks know for sure that their forms rarely change? Or know that their data collectors don’t often have connectivity. 

The thing that I have seen as problematic with the frequent updates is that there are “Failure” notifications too often. Your concept of some kind of back off and retry would be great for that. When you see it, could you please look at your Central log to see if there are any hints, too? It’s really weird.

**Comment by seadowg** [comment]
> I find it interesting that the second most popular choice is every 24hrs but I don’t really know what that means. Maybe those folks know for sure that their forms rarely change? Or know that their data collectors don’t often have connectivity.

Yeah I don't know really. It's hard to find the right values for these things. This is especially true given the "push" nature of a lot of these kinds of updates that people are typically used to.

> Your concept of some kind of back off and retry would be great for that. When you see it, could you please look at your Central log to see if there are any hints, too? It’s really weird.

I think I did this before and couldn't see any failures, which led me to believe that it's the phone losing signal. I keep meaning to check logs again, but it often happens when I'm out and about (which also suggests that it's the phone). I think a change to the app early next release with more details of failures would be helpful for sorting all this.
