### ISSUE TITLE
Investigate the best way to manage dependency versions across modules

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4691]
Right now we have a bunch of dependencies shared among modules and have been using version constants to keep them in sync where we can. Is there a better way to do this? 

If not, we should sweep the modules we have so far and try and pull out as many constants as we can.

**Comment by grzesiek2010** [comment]
I think this article is a good summary of the options we have: https://proandroiddev.com/how-to-manage-dependencies-in-multi-module-project-84620afbb415
We use the first one now and to me the last option is what we should implement.

Mitch Tabian has a good sample of it here: https://github.com/mitchtabian/Clean-Notes/tree/master/buildSrc
I like the way he keeps different kinds of dependencies in separate files https://github.com/mitchtabian/Clean-Notes/tree/master/buildSrc/src/main/java/dependencies (but it's not a must we can implement it later).

@seadowg any thoughts?

**Comment by seadowg** [comment]
Oh, I'm a big fan of the `buildSrc` route (which I think is the one you mean)! Eventually we could have different files for different kinds of dependencies, but initially being able to type `Dependencies.mockito` and just get what you want would be so nice!

**Comment by grzesiek2010** [comment]
> which I think is the one you mean

yes!

Ok so I'll go ahead and implement that way. I was about to update dependencies like after every release so maybe I'll do that in one pr if you don't have anything against.
