### ISSUE TITLE
Infinite load visible when open Get Blank Form for newly added Google account 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4701]
#### Software and hardware versions 
Collect v2021.2 Android all device used...

#### Problem description
When testing create/import project settings with Google Drive type I have noticed that I am unable to display Get Blank Form for a newly added Google account that was not previously used on that device:
![Screenshot_20210716-111957_Google Play services](https://user-images.githubusercontent.com/33342488/125928140-e21b67a5-32eb-458e-afcd-a15eb957180f.jpg)

I have compared behavior with v1.30.1 where when open Get Blank Form I can see dialog:
![Screenshot_2021-07-16-11-20-33-496_com google android gms](https://user-images.githubusercontent.com/33342488/125928232-6689b5d3-64ea-4c99-ade6-986c4f6d658d.jpg)

#### Steps to reproduce the problem
1. Create new project with Google Drive type (I was able to reproduce manually and via import)
2. Add a Google account that was not used previously on your device
3. Go to Get Blank Form

#### Expected behavior
Access dialog should be visible, user should be able to accept and display Get Blank Form view.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
This doesn't seem to me like regression. I was able to reproduce the issue installing the current master but also previous releases v1.30.1 and v1.29.5 and at the same time It somehow worked well for me on the same versions so I would say it's random.
I debugged the project and I didn't notice any valuable logs, there is only

> [GoogleAccountDataServiceImpl] getToken() -> NEED_REMOTE_CONSENT. App: org.odk.collect.android, Service: oauth2: https://www.googleapis.com/auth/drive

but I get it every time no matter if everything works well or not.

I also found this topics: 
https://support.google.com/accounts/thread/4692671/stuck-loading-when-signing-into-apps-with-jy-google-account?hl=en
https://support.google.com/android/thread/13378455/google-account-stuck-at-loading-screen?hl=en
https://support.google.com/accounts/thread/18483696/infinite-loading-screen-when-signing-in?hl=en
https://stackoverflow.com/questions/65974714/google-oauth-sign-in-stuck-loading-consent-screen
https://stackoverflow.com/questions/65853630/android-app-with-google-drive-api-stucks-after-choosing-an-account-why/65900011#65900011

here is the issue https://issuetracker.google.com/issues/178183308 there someone claims that this would be a solution:

>Guys, I have found solution for this problem on StackOverflow.
On Google Cloud Plateform
OAuth Consent Screen set "Publishing Status" = In production
After that blank screen problem will be solved.

but I guess we have that status... right @lognaturel?

@kkrawczyk123 did you build the app on your own? Maybe that's the problem. My impression is that if I build it on my own I'm able to reproduce the issue (pretty much every time) but if I use the Play Store it works well more often (not in all cases but still)

**Comment by grzesiek2010** [comment]
@kkrawczyk123 is busy with testing but she said that the version which worked well was from the store and the one which contained the bug she build on her own... that would correspond with what I noticed

**Comment by grzesiek2010** [comment]
Ahh this might be related to https://github.com/getodk/collect/issues/4608

**Comment by lognaturel** [comment]
> if I use the Play Store it works well more often (not in all cases but still)

That's really weird! Publishing status is `in production`. 

It's definitely in the same general space as #4608. But I wouldn't expect any change until September. You get the same infinite spin? And then what, you kill the app and reopen?

**Comment by grzesiek2010** [comment]
> You get the same infinite spin?

as I said I get it pretty much in all attempts if I build the app on my own. If I use Play Store it works well more often but not always (maybe because of the fact that some data is left after doing that on the same device?). Kasia also confirmed that she caught the bug building the app on her own and the after installing the version from the store everything was fine.

So maybe if none of our users complained we should just wait assuming that release versions are fine.

> And then what, you kill the app and reopen?

no then I uninstall it and install a version from the store

**Comment by lognaturel** [comment]
I've tried with the latest signed build from master and can't reproduce. @grzesiek2010 did reproduce on signed builds but only after having experienced it on unsigned builds so it's not conclusively an issue. I agree with waiting to see if we have complaints. Of course, if this comes up on a signed build during regression testing, we should reopen.
