### ISSUE TITLE
Missing location permission dialog is visible even when permission has been allowed

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4706]
#### Software and hardware versions 
Collect master

#### Problem description
Missing location permission dialog is visible even when permission has been allowed

#### Steps to reproduce the problem
1. User installs Collect
2. User downloads form with Geo widget (I noticed this when I checked Geotrace widget)
3. User clicks on `Start GeoTrace` button
4. User is asked about location permission
5. User clicks ALLOW
6. User sees the same dialog when Deny is clicked

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/126306720-74029c8b-ae94-4bab-8ef1-478652aee4f3.png">

7. User closes this dialog
8. User is able to open map 

#### Expected behavior
Map appears when permissions are allowed

#### Notes
To reproduce it easily, you can unselect location permission and continue from point 3

**Comment by grzesiek2010** [comment]
This is a strange issue... I was able to reproduce it on API 27 but not on API 29 and 30
It's regression for sure and I found the commit that causes the problem: 
https://github.com/getodk/collect/pull/4677/commits/0c7497140716a80df564d9e8b5c9de70715c99c3#diff-c65e1dc7ab55ac6215bbf54427b381edbfa839b083c49ad4e26defd8cabeeeb1R5

@seadowg the change you added in that commit `android:maxSdkVersion="22"` according to the docs means `The highest API level at which this permission should be granted to your app.`

Does that mean we no longer need that permission for API 22+?

the problem is that if we request location permission we request both `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION` and the result on some APIs (because of the change mentioned above) is that if a user grants location permission only `ACCESS_FINE_LOCATION` is granted but not `ACCESS_COARSE_LOCATION` what treats the whole action as denied.

**Comment by seadowg** [comment]
> Does that mean we no longer need that permission for API 22+?

Yeah that was auto generated for me, but I thought made sense as you'd get (runtime) permission requests after that right? I'm realizing reading the docs it feels like it still needs to be declared (https://developer.android.com/training/permissions/declaring). I'm guessing the fix will be to just add fine and coarse declarations there and not have any `maxSdkVersion`?

**Comment by grzesiek2010** [comment]
I mean just removing `maxSdkVersion` does the job but then it doesn't make sense to keep that permission there at all since it's declared in `collect_app/AndroidManifest.xml` so there is no need to override it in `location` module right?

**Comment by seadowg** [comment]
I think we need it in `location` to avoid build/IDE warnings that we don't have it. We could just suppress them in the module I guess and just expect consumers (`collect_app`) to have the permission declared I guess.

**Comment by grzesiek2010** [comment]
Ok you had to create a `Manifest.xml` file for that `location` module to register `LocationTrackerService`. If it's created it has to specify its own permissions (permissions from the main module are not used) right?
That means we should just copy:
```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
there.

As I understand you got an error: 
`Missing permissions required by LocationManager.removeUpdates: android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION`

and fixed it via Android Studio which added:
```
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        android:maxSdkVersion="22" />
```
to `location/AndroidManifest.xml`

you had two options in Android studio (to fix that warrning):
- adding `ACCESS_COARSE_LOCATION`
- adding `ACCESS_FINE_LOCATION`

and you clicked the first one.
But that means the `location` module works just with `ACCESS_COARSE_LOCATION` and additionaly that auto-generated `android:maxSdkVersion="22"` caused our issue. Am I right?

**Comment by seadowg** [comment]
Yeah exactly. I'm wondering if a nice way to handle this is to just use the `@RequiresPermission` annotation on our methods in `location` that need permissions. That way, we can avoid doubling up on the permission declaration, but we'll also get a warning in the consumer (`collect_app`) if we don't have permissions there (which we wouldn't get if we use `@SuppressWarnings`).

**Comment by grzesiek2010** [comment]
As i understand we don't need to request those permissions using our `PermissionsProvider` in `location` module right. It happens in the main module and then if it's granted the job is delegated to that new location module?

**Comment by seadowg** [comment]
Yeah, we let Collect handle the actual permission request, so I think that even more reinforces just using `@RequiresPermission`.

**Comment by lognaturel** [comment]
I missed some of this conversation and now see there was a discrepancy between what @seadowg suggested and what happened. Suppressing the lints makes a lot of sense to me. Also adding `RequiresPermission` would be a nice improvement though I think just doing that would still result in a lint failure? Anyway, maybe a quick thing to revisit if you felt strongly about it, @seadowg.
