### ISSUE TITLE
When hide some user settings, headers are still visible 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4714]
#### Software and hardware versions 
Collect v2021x, Android vx.x.x, device used...

#### Problem description
When testing regression I have noticed that when hide form management settings or collect anonymous usage data headers connected to that options are still visible when open Form management and User and device identity.
ex. I hid all form management settings except show guidance for questions:
| Collect v2021 | Collect 1.30.1 |
| ----- | ------|
|![Screenshot_2021-07-21-13-37-32-359_org odk collect android](https://user-images.githubusercontent.com/33342488/126484789-f5ede82b-1fbb-44c9-b0d5-11595aaebc59.jpg) | ![Screenshot (Jul 21, 2021 1_41_43 PM)](https://user-images.githubusercontent.com/33342488/126484823-2f1ec5c4-febb-4713-b7a7-43882217b1dc.png) |
| ![Screenshot_2021-07-21-13-52-31-709_org odk collect android](https://user-images.githubusercontent.com/33342488/126484895-d81e4da7-08b1-438f-a9e3-8f569351c8d1.jpg) | ![Screenshot (Jul 21, 2021 1_53_19 PM)](https://user-images.githubusercontent.com/33342488/126484917-d125c113-0d50-42f2-9924-afd880255c43.png) |

#### Steps to reproduce the problem
1. Hide in User Settings form management settings and collect anonymous usage data 
2. Open Form Management and User and device identity

#### Expected behavior
Unnecessary headers should be hidden. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
This is definitely nice to have a fix for but doesn't feel essential to me/could go in a point release!
