### ISSUE TITLE
Improve geopoint dialog

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4718]
The geopoint dialog currently does not make it easy for users to decide when to accept the point.

- [x] Consolidate suggestions from [forum post](https://forum.getodk.org/t/collect-improve-geopoint-dialog-so-it-better-highlights-acceptable-accuracy/34246) + [#3324](https://github.com/getodk/collect/issues/3324) and share a mockup

**Comment by seadowg** [comment]
As part of this, it'd also be good to move away from using `ProgressDialog` in the geopoint dialog implementation (deprecated in #4803).

**Comment by seadowg** [comment]
Keeping notes on research/design [here](https://github.com/seadowg/collect-design/blob/master/research/geopoint.md).

**Comment by seadowg** [comment]
Ok some design sketches I've been working on. The most basic is using the current text based style but rejigging what we show:

<img width="306" alt="Screenshot 2021-11-03 at 14 32 45" src="https://user-images.githubusercontent.com/556280/140080299-26dcd51f-3f77-4f08-a0f8-947fb26f923b.png">

The most significant change here is that we don't show satellites or provider unless there is a problem with them - we'd show a warning about satellites if there are less than 4 and a warning about providers if it's not "fused". These warnings could include instructions on how to improve the situation. For me this feels like an improvement on its own and I think we could maybe make it a first step/PR regardless of where we go.

The next concept is using progress bars:

<img width="297" alt="Screenshot 2021-11-03 at 14 34 44" src="https://user-images.githubusercontent.com/556280/140080655-f7f9d6a5-5433-4db4-9e29-e3de92185b3b.png">

<img width="359" alt="Screenshot 2021-11-03 at 14 35 05" src="https://user-images.githubusercontent.com/556280/140080724-827448ad-960f-4691-9d1c-7b95db490e2b.png">

The idea is here is to have a progress bar that will fill when the target accuracy is reached (and will be proportionally fill from the min of the lowest in the session and some chosen arbitrary accuracy).

I've also been playing with a more "animated" version based on how maps present this suggested by @yanokwa:

<img width="300" alt="Screenshot 2021-11-03 at 14 38 04" src="https://user-images.githubusercontent.com/556280/140081275-ac2daa93-d36d-4819-bcb6-a0e241a20f94.png">

Here the outer circle gets smaller until it target accuracy is achieved. Then the circles line up and we get a nice big tick:

<img width="299" alt="Screenshot 2021-11-03 at 14 38 50" src="https://user-images.githubusercontent.com/556280/140081423-0a828412-18bc-41de-9abe-6fd62119a87b.png">.

All of these are differencing amounts of work and I have preferences but wanted to get a conversation going now around initial thoughts now. cc/ @lognaturel @yanokwa @grzesiek2010 @mmarciniak90 @kkrawczyk123.

As a quick note: not all the designs include "Time elapsed" but I think we could easily add it to any of them.

**Comment by yanokwa** [comment]
Now that I've seen these together, I'm a huge fan of my version! It matches what other mapping applications do and I think it's nice to leverage that interaction, rather than focus on the notion of target accuracy (which we don't really use elsewhere, right).

I'd prefer that the two circles stay even after target accuracy has changed and that we update the text at the bottom. My reasoning is that 
1. I bet no one uses target accuracy in their forms (we'll see what the data says)
2. You could get better than targer accuracy by waiting

I agree that we don't need to know the provider or number of satellites unless there is a problem. I also agree that we should say what they should do to resolve the problem rather than report the number of satellites. 

My gut is that showing the elapsed time is probably helpful, but I'd be OK dropping it until someone complains.

**Comment by seadowg** [comment]
> I'd prefer that the two circles stay even after target accuracy has changed

@yanokwa could you do me a quick paper sketch of what you have in your head for the end state (when the target has been reached)?

**Comment by seadowg** [comment]
OK, did another pass on the "animated" version:

<img width="328" alt="Screenshot 2021-11-09 at 11 08 44" src="https://user-images.githubusercontent.com/556280/140913566-afeb50c9-45fb-4430-8cb1-91605cde3bb6.png">

I think this will work nicely. We'll need to build an animation for it to look good: the outer circle should grow and become more transparent (until disappearing) on repeat. How far the outer circle grows before disappearing should be relative to the current accuracy (larger accuracy has a larger outer circle).

@yanokwa @grzesiek2010 thoughts?

**Comment by grzesiek2010** [comment]
I don't know if we need to display both:
- current accuracy (12m in you sample)
- the warring message

Maybe it would be better to display that warring only (if needed) something like: `Accuracy low (12m). If you are indoor, please go outside`? Then the inner circle could be smaller.

**Comment by seadowg** [comment]
> I don't know if we need to display both

You mean only show accuracy if it's below the threshold?

**Comment by grzesiek2010** [comment]
> You mean only show accuracy if it's below the threshold?

yes but that means always at the same time because once we achieve required accuracy the dialog is closed automatically right?

**Comment by seadowg** [comment]
> yes but that means always at the same time because once we achieve required accuracy the dialog is closed automatically right?

Ah yeah true. I guess we're only showing the current accuracy to allow the user to compromise for an accuracy that's almost good enough. Another option I haven't explored is making the user confirm (via another dialog) if they hit "Save" for an accuracy that doesn't meet the threshold.

As much as I like the aesthetic of @yanokwa's pulse idea I'm leaning more and more towards a progress bar as I really think we're trying to make it a clear as possible that they should be waiting for the correct accuracy, and I'm not sure if we get that from the pulse.

**Comment by grzesiek2010** [comment]
As i said during the meeting I still like more Yaw's proposal.
I think it would be strange to represent things like accuracy that might be better in one second the worse and again better using progress bar. Maybe I'm wrong but to me a progress is something that happens step by step usually without steps back.

**Comment by seadowg** [comment]
For the moment, we're going to wait on analytics data around how popular `accuracyThreshold` is. This will hopefully make it easier for us to choose a direction.

**Comment by seadowg** [comment]
Ok looking at analytics, it looks like our way of measuring this is a little flawed. For some reason, our custom dimension on the events (`form`) only seems to display a max of 200 items - you'll see both `AccuracyThreshold` and `AccuracyThresholdDefault` show as having 200 different values for the custom dimension. I'm guessing this is a max Firebase is enforcing somewhere. I'll dig more into that.

Despite that problem, we can still measure how often the events occurred (widgets were shown). It's pretty clear that using the default is the preferred option as we displayed geopoint widgets without a specified threshold 430k times and only showed them with a specified threshold 56k times. Given that, I think we can probably go with a subtler UI with respect to the threshold (like the UI pulse/circle UI). I'm also thinking we could get rid of the auto-close behaviour when no threshold has been set. Closing at 5m by default seems strange if the enumerator would like to get a more accurate reading. Thoughts?

**Comment by grzesiek2010** [comment]
> Closing at 5m by default seems strange

I agree with this and I still like that option with animated circle.

**Comment by seadowg** [comment]
OK, I think the way to go here is to build a reworked progress dialog with new behaviour:

* Only closes automatically if threshold is set in form
* Shows warning if satellites are low (under 4) or if non "fused" provider in use
* Just shows current accuracy

This can be a single issue/PR. We'll have a second issue for creating the animated current accuracy display like we've described here. Sound good @yanokwa @grzesiek2010?

I think we should also look at making it easier to set an accuracy threshold (probably using a parameter), but for now I think making it so the user can wait for accuracies below 5m (when no threshold is set) and improving messaging around bad accuracy scenarios is a good step forward. It also feels like using a constraint to enforce the desired accuracy is probably better than using the threshold.

**Comment by grzesiek2010** [comment]
> I think we should also look at making it easier to set an accuracy threshold (probably using a parameter)

What do you mean by that? What parameter?

**Comment by lognaturel** [comment]
> Only closes automatically if threshold is set in form

I think you've made the assumption that if folks don't set a default explicitly, then they don't want any default capture. My guess is that most folks who don't set a default explicitly are happy enough with the 5m threshold and train their data collectors to just open the geopoint dialog and leave it open until a point is captured. The change you're proposing may be disruptive. Imagine a data collector who knows nothing about accuracy and has been using the widget by just waiting until capture. Now they'll wait a long time. At some point they'll figure something is probably up and capture the point. They won't have any new information about how to use the updated interaction in the future. They'll be more likely to immediately capture and get a high/bad accuracy. Maybe I'm underestimating how helpful/clear the animation will be but I'm not sure that it will help someone who doesn't have any concept of accuracy (map literacy is low and folks may never have seen or noticed the accuracy bubble animation on e.g. Google Maps).

> It also feels like using a constraint to enforce the desired accuracy is probably better than using the threshold.

But keep in mind that there are many data collectors who have been trained with existing forms which won't change.

> easier to set an accuracy threshold (probably using a parameter)

Yes, using the XLSForm `parameters` column would be nice.

**Comment by lognaturel** [comment]
How about posting to [the forum thread](https://forum.getodk.org/t/collect-improve-geopoint-dialog-so-it-better-highlights-acceptable-accuracy/34246)? I think it would be great to get some more field voices in the conversation. My guess is that the circle animation isn't sufficient. Maybe an addition like red text that says "N meters from target accuracy" or something like that could help.

**Comment by seadowg** [comment]
@lognaturel all great points. I've scheduled some time for us to dig deeper into all this and try and see if we can come up with a better design.

**Comment by seadowg** [comment]
We've (@lognaturel and I) have worked on a new design which I'll post to the forum with a quick write-up for feedback.

**Comment by seadowg** [comment]
Ok we're going to move ahead with the mock-up posted on the forum and play around with the feedback in implementation rather than iterating on the mockup:

<img width="328" alt="Screenshot 2021-11-09 at 11 08 44" src="https://user-images.githubusercontent.com/556280/146011476-8e161b89-548d-4898-90e5-8bd242fa0912.png">

The text under the accuracy ("2.25m from..." and "Please wait...") will be dynamic:

* If accuracy > 100m: Should read "Unacceptable accuracy" and "Please make sure you can see the sky if outside"
* If accuracy > 10m: Should read "Poor accuracy" and "Please wait for improved accuracy"
* If accuracy <= 10m: Should read "x from goal of y" and "Please wait for improved accuracy"

Things to experiment with:

* Button text changing to "Save with poor/unacceptable accuracy" vs a confirmation dialog
* Adding animations to current accuracy value to reinforce that something is happening/changing
* Text appearances throughout to make the dialog feel less cluttered
* Some "title" somewhere to explain that the big number is accuracy
* Dialog should block saving before location is found

The PR should present a preferred version that we can then discuss.
