### ISSUE TITLE
External cascading select shows invalid choices if displayed as field-list

### ISSUE THREAD

**Issue by cooperka** [getodk/collect#4719]
#### Software and hardware versions 

Collect v1.30.1, Android 9, Pixel 2 XL

#### Definitions

What I mean by cascading select: There are multiple levels of choices, each depending on the previous. For example, you might choose **Country > State > City**.

What I mean by external: There are a LOT of options, so we ship it as a separate CSV file using `<input query="instance(...) ... />` in the form XML (rather than including the options directly in the form definition). See this [itemsets-countries.csv](https://github.com/getodk/collect/files/6859911/itemsets-countries.csv) CSV file for an example.

#### Problem description

Normally, a cascading select should either:

1. Be paginated (choose the country on page 1, then click "next" to choose the state on page 2), e.g.

<div>
<img width="240" title="paginated page 1" src="https://user-images.githubusercontent.com/2047062/126589420-bf6f9fed-556b-44a6-9ae2-7d5407aa9444.png" />
</div>

Or,

2. With `appearance="field-list"` it should show only the top-level options (countries) before allowing the user to choose second-level options (states in that country you've selected), e.g.

<div>
<img width="240" title="field-list step 1" src="https://user-images.githubusercontent.com/2047062/126589483-fa347128-81d3-4af1-9ca8-fb8e4f4112a4.png" />
<img width="240" title="field-list step 2" src="https://user-images.githubusercontent.com/2047062/126589485-827d715d-6352-4d6b-aa71-72b43dcba421.png" />
</div>

The bug I'm seeing is that with an **external** cascading select with `appearance="field-list"`, it shows all 3 questions at once, and they're all duplicates of each other! You can also skip the first level and begin at any step (shown below), and that messes up the data when it comes back.

<div>
<img width="240" title="bug step 1" src="https://user-images.githubusercontent.com/2047062/126590996-41889256-b350-4e54-86f5-02992e3c5cfa.png" />
<img width="240" title="bug step 2" src="https://user-images.githubusercontent.com/2047062/126590997-a7972c0d-908c-44d8-944c-406acd6f9c62.png" />
</div>

#### Steps to reproduce the problem

1. Download the following 3 files: [2021-select-bug.zip](https://github.com/getodk/collect/files/6860040/2021-select-bug.zip)
1. Upload to your device:
    ```console
    adb push ~/Downloads/2021-select-works-internal.xml /sdcard/Android/data/org.odk.collect.android/files/forms/
    adb push ~/Downloads/2021-select-bug-external.xml /sdcard/Android/data/org.odk.collect.android/files/forms/
    adb push ~/Downloads/itemsets.csv /sdcard/Android/data/org.odk.collect.android/files/forms/2021-select-bug-external-media/
    ```
1. Try both forms, the external version shows the bug

#### Expected behavior

External selects should work the same as internal selects.

#### Other information 

A helpful next step here would probably be to start git bisecting and see where the bug was introduced. I may start doing this. I'd like to hear if a maintainer here has advice or input.

**Comment by lognaturel** [comment]
Did you try the standards compliant [external secondary instances](https://docs.getodk.org/form-datasets/)? Is there a strong reason to use “fast external itemsets” (eg you need translations or there are 50k+ items and older devices)? I’d be curious to know where you got the XML spec for it since it’s undocumented. 

Do report back on what the bisect finds. I would be surprised if this had ever been supported.

**Comment by cooperka** [comment]
Confirmed this behavior exists at least as far back as Collect v1.28.4 (Nov 2020), so I'm not gonna try to mess with it~~

Thanks for the documentation, I'm sure this external CSV feature in NEMO was written too many years ago to try to justify supporting it here, so we'll make changes on our end to resolve this. Cheers.
