### ISSUE TITLE
Missing margin in the list of projects that are not currently used when RTL language is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4732]
#### Software and hardware versions 
Collect v2021.2

#### Problem description
Missing margin in the list of projects that are not currently used when RTL language is set

#### Steps to reproduce the problem
1. User uses Collect with some RTL language
2. User opens projects list

![Screenshot_20210726-171026_ODK Collect](https://user-images.githubusercontent.com/3907554/127013507-2d142dbd-cbe4-495a-8e40-5cc97d902451.jpg)

#### Expected behavior
Margin should be added

**Comment by lognaturel** [comment]
I think there's a deeper layout issue here. It's not so much that there should be margin added at the left but that the start of the project name and project details should be constrained to the end of the project logo rather than the left side of the screen.
