### ISSUE TITLE
Catch all errors when recomputing values in a field-list and show a helpful dialog

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4750]
[This form](https://docs.google.com/spreadsheets/d/1nzMwwHbFuKU9LEiSwCWDi-2_7T_71KFSnihOFI_YZsY/edit#gid=0) has a select minimal with a value that gets used in a calculate for another select that was previously filtered to have no choices. It causes [this crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/15e3697cc76c108d13ec3a7303005186?versions=v2021.2.0%20(4242)&time=last-seven-days&sessionEventKey=61017F8E023900017486E6A412D3A914_1568454006980881959). Because the second select's choices have never been rendered, choices are not attached to the selection.

Somewhat related, [this crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/d31d1c268cdbe4b661aa40cced4ca763?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=6101100B015A000142AB98915C2DF016_1568442290527831492) can be reproduced by having a calculate on a select that produces a value not related to the choices. e.g. I put "foobar" in the `calculate` for a select that did not include "foobar" in its choices.

Also related to https://github.com/getodk/collect/issues/4170.

People think they can use calculates as dynamic defaults. That will not work and they should not do that. In a way, it's not so bad that it crashes so catastrophically because at least they're not getting bad values which they would if the calculate succeeded. This can be fixed by adding a `trigger`. For example, in the sample form at top, add `${select}` in the trigger column. That is how [dynamic defaults are supposed to be expressed](https://docs.getodk.org/form-logic/#dynamic-defaults-from-form-data).

Could we perhaps catch all of these and show a better error message suggesting there might be a misuse of calculates?

**Comment by grzesiek2010** [comment]
It would be great to catch the exception and throw `FormDesignException` but it's not easy to identify that this is it...  
Generally updating field-lit groups is a source of many possible issues so we could maybe just wrap everything in try-catch and display a dialog that something went wrong and it might be a form design issue.

**Comment by lognaturel** [comment]
> wrap everything in try-catch and display a dialog that something went wrong and it might be a form design issue.

That sounds good to me. I've also filed a pyxform issue at https://github.com/XLSForm/pyxform/issues/546 The Collect message could be something like `Failure trying to update values. This is generally because of incorrect usage of calculations in the form design.` + `\n\nR.id.report_to_project_lead`

Then the form should probably just close? It seems there's nothing of value that can be done with a form that has this kind of issue.

**Comment by lognaturel** [comment]
The two first cases with calculates and selects turn out to be the same as opening a record for edit. That is, there has to be an attempt to bind the selected answer(s) to the available choices or we can’t open a record for edit.
