### ISSUE TITLE
Crash trying to connect to db when current project doesn't exist

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4756]
#### Software and hardware versions 
Collect v2021.2

#### Problem description
If the project id saved in meta settings corresponds to a project that was deleted from the filesystem, Collect will crash on open. This is likely not a very common operation but given that we now see clear evidence that people are pushing both forms and instances through the filesystem, it wouldn't be surprising if they're also deleting projects that way.

I believe this explains a subset of [the database crashes we see in Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?versions=v2021.2.0%20(4242)&time=last-seven-days&sessionEventKey=61031FAD03BA00010D413B71613F3C76_1568911492518499770).

#### Steps to reproduce the problem
1. Create a project from Collect
2. `adb shell` and delete the project
3. launch Collect

#### Expected behavior
No crash.

**Comment by lognaturel** [comment]
I thought we could fix this by updating the current project based on the filesystem at app launch but I don't think that would be sufficient. It seems that what's actually crashing are the background tasks that keep running: [main menu instance count updater](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?versions=v2021.2.0%20(4242)&time=last-seven-days&sessionEventKey=61031FA300B400010BF23B71613F3C76_1568911450225484665), and I've seen it from match exactly as well though no Crashlytics report that I can see.

I briefly discussed this with @seadowg and he thought this wasn't important to address because users shouldn't expect that they can manipulate the filesystem and get good behavior. I agree it's not a super common use case but on the other hand Collect has had that behavior for over a decade so it's an abrupt change. @seadowg, I now believe that 100% of [this Crashlytics issue](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?versions=v2021.2.0%20(4242)&time=last-seven-days&sessionEventKey=61031FAD03BA00010D413B71613F3C76_1568911492518499770) are caused by this situation. That explains why it happens so many times for each user -- I see it over and over again locally as well.

Is there anything lightweight we can do to rescue users from this state?

**Comment by seadowg** [comment]
We could add specific checks to the main menu (probably in `onResume`) and background tasks (autosend, match exactly and auto update) that check whether the current project (or the specified project in the background task case) still exists on disk. For background tasks we just fail early and for the main menu we can fallback to an existing project or just to the launch screen.

Another option would be to "sync" the projects with what's on disk (delete projects no longer on disk and fallback current project) when the app launches and then let these crashes occur. Then when the user relaunches the app after a crash the problem will resolve itself. That's potentially simpler?

**Comment by lognaturel** [comment]
> Another option would be to "sync" the projects with what's on disk (delete projects no longer on disk and fallback current project) when the app launches

~This is what I initially had in mind but I got the sense that it would be too late -- that some of the tasks running in the background would already have "captured" the projectid. But maybe I'm wrong about that! In any case, it's the biggest crash we have with no sign of slowing down so I do think we should address it sooner than later. If it is the case that doing some fallback on app launch would work, that seems like an easy win. I don't even think it has to be a full sync -- just a check to see whether the current project id exists, and if not, set it to a project that does exist (whichever) and if no project exists, handle that such that the first launch screen is displayed.~ I'm losing my mind, sorry. I did a really quick debugging session on Friday that I now see led me astray because I didn't put the breakpoint where I intended and I convinced myself the crash happened before initialization which I no longer think it does. And then I tried a quick fix where the current project was updated based on the projects repository but of course the projects repository is also in a stale state in this case. So yes, I think you're right it has to be a full sync which is not a big deal. I'm going to leave this in your much more capable hands... 😅😭

**Comment by seadowg** [comment]
I think our solution here (as you've said before) is to remove any projects that don't exist any longer on disk from the projects repository, and then fall back to one that does exist if the current has been removed. We'd also have to just clear the current project if all the projects are gone. I don't want to accidentally add support for copying projects on to disk (and have Collect add them) here, so will avoid an actual "sync" with the disk.

**Comment by seadowg** [comment]
New plan (as @lognaturel discussed on Slack) is just to create project directories on the fly if the current project doesn't exist. That way we don't have to bother with a "sync" at all and we prevent any crashes due to non existent directories.
