### ISSUE TITLE
Empty file with project name inside project folder is not recreated

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4766]
#### Software and hardware versions 
Collect v2021.2

#### Problem description
Empty file with project name inside project folder is not recreated

#### Steps to reproduce the problem
Use case 1 - special characters
1. User opens Settings -> Project display
2. User changes `Project name`
3. User puts a few special characters
4. Empty file with project name inside project folder is not created

Examples causing issue:

|![Screenshot_20210731-093440_ODK Collect](https://user-images.githubusercontent.com/3907554/127732687-45f22311-e001-4ffd-8b1f-9628f4000597.jpg)|![Screenshot_20210731-093103](https://user-images.githubusercontent.com/3907554/127732690-1944790f-3e29-4ad2-92c6-36f13cc9fe45.png)|
|---|---|

Use case 2 - removed directories
1. User creates project(s)
2. User removes `files` or `projects` or separate project directory
3. User restarts Collect, directories are recreated
4. Empty file with project name inside project folder is not recreated

#### Expected behavior
Empty file with project name inside project folder is recreated

**Comment by lognaturel** [comment]
@mmarciniak90 you tried this on the released version, right? Could you please try it on `master`? I think this is likely a duplicate of https://github.com/getodk/collect/issues/4747

**Comment by mmarciniak90** [comment]
@lognaturel you're right, the crash no longer occurs but there is still an issue with an empty file inside the project folder. The file is not created for these examples so I'm going to change the description.

**Comment by grzesiek2010** [comment]
The second case should be handled but I'm not sure about the first one. We can't create a file with reserved characters so what should we do?
- do nothing since it's a rare case
- create a file with a message that project name contains reserved characters
- replace/remove reserved characters from the file name

@seadowg @lognaturel what do you think?

**Comment by seadowg** [comment]
> The second case should be handled

Yeah, I think we could even make `StoragePathProvider` create the file when it creates the project dir.

> We can't create a file with reserved characters so what should we do?

I think just sanitizing it to be saved makes sense to me. Removing special characters feels good enough.
