### ISSUE TITLE
Facing issue with the upgrade version of ODK Collect app (v2021.2.2).

### ISSUE THREAD

**Issue by Sidra-adnan** [getodk/collect#4783]
1. **What is the problem be very detailed?**
Facing issue with the new version of odk collect app (v2021.2.2).

First test run results: 
•	ODK collect keeps stopping.
•	 We were unable to fill the forms properly.
•	Unable to send final submissions to the server.

Second test run result: 
•	Got error on the same question, and now because of incorrect usage of calculation in the form, but this issue was not there in the collect's previous version i.e. v1.30.1.
•	Unable to fill the form properly due to which we were not able to send the submissions to the server.

2.**What app or server are you using and on what device and operating system? Include version number.**
 ODK Central v1.1.1, ODK Collect upgraded version i.e. v2021.2.2

3. **What you have tried to fix the problem?**
The problem is resolved by installing the previous version of odk collect app i.e. v1.30.1. All the forms works smoothly with this version of collect app.

4.**What steps can we take to reproduce the problem?**
Attaching the xlsx survey form, you can use it with the upgrade version of collect app in this way you’ll be able to reproduce the error.

5.**Anything else we should know or have? If you have a test form or screenshot or logs attached below?**
Xlsx survey and screen recording of both versions are attached for your reference.

Would really appreciate it, if anyone of you please help me in solving this error. 

[form-odk (1).xlsx](https://github.com/getodk/collect/files/6963071/form-odk.1.xlsx)

![WhatsApp Image 2021-08-10 at 8 56 32 PM](https://user-images.githubusercontent.com/75972027/128898060-badd971d-748a-4e1e-a23b-cebfbe47e3fc.jpeg)
![WhatsApp Image 2021-08-10 at 8 58 31 PM](https://user-images.githubusercontent.com/75972027/128898072-6c32435a-dbe2-4392-8cbd-54faf48faf3e.jpeg)

https://user-images.githubusercontent.com/75972027/128898077-41ce4897-3395-4c23-af03-2206706fe2a6.mp4

https://user-images.githubusercontent.com/75972027/128898090-c25edd13-25d7-46fa-8fe2-2704cd9ad7af.mp4

**Comment by grzesiek2010** [comment]
Hi @Sidra-adnan 
Thanks for the detailed description that really helped to track down the issue quickly.

Your form has a form design issue in the way you use dynamic defaults. A short answer would be: You need to add a `trigger`. Please read the documentation: https://docs.getodk.org/form-logic/#dynamic-defaults-from-form-data
Here you can find an explanation of the same problem if you want to know more details and understand what happens under the hood: https://github.com/getodk/collect/issues/4750
I'm also attaching a fixed version of your form. I just added one columns (highlighted in yellow): 
[form-odk.1.xlsx](https://github.com/getodk/collect/files/6966264/form-odk.1.xlsx)

Please let us know if it works for you and for next time the [forum](https://forum.opendatakit.org/) is a better place for reporting problems like this one.

**Comment by Sidra-adnan** [comment]
Hi @grzesiek2010,

Thank you for your swift response. This was helpful!
I hope this minor change will not affect the submissions that are already there on odk central?

Regards

**Comment by grzesiek2010** [comment]
> I hope this minor change will not affect the submissions that are already there on odk central?

if you update your form and download a new version everything should be fine.
