### ISSUE TITLE
Add shared map layers directory

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4784]
From https://forum.getodk.org/t/use-reference-layers-across-several-collect-projects/34601.

Right now, if users want to add map layers, they can add them to the project level `layers` directory. This means if a layer is shared between multiple projects, it will need to be copied onto the device multiple times, which could end up wasting a lot of storage. We should add a shared `layers` directory at the top level that all projects can access.

## Acceptance

- [x] Given I've setup a Project in Collect
And I've copied a layer to the Project's `layers` directory (`/projects/{projectId}/layers`)
And I've copied a different layer to the shared `layers` directory (`/layers`)
When I navigate to map settings for my Project
And I click "Layer data file"
Then I see both layers are available

- [x] Given I've setup a Project in Collect
And I've copied a different layer to the shared `layers` directory (`/layers`)
When I navigate to map settings for my Project
And I click "Layer data file"
And I select the layer in the shared `layers` directory
And I open a map in a form
Then the layer loads correctly

**Comment by seadowg** [comment]
One thing I've realized when looking at this is that we need to update the caption that appears at the bottom of the reference layer selection dialog. At the moment it says: "There are no layer files in <layer directory> that are supported by the <basemap type> basemap." ("Above are all the layer files in..." when there are layer files). 

My thinking is that for the moment it just becomes: "There are no layer files that are supported by the <basemap type> basemap". The dialog feels like an awkward place to display multiple, long paths. Maybe we could link to docs as well so that it's clear where the files should be?

cc/ @yanokwa @lognaturel

**Comment by yanokwa** [comment]
Historically, we've put the path in the UI because people were manually managing images in a form and the like. I don't think that specific use-case is relevant today, but it feels like as long as folks are manually managing layers, they need some guidance. I think a single docs link is reasonable (and I'd love to see a before/after screenshot). 

Relatedly, I think we should eventually remove the specific paths in the other parts of the question widget UI. If you agree, file an issue.

**Comment by seadowg** [comment]
> Relatedly, I think we should eventually remove the specific paths in the other parts of the question widget UI

I'm not sure what paths you mean?

**Comment by seadowg** [comment]
Ok here's some different options I've quickly hacked to together:

1. Add an iconified text button in the space where the caption used to be:

    <img src="https://user-images.githubusercontent.com/556280/136771124-925b11e2-3cb0-4b3e-8477-e54cd9d5afbb.png" width=320/>

1. Add a "Get help" button as the dialog's "neutral" button:

    <img src="https://user-images.githubusercontent.com/556280/136771424-ba488adf-60ec-424e-80d3-40153358d164.png" width=320/>

1. Add a "Get help" button as the dialog's "negative" button (and hackily make "Cancel" the "positive" button):

    <img src="https://user-images.githubusercontent.com/556280/136771620-2dca65ba-c85b-43f9-b0af-27a9291e5dca.png" width=320/>

Clicking on any of these would lead to the docs:

<img src="https://user-images.githubusercontent.com/556280/136771928-24c8bd3f-4809-4751-a8b6-a88bc04ad4c9.png" width=320/>

My inclination is to go with option 2. It's not the prettiest, but it keeps the help option away from the standard dialog action  space (so hopefully avoiding accidental clicks) and the option is still placed prominently enough to be obvious. Going with options 2 or 3 would mean avoiding maintaining the custom "caption" on the dialog which would be a real positive for our future sanity.

@grzesiek2010 @yanokwa let me know what you think!

**Comment by seadowg** [comment]
Actually a 4th option would be to add a "?" icon at the top right of the screen that just links to https://docs.getodk.org/collect-settings/#maps-settings. We've talked about introducing this more generally and I think now would be a good time to use it, it'd also be far less maintenance than any of the other options as it doesn't involve a customization of the preference dialog. I'll go ahead with this option but let me know if there are any disagreements with that.

**Comment by yanokwa** [comment]
I'm OK with the ❓ icon. Only concern is if people will know what to do with that. The "Get help with reference layers" option is extremely clear in that regard, so I prefer it. It could even be "Learn more about reference layers".

As to the specific widgets, I was referring to what happens if you upload a form with missing media. https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java#L157 is an example.

**Comment by seadowg** [comment]
> I'm OK with the ❓ icon. Only concern is if people will know what to do with that. The "Get help with reference layers" option is extremely clear in that regard, so I prefer it. It could even be "Learn more about reference layers".

Yeah it's not the best, but once I factor in effort from us, I'm feeling best about adding help buttons to settings pages rather than at an individual setting level. You can check it out in the PR (#4842) now.

> As to the specific widgets, I was referring to what happens if you upload a form with missing media. https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java#L157 is an example.

Ah right. Yeah, agreed this kind of thing should got in the long term.

**Comment by yanokwa** [comment]
Adding to the settings page looks fine but it's not super discoverable as just an icon...especially since it's not in every settings page. Some text in teal that says "Learn more" or "Get help" in that corner would made it more visible. A ? in the dialog would be more visible too since there aren't that many elements in the dialog, but I understand why you might not want to do that.

**Comment by seadowg** [comment]
> Adding to the settings page looks fine but it's not super discoverable as just an icon...especially since it's not in every settings page. Some text in teal that says "Learn more" or "Get help" in that corner would made it more visible.

@yanokwa Thinking about it this morning, I'd like more time for us to feel out a "Get help" pattern that works more generally here across all preference screens. I'll revert back to just having a "Get help with Reference Layers" link in the dialog - that solves our problem here without rushing in an approach that we'll want to emulate everywhere. I'll also add an issue around settings docs links that we can focus on in a later release.
