### ISSUE TITLE
Username isn't updated correctly when switching projects

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4792]
#### Software and hardware versions 
Collect v2021.2

#### Problem description
When switching between projects, the username preload doesn't get updated. I haven't tried it but I assume that the same problem exists with phone number and email.

#### Steps to reproduce the problem
1. Create a form that accesses the username such as [this one](https://docs.google.com/spreadsheets/d/15Tp1CauiRuTgudfZ6OClGamM5q9ezV2G-wg1AoF8PQQ/edit#gid=0)
2. Create multiple Collect projects that access this form with and without usernames (e.g. from App Users `Foo` and `Username test` at https://test.getodk.cloud/#/projects/149/app-users)
3. Switch between projects and see that the username of whichever project was created last gets used
4. Close the form, switch to a project that has a username other than the one that was being used, kill Collect, reopen it, fill the form and see that the expected username is now used.

#### Expected behavior
Switching projects should reset username, phone number and email preloads.

#### Other information 
This is likely a matter of reloading some things from `PropertyManager` on project switch. It would be good to think through anything else that might not be reset.

**Comment by grzesiek2010** [comment]
Right `PropertyManager` needs to be reloaded and we would need to do that every time the current project is changed:
-switching a project
-adding  a new project
-deleting a project
-existing project migration

so it might happen in many places and I think that handling all those cases separately would be risky and in the future we might add something and forget to add reloading properties again.

One solution would be to trigger reloading every time `CurrentProjectProvider#setCurrentProject()` but that would mean passing `PropertyManager` and coupling those objects. 
A better and safe solution would be to reload those prefs every time we load a form:
https://github.com/getodk/collect/pull/4793

what do you think?

**Comment by seadowg** [comment]
We still need to merge the changes into master to close this.
