### ISSUE TITLE
@grzesiek2010  I have tested the changes on the android versions mentioned in the issue i.e Android 5.1, 8.1, 9.0, 10.0, and everything works fine. No unexpected behavior is present in the settings button. If there are any more steps in testing please let me know. Thank You!

### ISSUE THREAD

**Issue by gp-agtech** [getodk/collect#4808]
I wonder whether android 7.1 support ODK collect.
Any clues? Looking into buying this phone for ODK collect https://www.sunmi.cz/en/sunmi_l2k.html

**Comment by grzesiek2010** [comment]
> I wonder whether android 7.1 support ODK collect.

We support android 5.0 and newer versions. If you want to ask about the recommended device you can search the forum https://forum.getodk.org/ as I remember there were similar topics or create your own one.
