### ISSUE TITLE
Google map not loading in GeoPoint Widget

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#482]
#### Software and hardware versions 
Collect v1.4, Android v4.4, device used...

#### Problem description
Google map is not loading in GeoPoint Widget

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

![device-2017-03-01-145412](https://cloud.githubusercontent.com/assets/8918023/23453725/6ff759e6-fe8f-11e6-8a0e-f506d1b8fbc8.png)

**Comment by grzesiek2010** [comment]
Look at https://github.com/opendatakit/collect#using-apis-for-local-development -> Google Maps API probably this is your problem. Please confirm that and close the issue if everything is ok.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Thanks, that indeed was the problem.  
Closing the issue.
