### ISSUE TITLE
Font styling does not work in list-nolabel

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#4822]
#### Software and hardware versions 
Collect v2021.2.3

#### Problem description
Font styling does not work in list-nolabel

#### Steps to reproduce the problem

[color-test.xlsx](https://github.com/getodk/collect/files/7107337/color-test.xlsx)

**survey sheet**
<img width="684" alt="Screen Shot 2021-09-03 at 09 33 32" src="https://user-images.githubusercontent.com/32369/132039130-e9c71722-9566-4039-a44e-32ee4fe9d630.png">

**choices sheet**
<img width="388" alt="Screen Shot 2021-09-03 at 09 33 51" src="https://user-images.githubusercontent.com/32369/132039147-9868901f-dfb8-413b-8703-6f8bc73f4f0c.png">

**collect UI**
<img width="474" alt="Screen Shot 2021-09-03 at 09 29 19" src="https://user-images.githubusercontent.com/32369/132038944-f438b5ca-6bd8-4666-b9c3-c89114dbe424.png">

#### Expected behavior
Labels should show font styling

**Comment by ghost** [comment]
Hello I'd like to work on this issue can you explain a bit more about this issue
