### ISSUE TITLE
Issues with newly updated themes 

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4832]
#### Software and hardware versions 
Current master branch

#### Problem description

1. Empty area around the clipboard menu (only in preferences, in form filling everything seems to be fine)

|  |  |
| ------------- | ------------- |
| ![Screenshot_1632428898](https://user-images.githubusercontent.com/3276264/134579951-35a9401e-bf4f-4a16-a2c8-9638055b9209.png)  | ![Screenshot_1632428969](https://user-images.githubusercontent.com/3276264/134579957-241c319b-9ef0-4761-a3d2-48fb143378b3.png)  |

2. Disabled buttons in form entry looks good (like disabled) but other buttons not really if they are in the same state

| Get selected button is disabled but it's hardly visible | This looks good |
| ------------- | ------------- |
| ![Screenshot_1632429051](https://user-images.githubusercontent.com/3276264/134580557-457b4b74-a8af-4017-8391-c6c98cc22195.png)  | ![Screenshot_1632429066](https://user-images.githubusercontent.com/3276264/134580562-eea57e40-b5c2-4ca1-af52-d939e587ffc8.png) |

~~3. I noticed that after switching themes sometimes some elements are not undated immediately like the `x` icon~~ EDIT (from @seadowg): This is an existing issue we noticed during the QA pass and decided not to fix. I'll pull it out as a [separate issue](https://github.com/getodk/collect/issues/4836) and mark it as such.

**Comment by seadowg** [comment]
I've asked a question on the Material Components Discord channel about the first one: https://discord.com/channels/259087343246508035/259087343246508035/894576324411273266
