### ISSUE TITLE
Integer questions do not play video

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#4834]
#### Software and hardware versions 
Collect 2012.2.4

#### Problem description
Reported at https://forum.getodk.org/t/integer-questions-do-not-play-videos/35175. On integer question types, the video do not play. The video button is displayed but the video is not opened

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
[Example Problem.zip](https://github.com/getodk/collect/files/7232052/Example.Problem.zip)

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 are you able to check if this is a regression?

**Comment by kkrawczyk123** [comment]
@seadowg  I have tried few past versions of Collect and from my investigation, it looks like it has been broken somewhere between 1.26.1 and 1.26.2.
