### ISSUE TITLE
Collect should use `READ_PHONE_NUMBERS` permission instead of `READ_PHONE_STATE` on API 30+

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4838]
https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers

**Comment by TomRCummings** [comment]
@getodk-bot claim

**Comment by seadowg** [comment]
Hmmm I wonder if @getodk-bot is having problems. I'll assign you @TomRCummings.

**Comment by grzesiek2010** [comment]
We are going to get rid of auto-populating phone numbers so this permission won't be used anymore.
