### ISSUE TITLE
Form update notification from not-used project displays while using another project

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4841]
#### Software and hardware versions 
Collect v store version, master Android vx.x.x, device used...

#### Problem description
When testing Central I have noticed that I am obtaining form update notifications from another project than one that I am using. 

#### Steps to reproduce the problem
1. Scan draft testing qr code from Central as project1
2. Publish form on Central
3. Scan other qr code from Central as project2, this time legacy qr code so an automatic form update is disabled
4. Stay on 2nd project 
5. Wait ~ 15min
I am getting a form update failed notification from another project than the one that I am using.

#### Expected behavior
User should only see notifications from the currently used project.

**Comment by seadowg** [comment]
Related to #4787. We should probably still show notifications for other projects (other than the current one) but we need to make it clearer what's going when the user sees the notification.

**Comment by seadowg** [comment]
Like we're proposing in #4787 the fix here should just be to display the project in the notification in the notification subtext
