### ISSUE TITLE
The location crosshair is not visible on Mapbox

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4858]
#### Software and hardware versions 
Collect master

#### Problem description
The location crosshair is not visible on Mapbox

#### Steps to reproduce the problem
1. User uses Mapbox 
2. User opens Geowidget with map appearance
3. User sees a blue circle but the crosshair is not visible

#### Expected behavior
The user's location is displayed using a crosshair at the location

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/137172158-0eda8175-fb86-4ef7-a59e-408f0aad59c1.jpg">

#### Other information 
Noticed during testing #4852

**Comment by seadowg** [comment]
@mmarciniak90 I'm guessing this is a regression right?

**Comment by mmarciniak90** [comment]
Yes, it is. I added the correct label. Thanks.
