### ISSUE TITLE
[By April 2022] Declare info for Play Store safety section

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4871]
https://android-developers.googleblog.com/2021/07/new-google-play-safety-section.html

**Comment by lognaturel** [comment]
Let's use [this Google doc](https://docs.google.com/document/d/1iilvb2xrJzDWvhU8g_Tfe5mQMJLUGP_DZglCMfYH314/edit) to iterate on text.

Current timeline from [support docs](https://support.google.com/googleplay/android-developer/answer/10787469):
```
    October 2021: The Data safety form is available on the App content page in Play Console.
        Developers can fill out and submit the form to receive early feedback on identified issues. App submissions will not be impacted based on your Data safety form during this time. (Your app may be impacted if there are other policy violations.)
        If there are issues in your Data safety form, you’ll receive an email letting you know “App Content Approved with Issues” – you should review details and take action. You can temporarily proceed to publish app updates by manually reverting your Data safety form in Play Console back to draft mode.
        Developers should add a link to their app’s privacy policy if they haven’t already.
    February 2022: The Data safety section will be available on Google Play to all users.
        If there are any discrepancies in the information provided, users will see a note on your store listing under Data safety that says “No data available” and you’ll receive an email letting you know your new app submission or app update is rejected.
        You can temporarily proceed to publish app updates by manually reverting your Data safety form in Play Console back to draft mode.
        Developers must have a privacy policy listed to have their data safety information shown to users.
    April 2022: New app submissions and app updates will be rejected in Play Console if there are unresolved issues with the form.
        All new apps and app updates will require a completed Data safety form. You can no longer publish a new app or app update if your Data safety form is incomplete or has unaddressed issues.
        All new apps and app updates will require a valid privacy policy.
    After April 2022: Non-compliant apps may face additional enforcement actions in the future.
```

**Comment by yanokwa** [comment]
I'd encourage us to have this finished way before the April timeline. Maybe mid February? I believe we will need to fill out a form and submit it to Google for approval. If we wait until April, there will likely be a huge backlog.

**Comment by seadowg** [comment]
@yanokwa agreed! This is part of (and at the top of the list of) our next release cycle.

**Comment by lognaturel** [comment]
Thanks for completing this, @yanokwa. [The doc](https://docs.google.com/document/d/1iilvb2xrJzDWvhU8g_Tfe5mQMJLUGP_DZglCMfYH314/edit) has more details on some of the decisions we had to make. As usual, Collect doesn't fit the information asked very well.

It looks like the section hasn't rolled out to the Play Store yet. We'll revisit periodically as it gets displayed to make sure that our responses are consistent with other similar apps'.

**Comment by yanokwa** [comment]
Just got a message from Google. 

> Users will start seeing the Data safety section in Google Play store starting late April. Privacy policies and approved Data safety forms will be required for all apps starting July 20, 2022 for any new apps and / or updates.

There is a changelog at the bottom of https://support.google.com/googleplay/android-developer/answer/10787469. There's nothing actionable on our part.
