### ISSUE TITLE
Crosshair disappears when change offline layer and minimize app when use Mapbox

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4873]
#### Software and hardware versions 
Collect v1.x.x, Android v all, device used...

#### Problem description
When testing #4867 I have noticed another issue connected to crosshair when using Mapbox with offline layers.

#### Steps to reproduce the problem
Scenario 1:
1. Add at least 1 offline layer
2. Set Mapbox in settings
3. Open map view (crosshair visible)
4. Select offline layer - crosshair is no longer visible
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/33342488/137926377-45f145d6-85f1-47e1-bc85-7227be174206.gif)

Scenario 2:
1. Set Mapbox and offline layer in settings
2. Open Map view (crosshair visible)
3. Minimize app
4. Go back to app - crosshair is no longer visible

#### Expected behavior
Crosshair should not disappear when minimize app or select offline layers

#### Other information 
Both issues work correctly on v1.26

**Comment by lognaturel** [comment]
@grzesiek2010 the underlying issue you describe in the PR is tracked at https://github.com/getodk/collect/issues/3883. There’s more discussion linked to from my comment.

**Comment by grzesiek2010** [comment]
Thanks @lognaturel
