### ISSUE TITLE
Unable to play video attached to form on Android 11 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4876]
#### Software and hardware versions 
Collect v play store/master Android v 11 device used...

#### Problem description
When testing #4860 I have noticed that playing video does not work on Android 11 device:
![Screenshot (Oct 20, 2021 3_37_09 PM)](https://user-images.githubusercontent.com/33342488/138118370-16b1720c-7b85-4527-a848-7cd5da5ca394.png)

#### Steps to reproduce the problem
1. Open any form with video attachment/ 1st question of attached form
2. Try to play video

#### Expected behavior
User should be able to play video

#### Other information 
- example of form: https://github.com/getodk/collect/files/7232052/Example.Problem.zip
- works well on v2021.2 beta 0

**Comment by grzesiek2010** [comment]
Does it work well if you play a video recorder/attached using the video widget?

**Comment by kkrawczyk123** [comment]
No, I can see:
![Screenshot_20211021-122350](https://user-images.githubusercontent.com/33342488/138259720-a62d36f0-f6b7-46ec-a00a-462f4228312e.png)
