### ISSUE TITLE
Revise submit notifications

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4884]
Auto and background manual submits should have the new error flow as part of their notifications.

Success notification:
* Should have [subtext](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setSubText(java.lang.CharSequence)) with project name
* Title text should be "All uploads succeeded!"
* Clicking takes user to Main Menu

Failure notification:
* Should have [subtext](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setSubText(java.lang.CharSequence)) with project name
* Title text should be "<failures> of <total uploads> uploads failed!
* Clicking takes user to Send Finalized Form
* Additional action "Show details" takes user to errors screen with errors

**Comment by grzesiek2010** [comment]
This is partly fixed by https://github.com/getodk/collect/pull/492

**Comment by seadowg** [comment]
@grzesiek2010 is the "partly" because it mentions "manual" submits? If so, let's just edit the description and close this off. I wrote this issue thinking we'd do background manual submits first, so the context is wrong.

**Comment by grzesiek2010** [comment]
Partly because `Additional action "Show details" takes user to errors screen with errors` is not implemented. As i said in https://github.com/getodk/collect/pull/4929:
> The last thing of note is that for now I decided to display the failure message in the notification because current implementation of auto submit does return just one message like in case of match exactly so there is nothing we could display in our new ErrorActivity. This will be improved later.

so this is not implemented.
