### ISSUE TITLE
Calendar numbers are unreadable on Android 4.1.2

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#489]
#### Software and hardware versions 
Collect v1.4.16-18-gd398fc05, Android 4.1.2 Nexus 5 emulator

#### Problem description
<img width="223" alt="screen shot 2017-03-01 at 12 48 59 pm" src="https://cloud.githubusercontent.com/assets/967540/23473252/812b8884-fe7d-11e6-9819-df0faffb7f96.png">

#### Steps to reproduce the problem
1. Download a form with a calendar question such as New Widgets from the default test server
1. Go to the question with the calendar widget

#### Expected behavior
From API 22 emulator:
<img width="225" alt="screen shot 2017-03-01 at 12 52 07 pm" src="https://cloud.githubusercontent.com/assets/967540/23473348/eb2255f6-fe7d-11e6-8ba1-6a3de64235e3.png">

#### Other information 
The calendar scrolling is also not optimal but that should be addressed as a separate issue.

**Comment by shobhitagarwal1612** [comment]
How about we input the date from user in custom dialog box?

**Comment by lognaturel** [comment]
For now I think we should try to just make the numbers the same size across Android versions if possible. 

I do agree that the date and date-time widgets need rethinking. If you could file a separate issue with your thoughts on what that would look like, that would be very helpful. Before doing that, I recommend you check out the related issues filed by @dalerhoda.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I'm onto this issue for now

**Comment by shobhitagarwal1612** [comment]
@lognaturel I build the latest code and installed it on Samsung GT-S5282 Android 4.1.2, API 16 but couldn't find the reported issue. 

Attached image is of the same device
![device-2017-03-02-002921](https://cloud.githubusercontent.com/assets/8918023/23476101/9f1b4034-fedf-11e6-8dd4-5c37c6790447.png)

Could you also give information of the details of screen of the android 4.1.2 emulator used

**Comment by lognaturel** [comment]
That is very strange, @shobhitagarwal1612. I've updated my initial issue to say I was using a Nexus 5 emulator. I'm not sure whether that's relevant or perhaps it's a screen size/resolution related issue. I also notice that your numbers are perfectly centered but mine on API 22 are aligned with the top of each line so evidently there are some inconsistencies with this widget. Perhaps @grzesiek2010 has some ideas as he's dealt with weird bugs in this area before.

**Comment by grzesiek2010** [comment]
It's pretty easy to reproduce you have to use vd Nexus 5 and Android 4.1 as @lognaturel mentioned.
http://stackoverflow.com/questions/14980242/small-numbers-in-calendarview-android
they say it's been fixed in 4.2 and there is a solution there too (I didn't test that solution).
