### ISSUE TITLE
Stop using reference to mutable list as data backing `FileArrayAdapter`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4899]
We're seeing the occasional [crash](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4d7d67b41b272b264d991d4959873afc?time=last-seven-days&versions=v2021.3.0%20(4316)&sessionEventKey=61844403001D00012745F22552D65CAC_1605271776140814949) linked to the `FileArrayAdapter`:

```java
Fatal Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(16908298, class android.widget.ListView) with Adapter(class org.odk.collect.android.adapters.FileArrayAdapter)]
       at android.widget.ListView.layoutChildren(ListView.java:1597)
       at android.widget.AbsListView$CheckForTap.run(AbsListView.java:4344)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Reviewing `FileArrayAdapter`, it does look like that the data it's back with is a `List` passed from its parent `GoogleDriveActivity` and that that `List` is mutated in `getResultsFromApi` without a `notifyDataSetChanged` call. I wasn't able to reproduce, but we can see from the crash that someone is experiencing this.

In general, it's a pretty bad idea to share a direct reference to a mutable `List` between two objects like this, especially when we're dealing with something as complex as an `Adapter`. To remove any risk of this kind of crash, and to make the code less confusing, we should just remove the shared reference and make the `Adapter` the single source of truth or copy data from the Activity to the Adapter when changing it (with a setter).

**Comment by grzesiek2010** [comment]
We are going to remove Google Drive integration so let's close this issue.
