### ISSUE TITLE
Check whether Google play services are installed or not

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#490]
#### Problem description
Currently the app doesn't check whether the play services of the required version are installed or not before trying to access any concerned google API like Google Maps, Google Sheets or Google Drive API. Right now the app doesn't give any hint to the user as to what is happening when services are not found

#### Expected behavior
To show a dialog box that the required services are not found and a option to update to the latest version

@lognaturel @yanokwa @Dvik Any thoughts?

**Comment by Dvik** [comment]
i'm working on #132 which would fix the play services issue whenever location is accessed. 
i'm also testing #488 on an API 16 emulator with no Google Play Service.

**Comment by lognaturel** [comment]
Great! So maybe we can wait for @Dvik's fix for #132 and then see how it can be generalized.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @Dvik There's a nice fix for #132 in #491 that's ready to merge after a small style change. Let's leave this one to @Dvik since he's in that code already!

**Comment by shobhitagarwal1612** [comment]
@lognaturel Is this issue still open?

**Comment by lognaturel** [comment]
@Dvik I know you mentioned on another issue being busy. Would you like to also let someone else take this one on? We would really like to have it in the next release (complete by March 22nd)! 😊

**Comment by shobhitagarwal1612** [comment]
@lognaturel I had to check if play services are installed or not while updating the sheets library. If @Dvik allows, I can quickly add the same code to the other classes as well

**Comment by Dvik** [comment]
Yeah, sure.
I would be more than happy to let someone take it up.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I think you have most of the code needed in #607. Would you like to take this one on when you're done there?

**Comment by shobhitagarwal1612** [comment]
Yeah, I would love to

**Comment by grzesiek2010** [comment]
I am working on this as @shobhitagarwal1612 is busy and we need that for Wednesday's code freeze.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Thanks for taking it up.
