### ISSUE TITLE
Block editing forms that are being sent (and vice versa)

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4907]
The user shouldn't be able to edit a finalized instance while instances are being sent. One thing we could do here is completely block the ability to edit a finalized instance, but that could be controversial. 

A softer option would be to utilize the instance's `changeLock` during editing of a finalized instance. In that world:

* Opening a finalized instance would be blocked when the instances are locked (during auto send)
* Auto send wouldn't run when a finalized form is open

I would definitely be in favour of preventing edits if we feel we can get away with it. Interested in thoughts from @grzesiek2010 and @lognaturel on that one.

**Comment by lognaturel** [comment]
We are going to be blocking edits of finalized forms so this no longer applies.
