### ISSUE TITLE
Support `map` appearance in `select`/`select_one_from_file`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4943]
As discussed on [the forum](https://forum.getodk.org/t/ability-to-load-locations-into-the-geowidget-to-guide-data-collection/27406/12) (along with design details), we want to add support for `.geojson` files in Select questions. This means adding a `map` appearance for `select_one`/`select_one_from_file` (it's opaque to Collect which "select one" is actually being used in the form) that allows the enumerator to select an item from a map. Each item in the map is positioned using data from the select choice's `geometery` column.

## Backlog
 
- [x] #4947
- [x] #4949
- [x] #4948 
- [x] Make sure button text size uses dynamic font size (`answerSize`)

## Cleanup

- [x] Investigate moving shared map behaviour from `SelectionMapFragment` into `MapFragment` implementations (maintaining map zoom on recreate for instance)
- [x] Remove individual implementations of zoom behaviour
- [x] Investigate extracting `maps` module to house `MapFragment`, `MapPoint` and `MapFragmentFactory` and creating modules for each implementation (classic **D**epenednecy **I**nversion **P**rinciple setup)
- [x] Organize `geo` package structure
- [x] Add loading state/progress dialog to maps - currently DB operations are all happening on the UI thread (existing problem)
- [x] Add tests to cover bottom sheet behaviour (currently untestable due to animations always running)

**Comment by lognaturel** [comment]
> Exposing standard GeoJSON Feature attributes (type and coordinates) for select choices

In the forum writeup, I proposed exposing `geometry` in ODK format. That means the type isn't needed. A first split on ";" could be used to figure out how many points there are. If there are more than one, it's a shape if the first and last points are identical. Does that seem ok, @seadowg or do you see an issue with it?

Because we're using the `map` appearance to determine that a map should be drawn, there's nothing special about the source file being `geojson` and I think work on this can start right away. By the time JavaRosa does its parsing, we won't be able to tell what the source was anyway. Any select with `geometry`, `name` and `id` fields should work.

**Comment by lognaturel** [comment]
> Any select with geometry, name and id fields should work.

I think it's even better than that -- only `geometry` is needed. The XForm configures which fields to use as `name` and `label`. It will be `id` and `title` by default for geojson as it is now `name` and `label` by default for other selects but [will soon be configurable](https://github.com/XLSForm/pyxform/issues/461).

[Here](https://docs.google.com/spreadsheets/d/191Taxl2BU1UmBPpU4SLXEiP2cnhVx7mSe8TJeKnEDAI/edit#gid=1988906120) is a form that should work.

All this makes me wonder a bit whether the geometry field should be configurable as well. Will ponder what that might look like but we can start assuming its name is `geometry`.

**Comment by seadowg** [comment]
> [Here](https://docs.google.com/spreadsheets/d/191Taxl2BU1UmBPpU4SLXEiP2cnhVx7mSe8TJeKnEDAI/edit#gid=1988906120) is a form that should work.

Ace! Could you add examples of how the different GeoJSON features will look (like `LineString`, `MultiLineString` etc). I want to make sure I have that all correctly understood in my head.

**Comment by lognaturel** [comment]
Consider requesting no markers on the basemap if it's possible. It's very tempting to tap on them and it's hard to see the form-specified markers in certain locations where there are many many markers on the basemap.

Wild idea: `string` field with `map` appearance that lets users select markers on the base map. Presumably GMaps and Mapbox make that possible and would return an OSM id. Not sure about osmdroid and its raster tiles.

**Comment by lognaturel** [comment]
I've filed a separate issue for invalid geometries: https://github.com/getodk/collect/issues/5075. After thinking through it more I don't think it has to be part of the initial feature and I would tend to take it out of this meta issue.
