### ISSUE TITLE
Add support for `select_one`/`select_one_from_file` with `map` appearance and without `quick` appearance

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4948]
## Acceptance

- [x] Given I'm on the map after clicking "Select place"
When I click on a point
And I click "Select"
Then I return to the question with the selected point as the answer

- [x] Given I'm on the map after clicking "Select place"
When I click on a point with a `label` column
Then I see the `label`

- [x] Given I'm on the map after clicking "Select place"
When I click on a point with additional non `name`/`label` columns
Then I see the `"<column name>: <column value>"` for the point

**Comment by lognaturel** [comment]
https://github.com/getodk/collect/pull/5073#discussion_r836654302 has discussion about localized forms and what to do in the case of no label.
