### ISSUE TITLE
Add support for `map` and `quick` appearance in `select_one`/`select_one_from_file`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4949]
## Acceptance

- [x] Given I've loaded a form into Collect with a `select_one`/`select_one_from_file` with multiple choices with a point in their `geometry` column and `map`/`quick` appearances
When I open the form
And I navigate to the question
And I click "Select place"
Then I see all the points on a map at the correct coordinates
And the question label is shown at the top of the screen

- [x] Given I'm on the map after clicking "Select place"
When I click on a point
Then I return to the question with the selected choice as the answer

## Notes

An example form with a `geometry` column for choices is [here](https://docs.google.com/spreadsheets/d/191Taxl2BU1UmBPpU4SLXEiP2cnhVx7mSe8TJeKnEDAI/edit#gid=1988906120).

The [forum post](https://forum.getodk.org/t/ability-to-load-locations-into-the-geowidget-to-guide-data-collection/27406/12) mentions matching the form map colors for the map markers here, but I think it would be a good idea to experiment with using theme colors. For instance, we could use `?colorSurface` for unselected markers and `?colorSecondary` for selected ones (to match radio buttons etc).

**Comment by lognaturel** [comment]
The necessary JavaRosa snapshot should now be available: https://oss.sonatype.org/content/repositories/snapshots/org/getodk/javarosa/3.4.0-SNAPSHOT/
