### ISSUE TITLE
React to location permission changes in Android 12

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4959]
In Android 12, users are always given the choice between fine and coarse location accuracy: https://developer.android.com/training/location/permissions

This is problematic because data collectors may accidentally select coarse and then not be able to capture points as required by the form

- [ ] Brainstorm some concrete directions we could take
  - have a permission-granting flow at app launch so a project manager can do that for a bunch of devices (@seadowg)
  - have some way in the geo widgets to jump to settings and adjust
- [x] Post ideas on forum and solicit feedback https://forum.getodk.org/t/dont-allow-access-to-geo-question-types-if-coarse-vs-fine-location-perms-given/39355

**Comment by seadowg** [comment]
We also need `FINE_LOCATION` to access satellite data as well so we'll need to consider this here.

**Comment by lognaturel** [comment]
Addressed by https://github.com/getodk/collect/issues/5299 -- we just fail if only coarse permissions are granted.
