### ISSUE TITLE
Replace deprecated CopyFormRule

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4967]
#### Problem description
`CopyFormRule` is a [rule](https://ncorti.com/blog/junit-rules) we use in our tests to copy forms that we need to use in particular tests to app storage before starting a test. It is marked as deprecated and should be removed. We should use `copyForm()` form `Page` instead, like we do for example in `AndroidShortcutsTest`

**Comment by dczerwinski** [comment]
@getodk-bot claim
