### ISSUE TITLE
Google account options should refresh when 'Google account' is tapped

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#498]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
After adding a Google account to the device, it is not available in the Google account selection menu.

#### Steps to reproduce the problem
1. Set the platform to Google Drive, Google Sheets
1. Tap Configure platform settings
1. Go to the device Settings > Account > Google and add a Google account
1. Go back to ODK Collect
1. Tap Google account and the new account doesn't appear
1. Tap back to return to the general settings
1. Tap Configure platform settings
1. Tap Google account and the new account appears

#### Expected behavior
The account list should be refreshed when Google account is tapped.

**Comment by rishsethia** [comment]
Hi @lognaturel I am trying to solve this !
I will send a PR when solved !
Thanks

**Comment by Dvik** [comment]
it's probably because we should get the accounts in `onResume()` rather than `onCreate()`. 

@rishsethia are u working on it or should i send a PR as i've almost set up the code to do so?

**Comment by rishsethia** [comment]
@Dvik 
You can go ahead since you've set up the code ! I was looking to solve it after finishing my current task !
All the best ! :D
