### ISSUE TITLE
Fix deprecated methods in FormEntryPage

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4983]
#### Problem description
In `FormEntryPage` we have deprecated methods like:
- swipeToNextQuestion
- swipeToPreviousQuestion
- clickOnDoNotAddGroup
- clickOnDoNotAddGroupEndingForm
- clickOnAddGroup

Every method has its own description so it should be clear what we want to use instead.

**Comment by dczerwinski** [comment]
@getodk-bot claim
