### ISSUE TITLE
"Yes" and "No" responses are displayed incorrectly in hierarchy view in single select widgets

### ISSUE THREAD

**Issue by srujner** [getodk/collect#4984]
#### Software and hardware versions 
Collect v2022.1 Android 11, Pixel 3a

#### Problem description

I've noticed a small regression issue related to single select widget in hierarchy view. The answers "Yes" and "No" should be green or red.

![Screenshot_20220121-125553](https://user-images.githubusercontent.com/85225519/150530376-1a3acf61-df25-49d3-b00d-bef539f85c75.png)

the same case from v2021.3:

![Screenshot_20220121-134252](https://user-images.githubusercontent.com/85225519/150530454-1c4407b0-d108-4766-bdec-9114941362ea.png)

#### Steps to reproduce the problem
1. Download style-example.xml
2. Fill blank form for style-example
3. Open hierarchy view

#### Expected behavior
An answer "Yes" should be green and an answer "No" should be red.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by srujner** [comment]
I also noticed that a similar issue is with the CenterText:
![Screenshot_20220121-143724](https://user-images.githubusercontent.com/85225519/150537192-7ec30cce-38cc-474e-8837-4c48d12529aa.png)

**Comment by seadowg** [comment]
I'm going to guess I oversimplified something in the additions I made to https://github.com/getodk/collect/pull/4897. Looking at it again, we made the assumption that answers (which are used as the secondary text) wouldn't include HTML that we'd want to render. The original problem in fact was that answers were rendering weirdly if you [typed HTML in as a text answer](https://github.com/getodk/collect/pull/4897/).

@lognaturel it looks to me like we do "officially" support HTML in choice labels (which will get used as answer text) according to [the docs](https://docs.getodk.org/form-styling/#id14). Are there other special cases? What if another answer is just a computed mirror (like a dynamic default) of a choice label for instance? Is rendering HTML for text answers actually the better problem to have?

**Comment by lognaturel** [comment]
> Are there other special cases

I don’t believe so. I think the rule should be that html is rendered in strings that are intended only for display. That means labels and hints. I believe the only values that get replaced by labels are selects and the closely-related rank. In all other cases values are raw. 

I don’t exactly remember how values end up in the hierarchy view. Ideally selects could be treated specially. 

> What if another answer is just a computed mirror (like a dynamic default) of a choice label for instance?

This is possible but unlikely, I think. I would expect that not to be html rendered. 

If all this is too difficult I think we should consider backing out of the change.

**Comment by seadowg** [comment]
> If all this is too difficult I think we should consider backing out of the change.

Agreed! I think we should introduce a special case for selects and acknowledge that if a choice label with HTML is used as a dynamic default somewhere else, it won't get rendered as HTML (and will just show as plain text).

**Comment by lognaturel** [comment]
Sounds great! What I meant by backing out is that if it’s too hard to introduce the special case then backing out of #4897 might be best.

**Comment by grzesiek2010** [comment]
https://github.com/getodk/collect/issues/4480 was not something big so I think we should just revert https://github.com/getodk/collect/pull/4897 for v2022.1.

**Comment by grzesiek2010** [comment]
After looking at that #4897 I think it added some nice refactoring and tests so I think we can just add styling back instead of reverting the whole pr. I created a pull request for that: https://github.com/getodk/collect/pull/4992. Then we should reopen #4480 and add more details to fix it according to what @seadowg said:

> I think we should introduce a special case for selects and acknowledge that if a choice label with HTML is used as a dynamic default somewhere else, it won't get rendered as HTML (and will just show as plain text).
