### ISSUE TITLE
Change the behaviour of 'Leave a review' under About screen

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#499]
#### Software and hardware versions 
Collect v1.4, Android v4.4, device used...

#### Problem description
In `About screen` there is a `Leave a review` option. The description of the option says _Leave a review on Google Play_. On clicking the option a chooser intent appears. The problem is that if the user has google play store installed, then also a list of all available options appear instead of directly opening the Google Play Store app.

#### Steps to reproduce the problem
Click **Leave a review** under `About screen`
#### Expected behavior
If the device has GooglePlayStore installed then directly open GooglePlayStore. Otherwise ask the user to choose from a list of available options

**Comment by shobhitagarwal1612** [comment]
I am working on it

**Comment by lognaturel** [comment]
Do you want to let the user choose if PlayStore isn't there or just use the default browser? We don't really want users going to PlayStore alternatives. The browser seems like a good choice to me.

**Comment by shobhitagarwal1612** [comment]
I will list all the available browsers only in case google play store is not found. The user may then select to open in the preferred browser

**Comment by lognaturel** [comment]
Ok, so you can filter to just show browsers and not alternative app stores, right?

**Comment by shobhitagarwal1612** [comment]
Yes
