### ISSUE TITLE
FormEntryActivity does not return instance uri after finishing a form

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5008]
#### Software and hardware versions 
Collect v2021.3.4

#### Problem description
`FormEntryActivity` does not return instance uri after finishing a form. The problem seems to be caused by the fact that we hide `FormEntryActivity` behind `FormUriActivity` after merging https://github.com/getodk/collect/commit/0e927d7a8bdc3254690cf27b49083235bf95214e and `FormUriActivity` does not return the value returned by `FormEntryActivity` it is just ignored.

#### Other information 
The problem has been originally reported on the forum: https://forum.getodk.org/t/data-uri-is-null-in-onactivityresult/36548

**Comment by seadowg** [comment]
We should cherry-pick the fix for this onto a `v2022.1.x` branch so we can release it as a patch.
