### ISSUE TITLE
Back button doesn't close Geopoint dialog

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5018]
#### Software and hardware versions 

Collect v2022.1.0

#### Problem description

The back button doesn't do anything while the Geopoint dialog is up.

#### Steps to reproduce the problem

1. Open a form with a `geopoint` question
2. Navigate to the question and hit "Start GeoPoint"
3. Press back

#### Expected behavior

The back button should return to the form.

**Comment by grzesiek2010** [comment]
If this is not a regression is it still something we want to change?

**Comment by seadowg** [comment]
> If this is not a regression is it still something we want to change?

Good question. Personally I think so. I guess it increases the chance for accidental closing, but the GPS will have warmed up so it's not like the user would then have to start the process of getting a fix all over again. What do you think?

**Comment by grzesiek2010** [comment]
> What do you think?

I'm not that sure that's why I'm asking... @lognaturel what do you think?

**Comment by lognaturel** [comment]
Yeah, it's nice to have consistency and plus a user has asked about it. Agree with @seadowg that there's no clear benefit from deviating from usual dialog behavior.

**Comment by grzesiek2010** [comment]
>Yeah, it's nice to have consistency

but consistency with what? To me consistent behavior when it comes to dialogs is when:
- you can close it only clicking on one of its buttons (it's not closable)
- or you can close it clicking the buttons but also the device back button and out of its area (it is closable)

here we just do that for back button what's not intuitive to me. Can't we just make it closable if you think that the current behavior should be changed?

**Comment by seadowg** [comment]
Looking at Material's Navigation patterns ([here](https://material.io/archive/guidelines/patterns/navigation.html#navigation-up-back-buttons)) it does seem like the back button should close dialogs:

> The Back button also: 
> * Dismisses floating windows (such as dialogs or popups)

However, the argument could easily be made that the user is doing something critical and so should explicitly have to exit the dialog. To be honest though, I'm not sure how strong that is given they would also have to explicitly be hitting back (not that easy to accidentally hit or Android would be chaos), they can just reopen the dialog without losing progress (the GPS will be warm) and if this wasn't a dialog hitting back would definitely close the screen. 

I think I'd vote for going with the change and making the back button close the dialog as otherwise we're deviating from the standard pattern and I don't think we really have enough justification to do that.

**Comment by lognaturel** [comment]
In the spirit of freeing up brain cells for all of us, yes, let's go with it. Sorry for the back and forth, @grzesiek2010. I don't feel especially strongly and just want us to move on!

**Comment by grzesiek2010** [comment]
Ok my feelings are also not that strong to argue. Let's add this change.
