### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5050]
#### Software and hardware versions 
After Collect v2022.1

#### Problem description
Commits added after 2022.1 was released have increased the app size by 2mb (to 14mb).

My hunch is that this is because many of the modules are not minified. The recent changes pulled out a geo module which imports a lot of dependencies.

**Comment by seadowg** [comment]
> My hunch is that this is because many of the modules are not minified. The recent changes pulled out a geo module which imports a lot of dependencies.

Modules should not be minified (they should have `minifyEnabled false`). When you're building an APK you're compiling your app module (ours is `collect_app`) and then minification gets run on the output of that compilation ([example SO](https://stackoverflow.com/a/50819864/11400117)). It could be that we've broken that setup somehow or that our proguard rules are allowing something big to not get minified (moving things around could definitely exacerbate a wild card rule). Another possibility is that we've included some resources in the wrong place.

**Comment by seadowg** [comment]
After a `git bisect` it looks like the offending commit is 538e7c68f9408306bf691da1530a69122e2ed9d6. It's likely that something from `json-schema-validator` is the problem.

**Comment by seadowg** [comment]
Yup! Removing the `json-schema-validator` dependency but leaving the reset of the commit the same (other than commenting out the references to the library code) drops the APK size back down to 12.3MB.

**Comment by seadowg** [comment]
We get a much smaller increase (to 12.8MB) using https://github.com/networknt/json-schema-validator which is less popular but actually seems to be more up to date. Both libraries use Jackson, but it might be that this one is easier to minimize for some reason. I'll run tests etc with the new library to fully confirm it can be a drop-in replacement.

**Comment by lognaturel** [comment]
Aha, I clearly had some proguard misconceptions all around. Thanks for getting me untwisted! I am absolutely shocked that json schema validation could add 2mb to the app. Glad to hear there's likely a drop-in replacement.

Feeling very glad we decided to do an early beta. 👍

**Comment by seadowg** [comment]
Should have been closed by #5053
