### ISSUE TITLE
Upgrade Mapbox Telemetry

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5068]
There's a common crash in background for Android 11 and 12 caused by Mapbox Telemetry ([Crashlytics](https://console.firebase.google.com/u/3/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/d7915614a65b916b7ca2bb21f58b8098?time=last-seven-days&versions=v2022.1.2%20(4382)&types=crash&sessionEventKey=62376BB6016F000158798B3E452D7A52_1655689378786766287) (needs auth)).

A fix was released in [v7.0.3](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-7.0.3-core-4.0.2). I think we might be able to update to the latest ([v8.1.1](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-8.1.1-core-5.0.1)).

#4893 tracks upgrading Mapbox itself and we are not going to take any action on that now.

**Comment by grzesiek2010** [comment]
The newest version available on mvnrepository is 7.0.0 which we already use. Newer versions require using tokens in the same way like other mapbox projects so we can't even download the project from github and build on our own / add to own own (local) maven repository.

**Comment by lognaturel** [comment]
> Newer versions require using tokens

I don't believe that's the case. I've asked for clarification at https://github.com/mapbox/mapbox-events-android/issues/563. I believe we could build and include the libs ourselves if they can't be pushed to Maven Central for some reason. The license for those packages is MIT.

**Comment by lognaturel** [comment]
https://github.com/mapbox/mapbox-events-android/issues/563#issuecomment-1085688127

I think we should try to use our own build of 7.0.3. That should fix the crashes. If it’s easy we could also try the 8.x but seems more likely to have incompatibilities.

**Comment by lognaturel** [comment]
Talked to @seadowg and we'll punt on this until we figure out what to do about Mapbox longer term (https://github.com/getodk/collect/issues/4893)
