### ISSUE TITLE
Handle invalid geometries

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5075]
#### Software and hardware versions 
Collect v2022.1 and prior

#### Problem description
There are two overlapping problems:
- The `geometry` field is not validated prior to the corresponding choice being rendered. It could contain anything. We've seen crashes because of attempts to use geojson instead of ODK-formatted features, for example
- Mapbox and osmdroid crash when handed geometry that is out of bounds at least in the instance form map and possibly in other map uses. Google Maps appears to wrap around in the case of longitude and render off map in the case of latitude. This one may need to be spun off depending on where the proposed dialog described below is shown from.

#### Steps to reproduce the problem
The easiest is to use the select from map with a [form that has invalid points](https://docs.google.com/spreadsheets/d/1CDGcthyS7KJgnJikmJttLdwFS4xsSysDRuoxdVQS2zQ/edit?usp=sharing). You can also enter incorrect geometry (like `blah`).

#### Expected behavior

Shows a dialog (when points are invalid or geometry is invalid) that reads: "The choice with label <choice label> has invalid geometry (<geometry>)". Clicking OK returns to the form (from the dialog).

**Comment by lognaturel** [comment]
There’s a somewhat related issue at the poles: https://github.com/osmdroid/osmdroid/issues/1339#issuecomment-491519929

**Comment by seadowg** [comment]
Related to this we can also end up with `geometry` in an incorrect format (an example could be `0, 0, 0, 0`). We're seeing that appear in the wild in [this Crashlytics report](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/db72f993c1c08aa205771dfc1767bdbf?time=last-seven-days&versions=v2022.2.0%20(4418)&types=crash&sessionEventKey=625814AE002F00016447C11EC9338ADA_1664882394848775403).
