### ISSUE TITLE
Improve display of errors in landscape

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#5082]
#### Software and hardware versions 
Collect v2022.2 beta 2, Android vx.x.x, device used...

#### Problem description
The outcome of testing #5055  List of failure errors it not adjusted to landscape, see:
![Screenshot_20220404-121550](https://user-images.githubusercontent.com/33342488/161555398-b03736ba-5b95-4858-b138-23f492109c2b.png)

#### Steps to reproduce the problem
1. ex. show details of autosend failure notification
2. rotate device to landscape

#### Expected behavior
Error width should be adjusted to screen in landscape

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
@kkrawczyk123 Could you please link me to the form that leads to this error and/or give me a brief explanation of what's going on? I feel like we've run into something like it recently and I couldn't figure it out.

**Comment by kkrawczyk123** [comment]
@lognaturel It's just a simple random form. In this case, I was testing failing autosend by adding some random input to server URL, as it's visible in the error "308gjh" - that project does not exist on Central. Failing notifications are mostly tested by some weird changes to server URL, like adding or removing something.

**Comment by grzesiek2010** [comment]
Yeah there was a bug when I hardcoded short errors the list looked even worse:
![Screenshot_1649156699](https://user-images.githubusercontent.com/3276264/161747450-adfd4d1f-fefe-43fd-ae5e-86c1d0fdb974.png)

Fixed in https://github.com/getodk/collect/pull/5085

**Comment by lognaturel** [comment]
> "308gjh" - that project does not exist on Central

Aha, got it, thanks!
