### ISSUE TITLE
Replace deprecated getWidth and getHeight methods

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#511]
The `getWidth` and `getHeight` methods on `Display` are deprecated which results in compilation warnings. Replace all calls on `getWidth` and `getHeight` following the recommendation in the [API docs](https://developer.android.com/reference/android/view/Display.html#getWidth()). 

This should be submitted as a single pull request that ONLY makes this change.

**Comment by Bastiantheone** [comment]
@lognaturel can I work on this?
