### ISSUE TITLE
If blank form is missing from /odk/forms, remove it from DB

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#512]
When you push form to Collect's SD card (e.g., `adb push my_form.xml /sdcard/odk/forms`) and go to `Fill Blank Form`, the app scans the SD card and adds the form to the DB. It even updates the form title when you push a new form with new data. 

But when you remove the form, it does nothing. Instead, when you tap on the form, it shows you a form not found dialog. It would be nice if removing the form also removed the DB entry. But, there's probably a reason why it was left it in the DB...

**Comment by nribeka** [comment]
@yanokwa care to elaborate more on this?

**Comment by nribeka** [comment]
I will have a look at this one.

**Comment by lognaturel** [comment]
@nribeka First question is whether this is the right thing to do...

**Comment by nribeka** [comment]
The problem seems to be logical to me because it's a dangling / inconsistent state in the application data. This probably not gonna happen to a lot of users, but people who poke around the file system structure for odk would be affected.

**Comment by lognaturel** [comment]
Yes, true. I wonder what @yanokwa could have meant with his kind of ominous "But, there's probably a reason why it was left it in the DB..."

**Comment by yanokwa** [comment]
I said it ominously to spark a discussion. I agree with @nribeka that it is inconsistent and if we make it consistent and break some behavior down the line, we'll have this issue to document it.

**Comment by lognaturel** [comment]
Ok, sounds good. Do you think this might be a good one for a new contributor to take on? Perhaps @nribeka you could give a few hints on where to find the relevant code and we could mark it as contributor friendly? Maybe it's even a quick win?

**Comment by nribeka** [comment]
This could be a quick win too after looking at the code. On step two (from line 99 in DiskSyncTask.java), it's iterating all form records in the forms db, checking if the form file referenced in the db exists or not. If it's not exists in the sdcard, it's just logging a message right now when it should be deleting that record (or create a list of to be deleted record and do deletion afterwards).

**Comment by nribeka** [comment]
A refactoring is needed too since the variable name holding the form path is called sqlFilename & and sqlFile for the form's file object.

**Comment by icemc** [comment]
@yanokwa hi, I'm new to open source development but have some experience in android and databases. I will like to work on this issue.

**Comment by yanokwa** [comment]
@Icemc please give it a try

**Comment by srujanjha** [comment]
@yanokwa , @lognaturel , I want to work on this issue. Can I give it a try ?

**Comment by lognaturel** [comment]
@nribeka @icemc @yanokwa Should we do the same for instances? If an instance gets deleted on disk, you can still see it in the interface, edit it if it's editable, but then you can't save it. If you think it's worth doing, please file an issue!

**Comment by nribeka** [comment]
Good call @lognaturel. I think we should add that to the sync task too. 👍

**Comment by lognaturel** [comment]
@icemc If you'd like to take that one too, feel free to file the issue and start work on it!

**Comment by nribeka** [comment]
@lognaturel #625 created. @icemc, you can do that one as well.

**Comment by icemc** [comment]
@nribeka @lognaturel  sorry for not responding to your call. I was not feeling fine lately and was absent for a while. please let me know if the issue hasn't be taken yet. Thanks
