### ISSUE TITLE
Bump targetSdkVersion to API 31

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5129]
#### Problem description
Every year we have to bump the `targetSdkVersion` to [Meet Google Play's target API level requirement](https://developer.android.com/google/play/requirements/target-sdk).
Theoretically we can keep releasing new versions of our app till November with the current `targetSdkVersion` which is 30 but I think this year we should do that earlier becasue:
- I remember that last year we procrastinated and the conclusion was that next time we should do that earlier
- It's better to do that at the begging of a release cycle to have time to catch bugs that might occur 
- It might be better to do that now when @kkrawczyk123 is still available and can help @srujner with this crazy annual case where anything might be broken

#### Expected behavior
The app should work well with `targetSdkVersion` 31 with no bugs/crashes/regressions

#### Things to do:
- [x] Bump `targetSdkVersion` to 31
- [x] Explicitly declare the [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) attribute for components that should be exported https://developer.android.com/about/versions/12/behavior-changes-12#exported
- [x] Specify pending intents mutability https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
- [x] Double check toast text will fit https://developer.android.com/about/versions/12/behavior-changes-12#toast-redesign
- [x] Check behaviour of permissions and scheduled jobs (auto update, match exactly etc) when coming in and out of hibernation https://developer.android.com/topic/performance/app-hibernation#manually-invoke

@seadowg please when you are free also review the documentation https://developer.android.com/about/versions/12/behavior-changes-12 to make sure we do not miss anything obvious.

**Comment by seadowg** [comment]
We have another issue to cover the last point  for instrumentation tests (#4874), and I believe our Robolectric tests should switch with the target SDK, so I'll scratch that out.

**Comment by seadowg** [comment]
I've added a couple of things to the list. Looks like we might have to deal with hibernation 🥶

**Comment by grzesiek2010** [comment]
> We have another issue to cover the last point for instrumentation tests (https://github.com/getodk/collect/issues/4874), and I believe our Robolectric tests should switch with the target SDK, so I'll scratch that out.

I meant just doing that once for now to verify that everything is fine at least according to our tests what I've already done.

**Comment by grzesiek2010** [comment]
> Check behaviour of permissions and scheduled jobs (auto update, match exactly etc) when coming in and out of hibernation https://developer.android.com/topic/performance/app-hibernation#manually-invoke

permissions are reset, background jobs stopped. When you open the app again and exit the mode background jobs are rescheduled. 
It make sense and I don't think this is something we should car about now. In the doc they say:

> If your app only ever exhibits the behaviors described in the following list, your app enters hibernation **after a few months**

so it looks like the mode is enabled only if the app is not used indeed.

**Comment by seadowg** [comment]
> so it looks like the mode is enabled only if the app is not used indeed.

Right but if the `WorkManager` scheduled jobs are cleared we might restart the app after hibernation with something like auto send enabled but no longer scheduled right?

**Comment by grzesiek2010** [comment]
> Right but if the WorkManager scheduled jobs are cleared we might restart the app after hibernation with something like auto send enabled but no longer scheduled right?

I've just tested `match exactly` and after reopening the app the job was enabled and rescheduled so it works properly. `Auto send` is not a periodic job it's triggered when enabled in settings or when you save a form so it's not a good example here I think or maybe I'm missing something?

**Comment by seadowg** [comment]
> I've just tested match exactly and after reopening the app the job was enabled and rescheduled so it works properly. 

It works after the app is hibernated and then reopened? I'm not sure how that works as it seems from their docs like all our scheduled jobs get cleared. Not sure where in the code we reschedule other than when settings are imported or the relevant settings are changed.

> Auto send is not a periodic job it's triggered when enabled in settings or when you save a form so it's not a good example 

Sorry, yes that's true! Auto update/Match exactly are the better examples.

**Comment by grzesiek2010** [comment]
> It works after the app is hibernated and then reopened?

From my short testing what I've noticed is that jobs are canceled/stopped when the app enters the hibernate mode and then when you reopen the app it exits the mode and jobs are scheduled again with the same settings. It matches what they say in https://developer.android.com/topic/performance/app-hibernation#system-behavior-leave-hibernation probably it works out of the box because we use `WorkManager`.

**Comment by grzesiek2010** [comment]
> Double check toast text will fit

I verified that on Android 12 the icon is displayed properly. I don't remember any very long toasts that would take more than two lines so I think it doesn't make sense to review all possible toasts in the app, this is rather something the QA team should pay attention to during testing other stuff.

**Comment by seadowg** [comment]
> probably it works out of the box because we use WorkManager.

Ah, nice! I'd assumed they meant "it'll be easier to reschedule with WorkManager". I'm still not comfortable with how WorkManager scheduling works, but it sounds like we're covered in this case.
