### ISSUE TITLE
Remove redundant casts

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#513]
There are several redundant casts across the code base leading to compilation warnings that look like this:

````
/odk/collect/collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java:128: warning: [cast] redundant cast to Element
                Element xformElement = (Element) xformsElement.getElement(i);
````

Find all such instances and remove the redundant casts. This should be submitted as a pull request that ONLY makes this change.

**Comment by vikasdesale** [comment]
Can I work on this @lognaturel

**Comment by lognaturel** [comment]
@vikasdesale Please do!

**Comment by vikasdesale** [comment]
I have added PR.Please check @lognaturel.

**Comment by lokeshkvn** [comment]
@vikasdesale you had not removed all the redundant casts , @lognaturel I am working on this Issue assign it as ' in progress '

**Comment by lognaturel** [comment]
@lokeshkvn Please give @vikasdesale another day or two in case he would like to take it. It's still his issue until he says he doesn't want it or a few days pass!

**Comment by lokeshkvn** [comment]
Okay 👍

**Comment by vikasdesale** [comment]
Hi @lognaturel  
I have college work for past few day that's why I haven't completed it.but I will send PR till tomorrow evening. Is it OK for you?
sorry for the inconvenience.

**Comment by Ishmeetsingh97** [comment]
Hi, if its still open can i work on it ? @lognaturel

**Comment by shreyasnbhat** [comment]
@lognaturel 
I have identified about 11 typecasts that need to be removed.
I could send a PR.
Should I?

**Comment by lognaturel** [comment]
@vikasdesale We should move ahead on this. @lokeshkvn and @shreyasnbhat, you have both had a chance to get some quick wins merged so @Ishmeetsingh97 should go ahead. Thank you!

@Ishmeetsingh97 in your pull request, please describe how you made sure you handled all cases AND how you made sure it had no effect on behavior.
