### ISSUE TITLE
Styling error on required message after not entering required data

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5132]
**Software and hardware versions**

Collect current master, Android 10 and 11

**Problem description**
 During testing #5064 I noticed that in one form, when user do not provide required data and click on the next button, the toast message have styling issues.
 Form: 
[Soil_collect.xlsx](https://github.com/getodk/collect/files/8630845/Soil_collect.xlsx)

**Steps to reproduce the problem**
1. Open attached form
2. Go to the "Enter your current location's sample number" screen
3. Do not provide any data
4. Click on the "Next" button

**Expected behavior**

The toast message should be visible without any styling errors

**Other information**
**View on Android 11 Pixel device**
![Screenshot_20220505-134156](https://user-images.githubusercontent.com/85225519/166916905-b783dd35-72ef-44c2-bcfa-835f1c523334.png)

**View on Android 10 Xiaomi device**
![Screenshot_2022-05-05-13-26-44-700_org odk collect android](https://user-images.githubusercontent.com/85225519/166916913-13948bad-d684-4248-879d-f133d0de994b.jpg)

**Comment by lognaturel** [comment]
We don't support HTML in required or constraint messages so this is the expected behavior!

We're also going to be moving these messages inline soon.
