### ISSUE TITLE
Memory leak in application on Android 10 after toast message appears

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5134]
**Software and hardware versions**
Collect current master, Android 10, xiaomi device

**Problem description**
During testing #5128  I noticed leak in Canary Leaks application after toast message appears

**Steps to reproduce the problem**
1. Install ODK app and launch the app;
2. Select "Manually enter project details";
3. Configure by Google Drive;
4. Add account for ODK Collect;
5. Open Leaks application and navigate to the "Head Dumps" tab;
6. Click on the "Dump Head Now" button;
7. Wait for the analyzing head dump to finish.

**Expected behavior**
No leaks in application

**Other information**
Issue is not reproducing on Android 11
Found leak:
![Screenshot_2022-05-06-11-14-30-775_org odk collect android](https://user-images.githubusercontent.com/85225519/167117440-36883951-88f1-4ca4-a673-3a4f77242433.jpg)
![Screenshot_2022-05-06-11-14-33-596_org odk collect android](https://user-images.githubusercontent.com/85225519/167117452-5d2db6e4-0b2b-4f6e-8093-8872d06051fd.jpg)

**Comment by seadowg** [comment]
This flow isn't available in the app any longer so I'm closing this.
