### ISSUE TITLE
Redesign selection summary sheet

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5136]
~~Blocked by #4943~~

The summary sheet should be redesigned to look like this when it's fully expanded:

<img width="352" alt="Screenshot 2022-06-03 at 10 27 16" src="https://user-images.githubusercontent.com/556280/171828028-43fc11b8-c0c2-47c6-bc3e-f298439d1bb7.png">

In addition:

* There should be a divider between each property 
* Clicking on an item on the map should open the bottom sheet ["collapsed"](https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior#STATE_COLLAPSED) and the peek height (the lowest part shown) should be:
    * the bottom of the only property for items with a single property
    * the middle of the second property for items with multiple properties

**Comment by lognaturel** [comment]
Super small nit: I believe the horizontal rule is intended to be more subtle.
