### ISSUE TITLE
Let color of activities be set by the operating system

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#514]
In the current builds of Collect, screens like the Main Menu are light gray (`#ededed`), while screens like `Send Finalized Forms` when blank and `Get Blank Form` are white (`#ffffff`). 

This difference in coloring is likely because the gray color is set by the OS while the white color is set by the application. 

I propose we remove the explicit setting of white and have the OS set the default color.

**Comment by lognaturel** [comment]
Makes sense to me.

**Comment by getsanjeev** [comment]
I would like to fix it. @yanokwa

**Comment by yanokwa** [comment]
@getsanjeev It's yours!

**Comment by getsanjeev** [comment]
@yanokwa what exactly do you mean by 'screen main menu is gray'. I see that background is white(default) and buttons are gray(default).

**Comment by yanokwa** [comment]
@getsanjeev You can see the differences here. This is master running in a Android 7.1.1 emulator.

![grey](https://cloud.githubusercontent.com/assets/32369/23629537/04ef013a-0286-11e7-8107-44ed21715324.png)
![white1](https://cloud.githubusercontent.com/assets/32369/23629535/04ec9148-0286-11e7-92e6-5636425b4f56.png)
![white2](https://cloud.githubusercontent.com/assets/32369/23629536/04eedaca-0286-11e7-888a-80a9375b00d9.png)

**Comment by nribeka** [comment]
I think if we could add theme, that would be nice. At least dark and light theme 👍

**Comment by yanokwa** [comment]
@nribeka That's a ✨great✨ idea. Please open another issue with this suggestion. My guess is that'll have to come after the UI refresh (#464)

**Comment by lognaturel** [comment]
@nribeka @getsanjeev This change should make sure that the background color used across the app is the default background color for the current theme. That will make it easier to add themes in the future (#528). In other words, don't hardcode the color to #EDEDED, please!

**Comment by getsanjeev** [comment]
@lognaturel I just need to remove two lines where colors have been explicitly set to WHITE(one in list getlistview.setbackground(WHITE) & other in text box android : backgorund  = '#FFF'). I guess thats what you mean.

**Comment by lognaturel** [comment]
@getsanjeev That seems right!

**Comment by lognaturel** [comment]
This actually affects a lot of components that are overriding the theme defaults. For example:
<img width="244" alt="screen shot 2017-03-07 at 8 32 05 pm" src="https://cloud.githubusercontent.com/assets/967540/23686019/2c1564b2-0375-11e7-9f59-38a21ace7026.png">

Reached from this button:
<img width="40" alt="screen shot 2017-03-07 at 8 32 40 pm" src="https://cloud.githubusercontent.com/assets/967540/23686032/3e9c9c4a-0375-11e7-8370-f7be7aaff01c.png">

Or this mess in the Birds form:
<img width="241" alt="screen shot 2017-03-08 at 10 30 31 am" src="https://cloud.githubusercontent.com/assets/967540/23710318/4d4576a2-03ea-11e7-87f9-e70c7bd764ef.png">

A quick search for `setBackgroundColor` suggests there are a lot of places this happens. Doing this completely will require a careful check of each screen it affects.

@getsanjeev perhaps you want to take the rest of it? Or @UrjaPawar? Please comment if you're taking it on and I'll tag as 'in progress'!

**Comment by lokeshkvn** [comment]
@lognaturel 
I want to work on this issue , Tag it as 'in progress'

**Comment by lokeshkvn** [comment]
Now the problem in birds form is solved ,
 
![device-2017-03-08-222443](https://cloud.githubusercontent.com/assets/16884938/23714270/9c1e17b6-044e-11e7-9c89-e85926b14915.png)

Now Checking for other components 😃

**Comment by getsanjeev** [comment]
@lognaturel I am working on other issue. Let someone else take it further. Thanks.
