### ISSUE TITLE
Problems with creating files on device storage

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5145]
#### Problem description
We have been receiving reports about problems with accessing app directory which we use to save files. In v2022.2.2 we added more logs and here are the results:

- [open failed: EACCES (Permission denied) | No such file or directory | Operation not permitted | open failed: EROFS (Read-only file system) | Permission denied](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4ff8a6e3b84fc921539f2592eba88c84?time=last-seven-days&versions=v2022.2.2%20(4437)&types=crash&sessionEventKey=6283DE3D00B000010624EAA39C8B8CE8_1677207395531930656)
- [External files dir is null!](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/535e9fed953082e894f6263be94462b0?time=last-seven-days&versions=v2022.2.2%20(4437)&types=crash&sessionEventKey=628752C902DE00011E60B926C195CE47_1678179966787820882)
- [External files dir does not exist: /storage/emulated/0/Android/data/org.odk.collect.android/files](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/a8eebdc52ac37e3c247a8fc13cc8d3d0?time=last-seven-days&versions=v2022.2.2%20(4437)&types=crash&sessionEventKey=62811BE302EB00012DE6191AA7D0D4D5_1676430775496630780)

@kkrawczyk123 was able to reproduce one of those issues (see https://forum.getodk.org/t/can-t-create-directory-and-application-crashes/36583/15?u=grzesiek2010)
I took that device from here so I can take a look at it to see if there is anything we can do.

**Comment by grzesiek2010** [comment]
I Was able to reproduce the issue with these logs:

```
Caused by: java.lang.IllegalStateException: App can't write to external files dir: /storage/emulated/0/Android/data/org.odk.collect.android/files
        at org.odk.collect.androidshared.system.ExternalFilesUtils.testExternalFilesAccess(ExternalFilesUtils.kt:26)
        at org.odk.collect.android.application.Collect.onCreate(Collect.java:143)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
        at android.app.ActivityThread.access$1400(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5298) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
     Caused by: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at org.odk.collect.androidshared.system.ExternalFilesUtils.testExternalFilesAccess(ExternalFilesUtils.kt:18)
        at org.odk.collect.android.application.Collect.onCreate(Collect.java:143) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5298) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
```

I'm going to dig deeper now.

**Comment by grzesiek2010** [comment]
W have had collected a few different crash causes but I was focused on `Permission denied` which I was able to reproduce too. Maybe other causes are also related but different devices just throw different exceptions, who knows.

I've read the documentation about storage to make sure we do not miss any permissions or something and it seems like we do not. Everything seems fine...
I think the reason of at least part of the reports is connecting devices to computers via USB. I've seen answers on Stackoverflow like:
- https://stackoverflow.com/a/13450208
- https://stackoverflow.com/a/13569364
- https://stackoverflow.com/a/24842735
- https://stackoverflow.com/a/26505238

This is kind of what I've experienced too. When I had the problem with installing ODK Collect from Play Store I unplugged it from my computer and rebooted then it worked well. However this does not solve our problem.

I've noticed one interesting thing. If I add `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` to the Manifest file it solves the problem and I can install the app without any problems. This is weird because the documentation in https://developer.android.com/training/data-storage explicitly says that:

> if your app targets Android 11 (API level 30) or higher, the WRITE_EXTERNAL_STORAGE permission doesn't have any effect on your app's access to storage.

so this looks like a bug in some Android versions or maybe implementations for particular vendors?

@lognaturel @seadowg do you think it's a good idea to have a point release with that extra permission to check if it has any effect?

**Comment by seadowg** [comment]
> which I was able to reproduce too.

> I've noticed one interesting thing. If I add <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> to the Manifest file it solves the problem and I can install the app without any problems.

What steps do you need to run through to reproduce?

**Comment by grzesiek2010** [comment]
Just install the app via usb (it can be master but that does not matter). You might need to switch to `selfSignedRelease`.
But I doubt you will be able to do that. It happens only on one device that I took from @kkrawczyk123

**Comment by lognaturel** [comment]
> this looks like a bug in some Android versions or maybe implementations for particular vendors

Seems like a reasonable hypothesis.

> add <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> to the Manifest

Is there a downside to this? We can request it from the user only as a fallback, right? That is, most users wouldn't be prompted to give the permission, only those for whom access to our external folder fails?

**Comment by grzesiek2010** [comment]
> Is there a downside to this?

The only thing I can think of is that Google Play might not like it somehow since the doc says it does not change anything.

> We can request it from the user only as a fallback, right? That is, most users wouldn't be prompted to give the permission, only those for whom access to our external folder fails?

No because I do not request that permission like we used to do in pre-scoped storage versions displaying a dialog. I just added it to the manifest and that's it it somehow fixed my problem. So no one will be prompted to grant it.

**Comment by seadowg** [comment]
> The only thing I can think of is that Google Play might not like it somehow since the doc says it does not change anything.

I believe it will show up on the Play Store in "App permissions" although I'm not sure what the text would be. Most likely "modify or delete the contents of your shared storage" which we currently don't have (look at SyncThing's [manifest](https://github.com/syncthing/syncthing-android/blob/main/app/src/main/AndroidManifest.xml) and [Play Store page](https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid&gl=US) for instance. @lognaturel I think you could probably build an APK and upload to the Play Store (without releasing) as an experiment as I believe it will warn you if you're adding permissions.

> When I had the problem with installing ODK Collect from Play Store I unplugged it from my computer and rebooted then it worked well. However this does not solve our problem.

If this is an error on a small number of devices (it sounds like a bug in their OEM code), and if rebooting solves it, could we just throw up an error message telling the user to reboot their device?

**Comment by lognaturel** [comment]
A few misc observations about the general inability to access the external files dir:
- 47% of affected devices are TECNO, 10% HUAWEI. 34 other manufacturers have smaller incident counts
- 68% of affected devices run Android 7. It also happens on all other Android versions including Android 12 but at much lower frequency
- 66% of devices are in background when this happens
- Not related to the permissions issue @grzesiek2010 is tracking but [this Stackoverflow post](https://stackoverflow.com/a/33388603/137744) has interesting info about how external files dir works and why it might not for some devices

I've tried installing a self-signed release build on my Android 5.1.1 Galaxy Tab A while connected to USB. That works fine. Not too surprising -- Samsung devices account for 4% of the related crashes despite being popular.

I've added `WRITE_EXTERNAL_STORAGE` to the manifest and pushed an internal testing version to the Play Store. This didn't give any warnings though the Play Store does detect and list the new permission. I tried going down the release track path and got "Users that have the APK with version code 4437 may need to accept the android.permission.WRITE_EXTERNAL_STORAGE permission, which may result in them not upgrading to this version of the app." Soft warning that's collapsed by default.

**Comment by seadowg** [comment]
> Not related to the permissions issue @grzesiek2010 is tracking but [this Stackoverflow post](https://stackoverflow.com/a/33388603/137744) has interesting info about how external files dir works and why it might not for some devices

This is fascinating. I was confused as to how this could be an OEM issue and this seems to explain it. I'm still unclear on why the OS can't manage this itself (and not need an OEM to configure it) but that's not something we can change.

> I tried going down the release track path and got "Users that have the APK with version code 4437 may need to accept the android.permission.WRITE_EXTERNAL_STORAGE permission, which may result in them not upgrading to this version of the app." Soft warning that's collapsed by default.

I haven't had a chance to check this as I don't have my test device with me, but the other thing to check would be whether this results in an extra permission being displayed in the Play Store to users (I'd expect "modify or delete the contents of your shared storage" to appear).

**Comment by grzesiek2010** [comment]
I've just tested the beta version from @lognaturel and it seems to work:
1. I installed current master branch via Android Studio - `CRASH`
2. Then I installed the version from Play Store available for all users - `CRASH`
3. Then I installed the one which contains that weird fix and everything was `FINE`

When it comes to permissions I've noticed a small difference on one of tested devices (in Storage there is one more point):
| v2022.2.1  | beta with the fix |
| ------------- | ------------- |
| ![perm2](https://user-images.githubusercontent.com/3276264/170696161-05429395-8eae-4dec-b743-4735a9488695.png)  | ![perm1](https://user-images.githubusercontent.com/3276264/170696165-32f3c98f-acf1-4aeb-8a70-707b66d6406f.png) |

**Comment by seadowg** [comment]
I really wish we'd spotted this when removing `WRITE_EXTERNAL_STORAGE` so we didn't have to think about adding the extra permission back. I think I'm leaning towards doing a release with `WRITE_EXTERNAL_STORAGE` for now and thinking about an error message in the future. 

I am worried that long term, this could come back to bite us (they could deprecate remove/the permission for example), so I do think we should make sure to file an Android issue with these findings. It looks like there was a [closed issue](https://issuetracker.google.com/u/1/issues/37068115) that describes similar problems. @grzesiek2010 can you please create a new issue referencing that old one, this PR and with the details of the device and reproduction steps you have?

**Comment by grzesiek2010** [comment]
> I think I'm leaning towards doing a release with WRITE_EXTERNAL_STORAGE for now and thinking about an error message in the future.

I agree we are going to have a point release for https://github.com/getodk/collect/issues/5147 either way so It's a good opportunity to check this one.

> @grzesiek2010 can you please create a new issue referencing that old one, this PR and with the details of the device and reproduction steps you have?

Yes I can do that but maybe when we release a new version with that fix so that we have confirmation that it really works for other users too.

**Comment by seadowg** [comment]
> Yes I can do that but maybe when we release a new version with that fix so that we have confirmation that it really works for other users too.

Great idea!

**Comment by grzesiek2010** [comment]
Ok so I've created a pr for the hotfix https://github.com/getodk/collect/pull/5150

**Comment by seadowg** [comment]
We're still seeing the related crashes in production (both in the current release and the beta release), so I'm reopening this.

We discussed looking at adding a global "catch all" error dialogue on crashes to counter this and #4108.
