### ISSUE TITLE
Clicking "Save as draft" when "Moving backwards" is disabled creates inaccessible submissions

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5148]
#### Software and hardware versions 
Collect v2022.2.2+

#### Steps to reproduce the problem
1. In protected Form Entry Settings, uncheck Moving backwards. 
1. Accept the suggested other setting changes.
1. Fill out a form
1. Click "Save as draft" on the end screen
1. See that the filled form is inaccessible

#### Expected behavior

The Moving backwards setting should also uncheck "Save as draft" (in the "Form End" section) to force finalization.

**Comment by grzesiek2010** [comment]
@lognaturel @seadowg now the description is outdated and we don't have that checkbox but should we hide the 'Save as draft' option from the end screen? The result would be the same `the filled form is inaccessible`

**Comment by seadowg** [comment]
I've updated this, and also added it to v2023.2 as it would be good to clean this up before general release.
