### ISSUE TITLE
Can't start external app on android 11+

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5157]
#### Problem description
Can't start external app on android 11+
The problem has been originally reported on the forum: https://forum.getodk.org/t/external-app-doesn-t-opening/37644

#### Steps to reproduce the problem
1. Install https://play.google.com/store/apps/details?id=com.peace.ArMeasure&hl=de&gl=US
2. Test the attached form on android 11+ [exApp.xlsx](https://github.com/getodk/collect/files/8823956/exApp.xlsx)

**Comment by seadowg** [comment]
Going to move this into Hotfix as it could be serious for some projects. 

Do @getodk/testers have an Android 11 device? It feels like we must have a gap in our testing (automated and manual) for this to get through.

**Comment by grzesiek2010** [comment]
> Going to move this into Hotfix as it could be serious for some projects.

I was just going to say the same.

> Do https://github.com/orgs/getodk/teams/testers have an Android 11 device? 

Yes we have and we are able to reproduce the issue I described. 

> It feels like we must have a gap in our testing (automated and manual) for this to get through.

It seems like we don't test cases like that (staring any app) we rather test staring apps that export activities like https://github.com/getodk/counter

**Comment by grzesiek2010** [comment]
> It seems like we don't test cases like that (staring any app) we rather test staring apps that export activities like https://github.com/getodk/counter

and testing cases like that is not something easy for QAs. They never know if a given app exports activities or if we start it by its package name. I think it would be good to create a special app for them for testing + a form to verify we can start it by its package name + using exported activities + using intent filter signatures. 
I you agree I'm going to do that.

**Comment by seadowg** [comment]
> It seems like we don't test cases like that (staring any app) we rather test staring apps that export activities like https://github.com/getodk/counter

Ah wait, so this is only a problem if the Activity being opened isn't exported (as in it doesn't have `exported=true` in its `activity` block)? I'm confused as I assumed that if an Activity wasn't exported, then it couldn't be launched by any other application? I'm guessing I'm missing something here.

**Comment by grzesiek2010** [comment]
> Ah wait, so this is only a problem if the Activity being opened isn't exported (as in it doesn't have exported=true in its activity block)? I'm confused as I assumed that if an Activity wasn't exported, then it couldn't be launched by any other application? I'm guessing I'm missing something here.

Yes this issue is not about staring any activity (then you are right exporting would be required) but staring launcher activities that have:
```
       <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
```

I believe it should be possible to do that and it worked before it stopped working in android 11+ so I fixed it.
