### ISSUE TITLE
Add preference for instance sync task

### ISSUE THREAD

**Issue by nribeka** [getodk/collect#516]
Currently the instance async task default the synced form instances InstanceProviderAPI.STATUS_COMPLETE as the status. I think we want to give the user the preference to sync it as either complete or incomplete.

The preference I think should be a boolean and apply this value to the InstanceSyncTask.

**Comment by yanokwa** [comment]
This preference should also be hidable in Admin Preferences.

**Comment by dcbriccetti** [comment]
To whoever does this: The hiding is now done using an array in `AdminKeys.java`: `adminToGeneral`.

**Comment by shobhitagarwal1612** [comment]
@yanokwa I would like to handle this issue.

**Comment by yanokwa** [comment]
@shobhitagarwal1612 Please start when #485 is merged.
