### ISSUE TITLE
Placement by tapping doesn't work for OSM for GeoTrace and GeoShape widgets

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5168]
**Software and hardware versions** 
Collect v2022.3, Android probably all

**Problem description**

In Geoshape widget and Geotrace widget placement by tapping doesn’t work for OSM. User is not able to set points on the map by tapping in Collect v2022.2.3. 
With OSM placement by tapping works in Collect v2022.2.3. 

**Steps to reproduce the problem**

1. Select OSM as a source of maps
2. Open form with Geo widgets
3. Go to Geotrace widget / Geoshape widget
4. Hit Start
5. Add points by method input- placement by tapping
6. Hit start
7. Tap on the map

**Expected behavior**

User is able to set points on map by tapping.

**Other information** 

Checked on All widgets form. Geoshape and Geotrace works on Google Maps.

https://user-images.githubusercontent.com/56479916/175320705-81dcb69e-f1fd-4d74-8fd8-556a7518d4b1.mp4

**Comment by lognaturel** [comment]
This also feels like a good candidate for squeezing into this release or including in the point release. It’s been released but not for that long.

**Comment by dbemke** [comment]
@seadowg  I think I’ve just found a mistake that I made. I’ve checked that again and (OSM) placement by tapping works well on Android 11 and 8.1 in Collect v2022.2.3. In the video there is Collect v2022.3 beta 0 so this might be regression?

**Comment by seadowg** [comment]
@dbemke yeah if this worked in v2022.2.3 (the last released version) it should be a regression. Could you update the description with that new info and add the "regression" label to this issue please?
