### ISSUE TITLE
It is possible to add a project without setting current project id

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5176]
#### Problem description
It is possible to add a project without setting current project id what causes crashes. It happens when a QR code does not contain project details so they need to be generated based on URL but the URL is invalid.
**IMPORTANT**: We already check URLs so not all types of error cause the issue but for example a URL like: `https:\/\/demo.getodk.org` does

#### Steps to reproduce the problem
1. Try to scan this qr code: 
![settings](https://user-images.githubusercontent.com/3276264/177504047-a6f249d2-8dd2-4eda-a0db-eae7b27407eb.png)
2. The first attempt will result with a message that the qr code is invalid
3. The second attempt will result with the `Duplicate Project` dialog - Select the first option (adding a duplicate project)

The same is possible when loading a QR code from a file (also two attempts are needed).

#### Expected behavior
The project should be added properly with no crashes. Even though the URL is invalid it should be imported so that a user can fix it in the app.

**Comment by dbemke** [comment]
I also experienced this while creating QR code with different settings. Steps to reproduce where the same but in first attempt of  scanning the QR there were both messages: qr code is invalid and choice to add duplicate project or switch to existing project. 
Clicking add duplicate closes the app. Clicking switch to existing project, goes back to previous project but name of the project and letters in the icon disappears.

**Comment by lognaturel** [comment]
Is this likely to explain [this Crashlytics report](https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8d842445557fcf3942b4e99ba2f89aec?time=last-ninety-days&types=crash&sessionEventKey=62C64C2A033400015E5E410BADE4B60A_1695905622417877922)?

**Comment by grzesiek2010** [comment]
> Is this likely to explain [this Crashlytics report](https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8d842445557fcf3942b4e99ba2f89aec?time=last-ninety-days&types=crash&sessionEventKey=62C64C2A033400015E5E410BADE4B60A_1695905622417877922)?

Logs are the same but I can't be sure if my steps is the only way to reproduce it. It might be the same crash that is a result of a few different bugs.

**Comment by seadowg** [comment]
> Is this likely to explain [this Crashlytics report](https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8d842445557fcf3942b4e99ba2f89aec?time=last-ninety-days&types=crash&sessionEventKey=62C64C2A033400015E5E410BADE4B60A_1695905622417877922)?

Yes! I think if you can add a project without setting an ID. The easiest way to do this is with project details that throw an exception during import which causes the whole creation process to exit early and not clean up properly. Then, if you reopen the app, it will take you to the `MainMenuActivity` because there are projects. Does that sound correct @grzesiek2010? 

I think making sure project creation is always cleaned up when a problem occurs (like I describe in https://github.com/getodk/collect/pull/5154#issuecomment-1178752812) should hopefully tackle this.

**Comment by grzesiek2010** [comment]
> Does that sound correct @grzesiek2010?

Yes.

The case described in this issue is already fixed in https://github.com/getodk/collect/pull/5154 but I wanted add `try-catch` to catch anything that might be thrown during importing settings to avoid other similar issues like that.
