### ISSUE TITLE
In OSM clicking View or Change Geotrace/Geoshape, after having saved a few points with manual location recording, zooms to a wrong place

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5184]
**Software and hardware versions** 

Android all

**Problem description**

In OSM clicking View or Change Geotrace/Geoshape after having saved a few points in manual location recording way, zooms to some continent view ( not to location).

**Steps to reproduce the problem**

1. Choose OpenStreetMap in settings as a source of maps.
2. Open All widgets form.
3.  Go to Geoshape/Geotrace widget.
4. Click on adding location button and choose manual location recording.
5. Click start.
6. Add a few points.
7. Click save.
8. Click View or Change Geotrace/Geoshape.

**Expected behavior**

Map is zoomed to the place where the points were added.

**Comment by seadowg** [comment]
Not able to reproduce this. It also zooms to the recorded points for me. Do the points have to be far from current location or something?

**Comment by dbemke** [comment]
@seadowg I recorded a video to show the zoom( video with fake gps but work the same without it) . I was thinking that after going back to map it should zoom in.

https://user-images.githubusercontent.com/56479916/180249122-f4000d21-0e9d-4fd7-833b-ea9a5c5a6eca.mp4

**Comment by seadowg** [comment]
@dbemke does this happen on multiple devices?

**Comment by dbemke** [comment]
@seadowg Now I've checked again Android 11, 8.1 Collect v 2022.3 Beta 2  and on Android 11 Collect v2022.2.3 and in all cases result is like the one this video.

**Comment by seadowg** [comment]
@srujner are you able to reproduce this as well?

**Comment by srujner** [comment]
@seadowg I checked on current Master and I wasn't able to reproduce this issue on Android 12 and 13, but then I checked the store version (2022.3.5) where the issue with removing points in GeoShape widget still exists and I could reproduce it in GeoShape on 12 and 13. @dbemke can You check once again in a free time on current master?

**Comment by dbemke** [comment]
on master 31897362c00974e7df889ef685337244f0ac5604 on Android 8.1, 10 the issue doesn't occur

**Comment by lognaturel** [comment]
> on master https://github.com/getodk/collect/commit/31897362c00974e7df889ef685337244f0ac5604

Ahh, great idea putting the commit hash. We should probably do that in addition to saying `master` so it continues being useful in the future.

Great to see that it's fixed. 👍
