### ISSUE TITLE
Zoom button to added points in map-internal-select form used with Google maps doesn’t show the whole point marker

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5185]
**Software and hardware versions** 

Collect v2022.3 22-g2b824ba182
Android 5.1, 10, 11, 12

**Problem description**

After clicking button zoom to all points in map-internal-select form used with Google maps, points are shown exactly at the edge of map so the user is able to see just a small part of those points.

**Steps to reproduce the problem**

1. Select Google maps as a source of maps
2. Open map-internal-select form
[map-internal-select.xml.txt](https://github.com/getodk/collect/files/9102011/map-internal-select.xml.txt)
3. Click select place
4. Click view all points button

**Expected behavior**

User is able to see points on the map.

**Comment by seadowg** [comment]
I'm not able to reproduce this:

![signal-2022-07-21-134338](https://user-images.githubusercontent.com/556280/180216338-6eeb1dde-1eb4-4946-b0e4-f496966d43cb.png)

Is it only on a specific device you're seeing it?

**Comment by lognaturel** [comment]
I've seen this on one of my devices as well. I figured it was some edge case and I'm not too worried about it.
