### ISSUE TITLE
Allow sorting blank forms by last saved

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5195]
As discussed [on the forum](https://forum.getodk.org/t/possibility-to-order-the-form-list-following-the-number-of-submission-most-used-on-top-in-collect/36524/6)

## Acceptance

- [ ] Given I have more than one blank form
And have recently filled one of them out (but not the others)
When I go to Fill Blank Form
And change sort order to "Last saved first"
Then the form I recently filled out moves to the top

- [ ] Given I have more than two blank forms
And I fill one out and then another
When I go to Fill Blank Form
And change sort order to "Last saved first"
Then the form I most recently filled out moves to the top
And the form I filled out before that is second in the list

**Comment by lognaturel** [comment]
Just realized we also need to break ties which will be particularly common when no submissions have been filled in. How about based on last **form definition** update time? I think the other sensible option is alphabetically. I don't have strong feelings either way, let's just make sure to document which it is.

**Comment by seadowg** [comment]
> Just realized we also need to break ties which will be particularly common when no submissions have been filled in. How about based on last form definition update time?

I was imagining that it would be a stable sort so that items equal items stay in their original order (as that's what Java/Kotlin's sorting algorithm will give us) and that we wouldn't have "fallback" ordering. However, I don't feel like it matters if it's stable or unstable from reading the forum discussion?

**Comment by lognaturel** [comment]
> stay in their original order 

I imagine that would be by db id and so probably equivalent to form def update time. I think the most important thing is that it's explainable. Some users may have forms that don't have submissions for a while and so knowing how they're going to be ordered is helpful, I think. Maybe we don't worry about that for now and either document what we get by default or consider changing it if we find it doesn't really make sense.

**Comment by seadowg** [comment]
> Maybe we don't worry about that for now and either document what we get by default or consider changing it if we find it doesn't really make sense.

Agreed. I was thinking we'd only need to document that the forms will be sorted by their last saved instance time and not mention what happens with forms that have equivalent or no last saved time. My assumption would be that equivalent last saves are pretty much impossible (you can't save two forms at once) and that forms with no last saved time would quickly gain one or not be very important?

**Comment by lognaturel** [comment]
> forms with no last saved time would quickly gain one or not be very important

OK, maybe you're right. I've been talking to folks with a LOT of forms recently so that has certainly affected my outlook. Let's start there, anyway, and we can see whether that's sufficient!
