### ISSUE TITLE
The settings contained in the form do not have higher priority than the settings from the app. 

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5198]
**Software and hardware versions**

Android 10 and 11

**Problem description**

The application settings are more important than the form settings.

**Steps to reproduce the problem**

1. Download attached forms or scan QR code;
2. Go to the Project Settings and set: Auto Send - Off; Delete after send - Off; 
3. Open and send form "Auto-Submit_True_Auto-Delete_True";
4. Form should be auto sent and removed from device. 
5. Go to the Project Settings and set: Auto Send - On; Delete after send - On; 
6. Open and send form "Auto-Submit_False_Auto-Delete_False";
7. Form should needs to be manually selected to send. 

**Expected behavior**
The settings contained in the form should have higher priority than the settings from the app. 
[Auto-Submit_True_Auto-Delete_True.xml.txt](https://github.com/getodk/collect/files/9157775/Auto-Submit_True_Auto-Delete_True.xml.txt)
[Auto-Submit_False_Auto-Delete_False.xml.txt](https://github.com/getodk/collect/files/9157778/Auto-Submit_False_Auto-Delete_False.xml.txt)

![Screenshot(13)](https://user-images.githubusercontent.com/85225519/180172606-671cb20b-b6c5-48ce-b277-a3b088829b14.png)

**Comment by grzesiek2010** [comment]
@srujner those are old forms and they use outdated attribute names. Instead of `auto-submit` it should be `auto-send`. We changed it in https://github.com/getodk/collect/pull/1953. Please verify that after updating that attribute name in the form everything is fine. If so just close the issue.

**Comment by srujner** [comment]
@grzesiek2010 You were right, I updated the forms with auto-send attribute and everything works fine. I've already changed the test steps so there won't be any misunderstandings in the future.
