### ISSUE TITLE
Stop using `WeakReference` in `BaseLocationClient`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5208]
When using the [Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern), storing observers (or listeners) using Java's `WeakReference` removes any guarantees that the observer is notified (a listener is called) but does introduce the advantage of not having to explicitly unregister an observation. In a lot of cases, the hidden detail of the former is actually completely undesired, even if the latter is useful. This is certainly the case for `BaseLocationClient` - storing the `LocationClientListener` as a `WeakReference` can result in cases where it is never called (if it is an anonymous object for instance). 

We should switch to using a direct reference for the `LocationClientListener` and manually unregister it in calling classes instead of relying on `WeakReference`.

As a side note, we should probably avoid `WeakReference` as much as possible. It always seems like such a good idea, but anonymous objects and lambdas mess up the expected memory behaviour very subtely. I have been fooled by this more times than I'm comfortable with.

**Comment by lognaturel** [comment]
Agreed in principle about avoiding `WeakReference`. I believe the original source of that one was https://docs.mapbox.com/android/core/guides/#requesting-location-updates Now the code has changed quite a bit so hopefully there is a straightforward path to explicitly unregister (I haven't looked).

https://github.com/getodk/collect/blob/249f2b1e228001125dbac65521f344f9ea6ba888/location/src/main/java/org/odk/collect/location/LocationClient.java#L47 will need to be updated I think.
