### ISSUE TITLE
Change deprecated method getDrawable

### ISSUE THREAD

**Issue by vikasdesale** [getodk/collect#522]
There are several uses of deprecated method getDrawable across the code base leading to compilation warnings that look like this:

     warning: [deprecation] getDrawable(int) in Resources has been deprecated
     marker.setIcon(getResources().getDrawable(R.drawable.ic_place_black_36dp));

change this methods.

**Comment by vikasdesale** [comment]
Can I work on these issues of deprecated methods uses across the code base @lognaturel

**Comment by lognaturel** [comment]
@vikasdesale Yes, this is a good one to update as well as it will make the introduction of different themes easier.

**Comment by vikasdesale** [comment]
Please review @lognaturel.I have created PR for this issue.
