### ISSUE TITLE
Deleting added points is Geoshape/ Geotrace used with OSM doesn’t remove lines connecting points

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5224]
**Software and hardware versions** 

Collect v2022.3 beta 2, Android probably all

**Problem description**

In Geoshape and Geotrace widget used with OpenStreetMap after deleting already added points by manual lodation recording, placement by tapping or automatic location recording points disappear, the number of points is reduced to zero but the line connecting the points is not removed.
If the user clicks save button and then goes back to Geoshape/ Geotrace the line is no longer on the map. 

https://user-images.githubusercontent.com/56479916/181520311-4346a5c9-f416-458d-a09f-5d53e2ab6c56.mp4

**Steps to reproduce the problem**

1. Choose OpenStreetMap as a source of maps.
2. Go to All widgets form.
3. Go to Geotrace/ Geoshape.
4. Start Geotrace/ Geoshape.
5. Click add points button.
6. Choose manual location recording, pacement by tapping or automatic location recording.
7. Add a few points.
8. Click pause.
9. If added points are very close to each other, manually move one of the points so that you can see a line connecting points.
10. Click delete button.
11. Choose „clear” in the dialogue.

**Expected behavior**

After deleting points, the points should be removed: number of points entered should be 0, points and connecting lines should disappear.

**Other information** 

In Collect v2022.2.3 works as expected.

**Comment by seadowg** [comment]
Whooops. Closed by mistake.
