### ISSUE TITLE
Debug builds have log of form added and removed via disk sync

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5230]
Each log line should have the format:

```
<timecode>,<FormSyncAdd/FormSyncRemove>,<project id>,<form id>,<form version>
```

An example for removing a form that was deleted on disk from the demo project would be:

```
2022-08-01T19:38:11Z,FormSyncRemove,DEMO,all-widget,7
```

The log should be saved to disk in ODK's root (user visible) directory as `debug.csv`.

**Comment by seadowg** [comment]
@lognaturel this is actually feeling a little contrived to me. Maybe we just start with https://github.com/getodk/collect/issues/5231?

**Comment by lognaturel** [comment]
Yes, agreed! I think the log is a good idea but it's not the primary focus, getting some feedback on entity creation is. So I think we can do #5231 pretty ad-hoc (maybe using `Timber.i` initially) and then decide whether we want to structure it and have a log.
