### ISSUE TITLE
Make it clearer when "Ignore changes" will delete instance

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5232]
~~Blocked by #5391~~

Collect automatically creates "save points" for form that are automatically reloaded when filling a new instance of a form in. These save points get cleared once the form is saved by the user (through the save and exit button, the top right save button or the back button save). This can create confusing scenarios where it's unclear what "Ignore Changes" (the other option when hitting back) actually does. To remedy this, we want to change the "Ignore changes" button to read "Discard form" when filling out a new form from scratch or from a save point.

## Acceptance

- [x] Given I'm filling in a new form
When I press the back button
And I click "Discard form"
Then I am returned to the main menu
And no new saved form has been created

- [x] Given I'm filling in a new form
When I force stop the app
And then open the app again
And I open the same form again from Fill Blank Form
And I press the back button
And I click "Discard form"
Then I am returned to the main menu
And no new saved form has been created

**Comment by lognaturel** [comment]
To consider for the future: use relative time for "discard since"

**Comment by seadowg** [comment]
Will just build this on top of #5391 for the moment
