### ISSUE TITLE
Investigate max zoom levels for maps

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5242]
As per [this forum post](https://forum.getodk.org/t/problem-mapbox-satellite-and-mtiles-layer/38542/3?u=seadowg), it seems like the max zoom level for Mapbox has been reduced in Collect v2022.3. We should investigate whether we can get back to the zoom levels that were possible in v2022.2. Additionally, it would be good to look into whether we can unlock those kinds of zoom levels in OSM/Google.

**Comment by grzesiek2010** [comment]
> Mapbox provides maps in 23 zoom levels, with 0 being the lowest zoom level (fully zoomed out) and 22 being the highest (fully zoomed in).

https://docs.mapbox.com/help/glossary/zoom-level/

I don't think we can change it but let's take a look...

**Comment by grzesiek2010** [comment]
Ok I've checked it and this is now only possible with OSM, but also not too much because otherwise it might throw exceptions like `java.lang.IllegalArgumentException: MapTileIndex: Zoom (30) is too big (zoom=30)`. Should we do that for this provider I'm not sure? What do you think @seadowg @lognaturel?

**Comment by seadowg** [comment]
> Ok I've checked it and this is now only possible with OSM,

So we're already supporting the max possible zoom levels for Google Maps and Mapbox right?

> it might throw exceptions like java.lang.IllegalArgumentException: MapTileIndex: Zoom (30) is too big (zoom=30). Should we do that for this provider I'm not sure?

Are you saying we **could** add extra zoom levels for OSM but need to limit it to 30?

**Comment by grzesiek2010** [comment]
> So we're already supporting the max possible zoom levels for Google Maps and Mapbox right?

Yes

> Are you saying we could add extra zoom levels for OSM but need to limit it to 30?

I'm not sure what value is the last supported one, I've just got that exception testing 30 probably something lower would work fine but I would need to test more.

**Comment by seadowg** [comment]
I've filed an issue with Mapbox https://github.com/mapbox/mapbox-maps-android/issues/1802.
