### ISSUE TITLE
Missing „form resume” in audit log events when moving backward in not allowed in Collect settings

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5253]
**Software and hardware versions** 

Collect v2022.2.3,  Android probably all

**Problem description**

When moving backwards is not allowed in Collect settings and the user resumes a form with audit from a save point there is no information about „form resume” in audit log events.

**Steps to reproduce the problem**

1. Go to Collect Settings → Access control → Form Entry Settings.
2. Uncheck Moving backwards.
3. Go to a form with audit (e.g. AuditTest).
[AuditTest.xml.txt](https://github.com/getodk/collect/files/9358273/AuditTest.xml.txt)

4. Fill some answers.
5. Kill the app (while the form is opened).
6. Go back to Collect and the form.
7. Save Form and Exit.
8. Go to audit.csv file of the form.

**Expected behavior**

There should be information about „form resume” in audit.csv file .

**Other information** 

I haven’t checked earlier versions of Collect, so the issue may occur there as well.

**Comment by seadowg** [comment]
@lognaturel do you agree that this is a problem?

**Comment by lognaturel** [comment]
It certainly feels like a bug but from what I read here it doesn’t seem critical. We do correctly only allow going to the question that was last on the screen or a question after that, right? If we allow going back in the form that way it would feel very serious to me.

**Comment by seadowg** [comment]
> We do correctly only allow going to the question that was last on the screen or a question after that, right?

Yeah, that's my understanding from when we first found this. Does that sound correct @dbemke?

**Comment by seadowg** [comment]
I've realised that this could be a big problem for people trying to track the length of form sessions
