### ISSUE TITLE
Denying access to location in the app permissions and in the form with background location recording results in flashing screen

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5257]
**Software and hardware versions** 

Collect v2022.3.2,  Android probably all

**Problem description**

There is a flashing screen after denying access to location while filling in a form with background location recording, provided that the user had denied access to location in app permissions in device settings (device’s location permission is on). The app doesn’t crash.
On Android 8.1 denying access to location results in reappearing dialog.

Steps to reproduce the problem

1. Go to device location settings.
2. Device’s location permission is on.
3. Turn off ODK Collect location permission in device settings.
4. Go to ODK Collect.
5. Go to AuditTestLocationBackground form.
[AuditTestLocationBackground.xml.txt](https://github.com/getodk/collect/files/9381916/AuditTestLocationBackground.xml.txt)

6. Choose „don’t allow”/”deny” access to device’s location in the dialog.

**Expected behavior**

After denying access the user should see another dialog asking to access location by opening settings and should be able to continue filling in the form.

**Other information** 

In All widgets form denying access to location while using Geo widgets works as expected.

**Comment by seadowg** [comment]
Is this present in v2022.2 as well?

**Comment by dbemke** [comment]
Collect v2022.2.0 works as expected
