### ISSUE TITLE
In a form with metadata, denying access to phone and then allowing it in phone settings results in the form being in loading state

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5261]
**Software and hardware versions** 

Collect v2022.3.3,  Android probably all

**Problem description**

In form with metadata, after denying ODK Collect to make and manage phone calls, then in next dialog choosing „open settings” and allowing access to phone in device settings, the form is in a loading form state. The user is unable to complete the form.

**Steps to reproduce the problem**

1. Go to Metadata form.
[metadata.xml.txt](https://github.com/getodk/collect/files/9402538/metadata.xml.txt)
2. Deny ODK Collect to make and manage phone calls.
3. In the next dialog „Read phone state permission” click „open settings”.
4. In ODK Collect app permissions allow phone access.
5. Click the device back button.

**Expected behavior**

The user should be able to complete the form after allowing phone access in the app settings.

**Other information** 

If the user rotates the screen (after actions from steps to reproduce), the form is opened as expected.
In Collect v2022.2.0 if the user denies access to phone, the form closes.

**Comment by seadowg** [comment]
Ah this is similar to #5240 - the app is killed and then "restored" when a permission changes in settings. Looks like restoring in this scenario causes problems for some reason.

**Comment by seadowg** [comment]
@dbemke is this fixed in https://github.com/getodk/collect/pull/5212?

**Comment by dbemke** [comment]
in PR#5212 there was a similar case and it was fixed in that PR, but this issue is on master and PR#5212 didn't fix it
