### ISSUE TITLE
The order of question and location tracking enabled events in audit log after form resume

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5262]
**Software and hardware versions** 

Collect v2022.3.2,  Android probably all

**Problem description**

I’ve noticed that there is a different order of "question” and "location tracking enabled” events in audit log when the form is saved for the first time and after editing the form. When the form is completed for the first time, at the beginning of audit log first there is a "location tracking enabled” and then a "question” event. After editing the same form, in audit log after "form resume” event first there is a "question” event and then a "location tracking enabled” event.
![auditlogresumeorder](https://user-images.githubusercontent.com/56479916/186170567-1705a462-af75-489a-b490-5a47eae152db.png)

**Steps to reproduce the problem**

1. Go to AuditTest form.
[AuditTest.xml.txt](https://github.com/getodk/collect/files/12817404/AuditTest.xml.txt)
2. Allow tracking location if necessary.
3. Fill in some questions.
4. Save and exit the form.
5. Go to Edit Saved Form.
6. Edit the form and save it.
7. Go to audit.csv file.

**Expected behavior**

The order of those events in audit log after editing the form should be the same as in completing the form for the first time.

**Comment by seadowg** [comment]
Is this present in v2022.2 as well?

**Comment by dbemke** [comment]
In Collect v2022.2.0 after form resume, the question event is before location tracking.

**Comment by seadowg** [comment]
@lognaturel do you agree that this is a problem?

**Comment by grzesiek2010** [comment]
I've investigated this issue and it looks like it can be easily fixed so let's do that.
