### ISSUE TITLE
A crash after minimizing the app while recording a selfie video

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5265]
Blocked by #5196

**Software and hardware versions** 

Collect v2021.3.4,  Android probably all

**Problem description**

There is a crash if the users minimizes the app while recording a video via selfie video widget. The issue is reproducible on all devices but the frequency of occurrence differs between devices. On Nexus with Android 8.1 and Samsung with Android 11 the issue is always reproducible. Redmi with Android 10 it is often. On Pixel with Android 12 it is sometimes if the user clicks the button(the picture below) after the fifth step to reproduce.
![pixelb](https://user-images.githubusercontent.com/56479916/186909221-802062a3-fe21-4f33-9d5f-f7e938d9d908.jpg)

**Steps to reproduce the problem**

1. Go to All widgets form.
2. Go to Selfie video widget.
3. Click Record Video.
4. Tap the screen to start recording.
5. Minimize the app.
6. Go back to the app.
7. Tap the screen.

**Expected behavior**

The app shouldn’t crash.

**Other information**

If in device settings don’t keep activities is on, the app doesn’t crash.

**Comment by seadowg** [comment]
We should look at this as part of #5196
