### ISSUE TITLE
Dialog asking to grant permissions overlays the lock screen on Android 8.1

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5273]
**Software and hardware versions** 

Collect v2021.3.4,  Android 8.1

**Problem description**

The issue occurs only on Android 8.1.
If the user locks the screen when a dialog asking to grant permission to access the camera, the location, the microphone etc. is opened, the dialog overlays the lock screen view. After clicking a button to unlock the screen, the user sees the dialog and needs to tap "deny" or "allow" in the dialog to be able to continue unlocking the screen. What the users sees when trying to unlock the screen is presented in pictures below.
![lockedscreen](https://user-images.githubusercontent.com/56479916/187940552-b1994454-d5f2-4c35-86a3-d6a47f9b6170.png)

**Steps to reproduce the problem**

1. Go to All widgets form.
2. Go to Image widget.
3. Tap "Take Picture" (make sure that the camera permission is not granted in the device settings).
4. Lock the screen.
5. Unlock the screen.

**Expected behavior**

The user should see the lock screen first, the dialog asking to grant permission should overlay Collect app.

**Comment by grzesiek2010** [comment]
This is a dialog displayed by the system not by us so It must be a bug in that Android version. I think we can close it.
