### ISSUE TITLE
Shortcuts (or external apps) allow multiple forms to be filled at once and cause confusion

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5274]
#### ODK Collect version

v2022.3.5

#### Android version

All

#### Device used

Pixel 2 emulator

#### Problem description

A shortcut or external app can be used to start filling/editing a form while another is already in progress. This cause strange flows (an example is in the steps to reproduce).

#### Steps to reproduce the problem

1. Create a shortcut to a form
2. Start filling the same form in the app
3. Return to the home screen and start filling the form via the shortcut

The second "session" opens in the hierarchy view with the answers from the first session. Then:

4. Click "Go to End"
5. Click "Save form and exit"

User is shown the end screen again (from the first session), but nav buttons or swiping no longer work. If they click "Save form and exit" the form saves and they end up with only one saved instance.

#### Expected behavior

The second "session" should still open in hierarchy mode, but when we return to the first we should be able to navigate and edit the form. There should only be one instance saved from both sessions and any changes made in the first (after saving the second) should override those made in the second. For example, if I'm using our test `one-question.xml`:

1. I open the form from Collect and enter 32 for the "what is your age" question
2. I open the form from a shortcut, click "Go to End" and then save and exit
3. I'm returned to my first session and I change the answer from 32 to 33 and then save and exit
4. When I look at the instance in "Edit Saved Form" the answer to the question should be 33

**Comment by lognaturel** [comment]
> Start filling the same form in the app

Is this required or is it the same thing if you launch from the shortcut twice?

> The second "session" opens in the hierarchy view with the answers from the first session.

I've heard of some organizations hiding the Collect app and ask their field staff to only use direct shortcuts to forms. In those cases, I imagine the desired behavior is that if you tap on the shortcut for the form with formid A and there was an ongoing session filling out formid A, the data collected so far is recovered. So I believe the current behavior is the most expected from a user standpoint. Does it crash?

With (1), let's say a user taps the shortcut and starts filling in data. Then they break for lunch, come back later, and click on the same shortcut again. What I think would happen:
- if Collect is still in memory, they open a second "session" with a blank form and it's impossible to ever complete the initial "session"
- if Collect went out of memory, they open a new "session" which recovers from savepoint and they can pick up where they left off

**Comment by grzesiek2010** [comment]
> Is this required or is it the same thing if you launch from the shortcut twice?

If you start the same form from the shortcut then everything is fine. The problem is when you do that like @seadowg described because you end up with two instances of the `FormEntryActivity` but with one shared form controller (in the application class) at least now because @seadowg is going to change that in https://github.com/getodk/collect/pull/5267 and then weird things happens.
Even worse things happen if you start different forms in a similar way then you end up not only with multiple instances of different forms but with a sharable form controller that represent those different forms.

**Comment by seadowg** [comment]
> I've heard of some organizations hiding the Collect app and ask their field staff to only use direct shortcuts to forms. In those cases, I imagine the desired behavior is that if you tap on the shortcut for the form with formid A and there was an ongoing session filling out formid A, the data collected so far is recovered. So I believe the current behavior is the most expected from a user standpoint. Does it crash?

I've updated the "Steps to reproduce the problem" to show the weirdness we run into:

> 1. Create a shortcut to a form
> 2. Start filling the same form in the app
> 3. Return to the home screen and start filling the form via the shortcut
>
> The second "session" opens in the hierarchy view with the answers from the first session. Then:
> 
> 4. Click "Go to End"
> 5. Click "Save form and exit"
> 
> User is shown the end screen again (from the first session), but nav buttons or swiping no longer work. If they click "Save form and exit" the form saves and they end up with only one saved instance.

The flow you're describing makes sense, but the user ends up in a weird state currently. If we want to support it properly, it sounds like tapping on a shortcut when a session for that form is already in progress should resume that session (and not open a second one). And, tapping a shortcut for a different form while a session is already in progress should open a second session (they stack). That's an expanded version of (3) I guess. Does that sound right?

**Comment by lognaturel** [comment]
> tapping on a shortcut when a session for that form is already in progress should resume that session (and not open a second one). And, tapping a shortcut for a different form while a session is already in progress should open a second session (they stack).

That sounds ideal if possible!

**Comment by seadowg** [comment]
Oooops. Actually, I was a little off. If the user is only using shortcuts, currently they do resume form entry as expected when clicking on the shortcut a second time. I'm guessing Android keeps track of the fact that it already has a task running for this shortcut, and just resumes it instead of starting a new one with the shortcut intent. They end up in the same stuck state (navigation not working) as in the issue description if they open two form filling sessions for different forms however (which I'm surprised no one has complained about).

I think the "open a form normally and then with a shortcut case" is always going to be a little weird because of savepoints - even with making it possible to have multiple sessions open you still end up editing the same instance in every session (for sessions of the same form). I think that case is much rarer though (even if it's a good demonstration of the underlying problem) and we probably want to smooth that out over time along with #4879 and #3494 as we get towards the ability to open a from from within another form.
