### ISSUE TITLE
Crash of Collect built in debug mode after opening Leaks app 

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5276]
**Software and hardware versions** 

Collect v2022.3.4 debug mode,  Android probably all

**Problem description**

There is a crash of ODK Collect app built in debug mode when the user opens Leaks app. The issue doesn’t always occur (e.g. it occurs in 1 out of 4 tries).

**Steps to reproduce the problem**

1. Open ODK Collect app.
2. Click device back button.
3. Open Leaks app.

**Expected behavior**

The app shouldn’t crash.

**Comment by grzesiek2010** [comment]
This seems to be a bug in LeakCanary https://github.com/square/leakcanary/issues/2411
We need to wait for their release. It shouldn't affect the way reports (about leaks) are displayed it's just annoying. I'm closing the issue.
