### ISSUE TITLE
Buttons at the bottom of Send Finalized Form screen should each take up half the width

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#529]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
The 'Clear/Select All' and 'Send Selected' buttons change slightly in size when the check boxes are toggled using the 'Clear/Select All' button.

#### Steps to reproduce the problem
1. Fill out and finalize at least one form
1. Tap the Send Finalized Form button
1. Tap on the 'Select/Clear All' button a few times

#### Expected behavior
The buttons should have a fixed size of half of the available width.

#### Other information 
There's the same problem with 'delete saved forms'. It would be fine to do both as one pull request.

Related to #408.

**Comment by faizmalkani** [comment]
Working on this, please add an inprogress label @lognaturel

**Comment by faizmalkani** [comment]
Fixed in https://github.com/opendatakit/collect/pull/533 @lognaturel
