### ISSUE TITLE
Missing dialog when a user opens settings and clicks device back button while reconfiguring with QR code

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5290]
#### ODK Collect version
v2022.3.0
#### Android version
Android 10, 11, 12, 13 (on the emulator)
#### Device used
Xiaomi Redmi 9T, Samsung Galaxy M12, Pixel 3a
#### Problem description
When a user denies Collect to take pictures and record video while reconfiguring with QR code and open settings and just clicks back button there is a blank page and no dialog. On Redmi 9T reproducing steps 5-8 results in the whole screen being black.
#### Steps to reproduce the problem
1. Go to Settings → Project Managment → Reconfigure with QR code
2. Tap "deny” ODK Collect to take pictures and record video.
3. In next dialog tap "Open settings”.
4. Click device back button.

(Additional steps for Redmi 9T)
5. Rotate the device twice so it’s in a vertical position.
6. Tap "deny” ODK to take pictures and record video.
7. Click device back button.
8. Tap "ok” in the next dialog.
#### Expected behavior
After opening settings and clicking the back button, the user should see a dialog.
#### Other information 
On Android 8.1 the issue doesn’t occur.

**Comment by leiaar** [comment]
I am requesting to be assigned this issue. I have written a fix and will open a pull request once assigned. Thank you.

**Comment by dbemke** [comment]
After merging https://github.com/getodk/collect/pull/5434 the issue will be resolved. 
Following steps from the issue will result in being moved to the Project Management view. The user will be also moved to the Project Management view after tapping "open settings" and granting access to the camera.
Verified on Android 10, 11, 13.
