### ISSUE TITLE
Missing events/answers in audit log for track changes reason form if the form was minimized and the changes where made on the reopened page

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5291]
#### ODK Collect version
v2022.3.0
#### Android version
probably all
#### Device used
Samsung M12, Redmi 9T, 12(on the emulator), 13 (on the emulator)
#### Problem description
If a user starts filling a form with audit and tracking changes and minimizes it and goes back to filling the same page(without swiping to next page) and changes the answers, there is a difference between answers visible in "View Sent Form” and audit.csv file. The changed answers are not in audit.csv file. If the submission is viewed on Central or via Enketo all the answers are visible.

For forms with `track-changes-reason` (like in the steps below), the user is able to bypass the change reason prompt with this flow.

#### Steps to reproduce the problem
1. Go to Track Changes Reason form.
[track-changes-reason-on-edit.xml.txt](https://github.com/getodk/collect/files/9624044/track-changes-reason-on-edit.xml.txt)
2. Start filling the form.
3. Minimize the form while on page with "What’s up?” question.
4. Go back to the form and don’t swipe to the previous/following page.
5. Add something to the answer on the page which was opened after going back to the form.
6. Finalize and exit the form.
7. Go to audit log and go to "View Sent Form” and compare the final answers. 

#### Expected behavior

The answers added in step 5 should be visible in audit log.

#### Other information 
If the user clicks next and then back, the changed answers will be in audit log.
I haven’t checked earlier versions than v2022.3.0
If don't keep activities is on, all the answers are in the audit log.

**Comment by seadowg** [comment]
@dbemke could you check v2022.2 as well please?

**Comment by dbemke** [comment]
@seadowg I've just checked v2022.2.0 and the answer added in step 5 is present in audit.csv file so the issue isn't present in v2022.2.0

**Comment by lognaturel** [comment]
Agreed that this is serious.
