### ISSUE TITLE
The question event is duplicated in csv file after each rotation of the screen.

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5303]
**ODK Collect version**
v2022.3 Beta 2

**Android version**
8.1, 10, 11, 12, 13

**Device used**
Nexus 5X, Redmi 9T, Samsung Galaxy M12, Pixel 3A, Pixel 6A

**Problem description**
Each time the user rotates the screen, a new line with "question" appears.

**Steps to reproduce the problem**

1. Open Fill Blank Form and navigate to the Track Changes Reason form;
https://github.com/getodk/collect/files/9763534/track-changes-reason-on-edit.xml.txt

2. Write "Test" in "What  up" question and rotate the screen several times;
3. Save the form and navigate to the audit.csv file;
4. Open Audit.csv file.

**Expected behavior**

The line with "question/data/what_up" should not be duplicated after each rotation.

**Other information**
Bug was first introduced in version: https://github.com/getodk/collect/releases/tag/v2022.3-beta.2
![194529867-7459de04-1144-4d0b-82e1-8ade511ed8fd](https://user-images.githubusercontent.com/85225519/195305986-25b98478-a403-4a7a-94be-e5673c148077.png)

**Comment by grzesiek2010** [comment]
This issue does not ocurr anymore.
