### ISSUE TITLE
Create an automated test to ensure an admin setting shows and hides the associated feature

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#532]
Create a test that does the following for one admin setting in the “User can access main menu items” category:

1. Open Admin Settings
2. Set the `Delete after send` checkbox’s state to **checked**
3. Go General Settings
4. Assert that the `Delete after send` checkbox is present
5. Uncheck the same admin checkbox and assert that the general checkbox is hidden

**Comment by yadav-rahul** [comment]
@lognaturel I would like to work on this issue.
