### ISSUE TITLE
Editing a form with background audio recording and audio quality set crashes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5323]
#### ODK Collect version
master 1189d9e3e7ee73e1c5694fd4ecf70ecdb7bd09b0
#### Android version
8.1, 10, 11, 12, 13 
#### Device used
Nexus 5X, Redmi 9T, Galaxy M12, Pixel 3a, Pixel 6a
#### Problem description
The Collect app crashes when a form with set audio quality (in xml file) and background audio recording is edited.
#### Steps to reproduce the problem
1. Fill and save AuditTestLocationBackgroundAudio form or low quality form.
[low_quality.xml.txt](https://github.com/getodk/collect/files/9859920/low_quality.xml.txt)
[AuditTestLocationBackgroundAudio.xml.txt](https://github.com/getodk/collect/files/9859931/AuditTestLocationBackgroundAudio.xml.txt)

2. Go to Edit Saved Form.
3. Edit and save the form.
#### Expected behavior
The app shouldn’t crash.
#### Other information 
On the store version (v2022.3.6) the issue doesn’t occur.
I removed from xml files audio quality setting and the crash doesn't occur then.
[low_quality(1).xml.txt](https://github.com/getodk/collect/files/9859967/low_quality.1.xml.txt)
[AuditTestLocationBackgroundAdiowithoutadioquality.xml.txt](https://github.com/getodk/collect/files/9859971/AuditTestLocationBackgroundAdiowithoutadioquality.xml.txt)

**Comment by seadowg** [comment]
I'm assuming this is a regression from #5309.

**Comment by grzesiek2010** [comment]
> I'm assuming this is a regression from https://github.com/getodk/collect/pull/5309.

No. It turned out to be a bug in the newest version of `mp4parser:muxer`. https://github.com/getodk/collect/pull/5334
