### ISSUE TITLE
Error notification is showing after every rotation of the screen

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5327]
**ODK Collect version**
master https://github.com/getodk/collect/commit/57ab44d3657b4efc4f62f92397ba8719a3db333d

**Android version**
8.1, 10, 11, 12, 13 

**Device used**
Nexus 5X, Redmi 9T, Galaxy M12, Pixel 3a, Pixel 6a

**Problem description**

Bug found during testing PR: https://github.com/getodk/collect/pull/5318
The notification "Sorry, this response is required" appears after every rotation, even when the answer is selected.

**Steps to reproduce the problem**

- Open [nigeria_wards_internal.xml.txt](https://github.com/getodk/collect/files/9880153/nigeria_wards_internal.xml.txt)
- Select any answer in first question;
- Move to the hierarchy view;
- Go to the Required page e.g Ward;
- Click next button (the notification will appear);
- Close notification and go back to the first question;
- Rotate the screen.

https://user-images.githubusercontent.com/85225519/198309100-eed94532-1edf-4b78-bdd3-b92da09a2ae6.mp4

**Expected behavior**
The notification "Sorry, this response is required" should not appear after rotating the screen

**Other information**

**Comment by seadowg** [comment]
Nice find. I actually think this is fine. I think we'll end up redesigning the constraint UI sometime in the future and I think we can refine details like this when doing that. Marking this as "won't fix" and closing for the moment.
