### ISSUE TITLE
Non-empty values passed in auto-send are interpreted as false (forms should not be sent automatically)

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5339]
#### ODK Collect version
All versions.

#### Problem description
In `auto-send` we support only true/false values. If a user wants to use project settings they have to leave the value empty. That default behavior should be take place also if any unsupported value is passed in `auto-send`. However currently any non-empty value other than true/false is treated as false. Moreover ODK Build adds `default` value by default what is then interpreted by ODK Collect as false.
The same problem might occur in `auto-delete` too.

#### Steps to reproduce the problem
Try to finalize the attached form: 
[AutoSendTest.xlsx](https://github.com/getodk/collect/files/10020535/AutoSendTest.xlsx)

#### Expected behavior
In both `auto-send` and `auto-delete` it should work like:

```
true -> true
false -> false
empty value or any non-empty value -> default behavior (checking project settings)
```

#### Other information 
The problem has been originally reported on the forum: https://forum.getodk.org/t/odk-collect-app-form-auto-send-not-working/39544/11

**Comment by yanokwa** [comment]
Build only adds the "default" value when you export to XLSForm. See https://github.com/getodk/build/blob/30cb0fca9af28f865eec57e032cae1932d542e9c/server/views/index.erb#L327 for the relevant code.

When you export to XML, it doesn't include `auto-send` attribute at all. It probably shouldn't put anything and I've filed an issue at https://github.com/getodk/build/issues/319. 

I think we should still proceed with this fix in Collect.

**Comment by florianm** [comment]
So Build https://github.com/getodk/build/blob/30cb0fca9af28f865eec57e032cae1932d542e9c/server/views/index.erb#L328 should read 

```
<option value="" selected="selected">Follow ODK Collect settings</option>
```
instead? (same for autodelete)

edit: ready for review https://github.com/getodk/build/pull/320

**Comment by yanokwa** [comment]
@florianm I think that'd work!
