### ISSUE TITLE
Sort by last saved is not translated to other languages

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5342]
#### ODK Collect version
v2022.4 Beta 2
#### Android version
10, 13 (probably all)
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
In Fill Blank Form sort by last saved is not translated to other languages.
#### Steps to reproduce the problem
1. In Collect settings change language to e.g. Spanish.
2. Go to Fill Blank Form.
3. Tap sort by.
#### Expected behavior
All sort by options should be translated.

**Comment by grzesiek2010** [comment]
We do not add new translations along with implementing a new feature/fix. If there are new strings they are in English and then we let contributors translate them using https://explore.transifex.com/getodk/collect/. Such new translations are added at the end of every release cycle.
