### ISSUE TITLE
Importing a big sized image while reconfiguring with QR code crashes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5346]
#### ODK Collect version
v2022.3.0, v2022.4 Beta 2
#### Android version
10, 13 (probably all)
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
The app crashes if a user tries to import a big sized image (which isn’t a QR code) while reconfiguring with QR code.
#### Steps to reproduce the problem
1. Go to Settings, Project management, Reconfigure with QR code
2. Tap on the three dots and import QR code.
3. Select a big sized file (I tried 27MB image).
#### Expected behavior
The app shouldn’t crash. User should see a toast.

**Comment by seadowg** [comment]
Looks like we're seeing this in Crashlytics: https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7e418d89695b6891711feafdd3d5a642?time=last-seven-days&versions=v2022.4-beta.2%20(4531)&types=crash&sessionEventKey=6377834000B00001170C8D036CECD717_1745787297916921103
