### ISSUE TITLE
Add analytics for manually-specified instance name

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5350]
Instance name is editable when it is not specified by an expression in the form definition. Any name specified that way is local to Collect only.

Our hypothesis is that this gets used very rarely. We'd like to verify that.

**Comment by seadowg** [comment]
My thinking here is that we want to know how often users actually type a name in to the instance name (or "save as") field. To be very specific the acceptance would be:

```
Given I'm on the end screen of a form without an instance name expression
When I fill in the "Name this form" field
And tap "Save form and exit"
Then an analytics event records that I used the instance name/save as field

Given I'm on the end screen of a form without an instance name expression
When I tap "Save form and exit"
Then there is no analytics event that records that I used the instance name/save as field (or there is one recording that I didn't use it)
```

Do you agree @lognaturel? #5354 would measure how often the manual instance name (or "save as") would be available which doesn't seem quite right to me.

**Comment by lognaturel** [comment]
Yes, agreed with those acceptance criteria.
