### ISSUE TITLE
Don't include vertical space for a value for note fields

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5352]
See [the forum](https://forum.getodk.org/t/form-with-appearance-field-list-and-nested-group-label/39625/4?u=ln)

**Comment by grzesiek2010** [comment]
We don't have a separate widget for notes. `Note` is treated as `string` `read-only` widget. To be consistent we decided to treat all `read-only` widgets without answers in the same way by hiding the answer container and displaying a space box (see: https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java#L361)

I don't think we should introduce a special case for notes. Maybe we should just get rid of that space box and then all `read-only` widgets without answers will be displayed in the same way (in the way that the user on the forum expected). What do you think?

**Comment by lognaturel** [comment]
Huh, I wonder why we added that space box! Yes, removing that space for all read-only widgets without answers seems good to me. It will only make a difference in a field-list and I think not having the vertical space is the most expected result.
