### ISSUE TITLE
Rework logging analytics

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5353]
#### Problem description
Every time when I need to add new analytics it's confusing to me what class/method should I use. I need to look at other existing logs to understand how to do that. Every time it takes more time that it should. 

Problems with analytics that I see are:
1. In some places we log analytics using `BlockableFirebaseAnalytics` object in other it's via `AnalyticsUtils`.
2. There are some deprecated methods in `BlockableFirebaseAnalytics` but there is no description why they are deprecated.
3. I think we could just have a class like `AnalyticsUtils` with static methods. Now in many classes we pass `Analytics` object and use it to log analytics. To me it's an overkill. Analytics are for us we can test them in [Android Studio](https://firebase.google.com/docs/analytics/events?platform=android) so there is no need to pass that object to every class where we want to log analytics and then even write automate tests for that. We very often add and remove analytics so then we need to often add and remove such objects from classes.
4. I'm not sure if the way we log events that should be unique to the same form is the perfect way. We log form hashes as parameters and it seems like the limit for parameters is 200 so if there are a lot of different forms we do not really now how many unique forms were used.

**Comment by seadowg** [comment]
Agreed! I think we should only really be using `Analytics.log` or `AnalyticsUtils` (for the collect specific stuff like form and server events or complex/shared logging code). The only time we should be interacting with instances of the `Analytics` interface directly would be times we want to test the analytics calls (which are rare).

> I'm not sure if the way we log events that should be unique to the same form is the perfect way. We log form hashes as parameters and it seems like the limit for parameters is 200 so if there are a lot of different forms we do not really now how many unique forms were used.

@lognaturel has said she still finds this useful as it at least allows us to know if the event is firing for just a few forms/servers (imagine an event that only 3 servers were firing for instance) or many different ones.

**Comment by grzesiek2010** [comment]
> The only time we should be interacting with instances of the Analytics interface directly would be times we want to test the analytics calls (which are rare)

I think we shouldn't at all. As I said above it's just logs we see if it works if not we can fix it it's not something that affects users so having a utility class like `AnalyticsUtils` should be totally enough. The only case we should test is if analytics are enabled/disabled.

> @lognaturel has said she still finds this useful as it at least allows us to know if the event is firing for just a few forms/servers (imagine an event that only 3 servers were firing for instance) or many different ones.

Yeah it seems like there is no easy better way so I agree it's not accurate but gives us some sense of how common given events are.
