### ISSUE TITLE
Automate the display of open source license

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5355]
#### Problem description
The way we display a list of dependencies we use in our project is not automated at all but the list is pretty long so it's easy to miss something or make a mistake by displaying it with a wrong license. It also requires updating every time we add/remove any dependency. It's been a while since we implemented it and maybe now there is a better way to solve that issue. For example https://developers.google.com/android/guides/opensource but it would bee good to investigate other options.

**Comment by seadowg** [comment]
I used Google's library in LSHTM's Keppel project, and it was pretty simple: https://github.com/LSHTM-ORK/ODK_Biometrics/blob/fc6246e8c9cc659ca0bfd4c383f11ba2cdb065db/Android/app/src/main/java/uk/ac/lshtm/keppel/android/settings/SettingsActivity.kt#L50.

**Comment by grzesiek2010** [comment]
It seems like there are two tools worth using:
- [play-services-oss-licenses](https://developers.google.com/android/guides/opensource):
- [mikepenz/AboutLibraries](https://github.com/mikepenz/AboutLibraries)

Both are easy to implement (I gave it a try so you can use [my branch](https://github.com/grzesiek2010/collect/tree/libs) to test both solutions). However [mikepenz/AboutLibraries](https://github.com/mikepenz/AboutLibraries) seems to be more sophisticated...

The UI we get out of the box looks better:

| play-services-oss-licenses | mikepenz/AboutLibraries |
| ------------- | ------------- |
| ![Screenshot_1669374006](https://user-images.githubusercontent.com/3276264/203974222-bfeca010-b483-4787-b5a6-010c21cde9a0.png) | ![Screenshot_1669372325](https://user-images.githubusercontent.com/3276264/203974216-fb6c20cb-be75-443a-b588-7326d2252f46.png)  |
 
Another difference is that after clicking on every item in case of `play-services-oss-licenses` we might see a simple link like:
![Screenshot_1669375129](https://user-images.githubusercontent.com/3276264/203974572-41a1535a-89d1-49d2-b0c5-e92532b23704.png)
but `mikepenz/AboutLibraries` opens the documentation or github page of the project.

`mikepenz/AboutLibraries` seems to give us more option to style the list (see: https://github.com/mikepenz/AboutLibraries/tree/v8.9.4#about-this-app-ui).

The last advantage of `mikepenz/AboutLibraries` to me is that we can grab a list of used projects and build our own view to display them if we want in the future (see: https://github.com/mikepenz/AboutLibraries/tree/v8.9.4#access-generated-library-details).

Taking into account all those advantages of `mikepenz/AboutLibraries` and the fact that it's not an abandoned project (it seems to be actively maintained and has over 3k stars on github), am leaning towards starting with it. If We don't like it or there is something wrong with it we can always switch to `play-services-oss-licenses` since as I said implementation of both is pretty easy.

@seadowg any thoughts?

**Comment by seadowg** [comment]
I'd still be inlined to go with `[play-services-oss-licenses](https://developers.google.com/android/guides/opensource)` as it feels like the "official" solution, and I don't really think we need to care very much about the visuals here. Ultimately, I don't have strong opinions here though as it looks like both result in basically one line of code on our side.

One thing to consider might be APK size though: does one result in a larger (signed) APK than the other?

**Comment by grzesiek2010** [comment]
> One thing to consider might be APK size though: does one result in a larger (signed) APK than the other?

Right `mikepenz/AboutLibraries` is a bit heavier so let's use `play-services-oss-licenses`.
