### ISSUE TITLE
In some languages the UI in the Project tab looks confusing/missing buttons

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5357]
**ODK Collect version**
Current master 6e836499110deb34377a8558cbc815fdc08ca25c, the store version v2022.4 Beta 2

**Android version**
10, 12, 13 (probably all)

**Device used**
Redmi 9T, Pixel 3a, Pixel 6a

**Problem description**

After changing the device language to e.g. Italiano and going to the Projects tab some of the buttons are invisible because of the words length. 

**Steps to reproduce the problem**

1. Go to settings -> User interface
2. Click on the Language 
3. Change language to "Italiano" 
4. Click on the Project icon
![Screenshot_20221117-104839](https://user-images.githubusercontent.com/85225519/203583682-b967a3b2-983c-44cf-af9f-e08ff0eb42d5.png)

**Expected behavior**
All of the icons should be visible correctly and no words should be cut off

**Comment by lognaturel** [comment]
The title of the issue says it's crashing but it's really just confusing/weird/ugly, right?

We knew this was a risk. I added a translation issue [here](https://www.transifex.com/getodk/collect/translate/#it/strings/320127410?q=text%3A'add+project'). Maybe we handle it that way?

**Comment by srujner** [comment]
Yes, you're right, the first title was a little bit dramatic. 
It's ok for me.

**Comment by seadowg** [comment]
Closing this as we have a translation issue for it now.
