### ISSUE TITLE
The user needs to tap twice on the plus button in the hierarchy view to add a repeat

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5362]
#### ODK Collect version
v2021.3.4, the store version, master 6e836499110deb34377a8558cbc815fdc08ca25c
#### Android version
8.1, 11, 13 (probably all)
#### Device used
Nexus 5X, Redmi 9T, Pixel 6a
#### Problem description
Adding a repeat and filling the question, then quickly going to hierarchy view makes the user tap twice on the plus button to add another repeat. It seems that if the user waits a bit longer before going from step nr 4 to step nr 5 and 6 the issue doesn’t occur. If the user doesn’t fill anything in the question field, the issue doesn’t occur.
#### Steps to reproduce the problem
1. Go to nested-repeats.xml form.
[nested-repeats.xml.txt](https://github.com/getodk/collect/files/10082333/nested-repeats.xml.txt)
2. Add "Friends".
3. Fill in a name of a friend.
4. Tap the hierarchy view.
5. Tap the arrow to go up.
6. Tap the plus button
#### Expected behavior
Tapping once on the plus button should add a repeat.

**Comment by seadowg** [comment]
I'm wondering if this is related to #4457
