### ISSUE TITLE
Improvements to the new crash screen

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5365]
#### ODK Collect version
v2022.4

#### Problem description
In the latest version we have added crash handling (see: https://github.com/getodk/collect/pull/5324). There is a new screen which pops up after reopening the app after it crashed. It looks like:
![image](https://user-images.githubusercontent.com/3276264/203824549-296ac78c-f18d-443b-a5e5-bbbdc8633ffe.png)

We talked about further improvements like for example sharing logs on the forum (or via email) https://github.com/getodk/collect/pull/5324#issuecomment-1303803995

Maybe there is something else we should change too. @lognaturel @seadowg any thoughts?

**Comment by grzesiek2010** [comment]
Another thing that comes to my mind is that reviewing crash reports I've noticed that we have a lot of different `OutOfMemory` errors. The app is big and such errors might occur in many different places in the app so it's impossible to catch all of them. Instead we could think about handling some errors like this one in the new view and providing a more readable explanation of what happened than just `OutOfMemory` and logs.

**Comment by lognaturel** [comment]
Another specific one to have a message for: storage issues could recommend restarting.

Maybe get the full, copy-able stacktrace in a separate dialog.

**Comment by seadowg** [comment]
This feels too general for an issue. We can discuss and create issues for improvements when we're planning work like this as part of a release.
