### ISSUE TITLE
Linked two Odk from

### ISSUE THREAD

**Issue by kimanimollel** [getodk/collect#5377]
#### Other information 

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by kimanimollel** [comment]
I hope you are doing well
Welcome for discussion, how can able to join two odk forms by recalling another form

**Comment by lognaturel** [comment]
Please use the forum for support requests. You can see a similar thread posted recently at https://forum.getodk.org/t/how-to-link-2-odk-forms/39822
