### ISSUE TITLE
If Credentials are Invalid Tell the User

### ISSUE THREAD

**Issue by wonderchook** [getodk/collect#538]
Currently if a user has an incorrect username and password and attempts to submit surveys to the server they only receive a screen asking for the username and password. No indication is given that something is wrong. It would be nice if we could tell them to verify their username and password. 

![screenshot_20170307-154330](https://cloud.githubusercontent.com/assets/67992/23683347/5b25c3d2-034d-11e7-9002-ffe0f3993558.png)

#### Software and hardware versions 
Collect v1.4.10, Galaxy S6

**Comment by Midhun07** [comment]
Can i work on this issue?

**Comment by lognaturel** [comment]
@Midhun07 Please do! I haven't looked at that code in a while and I'm not sure what you'll find. I encourage you to start by writing up a little proposal on how you'll approach it and sharing it here.

**Comment by UrjaPawar** [comment]
@wonderchook I want to solve this issue but am not getting this function in the app. The app I am running doesn't ask for any authorization while sending the forms!

**Comment by lognaturel** [comment]
@UrjaPawar I do think @Midhun07 has this one! In order to verify the existing behavior, you'll need a server that requires a username and password. I believe https://opendatakittrial.appspot.com does. You can use username admin and password aggregate. Don't fill them out in the settings and when you try to pull blank forms you should see that dialog.

**Comment by UrjaPawar** [comment]
@lognaturel Should I integrate the app with the server you mentioned? I haven't filled them in the settings
![ezgif-1-e841aa44a1](https://cloud.githubusercontent.com/assets/16853965/23714095/0f8927d2-044e-11e7-998b-95acc9498a24.gif)

**Comment by lognaturel** [comment]
@UrjaPawar You changed the server URL to https://opendatakittrial.appspot.com, left username and password blank and can send forms without credentials? I have verified that I can't. Did you put the credentials in at any point? There are some strange things still about how sessions are stored and invalidated. Can you try killing the app and trying again?

**Comment by UrjaPawar** [comment]
@lognaturel  I did put up the credentials but even before that I was getting same result. Yes! I tried killing the app but still getting same behavior! Let me see if I can figure what is going wrong

**Comment by Midhun07** [comment]
I reproduced the issue by adding the same URL ( [ https://opendatakittrial.appspot.com](url) ). But different username and password. The issue is real as there is no indication of what's wrong.

**Comment by Midhun07** [comment]
@lognaturel I found out the problem, Here one has to fill the credentials like site, username and password. When submitting form, app sends the user saved credentials. It is then, if the credentials mismatch occurs the Alert dialog prompts the user to re-enter the credentials. So, my idea is, at this point change the message displayed in the dialog as per the error reported by the server like authentication error in this case. 

Hope my proposal is clear. Please guide.

**Comment by lognaturel** [comment]
@Midhun07 Thanks for looking into it. That sounds like a fine general approach. I think you get an HTTP status as well and it may be better to use that and write a custom message such as "The username or password is incorrect." That way it can be translated.

**Comment by Midhun07** [comment]
@lognaturel Thats getting checked as this happens. Its here:
`if (statusCode == HttpStatus.SC_UNAUTHORIZED) { `                 
                    `Collect.getInstance().getCookieStore().clear();`
                   ` WebUtils.discardEntityBytes(response);   `              
                   `outcome.mAuthRequestingServer = u;`
                    `return false;`
               ` }`
And then it shows up the Alert dialog. Thus i guess we only need to change the alert message.

**Comment by lognaturel** [comment]
@Midhun07 that sounds great.

**Comment by Midhun07** [comment]
@lognaturel Since only the string needs to be changed, does it require a test unit?If no shall i commit and pull a request?

**Comment by lognaturel** [comment]
@Midhun07 A manual verification is sufficient for this.
