### ISSUE TITLE
Error dialog after minimizing the app during selfie recording video

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5381]
**ODK Collect version**
Current master 4ec8ed26aafde5e621268999b36ee17cbfaed882

**Android version**
5.1, 12, 13 (probably all)

**Device used**
Huawei, Pixel 3a, Pixel 6a

**Problem description**
Error dialog after minimizing the app during recording video:

**Steps to reproduce the problem**

1. Open All Widgets and navigate to the Selfie video widget
2. Click on the Record Video button
3. Tap the screen to start recording
4. Minimize the app
5. The error "There was an error taking picture" will appear
6. Return to the app - the video will be stopped

https://user-images.githubusercontent.com/85225519/207819771-91fcd7a3-12af-46d7-abaa-160b19af223e.mp4

**Expected Behavior**
After returning to the selfie video, the recording should be stopped but user should be able to resume it and no error message should be visible.

**Comment by seadowg** [comment]
We'll hang fire on scheduling this for the moment as we might remove the selfie video widget (given it's seeing no usage).

**Comment by grzesiek2010** [comment]
We have removed the widget so let's close the issue.
