### ISSUE TITLE
Wrong display message while deleting saved/blank forms

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#539]
#### Software and hardware versions 
Collect v1.4.16, Android v4.4.2, API 19

#### Problem description
Deleting saved forms or blank forms from `Delete Saved Forms` option on `Main Menu` displays wrong Toast message (Selected forms failed to delete). But the saved form or the blank form actually gets deleted

#### Steps to reproduce the problem
1. Select `Fill Blank Form` 
2. Fill any form and click the `save` icon
3. Save the changes and go back to main menu
4. Click on `Delete Saved Form`
5. Delete the `saved form(s)` or `blank form(s)`

#### Expected behavior
Display message "1 form(s) successfully deleted!"

### Actual behaviour 
Message displayed "Sorry, -1 of 0 selected form(s) failed to delete!"

![device-2017-03-08-104822](https://cloud.githubusercontent.com/assets/8918023/23691625/a11eaf5a-03ef-11e7-8e7b-6decbf0c3c0c.gif)

**Comment by UrjaPawar** [comment]
@shobhitagarwal1612  I would like to work on this issue

**Comment by grzesiek2010** [comment]
@UrjaPawar I'm affraid @shobhitagarwal1612 created this issue just for himself :) and as you can see above he already created pr. You can review this pr or try to find another issue for you.

**Comment by UrjaPawar** [comment]
Ok! Thanks for help @grzesiek2010

**Comment by lognaturel** [comment]
@UrjaPawar Welcome to the project! Do let us know if you're having trouble finding a good issue to work on. There's a lot of activity these days so issues get claimed quickly! I encourage you to come say hi in the Slack channel at http://slack.opendatakit.org You can also do what @shobhitagarwal1612 has been doing and as you go through the app, file issues for problems that you notice.

**Comment by UrjaPawar** [comment]
@lognaturel Thank you! I am a newbie to Open Source Development and am working on one of the issues listed, I noticed that the issues labeled "quick win" are taken up by competitive developers. I really need to develop my speed! :)

**Comment by lognaturel** [comment]
@UrjaPawar Are they really all taken already?! I'll see if I can file more. I think there must be some other small bugs introduced by all the changes we made recently. Do make sure you "claim" any issue you're working on so we can mark it as "in progress"! 😊

**Comment by UrjaPawar** [comment]
@lognaturel Yes! I saw that developers claimed and pulled the requests
Again Thanks!
