### ISSUE TITLE
Remove custom instance name and "Mark as finalized" checkbox

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5416]
### New buttons/layout

- [x] Given I've navigated to the end of a form
Then I don't see the instance name field
And I don't see the "Mark form as finalized" checkbox
And I don't see the "Save form and Exit" button
And I don't see the "You are at the end of \<form name\> text"

- [x] Given I've navigated to the end of a form
Then I see text reading "You are at the end of \<instance name>\"

- [x] Given I've navigated to the end of a new form
When I click "Finalize"
Then I am returned to the main menu
And there is a new saved form in Edit Saved Form and Send Finalized Form

- [x] Given I've navigated to the end of a form
When I click "Save as draft"
Then I am returned to the main menu
And there is a new saved form in Edit Saved Form
And there is not a new saved form in Send Finalized Form

### Updated admin settings

- [x] Given I'm in Form Management settings for a project
Then I no longer see the "Default to finalized" setting

- [x] Given I'm in Access Control settings for a project
Then I no longer see the "Default to finalized" setting in User Settings

- [x] Given I'm in Access Control settings for a project
Then I no longer see the "Mark form as finalized" setting in Form Entry Settings

- [x] Given I'm in Access Control settings for a project
When I navigate to Form Entry Settings
And I toggle off "Finalize"
And navigate to the end of a form
Then the "Finalize" button is disabled

- [x] Given I'm in Access Control settings for a project
When I navigate to Form Entry Settings
And I toggle off "Save as draft"
And navigate to the end of a form
Then the "Save as draft" button is disabled

- [x] Given I've scanned an old QR code
And "Default to finalized" in Form Entry was toggled off when the code was generated
And "Mark form as finalized" was disabled in Access Control (under Form Entry Settings) when the code was generated
When I go to Form Entry Settings in Access Control
Then "Finalize" is disabled

- [x] Given I've scanned an old QR code
And "Default to finalized" in Form Entry was toggled on when the code was generated
And "Mark form as finalized" was disabled in Access Control (under Form Entry Settings) when the code was generated
When I go to Form Entry Settings in Access Control
Then "Save as draft" is disabled

- [x] Given I've upgraded the app
And "Default to finalized" in Form Entry was toggled off
And "Mark form as finalized" was disabled in Access Control (under Form Entry Settings)
When I go to Form Entry Settings in Access Control
Then "Finalize" is disabled

- [x] Given I've upgraded the app
And "Default to finalized" in Form Entry was toggled on
And "Mark form as finalized" was disabled in Access Control (under Form Entry Settings)
When I go to Form Entry Settings in Access Control
Then "Save as draft" is disabled

- [x] Given I'm in Access Control settings for a project
When I navigate to Form Entry Settings
And I toggle off "Save as draft"
Then the "Finalize" setting is disabled (I can't toggle it)

- [x] Given I'm in Access Control settings for a project
When I navigate to Form Entry Settings
And I toggle off "Finalize"
Then the "Save as draft" setting is disabled (I can't toggle it)

## Notes

The "Save as Draft" button won't make a lot of sense when editing a finalized form. How this behaves is up to the implementer as we'll remove the ability to get into the situation instead of smoothing it out.

This is based on the proposed changes from https://forum.getodk.org/t/collect-form-finalization-improvements/40208.
User flow is here - https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=487%3A20892&t=SoSD4aJLJLL3Kipd-1. The exact layout will be different as we're not doing the "summary" on the end page yet, we can play with whatever feels right in PR review.

**Comment by seadowg** [comment]
@grzesiek2010 there's still some acceptance to write up here - we need to think about admin settings for the new button setup.

**Comment by alyblenkin** [comment]
Hey @seadowg, I was just chatting with @grzesiek2010, and he pointed out that the [ confirmation dialog](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=504%3A38619&t=SUq2WbwR96jGWcww-1) isn't part of this story. I remember discussing it when we were breaking this down, but it's not in the acceptance criteria. Perhaps it was an oversight because there isn't another issue with the dialog in it. 

The last screen in the finalization flow is the dialog, where they "save as draft" or "finalize" to create some friction/ force the user to confirm to prevent any mistakes. Right now, the acceptance criteria says the flow ends on this page. 
![Screenshot_1681856237](https://user-images.githubusercontent.com/7871340/232920593-9ee7f6f2-9035-4d47-8e8e-a47b7567ddb0.png)

**Comment by seadowg** [comment]
The dialog gets added in #5418. I felt like we didn't need the dialog until we actually removed the ability to edit finalized forms.

**Comment by grzesiek2010** [comment]
So what about those `Finalzie`/`Save as draft` buttons in the acceptance criteria? The title of the issue indicates it's a small change in the End screen but the acceptance criteria confuse me...
