### ISSUE TITLE
Refine form saving language

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5417]
Follow-on from https://github.com/getodk/collect/issues/5232 in context of new "Save as draft" language

## Acceptance

- [x] Given I'm filling out a form
When I press back
And I click "Save as draft" (replacing "Save changes")
Then I am returned to the Main Menu

- [x] Given I'm at the end of a form
And auto-send is enabled
When I press "Send" (replacing "Finalize" when auto-send is enabled)
Then I am returned to the Main Menu
And there is (eventually) a new saved form in View Saved Form

## Notes

To clarify, "auto-send is enabled": this means at the form or settings level. Conversely, we auto-send would not be enabled for the purposes of this issue if it was enabled in settings, but disabled for the form. The logic to determine whether a form will be included during auto send or not is defined in [`InstanceAutoSendFetcher`](https://github.com/getodk/collect/blob/55f9519310315130e47f7d7f7c7d2889c7047372/collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt) and [its test](https://github.com/getodk/collect/blob/55f9519310315130e47f7d7f7c7d2889c7047372/collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt).

**Comment by grzesiek2010** [comment]
What if auto-send is enabled in settings but disabled on a form level? Or the other way around? Probably we should take form-level settings into account, right?

**Comment by seadowg** [comment]
> What if auto-send is enabled in settings but disabled on a form level? Or the other way around? Probably we should take form-level settings into account, right?

I always forget about form level auto send. It'll need to check both. I would say that it should say send if the form will be sent and that should take the form level setting into account. 

Just to note: this probably isn't worth starting until after https://github.com/getodk/collect/issues/5416 right? I'll block it for now.

**Comment by grzesiek2010** [comment]
> Just to note: this probably isn't worth starting until after https://github.com/getodk/collect/issues/5416 right? I'll block it for now.

Why? I don't think there would be any conflicts.

**Comment by seadowg** [comment]
Changing the text from "Finalize" to "Send" doesn't make sense for the current form end page. We could add the same logic to the "Save form and Exit" button, but it would mean implementing the feature twice or having to readapt the initial implementation when building the new form end page.
