### ISSUE TITLE
Block editing of finalized or sent forms via Content Provider

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5419]
Even if it's not possible to edit a finalized or sent/failed to send form in Collect via the UI, it might still be possible via the forms content provider by querying for the form and then opening it for editing with an intent. Collect should show an error message in this scenario.

**Comment by lognaturel** [comment]
Check: is it possible to try to edit a sent form today?

**Comment by seadowg** [comment]
@lognaturel yup! Looks like it is possible. I'll add that to the issue.
