### ISSUE TITLE
CircleCI run of instrumented tests

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#542]
As you know we have some new [instrumented tests](https://github.com/opendatakit/collect/tree/master/collect_app/src/androidTest/java/org/odk/collect/android)
In order to run these tests we need to setup [CircleCI configuration file](https://github.com/opendatakit/collect/blob/master/circle.yml)

I tried when I worked on my fisrt UI test but without success. You can find more info here: https://github.com/opendatakit/collect/issues/392#issuecomment-279236981

These links might be helpful:
https://circleci.com/docs/1.0/android/
https://github.com/circleci/EspressoSample

**Comment by lognaturel** [comment]
I started some work to try to clean up the circle yml file which has some redundant things in it. You can see that [here](https://github.com/opendatakit/collect/compare/master...lognaturel:circle-yml-cleanup). How about starting from there and seeing if you can get the current instrumented tests in the `androidTest` folder to run?

The current state of the file isn't quite right. For some reason the tests and lint results aren't being copied over and I'm not sure why. It might have to do with me trying to move the artifacts copy.

I'm confident that the `machine` and `dependencies` sections are improved. I'm not so sure about the `test` section, I was still experimenting and you can pick up from there, merging in some of what you had tried previously and seeing what you find out.
