### ISSUE TITLE
Show snackbar notification when a form is saved or sent

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5424]
**Acceptance**
- [x] Given I'm filling or editing a form
And I'm at the end of the form
When I click "Save as Draft"
Then I am returned to the Main Menu
And I see a snack bar reading "Your form was saved as a draft." with an "Edit" action and a dismiss (X) button

- [x] Given I'm filling or editing a form
And I'm at the end of the form
And I click "Save as Draft"
And I click "Edit" on the snack bar
Then the form instance is opened for editing

- [x] Given I'm filling or editing a form
And I'm at the end of the form
When I click "Finalize"
Then I am returned to the Main Menu
And I see a snack bar reading "Your form was saved." with a "View" action and a dismiss (X) button

- [x] Given I'm filling or editing a form
And I'm at the end of the form
And I click "Finalize"
And I click "View" on the snack bar
Then the form instance is opened in read-only mode

- [x] Given I'm filling or editing a form
And auto send is enabled
And the device is connected to the internet
And I'm at the end of the form
When I click "Send"
Then I am returned to the Main Menu
And I see a snack bar reading "Sending form..." with a "View" action and a dismiss (X) button

**Comment by alyblenkin** [comment]
@seadowg - I've updated the designs in Figma in the page titled "✅  Dev ready: Form finalization". I also added the link to the google doc.

I came across an [article](https://www.notion.so/Review-toasts-and-accessibility-c7df97e5297146f0ace749e36fbdfa60?pvs=4#82ac7886e2c44d6788778a501c0153f4) today that has some really good tips on making snackbars accessible. Material is rigorously tested, which is great, but I thought this article highlighted some extra points that are worth considering: 

- **Pick a decently long default** A good length of time to keep messages up is 5 seconds plus 1 extra second for every 120 words, rounding up. This is how fast the average American reads. That means the shortest default that should be used as a best practice is 6 seconds. What's our default? 
- **Keyboard access and Keyboard Focus Indicator** Using the keyboard, the user should be able to tab and shift tab through the elements of the toast message. Each activatable element requires a keyboard focus indicator which should meet the minimum 3.0:1 color ratio requirement established by WCAG 2.1 guideline [[1.4.11](https://www.w3.org/TR/WCAG21/#non-text-contrast)](https://www.w3.org/TR/WCAG21/#non-text-contrast). Do we optimize for keyboards?
- **Orientation** New to WCAG 2.1, [[Guideline 1.3.4](https://www.w3.org/TR/WCAG21/#orientation)](https://www.w3.org/TR/WCAG21/#orientation) requires support for both landscape and portrait mode for native apps. Therefore, if a toast message is initially displayed in portrait mode and the user rotates the phone, it should reorient successfully in the same location. Best practice would be to re-start the countdown after the rotation is complete. This might already be addressed :) 

I also hope I using these comments correctly!

**Comment by seadowg** [comment]
> I came across an [article](https://www.notion.so/Review-toasts-and-accessibility-c7df97e5297146f0ace749e36fbdfa60?pvs=4#82ac7886e2c44d6788778a501c0153f4) today that has some really good tips on making snackbars accessible. Material is rigorously tested, which is great, but I thought this article highlighted some extra points that are worth considering:

It looks like that link is to your private Notion account. Could you update it with a link to the article itself?

> - **Pick a decently long default** A good length of time to keep messages up is 5 seconds plus 1 extra second for every 120 words, rounding up. This is how fast the average American reads. That means the shortest default that should be used as a best practice is 6 seconds. What's our default? 
> - **Keyboard access and Keyboard Focus Indicator** Using the keyboard, the user should be able to tab and shift tab through the elements of the toast message. Each activatable element requires a keyboard focus indicator which should meet the minimum 3.0:1 color ratio requirement established by WCAG 2.1 guideline [[1.4.11](https://www.w3.org/TR/WCAG21/#non-text-contrast)](https://www.w3.org/TR/WCAG21/#non-text-contrast). Do we optimize for keyboards?
> - **Orientation** New to WCAG 2.1, [[Guideline 1.3.4](https://www.w3.org/TR/WCAG21/#orientation)](https://www.w3.org/TR/WCAG21/#orientation) requires support for both landscape and portrait mode for native apps. Therefore, if a toast message is initially displayed in portrait mode and the user rotates the phone, it should reorient successfully in the same location. Best practice would be to re-start the countdown after the rotation is complete. This might already be addressed :) 

I'm guessing these will all be handled for us by the Material framework, but they're really good to point out. We should give them a try when reviewing the PR that implements this.

> I've updated the designs in Figma in the page titled "✅ Dev ready: Form finalization". I also added the link to the google doc.

A few notes on this:

* I don't think we should say "Your form was successfully sent" in the auto send case. The form will be sent in the background "as soon as possible", but we won't know at that moment whether it's been a success or not. The user does get a notification once the form has either succeeded or failed to send though. Maybe we should say something like "Sending form..."?
* I don't think we should have separate text for the "device is offline and auto send is disabled" case. In that scenario, they'd have to manually send the form whether they were offline or not. I think if we're saving a form and auto send is off, we should just say "Your form was saved.". Does that sound OK to you?

**Comment by alyblenkin** [comment]
Here is the proper link - https://sheribyrnehaber.medium.com/designing-toast-messages-for-accessibility-fb610ac364be. I agree that I think Material will handle most cases! 

And sorry, I should have made that more clear in Figma (maybe I'll add little comments or headers above):

- "Your form was successfully sent" shows up when they are back online. When they send and are offline, they would see "It looks like you are offline. From will send when you are online", but we could certainly say, "It looks like you are offline. Your from will send as soon as possible."
- We heard in the user research that folks forget to send when the device is offline, and auto send is disabled. The goal was to prompt the user so that the managers don't have to remind them.

**Comment by seadowg** [comment]
@alyblenkin had a call about this and decided a few things:

* We're going to have a message like "Sending form..."  in the snack bar when the form is finalized, auto send is enabled and the device is online and leave the success/failure message to the system notification that's sent when auto send completes. @alyblenkin is going to mock that up (and hopefully improve on my copywriting 😆).
* We're going to punt on trying to prompt the user to send a form later when they're online. We're not sure the moment after finalizing is the correct time to do this, and we're worried that prompting enumerators to do something at this point might actually be confusing if they've been trained to do something else. We did discuss how there might be some other solutions like adding an optional reminder notification to send forms, although it might be that more people using auto send will make the "forgetting to send" forms problems less relevant.
