### ISSUE TITLE
Unable to add gif as picture to image widgets

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5435]
**ODK Collect version**
v2022.4.2 current master c462ede703d6b17162147d26543b7ea0c61282db, 
PR #5344 

**Android version**
10,11,12,13 (probably all)

**Device used**
Xiaomi Redmi 9T, Samsung Galaxy M12, Pixel 3a, Pixel 6a

**Problem description**
I have noticed during testing PR #5344 that there is no way to add gif as picture in image widgets. I am able to add the same file on store version 2022.4.4

**Steps to reproduce the problem**

1. Open any image widget;
2. Try to add gif as image;
3. Except picture attached to widget you will see information that selected file is not a valid picture;
![131836763-6ded96f4-655a-4c18-8d59-f82ead4e98f8](https://user-images.githubusercontent.com/85225519/217226946-aaefceda-92d4-445d-9bbf-c26bb31f47f8.png)

**Expected behavior**
User should be able to upload gif into image widget/annotate widget.

**Other information**
file that I have used for testing:
![131836892-e7e8d774-3702-49ae-86bd-cb6f73200f7c](https://user-images.githubusercontent.com/85225519/217226969-6b8d6b24-e954-4d43-b91b-f254564d4e8e.gif)

**Comment by seadowg** [comment]
We should investigate how much effort this might be to fix. Let's timebox that to around 3 hours.

**Comment by grzesiek2010** [comment]
I took a look at the issue and upgrading [exifinterface](https://github.com/getodk/collect/commit/ea5e54ac1dbb40554506f2a88087b7380e8d0788) fixes it.
Unfortunately, it brings back this issue: https://github.com/getodk/collect/issues/5033. I think we should handle it in the way I originally proposed back then (not copying the whole exif data with elements that might hold outdated data) and just copying the most important exif attributes that does not change after scaling an image. It would be like this: https://github.com/getodk/collect/commit/56292510026e43c98eede9c8a12854647fafbcd8

What do you think?

**Comment by grzesiek2010** [comment]
I think this issue might be related https://forum.getodk.org/t/problem-downloading-images-from-odk-central/40228
So I guess that in some cases after scaling images we can attach them but they are still not valid entirely and can't be opened by some viewers. That's another argument in favor of doing what I said above.

@lognaturel @seadowg please share your thoughts.

**Comment by lognaturel** [comment]
Upgrading exifinterface and using a fixed "allow list" of exif attributes works for me.

**Comment by seadowg** [comment]
Yup let's go with that!
