### ISSUE TITLE
Hamcrest vs JUnit asserts

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5436]
#### Problem description
According to our [Code style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md) we should favor [Hamcrest](http://hamcrest.org/JavaHamcrest/) asserts over JUnit asserts for readability. However, for simple true/false/null checks, it might be better to use `assertTrue(something)`/`assertFalse(something)`/`assertNull(something)` instead of `assertThat(something, is(false))` which is verbose. We started this discussion in https://github.com/getodk/collect/pull/5395#discussion_r1093510079

**Comment by seadowg** [comment]
I'd still prefer to just use one assertion library. This definitely comes down to a personal preference, but the best way I can justify it is: it feels easier to me to only ever have to read (and write) one style of assertion.

**Comment by grzesiek2010** [comment]
Let's close this issue and stick with [Hamcrest](http://hamcrest.org/JavaHamcrest/)
