### ISSUE TITLE
Introduce Dependency Injection (Dagger)

### ISSUE THREAD

**Issue by nribeka** [getodk/collect#544]
With dependency injection I think it would make it easier to make more modular code and inject them as needed. Dagger I think also will help with cleaning up the odk code base.

Some discussion need to happen before we decided to try Dagger as Roboguice (one of the popular dependency injection for Android) was deprecating themselves a while ago. I think Dagger 2 borrow a lot of ideas from Google's Guice project (which I think was the base for Roboguice). So I think going through the documentation for Dagger, Guice and Roboguice would help us in this discussion.

**Comment by srsudar** [comment]
I think this will be a huge task. My experience with Dagger 2 is limited, having only used it in [this app](https://github.com/srsudar/GithubHotness).

I found this series very helpful to understanding Dagger:
* https://frogermcs.github.io/dependency-injection-with-dagger-2-introdution-to-di/
* https://frogermcs.github.io/dependency-injection-with-dagger-2-the-api/
* https://frogermcs.github.io/dependency-injection-with-dagger-2-custom-scopes/

I was surprised to find that Dagger wasn't that helpful in terms of facilitating unit testing, which surprised me. [This site](https://google.github.io/dagger/testing.html) from the Dagger people talks about how it can facilitate testing and explicitly says not to use it in unit testing.

My gut is that this might be too big a task for the tradeoffs right now. There's a very steep learning curve, and it really changes the structure of the codebase (unless I've been using it wrong, which could be). I loved the way my code looked when it was working, and I think it's a good idea for something to think about long term. In the near term I'd be more interested in getting things cleaned up and unit-testable without a DI framework.

Happy to be disagreed with, though. =)

**Comment by nribeka** [comment]
I agree this definitely about long term trajectory and it's going to be a lot of changes. I used only guice before and I really liked the way it works. Very simple and you can control elements of your project and just inject them when you need it.

From my experience DI compartmentalize the code really well. You can clearly see the layering of your application. Service to do a lot of business logic, view for presenting and displaying information.

**Comment by getsanjeev** [comment]
That will be really cool but very risky. 
@nribeka Should  not we think about using butter knife first to remove boilerplate. Making large changes to code base at once would not do much good.

**Comment by lognaturel** [comment]
@PatrickDale It would be interested to hear your perspective as well.

**Comment by heyjamesknight** [comment]
To bring this discussion back: I think Dagger (and possibly even moving towards "Clean") could definitely improve the code base, but I think we need to be aware of the cost involved. 

Although messy and complex, the current code base is relatively easy to understand and navigate, even for people new to Android. While Dagger will undoubtably improve how easy it is to understand and improve individual modules or classes, it will definitely harm the project's ease of entry as a whole. Dagger takes a decent investment to "get", and can seem like utter and magic for a month or more when someone is first learning it.

I think the best course of action would be to introduce it in a small part of the code base—somewhere we can see improvements without "Daggerifying" the whole project. I'd be happy to show an example of what could be done with the Widget subclasses if people think that would be valuable?

**Comment by dsrees** [comment]
As a new member of the ODK community, I still have plenty to learn about the code base, but I am tremendous supporter of using Dependency Injection whenever possible. Both Dagger and ButterKnife are wonderful libraries and would greatly clean up the codebase. I have extensive experience using both and would be more than happy to contribute my experience if needed to move towards a more DI centered project

**Comment by heyjamesknight** [comment]
I think we need a better understanding of how comfortable with DI/Dagger the community as a whole is. ButterKnife is a much more minor change so I'll leave that discussion for the related thread #550, but I think we should be relatively sure that moving towards Dagger won't alienate a large portion of current and potential contributors. It is a major change, and one that requires significant educational investment on the part of each contributor (which they may or may not have already undertaken).

**Comment by lognaturel** [comment]
I invite folks interested in this conversation to check out #1678 which introduces Dagger, ButterKnife and related dependencies in support of the geo widgets refactor. The idea is to address a particularly problematic part of the code first without needing to make big changes across the rest of the code base. There have also been more discussions in Slack.

**Comment by grzesiek2010** [comment]
We use Dagger and Butterknife so we can close. If I'm wrong please reopen @lognaturel.
