### ISSUE TITLE
Add tests for public integration points 

### ISSUE THREAD

**Issue by batkinson** [getodk/collect#545]
As discovered in #535, Collect has for some time exposed functionality that allows any android application to integrate with it. For both Collect developers and integrating applications developers, add reasonable test coverage for the major integration points so that internal changes do not unknowingly breaking integrating applications.

This is somewhat related to #74, since implicit Intents are one external integration point. Public ContentProviders are another.

**Comment by sanovikov71** [comment]
Hi, I would like to add some tests here.

**Comment by seadowg** [comment]
There has been some good progress on this recently (Content Providers are now tested for instance) so I think we can close this.
