### ISSUE TITLE
Location tracking snackbar interacts badly with Next button

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5454]
https://forum.getodk.org/t/hiding-the-location-tracking-message/40379

Can we indicate to Android that the Next/Prev button bar is part of the static content of the form filling screen so that snackbars should not cover it?

https://stackoverflow.com/a/58665768/137744 might have the answer.

Let's start with a quick (~1hr) spike and if it ends up being a small change, let's try to do it now, if not, let's update the issue with new information and possible next steps.

**Comment by grzesiek2010** [comment]
Yes it wasn't complex and as I think about it now I agree that this is something we should add https://github.com/getodk/collect/pull/5455
