### ISSUE TITLE
show password option in admin settings

### ISSUE THREAD

**Issue by pkarira** [getodk/collect#547]
There is no show password option in "Enter Admin Password" and "Change Admin Password" dialog boxes .

**Comment by pkarira** [comment]
@lognaturel should I start working on this ?

**Comment by lognaturel** [comment]
@pkarira That sounds good. You'll do a checkbox below the password field, right?

**Comment by pkarira** [comment]
yeah sure .

**Comment by lognaturel** [comment]
Closed by #451. @pkarira, for future reference, it seems the keywords to close issues have to be in the pull request description or a commit message to automatically close the corresponding issue! (I just learned that)
