### ISSUE TITLE
Dagger init implementation needs to be updated

### ISSUE THREAD

**Issue by kalyncoose** [getodk/collect#5471]
https://github.com/getodk/collect/blob/e8d2ebddc9f7f3a9c43822a3a1a32ea9b94ab304/collect_app/src/main/java/org/odk/collect/android/external/FormsProvider.java#L110
The current implementation of initializing Dagger is incorrect, as a Cursor query consistently returns `null` on first query attempt due to this initialization method. Please see this [StackOverflow issue](https://stackoverflow.com/questions/23521083/inject-database-in-a-contentprovider-with-dagger/44413873#44413873) which describes the correct implementation, with the intended outcome that we will never accidentally receive a `null` on first Cursor query.

**Comment by seadowg** [comment]
Hey @kalyncoose 👋!

> a Cursor query consistent returns null on first query attempt due to this initialization method.

Are you able to provide a test or reproduction steps that demonstrate this? As far as I'm aware, we don't make any queries against `FormsProvider` until `Application#onCreate` has been called (where we create our Dagger components). If I'm right about that (which I could definitely not be), performing field injection on `FormsProvider` at the start of each query method should be fine. 

As you'll see, we reference the same SO post you've linked to in [a comment above `deferDaggerInit`](https://github.com/getodk/collect/blob/e8d2ebddc9f7f3a9c43822a3a1a32ea9b94ab304/collect_app/src/main/java/org/odk/collect/android/external/FormsProvider.java#L98), but we've opted to go with the "on demand" injection approach over moving to component creation in `ContentProvider#attachBaseContext`. I'm guessing that was so we didn't have to rework the component creation in our `Application` class (`Collect`).

**Comment by kalyncoose** [comment]
Hi @seadowg, I apologize I was not able to respond sooner. My teammate has the technical knowledge on this issue so I am pasting his response below:

### Preface
We have a React Native app (`MyApp` for example) that has the proper query permissions and activity intents setup for communicating between our app and ODK Collect (when both are installed on the device). Aside from the activity, we have a separate Kotlin module that has the function for using the Android `Cursor` and `Context` to obtain information from ODK Collect.

Query:
```xml
<queries>
    <package android:name="org.odk.collect.android" />
</queries>
```

Activity:
```xml
<activity
        android:name=".odk.ODKDataExchangeActivity"
        android:exported="true">
    <intent-filter>
        <action android:name="${packageName}"/>
        <category android:name="android.intent.category.DEFAULT"/>
    </intent-filter>
</activity>
```

Module:
<details>
  <summary>Click to expand...</summary>

```kotlin
import android.net.Uri
import android.util.Log
import android.database.Cursor
import android.content.Context

val ODK_FORMS_CONTENT_PROVIDER: String = "content://org.odk.collect.android.provider.odk.forms/forms"
val MAX_RETRIES: Int = 2
val formId: String = "odk_survey_name"

private fun getFormIdFromOdkProvider(formId: String?): Int? {

      // Validation
      if (formId == null) {
          Log.d("MyApp", "[getFormIdFromOdkProvider] formId is null")

          return null
      }

      // Set cursor query's configuration.
      val projectionList = arrayOf(
          "_id",
          "jrFormId",
          "jrVersion",
          "displayName",
          "date"
      )
      val selectionClause = "jrFormId=?"
      val selectionArgs = arrayOf(
              formId
          )
      val sortOrder = "date DESC"

      // Use ContentResolver to query ODK Collect's Content Provider.
      for (i in 1..MAX_RETRIES) {
          try {
              ctx.getContentResolver().query(
                  Uri.parse(ODK_FORMS_CONTENT_PROVIDER),
                  projectionList,
                  selectionClause,
                  selectionArgs,
                  sortOrder
              )?.use { c: Cursor ->
                  if (c.moveToFirst()) {
                      c.columnNames.filter { it == "_id" }.firstOrNull().let { idColumn ->
                          return c.getString(c.getColumnIndexOrThrow(idColumn)).toIntOrNull()
                      }
                  }
              }
              Log.d("MyApp", "[getFormIdFromOdkProvider] cursor is null or empty")
          } catch (e: Exception) {
              Log.e("MyApp", "[getFormIdFromOdkProvider] Error: $e")
          }
      }

      return null
  }

```
</details>

### Module Explanation

1. `MyApp` calls `getFormIdFromOdkProvider()`, passing in the name (i.e. `formId`) of the survey that `MyApp` wants to open.
   * If the form is found in ODK Collect's `FormProvider`, `getFormIdFromOdkProvider()` returns the local form's ID found within ODK Collect's DB (or `null` if not found).
1. Once `MyApp` has the URI of the local form, it sends an intent to "Edit" a blank form by that URI.
1. A retry mechanism was added to handle a `NullPointerException` that appears to be thrown on the **first** `cursor.query()` call made after resetting / refreshing the local ODK Collect's DB Form records.

### Steps to Reproduce
Assuming you had an Android app like `MyApp` installed and ODK Collect:

1. In ODK Collect, delete all local copies of the form your app is interested in querying against (using Project Settings --> Project Management --> Reset --> Blank Forms). 
1. Then, refresh the list of blank forms in ODK Collect, **AND** don't open any of the forms in ODK Collect.
1. Now, have your app attempt to query ODK Collect's Form Provider by the `jrFormId`. 
   * On the first query attempt, a NullPointerException will most likely be thrown. 
   * However, without any changes to anything in your app or in ODK Collect, a 2nd query attempt will return the `jrFormId` (as long as it exists in the ODK Collect DB).

### Conclusion
I apologize I cannot give you an exact reproduction with the dev version of ODK Collect and a sample Android app. By reading through the code and explanation, does the issue make sense? Is this scenario causing unintended behavior inside ODK Collect - where some new code could help mitigate it?

I appreciate all of your community's time and effort into this. Thanks!

**Comment by seadowg** [comment]
> Then, refresh the list of blank forms in ODK Collect

I'm not sure what you mean by this. How are you getting forms onto the device? Are you using a server or pushing them with ADB? What form management setting are you using?


> On the first query attempt, a NullPointerException will most likely be thrown.

Do you have an example stack trace for this? Does the `NullPointerException` get thrown in Collect's code or yours?

**Comment by King-Bahb** [comment]
Our forms are stored in ODK Central. We refresh the forms within ODK Collect on demand from the client.

The `NullPointerException` is thrown by ODK Collect.

**Comment by seadowg** [comment]
@King-Bahb if possible, could you please post a stack trace for the crash?

**Comment by seadowg** [comment]
I'm going to close this as we haven't heard anything for a while, but please feel to reopen if you're still experiencing the problem!
