### ISSUE TITLE
Broken image file is still visible in the hierarchy view and there is possibility to send submission with this image.

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5480]
**ODK Collect version**

the master version 4ced1468b013d976b175bba0394631cd0256113e

**Android version**
Probably all

**Device used**
Redmi 9T, Galaxy M12, Galaxy A32, Google Pixel 3a and 6a

**Problem description**

Issue noticed during testing #5433. I was able to send submission with broken.png file and download it from Central

**Steps to reproduce the problem**

- Install the ODK Collect and download a form with an Image Widget;
- Try to attach an image that is broken like: ![broken](https://user-images.githubusercontent.com/85225519/224014855-2af51839-528d-4212-af68-07af503219ad.png)
- The image should not be attached and there should be an error message "selected file is not a valid image";
- Go to the hierarchy view (The .png number will be visible);
- Save Form and send Submission to Central;
- Open Central, navigate to Form submissions, Select Image_Widget in Columns Shown and notice that the user is able to download an Image_widget .png file;
- Download and try to open broken file;
- "Could not load image" error will be visible.

**Expected behavior**

- Broken image should not be visible in the hierarchy view
- Broken image should not be send to Central

**Other Information:**

![Screenshot_20230309-125713](https://user-images.githubusercontent.com/85225519/224016294-93427809-32ae-4135-892c-e7b70194410d.png)

**Comment by seadowg** [comment]
I'm actually not sure if we should fix this or not. It feels like there's always a risk that Collect might have a problem displaying an image that's actually "valid" and so blocking uploads could prevent people from submitting data.
