### ISSUE TITLE
Do not start FormEntryActivity if the intent data is null

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5484]
#### Problem description
We have merged this pr: https://github.com/getodk/collect/pull/5475 to avoid NPEs if the intent data is null. According to the discussion in the pr it would be better to improve that solution and avoid starting `FormEntryActivity` at all in this case. See: https://github.com/getodk/collect/pull/5475#discussion_r1129733979

**Comment by seadowg** [comment]
I'm going to take this out of v2023.2, as it doesn't feel like a high priority change to me. Happy to discuss, though! Definitely worth just changing if we end up working on something related, though.

**Comment by grzesiek2010** [comment]
This has been fixed in https://github.com/getodk/collect/pull/5542
