### ISSUE TITLE
Adding and trying to mark up a gif file in Annotate widget causes a crash

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5485]
**ODK Collect version**

present after merging PR#5465

**Android version**

10, 13

**Device used**

Redmi 9T, Galaxy A32

**Problem description**

It is possible to add a gif file in the Annotate widget and after clicking the "Markup Image” button there is a crash. On the master version 9440f490211adb834f490893ba33c13a4115746c after adding the gif file there is information that the file is not valid and there is also a crash after trying to mark up the image as mention in the issue https://github.com/getodk/collect/issues/5479

**Steps to reproduce the problem**
1. Go to Annotate widget in All widgets form. 
2. Tap "Choose image" button. 
3. Add the gif file from the link.
https://drive.google.com/drive/folders/1IeuxQZU8Sw90PAOnTRlMToB3Wp_LuCoN?usp=share_link 
4. Tap "Markup Image" button.

**Expected behavior**

The app shouldn’t crash.

**Comment by seadowg** [comment]
I'm not sure if we can (or should) allow marking up GIFs, or if we should be blocking them here.

**Comment by lognaturel** [comment]
What happens with a non-animated gif?

**Comment by dbemke** [comment]
I uploaded non-animated gif file and after tapping "Markup" button there is a crash.
![Sunflower](https://user-images.githubusercontent.com/56479916/224938854-6b8f2734-c693-4a10-b363-f06664a69e1f.gif)

**Comment by grzesiek2010** [comment]
I think we should ignore gifs and only allow png/jpg/jpeg.

**Comment by seadowg** [comment]
We should make it so that they aren't able to select `.gifs`.
