### ISSUE TITLE
Make constants in AdminKeys final (as in PreferenceKeys)

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#549]
To be true constants, all of the string values declared in `AdminKeys` should be final.

**Comment by Bastiantheone** [comment]
Can I work on this one?

**Comment by J2112O** [comment]
I am brand new at contributing but would like to get involved and if no one else does this one, I would like to try. Thank you.

**Comment by lognaturel** [comment]
@Bastiantheone Since you've already successfully completed a "quick win", let's leave this one for @J2112O! I know you're ready for bigger issues! 😊

**Comment by J2112O** [comment]
Thank you. I will get on this.

**Comment by J2112O** [comment]
@lognaturel I am sorry but I am working on and trying to fix my system which is broken at the moment. By all means, let someone else have this as I am not sure when I will be up and running. I can always come back and get involved in the future when my system is up and functioning. Sorry about that. Thank you.

**Comment by royrivnam** [comment]
@lognaturel can i work on this one..??i want to try this one...

**Comment by lognaturel** [comment]
Thanks, @J2112O. If you're having problems with the build, do come talk to us in #collect-code in the Slack (http://slack.opendatakit.org). @royrivnam please go ahead.

**Comment by royrivnam** [comment]
@lognaturel can u give a lead on what exactly i need to solve...by admin keys do you mean the constant variables defined in the admin classes??just give me a lead please..as far as i have understood i changed the constants in Admin related classes to true constants...am i doing the right thing??

**Comment by Ishmeetsingh97** [comment]
Hi, @lognaturel Can i work on it ?

**Comment by lognaturel** [comment]
@royrivnam I apologize for not seeing your comment earlier. Yes, that's correct, please finish it up and submit a pull request.

**Comment by royrivnam** [comment]
okay i am submitting another pull request as soon as possible..sorry for not seeing the message earlier... but its showing the issue has been closed so should i submit another pull request again... @lognaturel

**Comment by royrivnam** [comment]
@lognaturel new pull request submiited
