### ISSUE TITLE
Rework form exit modal to provide last saved date/time and to use new draft language

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5490]
## New update 
After iterating on the designs, we have come up with 3 different exit modal states below. This story will also include updating the language on the main menu, as we are introducing save as a draft terminology. 

### **Exit modal states**
1. Unsaved changes 
2. Previously saved changes 
3. When "save as draft" is disabled 

<img width="1266" alt="Screenshot 2023-05-05 at 4 40 13 PM" src="https://user-images.githubusercontent.com/7871340/236585227-4c3b69f4-fd8d-48ca-b6e1-11fa1724c791.png">

We want to highlight the primary CTA, which is to 'save as draft' or 'continue editing' their form. We also made the decision to put 'discard changes' at the top to help prevent anyone from accidentally tapping it and included icons to avoid any confusion. 

[Figma link](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=790%3A38027&t=IAjtZgVlbpFuvpNe-1)

### **Main menu** 
The new language is in [Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=531%3A22316&t=IAjtZgVlbpFuvpNe-1). We also want to make sure everything is sentence case. 

## Archive [keeping this for reference]
#5474 makes small language improvements to help users make the right decision on the form exit modal. We should also:
- show the last save time
- use the word "draft" in the save case
- consider an additional layer of confirmation as [suggested on forum](https://forum.getodk.org/t/improve-ui-to-reduce-mistaken-selection-of-ignore-changes/19573). Side note: a couple of weeks ago I got a report from a user that one of their staff members panicked and /saved/ when they meant to /discard/. So this exit path can cause problems in both cases. I'm somewhat hopeful that we can improve both 
- ideally we can keep the save and delete icons. I don't think there's really a Material Design way to do that. Anecdotally they did help reduce errors and it feels in line with where we're going with the UI.

### Previously saved proposal:
Save changes?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   X

This form was last saved on **Jan 3, 2023 at 23:23**. 
Do you want to save changes made since then?

🗑 Discard &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 💾 Save

### New form proposal:
Save form?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; X

This form has never been saved. Do you want
to save it as a draft?

🗑 Discard form  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 💾 Save draft

## Alternatives

An alternative we've considered is getting rid of this decision point. If Collect is configured such that drafts can be saved, we could always save the draft. If drafts can't be saved, we could have a confirmation to discard. The downside with that is that we wouldn't support the case where someone has opened a draft for editing, made some modifications, and realized those modifications were wrong in some way.

CC @alyblenkin

**Comment by alyblenkin** [comment]
It's unfortunate that Material doesn't really support the use of icons in modals, but I agree they are very helpful when scanning information! I think it's consistent with the visual hierarchy we are working towards with the menu redesign as well. 

This is similar to what we designed recently in the screenshot below. Note: I also use 'cancel' instead of the 'X' to hopefully prevent people from a mistake. However, I don't currently have a design for a header and body text, as you have above. We could use the [MUI dialogs](https://m3.material.io/components/dialogs/overview), like we are doing with the finalize/send confirmation, but we would need to customize it to add the icons. 

<img width="866" alt="Screenshot 2023-03-14 at 1 36 14 PM" src="https://user-images.githubusercontent.com/7871340/225133635-15356c58-bece-498a-bd0e-508a0069e76b.png">

I think we would want to keep this as a decision point to ensure we are still designing for folks that are editing a draft, making modifications, notices that are wrong and deciding they don't want to save. I don't know how often that happens, but I can certainly see it being a use case! Another option is having a snackbar that allows the user to "undo" the action if they didn't mean to discard the form. 

![Snackbar_undo](https://user-images.githubusercontent.com/7871340/225134392-7d297c36-1d63-4da2-ade7-e74f112fa280.png)

**Comment by alyblenkin** [comment]
Adding this here for the discussion this morning 
<img width="345" alt="Screenshot 2023-03-21 at 8 33 56 AM" src="https://user-images.githubusercontent.com/7871340/226657660-a153d717-8bde-4088-b00e-8c5724f8af0c.png">

**Comment by lognaturel** [comment]
Similar from Discourse when you're composing and click something that also would open the composition UI or you click "close":

<img width="330" alt="Screen Shot 2023-03-21 at 8 59 19 AM" src="https://user-images.githubusercontent.com/967540/226667209-48714336-9840-4a8b-8a5b-dec3d2fd3ebd.png">

**Comment by alyblenkin** [comment]
I have too many combinations now 😅! One thing I’ve been thinking about is what type of behaviour do we want to encourage? Discarding or saving? I also want to make sure we don't overwhelm people with too many button choices (like having "continue editing" and "X" when they do the same thing).

### Proposals

<img width="1061" alt="Screenshot 2023-03-21 at 5 15 05 PM" src="https://user-images.githubusercontent.com/7871340/226769910-83b0c6e0-0752-4433-b116-6a59e77a16a8.png">



### **Other examples** 
- Instagram prompts to "discard changes" 
- LinkedIn prompts to "save as draft"
- Twitter prompts to "save tweet"
- Discord has an open question, unlike the others, but the primary action is to discard 
- Google calendar prompts to "discard changes"

<img width="876" alt="Screenshot 2023-03-21 at 4 52 38 PM" src="https://user-images.githubusercontent.com/7871340/226767511-2ea6806c-03e2-4f04-8bbc-2268d0ba292c.png">

I also stumbled upon this gem 
https://brianlovin.com/writing/design-to-save-people-from-themselves

**Comment by lognaturel** [comment]
> what type of behaviour do we want to encourage?

In what I've seen, saving is much more common. The implications of discarding when saving is the right thing to do are typically worse (minus the example I mentioned in the original issue).

I like the three explicit actions and I find the icons helpful. It feels to me like putting Discard on top would be less dangerous. That is, I think the topmost button will be hardest to hit accurately and that if you misstap, you're more likely to hit the one below the one you wanted to tap.

I believe we've been moving towards short questions as dialog titles. I like "Discard xyz?" the most.

For the New unsaved changes, I think we want to stick with "Discard form?" which is new language we've introduced. In that case, the form has never been saved and will be entirely discarded. I find the date helpful but don't feel super strongly about it.

I think "Discard changes?" is really clear for the previously-saved case.

**Comment by alyblenkin** [comment]
Thanks for the feedback! I agree; having "Discard xyx" at the top with the icons will help the user avoid making mistakes. I've also flipped the order of the buttons, so discard is at the top as well. 

The timestamp might be helpful as a reference point, so I think we should include it. This would be a good thing to test eventually, but I don't think it will negatively impact the experience including it. 

**New proposal:**

<img width="464" alt="Screenshot 2023-03-27 at 9 00 07 AM" src="https://user-images.githubusercontent.com/7871340/227997421-bbe866d7-4418-4755-bf3c-9e11c5f31e81.png">

**Comment by alyblenkin** [comment]
I wanted to come back to this one. Let me know what you think about the proposal above @lognaturel. The screens are at the bottom of the "Dev ready" page - https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=790%3A38250&t=SoSD4aJLJLL3Kipd-1

**Comment by alyblenkin** [comment]
Note that I've updated the buttons on this screen. They are now outlined/ filled instead of elevated, like the main menu.

**Comment by seadowg** [comment]
@alyblenkin we currently switch the text for "Discard changes" to "Discard form" in case **1** (unsaved changes). Do you think we want to keep doing that or do you think it doesn't make sense any longer? Personally, it feels like it still adds value.

**Comment by alyblenkin** [comment]
@seadowg I think it still makes sense and adds value!
