### ISSUE TITLE
"Discard Form" translation

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5497]
#### ODK Collect version
2023.1 Beta 4
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
It looks as if after changing the "Ignore Changes” to "Discard Form” the translation is applied from the previous version. I’m not sure about all the languages but in Polish "Discard Form” is translated so that it means ignore/discard changes (not form). "Discard changes” is not translated in any of the languages.
#### Steps to reproduce the problem
1. In settings choose a language other than English.
2. Open any form.
3. Tap the device back button.
4. Check the translation of "Discard Form”.

**Comment by lognaturel** [comment]
That’s expected — translations are only updated right before release.
