### ISSUE TITLE
Location values are not present in xml instance file in forms: setlocation-action-with-repeats.xml, setlocation-action-value-changed.xml.

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5511]
#### ODK Collect version
2022.4.4, 2023.1 Beta 4
#### Android version
10, 13
#### Device used
Redmi T, Pixel 6a
#### Problem description
Location values are not present in xml instance file in forms: setlocation-action-with-repeats.xml, setlocation-action-value-changed.xml.
#### Steps to reproduce the problem
1. Fill in the forms.
[setlocation-action-value-changed.xml.txt](https://github.com/getodk/collect/files/11038490/setlocation-action-value-changed.xml.txt)
[setlocation-action-with-repeats.xml.txt](https://github.com/getodk/collect/files/11038491/setlocation-action-with-repeats.xml.txt)
2. Go to Form Manager and open the instance folder with the xml file of that form.
3. Check the location
#### Expected behavior
Location should be present in the instance file.

**Comment by lognaturel** [comment]
These look like they're just outdated forms! We initially named the action `setlocation` but right before release we realized `setgeopoint` would be more specific. I think if you use `setgeopoint`, things should work. Those forms come from JavaRosa tests.

**Comment by seadowg** [comment]
Closing this, but please reopen if you disagree @dbemke or @lognaturel.
