### ISSUE TITLE
The app is crashing after entering the hierarchy view

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5513]
**ODK Collect version**
v2023.1 Beta 4, v2022.4.4

**Android version**
10, 13

**Device used**
Redmi 9T, Pixel 6a

**Problem description**
There is a crash after entering the hierarchy view in the indefinite.xml form

- Start filling the form:
[indefinite_repeat_and_remove_already_selected_from_species_list.xml.txt](https://github.com/getodk/collect/files/11038834/indefinite_repeat_and_remove_already_selected_from_species_list.xml.txt)
- Enter the hierarchy view;
- The app will crash.

https://user-images.githubusercontent.com/85225519/226872285-6fb215da-0dee-4b09-bf1a-7eac6336b02f.mp4

**Expected behavior**
There app should not crash

**Other information**

- In the version 2022.4.4 the error is also reproducing;
- There is no dialog about crash after restoring the app.

**Comment by lognaturel** [comment]
You have an old version of the form with a form design issue. Please update to the one from https://forum.getodk.org/t/infinite-loop-and-dynamically-delete-already-selected-options-from-list/25902/12?u=ln
