### ISSUE TITLE
in Geoshape/trace OSM adds points when tapping "-” and "+” buttons

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5522]
#### ODK Collect version
2022.4.4, the master version
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
When Osm is set as a source of maps in Geoshape and Geotrace widgets in placement by tapping it is possible to add points by tapping on the "-” and "+” zoom buttons
#### Steps to reproduce the problem
1. Set OSM as a source of maps.
2. Go to All widgets form to Geoshape/Geotrace widget.
3. Open the map  and choose placement by tapping as an input method.
4. Tap to add a point.
5. When "-” and "+” zoom buttons appear at the bottom of the map, tap one of the buttons.
6. Check if a point was created.

https://user-images.githubusercontent.com/56479916/227896221-3f0534c8-2be2-4fa0-808f-06607b35412f.mp4

#### Expected behavior

There shouldn't be +/- zoom buttons in OSM

**Comment by seadowg** [comment]
We could potentially just remove the buttons (as no other provider has them), but we should look into if they help people or not.

**Comment by grzesiek2010** [comment]
I'm pretty sure there will be someone unhappy with this decision but I think we should try to keep all three map engines consistent so if we do not have buttons for zooming in google and mapbox then let's remove it from osm.
