### ISSUE TITLE
The acknowledge mark gets deselected if don’t keep activities is on and the user minimizes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5523]
#### ODK Collect version
2022.4.4, 2023.1 Beta 5
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
I reproduced the case mentioned https://forum.getodk.org/t/entered-odk-collect-data-gets-lost-after-a-while/40518.
The acknowledge marks gets deselected when don’t keep activities is on and the user minimizes the app.
#### Steps to reproduce the problem
Scenario 1:
1. In device settings enable "don’t keep activities”.
2. In Collect go to Diary App GOLIAT form.
[ODK Diary App_GOLIAT_07022023.xlsx.txt](https://github.com/getodk/collect/files/11077420/ODK.Diary.App_GOLIAT_07022023.xlsx.txt)
3. Select "OK. Please Continue” in Start Measuring part (don’t select both).
![DappGoliat](https://user-images.githubusercontent.com/56479916/227914352-ecad5058-59fb-4d31-bec8-94b462d37546.png)
4. Minimize the app, switch to a different app and go back to Collect.

In this case the answer will get deselected.

Scenario 2:
1. In device settings enable "don’t keep activities”.
2. In Collect go to Diary App GOLIAT form.
3. Select "OK. Please Continue” in Finish Measuring part (don’t select both).
4. Minimize the app, switch to a different app and go back to Collect.

In this case after going back to the app, both parts (Start and Finish) will be selected.

#### Expected behavior
Answers shouldn’t change.
#### Other information 
If the user adds a repeat and then follows the steps, the answers that get selected/deselected after minimizing the app are in the current repeat opened (selected answers in previous repeats will stay as the user chose).
If the user selects both in Start and Finish Measuring then after minimizing both stay selected.

**Comment by grzesiek2010** [comment]
@dbemke are you also able to reproduce it with the `All Widgets` form?

**Comment by dbemke** [comment]
I checked. In All widgets if don't keep activities is enabled and answer in Trigger widget is selected, after minimizing the app the answer stays selected.
