### ISSUE TITLE
Values in range widgets a in field list are changed after minimizing the app if "don’t keep activities” is enabled

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5530]
#### ODK Collect version
2023.1.0, the master version
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
Values shown on axis in range widgets a in field list are changed after minimizing the app if "don’t keep activities” is enabled.
![allfieldlist](https://user-images.githubusercontent.com/56479916/228236048-fac1e8d9-8b82-46ea-929e-7dc5db4a7a0d.png)

#### Steps to reproduce the problem
1. In device settings enable "don’t keep activities”.
2. Go to All widgets field list form.
[all-widgets-fieldlist.xml.txt](https://github.com/getodk/collect/files/11089258/all-widgets-fieldlist.xml.txt)
3. Fill in the answers until you can choose value in the range widgets.
4. Minimize the app, go to a different app and go back to Collect.
5. Check the marked values in the range widgets.
#### Expected behavior
Chosen values should be shown correctly on the axis.
#### Other information 
In All widgets form- range widgets (without field list) if the user follows the steps the selected value isn’t changed.

**Comment by grzesiek2010** [comment]
What about v2022.4.4? Is this a regression?

**Comment by dbemke** [comment]
The issue is also present in v2022.4.4

**Comment by grzesiek2010** [comment]
It seems to be a broader issue that might be related to other widgets too. We have this issue for the Range widget and [this one](https://github.com/getodk/collect/issues/5523) for the Trigger widget.
It looks like we do not handle properly the case where there is more than just one widget of the same type on one page.
@dbemke @srujner when you have some free time please try to do the same with other widgets.

**Comment by seadowg** [comment]
@getodk/testers did you get a chance to explore if this was a problem for any other widgets?

**Comment by srujner** [comment]
> @getodk/testers did you get a chance to explore if this was a problem for any other widgets?

@seadowg Not yet, but I will have some time to test it today or tomorrow.

**Comment by srujner** [comment]
@seadowg I was not able to reproduce it on Android 12 (Google Pixel 3a) and 13 (Google Pixel 6a), but I found a different issue with Range Decimal Widget, after Minimizing the app, going to a different app and going back to the Collect the value in Range Decimal Widget ignores 0.5, it also reproduces on Android 10:
![Screenshot_20230508-121015](https://user-images.githubusercontent.com/85225519/236798286-9f1668b7-3388-4571-b1f2-060b65eb889e.png)
