### ISSUE TITLE
Missing event in Track Changes audit log when the user exits the form by going to project settings

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5551]
#### ODK Collect version
2022.4.4, the store version 2023.1.2, the master version 1f9155c7f1f6c1d91532993fd45cc9b68270124a
#### Android version
10, 11, 13
#### Device used
Redmi 9T, Galaxy M12, Galaxy A32
#### Problem description
In a Track Changes form when the user exits the form by going to project settings (and e.g. changes the theme) and later on saves the form, the question on which the user exited the form is missing in the audit log. In View Sent Form all the answers are present. The same issue appears when the user kills the app instead of going to project settings.
#### Steps to reproduce the problem
1. Go to Track Changes Reason 2q form.
[track-changes-reason-on-edit-2q.xml.txt](https://github.com/getodk/collect/files/11232991/track-changes-reason-on-edit-2q.xml.txt)
2. Fill the first and the second question.
3. While on the second question page, go to the Project setting and change the theme of the app.
4. Go to Fill Blank Form and reopen the form.
5. While on the hierarchy view, tap "Go to end”.
6. Finalize and save the form.
7. Enter and save the reason for changes.
8. Go to audit log file and check if both answers are present in the audit log.
#### Expected behavior
All answers should be in the audit log.

**Comment by seadowg** [comment]
@dbemke does this need to be a Track Changes Reason form or do we have the same problem with any form that logs question values?

**Comment by dbemke** [comment]
I tired with Audit Test form and the last question event on which the form was exited is not present in the audit log but visible in "Sent" when you view the form.

**Comment by seadowg** [comment]
Great! So we can change the issue description so it's any form with `track-changes=true` rather than forms using `track-changes-reasons`?
