### ISSUE TITLE
RTL Select widgets text aligment

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5555]
#### ODK Collect version
the store version 2023.1.2, the master version 1f9155c7f1f6c1d91532993fd45cc9b68270124a
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A23
#### Problem description
When RTL language is applied in the app in Select widgets it looks as if radio buttons are aligned to the right, but the text is aligned to the left. The screenshot shows selects with LTR and RTL languages.

![ltrRTLselects](https://user-images.githubusercontent.com/56479916/233051882-d9be4dcf-85c0-4208-8fb5-d23f53b1a24a.png)

#### Steps to reproduce the problem
1. Go to Settings→ User Interface→ Language and choose a RTL language.
2. Go to All widgets form.
3. Go to select widgets.

**Comment by grzesiek2010** [comment]
This might be fully/partly fixed by https://github.com/getodk/collect/pull/5553
