### ISSUE TITLE
Save as draft button is red on Android 5.1

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5582]
#### ODK Collect version
https://github.com/getodk/collect/commit/fce19daf231d775a899ef915a5e3a1e7d071a985

#### Android version
5.1

#### Device used
Samsung Galaxy Tab A

#### Problem description
![Screenshot_20230512_133449](https://github.com/getodk/collect/assets/967540/d91a86ba-d015-4f10-a114-ce62446d771f)

#### Steps to reproduce the problem
Go to the form end screen in Android 5.1

#### Expected behavior
Not red!

#### Other information 
I think we'll probably close this as "Won't fix" but I wanted to have a record of it. I was surprised that I couldn't find an issue like this, I'm pretty sure we've encountered it before.

**Comment by seadowg** [comment]
Closing this as "won't fix"
