### ISSUE TITLE
Adding a notification badge to the main menu 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5600]
### Problem description
Given that the language on the main menu has changed from "Send Finalized Form" to "Ready to send", we are concerned that people may not notice that an action is needed if auto-send is turned off. We want to gently nudge users to send their forms. The snackbar will help with this, but it's not enough of a reminder.

<img width="933" alt="Screenshot 2023-05-23 at 10 52 58 AM" src="https://github.com/getodk/collect/assets/7871340/8aeb1233-42e0-4a56-95fd-5e5d0ecaa077">

We decided to split up these designs into two stories. Here is the other issue for ["Ready to Send"](https://github.com/getodk/collect/issues/5605#issue-1722537178).

[Figma link](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1617%3A58374&t=KuBo4bWoKO3PgNoS-1) to updated designs. [Previous iterations](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1521%3A61447&t=KuBo4bWoKO3PgNoS-1) can be found here. 

### Solution
**Main menu** 
- Add a blue badge or dot to the send icon to indicate an action is needed.
- The badge goes away once they've sent all the forms. We hope it's not too visually distracting because it's not red.
- "Ready to send" text is bold when they have forms to send. 

### Notes

You can add a badge to an icon use Material Component's `Badget Drawable`, although it is a little funky as you need to add it after the view tree is laid out like so:

```kotlin
icon.viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
    override fun onGlobalLayout() {
        val badgeDrawable = BadgeDrawable.create(context);
        badgeDrawable.backgroundColor = getThemeAttributeValue(context, R.attr.colorPrimary)
        BadgeUtils.attachBadgeDrawable(badgeDrawable, icon);

        icon.viewTreeObserver.removeOnGlobalLayoutListener(this);
    }
})
```

**Comment by alyblenkin** [comment]
One other alternative I wanted to put out there

<img width="409" alt="Screenshot 2023-05-19 at 4 40 34 PM" src="https://github.com/getodk/collect/assets/7871340/282d27a1-ea08-4462-af0f-6cb9c73860f6">

**Comment by yanokwa** [comment]
I like "Last successful send:", but "Last sent:" would be shorter and, IMO, still be understandable. 

I think the blue background on the message attracts too much attention. I'd put the "Last form successfully sent" in the style and location of the "You have 4 forms ready to send" (and don't include that message).

**Comment by alyblenkin** [comment]
> I like "Last successful send:", but "Last sent:" would be shorter and, IMO, still be understandable.

I agree with the shorter message looking at this again.

> I think the blue background on the message attracts too much attention. I'd put the "Last form successfully sent" in the style and location of the "You have 4 forms ready to send" (and don't include that message).

The goal is to get their attention so they take action. I would be more concerned if this blue message were on the main menu because that would be very distracting. The text without an icon or accent colour to draw the eye will make it easy to miss. It would be great to test this with users, but people tend to skip over plain text. 

I wrote, "You have 4 forms ready to send" because I want it to be action-oriented. If they see a blue dot, they are going to want to figure out why. When they land on the next screen, seeing "Last sent:" doesn't tell them what action to take. I've designed a few other alternatives that still create a visual hierarchy. 

<img width="1227" alt="Screenshot 2023-05-22 at 9 12 32 AM" src="https://github.com/getodk/collect/assets/7871340/90a1d903-e59d-4f69-9704-55156d508782">

**Comment by yanokwa** [comment]
I hear you on the action orientedness. 

v5 resonates the most with me. It's eye-catching without being distracting. 

I'd also change the language to "Last form sent: 2 days ago" because then it flows naturally to say "4 forms ready to send"

**Comment by alyblenkin** [comment]
I think that one is my favourite too. Good point on the language – I think this flows much better 

<img width="213" alt="Screenshot 2023-05-22 at 9 32 12 AM" src="https://github.com/getodk/collect/assets/7871340/f2dff92c-6ea5-42a2-bc5f-ea5c666ead9b">

**Comment by lognaturel** [comment]
@seadowg Pointed out a few things: 
* the main menu and sending screen changes can become two separate issues (at some point) and don't have to be in the same release. 
* another option might be to revert the language to verb phrases. We could go back to "Send form" and "View sent". 
* we do hope manual sending will get phased out over time (though it's in broad use currently).
* in some workflows, "ready to send" might not be as meaningful. I think it's always an indicator of work completed so it does feel important. As @seadowg pointed out, we could make it configurable if we find out that there's a need to turn it off.

My current preference would be to add the nudge on the main menu for this release and keep "Ready to send".

**Comment by alyblenkin** [comment]
Great feedback @seadowg @lognaturel 

> * @seadowg Pointed out a few things:
> * the main menu and sending screen changes can become two separate issues (at some point) and don't have to be in the same release.

I can split it out into two issues. 


> * another option might be to revert the language to verb phrases. We could go back to "Send form" and "View sent".
> * we do hope manual sending will get phased out over time (though it's in broad use currently).

We could go back to the old language; however, we made some of these decisions to move us in the direction of phasing out manual sending, as you mentioned. It felt like too big of a jump to make auto-send the default right now based on all the feedback, but my hope is that by keeping this language, we can drive towards this new behaviour. 

> * in some workflows, "ready to send" might not be as meaningful. I think it's always an indicator of work completed, so it does feel important. As @seadowg pointed out, we could make it configurable if we find out that there's a need to turn it off.
> 
It's a good point that it could be configurable, and it's true this won't work for all flows - it's so tough! 

> My current preference would be to add the nudge on the main menu for this release and keep "Ready to send".

I agree with adding this small nudge and keeping "Ready to send" for now.

**Comment by alyblenkin** [comment]
Great feedback @seadowg @lognaturel 

> * @seadowg Pointed out a few things:
> * the main menu and sending screen changes can become two separate issues (at some point) and don't have to be in the same release.

I can split it out into two issues. 


> * another option might be to revert the language to verb phrases. We could go back to "Send form" and "View sent".
> * we do hope manual sending will get phased out over time (though it's in broad use currently).

We could go back to the old language; however, we iterated on this a lot to land on something that felt meaningful based on all the user feedback in the survey. 

And it's a good point about manual sending getting phased out eventually. It seemed like too big of a jump to make auto-send the default based on all the feedback, but I think we are moving in that direction with a lot of these changes. 

> * in some workflows, "ready to send" might not be as meaningful. I think it's always an indicator of work completed, so it does feel important. As @seadowg pointed out, we could make it configurable if we find out that there's a need to turn it off.
> 
It's a good point that it could be configurable, and it's true this won't work for all flows - it's so tough! 

> My current preference would be to add the nudge on the main menu for this release and keep "Ready to send".

I agree with adding this small nudge and keeping "Ready to send" for now.

**Comment by seadowg** [comment]
Sounds like we're happy to go with the badge/bold text as described at the top then. I had a quick spike on the viability of the badge (as it's still experimental in Material Components), but it seems to work fine and I'll add a code sample.

**Comment by grzesiek2010** [comment]
> although it is a little funky as you need to add it after the view tree is laid out like so

I think we won't need to care about this as adding/removing that badge will always take place after creating the layout see: https://github.com/getodk/collect/pull/5606/files#diff-8638cd52b1b35ed1e1e47ab0626332d7258607345ae744db403446d014877d02R64

**Comment by seadowg** [comment]
> I think we won't need to care about this as adding/removing that badge will always take place after creating the layout see:

Ah interesting. It was probably more difficult to spike it out always being there 😆
