### ISSUE TITLE
Making the "Ready to Send" screen more actionable 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5605]
### Problem description
Given that the language on the main menu has changed from "Send Finalized Form" to "Ready to send", we are concerned that people may not notice that an action is needed if auto-send is turned off. 

As part of [adding a notification badge](https://github.com/getodk/collect/issues/5600#issue-1717942172) to the main menu, we also want to gently nudge users to send their forms from the "Ready to send" page.

![Image](https://github.com/getodk/collect/assets/7871340/3b50bf7c-4138-4dc6-82c2-c886b105b24c)

Note - this is the wrong icon; I don't have that file with a checkmark in my icon library. 

[Figma link](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=487%3A20892&t=08VUnF37zQkQXEwd-1) 

### Solution
**"Ready to send" page** 
- Adding the send icon, title and subtext to establish more of a visual hierarchy on the page.
- I decided to go with the send icon, instead of the checkmark, because it's a nice link from their last action. 
- We want to use the relative time to make it easier for data collectors to recall (e.g. "two days ago").

**Comment by alyblenkin** [comment]
I will update the mockup to include the icon with the checkmark, but later we my want to think about revising this.

**Comment by grzesiek2010** [comment]
I have some questions:
- what if there are no sent forms yet (fresh install)? The message should be `Last form sent: ...`
- what if a user deletes sent forms manually or has removing them automatically enabled in settings? In this case, we can't read the database and check when the last form was sent. Probably we should keep the time of the last sent form (in sharedprefs for example) to make displaying it possible no matter if the database was cleared or not.

@seadowg @alyblenkin what do you think?

**Comment by seadowg** [comment]
> what if there are no sent forms yet (fresh install)? The message should be Last form sent: ...

I think we should hide the banner in that case.

> what if a user deletes sent forms manually or has removing them automatically enabled in settings? In this case, we can't read the database and check when the last form was sent. Probably we should keep the time of the last sent form (in sharedprefs for example) to make displaying it possible no matter if the database was cleared or not.

Again I think we can just hide the banner here so as to not introduce the extra complexity.

**Comment by alyblenkin** [comment]
> what if there are no sent forms yet (fresh install)? The message should be `Last form sent: ...`

I was assuming that would be an empty state or removing the banner. I actually have a design story around changing the copy for that screen. If we do want to go with the empty state. We could say:

“You don’t have any forms ready to send.
Try finalizing drafts before sending"

<img width="320" alt="Screenshot 2023-07-20 at 8 09 08 AM" src="https://github.com/getodk/collect/assets/7871340/fd6b1bc7-d0bd-4719-8d6c-11701dc79240">


> * what if a user deletes sent forms manually or has removing them automatically enabled in settings? In this case, we can't read the database and check when the last form was sent. Probably we should keep the time of the last sent form (in sharedprefs for example) to make displaying it possible no matter if the database was cleared or not.

I wouldn't show the banner here.

**Comment by grzesiek2010** [comment]
ok and @alyblenkin what about the icon that should be used? Is it the same as in your mockups? I thought you wanted to change something there.

**Comment by alyblenkin** [comment]
We want to use the send icon, the same as we have in the mockup.
