### ISSUE TITLE
Printer widget layout puts label inside button 

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#561]
In Collect v1.4.16, if you use the printer widget (text with appearance=printer), the layout is broken. I'm pretty sure this is the case on all versions of Android, but I've only tried on Android 6 and 7.

**Bad: Print widget. The text should be above the button.**

![print](https://cloud.githubusercontent.com/assets/32369/23803713/6102b5a0-0585-11e7-828d-db743e71b4d1.png)

**Good: Print widget. This is what it is supposed to look like.**

![collect_printer](https://cloud.githubusercontent.com/assets/32369/23803866/eee8ff46-0585-11e7-86d9-0acf21edcc12.png)

**Good: GeoPointWidget. This is what a similar widget looks like.**

![gps](https://cloud.githubusercontent.com/assets/32369/23803744/7d1212d6-0585-11e7-91e7-648df376d605.png)

**Sample form for reproduction**
 * [print.xml.txt](https://github.com/opendatakit/collect/files/834521/print.xml.txt)
 * [print.xlsx](https://github.com/opendatakit/collect/files/834522/print.xlsx)

**Comment by nribeka** [comment]
The print should have capital P too.

**Comment by lognaturel** [comment]
@lokeshkvn Thanks for addressing this! In the future, please use [keywords to close issues](https://help.github.com/articles/closing-issues-via-commit-messages/) in your pull requests so the corresponding issue closes automatically. I also strongly recommend using separate branches for each issue you work on.

@nribeka "print" with a lowercase is the name of the sample form Yaw posted. 😊

**Comment by lokeshkvn** [comment]
Okay ,Thanks 😊
