### ISSUE TITLE
The list of drafts contains sorting options that are no longer relevant

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5615]
#### ODK Collect version
The master branch

#### Steps to reproduce the problem
The list of drafts contains only forms that are drafts (have incomplete status). In previous versions we had also finalized forms there so we allowed sorting by status. This no longer makes sense since there is just one possible status: incomplete.

![Screenshot_1685524686](https://github.com/getodk/collect/assets/3276264/003d7bb4-1abb-4f22-9499-e25c71076ed5)

#### Expected behavior
The two last options should be removed

**Comment by lognaturel** [comment]
YES
