### ISSUE TITLE
Display errors inline rather than in toast

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5618]
#### Problem description
We want to improve how we display errors by adding clear error messages to make it easier for data collectors to scan and address the issue. Currently, we have the toast that pops up, and it's easy to miss. I do think it's improved now that it's darker and centred, but we want to improve this further. 

We are not doing the hierarchy view yet, which you will see in [Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1761%3A60286&t=yiG40KoHuGRmotn1-1). This issue is focusing on errors within the form experience.

![Image](https://github.com/getodk/collect/assets/7871340/782ddc20-e63f-43ad-8961-c2ae14b0403e)

#### Solution

- Adding a red outline with rounded corners to highlight the error (we don't want to add more margin). 
- Error message is the same for all types of errors (exclamation mark icon and text "Required question" or incorrect if they have specific logic defined.
- The only question type that is different is how we display [text field errors](https://m3.material.io/components/text-fields/specs#f157ea73-f2fd-4d99-aab3-c96bd9c91eec), we will display the exclamation at the end of the field with supporting text "This question is required". For the moment, we'll text fields should show errors in the same way as everything else. We can add the text field specific error appearance later.
- If the question is really long, we want to scroll the user to the bottom of the page if there is an error (similar to what we do for multiple questions). 
- Currently, the error fades in when you have a group of questions, which we want to keep inside the bounds of the outline. This might be something we want to pair on to get right. 

#### Other information 

One thing that is related, but out of scope for this issue, is potentially allowing data collectors to skip a required question. In a recent user research session, a project manager told me that they have required questions, but sometimes the data collector can't, for whatever reason, submit an answer. 

They explained that data collectors add dummy text or anything to bypass the question, which means they have to clean up the data after. They could just make the question not required, but they said having some sort of option to skip and come back later would be helpful. I'm adding this here because I think it's interesting in the context of errors for us to consider down the road if it's a common issue.

**Comment by seadowg** [comment]
@grzesiek2010 do you think we should break this into two issues (one where everything uses the generic error message and one where we add a specific error state for text) or just keep it as one? I'm undecided.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 do you think we should break this into two issues (one where everything uses the generic error message and one where we add a specific error state for text) or just keep it as one? I'm undecided.

Do you mean separating text widgets (which will be highlighted differently) and other types of widgets or maybe separating displaying plain error messages like required/invalid and those customized on a form level?

One question for @alyblenkin: was moving the red asterisk (that indicates it's a required question) from the beginning to the end of a question, intentional?

I think as a part of this issue it would be good to rework the way we display that asterisk. The current way is rather a stopgap where we add that asterisk to the text of the question and display it in one `TextView`. We already had one problem with this approach https://github.com/getodk/collect/issues/5281. I think the asterisk should be displayed as a separate element and then it doesn't even has to be an asterisk it might be something else if you think it would be better @alyblenkin

**Comment by alyblenkin** [comment]
I'm glad you brought this up @grzesiek2010! We were going to make this change with Enketo and move the asterisk to the end, as that's a common pattern in form design, but after discussions with Hélène and Trevor, there is some compelling [evidence to suggest this isn't as accessible ](https://www.nngroup.com/articles/required-fields/).

We decided the asterisk should just before the field description to help the users easily scan which fields are required, but I created this mockup before and forgot to update it based on these discussions! I can update that in the file - I think we should keep this pattern. 

Eventually, we may want to go the extra step and ad[d "required" to the label](https://dequeuniversity.com/tips/identify-required-elements), which is a better user experience for sighted users and available to assistive technology users.

**Comment by grzesiek2010** [comment]
Ok above I said that it should be a part of this issue but now I think that we can do that later. So to sum up my thinking is that there should be a separate view for that asterisk not to add it to the question text and avoid issues like https://github.com/getodk/collect/issues/5281 @seadowg do you want to add anything?

**Comment by seadowg** [comment]
> Do you mean separating text widgets (which will be highlighted differently) and other types of widgets or maybe separating displaying plain error messages like required/invalid and those customized on a form level?

No, but I totally see how it came across that way! I was wondering if we should separate this into two issues:

1. Removing the toast and instead showing a red outline and the constraint (or required) message at the bottom of the widget for all widgets (including text ones)
2. Making the text widgets show the constraint/required message differently (highlighting the text field itself)

I was thinking that we'd probably end up adding something like a `#setError` on `QuestionWidget` that could be overridden by individual widgets and that doing that for `StringWidget` could be a separate issue/PR. Alternatively, it might just be easier to do it as one chunk - I wasn't sure.

It also sounds like we want an additional issue for moving the asterisk to the beginning of the question label (and making it a separate view) yeah?

**Comment by grzesiek2010** [comment]
> 1. Removing the toast and instead showing a red outline and the constraint (or required) message at the bottom of the widget for all widgets (including text ones)
> 2. Making the text widgets show the constraint/required message differently (highlighting the text field itself)

Yeah we can do that.

> It also sounds like we want an additional issue for moving the asterisk to the beginning of the question label (and making it a separate view) yeah?

Yes.
