### ISSUE TITLE
Only build search/pulldata database for forms that require it

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5620]
If a form has a secondary instance, but does not use a `search` or `pulldata` expression at any point, it should not preload data when loading the form. This can currently be seen to be happening in the form loading dialog when the "Pre-loading data from..." message shows up.

Forms containing `search` (which looks like a function, but is actually part of the `appearance` for a `select`) or `pulldata` (a function handled by Collect with the `IFunctionHandler` API) should continue to preload (and show in form loading that they are doing it).

## Acceptance

- [x] Given I have a form in my project with an external secondary instance (as a CSV)
And it doesn't include any `search` or `pulldata` expressions
When I open the form for the first time
Then I do not see the "Pre-loading data from..." status while loading

- [x] Given I have a form in my project with an external secondary instance (as a CSV)
And it does include a `search` and/or `pulldata` expression
When I open the form for the first time
Then I see the "Pre-loading data from..." status while loading

**Comment by seadowg** [comment]
@lognaturel does this look correct you?

**Comment by lognaturel** [comment]
Yes!

**Comment by seadowg** [comment]
Moving this to "not ready" while we reconsider priorities for optimisation work.
