### ISSUE TITLE
In image select one widget minimizing the app with "don't keep activities" on moves the user to the hierarchy view

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5631]
#### ODK Collect version
the master version 8babf2cc47207c31a6226020eff477239bc416f7
#### Android version
8.1, 10, 11
#### Device used
Nexus 5X, Redmi 9T, Galaxy M12
#### Problem description
When the user minimizes the app while "don’t keep activities” is enabled on the image select one widget, he is moved to the hierarchy view after going back to the app (as if minimizing causes a savepoint in the form).
#### Steps to reproduce the problem
1. In device settings enable "don’t keep activities”.
2. Go to All widgets form – Image select one widget.
3. Minimize the app.
4. Go back to the app.
#### Expected behavior
The user shouldn’t be moved to the hierarchy view. The user should be at image select one widget.
#### Other information
The issue is not present in the store version 2023.1.2

**Comment by seadowg** [comment]
This is fixed in the current `master` (cefefaa81b2c9d6301a7dfcfabfcdae54654c00e) so I'll close this. Definitely give it a check in case I'm mistaken @dbemke!

**Comment by dbemke** [comment]
Yes. it's fixed in the current master
