### ISSUE TITLE
Crash of the app after zooming to points in a map-internal-select form with Google maps

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5634]
#### ODK Collect version
2023.1.1, the store version 2023.1.2, the master version 3f5ab8e84d64a27bb60ecf6cf3672b8548a07d8b
#### Android version
8.1, 10, 13
#### Device used
Nexus 5X, Redmi 9T, Galaxy A23
#### Problem description
When Google maps is set as a source of map zooming to all points crashes the app in map-internal select form.
In other version of the form without added traces the issue doesn’t occur. Form not causing the crash 
[map-internal-select(2).xlsx.txt](https://github.com/getodk/collect/files/11758991/map-internal-select.2.xlsx.txt)

#### Steps to reproduce the problem
1. Go to map-internal-select form.
[map-internal-select(1).xlsx.txt](https://github.com/getodk/collect/files/11758924/map-internal-select.1.xlsx.txt)
2. Tap "Select place”.
3. Tap on the button to zoom to all points.
#### Expected behavior
The app shouldn’t crash.
#### Other information
The issue doesn’t occur in Select on from map in the demo project or random select one map froms with geojson, csv, xml attachments.

**Comment by lognaturel** [comment]
The crash no longer occurs! 🎉 We do want to also see whether it's possible to improve the zoom behavior per https://github.com/getodk/collect/pull/5700#issuecomment-1680349821

**Comment by seadowg** [comment]
Would definitely be nice to improve the zoom behaviour. @dbemke if you think that needs an issue then go ahead and file one, but I think that's ok to leave until we feel like its a priority. We can close this now the crash itself is fixed.
