### ISSUE TITLE
Viewing encrypted submissions via snackbar

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5642]
#### ODK Collect version
the beta version 2023.2 Beta 3
#### Android version
10
#### Device used
Redmi 9T
#### Problem description
After sending a submission in an encrypted project it is possible to "view” the sent form via snackbar. The user is moved to the view of a sent form with "Nothing available to display”. It’s seems ok since the submission was encrypted but on the other hand allowing the user to view something that isn’t available seems unnecessary so I’m not sure if it’s expected or not.
![encryptedsubmissionview](https://github.com/getodk/collect/assets/56479916/19288b24-66cb-4f70-818e-8b9bae1b4c0b)

#### Steps to reproduce the problem
1. Add and encrypted project to Collect.
2. Go to any form and send a submission.
3. When moved to the main menu, in the snackbar click "View”.

#### Expected behaviour

The "View" button should not appear for encrypted submissions.

**Comment by grzesiek2010** [comment]
I think the view button should not be displayed in this case. @seadowg what do you think?

**Comment by seadowg** [comment]
Agreed! I think we should probably fix this for v2023.2.
