### ISSUE TITLE
Minimizing the app with no background processes setting moves the user to the first question 

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5646]
#### ODK Collect version
v 2023.2. Beta 3
#### Android version
10, 11
#### Device used
Redmi 9T, Galaxy M12
#### Problem description
There is a difference in the expected result compared to 2023.1.2. In the present 2023.2 Beta 3 following the steps described below results in being moved to the first question, while in 2023.1.2 the user was moved to the second question.
#### Steps to reproduce the problem
1. Set "Background process limit" to "No background processes" in Developer Options.
2. Open a form with a Select One From Map question.
3. Go to the second question.
4. Go to the hierarchy view.
5. Switch to another app.
6. Go back to Collect.
#### Expected behavior
In the store version 2023.1.2 expected behavior was that the user is at the second question after going back to the form.

**Comment by seadowg** [comment]
I think we do expect this to be different in v2023.2 (since we fixed the restore crashes in #5240), but I'm confused as to why you end up on the first question and not the hierarchy. If you try the same steps, but stay don't visit the hierarchy before multitasking, you'll see you get returned to the hierarchy (as the save point is loaded). I'll investigate.

**Comment by srujner** [comment]
On Android 13 user is taken back to hierarchy view, so it works correctly.

**Comment by dbemke** [comment]
The steps for this test and expected results were from RR#5366 and I thought about #5240 but after combining those two I don't know what is the expected now

**Comment by seadowg** [comment]
Oh it's to do with some weirdness created by the `FormHiearchyActivity` being started for result and then there for some reason being a result to deal with when the app restores (which doesn't make much sense to me). There's more to dig into here, but I think we should leave this for the next release. Returning to the first question doesn't seem much worse, and it's certainly better than a crash which we would have seen a couple of releases ago.

**Comment by seadowg** [comment]
I've accidentally fixed this while investigating a crash.
