### ISSUE TITLE
Default image disappears in the Signature widget if the user clicks "Reset" while marking up the image

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5650]
#### ODK Collect version
the store version 2023.1.2, the version 2023.2 Beta 4
#### Android version
10, 11, 13
#### Device used
Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
Default image disappears in the Signature widget if the user clicks "Reset" while marking up the image.
#### Steps to reproduce the problem
1. Go to defualtImage form with pictues.
[defaultImage_pictures(3).xml.txt](https://github.com/getodk/collect/files/11891824/defaultImage_pictures.3.xml.txt)
[doc.png.txt](https://github.com/getodk/collect/files/11891840/doc.png.txt)
[apple.png.txt](https://github.com/getodk/collect/files/11891841/apple.png.txt)
2. Go to signature widget and click "Gather Signature”.
3. Click the + icon.
4. Click "Reset”.
5. Click the + icon and Save and Close.
#### Expected behavior
As discussed here, the signature widget should not support a default image at all. If one is specified for a signature widget question it should not be loaded/displayed.

**Comment by seadowg** [comment]
@lognaturel this seems broken to me. Just wanted to check with you that it's not desired behaviour.

**Comment by lognaturel** [comment]
It works as expected with an annotation widget? The most surprising thing I see in this issue is that the signature widget allows a default image to be set at all. I would expect that to only be relevant to the annotation widget.

**Comment by seadowg** [comment]
@dbemke could you confirm this was with the signature widget rather than the annotation widget?

**Comment by dbemke** [comment]
In the form mentioned in the issue there are both Signature and Annotation widget. In the Annotation widget resetting doesn't  remove the default image. In the Signature widget resetting removes the default image. (Checked again on v20223.3 Beta 2)

**Comment by seadowg** [comment]
> In the Signature widget resetting removes the default image. (Checked again on v20223.3 Beta 2)

@lognaturel it sounds like you're suggesting that the real problem here is the signature widget allowing a default image to be set right?

**Comment by lognaturel** [comment]
Yes, that sounds unintentional to me and could be removed!

**Comment by seadowg** [comment]
Cool! I'll update the issue.

**Comment by lognaturel** [comment]
I think we can close this. My guess is that no one (outside of QA!) will think to use a default image with signature.
