### ISSUE TITLE
Filter is cleared after minimizing or blocking the app in select one/multiple widgets

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5651]
#### ODK Collect version
v2023.2 Beta 4, v2023.1.2
#### Android version
11, 12, 13
#### Device used
Samsung Galaxy M12, Google Pixel 3a, Google Pixel 6a
#### Problem description
Filter is cleared after minimizing or blocking the app in select one/multiple widgets
#### Steps to reproduce the problem
1. Turn on "Don't keep activities" in Developer settings
1. Create Demo Project;
2. Open All Widgets Form;
3. Navigate to the Select One Widgets and open Select one search widget;
4. Fill the Filter field;
5. Minimize or block the app;
6. Filter is cleared.
#### Expected behavior
Filter should not be cleared.
#### Other information 

https://github.com/getodk/collect/assets/85225519/5451daa8-2a50-40df-896f-eba9279594c5

**Comment by seadowg** [comment]
Is this with "Don't keep Activities" on? That's the only way I could reproduce on Android 11.

**Comment by srujner** [comment]
@seadowg Yes, you're right. It is happening only with Don't keep activities on and on all Androids. 
I checked with Background processing and forget about this one.

**Comment by grzesiek2010** [comment]
I don't think we should preserve that state it's not a big deal but fixing it would only add complexity.

**Comment by seadowg** [comment]
Closing this as it's "won't fix"
