### ISSUE TITLE
Make it possible to request form validation without finalizing

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5655]
Prior to the changes to form finalization, it was possible to use "mark as finalized" as a way to validate a form's content. For example, here's a workflow we know has been in use:
- Fill out the form
- Check mark as finalized, click "Save and Exit"
- Fix any validation errors
- Show finalized forms to a supervisor
- The supervisor makes any necessary changes and then sends reviewed forms

Now that finalization is truly final, this workflow would only work if there's a required question that represents supervisor acceptance. For example, that could be a text field with label "Supervisor initials when reviewed". If a form has such a question, the user can tap the "Finalize" or "Send" button to identify other possible validation errors without risking locking down the form. This may require form design changes, though.

To help address this change in behavior, we will add a button to the form filling overflow menu to request form validation. This is not very discoverable but it is easy to communicate about. We do plan to provide some validation on the form hierarchy screen at some point which will reduce the need for this button.

- [x] Given that I'm filling out a form
  When I tap the overflow menu (⋮)
  I see a "Check for errors" option

- [x] Given that I tap the "Check for errors" option
  And that the form has one or more missing required values
  Then I am redirected to the first required question with a missing value
  And I see the missing value message

- [x] Given that I tap the "Check for errors" option
  And that the form has one or more violated constraint
  Then I am redirected to the first question with a violated constraint
  And I see the constraint message

- [x] Given that I tap the "Check for errors" option
  And that validation takes multiple seconds
  Then the screen is grayed out and a progress bar is shown at the top

- [x] Given that I tap the "Check for errors" option
  And that the form is fully valid
[  I see a snack bar](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1972%3A67794&t=0usuO6ANbkGyqDkx-1) that indicates that the form is valid

**Comment by alyblenkin** [comment]
I added the link to Figma above. I decided to go with the snack bar because if the check is valid we don't want to disrupt the flow with a dialog, as there isn't any action to be taken. 

We also discussed in Slack potentially adding a dialog to ask the user if they want to ["Review changes"](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1972%3A67924&t=0usuO6ANbkGyqDkx-1) instead of going straight to the first error. We decided this might come later, but I wanted to note it here.
