### ISSUE TITLE
Adding a snackbar for successful or failed submissions 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5656]
#### Problem description

When I send forms from "Ready to send", I want to see a snackbar informing me if a submission was successful or had any errors. We don't want this to be a dialog because it's too disruptive, and no action is needed if it's successful. 

**Success message:**
"[Name of form] was successfully sent.  X"

**Failure message:**
"[Name of form] failed to send because of errors.  View  X"

Current state
![Screenshot_20230629-002024_ODK Collect](https://github.com/getodk/collect/assets/7871340/27099486-de9c-4513-86e9-8300fe620289)

Question: 
If the user is sending a large batch of forms, do we want to show one message once all the forms are sent, or is there value in seeing each submission result, as we have now?

**Comment by seadowg** [comment]
@alyblenkin I think we'd also need to change the way we do progress here as it's a dialog so we'd end up with progress dialog and then a snack bar (which doesn't feel right to me).

**Comment by lognaturel** [comment]
Somewhat related: https://github.com/getodk/collect/issues/4540

**Comment by alyblenkin** [comment]
> @alyblenkin I think we'd also need to change the way we do progress here as it's a dialog so we'd end up with progress dialog and then a snack bar (which doesn't feel right to me).

@lognaturel I agree that it is somewhat related to #4540. It would be great if they could continue their task and not be blocked. 

@seadowg Could we explore a snackbar that says "Sending..." and then switches to "Sent" once it has been successful? I believe we've discussed this before because I have designs for it, but perhaps it was difficult to implement? This would be ideal because both use cases get feedback, the users that want to verify it has been sent, and workflows where they want to go to the next task. 

The other option you mentioned, display the progress dialog (blocking them from doing anything) and then display the snackbar once it has been submitted, like we were thinking about [here](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3048%3A97490&mode=design&t=isftoQz89RtAUv2P-1), isn't ideal, but I think we are already using this design pattern when users check for errors. However, I think you would only see the progress dialog if it's slow – I always see the snackbar immediately.

**Comment by lognaturel** [comment]
Having thought more about it, I think this should be considered a subset of #4540. I don't think it makes sense to change just the progress feedback without also making the work asynchronous. The main reason to make sending async would be so there's a single code path for submission. Otherwise I don't think there's a reason to prioritize this work given that the recommended way to send is with autosend.

**Comment by alyblenkin** [comment]
Side note: I just noticed that google drive uses this behaviour (progress dialog > snackbar) when uploading files on mobile.

**Comment by seadowg** [comment]
> Having thought more about it, I think this should be considered a subset of https://github.com/getodk/collect/issues/4540. I don't think it makes sense to change just the progress feedback without also making the work asynchronous. The main reason to make sending async would be so there's a single code path for submission. Otherwise I don't think there's a reason to prioritize this work given that the recommended way to send is with autosend.

That makes sense to me! I'll close this issue for now.
