### ISSUE TITLE
Improve .gitignore to share settings

### ISSUE THREAD

**Issue by adithya321** [getodk/collect#567]
I use the Default code style scheme in Android Studio and when I ran Reformat Code on the whole project, I got 222 changed files.
![image](https://cloud.githubusercontent.com/assets/3854934/23822012/eee4fd40-0668-11e7-9633-60078460c992.png)

Android Studio creates a new project with the following .gitignore file
```
*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
/captures
.externalNativeBuild
```
All these are included in the current [collect/.gitignore](https://github.com/opendatakit/collect/blob/master/.gitignore) file but the whole .idea folder is ignored. [Android.gitgnore](https://github.com/github/gitignore/blob/master/Android.gitignore) excludes only the following .idea files
```
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/dictionaries
.idea/libraries
```
By ignoring only these files, we can share settings and enforce a code style so that when we invoke Reformat Code, the code will match the style guidelines.

[Share the settings with the whole team](https://tips.seebrock3r.me/share-the-settings-with-the-whole-team-android-studio-protip-6-3cce16eb2ea4#.44nfy47r3)
[Share the settings with the whole team — a year later](https://tips.seebrock3r.me/share-settings-with-the-team-a-year-later-e28c24fc07aa#.100ffj5b2)

JetBrains Recommendation:
[How to manage projects under Version Control Systems](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems)
[Synchronizing and Sharing Settings](https://www.jetbrains.com/help/idea/2016.1/synchronizing-and-sharing-settings.html)

**Comment by supreme96** [comment]
Can I take this one?

**Comment by lognaturel** [comment]
@adithya321 @supreme96 We will use `checkstyle` for style settings so that the check can be automated in continuous integration. I have opened issue #602 to discuss this and I encourage you to participate.

Are there other settings that you think would be worth sharing?

**Comment by shobhitagarwal1612** [comment]
@lognaturel Can we close this?

**Comment by shobhitagarwal1612** [comment]
We are already using `checkstyle` to enforce the code styling
