### ISSUE TITLE
Show warning when editing finalized form

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5680]
When a user taps on a finalized form in "Ready to send" that opens for editing (before the grace period ends), they should see a dialog with the title "Important update" and the text:

> After September 30th, you will not be able to edit finalized forms.
>
> Save forms as draft to edit them. You can check for errors in a draft form by using ⋮ > Check for errors.

The dialog should have a single OK button that dismisses the dialog and returns the user to the form. This dialog should show every time.

In addition, we want to track how often "Check for errors" is used. The should be tracked with a form event (with `Analytics.log(<event name>, "form")`).

**Comment by yanokwa** [comment]
I'd prefer something like this...

> After September 30th, you will not be able to edit finalized forms. Save forms as draft to edit them later. 
>
> You can check if a draft form is complete and valid by using ⋮ > Check for errors.

I'm not sure about using "complete and valid" in the second sentence. Complete is a word I don't think we've used before. Maybe "valid and ready to send" might be better. Or "error-free and ready to send".

**Comment by lognaturel** [comment]
> I'm not sure about using "complete and valid" in the second sentence.

Agreed. Maybe keep it simple and say "You can check for errors in a draft form by using ⋮ > Check for errors."

**Comment by seadowg** [comment]
Makes sense to me! I've changed it.

**Comment by alyblenkin** [comment]
I like these iterations! I think the ⋮ and > look strange in a sentence when they are right next to each other. I know I'm making it longer, but what about something like this to make it more user-friendly? 

"After September 30th, you will not be able to edit finalized forms.

Save forms as draft to edit them. You can check for errors in a draft form by using the button with the three dots (⋮) and Check for errors."

**Comment by seadowg** [comment]
> "After September 30th, you will not be able to edit finalized forms.
>
> Save forms as draft to edit them. You can check for errors in a draft form by using the button with the three dots (⋮) and Check for errors."

I'm happy with that change. @grzesiek2010 are you able to update the PR?

**Comment by yanokwa** [comment]
Nit pick but I think "Save forms as draft to edit them" should be on the first line.

**Comment by alyblenkin** [comment]
@yanokwa - I think they need the first sentence for context because they will be in "Ready to send" and that might be confusing to see first.

**Comment by yanokwa** [comment]
I agree. What I'm proposing is..

> After September 30th, you will not be able to edit finalized forms. Save forms as draft to edit them later.
>
> You can check for errors in a draft form by tapping the three dots (⋮) and then Check for errors."

I tweaked the second sentence because I couldn't help myself. I like shorter sentences.

**Comment by alyblenkin** [comment]
Yes, this is perfect. Sorry, I misread your comment. Shorter sentences are great!
