### ISSUE TITLE
Snackbar "Your form tracks your location..” reappears after going to the hierarchy view if don’t keep activities is enabled

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5683]
#### ODK Collect version
the store version 2023.2.2, the master version e02d656b289e75dadf760238a998cef46b3dd950
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
The snackbar "Your form tracks your location..” reappears after going to the hierarchy view if don’t keep activities is enabled.
#### Steps to reproduce the problem
1. Don’t keep activities is enabled in the device settings.
2. Go to AuditTestLocationBackground form.
[AuditTestLocationBackground.xml.txt](https://github.com/getodk/collect/files/12080265/AuditTestLocationBackground.xml.txt)
3. When the "Your form tracks location..” snackbar disappears, go to the hierarchy view and tap on any question.
#### Expected behavior
The snackbar shouldn’t reappear.

**Comment by seadowg** [comment]
I chatted about this with @lognaturel and we decided this is ok as location tracking would start and stop in this case (when you leave and then return to the screen).
