### ISSUE TITLE
Redundancy of Exit Sample Prompt/Dialogue Box

### ISSUE THREAD

**Issue by ajayrahul97** [getodk/collect#569]
#### Problem description : 
Exit Sample prompt is being displayed every time user navigates back from the "Edit Saved Form" page, even if the user does not change any details in the form , or , even if the details are already saved in the form.

#### Expected behavior
Ideally , the prompt should be displayed only when changes made are not saved.
An internal flag should be set to check if there were any changes made or not .

**Comment by lognaturel** [comment]
I don't really see this as a problem, @ajayrahul97. The toast confirms that the user chose to save changes rather than ignore them. @nribeka what do you think?

**Comment by ajayrahul97** [comment]
@lognaturel,  im not against that toast , what i meant is , the toast should appear only when there are changes made , not everytime the user navigates back to the main screen . Even if I just open the edit screen , do nothing and go back, the dialogue box appears, ..or ...even if I save and then navigate back , the prompt appears !

**Comment by lognaturel** [comment]
@ajayrahul97 So your suggestion is to not show the save/ignore dialog if no actual changes have been made, am I now understanding you correctly? I think it's the kind of thing that as a user I prefer to have consistent. If I forget that I didn't make changes and then don't have the option to save, that makes me uncomfortable. @nribeka @yanokwa would be great to have some other opinions!

**Comment by ajayrahul97** [comment]
@lognaturel  , take any text-editor for instance, when we close the window , it shows the prompt only if there are some unsaved changes, not every time the user closes the window. So what i'm proposing here is to detect any key press after **_saving the form/opening the form_** and if there was any key pressed then show the prompt otherwise no.

**Comment by yanokwa** [comment]
I agree that you should only be warned if you've made changes. I don't think consistency is an issue here. Or rather, if I haven't made changes, it's a little scary to get that dialog. 

We do need to be careful about what sets that flag. A swipe is generally what saves data, not a key press. The other thing to be aware of is that I think the act of opening a form triggers unseen changes -- namely, timestamps that aren't wrapped with once() are updated. @mitchellsundt, can you confirm?

**Comment by lognaturel** [comment]
Closing in favor of #1887
