### ISSUE TITLE
Answers from select one questions are not read properly if they start/end with whitespaces and come from an external file

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5692]
#### Problem description
Answers from select one questions are not read properly if they start/end with whitespaces and come from an external file
I prepared a test form with three questions where:
- the first one has choices that come from the XML file itself
- the second one has choices from [an external csv file](https://docs.getodk.org/form-question-types/#select-from-external-dataset) (select_one_from_file)
- the fired one has choices from an external csv file (using the [search](https://xlsform.org/en/#dynamic-selects-from-pre-loaded-data) function)

#### Steps to reproduce the problem
1. Open the attached form: [SelectWIthWhitespaces.zip](https://github.com/getodk/collect/files/12149596/SelectWIthWhitespaces.zip)
2. Answer each of the three questions
3. Save the form as a draft
4. Edit the form

#### Expected behavior
All answers should be read correctly and displayed in the app.

#### Other information 
The first question with choices from the XML file works well
For the question with choices from [an external csv file](https://docs.getodk.org/form-question-types/#select-from-external-dataset) (select_one_from_file) the answer is gone after editing a form (not visible in the hierarchy view and not visible in the question itself
For the question with choices from an external csv file (using the [search](https://xlsform.org/en/#dynamic-selects-from-pre-loaded-data) function), the answer is visible initially in the hierarchy but not in the question itself

**Comment by lognaturel** [comment]
Merged in JavaRosa so it should be available in Collect after a rebuild!

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- selects in drafts in the form mentioned above
- regression checks in selects
- don't keep activities enabled/disabled

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14

**Comment by srujner** [comment]
**Tested with Success!**

Verified on a device with Android 13

**Comment by grzesiek2010** [comment]
Closed in https://github.com/getodk/javarosa/pull/752
