### ISSUE TITLE
Address or suppress audit header error about null FileWriter

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5703]
We are currently logging a frequent audit-related error: [Crashlytics](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/e577bff0dbc501d14310b1dfbdbeaf33?time=last-seven-days&sessionEventKey=64DCDF1800D800017A984CE6B483FB31_1846376940478461415) (requires auth).

Since we are in the audit context for this release, I think we should do something about it. If it's not important, we should not log it. I expect it does point to something going wrong.

**Comment by lognaturel** [comment]
@seadowg I think this would be good to take a look at for the next release but will let you make the call!

**Comment by seadowg** [comment]
Let's see if we can get it in this release.

**Comment by grzesiek2010** [comment]
FileWriter is always null if there is no need to update the header so it will always log that error in such cases. It doesn't make sense so I would get rid of this and other similar logs from `AuditEventSaveTask` the ones we log in `catch` blocks should be enough.
