### ISSUE TITLE
Remove deprecated app bundles and APKS

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#5709]
The Play Store says...
> To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements. From Oct 31, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

The affected app bundles are:
<img width="990" alt="Screenshot 2023-08-21 at 12 55 02" src="https://github.com/getodk/collect/assets/32369/484cfe56-ed68-4b7f-bb7e-d7c897e05df5">

Note that these are all retained app bundles of the current release. I believe we have to publish a new release and unrelease these bundles. We will need to communicate to users that these APKs will no longer be available on the Play Store.

**Comment by lognaturel** [comment]
The error is no longer showing up so it looks like either the policy changed or we misunderstood it.
