### ISSUE TITLE
non numeric contact number 

### ISSUE THREAD

**Issue by pkarira** [getodk/collect#571]
In Hypertension screening , it allows us to input non numeric contact number.
![screenshot_2017-03-11-23-58-49](https://cloud.githubusercontent.com/assets/17070693/23825829/60b80fcc-06b7-11e7-9c3e-55f8ae6a93e5.png)
@lognaturel should I resolve this small issue .

**Comment by lognaturel** [comment]
That is because the form was designed that way. Form designers can choose to limit input types and provide validation if they want.
