### ISSUE TITLE
Bulk finalization

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5714]
Original proposal: https://docs.google.com/document/d/1u16s0dN7wO7XMhlK8rKFDEfZCtYkK5kyFgccQ6ATOM8/edit#heading=h.4url4222egph

### Acceptance

- [x] Given I've saved at least one form as a draft
And I'm on the Drafts screen
When I click the options menu
And I click "Finalize all forms"
Then I see a snackbar saying "Success! \<number of forms\> forms finalized."
And the forms no longer appear in Drafts
And the forms are now finalized (and in "Ready to send")

- [x] Given I've saved at least one form as a draft
And I'm on the Drafts screen
When I click the options menu
And I click "Finalize all forms"
Then I see a progress dialog while forms are finalized
And I am unable to do anything else in the app

- [x] Given I've saved at least one form as a draft
And I'm on the Drafts screen
When I click the options menu
And I click "Finalize all forms"
And one or more forms has constraint violations
Then I see a snackbar informing me that "\<number of forms finalized\> forms finalized. \<number of forms with errors\> forms have errors. Address issues before finalizing all forms."
And the forms with errors have the status "Saved with errors on \<timestamp\>"
And the other forms have been successfully finalized

- [x] Handle bulk finalisation for partial submission forms (with a `ref` in their `submission` element)
- [x] Instance name should be updated (in UI) if validation or finalization updates it (like it would if the name involved `now()` or `random()`)

### Design questions

- ~~How discoverable should this be? Should it be part of the options menu or something clearer like a FAB?~~
    - Options menu. Should be available, but not a primary action.
- ~~Should finalising block the user from doing other things, or should it happen in the background?~~
    - This is a critical action and it's unlikely the user is doing anything else in Collect so a blocking progress dialog is fine. 
    - We should consider using something like WorkManager if that's better for making sure the job runs if the app isn't in the foreground.
- ~~How should we inform the user of constraint violations or errors?~~
    - Show a dialog and also put forms in a new "saved with errors" state
- ~~Should finalising "fail fast" after the first form with constraint violations/errors, or try and finalise everything?~~
    - Keep validating after a fail

### Follow on work

- #5718
- #5741
- #5739 
- #5740
- Handle exceptions that could happen during bulk finalization
- Don't revalidate invalid forms
- Handle bulk finalization for forms with geography
    - Could validation/finalization alter the geography?

**Comment by seadowg** [comment]
@alyblenkin I've just updated the issue so that we show a snackbar instead of dialog for the success and failure states as per the mockup.

**Comment by alyblenkin** [comment]
@seadowg Do you think we should have acceptance criteria for the scenario when a number of forms are sent and some have errors?

Show something like "number of forms successfully finalized. number of forms had errors. Address issues before finalizing your forms"

For the progress dialog, do we think it's possible to show "number of forms/total"? Or is that a future iteration?

**Comment by seadowg** [comment]
> Do you think we should have acceptance criteria for the scenario when a number of forms are sent and some have errors?
>
> Show something like "number of forms successfully finalized. number of forms had errors. Address issues before finalizing your forms"

We do already:

>  Given I've saved at least one form as a draft
And I'm on the Drafts screen
When I click the options menu
And I click "Finalize all forms"
And one or more forms has constraint violations
Then I see a snackbar informing me that "<number of forms with errors> forms have errors. Address issues before finalizing all forms."
And the forms with errors have the status "Saved with errors on <timestamp>"
And the other forms have been successfully finalized


I'll update this with text you're suggesting, as that's definitely better!

**Comment by seadowg** [comment]
> For the progress dialog, do we think it's possible to show "number of forms/total"? Or is that a future iteration?

Let's leave that for the moment. Definitely possible at some point.
