### ISSUE TITLE
Validation feedback for unfinalized forms

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5718]
~~Blocked by #5714~~

If just "Save as draft" is available the user gets no feedback if they're saving a form with constraint violations.

### Acceptance

- [x] Given I'm on the end screen of a form
And there are no violated constraints
When I click "Save as draft"
Then I am taken to the main menu
And the form shows in Drafts with the "Complete" pill

- [x] Given I'm on the end screen of a form
And there are violated constraints
When I click "Save as draft"
Then I am taken to the main menu
And the form shows in Drafts with the "Incomplete" pill

### Notes

Good to keep in mind while implementing: t's likely we'll move the exact trigger for when validation occurs around. For instance, it might be that we want to display the validation "status" on the end screen itself (so would need to validate on swipe to it).

**Comment by seadowg** [comment]
@grzesiek2010 woh woh this wasn't ready to go yet (still in "not ready"). We need to decide on a branch point for v2023.3 and I think we'll want to do this after #5714 (was just about to block it). Will hopefully have all that planned out tomorrow.

**Comment by grzesiek2010** [comment]
Ah ok. I was just about to start but then had a break so I haven't written a single line of code yet.

**Comment by seadowg** [comment]
@grzesiek2010 no worries! I'm keeping the [backlog](https://github.com/orgs/getodk/projects/9) up to date, so everything in "backlog" is good to work on and prioritised (most important thing first).

**Comment by alyblenkin** [comment]
@seadowg and I chatted about a few options for validation feedback. Ideally, I would like to move us closer to a summary view and display a message about the errors on the end screen, but we are worried about performance. 

We are thinking the next best iteration, given the unknown of how much it will slow down performance, would be to show a dialog when the user taps "save as draft." 

Open to feedback on the text...

<img width="1166" alt="Screenshot 2023-09-08 at 9 36 28 AM" src="https://github.com/getodk/collect/assets/7871340/f6cc09af-a18a-4fa2-a8dd-27aa5ba38900">

**Comment by seadowg** [comment]
> Open to feedback on the text...

I think either works! We can always tweak that later.

**Comment by alyblenkin** [comment]
@seadowg, sounds good! Let's go with the first mockup!

**Comment by seadowg** [comment]
@lognaturel @alyblenkin ignoring the dialog for now, do we want a form that we save via the quit dialog and "Save as draft" (rather than the end screen) that doesn't have an constraint violations to be marked as "complete"? That feels a little confusing to me, but I guess it's also possible to navigate to the end screen via the hierarchy and exit "early" (without actually "finishing" the form).

**Comment by lognaturel** [comment]
> ignoring the dialog for now

Yes, that feels right, let's decide whether we want/need it when we can see the behavior in action. There are real tradeoffs.

> do we want a form that we save via the quit dialog and "Save as draft" (rather than the end screen) that doesn't have an constraint violations to be marked as "complete"? 

This is one of the reasons why I was so against "complete"/"incomplete" previously! 

If your form design doesn't require answers for some reason, all of your filled forms will be "complete" all the time, even if you open and immediately save as draft (e.g. the All Widgets form). As we were talking about this, first I realized that it's probably a rare pattern. And then I think that if you do design your form not to have any required questions or constraints, then the intent is that even a blank submission is "complete." As you said, it's not really fundamentally different from jumping to the form end or even swiping through all the questions mechanically. We could probably try to be more strict about what "completeness" requires by doing something like keeping track of whether all fields have been *displayed* but I'm not convinced there would be significant user benefit. I think we need "complete" to mean the same thing as "finalization will succeed" and if we start changing the criteria for finalization that will be a whole other layer of disruption for users. All that said, I still feel somewhat uncomfortable about it so happy to dig in further. Maybe there's some alternative we haven't explored yet.

The other reason I was against complete/incomplete was more pedantic -- if you have a filled form in which all required fields are complete but have a constraint error, calling it "incomplete" feels subtly wrong. I've mostly been convinced this is relatively rare and also acceptable: if there's a constraint violation, your work isn't complete, there's still something to do.

**Comment by alyblenkin** [comment]
> If your form design doesn't require answers for some reason, all of your filled forms will be "complete" all the time, even if you open and immediately save as draft (e.g. the All Widgets form). As we were talking about this, first I realized that it's probably a rare pattern. And then I think that if you do design your form not to have any required questions or constraints, then the intent is that even a blank submission is "complete." As you said, it's not really fundamentally different from jumping to the form end or even swiping through all the questions mechanically. 

I agree this seems like it would be rare!

> We could probably try to be more strict about what "completeness" requires by doing something like keeping track of whether all fields have been _displayed_ but I'm not convinced there would be significant user benefit. 

If we do use this new language, I think being more strict on "completeness" would be helpful for the user, and we don't mark it as complete until they've viewed each question. I think this is how TurboTax works – it would be weird to see something marked as "complete" before you've viewed it. I believe they show how many questions you've viewed  "30/90 questions complete or as a percentage" because a lot of the questions aren't required. Maybe another option could be displaying "Not started" or "No data entered" if they've just jumped to the end and saved it as a draft?

> The other reason I was against complete/incomplete was more pedantic -- if you have a filled form in which all required fields are complete but have a constraint error, calling it "incomplete" feels subtly wrong. I've mostly been convinced this is relatively rare and also acceptable: if there's a constraint violation, your work isn't complete, there's still something to do.

I don't think this is a big issue because I agree that your work isn't complete if there is a constraint violation. 

Let's discuss tomorrow! I'm also happy to go back to using "No errors/errors" instead, but I do think it's interesting to try using this language to see if it works.

**Comment by seadowg** [comment]
Ok so for the moment we'll display "Complete" for forms that we expect to finalize successfully.

**Comment by seadowg** [comment]
@alyblenkin I'm feeling like it makes sense to drop the dialog for now. The delta in terms of work/complexity in between showing a dialog and just marking the form as "complete"/"incomplete" is a lot larger than I'd expected. 

We can definitely still come back to this, but I'd rather avoid it for v2023.3 to prevent problems merging the release branch into `master` (due to large modifications to the existing save flow code) later or having to write a bunch of new code for saving. The latter is something I want to do, but again would rather do it for v2023.4 which would give it more breathing room.
