### ISSUE TITLE
Styling the landing screen

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5733]
Updated Oct 3: 

We want to update the landing page so it's more consistent with the new design direction. 

**UI updates**
- Logo left aligned
- M3 buttons instead of the skinny buttons
- We don't want the buttons to stretch on larger devices. Similar to what we implemented for the home screen buttons and what we plan to do for #5735 – I believe we agreed that the max-width for larger devices would be 460px.
- Increase font size slightly for "Don't have a project?" and use a Medium text style? I think it will help make that text more obvious.

![Image](https://github.com/getodk/collect/assets/7871340/e1f8de9b-a2ef-42e2-9eef-7e9abae149e5)

**Other thought**
- I think making the text larger would create a stronger visual hierarchy. I know we are worried about a longer title, but I played around with some quick translations to see and I don't think it's that bad if we increase the font size for the title.

![Image](https://github.com/getodk/collect/assets/7871340/dedd93cb-d9dc-4210-bc27-74dd59c6ad88)

**Comment by alyblenkin** [comment]
Feedback: 

- We originally had it left aligned to allow for longer translations 
- Need to agree on min screen height we’re considering

@lognaturel - Let me know if I'm missing other considerations you had noted down

**Comment by lognaturel** [comment]
One other thing that I can think of is that we didn't want the buttons to stretch all the way to the edges of a wide screen.

https://forum.getodk.org/t/collect-prompt-for-server-configuration-on-first-launch/33051 has some iteration but nothing hugely relevant to this proposed change, I think.

Regarding minimum screen height, unfortunately I can't find any specific information about screen size from the Play Store. Here are specific devices that are popular:
<img width="490" alt="Screenshot 2023-10-03 at 9 47 04 AM" src="https://github.com/getodk/collect/assets/967540/2132fdbf-e13c-48b7-a365-507c0d3da1b6">

They're all pretty tall. Clearly that's the trend, even with budget devices. As long as the screen can scroll if needed, I don't think we need to worry too much about short devices.

Only 6% of our users currently use tablets.

**Comment by alyblenkin** [comment]
Yes, I agree that we want to make sure the buttons don't stretch on wide screens, similar to what we are thinking for #5735.

Thanks for sharing the screen sizes from the Play Store.
