### ISSUE TITLE
Button styling: increase font size

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5735]
**Context** 
When we implemented [M3 button styling](https://github.com/getodk/collect/issues/5567), we decided to slightly adjust the button height to make the hit target easier for folks. 

We noticed that the full-width button text looked drastically smaller as a result. When we looked into increasing the font size, it wasn't an easy fix because it was either too big or too small, and we would need to create something custom. 

**Soultion** 

- Increase button font size so it feels more unified 
- Remove bold font from inline buttons 

**Update Sept 25 [adding these ideas for us to pair on]**
- Make the black outline lighter (right now, it's visually distracting)
- Making the buttons scale nicely depending on your device. We might want to try scaling the buttons to the text size for tablets because the full-width buttons are too much. 

**Example of full-width inline button text being too small**

![Image](https://user-images.githubusercontent.com/7871340/267136252-ce77367e-0ad0-4609-b539-283cc1a0f2d4.png)

**Comment by lognaturel** [comment]
What about using the same font style as the main screen buttons?

**Comment by grzesiek2010** [comment]
> Increase button font size so it feels more unified

@alyblenkin are we talking about the question buttons (the blue ones used to provide answers) or maybe the navigation buttons too? Or maybe generally all buttons not only those visible in form filling?

**Comment by alyblenkin** [comment]
> > Increase button font size so it feels more unified
> 
> @alyblenkin are we talking about the question buttons (the blue ones used to provide answers) or maybe the navigation buttons too? Or maybe generally all buttons not only those visible in form filling?

Yes, we want to look at generally all buttons!
