### ISSUE TITLE
Handle bulk finalization for instances with save points

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5739]
## Acceptance

- [x] Given I was editing a draft and then quit the app half way through
When I go to Drafts
And I click "Finalize all forms"
Then the draft is not finalized
And the draft shows as "Incomplete"

## To discuss

- Do we do allow a form with a save point to be bulk finalized? If so, do we load the save point rather than the instance?
    - No. We skip finalising it and mark it as "invalid" (in the DB).

**Comment by lognaturel** [comment]
I think we should always fail in that case to force the user to review. They didn’t intend to leave the form so they should have to come back to it. Unfortunately they won’t get a lot of context on what happened but I think that’s ok for now.

**Comment by seadowg** [comment]
> I think we should always fail in that case to force the user to review. They didn’t intend to leave the form so they should have to come back to it. Unfortunately they won’t get a lot of context on what happened but I think that’s ok for now.

You mean just move the instance into a "saved with errors" state rather than showing anything specific for the moment?

**Comment by lognaturel** [comment]
Yes, exactly. And I think "Incomplete" is fine and maybe actually even better language in this case -- what we know is that there's still some action that we'd like the user to take.
