### ISSUE TITLE
Adapt bulk finalisation to current settings

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5741]
## Acceptance

- [x] Given I have at least one draft saved
And I have auto send enabled
When I go to "Drafts"
And I open the options menu
And I click "Finalize all forms"
Then all drafts are finalised and sent when auto send runs

- [x] Given I'm using an older version of Collect
And the finalize button is disabled
And there is at least one draft
And I upgrade to the current version
When I go to Drafts
Then there is no option to bulk finalize

- [x] Given I have at least one draft saved
When I go to "Form entry settings" in protected settings
And I uncheck "Finalize all drafts" in the "Uncheck to hide from Drafts" section
And I go to drafts
Then there is no option to bulk finalize

## To discuss

- ~~Where should the setting to disable bulk finalize live?~~
   - > @lognaturel How about in "Form Entry Settings" in a new section called "Uncheck to hide from Drafts"? Called "Finalize all drafts". It's not exactly "Form entry" but it feels very related and it is useful to have that setting on the same screen as where the "Finalize" and "Draft" buttons can be configured.
- ~~What should we do in the case where bulk finalize and finalize are disabled? Should that setup be forbidden?~~
    - > @lognaturel I don’t think it should be. It would support workflows in which sending requires the admin password.

**Comment by lognaturel** [comment]
> What should we do in the case where bulk finalize and finalize are disabled? Should that setup be forbidden?

I don’t think it should be. It would support workflows in which sending requires the admin password. 

Relatedly, I think that if Collect is configured to disable finalize/send from the last form screen and a user upgrades to this version, then bulk finalize should also be hidden. Otherwise we’d be opening up a way for data collectors to send in workflows where they weren’t able to before. Those existing users should need to opt in to this new behavior.

**Comment by seadowg** [comment]
> I don’t think it should be. It would support workflows in which sending requires the admin password.

Right good point. So we don't bother with a message in that case then I guess.

**Comment by lognaturel** [comment]
> all drafts are finalised and sent when auto send runs

Not sure whether this should be tracked here or in a separate issue, but I think bulk finalization needs to trigger autosend when it completes and has finalized more than one form.

> "Send all forms" (replacing "Finalize all forms")

I think we should consider always showing "Finalize all forms". It's one less (tiny) bit of logic to consider which makes things like docs easier to write. And it better addresses cases where form-level autosend might be specified for some forms.

> Where should the setting to disable bulk finalize live?

How about in "Form Entry Settings" in a new section called "Uncheck to hide from Drafts"? Called "Finalize all drafts". It's not exactly "Form entry" but it feels very related and it is useful to have that setting on the same screen as where the "Finalize" and "Draft" buttons can be configured.

**Comment by seadowg** [comment]
@lognaturel @alyblenkin I'm sure this made sense a month ago, but today I'm not sure why we added this:

> Given I'm on the end screen of a form
And the "Finalize" button is hidden from the end screen (in protected settings)
Then I see a banner reading "To send forms, go to the menu in Drafts, and select "Finalize all forms."


Is this to support workflows where "Finalize" is disabled from form end, but bulk finalized is still enabled? That would make sense to me, but I'm undecided on if we should be "promoting" bulk finalized like this. Either way, I guess we need to also not show this message in the case where both finalize options are hidden?

**Comment by lognaturel** [comment]
I’m also not sure about this one. I think a more common path (certainly now when bulk finalize is new) would be that a supervisor unlocks admin mode, verifies each submission, and finalizes as they go.

Is it ok to just have no help/warning text?

**Comment by alyblenkin** [comment]
Ah yes, we were considering showing [different text](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=2465%3A29310&mode=design&t=raS5ZciiCJJavcgw-1) in the blue message on the end screen. 

> Is it ok to just have no help/warning text?

I think we can get away with not displaying any information there! I think it was more of an idea we explored, but we didn't decide if we wanted to go forward with it.

**Comment by srujner** [comment]
1) In the Acceptance there is: And I uncheck "Finalize all drafts" in the "Uncheck to hide from Drafts" section”
But in the app it is called “Finalize all forms” instead of “Finalize all drafts”. Is there a bug in the Acceptance Criteria or in the app?
