### ISSUE TITLE
Double "end screen” event in the audit logs in a form with background audio

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5752]
#### ODK Collect version
the store version 2023.2.4, the master version ab1af3340487565345779efd39cb13145738471a
#### Android version
10, 11, 13
#### Device used
Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
There is a double "end screen” event in a form with audit and background location and audio.
#### Steps to reproduce the problem
1. Go to AuditTestLocationBackgroundAudio.xml.
[AuditTestLocationBackgroundAudio.xml.txt](https://github.com/getodk/collect/files/12736494/AuditTestLocationBackgroundAudio.xml.txt)
2. Fill the form and send or save as draft.
3. Check the CSV file with the audit logs.
#### Expected behavior
The "end screen” event should appear only once.
#### Other information
I tired to eliminate some factors but for the time being I manage to reproduce it only in this form with audit. I tried the same form (with background location) without audio and the issue doesn’t occur.

**Comment by grzesiek2010** [comment]
This will be fixed by https://github.com/getodk/collect/pull/5742
