### ISSUE TITLE
Use form-based hostname when asking for credentials

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#576]
URLs specified in a form ([submission_url](http://xlsform.org/#settings)), can override Collect's settings. When the user is asked for credentials, use the hostname in the URL and not the settings.

**Comment by Midhun07** [comment]
@yanokwa can i work on this? This is related to another issue "issue #538: If credentials are invalid tell the user ". I have submitted a patch for that issue. i think once that gets accepted this can be worked upon.

**Comment by lognaturel** [comment]
Yes please, @Midhun07.

**Comment by Midhun07** [comment]
@yanokwa i think i misunderstood the form that you have mentioned here. I searched the project files but didn't find such a form. Where am i getting wrong? Please guide.

**Comment by yanokwa** [comment]
@Midhun07 Sorry I wasn't clearer! Generally, forms post to the server URL that is in the settings. The XML of that form looks like this..
```
<model>
   <instance>
```
Forms can also post to form-specific URLs. This is required when using encrypted forms, but you can also just set it in regular forms.
```
<model>
   <submission action="https://nafundi-test.appspot.com/submission" method="form-data-post"/>
   <instance>
```

So in the case of a form submission where there is a form-specific URL and credentials are required, it'd be good if the error message referred to that form-specific hostname. 

To test, set your device's server to https://opendatakit.appspot.com. Confirm this is working by getting blank form. You should see forms like Biggest N of Set, Birds, Cascading Select. 

Now, rename this form ([custom-url.xml.txt](https://github.com/opendatakit/collect/files/848378/custom-url.xml.txt)) to custom-url.xml and [manually push it to your device](https://github.com/opendatakit/collect/#testing-a-form-locally). Note that the form XML has https://nafundi-test.appspot.com/submission as the submission url.

With your computer's browser, log into the https://nafundi-test.appspot.com with admin/admin. Go into Site Admin, then preferences, and uncheck all permissions for anonymousUser. Save Changes.

Now fill out the custom-url form on your device and try to send it in. It should show an alert that says you should enter the username and password for opendatakit.appspot.com. But that isn't correct! The server should be nafundi-test.appspot.com because that's what is in the form.

And to be extra sure things work when you are making your changes, try creating another user on the server with Data Collector privileges and make sure those credentials work.

When you are done testing, re-enable permissions for anonymousUser.

**Comment by yanokwa** [comment]
Hi @anudeepti2004! Can you give this issue a try?

**Comment by anudeepti2004** [comment]
Absolutely

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
