### ISSUE TITLE
Finalizing a broken form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5771]
#### ODK Collect version
the store version 2023.2.4, the master version 8ebe28693618f3c8a6fb07e92f5755f266f08c54
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A23
#### Problem description
This issue is a follow-up of discussion in PR #5760 connected with possibility of finalizing (also bulk finalizing) broken forms.
Should it be possible to finalize a broken form (with an error)?
#### Steps to reproduce the problem
1. Go to a form with some errors (example g6error).
[g6Error.xml.txt](https://github.com/getodk/collect/files/12845358/g6Error.xml.txt)
2. In the error message tap "Ok”.
3. Finalize the form

OR

1. Go to the form.
2. In the error message tap "Ok”.
3. Save the form as draft.
4. Go to Drafts (form is complete) and tap "Finalize all forms”.

**Comment by seadowg** [comment]
@lognaturel we're ok with this right? I can't remember if we ever had a discussion about it. I think this is probably a "won't fix".

**Comment by lognaturel** [comment]
My initial reaction was that it's a problem we should fix. Then I considered that if it doesn't prevent the user from filling out a required value and doesn't lead to a constraint violation, maybe it's ok. A case where this kind of error might happen would be if a form uses a newer form feature and a user with an older client consumes it. If it only affects an optional field, maybe it's not the end of the world. I'm ok with closing as won't fix.
