### ISSUE TITLE
Out of memory, Collect isn't reponding while editing a big form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5777]
#### ODK Collect version
the store version 2023.2.4, the master version
#### Android version
8.1, 10, 11, 13
#### Device used
Nexus 5X, Redmi 9T, Samsung M12, Pixel 6a
#### Problem description
Editing a big form with external CSV causes the "Out of memory” crash or "Collect isn’t responding”.  
The results may be a bit different for each reproduction but in general:
- it happens while the form is edited (rather older devices), when the form is saved as draft or finalized (in a form and bulk finalized)
- on Nexus and Redmi (older devices) "Collect isn’t responding” appears almost every time
- on Redmi there was "Out of memory” crash
- on Pixel 6a (Android 13) after repeating steps 4-6 four times there "out of memory” error
- almost on all devices while editing the screen goes white/black for a moment
#### Steps to reproduce the problem
1. In settings auto send  is off.
2. Open Kobo test form.
[Kobo_Test.xlsx.txt](https://github.com/getodk/collect/files/12879412/Kobo_Test.xlsx.txt)
[places.csv.txt](https://github.com/getodk/collect/files/12879415/places.csv.txt)
3. Don’t fill answers, go to the hierarchy view, go to end and save as draft.
4. Go to Drafts and fill the answers.
5. Finalize the form.
6. Edit the finalized form (change all the answers) and finalize again.

If necessary repeat steps 4 – 6. The form can be finalized or saved as draft.

Android 10    and    Android 13
![ouofmemory](https://github.com/getodk/collect/assets/56479916/be98b231-ce1d-4a0d-b556-32f1fbb81447)

**Comment by dbemke** [comment]
The "Out if memory" crash occurred also while opening a form after "Finalize all forms" on 10 big Incomplete forms (on Android 10 Redmi 9T).

**Steps to reproduced:** 
1. Save as draft 10 (or more) big forms and leave some required questions empty (form in the issue above).
2. Go to Drafts and tap "Finalize all forms".
3. Go to Start new form and try to open the big form.

If necessary repeat steps a few more times.

**Comment by seadowg** [comment]
Great find! Sounds like we have something hanging around in memory from loading/saving/finalizing forms.

@lognaturel I'm going to move this into the v2023.3 release.
