### ISSUE TITLE
Update the way valid/invalid drafts are displayed on a map

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5787]
#### Problem description
As I said in https://github.com/getodk/collect/pull/5786#discussion_r1365290974
drafts might have valid/invalid status but they are displayed on a map in the same way. 

#### Solution
Display the errors/no errors pill on a bottom sheet so users still have the map's context when assessing what action they need to take. 

- Changing the information hierarchy to match the drafts list 
- Removing the form icon if possible, if not, could we make it black so it's consistent with the others?
- Edit button moves below the errors label and timestamp
- Add 'drag handle'

[Figma mockup](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3252%3A39096&mode=design&t=hfGygb6uRsRUY6Rt-1)

Edit Nov 23:
One thing I didn't consider was displaying geometry, now that we plan to move the edit button below the error label and timestamp. Given that we are implementing the 'drag handle' at the top of the sheet with the MBtiles work, I would like to use that same functionality here and display the geometry so it's visible, it doesn't fall beneath the fold, and it can expand if needed.

**Comment by seadowg** [comment]
@alyblenkin would be good to get your take on this!

**Comment by alyblenkin** [comment]
@seadowg @grzesiek2010 - I think we should keep the design pretty close to how we display errors/no errors in the drafts list. Adding icons to the map might make it more confusing. [Figma mockup](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3252%3A39096&mode=design&t=isftoQz89RtAUv2P-1).

**Comment by seadowg** [comment]
This looks good to me! Could you update the issue description with that and any details you think are important?
