### ISSUE TITLE
Include "finalize all drafts" setting in migration of old "mark form as finalized" 

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5788]
From @dbemke in https://github.com/getodk/collect/pull/5776#issuecomment-1772620550

Old QR codes may have the old "mark form as finalized" admin setting. That setting was migrated to show/hide finalize and save as draft buttons on the form end screen. Now the finalize setting was migrated again so that introducing the "finalize all drafts" setting doesn't add a path to finalize for existing configurations. We should migrate the original "mark form as finalized" admin setting to match that.

**Comment by seadowg** [comment]
Just to clarify what @lognaturel is saying here (correct me if I'm wrong): if "default to finalized" is false and "mark as finalized" is hidden in old settings and they're migrated (via an import or an upgrade) the "Finalize all drafts" should be hidden.
