### ISSUE TITLE
Editing finalized banner doesn't appear in GD project

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5789]
#### ODK Collect version
the store version 2023.3 Beta 0
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
The banner (editing finalized) introduced in the PR #5762 doesn’t appear in a GD project. After editing a finalized form in the upgraded version of Collect the banner appears in other projects before editing a finalized form in it.
#### Steps to reproduce the problem
1. Download a released version e.g. 2023.1.2 (possible to create GD projects).
2. Download and finalize some forms.
3. Go to the playstore and update to 2023.3 Beta 0
4. Go to the GD project and edit a finalized form ( the editing finalized banner isn’t shown).
5. Add a Central project ( the banner is shown).
#### Expected behavior
The banner should appear in a GD project after editing a finalized form.
The banner shouldn’t appear in other project until editing a finalized form.

**Comment by grzesiek2010** [comment]
This is the expected behavior see https://github.com/getodk/collect/pull/5762#discussion_r1352612479

**Comment by dbemke** [comment]
@grzesiek2010 Is it also expected that if I edit a finalized form and add a new project the banner is shown also in following projects in which none of the finalized forms were edited? (No matter if it's a GD project)

**Comment by grzesiek2010** [comment]
> @grzesiek2010 Is it also expected that if I edit a finalized form and add a new project the banner is shown also in following projects in which none of the finalized forms were edited? (No matter if it's a GD project)

It was implemented like that so I believe the answer is yes but let's ask @seadowg for confirmation.
