### ISSUE TITLE
Adding Up Button

### ISSUE THREAD

**Issue by rijuldhir** [getodk/collect#579]
Software and hardware versions
Current master branch

It would be nice UI Change adding Up buttons to all of the activities. I would like to work on it

**Comment by lognaturel** [comment]
I think that this should probably be part of #464 as the flow through the app could change dramatically.

**Comment by rijuldhir** [comment]
@lognaturel 
As this is a GSoC Project. So should I make Proposal for User Experience as I am a GSoC Participant too ?
I am keen on improving UI of the App

**Comment by lognaturel** [comment]
Yes, this could very well be something you include as part of your proposal! I would encourage you to think about the questions that I asked in the issue. As you're thinking about those, if you find that up buttons would help with navigation, you can include that in your proposal writeup.
