### ISSUE TITLE
Selfie widget doesn't change to landscape view

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5804]
#### ODK Collect version
the store version 2023.3 Beta 1, 2023.2.4
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
In Selfie widget the camera doesn’t change to landscape view after rotation. The taken photo is in the portrait view.
#### Steps to reproduce the problem
1. Open All widgets form and go to Selfie widget.
2. Tap "Take a picture”.
3. Rotate the device so that it’s in the landscape view.
4. Take a photo.
#### Expected behavior
The camera should take photos in the landscape view.

**Comment by seadowg** [comment]
We might mark this as "won't fix" as we're not sure we need to support landscape selfies

**Comment by seadowg** [comment]
Marking this as "won't fix".
