### ISSUE TITLE
As of July 31, 2023, Stamen Map Tiles are served by Stadia Maps

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5806]
#### Problem description
As of July 31, 2023, Stamen Map Tiles are served by Stadia Maps. Learn more here: https://maps.stamen.com/stadia-partnership/
It seems that this will no longer be free:

```
Once you have signed up for an account with Stadia, your cost is based on tile usage, meaning how many map tiles are requested through your app or website.

- If your current usage is less than 200,000 tiles / month—FREE for non-commercial use
- If your usage goes above 200,000 tiles / month or you are a commercial user—plans start at $20/month. The full pricing is [here](https://stadiamaps.com/pricing/).
```

This should be removed and the setting should be migrated to OSM.

**Comment by yanokwa** [comment]
Do we have a sense for how many people use this basemap vs the others? I'm not opposed to paying for tiles if it's something that is needed, but my gut is that Google/OSM/Mapbox is sufficient.

**Comment by lognaturel** [comment]
I think we should remove it. We just need to make sure anyone who has it set gracefully falls back to some other base map, default osm I imagine.

**Comment by grzesiek2010** [comment]
> Do we have a sense for how many people use this basemap vs the others?

We don't have any data. I think I agree with @lognaturel that we probably can remove it but if you want to be cautious we can add analytics in v2023.3 to check it and then if the number of users is low we can remove Stamen maps in v2023.4.
