### ISSUE TITLE
Minimizing the app while on enter identity dialog (in Identify user form) closes the form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5807]
#### ODK Collect version
the store version 2023.3 Beta 1, 2023.2.4
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
Minimizing the app while on enter identity dialog (in Identify user form) closes the form without any save point and "reopens/ doubles" the app/main menu
#### Steps to reproduce the problem
1. Go to Identifity user form.
[identify-user-audit.xml.txt](https://github.com/getodk/collect/files/13186755/identify-user-audit.xml.txt)
2.  While on "Enter identity” dialog, minimize the app, go to a different app and go back.
3. The user is moved to the main menu, click the device back button - the main menu is "opened/loaded” once again.

If steps 1-2 are repeated 4 times, the user needs to click back button 4 times to leave the app (4 times main menu loads).
#### Expected behavior
The form shouldn’t close after minimizing

**Comment by grzesiek2010** [comment]
It's the same as https://github.com/getodk/collect/issues/5549 right?

**Comment by dbemke** [comment]
Yes but I also added the "reopening" of the app in this issue

**Comment by seadowg** [comment]
> Yes but I also added the "reopening" of the app in this issue

I don't understand. Should this be two issues or is there just more to add to #5549?

**Comment by dbemke** [comment]
@seadowg I don't know if it should be a separate issue because I don't know the root cause of them.

**Comment by grzesiek2010** [comment]
I think it could be one issue. @dbemke please update https://github.com/getodk/collect/issues/5549 to include details from this one and we can close it.
