### ISSUE TITLE
Save Point is not created in Identify User form

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5808]
**ODK Collect version**
the store version 2023.3 Beta 1

**Android version**
10, 13

**Device used**
Redmi 9T, Pixel 6a

**Problem description**
Save Point is not created in Identify User form.

**Steps to reproduce the problem:**

1. Start new form: [identify-user.xml.txt](https://github.com/getodk/collect/files/13186815/identify-user.xml.txt);
2. Fill the Identity field and move to the next tab;
3. Save Form as Draft;
4. Go to the Drafts tab and edit Saved before form;
5. Kill the app when you are at the Enter Identity tab;
6. Open the app, go to the Drafts tab and click on Finalize All Drafts;
7. Tap "Finalize" when the dialog displays;
8. Form has been Finalized

**Expected Results;**
Form should not be Finalized

**Comment by seadowg** [comment]
I'm not sure this is a bug. At step 5 you don't actually start form entry as you don't enter an identity right? If so, I wouldn't expect there to be a save point yet.

**Comment by srujner** [comment]
> I'm not sure this is a bug. At step 5 you don't actually start form entry as you don't enter an identity right? If so, I wouldn't expect there to be a save point yet.

Yes, if I enter identity and move to the next step and then kill the app, save point is created correctly.

**Comment by seadowg** [comment]
Right. This is excepted then as we haven't actually started form entry yet. Does that make sense?

**Comment by srujner** [comment]
Yes!
