### ISSUE TITLE
Show details after "Form update failed"

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5809]
#### ODK Collect version
the store version 2023.3 Beta 1, 2023.2.4
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
The notification after downloading a project with a form which failed to download doesn’t show details of the form which failed (in match exactly). If I the user taps the notification, he’s moved to the list of new forms (without any additional information/ dialog).
![formdowloadFailed](https://github.com/getodk/collect/assets/56479916/9405abf5-e9a6-4952-b153-2f07391d061e)

If it’s in manual blank form update mode the user can click "Show details" in the dialog and see which forms failed.
![details](https://github.com/getodk/collect/assets/56479916/234779b4-1e58-44c7-85a2-60a487d4fa50)

I think this might have been like that for a while (tests covered only manual mode) or it is the expected result but I decided to file an issue so that you can verify if in match exactly the details of failed forms should also be shown.
#### Steps to reproduce the problem
1. In Central add a broken form to a project.
[asasas.xml.txt](https://github.com/getodk/collect/files/13189176/asasas.xml.txt)
2. Add this project to Collect (match exactly mode).
3. Check the notification after downloading all forms (about 1 that failed).
4. Tap the notification.

**Comment by seadowg** [comment]
As far as I know, this was never a feature. Definitely would be nice if it behaved as described, but not something we're planning to work on soon. I'll close this.
