### ISSUE TITLE
Missing "Form update successful" notification

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5810]
#### ODK Collect version
the store version 2023.2.4, 2023.3 Beta 1
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
There is no notification "form update successful” after updating a list of forms in match exactly blank form update mode.
("Form update failed” notification appears when there is a broken form- works as expected).
#### Steps to reproduce the problem
Match exactly blank form update mode
1. Add a project from Central to Collect.
2. Wait until the list of forms downloaded.
3. Go to Central and add access to some forms in the project (or change a version of a form).
4. Wait on the main menu (don’t open start new form) about 15min until match exactly downloads the added forms
#### Expected behavior
There should be a notification about form updates.

**Comment by seadowg** [comment]
> There should be a notification about form updates.

No there shouldn't! We only show notifications when syncing fails in "Exactly match server" mode.
