### ISSUE TITLE
Saving as draft from form exit dialog results in screen flashing

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5817]
#### ODK Collect version
v2023.3-beta.2; I have not yet verified whether it also happens on older versions

#### Android version
Android 13

#### Device used
Samsung Galaxy A13

#### Problem description

https://github.com/getodk/collect/assets/967540/d239b1ef-ef34-4f7a-955f-17b07a96e51f

#### Steps to reproduce the problem
In a form, tap the back button and select "Save as draft"

#### Expected behavior
Same experience as tapping "Save as draft" from the end of the form: there's no flashing of the screen.

**Comment by seadowg** [comment]
This is a duplicate of #5601 as far as I can tell. Going to copy the video over there though as it's a great example of the problem!
