### ISSUE TITLE
Extend separator lines for Start new form

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5819]
Separator lines were just extended for all filled form listings. They're still short for the blank form listing:
<img width="760" alt="Template(1)" src="https://github.com/getodk/collect/assets/967540/cf8970b9-b3d2-46f6-8dc1-ce7ee887d006">

**Comment by grzesiek2010** [comment]
This has been already fixed in https://github.com/getodk/collect/pull/5765 see https://github.com/getodk/collect/commit/a742228a3224f96443656b9e7866c5adca8ca091#diff-27e2a45d11834c0c9908b4f0a3c97d443500de6700fb110f965ef9115fcbf981L6
