### ISSUE TITLE
Empty states: Copy changes 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5820]
#### Problem description
Some of the copy changes were missed for "Delete" and "Start new form" when [improving empty states ](https://github.com/getodk/collect/pull/5768). Looking at it again, we thought we could make the copy for "Start new form" more actionable, so I've updated that below. 

Current copy: 
- Start new form: "No blank forms: Once you have blank forms, they will appear here"
- Delete: "Nothing available to display" 

Updated copy:
- Start new form: "No blank forms: Download form to get started"
- Delete: "No forms to delete: Once you have saved forms they will appear here"

[Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3284%3A88158&mode=design&t=hfGygb6uRsRUY6Rt-1)

**Comment by grzesiek2010** [comment]
@alyblenkin please take a look.
Do you think that we should differentiate somehow messages displayed in the lists of forms to delete to have different ones for the list of blank forms and the list of filled forms? They exist in the same place and you switch between them just when you swipe left/right.
