### ISSUE TITLE
Questions are not updated if select_multiple used with no-buttons appearance on a field-list

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5821]
#### ODK Collect version

v2023.2.4

#### Problem description
The issue has been originally reported on the forum: https://forum.getodk.org/t/relevance-from-select-multiple-answers-not-triggering-while-inside-field-list-group/43627

If there is a `select_multiple` question used with `no-buttons` appearance and it's placed on a `field-list` so that the visibility of other questions depend on that first question, then other questions are not updated automatically.

#### Steps to reproduce the problem
Test the form from the forum:
[sample.xlsx](https://github.com/getodk/collect/files/13264277/sample.xlsx)
1. Navigate to the second question
2. Select one of the options
3. Other questions should appear/disappear based on the selected option

**Comment by seadowg** [comment]
@grzesiek2010 is this a problem with the beta or is it an existing issue?

**Comment by seadowg** [comment]
This feels high priority to me as it could lead to incorrect form entry due to missed questions. I don't think it's worth holding up our v2023.3 release however so I'll create a v2023.3.x milestone for hotfixes that this can slide into.

**Comment by grzesiek2010** [comment]
It's not regression so it's not super important but would be good to add it to v2023.4 or v2023.3.x if we are going to have a point release with some other hotfixes.
