### ISSUE TITLE
Keyboard collapsed on some text field (every other?)

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5828]
#### ODK Collect version
v2023.3.0

#### Android version
13

#### Device used
Samsung Galaxy A13

#### Problem description

https://github.com/getodk/collect/assets/967540/77044f23-f303-4418-909f-ef00cb71cb34

#### Steps to reproduce the problem
Unsure! On my device, any form with fields that require keyboard input one after the other will repro. I asked @alyblenkin about this and she says that on her device the keyboard is always shown when expected.

The Galaxy A13 I'm using now is our second-most popular device so it does feel important to look into. @dbemke and @srujner can you please see whether you can reproduce?

#### Expected behavior
The keyboard is shown when the first field on the screen has text input.

**Comment by lognaturel** [comment]
@seadowg pointed out that it could be the Samsung keyboard app. I tried the Gboard app and got the same behavior. He thinks it could be a Samsung-specific issue.

**Comment by lognaturel** [comment]
Same behavior on [Galaxy Tab A7](https://www.samsung.com/us/mobile/tablets/galaxy-tab-a/galaxy-tab-a7-lite-8-7-32gb-grey-at-t-sm-t227uzaaatt/) which is another of our most popular devices. This is feeling pretty serious to me now.

**Comment by seadowg** [comment]
> Same behavior on [Galaxy Tab A7](https://www.samsung.com/us/mobile/tablets/galaxy-tab-a/galaxy-tab-a7-lite-8-7-32gb-grey-at-t-sm-t227uzaaatt/) which is another of our most popular devices. This is feeling pretty serious to me now.

No luck reproducing on an emulator with the same API level? That's assuming the tablet and the phone are running the same Android. I can probably get myself a Tab quickly if we need specific devices for repro.

**Comment by lognaturel** [comment]
And to be explicit, this is new behavior in v2023.3.0; v2023.2.3 works as expected on both devices.

**Comment by grzesiek2010** [comment]
> And to be explicit, this is new behavior in v2023.3.0; v2023.2.3 works as expected on both devices.

are you sure? I've just reproduced it on an emulator (Pixel 2 API 31) but I see the same behavior on v2023.2.3, v2023.2.4, v2023.3.0.

**Comment by lognaturel** [comment]
Huh. I thought I'd confirmed it worked on the Galaxy A13 with previous versions but now it's reproducing the issue every time I try. Maybe I got confused between devices?

The Galaxy Tab A7 works as expected on 2023.2.3:

https://github.com/getodk/collect/assets/967540/5a6888c3-cae6-4630-ad17-d2ad9ca0a7b3

Glad you have an emulator repro, that will hopefully make it easier to hunt down.

**Comment by srujner** [comment]
@lognaturel Hey I was able to reproduce the collapsing keyboard but in a different way. Simply moving forward and back caused no error, but when I added empty "Enters" to String widget and started rotating the device then the keyboard collapsed. 
**Android 13, Google Pixel 6a, v2023.3.0**

https://github.com/getodk/collect/assets/85225519/8a9f6ceb-e75d-48f1-ad23-9b43184ddb10
