### ISSUE TITLE
Add question type that shows preview and prints to Android-connected printer

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5831]
Background forum thread: https://forum.getodk.org/t/printing-id-cards/6904/6?u=ln

## Acceptance

-  [x] Given I have a form field that requests printing (it has the `printer` appearance)
  When I view that form field
  Then I see a "Print" button

- [x] Given I see a "Print" button during a form filling session
  When I tap that button
  Then I see an indeterminate progress indicator
  Then I see a preview of the rendered HTML from the form definition

- [x] Given I see a "Print" button during a form filling session
  When I tap that button
  And I see a preview
  When I tap the device back button
  Then I am returned to the printing form field and nothing has printed

- [x] Given I see a "Print" button during a form filling session
  When I tap that button
  And I see a preview
  When I tap the print FAB
  Then I the specified printer prints the document

### HTML contents

- [x] Given my form field that requires printing is set to a value that concatenates in values from the form
  When I view that form field and tap the "Print" button
  Then the preview includes values for those form fields

- [x] Given my form field that requires printing is set to a value that concatenates in values from the form
  When I view that form field and tap the "Print" button
  Then I tap the device back button
  Then I change the value of one of the form fields used in the HTML
  When I view that form field and tap the "Print" button
  Then the preview includes the new value for the form field

- [x] Given my form field that requires printing is set to a value that includes an opening and a closing `qrcode` tags
  When I view that form field and tap the "Print" button
  Then the preview includes a QR Code that encodes the text between the opening and closing `qrcode` tags

- [x] Given my form field that requires printing is set to a value that includes multiple opening and closing `qrcode` tags
  When I view that form field and tap the "Print" button
  Then the preview includes multiple QR Codes each encoding the text between the opening and closing `qrcode` tags

### Notes
- It should always be possible to print to PDF file (we may not have control over this but should check it's possible on all Android versions)
- It should be possible to print many times. There's no state that keeps track of whether printing has succeeded or not.

**Comment by grzesiek2010** [comment]
> Given I see a "Print" button during a form filling session
When I tap that button
And I see a preview
When I tap 'Cancel'
Then I am returned to the printing form field and nothing has printed

@lognaturel I don't see any `cancel` button in the preview. Do you? If so it must depend on the Android version.
