### ISSUE TITLE
Convert reference layer selection to bottom sheet in select one from map

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5845]
## Acceptance

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
And no layer has been selected before
When I open the select one from map view
And I press the layers button
Then I see a list of the available layers as bottom sheet
And "None" is selected

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
And I've selected one of those layers in settings
When I open the select one from map view
And I press the layers button
Then I see a list of the available layers as bottom sheet
And the expected layer is selected

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I swipe the bottom sheet up above the middle of the screen
Then the bottom sheet should fill the screen

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I press back
Then I should return the map

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I select a layer
And I click "Save"
Then I am returned to the map with that layer being used

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I select a layer
And I click "Cancel"
Then I am returned to the map with whatever was being used before as the reference layer

## Notes

- Figma link: https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows.
- In the current/old UI, the list of layers are loaded on the UI thread (straight from `DirectoryReferenceLayerRepository`). Given this involves scanning the file system, this should definitely be happening in a background thread (probably using `Scheduler#immediate`) and the bottom sheet should display a centred (in the bottom sheet) [circular progress indicator](https://m3.material.io/components/progress-indicators/overview) while they're loading.
- The implementation of the bottom sheet itself will probably be similar to the summary sheet in `SelectionMapFragment` although it might need to be a `Fragment` itself so that it's more reusable (as it will eventually be used in other places).

**Comment by konishon** [comment]
@seadowg 
Here's the plan for the implementation of this issue 

# Bottomsheet and Offline Preferences 

- Add OfflineMapLayerPreferencesFragment,  A new Kotlin class that acts like our current map preferences screen but focuses on just managing map layers.
- Create OfflineMapLayersListBottomSheetDialog, when it's created (onViewCreated() is called) replace it with OfflineMapLayerPreferencesFragment
- Within the OfflineMapLayerPreference, I'll add a new ButtonPreference component for importing new layers (add layer button)
- For importing and moving files, I am planning to add the methods in FileUtils. Large part of this work has been completed on this fork (https://github.com/konishon/collect/tree/v2023.2.0.3-mbtiles-import) 

# File Stucture 
- org/odk/collect/android/preferences/screens/OfflineMapLayerPreferencesFragment.kt
- org/odk/collect/android/preferences/ButtonPreference.kt
- org/odk/collect/android/geo/OfflineMapLayersListBottomSheetDialog.kt

**Comment by seadowg** [comment]
Thanks for detailing that @konishon. I've got a few thoughts:

* I don't think we need any of the new components to use Android's Preferences framework (I think that's what you're implying for `OfflineMapLayerPreferencesFragment`, but sorry if that's incorrect). I was thinking the the bottom sheet could be implemented using a `BottomSheetDialogFragment`?
* I'm not sure about about adding anything to `FileUtils`. The logic for moving files will most likely need to be at least live in a `ViewModel` so that it can be executed in the background (via `Scheduler`) and be safe from problems introduced through rotations etc (the process of [creating a demo project on `FirstLaunchActivity`](https://github.com/getodk/collect/blob/484889eeed73e9a7737034889a1fbbc9fb1a700f/collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt#L125) is a good example of that kind of structure). I definitely agree the logic for importing could live separate from the view code though - we typically use a ["use case"](https://en.wikipedia.org/wiki/Use_case) pattern for things like that (see `LocalFormUseCases` or any other `...UseCases` classes for examples).
* I think all of this should live in the `maps` submodule rather than in `collect_app` as it'll need to be accessible from `SelectionMapFragment` and it's also maps specific code. The `ReferenceLayerRepository`, `Settings` and the settings key to use for maps could be passed via the constructor for the `BottomSheetDialogFragment` using a `FragmentFactory` (see `SelectionMapFragment` for an example of that structure).

**Comment by konishon** [comment]
> * I don't think we need any of the new components to use Android's Preferences framework (I think that's what you're implying for `OfflineMapLayerPreferencesFragment`, but sorry if that's incorrect). I was thinking the the bottom sheet could be implemented using a `BottomSheetDialogFragment`?

Hey! Thanks for all the feedback. @seadowg I want to discuss the first comment first, as it is crucial for the implementation. 

I wanted to add more technical clarity, 

1. `OfflineMapLayersListBottomSheetDialog` class will inherit `BottomSheetDialogFragment`
and on `onViewCreated` method `OfflineMapLayerPreferencesFragment` will be attached. 

```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val mapsPreferencesFragment = OfflineMapLayerPreferencesFragment()
        childFragmentManager.beginTransaction()
                .replace(org.odk.collect.android.R.id.bottom_sheet_fragment_container, mapsPreferencesFragment)
                .commit()
    }
```


2. `OfflineMapLayerPreferencesFragment` class will inherit `BaseProjectPreferencesFragment` class. 
Similar to `[MapsPreferencesFragment`](https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt)

**Comment by seadowg** [comment]
> 1. OfflineMapLayersListBottomSheetDialog class will inherit BottomSheetDialogFragment
and on onViewCreated method OfflineMapLayerPreferencesFragment will be attached.

Why does the bottom sheet replace itself with `OfflineMapLayerPreferencesFragment`. Couldn't the bottom sheet be responsible for displaying the list of layers?

> 2. OfflineMapLayerPreferencesFragment class will inherit BaseProjectPreferencesFragment class.
Similar to [MapsPreferencesFragment]

I'm not sure why you need to extend `BaseProjectPreferencesFragment`? As far as I can tell, we could build this UI within a `BottomSheetDialogFragment` (as suggested above). The layers can be fetched from `ReferenceLayerRepository` and the setting is read/write-able from `Settings` (which can be grabbed for the project from `SettingsProvider`). Does that makes sense?

**Comment by konishon** [comment]
> Thanks for detailing that @konishon. I've got a few thoughts:
> 
> * I don't think we need any of the new components to use Android's Preferences framework (I think that's what you're implying for `OfflineMapLayerPreferencesFragment`, but sorry if that's incorrect). I was thinking the the bottom sheet could be implemented using a `BottomSheetDialogFragment`?
> * I'm not sure about about adding anything to `FileUtils`. The logic for moving files will most likely need to be at least live in a `ViewModel` so that it can be executed in the background (via `Scheduler`) and be safe from problems introduced through rotations etc (the process of [creating a demo project on `FirstLaunchActivity`](https://github.com/getodk/collect/blob/484889eeed73e9a7737034889a1fbbc9fb1a700f/collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt#L125) is a good example of that kind of structure). I definitely agree the logic for importing could live separate from the view code though - we typically use a ["use case"](https://en.wikipedia.org/wiki/Use_case) pattern for things like that (see `LocalFormUseCases` or any other `...UseCases` classes for examples).


I've refined the implementation by integrating a bottom sheet that utilizes the SettingsProvider for reading and writing settings. Additionally, I've wrapped  the file handling within a ViewModel and utilized a Scheduler for more efficient management.

Updated code: 
https://github.com/konishon/collect/commit/dacd1efb8f9ac7b58a170839eb3bedb72a6ba2d3
https://github.com/konishon/collect/commit/475962b20bb006c9819aada0d329cca67168ada0

> * I think all of this should live in the `maps` submodule rather than in `collect_app` as it'll need to be accessible from `SelectionMapFragment` and it's also maps specific code. The `ReferenceLayerRepository`, `Settings` and the settings key to use for maps could be passed via the constructor for the `BottomSheetDialogFragment` using a `FragmentFactory` (see `SelectionMapFragment` for an example of that structure).

This can be moved? but we will we need to add the main module as a dependency?

**Comment by seadowg** [comment]
> This can be moved? but we will we need to add the main module as a dependency?

Definitely can be moved. Maybe it's worth submitting a PR now if you have code to review and we can discuss there?

**Comment by konishon** [comment]
@seadowg I have sent a draft PR
