### ISSUE TITLE
Allow MBTile files to be imported

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5846]
## Acceptance

- [ ] Given I'm filling out a form with a select one from map question
When I open the select one from map view
And I press the layers button
And I press "Add layer"
Then I only see `.mbtile` layer files when browsing files

- [x] Given I'm filling out a form with a select one from map question
When I open the select one from map view
And I press the layers button
And I press "Add layer"
And I select an MBTile file in the Android file picker
Then I am returned to the list of layers
And the new layer is on the list
And I can use it on the map

- [x] Given I've imported an MBTile using the "Add layer" button
Then it is available to select in all projects in Collect

## Notes

- This will involve copying a file from a path the file picker gives us. This operation should happen on a background thread (probably using `Scheduler#immediate`) rather than the UI thread. A progress dialog (`MaterialProgressDialogFragment`) should be shown during the import.

## Questions

- Should the picker only show .mbtile files?

**Comment by spwoodcock** [comment]
I can't see any reason for allowing files other than `.mbtiles` to be selected.

There are similar tile container formats using SQLite, such as that used by OSMAnd, but they have a different table structure and are not compatible. Extensions can vary: `.sqlite`, `.sqlite3`, `.db`.

But I would say that mbtiles must always have the `.mbtiles` extension to be valid.

> This does raise the question: do we need any validation that the file is indeed an MBTile file with the correct internal layout? I assume if we attempt to load an incompatible file, then the error should be caught and the user is informed that the file is 'Not valid MBTiles format`.

**Comment by seadowg** [comment]
> But I would say that mbtiles must always have the .mbtiles extension to be valid.

Do you think we should only display `.mbtile` files in the picker then?

**Comment by spwoodcock** [comment]
Yep exactly - I think it should be ok to do that 👍
