### ISSUE TITLE
Sending complete form progress dialog showing sliced upload

### ISSUE THREAD

**Issue by nribeka** [getodk/collect#585]
#### Software and hardware versions 
Collect code latest from master

#### Problem description
With the current slicing, when you upload more than the slice size, the dialog will show the sliced counter instead of the overall upload counter.

#### Steps to reproduce the problem
* Change the slice size to lower number in `ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT` (I use 3).
* In the send finalized form section, select forms more than the slice size (7 forms in my case).
* Press "Send Selected" to upload the form
* The dialog will display "Sending 1 of 3 forms" twice and "Sending 1 of 1 forms" for the last slice.

#### Expected behavior
The dialog should display the progress of the upload as a whole instead. So it should show "Sending 1 of 7 forms" and then start counting to 7.

**Comment by rijuldhir** [comment]
Can I work on this?

**Comment by lakshyagupta21** [comment]
I would like to work on this.

**Comment by lognaturel** [comment]
@rijuldhir @lokeshkvn @lakshyagupta21 Can you please read any issue thread carefully and if someone has already asked for or claimed an issue, leave them to do it? This one should go to @rijuldhir

**Comment by lakshyagupta21** [comment]
@lognaturel Sorry, actually i already started working on it that's why i asked as i found this issue while testing for one of the [previous](https://github.com/opendatakit/collect/issues/518) issue. It won't happen again in future @rijuldhir can work on this.

**Comment by lognaturel** [comment]
@lakshyagupta21 It's ok but just make sure to say right away that you're taking it in the future! 😊 It's also a good idea to say if it's related to another issue so it's clear you have some extra context for solving it. It's up to @rijuldhir to either ask more questions here to understand the problem fully or pass it on to you!
