### ISSUE TITLE
Fields for entry of name in forms should be single line

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#587]
Android v6.0.1, device used: OnePlus One

Steps to reproduce problem:
1.Fill a form such as 'Biggest N of Set' or 'Hypertension Screening'
2.Go to any question involving entry of a name(such as question 4 in 'Hypertension Screening')

Upon pressing the enter key on the on-screen keyboard, the name field allows for multi-line entry. 

It should only allow single line entry, as in most forms, there are three entry fields(first name, middle name,last name).

I will get to work on this, if there aren't any discrepancies.

**Comment by lognaturel** [comment]
This is probably not something that requires a code change. It is up to a form designer to decide whether they want to include any validation of the fields. You can find examples [here](https://opendatakit.org/help/form-design/binding/).
