### ISSUE TITLE
Rotating the device when an overflow menu is opened changes theme in some parts of the app if there are opposite themes in the app and in the device

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5898]
#### ODK Collect version
the store version 2023.3.1, the master version ee016ccddd023ed4ed3d825d83c642011e6e85c7 (2024.1.0 Beta 0)
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
If there are opposite themes in the app and in the device rotating the device when the menu options are opened (e.g. finalize all drafts in Drafts; in an opened form check for errors, change language, project settings) results in a wrong theme being applied in some parts if the app. If the same theme is set in the app and in the device the issue doesn’t occur.
![rotateTheme](https://github.com/getodk/collect/assets/56479916/df0c1d1d-8202-4c02-ba74-d9c573e10a12)

#### Steps to reproduce the problem
1. In the app set an opposite theme to the theme set in the device.
2. Go to "Start new form" and open a form.
3. Tap the three dots.
4. When the menu options are opened, rotate the screen.
#### Expected behavior
After rotating the screen the theme should be consistent with the theme set in the app in all parts of the app.

**Comment by seadowg** [comment]
Looking at analytics, only 11% of our uses are currently not using the "Use device theme" option (the default). We've had a really hard time addressing these kinds of issues (most end up marked as "won't fix"), so I think it might be time to try and phase the "Dark" and "Light" themes out. Thoughts @lognaturel @alyblenkin?

**Comment by lognaturel** [comment]
Discussed briefly as a team. It will take some amount of work and communication to deprecate the option. For now we'll keep filing these kinds of issues and mark them as won't fix. If there are many discovered or users start reporting them we'll consider what to do.
