### ISSUE TITLE
A new form is opened instead of a saved draft after clicking on a draft in the list of Drafts

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5925]
#### Problem description
A new form is opened instead of a saved draft after clicking on a draft in the list of Drafts.

https://github.com/getodk/collect/assets/3276264/b7497563-86ad-4cd5-bcc2-81f2f3a5de5d

#### Other information 
The discussion on slack: https://getodk.slack.com/archives/C03QX56DD8C/p1705588192265139

**Comment by lognaturel** [comment]
This was something @dbemke experienced on her Redmi 9t android 10 while working on v2024.1.0. @dbemke have you seen anything like this again? If not, I think we should close for now.

**Comment by dbemke** [comment]
> have you seen anything like this again?

No
