### ISSUE TITLE
Update geo button language so the defaults are user-friendly 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5930]
### **Problem**

We want to make geo language/ functionality easier to understand for new users while not confusing existing users. 

### **Solution**

**Language update** 

States | Start Geopoint | Start Geopoint with map | Start Geotrace | Start Geoshape
-- | -- | -- | -- | --
If there is no answer | Get point | Get point | Get line | Get polygon
If there are answers added | Change point | View or change point | View or change line | View or change polygon
Read only | | View point | View line | View polygon

**Comment by alyblenkin** [comment]
A few updates on the icons and language for the geo buttons. 

### Material icons

I think these might be best if we wanted to use Material icons (see [google sheet](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0) for other language options)

- Get location: [Location searching icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alocation_searching%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Get polygon: [linked services](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alinked_services%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) (not great but it might be the closest) 
- Get polyline: [polyline icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apolyline%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)


### Open-source GIS libraries 

[SVG Repo](https://www.svgrepo.com/)
- [Polygon](https://www.svgrepo.com/svg/399227/polygon-pt)
- [Polyline](https://www.svgrepo.com/svg/399231/polyline-pt)

[Font GIS ](https://viglino.github.io/font-gis/)(figma mockup below)
- [Polygon](https://viglino.github.io/font-gis/?q=polygon&fg=polygon-pt)
- [Polyline](https://viglino.github.io/font-gis/?q=polylin&fg=polyline-pt)


![Image](https://github.com/getodk/collect/assets/7871340/f9ad93da-4430-49d7-8c86-5808a0cd08b4)

I'm leaning towards using an icon library with better GIS options. Curious to know what you think @seadowg @grzesiek2010

**Comment by grzesiek2010** [comment]
It looks like there is no difference between the ones from SVG Repo and Font-gis or I'm missing something? I like them.

**Comment by alyblenkin** [comment]
@grzesiek2010, yes, there isn't a huge difference! The [SVG repo](https://www.svgrepo.com/collection/gis-mapping-icons/) has a wider range of options and styles, so that would be my preference. 

It might even come in handy for icons we need beyond the GIS set, like the [signature icon](https://www.svgrepo.com/svg/437226/signature). I also tested out the Figma icon pack, and it works well, so that would make mockups easier. 

I'll update the issue. This will only focus on updating the geo icon buttons for now.

**Comment by grzesiek2010** [comment]
@alyblenkin 
The buttons can have different titles depending on their states. I've updated the titles for the cases where the answers are already added and for the read-only mode. Please take a look and let me know if this is ok: https://github.com/getodk/collect/pull/6014/files#diff-979dfee8cac80ace70fd9295919cf27a53c1576a529230fd44e8d592e5c57658R1268

**Comment by alyblenkin** [comment]
> @alyblenkin I've updated the titles for the cases where the answers are already added and for the read-only mode. Please take a look and let me know if this is ok: https://github.com/getodk/collect/pull/6014/files#diff-979dfee8cac80ace70fd9295919cf27a53c1576a529230fd44e8d592e5c57658R1268

Looks good to me!

**Comment by alyblenkin** [comment]
I've updated the [google sheet ](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=618642060)with the new geo button language for the different states based on the forum feedback. 

I think we could use either "Add" or "Get" when there isn't an answer. I prefer "add" because the actions are very clear (add, view, or change). Let me know if you disagree, @lognaturel. 


States | "Start Geopoint" button language | "Start Geotrace" button language | "Start Geoshape" button language
-- | -- | -- | --
If no answer | Add point | Add line | Add polygon
If there are answers added | Change point | View or change line | View or change polygon
Read only | View point | View line | View polygon
