### ISSUE TITLE
Changing "Widgets" to "Questions" in the All Widgets form

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5931]
Updating the language in the demo form, so we always refer to 'widgets' as 'question types' to make it more user-friendly. 

Using 'questions' instead of 'widgets' will be a major change for docs and in our communications (e.g. social media or the forum).

**Comment by seadowg** [comment]
Agreed we should update the demo form. Is there anywhere in the app we actually mention widgets? I think this might be a docs issue rather than a Collect issue.

**Comment by alyblenkin** [comment]
@ca

> Agreed we should update the demo form. Is there anywhere in the app we actually mention widgets? I think this might be a docs issue rather than a Collect issue.

It's only in the demo form! I made it seem like there are other places in the description - I will update that now. It's more of a docs issue.

**Comment by seadowg** [comment]
No problem! That's something file over at https://github.com/getodk/docs. I think @lognaturel will be able to update the demo form.
