### ISSUE TITLE
Adjust text spacing in form entry

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5932]
In QA, the team came across a small [spacing issue](https://github.com/getodk/collect/pull/5885#issuecomment-1900484062). 

They noticed that the space between the question and answer is different than the spacing for an empty line to break up the text/ start a new paragraph. 

I don't think this is a show-stopper! If it is an easy fix, the spacing should be the same between both. 
It might be something we should pair on to get right.

![Image](https://github.com/getodk/collect/assets/7871340/6dd71226-df16-4601-9a4c-ef03d10b5d67)

**Comment by lognaturel** [comment]
Please spin this out if it doesn't feel related enough!

I think we've stretched things out a bit too much vertically:
- The spacing between paragraphs and between question label and answer feel like the most uncomfortable change to me
- The spacing between lines when a paragraph's text wraps feels like a bit too much but this feels less important than above. I could be convinced that this is an improvement and that I'm just not used to it yet.
- I think the font is the same size but now that it's lighter weight, does it feel a bit big to anyone else, especially relative to the hint font size? This feels least important

The first one I feel like needs to be addressed in 2024.1

| Before      | Now |
| ----------- | ----------- |
| ![bold-label](https://github.com/getodk/collect/assets/967540/f4dab63c-d5fb-4731-b647-2d2be5018954) |![big-label](https://github.com/getodk/collect/assets/967540/54963761-c357-498b-a420-2c679018bdb8) |

**Comment by lognaturel** [comment]
Going back to the original question from @dbemke, let's say a user entered their name on two lines. It would currently be displayed as

```
What is your name?
    Bob
    
    Smith
```

@dbemke were you thinking that should be

```
What is your name?
    Bob
    Smith
```

or 

```
What is your name?

    Bob

    Smith
```

I imagine you mean the first one? What if it were a longer answer, though? I think having a paragraph break there makes sense and that one does look balanced to me!

**Comment by dbemke** [comment]
> I think having a paragraph break there makes sense and that one does look balanced to me!

I had a look at different widgets and tried to image what users might enter there and why they go to the hierarchy view (e.g check filled answers). I agree that the paragraph break would make it easier to check/read/find filled answers in the hierarchy view.

**Comment by alyblenkin** [comment]
Thanks for your feedback everyone! Looking at the before and after images, I agree that it looks stretched, and the paragraph breaks are helpful for reviewing/checking answers. 

Playing around with these things in a pairing session @grzesiek2010 might be easier.

**Pairing tasks:**
- Check the overall spacing:
    - Spacing between paragraphs 
    - Spacing between question, label and answer 
    - Text wrapping 
    - Determine where things have stretched out vertically 

I think we should hold off on the font size for now because I'm assuming if we fix some of these issues, it might address this issue of it looking too big.
