### ISSUE TITLE
Add appearance to mask input with *

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5937]
https://forum.getodk.org/t/support-for-password-and-no-send-appearances/41152

Text and number widgets should add support for a new `masked` appearance. When this is present, text should be hidden with `*` like in a password field. There's an input type for this in Android `EditText` (`textPassword`). The text should be masked everywhere the `masked` field appears directly including in the hierarchy/summary view. It should not be masked when used in e.g. concat statements or labels (it's up to users not to do that).

If this is combined with `thousands-sep` the field should use `masked` (rather than trying to combine with separators). The appearance should work with external questions as well.

**Comment by seadowg** [comment]
@lognaturel is this something we want to add to the [roadmap](http://getodk.org/roadmap)?

**Comment by lognaturel** [comment]
@alyblenkin how do we decide whether something is "big enough" to be on the roadmap? I guess it could be very big for someone who has a reviewer workflow and wants reasonable certainty that a PIN can't be seen by data collectors. Maybe we should?

**Comment by alyblenkin** [comment]
> @alyblenkin how do we decide whether something is "big enough" to be on the roadmap? I guess it could be very big for someone who has a reviewer workflow and wants reasonable certainty that a pin can't be seen by data collectors. Maybe we should?

It's a good question. We are still figuring out a balance. We have a mix of high-level problem areas and very specific features. Ideally, we add outcomes to the roadmap if we know it will deliver value for a large group of people, client requests/ feedback or a strategic business goal. We tend to add smaller features only if it's for a client (like the Buddist calendar). We should also consider adding something to the roadmap if it's helpful to communicate with the community. So if this feature is worthwhile radiating outwards, we should certainly add it.
