### ISSUE TITLE
In date time widget which is required tapping check for errors removes an answer if only one of them was filled

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5954]
#### ODK Collect version
the store version 2023.3.1, 2024.1.0 beta 2
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In date time widget which is required tapping check for errors removes an answer if only one of them was filled.
![datetimer](https://github.com/getodk/collect/assets/56479916/63877b18-f306-4133-986e-cdd167cf0fd7)
#### Steps to reproduce the problem
1. Go to the form to the dateTimereq question.
[dateTimeTest.xml.txt](https://github.com/getodk/collect/files/14206777/dateTimeTest.xml.txt)
2. Tap "Select date” and confirm the date (don’t fill "Select time”).
3. Tap three dots, Check for errors. 
#### Expected behavior
Filled answer shouldn’t be removed

**Comment by grzesiek2010** [comment]
I think this s ok. In the case of the **Datetime** widget the answer consists of two elements: **date** and **time**. If you set just one of those there is still no answer and it will be cleared if you:
- navigate back in the form
- open the hierarchy view
- rotate the device

so it's ok to clear it when the form is being validated. Maybe it's not perfect but at least consistent with other cases. Fixing it would add complexity we don't need.
