### ISSUE TITLE
"Form updates available" notication flow

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5959]
#### ODK Collect version
the store version 2024.1.0 beta 2
#### Android version
10,14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After changes in notifications I’m not sure if going to the main menu is the best expected behavior in this case. 
When I switch from match exactly to "Previously downloaded forms only” and I add a new version of a form on a server there is a notification about available updates. Before changes in notifications this notification moved the user to the list of forms to download. Currently the user is moved to the main menu. I’m not sure if it would be possible to change where the user is moved after tapping this notification. I think that going to the list of forms to download gave the user more context – the user could see which form was updated.
#### Steps to reproduce the problem
1. Add a project to Collect.
2. Go to Settings- Form management- Blank form update mode and change to "Previously downloaded forms only” .
3. Add a new version of a form on the server.
4. Go back to Collect and wait for the notification to appear.
5. Tap the notification.
![formupdates](https://github.com/getodk/collect/assets/56479916/e21434bb-d259-4ef1-bc24-ca8b1e5d39d1)

**Comment by lognaturel** [comment]
I do think this is the expected behavior, now. Agreed that it’s not as helpful.

**Comment by grzesiek2010** [comment]
Yes this is expected, see: https://github.com/getodk/collect/pull/5827
