### ISSUE TITLE
Display message on end screen when autosend is enabled and saving drafts is disabled

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5960]
If auto-send is enabled and saving drafts is disabled, there [isn't a warning](https://github.com/getodk/collect/issues/5948#issuecomment-1936041853).

We want to display "Sent forms are not editable" and "Learn more" link, as we do when saving as draft is disabled and auto send is disabled.

**Comment by alyblenkin** [comment]
We may not want to do this in the next release, so we can finish this cycle. What do you think @lognaturel? Given that we don't have the warning now, I don't think it's a huge deal to wait.

**Comment by lognaturel** [comment]
Totally agree! We can skip it entirely, too. I think for folks with that kind of configuration, it’s expected and good that finalization is final.
