### ISSUE TITLE
Text field in field list snaps under keyboard when tapped to focus

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5963]
#### ODK Collect version
[92ad4fc](https://github.com/getodk/collect/commit/92ad4fc400795d11857d819ef650d6890f5cdb4a)

#### Android version
13

#### Device used
Samsung Galaxy

#### Problem description
| now | before             |
|----------|-------------------------------------------------------------------------------------------------------------------|
|  https://github.com/getodk/collect/assets/967540/3bec34d8-5664-4f34-983d-9f5452417ead | https://github.com/getodk/collect/assets/967540/7aebf4a4-3faf-46c1-850e-14382dc1dc0f |

#### Steps to reproduce the problem

Load the [WHO VA](https://github.com/SwissTPH/WHO-VA) form. In the first screen, tap to set the interviewer ID.

#### Expected behavior
Question that's getting focus snaps above keyboard, not below.

**Comment by grzesiek2010** [comment]
I've just tried to reproduce this on 3 devices but to no avail... @srujner @dbemke are you able to reproduce maybe?

**Comment by dbemke** [comment]
I managed to reproduce it on Samsung Galaxy M12 android 11 and Pixel 7a android 14.
I'm not able to reproduce it on Redmi 9t android 10 or Nexus 5x android 8.1.

**Comment by grzesiek2010** [comment]
Ok I'm also able to reproduce now, thanks.

**Comment by grzesiek2010** [comment]
This is not regression. I can reproduce it on v2023.3.1 and I believe it worked in the same way on older versions too. Given that I think we can remove the hight priority flag and add the issue to v2024.2.

**Comment by lognaturel** [comment]
My understanding (correct me if I'm wrong, @grzesiek2010) is that this will always have happened with field lists in which there are text questions at the top of the screen that don't trigger changes to other questions on the screen AND text questions near the bottom of screen. There's a handler for screen repaint events that gets triggered when the keyboard appears and scrolls back up to questions near the top of the screen.

It's more likely to happen now because text fields are taller and so it's more likely that questions will be off screen.

We're going to take ~24hrs to evaluate options and then decide what to do. Some initial ideas:
- Decrease vertical padding in text fields. That will make the issue less likely to occur, as it was previously.
- It sounds like there's some kind of change event that's "hanging." Can that be "consumed" in some way?
- Can the keyboard event be more independent from the other updates?

**Comment by lognaturel** [comment]
> text questions at the top of the screen that don't trigger changes to other questions on the screen

I don't think this is right. I think it's any question type. In the form I shared it snaps to the bottom of the select, right?

**Comment by grzesiek2010** [comment]
> I don't think this is right. I think it's any question type. In the form I shared it snaps to the bottom of the select, right?

I haven't tested it but yeah I believe it could be any question type.

**Comment by lognaturel** [comment]
I'm having a hard time building a consistent mental model. The keyboard type has to change to trigger the issue, I think? And then there's a jump back to the last text field that was modified?

https://github.com/getodk/collect/assets/967540/ab53a057-6081-4802-8490-197df13446f8

**Comment by grzesiek2010** [comment]
It's not only about the keyboard. It's one of the events that trigger `onLayoutChange` but there are more I belive:

https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java#L2281 

```java
try {
      updateFieldListQuestions(changedWidget.getFormEntryPrompt().getIndex());
      
      odkView.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
          @Override
          public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
              if (!odkView.isDisplayed(changedWidget)) {
                  odkView.scrollToTopOf(changedWidget);
              }
              odkView.removeOnLayoutChangeListener(this);
          }
      });
      } catch (RepeatsInFieldListException e) {
            createErrorDialog(new FormError.NonFatal(e.getMessage()));
      } catch (Exception | Error e) {
            Timber.e(e);
            createErrorDialog(new FormError.Fatal(getString(org.odk.collect.strings.R.string.update_widgets_error)));
      }
```

that's when the scrolling to the edited question takes place.
The scrolling was implemented to make sure we scroll to the question with a new answer. For example when it's populated by an external app. But do we need that listener to achieve that at all? I'm thinking about removing it so that scrolling would be called immediately after updating the list of questions and won't be triggered by events like showing the keyboard.

**Comment by grzesiek2010** [comment]
> The keyboard type has to change to trigger the issue, I think?

I think so because if it's already displayed the layout does not change. It needs to be hidden and then shown or change its type but as I said it might be also triggered by other events that change the layout.

**Comment by lognaturel** [comment]
> I think so because if it's already displayed the layout does not change.

That's good news at least. It makes it feel less urgent to me.

> I'm thinking about removing it so that scrolling would be called immediately after updating the list of questions and won't be triggered by events like showing the keyboard.

I like your thinking. So we just need to see how risky something like that feels. We'd want to check field lists with different types, particularly with external apps and secondary screens (like geopoint/image).

**Comment by grzesiek2010** [comment]
Let me see if we have any automated tests that cover the scrolling. It would be safer to introduce changes if we had at least one.

**Comment by seadowg** [comment]
@grzesiek2010 I'm pretty sure `FieldListUpdateTest` covers that (or at least maintaining focus on widgets).

**Comment by seadowg** [comment]
I'm going to move this to v2024.1.x for the moment, as it feels like we can release without a fix.
