### ISSUE TITLE
Entity updates from the server

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5972]
~~Blocked by #5924~~

If an entity exists both locally and on the server (an entity has been created or updated locally and also exists in the form's secondary instance entity list), the one used in follow up/update forms (and in the entity browser) depends on the entity's version:

- If one version is greater than the other, that entity should be used
- If the versions are equal, the local one should be used (local updates are displayed instead of server ones)

**Comment by seadowg** [comment]
@lognaturel how do you feel about these rules? I felt like using the local version in the case of a match makes sense to bias towards the enumerator seeing the data they entered and then only moving away from it if it's updated again on the server.

**Comment by Silvergreenim** [comment]
> [
```css

> ### [**605812004811355488347**](

- [ ] 
/

)

``` ](https://github.com/getodk/collect/issues/5972#issue-2138339832``)
