### ISSUE TITLE
Adjusting max width of buttons

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5973]
When we were implementing M3, we set a max width for the buttons for larger devices and tablets. 

However, in a user demo, we noticed they still appear to be stretched. I think it might be easiest to pair on this and adjust the width of the buttons and potentially the text.

![Image](https://github.com/getodk/collect/assets/7871340/68a629cd-791f-4bab-bd05-8aacc3905ebb)

**Comment by alyblenkin** [comment]
@seadowg and I had a quick chat about this one. It's not a huge deal if we don't fit it into this release.

**Comment by seadowg** [comment]
@alyblenkin I think if you add a list of places you think the max width should be applied, it'll be pretty easy to do.

**Comment by alyblenkin** [comment]
@seadowg I started playing around with [adjusting the width of the buttons](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=4440%3A89713&mode=design&t=Yexr1cO1IlSTOjnu-1). I also adjusted the width of the text as well and I think it looks better. The question is easier to read because there are fewer words in one line.


![Image](https://github.com/getodk/collect/assets/7871340/906f5115-661f-4992-9fac-eaa9bcd5ae81)


![Image](https://github.com/getodk/collect/assets/7871340/9da15a4c-a7a5-4fdf-8b3a-31a2e0bd4152)


cc @lognaturel

**Comment by seadowg** [comment]
> The question is easier to read because there are fewer words in one line.

I like this! So really the change we want to make here is to "enforce a max width for form entry content"?

**Comment by alyblenkin** [comment]
That's what I'm thinking! @lognaturel, can you think of any negative implications of doing this?

**Comment by lognaturel** [comment]
Do you have a sense of what exceptions we'd need to maintain? Here are some I can think of:
- All the column-related select appearances (e.g. https://docs.getodk.org/form-question-types/#select-widget-with-columns-pack-appearance)
- [Select grids](https://docs.getodk.org/form-question-types/#grid-of-selects-on-the-same-screen)
- [Select from image](https://docs.getodk.org/form-question-types/#select-from-image-widget)

There are some like range that I'm less sure about.

Would edit texts and select options also be centered and width-limited? That feels like it could be harder to use.

I imagine we'd have to communicate early and give users time to transition if they've done things like specifically put in linebreaks to match their device size.

Overall it makes me a little nervous! On the other hand, maybe it would be like the Enketo max width which does seem to work relatively well. What max width in pixels are you imagining?

**Comment by lognaturel** [comment]
What I had in mind was more like reducing the width of the button to something like 3 columns and leaving everything alone for now.

**Comment by alyblenkin** [comment]
Finally coming back to this one!

> On the other hand, maybe it would be like the Enketo max width which does seem to work relatively well. What max width in pixels are you imagining?

Yes, I think Enketo works well with having a max width! I was using a Surface Pro 9 as a reference and it was 990px for the width but that was just mocking it up quickly. I think we could do a pairing session to test out what work best on different size devices with the other appearances. My idea was to only bring it in slightly so we don't have super long sentences, but we would need to play around to see how it would work using other appearances to ensure it doesn't make other things worse. 

I agree this would need to be communicated in advance because people have designed their forms accordingly.

Reducing the button width because that was the initial goal seems like a good place to start, and then come back to this. So something like this


<img width="749" alt="Screenshot 2024-04-18 at 2 45 24 PM" src="https://github.com/getodk/collect/assets/7871340/31e0f40c-13b2-475b-beb6-b3d260332d45">

**Comment by alyblenkin** [comment]
I chatted with @seadowg about this one, and we don't think it's a quick fix and needs more design time. We initially thought we could change the button width. However, if we do that, the question and answer are still full-width, which makes it harder to understand what's going on (your eye needs to zig-zag to process the information) and might make tapping the button slightly more difficult. 

Since this is not a high priority and needs more design time, we are considering deprioritizing it for now until I have time to dig into some of these questions: 

- Should we have a different view for landscape? 
- How are people using landscape today? 
- What if we make specific questions max width so it doesn't negatively impact the experience selects with images for example.

**Comment by lognaturel** [comment]
Good point about usability. Sounds good to deprioritize! How about closing the issue for now since we've completed the low-hanging fruit and come to a conclusion for now.

I don't think landscape is common at all. It's a useful way to check the experience for small tablets which are very common (e.g. Galaxy Tabs). Large tablets are not all that common.
