### ISSUE TITLE
Leaks In the ODK after the screen rotation

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5976]
#### ODK Collect version
master: f20b15e8337a7e8440ae7600da3b803a5dbad8dc
#### Android version
10,13,14
#### Device used
Xiaomi Redmi 9T, Google Pixel 6a,7a
#### Problem description
Leak was found after the screen rotation

**Steps to reproduce:**

1. Open All widgets form to the first question.
2. Rotate the device.

#### Other information

![1](https://github.com/getodk/collect/assets/85225519/11be0614-79b8-4479-9dba-e59394e700cc)
![2](https://github.com/getodk/collect/assets/85225519/41a11844-4df5-4e6c-b710-fffe5bb422af)

**Comment by dbemke** [comment]
A leak after screen rotation.
![rotateLeakk](https://github.com/getodk/collect/assets/56479916/9292790a-2a44-428f-b2f2-d428b64f86fe)
![rotateLeak](https://github.com/getodk/collect/assets/56479916/dc1babe8-c50c-43a0-b661-693170e09b52)


**Steps to reproduce:**
1. Open All widgets form to the first question.
2. Rotate the device.

**Comment by seadowg** [comment]
@dbemke @srujner is it possible to break this into separate issues instead? We don't really have a way to deal with an issue that's never closed in our workflow right now.

**Comment by srujner** [comment]
@seadowg Of course, we thought that it'll be easier if all related issues will be in one. 
Could you maybe add a new label? Just for Leaks.

**Comment by seadowg** [comment]
> Could you maybe add a new label? Just for Leaks.

If that's useful for you? I don't think I need it for anything.

**Comment by srujner** [comment]
> > Could you maybe add a new label? Just for Leaks.
> 
> If that's useful for you? I don't think I need it for anything.

If it doesn't make anything easier for you then lets forget it ;)

**Comment by seadowg** [comment]
> If it doesn't make anything easier for you then lets forget it ;)

Yeah doesn't really matter to me! @dbemke can you just replace the issue description and title so that it corresponds to the leak you [commented with](https://github.com/getodk/collect/issues/5976#issuecomment-1985224486)?
