### ISSUE TITLE
NPE when loading save point

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5987]
#### ODK Collect version

v2024.1.1

#### Problem description

https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8634a8c0b8bbe19d2790751384a53014?time=last-ninety-days&sessionEventKey=65DBFCA60253000105B5038833747213_1918183420521756190

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.odk.collect.forms.Form.getFormFilePath()' on a null object reference
       at org.odk.collect.android.tasks.FormLoaderTask.loadSavePoint(FormLoaderTask.java:7)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java)
       at org.odk.collect.async.SchedulerAsyncTaskMimic.execute$lambda$0(SchedulerAsyncTaskMimic.kt:15)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```

**Comment by seadowg** [comment]
The only way I can find to reproduce this is to start `FormFillingActivity` with `ACTION_EDIT` and a forms URI for a form that doesn't exist in the current project. I need to write a unit test to make that happen however, as I don't think there is a way to get to `FormFillingActivity` without going through `FormUriActivity` which handles this error (the user sees a message with "Bad URI:"). 

My guess is that it might be possible that this is someone returning to an already opened `FormFillingActivity` after the open form was somehow deleted or the project changed. This could then happen multiple times until Android decides not to restart the app with a restored back stack (https://www.seadowg.com/2022/10/24/crash-test.html). The only fix I can see is to show an error and close the Activity. @grzesiek2010 let me know if you see other possible ways to reproduce.

**Comment by grzesiek2010** [comment]
> The only fix I can see is to show an error and close the Activity. @grzesiek2010 let me know if you see other possible ways to reproduce.

I don't but I'm wondering whether we should add a simple null check or do something more because... in `FormUriActivity` we have a bunch of steps to verify if a form can be loaded. If it's true that after passing all those steps you can mess up with the form and get back to the app that means we would need to handle all those cases (we already handle in `ForUriActivity`), in `FormFillingActivity` too. That doesn't make sense and we should rework it somehow.
Plus it doesn't seem to be a regression. I think the changes we have introduced just caused the crash occurring in that particular place. In older versions there would probably be a crash somewhere else?

**Comment by seadowg** [comment]
> I think the changes we have introduced just caused the crash occurring in that particular place.

That would make sense to me.

> If it's true that after passing all those steps you can mess up with the form and get back to the app that means we would need to handle all those cases (we already handle in ForUriActivity), in FormFillingActivity too. That doesn't make sense and we should rework it somehow.

That's a good point. Let's keep an eye on other similar crashes as we might just want to take our `FormUriActivity` logic and make it something we can call from `FormFillingActivity` instead. Do you think we should leave this crash unfixed for the moment given we think it should resolve itself (one the app is restarted without a back stack restore) and that we might make a bigger change to fix it in the future?

**Comment by grzesiek2010** [comment]
> Do you think we should leave this crash unfixed for the moment given we think it should resolve itself (one the app is restarted without a back stack restore) and that we might make a bigger change to fix it in the future?

I'm torn I would say ok let's have this temporary fix and think about something more soon but I'm not sure if it's enough even for now... the reports say 5 users / 540 events. Maybe the group of affected users is small but that means it happens very often for a single member of that group (~100 cases per user). This doesn't seem like a form that was deleted somehow between starting a form and returning to it. To be honest it looks like those 5 users are desperately trying to start a new form and always end up with a crash.

**Comment by grzesiek2010** [comment]
> To be honest it looks like those 5 users are desperately trying to start a new form and always end up with a crash.

The logs do not support this theory though. The session always starts with `FormFillingActivity` so either that activity is started directly (which I believed was not possible) or someone returns to the app (would anyone do that over 100 times?).

**Comment by grzesiek2010** [comment]
> so either that activity is started directly (which I believed was not possible)

Playing with the testing app: https://github.com/grzesiek2010/collectTester it looks like it is not possible indeed.

the interesting fact is that 98% of the crashes are caused by Galaxy Tab A Android 8.1 it looks like it is one user that is responsible for that 98% (over 500) of the crashes.

Now I think that we shouldn't silence these events by adding a null check. We should keep an eye on it and fix if needed... unless you want to display a personalized message for that user with a request for clarification because I believe they are doing some crazy things :smile:

**Comment by grzesiek2010** [comment]
Another interesting fact is that those crashes are not visible in the Google Play Console, only in Firebase... it crossed my mind that it's not our official release and someone is building their own app with access to our firebase project but that would be crazy.... unless it's @lognaturel playing with us :smile:

**Comment by seadowg** [comment]
> Now I think that we shouldn't silence these events by adding a null check. We should keep an eye on it and fix if needed... unless you want to display a personalized message for that user with a request for clarification because I believe they are doing some crazy things 😄

Yeah that's what I'm thinking! I've used our standard "please email support" message.

**Comment by grzesiek2010** [comment]
> Yeah that's what I'm thinking! I've used our standard "please email support" message.

I think we will never hear from that user but ok let's try.
