### ISSUE TITLE
LayoutParams.FILL_PARENT is deprecated

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#599]
Android v6.0.1 device used: OnePlus One

In the app,I have found 6 usages of LayoutParams.FILL_PARENT,which is deprecated. It should be replaced with LayoutParams.MATCH_PARENT.

I am working on this.

**Comment by anuradhagupta345** [comment]
I am on it.

**Comment by nribeka** [comment]
@anuradhagupta345 it's already labeled as in progress, so someone is already working on it. Try look for other issues that are not marked with in progress.
