### ISSUE TITLE
Offline entities

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5991]
**Release blockers (prioritised):**
- [x] #6029
- [x] #6031
- [x] #6011
- [x] #6229
- [x] #5623
- [x] #6245
- [x] #6012
- [x] https://github.com/getodk/collect/issues/6350
- [x] https://github.com/getodk/collect/issues/6304
- [x] https://github.com/getodk/collect/issues/6336
- [x] #6128
- [x] Entities created locally before there is a follow-up form should be available when it is downloaded (without submitting)
- [x] There's most likely forms that don't meet the spec that can be filled (create without label for instance) or will cause the app to crash
- [x] #6232
- [ ] Collect does not validate that entity spec features are used in appropriate version

**To improve:** 
- [x] #6231
- [ ] No log of changes to entities (should be available outside)
- [x] Datasets are downloaded and stored for every form
- [x] Online entities are not shown in browser
- [x] Form loading takes longer for entity follow up forms (because of building combined instance) than normal secondary instance forms
    - The is quite severe due to n^2 lookups required for deduplicating
- [ ] #6030
- [ ] A form with a secondary instance matching an entity list in the same project will get the entity list instead of the secondary instance
- [ ] Investigate using `row_number()` for DB queries on API 29+
- [ ] Make sure bulk finalization works for updates both locally and on the server

**Comment by lognaturel** [comment]
> Datasets are downloaded and stored for every form

Should this consideration be part of #6029? 

Currently I think the only case that a download would happen for multiple forms is if an entity list changed part way through a match exactly sync. Otherwise, there would be a server request, but the server would immediately respond with a 304 and the entity list would be returned from cache. But yes, each entity list is stored once for each form.

**Comment by seadowg** [comment]
> Should this consideration be part of https://github.com/getodk/collect/issues/6029?

I think it probably gets ticked off as part of that, but it's a different problem so I'd like to keep it called out separately.

**Comment by seadowg** [comment]
I'm closing this as it's now easier to just track entity work as a normal part of the backlog than here.

**Comment by lognaturel** [comment]
I was just about to update with some notes on release timeline and current limitations (eg no integrityUrl)! I think it would be helpful to have that info tracked alongside open issues. Maybe it’s a new meta issue?

**Comment by seadowg** [comment]
> I was just about to update with some notes on release timeline and current limitations (eg no integrityUrl)! I think it would be helpful to have that info tracked alongside open issues. Maybe it’s a new meta issue?

Maybe a doc? I do agree it would be good to have some shared thoughts on all that.
