### ISSUE TITLE
Fix `FieldListUpdateTest#listOfQuestionsShouldNotBeScrolledToTheLastEditedQuestionAfterClickingOnAQuestion`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5996]
~~Blocked by #6059~~

This test fails on Test Lab, but not locally ([example](https://console.firebase.google.com/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/6782266433663054701)).

**Comment by grzesiek2010** [comment]
I've tried to solve this issue but I haven't been able. Playing with some delays like 0.5s or 1s reduced the number of failures from 8 for 50 attempts to 1 for 50 attempts but it's not a solution. @seadowg maybe you will be able to figure it out.

**Comment by seadowg** [comment]
It seems like this fails locally on API 34 devices which is helpful. One thing to avoid here is fixing the test by cheating like I did in https://github.com/getodk/collect/pull/6077.
