### ISSUE TITLE
Implement savepoints migration

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5997]
#### Problem description
In https://github.com/getodk/collect/pull/5951 we have reworked the way we deal with savepoints. The new approach is based on a database and requires some kind of data migration to provide backward compatibility.

**Comment by seadowg** [comment]
My take is that we can't release without being able to migrate existing save points or else we risk losing people's data.

@grzesiek2010 is there anything we need to capture here other than the fact that a save point created before upgrading is still available after upgrading?
