### ISSUE TITLE
Unused Methods and Variables

### ISSUE THREAD

**Issue by nsai500** [getodk/collect#600]
There are some unused methods and variables.Some of them are assigned but were never used and can be removed safely. Below is a list of the class name with respective methods and variables

1) AppListActivity--getCheckedIdObjects method is never used

2) BearingActivity--mBearing variable is never used(assigned value mBearing = String.format("%.3f", degrees)

3) FormEntryActivity--saveAnswer method is never used

4) GeoPointMapActivity--mRefreshLocation never used
                                         mZoomed(assigned some values but never used)
                                         mLocationAccuracy (assigned some values but never used)

5) GeoPointOsmMapActivity-- mHandler , sharedPreferences , basemap  never used
                                                mZoomed (assigned some values but never used) 
                                                mLocationAccuracy (assigned some values but never used)

6) GeoShapeGoogleMapActivity-- sharedPreferences ,basemap,gmapSettings ,polygon_button never used
                                                   initZoom(assigned some values but never used) 
                                                   latLngsArray (assigned some values but never used)
                                                   data_loaded (assigned some values but never used)
                                                   clear_button_test (assigned some values but never used)

7) GeoShapeOsmMapActivity--polygon_connection(assigned some values but never used)
                                                 sharedPreferences , layerStatus , selected_layer  never used

8) GeoTraceGoogleMapActivity-- polygon_button , progress , sharedPreferences ,  gmapSettings 
                                                     basemap , latLngsArray  never used
                                                     inital_location_found (assigned some values but never used) 
                                                     clear_button_test (assigned some values but never used)
                                                     initZoom(assigned some values but never used)

9) GeoTraceOsmMapActivity-- sharedPreferences(assigned some values but never used)
                                                 inital_location_found(assigned some values but never used)

**Comment by anuradhagupta345** [comment]
Shall I work on this?

**Comment by supreme96** [comment]
@anuradhagupta345 Have you made any progress on this?

**Comment by lognaturel** [comment]
@nsai500 If you would like to address this, please go ahead. Please add a different commit for each file.

**Comment by nsai500** [comment]
@lognaturel I won't be available for a couple of days. Anyone else who wants to work on this can go ahead.

**Comment by supreme96** [comment]
@lognaturel  I'll take this one!

**Comment by royrivnam** [comment]
@supreme96 Have you made any progress on this??if not then i will go for it

**Comment by supreme96** [comment]
@royrivnam Yeah. I am working on this one.

**Comment by royrivnam** [comment]
@supreme96 can i also give this a try if you don't mind.. or just leave a comment if you by any chance get busy with something else before completing this issue..then i shall try

**Comment by supreme96** [comment]
I don't think that would work very well. Can you please pick another issue?

**Comment by royrivnam** [comment]
its okay... its all yours....

**Comment by shobhitagarwal1612** [comment]
Fixed in #661

**Comment by lognaturel** [comment]
Thanks @shobhitagarwal1612!
