### ISSUE TITLE
Multiclick on offline layer button in form map

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6013]
#### ODK Collect version
2023.3.1, the store version 2024.1.2, the master version 6c6c19d8f1e9b4b89f1d10a31fe698e67e864dd7

#### Android version
10, 11, 14 

#### Device used
Samsung Galaxy M12, Redmi 9T, Pixel 7A

#### Problem description
Pressing offline layer button causes offline layer dialog to open multiple times.
Issue occurs in form map and select one from map form.

#### Steps to reproduce the problem
1. Go to demo project
2. Open form map
3. Press offline layer button multiple times

#### Expected behavior
Offline layer dialog should open only once

#### Other information 

https://github.com/getodk/collect/assets/162433284/d9b53fab-fe5c-4c57-87f7-f3f4a214a9cb

**Comment by seadowg** [comment]
This will most likely get fixed as part of #5845.
