### ISSUE TITLE
Crash in the Nested repeats for audit form while removing an empty inner repeat

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6015]
#### ODK Collect version
2023.3.1. the store version 2024.1.2, the master version 6c6c19d8f1e9b4b89f1d10a31fe698e67e864dd7
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There is a crash in the 3231 Nested repeats for audit form while removing an empty inner repeat.
 [https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/a[…]ey=65DB5F0903B2000171A29DE4E04C99F0_1918010274617643865](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/ea07d0f482dae5c1119a950eb82e2b0d?time=last-seven-days&types=crash&versions=2024.1.1%20(4793)&sessionEventKey=65DB5F0903B2000171A29DE4E04C99F0_1918010274617643865)
#### Steps to reproduce the problem
1. Open to 3231 Nested repeats for audit form.
[3231nested-repeats-for-audit.xml.txt](https://github.com/getodk/collect/files/14602643/3231nested-repeats-for-audit.xml.txt)

2. Go to the hierarchy view.
3. Tap the arrow 4 times so that you can see outer repeat1, outer group 1, outer repeat 2.
4. Tap Outer group 1.
5. Tap the bin to remove the group (inner repeat 2).
6. In the dialog (Remove group "null” and all of its sub-groups?) tap "Remove group”.
#### Expected behavior
The app shouldn’t crash

**Comment by grzesiek2010** [comment]
The described section contains a repeatable (inner group) group that is wrapped into a regular group (outer group) so there are no nested repeats there.
The outer group is not repeatable so it shouldn't be even possible to try to remove it. It looks like we mistakenly treat that group as a repeatable one. Here is a much simpler form that reproduces the issue as well:
[groups_crash.xlsx](https://github.com/getodk/collect/files/15060639/groups_crash.xlsx)
