### ISSUE TITLE
Add icons to buttons

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6016]
**Context**
As part of our work improving the [Geo buttons](https://github.com/orgs/getodk/projects/9/views/8?pane=issue&itemId=50778689), we want to add icons to other buttons to make them more intuitive. 

We will not be changing the language as part of this story.

**Icons**
Please see [Google sheet](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0)

**Comment by grzesiek2010** [comment]
@alyblenkin there is one extra place where we display a button (like in normal questions). It's for populating multiple fields from an external app: https://docs.getodk.org/collect-external-apps/#external-apps-to-populate-multiple-fields
This button looks like this (after my tweaks from https://github.com/getodk/collect/pull/6018): 
![Screenshot_1710615457](https://github.com/getodk/collect/assets/3276264/db832ab3-c1f9-41db-9f10-d57cd3afb123)

Just wanted to let you know. I think you will agree that we should use there the same icon we use for starting external apps in single external questions.

**Comment by alyblenkin** [comment]
@grzesiek2010 I agree that makes sense!
