### ISSUE TITLE
Fix style throughout the codebase and check style as part of the build process

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#602]
The code base is currently not very consistent when it comes to code style. We should agree on a style guide to follow, fix style across the codebase and enable style checks as part of the build process.

We already have a good [checkstyle file](https://github.com/opendatakit/collect/blob/master/config/checkstyle/checkstyle.xml). It can be run with `gradle checkstyle` and eventually added to continuous integration. I also like to use the [checkstyle IDEA plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) in Android Studio.

I would like to propose the following changes to the existing checkstyle file:
- Enforce standard [`MethodName`](http://checkstyle.sourceforge.net/config_naming.html#MethodName)
- Enforce standard [`ParameterName`](http://checkstyle.sourceforge.net/config_naming.html#ParameterName)
- Enforce standard [`StaticVariableName`](http://checkstyle.sourceforge.net/config_naming.html#StaticVariableName)
- Require curly braces as in [Android contributor guide](https://source.android.com/source/code-style.html). I'd like to go further than them and require them even for one-line `if`s but I don't feel strongly about it. [`NeedBraces`](http://checkstyle.sourceforge.net/config_blocks.html#NeedBraces)
- Require the opening curly brace to be on the end of the line of the test as in [Android contributor guide](https://source.android.com/source/code-style.html). [`LeftCurly`](http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly)
- Require the closing curly brace to be on the same line as the next part of a multi-block statement as in [Android contributor guide](https://source.android.com/source/code-style.html). [`RightCurly`](http://checkstyle.sourceforge.net/config_blocks.html#RightCurly)

We should also decide whether or not to enforce the common Android convention to use an `m` prefix for non-public, non-static fields and an `s` for non-public, static fields. I know @nribeka and @dcbriccetti have strong feelings about this.

And finally, we need to agree on a strategy for bringing the codebase in line with the configuration file in a way that is incremental and verifiable. Here are some options:
- a single pull request with a different commit for each problem fixed.
- one pull request per file. 
- one pull request per category of issue.
- ???

**Comment by pratikmjoshi** [comment]
@lognaturel I think one pull request per category of issue with a different commit for each file in which the issue is solved can be another option.

**Comment by grzesiek2010** [comment]
I'm in favour of one pull request per category of issue. Can't wait for results :)

**Comment by nribeka** [comment]
I have a strong feeling of not using the [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) moving forward. You guys can read the pros and cons in wikipedia.

I think we're still mising some stuff like from checkstyle config:
- [OneTopLevelClass](http://checkstyle.sourceforge.net/config_design.html#OneTopLevelClass)
- [EqualsAvoidNull](http://checkstyle.sourceforge.net/config_coding.html#EqualsAvoidNull)

We can use the [Google's](http://checkstyle.sourceforge.net/google_style.html) one as some guideline I think.

**Comment by lognaturel** [comment]
How about we start with a blank checkstyle file and incrementally add checks that we fix across the code base. I have submitted an example at #832. I'd be fine with either moving towards [Google's checkstyle file](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) or [android-check's easy file](https://github.com/noveogroup/android-check/blob/master/android-check-plugin/src/main/resources/checkstyle/checkstyle-easy.xml).

**Comment by lognaturel** [comment]
I had a bit more time to think about this and had a change in heart. @nribeka is right, let's use the Google checkstyle file since their style guide is what we're currently pointing people to. I now propose we start out with the whole thing in there but with checks commented out. Contributors can pick ONE check to uncomment, review the errors, fix them committing changes for each file and then issue a pull request. In some cases, we may want to include ODK-specific checks and those can be grouped at the top. For example, I added some import checks.

#832 has been updated accordingly. How does that sound? @grzesiek2010 @pratikmjoshi @yanokwa @shobhitagarwal1612 @nribeka

**Comment by yanokwa** [comment]
I had the same idea so I agree!

**Comment by shobhitagarwal1612** [comment]
Sounds great

**Comment by grzesiek2010** [comment]
Sounds good to me as well.

**Comment by shobhitagarwal1612** [comment]
Can we close this now?

**Comment by lognaturel** [comment]
Sounds good to me.
