### ISSUE TITLE
Date Picker in forms is not placed well

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#604]
Android v6.0.1, device used: OnePlus One

The date picker in the forms does not fit the phone screen and has a horizontal scroll to accommodate. I feel this is awkward for the user and does not look nice. Also, if you scroll right, you sometimes swipe to the next question as well. I have shown it in the screenshots below:

Steps to reproduce the problem
1.Go to a form with a date entry required.(e.g. Hypertension Screening)
2.Go to a date picker question(such as 3rd one in Hypertension Screening).

![screenshot_20170315-052237](https://cloud.githubusercontent.com/assets/19923446/23927545/6ac33a56-0940-11e7-9c05-89ff02f5a0c0.png)

When scrolling right sometimes, it goes to the next question(or is stopped by check condition):

![screenshot_20170315-052243](https://cloud.githubusercontent.com/assets/19923446/23927552/7102bf0e-0940-11e7-8879-341968effeeb.png)

I think the two pickers should be centred vertically, with the month and year picker above the day picker. That way, the above problem of accidentally swiping to next question is eliminated. Otherwise, it would also be nice if we could use a custom datepicker from online.
I would like to work on this if possible.

**Comment by anuradhagupta345** [comment]
@lognaturel I find this issue interesting to be work on. Shall I work on this?

**Comment by parthuest** [comment]
@anuradhagupta345 can you please choose one of the issues #600 and #604. I want to work one of these too. Thank you.

**Comment by lognaturel** [comment]
@anuradhagupta345 @parthuest Please hold off on these date and calendar related issues until we have time to discuss.

**Comment by parthuest** [comment]
Okay.

**Comment by lognaturel** [comment]
Updated to use the material design calendar a few versions ago.
