### ISSUE TITLE
"No error" pill is gray

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6046]
#### ODK Collect version
the master version 38a4b0ec4eea71fda685493b3931137b11ec5621
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The "No error” pill in Drafts changed color to gray (used to be blue).
The issue doesn’t occur in the store version 2024.1.3
![gray](https://github.com/getodk/collect/assets/56479916/97b17863-7356-4bfa-99a3-6b40b3cdc880)

#### Steps to reproduce the problem
1. Set light mode in Collect.
2. Save a draft without errors.
3. Go to Drafts
#### Expected behavior
The "No error” pill should be blue.

**Comment by grzesiek2010** [comment]
@alyblenkin  what do you think? Is gray ok or we should use blue?

**Comment by alyblenkin** [comment]
It would be great if we could use blue and red here to emphasize the states. @seadowg, is it still possible to use blue with the new tonal surface changes? I think it's okay to use gray for the end screen and messages, but here, it's important for it to be highlighted.

**Comment by seadowg** [comment]
>  @seadowg, is it still possible to use blue with the new tonal surface changes? I think it's okay to use gray for the end screen and messages, but here, it's important for it to be highlighted.

We could just use our primary color?

**Comment by dbemke** [comment]
After merging #6000 the gray "no errors" pill occurs also in the form map.

**Comment by grzesiek2010** [comment]
> We could just use our primary color?

I'm not sure... @alyblenkin?
![Screenshot_1711737419](https://github.com/getodk/collect/assets/3276264/4454cef4-de3c-40e8-a735-ec1a57c85bb1)

**Comment by alyblenkin** [comment]
> We could just use our primary color?

Ideally, I would use a lighter colour because we reserve the primary colour for our buttons. 

Another thought I just had was to make the pill outlines blue, which surprisingly works pretty well. 
The mockups below don't have the form icon, so they will look different. The pills are also fully rounded (something I want to get to eventually!).

<img width="940" alt="Screenshot 2024-04-02 at 9 16 18 AM" src="https://github.com/getodk/collect/assets/7871340/99e8fb7f-7bd8-49c6-af66-e3a9e4cbf93f">

**Comment by seadowg** [comment]
@alyblenkin I just remembered that there isn't a spec for Pill, so we can do whatever we want here really (as long as we feel it's probably what "Google would want"). Let's schedule a pairing session to improve this.
