### ISSUE TITLE
Add Test for Layout and Options Menu in MainActivityTest

### ISSUE THREAD

**Issue by lokeshkvn** [getodk/collect#605]
*MainActivityTest* implemented by @yadav-rahul doesn't have test for checking layout and options menu.
As Options Menu are important component in ODK-collect , there must be a local unit test to check whether intents from options menu are working properly or not.

- [ ] Add test for main activity layout.
- [ ] Add test for each options menu.

**Comment by lokeshkvn** [comment]
@In @yanokwa @yadav-rahul  I am working on this issue.

**Comment by yadav-rahul** [comment]
@lokeshkvn Please go ahead.
