### ISSUE TITLE
A form with saveIncomplete creates both a savepoint in a new form and a draft.

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6051]
#### ODK Collect version
the master version 38a4b0ec4eea71fda685493b3931137b11ec5621
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
A form with saveIncomplete creates both a savepoint (in a form in "Start new form”) and a draft.
The issue doesn’t occur in the store version 2024.1.3 (after creating a savepoint in Start new form the form doesn’t open in the hierarchy view with saved answers).
#### Steps to reproduce the problem
1. Open the form and fill 2 questions.
[saveIncomplete(2).xlsx.txt](https://github.com/getodk/collect/files/14785737/saveIncomplete.2.xlsx.txt)
2. Go to the end page.
3. While at the end page go to settings and change the theme of the app so that a savepoint is created.
4. Check if a draft was created (don’t open it).
5. Go to "Start new form” and open the form.
6. In the recovery dialog choose "Recover”.
7. Save the form as draft.
#### Expected behavior
I’m not sure what should be the expected behavior in this case. In the store version the form was saved as a draft.

**Comment by grzesiek2010** [comment]
Nice find but you can reproduce the same bug without that `saveIncomplete` option. What `saveIncomplete` does is save a form for us when a question with that option is created. You can reproduce the same issue by doing:
1. Open any blank form.
2. Click the save button.
3. Create a savepoint by killing the app for example.
4. Reopen the app

There should be a save savepoint but for a saved (not blank) form, as after saving a form manually (or using `saveIncomplete`) what I did in the second step, the form is no longer a blank form but a saved one.
