### ISSUE TITLE
Possible to tap project icon and a button from the main menu at the same time

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6053]
#### ODK Collect version
the store version 2024.1.3, the master version 38a4b0ec4eea71fda685493b3931137b11ec5621
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After tapping simultaneously the project icon and a button from main menu, both the chosen part from the main menu and project settings dialog open.
#### Steps to reproduce the problem
1. Open the demo project in Collect.
2. Tap simultaneously on the project icon and "Start new form"/"Drafts" or other main menu button.
3. When "Start new Form" opens tap the device back button.

#### Expected behavior
The user shouldn’t be able to multi click buttons.
#### Other information
Probably the same as #5307

**Comment by seadowg** [comment]
I'm considering closing this as a "won't fix". @dbemke is there anything risky or problematic about this or is it just a little strange? As far as I can the user can't get themselves in any danger (like having multiple forms open for example) from this multi click.

**Comment by dbemke** [comment]
> is there anything risky or problematic about this or is it just a little strange?

I don't think so. It also existed in the past and there weren't any crashes. The list of new forms is opened first and then after going back there is the projects dialog so doesn't seem risky.
