### ISSUE TITLE
Change the launch icons for external questions, so they are consistent.

### ISSUE THREAD

**Issue by srujner** [getodk/collect#6055]
**ODK Collect version**
the master version 0f4b444210e2a1f8af4db4c14df2bfad3ae91be2

**Android version**
12,13

**Device used**
Google Pixel 3a,6a

**Problem description**
Icon for external question buttons is inconsistent.
The biggest problem I have is with the external audio question and the microphone icon. 
It may suggest to the user that a recording will be used which may not always be true.

**Steps to reproduce the problem**

1. Open the demo project in Collect.
2. Navigate to the one of the external question

**Expected behavior**
Icons has been changed

**Other information**
![Screenshot_20240326-105059](https://github.com/getodk/collect/assets/85225519/cc96e915-22d3-4d77-bc90-627ef0cd3b8c)

**Comment by seadowg** [comment]
![Image](https://github.com/getodk/collect/assets/556280/1c403ddb-155e-4f19-bce7-4d28c4080166)

@srujner are you thinking they should all look like this? I do think your point that something like the microphone might suggest the wrong thing to the user makes sense. Good to hear your take here @alyblenkin.

**Comment by srujner** [comment]
@seadowg Yes and also we discussed this with @alyblenkin that this icon for all External Questions should fit well
