### ISSUE TITLE
Instance folder remains after discarding savepoint from Audit Forms

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6057]
#### ODK Collect version
the master version 38a4b0ec4eea71fda685493b3931137b11ec5621

#### Android version
10, 11

#### Device used
Samsung Galaxy M12, Redmi 9T

#### Problem description
Instance folder remains after discarding savepoint from Audit Forms

#### Steps to reproduce the problem
1. Open AuditTest form
[AuditTest.xml.txt](https://github.com/getodk/collect/files/14790275/AuditTest.xml.txt)
2. Fill some question in form
3. Kill app to create savepoint
4. Open app again
5. Open AuditTest form again
6. In recovery dialog press Discard
7. Press device back button and discard form
8. Go to instances folder in file manager

#### Expected behavior
Instance folder should be deleted after discarding savepoint

**Comment by seadowg** [comment]
@WKobus how does this compare to the behaviour in previous versions of Collect?

**Comment by WKobus** [comment]
@seadowg On store version when user reopen form with previously created savepoint and then discards this form, instance folder is deleted.
