### ISSUE TITLE
✨ Google Summer of Code 2017 - Important dates and Q&A ✨

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#606]
Welcome to all students considering submitting a proposal for [Google Summer of Code 2017](https://summerofcode.withgoogle.com/organizations/4911125733834752/)! We are very excited to have you here and thank you so much for all the wonderful contributions you have already made. 🎉

Project proposal time is coming up! You will have between **March 20th and April 3rd** to submit your proposal document. We encourage you to submit a draft as soon as possible to solicit feedback.

If you have any questions about the proposal process, please ask in the comments for this issue or [on Slack](http://slack.opendatakit.org) in the #gsoc channel. Although we don't have a formal template that you must follow, we will use this issue to give you a sense of the things we are looking for. Please also review [the GSoC manual page on proposals](http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/).

**Include your GitHub and Slack handles**
That's how we've come to know you!

**Explain why your project and approach benefit the ODK community**
What do you think the major impact of your project will be? Why is your approach the best one out of all the other possible approaches?

**Have a clear plan**
Your proposal is an opportunity to show us that you will be able to complete a successful project during the 12 weeks of GSoC. We will expect your writeup to include a rough timeline with major tasks described over time. How will you break the project into pieces that can be reviewed and added incrementally? How will you solicit feedback from the community and incorporate it into your design and code? What are some aspects you could cut if you run out of time or extra features you could add if you have extra time? How will you verify that your code is correct?

**Explain why you're a great fit for your project**
What prior experience can you draw from? Show us specific projects or even link to particular code samples! How have your recent contributions to ODK and conversations in the Slack prepared you to be a great community member?

**Communicate clearly and precisely**
We highly encourage diagrams and sketches when they help describe your ideas more clearly.

Again, don't hesitate to ask any questions you may have on this issue. We can't wait to read your proposals!

**Comment by ghost** [comment]
**Pro tip:** There's no rule that says your proposal must be the first time that potential ODK project mentors hear about your idea! 😄 You can communicate with & work with potential mentors _now_, ahead of time, to better clarify both your ideas as well as your understanding of ODK software. Remember that everyone here's a volunteer, so they may not respond immediately, but everyone's also very friendly and are often eager to help you think about your ideas.

Also, don't worry about getting the timeline exactly perfect: Just do your best to make it realistic. Selected students will work with their mentors before the program starts to confirm & add details to the project plan, and to make sure it works for everyone.

Most of all, have fun getting to know people & their work! Friendly people that the mentors remember almost always stand out in a crowd of project proposals. 👍
