### ISSUE TITLE
Buttons are blocked a bit too long after e.g. going to the end page

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6061]
#### ODK Collect version
the master version 031183e90dc4fa51ec389aa4987eeb048a6b470f
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Buttons are blocked a bit too long after e.g. going to the end page in a form and tapping a button quickly. If a user taps the button at the end page quickly (after coming to the end page), it's necessary to tap the button twice.
The issue doesn't occur in the store version.

https://github.com/getodk/collect/assets/56479916/abc06599-f7f0-4ed0-bea4-46309a36398a

#### Steps to reproduce the problem
1. Open a form.
2. Go to the hierarchy view.
3. Tap "Go to end”.
4.  Tap "save as draft”/ "send” button quickly.
#### Expected behavior
The user shouldn't notice the time when the buttons are blocked.

**Comment by dbemke** [comment]
Another way to reproduce it:
1. Save some drafts or send forms.
2. Go to "Delete form - Saved Forms".
3. Tap "Select all" and quickly after that "Delete Selected".

**Comment by srujner** [comment]
I also found some other way to reproduce it in a different way:

1. Have at least one form in Ready to Send tab;
2. Quickly click on the Select All button and then Send Selected button;

The Send Selected buttons needs 2-3 taps to become active and send selected forms

**Comment by seadowg** [comment]
@grzesiek2010 I'm thinking that a solve for this is to just ditch the `javaClass.name` default for the `screenName` param (for `MultiClickGuard#allowClick`) and just pass in a screen name constant (but make `screenName` optional). This would let us target the cases the places where users are more likely to quick through quickly (I ran into the form end screen one a couple of times today for example).

**Comment by seadowg** [comment]
We chatted about this in a meeting and it sounds like we're in agreement to fix the cases mentioned in the issue as well as allowing faster clicks for the "next" and "back" button in form entry. For some of these, the `screenName` approached above will be the most appropriate, but for others it might just make sense to opt out of the `MultiClickButton` approach.
