### ISSUE TITLE
Minimizing marker on map is delayed

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6065]
#### ODK Collect version
the master version b672483b28483f2cee9129f410344ee4ab82b851

#### Android version
10, 11, 13, 14 

#### Device used
Redmi 9T, Samsung Galaxy M12, Pixel 6a, Pixel 7a

#### Problem description
Minimizing marker on map is delayed.
Issue occurs on select one from map and form map.

#### Steps to reproduce the problem
1. Open All Widgets form
2. Go to Select one from map question
3. Press select place button
4. Tap on any marker on map
5. Press device back button

#### Expected behavior
Marker should be minimized immediately after pressing device back button.

#### Other information 

https://github.com/getodk/collect/assets/162433284/781ecc10-2635-415f-8895-76b0bc9fbda7

**Comment by seadowg** [comment]
@WKobus is this happening in Mapbox/Google Maps as well as OSM?

**Comment by WKobus** [comment]
@seadowg It occurs only on OSM.

**Comment by seadowg** [comment]
It looks to me like OSM sometimes waits to redraw the map for some time. @grzesiek2010 I'm going to include this in the current milestone as I know you're going to be looking at code in that area anyway, but I don't think this is high priority.
