### ISSUE TITLE
Cursor moved to the left in number questions with masked appearance after swiping

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6072]
#### ODK Collect version
the master version e1fa49fdee8987ae9744f8fa4270fd931e31f7df
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In number questions with masked appearance after entering some numbers and swiping forward and backwards the cursor moves to the left side (beginning of the entered number). 
The issue doesn’t occur in integer with thousands-separators questions.
#### Steps to reproduce the problem
1. Go to the form.
[masked_text.xlsx.txt](https://github.com/getodk/collect/files/14932743/masked_text.xlsx.txt)
2. Go to a masked integer/decimal/text number question and enter some numbers.
3. Swipe forward and backwards.
4. Check the position of the cursor.

#### Expected behavior
After going back to a question the cursor should be at the end.

**Comment by seadowg** [comment]
@dbemke what do you mean by "placeholder" here? Maybe a video would help?

**Comment by dbemke** [comment]
https://github.com/getodk/collect/assets/56479916/a6d55a71-a35a-4908-b001-de72a2cc0d74

**Comment by grzesiek2010** [comment]
Thanks for the video. This is called the cursor. I've updated the issue.
