### ISSUE TITLE
Last written character is not shown in masked integer with thousand-sep appearance

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6073]
#### ODK Collect version
the master version e1fa49fdee8987ae9744f8fa4270fd931e31f7df

#### Android version
10, 11

#### Device used
Redmi 9T, Samsung M12

#### Problem description
Last written character is not shown in masked integer with thousand-sep appearance

#### Steps to reproduce the problem
1. Open masked_text form
[masked_text.xlsx.txt](https://github.com/getodk/collect/files/14933298/masked_text.xlsx.txt)
3. Go to Masked integer thousands-sep question
4. Input any characters

#### Expected behavior
Last written character in masked integer with thousand-sep appearance should be shown for a brief moment.

#### Other information 

https://github.com/getodk/collect/assets/162433284/24d58c5c-931b-4794-b8b4-7067e1221d90

**Comment by seadowg** [comment]
@WKobus I can't see what's wrong from the vide? Perhaps it's really fast and I'm missing something.

**Comment by WKobus** [comment]
@seadowg I was talking with Grzegorz and he said that last entered character should be shown for 2 seconds, as it is in masked Integer question without thousands sep, in Integer with thousands sep every character is immediately masked.

**Comment by seadowg** [comment]
Ah I misread!

**Comment by grzesiek2010** [comment]
It doesn't make sense to allow combining those two appearances as `thousand-sep` only formats numbers displayed in an `Edittext` and does not affect the saved values (to the XML file). That means formatting numbers that are hidden either way is useless. Whatever is easier to implement but probably the `masked` appearance should win here and the `thousand-sep` should be ignored.

**Comment by seadowg** [comment]
> Whatever is easier to implement but probably the masked appearance should win here and the thousand-sep should be ignored.

Yup we want `masked` to win (https://github.com/getodk/collect/issues/5937).

I don't think I actually do understand what the problem is here and how it relates to `thousand-sep`. 

@WKobus are you able to elaborate on "Last written character in masked integer with thousand-sep appearance should be shown for a brief moment.". What exactly is it you expect to see here? As far as I can tell from the video, the numbers are being masked as you type them which I would expect.

**Comment by WKobus** [comment]
As i said in previous comment, while I was talking to Grzegorz he said that last character entered should be shown for about 2 seconds, as it is in Integer question without thousands sep appearance, so I would expect it to work same way with thousands sep appearance.
Here is comparsion between Integer with thousands sep and without thousands sep

**Masked Integer without thousands sep**

https://github.com/getodk/collect/assets/162433284/781c36da-0d9e-4af9-a483-686d418c10f9

**Masked Integer with thousands sep**

https://github.com/getodk/collect/assets/162433284/b7ed173a-61cc-4b0d-87e2-3ccabc990d21

**Comment by seadowg** [comment]
Got it thanks!
