### ISSUE TITLE
Answer entered in masked text field can be seen in android keyboard

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6080]
#### ODK Collect version
the master version e1fa49fdee8987ae9744f8fa4270fd931e31f7df

#### Android version
10, 11, 14

#### Device used
Redmi 9T, Samsung M12, Pixel 7a

#### Problem description
Answer entered in masked text field can be seen in android keyboard suggestions and in android keyboard on landscape view

#### Steps to reproduce the problem
1. Open masked_text form
2. Go to Masked text question
3. Type anything
4. Rotate device to landscape view

#### Expected behavior
Answer entered in masked text field should be hidden from android keyboard suggestions and android keyboard on landscape view

#### Other information 

https://github.com/getodk/collect/assets/162433284/76fc2a78-0333-4987-aa5e-891eebbe8e2f

**Comment by tobiasmcnulty** [comment]
Thanks for finding and reporting this! This is a concern for our team as well.

**Comment by grzesiek2010** [comment]
This seems to be fixed by https://github.com/getodk/collect/pull/6088 so I'm closing. @WKobus @dbemke please remember about this issue while testing https://github.com/getodk/collect/pull/6088.
