### ISSUE TITLE
If a user discards changes made in a saved draft, discarded events are shown in audit logs

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6081]
#### ODK Collect version
the store version 2024.1.3, the master version e1fa49fdee8987ae9744f8fa4270fd931e31f7df
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
If a user discards changes made in a saved draft, discarded actions/events are present in audit logs.
#### Steps to reproduce the problem
1. Fill an audit form and save it as draft.
[track-changes-reason-on-edit-2q.xml.txt](https://github.com/getodk/collect/files/14945891/track-changes-reason-on-edit-2q.xml.txt)
2. Open the draft and edit some answers.
3. Tap the device back button and discard changes.
4. Open the CSV file with audit logs (check if there is "form resume" event and question events).
#### Expected behavior
Discarded actions and changes in answers shouldn’t be visible in audit logs.

**Comment by grzesiek2010** [comment]
Are we certain that we want to ignore such events, or should we continue logging them as we do now to provide users with some insight into what happened while filling out the form, and add a new log indicating that the changes have been discarded? I kind of think that those events might be useful. @lognaturel @seadowg any thoughts?

**Comment by seadowg** [comment]
> I kind of think that those events might be useful. @lognaturel @seadowg any thoughts?

Yeah I actually agree coming back to this! Do we end up with a form exit event as well so it's clear what happened?

**Comment by grzesiek2010** [comment]
> Do we end up with a form exit event as well so it's clear what happened?

There is a `form exit` event, but it is not clear that changes have been discarded. The only difference is the absence of a preceding `form save` event. I believe that if, in the scenario where we save a form, the order of events is:
`form save`
`form exit`
then, in this scenario, it should be:
`ignore changes`
`form exit`

That would mean adding a new `ignore changes` event.

**Comment by seadowg** [comment]
> That would mean adding a new ignore changes event.

It feels ok to me that we just get a `form exit` (without a `form save`). I'd be ok with closing this, but it'd be good to get input from @lognaturel.

**Comment by lognaturel** [comment]
I agree that the way things are is ok.
