### ISSUE TITLE
Reducing the top margin in the map bottom sheet

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6082]
#### ODK Collect version
the master version e1fa49fdee8987ae9744f8fa4270fd931e31f7df
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In the horizontal view when there are properties added to a point, the bottom sheet covers a half of the screen which makes looking at/using the map quite difficult. Even if there is the "errors/no errors" pill there is a bit of empty space at the top of the bottom sheet (covering the map).
![verticalBottom](https://github.com/getodk/collect/assets/56479916/09e54286-c61a-4b04-b085-a2fa261b94fc)

#### Steps to reproduce the problem
1. Open a form map or select one from map form.
2. Rotate the device so that it is in the horizontal view.
3. Select a point.

#### Expected behavior
Reducing the top margin might make using the map and the bottom sheet in the horizontal view more user-friendly.

**Comment by seadowg** [comment]
This will be part of #6099.
