### ISSUE TITLE
Geopoint with no appearance button with an added answer with a wrong text

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6094]
#### ODK Collect version
the master version 4f54bcce2d548e9869b2ec6fbf9e674d37e77fa1
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
According to changes introduced in #6014 in Geopoint widget with no appearance after saving a point the button should change to "View or change point” but it’s "Change point”
#### Steps to reproduce the problem
1. Open All question types form and go to Location with user confirmation question.
2.  Click "Get point” and save a point.
3. Check the text in the button.

**Comment by dbemke** [comment]
I've just read comments in the PR again.. and I'm not sure what is the expected. If there isn't a map appearance the text should be different?

**Comment by grzesiek2010** [comment]
The table in the pr is not correct please take a look at the one from the issue: https://github.com/getodk/collect/issues/5930#issue-2094479298
if a geo question does not use a map there is no way to view its answer after clicking on the button so the text should be just `Change point`.
