### ISSUE TITLE
Save button is active in Geo widgets with readonly option

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6096]
#### ODK Collect version
the master version 4f54bcce2d548e9869b2ec6fbf9e674d37e77fa1, the store version 2024.1.3

#### Android version 
10, 11, 14

#### Device used
Redmi 9T, Samsung M12, Pixel 7a

#### Problem description
Save button is active in Geo widgets with readonly option, due to this it is possible to change answers in GeoTrace and GeoShape questions by moving points on map and then pressing save button. Additionally pressing save button in Geo questions with readonly option, results in changing button from "View ...." to "View or change ...."

#### Steps to reproduce the problem
1. Open Geo read-only form
2. Go to GeoTrace question
3. Press "View line" button
4. Move points
5. Press save button
#### Expected behavior
Save button should be inactive in Geo widgets with readonly option

#### Other information 

https://github.com/getodk/collect/assets/162433284/d5764878-8a22-4676-b0a4-8d3bb17a2599

**Comment by dbemke** [comment]
The form to reproduce the issue 
[Geo Read-only.xlsx.txt](https://github.com/getodk/collect/files/14979662/Geo.Read-only.xlsx.txt)
