### ISSUE TITLE
Deprecated method call for dismissing progress dialog

### ISSUE THREAD

**Issue by nikhilbalyan** [getodk/collect#610]
#### Software and hardware versions 
Collect v1.4.1686-g93455d3-dirty, Android v5.1, Motorola MOTO E

#### Problem description
We are using the deprecated way of dismissing the dialog dismissDialog(PROGRESS_DIALOG).

#### Steps to reproduce the problem
Line 200 and line 210 in FormDownloadList are using the deprecated way of dismissing the dialog

#### Other information 
we should use mProgressDialog.dismiss()

**Comment by getsanjeev** [comment]
I would like to fix it, once reviewed.

**Comment by lognaturel** [comment]
This seems like a subset of #541, @nikhilbalyan. I think we should first agree on an approach for cleaning up dialogs across the code base and then we can make sure that deprecated calls are removed as part of that broader refactor.

**Comment by nikhilbalyan** [comment]
Sure @lognaturel

**Comment by lognaturel** [comment]
@nikhilbalyan I should add -- I encourage you to add your thoughts to #541!
