### ISSUE TITLE
Broken geojson in one project prevents downloading forms using correct geojson with same name from other projects 

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6100]
#### ODK Collect version
the master version 213624d9733b436ecf5cbe168296bc4eb25c1b85, the store version v2024.1.3
#### Android version
10, 11, 14

#### Device used
Redmi 9T, Samsung M12, Pixel 7a

#### Problem description
Broken geojson in one project prevents downloading forms using same geojson name from other projects 

#### Steps to reproduce the problem
1. In central upload in first project s1FromMap form and upload correct geojson
[s1FromMap.xlsx](https://github.com/getodk/collect/files/15042543/s1FromMap.xlsx)
[items.geojson.txt](https://github.com/getodk/collect/files/15042540/items.geojson.txt)
2. In second project upload s1FromMap form and upload broken geojson
[items.geojson.txt](https://github.com/getodk/collect/files/15042569/items.geojson.txt)
3. In collect open second project with broken geojson
4. Open s1FromMap form
5. Go to first project with correct geojson
6. Try to download s1FromMap from first project

#### Expected behavior
User should be able to download form with correct geojson from first project

**Comment by seadowg** [comment]
@WKobus @dbemke is this a duplicate of #6097?

**Comment by WKobus** [comment]
@seadowg Difference between #6097 and this issue is that in this issue not only one project with broken geojson is affected, but all other projects using geojson with same name, however cause might be the same, so if that is the case it can be closed as duplicate.

**Comment by seadowg** [comment]
@WKobus sounds right! Could you just add the info here to that issue? I think because the setup (adding broken geojson to a project) is the same it'll be easier to look at as one issue.
