### ISSUE TITLE
Filter soft-deleted submissions out of delete form list

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6110]
#### ODK Collect version
https://github.com/getodk/collect/commit/d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5

#### Android version
13

#### Device used
Samsung Galaxy A13

#### Problem description
Soft-deleted submissions are still shown in the delete form list.

#### Steps to reproduce the problem
1. Go to the Delete form list
1. Select several sent submissions
1. Delete those submissions
1. See that they're still there

#### Expected behavior
Soft-deleted submissions don't appear in the delete form list.

**Comment by grzesiek2010** [comment]
There is already an issue and a fix for this see:
https://github.com/getodk/collect/issues/6017 and https://github.com/getodk/collect/pull/6107

**Comment by lognaturel** [comment]
😢 Sorry, thank you!
