### ISSUE TITLE
Up to three different progress indicators can be shown sequentially at form load

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6111]
#### ODK Collect version
https://github.com/getodk/collect/commit/d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5

#### Android version
13

#### Device used
Galaxy A13

#### Problem description
We now provide more indication of progress which is good. However, it's displayed differently for different actions and those can stack.

#### Steps to reproduce the problem
Launch a form that has an attached CSV which it queries. For example: 
[Archive.zip](https://github.com/getodk/collect/files/15100997/Archive.zip)

https://github.com/getodk/collect/assets/967540/898f21ce-32fc-42e6-8bd3-7481b57c2b6c

This is made worse by having offline entities enabled in that version.

Here is a one-question form on the store version (2024.1.3):

https://github.com/getodk/collect/assets/967540/5df3fa5c-7a18-4891-b5ba-00766774c008

#### Expected behavior
One progress indicator.

**Comment by lognaturel** [comment]
Although this is messy, it's not likely to be a priority any time soon. Let's close for now.

**Comment by lognaturel** [comment]
CC @alyblenkin maybe just something to have in the back of your mind as we revisit some of these screens and think about other contexts in which we have progress indicators.

**Comment by alyblenkin** [comment]
Yes, I think we did a few iterations on progress indicators earlier in the year. This is a good example of something we could fix eventually.
