### ISSUE TITLE
After finalizing form and changing auto send setting forms that should be sent are being finalized

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6113]
#### ODK Collect version
the master version d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5

#### Android version
10, 14

#### Device used
Samsung Galaxy M12, Pixel 7a

#### Problem description
After finalizing form and changing auto send setting, forms that should be sent are being finalized, additionally forms that are already in ready to send are not being auto sent.

#### Steps to reproduce the problem
Precondition:
Wifi is on

1. Go to settings > form management and set auto send to cellular only
2. Go to any form
3. Finalize form
4. Go to settings > form management and set auto send to wifi only or wifi or cellular 
5. Go to any form
6. Send form
7. Go to Ready to send view

#### Expected behavior
When wifi is on and auto send setting is set to wifi only or wifi and cellular form should be sent, when pressing send button at the end of page and forms from ready to send should be auto sent also.

**Comment by seadowg** [comment]
> After finalizing form and changing auto send setting, forms that should be sent are being finalized

I don't understand "forms that should be sent are being finalized" here.

**Comment by WKobus** [comment]
@seadowg What I meant by "forms that should be sent are being finalized" is that I have wifi on and auto send setting set to "wifi only" or "wifi or cellular", so when I'm on end page and press send button, form should be sent but it is finalized instead, also forms that are already in ready to send are not being auto sent.

**Comment by seadowg** [comment]
Blocking this for the moment as it might be that fixing #6112 also fixes this.
