### ISSUE TITLE
FormListActivity and InstanceListActivity not registered in Android manifest

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#612]
FormListActivity and InstanceListActivity are not registered in the Android manifest. 

I'll add them to the manifest.

**Comment by lakshyagupta21** [comment]
@pratikmjoshi There is no need to add them to the manifest as there is no UI attached to any of the files.
[Refer this link](https://developer.android.com/guide/topics/manifest/activity-element.html)

**Comment by pratikmjoshi** [comment]
@lakshyagupta21 Yeah, but they raise warnings during builds, so its better to just add them to the manifest.

**Comment by lognaturel** [comment]
[This](http://stackoverflow.com/questions/5844561/android-abstract-activity-in-manifest) suggests there's no reason to put abstract classes in the manifest. (As an aside, I think `InstanceListActivity` should be made abstract, if you agree you are welcome to submit a small pull request for that.)

I'm actually not seeing the warning! Where do you see it @pratikmjoshi? Can you please copy the full text?

**Comment by nikhilbalyan** [comment]
@lognaturel i guess warning are shown while we commit changes via android studio. please verify @pratikmjoshi

**Comment by pratikmjoshi** [comment]
@lognaturel @nikhilbalyan The warnings as shown while we build the app via android studio. As shown below:
![temp](https://cloud.githubusercontent.com/assets/19923446/23968139/a91515a2-09e7-11e7-98fa-b29bb1baa411.png)

If you go to android studio, analyze->inspect code, you can view all these warnings. I just made a pull request for one type of warning. Are these warnings occurring when you build the app on android studio as well? Or is there something I'm missing?

@lognaturel Yes it should be. I will submit the pr for making InstanceListActivity abstract. I guess FormListActivity should also be made abstract. Should I do that as well?

**Comment by lognaturel** [comment]
Yes, please also make `FormListActivity` abstract!

So it sounds like what you're seeing are [lint warnings](https://developer.android.com/studio/write/lint.html) but strangely enough I can't seem to find any having to do with those activities missing from the manifest! Can you please copy the text of the warning?

**Comment by pratikmjoshi** [comment]
@lognaturel  Yes, those are lint warnings. Actually, these warnings are removed once I made InstanceListActivity and FormListActivity abstract. So I'll reference that pr as a fix to this issue.

There seem to be a lot of lint warnings. Are these warnings classified as structural problems?  I would be interested in getting rid of these warnings. Any suggestions on how I should approach this?


Before I made the above change:
![example](https://cloud.githubusercontent.com/assets/19923446/23970152/e5554846-09ee-11e7-86d6-7a4550af63a0.png)

**Comment by lognaturel** [comment]
How interesting, I wonder why I wasn't seeing it in my lint report when I ran it from the command line. Maybe running it from Android Studio ignores the `lint.xml` file? I just run it with `./gradlew lint`.

Awesome that making the classes abstract was a solution.

You're right that it would be good to address some of these. The challenge is that lint is not a very precise instrument and some of the warnings really should be ignored (typos, for example, are usually incorrectly identified). There are also some things we've also deliberately chosen to do like targeting API 22. So the results will take some interpreting and thinking about.

If you're interested in this, I'd say try to identify warnings that are clearly worth acting on and file some issues with proposed solutions. We can then make sure your proposed solution is the right one and then you can make it happen!
