### ISSUE TITLE
Send submissions in oldest first order

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#6128]
Collect should always send submissions in oldest to newest (in terms of finalization date). This will limit the number of out of order entity updates that servers will have to deal with. 

Currently, submissions are either sent in display order (for manual sending) and database order (for auto send).

We should make sure we use oldest to newest order for these operations:

- [x] Auto sending forms
- [x] Bulk finalising drafts
- [x] Manually sending a selected set of forms

They don't all need to be fixed in one PR (or even released at the same time).

**Comment by seadowg** [comment]
@lognaturel I've added bulk finalisation here as we could end up auto sending in the wrong order if we bulk finalize in the wrong order in cases where the sending happens very quickly (i.e. we get spin up multiple auto send tasks).

**Comment by lognaturel** [comment]
@grzesiek2010 I think you're going to take this one on, right? Would be good to prioritize it so we can test it along with some of the other interesting offline Entities cases. Thanks!

**Comment by grzesiek2010** [comment]
> Would be good to prioritize it so we can test it along with some of the other interesting offline Entities cases. Thanks!

Sure!
