### ISSUE TITLE
Unable to get 5 meter accuracy in the geopoint on Android 8.1 and 10

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6130]
#### ODK Collect version
the store version 2024.1.3, the master version ee9b02a540187bd3d7959f979d4e81927f8e9d7c
#### Android version
8.1, 10
#### Device used
Nexus 5X, Redmi 9T
#### Problem description
In  the geopoint widget with no appearance I’m not able to get location accuracy 5m or less ( point isn’t saved automatically) on Android 8.1 and 10. I’m not sure what factors may influence these 2 devices and getting location (other devices can get 5m accuracy).
#### The way I tested it
1. I put 2 devices outside on a balcony on a day with clear skies.
2. I started getting the geopoint and waited 5 minutes (I didn’t move the devices).
3. During 5 minutes the best accuracy was about 9 meters.

**Comment by seadowg** [comment]
@dbemke Are you able to get 5m accuracy on these devices using another app? It's very likely a hardware limitation rather than anything to do with Collect.

**Comment by dbemke** [comment]
> It's very likely a hardware limitation rather than anything to do with Collect.

That's the part which I'm not sure how to verify it so that's my result are reliable. I'm pretty sure that in the past Android 10 was able to get 5m accuracy. Before filing the issue I tried to eliminate some factors like the weather and the place so I tried to get 5m accuracy in 2 different cities, in a place near a lake (so there weren't many building around), with different weather. Now, I tried in My GPS Location app and the best accuracy was also only 10m but it's cloudy today so again I don't feel that the results I get are 100% reliable.

**Comment by seadowg** [comment]
> Now, I tried in My GPS Location app and the best accuracy was also only 10m but it's cloudy today so again I don't feel that the results I get are 100% reliable.

There are so many things that could affect it ([this article](https://ciechanow.ski/gps/?utm_source=pocket_saves) is a pretty amazing deep dive on how GPS actually works) and that could change over time. As long as we're not seeing massively different accuracies in Collect from other apps, I don't think this is something we can do anything about.
