### ISSUE TITLE
Fix the gap below the app bar

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6135]
There is a tiny gap below the app bar when viewing "Ready to send" and the progress bar. I think this happened recently, and it would be nice to tighten it up. 

It's small, and I wasn't going to mention it, but Hélène noticed it too :)

**Comment by seadowg** [comment]
I think as part of this we should look at use a more Material 3 approach to the app bar where the app bar is flat until the content is scrolled and then it becomes raised (probably through tonal color changes). See Signal for a canonical (and open source) example. I'm guessing this uses `CoordinatorLayout`. 

A simpler first step might be to just use a more raised (tonal) colour for our app bar so we don't need the shadow, but I'd be keen for us to investigate the slicker interaction.
