### ISSUE TITLE
Add +/- buttons to integer question type

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6137]
### Problem 

We've heard [a lot of feedback](https://www.notion.so/getodk/Users-want-a-more-intuitive-way-to-count-things-d1f32559f44b4835b6c0043d2a652742?pvs=4) around making it easier and more intuitive to count things. For example, if you want to count turtle eggs, trash, or plants it would be efficient to use a +/- button than to manually enter the number.

### Solution

- For integer questions, we want simple buttons on the right and left of the screen so it's easy to access 
- Large enough hit target without taking up too much vertical space 
- It will only increase by one for now, and we are not allowing negative numbers 

[Figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5205%3A86781&t=QzSkjeZXBnWva4mT-1) 

### Future considerations

- Allow negative numbers
- Consider how a user might reset 
- How this might work for adding a range 
- Long press to increase by increments of 10 or something 
- Haptic feedback would be an interesting next step

**Comment by grzesiek2010** [comment]
Should this change the default integer question or add a new appearance like `counter` for example which would display that question type in the described way? I thought that it would be a new appearance but now I'm not sure reading the issue.

**Comment by lognaturel** [comment]
It should be a new appearance! I agree that `counter` feels like it's non-controversial.
