### ISSUE TITLE
Missing saved values in selects in the multi warning form with values containing spaces

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6144]
#### ODK Collect version
the store version 2024.1.3, the master version df28fb6d9d7a84f0e796e170011d6e8c79ca8063
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After saving a draft of the multi warning form saved answers aren’t present in the draft.
#### Steps to reproduce the problem
1. Go to start new form and fill the form.
[multi-warning.xml.txt](https://github.com/getodk/collect/files/15389668/multi-warning.xml.txt)
2. Save the form as draft.
3. Go to Drafts and open the form, check answers
#### Expected behavior
Values shouldn’t disappear.

**Comment by seadowg** [comment]
@dbemke was this introduced in v2024.1.3 or is it also present in v2023 versions?

**Comment by dbemke** [comment]
In 2023.3.1 values also disappear after saving them as a draft

**Comment by seadowg** [comment]
@dbemke could you include some more information about the multi warning form? It's not something I'm familiar with. That'd save me setting up a new project to test it.

**Comment by dbemke** [comment]
https://test.getodk.cloud/#/projects/531/forms/multi%20warning/draft

**Comment by seadowg** [comment]
@dbemke are you able to reproduce with other forms or just this one?

**Comment by dbemke** [comment]
Only this one. We were testing bugs in selects with whitespaces at the beginning and I found this form while testing

**Comment by dbemke** [comment]
I tried to upload a xlsx form with select with spaces and I get this
![centralwhitspaces](https://github.com/getodk/collect/assets/56479916/1673cacf-c1b0-4297-a213-5535584a4d2f)
In the multi warning form in the issue there are spaces (see the screenshot). I don't know if it's the difference between uploading an xlsx or xml or it might be something different than spaces causing that
![multiwarningForm](https://github.com/getodk/collect/assets/56479916/b9efe0ea-6e07-4031-9464-8a0e04bad47f)

**Comment by seadowg** [comment]
As discussed with @lognaturel, the form is broken and wouldn't be possible to create with XLSForm so we won't be fixing this.
