### ISSUE TITLE
Dynamic read-only not updated in field list

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6149]
I haven't actually verified this but I believe that similar to https://github.com/getodk/collect/issues/5941, when read-only is dynamic based on some condition (e.g. ${age} > 18), it's not updated in a field list.

This is not urgent to address but I want us to have a record of it. When we have a chance, someone can attach a sample form.

**Comment by dbemke** [comment]
I created a form and it works as expected. Is this a type of form you were thinking of?
[field-list required.xlsx.txt](https://github.com/user-attachments/files/15613373/field-list.required.xlsx.txt)

**Comment by lognaturel** [comment]
The important thing is having an expression for read-only like [dynamic-readonly.xlsx.txt](https://github.com/user-attachments/files/17334104/dynamic-readonly.xlsx.txt)

Happy to report that it works as expected!
