### ISSUE TITLE
Asterix not displayed well with double baskslashes A\\*B\\*C

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6151]
#### ODK Collect version
the store version 2024.1.3, the master version df28fb6d9d7a84f0e796e170011d6e8c79ca8063
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Asterix isn't displayed well in `A\\*B\\*C` Collect. In Collect it is 
![collectAsterix](https://github.com/getodk/collect/assets/56479916/8861fc60-dc45-4581-8c97-01c3d7b0e544)

#### Steps to reproduce the problem
1. Open the form and find the `A\\*B\\*C` example in selects
[SelectFormFileMarkdown.xlsx.txt](https://github.com/getodk/collect/files/15414053/SelectFormFileMarkdown.xlsx.txt)
[abc.csv](https://github.com/getodk/collect/files/15414055/abc.csv)

#### Expected behavior
`A\\*B\\*C` in Collect should be displayed as `A*B*C`

**Comment by grzesiek2010** [comment]
Everything works as expected to me. If you want to display `A*B*C` you should use `A\*B\*C` (single slashes).
If you use double slashes that result also seems to be correct. The result is different than what you can test using GitHub but GitHub might be wrong if I test it with an online tool like https://markdowntohtml.com/ it works like in Collect.
