### ISSUE TITLE
Crash after multiclicking "delete selected" in "Delete form- blank forms"

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6159]
#### ODK Collect version
the master version e909810553c0a39672dfaf225e43362432c8571c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It’s possible to multiclick "Delete selected” in "Delete forms - blank forms” and after trying to delete an already deleted form there’s a crash.
In the store version 2024.1.3 the app doesn’t crash.
#### Steps to reproduce the problem
1. Create a demo project and download forms.
2. Go to "Delete form – blank forms”.
3. Select a form and tap "delete selected” twice (quickly).
4. In the dialog tap "delete forms” and then again tap "delete forms”.
#### Expected behavior
Muticlicking shouldn’t be possible

**Comment by seadowg** [comment]
Instead of relying on `MultiClickGuard` here, it may be that we should just be disabling the button while forms are deleted.
