### ISSUE TITLE
An entity list that doesn't exist in any form in a project disappears from entity list in experimental settings

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6160]
#### ODK Collect version
the master version edcffccf3e5d5793e4ace510c88d16585e8cd075
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
An entity list that doesn't exist in any form in a project disappears from entity list in experimental settings after refreshing the list of bank forms.
#### Steps to reproduce the problem
1. In experimental settings enable local entities.
2. Go to entity lists.
3. Tap the three dots – Add entity list.
4. Enter a name of a entity list that doesn’t exist in any form in the device (e.g. "abc”) and tap "add”.
5. Tap the three dots – Add entity list.
6. Enter a name of a entity list that exists in a form in the device (e.g. "trees”) and tap "add”.
7. Go to Start new form and refresh the list of forms.
8. Go to experimental settings and check if  "abc” is in the entity list
#### Other information
If I add just an entity list that doesn't exist in forms (so it's the first and only entity list in experimental settings) and refresh the list of blank forms, then the issue doesn't occur (entity list doesn't disappear).

**Comment by seadowg** [comment]
@dbemke I can't reproduce this. Can you double-check against `master`?

**Comment by dbemke** [comment]
I just checked on the master version baaf0ed6a7997c80007f33388c06c983e46e8836 on Android 10 and I the issue doesn't occur there.

**Comment by seadowg** [comment]
Great! Must have been fixed by some of the improvements we made. I'll close this. 

Could you double-check https://github.com/getodk/collect/issues/6163 as well and close it if it's not reproducing?
