### ISSUE TITLE
Entities header in entities lists in experimental settings

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6161]
#### ODK Collect version
the master version d67e55a75cc20d31fdd9468f575ed2c2aa239dac
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
When I go to experimental settings - View entity list I open the list of entity lists but the header says that these are entities. Is this expected?
![entityListVsEntities](https://github.com/getodk/collect/assets/56479916/93043140-0d08-4c70-ac66-b2cfe6507148)
#### Steps to reproduce the problem
1. In experimental settings enable local entities.
2. Tap "view entity lists".

**Comment by seadowg** [comment]
This should read "Entity lists" now.
