### ISSUE TITLE
Properties without ID and title in geojson cause error when opening select from map form

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6162]
#### ODK Collect version
the store version 2024.1.3, the master version e94c1e771eeb864188bbd35b2e7f1748d23e7ae8

#### Android version
10, 14

#### Device used
Galaxy M23, Redmi 7

#### Problem description
Properties without ID and title in geojson cause error when opening select from map form

#### Steps to reproduce the problem
1. In central upload s1FromMap form and Geojson without ID and Title in properties
[S1FromMap.xlsx.txt](https://github.com/user-attachments/files/15512923/S1FromMap.xlsx.txt)
[items.geojson.txt](https://github.com/user-attachments/files/15512943/items.geojson.txt)
2. Go to collect > start new form
3. Open s1FromMap form

#### Expected behavior
Form should open without error when properties in attached geojson do not have ID and title

#### Other information 
![XRecorder_31052024_134937](https://github.com/getodk/collect/assets/162433284/4c1ed763-4c6a-46b8-a510-bfc95426a9d9)

**Comment by seadowg** [comment]
@grzesiek2010 this is expected right? I think we need id/title to treat them as selects.

**Comment by grzesiek2010** [comment]
Yeah I believe that `id`/`title` in geojson represents the same as `name`/`label` in the choices sheet and that's why it's required but I wanted to double check so when @WKobus asked me if he should file an issue I said yes. I will take a look at the code to be sure and probably close the issue.

**Comment by seadowg** [comment]
@grzesiek2010 guessing we're ok to close this?

**Comment by grzesiek2010** [comment]
Yeah, I’ve just double-checked, and as I mentioned, the ID is indeed required as described in the docs: https://docs.getodk.org/form-datasets/#building-selects-from-geojson-files. However, the title is not. It looks odd when there’s no title, but there’s no error.
We can close this.
