### ISSUE TITLE
Manually added second dataset/entity list is removed after refreshing the list of blank forms

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6163]
#### ODK Collect version
the master version d67e55a75cc20d31fdd9468f575ed2c2aa239dac
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that after manually adding a dataset in experimental offline entities the first dataset shows the list of entities after refreshing the list of blank form but repeating it for another dataset results in removing the dataset form the list of entity list in experimental setting.
If I create an offline entity after adding the entity list, the entity list won't disappear even if it's the second entity list/dataset.
#### Steps to reproduce the problem
1. Create a project which contains 3 different datasets (entity lists)
2. In experimental settings enable local entities.
3. Go to view entity lists.
4. Tap the three dots – Add entity list.
5. Refresh the list of blank forms.
6. Go to view entity list and check if the first entity list is there (the dataset exists and you can see entities in it).
7. Tap the three dots – Add entity list and enter the name of the second dataset (entity list).
8. Refresh the list of blank forms.
9. Go to view entity list and check if the second entity list is there.
10. Repeat steps 3-6 for the third dataset.

**Comment by seadowg** [comment]
@dbemke is this not a duplicate of #6160?

**Comment by dbemke** [comment]
I don't know if it's the same #6160 is about a dataset that isn't in forms in a device. This one that sometimes I can't add a dataset that it in forms in the device if it's a second dataset. I don't know what is the root cause in both

**Comment by seadowg** [comment]
@dbemke good point. I think they're most likely the same, but I'll leave both in.

**Comment by seadowg** [comment]
This might be fixed (as we saw with #6160).
