### ISSUE TITLE
Offline maps UI improvements

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#6172]
From @alyblenkin: I think this is looking really good!  I'll hold off on UI tweaks for now until everything else is ready. A few thoughts when playing around with the build:

**Adding an unsupported file**
If we wanted to give some feedback if the user adds an unsupported file, we could have a [dialog](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5320%3A58659&t=YzdjqdwJz0JeJlG9-1) explaining what's happening. The first time I tried adding a layer, I accidentally tapped the photo above my mbtile and didn't realize what happened. If the user has other files on their device I could see that happening by accident. 

**What if I add the same layer twice?**
I'm wondering if we should have a dialog if you try to add a layer that is already added? If the names are really similar, you might not realize you've already added that file.

**Progress indicator when adding a layer**
I didn't specify the interaction here, but I'm glad we have it because it does take some time to add the mbtiles. I'm thinking we should either show the [progress bar](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5320%3A58729&t=YzdjqdwJz0JeJlG9-1) at the top or show the circular indicator in a container with some text to explain what's happening. This is more of a UI thing, so we can come back to this later.

**Comment by lognaturel** [comment]
In the original mockups, the file picker allowed multiple selection. At least on my device, there's only single selection. I notice that there's some inconsistency between singular and plural that we'll need to smooth out once we decide whether we're doing single or multi selection. If it's a significant implementation difference to do multi-selection, let's stick with single and replace the plural "Layers" in the confirmation screen.

My initial instinct was to try tapping on the layer name once it populated in the confirmation screen because it looks like a button to me. I don't have a suggestion related to that but wanted to mention it.

**Comment by grzesiek2010** [comment]
> In the original mockups, the file picker allowed multiple selection. At least on my device, there's only single selection. I notice that there's some inconsistency between singular and plural that we'll need to smooth out once we decide whether we're doing single or multi selection. If it's a significant implementation difference to do multi-selection, let's stick with single and replace the plural "Layers" in the confirmation screen.

You can select multiple layers. I don't know what your file picker looks like but mine is confusing so maybe that's the reason:
![image](https://github.com/getodk/collect/assets/3276264/43b9fff9-2a38-46b9-a380-93012977640f)
If I click on the title just one element is selected and the picker is closed. To select multiple files I have to click on the icon...

**Comment by alyblenkin** [comment]
I can add multiple too!

**Comment by alyblenkin** [comment]
> My initial instinct was to try tapping on the layer name once it populated in the confirmation screen because it looks like a button to me. I don't have a suggestion related to that but wanted to mention it.

Do you mean the layers here look like buttons? We could say "Layers added" to make that more clear
![Selected](https://github.com/getodk/collect/assets/7871340/75992ad5-add4-447f-9ad4-a2c72a32914e)

**Comment by lognaturel** [comment]
🤯 Thank you both! Yes, I can select multiple by tapping on the icon as well. I was initially in thumbnail mode rather than list mode and the icons are small and hard to tap. 

> Do you mean the layers here look like buttons? We could say "Layers added" to make that more clear

Yes. How about "Layers to add"?

**Comment by lognaturel** [comment]
Regarding plurals, I think we can either make all pluralization depend on the actual number of layers selected or always use plural. I don't really mind either way but there shouldn't be a mix of plural and singular (e.g "the layer available" -> "the layers available", "Add layer" -> "Add layers")

**Comment by alyblenkin** [comment]
Yes, good point! I was also chatting to @grzesiek2010 about what happens if people have many layers. He brought up how that might push the "Select layer access" below the fold. We thought it would be good to see what users think of the beta, but I think our assumption is that people won't be adding that many layers at a time.

**Comment by lognaturel** [comment]
> it because it does take some time to add the mbtiles

What is taking so long?! I'm surprised.

> I'm wondering if we should have a dialog if you try to add a layer that is already added?

I think this is ok to leave as-is. It feels like the end result is the right behavior (you can select the file you added).

**Comment by lognaturel** [comment]
From [Andrew's testing](https://forum.getodk.org/t/odk-collect-v2024-2-beta-prompt-to-recover-select-from-map-line-and-shape-styling-offline-entities-prototype/47002/14): the order has changed. I imagine some projects would find A-Z more valuable and others would find by date/time more helpful. I have a slight preference for keeping the prior behavior (A-Z)

**Comment by seadowg** [comment]
Ok so here are the small changes I think we need to make based on this discussion:

- Make all references to "layer" plural rather than the current mix of singular/plural ("Add layer" becomes "Add layers" for example).
- Anchor the "Layers" title to the top of the screen and the "Select layers access" section to the bottom of the screen with the layers scrollable in between. This allows the list of layers to be as long as required without pushing anything off-screen.
- Change the display order of exiting layers so that they are in A-Z order.

There are also a couple of larger changes I think we should create other issue for:

- Revising the progress indicator when importing layers
- Creating a better experience when trying to import non `.mbtile` files

Does that sound good to everyone? If so, I'll update the issue description for the small things and create the new issues for the larger ones.

**Comment by srujner** [comment]
Hey, I think the horizontal view also needs some improvements. Even with one layer, it's very hard to select it. 
With more layers, just moving around is annoying, deleting the same. Anyway, you can see it in the video 

https://github.com/getodk/collect/assets/85225519/8a6f5a91-5bb1-4f88-bf0b-b15b0df0d65e

**Comment by grzesiek2010** [comment]
> Hey, I think the horizontal view also needs some improvements. Even with one layer, it's very hard to select it.
With more layers, just moving around is annoying, deleting the same. Anyway, you can see it in the video

This would probably require having a different layout for horizontal mode as there is just not enough space there...

**Comment by alyblenkin** [comment]
I agree @grzesiek2010, we would likely want to change the layout for landscape, and I doubt that's a priority for this iteration. One small thing we could do is just have the title and a "read more" button below to save vertical space when in landscape mode.
