### ISSUE TITLE
Checking the condition instead of the Error handling via try/catch

### ISSUE THREAD

**Issue by nikhilbalyan** [getodk/collect#618]
#### Software and hardware versions 
Collect v1.4.1686-g934455d3, Android 5.1, Moto E

#### Problem description
Right now inside the Media Layout from line 143 to 148 we are doing the error handling if no application is found to view the video
#### Expected behavior
We should check instead of crashing the application via get content resolver if an application exists which can listen to that intent

I would love to work on the issue

**Comment by lognaturel** [comment]
@nikhilbalyan Sounds good!

**Comment by nikhilbalyan** [comment]
similar issue exists in almost all the Widget classes Working on them and will soon send a PR with all changes

**Comment by lognaturel** [comment]
Closed in #621.
