### ISSUE TITLE
Handle unsupported files when importing `.mbtiles`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#6199]
## User problem 
Both unsupported file types (non-`.mbtiles`) and layers not supported by the current map engine.

As a user adding offline layers 
I want to get error feedback when I've added an unsupported file type 
So that I can understand what happened and correct my mistake 

## Two user flows

**User attempts to add only unsupported files** (doesn't go through the entire flow)

> \<number of unsupported files\> layers can't be added
> The files you selected are not MBTiles. You can only add MBtiles files.

**User adds supported and unsupported files**

> \<number of unsupported files\> layers can't be added
> Some of the files you selected are not MBTiles. You can only add MBtiles files.

[Figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=3615-61784&t=irkJSqFzat0emlVt-1)

**Comment by alyblenkin** [comment]
@seadowg @lognaturel - It sounds like we are going to do this later, but I wanted to capture the two user flows we spoke about:

**User only selected unsupported files**  (doesn't go through the entire flow)

> **No. layers can't be added** 
> The files you selected are not MBTiles. You can only add MBtiles files.

**User selects supported and unsupported files** 

> **No. layers can't be added** 
> Some of the files you selected are not MBTiles. You can only add MBtiles files.  

Feel free to edit the copy! 

[Figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=3615-61784&t=irkJSqFzat0emlVt-1)

**Comment by lognaturel** [comment]
Looks good! The file type is "MBtiles" with an s so I updated that.

Maybe "The files you selected are not MBTiles. You can only add MBtiles files."

**Comment by seadowg** [comment]
We also at some point need to address the case where a user picks MBTiles files that aren't support by the current engine. In that flow, they just don't end up showing for selection after import. Personally, that feels more confusing but is hopefully less likely to happen? Should we pull out a separate issue for it?

**Comment by alyblenkin** [comment]
Good point. I wonder how we would address that. That might be something we could highlight in the docs? Or potentially in the description of the bottom sheet?

**Comment by seadowg** [comment]
I'm thinking we pull that out as a separate issue and solve it separately. That sound ok @alyblenkin and @lognaturel? I guess the real question is: are we OK to handle that case after release?

**Comment by lognaturel** [comment]
Yes, it feels much less likely!

**Comment by alyblenkin** [comment]
@seadowg so do we want to still do the two flows above, and spin out another issue for the case you mentioned and come back to it later? I want to make sure I'm not blocking anything here!

**Comment by seadowg** [comment]
> @seadowg so do we want to still do the two flows above, and spin out another issue for the case you mentioned and come back to it later? I want to make sure I'm not blocking anything here!

Yup! Sorry I hadn't had a chance to split it out yet, but will do that now 👍.

**Comment by grzesiek2010** [comment]
There is something wrong with the description or maybe with my understanding.
In the description, I see `No. layers can't be added` in both cases which indicates that in both cases we should block adding layers (all of them). According to what I see on Figma if it's a mix of supported and unsupported layers a dialog should be displayed (to inform users about what happened) but the supported ones should still be imported. @seadowg which source is the correct one?

**Comment by seadowg** [comment]
I was confused there as well! It should be `<number of unsupported layers> layers can't be added`, so if two couldn't be imported it would be "2 layers can't be added". I'll update the description.
