### ISSUE TITLE
A form is finalized (not sent) if there is "default" auto send setting in the form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6203]
#### ODK Collect version
the master version fb11c1468b7dad7deb4c8423cd4ea2db9077fb7d
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
A form is finalized (appears in "Ready to send”- isn’t sent automatically) if in the form settings there is "default” in auto send options. 
(The issue doesn’t occur in the store version 2024.1.3)
#### Steps to reproduce the problem
1. In the project there is "wifi or cellular” auto send setting and there is a sim card and wifi on.
2. Open the form and send it.
[AutoSendDefault.xlsx.txt](https://github.com/user-attachments/files/15872099/AutoSendDefault.xlsx.txt)
3. Check the "Ready to send” list.
#### Expected behavior
I couldn’t find information in the documentation about using "default” in auto send setting in a form but in the past the setting sent the form.

**Comment by dbemke** [comment]
The same issue occurs in a form in which auto send is set to "1".
[my-form(3).xlsx.txt](https://github.com/user-attachments/files/15873065/my-form.3.xlsx.txt)

**Comment by seadowg** [comment]
> 1. In the project there is "wifi or cellular” auto send setting and there is a sim card and wifi on.
> 2. Open the form and send it.
[AutoSendDefault.xlsx.txt](https://github.com/user-attachments/files/15872099/AutoSendDefault.xlsx.txt)
> 3. Check the "Ready to send” list.

@dbemke it makes sense that we'd send the form in this scenario (we shouldn't treat "default" as "false"), but what happens in older versions when I disable auto send at a settings level with that form? Does it send because it treats "default" (or the "1" in the other example) as "true"?

**Comment by dbemke** [comment]
In the store version in form settings auto send: 
- default - send button at the end page of a form, form is sent automatically
- false - finalize button at the end page, the form is finalized
- true- send button at the end page of a form, form is sent automatically

Currently default - send button at the end page, the form isn't sent automatically
So in the past default acted like true but how it the code works I don't know.

**Comment by seadowg** [comment]
What about if auto send is disabled in Collect? In those cases "default" is behaving like there's no `auto-send` attribute. "true" only matters if the auto send setting is disabled.

**Comment by dbemke** [comment]
If in Collect settings there is auto send set to "off" then with default in form settings the form is finalized (in the store version)

**Comment by seadowg** [comment]
Cool! So with `auto-send` it does actually behave as the [specs say](https://getodk.github.io/xforms-spec/#submission-attributes), but with one exception/caveat: unsupported values (like "default" or "muffin") will be treated as if there was no `auto-send` attribute.
