### ISSUE TITLE
List of layers to import disappears in landscape view

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6212]
#### ODK Collect version
the master version 6993f66a733c5ce7a8bf758f982c84ccc340fb90

#### Android version
10, 14

#### Device used
Redmi 7, Galaxy M23

#### Problem description
List of layers to import disappears in landscape view, when rotating back to portrait view, list of layers to import is again visible.

#### Steps to reproduce the problem
1. Go to Project settings > Maps
2. Tap on Layer
3. Tap on Add Layers
4. Add any layer
5. Rotate device, while on list of layers to import view

#### Expected behavior
List of layers to import should be visible in landscape view

**Comment by seadowg** [comment]
@alyblenkin how do you think this screen should behave when the static parts (the header and the select access section) are longer than the screen? We could either have everything be scrollable (so it falls of screen but can be scrolled to) and have the list be scrollable within that, or do we want the whole thing to scroll as one?

**Comment by alyblenkin** [comment]
Good catch @WKobus! 

> @alyblenkin how do you think this screen should behave when the static parts (the header and the select access section) are longer than the screen? We could either have everything be scrollable (so it falls of screen but can be scrolled to) and have the list be scrollable within that, or do we want the whole thing to scroll as one?

I could see it working both ways, but I'm leaning towards having everything scrollable, so if it falls off the screen you can still get to it. It's not ideal to have multiple scrollable sections, but I think that's better than the whole thing scrolling as one. 

Side note: I also noticed that the title of the bottom sheet is cut off in landscape view.

**Comment by seadowg** [comment]
@alyblenkin Playing around with it, I feel like these are actually our two options:

1. Don't make the list of layers scrollable
2. Make the list of layers scrollable, but define a max height

Without a max/min height, the scrollable list will grow as much as it can within another scrollable list. That of course results in not a scrollable list as it has infinite room to grow (it's just more scrollable space). I'm going to go with 2, but set a max height so that we'll only see scroll bars for a lot of items (10+).

**Comment by alyblenkin** [comment]
> Without a max/min height, the scrollable list will grow as much as it can within another scrollable list. That of course results in not a scrollable list as it has infinite room to grow (it's just more scrollable space). I'm going to go with 2, but set a max height so that we'll only see scroll bars for a lot of items (10+).

I think option 2 sounds like a good option with a max height!
