### ISSUE TITLE
Minimizing the app with "no background processes” removes offline layers to add from the list and then trying to add layers crashes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6219]
#### ODK Collect version
the master version 7d30e187d65ecb5351a9b029d7b48c1fa0ee9181
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Minimizing the app with "no background processes” settings on removes offline layers to add from the list and then trying to add layers crashes the app.
![crashLayers](https://github.com/getodk/collect/assets/56479916/41700dd8-72b8-4b45-bbe6-d3bca1f4dde6)

#### Steps to reproduce the problem
1. Set "no background processes" in the device.
2. Go to any form with maps and open the map.
3. Tap the offline layers icon, "add layers” and select some layers to add.
4. While on "Add layers” with the list of layer to add, minimize the app and go to a different app.
5. Go back to Collect (the list of layers to add is empty).
6. Tap "add layers”.
#### Expected behavior
I'm not sure what is the expected result - if it's possible to keep offline layers on the list in this case or it's better to close all the dialogs/bottom sheets

**Comment by grzesiek2010** [comment]
This happens because we store selected layers (layers to import) using `LiveData` and it gets cleared on process death. @seadowg do you think it's worth the effort to keep that data using [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate)? I was rather thinking about dismissing that confirmation dialog and letting users select the layers again.

**Comment by seadowg** [comment]
> @seadowg do you think it's worth the effort to keep that data using [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate)? I was rather thinking about dismissing that confirmation dialog and letting users select the layers again.

I think for the moment we should just dismiss the dialog (going back to the picker) if this happens rather than investing in dealing with save state.
