### ISSUE TITLE
Counter app - question increment set to true doesn't open the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6246]
#### ODK Collect version
the master version 2024.2.0 BETA 4
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The counter app with a question with increment and autoincrement set to true doesn't launch the app (shows an error).
![counterError](https://github.com/getodk/collect/assets/56479916/666f2d86-cd89-4d55-b8a9-e8490f8379ed)

The issue doesn’t occur in the store version 2024.1.3
#### Steps to reproduce the problem
1. Install counter app
2. Go to the conter2 form.
[counter2.xlsx.txt](https://github.com/user-attachments/files/16068209/counter2.xlsx.txt)
3. Go to question with increment set to true.
4. Tap "launch”.
#### Expected behavior
The app should open.

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 as far as I know there's no reason this shouldn't work any longer, so I'm sticking this in for the current release.

**Comment by lognaturel** [comment]
Some things illustrated by [counter2-HM-1.xlsx](https://github.com/user-attachments/files/16071663/counter2-HM-1.xlsx):
- The `jr:itext('/data/form_name:label')` call works in a calculate
- The same call fails without `increment` or `autoincrement`
- From debugging, I see that in the released version `jr:itext('/data/form_name:label')` is passed to `getValueRepresentedBy` as expected. On `master`, the last parenthesis is lost (`jr:itext('/data/form_name:label'` is passed in)

I've verified that `ExternalAppsUtils.java` has not been touched in this release cycle.

**Comment by lognaturel** [comment]
@grzesiek2010 I wanted to take a quick look in case it was an issue in JR but I think it's something specific to external apps which you're much more familiar with than me. I suspect changes in https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/ExternalAppIntentProvider.java might be responsible. Could you please take a quick look and we can touch base tomorrow to decide on next steps if you can't quickly spot it?

**Comment by grzesiek2010** [comment]
@lognaturel you are right the bug was in `ExternalAppIntentProvider`. It's fixed in https://github.com/getodk/collect/pull/6247
