### ISSUE TITLE
Added vector offline layer isn’t visible in the bottom sheet in the map after adding in settings

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6248]
#### ODK Collect version
2024.2.0 BETA 4
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Added vector offline layer isn’t visible in the bottom sheet in the map after the steps described below.
If I don’t open the map (in step 2) before going to settings, the issue doesn’t occur.
#### Steps to reproduce the problem
1. Install Collect and add the demo project (download forms).
2. Go to Select one from map to select a point question and open the map.
3. Tap 3 dots – project settings -maps.
4. Change the source of maps to Mapbox.
5. Tap layers and add a vector offline layer.
6. Select and save the vector layer.
7. Tap the device back button to go back to the form.
8. Tap "Select place” and check the selected offline layer
#### Expected behavior
The layer should be applied and in the list in the map.

**Comment by grzesiek2010** [comment]
I've just tried to reproduce but to no avail...
@dbemke are you able to reproduce it on master as well?

**Comment by dbemke** [comment]
Try after opening the map open also offline layers and it needs to be a new installation.

**Comment by grzesiek2010** [comment]
Ok I know, `Don't keep activities` needs to be turned off.
