### ISSUE TITLE
Deleted form data still displayed in the UI

### ISSUE THREAD

**Issue by nribeka** [getodk/collect#625]
#### Software and hardware versions 
Collect latest build from master

#### Problem description
When user delete form data (instances) from the sd card, the form data will still gets displayed in the list of form data because the form data display only use the data from the database.

#### Steps to reproduce the problem
* Fill a blank form
* Delete the xml file from the sdcard (using adb or connecting the phone as drive)
* Go to the list of form data and the deleted form data will still be there.

#### Expected behavior
* Form data record from the database should be in sync with the underlying physical xml file. When user delete the xml file, we should delete the dangling record from the database as well.

**Comment by lakshyagupta21** [comment]
@nribeka I would like to work on it.

**Comment by nribeka** [comment]
@lakshyagupta21 confirm with @lognaturel later 👍

**Comment by lognaturel** [comment]
@lakshyagupta21 Sounds good. Please make sure to check out #595 as this will be very similar.

**Comment by lakshyagupta21** [comment]
@lognaturel I am thinking to write separate background task for this issue because the MainMenuActivity will update the number of files on buttons only when task gets completed. Am i doing it in correct way ?
