### ISSUE TITLE
Rotating the device while in "add layers” dialog the circular indicator shows downloading layers closes the dialog

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6254]
#### ODK Collect version
the master version f2ce0995dfe77673c8a6bfdef53a0fe2615fa4eb
#### Android version
8.1, 10, 14
#### Device used
Nexus 5X, Redmi 9T, Pixel 7a
#### Problem description
If a user rotates the device while in "add layers” dialog the circular indicator shows downloading layers, the dialog is closed. The issue doesn’t always occur.
The issue doesn’t occur in the 2024.2.0 BETA 4
#### Steps to reproduce the problem
1. Open any map and go to offline layers bottom sheet (or in Collect settings-maps).
2. Tap "add layers”.
3. Select some layers to add.
4. While you can see the circle spinning, rotate the device.
#### Expected behavior
The dialog shouldn’t disappear after rotating the screen.

**Comment by grzesiek2010** [comment]
This is caused by https://github.com/getodk/collect/pull/6243. Not perfect but I would leave it as is for now and improve once we decide what to do in https://github.com/getodk/collect/issues/6198
