### ISSUE TITLE
Constraint violation message is not dismissed when value from external app changes

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6266]
#### ODK Collect version
v2024.2.0

#### Android version
Android 14

#### Device used
Galaxy A13

#### Problem description
Using an external app question, when I get a different value from the external app, I may still see a stale error message that does not apply to the new value.

#### Steps to reproduce the problem
Use a form with an external app call and a constraint on it such as [this one](https://docs.google.com/spreadsheets/d/1XCPbItGnIxBDuQgAT4uhC5sYkd2cxiYDq3EpjIBhBu0/edit?gid=0#gid=0)
Violate the constraint, see that a message is shown as expected
Launch the app again, see that the message is still shown

#### Expected behavior
The error message is dismissed when the constraint condition is met

#### Other information 

I did some initial debugging and noticed that `ExStringWidget.hideError` overrides `QuestionWidget.hideError` without calling `super`. I added the `super` call and I believe that results in the currently-expected behavior: the error message is dismissed whenever the value changes.

~My original expectation was that values from external apps (+ barcode, etc) would be validated on return to Collect. I guess that would be different from other question types so maybe we don't want that? I also expected that fields in field lists would get their validation messages updated dynamically but it looks like it's only done on swipe, right?~ We can split this out into a separate issue if we eventually want but it's probably not that important.

**Comment by seadowg** [comment]
@lognaturel it'd be good to investigate if this has regressed or if it's always (within reason) been this way.

**Comment by lognaturel** [comment]
I believe it has been an issue since we introduced inline validation errors.

@grzesiek2010 mentioned this is probably because this question type has a button to launch an external activity it exists and also a fallback to a text field so it has two possible kinds of validation errors it can show.
