### ISSUE TITLE
Memory leak after selecting an offline layer and reopening a map

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6281]
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328, also 2024.2.x b44e199454102b244362836da0cebef022ca1730
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There’s a memory leak after selecting an offline layer and reopening a map.
![leakSelectLayer](https://github.com/user-attachments/assets/5a7d6898-6277-498d-971c-f1696803612c)

#### Steps to reproduce the problem
1. Go to All question types form
2. Open any widget with maps and add some offline layers.
3. Select and save and offline layer.
4. Go back to the form and open any map.

**Comment by grzesiek2010** [comment]
Important note: this leak only happens with `Open Street Maps`.
