### ISSUE TITLE
Unnecessary savepoint in a sent form without a specified instance ID

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6285]
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's an unnecessary savepoint in a sent form with a specified instance ID
![BirdsSavepoint](https://github.com/user-attachments/assets/58dd006e-cf3e-45db-9429-7013d081ed8a)

The issue doesn’t occur in the store version 2024.2.1 but the issued occurred in 2024.2.0.
#### Steps to reproduce the problem
1. Send Birds form ( https://test.getodk.cloud/#/projects/385/app-users user "submission").
2. Go to "Start new form” and open the form.

**Comment by seadowg** [comment]
@dbemke Should the title and description read "**without** a specified instance ID"?

**Comment by dbemke** [comment]
> Should the title and description read "**without** a specified instance ID"?

:) oooppsss thanks. I'll correct it.

**Comment by seadowg** [comment]
@grzesiek2010 this doesn't look like we need a fix out as a hotfix right? Seems ok to go into v2024.3.
