### ISSUE TITLE
Empty select in the card distribution form after sending registration form (offline entities enabled)

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6304]
#### ODK Collect version
the master version 1f2e2a6c979a095ac86ec53b445836b63e3a5849
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
If a voter registration form is filled and sent (with offline entities enabled), in the card distribution form the added voter's name isn't shown (empty select). 
![missingNames](https://github.com/user-attachments/assets/8abd63c9-2631-40b7-a9be-61d7a20c0b59)
If I refresh the list of blank forms, the voter's name appear.
#### Steps to reproduce the problem
1. Download a project with the voter registration and the card distribution forms.
(I used forms from https://staging.getodk.cloud/#/projects/65)
2. Enable offline entities in experimental settings.
3. Fill in and send the voter registration form.
4. (Don’t refresh the list of blank forms) Open the card distribution forms and check selects.

**Comment by seadowg** [comment]
@dbemke if you do refresh the form list does everything then work as expected?

**Comment by dbemke** [comment]
> if you do refresh the form list does everything then work as expected?

yes

**Comment by seadowg** [comment]
This looks like it's strange interactions between the filtered select and the implementation of `LocalEntitiesFilterStrategy`.
