### ISSUE TITLE
Difference in updating a form/forms with offline entities enabled and disabled

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6309]
#### ODK Collect version
the master version 1f2e2a6c979a095ac86ec53b445836b63e3a5849
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There are different results when a user updates an entity in a project with different forms using the dataset of the entity with offline entities enabled and disabled.
Manually downloading the update of the form with offline entities enabled results in updating all entities in all follow-up and update forms.
Manually downloading the update of the form with offline entities disabled results in updating only the downloaded/updated form.

I don't know what is the expected result but the difference might be confusing because the user gets different results while being offline or online.
#### Steps to reproduce the problem
Preconditions:
- Offline entities enabled
- Set manual update mode
- In a project there is update follow-up and different update forms using the same dataset (I used forms with trees dataset follow-up and update forms from https://staging.getodk.cloud/#/projects/65)
Steps:
1. Update one of entities in an update form and send it.
2. Go to Download form and select the filled update form to download.
3. Go to Start new form and check in which form entities got updated

Result: The updated entity is in all forms (although one was downloaded/updated)

Preconditions:
- Offline entities disabled
- Set manual update mode
- In a project there is update follow-up and different update forms
Steps:
1. Update one of entities in an update form and send it.
2. Go to Download form and select the filled update form to download.
3. Go to Start new form and check in which form entities got updated

Result: The updated entity is only in 1 form

**Comment by seadowg** [comment]
This is working as expected as far as I can tell. I'm pretty sure we'll remove the local entities setting when we actually release, but for right now forms should exactly as they would if using a normal secondary instance (rather than an entity list) - updating the media files for one form would never affect the media files for another (even if they have the same name or technically the same thing). @dbemke does that makes sense?

**Comment by dbemke** [comment]
> This is working as expected as far as I can tell. I'm pretty sure we'll remove the local entities setting when we actually release, but for right now forms should exactly as they would if using a normal secondary instance (rather than an entity list) - updating the media files for one form would never affect the media files for another (even if they have the same name or technically the same thing). @dbemke does that makes sense?

Yes. I wasn't sure how it should work and what's going to change. We'll keep the steps to reproduce in a doc and verify how it works in the future (just to remember where differences might be).
