### ISSUE TITLE
Only newest version of update form has updated entities

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6310]
#### ODK Collect version
the master version 1f2e2a6c979a095ac86ec53b445836b63e3a5849
#### Android version
10, 14

#### Device used
Redmi 7, Galaxy M23
#### Problem description
After refreshing list of blank forms, only newest version of update form has updated entities.
It occurs only when local entities are disabled, when local entities are enabled both forms have updated entities after refreshing list of blank forms
#### Steps to reproduce the problem
Preconditions:
- Local entities disabled
- Hide old form version setting disabled
- Project with trees registration form and 2 versions of update form
[trees_registration.xlsx](https://github.com/user-attachments/files/16511011/trees_registration.xlsx)
[trees_update.xlsx](https://github.com/user-attachments/files/16511017/trees_update.xlsx)

1. Go to trees registration form 
2. Fill form and send it
3. Wait a bit
4. Refresh list of blank forms
5. Open both trees update forms

**Comment by seadowg** [comment]
Interesting! This makes sense as far as I can tell. If local entities are disabled, we use the form's CSV entity list which won't get updated for older (than the newest local) version of the form. We don't plan to change that behaviour.

@lognaturel please correct me if I'm thinking incorrectly here!
