### ISSUE TITLE
Investigate the need to translate months in non-Gregorian calendars

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#6316]
#### Problem description
We support several non-Gregorian calendars, such as `Coptic`, `Bikram Sambat`, and `Ethiopian`, among others. The month names in these calendars are currently translatable. I'm unsure if this was intentional or an oversight, but I encountered it while working on [this issue](https://github.com/getodk/collect/pull/6294) and started reflecting on it further in [this discussion](https://github.com/getodk/collect/pull/6294#discussion_r1696661120).

I believe we should display the original month names in these calendars and avoid translating them, as doing so seems contrary to the purpose of supporting non-Gregorian calendars.

**Comment by grzesiek2010** [comment]
I'm closing as after discussing this with @lognaturel translating seems to be needed.

**Comment by lognaturel** [comment]
For context - some calendars are used in multiple languages. For example, the Ethiopian calendar is used in Amharic and Tigrinya. The Buddhist calendar we’re adding now is used primarily in Thai but also in Vietnamese and a few other Southeast Asian languages. In an ideal world we might be able to do something like indicate which languages it’s relevant to translate into. But it’s not a big deal if languages that certain calendars aren’t used in have poor translations.
