### ISSUE TITLE
Crash on opening the map (to select an entity) after finalizing a registration form and going to follow-up form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6336]
#### ODK Collect version
the master version 3669ada1310c97d2f8112eb6439205ae2442c65e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
If a registration form is finalized and after that in a follow-up form the map to select an entity is opened, there's a crash.
![followUPRegCrash](https://github.com/user-attachments/assets/f8788755-ee4b-46fa-8c66-58df0a1bf944)

#### Steps to reproduce the problem
1. Download a project with Trees registration form (containing entities) and Trees follow-up form.
2. Go to the Trees registration form and finalize/send a new entity.
3. Go to the Trees follow-up form and tap "Select place".

**Comment by WKobus** [comment]
Issue still occurs on master version cff7a1e9e2c535099db878ac90798b9425c80e3d

**Comment by seadowg** [comment]
Ah it looks like there was a fix made in JavaRosa, but we never updated Collect. I'll get that sorted.
