### ISSUE TITLE
Unable to download a changed file in draft testing

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6343]
#### ODK Collect version
the store version 2024.2.1, the master version fb83e3d238d6a880683f1575cf783b6173adf473
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
In draft testing changing a media file doesn't result in changing the file in the form after redownloading the form (e.g. via refreshing the list of blank forms).
#### Steps to reproduce the problem
1. Create a draft version of a form with media (upload the media) on Central.
[mediaTest.zip](https://github.com/user-attachments/files/16610530/mediaTest.zip)
2. Scan the draft testing QR code in Collect.
3. Change one of the media attachments (the same name of a file but different content) on Central.
![a](https://github.com/user-attachments/assets/8fa19509-456c-42d6-9962-5f8aa423be9d)
4. Refresh the list of blank forms in Collect.
5. Open the form and check the changed media file.
#### Expected behavior
Refreshing the list of blank forms for draft testing should result in downloading the changed media files.

**Comment by seadowg** [comment]
@lognaturel is this an expected quirk of Central drafts?

**Comment by lognaturel** [comment]
This didn't ring any kinds of bells when it was first filed, sorry! I filed it again at https://github.com/getodk/collect/issues/6419
