### ISSUE TITLE
SQlite syntax error- crash after refreshing list of blank forms containg entity form with property with "."

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6344]
#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
I think Collect crashes after trying to insert entity properties with "." to the DB.
![sqlitesyntaxerror](https://github.com/user-attachments/assets/71a15e34-7be0-40a9-9090-adf9ef29f724)

#### Steps to reproduce the problem
1. Upload the Basic update form (I used Basic update form in user "SQlite crash properties” https://staging.getodk.cloud/#/projects/20/app-users).
2. Scan the user code to Collect (the form appears in the list of blank forms).
3. Refresh the list of blank forms.

**Comment by lognaturel** [comment]
Would be good to check table name with . as well

**Comment by dbemke** [comment]
SQlite syntax error- crash after inserting an entity property with a hyphen

#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Collect crashes after trying to insert a property with a hyphen.
![hyphen](https://github.com/user-attachments/assets/5574cca1-3f43-44e9-91bc-e803b0db9769)


Afterwards even if I remove the property (so none of the forms uses the property), uninstall Collect and try to use the form the crash still appears.

#### Steps to reproduce the problem
1. Create a project with forms using a dataset with a property with a hyphen.
[test_registration(1).xlsx](https://github.com/user-attachments/files/16727885/test_registration.1.xlsx)
[Test.update.xlsx](https://github.com/user-attachments/files/16727886/Test.update.xlsx)


2. Download the forms to Collect.
3. Refresh the list of blank forms
