### ISSUE TITLE
Remove grey background on "Ready to send" screen

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6347]
As part of [#6320](https://github.com/getodk/collect/pull/6320#issuecomment-2289205679), we want remove the grey banner for "Form last sent" to be consistent with the new styling. Without the app bar elevation / shadow it looks disconnected.  

![Screenshot 2024-08-19 at 4 31 25 PM](https://github.com/user-attachments/assets/c1031a7a-015d-479a-b6b6-d14eea76bfb6)

**Comment by lognaturel** [comment]
Did you try it as a card by any chance?

**Comment by alyblenkin** [comment]
@lognaturel Yes, I did try it in a card! It's in the [figma link ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=6237-113970&t=MwrOsNQxXCrSHC2j-1). I was a little hesitant about it last week, but it's not so bad looking at it again.

**Comment by lognaturel** [comment]
I don't have a strong feeling either way, it's helpful to see both. It feels like my eyes know where to settle a bit more easily with the card but it's not a big difference.

**Comment by alyblenkin** [comment]
I think it does anchor the page a bit more! Let's go with the card and we can always drop it if it doesn't' work well with the new app bar.
