### ISSUE TITLE
Should all date widgets translate the date to the language which is set in Collect?

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6361]
#### ODK Collect version
the store version 2024.2.3, the master version 30f759c4afb6ddabafc6b00ee7f7bbe62ed262cd
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Should all calendars (date widgets) translate the date (month) to the language which is set in Collect (when in the device a different language is set)?
- Spanish is set both in the device and in Collect
![spanichInDevice](https://github.com/user-attachments/assets/06d29574-1520-47f4-b07e-8b4d875d05c1)

- English in the device, Spanish in Collect
![spanishInCOllect](https://github.com/user-attachments/assets/bf3300ab-005f-4259-b076-9544f1787cf4)

#### Steps to reproduce the problem
1. In the the device set English as a language.
2. In Collect set Spanish.
3. Go to All widgets form to date widgets

**Comment by lognaturel** [comment]
Most of these calendars only apply in a small set of languages. That means it doesn't really matter what translations there are for the month names in the other languages. In general we recommend that translators just copy over the original text. You can read more at https://github.com/getodk/collect/issues/6316#issuecomment-2289770380

**Comment by grzesiek2010** [comment]
I think the question was more about the part that displays the gregorian date. @dbemke correct me if I'm wrong. (21 Aug 2024) is displayed instead of (21 ago. 2024) if in Collect we use Spanish but English is set in the device.

**Comment by dbemke** [comment]
> (21 Aug 2024) is displayed instead of (21 ago. 2024) if in Collect we use Spanish but English is set in the device.

yes

**Comment by seadowg** [comment]
So the issue here is that Collect uses the system language instead of its own setting for date widgets?

**Comment by grzesiek2010** [comment]
> So the issue here is that Collect uses the system language instead of its own setting for date widgets?

Yes, at least for those non-gregorian ones. This is a similar issue https://github.com/getodk/collect/issues/6256.

**Comment by seadowg** [comment]
> This is a similar issue https://github.com/getodk/collect/issues/6256.

Ah, it's probably the same thing. @dbemke could you combine the details from here into #5256 and then close this please?
