### ISSUE TITLE
End page buttons not aligned properly on older devices in RTL

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6362]
#### ODK Collect version
the store version 2024.2.3, the master version 30f759c4afb6ddabafc6b00ee7f7bbe62ed262cd
#### Android version
10, 11, 8.1
#### Device used
Redmi 9T, Galaxy M12, Nexus 5X
#### Problem description
When RTL language is set in Collect the "Save as draft" and "Finalize/Send" buttons  at the end page of a form are aligned to the right (part of the "Save as draft" button is cut).
![saveAsDRaftButtonRtl](https://github.com/user-attachments/assets/53f1682e-0439-4cbc-827c-be73702631e3)
The issue doesn't occur on Pixel 7a (Android 14).
1. Set an RTL language in Collect.
2. Go to e.g. All widgets form to the end page.
#### Expected behavior
Whole buttons should be visible on all devices.

**Comment by lognaturel** [comment]
@karntrehan will take a look!

**Comment by grzesiek2010** [comment]
We agreed that if it isn’t done by Thursday, we should take over to ensure it’s included in v2024.3. I’ll take a look at it.

**Comment by karntrehan** [comment]
@grzesiek2010 I see that you have raised a PR for this already. Should I still look into this? What is pending?

**Comment by grzesiek2010** [comment]
> @grzesiek2010 I see that you have raised a PR for this already. Should I still look into this? What is pending?

No, as mentioned above, we aimed to complete it earlier that's why I took over, and it's now done and awaiting testing. Thanks!
