### ISSUE TITLE
Text in questions with audio gets highlighted (blue) when the audio is being played

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6368]
#### ODK Collect version
the store version 2024.2.4, the master version 61cd7bcda8e7f914e854b89f96e7ab12855b662d
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Text in question with audio gets highlighted (blue) when the audio is being played
![textBlue](https://github.com/user-attachments/assets/91a35686-6454-4862-8ee5-d6d7a2fcce2c)

#### Steps to reproduce the problem
1. Go to the mediaTestRequired form.
[mediaTestRequired.xlsx](https://github.com/user-attachments/files/16709972/mediaTestRequired.xlsx)
[a.mp3.txt](https://github.com/user-attachments/files/16709986/a.mp3.txt)

2. Go to questions with audio.
3. Play the audio.
##### Expected behavior
The text shouldn't change color.

**Comment by grzesiek2010** [comment]
That's a feature :smile: isn't it? Did I unblock it maybe in https://github.com/getodk/collect/pull/6332?

**Comment by dbemke** [comment]
> That's a feature 😄 isn't it? Did I unblock it maybe in #6332?

Yes. Feature :) ;) It was the same on the store version and the master so it wasn't introduced in the PR. It doesn't need to be required question.

**Comment by grzesiek2010** [comment]
> It doesn't need to be required question.

Right any question label should be highlighted when its audio is being played. So can we close the issue or I'm missing something maybe?
