### ISSUE TITLE
Enabling Firebase Crash Logs

### ISSUE THREAD

**Issue by nikhilbalyan** [getodk/collect#637]
#### Problem description
Right now we are not using any service for collecting the crash reports of the application.

#### Expected behavior
We should integrate the Firebase crash with the application so that we can collect the crashing report of the application.
#### Other information 

I would love to work on this issue and have a fruitful discussion about how i will be implementing this awesome feature in Collect.

**Comment by lognaturel** [comment]
Sounds good, @nikhilbalyan. Can you please start with a PR that only adds the dependency and then we can talk in #663 about the best way to do the actual logging?

**Comment by nribeka** [comment]
How about another person start acra with their acralyzer 🤣

**Comment by nikhilbalyan** [comment]
@lognaturel done
