### ISSUE TITLE
SQlite syntax error- crash after inserting an entity property with a hyphen

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6371]
#### ODK Collect version
the master version aa10b3be9a88f20ae76f69a28bfff62aaa43d08e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Collect crashes after trying to insert a property with a hyphen.
![hyphen](https://github.com/user-attachments/assets/80fadebb-e3de-4190-8780-b9821c03ef09)

Afterwards even if I remove the property (so none of the forms uses the property), uninstall Collect and try to use the form the crash still appears.

#### Steps to reproduce the problem
1. Create a project with forms using a dataset with a property with a hyphen.
[test_registration.xlsx](https://github.com/user-attachments/files/16726847/test_registration.xlsx)
[Test update.xlsx](https://github.com/user-attachments/files/16726849/Test.update.xlsx)

2. Download the forms to Collect.
3. Refresh the list of lank forms
#### Expected behavior
Collect shouldn't crash

**Comment by seadowg** [comment]
@dbemke could you combine this with #6344 please?
