### ISSUE TITLE
Not possible to delete sent instances of form that create or update entity

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6380]
#### ODK Collect version
the master version 9493502a0051b2a81038cc2f4c8c1736da8ef8fb
#### Android version
10,14 
#### Device used
Redmi 7, Galaxy M23
#### Problem description
Sent instances of forms that create or update entity do not show up in delete forms - saved form, due to this it is not possible to delete them.
#### Steps to reproduce the problem
1. Open trees registration form
[trees_registration.xml.txt](https://github.com/user-attachments/files/16993861/trees_registration.xml.txt)

2. Fill form and send it
3. Go to delete form - saved forms
#### Expected behavior
Sent instances of form that create or update entity should show up in delete forms - saved forms and it should be possible to delete them

**Comment by seadowg** [comment]
@lognaturel we're ok deleting instances after they've been sent right? I don't see that being a problem.

**Comment by lognaturel** [comment]
Yes, exactly. We don't want to delete them before because then the local and remote Entity representations will definitely be out of sync but once submissions have been received remotely it's fine to delete them locally.
