### ISSUE TITLE
Remove Implicit Intent From VideoWidget

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#639]
The video widget calls an implicit intent when the video can be easily played in the app itself using a video view.
Moreover, this is inconsistent with the image view widget in which the image is loaded without any implicit intents.

**Comment by lognaturel** [comment]
This was an explicit decision made because users wanted choices and this allowed for a better experience on certain phones. Perhaps it's time to move to an embedded player but we need to talk about this. @yanokwa @nribeka

**Comment by yanokwa** [comment]
When we started Collect, a lot of functionality was done via Intents and that decision has sort of stuck. 

I do not think a lot of people have a wide range of video players that they need to choose from. I do think jumping in and out of the app isn't as elegant as doing the work inline. And given that this change falls back nicely to the old system, I think it's fine.

If folks come back and demand using an external video player, then we can make that a setting.

@rajatthakur If you find other examples of external functionality that could be internalized (audio rec/play and video rec come to mind), can you file those as issues?

**Comment by nribeka** [comment]
I like the approach that it will fallback to using intent if the MediaPlayer can't handle it. If you could test or look around if there are limitations for the built in MediaPlayer and document it, I think it would be really helpful (maybe limitation in terms of size of the file, supported formats, etc).

I'm hoping with this information coupled with usage information, we could decide whether the Intent should be the default behavior and add a setting to allow internal player, or the other way around.

**Comment by shobhitagarwal1612** [comment]
Intents are one of Android’s key components. It’s a way of passing data between different parts of the app or, even better, different apps on the system.

Let’s say you have a gallery app that can share a download link to some images via SMS. Which of the two options seems more logical?

Option 1:
Request the SEND_SMS permission.

  <uses-permission android:name="android.permission.SEND_SMS" />
Write your own code for sending SMS using the SmsManager.
Explain to your users why your gallery app needs access to services that can cost money, and why they have to grant this permission to use your app.


Option 2:
Start an SMS Intent and let an app designed for SMS do the work

  Intent sendIntent = new Intent(Intent.ACTION_VIEW);
  sendIntent.setData(Uri.parse("sms:" + telephoneNumber));
  sendIntent.putExtra("sms_body", x);
  startActivity(sendIntent);

Unless there is a good reason to make a custom implementation (ex., a camera that applies filters), always use Intents for these scenarios. It will save you a lot of programming time, and strip the AndroidManifest.xml of unnecessary permissions.

**Comment by yanokwa** [comment]
@shobhitagarwal1612 I agree with you, but I think video/audio/pictures are different. I mean when I browse Twitter, I don't have to use intents to open video/audio/pictures, right? Because, it'd be super annoying.

And in this case, it's about the same amount of code. We are using the native media player and not building a new one.

**Comment by lognaturel** [comment]
Sounds good to me, I'll review the pull request shortly!

**Comment by rajatthakur** [comment]
Hi @yanokwa, 
I have already created an issue (#641) for the audio widget and have made a pull request (#643) for the same.
Thank You

**Comment by lognaturel** [comment]
Issue can be re-opened if a user asks about this. The big challenge is that video can be captured in different sizes and orientations and handling that with a good user experience is not straightforward.
