### ISSUE TITLE
Entity is not getting updated on central after finalizing two update forms for same entity and then sending new update form first.

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6392]
#### ODK Collect version
the master version 365128c01edf5aaf815b90821ba0d9840fbf4420

#### Android version
10, 14 
#### Device used
Redmi 7, Galaxy M23
#### Problem description
Entity is not getting updated on central after finalizing two update forms for same entity and then sending new update form first.
#### Steps to reproduce the problem
1. Scan project with update and registration form e.g. project "test" from https://staging.getodk.cloud/#/projects/98/app-users
2. Fill trees registration form and send it
3. Open trees update form
4. Update previously created entity and finalize form
5. Open trees update form again
6. Update previously updated entity and finalize form
7. Go to ready to send 
8. Send update form from step 6.
9. Go to central entities tab
#### Expected behavior
Entity should be updated on central after finalizing two update forms for same entity and then sending new update form first.

**Comment by WKobus** [comment]
I've checked this issue in entity forms with defined trunkVersion and branchId, I used cacti forms (project "cactus" from https://staging.getodk.cloud/#/projects/103/app-users) and issue still occurs with new forms.

**Comment by seadowg** [comment]
@WKobus you're only sending the second update right? If so, this is expected behaviour: Central know there's a missing submission (the first update). If you send that first one, you'll see Central works everything out after a couple of minutes.

@lognaturel worth double-checking my thinking here.

**Comment by lognaturel** [comment]
Yes, that sounds exactly right, @seadowg! What happens if you send the submission from step 4, @WKobus? Like @seadowg said, both should be processed soon after.

If you never send the one from step 4, the one from step 6 should be force processed after 5 days (and I'll update that setting so it's within 2 days instead while you're testing).

If you send the one from step 4 after force-processing, that should be marked as a conflict.

**Comment by seadowg** [comment]
> Yes, that sounds exactly right, @seadowg! What happens if you send the submission from step 4, @WKobus? Like @seadowg said, both should be processed soon after.

I'll close this as I saw this myself, but definitely let us know if that's not what you see @WKobus.

**Comment by WKobus** [comment]
Yeah, I see same behavior, @lognaturel  after sending form from step 6. and then sending form from step 4. entity from 6. step form appear in central.
