### ISSUE TITLE
Updating the first entity in a list of selects results in empty list of selects+ the updated entity in draft

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6409]
#### ODK Collect version
the master version d0dfddadb038567394cefcf874fabc4b08bdcf5c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that updating the first entity in a list of selects results in empty list of selects+ the updated entity in drafts. I'm not able to reproduce it with entities that aren't first in the list.
![firstEntUpdateDraft](https://github.com/user-attachments/assets/572740b8-4c9b-4979-99f8-323b001956d5)

#### Steps to reproduce the problem
1. Download a project with an update form which contains at least 2 entities ( you can use cacti or colors user in https://staging.getodk.cloud/#/projects/101/app-users)
2. Go to the update form (cactus monitoring or color update).
3. Select the first entity in the list (at the top)
4. Update the entity and save the form as draft.
5. Go to "Drafts" and open the form.
6. From the hierarchy view go to the first question (selects).
(additional)7. Select an empty entity and swipe to the next question.
![choosingEmpty](https://github.com/user-attachments/assets/071378d1-fb3b-4462-85af-04457e68ccae)
 
#### Expected behavior
All entities should be shown in drafts

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified cases:**
- the issue doesn't occur 
- entity forms

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14, 15
