### ISSUE TITLE
Offline layers not displayed correctly with Mapbox

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6420]
https://forum.getodk.org/t/map-widget-behaviour-draw-order-with-google-adjusting-vertices-on-not-mapbox-mapbox-stroke-width/48758/6?u=ln

**Comment by lognaturel** [comment]
Maybe related to #6401

**Comment by seadowg** [comment]
> Maybe related to https://github.com/getodk/collect/issues/6401

Agreed! I'll close this and add the forum link to that issue.
