### ISSUE TITLE
Performance on forms with different expressions

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6422]
#### ODK Collect version
the master version 66e9c1f10f707b803654bc57f7930b805edf2742
#### Android version
10,14
#### Device used
Redmi 7, Galaxy M23
#### Problem description
Forms with different expressions, for example:

- city=${city} and age=${age}
- age < 18
- starts-with(${fname}, ${start})

Are much slower during filtering or opening draft / finalized form.
On my Android 14 device - Galaxy M23, regular 100k entity filter form filtering and opening draft / finalized form takes about 0.5 second, but on forms with expressions filtering takes ~5 seconds and opening draft / finalized form takes ~7 seconds
#### Steps to reproduce the problem
1. Scan project "perf" from https://staging.getodk.cloud/#/projects/103/app-users
2. Go to start new form
3. Open Entities 100k and expression form
4. In first question type "7" and swipe to the next question
5. In second question type "7" and swipe to the next question
6. Save form as draft
7. Go to drafts and open previously saved form
8. Compare performance to 100k Entity filter form
9. Repeat steps 1-8 excluding step 5. for 100k entities >< expression form and 100k entities starts with expression form

**Comment by seadowg** [comment]
My guess would be that for the slower queries, v2024.2.4 (the store version) will be faster when filtering, but slower when loading the form than current `master`. Additionally, I'd guess that the second time you filter it'll be faster on `master`. Could you check if that's the case @WKobus?

My assumption is that the we've basically moved some expensive "work" (loading the instance into memory) from form load to the first filter on that instance.

**Comment by WKobus** [comment]
I've checked loading times using Galaxy M23 phone on "Entities 100k and expression" form and you're right, performance on store version and master version is different in places, that you mentioned in comment, those are results:

**Master version**
- Loading form - ~0.5s
- Filtering - ~6.5s
- Filtering second time - ~1.5s
- Loading draft/finalized form - ~6s

**Store version**
- Loading form - ~5s
- Filtering - ~3s
- Filtering second time - ~0.5s
- Loading draft/finalized form - ~8.5s

**Comment by seadowg** [comment]
Thanks @WKobus! @lognaturel this looks ok to me. Happy for to close?

**Comment by lognaturel** [comment]
That makes sense, thanks for digging deeper!
