### ISSUE TITLE
Visible gray screen and progress bar after playing sound in questions

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6431]
#### ODK Collect version
the master version 2d8bafd63d30a9aad6c196511b3455aa8ad2c172
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There's a change in questions with audio. When a user plays the sound in select or a question, the progress bar is visible a bit longer and the screen gets a bit grayed out. I compared it with the store version and this also occurs but it happens really quickly so the user doesn't notice it. Now it's visible - takes more time.

https://github.com/user-attachments/assets/b6b882e4-9c98-4068-ba78-7036ef312614

#### Steps to reproduce the problem
1. Open  mediatest form (from in user "selects" https://test.getodk.cloud/#/projects/385/app-users).
2. Tap the sound button.
#### Expected behavior
After playing sound in a question, a user shouldn't notice that the screen gets greyed out.

**Comment by seadowg** [comment]
@dbemke can you test this several times in both versions to confirm that loading is **always** significantly slower on the newer version. There's many variables that would affect the time taken (Play Store builds may have optimised code available that will make the app faster for example) and unless we're seeing seconds of difference, I don't think it's worth looking into.

**Comment by dbemke** [comment]
> Can you test this several times in both versions to confirm that loading is **always** significantly slower on the newer version

I checked the self signed released 2024.2.1 and it was also faster, but it seems that the issue was fixed somewhere between the master version from the issue and the current master cff7a1e9e2c535099db878ac90798b9425c80e3d cause I just reproduced the steps on Android 10 and 14 (on the current master) and it is as fast as it was on the store version - it seems ok now.
