### ISSUE TITLE
Loading images got slower

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6433]
#### ODK Collect version
the master version 2d8bafd63d30a9aad6c196511b3455aa8ad2c172
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Loading images got slower. The videos below show the master version and the store version on Android 10.

https://github.com/user-attachments/assets/17b3f7ff-f1f5-47a8-bd9f-c3d5e5ca7d88

https://github.com/user-attachments/assets/1a900f64-d0ad-4b7a-8ada-e3f4c6f5d5cb

#### Steps to reproduce the problem
1. Scan QR user "selects" in https://test.getodk.cloud/#/projects/385/app-users.
2. Open the mediatest form.
#### Expected behavior
I don't know if it's currently expected but it feels that now the user can notice that the images are loading.

**Comment by WKobus** [comment]
Loading image after taking picture in image widget also takes longer than on store version

**Steps to reproduce** 
1. Open all question types form
2. Go to image widget
3. Tap on Take Picture button
4. Take photo and tap OK

**Comment by lognaturel** [comment]
I think this is closely linked to https://github.com/getodk/collect/issues/6434
