### ISSUE TITLE
Crash of the app after trying to attach ~17MB image in Image widget

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6434]
#### ODK Collect version
the master version ce00913a7cd87d3f5b2472e834ac6a9974d1906c
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Crash of the app after trying to attach ~17MB image in Image widget
![carshImage](https://github.com/user-attachments/assets/317ffdb3-5c3f-4d8c-9ed2-782924c20f6a)

The issue doesn’t occur in the store version 2024.2.4
#### Steps to reproduce the problem
1. Go to All question types form to image widget.
2. Tap "Choose image" and attach an image (image 1.jpg 17MB in https://drive.google.com/drive/u/1/folders/1IeuxQZU8Sw90PAOnTRlMToB3Wp_LuCoN)
#### Expected behavior
The app shouldn't crash.

**Comment by lognaturel** [comment]
That makes sense as a side effect of https://github.com/getodk/collect/pull/6417

@grzesiek2010 maybe we can scale down once a certain size threshold is reached, otherwise maintain original size?
