### ISSUE TITLE
If a repeat has no label, improve the add repeat dialog text

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6439]
- Replace "Do not add" with "Cancel"
- Use title font for prompt text, otherwise keep the prompt text the same (quotes and question mark)
- If repeat has no label (label is null), use special text "Add another?" instead of using `null`

https://forum.getodk.org/t/repeat-groups-add-null-repeat-dialogue-and-remove-repeat/49836

**Comment by karntrehan** [comment]
Hie @lognaturel, is this a good-first-issue? I would love to contribute some fixes to collect but currently the list for good first issues seems to be very limited: [good first issue](https://github.com/getodk/collect/labels/good%20first%20issue).

Do let me know how I can contribute.

**Comment by lognaturel** [comment]
Thanks for your interest, @karntrehan! Yes, this should be a straightforward one to take on.

@alyblenkin what do you think of changing the text in the case of a repeat without a label from "Add "null"?" to "Add another?" and changing the "Do not add" button to "Cancel" for now?

**Comment by alyblenkin** [comment]
Welcome @karntrehan!

@lognaturel - "Add another" and "Cancel" makes a lot more sense here! For the option to remove a repeat, it would be strange to remove from tapping on the add action, so we may need to come back to that.

I don't think the support text helps too much here, but I played around with that just to see.

![Screenshot 2024-10-10 at 1 53 03 PM](https://github.com/user-attachments/assets/9a9431f4-246c-4290-b63c-3aa8d6b8bdd1)

**Comment by lognaturel** [comment]
> it would be strange to remove from tapping on the add action, so we may need to come back to that.

Agreed!

The common case is going to be something like Add "Person" or Add "sick dog" or something like that if the form creator has specified a label for the repeat. I think we should leave that alone and only add a new case for when the label is null. Given that, do you think we should increase the font size and make the question into more of a title as you have in the mockups? The length of the label is unknown. For example it could be Add "country representative who is responsible for local healthcare decisions".

Agreed we don't need two lines of text.

**Comment by alyblenkin** [comment]
> Given that, do you think we should increase the font size and make the question into more of a title as you have in the mockups? The length of the label is unknown. For example it could be Add "country representative who is responsible for local healthcare decisions".

Yes, I thought about longer titles. I wish we had a limit for labels to make it easier to read, but this is much larger piece of work, and not the actual pain point here :) 

Despite the fact that in some cases titles can be lengthy, I still think we should use the title font size because it creates a stronger hierarchy of information. Here is what it would look like with your example, which is very long/not ideal, but I think better than using the body text, which seems too small for a prompt. What do you think?

![Screenshot 2024-10-10 at 2 28 36 PM](https://github.com/user-attachments/assets/fa7a9ce0-f5ed-4dd9-a868-5937f256ec73)

**Comment by lognaturel** [comment]
Sounds good to me! I have updated the issue description.

**Comment by karntrehan** [comment]
I guess the code powering this flow is here:https://github.com/getodk/collect/blob/63050fdd265c42f3c340f0ada5cdff3c52a883bc/collect_app/src/main/java/org/odk/collect/android/formentry/repeats/AddRepeatDialog.java#L30

I will also need to update the tests here: https://github.com/getodk/collect/blob/63050fdd265c42f3c340f0ada5cdff3c52a883bc/collect_app/src/androidTest/java/org/odk/collect/android/support/pages/AddNewRepeatDialog.java#L30

I have asked the OP for a sample form to test my fix [here](https://forum.getodk.org/t/repeat-groups-add-null-repeat-dialogue-and-remove-repeat/49836/3?u=karntrehan). @lognaturel would be great if you could help with that as well, else I can try creating the form at my end.

**Comment by karntrehan** [comment]
Folks the PR has been raised. Here: https://github.com/getodk/collect/pull/6459

I have also fixed a few readme issues.
