### ISSUE TITLE
SQLite Crash in the application during refreshing list of forms with entities with old spec

### ISSUE THREAD

**Issue by srujner** [getodk/collect#6444]
ODK Collect version

the older master version 2024.3.0 Beta 0, the newest master version cff7a1e9e2c535099db878ac90798b9425c80e3d

**Android version**
13

**Device used**
Pixel 6a

**Problem description**
During testing #6311 I spend some time checking different behaviors with resetting the settings after updating Collect from older to newer version and crash occurs to me in two different ways. 

**Steps to reproduce the first problem**

1.  Install the older master version e.g. : 
[OLD Master before 6311.zip](https://github.com/user-attachments/files/17306074/OLD.Master.before.6311.zip)
2. Scan the QR code with project from Central including (Movie entities and Movies update (new spec) forms) 
![Screenshot(210)](https://github.com/user-attachments/assets/e0382754-aa3e-44d3-a90c-f609a42b8b30)
3. Navigate to the Start new form
4. Refresh the list of forms -> Crash will occur
![crash1](https://github.com/user-attachments/assets/f9457e5d-4e93-4a01-bfb8-c196a10b6d2e)

**Steps to reproduce the second problem**

1. Repeat the steps 1-3 from the issue above
2. Create a draft for Movie Entities form
3. Update ODK Collect with new master e.g 
[New master.zip](https://github.com/user-attachments/files/17306157/New.master.zip)
4. Navigate to the Settings -> Project Management -> Reset
5. Reset Saved forms and entities and Form load cache
6. Go to Start new form and click on the refresh -> Crash will occur
![crash2](https://github.com/user-attachments/assets/9d72dd50-6983-4313-8a0b-c4f791d1f596)

**Expected behavior**

Probably the app should not crash

**Comment by seadowg** [comment]
@srujner the first problem is a big that's now fixed that would still be present in that version of Collect (https://github.com/getodk/collect/issues/6344) as far as I can tell. For the second issue, is the version you're upgrading from v2024.3.0 Beta 0 or is it a `master` version from around then?

**Comment by srujner** [comment]
@seadowg For the second issue, it was a master around that, in the app it is 2024.3.0 Beta 0, 193-gb3383dcd6f, 
but I couldn't find the exact master version to match with this one

**Comment by seadowg** [comment]
> @seadowg For the second issue, it was a master around that, in the app it is 2024.3.0 Beta 0, 193-gb3383dcd6f,
but I couldn't find the exact master version to match with this one

Right! Could you try reproducing with the actual released version? We made a lot of changes that I wouldn't expect to support upgrading between PRs, but we should be able to upgrade from the actual released versions.

**Comment by srujner** [comment]
@seadowg Sorry I didn't write back sooner, but I didn't notice your reply. 

I checked the version 2024.2.x -> The list of forms did not download at all

Then I checked 2024.3.0 Beta 2, 3 and Beta 5 -> And I was not able to reproduce the issue

**Comment by seadowg** [comment]
> I checked the version 2024.2.x -> The list of forms did not download at all

Maybe I'm missing something, but that seems worrying right?

**Comment by srujner** [comment]
> > I checked the version 2024.2.x -> The list of forms did not download at all
> 
> Maybe I'm missing something, but that seems worrying right?

Forms in that project have the new spec already, probably that's the case. Shouldn't it work like that?

**Comment by seadowg** [comment]
Ah so they're rejected because Collect doesn't recognise the entity spec version? Just want to check we're definitely on the same page about what's happening here!

**Comment by srujner** [comment]
Yes, 99% it is that, because there is no similar issue with forms with older spec
