### ISSUE TITLE
Missing form map in All widgets/ All question type in "Start new form".

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6450]
#### ODK Collect version
the master version 63050fdd265c42f3c340f0ada5cdff3c52a883bc
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Missing form map in All widgets/ All question type in "Start new form".
The form map appears with other forms.
![FormMap](https://github.com/user-attachments/assets/65d880de-ab44-4b35-90ec-1011191ec63b)

#### Steps to reproduce the problem
1. Go to the demo project and download forms.
2. Go to "Start new form” and check if there is the form map for All question types form.
#### Expected behavior
The form map should appear.

**Comment by karntrehan** [comment]
@grzesiek2010 can I pick this up?

**Comment by lognaturel** [comment]
Good catch! Thanks for your interest, @karntrehan. This is in code that @grzesiek2010 touched recently and is needed for the release we're preparing for so it makes sense for him to get it done.
