### ISSUE TITLE
Entity with missing label

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6453]
#### ODK Collect version
the store version 2024.2.4, the master version 63050fdd265c42f3c340f0ada5cdff3c52a883bc
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
 If I create (offline) and send an entity with empty values, the entity appears in update/follow-up forms in the device. In Central the entity won’t get created because of the missing values in label.
 
![emptyLabel](https://github.com/user-attachments/assets/9c9939dc-0c9e-4a63-9d80-c417679776f5)

#### Steps to reproduce the problem
1. Scan the QR user "movies” https://staging.getodk.cloud/#/projects/101/app-users
2. Go to Movie entities form, don’t fill anything, send the form.
3. Refresh the list to f blank forms.
4. Go to Movies update form and check the list of entities.
5. Check the state of the entity on Central.

**Comment by seadowg** [comment]
@lognaturel I'm not sure I agree that [the spec](https://getodk.github.io/xforms-spec/entities) states that an entity must have a label? My reading is that a form must have a `label` node, but not that it has to be non blank.

**Comment by lognaturel** [comment]
The intent is for it to be required to be non-blank! We can clarify the spec language.

I do think that Collect should fail to create the Entity as well for consistency. This is the kind of failure that would be nice to log one day and maybe even present some UI around but I think that for now failing silently would be fine. I also think it's not a huge deal if we leave it like this for a release or two -- it's unlikely to be a common case. Once we introduce the integrity URL piece any extra local Entities will be cleared out.
