### ISSUE TITLE
Pulldata treats ".” and  "_” as the same symbol in entity properties

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6461]
#### ODK Collect version
the master version 5dad7f4dfd4f4952a9516d959b3ed10c33ca33b0
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It seems that pulldata treats ".” and  "_” as the same symbol in properties. Opening an entities update form (using pulldata) with properties "circumference_cm” and "circumference.cm” causes an error.
![errorPulldata](https://github.com/user-attachments/assets/bfdbfb47-6370-4a92-b8cd-353da03d12c2)

#### Steps to reproduce the problem
1. Create a project with trees registration form with properties "circumference_cm” and "circumference.cm”, trees update pulldata form or use user "one” in https://staging.getodk.cloud/#/projects/101/app-users
[trees_update_pulldata.xlsx.txt](https://github.com/user-attachments/files/17410170/trees_update_pulldata.xlsx.txt)
2. Download the project and open trees update pulldata form.
#### Expected behavior
I'm not sure what's the expected behavior (e.g. OData also converts some punctuation marks to "_") but maybe in Collect it shouldn't ?

**Comment by lognaturel** [comment]
I believe that in the short term https://github.com/getodk/collect/pull/6451 will address this. Maybe you can check it again when merged?

**Comment by dbemke** [comment]
> I believe that in the short term #6451 will address this. Maybe you can check it again when merged?

I checked it and in #6451 the issue occurs.

**Comment by lognaturel** [comment]
I think that may mean that the pulldata database is still being built in addition to the entities database even though it's not used. I'm somewhat surprised by this so we should probably see what's going on.

**Comment by lognaturel** [comment]
Closing in favor of the more general #6471
