### ISSUE TITLE
RTL issue with buttons on end of form send/finalize screen

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6479]
https://forum.getodk.org/t/ui-button-layout-misalignment-with-rtl-languages/50436/2

**Comment by lognaturel** [comment]
@karntrehan this should be a straightforward issue that would be valuable to get fixed if you're interested!

**Comment by karntrehan** [comment]
Would love to pick this up @lognaturel. Thank you for thinking of me. 

A few questions: 
1. Should we flip the icons or not? 
2. Should we center align text always? Irrespective or LTR to RTL?

**Comment by lognaturel** [comment]
Let's not change the icon flipping as part of the issue. Yes, the text should always be center aligned.

@dbemke mentioned this was already filed at https://github.com/getodk/collect/issues/6362! Closing in favor of that one. Do note that it doesn't happen on every device. If it doesn't look like an easy fix, let's talk about what to do.

**Comment by tiritea** [comment]
> Do note that it doesn't happen on every device. 

Guess I got 'lucky', huh? ... :-)

FWIW, this was on a Samsung Galaxy A12 running Android 12/API 31
