### ISSUE TITLE
Entity form opening and match exactly blocked after opening finalized entity form in ready to send

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6485]
#### ODK Collect version
the master version 2e63b33407128e7e17ca46241683945dd749c48f
#### Android version
15, 10 
#### Device used
Pixel 6a, Redmi 7

#### Problem description
Finalizing entity form and opening it in ready to send blocks entity form opening and match exactly.
#### Steps to reproduce the problem
1. Scan user "Cactus" from project https://staging.getodk.cloud/#/projects/103
2. Go to start new form
3. Open Cactus Registration form, fill it and finalize
4. Go to ready to send, open previously finalized form and close it
5. Go to start new form and open Cactus registration form again

#### Expected behavior
Finalizing entity form and opening it in ready to send should not block entity form opening and match exactly.

**Comment by lognaturel** [comment]
Great catch!! Did not think of this at all.
