### ISSUE TITLE
Entity property "_id" crashes the app after refreshing the list of blank forms

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6486]
#### ODK Collect version
the master version c7c4719561d269f65a7b9644c1084336ec033414
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Refreshing the list of blank forms with a form (update or follow-up) using a dataset with a property "_id” crashes the app.
![idproperty](https://github.com/user-attachments/assets/2505c4b2-0ea2-4e99-b89f-a47d943c54ea)

#### Steps to reproduce the problem
1. Download Collect.
2. Scan "trees” QR code https://test.getodk.cloud/#/projects/575/app-users
3. Go to "Start new form” and tap the arrow to download forms.
#### Expected behavior
The app shouldn't crash.

**Comment by lognaturel** [comment]
😬😬😬 Oh yes, that is definitely a problem. `_id` is required to use ContentProviders and other Android features.

We could possibly release this and see how common it is in Crashlytics. We should probably give another round of thought to how we go from CSV column name to db column names.

**Comment by dbemke** [comment]
If a user adds "_id" property, it isn't possible to download forms using that dataset (they don't appear in "Start new form") to Collect. Additionally, it isn't possible to remove the property on Central so the user needs to create a new project (add forms without the property).

**Comment by seadowg** [comment]
I think we can probably fix this by using a prefix for property columns in the entities DB (like `prop_<property>`). That should protect us from clashes.

**Comment by lognaturel** [comment]
That would be wise. @seadowg and I briefly chatted about this and I realized that there's also a conflict potential with `version` which is very likely to come up.
