### ISSUE TITLE
Removal of Deprecate Methods from whole project

### ISSUE THREAD

**Issue by nikhilbalyan** [getodk/collect#649]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Right now we have a lot of Deprecated methods in  the whole of project i am creating this issue so that all of them can be referenced at a single place
#### Steps to reproduce the problem
Like inside the DecimalWidgetClass we have deprecated methods
#### Expected behavior
Replace all the deprecated methods with latest programming guidelines
#### Other information 
Above issue can be fixed by
http://stackoverflow.com/questions/11947603/setbackground-vs-setbackgrounddrawable-android

I would love to work on this issue. @lognaturel

**Comment by lognaturel** [comment]
As you have seen with some of the other issues filed, we prefer to manage each deprecation type separately. That allows for easier verification of correctness and making sure that each solution chosen is the best possible one. If you'd like to help us with that, please file an issue for a specific deprecation and your proposal to address it. Thanks!
