### ISSUE TITLE
Crash processing Entity List when there are Entity properties with names that are identical except for case

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6501]
#### ODK Collect version
the master version 90d41ae9a7b0af8d2fddd87cb198dcb233473627
#### Android version
15, 10
#### Device used
Pixel 6a, Redmi 7
#### Problem description
App crashes after refreshing blank forms when there is "P_" entity property.
<img src="https://github.com/user-attachments/assets/0ccac982-e545-46f8-9b52-9939ef56451b" height="700">

#### Steps to reproduce the problem
1. Scan user "Cactus" from project https://staging.getodk.cloud/#/projects/103/app-users
2. Go to start new form
3. Refresh list of blank forms
#### Expected behavior
App should not crash after refreshing blank forms

**Comment by lognaturel** [comment]
Whoops! I think we should fix this but it could be in a point release.

**Comment by lognaturel** [comment]
Having discussed briefly with @seadowg, it now feels like it could be a deeper issue and deserves more of a look now.
