### ISSUE TITLE
Dates saved to offline Entity properties have the wrong format when used in XPath expressions

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6510]
#### ODK Collect version
v2024.1.0 beta 8

#### Problem description
When an offline update is made to an Entity and this update represents a date, the date is converted to DD/MM/YY HH:MM format instead of remaining in ISO 8601 format. This means that any expressions trying to use that date crashes. This is a local-only issue: once the Entity is updated on the server and synced back to the device, everything works as expected.

#### Steps to reproduce the problem
1. Create a form that saves a date to an Entity property and then later uses that date such as [this one](https://docs.google.com/spreadsheets/d/1_VsrftvmLgvuldUFtz2C1uxuUVSrMKRK8pKdZBZvNHw/edit?gid=1068911091#gid=1068911091)
2. Make sure that there is the `offline` column on the entities sheet and that its value is set to `yes`
3. Fill out and finalize a submission
4. Open the form again and see the crash
5. Open the Entities browser and the property has been incorrectly re-formated
![Screenshot_20241114_154559](https://github.com/user-attachments/assets/1dc4f34a-ecc7-44b3-82e4-227b13424b2d)

#### Expected behavior
Entity properties should always be treated as opaque strings. They should be saved and retrieved exactly as entered into the form.

#### Other information 

Something along the way is detecting a date and reformatting it. I don't think it's sqlite because I'm pretty sure sqlite stores dates in iso8601 format.

**Comment by grzesiek2010** [comment]
@lognaturel 
this issue is about properties but we can also save dates as labels for example so in those other cases it shouldn't be formated as well right?

> Open the form again and see the crash

Could you tell something more about this crash? I haven't experienced it at least using my forms: https://github.com/getodk/collect/pull/6514
Are you sure it is connected?

**Comment by lognaturel** [comment]
Yes, same with labels which are system-known properties. 

Your fix looks right to me. Were you able to reproduce the crash with the form I linked to? The issue is that there’s a format-date call on the property value that was saved so if that is not formatted correctly the function throws an exception.

**Comment by grzesiek2010** [comment]
> Were you able to reproduce the crash with the form I linked to?

I couldn’t use your form at all. When I added it to Central and tried to open it, I encountered this error:
![image](https://github.com/user-attachments/assets/220919e4-8a45-4157-b1b1-e043966daec8)

I needed a smaller form for testing anyway, so I built my own and didn’t investigate what’s wrong with yours.

**Comment by lognaturel** [comment]
Did you put any values in the Entity List? You should be able to use the values in the facilities sheet to download a CSV and populate `facilities`. See https://forum.getodk.org/t/restrict-duplicate-entries-submission-from-same-facility/47927/8?u=ln

**Comment by grzesiek2010** [comment]
I did... it looks like the csv is not marked as an entity file during downloading from Central:
![image](https://github.com/user-attachments/assets/a46ec142-56d0-462d-894f-73eb0e6b02f9)

It is late maybe I'm doing something wrong or there is a bug somewhere.

**Comment by lognaturel** [comment]
Very interesting! I think that might happen when the Entity List is empty. Maybe when you're ready to look at it again with fresh eyes you can add some facilities to the list. The form isn't expected to work with no facilities specified.

**Comment by grzesiek2010** [comment]
It is not empty:
![image](https://github.com/user-attachments/assets/455af0eb-7de3-4572-b769-721a0ad3fe96)

**Comment by lognaturel** [comment]
Intriguing! Ok, I'll look into it a bit as well and let you know if I see anything interesting.

**Comment by lognaturel** [comment]
We figured this out -- the Entity List wasn't attached to the form because a static CSV was. Now it's crashing as expected. 🎉
