### ISSUE TITLE
 Entity registration form with concat(${circumference}  ${species}) in the label field

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6532]
#### ODK Collect version
the store version 2024.3.2,the master version f0ce2a68fd6cbbf797890359980879bc0b45344e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
It's possible to fill an entity registration form with concat(${circumference}  ${species}) in the label field - the offline entity isn't created, In Central there's information "missing label"
[trees_registration.5.xlsx.txt](https://github.com/user-attachments/files/17922646/trees_registration.5.xlsx.txt)

#### Steps to reproduce the problem
1. Download user "concat”
https://staging.getodk.cloud/#/projects/101/app-users
2. Set auto send to "off”
3. Fill and finalize the trees registration form.
4. Go to update and check if the entity is in the list.
5. Send the registration form.
6. Check if the entity was created in Central.

**Comment by seadowg** [comment]
As far as I can see this is actually valid. The XLSForm expression `concat(${circumference} ${species})` ends up being `concat( /data/circumference    /data/species )` once it's compiled to XPath and that's equivalent to `concat(/data/circumference/data/species)`. You should be able to this by example by evaluating `$x("/html /body")` in the dev tools for whatever browser you're using.

This case is pretty much the worst case for this mistake as `concat` accepts any number of args (including a 1 arg case node sets which this hits). I wouldn't want to add any warnings or above spec strictness to Collect here, but I reckon it might make sense to add a warning/error to XLSForm (`pyxform`)?

**Comment by lognaturel** [comment]
Ah, perfect, thank you, that makes total sense.

I think it's such a specific and unlikely case that we can leave it unless we hear about users hitting it.
