### ISSUE TITLE
Entity registration form with concat(${circumference}, "cm", ${species}) in label does not create entity

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6541]
#### ODK Collect version
the store version v2024.3.2, the master version 069a192c765a6c927e285ccc7f489f1feee94c0d
#### Android version
10, 15
#### Device used
Redmi 7, Pixel 6a
#### Problem description
Entity registration form with concat(${circumference}, "cm", ${species}) in label does not create offline or online entity, there was similar issue with entities not being created due to concat - #6532 , however in this case I think concat looks more like real case scenario that can be used by users.
#### Steps to reproduce the problem
1.Scan user "tree" from project https://staging.getodk.cloud/#/projects/123/app-users
2. Go to start new form 
3. Open Trees registration form, fill it and send
4. Open Trees update form to check if entity is there
#### Expected behavior
Entity should be successfuly created

**Comment by lognaturel** [comment]
Here's a submission showing this issue: https://staging.getodk.cloud/#/projects/123/forms/trees_registration/submissions/uuid%3A311a49a4-0072-4a0d-9918-f42e364d7fe2

There's no value for `label`: https://staging.getodk.cloud/v1/projects/123/forms/trees_registration/submissions/uuid%3A311a49a4-0072-4a0d-9918-f42e364d7fe2.xml

In the form definition, I see 
`            <bind nodeset="/data/meta/entity/label" calculate="concat( /data/circumference , &quot;cm&quot;,  /data/species )" type="string" readonly="true()"/>`

I've verified that both `circumference` and `species` are required. I don't currently understand how it's possible for `label` to be blank.

**Comment by lognaturel** [comment]
Ahh, the form version for that submission is `2022110901lkjhg`. That form definition has the following binding for `/data/meta/entity/label`:

`            <bind nodeset="/data/meta/entity/label" calculate="concat( /data/circumference    /data/species )" type="string" readonly="true()"/>`

That's exactly the same form design issue as in https://github.com/getodk/collect/issues/6532

Maybe this is more common than I think. I'll keep thinking about whether it's worth putting a warning in pyxform and what that wording could look like.

I also think Central could/should provide better messaging around form version used. Right now it shows the initial submission form version even when an edit has been made. It could also highlight that an old form version was used.
