### ISSUE TITLE
Run lint/unit tests in CI on release builds

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#656]
Currently, we run lint and unit tests against debug builds. This is because developers are generally generating debug builds. On the CI server, we currently test against debug, but it might be a better idea to test against release.

**Comment by lognaturel** [comment]
@grzesiek2010, @seadowg this seems worth doing? I think the advantage is that the build would go through all the same transformation as for release. I believe this issue was filed after we had some build issues that only showed up for release.

**Comment by seadowg** [comment]
I don't see any harm in doing it! I haven't seen us run into any of these kinds of issues personally but if there's no blocker to doing it I say we go for it.

**Comment by yanokwa** [comment]
It might be time to take this on. It's no fun to catch issues when doing a release.

**Comment by seadowg** [comment]
I've put up a [PR](#4835) that adds a release build to CI. That's enough to catch the errors we've run into on the last few releases.

**Comment by seadowg** [comment]
It feels like the above change (and moving QA to a minified build) has helped us a lot with any cracks we were seeing that this might have fixed. Closing this.
