### ISSUE TITLE
Adding Timber for logging instead of Log class

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#663]
Timber is a logger with a small, extensible API which provides utility on top of Android's normal Log class. http://jakewharton.github.io/timber/

Pros :

- Development - Logging to logcat
- Production - Crash reporting to Crashlytics 

Timber and Crashlytics can be used along with AppCrashHandler which elegently handles unhandled exceptions by restarting the app instead of showing the system dialogs displaying an error has occurred.
Read the article here [link](https://www.slideshare.net/Infinum/infinum-android-talks-15-timber-crashlytics-a-match-made-in-heaven)

@yanokwa @lognaturel @nribeka Any thoughts?

**Comment by lognaturel** [comment]
I'd be in favor of this. As a first pass, I think we should use Firebase Crash Reporting for production as proposed in #637 since it integrates well with Firebase Analytics. That should be an easy decision to revisit if needed since `Tree`s can easily be swapped out.

**Comment by lognaturel** [comment]
(Also, this is merely speculation, but I wouldn't be surprised if Crashlytics was abandoned in favor of Firebase Analytics now that Google acquired Fabric.)

**Comment by shobhitagarwal1612** [comment]
I'm in favour of using Fabric. I have used it before and it provides much better support and analysis as compared to firebase analytics

**Comment by nribeka** [comment]
Yeah, that one will be gone. You know how google does stuff. Buy the company and absorb ("kill") the product 🤣

**Comment by lognaturel** [comment]
@shobhitagarwal1612 You're going to have to say a little more to convince us!

**Comment by shobhitagarwal1612** [comment]
Although I have a concern. We have seen earlier that GCM was merged with FCM and later the support for GCM is slowly being removed. Since Google now owns Fabric and already has Firebase Analytics. Will the fate of firebase analytics be the same? Are they going to be merged in the coming months? Any thoughts?

**Comment by shobhitagarwal1612** [comment]
Found an article saying 
> Google acquires Twitter’s Fabric mobile app dev tools, will be integrated into Firebase

I think it's better to use Firebase instead of Fabric since all of the best features of both are going to be merged into Firebase eventually.

**Comment by lognaturel** [comment]
Closed in #821
