### ISSUE TITLE
AudioButton should become a stop button when audio is playing

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#665]
Android v6.0.1, device used: OnePlus One

When you press the audiobutton to play the respective audio, the button should become a stop button, because sometimes there may be audio which is long and it isn't necessary to listen to the whole audio file.

Steps to reproduce problem:
Go to any form(e.g. Birds). Play any audio sound of a bird's cry. 

@lognaturel What are your suggestions on this?Can I go ahead with this?

**Comment by lognaturel** [comment]
That's a good idea @pratikmjoshi. I think you'll want to wait until #643 is fixed and merged.

**Comment by pratikmjoshi** [comment]
@lognaturel Can I move ahead with this issue? May I know the progress of issue #643?

**Comment by lognaturel** [comment]
@pratikmjoshi I'm sorry, I must have gotten confused, those aren't really related! Yes, please go ahead.

**Comment by Ishmeetsingh97** [comment]
Hi, @pratikmjoshi Are you still working on it ? 
I would like to solve this one.

**Comment by pratikmjoshi** [comment]
@Ishmeetsingh97 Yeah, I'm still working on it. I was waiting for a confirmation.
