### ISSUE TITLE
clone() does not declare CloneNotSupportedException

### ISSUE THREAD

**Issue by gmn0105** [getodk/collect#668]
#### Software and hardware versions 
Collect v1.4.16, Android v6.0.1, device used...One plus one
#### Problem description
In the Entry class, clone() method does not declare CloneNotSupportedException
#### Steps to reproduce the problem
Need to declare the CloneNotSupportedException
#### Expected behavior
Exception will be taken care of if thrown at any point

I'll send a minor pr for this fix
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
This is code in an external library that is included.
