### ISSUE TITLE
Static members accessed via instance reference

### ISSUE THREAD

**Issue by gmn0105** [getodk/collect#673]
#### Software and hardware versions 
Collect v1.4.16, Android v6.0.1, device used... One plus 1

#### Problem description
Few static variables in different classes have been accessed via instance reference.
As a static variable is always associated with a class it should be accessed via class reference
#### Steps to reproduce the problem
Access the static variables via class reference
And make the variables non-static wherever necessary.
I'll be sending a pr for this issue

**Comment by shobhitagarwal1612** [comment]
Fixed by #674
