### ISSUE TITLE
In Grid Widget, orange frame doesn't disappear for deselected icons

### ISSUE THREAD

**Issue by pratikmjoshi** [getodk/collect#678]
#### Software and hardware versions 
Android v6.0.1, device used: OnePlus One

Steps to reproduce problem:
1. Go to a form containing Grid Widget( e.g. New Widgets). 
2. Select an icon, and try to tap it again for deselection.
3. The orange frame around deselected icon doesn't disappear.

This issue occurs in single selection grid widget as well as multi-selection grid widget.

Expected behaviour:
The orange outline around the icon should disappear.

I'll send a PR for this.

**Comment by lognaturel** [comment]
The intent for the single grid widget was that it duplicate the functionality of radio buttons which are not deselected on second tap. Any field can be cleared by long pressing on it. @yanokwa @nribeka  do you think this functionality should be added?

**Comment by pratikmjoshi** [comment]
@lognaturel Sorry about that, didn't verify its functionality. However, the single selection grid widget would then need a check condition(toast) if the user accidentally selects more than one icon, which is not there(which is why I was unsure). On top of that, when long pressing and clearing the response, the orange frame around selected icons does not disappear, even thought field is cleared, which is an error.

My input on this functionality is that I feel it would be confusing for people to use. I myself have never encountered a radio button with field clearing using long press. I feel that it would be better for users to be able to deselect by tapping on the icon in multi-select grid widget and just be able to select another icon to change their field value.

**Comment by lognaturel** [comment]
It turns out there were a ton of bugs related to these widgets. #679 fixed some of the bugs did not change the behavior of tapping on a selected grid item to unselect it. Is this something we'd like to do?

**Comment by lognaturel** [comment]
I think we should consider this fixed. With #679 and #785, the behavior is as I would expect it.

Thanks again for reporting @pratikmjoshi and I apologize for having trouble initially understanding what the issue was about! I'm surprised there were so many problems with these widgets. But now they're fixed! 🎉
