### ISSUE TITLE
crash while getting forms form drive.

### ISSUE THREAD

**Issue by getsanjeev** [getodk/collect#680]
#### Software and hardware versions 
Collect v1.4.16, sdk 19 device used Huawei Honor Holly

#### Problem description
Application crashes when in General settings  -
Platform = Google Drive, Google Sheets
Configure platform settings = 
1. Google account = any account
2. Google Sheets URL  = blank

Go to GET BLANK FORM in MAIN MENU.
Click on My drive.
Application crashes.

#### Steps to reproduce the problem
make settings as above.

#### Expected behavior
Application should not crash, rather request user to make appropriate settings.

**Comment by getsanjeev** [comment]
It would be helpful, if someone reproduces the issue and suggests.

**Comment by pratikmjoshi** [comment]
@getsanjeev Did you follow the instructions from [here](https://github.com/opendatakit/collect#using-apis-for-local-development) ?

**Comment by getsanjeev** [comment]
@pratikmjoshi Thanks.
