### ISSUE TITLE
Choosing the set of Colors available in the annotation widget.

### ISSUE THREAD

**Issue by supreme96** [getodk/collect#682]
@lognaturel  @nribeka As discussed in #286, it is required to decide upon a set of colors that will be available in the Annotation widget in collect as an attempt to simplify and make the existing annotation widget more easier to use on mobile devices and other devices with smaller screen size.

Some of the basic colors that would be available should include : 
- White (#FFFFFF)
- Black (#000000)
- Red (#FF0000)
- Green (#008000)
- Blue (#0000FF)

( These colors are just a suggestion right now and more suggestions for additions to this set are invited )

**Comment by pratikmjoshi** [comment]
@supreme96 I think you should include a few mixed colors(from rgb). I would suggest 3 more: Orange(#FB8C00),Yellow( #FFEB3B), and Pink(#EC407A)

**Comment by lognaturel** [comment]
@supreme96 Do you have a sense of what you'd like the color picker interface to look like? I think that might help give you a sense of how many colors to include.

**Comment by supreme96** [comment]
@lognaturel Yeah, i do have a layout in mind. Will post some sketches for consideration in the evening.

**Comment by supreme96** [comment]
@lognaturel here's a sketch of a possible color picker interface -
![interface mk1](https://cloud.githubusercontent.com/assets/15019358/24247112/57382698-0ff0-11e7-8908-fb65f256e3e7.jpg)

PS: i couldn't get the image to upload in landscape orientation. Would appreciate if someone could tell me hw to do it :)

**Comment by lognaturel** [comment]
Some great ideas here. Closing in favor of #1907 since the conversation has now moved there.
