### ISSUE TITLE
Instrumentation test failing

### ISSUE THREAD

**Issue by harshitdiwedi03** [getodk/collect#683]
I tries running tests under `androidTest` directory but getting following error.
`Started running tests`
`Test running failed: Instrumentation run failed due to 'Process crashed.'`
`Empty test suite.`

Can anyone provide the possible fix for this?

**Comment by pkarira** [comment]
@yadav-rahul I think you can address this .

**Comment by yadav-rahul** [comment]
@harshitdiwedi03 I tried running all tests under androidTest directory and they all are working as usual. I think there might be some problem in setting up your environment.

**Comment by yanokwa** [comment]
I am also not having this problem. And neither is CirceCI. I am closing this issue until @harshitdiwedi03 can provide a step-by-step so we can reproduce.
