### ISSUE TITLE
Adding support for AppCompatActivity

### ISSUE THREAD

**Issue by Ishmeetsingh97** [getodk/collect#702]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
For the time being the activities don't support AppCompatActivity.
Benefits of using AppCompatActivity :
It not only provide backwards compatibility to our app but also provides us the access to the Material Design Library too. After this we can easily add FloatingActionButtons, Snackbars, AlertDialogBoxes and other material design widgets easily which now we can't.
#### Steps to reproduce the problem
No particular problem but deprecated classes used.
#### Expected behavior
New material design library to enhance the ui and design of the application.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
I would like to work on this.

**Comment by lognaturel** [comment]
Please review existing issues before filing new ones.
