### ISSUE TITLE
'_' used as an identifier

### ISSUE THREAD

**Issue by Ishmeetsingh97** [getodk/collect#703]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
After compling the application a lot of warning messages appear due to the use of this '_', Which is not supported in JAVA SE 8

Here the complete warning 
```
'_' used as an identifier
(use of '_' as an identifier might not be supported in releases after Java SE 8)
```
#### Steps to reproduce the problem
Just after compling the application on Android Studio must warning of such type occur.
#### Expected behavior
No warning should appears after using the new paradigm.
#### Other information 
I would like to work on it.

**Comment by lognaturel** [comment]
This is an issue that will need to be fixed in the JavaRosa library.
