### ISSUE TITLE
Many static variables are used using the context of the activity.

### ISSUE THREAD

**Issue by Ishmeetsingh97** [getodk/collect#704]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
After compling the application a lot of warning appear which point to many static variable which are called using the context the of activity which is not required and is an very old approach.

#### Steps to reproduce the problem
Compling the application and obversing the logs.
Complete warning looks like this 
```
Warning:(304, 62) [static] static variable should be qualified by type name, LocationManager, instead of by an expression
```
#### Expected behavior
No such warnings should appear.
#### Other information 
I'd like to work on it.

**Comment by lognaturel** [comment]
Please review existing issues before filing yours.
