### ISSUE TITLE
Can't run in API 16 emulator (maybe caused by upgrade to Android Studio 2.3?)

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#706]
#### Software and hardware versions 
Collect v1.4.16-113-g3f707159, Android 4.1.2, Nexus 5 emulator

#### Problem description
When launching Collect from master on an API 16 emulator, the error "Collect cannot access the SD card. Perhaps it is mounted via USB? (Current state: removed)". <strike>I have verified that there is an sdcard.</strike> AVD manager says that there is an SD card mounted but other applications can't find it either. This same emulator used to work until recently<strike> so there is a code change that caused this</strike> but I have verified that it occurs even with code that used to work so it's almost certainly not a code change that caused it.

@nribeka and @yanokwa have had the same experience.

Since API 16 is our `minSdkVersion`, it would be good to be able to emulate it.

**Comment by yadav-rahul** [comment]
@ln I tried on Samsung galaxy core running on Android version `4.1.2` and it is working fine. :)

**Comment by lognaturel** [comment]
That's great news! What version of Google Play Services do you have installed?

**Comment by yadav-rahul** [comment]
It is using version `10.2.98`.

**Comment by lognaturel** [comment]
Thanks so much, @yadav-rahul. It seems more likely that #707 is the root cause of the problem I'm experiencing, then.

**Comment by lognaturel** [comment]
Thanks to @nribeka and @yanokwa for trying out API 16 emulators. I tried the same emulator with 1.4.16 production which I previously ran in API 16 without trouble so I now think this has nothing to do with our code. Yay. It's still something that would be good to figure out because we do need to verify functionality in API 16.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Works for me too. Tried running it on API 16 emulator with old play services and no play services, worked fine in both the cases.

**Comment by yanokwa** [comment]
@shobhitagarwal1612 What version of Android Studio are you running?

**Comment by yanokwa** [comment]
This is a problem with the upstream tools. You can follow the issue at https://code.google.com/p/android/issues/detail?id=240155.

If you are working on ODK Collect for personal use, then you can try https://www.genymotion.com/fun-zone

**Comment by lognaturel** [comment]
Thank you, I was looking for something like that! Glad it's not our code.

@shobhitagarwal1612 out of curiosity, do you use an alternate emulator?

**Comment by shobhitagarwal1612** [comment]
@yanokwa I use the latest build of Android Studio 2.3 (linux). 
@lognaturel I used the emulators provided by the Android Studio sdk. Earlier(2 - 3 months ago), I also used `genymotion` as it's fast but since the release of `Android Studio 2.0`, the emulators of Android Studio work great as well.

**Comment by lognaturel** [comment]
Got it, thanks @shobhitagarwal1612, seems pretty clear it's a Mac + Android 2.3 problem.
