### ISSUE TITLE
Redundant TypeCasts exist in Project

### ISSUE THREAD

**Issue by shreyasnbhat** [getodk/collect#708]
#### Software and hardware versions 
Collect v1.4.16, Android v7.1.1, OnePlus 2

#### Problem description
Many redundant typecasts still exists in the codebase.

#### Expected behavior
Needs to be removed.

I'll send a PR.

**Comment by lognaturel** [comment]
Please look at existing issues before filing your own.

**Comment by shreyasnbhat** [comment]
@lognaturel Extremely Sorry about this. Would take of this in the future.
