### ISSUE TITLE
Bad submission_url causes crash on submission

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#709]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
Form with bad submission url crashes Collect on submission.

```
AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
AndroidRuntime: Process: org.odk.collect.android, PID: 3533
AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Host name may not be null
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.util.Args.containsNoBlanks(Args.java:81)
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.HttpHost.<init>(HttpHost.java:80)
AndroidRuntime: 	at org.opendatakit.httpclientandroidlib.HttpHost.<init>(HttpHost.java:135)
AndroidRuntime: 	at org.odk.collect.android.utilities.WebUtils.enablePreemptiveBasicAuth(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.uploadOneSubmission(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.doInBackground(
AndroidRuntime: 	at org.odk.collect.android.tasks.InstanceUploaderTask.doInBackground(
AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AndroidRuntime: 	... 3 more
ActivityManager:   Force finishing activity es.InstanceUploaderActivity
ActivityManager:   Force finishing activity org.odk.collect.android/.activities.InstanceUploaderList
```

#### Steps to reproduce the problem
Create a form with a bad URL (e.g., `https:/server.com` instead of `https://server.com`). Fill out form and submit. To reproduce, try these forms:
* [bug.xlsx](https://github.com/opendatakit/collect/files/853365/bug.xlsx)
* [bug.xml.txt](https://github.com/opendatakit/collect/files/853366/bug.xml.txt)

If you'd like to make your own forms, for XLSForm (put a `submission_url` header with the value below in the `settings` sheet). For XForm, 
```
<model>
  <submission action="https:/server.com/submission" method="form-data-post"/>
  <instance>
```

#### Expected behavior
Users should be alerted as soon as possible when the submission URL is bad. 

#### Proposed fix
One potential fix is that `DiskSyncTask.java` should check the submission url and make sure it's valid. Validity should match to what we do when saving server preferences (see #175 for more). If a URL is valid, great. If it's not, then it should alert the user and rename it to `form.xml.bad` (or just delete it).

**Comment by pratikmjoshi** [comment]
@yanokwa I'll work on this if its fine with you.

**Comment by yanokwa** [comment]
Hi @pratikmjoshi! Please give it a try.

**Comment by pratikmjoshi** [comment]
@yanokwa I was planning to use Apache's urlValidator class to check for bad url. Is this a good way to go?

**Comment by shobhitagarwal1612** [comment]
The app doesn't crash anymore on submission with bad url
