### ISSUE TITLE
Save per-screen sorting options 

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#718]
I think each screen that has the option to sorting forms, should persist that choice. And the selection slide out screen should have a different color (I like #2196F3) for the sort order that is selected.

**Comment by getsanjeev** [comment]
@yanokwa you mean that in the slider, the current selected option (By name or By date or other) should be in different color? Have not understood well.

**Comment by pratikmjoshi** [comment]
@yanokwa Can I work on this?

**Comment by yanokwa** [comment]
@getsanjeev You are correct. The text color of the selected option should be 2196F3 (or whatever).

@pratikmjoshi Let's let @grzesiek2010 take this one since he's more familiar with that code base.
