### ISSUE TITLE
Resize scanning UI to fit text

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#720]
If you have a form that is invalid (e.g., invalid XML), the error message that shows up in `Fill Blank Form` or `Get Blank Form` takes up two rows, when it should take up one row. This is likely because there is an extra newline.

![screen shot 2017-03-20 at 18 22 15](https://cloud.githubusercontent.com/assets/32369/24124457/3082bab6-0d9a-11e7-82ba-614a408037b5.png)

![screen shot 2017-03-20 at 17 47 17](https://cloud.githubusercontent.com/assets/32369/24124463/3622e1b2-0d9a-11e7-925c-0ffcb75c416e.png)

**Comment by rijuldhir** [comment]
Can i work on this ?

**Comment by shobhitagarwal1612** [comment]
This is fixed in #725.
