### ISSUE TITLE
adding toast message asking to press back again to exit

### ISSUE THREAD

**Issue by pranavgupta1234** [getodk/collect#723]
#### Software and hardware versions 
Android Lollipop 5.0.2 (API Level 21)

#### Problem description
Clicking on back button directly forces the app on background
#### Steps to reproduce the problem
Click android physical back button to close the app

#### Expected behavior
A toast message with asking user to press back again to exit toast is generated 
#### Other information 
Use a handler with postdelayed for some specific time interval

**Comment by pranavgupta1234** [comment]
I would love to work on this issue :)

**Comment by faizmalkani** [comment]
I'd suggest not implementing this behavior, since it's considered terrible user experience. If the user presses back, let them leave, don't add another press.

http://www.androiddesignpatterns.com/2012/08/exit-application-dialogs-are-evil-dont.html

**Comment by grzesiek2010** [comment]
I also think it's not a good pattern.

**Comment by lognaturel** [comment]
Thank you, @pranavgupta1234 for sharing your suggestions. This is not a feature that will increase the usability of the app so we would prefer not to include it.
