### ISSUE TITLE
Add ability to duplicate edited or finalized forms

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#727]
> Hello everyone, I wanted to ask if there is a way to copy saved forms which I can find under "Edit Saved Form" inside ODK Collect app on my phone? Why would I want to do that? Sometimes you need to fill in a couple of very similar forms.
> 
> It would be great if instead of running through the similar process, again and again, I could fill in one form, save it, copy it, then edit necessary fields and sent as a new submission. I think adding simple copy form functionality inside "Edit Saved Form" tab would dramatically improve an already great ODK.
– From rrespondek@gmail.com

**Comment by rijuldhir** [comment]
I can try this with a bit of help @yanokwa

**Comment by pratikmjoshi** [comment]
@yanokwa I think the problem with this is classifying which fields are the same and which aren't, for example, a string field asking for a name could mean first, middle or last name. This can make copying cumbersome. I think one improvement for a future release can be that ODK Collect can create an account for a user, with his/her name, address, contact details, stored as account details. This way, all basic details will be pre-entered into a form. However, this will require work from the Briefcase side as well(There should specifically be a name widget, address widget, and contact details widget).

Edit: Oh, I didn't notice that this discussion is ongoing in issue #311

**Comment by yanokwa** [comment]
@pratikmjoshi I don't think that's what the user wants (also, that functionality exists and is being improved at #311). I think they want to take an arbitrary form and duplicate it.

@rijuldhir Can you describe how this will look in the user interface so it's intuitive to users? Filled forms also have unique instanceIDs, how will you generate those?

**Comment by nribeka** [comment]
Why can't this just be a complete copy pasta of the db record and the instance xml @yanokwa? I think we probably just need to do that right? And then the user can adjust the values of separate instances as needed?

**Comment by yanokwa** [comment]
No copy pasta on this one, @nribeka. I think we want to treat this like a new instance (so new timestamped filepath and new instance ID) created at the time you hit duplicate, but with the exact data inside. One gotcha is what to do with multimedia. We can copy it over, but then it's the same name as the original. That could cause problems in downstream tools.

**Comment by shobhitagarwal1612** [comment]
> No copy pasta on this one, @nribeka. I think we want to treat this like a new instance (so new timestamped filepath and new instance ID) created at the time you hit duplicate, but with the exact data inside. One gotcha is what to do with multimedia. We can copy it over, but then it's the same name as the original. That could cause problems in downstream tools.


We can append timestamp to the filename. 
`eg. sample-image-20170323-014415.jpg`

**Comment by nribeka** [comment]
I looked at the naming scheme for the media file and it seems to be using currentTimeMillis().

I mean it's a copy pasta but still you need to follow the naming convention for the instances, media etc. Not a complete copy pasta, but copy pasta nonetheless I think 🤣 

I say spike on this and iterate over it.

**Comment by lognaturel** [comment]
@rafres posted #818, let's keep the conversation going there.
