### ISSUE TITLE
Let color of empty lists be set by the operating system

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#728]
In the current builds of Collect, the empty screen (`Nothing available to display`) screen that shows up on list views (e.g., on Edit Saved Form and every other form list activity) are white (#ffffff). They should be light gray (#ededed).

This difference in coloring is likely because the gray color is set by the OS while the white color is set by the application. This is related to Issue #514. 

<img width="602" alt="screen shot 2017-03-21 at 17 26 31" src="https://cloud.githubusercontent.com/assets/32369/24171604/8cf54554-0e5b-11e7-9c43-20a21633c13d.png">

**Comment by pranavgupta1234** [comment]
I would love to work on this issue :)
