### ISSUE TITLE
Add blank line between results in all result dialogs

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#730]
**Download multiple files from Google Drive**
<img width="418" alt="screen shot 2017-03-21 at 20 52 01" src="https://cloud.githubusercontent.com/assets/32369/24177603/0010bd34-0e7a-11e7-98b7-6cf4b5ebd5fe.png">

**Reset application from Admin Settings**
<img width="412" alt="screen shot 2017-03-21 at 21 05 19" src="https://cloud.githubusercontent.com/assets/32369/24177620/1a78c4dc-0e7a-11e7-8d88-887ebad55260.png">

I'm not sure where else this happens, but it'd be good to standardize on adding spaces.

**Comment by shobhitagarwal1612** [comment]
@yanokwa This issue is fixed in #465.

**Comment by lognaturel** [comment]
@yanokwa I don't really understand what you're asking for! Those are strings with newlines between each result. Are you saying you would like to have `\n\n` instead of `\n`?

**Comment by yanokwa** [comment]
`\n\n` is what I'm expecting. I think when you download forms, it uses `\n\n` so some consistency would be nice.

**Comment by lognaturel** [comment]
Ah, got it, thanks. I guess adding an additional newline is good because there can sometimes be wrapping:
<img width="231" alt="screen shot 2017-04-11 at 2 22 43 pm" src="https://cloud.githubusercontent.com/assets/967540/24931505/6234ccaa-1ec2-11e7-8125-e80ac38b7c12.png">

**Comment by nribeka** [comment]
Maybe we can use the [System.lineSeparator()](http://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--) call to get the system prefered line separator?

**Comment by lognaturel** [comment]
@nribeka Sure, that'd be fine. But if you find a way to run this Android app on Windows, let me know how!!! 😉

**Comment by MukundAnanthu** [comment]
I can take this up

**Comment by lognaturel** [comment]
Thanks, @mukundananthu!
