### ISSUE TITLE
UI Refinement for collect app buttons.

### ISSUE THREAD

**Issue by Ishmeetsingh97** [getodk/collect#732]
#### Problem description
I want to make an UI refinement for collect app to look better. I want to make of the corners of the buttons round on the main menu.
#### Expected behavior
Which would look something like this.
https://drive.google.com/open?id=0B_WC0sIXpPMadmY1RDFMdTNGQkU
#### Other information 
Please assign the issue if you like the refinement.

P.S 
The font will be the same as before. The font in the picture is the font of my device. OR If its okay, I can also work on the font for the application.

**Comment by rijuldhir** [comment]
@Ishmeetsingh97 I think it will be covered under GSoC Project UI improvements

**Comment by yanokwa** [comment]
@rijuldhir Agreed and for that reason, I'm closing this issue.
