### ISSUE TITLE
Error Dialog in AlignedImageWidget incorrectly displayed 

### ISSUE THREAD

**Issue by rishsethia** [getodk/collect#737]
#### Problem description
In an AlignedImageWidget , we get an error for no reason due to a bug in the code 

#### Steps to reproduce the problem
Just using AlignedImageWidget in the form
<img width="592" alt="issue_odk" src="https://cloud.githubusercontent.com/assets/11053890/24213127/6f30a78c-0f57-11e7-8c32-65a0681c7100.png">

#### Other information 
This is due to a simple bug in the AlignedImageWidget code 

And I am working on it !

**Comment by lognaturel** [comment]
Thanks for building the monster form and looking into this, @rishsethia! I must admit this is not a widget I'm familiar with. Given the comments on the class, it appears that there is a "Aligned-image camera app" which is [here](https://github.com/opendatakit/alignedcamera). Did you try it out and make sure your fix makes sense with it?

I'm kind of wondering whether we should just deprecate this widget given that the aligned camera app isn't supported anymore. @yanokwa?
