### ISSUE TITLE
Unable to pick an instance in InstanceChooserList

### ISSUE THREAD

**Issue by rishsethia** [getodk/collect#739]
This is due to the fact that intent filter for the same is missing in android manifest .

android.intent.action.PICK is handled in the InstanceChooserList but there is no intent filter for it in the manifest

@yanokwa @lognaturel  Please review !

**Comment by lognaturel** [comment]
@rishsethia Can you please say more about what problem you are trying to solve? How do you imagine that this would be used?

**Comment by rishsethia** [comment]
Please refer to this document that I documented on using Collect's intents : 
https://docs.google.com/document/d/1UX02GmovwSAWPK0xdDt1RwKqyY4n4_yA6Ltehb-PvP0/edit

**Comment by grzesiek2010** [comment]
@lognaturel not sure if I understand but if it's about using intents and external apps it's possible of course what my demo app shows https://github.com/grzesiek2010/collectTester

**Comment by lognaturel** [comment]
@rishsethia I'm doing some cleanup and notice this was never concluded. As you said, `InstanceChooserList` does indeed have code for handling a `PICK` action but it's never exposed making it impossible to use externally. It should be accessible, just as with `FormChooserList`.

I see you already have a commit for it, would you like to issue a pull request?

**Comment by lognaturel** [comment]
This would be nice for symmetry but we haven't heard of a user needing it and the smaller we keep the external API the easier it is to maintain so let's close pending a request.
