### ISSUE TITLE
Refactor FormHierarchyActivity so FORM_MODE extra isn't needed

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#740]
`FormHierarchyActivity` was originally designed to display a form's hierarchy and enable form editing. With the introduction of the "View Sent Form" feature, there was a need for a read-only form hierarchy. This was implemented by adding a string extra with key `ApplicationConstants.BundleKeys.FORM_MODE` which can have values `ApplicationConstants.FormModes.VIEW_SENT` or `ApplicationConstants.FormModes.EDIT_SAVED`. 

This is not great class design and had unintended consequences (#535). This design should be rethought so that the constants can be removed. There should probably be separate activities for a form hierarchy that can be edited and a read-only form hierarchy.

**Comment by rishsethia** [comment]
@lognaturel 
Yes , this is true . And also when launching collect through external intents , the current way of handling is via these constants , which are redundant in that case and not needed ! 
If you want , I want to work on the same !

**Comment by lognaturel** [comment]
@rishsethia That would be great. Please think carefully about the concepts each class represents and don't hesitate to talk in #collect-code about your approach.

**Comment by lognaturel** [comment]
@rishsethia Would you still like to address this one or should we let someone else take a look at it? It would be nice to do for the May release.

**Comment by rishsethia** [comment]
Hi @lognaturel, 
I would love to work on this issue , but currently my exams are going on , so this might take a bit time to do ! If there's a strict deadline, we might have to delegate , otherwise , I will be more than happy to solve it !
