### ISSUE TITLE
PNGs are uploaded with jpg extension to Google Drive

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#742]
#### Software and hardware versions 
Collect v1.4.16-127-g4673b97e

#### Problem description
PNG images are uploaded as JPGs to Google Drive. They get a .jpg extension but still appear to have transparency and the same size as the original PNG. When downloading the file, the extension can be changed to png.

#### Steps to reproduce the problem
1. Set the protocol to "Google Drive, Google Sheets"
1. Download a form that requires an image such as the demo form posted [here](https://nafundi.com/blog/posts/serverless-odk-deployments-with-google-apps/)
1. Fill the form, pick a PNG for the image
1. Upload the form
1. Look at the image on Google Drive

#### Expected behavior
PNG images should be uploaded with .png extension.

**Comment by shobhitagarwal1612** [comment]
I was thinking, we can now finally allow uploading of all kind of media files. Currently, we are filtering out only the images using the attribute value. By removing this check and checking the file content before uploading, we can add support for all kinds of files. That will fix this issue as well.
@lognaturel Any thoughts?
