### ISSUE TITLE
Support additional media types with Google Drive, Google Sheets protocol

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#744]
With #722, Google Drive became the storage location for images attached to Google Sheets submissions (it was formerly Picasa). This means media types other than images can now be supported by the Google Drive, Google Sheets protocol.

This addition should also address #742, PNGs currently being uploaded as jpgs.

**Comment by shobhitagarwal1612** [comment]
May I handle this as well?

**Comment by lognaturel** [comment]
Sounds good, @shobhitagarwal1612. It will go in the next release so no rush!
