### ISSUE TITLE
Remove unused resources

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#746]
When you run `./gradle lint`, a report is generated at `collect_app/build/reports/lint-results.html` with potential problems with Collect. Find the `Unused resources` section, confirm those resources are unused, then remove them.

This might seem straightforward, but it is not. Lint sometimes reports resources unused if you use them in code instead of XML. Given that, before you send in a PR:

1. Check the web for other approaches and tools that can help you track down unused resources. Don't just rely on lint and Android Studio. 
1. Search the source code for resources to confirm that they aren't used.
1. Use small commits for each category of deletions (e.g., strings, icons, layouts)

Your PR should explain how you verified that you didn't break functionality on API 16, 22, and 25. Include links to the tools and methodology you used.

**Comment by haseeb33** [comment]
I want to work on this can you please guide how can I contribute?

**Comment by yanokwa** [comment]
@haseeb33 Start at https://github.com/opendatakit/collect/blob/master/README.md, be sure to read https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md, then if you have a specific question about this issue, ask.

**Comment by haseeb33** [comment]
Sure, Thanks!

**Comment by yanokwa** [comment]
Good luck, @haseeb33. And please make sure your PR explains how you verified functionality.

**Comment by haseeb33** [comment]
Sure, I will try my level best to deliver best.

**Comment by haseeb33** [comment]
Inspect code(lint) showed 4123 results. 
Now doing find usage method for every resource.
Is this method reliable to remove unused resource?

**Comment by lognaturel** [comment]
@haseeb33 I think @yanokwa's original writeup answers this question! Consider doing this as several small pull requests.

**Comment by haseeb33** [comment]
Sure, I will do it in small pull requests. for example for animations(1 PR), for strings(1 PR), similar type of images(1 PR) and similar but there are two ways to remove unused resources.
1. gradle lint(I think which is not very accurate in our case)
2. find the usage of each item in whole project. if the item exists keep it otherwise delete it(which I am re-commanding)
Maybe we have more ways to do this but I know just these two. so my question is.
Is the second method reliable to remove unused resources?

**Comment by yanokwa** [comment]
@haseeb33 I think starting with lint, then finding usage is a good approach. My advice is to start with small and easy to verify resources and go from there.

**Comment by grzesiek2010** [comment]
@haseeb33 Are you still working on it?

**Comment by haseeb33** [comment]
@grzesiek2010 I am Sorry. I had an accident and wasn't able to work on any project and I'm working on it.
Sorry once again.

**Comment by grzesiek2010** [comment]
@haseeb33 No worries. I hope you are ok. Let us know if you have a problem with this issue or you are not able to continue.

**Comment by haseeb33** [comment]
@grzesiek2010 I am sorry. I am not able to continue on this one because of some issues and my shifted interest towards data science. Once again i am sorry.

**Comment by grzesiek2010** [comment]
@haseeb33 I see. We have lots of issues and everyone is welcome you too of course so you can get back to us whenever you want.

**Comment by haseeb33** [comment]
@grzesiek2010 Sure. I will put my 100% next time if I participate and I am really sorry about this one.
