### ISSUE TITLE
In strings, ellipsis string can be replaced with ellipsis character

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#747]
When you run `./gradle lint`, a report is generated at `collect_app/build/reports/lint-results.html` with potential problems with Collect. Find the `Ellipsis string can be replaced with ellipsis character` section and fix those.

**Comment by championoverthinker** [comment]
Can I work on this?

**Comment by lognaturel** [comment]
Yes please, @sjain281297

**Comment by grzesiek2010** [comment]
@lognaturel We can close this one. It's fixed.

**Comment by yanokwa** [comment]
Closed by #750
