### ISSUE TITLE
Printing from Zebra iMZ printer

### ISSUE THREAD

**Issue by ghost** [getodk/collect#752]
#### Printing from Zebra iMZ printer
My main aim is to print an ODK Collect generated barcode (QRCode) from Zebra iMZ printer.
First I wanted to know the printing capabilities of the printer with Collect and therefore I've installed ODK Zebra sensors and ODK Zebra printer on my device as outlined in documentation
Below is an example i have used to test printing;
![image](https://cloud.githubusercontent.com/assets/12542345/24233218/d7578b24-0fa1-11e7-9b24-13e5f3a6447e.png)

#### Steps and behavior
I make sure my printer is turned on and paired with the android device via Bluetooth.

From ODK Collect, printer widget is triggered i.e. 'initiate printing' tab appears which when tapped opens an ODK Zebra Printer screen with Print, Connect to another printer and Exit print screen tabs. I proceed and tap connect to printer >> Install printer >> Add Bluetooth Device >> I select the printer from the listed devices after which the screen goes back to printer screen where I now tap Print. 
At this point I'm expecting the printer to responds by printing the customer_name or at least give a sound to indicated connectivity but NOTHING happens. The printer light doesn't change either.

#### Conclusion
Printing is however possible from Zebra Utilities app but not from ODK Collect. 
My guess is that the issue is with the ODK Collect.

**Comment by lognaturel** [comment]
Thank you for including so much detail, @WambuiKaranja! Does anyone have a Zebra printer that they could use to help troubleshoot this? @grzesiek2010 maybe?

I re-filed the question about QR code generation as #758 because I think it will be addressed separately.

**Comment by yanokwa** [comment]
@mitchellsundt Does anyone at the lab have this kind of printer?

**Comment by ghost** [comment]
Good morning all,
I there some progress on this issue? kindly help.
Thanks

**Comment by yanokwa** [comment]
@clarlars graciously tried this out and here's what she found.
> In terms of the Zebra printer, I tested it against the latest code in the development branches of the sensorsframework and sensordrivers repos and was able to get it to work using the attached files. I tested it on a Nexus 6 running Android 5.1 with ODK Collect 1.4.16. 

@WambuiKaranja can you try this [printerForm.xlsx](https://github.com/opendatakit/collect/files/880713/printerForm.xlsx) file and see what you find?

**Comment by clarlars** [comment]
I'd also like to add that the development branches of the sensorsframework and sensordrivers are not production ready.  More changes are expected to both of these code bases.

**Comment by wbrunette** [comment]
To be informative. The master branch is what most people should be looking as the "development" branch is not in production ready and more changes are coming to that branch as Clarice mentioned. When the changes are finished they will be moved to the master branch.

Also it's wise to pay attention to the release tags if you want to pull in code from other repos to make sure it matches (the gradle scripts should pull the correctly versioned jar) but if you want to look at the source code of the library the version tags need to match up.

**Comment by lognaturel** [comment]
@WambuiKaranja Has this ever worked for you before? Are [these](https://opendatakit.org/use/sensors/zebra-printer-driver/) the instructions that you followed? Did you install the [sensors framework](https://play.google.com/store/apps/details?id=org.opendatakit.sensors&hl=en) and the [Zebra printer driver](https://play.google.com/store/apps/details?id=org.opendatakit.sensors.drivers.zebra.bt&hl=en) from the Play Store? @Khadomax if you could answer the same questions, that would be very helpful.

@clarlars Would it be possible for you to quickly try it out with the Play Store versions of all the tools just so we have one more bit of information? Thanks so much!

**Comment by clarlars** [comment]
I was able to print using a Zebra MZ 320 printer with a Nexus 6 running Android 5.1.  I used the Play Store versions of ODK Collect 1.5.1, ODK Sensors Framework, and the ODK Zebra Printer Driver.

**Comment by lognaturel** [comment]
Great news, thank you @clarlars!

**Comment by Khadomax** [comment]
Dear Team,
I used everything from Playstore version

………..
Thanks,
Kind Regards,
Stanley

**Comment by ghost** [comment]
Hi guys,
Finally the codes worked just fine even on a different printer (have tested on Zebra RW220).
Your contributions are much appreciated. Big up to @clarlars .

Thanks and best regards
Wambui
