### ISSUE TITLE
The spreadsheet is not resized.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#753]
#### Software and hardware versions 
Current master branch

#### Problem description
The spreadsheet is not resized when we send column names.

#### Steps to reproduce the problem
Send finalized form using spreadsheet.

#### Expected behavior
The spreadsheet should be resized as earlier (we should remove unnecessary columns).

#### Other information 
It was [here](https://github.com/opendatakit/collect/pull/607/files#diff-c17c3e783e785138f9fea8d87888510aL422) this functionality was removed.

@shobhitagarwal1612 I think you might want to do that.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Please review
