### ISSUE TITLE
Generate and print QRCode from ID

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#758]
From @WambuiKaranja:

From collected information on Collect, I want to generate an id which will be printed as a barcode(QRCode) via Zebra iMZ220. 
Here is an example I have tried,

![image](https://cloud.githubusercontent.com/assets/12542345/24234029/31616dec-0fa7-11e7-8907-6fd222dc800d.png)

Can the above generate a QRCode I am looking for? Has anyone printed a barcode?

**Comment by shobhitagarwal1612** [comment]
We can create QRCodes offline using [ZXING](https://github.com/zxing/zxing). 
```
try {
    // generate a 150x150 QR code
    Bitmap bm = encodeAsBitmap(barcode_content, BarcodeFormat.QR_CODE, 150, 150);

    if(bm != null) {
        image_view.setImageBitmap(bm);
    }
} catch (WriterException e) {  }
```

**Comment by ghost** [comment]
Thank you @shobhitagarwal1612 but is there a simplified way for a non developer?
Thanks

**Comment by shobhitagarwal1612** [comment]
So do you want to print the QRCode right from the collect app?

**Comment by ghost** [comment]
Yes i want to print a QRcode id from collect @shobhitagarwal1612

**Comment by yanokwa** [comment]
This will require some work on the XForms spec first, so I've filed an issue at https://github.com/opendatakit/xforms-spec/issues/101.
