### ISSUE TITLE
closing drawer on pressing back button in activities

### ISSUE THREAD

**Issue by pranavgupta1234** [getodk/collect#759]
#### Software and hardware versions 
Android 5.0.2 API Level 21

#### Problem description
pressing back button closes the drawer as well as activity

#### Steps to reproduce the problem
press back button say in FormChooserList activity
![old](https://cloud.githubusercontent.com/assets/21027310/24274053/fc77ca2c-104b-11e7-8042-977a964f044a.gif)

#### Expected behavior
Pressing back button should close the drawer only(if open) else close activity as seen on standard apps
![new](https://cloud.githubusercontent.com/assets/21027310/24274169/98857c7a-104c-11e7-85e9-46e3f4f4f49b.gif)

#### Other information 
overriding onBackPressed will do the task

**Comment by pranavgupta1234** [comment]
should I go for a PR for this ?

**Comment by lognaturel** [comment]
Good one! Yes please, @pranavgupta1234.
