### ISSUE TITLE
Disjoint aggregated data

### ISSUE THREAD

**Issue by ghost** [getodk/collect#763]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
My projects aims at collecting data on some subjects over a period of time and at different stages/times. I have therefore developed one xlsform with sub-sections in groups(stages). Using a cascading select I am able to select the stage I want to fill information. Now the challenge is, while I am able to collect all the information, the groups appears to be disjointed such that when I view my aggregated data in ona subject_id is repeated multiple times depending on the number of groups/stages and information appears in columns depending on group filled
How can I make subject_id unique such that all the data on that subject appears in one row?

Thank you.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by yanokwa** [comment]
Hi @WambuiKaranja! Since this is a form design question it belongs on email opendatakit@googlegroups.com. I'm closing this issue for that reason.
