### ISSUE TITLE
Referencing data in a different group

### ISSUE THREAD

**Issue by ghost** [getodk/collect#764]
#### Software and hardware versions 
Collect v1.4.16.x, Android v5.0.2..

#### Problem description
I've one xlsform with 5 subsections designed as groups. When I fill one subsection, the form is submitted. Now, how do I reference data in the filled group such that if a subject died, then it will be omitted in the next group?

Thank you.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by yanokwa** [comment]
Since this is a form design question it belongs on the mailing list. Please email it to opendatakit@googlegroups.com. I'm closing this issue for that reason.
