### ISSUE TITLE
Fix RtlHardcoded lints

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#772]
When you run ./gradlew lint, a report is generated at collect_app/build/reports/lint-results.html with potential problems with Collect. Find all with RtlHardcoded id and fix those.

@sjain281297 you've fixed #747 quickly so maybe you want to take this one as well?

**Comment by championoverthinker** [comment]
@grzesiek2010 sure :+1:

**Comment by lognaturel** [comment]
Closed by #774
