### ISSUE TITLE
replacing the deprecated attribute singleLine with maxLines for edittext 

### ISSUE THREAD

**Issue by pranavgupta1234** [getodk/collect#773]
#### Software and hardware versions 
Android 5.0.2 API Level 21
#### Problem description
usage of deprecated attribute
#### Steps to reproduce the problem
check for edittext say in drive_layout xml file
#### Expected behavior
maxLines="1" should be used instead

**Comment by lognaturel** [comment]
I believe #659 already addresses this, it's just waiting for @shreyasnbhat to fix the behavior!

**Comment by shreyasnbhat** [comment]
@lognaturel Sorry for the delays!
Would be working on it from next week. I have been quite busy!

**Comment by pranavgupta1234** [comment]
@lognaturel sorry I didn't check that

**Comment by lognaturel** [comment]
It's all right, @pranavgupta1234, thanks to both you and @shreyasnbhat for helping out with Collect!
