### ISSUE TITLE
Deprecate or replace AlignedImageWidget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#775]
It appears that `AlignedImageWidget` was created along with the separate [aligned-camera app](https://github.com/opendatakit/alignedcamera) to help users take aligned photos. The aligned-camera app takes up to 6 parameters describing an overlaid bounding box that the user will see when taking a picture. It was supposed to be possible to leave later parameters blank but there was a logic error in the code copying over parameter values (#737).

Since it doesn't seem reasonable to ask users to install an unsupported camera app from source, I think we should try to get this functionality in a different way. Is there an existing camera app that could help with this? Can we do an overlay without having to create a separate app?

**Comment by shobhitagarwal1612** [comment]
I think we can get the desired results using [`surface view`](https://developer.android.com/reference/android/view/SurfaceView.html)

- Create an activity for capturing photo along with all the required options(for aligning the photo)
- Saving the photo to disk for preview
- Displaying the preview in a fragment with confirmation buttons 
- If it's OK, then return from the activity with the required extras otherwise delete the saved photo and return back to the photo capturing activity

**Comment by lognaturel** [comment]
@shobhitagarwal1612 That's sounding very good!

**Comment by shobhitagarwal1612** [comment]
What tools are required in this widget for capturing aligned images?

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I'm afraid I don't quite understand your question! What do you mean by tools? If you're talking about physical devices, I do think this was originally designed to be used with some kind of box that would ensure a constant distance from the item being photographed.

**Comment by shobhitagarwal1612** [comment]
By tools I meant what are the things that help taking aligned photos  in this widget. Eg. Gridlines, sensors, etc.

**Comment by lognaturel** [comment]
Currently, it seems to be two bounding boxes created with these parameters - outerRecWidth, outerRecHeight, innerRecWidth, innerRecHeight, innerRec-x-offset, innerRec-y-offset. I must admit I haven't compiled the camera app to actually try it!

**Comment by jd-alexander** [comment]
I am rewriting some image widget functions to adhere to some file access stipulations imposed by Nougat  #2263 and I stumbled upon the `AlignedImageWidget` class. I was wondering if it was deprecated or not but this issue confirmed my suspicions :) So it's okay to just skip over it?

**Comment by grzesiek2010** [comment]
There is a pr which removes this widget so we can close it.
