### ISSUE TITLE
Configure Server Settings by scanning 2D barcode

### ISSUE THREAD

**Issue by smoyte** [getodk/collect#781]
Since server settings (especially username and password) are not good candidates for bulk configuration, it seems that using 2D barcodes for quick entry of settings would be nice to have and would greatly simplify fleet configuration.

The developer of this issue could come up with the encoding for what to store in the barcode based on whatever makes coding this easiest. ELMO and other consumers could then spit out a compliant one on the screen or printed sheets and ODK could read it. 

As long as you can select 'Aggregate' as the platform and set the server URL, username, and password with it, we'd be set. Others may want the Google Sheets options in there so it would be good include that. Pretty much everything under the 'Server Settings' header should be settable this way.

For actually performing the scan, I would envision a new row under Server Settings, either at the top or the bottom of the section, labeled 'Capture from 2D Barcode' or something like this. Tapping that would open your standard barcode reader, and a successful capture would return you to the settings screen with everything filled in. Seeing the correct value displayed under Username should be enough of a visual cue to the user that it worked.

Thoughts?

**Comment by yanokwa** [comment]
I love the idea of using barcodes for settings, but why not all settings? It seems like that'd be more flexible.

For barcode generation, I'd bias to doing it on the device. You can configure one parent device the way you want, generate the barcode on that parent, then the children device scan that one. This way, you don't need Internet or a printer to bulk configure.

**Comment by shobhitagarwal1612** [comment]
Using **2D barcodes** will make configuring of app much easier. Also, we can add a share button to send the generated **2d barcode** image remotely too. This would require addition of another option of `Choose an image` along with `Scan a 2D Barcode`.
@yanokwa Any thoughts?

**Comment by smoyte** [comment]
@shobhitagarwal1612 Nice idea about sharing the image and picking it on another phone. I guess that should be tracked as a separate issue. Not sure when you all split these up...

**Comment by smoyte** [comment]
@yanokwa The reason I drew the line at just server settings was 1. it's the only thing you can't really use bulk config for, and 2. I'm not sure about capacity constraints. 

A reasonably sized QR code holds about 1KB of alphanumeric data. You can push it to 2-4KB if you really need to but that makes them harder to read and more error prone.

If you can come up with an encoding that comfortably fits everything in that size and that is flexible enough so that ELMO can just generate the server settings stuff if it wants to not bother with the rest, I'm cool with that. I haven't looked closely enough to see if this is realistic.

**Comment by smoyte** [comment]
@yanokwa Having the phone able to generate the codes would be a cool feature but wouldn't work for us. The appeal for us is to be able to configure a fleet of devices with different credentials for each device. Imagine a workflow like this: 

1. create user in ELMO
2. scan code with phone
3. put phone in box
4. get a new phone and repeat

If you think of the settings as ALL_SETTINGS = CREDENTIALS + OTHER_SETTINGS, then OTHER_SETTINGS can be the same on all, but CREDENTIALS need to change. And perhaps one day we might also want to set some of those form metadata things like email or whatever this way too.

So ELMO needs to be able to generate the codes, which shouldn't be a problem as long as you don't sign the codes with a secret key! :)

But now that I think about it, it would be pretty sweet to configure _all_ the settings this way instead of Server Settings, so that a bulk configuration step involving plugging in the phone wouldn't be necessary. Hmmm.

The issue there would be telling ELMO what all the OTHER_SETTINGS are so that it could package them up with the CREDENTIALS when building the code.

So I just dug into the existing encoding of settings which is based on Java object serialization. A typical example takes up about 1400 bytes and the encoding doesn't seem super efficient. Here is a sample:

```
¨Ì�sr�java.util.HashMap⁄¡√`—�F�
loadFactorI�	thresholdxp?@�����w��� ���t�passwordt�	xxxxxxt�firstRunsr�java.lang.BooleanÕ rÄ’ú˙Ó�Z�valuexp�t�google_sheets_urlt��t�
autosend_wifiq�~�t�map_sdk_behaviort�google_mapst�delete_sendq�~�t�formlist_urlt�	/formListt�protocolt�other_protocolt�autosend_networkq�~�t�default_completedsq�~�t�map_basemap_behaviort�streetst�	font_sizet�21t�lastVersionsr�java.lang.Long;ã‰êÃè#ﬂ�J�valuexr�java.lang.NumberÜ¨ïî‡ã��xp������)t�usernamet�TM492t�
navigationt�swipet�selected_google_accountq�~�t�submission_urlt�/submissiont�
server_urlt�https://opendatakit.appspot.comt�constraint_behaviort�on_swipet�high_resolutionq�~�xsq�~��?@�����0w���@���t�show_map_basemapq�~�t�change_font_sizeq�~�t�show_map_sdkq�~�t�show_splash_screenq�~�t�
autosend_wifiq�~�t�change_languageq�~�t�delete_after_sendq�~�t�jump_toq�~�t�delete_savedq�~�t�access_settingsq�~�t�
edit_savedq�~�t�high_resolutionq�~�t�	get_blankq�~�t�change_protocol_settingsq�~�t�save_midq�~�t�form_processing_logict�-1t�change_passwordq�~�t�
change_serverq�~�t�send_finalizedq�~�t�change_usernameq�~�t�save_asq�~�t�autosend_networkq�~�t�change_google_accountq�~�t�mark_as_finalizedq�~�t�
navigationq�~�t�default_to_finalizedq�~�t�constraint_behaviorq�~�x
```

I think we could come up with something both more compact and more human readable.

How about this:

1. Come up with a nice and compact and readable JSON encoding of the various preferences.
1. Add an option next to 'Save settings to disk' like 'Send settings to server'. Tapping this makes a POST call to a (hardcoded?) api path on the existing configured server like `https://example.com/odk-settings`. The server does with it what it wishes. ELMO would grab the settings and save them and use them as a base for barcode generation.
1. Use the JSON encoded-data as the content of the barcode.
1. (Optionally) Change the save to disk code to also use the JSON format, keeping the binary format around for legacy purposes (easy to detect which is which). Just for consistency's sake.

This way ELMO can use the settings sent from the phone as a base, patch in the variable credentials, and generate a code for each user.

If step 2 comes later that could be OK. We could add a JSON-encoded typical slate of settings to ELMO as a base and let power users edit it by hand.

Thoughts?

**Comment by lognaturel** [comment]
We had a great chat in #collect-code about this. There's lots of agreement that it's a good feature so we should move ahead. I haven't had a good chance to think about the encoding yet but will try to soon. @shobhitagarwal1612 will start doing some UI design and building components on the Collect side so those are ready to go once we come to agreement on the encoding. There are quite a few apps doing this kind of thing, especially for sharing contacts, so we should have some interesting examples to draw from.

**Comment by shobhitagarwal1612** [comment]
@lognaturel @yanokwa @hooverlunch I have added `protocol, server_url, google_sheets_url, formlist_url, submission_url, username and password ` for the generation of QRCode. What are the other requirements?

**Comment by lognaturel** [comment]
I do think it would be ideal to represent all general and admin settings if possible. What about doing something like writing out all settings that differ from the defaults (for that version of Collect)? Importing settings would then involve two steps -- restoring defaults and then applying changes from the QR code JSON. The JSON could include a version number so that compatibility between the QR code version and the Collect version that's scanning it can be verified.

@hooverlunch, did you have suggestions for the encoding? Abridging the keys? Something else?

@shobhitagarwal1612's current implementation uses full key names and values. zlib compression brings the size down about 10%. 7 keys lead to about 200 chars.

**Comment by smoyte** [comment]
It would be great to see an example of the full JSON string (pretty printed if possible) that would result from including all settings. That might help us think about how to make it smaller.

I think abbreviating the keys is an obvious idea. We could have a hash that maps full to abbreviated and back.

As for the values, I'm not sure what they look like. They could perhaps be abbreviated too... Seeing an example would help.

**Comment by lognaturel** [comment]
I did this in a super slapdash way but I think most keys should be there:
```
{
  "admin_pw": "",
  "edit_saved": true,
  "send_finalized": true,
  "view_sent": true,
  "get_blank": true,
  "delete_saved": true,
  "save_mid": true,
  "jump_to": true,
  "change_language": true,
  "access_settings": true,
  "save_as": true,
  "mark_as_finalized": true,
  "admin_password": true,
  "import_settings": true,
  "change_server": true,
  "change_protocol_settings": true,
  "change_form_metadata": true,
  "change_font_size": true,
  "default_to_finalized": true,
  "high_resolution": true,
  "show_splash_screen": true,
  "delete_after_send": true,
  "instance_form_sync": true,
  "app_language": "en",
  "autosend_wifi": false,
  "autosend_network": false,
  "navigation": "swipe",
  "constraint_behavior": "on_swipe",
  "show_map_sdk": true,
  "show_map_basemap": true,
  "analytics": true,
  "lastVersion": 2209,
  "firstRun": false,
  "showSplash": true,
  "splashPath": "",
  "font_size": "21",
  "delete_send": false,
  "instance_sync": true,
  "protocol": "odk_default",
  "protocol_settings": "",
  "selected_google_account": "",
  "username": "",
  "password": "",
  "form_metadata": "",
  "metadata_username": "",
  "metadata_phonenumber": "",
  "metadata_email": "",
  "server_url": "",
  "google_sheets_url": "",
  "formlist_url": "",
  "submission_url": "",
  "swipe": "",
  "buttons": "",
  "on_swipe": "",
  "default_completed": true,
  "map_sdk_behavior": "google_maps",
  "map_basemap_behavior": "streets",
  "osmdroid": "",
  "streets": "",
  "mapquest_streets": ""
}
```
That's 1262 bytes before compression, 676 after (booleans, quotes, there's a ton of redundancy).

There are a handful of things missing because sometimes the key text for the setting and the corresponding admin setting are the same (the admin setting is used to show/hide the setting; an example is "analytics"). How about supporting that by introducing `general` and `admin` keys in the json? As an example, we'd end up with something like
```
{
  "general": {
    "analytics": true
  },
  "admin": {
    "analytics": false
  }
}
```

@hooverlunch you should be able to use zlib on your end to generate readable codes, right?

**Comment by smoyte** [comment]
So here are some ideas for compression:

1. Make a hash map for abbreviating keys and values, so `map_basemap_behavior` could become `mapbb`, `submission_url` -> `sburl`, `high_resolution` -> `hires`, `google_maps` -> `gmaps` etc. Perhaps aiming for max of 5 chars each? These should be sorted in the code so it's easy to avoid adding duplicates. If not all values are captured, that's fine, they just won't get shortened/expanded.
1. (This may already be done) Define defaults for each setting and don't include the setting in the barcode unless it differs from the default.
1. I notice there are lots of instances of `true`. We could abbreviate that but that would be trickier since it wouldn't be valid JSON and I think compression will take care of that anyway?

**Comment by lognaturel** [comment]
It will come as no surprise that I favor option 2. 😁 I think it's what will have the most impact on the size without adding another level of obfuscation. Currently the defaults are spread across the code but I think it would be a very good thing to have them in a single place so they are more explicit.

I agree that 3 is probably not worth doing much about, compression can handle it well.

**Comment by smoyte** [comment]
If we don't do #1 and someone has a lot of settings set, what is the worst case for the size of the compressed JSON? I think we should know what the upper bound is and what we do if it's greater than the max capacity of a QR code.

My gut says we may need #1 and #2 but not sure.

**Comment by lognaturel** [comment]
With the settings list above, if I assume 30 chars for free text fields and 90 chars for URLs, that gets to just shy of 1900 bytes uncompressed. That would be a very strange configuration with a very long Aggregate URL and also a fallback Google docs submission URL. Since there would be more variation in the freeform text, I suppose it wouldn't compress as much so we'd probably be looking at something like 1000 or 1200 bytes compressed.

**Comment by smoyte** [comment]
Ok I think that would fit. We should probably have a failsafe with a user friendly error ("Your settings are too long to fit ...") just in case?

**Comment by lognaturel** [comment]
Yes, I think it will fit, even if we're adding a lot more settings. And I think @shobhitagarwal1612 already has a check and warning for max length!

Another thing I've been thinking about is passwords. I think it is important that they be included because it's core to your use case (configuring server username/password for each device) and I think it's important for mass configuration (configuring a single admin password for all devices). I do think we should warn users that when they display and share QR codes, they're essentially sharing plain text passwords. I don't know how/where that happens, though.

**Comment by smoyte** [comment]
Interesting point. It got me thinking: for the phone-to-phone use case does it even make sense to include login credentials? I could see that in fact being a deal breaker for some folks. i.e. "I wanted to share my settings with my fellow enumerator but not my password! So I couldn't use this..." Perhaps we should have a checkbox, off by default, saying "Include login credentials"?

Then if you check it perhaps it says in a popup "Please note that your password is not encrypted inside the QR code. Please treat it with care."

When ELMO is generating these obviously we _would_ include the password and give a similar warning.

**Comment by yanokwa** [comment]
I think it does make sense to include credentials. There are some deployments, where you have groups of enumerators with the same credentials. What about on the generating device, we have two checkboxes for including or excluding the server and admin password in the generation?

To be explicit, the reason we need compression is not just to fit all the data. The smaller the data, the faster and less error prone the scan.

As to compression, I like option 2 (Define defaults for each setting and don't include the setting in the barcode unless it differs from the default) as a sane first pass. A not so sane second pass is to use two digit codes as keys. How readable do the keys have to be, really?
