### ISSUE TITLE
Missing error messages on Google auth failures

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#784]
There are places in the code where exceptions are caught, and the user should be notified with an appropriate level of detail, but isn’t. Examples:

- GoogleSheetsUploaderActivity catches a GoogleAuthException, but all the user sees is “Sorry, no form was uploaded.” To reproduce, fail to perform the Google Drive setup tasks described in the Collect README.
- GoogleDriveActivity shows no response to a GoogleAuthIOException

Report errors to the user where appropriate.

**Comment by saurabhjn76** [comment]
may I work on this?

**Comment by lognaturel** [comment]
That would be great, @saurabhjn76. I would recommend starting with a pull request that addresses the two specific examples @dcbriccetti mentioned. You'll have to make sure to think carefully about what those exceptions mean and what kind of message will provide enough detail for users.

Then you can go through the app and add a list of other areas where you see error messages with insufficient detail as a comment here and we can discuss.

**Comment by saurabhjn76** [comment]
-  GoogleAuthException(GoogleSheetsUploaderActivity): denotes an authorization problem such as invalid client
  Error message - "Authentication Failed: Please verify credentials and try uploading the forms again"

 - GoogleAuthIOException(GoogleDriveActivity):
Error Message: "Authorization Failed: Unable to fetch drive contents"

Are these messages fine?

**Comment by shobhitagarwal1612** [comment]
Fixed in #790

**Comment by lognaturel** [comment]
There is a broader issue here. There are a number of cases throughout the app where either there's a hard crash or unexpected behavior with no user feedback. I think we should keep this issue open as a reminder @shobhitagarwal1612. If someone wants to do a systematic inventory at some point, that would be fantastic.

**Comment by Shubham-vish** [comment]
I'm willing to work on this if it is available.
