### ISSUE TITLE
Long pressing on grid widgets should clear the selection visually

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#785]
#### Software and hardware versions 
Collect v1.5.1

#### Problem description
Long pressing on a GridWidget or a GridMultiWidget clears the selection but doesn't update the visuals.

#### Steps to reproduce the problem
1. Open a form with a grid widget and a grid widget multi-select such as New Widgets
1. Long press on either widget to pop up the clear response prompt
1. Clear the response, nothing changes visually
1. Swipe forward and then back to verify that the answer was cleared

#### Expected behavior
The orange background should be cleared when the widget responses are cleared by long pressing.

**Comment by krishnarai30** [comment]
@lognaturel will be solving this ASAP!

**Comment by pratikmjoshi** [comment]
@lognaturel I think I had raised a similar issue in #678, could you please clarify?

**Comment by lognaturel** [comment]
Thanks, @krishnarai30!

@pratikmjoshi, long pressing to clear answers is standard across widgets and something that should be supported for all of them. Data collectors are trained to use it. This issue is to fix that.

See my comment [here](https://github.com/opendatakit/collect/pull/679#issuecomment-289938690) regarding what #679 did address and what still needs to be considered in #678. Does that make sense?

**Comment by pratikmjoshi** [comment]
Ahh yes it makes sense.

**Comment by nmpatsal** [comment]
May I try it?

**Comment by lognaturel** [comment]
@krishnarai30 are you still working on this one? If not, let us know and @nmpatsal can take it on.

**Comment by krishnarai30** [comment]
@lognaturel @nmpatsal let's both work on the issue!

**Comment by lognaturel** [comment]
@krishnarai30 @nmpatsal Sounds good! If you want to chat about it, you can use a thread in the Slack #collect-code channel so others can jump in as needed. It should hopefully be relatively straight forward.

**Comment by nmpatsal** [comment]
Sorry, I am working for a course where my professor assess my contributions and I am working team with @nikialexopoulou. So, it is better to @krishnarai30 work on this issue! However, thank you for letting me to contribute too!
