### ISSUE TITLE
Update open source licenses as needed

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#786]
We have added and removed some dependencies but haven't updated the open source licenses to match. For example, gdata and guava are no longer required. 

Make sure that all dependencies listed in the gradle file and in the lib file have the correct open source license listed. Remove any dependencies that aren't included anymore.

**Comment by krishnarai30** [comment]
@lognaturel onto it!

**Comment by lognaturel** [comment]
Thanks @krishnarai30!

**Comment by lognaturel** [comment]
Closed by #792
