### ISSUE TITLE
Use onSaveInstanceState to retain activity state instead of using configChanges

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#799]
#### Problem description
Using `configChanges` is a bad practice for retaining the state of the activity. This has been used in [GoogleSheetsUploaderActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/AndroidManifest.xml#L155), [GoogleDriveActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/AndroidManifest.xml#L117), etc.

#### Expected behavior
This should be replaced by using `onSaveInstanceState` to retain the state of the activity on destroy and recreation.

**Comment by rockydcoder** [comment]
`onSaveInstanceState` is already being used in those activities. What we need to override is `onRestoreInstanceState`. And then we can remove the `configChanges` from manifest

**Comment by lognaturel** [comment]
We've run into confusion around this a few times so would like to prioritize it for the v1.27 release. 

From @seadowg in [the v1.27 planning document](https://docs.google.com/document/d/1Bjz6pjtqIjd5QoFTCPpwKBIINGlX2p_4Q6bol_ot1wA/edit#): 
> it looks like `orientation` on its own doesn't change the behaviour on rotation (the Activity is still recreated) but that using `orientation|screenSize` does. The `MainMenuActivity` for instance doesn't call `onCreate` when it is rotated.

**Comment by grzesiek2010** [comment]
I'm going to close it since a lot has changed since that issue was created.
