### ISSUE TITLE
Check if updated CSVs on Aggregate get updated in Collect

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#822]
According to https://groups.google.com/d/msg/opendatakit/UD1inyjxB4M/OsDtYnoaL8UJ when you update a CSV that's associated with a form in Aggregate, Collect does not update the CSV. It should.

**Comment by grzesiek2010** [comment]
I used this form https://opendatakit.org/wp-content/uploads/2013/11/external_itemsets_example.zip

I uploaded the form and its csv file to Aggregate then I downloaded the form and finalized one instance. After that, I edited the csv file manually and uploaded the form and it's csv to Aggregate again. When I downloaded the form again I was able to see new values.
So in my opinion, it works well.

**Comment by lognaturel** [comment]
This would be important behavior to document fully and accurately.

Where in the code does the update happen? What happens if my Internet connection is very slow and the csv change is very big?

Is this also the behavior for "preloads"? https://opendatakit.org/help/form-design/data-preloading/

**Comment by grzesiek2010** [comment]
@lognaturel 

> Is this also the behavior for "preloads"? https://opendatakit.org/help/form-design/data-preloading/

preloads work well too. I tested this form: https://opendatakit.org/downloads/download-info/sample-preloading-form/

If you want to know more details:
I was right yesterday. If we use external itemsets we create a table in `ItemsetDbAdapter` for used csv file when we load the form for the first time and we don't need to create that table again we can just use existed table as long as the csv file is the same and we use md5 hash to check this as I said yesterday.

When it comes to preloads it works well too but in a different way. We create a db file, we load preloads and this file is stored in `odk/forms/form_name/` after that related csv file is renamed from eg. `hhplotdetails.csv` to `hhplotdetails.csv.imported`. As long as only that `hhplotdetails.csv.imported` exists we use that database we created but if you download a form again from aggregate you have `hhplotdetails.csv` again and then the database is recreated.

**Comment by lognaturel** [comment]
To summarize:
- you have confirmed that the download is NOT automatic
- you have confirmed that uploading the same form definition with a bump in the version number along with a new CSV allows Collect to see the new form version
- you have confirmed that downloading the new form version results in the new CSV being used when the latest form version is filled. This is true for both preloads and external itemsets

Is that right?

I believe that at that point you will see two versions of the form in Collect, right? Do they both use the most recent CSV?

**Comment by grzesiek2010** [comment]
> you have confirmed that the download is NOT automatic

Yes, how could it work automattically? It has been never implemented. We need to download the form manually again.

To answer other questions I feel that I need to clarify something. In aggregate, there is only one option called `Add New Form`.

- If you use `Add New Form` option and you upload a form with the same version you already have then, as a result, you will see one form on your devices. This form will be updated, for example, if you edited your csv files you will see new values. 

- if you use `Add New Form` option add upload a form with bumped version number then you will see two different forms on your device. The old one will still use old values and the new one will use new values.

In both cases it works well I think.

So:

> you have confirmed that uploading the same form definition with a bump in the version number along with a new CSV allows Collect to see the new form version

Yes.

> you have confirmed that downloading the new form version results in the new CSV being used when the latest form version is filled. This is true for both preloads and external itemsets

Don't know if I understand but as I said above the old form will use it's old values and the new one will use it's new values. For both (preloads and external itemsets

> I believe that at that point you will see two versions of the form in Collect, right? Do they both use the most recent CSV?

The answer is above it depends on what you did with your form version.

I think we can close this issue. I'll add a link to this thread in the [doc](https://docs.google.com/document/d/1tw_EW_HRvbSom1cX9-Q5mcFXCAHxiqLDMUeoRNVoQ2I/edit).

Is it clear enough for you @lognaturel ?

**Comment by lognaturel** [comment]
Yes, thank you.
