### ISSUE TITLE
Remove Unused Imports

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#825]
**Software and hardware versions**

Collect v1.4.16, Android v6.0, Nexus 5

**Problem description**

There are certain unused imports in the codebase which need to be removed.

**Comment by grzesiek2010** [comment]
@lognaturel It doesn't make sense to merge another pr that removes unused imports if we still allow to build project with unused imports. We should start using checkstyle and there define UnusedImports as an error.

**Comment by lognaturel** [comment]
@rajatthakur @grzesiek2010 I do agree it's annoying that these keep coming back up. Let me see if we can come up with a good way of starting to enable some checkstyle verification.
