### ISSUE TITLE
Long press on button doesn't work using GeoTraceWidget/GeoShapeWidget

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#827]
#### Software and hardware versions 
Collect v1.5.1

#### Problem description
We are not able to remove response using [GeoTraceWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java) and [GeoShapeWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java) when we long press on buttons.

#### Steps to reproduce the problem
1. Open the attached form.
2. Long press on button "Starte GeoTrace" or "Start GeoShape"

#### Expected behavior
2. "Remove response" option should be visible as with every other widget

[locations.txt](https://github.com/opendatakit/collect/files/895981/locations.txt)

**Comment by shobhitagarwal1612** [comment]
I would like to work on this

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 I think it's too easy and you are able to work on more complex issues. I'm completly sure @lognaturel would say exactly the same :)

**Comment by shobhitagarwal1612** [comment]
Can you suggest some bugs for me? :smiley:

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 let's talk on slack.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @grzesiek2010 😊😊😊 Yes, I do agree. I would recommend that you have these kinds of Slack discussions in #collect-code, that's what it's there for! That way others can also jump in with suggestions.

I hope a wonderful new contributor takes this one on!

**Comment by rijuldhir** [comment]
I can work on it

**Comment by lognaturel** [comment]
That sounds great, thanks @rijuldhir

**Comment by lognaturel** [comment]
@yanokwa You mentioned in passing that there could be a reason that this behavior wasn't included. Do you have any idea what that could be?
