### ISSUE TITLE
Button text is not changed to default after removing response

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#828]
#### Software and hardware versions 
Collect v1.5.1

#### Problem description
Button text is not changed to default after removing response when we use [GeoTraceWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java) and [GeoShapeWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java)

#### Steps to reproduce the problem
1. Open the attached form.
2. Record path or shape
3. Remove response

#### Expected behavior
The button text should be changed back to default "Start Geotrace" / "Start GeoShape"

#### Actual behavior
We can see "View or CHange GeoTrace" / "View or CHange GeoShape"

[locations.txt](https://github.com/opendatakit/collect/files/895995/locations.txt)

**Comment by getsanjeev** [comment]
@grzesiek2010 May I?

**Comment by grzesiek2010** [comment]
@getsanjeev yes you can.

**Comment by getsanjeev** [comment]
@grzesiek2010 Can you please tell me which forms did you try with?

**Comment by grzesiek2010** [comment]
@getsanjeev 
[loc.txt](https://github.com/opendatakit/collect/files/922140/loc.txt)

**Comment by grzesiek2010** [comment]
I'll fix this today as we need this for April release.
