### ISSUE TITLE
Improve "Finished scanning" message

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#836]
#### Software and hardware versions 
Collect v1.5.1

#### Problem description
If we open one of our lists: Fil Blank Form, Edit Saved Form, Send Finalized Form, View Sent Form or Delete Saved Form we can see a message at the top of the list: "Finished scanning." if it's a list of instances and "Finished scanning. All forms loaded." if it's a list of forms. I think it should be consistent so we should use "Finished scanning." in both cases or "Finished scanning. All instances loaded." and "Finished scanning. All forms loaded." otherwise.

I know as well that we can't just edit this string (if we choose the second option) using Android Studio as all values are from [Transifex](https://www.transifex.com/opendatakit/odk-collect/dashboard/) @lognaturel am I right?

**Comment by lognaturel** [comment]
Correct about updating the translations. It has to be done in Transifex.

I think @yanokwa at some point mentioned the idea of hiding the message at some point or displaying it differently. I also expect that it would be likely to change in the UI refresh. So perhaps we should wait on this?

**Comment by grzesiek2010** [comment]
Why should it be a part of UI refresh?

**Comment by lognaturel** [comment]
@grzesiek2010 because the way that information is presented could change significantly or be removed.

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
