### ISSUE TITLE
Error when images are missing

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#839]
#### Software and hardware versions 
Collect v1.4.16, Android v6.0, Nexus 5

#### Problem description
The user is presented with the error message if the file does not exist.

<img src="https://cloud.githubusercontent.com/assets/24683388/24765498/a2cb1a18-1b15-11e7-86d5-12a918bf3c6d.png" width="250" padding = "10">

#### Steps to reproduce the problem

1. Delete some of the image files that come with the birds form.
2. Open the birds form and swipe to the 4th question.

#### Expected behavior

An icon indicating that the file does exist should be displayed instead of the error message.

**Comment by yanokwa** [comment]
Closing because it's important to know what image is missing and where it should be placed.
