### ISSUE TITLE
Very Small Icons

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#842]
#### Software and hardware versions 
Collect v1.4.16, Android v6.0, Nexus 5

#### Problem description

Very small icons in GridWidget.

<img src="https://cloud.githubusercontent.com/assets/24683388/24768455/392d9fee-1b20-11e7-8ddb-24c519373fd4.png" width="250" padding = "10">

#### Steps to reproduce the problem

1. Go to the second question in the Forest Plot Survey Form.

#### Expected behavior

The icons should be appropriately sized.

**Comment by lognaturel** [comment]
@yanokwa @nribeka Do you know what the intent was for this widget and/or do you have a preference on the icon size?

**Comment by nribeka** [comment]
I think the number of element per row (column count) is controlled from the form.

So probably don't need to do this? From the documentation:

> To define a grid with a fixed number of columns, specify the number of columns as a '-width' suffix to the 'compact' appearance. I.e., to force 4 columns:
> `<select1 appearance="compact-4" ref="/NewWidgets/grid">`

**Comment by lognaturel** [comment]
Yes, I think that -1 is the correct default. Closing.
