### ISSUE TITLE
Button should be disabled when all form are unselected

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#847]
#### Software and hardware versions 
Collect v1.5.1

#### Problem description
Button should be disabled when all form are unselected.

#### Steps to reproduce the problem
1. Fill and sent one of available forms
2. Go to "Send Finalized Form"
3. Choose "Change View" -> "Show Sent and Unsent Forms" from context menu
4. Check sent form
5. Choose "Change View" -> "Show Unsent Forms" from context menu

#### Expected behavior
"Send Selected" button is still enabled

#### Other information 
It's not a big problem as we get a message "Sorry, you have not selected any forms" but we should improve that.

**Comment by rijuldhir** [comment]
I can work on it

**Comment by grzesiek2010** [comment]
@rijuldhir yes please.

**Comment by SIMRAN1** [comment]
I want to work on this issue @grzesiek2010 .Shall I proceed?

**Comment by lognaturel** [comment]
@SIMRAN1 please make sure to read the comments on an issue! @rijuldhir is already working on this one.

**Comment by lognaturel** [comment]
See #924 for a start and some comments on it.

**Comment by lognaturel** [comment]
@grzesiek2010 Can you please take this one real quick so we can get it in the May release? Thanks!

**Comment by grzesiek2010** [comment]
@lognaturel sure I'll fix it.
