### ISSUE TITLE
Pulldata from Google sheets

### ISSUE THREAD

**Issue by ghost** [getodk/collect#849]
#### Software and hardware versions 
Collect v1.5.1, Android v5.0.2, device used...

#### Problem description
Is it possible to pulldata from google sheets? If so, how is it done?

#### Expected behavior
Function as the normal xlsform pulldata() function

Thank you.

**Comment by lognaturel** [comment]
This isn't something that exists at the moment. If it's a feature you'd like us to consider, please describe the general problem you'd like to solve -- what are you trying to do that you can't do today? That will help us figure out the best way to approach it.

**Comment by ghost** [comment]
Thanks @lognaturel
I want to be referring to data collected, say yesterday to determine what will be included in tomorrow activities. So, I have one form with groups and repeats of activities that are to take place over a long period of time. For example, if I say i want to record flowering plants today and submit recorded data at the end of the day. Tomorrow morning i want to pull only the data recorded yesterday to do pollination on those plants. 
I have tried to pull the data from the same form through 'select dataset to link' in ona but it gets the .csv files (used at the flowering stage) attached instead of data recorded on the xlsform.

To solve this, I've used google sheets to receive submitted data so that I can pull it from there.
The challenge is how to pull the data from google sheets.

I hope I've explained it better this time.
Thanks

**Comment by lognaturel** [comment]
It's now possible to attach CSVs to be queried by pulldata to forms served by Google Sheets. The workflow @ghost describes would require the addition of some automation step that periodically converts collected data to a CSV. Or simply manually exporting the data to CSV on a nightly basis.
