### ISSUE TITLE
Replace all Log calls with Timber

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#864]
Now that we are using the [Timber](https://github.com/JakeWharton/timber) library for logging appropriately in development and production (thanks @shobhitagarwal1612 and @anudeepti2004!), all `Log` calls in the codebase should be replaced by calls to the corresponding `Timber` method. [Here](http://jakewharton.github.io/timber/) is the appropriate reference.

Timber also includes a number of `lint` checks which should all pass. See [here](https://github.com/JakeWharton/timber#lint) for a description of each of them.

In particular, formatted strings should be used instead of concatenation and there should be no redundant calls on `e.getMessages()`. That makes this a fairly big job requiring careful attention. I'd recommend doing it a few classes at a time and doing one commit per updated file. You can indicate in the comments what classes you're taking on.

**Comment by nmpatsal** [comment]
May I take this one @lognaturel ?

**Comment by lognaturel** [comment]
@nmpatsal Yes, please! Do make sure to read the documentation and look at examples already in the code before you get started.

**Comment by lognaturel** [comment]
Thank you, @nmpatsal!
