### ISSUE TITLE
Bad submission_url in forms from Aggregate should not be loaded

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#873]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
A form with a bad submission URL can be loaded into Collect's Fill Blank Form. This is a problem because submission URLs override Collect's server settings so you can never send data to Aggregate after you fill out a blank form.

#### Steps to reproduce the problem
Create a form with a bad URL (e.g., `https:/server.com` instead of `https://server.com`). Fill out form and submit. To reproduce, try these forms:
* [bug.xlsx](https://github.com/opendatakit/collect/files/853365/bug.xlsx)
* [bug.xml.txt](https://github.com/opendatakit/collect/files/853366/bug.xml.txt)

If you'd like to make your own forms, for XLSForm (put a `submission_url` header with the value below in the `settings` sheet). For XForm, 
```
<model>
  <submission action="https:/server.com/submission" method="form-data-post"/>
  <instance>
```

#### Expected behavior
Users should be alerted as soon as possible when the submission URL is bad. 

There is already code in `DiskSyncTask.java` (https://github.com/opendatakit/collect/pull/716) that prevents forms that are loaded from the SD card or from Google Drive to be removed. This issue is for forms that are downloaded from Aggregate.

**Comment by yanokwa** [comment]
@pratikmjoshi You interested in taking this issue on?

**Comment by pratikmjoshi** [comment]
@yanokwa Yes definitely, I'll get to work on this
