### ISSUE TITLE
Change GeoPointMapActivity name to GeoPointGoogleMapActivity

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#876]
I think we should be consistent. We have similar classes for Google maps and OSM:
GeoShapeGoogleMapActivity - GeoShapeOsmMapActivity
GeoTraceGoogleMapActivity - GeoTraceOsmMapActivity
so it should be as well
GeoPoint**Google**MapActivity - GeoPointOsmMapActivity

**Comment by lognaturel** [comment]
Let's wrap this into #507. I'm sure a lot will change once we get to it.
