### ISSUE TITLE
Explore replacing intent call in widgets with chrome tabs

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#878]
Both the URL widget and inline Markdown support allow Collect to launch a URL. As discussed at https://github.com/opendatakit/collect/issues/563, it'd be nice this were replaced with chrome tabs. The URL Widget seems straightforward, but I'm not sure how this will affect how we open links in Markdown.

Below are an XLSForm and XForm that shows how to open a URL with the URL Widget and with Markdown. 
[urls.xlsx](https://github.com/opendatakit/collect/files/918324/urls.xlsx)
[urls.xml.txt](https://github.com/opendatakit/collect/files/918325/urls.xml.txt)

**Comment by yanokwa** [comment]
@getsanjeev This might be a good issue for you. Are you interested?

**Comment by getsanjeev** [comment]
@yanokwa I would love to take this one. I have my mid semester exams so I would start working after two days.

**Comment by grzesiek2010** [comment]
@getsanjeev please finish https://github.com/opendatakit/collect/pull/845 and https://github.com/opendatakit/collect/issues/828 as those are yours and then you can take something next. I mean it's yours as well of course as @yanokwa said but keep the right order.

**Comment by shobhitagarwal1612** [comment]
Closed in #1174
