### ISSUE TITLE
Display dates from date or datetime widgets and times from time or datetime widgets using the phone locale

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#897]
Currently, Date, Time and DateTime widgets are displayed using the `getDisplayText` method on the `IAnswerData` that they represent. That method does not respect the device's locale. 

For example, a date widget with appearance `no-calendar` and the phone locale set to US English:
<img width="241" alt="screen shot 2017-04-14 at 12 17 24 pm" src="https://cloud.githubusercontent.com/assets/967540/25053653/5536427a-210d-11e7-9a46-a9d35bf5677a.png">
The date should use the order 4/17/17. I think it would be even better using the `LONG` format -- `April 17, 2017` in US English or `17 avril 2017` in FR French. For times I like the `MEDIUM` format -- `7:03:47 AM` in US English or 07:03:07 in FR French. See docs [here](http://docs.oracle.com/javase/tutorial/i18n/format/dateFormat.html).

Similarly, in the jump menu (`FormHierarchyActivity`):
<img width="165" alt="screen shot 2017-04-14 at 12 17 37 pm" src="https://cloud.githubusercontent.com/assets/967540/25053689/82377e10-210d-11e7-9ba2-410355b5af01.png">

[This form](https://github.com/opendatakit/collect/files/878646/dates.txt) is a good one to use for seeing the problem.

This should be easy enough to address for the widgets but it's somewhat annoying for the jump menu. One simple approach would be to add special cases in `FormEntryPrompt`'s `getAnswerText`. It would be good to describe some different approaches here so we can discuss.

**Comment by nmpatsal** [comment]
Let us to take it with @nikialexopoulou because we already started in this direction.

**Comment by lognaturel** [comment]
That sounds good @nmpatsal @nikialexopoulou. It does look like a simple issue but it's somewhat more complicated because it touches JavaRosa! I'm looking forward to seeing how you propose to address it.

**Comment by lognaturel** [comment]
I would recommend addressing the date display on the widgets themselves first as one pull request. I think that will be relatively straight forward and we do want to include that in the April release. The `FormHierarchyActivity` part is more complicated and can wait since that behavior has been there for a long time.

**Comment by lognaturel** [comment]
There's one more requirement for this that I just thought of. The date display should respect the `appearance`. That is, if the `appearance` is `month-year`, the date should be displayed as April 2017, for example, NOT as April 1, 2017.

Do you think you can get the first part of this done by Monday 4/24? If not, let us know so someone else can complete it before the code freeze next Wednesday!

**Comment by nikialexopoulou** [comment]
@lognaturel we'll try to make it. If we see that we can't do it, we'll inform you by tomorrow.

**Comment by nikialexopoulou** [comment]
@lognaturel we can't complete the issue, so if anyone else would like to take it, please do. I'm sorry we're late but we were trying till today.

**Comment by lognaturel** [comment]
Thanks for letting us know, @nikialexopoulou.

**Comment by grzesiek2010** [comment]
@lognaturel I have fixed this locally but I would like to merge #935 first.
