### ISSUE TITLE
Buttons in DrawWidget don't look good

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#914]
#### Software and hardware versions 
Collect v1.5.1

#### Steps to reproduce the problem
Use this form: 
[draw.txt](https://github.com/opendatakit/collect/files/929900/draw.txt)

#### Other information 
![screenshot_2017-04-18-15-17-10](https://cloud.githubusercontent.com/assets/3276264/25134411/ca0529a0-244f-11e7-8e27-997276811e14.png)

**Comment by lognaturel** [comment]
It's not clear what the right thing to do here is. I believe that 4 equal-width buttons will result in weird wrapping in some languages, maybe even English.

**Comment by nribeka** [comment]
Maybe we can rearrange the button? Two at the top and two at the bottom? 🤣 

The top two probably will be reset and set color, the two at the bottom will be save and cancel.

**Comment by thedavidmccann** [comment]
![odk_draw_buttons](https://cloud.githubusercontent.com/assets/288112/26410373/07516534-4071-11e7-97d8-e1fc4cdefae0.gif)

Here's the behavior in the emulator.  The buttons look really slick!  However, I can't seem to get "set color" to persist my changes.  Anyone else seeing this?

**Comment by grzesiek2010** [comment]
@daveycrockett as you can see there is "WIP" tag now I wait for #493 and I'll continue.

**Comment by thedavidmccann** [comment]
Thanks for the clarification!  Is there any other feedback you're looking for on the PR, or does it make sense to close until there's something actionable (i.e. after #493 is done)?

**Comment by grzesiek2010** [comment]
@daveycrockett no thanks! When it comes to closing the PR I don't know, no matter. I've heard from @lognaturel that we should close old prs if the progress is stopped but  I have no opinion.

**Comment by thedavidmccann** [comment]
@grzesiek2010 I'd agree I don't have a strong opinion...I'll admit my confusion was around interpreting "WIP" to mean that it was incremental work that could be merged in on its own but was part of a larger goal, and saw no indication that it wasn't just awaiting review.  Perhaps either closing the PR, or adding a "blocked" tag would be good conventions?  I'll raise in slack and see if people have opinions.
