### ISSUE TITLE
Date and time dialogs should not disappear when area outside of the dialog is tapped

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#923]
#### Software and hardware versions 
Collect v1.5.1-87-g8a53ecd2

#### Steps to reproduce the problem
1. Open form [dates.txt](https://github.com/opendatakit/collect/files/906091/dates.txt)
1. Go to any field that uses a dialog box for setting the value
1. Tap on the button to open the dialog box
1. Tap outside the dialog box, the dialog box is dismissed and the date/time remains unchanged

#### Expected behavior
Tapping outside the dialog box should not dismiss it because it is too likely that a user would accidentally do that. The Android calendar app also makes it so that tapping outside a date or time selection dialog doesn't dismiss it.

**Comment by getsanjeev** [comment]
@lognaturel Can you please tell How to open forms like dates.txt . I have always worked only with the forms available in getBlankForms. It would be helpful if you can explain the idea.

**Comment by lognaturel** [comment]
@getsanjeev Take a look at the "testing a form locally" section of the readme!
