### ISSUE TITLE
Dates in date widget always go back to Jan 1, 1970

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#939]
#### Software and hardware versions 
Collect v1.5.1-93-gefeaf935

#### Steps to reproduce the problem
1. Download a form with a calendar date widget (e.g. Widgets from the default server)
1. Notice that the month/year spinners are set to Jan 1900
1. Tap in the calendar, the spinners change to the current month/year
1. Set a date, swipe to the next question, then swipe back, the spinners are back to Jan 1900
1. Go to the jump screen, the date there is always today's date

#### Expected behavior
It should be possible to set the date with the spinners and calendar.

**Comment by lognaturel** [comment]
This is because there isn't any code to update the calendar view anymore. Some of the code removed in #789 will need to come back. @grzesiek2010 can you please take a look at this one?

**Comment by lognaturel** [comment]
Ahhhh, sneaky. You've already addressed this in #935, right?

**Comment by grzesiek2010** [comment]
@lognaturel yes it works well in #935 so if rest of changes are ok we can merge all together otherwise I can create separate pr.

**Comment by lognaturel** [comment]
Cool, will review #935 shortly.

**Comment by lognaturel** [comment]
Actually, let me leave this open until we merge #935 because it's likely someone else would notice and report it.
