### ISSUE TITLE
Capture redundancy between DrawWidget, AnnotateWidget and SignatureWidget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#943]
`DrawWidget`, `AnnotateWidget` and `SignatureWidget` have a lot in common but that similarity is not reflected in the code. Capturing that similarity will make it possible to make interface improvements to all three at the same time.

**Comment by nikialexopoulou** [comment]
@lognaturel Is someone assigned to this issue?

**Comment by lognaturel** [comment]
@nikialexopoulou No one is currently but now that I'm thinking about it, I wonder whether @grzesiek2010 should look at it since he's reviewing the draw activity in #961. It might make sense to look at them together since they may start diverging more. @grzesiek2010?

@nikialexopoulou Are there other issues that interest you? I can also think about some that you might like and would be good for the May release when I do a pass through tomorrow! I'll let you know in Slack what some of those ideas might be.

**Comment by nikialexopoulou** [comment]
@lognaturel ok, thank you!

**Comment by xsteelej** [comment]
Work in progress

**Comment by xsteelej** [comment]
Awaiting test
