### ISSUE TITLE
After running InstanceUploaderTaskTest, Aggregate URL is set to localhost

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#972]
#### Software and hardware versions 
Collect v1.5.1-118-g17bb0d48

#### Problem description
After running InstanceUploaderTaskTest, Aggregate URL is set to localhost.

#### Steps to reproduce the problem
1. Set Aggregate URL to a working server in General Settings > Platform Settings
1. Run `InstanceUploaderTaskTest`
1. Go to General Settings > Platform Settings and verify that the server is now set to something like `http://localhost:34226/`

#### Expected behavior
The test cleanup should set the Aggregate URL back to its previous value.

@alxndrsn Hopefully this adds some clarity to what I was talking about in #964! I think this is a pretty nice issue for a new contributor.

**Comment by alxndrsn** [comment]
On it.
