### ISSUE TITLE
OK/Cancel text changed to some other language on Moto G4

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#993]
#### Software and hardware versions 
Collect v1.6.0, Android v7.0, Moto G4

#### Problem description
OK/Cancel text changed to some other language on Moto G4.

#### Steps to reproduce the problem
In device, set device language to English. In Collect's General Settings, set Language to use device language. In General Settings, tap on Platform. Instead of Cancel, you'll see non-English text.

![device-2017-04-30-145011](https://cloud.githubusercontent.com/assets/32369/25567487/8a00535c-2db4-11e7-955e-8ea0c5f840cf.png)

#### Expected behavior
I expect to see Cancel.

#### Other information 
If you toggle the device language from say French to English, the cancel text in Collect will be correct. If you change the device language in Collect to any well-translated language (e.g., French), the cancel text will be correct. Change it back in Collect to English and the text will be incorrect.

https://stackoverflow.com/questions/42574641/date-picker-ok-cancel-button-text-changed-to-some-other-language-in-nougatmoto

**Comment by lognaturel** [comment]
No user has complained about this so I don't think it's worth spending cycles on. It's some kind of Android/device bug.
