### ISSUE TITLE
Date widget issue on Android 7.1.X

### ISSUE THREAD

**Issue by FlorentDotMe** [getodk/collect#995]
#### Software and hardware versions 
Collect: v1.6.0
Honor 5C / LineageOS 14.1 / Android 7.1.1
Nexus 5 / LineageOS 14.1 / Android 7.1.2
Nexus 9 / Stock 7.1.1

Works on Android 6.0, 4.2.

#### Problem description
Since the 1.6.0 Collect update, existing forms using the Date widget crash when loading the date type question.

![screenshot_20170502-120511](https://cloud.githubusercontent.com/assets/292081/25613905/30d3460e-2f30-11e7-9b8e-53a310f6c316.png)

#### Steps to reproduce the problem
Fill an existing or new form that includes the Date widget.

#### Expected behavior
The Date widget should open when loading the concerned version.

### Other information
Works on:
* Sony C1904, Android 7.1.1 Lineage OS
* Pixel emulator, Android 7.1.1
* Genymotion emulator, Android 7.1.0

**Comment by yanokwa** [comment]
@FlorentDotMe Sorry this update is causing you problems! Can you please include two - three question form (XLS or XML) that has this problem?

**Comment by FlorentDotMe** [comment]
@yanokwa Please find attached a very simple form with which I'm facing the issue, and related screenshots.

[Issue 995 - example.zip](https://github.com/opendatakit/collect/files/970489/Issue.995.-.example.zip)

**Comment by shobhitagarwal1612** [comment]
I was unable to reproduce the bug with the provided form. I tested on both debug and release versions. 
Android 7.1.1 Lineage OS
Sony C1904
API 25

![device-2017-05-02-185206](https://cloud.githubusercontent.com/assets/8918023/25619536/df8eee22-2f68-11e7-875c-2e00ebbb9061.png)

**Comment by yanokwa** [comment]
@FlorentDotMe What physical device do you have?

**Comment by FlorentDotMe** [comment]
That's surprising, as for now the problem occurs on 3 of my devices:
- Honor 5C / LineageOS 14.1 / Android 7.1.1
- Nexus 5 / LineageOS 14.1 / Android 7.1.2
- Nexus 9 / Stock 7.1.1

All of these devices were working well with the previous Collect version.

**Comment by lognaturel** [comment]
My guess is that something has changed in the way that empty dates are interpreted. @FlorentDotMe @dig360 One possible quick fix to try is to add `today()` to the default column for your dates. We'll keep seeing what we can do to address it more fundamentally but it's unfortunately difficult to fix something we can't reproduce! :/

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @yanokwa Could you try changing your phone's language to French or Spanish? Or @FlorentDotMe @dig360, could you see what happens if you change the language to English (US)?

**Comment by yanokwa** [comment]
I cannot repro this on a Pixel emulator running 7.1.1 (or a Genymotion emulator running 7.1.0). For the former, I've tried French and English. I've tried new forms, edited forms, changed dates, and nada. Very strange...

![may-02-2017 09-07-31](https://cloud.githubusercontent.com/assets/32369/25621415/eadb7cac-2f16-11e7-8c96-898d1014c9fc.gif)

**Comment by FlorentDotMe** [comment]
@lognaturel My Honor 5C is already fully in English, Nexus 5 and Nexus 9 are in French. Issue doesn't seem related to the language. I also tried your suggestion by adding today() as default value, but it didn't fix the problem.
@yanokwa I'm deploying the right emulator to reproduce as you did.

Having the issue on 3 different devices (different hardware, different ROM, but same API) let me think that I shouldn't be alone to face this problem.

**Comment by yanokwa** [comment]
Thanks for the additional detail, @FlorentDotMe! If you want to work with us in real-time to repro it, we are on http://slack.opendatakit.org in the #collect-code channel.

**Comment by dig360** [comment]
@lognaturel : just tried in english, I receive the same message. I'll change the default value later to try to fix that way... Not actually at home... I'll back with the result.

**Comment by lognaturel** [comment]
Thanks @dig360! @FlorentDotMe tried that and it didn't work so I don't think it will help unfortunately. 

My new hypothesis is that some Android builds have extra early checks for date validity and that the problem is [here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java#L238). What we've been doing is setting the picker date to a non-sense value when it's initialized and then immediately setting it to the right value [here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java#L241). But that may not work for all Android builds.

What would be really helpful is if one of you who has this problem could try changing the `0, 0, 0` to a date that's in range such as `2017, 05, 02` and report back on whether that fixes the problem.

**Comment by lognaturel** [comment]
Here's an APK: [collect_app-debug.apk.zip](https://github.com/opendatakit/collect/files/970916/collect_app-debug.apk.zip)

First uninstall Collect. Then copy the APK to the phone and tap to install. Or if you have developer tools installed you can run `adb install collect_app-debug.apk`. Thanks!

**Comment by lognaturel** [comment]
@dig360, @FlorentDotMe was able to try out the patched version and confirm that it fixes the problem! We're working on a 1.6.1 patch release that should be out shortly.

**Comment by yanokwa** [comment]
The releases are rolling out on the Google Play store now!

**Comment by yanokwa** [comment]
@dig360 and @FlorentDotMe The releases are rolling out on the Google Play store now. Please upgrade to fix the issues you reported!

**Comment by dig360** [comment]
Release 1.6.1 solved the issue for me. Thank you for the very quick answer.
Bests Regards
Didier
